### ISSUE TITLE
Unspecified register (Howdy)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#100]
Issue reported by **Howdy** at 2014-11-26 23:36:31 UTC
Time: 2014-11-26T23:32:28+00:00
Session ID: 30c6c4284a874b8e397a87051f47772d
Problem Page URL: [/freereg_contents/54080f0beca9eb1ee090d27c/show_church](/freereg_contents/54080f0beca9eb1ee090d27c/show_church)
Previous Page URL: [http://test2.freereg.org.uk/freereg_contents/53cd496ceca9ebee4f006a18/show_place](http://test2.freereg.org.uk/freereg_contents/53cd496ceca9ebee4f006a18/show_place)
Reported Issue:
This page does lead to further references, but it is not obvious that one needs to drill-down to get to them.  Is it possible to put that information on this page rather than requiring a drill-down?    

![Screenshot](http://test2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
But you can go straight to the register from the main page
