### ISSUE TITLE
Group opt in/out userid felds

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeUKRegProductIssues#1000]
Over the years we have added many fields that allow userid to do different things. These should be grouped in the show and edit views

**Comment by Captainkirkdawson** [comment]
Do this when code for #1310 is done

**Comment by Captainkirkdawson** [comment]
Displays have been adjusted in flexible_csv branch

**Comment by Captainkirkdawson** [comment]
On test2

**Comment by Captainkirkdawson** [comment]
Deployed to production

**Comment by SteveBiggs** [comment]
Assuming these are the only opt in/out fields:

![Capture.GIF](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/588631f51e19621a00230146/125516c66e82c728ace21e0d46cb958a379791accda5fd53b652fa912a5265296b51f02e7384e671e6162351580d4bac43585f45ffac8928f0a42062c80d55b98e30063e937f03a6aa8316b500bf228b4780bfba8e49c4ed3f37aa.GIF)
then all looks good.
