### ISSUE TITLE
83655387 Website Problem (Barrie Robinson)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1001]
Issue reported by **Barrie Robinson** at 2017-08-26 05:36:27 UTC
Time: 2017-08-26T05:27:40+00:00
Session ID: 022fbf98637dadfbb4d44a9298090649
Problem Page URL: []()
Previous Page URL: [https://www.freereg.org.uk/contacts/new](https://www.freereg.org.uk/contacts/new)
Reported Issue:
Having become the Coordinator for the Warwickshire County and Syndicate, I felt I should be completely up to date with procedures such as using winREG, and uploading files with winREG, as I haven't used these for ages. I have had a lot of trouble accessing the website , most of which might have arisen from using older browser versions, so have tried on my new laptop, which uses Windows 10 and Microsoft Edge. I downloaded the latest version of winREG, and imported a file to upload. No problem accessing the site including logging on as a member in Microsoft Edge, but as soon as I try to log on to the site in winREG using the freeREG server gateway tool and clicking on the logon button, I get the message, Errors! Your account has been disabled. As my account has obviously not been disabled (I can still log on anywhere else) I need to contact the people who manage the server.    

![Screenshot](http://www.freereg.org.uk/uploads/contact/screenshot/59a108dbf493fdf343adb3ba/_old_)

**Comment by Captainkirkdawson** [comment]
WinREG cannot be used to access the servers in FR2. It never was able to so do. WinFreeREG which was to be able to work with FR2 has yet to be released.
Uploading has to be done directly into the servers

**Comment by edickens** [comment]
This raises the issue of maintaining WinFreeREG.  Can we get the source from Mike Fry and find someone else to program it?  It is his copyright and he has developed it for free as I understand it.
If not, then should we go for online data entry sooner rather than later?

**Comment by Sherlock21** [comment]
As an outsider ( i.e. one who does not use it)  It seems there are major issues with WinFreeReg which can only put Transcribers & CC's off using it in my view - so a speedy solution of some sort is essential.

**Comment by edickens** [comment]
We do not recommend using WinFreeREG for now.  The reference to it has been removed from the Server's Help pages.
But the problem is that WinReg still has the option to link to the server for uploading, but it does not work as that refers to FR1.
