### ISSUE TITLE
88214908 Relocate needs documentation. (Barrie)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1005]
Issue reported by **brobinson43** at 2017-10-18 00:08:28 UTC
Time: 2017-10-18T00:00:31+00:00
Session ID: 2b5717a57ee0e5399271c5093505f909
Problem Page URL: [/cms/information-for-coordinators](/cms/information-for-coordinators)
Previous Page URL: [https://www.freereg.org.uk/contacts](https://www.freereg.org.uk/contacts)
Reported Issue:
I had difficulty finding how to change the type of a register. Eric Dickens told me to use 'Relocate' for the batch, but could not find this word in the help files. Also the button, Çhange Register Type' does not seem to work appropriately, as it produces a new register of type Parish Register if one already exists, rather than moving an unspecified register to an existing Parish Register.
So some documentation of 'Relocate batch' would be helpful.    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/59e69b7cf493fd5453e2190b/_old_)

**Comment by AlOneill** [comment]
The current information on Relocate can be seen here:
https://www.freereg.org.uk/cms/information-for-coordinators/coordinator-actions#relocateMerge

What needs adding/changing to make this section more useful?

**Comment by SteveBiggs** [comment]
Looks clear enough to me. Suggest this issue be closed.

**Comment by benwbrum** [comment]
Closing
