### ISSUE TITLE
Error getting into Refinery on test2 and test 3

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeUKRegProductIssues#1007]
Error: https://drive.google.com/file/d/0BzRDUeF70MtpLUJqSzUwY2ozNHM/view?usp=sharing

using chrome.

**Comment by Captainkirkdawson** [comment]
Lack of specificity on steps taken that arrive at that page means that statement of bug is premature
The RefineryCMS action on test2 gives the correct display.
![refinery.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53ecbbfc82b317f7d9ad93dc/125516c66e82c728ace21e0d46fa919c2a8c86bb96abf301b44fff9e2c4533317346f6787586e22de61b2f595f581ca9415a5f44fdfadc2ba5e02e6c981e5ab38532022d8c6853beb2901dbf0bbb258b4686b1bf8f44c3ee3c2df5c6.JPG)

**Comment by Captainkirkdawson** [comment]
The display provided has a hint of mixed applications. Note the FreeCEN statement in top left of snip. Should not be there is you are accesssing RefineryCMS from the RefineryCMS action through FreeREG
![refinery1.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53ecbbfc82b317f7d9ad93dc/125516c66e82c728ace21e0d46fa919c2a8c86bb96b8fd0fe64de29b234324676b5ee17e2380e029ba1b2255575f49fe44585d44fcf88a7ea6b56a62964e49bc8f3900299f7744eeaa880dbe09b0218e4f8cb5bb8944c9ee3522ee99c2.JPG)

**Comment by PatReynolds** [comment]
The steps I took were: go to test2 / test3 website.  Log in.  From actions, select 'refinery'.  Please ignore the mention of FreeCEN in the screenshot - it is a link from my browser to the FreeCEN statistics page, nothing to do with the tab I am in.

**Comment by richpomfret** [comment]
Works for others on test2, therefore could be specific to Pat's account or user type.

**Comment by PatReynolds** [comment]
Problem may be that I can sign in with user name, but not with email address.

**Comment by Vino-S** [comment]
Hi Pat,
Thanks for the detail. I found that your email address in UseriDetail model was set as **pat.reynolds@freeUKgenealogy.org.uk**. I had corrected it now 
(pat.reynolds@freeukgenealogy.org.uk). Could you please try to login using your email address again in test3 and let me know if there is an issue?

**Comment by PatReynolds** [comment]
Error still remains :-(

**Comment by PatReynolds** [comment]
Works fine now, thank you.
