### ISSUE TITLE
88511861 "Revise Search" and "New Search" buttons put in the same order on every page. -
 Enhancement Suggestion (Ian Pidgeon)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1008]
Issue reported by **Ian Pidgeon** at 2017-10-21 10:37:41 UTC
Time: 2017-10-21T10:30:32+00:00
Session ID: 1cda620440222f7e338cc2751af91245
Problem Page URL: []()
Previous Page URL: [https://www.freereg.org.uk/contacts/new](https://www.freereg.org.uk/contacts/new)
Reported Issue:
It would be helpful if the "Revise Search" and "New Seach" buttons were in the same order on every page.  
On the entry pages, they are in reverse order, so that there is a tendency to hit New when one intends to hit Revise.  This is particularly annoying for older people with cataracts, for whom your colour scheme makes it  difficult to read!!  (Such as this light grey on white - black would be better!)    

![Screenshot](http://www.freereg.org.uk/uploads/contact/screenshot/59eb2375f493fd5453fd3bf5/_old_)

**Comment by SteveBiggs** [comment]
Reverse the Revise and New buttons on the individual entry page so that Revise is the leftmost.

**Comment by SteveBiggs** [comment]
Tested and good on Test3. Need to push to production.

**Comment by SteveBiggs** [comment]
Fixed on production. Can be closed.
