### ISSUE TITLE
Crash when clicking Link on show_register page (steveroland)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#101]
Issue reported by **steveroland** at 2014-11-26 23:39:16 UTC
Time: 2014-11-26T23:31:14+00:00
Session ID: 92f0095848d9e899a24d34d58739c9c6
Problem Page URL: [/manage_resources/new](/manage_resources/new)
Previous Page URL: [http://test2.freereg.org.uk/refinery/login](http://test2.freereg.org.uk/refinery/login)
Reported Issue:
On page http://test2.freereg.org.uk/freereg_contents/5409ebd6eca9eb71826cde5f/show_register when any of the Link to decadal data is clicked, the attached error page came up.    

![Screenshot](http://test2.freereg.org.uk/tmp/carrierwave/1417045156-65046-7519/Link_error.jpg)

**Comment by Captainkirkdawson** [comment]
fixed

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Captainkirkdawson** [comment]
Thanks Kirk, looks good now.

Steve
