### ISSUE TITLE
89394769 Unable to send contacts on system (Denise Colbert)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1011]
Issue reported by **DenGage** at 2017-10-31 15:52:49 UTC
Time: 2017-10-31T15:50:59+00:00
Session ID: 85b28a9c864d2ba93d44e2f19882856a
Problem Page URL: [/contacts](/contacts)
Previous Page URL: [https://www.freereg.org.uk/userid_details/my_own](https://www.freereg.org.uk/userid_details/my_own)
Reported Issue:
I previously had this in my Actions, but now I don't seem to. Possibly since I was given access to all contacts for Comms?    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/59f89c51f493fd0e1f3968b1/_old_)

**Comment by richpomfret** [comment]
Appears to be a permissions issue. Vino to investigate.

**Comment by DeniseColbert** [comment]
This is what I have in my actions:

![image](https://user-images.githubusercontent.com/19173257/32540953-2f27b4c2-c466-11e7-8b82-f44b83dd7120.png)

But Contacts gives me all the messages that have come in through Comms and no option to send messages- ideally I need both facilities. Is this possible?

**Comment by Vino-S** [comment]
Hi @DeniseColbert ,
I guess you are not having access to "Message System". I have changed your role in Freereg from "technical" to "engagement_coordinator" so that you could have access to "Message System". Please logout and login again let me know if you had got the access. Please also make sure you also have access to  your other important Actions as your role has been updated.

**Comment by DeniseColbert** [comment]
Hi Vino, I now have access to the message system, but no longer have access to Feedback messages, which I also need

![image](https://user-images.githubusercontent.com/19173257/32546316-98cfd30e-c476-11e7-983a-9a9f50ddd74a.png)

**Comment by richpomfret** [comment]
This has now been fixed too. @DeniseColbert can you test again please?
