### ISSUE TITLE
Document the scripts that can be handled by our server / projects

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeUKRegProductIssues#1012]

**Comment by Captainkirkdawson** [comment]
What do you mean? Many of the the FreeREG scripts used on a regular basis are documented in the system documentation folders

**Comment by PatReynolds** [comment]
It needs info because this was an issue I created as a result of a discussion in a scrum ... and now none of us can remember what it means!  We are hoping that someone does ...

**Comment by edickens** [comment]
Was it so that we know which type of documents we can attach to messages?  At present it is just jpg.  I want to attach a pdf.
