### ISSUE TITLE
Change text of auto-response message to contacts and Feedback

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeUKRegProductIssues#1013]
Current text: A member of the team should be in touch within two business days.

As we split the comms role up, volunteers won't be able to guarantee a response in 2 business days. Can we change text to reflect this? Possibly "A member of the team should be in touch in 2-5 business days."?

**Comment by SteveBiggs** [comment]
I wouldn't state any deadline, just "A member of the team will be in touch shortly."

**Comment by PatReynolds** [comment]
From the original communication specification: there should be contact details for if no response is received.  Is that still thought a good idea?

**Comment by edickens** [comment]
That is what the "Telephone number" field is for.  It is not validated, so can contain whatever means of contact the person prefers.

**Comment by richpomfret** [comment]
Let's go with 'as soon as we can'.

**Comment by SteveBiggs** [comment]
When/where has this been implemented? A feedback came in this morning still stating 2 business days.

**Comment by Captainkirkdawson** [comment]
Deployed to production

**Comment by SteveBiggs** [comment]
Has this been applied to Feedback messages too?

**Comment by Captainkirkdawson** [comment]
@Vino-S  could you respond please

**Comment by Captainkirkdawson** [comment]
Given the story title I suspect not

**Comment by SteveBiggs** [comment]
I've changed the title. @Vino-S please make the same change to Feedback auto-response messages.

**Comment by RohitLearner** [comment]
In the event that there are further odds of changes in content for the auto-response message, observe for the best after drafts:-

1. Hello, Thank you for your email. Resolving your issues and answering questions is a top priority for us. A member of our team will follow up with you within 2 business days to resolve your inquiry.
Regards,

2. Dear XYZ,
Thank you for reaching out to FreeUkGen desk. We have received your email, and our team will be in touch with you soon.
You may refer to our FAQs at www.freeukgen.com/faqs for more information.
Please note that our working hours is 0730 to 1900 (GMT +100) from Monday to Saturday. We regret the delay in reply over the non-working hours.
Thank you for your understanding.
Best regards,

3. https://kickofflabs.com/blog/writing-a-good-auto-responder-to-say-thank-you/ 
Pick any of the over ones according to your advantage.

**Comment by SteveBiggs** [comment]
Text has been changed and looks good. Can be closed.
