### ISSUE TITLE
Message system does not send confirmation email

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeUKRegProductIssues#1014]
Priority 16 (0	1	8	7)
Sent a message t0day, did not receive email confirming that it was sent

**Comment by DeniseColbert** [comment]
The system should send a copy of the email sent, to the sender

**Comment by Captainkirkdawson** [comment]
@SteveBiggs  has this been addressed as part of the rewrite done by Vino?

**Comment by SteveBiggs** [comment]
Appears not @Captainkirkdawson. Just sent a test message from the general Message System to project_manager and did not get a copy myself.

**Comment by Captainkirkdawson** [comment]
Have added the sender to the list of recipients

**Comment by Captainkirkdawson** [comment]
Have deployed the new version to test3 for evaluation

**Comment by SteveBiggs** [comment]
Sent a message to only "Computer" and received a copy so this looks good now.
