### ISSUE TITLE
Update Terms of Use and IPR notices and year to 2018 where needed

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeUKRegProductIssues#1017]
See https://docs.google.com/a/freeukgenealogy.org.uk/document/d/1ua6ODxzxxgUgvsXkRONpZjiP0C-XRE_K-9ajJQ2J0Kc/edit?usp=sharing

**Comment by Sherlock21** [comment]
one little question:

To whom is this notice directed please?
a) the Volunteer?
or  b) the Member of the Public doing research?
or c) else to whom.

and if (b) where in individual record they are searching, does / willthe type of CC tag appear please?

OR have I got the wrong end of the stick?

**Comment by helhyde** [comment]
Anyone visiting the website.  I would imagine t&c and ipr notices would be
in the footer. But there may be a better place.

**Comment by Sherlock21** [comment]
This story could well benefit from such essential clues written into the title please - so we don't go off at a tangent with wrong ideas and comments.

**Comment by PatReynolds** [comment]
Have updated the T&C on live, but cannot change the year, so assigning that to @Vino-S

**Comment by benwbrum** [comment]
Pat to verify.

**Comment by richpomfret** [comment]
Verified.
