### ISSUE TITLE
89119004 There is a problem with letter-casing of file names (Staffordshire)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1019]
Issue reported by **STSCoord** at 2017-10-28 11:16:44 UTC
Time: 2017-10-28T11:04:51+00:00
Session ID: e0c797a86c942544570940b2458bb198
Problem Page URL: [/csvfiles/563eac06f493fdb8c300648d/edit](/csvfiles/563eac06f493fdb8c300648d/edit)
Previous Page URL: [https://www.freereg.org.uk/csvfiles/563eac06f493fdb8c300648d/edit](https://www.freereg.org.uk/csvfiles/563eac06f493fdb8c300648d/edit)
Reported Issue:
On FreeREG server there is a file STSBLTBA6.csv (note the letter case of the file type - lower case). The filename in the file header is the same, with the lower case of the file type.

I downloaded the file to my PC and, among other things, I changed the file name in the file header to STSBLTBA6.CSV (upper case file type). I then saved the file on my PC with the upper case file type.

When I tried to upload this file, I was informed that the file already exists and to do a "Replace". When I tried to do the "Replace", I was informed that the file must have the same name.

I was under the impression that letter casing in file names is not relevant, BUT IT IS.

The only way of getting my amendments onto the system is to (a) delete the existing file and then (b) upload the new file.    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/59f4671cf493fd0e1f1c2d6e/_old_)

**Comment by Sherlock21** [comment]
it is common to all counties - I too have noticed that my uploaded files with lower case file extension, come back downloaded as having upper case extensions.
I dont often use the downloaded file - so all my uploading ( from a Mac) goes in as the lower case extension and  work both as New files and as Reloads regardless of what the system says is there.

I do recall that Kirk said there actually was a difference in the meaning and treatment of upper case extensions from Windows, - but I dont know any more as it did not affect me.

Eric B

**Comment by edickens** [comment]
FR1 was case sensitive on filenames.  FR is not.  So care is needed.  The secret is not to have different files with the only difference being the case of the extension.

**Comment by richpomfret** [comment]
Potential rake task here to ensure no data is lost.

**Comment by Captainkirkdawson** [comment]
Firstly FR IS case sensitive. It runs on a unix based system and that is totally case sensitive. It is case sensitive both in the name and the extension
Secondly the file name in the header is irrelevant in FR. It uses the file name that you upload from your system for the file name respecting the case being delivered by your system.
Thirdly the file download fully respects the case of the file name and extension of the file that was uploaded.
So files NFKSOUMA.CSV, NFKSOUMA.csv, nfksouma.CSV and nfksouma.csv are 4 different files as far as a unix based system and FR is concerned.


Windows however is a very different animal. It IS NOT case sensitive.If you open a file called NFKSOUMA.csv in a folder  and try save it in the same folder as NFKSOUMA.CSV it will not the file will still be NFKSOUMA.csv. Now if you were to save it in a different folder then it would save as NFKSOUMA.CSV.
It would be possible to speculate that the initial attempt to change case was on a windows system in the same folder. So the upload attempt was actually of the same existing file hence the rejection.

These are 3 examples of the same file bur with different case
![case.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53ecbbfc82b317f7d9ad93dc/125516c66e82c728ace21e0d46eb958926c0cfeb9ffbb049a15ee4d6730472202c07a22e29dcb770ef1579545f5d4eac405b0a44ffaf9b37b4f46d2ede0356b49b381d66cc2f10abb2831abd00b8248e4686b4bd8d4dd2a5.JPG)
![case1.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53ecbbfc82b317f7d9ad93dc/125516c66e82c728ace21e0d46eb958926d3c1e5cdf9ad4cae58f3806b1c65267a01a02a75dcba7ce7122c035a5f4cac41595c11fcfadf39baa47e21d40854b088270a36d43703adb1881eba03bb228f4a8cb5be8b4bc5fa70.JPG)

**Comment by richpomfret** [comment]
Closing.
