### ISSUE TITLE
90753891 Problem with WinREG/3 (Stuart)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1021]
Issue reported by **vk3dwu** at 2017-11-16 09:24:51 UTC
Time: 2017-11-16T09:21:54+00:00
Session ID: e0e134e6bc302d9fd7304c096181212b
Problem Page URL: [/cms/information-for-transcribers](/cms/information-for-transcribers)
Previous Page URL: [https://www.freereg.org.uk/](https://www.freereg.org.uk/)
Reported Issue:
I hope someone can help me......  A Windows 10 update ran today and I now cannot run the latest WinREG/3 (3.2.22).  All I get is a dialogue box which tells me that "WinREG/3 for Windows has stopped working"  and that "Windows is checking for a solution to the problem".  Of course, in typical Windows fashion, the dialogue box simply disappears without suggesting a solution or advising that no solution can be found.  I have tried uninstalling and reinstalling but the problem persists.  Ran a Malware check and a McAfee quick scan, both of which found nothing untoward.  Have reverted to 3.2.20 which appears to be OK but would much rather be using the latest.  Anyone got any idea what the problem might be?
    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/5a0d5963f493fddd1d4ff50f/_old_)

**Comment by richpomfret** [comment]
For our new coder to look at.

**Comment by richpomfret** [comment]
In the meantime, we can advise users to roll back to a previous version to get it working (if needed).

**Comment by SteveBiggs** [comment]
@DeniseColbert  have you replied to Stuart to say that it's perfectly fine to use an earlier version?

**Comment by DeniseColbert** [comment]
Have done that, and said we'll update him.

**Comment by SteveBiggs** [comment]
Great, thanks Denise.
