### ISSUE TITLE
91352803 Wrong syndicate members (Barrie)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1022]
Issue reported by **brobinson43** at 2017-11-23 07:46:43 UTC
Time: 2017-11-23T07:43:40+00:00
Session ID: 2d9f916ca27ed749da42d416f58a5bb8
Problem Page URL: [/userid_details/selection?option=Select+specific+surname%2Fforename](/userid_details/selection?option=Select+specific+surname%2Fforename)
Previous Page URL: [https://www.freereg.org.uk/manage_syndicates/select_action](https://www.freereg.org.uk/manage_syndicates/select_action)
Reported Issue:
When I look at members under 'Manage syndicate'  (for the Warwickshire syndicate) whether Active, all, by username, by email address or by surname:given name, I get a whole lot of transcribers none of whom I recognize, and no transcribers from the WAR syndicate!    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/5a167ce3f493fd98ace395eb/_old_)

**Comment by DeniseColbert** [comment]
Subsequent comment: 

"In reference to the previous problem with wrong transcribers for my syndicate, I logged out and logged back in again, and all was OK. However, I would still think there's an underlying problem that needs fixing."
