### ISSUE TITLE
91476957 Enhancement Suggestion (Peter Smith)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1023]
Issue reported by **Peter Smith** at 2017-11-24 18:15:57 UTC
Time: 2017-11-24T18:04:06+00:00
Session ID: 983370e7dfab65ed4e37246ab67cdc60
Problem Page URL: []()
Previous Page URL: [https://www.freereg.org.uk/contacts/new](https://www.freereg.org.uk/contacts/new)
Reported Issue:
When filling in a search form, it is very quick and convieniet to go from one field to the next with the tab key. However this does not work with FreeReg as when (I am using Firefox) I enter a Surname and press tab, a help baloon opens up covering the next field (Forename(s)). Could you alter this so the the help baloon opens up ABOVE the field rather than covering it, so that one can enter a value?
(otherwise I am very happy with the function of this site)
http://www13.freereg.org.uk/uploads/contact/screenshot/5a1861ddf493fd98acee3438/FreeReg_search_form.jpg    

![Screenshot](http://www.freereg.org.uk/uploads/contact/screenshot/5a1861ddf493fd98acee3438/FreeReg_search_form.jpg)

**Comment by DeniseColbert** [comment]
I suggested that they double-tab and asked if they are happy with this solution; they replied:

"Yes, pressing the tab key a second time removes the help balloon, allowing me to enter a search value. It is not necessarily intuitive, but works. Is it necessary for the help balloon to always appear in this manner? A possibility would be to only show it if there is a field validation check."

**Comment by Captainkirkdawson** [comment]
Let them know it works this way to aid our visually impaired users.

**Comment by DeniseColbert** [comment]
Have done so.
