### ISSUE TITLE
91982046 List zero dates option only works for baptisms (Staffordshire)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1024]
Issue reported by **STSCoord** at 2017-11-30 14:34:06 UTC
Time: 2017-11-30T14:30:30+00:00
Session ID: 19966e944446169bce93b4bc3c61d8fa
Problem Page URL: [/freereg1_csv_files/546390ace9379010fc52a571/zero_year](/freereg1_csv_files/546390ace9379010fc52a571/zero_year)
Previous Page URL: [https://www.freereg.org.uk/freereg1_csv_files/546390ace9379010fc52a571](https://www.freereg.org.uk/freereg1_csv_files/546390ace9379010fc52a571)
Reported Issue:
The new option on the Batch Display screen displays records with a birth date but no baptism date. See the attached image.
http://www13.freereg.org.uk/uploads/feedback/screenshot/5a2016def493fd98ac231fc8/Capture.JPG    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/5a2016def493fd98ac231fc8/Capture.JPG)

**Comment by SteveBiggs** [comment]
This may be the case for old files, but once edited or reprocessed, they do not have this problem.

**Comment by SteveBiggs** [comment]
No dev action required.
