### ISSUE TITLE
92445317 Several MA files with no marriage dates (Staffordshire)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1025]
Issue reported by **STSCoord** at 2017-12-05 23:15:17 UTC
Time: 2017-12-05T23:05:26+00:00
Session ID: 19966e944446169bce93b4bc3c61d8fa
Problem Page URL: [/freereg1_csv_files/55c6cca4f493fd857c0095d0](/freereg1_csv_files/55c6cca4f493fd857c0095d0)
Previous Page URL: [https://www.freereg.org.uk/freereg1_csv_files/55c6cca4f493fd857c0095d0/zero_year_entries?](https://www.freereg.org.uk/freereg1_csv_files/55c6cca4f493fd857c0095d0/zero_year_entries?)
Reported Issue:
I have several MA files from various transcribers where the marriage date is empty through the whole file. Although this is the case, the decadels for the file show non-zero counts implying that the marriage dates from the file have, at one time, been processed into FreeREG and have since been lost. Why? ALso, why does it seem to be only MA files that are affected. This has been discovered since the "zero date listing" enhancement was installed. I do not think that it is anything to do with this very useful enhancement. As an aside, why has this enhancement not been included in the "log on" screen? Please contact mne for the contents of the CSV file. 
http://www13.freereg.org.uk/uploads/feedback/screenshot/5a272885f493fd98ac4829d3/Summary.JPG    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/5a272885f493fd98ac4829d3/Summary.JPG)

**Comment by edickens** [comment]
Michael Clarke's file STSLOTMA1.CSV definitely has lost all the MA dates.  Needs urgent investigation in case other are losing data and not realising it.

**Comment by Captainkirkdawson** [comment]
According to the entry and search record there was no date in the entry although the creation of a year date indicates there was something in the field originally. 

shard3:PRIMARY> db.freereg1_csv_entries.find({_id: ObjectId("55c6cca5f493fd857c0095d2")})
{ "_id" : ObjectId("55c6cca5f493fd857c0095d2"), "error_flag" : "false", "line_id" : "bevstubbs1.STSLOTMA1.CSV.1", "file_line_number" : 1, "register_entry_number" : "1", "year" : "1866", "groom_forename" : "Samuel", "groom_surname" : "ALLEN", "groom_age" : "20", "groom_parish" : null, "groom_condition" : "bachelor", "groom_occupation" : "Potter", "groom_abode" : "Lane End", "bride_forename" : "Eliza", "bride_surname" : "COLCLOUGH", "bride_age" : "19", "bride_parish" : null, "bride_condition" : "spinster", "bride_occupation" : null, "bride_abode" : "Edensor", "groom_father_forename" : "Felix", "groom_father_surname" : "ALLEN", "groom_father_occupation" : "Potter", "bride_father_forename" : "Samuel", "bride_father_surname" : "COLCLOUGH", "bride_father_occupation" : "Potter", "witness1_forename" : "Samuel", "witness1_surname" : "COLCLOUGH", "witness2_forename" : "Hannah", "witness2_surname" : "COLCLOUGH", "notes" : null, "county" : "STS", "place" : "Longton", "church_name" : "St John", "register_type" : "PR", "record_type" : "ma", "freereg1_csv_file_id" : ObjectId("55c6cca4f493fd857c0095d0"), "record_digest" : "lYhZS5S8aGwHfe1UO2ARFA==", "u_at" : ISODate("2015-08-09T03:44:37.056Z"), "c_at" : ISODate("2015-08-09T03:44:37.056Z"), "multiple_witnesses" : [ { "_id" : ObjectId("55f0d5d8f493fde8a602211d"), "witness_forename" : "Samuel", "witness_surname" : "COLCLOUGH" }, { "_id" : ObjectId("55f0d5d8f493fde8a602211e"), "witness_forename" : "Hannah", "witness_surname" : "COLCLOUGH" } ] }
shard3:PRIMARY> db.search_records.find({freereg1_csv_entry_id: ObjectId("55c6cca5f493fd857c0095d2")})
{ "_id" : ObjectId("58186fb0e93790eb7fcd50af"), "transcript_dates" : [ ], "search_dates" : [ ], "location_names" : [ "Longton (St John)", " [Parish Register]" ], "search_soundex" : [ { "first_name" : "E420", "last_name" : "C424", "type" : "p" }, { "first_name" : "S540", "last_name" : "A450", "type" : "p" }, { "first_name" : "F420", "last_name" : "A450", "type" : "f" }, { "first_name" : "S540", "last_name" : "C424", "type" : "f" }, { "first_name" : "S540", "last_name" : "C424", "type" : "w" }, { "first_name" : "H500", "last_name" : "C424", "type" : "w" }, { "first_name" : "E421", "last_name" : "C424", "type" : "p" } ], "record_type" : "ma", "search_record_version" : "2016-10-31T00:00:00+00:00", "chapman_code" : "STS", "line_id" : "bevstubbs1.STSLOTMA1.CSV.1", "transcript_names" : [ { "role" : "b", "type" : "primary", "first_name" : "Eliza", "last_name" : "COLCLOUGH" }, { "role" : "g", "type" : "primary", "first_name" : "Samuel", "last_name" : "ALLEN" }, { "role" : "gf", "type" : "other", "first_name" : "Felix", "last_name" : "ALLEN" }, { "role" : "bf", "type" : "other", "first_name" : "Samuel", "last_name" : "COLCLOUGH" }, { "role" : "wt", "type" : "witness", "first_name" : "Samuel", "last_name" : "COLCLOUGH" }, { "role" : "wt", "type" : "witness", "first_name" : "Hannah", "last_name" : "COLCLOUGH" } ], "freereg1_csv_entry_id" : ObjectId("55c6cca5f493fd857c0095d2"), "search_date" : null, "place_id" : ObjectId("53cd4984eca9ebee4f0093f9"), "digest" : "SMF+5Y6g15MUDW5fiwox5g==", "search_names" : [ { "_id" : ObjectId("58186fb0e93790eb7fcd50ae"), "first_name" : "eliza", "last_name" : "colclough", "origin" : "transcript", "type" : "p", "role" : "b", "gender" : "f" }, { "_id" : ObjectId("58186fb0e93790eb7fcd50b0"), "first_name" : "samuel", "last_name" : "allen", "origin" : "transcript", "type" : "p", "role" : "g", "gender" : "m" }, { "_id" : ObjectId("58186fb0e93790eb7fcd50b1"), "first_name" : "felix", "last_name" : "allen", "origin" : "transcript", "type" : "f", "role" : "gf", "gender" : "m" }, { "_id" : ObjectId("58186fb0e93790eb7fcd50b2"), "first_name" : "samuel", "last_name" : "colclough", "origin" : "transcript", "type" : "f", "role" : "bf", "gender" : "m" }, { "_id" : ObjectId("58186fb0e93790eb7fcd50b3"), "first_name" : "samuel", "last_name" : "colclough", "origin" : "transcript", "type" : "w", "role" : "wt", "gender" : null }, { "_id" : ObjectId("58186fb0e93790eb7fcd50b4"), "first_name" : "hannah", "last_name" : "colclough", "origin" : "transcript", "type" : "w", "role" : "wt", "gender" : null }, { "_id" : ObjectId("58186fb0e93790eb7fcd50ae"), "first_name" : "elizabeth", "last_name" : "colclough", "origin" : "e", "type" : "p", "role" : "b", "gender" : "f" } ] }

The attic files show that the file of  2015-8-8 has date entries.
+INFO,bevstubbs@talktalk.net,password,SEQUENCED,MARRIAGES,,3.02.11
#,CCC,Beverley Stubbs,Staffordshire,STSLOTMA1.CSV,17-Jun-2012
#,CREDIT,Beverley Stubbs,stubbsbev62@gmail.com
#,08-Aug-2015,Microfiche Original Register,
STS,Longton,St John PR,1,05 Mar 1866,Samuel,ALLEN,20,,bachelor,Potter,Lane End,Eliza,COLCLOUGH,19,,spinster,,Edensor,Felix,ALLEN,Potter,Samuel,COLCLOUGH,Potter,Samuel,COLCLOUGH,Hannah,COLCLOUGH,

The next file in the attic shows that all the marriage dates are missing.
+INFO,stubbsbev62@gmail.com,PASSWORD,SEQUENCED,MARRIAGES,Windows-1252
#,CCC,Beverley Stubbs,Staffordshire - Michael Clarke,STSLOTMA1.CSV,17-Jun-2012
#,CREDIT,Beverley Stubbs,stubbsbev62@gmail.com
#,25-Oct-2015,Microfiche Original Register,""
STS,Longton,St John PR,1,"",Samuel,ALLEN,20,"",bachelor,Potter,Lane End,Eliza,COLCLOUGH,19,"",spinster,"",Edensor,Felix,ALLEN,Potter,Samuel,COLCLOUGH,Potter,Samuel,COLCLOUGH,Hannah,COLCLOUGH,""

Note the empty fields are "" which would indicate that file had been processed by something in between. Given the name change in syndicate I suspect the the file had been downloaded after being processed on 08 Aug 2015.

**Comment by Captainkirkdawson** [comment]
Downloading MA files currently with dates have dates present in the downloaded file.

**Comment by SteveBiggs** [comment]
Issue appears to be isolated to a few MA files in STS uploaded on 8th Aug 2015. No reports elsewhere.

**Comment by Captainkirkdawson** [comment]
I agree that the issue appears to be limited to a few files in STS. Appears slightly more complex. The files were uploaded and processed correctly. They were then downloaded, processed off line and re uploaded and processed without date fields in October of 2015.
Do not believe there is any bug

**Comment by Sherlock21** [comment]
Wasn't this period in Aug 2015 one of the times when we had a system part outage to reorganise either the number of servers, or something - when there was a ban on uploading for a week or so? is that a clue?

**Comment by Sherlock21** [comment]
I have just been contacted by Ali Hill to say she has found a file that now has no marriage dates in it. It was OK up to 8 Aug 2015.

I investigated, and the marriage dates that were in, were all sound in the version that I downloaded from the Attic.

the userID is alihill and file name is WRYASBMA.CSV - this id is not that of the CC for WRY !.

Over to you. We will NOT change anything online.
AND to make it worse - Ali advises me there are more to come!

**Comment by Captainkirkdawson** [comment]
Someone downloaded the file and reuploaded the file today 8 Dec 2017 thereby  contaminating the evidence trail!

**Comment by Sherlock21** [comment]
i looked at it, using SH for show, in the listing. - then downloaded it in order to have a copy on my desktop - to compare with the Attic one that I also downloaded - for same reasons.

After determining that there was an issue, I did not alter anything and I asked Ali to not touch it either - but as there is a time lapse between us, having a think to identify there is an issue to be looked, at, and sending an email to ask Ali to not do anything with it, its inevitable. I have not had any further  emails form Ali since 11:23 GMT today 8 dec. So I can't add further at this point.

Might it be that just looking at, and downloading a batch, as above actually alters the data record?

**Comment by edickens** [comment]
Downloading will unlock the batch.  So even if the batch is not locked, would the server unset the flag just in case and so update the processed date?

**Comment by Captainkirkdawson** [comment]
No the file was downloaded, uploaded and processed but not to worry see next comment.

**Comment by Captainkirkdawson** [comment]
After digging deeply into our history I have found the following.
On August 8, 2015 we introduced a new method of calculating the date distribution of entries into the file processing software. It was observed that this code had a logic error that affected marriage dates. That error was fixed on 10 August 2015. The complete processor was replaced in May 2016.
It is highly likely that all marriage files processed between August 8 and August 10, 2015 will show no marriage dates. The exact time of introduction and solution on those dates is unknown which is why some of the files for that period may be correct.
Any attempt to download/upload or reprocess the file will NOT correct the problem.
I am evaluating the best solution

**Comment by edickens** [comment]
Can you identify the files and we can recover the files from the Attic and inform the CC to check if additions were made at that time?  We can save the files in error for checking purposes.  There should not be that many.

**Comment by Captainkirkdawson** [comment]
The solution is to download from the attic a version of the file dated between that period. Confirm that the dates are present. Then replace the file with the downloaded one (having removed the date extension on the file name). If there are multiple files for that period use the earliest of the period.

**Comment by Sherlock21** [comment]
given these last 2 posts, is it appropriate to stop all back fit processing by CC's and Transcribers, either direct on line, or by RL the batch, so as not to end up chasing out tales

In which case: would it be best if someone ( who could write to all Cc's and Transcribers) to tell them to hold off until further notice?  since i don't remember ever having a  feature that would let this be done by Administrator - or can it? 

Or is the proposal that everyone does their own, by hand? - in which case, they will actually need telling to do it as very few get these github lists do they?

**Comment by Captainkirkdawson** [comment]
EricD every coordinator/ data manager and system administrator has the ability to identify the affected files. 
Anything else would have to be programmed by vino as you know I am no longer active. 
I looked into this issue as I suspected that others lacked the detailed knowledge of the processor and its history to locate the actual issue without expending massive amounts of time.

**Comment by PatReynolds** [comment]
I've shared a draft message with Steve.

**Comment by SteveBiggs** [comment]
I already sent a message to all coords yesterday.

**Comment by Vino-S** [comment]
The following files was been affected and are all replaced:
1. STSGAYMA
2. STSLOTMA1
3. STSJMAMA
