### ISSUE TITLE
92026331 Display Age of Death in results list for burials Suggestion (Paul Turner)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1026]
Issue reported by **Paul Turner** at 2017-12-01 02:52:11 UTC
Time: 2017-12-01T02:45:50+00:00
Session ID: 9e5bae0fb4708138887c453cb3c931a9
Problem Page URL: []()
Previous Page URL: [https://www.freereg.org.uk/contacts/new](https://www.freereg.org.uk/contacts/new)
Reported Issue:
Hi,

First up, thanks for such a great free site.
I hope next year I be able to help you in the transcribing.

My question would be, is it possible to have in the Death Queries the person age in the results? This would speed up the process of looking for a person death date. As you know it's hard to pinpoint a person's death and sometimes the area. If it is between Censuses then quite a few of the same name will appear. As you know they like to stick to the same names.

Thanks again for the great site, all the best,

Paul Turner

    

![Screenshot](http://www.freereg.org.uk/uploads/contact/screenshot/5a20c3dbf493fd98ac2782cb/_old_)

**Comment by PatReynolds** [comment]
@DeniseColbert how did this get to you?  Is it a query about FreeREG?

**Comment by PatReynolds** [comment]
Paul has probably unfortunately found records with no age at death - so death summary results  should say 'age not given' or 'age blank'.

**Comment by edickens** [comment]
Our principle is that we do not show the field name in the Details report if the field is empty.  This is a good idea because, particularly in the case of Marriages where there are lots of fields, the researcher will be scrolling through a lot of blank fields, particularly with the older entries.  However, could this be an exception?  And if so, are there other fields which need to be handled the same way?

**Comment by DeniseColbert** [comment]
This came in to Comms

**Comment by Sherlock21** [comment]
As Eric D says above, the existing rule has served well in the past.
So what's the special feature of  this field?
I think that if we show some fields that are empty and omit others that are empty, then its a recipe for confusion. Especially true in the case of records that have as many fields as Marriages do.

**Comment by SteveBiggs** [comment]
We should reply back to Paul that the age at death is recorded and displayed with the search results if it was given in the original record, but if it was not present in the original record, it will not be displayed.

**Comment by Sherlock21** [comment]
Is it worth a little note on the Results Details Page saying: record fields which do not contain a value, are not listed here.?

But I just looked and the field for Transcriber Note is shown even if no details.

- a bit of an anomaly here?

**Comment by Captainkirkdawson** [comment]
We display the person's age, if present, on the search result details page
Comment is now provided "only fields with a value are shown".
Empty fields are not displayed.
The print,csv and json formats have all fields.
This responds to the discussion.
HOWEVER the user may have been requesting that the Age field appear in the search results page. We have in the past resisted all suggestions of adding additional fields to the basic results display

**Comment by SteveBiggs** [comment]
The title of the issue suggests he is talking about the summary results list. Including age would save some time in finding the correct record but if our policy is to not do so, then that's the answer to his question.

**Comment by SteveBiggs** [comment]
The way death age is displayed has been explained to Paul and he has not asked any further questions so this can be closed.
