### ISSUE TITLE
93009970 In Test3 I cannot log in with one of my IDs. (Eric)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1027]
Issue reported by **REGManager** at 2017-12-12 12:06:10 UTC
Time: 2017-12-12T12:02:14+00:00
Session ID: 47e6712a39f404093dcc150bbf773f78
Problem Page URL: [/manage_resources/new](/manage_resources/new)
Previous Page URL: [https://www.freereg.org.uk/cms/refinery/login](https://www.freereg.org.uk/cms/refinery/login)
Reported Issue:
I cannot log in with EricD, but can with all my others.  It says I have cookies disabled, which I do not, and it does not give me the option to accept cookies.  All my other IDs work fine.  Why?
http://www13.freereg.org.uk/uploads/feedback/screenshot/5a2fc632f493fd98ac822df4/Capture.JPG    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/5a2fc632f493fd98ac822df4/Capture.JPG)

**Comment by edickens** [comment]
OK now.  Close.
