### ISSUE TITLE
92489635 The contact I am trying to find does not exist (Pat)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1028]
Issue reported by **PatReynolds** at 2017-12-06 11:33:55 UTC
Time: 2017-12-06T11:32:48+00:00
Session ID: 6ffdaa7051a5535a50dcd32541c1feee
Problem Page URL: [/contacts/select_by_identifier](/contacts/select_by_identifier)
Previous Page URL: [https://www.freereg.org.uk/contacts/list_by_name](https://www.freereg.org.uk/contacts/list_by_name)
Reported Issue:
I am looking for contact number 53399079    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/5a27d5a3f493fd98ac4b8085/_old_)

**Comment by edickens** [comment]
Looks like everything before September has been deleted because it has been answered.  ED

**Comment by PatReynolds** [comment]
We currently have 58 issues created in 2016 which are 'open' where the only way we had of contacting the originator may be via the contacts page.  One going back to Dec 2014. A further 25 which were created in Sept 2017or earlier, and 10 later issues which are still on the contacts.

Admittedly this case was me taking too long to get around to responding ....

**Comment by SteveBiggs** [comment]
Perhaps the contact was answered (by email) but the issue was not closed for those ones? This is why we need a reply action within the FR system so that the history is saved.

**Comment by PatReynolds** [comment]
In this case, need to go to CommsCord email file to find it there.
