### ISSUE TITLE
92653660 csv errors file won't download (Eric)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1029]
Issue reported by **ericb** at 2017-12-08 09:07:40 UTC
Time: 2017-12-08T09:04:31+00:00
Session ID: 189d228f4105b439b5c5e0d1b90fa486
Problem Page URL: [/physical_files/processed_but_no_file](/physical_files/processed_but_no_file)
Previous Page URL: [https://www.freereg.org.uk/physical_files/select_action?](https://www.freereg.org.uk/physical_files/select_action?)
Reported Issue:
this report ( for DM) -Listing of physical files ; Processed but no file for all- shows 613 records in it. but it will not download for me.
error msg is: red. oops something went wrong.
I tried twice. and also disabled my Safari browser extensions (in cad that was the problem) but to no avail.    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/5a2a565cf493fd98ac5a0b63/_old_)

**Comment by SteveBiggs** [comment]
This is trying to download the report using the CSV link:
![Capture.GIF](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/588631f51e19621a00230146/125516c66e82c728ace21e0d46cb958a379791accda5fd53b652fa912a5265296b51f02e7384e671e6162351580d4bac43585f45ffac8928f0a42062c80d55b98e30063e937f03a6aa8317b500bf218e4a86beb5894ac3ef3837aa.GIF)

I get the same error when I try.

**Comment by Captainkirkdawson** [comment]
@Sherlock21 Fix applied to test2 you should now be able to download as csv file for all displays in physical files. Please try it out

**Comment by Sherlock21** [comment]
Tested this out in T2.

I got the green .csv feature in the right place, but clicking on that to download the file, gave this error message:-

**Comment by Sherlock21** [comment]
/Users/eric/Desktop/fail message.jpg

**Comment by Sherlock21** [comment]
The above test related to Files not Processed. - as there were no files Awaiting processing at that time.

ALSO there is no image attaching here, as Neither Drag & Drop, NOR Select the image worked for me.
I have sent it to Kirk by good old reliable email.

**Comment by Sherlock21** [comment]
The above test related to Files not Processed. - as there were no files Awaiting processing at that time.

ALSO there is no image attaching here, as Neither Drag & Drop, NOR Select the image worked for me.
I have sent it to Kirk by good old reliable email.

**Comment by Vino-S** [comment]
Hi @Captainkirkdawson ,

I have updated the code in test3.  The code fixes the following issues:
1. I have done various manual testing and considered when sorted_by is nil, the code will will fetch the complete list of batches.
2. There was an issue with CSV in List files waiting to be processed and List files Not Processed in Manage Syndicate Option, which is been fixed.

Please have a look and give me a feedback

**Comment by Captainkirkdawson** [comment]
@Vino-S we may have been working at cross purposes; ericb had emailed me directly with tests and I had applied some fixes in the development branch. Will have a look at integration of our respective mods

**Comment by Captainkirkdawson** [comment]
@Vino-S 

Adopted a different approach; stored the sorted by which in set in many displays into a session variable. Then used that when we were doing a csv .

Also enabled that to work for all coordinators.

EricB has fully tested the code on test2 so if you don't mind I would prefer we went with my changes.

**Comment by Vino-S** [comment]
Sure, Thanks Kirk  :)
