### ISSUE TITLE
92674255 Select ID for file replacement (Ali)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1030]
Issue reported by **alsibk** at 2017-12-08 14:50:55 UTC
Time: 2017-12-08T14:44:54+00:00
Session ID: a220b3ece40df72840572c455449236a
Problem Page URL: [/csvfiles/5a2a9eddf493fd49942ad931/edit](/csvfiles/5a2a9eddf493fd49942ad931/edit)
Previous Page URL: [https://www.freereg.org.uk/csvfiles/5a2a9eddf493fd49942ad931/edit](https://www.freereg.org.uk/csvfiles/5a2a9eddf493fd49942ad931/edit)
Reported Issue:
Not working.

I select correct ID and it is rejected.

See clip
http://www13.freereg.org.uk/uploads/feedback/screenshot/5a2aa6cff493fd98ac5bc828/Select_ID.jpg    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/5a2aa6cff493fd98ac5bc828/Select_ID.jpg)

**Comment by suffolkroots** [comment]
I found a way round this problem (can't remember what) and cancelled the problem report. It has not happened since, so unless others have experienced it I suggest this is closed.
