### ISSUE TITLE
92792091 I thought filenames were not case-sensitive (Staffordshire)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1031]
Issue reported by **STSCoord** at 2017-12-09 23:34:51 UTC
Time: 2017-12-09T23:27:12+00:00
Session ID: acf90bd1a2ebcad32587e524d9f03fe7
Problem Page URL: [/registers/540802d9eca9eb024871380f](/registers/540802d9eca9eb024871380f)
Previous Page URL: [https://www.freereg.org.uk/churches/540802d9eca9eb024871380d](https://www.freereg.org.uk/churches/540802d9eca9eb024871380d)
Reported Issue:
On the attached screengrab, I have highlighted two files/batches, the names of which only differ in the letter-case of the file extension - "csv" and "CSV". This caused me confusion at first because I thought that, somehow, I had got two files with the same name but different contents - how could this be? Then I spotted the letter-casing.
http://www13.freereg.org.uk/uploads/feedback/screenshot/5a2c731bf493fd98ac6b883e/Capture.JPG    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/5a2c731bf493fd98ac6b883e/Capture.JPG)

**Comment by Sherlock21** [comment]
michael has a very valid point here.

Mac uses create files with .csv in lower case. thats how they come. 
On the other hand, some Windows systems generate CSV files with upper case extension.

Now if the Transcriber generates Mac .csv files, and say the CC using a windows spreadsheet,  goes to  reload to it, what will that create? 
a refusal saying file names not the same?
or a second file like this example?

Not a good thing to have happen in my view.

EB

**Comment by edickens** [comment]
FR1 was case sensitive and there are duplicate filenames with just the case of CSV as the difference.  So FR had to be case sensitive.  But now the batch name includes the UserID, so perhaps case sensitivity is no longer needed.

**Comment by Sherlock21** [comment]
I agree with Eric D . it seems to be a disaster awaiting to happen as we have it now.

**Comment by suffolkroots** [comment]
Yes .csv and .CSV are seen as different files. In Windows, WinREG produces .CSV and spreadsheet produces .csv
Needs careful watching and is VERY annoying.

**Comment by PatReynolds** [comment]
The system should reject any upload that is identical (for the user ID) before the dot.  Then make system case-insensitive. (edited to take in EricD's comment)

**Comment by edickens** [comment]
To clarify.  It is the uploading of a new file when the filename must be unique within the UserID, including not being case sensitive.  When replacing a file, the filename must match, including case, to allow for those previously uploaded when not being case sensitive.

**Comment by Captainkirkdawson** [comment]
Filenames are case sensitive in all aspects. The whole unix file system is case sensitive. I see no reason to make any change.
