### ISSUE TITLE
94216425 Data Question (Martyn West)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1032]
Issue reported by **Martyn West** at 2017-12-26 11:13:45 UTC
Time: 2017-12-26T11:00:45+00:00
Session ID: 58c7f6c3381900aeda6db85df42e440f
Problem Page URL: []()
Previous Page URL: [https://www.freereg.org.uk/contacts/new](https://www.freereg.org.uk/contacts/new)
Reported Issue:
a few days before Christmas I decided to add more to the data I had already gleaned form your records for the town of Gillingham in Kent, on returning to your data base I found that all the dates from 1900 until now had 4 years and 1 day removed from all the dates. Thinking it was a correction that had been made I corrected my data and moved on to Dartford only to find that the same had happened there. I have stopped until it is clarified, is it a correction? or is it a virus on your system? The screen shot is your system now.
http://www13.freereg.org.uk/uploads/contact/screenshot/5a422ee9f493fd0c2e537d10/Gillingham.JPG    

![Screenshot](http://www.freereg.org.uk/uploads/contact/screenshot/5a422ee9f493fd0c2e537d10/Gillingham.JPG)

**Comment by Sherlock21** [comment]
I just checked 3 of my batches that I know have not been revised in the timescale here.
A Baptism file, a Marriage file and a Burial file.

Picked one record at random from my PC master copy file, compared against the Production batch and the dates were the same  in all 3 record types. (Baptism, Marriage & burial).

Also did a FR Search of one of the records chosen above. the Search returned the correct date.

So although I only took a small sample, it was randomly selected from my own batches. and I cannot repeat the finding.
 
So who is to try and understand this one?

Further enquiry in this one: i checked int he Attic. There are no records at all in the Attic for this transcriber. here is the current batch info for the record quoted above.


![screen shot 2018-01-03 at 21 35 31](https://user-images.githubusercontent.com/9368704/34540947-5b592a32-f0ce-11e7-9807-b626a3663472.png)

**Comment by SteveBiggs** [comment]
This should be passed to the coordinator for Kent to check.

**Comment by edickens** [comment]
Can be closed.  Cannot be reproduced.  SC is contacting transcriber.

**Comment by DeniseColbert** [comment]
Sorry, I thought I'd answered this?! I've replied to the originator with the image from Kent Coord to show that our transcription agrees with the register.
