### ISSUE TITLE
Add Report a Data Error (Problem) to each Search Result

### ISSUE THREAD

**Issue by Vino-S** [FreeUKGen/FreeUKRegProductIssues#1034]

**Comment by Vino-S** [comment]
Added "Report a problem" icon to each search result and also added the details of the result that is been reported to the email which will be useful for commscord.

Ready for testing in test3

**Comment by DeniseColbert** [comment]
Tested - 
Search results page- works fine, I like the icons 👍 
Record details page - I think the link may be easily missed where and how it currently is. perhaps if the link had the text "Report an Error in Transcription" and was placed centrally above the table, and also below the table?

![image](https://user-images.githubusercontent.com/19173257/34965040-21bc144a-fa49-11e7-82e5-63ac4f74725e.png)

![image](https://user-images.githubusercontent.com/19173257/34965029-0a577bf0-fa49-11e7-931f-6afdb9601d39.png)

**Comment by Vino-S** [comment]
Thanks Denise.
I had update the search_records details page with "Report an Error in Transcription" button. Please have a look.

**Comment by DeniseColbert** [comment]
Definitely more noticeable. 

Opinions as to whether we need the Report a Problem button at the bottom left of the page?

**Comment by Vino-S** [comment]
Yes that was what I was thinking too. If not needed we can remove that button.

**Comment by AlOneill** [comment]
Two things on Search Results:

To a blind user, the link is empty. Needs some 'hidden' text, such as:
`<span class="accessibility">Report a problem with  record 1</span>`
This text needs to be brief but clear, and can't be all identical — may need some work!

The column heading will always be wider than the content so suggest a `<br>` between "Report a" and "problem". This will allow table to adjust better at different widths.

**Comment by AlOneill** [comment]
The button in the caption on Search Detail looks unbalanced: try changing `btn--small ` to `btn--natural` and see what you think.

[Sorry, but cannot get image to drop or upload. Weird.]

**Comment by AlOneill** [comment]
Forgot to say: there will need to be visible focus and hover states for the icon, just as for any other link. Suggest we use the same styling as will be used on project and other icons  — will need to revisit once colour changes are in place.

**Comment by Vino-S** [comment]
Need to implement @AlOneill suggestions

**Comment by Captainkirkdawson** [comment]
I fail to see the requirement for an error report on the search results display. It creates accessibility problems as well as I cannot see how people can report a n error without looking at the full information on search detail display.

The change of the link to a button on the search detail display is good,

test3 says it is running issue_1034 but github does not contaIn such a branch. Why?

**Comment by richpomfret** [comment]
All agreed on removing buttons on summary page.

**Comment by edickens** [comment]
Am I correct that the "Report a Problem" is only for those who are registered and logged in.  The Contact Us is what is used for researchers.  There is always a Contact Us for reporting a Data Problem at the bottom of the page.  Perhaps what is requested here is a "Contact us with a Data Problem" which is more obvious in the Detailed Results screen?

**Comment by DeniseColbert** [comment]
Report a Problem is for researchers to report a discrepancy in the record (they are the ones Coords answer). Problems arise when researchers use the Contact Us link to report these issues, as they often select Data Question which doesn't include the record info, or show up in Coords list. Hence we are trying to get users to use the Report a Problem button / link.

**Comment by Captainkirkdawson** [comment]
@DeniseColbert the language being used in this story is very confusing. 
As @edickens correctly states Report a Problem is functionality available only Members. It is used for them to report issues with the way in which the website functions. It provides information on system variables to the programming team. It has existed since the initial development of FR2. It is displayed at the bottom of all pages displayed by a Member
That term should not be used for data problems or errors as it will mislead all of us.
There has always been a link to report data errors in the search results detail page. That functionality is a special component of the contact us that adds a link to the data entry in question and includes the CC. The search result details page is where such a link should be displayed (IMO). I agree that we should make this more apparent to the researcher if that is possible but lets call it what it is Report a Data Problem or Report a Data Error

**Comment by SteveBiggs** [comment]
We are agreed that the link does not stand out as well as it could:
![image](https://user-images.githubusercontent.com/25303607/35691719-24a79a96-0771-11e8-9581-94a1feb6f4e3.png)
Perhaps we just need to change the wording to something like "Click HERE to report a transcription error" and put it in bold print and/or make "HERE" a button?

**Comment by AlOneill** [comment]
Some things to bear in mind:
* Any link (in running text) will be bold (and have good contrast with page and surrounding text, once colour changes are in place.
* A button *is* the link, so any text must distinguish it from other links/nav on the page: screen-reader users can call up a list of links for a page — this will have no context. (Some of the text *could* be hidden from visual users, but screen-readers will announce both the visible *and* the invisible text.)
* Buttons with more text will be bigger, naturally.

**Comment by Captainkirkdawson** [comment]
Could I suggest that as this page is very active under other stories that this gets dealt with at the same time by @Captainkirkdawson

**Comment by benwbrum** [comment]
Kirk is in the middle of work on this chunk of code, so would like to take this on.

**Comment by Captainkirkdawson** [comment]
Code integrated into flexible_csv branch
