### ISSUE TITLE
95983213 Data Problem (Sharon Birt)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1036]
Issue reported by **Sharon Birt** at 2018-01-15 22:00:13 UTC
Time: 2018-01-15T21:59:26+00:00
Session ID: 60082cfe30fb34c3caf41a0541ca1dbe
Problem Page URL: [unknown](unknown)
Previous Page URL: [https://www.freereg.org.uk/contacts/5818639ce93790eb7fb56f10/report_error?query=5a5d22e4f493fdb03f52d4c1](https://www.freereg.org.uk/contacts/5818639ce93790eb7fb56f10/report_error?query=5a5d22e4f493fdb03f52d4c1)
Reported Issue:
Groom surname Wolcott    

![Screenshot](http://www.freereg.org.uk/uploads/contact/screenshot/5a5d246df493fdb03f52dfaa/_old_)

**Comment by DeniseColbert** [comment]
Not sure why this data problem was converted to an issue?

**Comment by SteveBiggs** [comment]
Nor am I and I can't find it in the list of contacts either. Has someone dealt with it?

**Comment by DeniseColbert** [comment]
Just seen that it has been replied to; maybe Coord clicked convert by mistake? Can be closed
