### ISSUE TITLE
97949111 Spelling of Gazetteer (Eric)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1041]
Issue reported by **REGManager** at 2018-02-07 16:05:11 UTC
Time: 2018-02-07T16:03:20+00:00
Session ID: 72255f5ec470b6f579f440a80a819657
Problem Page URL: [/places/53cbf613eca9eb03a6009ca3/edit](/places/53cbf613eca9eb03a6009ca3/edit)
Previous Page URL: [https://www.freereg.org.uk/places/53cbf613eca9eb03a6009ca3](https://www.freereg.org.uk/places/53cbf613eca9eb03a6009ca3)
Reported Issue:
In the Edit Place screen
http://www13.freereg.org.uk/uploads/feedback/screenshot/5a7b23b7f493fda05ed5ecc9/Capture.JPG    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/5a7b23b7f493fda05ed5ecc9/Capture.JPG)

**Comment by SteveBiggs** [comment]
![image](https://user-images.githubusercontent.com/25303607/35926988-7575c556-0c21-11e8-94a5-c8f988023c51.png)

**Comment by Sherlock21** [comment]
Which version are you complaining about please?
And who can now/will correct it?

**Comment by edickens** [comment]
Gazetteer is correct.

**Comment by SteveBiggs** [comment]
This has not been corrected on live site.

**Comment by Captainkirkdawson** [comment]
Have not been deployed to live still on test3
