### ISSUE TITLE
98890751 Typo 'or' should be 'of' (Stephen)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1042]
Issue reported by **SBManager** at 2018-02-18 13:39:11 UTC
Time: 2018-02-18T13:33:58+00:00
Session ID: bf92562e5f08a0e628d5d4277808ec19
Problem Page URL: [/registers/5811a440f493fdadb86b2296/edit](/registers/5811a440f493fdadb86b2296/edit)
Previous Page URL: [https://www.freereg.org.uk/registers/5811a440f493fdadb86b2296](https://www.freereg.org.uk/registers/5811a440f493fdadb86b2296)
Reported Issue:
Typo on Edit Register page - should read; 'Status of transcriptions'
http://www13.freereg.org.uk/uploads/feedback/screenshot/5a8981fff493fd507be309ee/Capture.GIF    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/5a8981fff493fd507be309ee/Capture.GIF)

**Comment by Captainkirkdawson** [comment]
Fixed in flexible_csv

**Comment by SteveBiggs** [comment]
Corrected on test2

**Comment by SteveBiggs** [comment]
Fixed in production
