### ISSUE TITLE
Wishing to use open data

### ISSUE THREAD

**Issue by RohitLearner** [FreeUKGen/FreeUKRegProductIssues#1043]
Greetings, I m Rohit. I might want to take an interest in the accompanying project 

Data Visualisation -showing our data

in GSoC 2018. To give appropriate representation, I would expect access to databases (all three ) to send finish and diverse ways to deal with handle this issue. So, kindly help in that regard. Send me a way to download all datasheets.

**Comment by Captainkirkdawson** [comment]
Personally I would have expected any  initiative would have demonstrated proposed techniques on representative samples as a first step.

**Comment by RohitLearner** [comment]
Please have a look and provide feedback as soon as possible on the following issue: 
https://waffle.io/freeukgen/myopicvicar/cards/5a67243e179fdd009ff2e102
I have already proposed an idea; kindly help me in providing right direction.
