### ISSUE TITLE
99657768 Can the text on the new "Names" report be made darker? (Staffordshire)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1044]
Issue reported by **STSCoord** at 2018-02-27 10:42:48 UTC
Time: 2018-02-27T09:48:47+00:00
Session ID: cc81637eabe9491af675ca023709ffdb
Problem Page URL: [/freereg1_csv_files/unique_names?object=59ded296f493fd76c068f12c](/freereg1_csv_files/unique_names?object=59ded296f493fd76c068f12c)
Previous Page URL: [https://www.freereg.org.uk/freereg1_csv_files/59ded296f493fd76c068f12c](https://www.freereg.org.uk/freereg1_csv_files/59ded296f493fd76c068f12c)
Reported Issue:
The text of the names is very light in comparison to the background and so it is not easily visible.

Would it also be possible to highlight the name headings by using bold or underlines?

A scrolling facility would be useful to work through the names.

Thought needs to be given to the possibility of a full marriage file (400 entries) with bride/groom/brides father/grooms father/witness 1/witness 2. Potentially 400 (entries) x 6 (named persons) x 2 (forename/surname) need to be scrolled through. This scenario is almost unworkable as the system currently stands.

What about correct 
punctuation? It should NOT be "Brides Name" but "Bride's Name" etc. "Brides" means "more than one bride", "Bride's" means "belonging to the bride"

Another useful report would be a comparison of the surname of the bride and groom with the surname of their father. Sometimes there are spelling differences in original registers but, theoretically, those differences should be picked up by the Transcriber and noted.    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/5a953628f493fd7927d53792/_old_)

**Comment by Captainkirkdawson** [comment]
But is it useful??????? It was a quickie based on a couple of comments

**Comment by Captainkirkdawson** [comment]
Text added to $1342
