### ISSUE TITLE
99740809 Zero years on email (Ali)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1045]
Issue reported by **alsibk** at 2018-02-28 09:46:49 UTC
Time: 2018-02-28T09:40:16+00:00
Session ID: f6a8ca34cd51bf4770be3f0d2ecc14ba
Problem Page URL: [/freereg1_csv_files](/freereg1_csv_files)
Previous Page URL: [https://www.freereg.org.uk/manage_counties/select_action](https://www.freereg.org.uk/manage_counties/select_action)
Reported Issue:
Zero years are no longer shown on processed email.

http://www13.freereg.org.uk/uploads/feedback/screenshot/5a967a89f493fd7927e03f95/Zero_years2.JPG    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/5a967a89f493fd7927e03f95/Zero_years2.JPG)

**Comment by Captainkirkdawson** [comment]
There is no indication that the email code for these messages has been changed in over a year.
@vino did you ever add that into the message?

**Comment by suffolkroots** [comment]
Header from "processed" email 7/2/2018
Charlie/WRYRHTBU2.CSV processed at 2018-02-07 16:22:47 +0000 with 0 errors over period 0-1786

Header from "processed email 27/2/2018
 lwilmot/WRYLINMA.CSV processed at 2018-02-27 22:56:57 +0000 with 0 errors over period 1565-1763     
This file has zero years but it is not indicated

**Comment by Captainkirkdawson** [comment]
Ah I thought you were saying the portion of the email was missing

**Comment by Captainkirkdawson** [comment]
Change pushed to test2 can @suffolkroots please test

**Comment by suffolkroots** [comment]
OK now thanks

alsibk/WRYBUWBA44.CSV processed at 2018-03-06 17:22:58 +0000 with 0 errors over period 0-1775

**Comment by Captainkirkdawson** [comment]
Deployed to production
