### ISSUE TITLE
99850830 Attachments cannot be read on FR site (Stephen)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1046]
Issue reported by **steveroland** at 2018-03-01 16:20:30 UTC
Time: 2018-03-01T16:15:22+00:00
Session ID: fca4b8af94cc7e9de4ad47796ddf098c
Problem Page URL: [/messages/5a956a11f493fd7927d71109/show_waitlist_msg](/messages/5a956a11f493fd7927d71109/show_waitlist_msg)
Previous Page URL: [https://www.freereg.org.uk/messages/userid_messages](https://www.freereg.org.uk/messages/userid_messages)
Reported Issue:
When a message with a pdf attachment is read in your messages on the FR website, it is not possible to read the attachment. Would it be possible to make it so you can?    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/5a98284ef493fd9b2c3393e3/_old_)

**Comment by edickens** [comment]
In this example the "Text attachment" doesn't do anything.
![capture](https://user-images.githubusercontent.com/8876165/37149445-e17044e2-22c5-11e8-8fde-a7d8a7c969a2.JPG)

**Comment by edickens** [comment]
It looks as if we still cannot read the attachment via the website, but the original message does have the attachment which is readable.  I also think that the sender gets a copy because I got two copies of the coordinators newsletter that I have just sent.  They both look the same so I don't know if one is the sender copy.

**Comment by edickens** [comment]
PS.  The main problem is that if someone logs in and gets this message:-
![Capture.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/542531935e93a002006d0247/125516c66e82c728ace21e0d46cb958a379791accda5fd53b652fa912a5265296b51f02e7384e671e6162351580d4bac43585f45ffac8928f0a42062c80d55b98e30063e937f03a6aa8317b500bf22894e81b4ba8345c5eb3e37aa.JPG)
and follows the link they cannot read the attachment.  So I cannot send my newsletters this way.  I will have to revert to the mailgroup system.

**Comment by Vino-S** [comment]
Ready for test in test3

**Comment by edickens** [comment]
Is it possible to give the filename of the attachment, and not just the message "click to view"?  The viewer will then know what they are about to see, and more importantly what format.
Does this work for pdf or should I test?
The help icon window is not quite wide enough and is losing the b of tab.

**Comment by Vino-S** [comment]
Hi @edickens ,
I have added filename of the attachment . It works for pdf attachment also. Also changed the tooltip for help icon.

**Comment by SteveBiggs** [comment]
Looks good. Thanks Vino.

**Comment by Vino-S** [comment]
Thanks Steve

**Comment by SteveBiggs** [comment]
Needs to be deployed to production.
