### ISSUE TITLE
GSOC Proposal 2018

### ISSUE THREAD

**Issue by RohitLearner** [FreeUKGen/FreeUKRegProductIssues#1048]
If you don't mind send us the format and sample of the required GSOC idea proposal that ought to be sent for the thoughts during the current year GSoC before 12 March 2018 with a specific end goal to get chose during the current year of GSOC.

**Comment by richpomfret** [comment]
We are currently putting together a proposal template/guidelines and will notify you once it has been completed.

**Comment by RohitLearner** [comment]
Thanks for the reply. It means a lot.
