### ISSUE TITLE
100699172 Selecting Create Image Server goes to Test2 (Eric)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1049]
Issue reported by **REGManager** at 2018-03-11 11:59:32 UTC
Time: 2018-03-11T11:53:40+00:00
Session ID: be77266e42bab157c7c57b515a88a72a
Problem Page URL: [/registers/5aa517ccf493fdb9d2c1e48b](/registers/5aa517ccf493fdb9d2c1e48b)
Previous Page URL: [https://www.freereg.org.uk/manage_counties/place_range?params=H](https://www.freereg.org.uk/manage_counties/place_range?params=H)
Reported Issue:
I'm correcting the five Errors from Bev's report and need to create the Sources.  But when I select Create Image Server, it sends me to Test2 and says I am not logged in.
http://www13.freereg.org.uk/uploads/feedback/screenshot/5aa51a24f493fdb9d2c1f615/Capture1.JPG    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/5aa51a24f493fdb9d2c1f615/Capture1.JPG)

**Comment by Captainkirkdawson** [comment]
Sorry about that I had forgotten to tell the image server to go back to production

Fixed now
