### ISSUE TITLE
100728433 Reject request for allocation gave error (Stephen)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1050]
Issue reported by **SBManager** at 2018-03-11 20:07:13 UTC
Time: 2018-03-11T20:02:48+00:00
Session ID: 206ca85a2b596684d6117a0f17886419
Problem Page URL: [/image_server_groups/5a9ec6fbf493fdbfcb98e6b0?assignment_filter_list=&image_group_filter=allocate+request](/image_server_groups/5a9ec6fbf493fdbfcb98e6b0?assignment_filter_list=&image_group_filter=allocate+request)
Previous Page URL: [https://www.freereg.org.uk/manage_counties/manage_allocate_request_image_group](https://www.freereg.org.uk/manage_counties/manage_allocate_request_image_group)
Reported Issue:
When I clicked Reject Allocate Request, I got an error page.
http://www13.freereg.org.uk/uploads/feedback/screenshot/5aa58c71f493fdb9d2c7893f/Capture.GIF    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/5aa58c71f493fdb9d2c7893f/Capture.GIF)

**Comment by Sherlock21** [comment]
IS this the one that I accidentally sent off?

if so its taken a long time to get to you hasnt it.

E

**Comment by Captainkirkdawson** [comment]
The system error was 
App 47575 stdout: Processing by ImageServerGroupsController#update as HTML
App 47575 stdout:   Parameters: {"authenticity_token"=>"22NNrzvW1+05azeH2EjapO9Id2r/PqzR05XMuO0dkr7uy9Y+S6hTQ6h7URbv5LzQlBDn/R2fHpA8noJwLFRUpg==", "type"=>"allocate reject", "id"=>"5a9ec6fbf493fdbfcb98e6b0"}
App 47575 stdout: Completed 500 Internal Server Error in 11ms (ActiveRecord: 0.3ms)
App 47575 stdout: ** [Airbrake] Success: Net::HTTPOK
App 47575 stdout: 
App 47575 stdout: NoMethodError (undefined method `redirect_to' for #<UserMailer:0x0000081d2be6a0>):
App 47575 stdout:   app/mailers/user_mailer.rb:201:in `notify_sc_allocate_request_rejection'
App 47575 stdout:   app/models/image_server_group.rb:342:in `update_image_and_group_for_put_request'
App 47575 stdout:   app/models/image_server_group.rb:362:in `update_put_request'
App 47575 stdout:   app/controllers/image_server_groups_controller.rb:234:in `update'
App 47575 stdout:

**Comment by Captainkirkdawson** [comment]
Bev has fixed on  test2 can you check @SteveBiggs

**Comment by SteveBiggs** [comment]
Tested and works fine on test2
