### ISSUE TITLE
101128536 Alternate email in Profile not accepted (Stephen)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1051]
Issue reported by **steveroland** at 2018-03-16 11:15:36 UTC
Time: 2018-03-16T11:13:25+00:00
Session ID: ed12ad1fd8308ea647b6a0220cd9194d
Problem Page URL: [/userid_details/5462b42de937907d70000747?page_name=](/userid_details/5462b42de937907d70000747?page_name=)
Previous Page URL: [https://www.freereg.org.uk/userid_details/5462b42de937907d70000747/edit](https://www.freereg.org.uk/userid_details/5462b42de937907d70000747/edit)
Reported Issue:
If I enter an alternate email address, it overwrites the main address. It's not possible to have an alternate email that's different to the main one.    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/5aaba758f493fd3ecba904bd/_old_)

**Comment by Captainkirkdawson** [comment]
Fixed

**Comment by SteveBiggs** [comment]
Tested and working now.
