### ISSUE TITLE
101204679 Possible missing records in files (Staffordshire)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1052]
Issue reported by **STSCoord** at 2018-03-17 08:24:39 UTC
Time: 2018-03-17T08:13:14+00:00
Session ID: 18bf971f811e8d4111a7809fea52bc3f
Problem Page URL: [/freereg1_csv_files/5a499421f493fd4b88454d04](/freereg1_csv_files/5a499421f493fd4b88454d04)
Previous Page URL: [https://www.freereg.org.uk/registers/5a404f1af493fd1e496fed3f](https://www.freereg.org.uk/registers/5a404f1af493fd1e496fed3f)
Reported Issue:
I have two files in STS from the same transcriber that do not download correctly.

These files are for userid Steffy. The filenames are STSRUSMA.CSV and STSRUSMA1.CSV.

STSRUSMA.CSV shows total records as 147 in FreeREG but when downloaded there are only 49 records.

STSRUSMA1.CSV shows total records as 183 in FreeREG but when downloaded there are NO records.

This is obviously a problem!

These files MAY have been in the group of "Lost files" from userid Steffy that were recovered from the attic over a year ago by Kirk.

If possible, I would like complete copies of these files as I need to check/correct them with the original parish registers.    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/5aacd0c7f493fd12b39174d3/_old_)

**Comment by SteveBiggs** [comment]
I have tried downloading the files and get the same result. There are previous versions in the attic.

**Comment by SteveBiggs** [comment]
Another coordinator has reported a similar issue:
I have 2 new transcribers who have uploaded MA files. Marvor with NBLSTNMA and Mibrewis63 with NBLWKWMA. When downloading to check I am only getting about 22 lines 4-5kbits of data. I have removed and reloaded STN and Mibrewis has reloaded his. Eric Wealleans Northumberland Coordinator

The problem appears to be related to whether the entry has witnesses - only the entries with witnesses seem to be downloading.

**Comment by Sherlock21** [comment]
I confirm the same findings a Steve above.

I also note that the Attic listing shows 4 entries within the hour for one file, and 6 for the other - Was this an attempt by the CC, to rectify the issue when he found it out? or something else.
I have downloaded the oldest copy format he Attic for each of the MA andMA1 field, and sent to the CC for his review , as requested.
My immediate thought : if this original action was an attempt to  delete some records  from each batch, then has that failed - hence  we see a 'full set' in the online view, but only get the part set from a download of the current batch?

Do you need to know  from the CC, what exactly they were trying to do?

**Comment by Sherlock21** [comment]
in reply to Steve's last post above, I have just checked one of my old marriages batches for NFK and that does not download from within View Batches, /Browse.
It too does not have any witnesses.

I tried  a later Marriage file of my own that does have witnesses, and that downloads correctly

**Comment by SteveBiggs** [comment]
Thanks Eric, I'm wondering if this has something to do with the flexible csv code just implemented?

**Comment by Sherlock21** [comment]
I don't know. In the testing that I did on that topic, i did not look for that possibility! but in any case, that has only just been uploaded to Production. whereas, in Michael's case the evidence of multiple file uploads ingot he Attic is symptomatic of someone apparently having some issues - and these were dates circa 31 Dec 2017.

**Comment by Captainkirkdawson** [comment]
Changed issue name corrupt implies something very different

Seems that @Sherlock21 is working on this so will not investigate until requested.

**Comment by Sherlock21** [comment]
I started on it, when first allocated to me in the Report from  STS . But then found that Stevebiggs had done quite a lot.
So I have stopped.

Kisk: Please take over if you would be so kind. Michael Clark confirms that he will not touch the 2 affected records until asked to.

**Comment by Captainkirkdawson** [comment]
The rewrite of the download code to support flexible_csv did not download entries for which there were no witnesses using the standard layout. Of the all the options we tested that was not one of them!!
It has been fixed.
It will have affected any marriage file download since March 7. 
@SteveBiggs @Sherlock21  you may want to let STSCoord know and support recovery from the attic

**Comment by Sherlock21** [comment]
I will go stand in the corner for the rest of the day!!!

**Comment by Captainkirkdawson** [comment]
You will find me there already so shall we go to the local together?

**Comment by Sherlock21** [comment]
Sorry, Kirk, but we are snowed in today!
We can dig each other out!

**Comment by SteveBiggs** [comment]
Tested and good now. Can be closed.
