### ISSUE TITLE
Visualization in GEDCOM

### ISSUE THREAD

**Issue by RohitLearner** [FreeUKGen/FreeUKRegProductIssues#1054]
As FreeUKGen is open source organization and widely popular. Shouldn't we provide a method of conversion from JSON to GEDCOM(file format)? GEDCOM is an open source determination for trading genealogical information between various ancestry programming. Or is there an explicit tool for conversion of JSON to GEDCOM; as visualization would be much better and effective in GEDCOM.

**Comment by PatReynolds** [comment]
It is our policy that we don't create genealogies ... we are beginning a conversation with wikitree.org to bring our data closer to their work, and vice versa (e.g. FreeCEN #387).  The work of https://fhiso.org/ may interest you, too.
