### ISSUE TITLE
102693894 Image Group name not Editable (Stephen)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1059]
Issue reported by **SBManager** at 2018-04-03 14:04:54 UTC
Time: 2018-04-03T14:01:34+00:00
Session ID: d21f5d802e5ecbff6caf0418a6eb5551
Problem Page URL: [/image_server_groups/5a9ecc40f493fdbfcb9aa8f8/edit](/image_server_groups/5a9ecc40f493fdbfcb9aa8f8/edit)
Previous Page URL: [https://www.freereg.org.uk/image_server_groups/5a9ecc40f493fdbfcb9aa8f8/edit](https://www.freereg.org.uk/image_server_groups/5a9ecc40f493fdbfcb9aa8f8/edit)
Reported Issue:
Under edit image group, the group name is an editable field but if you try to change it, an error "Image Group does not exist" is returned.
http://www13.freereg.org.uk/uploads/feedback/screenshot/5ac38a06f493fd692792251c/Capture.GIF    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/5ac38a06f493fd692792251c/Capture.GIF)

**Comment by Captainkirkdawson** [comment]
Have a suspicion that this might be a routing error on completion of the edit where the app tries to go back to the ISG that was just remained. Could you confirm if the name change you tried to make was in fact done

**Comment by bev-fc** [comment]
@Captainkirkdawson current code doesn't allow image group name change, it only allows group properties change within an existing image group

**Comment by Captainkirkdawson** [comment]
@bev-fc  when did we stop the ability to edit the Image Server Group name and why? I am sure we tested the ability to do that

**Comment by bev-fc** [comment]
@Captainkirkdawson it was not allowed since the beginning, image group name was created based on the folder name on IS during the bulk rake task, so user can create a new group name, and move images to new group, but no ability to modify existing group name

**Comment by Sherlock21** [comment]
The big snag with the methodology of : "Create another name, then move all the existing records over to that new name" is that the old name remains in the system, perhaps its "inactive" but it clutters up any subsequent listings. EG: the recent listing of Place Names that have not converted to the new Location Url. It contains about 9000 entries out of about 9500 that are there as: "inactive" but not identified as such in the public domain, and so the person trying to fix the real errors, can't see the wood for the trees when trying to sort out these errors.

With the benefit of hindsight,  my vote would be for the ability to Edit these names  and also have Delete really mean Take Out/ Remove.

**Comment by richpomfret** [comment]
Filename should not be editabe. To remove from edit display.

**Comment by Captainkirkdawson** [comment]
Change made by Bev. Deployed to test3

**Comment by edickens** [comment]
Does not work.
I tried to add "Indexes" to the end of this name:-
![capture](https://user-images.githubusercontent.com/8876165/39619957-78f86690-4f81-11e8-92bb-08a224ecdbb2.JPG)

**Comment by Captainkirkdawson** [comment]
@bev-fc  FYI

**Comment by bev-fc** [comment]
The change is to follow Rich's note "Filename should not be editabe. To remove from edit display."

**Comment by edickens** [comment]
Needs to be taken out of an edit box.  TY  E

**Comment by richpomfret** [comment]
@bev-fc Please change to plain field or text name (remove the box) so it doesn not appear like it can be edited.

**Comment by bev-fc** [comment]
done and running on test3

**Comment by richpomfret** [comment]
Thanks Bev - we shall deploy.
