### ISSUE TITLE
102852668 IG Year ending is being rejected (Eric)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1062]
Issue reported by **REGManager** at 2018-04-05 10:11:08 UTC
Time: 2018-04-05T10:05:41+00:00
Session ID: c55725a631013f8343f7fdbac0df9633
Problem Page URL: [/image_server_groups/5a9eb9d3f493fdbfcb90b1f3/edit](/image_server_groups/5a9eb9d3f493fdbfcb90b1f3/edit)
Previous Page URL: [https://www.freereg.org.uk/image_server_groups/5a9eb9d0f493fdbfcb90af78/index](https://www.freereg.org.uk/image_server_groups/5a9eb9d0f493fdbfcb90af78/index)
Reported Issue:
See the attached.
I'm putting in the year, but the year end is being rejected I think because of Error 3), but the Source does not have any years entered.
I cannot enter the years into the source as I do not know the full range of years of the source.
http://www13.freereg.org.uk/uploads/feedback/screenshot/5ac5f63cf493fd3c1e652e8c/Capture.JPG    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/5ac5f63cf493fd3c1e652e8c/Capture.JPG)

**Comment by Captainkirkdawson** [comment]
But clearly you know that the Source end date is 1798 or later so it should be fixed there. You should set the source dates first.

**Comment by richpomfret** [comment]
Closing.
