### ISSUE TITLE
105278950 Manage Syndicate button giving error message (Denise)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1067]
Issue reported by **DenGageSC** at 2018-05-03 12:09:10 UTC
Time: 2018-05-03T11:19:59+00:00
Session ID: 7cac3e856b0c06182e402ecef296ce80
Problem Page URL: [/manage_resources/new](/manage_resources/new)
Previous Page URL: [https://www.freereg.org.uk/](https://www.freereg.org.uk/)
Reported Issue:
(Denise)
http://www13.freereg.org.uk/uploads/feedback/screenshot/5aeafbe6f493fd0aa060e54c/Untitled_drawing.jpg    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/5aeafbe6f493fd0aa060e54c/Untitled_drawing.jpg)

**Comment by SteveBiggs** [comment]
EricD set Denise up as SC for a new syndicate, but when she selects Manage Syndicates, she gets this error page.

**Comment by Captainkirkdawson** [comment]
Stopped the system crash.

Had to get Denise to clear her FreeREG cookies

OK now
