### ISSUE TITLE
105784299 Why can't these Images be moved to another IG (Eric)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1068]
Issue reported by **REGManager** at 2018-05-09 08:31:39 UTC
Time: 2018-05-09T08:29:35+00:00
Session ID: 5c4cfb9367656a75d1f2b48926af4bbc
Problem Page URL: [/image_server_images/5ae44eeaf493fd0aa030125d/index](/image_server_images/5ae44eeaf493fd0aa030125d/index)
Previous Page URL: [https://www.freereg.org.uk/image_server_images/5ae44eeaf493fd0aa030125d/index](https://www.freereg.org.uk/image_server_images/5ae44eeaf493fd0aa030125d/index)
Reported Issue:
I get the attached message, but it does not tell me why.
http://www13.freereg.org.uk/uploads/feedback/screenshot/5af2b1ebf493fd61e71f7a86/Capture.JPG    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/5af2b1ebf493fd61e71f7a86/Capture.JPG)

**Comment by SteveBiggs** [comment]
It would appear that the 'Move Multiple Images' action is not working.

**Comment by edickens** [comment]
But the screen comes up for some other Image Groups?

**Comment by SteveBiggs** [comment]
The group must be in either Unallocated or Allocated status to allow images to be moved. This is in the help document.

**Comment by edickens** [comment]
So may I suggest that the message gives a reason.  If an error message comes up very rarely, then people will not remember the likely reason.

**Comment by bev-fc** [comment]
@edickens Can you help to provide the wording? I will change it accordingly.

**Comment by SteveBiggs** [comment]
I suggest:
"Only Unallocated or Allocated images can be moved"

**Comment by Captainkirkdawson** [comment]
deployed to test3

**Comment by SteveBiggs** [comment]
Tested and looks good.

**Comment by richpomfret** [comment]
To be deployed.
