### ISSUE TITLE
106043028 Data Manager Batch destroy times out and leaves incomplete status (Eric)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1069]
Priority (0 6 3 6) 15

Issue reported by **ericb** at 2018-05-12 08:23:48 UTC
Time: 2018-05-12T08:19:43+00:00
Session ID: 981ad6dab3f14ab14482cec77c59d5e1
Problem Page URL: [/manage_counties/selection?option=Review%20Specific%20Batch](/manage_counties/selection?option=Review%20Specific%20Batch)
Previous Page URL: []()
Reported Issue:
This is the feature which allows me to instantly delete a batch.  Today I keep getting the system msg: Oops something went wrong etc...

**I am working in PRODUCTION for this.**

 Please fix urgently As I have a backlog of files to delete.
eg: to be deleted are SRSWVMba10 (davejo) & STSWIGBA1 (Jonny)    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/5af6a494f493fd61e736efe4/_old_)

**Comment by Sherlock21** [comment]
Clearly no action yet, as the problem still exists today.

Please allocate to someone.

**Comment by Captainkirkdawson** [comment]
Is this still open?

**Comment by edickens** [comment]
Yes.  EricB asked me to chase it at tomorrows meeting.  It is quite urgent.

**Comment by Sherlock21** [comment]
For further info to Kirk:
some of the batches I was deleting ended with a Gateway timeout. this means  I did not get the onscreen message that the job had completed.

It is too difficult to browse through the listing to try and find a Missing batch, so I sent off the next batch for deletion.  That may have been before the timed out job had really finished. - if that is any help to you.

**Comment by Captainkirkdawson** [comment]
Well that was a vital piece of information!!!
Out of interest have you ever used this function before?

**Comment by Sherlock21** [comment]
I have used this tool on many occasions - first to test it, then 'for real'.
Sometimes for just one batch, sometimes for a few - 2 or 3.

At first testing I did get a "Gateway time out" message, but the job continued to its proper completion unless it was such a coincidence that the delete process had actually finished at about the same moment as I got the Gateway timeout message. - at the first occasion, I thought that you extended the time to whatever, before I would get a timeout message.

I have never got the present situation though, where I cannot get back to running this Delete tool having had a timeout.

**Comment by Captainkirkdawson** [comment]
You can run the action but not on the gateway timeout files!
This will take some time to deal with.

**Comment by Sherlock21** [comment]
OK, thank you Kirk.

The frozen files are therefore: 
STSWESBU2 (dbraden)
STSWIGBA1 (jonny)
STSWVMba10 (davejo).

**Comment by Captainkirkdawson** [comment]
Fix deployed to production 5 days ago. Forgot to note in this story

**Comment by Sherlock21** [comment]
Ah!. OK, I will do some now.

TY


On 27 Nov 2018, at 22:06, Kirk Dawson <notifications@github.com> wrote:

Fix deployed to production 5 days ago. Forgot to note in this story
