### ISSUE TITLE
Move forward with UCF

### ISSUE THREAD

**Issue by richpomfret** [FreeUKGen/FreeUKRegProductIssues#1073]
Progress/implement UCF AFTER reviewing possible KO effects to performance
needs #1134
needs #1178
needs #1135
needs #1259
needs #819

**Comment by Captainkirkdawson** [comment]
needs #1134
needs #1178
needs #1135
needs #1259
needs #819

**Comment by Captainkirkdawson** [comment]
Replaced with #1511
