### ISSUE TITLE
Do we collect any Personally Identifiable Information (PII)?

### ISSUE THREAD

**Issue by richpomfret** [FreeUKGen/FreeUKRegProductIssues#1076]
Priority ( 0 10 7 5) 22
To check to see if we do this at all with analytics. A common example of PII data collection is when a user information is being captured in a page URL that contains an “email= querystring” parameter. For example, it can happen on a thank-you page. Ensure that no PII is being collected and sent to Google Analytics.

**Comment by SteveBiggs** [comment]
Does transcribing a BA or MA of a living person count as collecting (and publishing) PII?

**Comment by PatReynolds** [comment]
Yes - but this and a large number of answers to this question have already been recorded.  I think Rich is specifically asking about PII in cookies.

**Comment by richpomfret** [comment]
Closing - will create a separate story for Advertising Features (cookies).
