### ISSUE TITLE
107442649 Spelling mistake (Guy van Enst)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1079]
Issue reported by **Guy van Enst** at 2018-05-28 13:10:49 UTC
Time: 2018-05-28T13:04:53+00:00
Session ID: 5d6cdb0dd915396703beccdd44a94222
Problem Page URL: []()
Previous Page URL: [https://www.freereg.org.uk/contacts](https://www.freereg.org.uk/contacts)
Reported Issue:
The search results page contains a typographic error: "Include Winesses" instead of "Include Witnesses"
http://www13.freereg.org.uk/uploads/contact/screenshot/5b0bffd9f493fd086122cf5a/Winesses.jpg    

![Screenshot](http://www.freereg.org.uk/uploads/contact/screenshot/5b0bffd9f493fd086122cf5a/Winesses.jpg)

**Comment by Captainkirkdawson** [comment]
Amazing. That has been there for 3 years.

**Comment by SteveBiggs** [comment]
Guy is very observant! :-)

**Comment by Captainkirkdawson** [comment]
Fixed and deployed to master, currently test3 and test2
