### ISSUE TITLE
Cannot log in using email address as identifier (graphiclunarkid)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#108]
Issue reported by **graphiclunarkid** at 2014-11-29 15:48:05 UTC
Time: 2014-11-29T15:44:11+00:00
Session ID: eaa1f6ee8d5d1feb99e92d133f32c63c
Problem Page URL: [/feedbacks?](/feedbacks?)
Previous Page URL: [http://test2.freereg.org.uk/manage_resources/new](http://test2.freereg.org.uk/manage_resources/new)
Reported Issue:
Reproduction steps:
1. Visit http://test2.freereg.org.uk/refinery/users/login
2. Enter email address associated with my account in the "username or email" field
3. Enter my password in the password field
4. Click "sign in" button

Expected: System logs me in and takes me to the members area

Got: "Sorry, your login or password was incorrect" (see screenshot)

Logging in with my username rather than my email address works OK.    

![Screenshot](http://test2.freereg.org.uk/tmp/carrierwave/1417276085-26560-6535/login-error.png)

**Comment by Captainkirkdawson** [comment]
System performed according to specification.

User registered richard@freeukgen.org.uk as the email address

Attempted to log in as richard.king@freeukgen.org.uk

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by edickens** [comment]
```
Richard,

  You have two UserIDs...






  E



  _____________________________________
```

Eric J Dickens
FreeREG Chairman
      On 29/11/2014 16:03, Kirk Dawson wrote:

```
System performed according to specification.


  User registered richard@freeukgen.org.uk as the email address


  Attempted to log in as richard.king@freeukgen.org.uk


  Kirk Dawson

  Fairmont Hot Springs, B.C.

  V0B 1L1


  On Sat, Nov 29, 2014 at 8:48 AM, FreeUKGenIssues
  <notifications@github.com>

  wrote:


  > Issue reported by *graphiclunarkid* at 2014-11-29 15:48:05
  UTC

  > Time: 2014-11-29T15:44:11+00:00

  > Session ID: eaa1f6ee8d5d1feb99e92d133f32c63c

  > Problem Page URL: /feedbacks?

  > Previous Page URL:
  http://test2.freereg.org.uk/manage_resources/new

  > Reported Issue:

  > Reproduction steps:

  >

  > 1. Visit http://test2.freereg.org.uk/refinery/users/login

  > 2. Enter email address associated with my account in the
  "username or

  > email" field

  > 3. Enter my password in the password field

  > 4. Click "sign in" button

  >

  > Expected: System logs me in and takes me to the members area

  >

  > Got: "Sorry, your login or password was incorrect" (see
  screenshot)

  >

  > Logging in with my username rather than my email address
  works OK.

  >

  > [image: Screenshot]

  >
```

https://camo.githubusercontent.com/7a34e59c461988fb771783772a343e3bda2a840d/687474703a2f2f74657374322e667265657265672e6f72672e756b2f746d702f63617272696572776176652f313431373237363038352d32363536302d363533352f6c6f67696e2d6572726f722e706e67
      >

```
  > —

  > Reply to this email directly or view it on GitHub

  >
  <https://github.com/FreeUKGen/FreeUKGenProductIssues/issues/108>.

  >
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by graphiclunarkid** [comment]
OK, I can log in using richard@ rather than richard.king@

However that is not my email address:

`<richard@freeukgen.org.uk>: host www.freebmd.org.uk[5.9.125.163] said: 550
    5.1.1 <richard@freeukgen.org.uk>: Recipient address rejected: User unknown
    in local recipient table (in reply to RCPT TO command)`

Does that mean my account is registered to a non-existent email address?

**Comment by Captainkirkdawson** [comment]
In answer to your question yes; it would not have happened normally as the
email would never have reached you to complete registration. But since we
currently trap all emails one of us likely forwarded it to you for
completion.

As Eric noted you have 2 registrations.

*graphiclunarkid with *richard@freeukgen.org.uk entered on 19 Nov and has
been activated as technical

and

*richard with *your preferred email address entered on 28 August as
technical but never activated.

You cannot change the email address in _graphiclunarkid_ to your preferred
one since someone else (You as richard) uses it

_Suggest the following course of action._

Either Eric or I delete the richard profile and you then change the email
address for *graphiclunarkid *to your preferred one

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by graphiclunarkid** [comment]
That would for me, Kirk. Thanks :smile:

If you let me know when you've deleted the other profile I will change the email address on the remaining one.

**Comment by Captainkirkdawson** [comment]
richard has gone you should now be able to change the other userid to that
email.

A good test.

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by graphiclunarkid** [comment]
This may be just due to my incompetence, but I can't see any way to change the email address associated with my account from within the Member Functions section!

**Comment by Captainkirkdawson** [comment]
Login, Select Profile, Select Edit and enter email

![richard5](https://cloud.githubusercontent.com/assets/2874694/5247504/2e44cbbe-7930-11e4-8d95-8756f5ed29e2.JPG)

**Comment by graphiclunarkid** [comment]
The [ Edit | send password change request | destroy ] menu-bar doesn't render for me. Here's what I get:

![no-menu-bar](https://cloud.githubusercontent.com/assets/433456/5250506/0e39f49a-798d-11e4-8697-419aab570b43.png)

**Comment by Captainkirkdawson** [comment]
You should be able to see an edit now

**Comment by graphiclunarkid** [comment]
Thanks. I've now changed my email address successfully. I also updated "has fiche reader" from "true" to "false". The form threw a permissions error on submission (copy below) however the data was saved - I logged out and back in again to check.

```
 Errno::EACCES in UseridDetailsController#update

Permission denied - (/raid-test/freereg2/users/graphiclunarkid/.uDetails, /raid-test/freereg2/users/graphiclunarkid/.uDetails.1417703616)

Rails.root: /home/apache/hosts/freereg2/MyopicVicar
Application Trace | Framework Trace | Full Trace

app/models/userid_detail.rb:154:in `rename'
app/models/userid_detail.rb:154:in `save_to_attic'
app/models/userid_detail.rb:77:in `write_userid_file'
app/controllers/userid_details_controller.rb:211:in `update'

Request

Parameters:

{"utf8"=>"✓",
 "_method"=>"put",
 "authenticity_token"=>"KbEuWfhwv+UmAp6f63P6Tt/hN4EDF7BNr+kwTOIazjk=",
 "userid_detail"=>{"person_forename"=>"Richard",
 "person_surname"=>"King",
 "email_address"=>"richard.king@freeukgen.org.uk",
 "address"=>"Norway",
 "telephone_number"=>"+4746626964",
 "fiche_reader"=>"false",
 "transcription_agreement"=>"false"},
 "commit"=>"Submit",
 "id"=>"546ce743e937909c62000001"}

Show session dump

Show env dump
Response

Headers:

None
```

**Comment by graphiclunarkid** [comment]
As discussed in sprint review, the segfault above is a known issue, so closing this story now.
