### ISSUE TITLE
107697621 IG is showing  "Unallocated" when all images are "Allocated" (Eric)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1080]
Priority (0 2 8 6) 16
Issue reported by **REGManager** at 2018-05-31 12:00:21 UTC
Time: 2018-05-31T11:57:43+00:00
Session ID: 6ce5e481c1eb2fe2fc375603365af045
Problem Page URL: [/image_server_groups/5b053235f493fd61e7895ab9/index](/image_server_groups/5b053235f493fd61e7895ab9/index)
Previous Page URL: [https://www.freereg.org.uk/image_server_images/5b054504f493fd61e78a214d/index](https://www.freereg.org.uk/image_server_images/5b054504f493fd61e78a214d/index)
Reported Issue:
See attached.
I think this has occurred when a single image was changed to Unallocated, which set this IG status, and then it was deleted, but the IG status was not recalculated.
http://www13.freereg.org.uk/uploads/feedback/screenshot/5b0fe3d5f493fd0861321f56/Capture.JPG    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/5b0fe3d5f493fd0861321f56/Capture.JPG)

**Comment by bev-fc** [comment]
@edickens I do not have access to Images on production server, can you reproduce it on test2?

**Comment by edickens** [comment]
Before I do, does Test2 have its own set of images, or does it look at the live image server?

**Comment by Captainkirkdawson** [comment]
There is only ONE image server. Production and the test servers ALL use the
same live image server so TAKE GREAT CARE in what you do

**Comment by Captainkirkdawson** [comment]
@bev-fc  there are no images on the production servers nor the test servers. They exist solely on langur the image server.
You can see what is actually on the image server through the Manage Image Server action
![capture](https://user-images.githubusercontent.com/2874694/40793169-f06ff5b6-64b8-11e8-9464-2a8f26eb7f23.JPG)

**Comment by bev-fc** [comment]
my account on production can not see those buttons.

**Comment by Captainkirkdawson** [comment]
But what about your accounts on test3 (or test2) they will access the SAME
image server and content

Kirk Dawson
5220 Riverside Drive
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by bev-fc** [comment]
Do they have the same database? That's why I asked if Eric can help to reproduce it on test2.

**Comment by Captainkirkdawson** [comment]
No they do not have the same database.


Be careful of test2 it is running the complete_flexible_csv branch

Kirk Dawson
5220 Riverside Drive
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by edickens** [comment]
Bev needs Manage Counties - Select WRY - Manage Images - Select Arksey cemetery - List image groups.  Manage image server looks at the actual images.
But to reproduce the situation in Test2 I have to delete an image from the image server.  I can do this if I download it first so that I can replace it, but Ali is working on these images.

**Comment by bev-fc** [comment]
@edickens I think I've seen the issue in code, maybe you can save that image for testing of the change.

**Comment by edickens** [comment]
Steve. Rather than using an image of Ali's, can I use one of yours?  Reference please.  It needs to be something that has been allocated.  I will replace it as soon as I've done the delete.

**Comment by richpomfret** [comment]
@edickens did you get a chance to look at this?

**Comment by edickens** [comment]
Not yet.  And is it worth a lot of effort.  I'm not sure how often it will occur.
I will have to upload an images an mess about with it and then delete it again.  Fraught with risk.

**Comment by Captainkirkdawson** [comment]
Based on last comment by EricD I suggest we close
