### ISSUE TITLE
107935675 Duplicate image groups can be created (Eric)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1081]
Issue reported by **REGManager** at 2018-06-03 06:07:55 UTC
Time: 2018-06-03T06:04:19+00:00
Session ID: b3f409bdcbe517bea1ca00e2d7bcd9ce
Problem Page URL: [/image_server_groups/5acbafd1f493fd60ff5ed97b/index](/image_server_groups/5acbafd1f493fd60ff5ed97b/index)
Previous Page URL: [https://www.freereg.org.uk/sources/5acbafd1f493fd60ff5ed97b?image_group_filter=](https://www.freereg.org.uk/sources/5acbafd1f493fd60ff5ed97b?image_group_filter=)
Reported Issue:
Although it did not seem to cause a problem, the "Create new image group" allows duplicate names within a Source to be created.  I suggest that this should not be allowed.
http://www13.freereg.org.uk/uploads/feedback/screenshot/5b1385bbf493fd086143b917/Capture.JPG    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/5b1385bbf493fd086143b917/Capture.JPG)

**Comment by Captainkirkdawson** [comment]
Solution is to add to the image_server_group.rb
validates :group_name, uniqueness: { scope: :source_id,
    message: "The group name must be unique within a source" }

**Comment by Captainkirkdawson** [comment]
Simple solution does not appear to work with mongoid 3

**Comment by Captainkirkdawson** [comment]
Examination of the code shows that pure duplicates should not be created. Identified a minor issue. Code deployed directly into master

**Comment by Captainkirkdawson** [comment]
@edickens  can you please test the bug fix on test2.

**Comment by edickens** [comment]
Should never happen, so testing not needed.  But if it happens it would cause problems.

**Comment by edickens** [comment]
Seeing above message, I will test on Master.

**Comment by Captainkirkdawson** [comment]
test needs to be done on test2

**Comment by edickens** [comment]
Yes.  Works fine.  My only suggestion is that the message to say "Already exists" should be in Red and it is reporting an error and could be mistaken for a successful creation.
