### ISSUE TITLE
108119240 Spelling in Profile (Eric)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1082]
Issue reported by **REGManager** at 2018-06-05 09:07:20 UTC
Time: 2018-06-05T09:03:56+00:00
Session ID: 6b0a85bcf585ee326a93411be12fcc9b
Problem Page URL: [/userid_details/my_own](/userid_details/my_own)
Previous Page URL: [https://www.freereg.org.uk/manage_resources/new](https://www.freereg.org.uk/manage_resources/new)
Reported Issue:
Another spelling correction needed.
http://www13.freereg.org.uk/uploads/feedback/screenshot/5b1652c8f493fd08614fb52f/Capture.JPG    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/5b1652c8f493fd08614fb52f/Capture.JPG)

**Comment by Captainkirkdawson** [comment]
Done and in test3
