### ISSUE TITLE
92691700 Data Problem (Francis Howcutt)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1083]
Issue reported by **Francis Howcutt** at 2017-12-08 19:41:40 UTC
Time: 2017-12-08T19:38:18+00:00
Session ID: ef4a12253bd95bfacf86a8a7cc320b9e
Problem Page URL: [unknown](unknown)
Previous Page URL: [https://www.freereg.org.uk/contacts/58184ab2e93790eb7f875971/report_error?query=5a2ae90533045b746c428d27](https://www.freereg.org.uk/contacts/58184ab2e93790eb7f875971/report_error?query=5a2ae90533045b746c428d27)
Reported Issue:
Mary BATTLE 
Thomas BOYSON 
Marriage 
28 Aug 1708 
Northamptonshire 
West Haddon : All Saints : Unspecified 

The surname of the bride should be CATTLE. Although the initial letter could plausibly be read as "B", when compared with the handwriting of the first letter of the neighbouring word "COUNTY" it is clear that the correct reading of the first letter of the bride's surname is "C".     

![Screenshot](http://www.freereg.org.uk/uploads/contact/screenshot/5a2aeaf4f493fd98ac5fe9ae/_old_)

**Comment by Captainkirkdawson** [comment]
This should not have been classified as an issue. How did it get here?

**Comment by SteveBiggs** [comment]
I've no idea, but it's been dealt with anyway.
