### ISSUE TITLE
Contact form submits when no comment entered

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeUKRegProductIssues#1084]
Check for valid content before submitting is permitted.

Priority 13
Economic 0
Urgency 3
Strategic 2
Cost 8

**Comment by richpomfret** [comment]
https://www.freereg.org.uk/contacts/new - to make comment 'required'.

**Comment by richpomfret** [comment]
@DeniseColbert to take a look on TEST3 to test this.
