### ISSUE TITLE
109269602 Data Problem (Catherine Bold)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1085]
Issue reported by **Catherine Bold** at 2018-06-18 16:40:02 UTC
Time: 2018-06-18T16:36:49+00:00
Session ID: 685304c02ef64ed4804962082e7e88c3
Problem Page URL: [unknown](unknown)
Previous Page URL: [https://www.freereg.org.uk/contacts/5817d386e93790eb7fa363a0/report_error?query=5b27dd93f493fdcb2e2a9bee](https://www.freereg.org.uk/contacts/5817d386e93790eb7fa363a0/report_error?query=5b27dd93f493fdcb2e2a9bee)
Reported Issue:
These two are very confusing, I am fairly sure one is the banns and one is the actual marriage?   Alison CLEOPHANE 
John CURRY	Marriage	26 May 1705	East Lothian	Athelstaneford : Parish Church : Unspecified	Row 31 
Alison CLARPHEN 
James CURREY	Marriage	27 Jun 1705	East Lothian	Gladsmuir : Gladsmuir Parish Church : Unspecified	Row 32 

could you possibly check the grooms name, I have it as John seems to odd to think there are two so similar in the same place?    

![Screenshot](http://www.freereg.org.uk/uploads/contact/screenshot/5b27e062f493fdcb2e2aa707/_old_)

**Comment by Captainkirkdawson** [comment]
Not a systems issue it is a pure data issue
