### ISSUE TITLE
103286430 Data Question (Gary Stanley)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1086]
Issue reported by **Gary Stanley** at 2018-04-10 10:40:30 UTC
Time: 2018-04-10T10:11:56+00:00
Session ID: 153dde4fdb298fec56954deb01984ecb
Problem Page URL: []()
Previous Page URL: [https://www.freereg.org.uk/contacts/new](https://www.freereg.org.uk/contacts/new)
Reported Issue:
To whom it may concern,

I run a project tracing and mapping Romany Gypsies & Travellers primarily in the UK (and USA) circa 1500-1900 (www.romaheritage.co.uk). The project uses the data you provide through FreeReg whenever it can and also likes to promote your activities also whenever we are able. I would like to inquire about the possibility that we may be able to help each other out ...

Tracing or finding Romany & Traveller records in the UK can become very difficult due to travelling patterns and the fact many of the families used alias surnames to avoid authorities. Sometimes the only way to distinguish Romany & Traveller records from others within a parish, is through unique forenames or notes on things like occupation/abode on baptism/marriage/burial records that denote the individual(s) as a Gypsy/Traveller/itinerant/sojourner/etc.

Currently the FreeReg does not let the public search these fields (occupations/abodes on records such as baptisms), but I wanted to ask whether internally a search like this had the potential to be carried out?
Supplying a list of search terms and having a list or spreadsheet of results returned from a dataset as large as yours, has the potential to open up the field of Romany & Traveller research overnight.

If FreeGenealogy were to perhaps consider doing something like this, our project would be more than happy to significantly increase it's promotion of the FreeGenealogy suite of websites through our own website and at events we attend in the real world or in any other way that would be helpful to you.

We would be grateful for your consideration over this matter and hopefully look forward to perhaps hearing from you in the near future.

Kind regards,

Gary Stanley
Project lead - ROMANI: An Anglo-American Heritage Project
(www.romaheritage.co.uk)    

![Screenshot](http://www.freereg.org.uk/uploads/contact/screenshot/5acc949ef493fd610958042b/_old_)

**Comment by richpomfret** [comment]
Pat to reply.

**Comment by PatReynolds** [comment]
Replied 3/7/2018.
