### ISSUE TITLE
110019136 Image Group images uploading problem (Eric)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1087]
Issue reported by **REGManager** at 2018-06-27 08:52:16 UTC
Time: 2018-06-27T08:47:04+00:00
Session ID: 747dbe48b073a16d784a8ab011789c45
Problem Page URL: [/image_server_groups/5a9ed09ff493fdbfcb9c4a8d/index](/image_server_groups/5a9ed09ff493fdbfcb9c4a8d/index)
Previous Page URL: [https://www.freereg.org.uk/image_server_groups/5a9ed09ff493fdbfcb9c4a8d/index](https://www.freereg.org.uk/image_server_groups/5a9ed09ff493fdbfcb9c4a8d/index)
Reported Issue:
I created a new image group, not knowing that this group of images was already there.  When I uploaded the images there was no reported error, but the images would already have been there.  The result is a new IG with two blank images which I cannot delete and so I cannot delete the IG.
So problems:-
- Duplicate images not being reported.
- Images being created with no name
- These no name images cannot be deleted.
See attached
http://www13.freereg.org.uk/uploads/feedback/screenshot/5b335040f493fd8c6acc5f80/Capture.JPG    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/5b335040f493fd8c6acc5f80/Capture.JPG)

**Comment by richpomfret** [comment]
We need to find a way to duplicate this. Also need to remove the examples Eric has given.

**Comment by PatReynolds** [comment]
@edickens to investigate

**Comment by edickens** [comment]
Seems to be fixed.  They are no blank images there now.
