### ISSUE TITLE
110032834 General Comment - Suggestion for Search URL Format (Paul Wright)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1088]
Issue reported by **Paul Wright** at 2018-06-27 12:40:34 UTC
Time: 2018-06-27T12:35:41+00:00
Session ID: f1479ef341238b7e6e745d6a9bf11c48
Problem Page URL: []()
Previous Page URL: [https://www.freereg.org.uk/contacts/new](https://www.freereg.org.uk/contacts/new)
Reported Issue:
Would it be possible for you to refactor your system so that there is a "permalink" for each record? I use FamilySearch, and have found older links back to your database in this format:
http://www.freereg.org.uk/cgi/SearchResults.pl?RecordType=Baptisms&RecordID=4399839

This went back to your main page. After searching manually I got this link for the same record:
https://www.freereg.org.uk/search_records/58182e00e93790eca39cbc52?search_id=5b33837ef493fd8c6fac04d6&ucf=false

I am not sure whether or not thie latter is a permalink, but for good future-proofing and working well with other geneaology sites, it would be really good to have a system that gave a sensible URL for each record, ideally somewhat human readable. For example, FamilySearch use a seven alphanumeric index for each peron's record, so the record can always be accessed using a URL like this:
https://www.familysearch.org/tree/person/details/L86H-489

I realise that this may involve a major change to your system so might take some time to do, but I would encourage it as it will make your system much more robust and usable.

Best wishes
Paul Wright    

![Screenshot](http://www.freereg.org.uk/uploads/contact/screenshot/5b3385c2f493fd8c6acd1c42/_old_)

**Comment by edickens** [comment]
Paul has replied:-
Hi

I got the old link from an old entry on FamilySearch.

It's good to know the current links are permanent. The part "?search_id=" made me think it referred to my specific search rather than the result.

But what is a link to us doing in FamilySearch?

**Comment by PatReynolds** [comment]
Is "But what is a link to us doing in FamilySearch?" Paul's comment or yours?

Can you ask him to give us the url of the page where the link is, then we will see why it is there.

Can you warn Paul that the current URLs are not permanent, and limited to a single server - if you get logged on to a different server, they don't work.  Please reassure him that permanent urls, including a format which gives data, as he asked, will soon be available.

**Comment by edickens** [comment]
Yes, that is my comment.  I have emailed Paul for more information.

**Comment by edickens** [comment]
Paul says:-

In FamilySearch, people can create source records manually and add links to external sites. That is what happened here: somebody found the record on your site and manually entered the link into FamilySearch. I have never come across a link to FreeReg in the proper FamilySearch record finder. I assume your two websites do not yet have a sharing arrangement in place.

**Comment by richpomfret** [comment]
Already working on this .
