### ISSUE TITLE
Place names with Not Approved but no Batch to be found (ericb)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#109]
Issue reported by **ericb** at 2014-11-30 09:51:10 UTC
Time: 2014-11-30T09:42:41+00:00
Session ID: 40ca4a1aa955b58a3d2ac080298853d9
Problem Page URL: [/places/53ce3902eca9ebd90c5342d9](/places/53ce3902eca9ebd90c5342d9)
Previous Page URL: [http://test2.freereg.org.uk/places](http://test2.freereg.org.uk/places)
Reported Issue:
This issue reported to me by Mary ( CC for CAM).
In CAM there are 2 place names in the Master Places listing - Balsham and also Little Abington which both show Pr after their name but I can't find a Batch associated, with gives rise to the Not Approved warning.

How did they get here?
How do we remove them? ( usually this would be by correcting the Batch and re uploading)
At the recent total reload 11 Nov, was not everything (except proper Place Names) removed?
 Mary's email attached. Ignore the bit about Gamblingay.    

![Screenshot](http://test2.freereg.org.uk/tmp/carrierwave/1417341070-40031-3467/CAM_not_Approved_Places.txt)

**Comment by Captainkirkdawson** [comment]
No the Places collection was not cleared and then rebuilt because to do
that could have undone a great deal of your work.
Will consider the rest later.

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Sherlock21** [comment]
Ahhh

I had expected that the Not Approved place names lines came in straight from the uploading file and so were only there so long as the uploading file was there. - Rather than becoming part of the Place names table as such.

So if the offending file is no longer there - as appears because its not shown do i just Destroy that place and its all over?

Would be OK if the feature for Crete a new place worked,- issues about GridRef or / and lat /lon not being accepted
on #30  which was for Only works with Lat/ Lon and not GridREf ; Then another I can't just find which says it won't now work with GridREf either.

E

**Comment by edickens** [comment]
```
If the "Not approved" was created in
  the July update, then the FR1 file corrected, this Place will
  still be there in FR2 with no files.  I am suggesting that at the
  final update all "Not approved" are deleted prior to the
  replacement of the transcriptions, thereby leaving "Not approved"
  created for any that still have batches that do not match.
  _____________________________________
```

Eric J Dickens
FreeREG Chairman
      On 30/11/2014 15:20, Kirk Dawson wrote:

```
No the Places collection was not cleared and then
  rebuilt because to do

  that could have undone a great deal of your work.

  Will consider the rest later.


  Kirk Dawson

  Fairmont Hot Springs, B.C.

  V0B 1L1


  On Sun, Nov 30, 2014 at 2:51 AM, FreeUKGenIssues
  <notifications@github.com>

  wrote:


  > Issue reported by *ericb* at 2014-11-30 09:51:10 UTC

  > Time: 2014-11-30T09:42:41+00:00

  > Session ID: 40ca4a1aa955b58a3d2ac080298853d9

  > Problem Page URL: /places/53ce3902eca9ebd90c5342d9

  > Previous Page URL: http://test2.freereg.org.uk/places

  > Reported Issue:

  > This issue reported to me by Mary ( CC for CAM).

  > In CAM there are 2 place names in the Master Places listing -
  Balsham and

  > also Little Abington which both show Pr after their name but
  I can't find a

  > Batch associated, with gives rise to the Not Approved
  warning.

  >

  > How did they get here?

  > How do we remove them? ( usually this would be by correcting
  the Batch and

  > re uploading)

  > At the recent total reload 11 Nov, was not everything (except
  proper Place

  > Names) removed?

  > Mary's email attached. Ignore the bit about Gamblingay.

  >

  > [image: Screenshot]

  >
```

https://camo.githubusercontent.com/600c8dbd0e0dd335b1d408e6d05a759bb0fd3d66/687474703a2f2f74657374322e667265657265672e6f72672e756b2f746d702f63617272696572776176652f313431373334313037302d34303033312d333436372f43414d5f6e6f745f417070726f7665645f506c616365732e747874
      >

```
  > —

  > Reply to this email directly or view it on GitHub

  >
  <https://github.com/FreeUKGen/FreeUKGenProductIssues/issues/109>.

  >
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by Captainkirkdawson** [comment]
Since the erroneous place names have no records and were simply left over from the earlier status they may be deleted. I did this.
