### ISSUE TITLE
www.freereg.org.uk/cms/refinery/users/login has Adsense problem

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeUKRegProductIssues#1090]
Adsense has placed a restriction on this page 28/6/2018

**Comment by richpomfret** [comment]
@PatReynolds to clarify the issue with Adsense. @vino to investigate potential code issue.

**Comment by richpomfret** [comment]
To also check if we have the same issue on FC2.

**Comment by PatReynolds** [comment]
Requested review of page 19/7/2018.  No issue on FC2.

**Comment by smrr723** [comment]
Resolved on production by Vino - needs confirmation/testing @PatReynolds  (can't move card in waffle)

**Comment by PatReynolds** [comment]
Have email from Google Adsense saying it is now fine.
