### ISSUE TITLE
110548619 Manage County, List of counties to select, is not sorted (Eric)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1093]
Issue reported by **REGManager** at 2018-07-03 11:56:59 UTC
Time: 2018-07-03T11:52:36+00:00
Session ID: d93e0dc4804a2b50ac24f2e024f54028
Problem Page URL: [/manage_counties/new](/manage_counties/new)
Previous Page URL: [https://www.freereg.org.uk/manage_resources/new](https://www.freereg.org.uk/manage_resources/new)
Reported Issue:
I have changed CC for DOR and the Channel Islands, but they are not in sequence any more.
http://www13.freereg.org.uk/uploads/feedback/screenshot/5b3b648bf493fd1e4b8ca112/Capture.JPG    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/5b3b648bf493fd1e4b8ca112/Capture.JPG)

**Comment by edickens** [comment]
Perhaps I have misunderstood.  As SysAdmin, my CC counties come first, then other counties.  But they are also sorted with Northern Ireland before England.
If this is the case, then no need to do anything as I now know were to find DOR and IOW.

**Comment by Sherlock21** [comment]
When I ( DM Profile) look up any County, or Syndicate from my Manage County or Manage Syndicate,  they all come listed by code in alphabetical order. So DOR comes in the D's. and CI comes in the C's.
BUT Chanel Islands insofar as Place Names management is concerned, is part of CORNWALL.

**Comment by richpomfret** [comment]
It's a 'feature'. ;)
