### ISSUE TITLE
110562084 Destroying zero years entries does not Lock batch (Eric)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1094]
Priority (0 3 8 6) 17
Issue reported by **REGManager** at 2018-07-03 15:41:24 UTC
Time: 2018-07-03T15:39:03+00:00
Session ID: 2bcf91e9fd086d46e666a4c32af6131e
Problem Page URL: [/freereg1_csv_files/5463bc4de937904abb336256/zero_year](/freereg1_csv_files/5463bc4de937904abb336256/zero_year)
Previous Page URL: [https://www.freereg.org.uk/freereg1_csv_files/5463bc4de937904abb336256](https://www.freereg.org.uk/freereg1_csv_files/5463bc4de937904abb336256)
Reported Issue:
If I destroy a blank entry the batch is not locked.  As a result, if the transcriber uploads it the blank entry will be reinstated and the zero year reappear.
Editing an entry does lock the batch.    
depends on #1581 
![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/5b3b9924f493fd96f896eac6/_old_)

**Comment by Captainkirkdawson** [comment]
@edickens  Lock added on entry deletion. Deployed to test3 for testing

**Comment by edickens** [comment]
Wrong Eric.  Perhaps we need to somehow get EricB and EricD in the subject.

**Comment by Sherlock21** [comment]
Surely, any edit online of a record should lock that record - including removing any rows for whatever cause?
Then the need  for the Transcriber to download the whole file follows the present process.

So I agree with the title of this story - and I don't remember creating it!

**Comment by Captainkirkdawson** [comment]
I got the correct Eric see the description, Issue reported by REGManager at 2018-07-03 15:41:24 UTC

Any deletion of an entry locks the batch just like any edit.

Regardless it needs testing.

**Comment by edickens** [comment]
I must have passed it on from an email that I received.
