### ISSUE TITLE
110562321 Reprocess Batch should work for locked batches (Eric)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1095]
Issue reported by **REGManager** at 2018-07-03 15:45:21 UTC
Time: 2018-07-03T15:42:42+00:00
Session ID: 2bcf91e9fd086d46e666a4c32af6131e
Problem Page URL: [/freereg1_csv_files/5463bc4de937904abb336256](/freereg1_csv_files/5463bc4de937904abb336256)
Previous Page URL: [https://www.freereg.org.uk/freereg1_csv_files/5463bc4de937904abb336256/zero_year](https://www.freereg.org.uk/freereg1_csv_files/5463bc4de937904abb336256/zero_year)
Reported Issue:
Reprocessing does not change anything in the batch, so it does not matter if the batch is locked or not.
Now it is time consuming to, having edited an entry, unlock the batch, reprocess the batch and then lock it again.    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/5b3b9a11f493fd96f896f312/_old_)

**Comment by richpomfret** [comment]
Technically not possible.
