### ISSUE TITLE
Check for Orphan entries

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeUKRegProductIssues#1096]
Priority (0 6 3 6) 15
See #1492 for how this problem was identified.

**Comment by Captainkirkdawson** [comment]
Code written and running on test3

**Comment by Captainkirkdawson** [comment]
With code deployed it can now be run on production

**Comment by Captainkirkdawson** [comment]
Running on production

**Comment by Sherlock21** [comment]
can you please advise me how and when this runs.
Any user action needed either as a once off now to catch all the backlog, or in the future?

**Comment by Captainkirkdawson** [comment]
This is a system manager tool. 
They run it when they see that there is a difference in he number of entries and search records. Something that should not occur/
It is not a member function.
It takes 2 days to complete.

**Comment by Sherlock21** [comment]
Thank You.
I thought it would be a long job to run, so wondered how it fitted in.

**Comment by Captainkirkdawson** [comment]
As noted 4 comments above it is currently running

**Comment by Captainkirkdawson** [comment]
116,000 orphans detected and removed.
