### ISSUE TITLE
GDPR Cookie consent switch needed

### ISSUE THREAD

**Issue by richpomfret** [FreeUKGen/FreeUKRegProductIssues#1097]
The current 'third party' toggle to be replaced with specific on/off switches for personalised advertising (targetting) and analytics.

**Comment by PatReynolds** [comment]
Now live.  I still think it would be nice to have a 'go back' button at the bottom, but that can be raised as a separate issue.

**Comment by PatReynolds** [comment]
Personalised adverts switched back on 9am 12/7. Income recovering.
