### ISSUE TITLE
17 Completing the Citation User Interaction layer with styling and accessibility enhancements NEEDED BY 1374

### ISSUE THREAD

**Issue by richpomfret** [FreeUKGen/FreeUKRegProductIssues#1098]
Priority ( 2 3 5 7)  17
Phase 3 of the citation generator feature: Completing the User Interaction layer with styling and accessibility enhancements. - see GSOC proposal for further info.

**Comment by Captainkirkdawson** [comment]
Hope someone else understands what this means for the FreeREG app, I for one am totally at a loss.

**Comment by PatReynolds** [comment]
@Rich - Ben is giving Sudaraka the location of the permanent urls today - can you ask Sudaraka to do anything remaining from this issue, please?

**Comment by Captainkirkdawson** [comment]
I remain totally unclear what is required. We have the citation which apparently follows the standards associated with the specific citation.
What styling or accessibility needs to be added as the citation is to be copied by the researcher and pasted in whatever system they use.

**Comment by Captainkirkdawson** [comment]
@PatReynolds having read the original specs documentation I see no need for further UI refinement suggest we close

**Comment by benwbrum** [comment]
@PatReynolds to review and probably close after testing citation generator in #1374.
