### ISSUE TITLE
Implement donate page

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#110]
As a researcher I want to see instructions on how to donate money to the project so I can send them some dosh.

ACCEPTANCE CRITERIA
- Paste in the HTML from the bank on the donate page

**Comment by Captainkirkdawson** [comment]
Don"t have a Donate link yet

**Comment by graphiclunarkid** [comment]
Awaiting details from the bank...

**Comment by Captainkirkdawson** [comment]
The dummy page if there waiting for text to be written in Refinery
