### ISSUE TITLE
111768646 Data Problem (Andy Phillips)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1101]
Priority (0 6 5 5) 16

Issue reported by **Andy Phillips** at 2018-07-17 14:50:46 UTC
Time: 2018-07-17T14:47:51+00:00
Session ID: e29d85f47e8463657cb3a5729e070b07
Problem Page URL: [unknown](unknown)
Previous Page URL: [https://www.freereg.org.uk/contacts/5b4c5c74f493fdb1c246a148/report_error?query=5b4e019033045b42d99357e3](https://www.freereg.org.uk/contacts/5b4c5c74f493fdb1c246a148/report_error?query=5b4e019033045b42d99357e3)
Reported Issue:
An error in transcription was corrected by me yesterday. The revised version appears in Search but the County (Somerset) is missing. Extract, with adjacent entries, from .csv file is
SOM,Midsomer Norton,Methodist PR,152,"",1862,"","",Thos Ha*s,Emily,SMITH,"",Midsomer Norton,"","","",""
SOM,Midsomer Norton,Methodist PR,153,03 Apr 1863,21 Jul 1863,Agnes Anne,F,Charles,Rhoda,SMITH,"",Mid Norton,"","","",""
SOM,Midsomer Norton,Methodist PR,154,15 Apr 1863,Jan 1863,John Seym*,M,John,Martha,TREASURE,"",Bishop Sutton,"","","",""    

![Screenshot](http://www.freereg.org.uk/uploads/contact/screenshot/5b4e0246f493fd85ed0f3e42/_old_)

**Comment by Captainkirkdawson** [comment]
This report  has no information on how "An error in transcription was corrected by me" was done. Nor is there any information on the specific record in question. This makes it impossible to research.

**Comment by richpomfret** [comment]
Need more info before we can find out what happened.

**Comment by SteveBiggs** [comment]
Details from Andy Phillips:

I have come across a problem as a result of correcting transcription errors.

Yesterday the same thing happened on another correction but I see no point in reporting it.

In both instances the file was too big to correct the entry by reloading the batch so I had to go into the Batch, scroll down to the required entry, correct and submit followed by downloading the whole file and then unlocking it.

On subsequent Search no results are found unless the specific parish is selected. However then the County is not displayed.

The first record, in SOMMSMBA1, displays
Agnes Anne SMITH	Baptism	21 Jul 1863		Midsomer Norton : Methodist : Parish Register	Row 1

and the second, in SOMTIMBA,
William Henry DUDDEN	Baptism	19 Feb 1828		Timsbury : St Mary : Parish Register	Row 1

All other records in these files continue to be found, correctly, in non parish specific searches with the County names displayed.

Am I doing something wrong or is there a system issue?

**Comment by SteveBiggs** [comment]
From Eric Booker:

!) Is it still the case that online edits require some of the processing to be done in an overnight batch job, before the record concerned actually features in the  search results?

Or is that no longer the case with anything - i.e. everything gets updated online at the time?

I have tried a search  for Agnes myself and agree with Andy - and I see nothing wrong in the batch concerned  either with the Agnes Anne Smith example - I did not bother to check the other one given that result.

If online editing is fully processed at the one go, as it were, then this is clearely a major issue isn't it.  So can you set off a suitablly actioned snag report please?


2) I cannot add anything to Andy’s other point about his previous report going nowhere - I might have raised a Bug Report at that  time - but as I can't any longer find my own issues within Github, I cant help on that one.

**Comment by SteveBiggs** [comment]
From the Somerset coordinator, Jackie:

Eric B suggested that we try REPROCESS (without uploading for a second time) which seem to work.

I was wondering that it might be because these were large files,that  they had been insufficiently processed after the edit. But I now see that although SOMTIMBA  is 5k+, the other SOMMSMBA1 is only 1187.

Today I've been attempting to deal with the Zero Years in SOMTIMBA, but I had several error messages. 

Also, the Reply to researcher option for SOMTIMBA in the Contact on the list wouldn't send the email either, so there is something odd about that file still. I've asked Eric B to look at it initially. 

I haven't got very far with the other contacts, having two email addresses is an unwanted complication at the moment.

**Comment by Captainkirkdawson** [comment]
Cannot duplicate
![Capture.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53ecbbfc82b317f7d9ad93dc/125516c66e82c728ace21e0d46cb958a379791accda5fd53b652fa912a5265296b51f02e7384e671e6162351580d4bac43585f45ffac8928f0a42062c80d55b98e30063e937f03a6aa801eb500bf238e4d87b1be8d4ec9ef3837aa.PNG)

**Comment by Captainkirkdawson** [comment]
I suspected that someone may have subsequently done something to muddy the trail.
So I went to test3 and tried to follow along with what Andy had done with the specific record. 
As a result I have detected that there MAY be an issue with the on line edit. This post does not confirm that but indicates that additional testing and research is warranted,

**Comment by Captainkirkdawson** [comment]
Code has been developed to address a possible cause for these symptoms

**Comment by Captainkirkdawson** [comment]
@Sherlock21 have deployed to test 3 needs your attention and testing. It addresses  #1566 and #1568 as well

**Comment by Sherlock21** [comment]
Just by chance, I already had a file WRYAAtestMa55.csv in T3 - it contains 30 records with one having a zero years error there already.
The date WAS 13 Jun 15*5
I corrected this online, to  13 Jun 1515 - for want of making any 4 digit year.
Hit SUBMIT and Fatal Error warning: OPPSS Somethings gone wrong etc in Red.

Backed out and stopped the test.

**Comment by Captainkirkdawson** [comment]
@Sherlock21 Forgot we could not update the search date because its part of the shard key. Work around submitted to test3. Please retest

**Comment by Sherlock21** [comment]
Cant do any until friday 7th - We have house visitors all week now.

Sorry.

Eric
On 4 Sep 2018, at 00:05, Kirk Dawson <notifications@github.com> wrote:

@Sherlock21 Forgot we could not update the search date because its part of the shard key. Work around submitted to test3. Please retest

**Comment by Captainkirkdawson** [comment]
@SteveBiggs emailed me with

Have started testing.

I uploaded a file (SSXARUBU.CSV) using flex csv with a death date and no burial date - it shows as a zero start year (not good).

However, a search for John Gardiner, 1875 in Sussex does find him.

**Comment by Captainkirkdawson** [comment]
Together with a second message

There's something really strange with this batch. The first entry is flagging as a zero year:
![image.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53ecbbfc82b317f7d9ad93dc/125516c66e82c728ace21e0d46e1999b2487c1e5cdf9ad4cae58f3806b1c65267a01a02a75dcba7ce7122c035a5f4cac41595c11fcfadf39baa47e21d40854b088270a36d43703adbf881eba02bc228f4b84bebd884dc0fa70.png)
but it has a valid burial date. Any idea why?

**Comment by Captainkirkdawson** [comment]
The upload of the original file had a first line
SSX,Arundel,St Nicholas,PR,1,04 Jan 18_5,,Daniel,CHATFIELD,,,,,,,,,83,,,,,,,,8-1-5-3,,
ie it has a UCF date. These create a zero year.
There was an online update 14 minutes later that updated the record to 04 Jan 1846 which is what the record now shows.
The issue is that a correction of a zero year record does not update the year field. Issue raised.

**Comment by Captainkirkdawson** [comment]
@SteveBiggs please continue

**Comment by SteveBiggs** [comment]
Thanks @Captainkirkdawson. I'm out tonight but will try to do some testing tomorrow (Friday is usually slightly quieter at work!)

**Comment by Captainkirkdawson** [comment]
@SteveBiggs @edickens @Sherlock21  I believe I have fixed the zero year issue.
In addition to testing that aspect we do need a full test of upload replace both old style and new fields. This was a significant rewrite
I have added a new field in the entry to show its date of processing. THIS WILL NOT BE RETROACTIVE but seen only in newly processed entries

**Comment by Sherlock21** [comment]
I have created a new file [ericb.TSTZEROBA1.csv] in t3.
It contains 6 records of which 1 contains a year 5 Jul * and other is completely missing.
Uploaded OK,
Looking at My Batches, the batch is listed BUT  does NOT show Zero Year flags:-

![zeroyears1](https://user-images.githubusercontent.com/9368704/45207922-3c7ab480-b281-11e8-98dd-91b1ce9a288a.jpg)

**Comment by Sherlock21** [comment]
Continuing from above item and enclosed image:-
In Show file ( from My Batches) the 2 test records are not shown as Zero Years.
But on looking at the date detail, the record is listed, with the part date correctly as Baptism date. and the record with no date is also listed correctly ( with no date of course.)

the other  4 records which have proper dates are listed correctly

I will not try and edit these so as not to mess the evidence.

**Comment by SteveBiggs** [comment]
I have been doing some uploading, online editing and replacing files today in test3 and searching resulting changed records - all looks Ok to me so far.

**Comment by Captainkirkdawson** [comment]
@Sherlock21 the problem with you file is the last record with both date fields empty. I will need to review. Please leave as is for time being

**Comment by Sherlock21** [comment]
Kirk
OK. I did this specifically to see what it would do with 2 missing dates.
AsI did not get a  system email I thought something wrong.

What's the solution: bounce it at the time of uploading? so at least the uploader can fix it them.

**Comment by Captainkirkdawson** [comment]
@Sherlock21 The problem has been resolved

**Comment by Captainkirkdawson** [comment]
Deployed to master and to colobus

**Comment by Sherlock21** [comment]
Continuing to test this story.
Using a new baptism file, Edit online, add a Birth Date of 17 Nov 1653 and set the Baptism date to Day and Month only. change the child's name to John Martin Ellis.
Search on Martin Ellis in date  range 1650 to 1655.
Result returned is correct as it shows date of event as the Baptism part date and the right record.

**Comment by Sherlock21** [comment]
Continuing to test this story.
Using a new baptism file, Edit online, add a Birth Date of 17 Nov 1653 and set the Baptism date to Day and Month only. change the child's name to John Martin Ellis.
Search on Martin Ellis in date  range 1650 to 1655.
Result returned is correct as it shows date of event as the Baptism part date and the right record.

**Comment by Sherlock21** [comment]
Continuing testing this story. There is a BUG revealed here.

Using a flex file, I uploaded DEVflexiTestMA10.csv. that was OK.
then added 3 ( proper ddmmmyyyy format) Contract dates into my file and Reloaded. again OK
Then added in a contact date of 1950? and reloaded that. It uploaded OK. the email say no errors, but the row that contains this Contract date of 1950? does NOT show any value in Contract date. - rest of that row is OK. 
Timing of this reload was 08:51 BST Tuesday 11 Sep 2018

**Comment by Sherlock21** [comment]
Testing of Burial records using a flexi file.
I have a small file of 5 records
All have burial dates and 2 also have death dates of some years earlier!
Search for a burial in the exact year = Correct result
Search for burial in the year of the death = correct result 
Online Edit to change the death date.
Search for  burial in this new death year = correct result
Reloaded the original file to take out the Death years and reset burials to original values.
Search for known Burials = Correct result.
Downloaded the Batch as now is  & compared with my file = Correct - all my online edits are reversed = correct result.

I consider this test of coding of the functionality of Death Dates in a burial file is satisfactory.
