### ISSUE TITLE
Audit of Coords

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeUKRegProductIssues#1102]
Eric is concerned that out of the (already small number of) active counties, some coordinators aren't responding to emails, particularly those from the registration of new transcribers.

Suggest an audit of Coords to establish those with no data, those with data (how much), and those inactive for other reasons.

Communication to be sent via email in case ISP's are blocking FR messages.

**Comment by edickens** [comment]
I have had feedback from most coordinators.  I think we do not need to chase them any more.
The facility to reply within the message system will show which data messages are not being answered.

**Comment by PatReynolds** [comment]
Added sources tag because may reveal images needing transcription

**Comment by PatReynolds** [comment]
Is this now resolved @edickens ?  If so, please close.

**Comment by edickens** [comment]
Yes, I have been in contact with most Coordinators and will be again soon when I get those with images, which are the important ones, to get the image availability uptodate.
But Denise asked if they are answering Data questions and replying to new transcribers.  This I think should be an ongoing monitoring by checking on replies.  However, until the Contact system is upgraded to create and log replies, I don't think we can do this.
