### ISSUE TITLE
Place name of sender in 'From' field in FR message system

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeUKRegProductIssues#1103]
To improve deliverability.

Also, senders to be reminded to sign off with their full name and role / FreeREG Exec

**Comment by richpomfret** [comment]
@DeniseColbert we can do the latter but not the former.

**Comment by DeniseColbert** [comment]
We can't place name of sender in messages? That's too bad, it could really help with avoiding the spam filter.

Can we have a pop-up, or a highlighted line of text on the message page e.g.

![image](https://user-images.githubusercontent.com/19173257/44105342-4bc6393c-9fe9-11e8-881c-0e4d54b452fb.png)

(sorry about the scruffy snip!)

**Comment by richpomfret** [comment]
@DeniseColbert Yes we can include a name of sender within a 'from field' which will appear in the email/message when sent. The second issue (after revisiting it) should be possible too. Nothing wrong with the scruffy snip, although what about an auto generated signature within the message? As we have two tasks here, they should become subtasks to a 'improve deliverability' epic story.

**Comment by DeniseColbert** [comment]
I've done that (hope it's right!) so closing.
