### ISSUE TITLE
112370806 RED failure message when sending to Syndicate members (Eric)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1104]
requires #1516 

Issue reported by **REGManager** at 2018-07-24 14:06:46 UTC
Time: 2018-07-24T14:03:26+00:00
Session ID: 13b51beab775fa14ba76233aad296b21
Problem Page URL: [/messages/5b4765c5f493fdb1c229e2e1/send_message](/messages/5b4765c5f493fdb1c229e2e1/send_message)
Previous Page URL: [https://www.freereg.org.uk/messages/5b4765c5f493fdb1c229e2e1](https://www.freereg.org.uk/messages/5b4765c5f493fdb1c229e2e1)
Reported Issue:
The RED "Something has gone wrong"  message came up when sending this message.
http://www13.freereg.org.uk/uploads/feedback/screenshot/5b573276f493fd6b3e82fa16/Capture1.JPG    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/5b573276f493fd6b3e82fa16/Capture1.JPG)

**Comment by richpomfret** [comment]
@edickens Try and duplicate if you can.

**Comment by edickens** [comment]
Duplicated at 08:35 31/7/18 BST.
Regmanager is also SC of Dorset (and other counties) as I didn't want to created a new UserID just for DOR.

**Comment by richpomfret** [comment]
This was caused by #1516

**Comment by Captainkirkdawson** [comment]
You must select the Members of Syndicate option
Test added and deployed to test3
