### ISSUE TITLE
112628440 Wrong start-end dates entered (Doreen)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1106]
Issue reported by **deo123** at 2018-07-27 13:40:40 UTC
Time: 2018-07-27T13:36:16+00:00
Session ID: f001eb1931fb587e3092c525eb21b8ab
Problem Page URL: [/image_server_groups/5a9ebb47f493fdbfcb929498/index](/image_server_groups/5a9ebb47f493fdbfcb929498/index)
Previous Page URL: [https://www.freereg.org.uk/sources/5a9ebb47f493fdbfcb929498?image_group_filter=](https://www.freereg.org.uk/sources/5a9ebb47f493fdbfcb929498?image_group_filter=)
Reported Issue:
Hi,

yes, it is me again.
Looks like the wrong start/End Dates have been entered, see attachement.
You have included the Piece No which is found on all Non-Conformist registers. Also you may have something like 1813-1837-vol1
Regards Doreen
http://www13.freereg.org.uk/uploads/feedback/screenshot/5b5b20d8f493fd75514e2209/wrond_start-end_dates_entered.JPG    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/5b5b20d8f493fd75514e2209/wrond_start-end_dates_entered.JPG)

**Comment by richpomfret** [comment]
No action needed here other than replying.

**Comment by edickens** [comment]
I have replied to Doreen.
