### ISSUE TITLE
112781300 No Remove option for a message (Eric)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1107]
Priority (0 3 8 6) 17
Issue reported by **REGManager** at 2018-07-29 08:08:20 UTC
Time: 2018-07-29T08:06:15+00:00
Session ID: c11376bbf09382e8010c87980fcf070f
Problem Page URL: [/feedbacks/userid_feedbacks](/feedbacks/userid_feedbacks)
Previous Page URL: [https://www.freereg.org.uk/manage_resources/new](https://www.freereg.org.uk/manage_resources/new)
Reported Issue:
I have this message but there is no option to remove it from my list when I have read it.
http://www13.freereg.org.uk/uploads/feedback/screenshot/5b5d75f4f493fd75515a28d1/Capture.JPG    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/5b5d75f4f493fd75515a28d1/Capture.JPG)

**Comment by Captainkirkdawson** [comment]
Why would you want to remove it. Does it not need a reply?

**Comment by edickens** [comment]
They are my messages.  Why would I want to reply to them?
![capture](https://user-images.githubusercontent.com/8876165/43383994-8ca74c14-93d4-11e8-9f72-246e9a00872d.JPG)
They are in the notification that I have a message and look as if they will be there forever.
When do they go?

**Comment by richpomfret** [comment]
Needs further discussion before implementation. This just refers to feedback reply notification upon login.

**Comment by SteveBiggs** [comment]
Is any further info needed? The request is to be able to remove the notification of a Feedback on the page (i.e. add a Remove button).

**Comment by Sherlock21** [comment]
In addition to not being able to remove a completed message, I notice that it stays listed as: NEW. even though I have read it and replied to it.

can you fix this too please at the same time

**Comment by edickens** [comment]
This is just the notification that I have messages.
![capture1](https://user-images.githubusercontent.com/8876165/44076942-edea6fd0-9f99-11e8-81a5-45e70954f781.JPG)
I just need to remove them from my list of notifications, not from the messages system.
![capture](https://user-images.githubusercontent.com/8876165/44076980-0d6d19de-9f9a-11e8-8ddd-f8ee414fc5d1.JPG)
If I get other types of messages, I can remove them from my list 
There are also no breadcrumbs.
