### ISSUE TITLE
112952374 RED message when sending email to Syndicate (Eric)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1109]
depends on #1516
Issue reported by **REGManager** at 2018-07-31 07:39:34 UTC
Time: 2018-07-31T07:35:26+00:00
Session ID: 212fa61320db7947907dab8beab37db4
Problem Page URL: [/messages/5b4765c5f493fdb1c229e2e1/send_message](/messages/5b4765c5f493fdb1c229e2e1/send_message)
Previous Page URL: [https://www.freereg.org.uk/messages](https://www.freereg.org.uk/messages)
Reported Issue:
Sent at 08:35 31/7/18 BST.
Logged in as Regmanager.  Selected manage syndicate.  Chose Dorset.  Selected Email syndicate.  Selected message.  Send message.  OK.  Crashed.
http://www13.freereg.org.uk/uploads/feedback/screenshot/5b601236f493fd1df79966f0/Capture.JPG    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/5b601236f493fd1df79966f0/Capture.JPG)

**Comment by Captainkirkdawson** [comment]
This was caused by #1516

**Comment by Captainkirkdawson** [comment]
@edickens You must select the Members of Syndicate option when you wish to send the message

**Comment by Captainkirkdawson** [comment]
@edickens A check has been added and deployed to test3
