### ISSUE TITLE
REGManager Funtions are all showing "Invalid Option" (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#111]
Issue reported by **REGManager** at 2014-12-04 08:44:15 UTC
Time: 2014-12-04T08:38:35+00:00
Session ID: 58a0a934f82a2be8258dae3f5f3449c2
Problem Page URL: [/userid_details/options](/userid_details/options)
Previous Page URL: [http://test2.freereg.org.uk/userid_details/options](http://test2.freereg.org.uk/userid_details/options)
Reported Issue:
Since changing the button style, the Manage UserID (and perhaps other) functions for REGManager  are showing Invalid Option.  I need to set up new volunteers who have registered in FR1.
If this is because I have been locked out from working with FR2, then do tell me and so save me wasting my time.
E    

![Screenshot](http://test2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
It is certainly NOT the latter

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by edickens** [comment]
```
Have you found where it happens? 
  Doreen has found the same.  I can provide more information if
  needed.

  E
  _____________________________________
```

Eric J Dickens
FreeREG Chairman
      On 04/12/2014 13:25, Kirk Dawson wrote:

```
It is certainly NOT the latter


  Kirk Dawson

  Fairmont Hot Springs, B.C.

  V0B 1L1


  On Thu, Dec 4, 2014 at 1:44 AM, FreeUKGenIssues
  <notifications@github.com>

  wrote:


  > Issue reported by *REGManager* at 2014-12-04 08:44:15 UTC

  > Time: 2014-12-04T08:38:35+00:00

  > Session ID: 58a0a934f82a2be8258dae3f5f3449c2

  > Problem Page URL: /userid_details/options

  > Previous Page URL:
  http://test2.freereg.org.uk/userid_details/options

  > Reported Issue:

  > Since changing the button style, the Manage UserID (and
  perhaps other)

  > functions for REGManager are showing Invalid Option. I need
  to set up new

  > volunteers who have registered in FR1.

  > If this is because I have been locked out from working with
  FR2, then do

  > tell me and so save me wasting my time.

  > E

  >

  > [image: Screenshot]

  >
```

https://camo.githubusercontent.com/a7c8fb6673d738b70608d7fd478267f9bda898d4/687474703a2f2f74657374322e667265657265672e6f72672e756b
      >

```
  > —

  > Reply to this email directly or view it on GitHub

  >
  <https://github.com/FreeUKGen/FreeUKGenProductIssues/issues/111>.

  >
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by Captainkirkdawson** [comment]
Fixed

**Comment by edickens** [comment]
Thanks Kirk.  Working OK.  Can be closed.
