### ISSUE TITLE
113210757 Notes not showing in Search result (Stephen)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1116]
Issue reported by **steveroland** at 2018-08-03 07:25:57 UTC
Time: 2018-08-03T07:23:38+00:00
Session ID: a8366e75fc4baf93720780c8596293eb
Problem Page URL: [/search_records/5b5df7a6f493fd6593557fb1?search_id=5b6402dcf493fd432d61b311&ucf=false](/search_records/5b5df7a6f493fd6593557fb1?search_id=5b6402dcf493fd432d61b311&ucf=false)
Previous Page URL: [https://www.freereg.org.uk/search_queries/5b6402dcf493fd432d61b311](https://www.freereg.org.uk/search_queries/5b6402dcf493fd432d61b311)
Reported Issue:
It's just come to my attention that the Notes field is not being displayed in a search result.    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/5b640385f493fd432d61b85e/_old_)

**Comment by Captainkirkdawson** [comment]
Have confirmed this to be the case. Likely an unintended consequence of the flexible csv and new fields code

**Comment by Captainkirkdawson** [comment]
Notes field has now been added. to display. Awaiting deployment

**Comment by Captainkirkdawson** [comment]
Deployed as urgent issue

**Comment by SteveBiggs** [comment]
Tested in production and Notes field is now displayed, thanks.
