### ISSUE TITLE
113865617 Zero years erroneously reported (Stephen)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1118]
Issue reported by **steveroland** at 2018-08-10 21:20:17 UTC
Time: 2018-08-10T21:14:52+00:00
Session ID: 6ea8e5de3d38b6b130f400754f59764e
Problem Page URL: [/freereg1_csv_files/5b6d81d7f493fd171230db9f/zero_year](/freereg1_csv_files/5b6d81d7f493fd171230db9f/zero_year)
Previous Page URL: [https://www.freereg.org.uk/freereg1_csv_files/5b6d81d7f493fd171230db9f](https://www.freereg.org.uk/freereg1_csv_files/5b6d81d7f493fd171230db9f)
Reported Issue:
Some batches are showing as having zero years when they have none such as this one.
http://www13.freereg.org.uk/uploads/feedback/screenshot/5b6e0191f493fd11a68e5d80/Capture.jpg    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/5b6e0191f493fd11a68e5d80/Capture.jpg)
Needs #1581

**Comment by Captainkirkdawson** [comment]
Were corrections made on line?

**Comment by Sherlock21** [comment]
Exactly the same point that I was going to add.
It needs to have a file Reloaded in order to get the zero years to recalculate doesn't it.

**Comment by Captainkirkdawson** [comment]
If this is confirmed then we could have an online date change trigger a recalculation.  Title would then be changed.

**Comment by Sherlock21** [comment]
quite recently, I did a few tests for someone (Andy Philips I think?). they were concerned that they had spent ages going throughout their batches to remove Zero's by doing it on line only to find the zero still stayed.
The only way i could get the  year range to show the -by then corrected - range was to reload the batch  with some other real change in it - even a full stop in the Notes field of the record(s) that had beed date corrected.

**Comment by Captainkirkdawson** [comment]
I believe that a reprocess of the batch will achieve the same end without all of the file manipulation.
I believe that all SA and perhaps you have access to that command in the show of a file. You have it in the physical files as well

**Comment by Captainkirkdawson** [comment]
Kirk,
Can you please check. I think that when an entry has its zero year corrected online then the year range IS recalculated, and reprocessing is not needed. But this does not happen when a blank, or other, entry is deleted.
I think that recalculate should take place every time any editing, insertion or deletion of an entry takes place. I'm not sure that this happens.

**Comment by Captainkirkdawson** [comment]
The story refers to the Zero_year display

**Comment by SteveBiggs** [comment]
No corrections were made online. This (and others) was a fresh file upload. I have just tried a reprocess and it did NOT remove the zero year reports. It would appear that the only way is to manually edit each "zero" entry online.

**Comment by Sherlock21** [comment]
But I myself, ( and other cc's) could not get rid of the zero by doing an online edit.

So is there more to this than we seem to think?
i.e. one size does not fit all.

**Comment by Captainkirkdawson** [comment]
This file has been corrected and as a result any attempt to research what was occurring cannot be performed.

**Comment by Captainkirkdawson** [comment]
I hope the code developed for #1661 and #1611 fixes this issue
