### ISSUE TITLE
Create UserID causes NoMethodError (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#112]
Issue reported by **REGManager** at 2014-12-05 12:40:04 UTC
Time: 2014-12-05T12:34:11+00:00
Session ID: 28918b30c4271af768c6368797045e05
Problem Page URL: [/userid_details/new](/userid_details/new)
Previous Page URL: [http://test2.freereg.org.uk/userid_details/options](http://test2.freereg.org.uk/userid_details/options)
Reported Issue:
Using REGManager function to create a new UserID, I get the attached screenshot.  It has been working correctly until a few days ago.
E

![Screenshot](http://test2.freereg.org.uk/tmp/carrierwave/1417783204-85773-8186/Capture.JPG)

**Comment by Captainkirkdawson** [comment]
I believe to be fixed; was an unsuccessful creation and did now know who you were on the recovery.

**Comment by edickens** [comment]
```
Hi Kirk,
  No, still fails.  See attached.  It should have been successful as
  it is not a duplicate UserID.

  Am trying to put in this volunteer...

  Hi,
```

The following person has just completed registration with FreeREG
Name: Christine Russ
Country: England
Email Address: kristinemiab@yahoo.co.uk
Coordinator: capn-bob@pegleg2.com
Submitter ID: ChrisR
Syndicate ID: DOR

Thanks

The machine inside FreeREG !

```
  E
  _____________________________________
```

Eric J Dickens
FreeREG Chairman
      On 05/12/2014 15:13, Kirk Dawson wrote:

```
  I believe to be fixed; was an unsuccessful creation and did now
    know who you were on the recovery.
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by edickens** [comment]
```
Hi Kirk,
  Yes, adding new UserIDs is fixed, but I don't think that the error
  reporting has been fixed.
  The reason for the error is "Duplicate email address". This is
  because Chris-Christine Russ is still there.




  We got rid of it in FR1 giving her a new email address ChrisR. 
  But she has files in FR2.
  Shall I set up ChrisR using a different email address; move her
  files to this UserID; delete "Chris"; then change the email
  address in "ChrisR"?
  E
  _____________________________________
```

Eric J Dickens
FreeREG Chairman
      On 06/12/2014 12:36, Eric Dickens-gmail wrote:

```
  Hi Kirk,
    No, still fails.  See attached.  It should have been successful
    as it is not a duplicate UserID.

    Am trying to put in this volunteer...

    Hi,
```

The following person has just completed registration with FreeREG
Name: Christine Russ
Country: England
Email Address: kristinemiab@yahoo.co.uk
Coordinator: capn-bob@pegleg2.com
Submitter ID: ChrisR
Syndicate ID: DOR

Thanks

The machine inside FreeREG !

```
    E
    _____________________________________
```

Eric J Dickens
FreeREG Chairman
        On 05/12/2014 15:13, Kirk Dawson wrote:

```
    I believe to be fixed; was an unsuccessful creation and did
      now know who you were on the recovery.
    —
      Reply to this email directly or view

        it on GitHub.
```

**Comment by Captainkirkdawson** [comment]
Have started a new issue on the point you raise.
