### ISSUE TITLE
114685027 Listing County Files shows ALL files by transcribers in syndicate (Stephen)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1120]
Issue reported by **steveroland** at 2018-08-20 08:57:07 UTC
Time: 2018-08-20T08:51:02+00:00
Session ID: 071c09edb017fbfaefd04a86946becb7
Problem Page URL: [/freereg1_csv_files?page=3](/freereg1_csv_files?page=3)
Previous Page URL: [https://www.freereg.org.uk/freereg1_csv_files](https://www.freereg.org.uk/freereg1_csv_files)
Reported Issue:
Listing files for my county (SSX) seems a lot slower now. It appears that all files for any county created by a transcriber in the syndicate is being listed. I thought it was only Sussex files?
http://www13.freereg.org.uk/uploads/feedback/screenshot/5b7a8263f493fdaa5d665b96/Capture.jpg    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/5b7a8263f493fdaa5d665b96/Capture.jpg)

**Comment by edickens** [comment]
If it is for a syndicate, or transcriber, then it will be all the work that they have done, which is what the SC is responsible for.

**Comment by SteveBiggs** [comment]
I know, but this is for the county not the syndicate per the attached screenshot (Manage County -> Review Batches ....)

**Comment by SteveBiggs** [comment]
However, I've just done the same listing again and now it is correctly showing only the county files! I'm wondering if it might have been a cookies problem as I may have had a SC tab open at the time .....

I will close the issue.
