### ISSUE TITLE
114864062 "SC uploads my data" does not show (Eric)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1121]
Issue reported by **REGManager** at 2018-08-22 10:41:02 UTC
Time: 2018-08-22T10:39:09+00:00
Session ID: 6d944376871907562c8a57c1fc8984a7
Problem Page URL: [/userid_details/5462b402e937907d70000045](/userid_details/5462b402e937907d70000045)
Previous Page URL: [https://www.freereg.org.uk/userid_details/5462b402e937907d70000045/edit](https://www.freereg.org.uk/userid_details/5462b402e937907d70000045/edit)
Reported Issue:
This does not show when viewing the profile, only when editing.    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/5b7d3dbef493fdaa6346bdb0/_old_)

**Comment by Captainkirkdawson** [comment]
The field entitled  "Just send my processing messages to my coordinator" means that "The SC uploads my data" Just different words. So the field is being displayed. Have changed the wording to match. Deployed to test3
