### ISSUE TITLE
114864432 Server Problems (annette gore)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1122]
Priority (2 6 9 5) 22

Issue reported by **annette gore** at 2018-08-22 10:47:12 UTC
Time: 2018-08-22T10:46:33+00:00
Session ID: b81428f21ed633d4ae30942359743ff2
Problem Page URL: []()
Previous Page URL: [https://www.freereg.org.uk/contacts/new](https://www.freereg.org.uk/contacts/new)
Reported Issue:
Your search encountered a problem please contact us with this message    

![Screenshot](http://www.freereg.org.uk/uploads/contact/screenshot/5b7d3f31f493fdaa6346c4e1/_old_)

**Comment by SteveBiggs** [comment]
We've received several similar messages this morning of failed searches. I tested a few searches myself that were all sucessful, so maybe the problem has passed. Will see if we get anymore reports .....

**Comment by DeniseColbert** [comment]
I think Mongo6 is down, it could be one of those situations where it depends which server you get on to. Have sent a message to Kirk and Lemon.

**Comment by SteveBiggs** [comment]
Thanks @DeniseColbert. Another failed search report just came in. Hopefully Mongo6 can be brought up quickly, but if not we should put a temporary message on the Search page saying we know there is a problem and it's being worked on ....

**Comment by Captainkirkdawson** [comment]
Message added and lemon is investigating

**Comment by Captainkirkdawson** [comment]
mongo6 had disk problems that have resulted in damage to the mongodb databases on mongo6. It has been removed from serving information. This leaves only mongo5 serving shard3.

**Comment by Captainkirkdawson** [comment]
An attempt to rebuild mongo6 databases appeared to cause a failure of mongo5 and the we were totally down for 2 hrs

**Comment by Captainkirkdawson** [comment]
Mongo5 restarted. mongo6 still unavailable.

**Comment by Captainkirkdawson** [comment]
mongo6 database rebuilt on second attempt. running OK as secondary. Have yet to bring back into service

**Comment by Captainkirkdawson** [comment]
drill now using secondaries again

**Comment by Captainkirkdawson** [comment]
mongo6 now serving database requests from drill will add howler and saki back in

**Comment by Captainkirkdawson** [comment]
All servers now in normal production configuration. 
Documentation on recovery process added as section 13 in 
 https://docs.google.com/document/d/1rrDCZBlej0U9QjRKgrm83LfpjhD6RQjIo8VRYX9IgGQ/edit#heading=h.eudedvge81lm

**Comment by SteveBiggs** [comment]
We should remove the warning notice on the Search page.

**Comment by Captainkirkdawson** [comment]
Thank you Steve

Removed
