### ISSUE TITLE
115746143 Website Problem (Jayne Parker)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1123]
Issue reported by **Jayne Parker** at 2018-09-01 15:42:23 UTC
Time: 2018-09-01T15:38:07+00:00
Session ID: 36838e3ecd24c866a2059bfe3e7d26cb
Problem Page URL: []()
Previous Page URL: [https://www.freereg.org.uk/contacts/new](https://www.freereg.org.uk/contacts/new)
Reported Issue:
Hello, 
Following on from my previous message, whilst that particular problem has now been resolved, I am still having problems with your site. I have been using your site for several years with no problems at all but this last week I have had several problems where I type in my search details and instead of bringing up the list of matching entries (or even an error message) it just skips back to the search screen with no details in it. It doesn't happen every time, but seems to happen if I leave one of the boxes empty (ie; no christian name or no town name, even though I have chosen a county)
many thanks
Jayne    

![Screenshot](http://www.freereg.org.uk/uploads/contact/screenshot/5b8ab35ff493fd30830d3b6b/_old_)

**Comment by Captainkirkdawson** [comment]
I am sorry but there is no way of researching such a broadly stated problem with no documentation,

**Comment by SteveBiggs** [comment]
I've already asked Jayne if there is any specific search that is guaranteed to fail but no reply as yet.
I will say that I have experienced this behaviour but it appears to be random (the same search sometimes succeeds and sometimes result in bounce back to blank form).

I'll have another try at reproducing reliably.

**Comment by PatReynolds** [comment]
Seems to be a duplicated of #1126

**Comment by SteveBiggs** [comment]
It is, but raised to show multiple users are experiencing this occasionally.

**Comment by SteveBiggs** [comment]
Closed to consolidate in one issue - #1126
