### ISSUE TITLE
BA files with dates showing zero date

### ISSUE THREAD

**Issue by suffolkroots** [FreeUKGen/FreeUKRegProductIssues#1124]
Baptism files with birthdate only are showing as zero date files.
![not zero date](https://user-images.githubusercontent.com/10379655/45019882-57e98380-b025-11e8-8d35-0a34ad2e74c2.jpg)

**Comment by Captainkirkdawson** [comment]
Expect that this is because the file was processed on 05 Jun 2015 before the code changes were made to use birth dates if baptism dates were not present.
Suggest a reprocess of the file

**Comment by richpomfret** [comment]
Steve to check for hidden spaces (as possible cause).

**Comment by SteveBiggs** [comment]
A reprocess is required.

**Comment by suffolkroots** [comment]
Steve I've already dealt with this.
As far as I am concerned it can be closed.

**Comment by SteveBiggs** [comment]
Thanks Ali.  Closing.
