### ISSUE TITLE
Field list not complete in Help.

### ISSUE THREAD

**Issue by suffolkroots** [FreeUKGen/FreeUKRegProductIssues#1125]
List of fields for spreadsheet does not include Film/Fiche and Image.
Attached is baps list as example
![fields](https://user-images.githubusercontent.com/10379655/45020166-11485900-b026-11e8-93ac-8d25528ccb0f.jpg)

**Comment by Captainkirkdawson** [comment]
This is addressed in the help materials written to cover the New Fields and will not be address separately.
