### ISSUE TITLE
116509392 Rassigned Image Group shows old userid (Stephen)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1127]
Issue reported by **steveroland** at 2018-09-10 11:43:12 UTC
Time: 2018-09-10T11:40:29+00:00
Session ID: 6555b73cf0e5fee895daf5a258351bdf
Problem Page URL: [/image_server_groups/5a9ec8e1f493fdbfcb998958](/image_server_groups/5a9ec8e1f493fdbfcb998958)
Previous Page URL: [https://www.freereg.org.uk/image_server_images/5a9ec8e1f493fdbfcb998958/index](https://www.freereg.org.uk/image_server_images/5a9ec8e1f493fdbfcb998958/index)
Reported Issue:
I reassigned this group to userid 'jmitchell'. The individual images show the new userid (image), but at the group level, it still shows the old one of 'jelit'.
http://www13.freereg.org.uk/uploads/feedback/screenshot/5b9658d0f493fd64b2fee23d/Capture.jpg    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/5b9658d0f493fd64b2fee23d/Capture.jpg)
E - 0/10
U - 4/10
S - 8/10
C - 7/10

19

**Comment by bev-fc** [comment]
Fix is applied to test3, please test it.

**Comment by SteveBiggs** [comment]
Looks good in test3

**Comment by richpomfret** [comment]
To be deployed on production.

**Comment by richpomfret** [comment]
Scott to check it has been deployed (should be fine).

**Comment by SteveBiggs** [comment]
I can confirm this is now working on production so can be closed.
