### ISSUE TITLE
116549065 No scroll bar on Select Syndicate window (Staffordshire)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1128]
Issue reported by **STSCoord** at 2018-09-10 22:44:25 UTC
Time: 2018-09-10T22:38:04+00:00
Session ID: 31ca0e5dfab55305175448bfa6499807
Problem Page URL: [/image_server_groups/5a9eccb4f493fdbfcb9ad3f1/allocate](/image_server_groups/5a9eccb4f493fdbfcb9ad3f1/allocate)
Previous Page URL: [https://www.freereg.org.uk/image_server_groups/5a9eccb4f493fdbfcb9ad3f1/index](https://www.freereg.org.uk/image_server_groups/5a9eccb4f493fdbfcb9ad3f1/index)
Reported Issue:
There is no scroll bar at the right side of the "Select Syndicate" window in Image Server (see attached screenshot).
My County is STS so I have to scroll down within this window a long way. Using the wheel on my mouse, sometimes it scrolls, sometimes not. Without the scroll bar, I cannot easily get to my County.
http://www13.freereg.org.uk/uploads/feedback/screenshot/5b96f3c9f493fd64b202f6f2/No_Scroll_Bar.JPG    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/5b96f3c9f493fd64b202f6f2/No_Scroll_Bar.JPG)

**Comment by bev-fc** [comment]
Fix is applied to test3, please test it.

**Comment by SteveBiggs** [comment]
Testes and good in test3. Please deploy to production

**Comment by SteveBiggs** [comment]
Tested and good in production. Can close.
