### ISSUE TITLE
116549433 STill no scroll bar on Select Syndicate (Staffordshire)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1129]
Issue reported by **STSCoord** at 2018-09-10 22:50:33 UTC
Time: 2018-09-10T22:44:25+00:00
Session ID: 31ca0e5dfab55305175448bfa6499807
Problem Page URL: [/image_server_groups/5a9eccb4f493fdbfcb9ad3f1/allocate](/image_server_groups/5a9eccb4f493fdbfcb9ad3f1/allocate)
Previous Page URL: [https://www.freereg.org.uk/feedbacks/new?utf8=%E2%9C%93&feedback_time=2018-09-10+22%3A38%3A04+UTC&session_id=31ca0e5dfab55305175448bfa6499807&user_id=STSCoord&problem_page_url=%2Fimage_server_groups%2F5a9eccb4f493fdbfcb9ad3f1%2Fallocate&previous_page_url=https%3A%2F%2Fwww.freereg.org.uk%2Fimage_server_groups%2F5a9eccb4f493fdbfcb9ad3f1%2Findex&feedback_type=issue](https://www.freereg.org.uk/feedbacks/new?utf8=%E2%9C%93&feedback_time=2018-09-10+22%3A38%3A04+UTC&session_id=31ca0e5dfab55305175448bfa6499807&user_id=STSCoord&problem_page_url=%2Fimage_server_groups%2F5a9eccb4f493fdbfcb9ad3f1%2Fallocate&previous_page_url=https%3A%2F%2Fwww.freereg.org.uk%2Fimage_server_groups%2F5a9eccb4f493fdbfcb9ad3f1%2Findex&feedback_type=issue)
Reported Issue:
After clicking on the first entry in the window and then hitting the down arrow,, the panel changes to wider mode. It also loses the ability to see tick boxes on the panel below. See attached screenshot
http://www13.freereg.org.uk/uploads/feedback/screenshot/5b96f539f493fd64b202f7f4/Still_no_scroll_bar.JPG    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/5b96f539f493fd64b202f7f4/Still_no_scroll_bar.JPG)

**Comment by SteveBiggs** [comment]
The browser is Microsoft Edge (in Win 10) and I have reproduced the problem.

**Comment by edickens** [comment]
Firefox in Wndows 7 is the same.

**Comment by bev-fc** [comment]
@SteveBiggs @edickens Fix is applied to test3, please test it.

**Comment by SteveBiggs** [comment]
@bev-fc  it still behaves the same in Edge in test3.

**Comment by bev-fc** [comment]
this is the screen shot of edge from my machine. 

![20180911_001](https://user-images.githubusercontent.com/22349799/45390209-6408ae80-b5ec-11e8-8b3c-633619b238a3.jpg)

**Comment by SteveBiggs** [comment]
Yes it works now thanks. Maybe I tested it too soon last night?

**Comment by bev-fc** [comment]
no clue. :/

**Comment by SteveBiggs** [comment]
No worries, important thing is it's good now!

**Comment by SteveBiggs** [comment]
Tested and good in production. Can close.
