### ISSUE TITLE
Apparent duplicate userids

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeUKRegProductIssues#113]
EricD reported that

"The reason for the error is "Duplicate email address". This is because Chris-Christine Russ is still there."

I believe there is the possibility of a deep hidden issue with the Userids.

When they were created I noted there were some 2000+ userids while there were only 1983 user folders.
You said not to worry. I think I should have worried. There should not have been more than 1 additional userids than folders. So something is likely wrong somewhere.

**Comment by edickens** [comment]
```
Hi Kirk,
  Today there are 1,998 UserIDs in FR1, and probably no more than 5
  added since you got a copy, and none deleted.  So your 1,983 would
  seem to be correct.  I think that there were more than 2,000 until
  we had a tidy up.
  E
  _____________________________________
```

Eric J Dickens
FreeREG Chairman
      On 07/12/2014 18:20, Kirk Dawson wrote:

```
  EricD reported that
  "The reason for the error is "Duplicate email address". This is
    because Chris-Christine Russ is still there."
  I believe there is the possibility of a deep hidden issue with
    the Userids.
  When they were created I noted there were some 2000+ userids
    while there were only 1983 user folders.
    You said not to worry. I think I should have worried. There
    should not have been more than 1 additional userids than
    folders. So something is likely wrong somewhere.
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by Captainkirkdawson** [comment]
There are currently 2046 Userids!! that includes say 10 who are registered only in FR2 eg Ben/Richard James and Josh and Darren. It is as I said at the time too many.

**Comment by edickens** [comment]
```
Kirk,
  I'm wondering if you have the ones that we deleted as duplicates. 
  In my control sheet I have 19 duplicate UserIDs and 40 duplicate
  email address.  I will have to check but it is possible that a lot
  of the UserIDs with duplicate email addresses have also been
  deleted as most were UserIDs of inactive transcribers who the CC
  had taken control of.
  Is that any help?
  E
  _____________________________________
```

Eric J Dickens
FreeREG Chairman
      On 07/12/2014 20:49, Kirk Dawson wrote:

```
  There are currently 2046 Userids!! that includes say 10 who are
    registered only in FR2 eg Ben/Richard James and Josh and Darren.
    It is as I said at the time too many.
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by Captainkirkdawson** [comment]
Not currently an active story.

**Comment by edickens** [comment]
Kirk,
I've just done a few spot checks and all the duplicates that we got rid of in FR1 are still there in FR2.  Do you think it is to do with which version of the FR1 list of UserIDs you got when you did the update on 12 November?  The FR1 update completed on 12 November,  so it should have been OK.  Perhaps you need to check with BenL.  The other problem may be that these duplicates are still showing files in FR2, even though they do not have them in FR1 and have been deleted.  But deleted UserIDs/files may still be in FR1 in the Archives, so would you have got them that way?
E

**Comment by Captainkirkdawson** [comment]
The problem was that the existing userids were not deleted from the collection before the build in early November. Have run a report and cleaned up the userids. There are now 2004 userids. This should be a few more than there are on FR1 due to people like Darren and Richard who are in FR2 but not
