### ISSUE TITLE
116766220 Created reply does not retain paragraph format (Eric)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1130]
Issue reported by **REGManager** at 2018-09-13 11:03:40 UTC
Time: 2018-09-13T11:02:21+00:00
Session ID: 3eb0e23d0f3c6b7e83ecea0a4dad88fe
Problem Page URL: [/contacts/5b98f108f493fd64b20e1cea/reply](/contacts/5b98f108f493fd64b20e1cea/reply)
Previous Page URL: [https://www.freereg.org.uk/contacts](https://www.freereg.org.uk/contacts)
Reported Issue:
When replying to a Contact, the message creation shows parapgraphs, but when sent the text is just one paragraph.    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/5b9a440cf493fd64b7fd46fa/_old_)

E = 0
U = 6
S = 8
C = 7
21

**Comment by DeniseColbert** [comment]
This isn't just when replying to Contacts; it happened when I sent a message through the system, too.

**Comment by SteveBiggs** [comment]
This is the behaviour in all  "free text" fields in FreeREG. Even the "Report a problem" description field. It would certainly be nice if formatting could be retained.

**Comment by Captainkirkdawson** [comment]
Do not understand. The message created and sent outlining the new system retains its paragraph structure.
