### ISSUE TITLE
117142829 Confusing field name on Edit Image Source screen (Staffordshire)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1132]
Issue reported by **STSCoord** at 2018-09-17 19:40:29 UTC
Time: 2018-09-17T19:29:14+00:00
Session ID: fa22f18852287331b0169820f80c4c8b
Problem Page URL: [/sources/5b9fffaef493fdf4fe5ecb4b?image_group_filter=](/sources/5b9fffaef493fdf4fe5ecb4b?image_group_filter=)
Previous Page URL: [https://www.freereg.org.uk/manage_counties/selection?option=Manage%20Images](https://www.freereg.org.uk/manage_counties/selection?option=Manage%20Images)
Reported Issue:
The field name of "xxx Date" implies that a FreeREG format date is required but when a valid date is entered, the system states that only 4 digits are required. This implies that only the year is required so the field name is misleading - it should be "xxx Year" and only needs the text box to be wide enough for 4 digits. It is possible that the year of the date could be double-dated so maybe space for a maximum of 7 characters is required. This also makes the error message wrong.
http://www13.freereg.org.uk/uploads/feedback/screenshot/5ba0032df493fdf4fe5eeec1/Capture.JPG    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/5ba0032df493fdf4fe5eeec1/Capture.JPG)

Economic 0, Urgency 3, Strategic 8,  Cost ?7?: Priority 18?

**Comment by SteveBiggs** [comment]
I agree that 'Date' should be 'Year', but keep it as 4 digits (if the first entry was say, 1662/63, then 1662 would be entered.

**Comment by Captainkirkdawson** [comment]
Implemented and put into production on Sept 18

**Comment by SteveBiggs** [comment]
Tested and good. Can be closed.

**Comment by Captainkirkdawson** [comment]
Reopened @bev-fc  While the _edit is basically done the show of the source should also use Start and End Year not Date and the error messages should also use Year.

**Comment by Captainkirkdawson** [comment]
Both source show and edit now use Year consistently. Deployed into test3 for testing

**Comment by richpomfret** [comment]
@SteveBiggs to take a look and test.

**Comment by SteveBiggs** [comment]
Tested and good.

**Comment by SteveBiggs** [comment]
Verified in production.
