### ISSUE TITLE
117273444 Unexpected error message when trying to reply to a contact (Staffordshire)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1133]
Issue reported by **STSCoord** at 2018-09-19 07:57:24 UTC
Time: 2018-09-19T07:54:04+00:00
Session ID: 217269b9d719d79ab04a4761c15bc231
Problem Page URL: [/contacts/5ba11f28f493fdf4fe640f09/reply](/contacts/5ba11f28f493fdf4fe640f09/reply)
Previous Page URL: [https://www.freereg.org.uk/contacts](https://www.freereg.org.uk/contacts)
Reported Issue:
I am getting the attached error when trying to reply to a contact. When I list my messages to a contact, I see the messages but they all show as Sent
http://www13.freereg.org.uk/uploads/feedback/screenshot/5ba20164f493fdf5035cdced/Capture.JPG    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/5ba20164f493fdf5035cdced/Capture.JPG)

Economic 0, Urgency 4, Strategic 8,  Cost 5: Priority 17

**Comment by SteveBiggs** [comment]
Started testing the messaging changes and since I have no Contacts in test3, decided to create one. Did a search and submitted a problem with a record, but got the red Something went wrong ..... The contact did appear in my list though.

**Comment by SteveBiggs** [comment]
Replied to contact and received in email as expected.

**Comment by SteveBiggs** [comment]
Copies also received in comscoord email.

**Comment by Captainkirkdawson** [comment]
Sorry about the red page @SteveBiggs had a wrong variable name in a last minute change when I added the sender to the list of copies if it was a different person.
Fixed and deployed to test3

**Comment by richpomfret** [comment]
To deploy once the new system has been reviewed.
