### ISSUE TITLE
119615325 Help for getting images still shows GETSCAN (Eric)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1135]
Issue reported by **REGManager** at 2018-10-16 10:28:45 UTC
Time: 2018-10-16T10:26:09+00:00
Session ID: 07f30870ac600f0d01cee8389fd383e2
Problem Page URL: [/cms/information-for-coordinators](/cms/information-for-coordinators)
Previous Page URL: [https://www.freereg.org.uk/image_server_groups/5bc4771ff493fd53d8e4f3e6/index](https://www.freereg.org.uk/image_server_groups/5bc4771ff493fd53d8e4f3e6/index)
Reported Issue:
This is the relevant Help.  Even if the Help for the new system is not ready, this should be removed and just have a reference to refer to Steve.

The Image Server

To find and allocate a set of images for a transcriber:

    Log in to the image server with your UserID and password.
    Browse to find images for a place in your county.
    Email EricD with the UserID of the transcriber and the image filenames.
    The images will be moved into a folder for that transcriber.
    The transcriber can then log in and download the images allocated to them.

    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/5bc5bd5df493fd53d8e540e6/_old_)

**Comment by Captainkirkdawson** [comment]
Holding change made to test3 and production
