### ISSUE TITLE
121159638 Attempt  to Delete a Batch crashed out  (Eric)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1136]
Issue reported by **ericb** at 2018-11-03 07:27:18 UTC
Time: 2018-11-03T07:20:43+00:00
Session ID: 0148bbf2d5717fb998933cb814bf6c44
Problem Page URL: [/freereg1_csv_files/5463a027e937902782aaa5ea](/freereg1_csv_files/5463a027e937902782aaa5ea)
Previous Page URL: [https://www.freereg.org.uk/manage_counties/selection?option=Review%20Specific%20Batch](https://www.freereg.org.uk/manage_counties/selection?option=Review%20Specific%20Batch)
Reported Issue:
started to delete a batch STSROWBU (Jonny).
I clicked on the Delete Original File and  all assoc. etc, and just got the red screen OOPS Sorry... etc
http://www13.freereg.org.uk/uploads/feedback/screenshot/5bdd4dd6f493fdaa5ddd0876/Delete_Jonny_file.jpg    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/5bdd4dd6f493fdaa5ddd0876/Delete_Jonny_file.jpg)

Economic 0, urgency 2, strategy3, cost 6: Pritority 11

**Comment by Captainkirkdawson** [comment]
See #1647 for cause

**Comment by richpomfret** [comment]
1582 is now tracking this issue - therefore closing this
