### ISSUE TITLE
121701639 All Feedbacks have disappeared (Stephen)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1138]
Issue reported by **SBManager** at 2018-11-09 14:00:39 UTC
Time: 2018-11-09T13:57:16+00:00
Session ID: bc9df5db4de49b596806f06808086e0c
Problem Page URL: [/feedbacks?](/feedbacks?)
Previous Page URL: [https://www.freereg.org.uk/manage_resources/new](https://www.freereg.org.uk/manage_resources/new)
Reported Issue:
Logged in as Sys Admin, I should see all feedbacks, but now the list is completely empty!    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/5be59307f493fd7f0686476f/_old_)

**Comment by Captainkirkdawson** [comment]
fixed

**Comment by SteveBiggs** [comment]
They are back now, thanks.
