### ISSUE TITLE
121710694 Create New Message button gone (Stephen)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1139]
Issue reported by **SBManager** at 2018-11-09 16:31:34 UTC
Time: 2018-11-09T16:28:09+00:00
Session ID: abe4047b27f2d4deb1e669aef28da4ac
Problem Page URL: [/messages?](/messages?)
Previous Page URL: [https://www.freereg.org.uk/manage_resources/new](https://www.freereg.org.uk/manage_resources/new)
Reported Issue:
In the Message System, there is now no Create New Message button (see screenshot).
http://www13.freereg.org.uk/uploads/feedback/screenshot/5be5b666f493fd7f018db9b8/Capture.jpg    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/5be5b666f493fd7f018db9b8/Capture.jpg)

**Comment by Captainkirkdawson** [comment]
Typo fixed deployed to test3

**Comment by SteveBiggs** [comment]
It's back in test3.
