### ISSUE TITLE
Clicking the Genuki link should open a new browser tab (steveroland)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#114]
Issue reported by **steveroland** at 2014-12-10 12:58:19 UTC
Time: 2014-12-10T12:53:14+00:00
Session ID: c98a18797c0ad2ae196489865355620d
Problem Page URL: [/places/53cbf613eca9eb03a6009c85](/places/53cbf613eca9eb03a6009c85)
Previous Page URL: [http://test2.freereg.org.uk/places?page=14](http://test2.freereg.org.uk/places?page=14)
Reported Issue:
When the Genuki link is clicked on a Place page, you are navigated away from FreeREG when in general you would want to keep that page open. It would be better to open Genuki in a new browser tab/page.    

![Screenshot](http://test2.freereg.org.uk)

**Comment by edickens** [comment]
```
The same applies to "Report a problem"
  so that it is possible to see what you were doing and not have to
  log back into FR2.
  E
  _____________________________________
```

Eric J Dickens
FreeREG Chairman
      On 10/12/2014 12:58, FreeUKGenIssues wrote:

```
  Issue reported by steveroland at 2014-12-10
    12:58:19 UTC
    Time: 2014-12-10T12:53:14+00:00
    Session ID: c98a18797c0ad2ae196489865355620d
    Problem Page URL: /places/53cbf613eca9eb03a6009c85
    Previous Page URL: http://test2.freereg.org.uk/places?page=14
    Reported Issue:
    When the Genuki link is clicked on a Place page, you are
    navigated away from FreeREG when in general you would want to
    keep that page open. It would be better to open Genuki in a new
    browser tab/page. 

  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by Sherlock21** [comment]
I agree with the proposal in both cases

**Comment by FreeUKGenIssues** [comment]
I agree on the Genuki link, but there is an alternative for the problem bug
which I'd like to suggest for discussion:

We could retain the existing mechanism directing the user to a problem
screen, but add the ability to redirect them back to where they were upon
filing of the problem report.  (This could be accompanied by a "Thanks for
reporting this" success message.)

What do you think -- better?  Worse?

**Comment by edickens** [comment]
```
I think worse, because if I need to
  take a screen print, or to refer to what I was doing, if the
  preparation of the report is not in a new Tag then I can't see
  what I was doing.

  But you could still have a "Go back" for those with browsers that
  do not have tags or do not know how to use them.  And a "Thank
  You" to confirm that the message has been received is always
  useful.

  Eric
  _____________________________________
```

Eric J Dickens
FreeREG Chairman
      On 10/12/2014 16:51, FreeUKGenIssues wrote:

```
I agree on the Genuki link, but there is an
  alternative for the problem bug

  which I'd like to suggest for discussion:


  We could retain the existing mechanism directing the user to a
  problem

  screen, but add the ability to redirect them back to where they
  were upon

  filing of the problem report. (This could be accompanied by a
  "Thanks for

  reporting this" success message.)



  What do you think -- better? Worse?


  On Wed, Dec 10, 2014 at 10:11 AM, Sherlock21
  <notifications@github.com>

  wrote:


  > I agree with the proposal in both cases

  >

  > —

  > Reply to this email directly or view it on GitHub

  >
```

https://github.com/FreeUKGen/FreeUKGenProductIssues/issues/114#issuecomment-66475973
      > .

```
  >
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by Sherlock21** [comment]
Well, after you hit the snag, but before you  start up the Report a Problem, can't one take however many screen prints on needs first? park them on your desk top, then start to Report A Problem.

And then attach the already-made evidence from your desk top?
EricB

**Comment by FreeUKGenIssues** [comment]
I think that EricD's point is a good one. Whenever I report a problem or
log a bug, I'm generally doing research and gathering data as I compose the
problem report

**Comment by Captainkirkdawson** [comment]
Genuki now opens in a new window

**Comment by Sherlock21** [comment]
Thanks K, I like this option better than the original.
