### ISSUE TITLE
121961933 Too many images (some duplicate names) (Barrie)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1140]
Issue reported by **brobinson43** at 2018-11-12 14:18:53 UTC
Time: 2018-11-12T14:09:20+00:00
Session ID: bf3b5da7c394c39c15a16d44956695fa
Problem Page URL: [/image_server_groups/5be9809bf493fd7f01a05e6a/index](/image_server_groups/5be9809bf493fd7f01a05e6a/index)
Previous Page URL: [https://www.freereg.org.uk/image_server_groups/5be9815ff493fd7f01a064d8](https://www.freereg.org.uk/image_server_groups/5be9815ff493fd7f01a064d8)
Reported Issue:
According to my reckoning, I have uploaded approximately 304 images to Image Group Nuneaton St Nicolas PR/WAR_Nuneaton_St Nicolas_BA 1813-1823. This was in six groups of approximately 51 images each. However there are now supposed to be 508 images. Upon reading through the image names, they are all out of order, and at least two have identical names (they should all be in the range IMG_0030 to IMG_0333)    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/5be98bcdf493fd7f01a0d9ac/_old_)

**Comment by SteveBiggs** [comment]
This has also been experienced by another coordinator today:

Is it possible for you to delete the two files on the image server under Tunstead Holy Trinity please?  I've clearly done something wrong as I was uploading 202 images and seemed to have ended up with 500!

My problem with ending up with more images than I started when uploading to image serve has struck again.  I've 345 images for Liverpool Quaker births, I was so careful to make sure I only did it in batches of 60 and it was all going into the one file... but from somewhere unknown I seem to have acquired over 200 images as it says there are 584 images?

**Comment by edickens** [comment]
Tunstead is LAN

**Comment by Captainkirkdawson** [comment]
I have made a change to the way the image server connects to the app. Not easy for me to test. But let me know if issues continue.  @edickens can you do the cleanup of the files on the image server please

**Comment by edickens** [comment]
Will do.  But what change might I be looking out for?

**Comment by edickens** [comment]
Earlier today I uploaded images for Parish Register register for Parish Church in Belbroughton of Worcestershire and they uploaded correctly.  What now?

**Comment by edickens** [comment]
Interesting
I have deleted Parish Register register for Holy Trinity in Tunstead of Lancashire BA 1840-1881.
The first image #170 came up as "Successful and No file" but all the others deleted a file.  So there were no duplicates.  I did not count them but I don't think that there were that many hundreds of images.  It is just the count in the Image Group which was wrong.  It now shows zero.
But I had other problems.  When doing the first delete I got:-
![capture](https://user-images.githubusercontent.com/8876165/48427716-4927f700-e761-11e8-896e-12e7956542d1.JPG)
which  I eventually got around as it then said that I was not logged in when I was.  I logged in as a second copy and that got me going again.
Deleting is a slow process because it uploads after each delete the full list of images and the advertising.  So to start with it is 10 seconds an image but speeds up as the list gets shorter.  No need to change.  We don't use it often and we get the advertising revenue.

**Comment by edickens** [comment]
The other image group for this place shows 52 images.  There are 52 images, but the last one is blank...
![capture](https://user-images.githubusercontent.com/8876165/48428194-60b3af80-e762-11e8-9522-d84d78b47019.JPG)
These are in sequence which made it much easier to check.

**Comment by Captainkirkdawson** [comment]
@edickens  have tried forcing image server to communicate only with the master app server to see if that fixes the upload problem. My tests seem to work but who knows
That should avoid the insecure message and achieve the same goal.  On the blank one in your post just delete it

**Comment by edickens** [comment]
OK.  Will delete the other Tunstead and get Jo  to upload again.  E

**Comment by edickens** [comment]
No insecure messages now.

**Comment by Captainkirkdawson** [comment]
@edickens  You may want to sort out Barrie's mess too. TY

**Comment by edickens** [comment]
Problem  is still there.  After uploading 205 images Jo said that the count was 365, but now the IG says 525.  I have used BitKinex and there are only 205 images.

![capture](https://user-images.githubusercontent.com/8876165/48470338-11fd2880-e7e9-11e8-8197-73199fce9164.JPG)

Is the program getting the count from the wrong place?

**Comment by edickens** [comment]
I will sort out Barrie's when the problem if fixed.  Should we put out a general message to stop uploading?  Because other CCs do upload.

**Comment by Captainkirkdawson** [comment]
No it is not getting the count from the wrong place. The problem is caused by the image server app talking to a slave copy of the app at the end of an upload, which "crashes" because its a slave.  If i force it to the master we get the http message. Which really is not a problem but from a user perspective it is. Have yet to find an alternate way of the 2 apps talking

**Comment by Captainkirkdawson** [comment]
@edickens could you and Jo confirm it is working correctly. With the assistance of @lemon-ukgen we should always have the return from the image server go to the app on the master server.

**Comment by edickens** [comment]
Tomorrow I will upload an images group and report how it goes.

**Comment by edickens** [comment]
This has not worked.  I uploaded 56 images but the count shows 73.
![capture](https://user-images.githubusercontent.com/8876165/48658460-081e3400-ea3a-11e8-9834-b49d2e814a62.JPG)
The listing of the images is wrong too.  Images 50 to 66 are shown three times.  There are only 56 actual image files on the image server.
I will not do any more until instructed.

**Comment by edickens** [comment]
SOM is uploading.  I'm not going to stop them, but will have to sort it out later...

The transcriber has found the images on his computer! Though he says they were digitised by one of your predecessors. 

I'm in the process of uploading them to the image server,

Jackie

**Comment by Captainkirkdawson** [comment]
@edickens  I have made a coding change that hope against hope will put this to bed. Seems to work for me but I only do a small number

**Comment by edickens** [comment]
That seems to have worked.
I will have to delete yesterday's IG and upload again as that batch count is wrong.
Will do some more and keep a close watch.
I'll also have to check SOM who have been uploading.

**Comment by edickens** [comment]
I thought it was going so well.  But this group has duplicated.  So there are 305 images for this source listed but in reality there are only 282, which is what is on the image server and is what I uploaded.
![capture](https://user-images.githubusercontent.com/8876165/48713299-d4910480-ec07-11e8-9bba-128cb6fed445.JPG)
The other groups are OK.

**Comment by Captainkirkdawson** [comment]
@edickens  but when I go to that image server group it tells me there are just 56 mages in order with no duplicates. Have you made changes???????????????? If so how am I expected to diagnose any thing?????

**Comment by edickens** [comment]
Sorry wrong one.
Images of Image Group Brindle St Joseph Burials 1767-1823 of the Other Transcript register for St Joseph in Brindle of Lancashire 
46 sb 23

**Comment by Captainkirkdawson** [comment]
The same duplicated pair of images show

 "_id" : ObjectId("5bf2c451f493fd9056d48f09"),
        "consistency" : true,
        **"image_server_group_id" : ObjectId("5bec4f59f493fd443c94ec24")**,
        "image_file_name" : "LAN_Brindle_BU_282.jpg",
        "u_at" : ISODate("2018-11-19T14:10:25.462Z"),
        "c_at" : ISODate("2018-11-19T**14:10:25.462Z"**),
        "status" : "u"
"_id" : ObjectId("5bf2c469f493fd9056d48f25"),
        "consistency" : true,
        **"image_server_group_id" : ObjectId("5bec4f59f493fd443c94ec24"),**
        "image_file_name" : "LAN_Brindle_BU_282.jpg",
        "u_at" : ISODate(**"2018-11-19T14:10:49.864Z"**),
        "c_at" : ISODate("2018-11-19T14:10:49.864Z"),
        "status" : "u"

They were created 24 seconds apart

**The logs show**

**The upload was initiated**
Started GET "/image_server_groups/5bec4f59f493fd443c94ec24/upload" for 5.9.125.163 at 2018-11-19 **14:09:47** +0000
App 36950 stdout: Processing by ImageServerGroupsController#upload as HTML
Started GET "/image_server_groups/upload_return?register=5b67ad58f493fd46891be4a6&folder_name=Brindle%20St%20Joseph%20TR&**image_server_group=5bec4f59f493fd443c94ec24**&userid=5462b414e937907d7000035c&files_exist=%20&files_uploaded=LAN_Brindle_BU_282.jpg/%20LAN_Brindle_BU_283.jpg/%20LAN_Brindle_BU_284.jpg/%20LAN_Brindle_BU_285.jpg/%20LAN_Brindle_BU_286.jpg/%20LAN_Brindle_BU_287.jpg/%20LAN_Brindle_BU_288.jpg/%20LAN_Brindle_BU_289.jpg/%20LAN_Brindle_BU_290.jpg/%20LAN_Brindle_BU_291.jpg/%20LAN_Brindle_BU_292.jpg/%20LAN_Brindle_BU_293.jpg/%20LAN_Brindle_BU_294.jpg/%20LAN_Brindle_BU_295.jpg/%20LAN_Brindle_BU_296.jpg/%20LAN_Brindle_BU_297.jpg/%20LAN_Brindle_BU_298.jpg/%20LAN_Brindle_BU_299.jpg/%20LAN_Brindle_BU_300.jpg/%20LAN_Brindle_BU_301.jpg/%20LAN_Brindle_BU_302.jpg/%20LAN_Brindle_BU_303.jpg/%20LAN_Brindle_BU_304.jpg" for 5.9.125.163 **at 2018-11-19 14:10:25** +0000

Then there was the acknowledgement of the upload 43 seconds later.

Started GET "/**image_server_groups/5bec4f59f493fd443c94ec24**" for 5.9.125.163 at 2018-11-19 **14:10:30 +0000**
Processing by ImageServerGroupsController#show as HTML

Followed by
Started GET "/**image_server_groups/5bec4f59f493fd443c94ec24**/initialize_status? 
 type=allocate+accept" for 5.9.125.163 **at 2018-11-19 14:10:47** +0000
 Processing by ImageServerGroupsController#initialize_status as HTML
Immedaitely following the display of image_server_groups/initialize_status.html
was the second processing of
Started GET "/image_server_groups/upload_return?register=5b67ad58f493fd46891be4a6&folder_name=Brindle%20St%20Joseph%20TR&**image_server_group=5bec4f59f493fd443c94ec24**&userid=5462b414e937907d7000035c&files_exist=%20&files_uploaded=LAN_Brindle_BU_282.jpg/%20LAN_Brindle_BU_283.jpg/%20LAN_Brindle_BU_284.jpg/%20LAN_Brindle_BU_285.jpg/%20LAN_Brindle_BU_286.jpg/%20LAN_Brindle_BU_287.jpg/%20LAN_Brindle_BU_288.jpg/%20LAN_Brindle_BU_289.jpg/%20LAN_Brindle_BU_290.jpg/%20LAN_Brindle_BU_291.jpg/%20LAN_Brindle_BU_292.jpg/%20LAN_Brindle_BU_293.jpg/%20LAN_Brindle_BU_294.jpg/%20LAN_Brindle_BU_295.jpg/%20LAN_Brindle_BU_296.jpg/%20LAN_Brindle_BU_297.jpg/%20LAN_Brindle_BU_298.jpg/%20LAN_Brindle_BU_299.jpg/%20LAN_Brindle_BU_300.jpg/%20LAN_Brindle_BU_301.jpg/%20LAN_Brindle_BU_302.jpg/%20LAN_Brindle_BU_303.jpg/%20LAN_Brindle_BU_304.jpg" for 5.9.125.163 **at 2018-11-19 14:10:49** +0000

Summary.
There was only one attempt in the timeframe to upload these files.
It took just 43 seconds to upload the 23 images on the IS server and return the result to the FR app. This was followed by a show of the group and immediately there after an initialization.
This was followed by the second processing of the upload_return.
Question was there a back between, was there a use of the breadcrumbs to get to the show

**Comment by edickens** [comment]
That was about the length of time it took to upload the images in that image group.

**Comment by Captainkirkdawson** [comment]
A further example of incorrect results from Jo

Show It uploaded and returned as normal

Started GET "/image_server_groups/upload_return?register=5b58abb6f493fd3f54ffe811&folder_name=Liverpool%20Quakers%20OR&image_server_group=5bf335d2f493fd9056d76dad&userid=5462b410e937907d700002b7&files_exist=334.jpg/%20261.jpg/%20262.jpg/%20263.jpg/%20264.jpg/%20265.jpg/%20266.jpg/%20267.jpg/%20268.jpg/%20269.jpg/%20270.jpg/%20271.jpg/%20272.jpg/%20273.jpg/%20274.jpg/%20275.jpg/%20276.jpg/%20277.jpg/%20278.jpg/%20279.jpg/%20280.jpg/%20281.jpg/%20282.jpg/%20283.jpg/%20284.jpg/%20285.jpg/%20286.jpg/%20287.jpg/%20288.jpg/%20289.jpg/%20290.jpg/%20291.jpg/%20292.jpg/%20293.jpg/%20294.jpg/%20295.jpg/%20296.jpg/%20297.jpg/%20298.jpg/%20299.jpg/%20300.jpg/%20301.jpg/%20302.jpg/%20303.jpg/%20304.jpg/%20305.jpg/%20306.jpg/%20307.jpg/%20308.jpg/%20309.jpg/%20310.jpg/%20311.jpg/%20312.jpg/%20313.jpg/%20314.jpg/%20315.jpg/%20316.jpg/%20317.jpg/%20318.jpg/%20319.jpg/%20320.jpg/%20321.jpg/%20322.jpg/%20323.jpg/%20324.jpg/%20325.jpg/%20326.jpg/%20327.jpg/%20328.jpg/%20329.jpg/%20330.jpg/%20331.jpg/%20332.jpg/%20333.jpg&files_uploaded=%20" for 5.9.125.163 at 2018-11-19 22:19:49 +0000
App 36950 stdout: Processing by ImageServerGroupsController#upload_return as HTML

That was followed 4 seconds later by
Started GET "/image_server_groups/5bf335d2f493fd9056d76dad" for 5.9.125.163 at 2018-11-19 22:19:53 +0000
App 36950 stdout: Processing by ImageServerGroupsController#show as HTML

And then 5 seconds larer by
Started GET "/image_server_groups/5bf335d2f493fd9056d76dad/edit" for 5.9.125.163 at 2018-11-19 22:19:58 +0000
App 36959 stdout: Processing by ImageServerGroupsController#edit as HTML

then 50 seconds a further show
Started GET "/image_server_groups/5bf335d2f493fd9056d76dad" for 5.9.125.163 at 2018-11-19 22:20:48 +0000
App 36950 stdout: Processing by ImageServerGroupsController#show as HTML

**Comment by Captainkirkdawson** [comment]
Both of these cases have one similarity that I can see and that is the the image server group document is being modified very soon  (within seconds) of the modifications to the group with the connection of many images. It is possible that the promulgation of the changes being made by the upload return are incomplete at the same the user is making further changes to the key document. Changes are meant to be applied to the database in order of arrival but?

**Comment by edickens** [comment]
That is very likely.
And when I delete, the message to say that the deletion has been successful does not get removed when the next action is requested.  So it is very easy to think that the action has completed when the message really applies to the one before.
Uploading and processing can take some time if the files are large.  There is a spinning wheel to show that things are working, but no message to say to wait until complete.

**Comment by Captainkirkdawson** [comment]
The further example of incorrect results from Jo in underreporting the uploads was a red herring and a user level problem. Hence my summary above is incorrect.

**Comment by Captainkirkdawson** [comment]
The duplication seen by Jo  on Liverpool Quakers Births took place on 12 Nov and was caused by  the upload_return script running on a secondary. This had been fixed. I will only research those issues for uploads taking place after the fix was put into place for that issue on Nov 16. I will look at a fix for existing occurrences

**Comment by Captainkirkdawson** [comment]
Have written and tested a rake task to detect and correct those groups with problems. Will take 2-3 hours to run. Does NOT prevent occurrence of problem.

**Comment by Captainkirkdawson** [comment]
The rake task was run on the evening of 21 Nov and it cleared out the duplicated image entries in the database. A report on where the issues appeared has been sent to ericD.
The issue on what caused the Brindle duplication remains uncorrected.

**Comment by Captainkirkdawson** [comment]
@edickens Have been able to consistently reproduce the duplication. It is caused by refreshing the page that displays the result of the upload. Now to find out how to stop that.

**Comment by Captainkirkdawson** [comment]
Have written a refresh trap and  it is no longer duplicating.
Also no longer create an empty entry on an upload with no uploaded files.
Have changed the colour of the duplicated list to red
Deployed to test3 and currently deploying to colobus

**Comment by edickens** [comment]
I have uploaded a lot of LAN Samlesbury with no problems.
But while doing this it has struck me that could the problem occur when a request is made to upload too many images in one go.  The red error message comes back and you then have to choose a smaller batch.  I think now that I may have done this when the error came up for me last time in LAN Brindle.
If I select a batch that is too big, it seems to upload all the images before it tells me that the batch is too big.  Is this when the details of that batch need to be cleared before the reduced size batch is uploaded?

**Comment by Captainkirkdawson** [comment]
In response to your email. The rake task will have resolved duplicates. People who have experienced this issue should be informed that it has been resolved.
In response to your post I do not believe your suggested issue is the cause of any problem.

**Comment by edickens** [comment]
Thanks Kirk.  Just a long shot.  I'll notify the CCs.
