### ISSUE TITLE
123170744 List images is not sorting to Filename order (Eric)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1141]
Issue reported by **REGManager** at 2018-11-26 14:05:44 UTC
Time: 2018-11-26T14:01:06+00:00
Session ID: f4bb93c98ba5e2976bd55cc22b1739a5
Problem Page URL: [/image_server_images/5bf335d2f493fd9056d76dad/index](/image_server_images/5bf335d2f493fd9056d76dad/index)
Previous Page URL: [https://www.freereg.org.uk/image_server_images/5bf335d2f493fd9056d76dad/index](https://www.freereg.org.uk/image_server_images/5bf335d2f493fd9056d76dad/index)
Reported Issue:
And there is no sort option.

http://www13.freereg.org.uk/uploads/feedback/screenshot/5bfbfdb8f493fd17246230b2/Capture.JPG    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/5bfbfdb8f493fd17246230b2/Capture.JPG)

**Comment by Captainkirkdawson** [comment]
fixed and deployed to test3
