### ISSUE TITLE
123711813 Cannot convert to an issue (Stephen)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1142]
Issue reported by **SBManager** at 2018-12-02 20:23:33 UTC
Time: 2018-12-02T20:21:48+00:00
Session ID: a3dd51dc446a8205ade888e6838af116
Problem Page URL: [/contacts/5c040f4df493fd0566de378a](/contacts/5c040f4df493fd0566de378a)
Previous Page URL: [https://www.freereg.org.uk/contacts?](https://www.freereg.org.uk/contacts?)
Reported Issue:
I'm trying to convert this Contact to an issue and it's giving a 'Missing page' error.
http://www13.freereg.org.uk/uploads/feedback/screenshot/5c043f45f493fd0566df3609/Capture.jpg    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/5c043f45f493fd0566df3609/Capture.jpg)

**Comment by Captainkirkdawson** [comment]
Issue has been fixed  as part of the overall communications clean up and deployed to test3
