### ISSUE TITLE
123772795 Changing Register Type Code (Eric)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1143]
Issue reported by **REGManager** at 2018-12-03 13:19:55 UTC
Time: 2018-12-03T13:16:26+00:00
Session ID: 7360ac7db62e390da2e8fd3b73eeaad6
Problem Page URL: [/sources/5c04f8c5f493fd0566e20dfd](/sources/5c04f8c5f493fd0566e20dfd)
Previous Page URL: [https://www.freereg.org.uk/sources/5c04f8c5f493fd0566e20dfd/edit](https://www.freereg.org.uk/sources/5c04f8c5f493fd0566e20dfd/edit)
Reported Issue:
I created a Register Type of OT "Other Transcript" for LND Broad Street Austin Friars Dutch Church, but when I come to upload the images it reports it as TR.  When the transcription is done it will be uploaded as OT.  Confusing.
I appreciate that previously created Register Types may not match the latest coding,  but new ones should.    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/5c052d7bf493fd0566e32471/_old_)

**Comment by Captainkirkdawson** [comment]
There is only one internal code TR. OT does not exist as an internal code.
It is interpreted as Other Transcript to the world at large

**Comment by richpomfret** [comment]
Closing.
