### ISSUE TITLE
120097220 Website Problem (Kinky Kirky)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1144]
Issue reported by **Kinky Kirky** at 2018-10-22 00:20:20 UTC
Time: 2018-10-22T00:19:10+00:00
Session ID: e87577072a1c97a917cf099aad4a423a
Problem Page URL: []()
Previous Page URL: [https://test3.freereg.org.uk/contacts/new](https://test3.freereg.org.uk/contacts/new)
Reported Issue:
This is a second test. I had deleted the first    

![Screenshot](http://test3.freereg.org.uk/uploads/contact/screenshot/5bcd17c4e93790caeceb119d/_old_)

**Comment by Captainkirkdawson** [comment]
This was a contact converted to an issue t test the fix for #1142 above
