### ISSUE TITLE
123953365 Image listed as being present on image server but then said not to exist (Mary)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1145]
Issue reported by **MaryKay** at 2018-12-05 15:29:25 UTC
Time: 2018-12-05T15:25:58+00:00
Session ID: 52ac55f33aaab120284bc3a9ee5846a0
Problem Page URL: [/image_server_images/5a9ebc60f493fdbfcb9393df/index](/image_server_images/5a9ebc60f493fdbfcb9393df/index)
Previous Page URL: [https://www.freereg.org.uk/image_server_groups/5a9ebc5ff493fdbfcb939329/index](https://www.freereg.org.uk/image_server_groups/5a9ebc5ff493fdbfcb939329/index)
Reported Issue:
In order to answer a query I want to look at HUN-Southoe-GR-1558-1671-007549339_00763.jpg
If I list the images for this register, it is shown.  If I attempt to download this, I get this message 'There was a problem with your request. There is no file HUN-Southoe-GR-1558-1671-007549339_00763.jpg '
    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/5c07eed5f493fd0566f1acd6/_old_)

E0 U2 S8 7: P17

**Comment by SteveBiggs** [comment]
Appears to be a linkage problem because the image is viewable via direct access through 'Manage Image Server'

**Comment by Captainkirkdawson** [comment]
@edickens The Problem is caused by there being 2 physical folders on the image server for Southoe. 
One is called Southoe PR and the other is called Southoe_converted PR. 
Whereas there is only one image server source  PR. Hence the app is looking for the file in the folder Southoe PR and it is not there.
So the issue will exist for ALL the images in the files that are physically located in the Southoe-converted PR folder. They need to be moved to the Southoe PR folder.

**Comment by Captainkirkdawson** [comment]
I suspect there may be similar problems in other HUN places where there are 2 folders for the same register. eg Fenstanton,Yaxley

**Comment by Captainkirkdawson** [comment]
Solution is to copy the images into the Southoe PR folder

**Comment by richpomfret** [comment]
@edickens can you copy the images as Kirk suggests?

**Comment by edickens** [comment]
Fixed.
I Copied rather than Move, so the images are still in the second Folder.  Let me know if the original can now be deleted.
Are there other situations where this occurs?
How did this occur?  I suspect that it was the initial set up.

**Comment by Captainkirkdawson** [comment]
@edickens  Yes its fine. You may remove the converted folder.

Yes I expect there others. Its the initial conversion that caused it.

**Comment by edickens** [comment]
Done
Can be closed.
