### ISSUE TITLE
124280168 A wrong link after replying to a contact (Eric)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1148]
Issue reported by **REGManager** at 2018-12-09 10:16:08 UTC
Time: 2018-12-09T10:14:21+00:00
Session ID: af7910d1beaca54ca399cf1b1f614046
Problem Page URL: [/messages](/messages)
Previous Page URL: [https://www.freereg.org.uk/contacts/5c0baf9df493fdf0e1242ec2/reply](https://www.freereg.org.uk/contacts/5c0baf9df493fdf0e1242ec2/reply)
Reported Issue:
I got the attached after replying to 124199325
http://www13.freereg.org.uk/uploads/feedback/screenshot/5c0ceb68f493fdf0e12ad6f3/Capture.JPG    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/5c0ceb68f493fdf0e12ad6f3/Capture.JPG)

**Comment by Captainkirkdawson** [comment]
The contact system need a tweak to be compatible with the message changes. Deployed to master as an urgent fix
