### ISSUE TITLE
124280739 Unable to remove a message from my login page list (Eric)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1149]
Issue reported by **REGManager** at 2018-12-09 10:25:39 UTC
Time: 2018-12-09T10:22:50+00:00
Session ID: af7910d1beaca54ca399cf1b1f614046
Problem Page URL: [/manage_resources/new](/manage_resources/new)
Previous Page URL: [https://www.freereg.org.uk/feedbacks/5b573276f493fd6b3e82fa16](https://www.freereg.org.uk/feedbacks/5b573276f493fd6b3e82fa16)
Reported Issue:
I have SH the message, then Archived it, then SH again, and then tried Destroy.  But it is still in my list to look although it has been destroyed.
See attached.
http://www13.freereg.org.uk/uploads/feedback/screenshot/5c0ceda3f493fdf0e12ae17b/Capture1.JPG    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/5c0ceda3f493fdf0e12ae17b/Capture1.JPG)

**Comment by Captainkirkdawson** [comment]
I had forgotten to remove the display code. Fixed and deployed to master with #1148
