### ISSUE TITLE
Routing Error (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#115]
Issue reported by **REGManager** at 2014-12-14 15:36:11 UTC
Time: 2014-12-14T15:31:52+00:00
Session ID: 2585ae834ef6cc16e8a1f638d7856345
Problem Page URL: [/freereg_contents/new](/freereg_contents/new)
Previous Page URL: [http://test2.freereg.org.uk/search_queries/new](http://test2.freereg.org.uk/search_queries/new)
Reported Issue:
With the DAP, no matter which county I select, I get a routing error.

I don't know if this is to do with Firefox, which I use.  I have just had an email about a FR1 problem following a Firefox update, and I will forward that message to Kirk separately.

I can't do a screen print without losing this report - the reason for asking for the Report a Problem to be a separate tab.    

![Screenshot](http://test2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
The first response should be that there is insufficient information on
which to do any diagnosis.

Nor does the statement about doing a screenshot seem valid. The "best"
practice is to make your screenshot before initiating the Reporting of a
Problem.

I suspect you are not selecting a place from the list of places. This is
mandatory. Will add a test and error message,

This nothing to do with Firefox. Our code is checked against the 4 main
browsers.

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by edickens** [comment]
```
Hi Kirk,

  I was just looking at "Data on the database content" and you are
  correct, I had not selected a place!

  E
  _____________________________________
```

Eric J Dickens
FreeREG Chairman
      On 14/12/2014 16:03, Kirk Dawson wrote:

```
The first response should be that there is
  insufficient information on

  which to do any diagnosis.


  Nor does the statement about doing a screenshot seem valid. The
  "best"

  practice is to make your screenshot before initiating the
  Reporting of a

  Problem.


  I suspect you are not selecting a place from the list of places.
  This is

  mandatory. Will add a test and error message,


  This nothing to do with Firefox. Our code is checked against the 4
  main

  browsers.



  Kirk Dawson

  Fairmont Hot Springs, B.C.

  V0B 1L1


  On Sun, Dec 14, 2014 at 8:36 AM, FreeUKGenIssues
  <notifications@github.com>

  wrote:

  >

  > Issue reported by *REGManager* at 2014-12-14 15:36:11 UTC

  > Time: 2014-12-14T15:31:52+00:00

  > Session ID: 2585ae834ef6cc16e8a1f638d7856345

  > Problem Page URL: /freereg_contents/new

  > Previous Page URL:
  http://test2.freereg.org.uk/search_queries/new

  > Reported Issue:

  > With the DAP, no matter which county I select, I get a
  routing error.

  >

  > I don't know if this is to do with Firefox, which I use. I
  have just had

  > an email about a FR1 problem following a Firefox update, and
  I will forward

  > that message to Kirk separately.

  >

  > I can't do a screen print without losing this report - the
  reason for

  > asking for the Report a Problem to be a separate tab.

  >

  > [image: Screenshot]

  >
```

https://camo.githubusercontent.com/a7c8fb6673d738b70608d7fd478267f9bda898d4/687474703a2f2f74657374322e667265657265672e6f72672e756b
      >

```
  > —

  > Reply to this email directly or view it on GitHub

  >
  <https://github.com/FreeUKGen/FreeUKGenProductIssues/issues/115>.

  >
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by Captainkirkdawson** [comment]
Have added a check so this does not occur again
