### ISSUE TITLE
124460587 When uploading images, spaces are converted to underscore (Eric)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1150]
Issue reported by **REGManager** at 2018-12-11 12:23:07 UTC
Time: 2018-12-11T12:16:37+00:00
Session ID: 6869c450267512b55dbe6a64851d7477
Problem Page URL: [/image_server_images/5c0fa7d6f493fd82b061bc8d/index](/image_server_images/5c0fa7d6f493fd82b061bc8d/index)
Previous Page URL: [https://www.freereg.org.uk/image_server_groups/5c0fa7d6f493fd82b061bc8d](https://www.freereg.org.uk/image_server_groups/5c0fa7d6f493fd82b061bc8d)
Reported Issue:
See attached.
When uploading images, spaces in the filename are being converted to Underscore.  Is this a change, or have I just not noticed?  Not really a problem,  but why?  Getscan did not like spaces, but we do not use it now.
Also, # is being ignored.
If it is not too difficult, I suggest that this conversion is removed and filenames are accepted as uploaded.

http://www13.freereg.org.uk/uploads/feedback/screenshot/5c0fac2bf493fd82b061cceb/Capture.JPG    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/5c0fac2bf493fd82b061cceb/Capture.JPG)

**Comment by Captainkirkdawson** [comment]
The characters permitted in a filename or folder name varies from operating system to operating system. So called special characters create unique problems and are best avoided. 
Special characters include spaces, <, >, |, \, :, (, ), &, ;, #, as well as wildcards such as ? and *.

**Comment by edickens** [comment]
OK Leave as is and I'll try to avoid these.
The Image Group name accepts spaces.  The Source too, so that the folder name on the image server has spaces.
ED
