### ISSUE TITLE
124632233 Image count in Image Group does not agree (Eric)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1152]
Issue reported by **REGManager** at 2018-12-13 12:03:53 UTC
Time: 2018-12-13T12:01:49+00:00
Session ID: be1e64353aa0241340cd6dfb3bb27e87
Problem Page URL: [/image_server_groups/5c10fe8af493fdac0a29d7fd](/image_server_groups/5c10fe8af493fdac0a29d7fd)
Previous Page URL: [https://www.freereg.org.uk/image_server_images/5c10fe8af493fdac0a29d7fd/index](https://www.freereg.org.uk/image_server_images/5c10fe8af493fdac0a29d7fd/index)
Reported Issue:
I have uploaded 1015 images into: 
Image Group for the Image Server Source of the Other Register register for Southern Cemetery in Manchester of Lancashire, but the count says 1040.  I have not counted the images, but they are in sequence with no duplicates.    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/5c124aa9f493fdfc1b361d46/_old_)

**Comment by bev-fc** [comment]
Do you have a link to see this issue from test3?

**Comment by Captainkirkdawson** [comment]
The likely cause of the mismatch is that during the upload of one batch you used the back button and a refresh which caused a reprocess and the trap I wrote gave you a red screen error.

**Comment by edickens** [comment]
I don't remember that and definitely didn't get a red screen error.  I just worked steadily through the list.  The only thing I may have done, is, after selecting the images, I was not sure if I had chosen the correct ones, so would have selected Browse again.  It is interesting that the count is wrong by 25 and I upload in groups of 25, so your theory would fit.

**Comment by Captainkirkdawson** [comment]
Code change made and rake task updated to permit a single server group correction.
Deployed to test3

**Comment by Captainkirkdawson** [comment]
deployed to production
