### ISSUE TITLE
120679003 Data Problem (David Kirk Dawson)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1153]
Issue reported by **David Kirk Dawson** at 2018-10-28 17:56:43 UTC
Time: 2018-10-28T17:53:17+00:00
Session ID: acaf2052a3f96c34c75be6a933fd0154
Problem Page URL: [unknown](unknown)
Previous Page URL: [https://test3.freereg.org.uk/contacts/58ef50b4f493fd490b5291d1/report_error?query=5bd5f772e937904f51073d2a](https://test3.freereg.org.uk/contacts/58ef50b4f493fd490b5291d1/report_error?query=5bd5f772e937904f51073d2a)
Reported Issue:
Steve this is a test of the revised contacts reporting and reply system on test3. There is nothing wrong with the error but want to ensure you get the message as an action message and can then reply to me. A meaningless screenshot is attached
http://test3.freereg.org.uk/uploads/contact/screenshot/5bd5f85be937904f51073dc0/search.JPG    

![Screenshot](http://test3.freereg.org.uk/uploads/contact/screenshot/5bd5f85be937904f51073dc0/search.JPG)

**Comment by SteveBiggs** [comment]
This was a test from test3 and can be ignored.
