### ISSUE TITLE
125079563 Uploaded image count (Eric)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1156]
Issue reported by **REGManager** at 2018-12-18 16:19:23 UTC
Time: 2018-12-18T16:12:36+00:00
Session ID: 4fc031d79e140a84f7a4d65339304067
Problem Page URL: [/image_server_groups/5c178f16f493fd65bb80a20f](/image_server_groups/5c178f16f493fd65bb80a20f)
Previous Page URL: [https://www.freereg.org.uk/image_server_groups/upload_return?register=58336f1ff493fd5ea0c8e380&folder_name=Manchester%20Southern%20Cemetery%20OR&image_server_group=5c178f16f493fd65bb80a20f&userid=5462b414e937907d7000035c&files_exist=%20&files_uploaded=LAN-Manchester-SouthernCemetery-F22P2_0850.jpg/%20LAN-Manchester-SouthernCemetery-F22P2_0851.jpg/%20LAN-Manchester-SouthernCemetery-F22P2_0852.jpg/%20LAN-Manchester-SouthernCemetery-F22P2_0853.jpg/%20LAN-Manchester-SouthernCemetery-F22P2_0854.jpg/%20LAN-Manchester-SouthernCemetery-F22P2_0855.jpg/%20LAN-Manchester-SouthernCemetery-F22P2_0856.jpg/%20LAN-Manchester-SouthernCemetery-F22P2_0857.jpg/%20LAN-Manchester-SouthernCemetery-F22P2_0858.jpg/%20LAN-Manchester-SouthernCemetery-F22P2_0859.jpg/%20LAN-Manchester-SouthernCemetery-F22P2_0860.jpg/%20LAN-Manchester-SouthernCemetery-F22P2_0861.jpg/%20LAN-Manchester-SouthernCemetery-F22P2_0862.jpg/%20LAN-Manchester-SouthernCemetery-F22P2_0863.jpg/%20LAN-Manchester-SouthernCemetery-F22P2_0864.jpg/%20LAN-Manchester-SouthernCemetery-F22P2_0865.jpg/%20LAN-Manchester-SouthernCemetery-F22P2_0866.jpg/%20LAN-Manchester-SouthernCemetery-F22P2_0867.jpg/%20LAN-Manchester-SouthernCemetery-F22P2_0868.jpg/%20LAN-Manchester-SouthernCemetery-F22P2_0869.jpg/%20LAN-Manchester-SouthernCemetery-F22P2_0870.jpg/%20LAN-Manchester-SouthernCemetery-F22P2_0871.jpg/%20LAN-Manchester-SouthernCemetery-F22P2_0872.jpg/%20LAN-Manchester-SouthernCemetery-F22P2_0873.jpg/%20LAN-Manchester-SouthernCemetery-F22P2_0874.jpg](https://www.freereg.org.uk/image_server_groups/upload_return?register=58336f1ff493fd5ea0c8e380&folder_name=Manchester%20Southern%20Cemetery%20OR&image_server_group=5c178f16f493fd65bb80a20f&userid=5462b414e937907d7000035c&files_exist=%20&files_uploaded=LAN-Manchester-SouthernCemetery-F22P2_0850.jpg/%20LAN-Manchester-SouthernCemetery-F22P2_0851.jpg/%20LAN-Manchester-SouthernCemetery-F22P2_0852.jpg/%20LAN-Manchester-SouthernCemetery-F22P2_0853.jpg/%20LAN-Manchester-SouthernCemetery-F22P2_0854.jpg/%20LAN-Manchester-SouthernCemetery-F22P2_0855.jpg/%20LAN-Manchester-SouthernCemetery-F22P2_0856.jpg/%20LAN-Manchester-SouthernCemetery-F22P2_0857.jpg/%20LAN-Manchester-SouthernCemetery-F22P2_0858.jpg/%20LAN-Manchester-SouthernCemetery-F22P2_0859.jpg/%20LAN-Manchester-SouthernCemetery-F22P2_0860.jpg/%20LAN-Manchester-SouthernCemetery-F22P2_0861.jpg/%20LAN-Manchester-SouthernCemetery-F22P2_0862.jpg/%20LAN-Manchester-SouthernCemetery-F22P2_0863.jpg/%20LAN-Manchester-SouthernCemetery-F22P2_0864.jpg/%20LAN-Manchester-SouthernCemetery-F22P2_0865.jpg/%20LAN-Manchester-SouthernCemetery-F22P2_0866.jpg/%20LAN-Manchester-SouthernCemetery-F22P2_0867.jpg/%20LAN-Manchester-SouthernCemetery-F22P2_0868.jpg/%20LAN-Manchester-SouthernCemetery-F22P2_0869.jpg/%20LAN-Manchester-SouthernCemetery-F22P2_0870.jpg/%20LAN-Manchester-SouthernCemetery-F22P2_0871.jpg/%20LAN-Manchester-SouthernCemetery-F22P2_0872.jpg/%20LAN-Manchester-SouthernCemetery-F22P2_0873.jpg/%20LAN-Manchester-SouthernCemetery-F22P2_0874.jpg)
Reported Issue:
This problem may have been fixed but not pushed to production.
But I now have firm evidence of what happens.
If I make a mistake and ask for the same image to be uploaded again, this correctly rejects the duplicate.  But the count of images is not corrected.  In fact the whole batch is counted twice.
For example, if I upload a batch of 25 images, and just one of them is a duplicate, 24 images are accepted but  the image count goes up by 24 + 25 = 49.
I don't know if this is of any help in identifying the problem.
The image group image count remains wrong for ever.    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/5c191e0bf493fdb4fb7a1618/_old_)

E0 U6 S7 C6: P19

**Comment by Captainkirkdawson** [comment]
Needs to be extracted from software update branch
