### ISSUE TITLE
125147729 Not obvious attachment (Staffordshire)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1157]
Issue reported by **STSCoord** at 2018-12-19 11:15:29 UTC
Time: 2018-12-19T11:12:16+00:00
Session ID: 91bafebe090df999601ccb0eb3926036
Problem Page URL: [/messages/5c18fb2df493fdb4fb790811?source=userid_messages](/messages/5c18fb2df493fdb4fb790811?source=userid_messages)
Previous Page URL: [https://www.freereg.org.uk/messages/userid_messages](https://www.freereg.org.uk/messages/userid_messages)
Reported Issue:
In the messaging system, it is not obvious where an attachment is and how to get at it. Maybe the text that needs to be pressed should be made into a button? It would certainly be more obvious on the screen.    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/5c1a2851f493fd69cb91954b/_old_)

**Comment by Captainkirkdawson** [comment]
Improvements made and committed for testing in test3
