### ISSUE TITLE
125193800 Latter or later? (Staffordshire)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1158]
Issue reported by **STSCoord** at 2018-12-20 00:03:20 UTC
Time: 2018-12-20T00:00:06+00:00
Session ID: 4cf6337ea5b63bfceb4f641876f0b8d8
Problem Page URL: [/image_server_groups/5a9ecc4ef493fdbfcb9aae2a/edit](/image_server_groups/5a9ecc4ef493fdbfcb9aae2a/edit)
Previous Page URL: [https://www.freereg.org.uk/image_server_groups/5a9ecc4df493fdbfcb9aadef/index](https://www.freereg.org.uk/image_server_groups/5a9ecc4df493fdbfcb9aadef/index)
Reported Issue:
Error text shows "latter" twice but it should be "later" (one "t" instead of two)
http://www13.freereg.org.uk/uploads/feedback/screenshot/5c1adc48f493fd69cb94ddbe/Capture.JPG    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/5c1adc48f493fd69cb94ddbe/Capture.JPG)

**Comment by Captainkirkdawson** [comment]
Done as part of #1745
