### ISSUE TITLE
Clicking on Search details gives a routing error (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#116]
Issue reported by **REGManager** at 2014-12-16 17:21:08 UTC
Time: 2014-12-16T17:16:50+00:00
Session ID: efed74467a0993bdbd3e46ae87785568
Problem Page URL: [/search_queries/54906902e937903624000001](/search_queries/54906902e937903624000001)
Previous Page URL: [http://test2.freereg.org.uk/search_queries/new](http://test2.freereg.org.uk/search_queries/new)
Reported Issue:
I was searching for Dickens, Somerset, 1820, 1840, MA.  Gives one result.  Then clicked details.
I was looking to see if we have added "Save to your computer" yet.    

![Screenshot](http://test2.freereg.org.uk/uploads/feedback/screenshot/54906a04e937903624000003/Capture.JPG)

**Comment by Captainkirkdawson** [comment]
It was caused by the "Next Record" function going out of bounds. This has been fixed.
