### ISSUE TITLE
126392331 Testing feedback (Captainkirk)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1160]
Issue reported by **CaptainKirkNorfolk** at 2019-01-02 20:58:51 UTC
Time: 2019-01-02T20:58:10+00:00
Session ID: c1ed36b7f65d66c579d2efa5e8c7a499
Problem Page URL: [/manage_resources/new](/manage_resources/new)
Previous Page URL: [https://test3.freereg.org.uk/cms/refinery/login](https://test3.freereg.org.uk/cms/refinery/login)
Reported Issue:
a test feeback
http://test3.freereg.org.uk/uploads/feedback/screenshot/5c2d260be93790aa8941b1f0/ethiopia_map.gif    

![Screenshot](http://test3.freereg.org.uk/uploads/feedback/screenshot/5c2d260be93790aa8941b1f0/ethiopia_map.gif)

**Comment by Captainkirkdawson** [comment]
was a test
