### ISSUE TITLE
125602628 Data Problem (Simon Pickering)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1161]
Issue reported by **Simon Pickering** at 2018-12-24 17:37:08 UTC
Time: 2018-12-24T17:36:40+00:00
Session ID: 66328a57ddd814b9f901cba67b1582f4
Problem Page URL: [unknown](unknown)
Previous Page URL: [https://www.freereg.org.uk/contacts/58181115e93790ec8bab03fc/report_error?query=5c20e9bdf4040be5936861e1](https://www.freereg.org.uk/contacts/58181115e93790ec8bab03fc/report_error?query=5c20e9bdf4040be5936861e1)
Reported Issue:
You have the baptism date BEFORE the birth date    

![Screenshot](http://www.freereg.org.uk/uploads/contact/screenshot/5c211944f493fd11711d01a1/_old_)

**Comment by Captainkirkdawson** [comment]
I do not know why this was converted from a data problem to an issue.

**Comment by richpomfret** [comment]
Disregarding.
