### ISSUE TITLE
127168604 Action info bubble contains unavailable actions (Stephen)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1162]
Issue reported by **steveroland** at 2019-01-11 20:36:44 UTC
Time: 2019-01-11T20:32:57+00:00
Session ID: 2e7c21264039696df81bfd522a083528
Problem Page URL: [/image_server_groups/5a9ec700f493fdbfcb98ea45/index](/image_server_groups/5a9ec700f493fdbfcb98ea45/index)
Previous Page URL: [https://www.freereg.org.uk/sources/5a9ec700f493fdbfcb98ea45?image_group_filter=](https://www.freereg.org.uk/sources/5a9ec700f493fdbfcb98ea45?image_group_filter=)
Reported Issue:
Hovering over the Action 'i' button lists available actions and includes AL and RJ which are not available from this page, so should be removed.
http://www13.freereg.org.uk/uploads/feedback/screenshot/5c38fe5cf493fd12df0f14d4/Untitled.png    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/5c38fe5cf493fd12df0f14d4/Untitled.png)

E0 U2 S8 C8: P18

**Comment by Captainkirkdawson** [comment]
Needs to be extracted from software update branch
