### ISSUE TITLE
Inability to log-in TEST3

### ISSUE THREAD

**Issue by richpomfret** [FreeUKGen/FreeUKRegProductIssues#1163]
Issue appears to be related to the recent software update.
Required by #1386

**Comment by Captainkirkdawson** [comment]
The issue did not appear on my server or cloud9 but only on test3.  test3 is freebsd while cloud9 is closer to linux. Issue was that the refinery user record no longer responded to the rails reader method. Had to access it through the hash instead. Chased a number of different rabbits before that sunk in!!
Fix deployed

**Comment by Captainkirkdawson** [comment]
This is a symptom of a fundamental problem with the software_update. 

My "fix" simply kicked the issue downstream.
Specifically the absence of ruby reader writers for the refinery_authentiation_devise_user model class

**Comment by Captainkirkdawson** [comment]
Have added @Vino-S  as the assignee in recognition of her breaking down the wall with a solution I could never have dreamed of. 
deployed to test3
