### ISSUE TITLE
128079780 Message 127964886 not received from Kirk (Eric)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1164]
Issue reported by **nejws05** at 2019-01-22 09:43:00 UTC
Time: 2019-01-22T09:38:05+00:00
Session ID: f917a0daa8e94e43c9673b747e550e8f
Problem Page URL: [/messages/userid_messages](/messages/userid_messages)
Previous Page URL: [https://www.freereg.org.uk/manage_resources/new](https://www.freereg.org.uk/manage_resources/new)
Reported Issue:
Message 127964886 advised sent 21/1/19
Has not appeared on my Freereg
NEJWS05
Eric Wealleans
Coordinator Northumberland
    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/5c46e5a4f493fd077ab813fb/_old_)

**Comment by Captainkirkdawson** [comment]
Explained to Him need to log into test3. He has now done so and is testing for us
