### ISSUE TITLE
128019285 Why can I not create a Church with a certain name? (Staffordshire)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1165]
Issue reported by **STSCoord** at 2019-01-21 16:54:45 UTC
Time: 2019-01-21T16:52:44+00:00
Session ID: 0d4bb05a10218c118fe6b354b5d13733
Problem Page URL: [/churches/5c45f8dcf493fde76bd6deb8](/churches/5c45f8dcf493fde76bd6deb8)
Previous Page URL: [https://www.freereg.org.uk/churches/new](https://www.freereg.org.uk/churches/new)
Reported Issue:
Every time I try to create a church called "St Pauls Road Wesleyan Methodist" the system creates "St Paul Road Wesleyan Methodist". West Smethwick.    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/5c45f955f493fde76bd6e02b/_old_)

**Comment by Captainkirkdawson** [comment]
Because we reduce all forms of plural to singular ie Pauls Paul's Pauls' will always be created as Paul.

Why? because we have had too many transcribers  using the variations for the same church. Then someone started creating the variations and suddenly we had 3 churches when there was only one

**Comment by Captainkirkdawson** [comment]
Replaced by #1789
