### ISSUE TITLE
128419913 Messages not accessible (Ali)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1167]
Issue reported by **alsibk** at 2019-01-26 08:11:53 UTC
Time: 2019-01-26T08:08:25+00:00
Session ID: f5bc283bd0b1782dfc92ffc4cd239f18
Problem Page URL: [/messages/userid_messages?locale=en](/messages/userid_messages?locale=en)
Previous Page URL: [https://www.freereg.org.uk/manage_resources/new?locale=en](https://www.freereg.org.uk/manage_resources/new?locale=en)
Reported Issue:
Can't retrieve messages received before 12 Jan    

![Screenshot](https://www.freereg.org.uk)

**Comment by SteveBiggs** [comment]
I couldn't reproduce with my CC login, but just tried with my Sys_Admin one and I get the same error.
Appears to be affecting certain userids?

**Comment by Captainkirkdawson** [comment]
@SteveBiggs  can you see this issue on test3? I have no old messages waiting to be read so cannot diagnose

**Comment by SteveBiggs** [comment]
I can read old messages on test3.

**Comment by Captainkirkdawson** [comment]
@SteveBiggs did you try both userids as above??

**Comment by SteveBiggs** [comment]
Works with both userids.

**Comment by Captainkirkdawson** [comment]
Propose no further action unless reappears

**Comment by Captainkirkdawson** [comment]
Removed this as being required by software update

**Comment by suffolkroots** [comment]
Still cannot retrieve older messages before 12 Jan

**Comment by SteveBiggs** [comment]
This was tested and working in test3, but is a problem now in production. Affects both my CC and Sys Admin userids.

**Comment by Captainkirkdawson** [comment]
@SteveBiggs  I need a little more information to get my head round the correct fix. Can you please give me a screenshot before you click a button and tell me what button  you are selecting.

**Comment by SteveBiggs** [comment]
If I click here:
![image](https://user-images.githubusercontent.com/25303607/52309524-50455680-2998-11e9-9ef2-41c2e0c0fb70.png)
I get the red error page

**Comment by SteveBiggs** [comment]
Click on any message pre-Jan 12th and you get:
![image](https://user-images.githubusercontent.com/25303607/52309687-da8dba80-2998-11e9-9193-86bb7d3b5a74.png)

**Comment by Captainkirkdawson** [comment]
@SteveBiggs  hat happens on a click of View Replies?

**Comment by SteveBiggs** [comment]
No, View Replies is OK, just Show has the problem.

**Comment by Captainkirkdawson** [comment]
Have applied a trial fix to production

**Comment by SteveBiggs** [comment]
Looks good to me now.
