### ISSUE TITLE
128423813 Missing parameters message (Eric)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1168]
Issue reported by **nejws05** at 2019-01-26 09:16:53 UTC
Time: 2019-01-26T09:11:43+00:00
Session ID: c4eea52c423217d5e1f20ae2b9eae9de
Problem Page URL: [/manage_counties/select_action?county=Northumberland&locale=en](/manage_counties/select_action?county=Northumberland&locale=en)
Previous Page URL: [https://www.freereg.org.uk/csvfiles/new](https://www.freereg.org.uk/csvfiles/new)
Reported Issue:
The following actions under Review batches bring up "Missing parameters" when selected.  batches with errors, batches by filename, userid then filename, batches most recent, batches oldest
NEJWS05. Eric Wealleans Coordinator Northumberland
    

![Screenshot](https://www.freereg.org.uk)
required by #1386

**Comment by SteveBiggs** [comment]
I've reproduced this - must have been missed during testing the new software release.

**Comment by Captainkirkdawson** [comment]
Fixed and deployed to test3
