### ISSUE TITLE
128508139 Create Image Group has disappeared (Eric)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1169]
Issue reported by **REGManager** at 2019-01-27 08:42:19 UTC
Time: 2019-01-27T08:39:57+00:00
Session ID: db17808b99ba50d551044805325a199d
Problem Page URL: [/sources/5c4ce322f493fd1e8dc739da?image_group_filter=&locale=en](/sources/5c4ce322f493fd1e8dc739da?image_group_filter=&locale=en)
Previous Page URL: [https://www.freereg.org.uk/sources/5c4ce322f493fd1e8dc739da?image_group_filter=&locale=en](https://www.freereg.org.uk/sources/5c4ce322f493fd1e8dc739da?image_group_filter=&locale=en)
Reported Issue:
See attachment.
Both Jo and I have the same problem.  We are trying to create the first image group for this Source.
https://www.freereg.org.uk/uploads/feedback/screenshot/5c4d6eebf493fd1e8dca2c10/Capture.JPG    

![Screenshot](https://www.freereg.org.uk)
Required by #1386

**Comment by Captainkirkdawson** [comment]
It has not disappeared; it would seem it was never there if there is no ISG to list

**Comment by Captainkirkdawson** [comment]
Resolved in test3
