### ISSUE TITLE
When creating a new Profile, the UserID is converted to all lowercase. (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#117]
Issue reported by **REGManager** at 2014-12-18 08:15:13 UTC
Time: 2014-12-18T08:05:43+00:00
Session ID: e50d927ca946e07879b0d4c85628f875
Problem Page URL: [/userid_details/options](/userid_details/options)
Previous Page URL: [http://test2.freereg.org.uk/manage_resources/new](http://test2.freereg.org.uk/manage_resources/new)
Reported Issue:
A new transcriber has registered in FR1 and I now have to enter that into FR2 so that any transcriptions match when the final update is done.  This transcriber chose "Sue" as a UserID, but it got set up as "sue", which is not a problem as a UserID is not case sensitive, but this will appear in reports.  Names starting lowercase look unusual.  so it is just the "Enter new UserID" that needs to retain the case.
And while on this subject, how are we going to ensure that someone chooses a sensible UserID?  There are lots of "Suex" but no "Sue", so this was accepted.  Although she was lucky as FR1 is case sensitive and we could have got a duplicate.  I do look out for it when they start registration, but it is not a good system.  Perhaps we need to look again at how a new volunteer chooses a UserID, and we should recommend a format.  Just "Sue" is not a good choice.    

![Screenshot](http://test2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Not sure this is really an issue. A userid is a Userid and case insensitive. The persons forename is Sue and is shown as Sue when used.
When registering we already include the following statement
"Avoid using your forename as it likely to have already been taken."

**Comment by edickens** [comment]
```
The point is that the UserID is not as
  typed in by the new volunteer.  If they are using their full name
  - say EricDickens - this will appear in reports as "ericdickens". 
  I don't see the need to convert to all lower case when they have
  entered something else.
  I agree that it makes no difference to the working of FR2.
  The statement to "Avoid using a forename" is not in FR1, so we
  will still get a few.
  EricD
  _____________________________________
```

Eric J Dickens
FreeREG Chairman
      On 19/12/2014 18:20, Kirk Dawson wrote:

```
  Not sure this is really an issue. A userid is a Userid and case
    insensitive. The persons forename is Sue and is shown as Sue
    when used.
    When registering we already include the following statement
    "Avoid using your forename as it likely to have already been
    taken."
  —
    Reply to this email directly or view
      it on GitHub.
```
