### ISSUE TITLE
129207067 Unable to edit/add witnesses to MA files (Eric)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1172]
Issue reported by **nejws05** at 2019-02-04 10:51:07 UTC
Time: 2019-02-04T10:47:07+00:00
Session ID: 94cb13406d25dd4a14be774a83203e6e
Problem Page URL: [/freereg1_csv_entries/54639b40e9379010fc8a912b/edit](/freereg1_csv_entries/54639b40e9379010fc8a912b/edit)
Previous Page URL: [https://www.freereg.org.uk/freereg1_csv_entries/54639b40e9379010fc8a912b](https://www.freereg.org.uk/freereg1_csv_entries/54639b40e9379010fc8a912b)
Reported Issue:
Unable to edit/add witnesses to MA files, all other fields come up as green editable boxes, witnesses as no colour, able to add  names but not uploaded.
Eric Wealleans
Coordinator Northumberland    

![Screenshot](https://www.freereg.org.uk/uploads/feedback/screenshot/5c58191bf493fdf08dccf34d/_old_)

p 0 9 6 6 :21

**Comment by SteveBiggs** [comment]
I have tested this in production and test3 and this problem exists in both.

**Comment by Captainkirkdawson** [comment]
Duplicate
See #1811

**Comment by Captainkirkdawson** [comment]
As noted in #1811 the issue is NOT as bad as might be anticipated. The entry IS updated. The search record IS correctly created.  A search with the witness option WILL return records with those records.
The issue is that the display of the entry does NOT show the updated.
If the EDIT of a record is used then it WILL include the updated fields.

**Comment by SteveBiggs** [comment]
Apologies, I didn't notice #1811.

**Comment by Captainkirkdawson** [comment]
1811 was closed and this left open

**Comment by Captainkirkdawson** [comment]
Fix applied to display of entry. Deployed to test3

**Comment by SteveBiggs** [comment]
An update to a witness does now show in the SH display, but the boxes are still white rather than green in the edit view.
![image](https://user-images.githubusercontent.com/25303607/54696523-e6d26f00-4b23-11e9-96cb-cfe43f0828f6.png)

**Comment by richpomfret** [comment]
@Captainkirkdawson to change the background for edit fields.

**Comment by Captainkirkdawson** [comment]
Done and deployed to test3

**Comment by SteveBiggs** [comment]
Tested and looks good.
