### ISSUE TITLE
129286730 Incomplete source (Eric)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1173]
Issue reported by **REGManager** at 2019-02-05 08:58:50 UTC
Time: 2019-02-05T08:56:39+00:00
Session ID: 19732492489c3ab2b99166fe9e102c57
Problem Page URL: [/manage_counties/selection?option=Manage%20Images](/manage_counties/selection?option=Manage%20Images)
Previous Page URL: [https://www.freereg.org.uk/manage_counties/selection?option=Manage%20Images](https://www.freereg.org.uk/manage_counties/selection?option=Manage%20Images)
Reported Issue:
I'm getting the attached message.  What does it mean and what can I do about it?  Sandra would like to delete this source.  ED
https://www.freereg.org.uk/uploads/feedback/screenshot/5c59504af493fdd93aa06274/Capture.JPG    

![Screenshot](https://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Fix found deployed to test3 and checked.
Deploying to production as critical error
