### ISSUE TITLE
129478264 Cannot Edit Image Source (Stephen)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1175]
Issue reported by **steveroland** at 2019-02-07 14:11:04 UTC
Time: 2019-02-07T14:08:36+00:00
Session ID: b8ec6759be0498bd7cf0481412c126b2
Problem Page URL: [/sources/5bb21c4cf493fd726885d757/edit?locale=en](/sources/5bb21c4cf493fd726885d757/edit?locale=en)
Previous Page URL: [https://www.freereg.org.uk/sources/5bb21c4cf493fd726885d757?image_group_filter=&locale=en](https://www.freereg.org.uk/sources/5bb21c4cf493fd726885d757?image_group_filter=&locale=en)
Reported Issue:
When I clicked 'Submit' it returned the red "Something is wrong ...." message.    

![Screenshot](https://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
The fix for this had already been written under #1829, It is awaiting deployment to production

**Comment by Captainkirkdawson** [comment]
Deployed
