### ISSUE TITLE
129478390 Cannot Create Image Groups (Stephen)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1176]
Issue reported by **steveroland** at 2019-02-07 14:13:10 UTC
Time: 2019-02-07T14:12:02+00:00
Session ID: b8ec6759be0498bd7cf0481412c126b2
Problem Page URL: [/image_server_groups/new?locale=en](/image_server_groups/new?locale=en)
Previous Page URL: [https://www.freereg.org.uk/image_server_groups/new?locale=en](https://www.freereg.org.uk/image_server_groups/new?locale=en)
Reported Issue:
See attached image.
https://www.freereg.org.uk/uploads/feedback/screenshot/5c5c3cf6f493fd259cbb47f6/Capture.jpg    

![Screenshot](https://www.freereg.org.uk)

**Comment by SteveBiggs** [comment]
Create image group now works as expected.
