### ISSUE TITLE
129563603 Download the extended fields gives error - Missing Page (Stephen)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1177]
Issue reported by **steveroland** at 2019-02-08 13:53:23 UTC
Time: 2019-02-08T13:49:59+00:00
Session ID: c8000991e6792f7d1b177075349ea8f5
Problem Page URL: [/cms/information-for-transcribers/flexible-csv-format/extended-baptism-fields](/cms/information-for-transcribers/flexible-csv-format/extended-baptism-fields)
Previous Page URL: [https://www.freereg.org.uk/cms/information-for-transcribers/flexible-csv-format](https://www.freereg.org.uk/cms/information-for-transcribers/flexible-csv-format)
Reported Issue:
The Flexible csv help is now live, but the links to the csv headers don't work.
https://www.freereg.org.uk/uploads/feedback/screenshot/5c5d89d3f493fd61116ef143/Capture.jpg    

![Screenshot](https://www.freereg.org.uk)

Needs #1371 to work correctly

**Comment by AlOneill** [comment]
Have commented to same effect (plus missing images) on issue #1371
It may be a question of which servers have been updated so far?

**Comment by Captainkirkdawson** [comment]
All servers get synced to the master mysql database hourly

**Comment by richpomfret** [comment]
To use as a specific test case - see refinery automation issue.
