### ISSUE TITLE
129630665 Move multiple Images failed (Barrie)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1178]
Issue reported by **brobinson43** at 2019-02-09 08:31:05 UTC
Time: 2019-02-09T08:14:51+00:00
Session ID: da84d612fd6dc39963add8def6d1922d
Problem Page URL: [/image_server_images/5c558740f493fdf092900a45/index?locale=en](/image_server_images/5c558740f493fdf092900a45/index?locale=en)
Previous Page URL: [https://www.freereg.org.uk/image_server_groups/5c558740f493fdf092900a45?locale=en](https://www.freereg.org.uk/image_server_groups/5c558740f493fdf092900a45?locale=en)
Reported Issue:
I accidentally uploaded some images to the wrong image group, and attempted to fix this by using Move Multiple Images. However the procedure failed.
The earliest screenshot shows the situation just before selecting the incorrectly placed images. The receiving image group was empty (and still is.)
The most recent screenshot attached shows the start of the wrong images, which were, naturally, unallocated. The rest had already been allocated.
After I'd selected the images to be moved (by clicking on the first one and Shift-clicking on the last) and then clicking on Submit, I then got an error message as shown in the third Screenshot, with the time stamp, 7:16:51 PM.

If the time information is necessary to you, it's Australian Eastern Daylight time which is UT +11 hours.
https://www.freereg.org.uk/uploads/feedback/screenshot/5c5e8fc9f493fd0e8e470745/Screen_shot_2019-02-09_at_7.16.51_PM.png    

![Screenshot](https://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Trial solution found. Error in error message. Deployed to test3 seems to work

**Comment by Captainkirkdawson** [comment]
Deployed to production
