### ISSUE TITLE
List of counties to show All (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#118]
Issue reported by **REGManager** at 2014-12-19 20:54:02 UTC
Time: 2014-12-19T20:52:31+00:00
Session ID: d3af8bbe80632b77cb7160a16172e72d
Problem Page URL: [/search_queries/new](/search_queries/new)
Previous Page URL: [http://test2.freereg.org.uk/manage_resources/new](http://test2.freereg.org.uk/manage_resources/new)
Reported Issue:
Can the blank entry at the top of any list say "All"?
EricD    

![Screenshot](http://test2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Do we want to encourage an all counties search? It will work and given a cut off on numbers of records it would not be too costly.

**Comment by benwbrum** [comment]
All counties search is very friendly for non-UK researchers.

My own genealogy shows me people who emigrated from England or Wales before 1750, so my ideal search would fill in forename, surname, and year range, but not county since I have no idea what part of the UK any if them came from.

This may be very different from the typical U K base researcher, but is common for the US and pre-1900 Commonwealth researchers.

**Comment by Captainkirkdawson** [comment]
It is currently permitted. You can select all counties.

Out of interest I tried smith and all counties nothing else. It timed out
at about 4 minutes.

I added a 1600-1601 criteria to smith and all counties. It completed in 4
minutes but with a max out on records.

Dawson timed out with no year boundary as did Brumfield!!!

Mind you with a 1500-1600 filter Brumfield came up with 1 match in about 30
seconds. My home town!!!!!!!!!!!!!

Joane BRUMFIELD
William WILLNOWE  Marriage  11 Jun 1583  Norfolk  Norwich
(St Peter Mancroft)
Interestingly similar  response time for  1600=1700 for which there were 29
Brumfields maily in the home counties

If we are to permit All then we need a) to have a time out control and/or
b) insist on a time range

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by edickens** [comment]
```
I'm not sure that we want to encourage
  it, but just having a blank in the table is confusing.  "All" is
  useful for marriages and burials, especially more recent ones, as
  people sometimes move far from where the family lives.  The number
  limit on searches will stop too much processing.
  EricD
  _____________________________________
```

Eric J Dickens
FreeREG Chairman
      On 01/01/2015 23:40, Kirk Dawson wrote:

```
  Do we want to encourage an all counties search? It will work
    and given a cut off on numbers of records it would not be too
    costly.
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by edickens** [comment]
```
I like the insistence of a date range
  when All (both county and place?) is selected.  Perhaps no more
  than 20 years?  The researcher usually knows this information.
  EricD
  _____________________________________
```

Eric J Dickens
FreeREG Chairman
      On 02/01/2015 02:01, Kirk Dawson wrote:

```
It is currently permitted. You can select all
  counties.


  Out of interest I tried smith and all counties nothing else. It
  timed out

  at about 4 minutes.


  I added a 1600-1601 criteria to smith and all counties. It
  completed in 4

  minutes but with a max out on records.


  Dawson timed out with no year boundary as did Brumfield!!!


  Mind you with a 1500-1600 filter Brumfield came up with 1 match in
  about 30

  seconds. My home town!!!!!!!!!!!!!


  Joane BRUMFIELD

  William WILLNOWE Marriage 11 Jun 1583 Norfolk Norwich

  (St Peter Mancroft)

  Interestingly similar response time for 1600=1700 for which there
  were 29

  Brumfields maily in the home counties


  If we are to permit All then we need a) to have a time out control
  and/or

  b) insist on a time range



  Kirk Dawson

  Fairmont Hot Springs, B.C.

  V0B 1L1


  On Thu, Jan 1, 2015 at 5:41 PM, Ben W. Brumfield
  <notifications@github.com>

  wrote:


  > All counties search is very friendly for non-UK researchers.

  >

  > My own genealogy shows me people who emigrated from England
  or Wales

  > before 1750, so my ideal search would fill in forename,
  surname, and year

  > range, but not county since I have no idea what part of the
  UK any if them

  > came from.

  >

  > This may be very different from the typical U K base
  researcher, but is

  > common for the US and pre-1900 Commonwealth researchers.

  >

  > Sent from my iPhone

  >

  > > On Jan 1, 2015, at 5:40 PM, Kirk Dawson
  <notifications@github.com>

  > wrote:

  > >

  > > Do we want to encourage an all counties search? It will
  work and given a

  > cut off on numbers of records it would not be too costly.

  > >

  > > —

  > > Reply to this email directly or view it on GitHub.

  > >

  >

  > —

  > Reply to this email directly or view it on GitHub

  >
```

https://github.com/FreeUKGen/FreeUKGenProductIssues/issues/118#issuecomment-68503793
      > .

```
  >
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by Sherlock21** [comment]
I can see there will be pressure from the general searcher, to increase the quantity limit of 250 records.   Against this position, one can very easily select any number more than 1 County as things are at present.
I would much prefer the coders work out a slick way of being able to increase the quantity of records per result,without affecting loadings, rather than do this task.

**Comment by Captainkirkdawson** [comment]
Was implemented
