### ISSUE TITLE
18 130751726 Problem uploading new images (Somerset)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1181]
Issue reported by **SOMCoord** at 2019-02-22 07:55:26 UTC
Time: 2019-02-22T07:50:52+00:00
Session ID: 0ec654fda2a7480263c8d9142a147635
Problem Page URL: [/image_server_groups/5c6d202af493fdc79ea194e8?locale=en](/image_server_groups/5c6d202af493fdc79ea194e8?locale=en)
Previous Page URL: [https://www.freereg.org.uk/image_server_groups/5c6d1b6af493fdc79ea135d0/index?locale=en](https://www.freereg.org.uk/image_server_groups/5c6d1b6af493fdc79ea135d0/index?locale=en)
Reported Issue:
I've tried 3 times (twice on Weds and just now) to upload some images to the server in the DT Register of Broadway St Aldhelm Somerset. Each time I've got the red error message which says go back to what you are doing but try to avoid doing  the same thing again. Which is a bit difficult as there is only 1 way to upload new images, and that is to upload them. 

So there is obviously a problem here, and I will desist until someone tells me otherwise. 

Jackie James Somerset Coord    

![Screenshot](https://www.freereg.org.uk)

E1, C4, S7, C6: P18

**Comment by SteveBiggs** [comment]
@edickens wrote:
The server has created a folder with register type DW, not DT:

![image](https://user-images.githubusercontent.com/25303607/53244342-86761c00-36a2-11e9-9c7c-b7dcf691b783.png)

I suspect the upload is trying to connect to a folder with DT.  I could change the folder name and ask Jackie to try again, but I think the programmers should look at this.  It is very likely to be the first DT to be uploaded.

**Comment by richpomfret** [comment]
@edickens to try changing the folder to DT for a short-term solution. Wider code fix required beyond that so the system can hande both.

**Comment by PatReynolds** [comment]
Is DW a code needed?  Was it a typo for DT (or is DT a typo for DW_?

**Comment by edickens** [comment]
Pat,
These are the codes:-
![capture](https://user-images.githubusercontent.com/8876165/53884348-4f452a80-4013-11e9-8e32-9362565d0964.JPG)
The  ones in brackets are what we used in FR1.
Eric

**Comment by PatReynolds** [comment]
Thanks for the info.  I can now prioritise.
