### ISSUE TITLE
131102722 Relocating register fails (Barrie)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1184]
Issue reported by **brobinson43** at 2019-02-26 09:25:22 UTC
Time: 2019-02-26T09:21:37+00:00
Session ID: 471384398f424527178815cf85235f5d
Problem Page URL: [/freereg1_csv_files/update_places?locale=en](/freereg1_csv_files/update_places?locale=en)
Previous Page URL: [https://www.freereg.org.uk/freereg1_csv_files/update_registers?church=5c52c0daf493fdf0928e9ca3](https://www.freereg.org.uk/freereg1_csv_files/update_registers?church=5c52c0daf493fdf0928e9ca3)
Reported Issue:
I have twice tried to relocate two batches from Nuneaton, St Nicholas,  Unspecified to Nuneaton, St Nicolas, Unspecified, in each case having selected the place, church and register, and the system keeps saying I have failed to select Register. I checked, and on the second ccasion at least, register Unspecified was selected.    

![Screenshot](https://www.freereg.org.uk)

E1, C4, S7, C7: P19

**Comment by SteveBiggs** [comment]
I tried the relocate and get the same result.

**Comment by SteveBiggs** [comment]
Same problem as previous Report under this subject, but with a different batch. So this time I have taken a screenshot: Unspecified is selected, but has not been singled out, so this is the cause of the problem. It's not choosing Unspecified when I select it. Barrie
![image](https://user-images.githubusercontent.com/25303607/53403806-3f42a080-39ac-11e9-9a68-67659bdda418.png)

**Comment by richpomfret** [comment]
Requires further testing.

**Comment by PatReynolds** [comment]
The relocation seems to be into an identical place (from and to Nuneaton, St Nicholas, Unspecified ).  Was the issue reported incorrectly, or have I misunderstood what was being done?

**Comment by SteveBiggs** [comment]
They are different church names, Pat. (St Nicholas and St Nicolas).

**Comment by PatReynolds** [comment]
Thanks for the info - I can now prioritise.

**Comment by Captainkirkdawson** [comment]
@SteveBiggs it would appear that Barrie has "solved" the problem as there are no  batches or unspecified registers associated with  St Nicholas for Nuneaton. 
I plan to have this closed unless you wish it pursued as a possible issue affecting no one.
My suspicion is that the unspecified type must be first changed to a valid register type and then moved.

**Comment by SteveBiggs** [comment]
Barrie was trying to move batches between different churches in the same place. It appears this is not supported.
Please confirm whether it should be possible to move batches between different churches in the same place.

**Comment by SteveBiggs** [comment]
I've updated my comment.

**Comment by Captainkirkdawson** [comment]
@SteveBiggs you cannot relocate a single batch to an unspecified register type period. 

Remember you can change all the batches in a register from one type to another by changing the register type.  eg unspecified to parish register or something else. 

You can also relocate all the batches in register from one church to another in the same place or another place.

You can also merge the same register types or churches for a place if the relocate creates "duplicates'

**Comment by SteveBiggs** [comment]
Thanks for the clarification @Captainkirkdawson . This can be closed.
