### ISSUE TITLE
131466045 I did not get message 131454346 (Eric)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1185]
Issue reported by **REGManager** at 2019-03-02 14:20:45 UTC
Time: 2019-03-02T14:14:25+00:00
Session ID: 47578b663ad87ee2876fd35f20015f57
Problem Page URL: [/manage_resources/new?locale=en](/manage_resources/new?locale=en)
Previous Page URL: [https://www.freereg.org.uk/cms/refinery/login](https://www.freereg.org.uk/cms/refinery/login)
Reported Issue:
Although I got a message to say that this message was waiting for me, it is not there nor when I select "Message System".

I assume it was for me (see attached) but there is no To:.

Viewing the source I get:-
Delivered-To: freereg.edickens@gmail.com
which is correct, although my website email for REGManager is Delivered-To: freereg.edickens+reg@gmail.com

Eric D
https://www.freereg.org.uk/uploads/feedback/screenshot/5c7a913df493fd00b6965692/Capture.JPG    

![Screenshot](https://www.freereg.org.uk)

**Comment by SteveBiggs** [comment]
Eric reports that he does not see ANY messages listed on his login page:
![image](https://user-images.githubusercontent.com/25303607/53683614-cf5d4e80-3cfa-11e9-8db5-886a3d210728.png)
He should see something like this:
![image](https://user-images.githubusercontent.com/25303607/53683622-e7cd6900-3cfa-11e9-947b-404c838ca508.png)

**Comment by richpomfret** [comment]
Explore what situations might cause this e.g. why the x messages box does not appear.
