### ISSUE TITLE
131976569 broken link (Corinne)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1187]
Issue reported by **chm** at 2019-03-08 12:09:29 UTC
Time: 2019-03-08T12:06:01+00:00
Session ID: 9e56d335a2f40c64da163ecd4ab87120
Problem Page URL: [/cms/information-for-transcribers](/cms/information-for-transcribers)
Previous Page URL: [https://www.freereg.org.uk/search_records/5c7f03ccf493fdf91eead7c7?locale=en&search_id=5c804d8ff493fd7710323f26&ucf=false](https://www.freereg.org.uk/search_records/5c7f03ccf493fdf91eead7c7?locale=en&search_id=5c804d8ff493fd7710323f26&ucf=false)
Reported Issue:
The Flexible CSV Format link in the Help Contents by Page section on https://www.freereg.org.uk/cms/information-for-transcribers is a broken link pointing to a page (https://www.freereg.org.uk/information-for-transcribers/flexible-csv-format) that doesn't exist and if I click on it I get an error message.    

![Screenshot](https://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
@AlOneill  there are 2 Flexible CSV format links on the Information for Transcribers page, The first one  works while the second does not. The first is in the side bar and is OK, The second is in the main text under the Help contents by page section.
This needs an urgent fix in production

**Comment by AlOneill** [comment]
@Captainkirkdawson Fixed on live — will do test3 now.

**Comment by AlOneill** [comment]
Not getting served any test3 pages — will try again tomorrow.

**Comment by Captainkirkdawson** [comment]
Currently test3 has a problem which I am looking at
Kirk Dawson
5220 Riverside Drive
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by AlOneill** [comment]
Now fixed also on test3.
