### ISSUE TITLE
23? 132060810 UCF records are not retrievable (Catherine Jury)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1188]
Issue reported by **Catherine Jury** at 2019-03-09 11:33:30 UTC
Time: 2019-03-09T11:10:14+00:00
Session ID: f0a707fe17be1c8cde6dd558a281bee0
Problem Page URL: []()
Previous Page URL: [https://www.freereg.org.uk/contacts/new](https://www.freereg.org.uk/contacts/new)
Reported Issue:
I have transcribed file CONSTIBA from a badly damaged register with appalling handwriting and spelling. There are some entries, which cannot be accessed via Freereg and yet are still possibly useful to a researcher.
To someone researching the surname Burres for example, two entries on this file would definitely be worth checking: '[B_]*' and '*[RI][IA]S'.
These are not currently searchable, even with wildcard & Soundex (although the first can be extracted by actually typing the UCF in the field, i.e. '[B_]*', but this is not user-friendly.
There are multiple similar entries starting with an asterisk or a UCF followed by an asterisk.
I have reported this a number of times, but have had no reply.    

![Screenshot](https://www.freereg.org.uk)
Depends on #1511

**Comment by Captainkirkdawson** [comment]
The basic code to retrieve UCF records has been written but the limited availability of the programers involved has stalled its implementation. At this time we have no estimate of when it might become available.

**Comment by Captainkirkdawson** [comment]
@SteveBiggs  to write back to researcher

**Comment by SteveBiggs** [comment]
Have written back to Cathy.
