### ISSUE TITLE
132059414 Wild card searches in soundex provide no results. (Catherine Jury)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1189]
Issue reported by **Catherine Jury** at 2019-03-09 11:10:14 UTC
Time: 2019-03-09T11:06:30+00:00
Session ID: f0a707fe17be1c8cde6dd558a281bee0
Problem Page URL: []()
Previous Page URL: [https://www.freereg.org.uk/contacts/new](https://www.freereg.org.uk/contacts/new)
Reported Issue:
Wildcard searches return nothing if they are used with a Soundex search. They also ignore the 'Last Year' field.   (latter issued moved to #1190) 

![Screenshot](https://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
This should be split into the 2 separate issues.
1. I would not expect soundex searches to work with wildcard characters they are 2 different concepts.
2, Wild card searches should respect the year limits. Need to confirm issue.

**Comment by PatReynolds** [comment]
Issue 2 now has its own story.

**Comment by Captainkirkdawson** [comment]
Could I suggest that we write back to Catherine who made the comment that we would not expect that a combination of these 2 very different techniques would work. Soundex assigns a numeric value to similar sounding letters. ; a wild card in that sense has no value. A wild card accepts any letter after the wildcard.
Perhaps the only action other than that is a note in the Help to that effect.

**Comment by SteveBiggs** [comment]
I have replied accordingly to Catherine. I will raise a new issue to get the Help updated.

**Comment by SteveBiggs** [comment]
#1861 raised for Help update. This issue can be closed.
