### ISSUE TITLE
132994021 View image works, but Delete image doesn't (Eric)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1193]
Issue reported by **REGManager** at 2019-03-20 06:47:01 UTC
Time: 2019-03-20T06:42:06+00:00
Session ID: 68999e596a773ba0dff54c7fb84e3a69
Problem Page URL: [/image_server_images/5be9811df493fd7f01a063c3/index?locale=en](/image_server_images/5be9811df493fd7f01a063c3/index?locale=en)
Previous Page URL: [https://www.freereg.org.uk/image_server_groups/5be9811df493fd7f01a063c3?locale=en](https://www.freereg.org.uk/image_server_groups/5be9811df493fd7f01a063c3?locale=en)
Reported Issue:
Red something has gone wrong screen.
See attached.
Take care because the spelling of the Church is important.
We need to delete the images that are of the format IMG_0030.jpg in WAR Nuneaton, St Nicholas
https://www.freereg.org.uk/uploads/feedback/screenshot/5c91e1e5f493fdc6401ee936/Capture.JPG    

![Screenshot](https://www.freereg.org.uk)

E 0, U6, S7, C7: P20

**Comment by Captainkirkdawson** [comment]
See errbit https://errbit.freeukgen.org.uk/apps/56297e8be93790333a000009/problems/5c642663e93790ed44f466a8

**Comment by Captainkirkdawson** [comment]
Fixed; was a spelling error; deploying to master and then colobus

**Comment by Captainkirkdawson** [comment]
@edickens  would you please confirm this is fixed

**Comment by edickens** [comment]
Yes.  Fixed.  TY.  ED
