### ISSUE TITLE
133169887 Witnesses to Baptisms (Eric)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1196]
Issue reported by **REGManager** at 2019-03-22 07:38:07 UTC
Time: 2019-03-22T07:34:56+00:00
Session ID: 0d8aaaa0b2292434760329fa191ff796
Problem Page URL: [/search_queries/new?locale=en](/search_queries/new?locale=en)
Previous Page URL: [https://www.freereg.org.uk/cms/information-for-transcribers/flexible-csv-format/extended-baptism-fields](https://www.freereg.org.uk/cms/information-for-transcribers/flexible-csv-format/extended-baptism-fields)
Reported Issue:
In the Search screen the help balloon against "Witnesses" says to "add witnesses to a marriage", but we now have witnesses to a Baptism under flexible CSV.
Does the search find these entries, and if so then the help balloon on the search screen needs to be changed.    

![Screenshot](https://www.freereg.org.uk)

E 0, U2, S5, C9: P16

**Comment by Captainkirkdawson** [comment]
We certainly create the witness  entries in the search record for a baptism.
I cannot recall if Ericb tested the retrieval in a search. If someone wishes to create a batch with such records and confirm it works then please so do.
It is a size 1 task to change the balloon. Perhaps longer to change documentation on the search.

**Comment by Captainkirkdawson** [comment]
The info bubble has been changed. Awaiting deployment.
