### ISSUE TITLE
133448550 CSVcheck error message (Denise)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1197]
Issue reported by **DenGage** at 2019-03-25 13:02:30 UTC
Time: 2019-03-25T13:01:07+00:00
Session ID: 41d4a14495a6a347bbd9311d14b91f42
Problem Page URL: [/search_queries/new?locale=en](/search_queries/new?locale=en)
Previous Page URL: [https://www.freereg.org.uk/manage_resources/new?locale=en](https://www.freereg.org.uk/manage_resources/new?locale=en)
Reported Issue:
Received on FreeUKGEN Contact form:

I am getting an error message in CSVcheck Fatal: row 2, File type switch does not match number of columns in data (0) all titles in column 2 must be non-blank I have been using csv check on this file for several weeks checking it regularly and never had a problem before. regards Keith (manicmongrel00@gmail.com)    

![Screenshot](https://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
@SteveBiggs could you tell me what this this person is talking about. I have not the foggiest idea

**Comment by FreecenBren** [comment]
The Row 2 and 3  have to have something in them for each column A to Y
inclusive.
CSVCHECK will fail otherwise.
Also if there is anything entered  in column Z  and onwards that will also
fail it.
This includes any digits or spaces added

I have written to Keith anyway

Brenda

**Comment by Captainkirkdawson** [comment]
Thank you  @FreecenBren.  you may ignore @SteveBiggs 
This should have been registered as an issue with FreeCEN and not FreeREG.
Since Brenda has responded to person I will close

**Comment by SteveBiggs** [comment]
@DeniseColbert raised it. I simply converted to issue as I do with any Feedback that I cannot answer directly.
