### ISSUE TITLE
133639204 Batches not linked (Eric)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1199]
Issue reported by **REGManager** at 2019-03-27 18:00:04 UTC
Time: 2019-03-27T17:58:00+00:00
Session ID: f19721b50572c220e8ec911453d438bb
Problem Page URL: [/registers/593f204bf493fd4a11cb4b47?locale=en](/registers/593f204bf493fd4a11cb4b47?locale=en)
Previous Page URL: [https://www.freereg.org.uk/registers/593f204bf493fd4a11cb4b47?locale=en](https://www.freereg.org.uk/registers/593f204bf493fd4a11cb4b47?locale=en)
Reported Issue:
Sandra had reported the attached.
Also MERLEABU2  Llanegryn St Mary and St Egryn 
https://www.freereg.org.uk/uploads/feedback/screenshot/5c9bba24f493fd63a5de1aed/Capture.JPG    

![Screenshot](https://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
The issue appears to be associated with ALL the files in MER. It appears that all the Places in MER have a county name of "Merioneth" where as the actual county name is "Merionethshire". Hence when a check is done to make sure the Place has a correct county name if fails.

**Comment by Captainkirkdawson** [comment]
The solution to this is in the hands of the coordinator.  As noted above all the Places in MER have a county name of 'Merioneth' At some point the MER county name was changed to 'Merionethshire'
Hence when we check to make sure that all names are in fact correct. See image which shows the conflict.![MER.JPG](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/9ca1090e-2826-4fc6-805c-3a9c913a3c22)
The solution is to use the Fill County and Country Fields action to assign the correct County name. This will be promulgated to  files in the Place.
In the case of MER this will apply to all Places

**Comment by Captainkirkdawson** [comment]
This is not the same issue as found in story #1203

**Comment by benwbrum** [comment]
No software changes needed; coordinator needs to be contacted to update county names.

**Comment by edickens** [comment]
All done.
