### ISSUE TITLE
i icon (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#120]
Issue reported by **REGManager** at 2014-12-19 21:06:01 UTC
Time: 2014-12-19T20:59:19+00:00
Session ID: d3af8bbe80632b77cb7160a16172e72d
Problem Page URL: [/search_queries/549491a6e937905d8f000012](/search_queries/549491a6e937905d8f000012)
Previous Page URL: [http://test2.freereg.org.uk/search_queries/5494916de937905d8f00000f](http://test2.freereg.org.uk/search_queries/5494916de937905d8f00000f)
Reported Issue:
I like the i icon.  I was going to say that it should be at the side of the column title as the balloon covers the column title, but I now see that it stops you accidentally selecting to sort the column.
My reason for the i is that with the i the balloons do not keep coming up and you only get them when you positively ask for them.  It is also easier to see where information is available.    

![Screenshot](http://test2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Included
