### ISSUE TITLE
133720126 "... files is locked" message (Staffordshire)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1200]
Issue reported by **STSCoord** at 2019-03-28 16:28:46 UTC
Time: 2019-03-28T16:15:55+00:00
Session ID: c8188275feec804f0083d6a07d2b1d76
Problem Page URL: [/freereg1_csv_files/5c74cc35f493fdba075f5454?locale=en](/freereg1_csv_files/5c74cc35f493fdba075f5454?locale=en)
Previous Page URL: [https://www.freereg.org.uk/freereg1_csv_entries/5c828f09f493fd4edf50c1af?locale=en&zero_listing=true](https://www.freereg.org.uk/freereg1_csv_entries/5c828f09f493fd4edf50c1af?locale=en&zero_listing=true)
Reported Issue:
There is a slight grammatical error in this message - it should be either "...file is locked" or "...files are locked". As the process carried out was an edit of an entry within a file, the message should be the singular version.
https://www.freereg.org.uk/uploads/feedback/screenshot/5c9cf63ef493fd06629beaf1/ChrisW.JPG    

![Screenshot](https://www.freereg.org.uk)
E 0, U2, S8, C9: P19

**Comment by Captainkirkdawson** [comment]
True but impact is minor and only seen by members and has been that way for 3 years.

**Comment by Captainkirkdawson** [comment]
Corrected and pushed to master
