### ISSUE TITLE
133657569 Testing of feedback (Kirk)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1201]
Issue reported by **Captkirk** at 2019-03-27 23:06:09 UTC
Time: 2019-03-27T23:05:22+00:00
Session ID: c62933605ae0b3fefa250fe4a56f6a99
Problem Page URL: [/feedbacks/list_archived?locale=en](/feedbacks/list_archived?locale=en)
Previous Page URL: [https://test2.freecen.org.uk/feedbacks?locale=en](https://test2.freecen.org.uk/feedbacks?locale=en)
Reported Issue:
A first test of feedback
http://test2.freecen.org.uk/uploads/feedback/screenshot/5c9c01e1e937901e8820cb50/seo6.JPG    

![Screenshot](http://test2.freecen.org.uk)

**Comment by Captainkirkdawson** [comment]
Was just a test
