### ISSUE TITLE
133778170 file not linked correctly (Julie)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1203]
Issue reported by **JHarold** at 2019-03-29 08:36:10 UTC
Time: 2019-03-29T08:34:07+00:00
Session ID: 711f84e25a42a75e8725c7edc431f114
Problem Page URL: [/freereg1_csv_files/5c8b7a70f493fd81a08d620d?locale=en](/freereg1_csv_files/5c8b7a70f493fd81a08d620d?locale=en)
Previous Page URL: [https://www.freereg.org.uk/freereg1_csv_files/5c8b7a70f493fd81a08d620d?locale=en](https://www.freereg.org.uk/freereg1_csv_files/5c8b7a70f493fd81a08d620d?locale=en)
Reported Issue:
I clicked on Unique names and got this.
https://www.freereg.org.uk/uploads/feedback/screenshot/5c9dd8faf493fdae65833a94/Capture.PNG    

![Screenshot](https://www.freereg.org.uk)

**Comment by SteveBiggs** [comment]
Having tried a few other random files, this appears to be a general problem.

**Comment by Captainkirkdawson** [comment]
Interesting this bug has been there for 2 months. Not much use being made of the unique names action!
Fixed and added to master. Deployed to test3.

**Comment by Captainkirkdawson** [comment]
Interestingly this is a different issue to the one found in story #1199

**Comment by SteveBiggs** [comment]
Tested and working correctly.
