### ISSUE TITLE
134825893 UCF and "UNKNOWN" (Eric)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1205]
Issue reported by **REGManager** at 2019-04-10 11:38:13 UTC
Time: 2019-04-10T11:35:07+00:00
Session ID: f1d5ba0bf7dcaeda2c79f3e15193fe28
Problem Page URL: [/search_queries/new?locale=en](/search_queries/new?locale=en)
Previous Page URL: [https://www.freereg.org.uk/manage_resources/new?locale=en](https://www.freereg.org.uk/manage_resources/new?locale=en)
Reported Issue:
In the UCF search is an entry in the Lastname of "UNKNOWN" being treated as if it were a Star in UCF?
This is something that transcribers have been entering when there is no name in the register.  This is different to the name not being readable, but the search should treat it the same otherwise the entry will not be found.    

![Screenshot](https://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
No it is treated as UNKNOWN

**Comment by edickens** [comment]
May I ask that at sometime "UNKNOWN" in the Lastname is found by UCF as a lot of records are being missed.

However, this way of recording an un-entered name is not what is recommend in the Help...

_If no name is given, leave the field blank, and put any remarks such as "A Woman Unknown" in the Notes field._

So a Blank should also be found by UCF.
