### ISSUE TITLE
Site navigation with drop down options(REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#121]
Issue reported by **REGManager** at 2014-12-19 22:42:13 UTC
Time: 2014-12-19T22:31:57+00:00
Session ID: 9d3b70e2af50633301c6284f82dad1e8
Problem Page URL: [/search_queries/new](/search_queries/new)
Previous Page URL: [http://test2.freereg.org.uk/manage_resources/new](http://test2.freereg.org.uk/manage_resources/new)
Reported Issue:
There is no place where a new visitor can see what we offer and where to go.  The main menus need to work with a drop down menu listing the options.  This is also a good way for an experienced user to go directly to the screen they want.  See http://www.irishgenealogy.ie/en/ then "Research in Ireland".  I don't think this is the best example, but it is a genealogy website against which we will be compared.  This system, which would be on every one of our screens, also lets you go back up the hierarchy without using lots of back buttons.
EricD    

![Screenshot](http://test2.freereg.org.uk)

**Comment by Sherlock21** [comment]
I agree. We have been saying  this for months already!

Its part of the Richard Initiative surely, to make the site user friendly. Its no use having the best hinterland in the world, if the travellers cant find how to get off their boat and access it!
Scrums are good for certain Parties, but now and again, a good Line Out beats all.

**Comment by Captainkirkdawson** [comment]
I disagree.

Who is FR2 primarily designed for? Researchers. 

They represent the vast majority of users using the system, What "site information" do they need to know about. 

Search 

Perhaps they might want to know about us, a very few may want to contact us, they may want to know about the data we have a very few might want to join us. We want them to support us, 

We need a means for our team to login and then have access to their functions. But those functions should not be part of  public "site information"
There is nothing else.

Almost all of these actions are already directly accessible 

In addition more and more of these people are or will be using tablets and phones to do their research.  They will not have pointing devices such as mouses. They will be scrolling and selecting.

So let us not design our site around yesterdays technology.

In my opinion there is only one group of actions that could benefit to grouping as part of "site information" 

About/contact/volunteer/register Perhaps these group together. 

I believe that we should ;
1)make the search page our home page. That the search menu item ONLY appear when you are not on the home or search page. 
2)That when on the search page we replace the search menu link with a link to the DAP. That way we eliminate the 2 buttons on the search page itself.
3) That we add a Help button that is page linked ie context linked

4) So our menu becomes for Researchers
About Us  Database Contents Donate  Members  Help when on the Home/Search Page
About Us  Search  Donate  Members  Help   when on any other page

5) That we group under About Us  Objectives/Contact/Volunteer that these either be either a menu or drop down depending on device

6) that the current approach continue for Members  when logged in
i.e. for most pages the functions are there in the sidebar and for others they are in the Member Functions. We do not need the About Us or Donate links

So for Members when logged in the menu will be either

Search  Member Functions  Help  Logout
or 
Database Contents  Member Functions  Help  Logout when on the search page and logged in

**Comment by edickens** [comment]
```
Hi Kirk,
  I like your 1) to 6) and having the Search on the homepage.  The
  only thing I might add is that Contact Us could be divided into
  the different areas such as Data Errors or Website problems or
  Volunteer.  Perhaps I should put this in a separate report.
  I made these comments just as a reaction to the website to be
  recorded for analysis at the end of a fortnight.
  Eric
  _____________________________________
```

Eric J Dickens
FreeREG Chairman
      On 20/12/2014 17:26, Kirk Dawson wrote:

```
  I disagree.
  Who is FR2 primarily designed for? Researchers. 
  They represent the vast majority of users using the system,
    What "site information" do they need to know about. 
  Search 
  Perhaps they might want to know about us, a very few may want
    to contact us, they may want to know about the data we have a
    very few might want to join us. We want them to support us, 
  We need a means for our team to login and then have access to
    their functions. But those functions should not be part of
    public "site information"
    There is nothing else.
  Almost all of these actions are already directly accessible 
  In addition more and more of these people are or will be using
    tablets and phones to do their research. They will not have
    pointing devices such as mouses. They will be scrolling and
    selecting.
  So let us not design our site around yesterdays technology.
  In my opinion there is only one group of actions that could
    benefit to grouping as part of "site information" 
  About/contact/volunteer/register Perhaps these group together.

  I believe that we should ;
    1)make the search page our home page. That the search menu item
    ONLY appear when you are not on the home or search page. 
    2)That when on the search page we replace the search menu link
    with a link to the DAP. That way we eliminate the 2 buttons on
    the search page itself.
    3) That we add a Help button that is page linked ie context
    linked
  4) So our menu becomes for Researchers
    About Us Database Contents Donate Members Help when on the
    Home/Search Page
    About Us Search Donate Members Help when on any other page
  5) That we group under About Us Objectives/Contact/Volunteer
    that these either be either a menu or drop down depending on
    device
  6) that the current approach continue for Members when logged
    in
    i.e. for most pages the functions are there in the sidebar and
    for others they are in the Member Functions. We do not need the
    About Us or Donate links
  So for Members when logged in the menu will be either
  Search Member Functions Help Logout
    or 
    Database Contents Member Functions Help Logout when on the
    search page and logged in
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by Sherlock21** [comment]
Kirk's Length reply moves the goal posts in this debate somewhat.
We have designed a "One Size Fits ALL" job up to now, since that was what appeared to be what was needed and the way the coders took things.

But Kirk's analysis of the present site of play is clearly based round
 "Who is FR2 Primarly Designed For? > Researchers".

And I agree on that baseline, then all that is needed is a site that has a landing on a Search or Volunteer Page - either the search form is there, with no messing about to find it, 
- a line to how to Volunteer. AND a link to few notes about the basis of our Data.
- how to DONATE.

THEN a different Site where the Workers (ie the Members) do their stuff.
Simple. If the  Researchers don't want or need to know all about the nuts and bolts of the activities of the Transcribers or the Managers etc, [and i agree totally : they done need that] then dont have it on the same website. A common landing from which one picks off the link to the right place, is one keying action too many for all parties.

If Two different sites, then as Kirk points out, can be structures to work self contained in 2 different ways - one for tablets and scrolling about.
-the other in the conventional way of fixed pages and keyboard & mouse. - Yesterday's technology for Yesterdays generation of users.

Then we wont get mixed up comments from the Dinosaurs like appears to be the case at present.

**Comment by Captainkirkdawson** [comment]
As the lead Dinosaur who lives in the land of Dinosaurs let me say I cannot conceive of living without my mouse and widescreen displays and while I have a smart phone I use it for its original purpose,  It is used when traveling for basic email and has data turned off except when I know I have a WiFi connection.
Unfortunately, at least in my mind, too many people have bought into the advertising hype and are going to be using tablets and phones to access our and other peoples system and so we are going to have to support them. 
The day that FR2 becomes 2 production sites is the day I resign from further involvement with the project. 
WE can achieve the tailoring while maintaining consistency in styling with one site.

**Comment by Sherlock21** [comment]
I am not attempting to present the case for ignoring the Tablet users. Not one bit. But sitting on the edge of this issue,  it seems to me that we are trying to make on software package work in two distinctly different environments. So I was merely suggesting: horses for courses - as I had in fact suggested previously.

Recently I was doing some searching  of database records on my iMac, and using the browser on there and the Old url that i have used for years to access the site.

Then for interest, to see what this site looked like on my iPad, i fired that up and did a bit of exploration. Logging on to the site by its url that I new, using the ipad's Browser Safari, I was greeted by the target site with a message to the effect: if I downloaded the site's own free App and loaded that onto my iPad, I would enjoy a much better service.

This to me suggested there were 2 totally different methodologies at work here, and what works best on a desk top PC, is not the best software for these tablet family of devices. 

And so I merely thought that you guys who understand these things, may find a better solution here, to cater for the PC market and the Tablet market in different ways.  

I am not " having a go" at the way things are going, nor using this vehicle to register my disagreement. I assure all that I won't bring it up again.

**Comment by edickens** [comment]
```
Another similar thing we need to cater
  for is the fact that many transcribers (and researchers) bookmark
  a page that is not the first screen so that they can go direct to
  where they want to go.  But this means that they miss the
  homepage.  If we have important messages, or don't have the
  advertising on later pages, then these will be missed.
  Eric

  _____________________________________
```

Eric J Dickens
FreeREG Chairman
      On 21/12/2014 13:33, Sherlock21 wrote:

```
  Kirk's Length reply moves the goal posts in this debate
    somewhat.
    We have designed a "One Size Fits ALL" job up to now, since that
    was what appeared to be what was needed and the way the coders
    took things.
  But Kirk's analysis of the present site of play is clearly
    based round
    "Who is FR2 Primarly Designed For? > Researchers".
  And I agree on that baseline, then all that is needed is a site
    that has a landing on a Search or Volunteer Page - either the
    search form is there, with no messing about to find it, 

    a line to how to Volunteer. AND a link to few notes about
      the basis of our Data.
    how to DONATE.

  THEN a different Site where the Workers (ie the Members) do
    their stuff.
    Simple. If the Researchers don't want or need to know all about
    the nuts and bolts of the activities of the Transcribers or the
    Managers etc, [and i agree totally : they done need that] then
    dont have it on the same website. A common landing from which
    one picks off the link to the right place, is one keying action
    too many for all parties.
  If Two different sites, then as Kirk points out, can be
    structures to work self contained in 2 different ways - one for
    tablets and scrolling about.
    -the other in the conventional way of fixed pages and keyboard
    & mouse. - Yesterday's technology for Yesterdays generation
    of users.
  Then we wont get mixed up comments from the Dinosaurs like
    appears to be the case at present.
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by edickens** [comment]
Following EricB's comment.  I think that transcribers and  others (all except researchers) must use PCs or Laptops.  We will not cater for any other system, even for those who have said they want to transcriber on their tablets on a beach.  You need a proper keyboard and mouse.
EricD

**Comment by benwbrum** [comment]
I came to the same conclusion about a different transcription tool I work on, the two days later was sitting next to one of my most active transcribers and to my chagrin noticed that she was working on an iPad with an attached keyboard!

I agree in principle with your priorities, however.

**Comment by benwbrum** [comment]
One thing I'm not clear on which Kirk may be able to clairify is: how much of this discussion could be resolved with Refinery integration with the menus?

**Comment by Captainkirkdawson** [comment]
This story and 341 are really one and the same as far as menus are concerned.
I have posted my proposed phase1 implementation in 341 for comment
The matter of tablet and phone transcription is really a separate matter

**Comment by edickens** [comment]
```
I think we must concentrate on
  replacing FR1, which does not cater for iPad or iPhone.
  We know of problems further down the line, but are sticking to the
  plan to do a bit at a time and at present just Search and not DAP.
  EricD

  _____________________________________
```

Eric J Dickens
FreeREG Chairman
      On 22/12/2014 15:48, Kirk Dawson wrote:

```
  This story and 341 are really one and the same as far as menus
    are concerned.
    I have posted my proposed phase1 implementation in 341 for
    comment
    The matter of tablet and phone transcription is really a
    separate matter
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by Captainkirkdawson** [comment]
341 is an active story that is being worked on in this sprint and has
nothing to do with tablets etc. I have only had reaction to the story from
EricB.

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1
