### ISSUE TITLE
138028780 The sort is based on baptism date(Helen Barrell)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1212]
Issue reported by **Helen Barrell** at 2019-05-17 13:19:40 UTC
Time: 2019-05-17T13:18:11+00:00
Session ID: f287f77ebd7c7f05b1d51671b9510d0c
Problem Page URL: []()
Previous Page URL: [https://www.freereg.org.uk/contacts/new](https://www.freereg.org.uk/contacts/new)
Reported Issue:
Sorry, me again!

I just did a search - George Day, Coggeshall (Essex), exact match, inc family members.

If you look at the results list, it's got a baptism at the top that's later chronologically than the burials. It's as if it's sorting by event type, then by date, rather than by date across all event types.

I don't think I've seen this before!

Helen.
https://www.freereg.org.uk/uploads/contact/screenshot/5cdeb4ecf493fd4a9c14ca47/day-coggeshall.PNG    

![Screenshot](https://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
If you look at the record there is no baptism date just a birth date. The sort is based on baptism date.

**Comment by richpomfret** [comment]
To add note on researchers help page. @AlOneill to take a look.

**Comment by AlOneill** [comment]
The updated advice is in the 2nd para of [Draft Help, Exploring your results](https://test3.freereg.org.uk/cms/draft-help#results).

**Comment by PatReynolds** [comment]
@PatReynolds to proof

**Comment by PatReynolds** [comment]
Excellent - ready to publish, thank you @AlOneill
