### ISSUE TITLE
138876280 Website on Mobile phone Problem (Edward Ebden)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1213]
Issue reported by **Edward Ebden** at 2019-05-27 08:44:40 UTC
Time: 2019-05-27T08:42:49+00:00
Session ID: cbe0efc96d07a5850124f988ee3c0927
Problem Page URL: [unknown](unknown)
Previous Page URL: [https://www.freereg.org.uk/contacts/5818f214e93790ec75cfe46e/report_error?locale=en&query=5ceb9a3f791e3bc41e3b8918](https://www.freereg.org.uk/contacts/5818f214e93790ec75cfe46e/report_error?locale=en&query=5ceb9a3f791e3bc41e3b8918)
Reported Issue:
Getting now a horrible rose red background now on my mobile phone,not on PC.This seems new.It is almost unreadable. Ok still on PC.Hope you don't mind my pointing it out! Edward     

![Screenshot](https://www.freereg.org.uk)

**Comment by SteveBiggs** [comment]
I've just tried it on my phone and he is right, the background of individual search results is now dark red.

**Comment by PatReynolds** [comment]
No problem with Chrome (Android 9).

**Comment by SteveBiggs** [comment]
I'm using Chrome on Android and do see the problem - you have to select an individual search result before the issue occurs.

**Comment by Captainkirkdawson** [comment]
Issue is unique to reg; unique to the display of an entry. It is using the background colour of the footer

**Comment by Captainkirkdawson** [comment]
Also apparent on test2 so we can diagnose solution

**Comment by PatReynolds** [comment]
Thanks, Steve - now looking at search results detail page, and see issue there.

**Comment by Captainkirkdawson** [comment]
Issue found; fix applied to test2 reg @SteveBiggs please confirm that test2 no longer shows issue

**Comment by SteveBiggs** [comment]
test2 now behaves correctly, thanks @Captainkirkdawson
