### ISSUE TITLE
139068407 Transcriber name showing instead of Pseudonym (Susan)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1214]
Issue reported by **hawkinssm** at 2019-05-29 14:06:47 UTC
Time: 2019-05-29T13:52:54+00:00
Session ID: f62931f1f4215fd27df35b32e74e056b
Problem Page URL: [/churches/58dc87d2f493fd654c0270a9?locale=en](/churches/58dc87d2f493fd654c0270a9?locale=en)
Previous Page URL: [https://www.freereg.org.uk/places/53cbf5e8eca9eb03a60051f5?locale=en](https://www.freereg.org.uk/places/53cbf5e8eca9eb03a60051f5?locale=en)
Reported Issue:
Hello I have had complaints from my transcribers and have lost 3 very good transcribers because of this issue. The transcribers are given an option to create a pseudonym if they wish, for privacy, but if you search by place and then church, it still shows the name of the transcriber, not the pseudonym. The screenshot is from Dover - The French Church and is an example of this problem - The transcriber has set her pseudonym as Sunshine, but her name still shows on this page.
https://www.freereg.org.uk/uploads/feedback/screenshot/5cee91f7f493fd5afe3e9514/Capture.JPG    

![Screenshot](https://www.freereg.org.uk)

**Comment by SteveBiggs** [comment]
Looking at Elaine's profile I notice she has not selected the option "Do not acknowledge my contributions" which may be why her name still shows?:

![Capture.jpg](https://images.zenhubusercontent.com/5cb596063b6bd6333fc1dc24/4445f100-adf4-4e65-8e5b-6ef01ebf841b)

**Comment by PatReynolds** [comment]
Privicy needs adding to the Transcriptions displays

**Comment by richpomfret** [comment]
1983 now in progress which means this will be covered and can be closed.
