### ISSUE TITLE
140810364 County Coordinator list - change of format (Ericd)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1215]
Issue reported by **REGManager** at 2019-06-18 17:59:24 UTC
Time: 2019-06-18T17:54:18+00:00
Session ID: 442c1fc854c6541064b2ea251e83ecdc
Problem Page URL: [/counties](/counties)
Previous Page URL: [https://www.freereg.org.uk/manage_resources/new?locale=en](https://www.freereg.org.uk/manage_resources/new?locale=en)
Reported Issue:
I see that the list of counties in this report now also has the name of the county and not just the Chapman code.
I don't remember seeing a request for this change.
I only comment because I extract this report for my four weekly statistics so a change of format affects my spreadsheet.  Not really a problem, but we do have to be careful making changes, even minor, without reference.
Hopefully it was agreed and I just missed it.
EricD    

![Screenshot](https://www.freereg.org.uk)

**Comment by richpomfret** [comment]
@edickens to provide further info.

**Comment by edickens** [comment]
This is from the list of County Coordinators.
![Capture.JPG](https://images.zenhubusercontent.com/5cb4c5e2cccdd751e9e85870/f014bff8-805d-4de7-bd5c-1b728ad100c3)
The first column used to just be just the Chapman code.  It is useful to know what each code means, but I was not expecting a change.  It was while looking for OVS that I saw this change. 
And there are two codes here with no description.

**Comment by FreecenBren** [comment]
Just a thought.

Those are the 2  Chapman Codes that FreeCEN decided to use at the start of
the project.
They are not official Chapman Codes, but are what FreeCEN decided to use 20
years ago.
This is what they stand for.

OVB = Is the chapman Code we use for those born oversea’s, but are either
British Subjects or Naturalised British Subjects.
Their actual place of birth is also recorded in the transcription as well.

OVF = is the Chapman Code for those born over sea’s, but are NOT British
Subjects nor Naturalised British Subjects.
Again,  their actual place of birth is also recorded in the transcription
as well.

With FreeREG deciding to use their own SEA etc., so you could say they are
“Surplus to requirements”

**Comment by Captainkirkdawson** [comment]
@edickens  the format change was an unintended consequence of the great merge. Cen used that format. Likely useful to retain.
Can we close

**Comment by edickens** [comment]
Makes a lot of sense to make them the same.  I can't see that in FreeCEN.
Close
