### ISSUE TITLE
141136833 Relocate Batch still not working (Barrie)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1217]
Issue reported by **brobinson43** at 2019-06-22 12:40:33 UTC
Time: 2019-06-22T12:35:22+00:00
Session ID: 41306779a8b2e24186727a0211782af7
Problem Page URL: [/freereg1_csv_files/update_registers?church=5409f063eca9eba206824758](/freereg1_csv_files/update_registers?church=5409f063eca9eba206824758)
Previous Page URL: [https://www.freereg.org.uk/freereg1_csv_files/update_churches?place=53cd498ceca9ebee4f00a27a](https://www.freereg.org.uk/freereg1_csv_files/update_churches?place=53cd498ceca9ebee4f00a27a)
Reported Issue:
I'm trying to relocate some batches which are presently PR when they should be OT. I've tried using an up-to-date computer with the latest (or nearly) web browser.
I selected the place (Haseley) and Church (St Mary) and then the intended register type (Other Transcript) but the place and church were not highlighted so I clicked on the single name, Haseley, and got the "Something went wrong" message. Should I just trust the Place and Church are actually selected after the first click on them?    

![Screenshot](https://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
There is an issue with the form but this story is not it

**Comment by richpomfret** [comment]
@Captainkirkdawson what is the issue with the form? It appears a few people (according to Steve) have encountered the relocate batch issue.

**Comment by Captainkirkdawson** [comment]
The relocate form for a batch will not function because of a similar issue to #1218 but it is not the same solution. The symptoms are an inability to submit the form for processing. It does NOT produce the "Something went wrong" message which has a very different basic cause and that is the the document being access does not have the correct linkage.
I will work initially on the general problem.

**Comment by Captainkirkdawson** [comment]
A fix to form has been applied. Deployed to test3 and 2
@SteveBiggs can you see if you can make it fail please

**Comment by SteveBiggs** [comment]
Seems to work fine on test2 and test3.

**Comment by Captainkirkdawson** [comment]
Deployed
