### ISSUE TITLE
141315138 cannot change date range (Doreen)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1218]
Issue reported by **deo123** at 2019-06-24 14:12:18 UTC
Time: 2019-06-24T14:10:26+00:00
Session ID: c0765413aca3314206e191fc73f0bd47
Problem Page URL: [/sources/5d0cd8cef493fd7833661c80/edit?locale=en](/sources/5d0cd8cef493fd7833661c80/edit?locale=en)
Previous Page URL: [https://www.freereg.org.uk/sources/5d0cd8cef493fd7833661c80?image_group_filter=&locale=en](https://www.freereg.org.uk/sources/5d0cd8cef493fd7833661c80?image_group_filter=&locale=en)
Reported Issue:
wanted to change hte date range but just froze.

Regards Doreen    

![Screenshot](https://www.freereg.org.uk)

**Comment by SteveBiggs** [comment]
I tested this in Chrome and Edge - the Submit button seems to have stopped working on the Edit Image Source page.

**Comment by Captainkirkdawson** [comment]
This was hard to track down. Turns out it was a conflict between html5 form validation, rails 5 elimination of double clicking, our change to automatic validation of required inputs on forms and the custom js used to validate this specific form.
Fix deployed to test3.  @SteveBiggs please check

**Comment by SteveBiggs** [comment]
Works as expected in test3. I also checked it in test2 and that works as well if that is significant?

**Comment by Captainkirkdawson** [comment]
Thanks Steve. Both test2 and test3 are running the same master code

**Comment by Captainkirkdawson** [comment]
Deployed
