### ISSUE TITLE
142081376 OVB does not come up when creating a Place (Ericd)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1219]
Issue reported by **REGManager** at 2019-07-03 11:02:56 UTC
Time: 2019-07-03T10:56:56+00:00
Session ID: c59625d5b9c91769dac3d4cdf93d772a
Problem Page URL: [/places/new?locale=en](/places/new?locale=en)
Previous Page URL: [https://www.freereg.org.uk/places?locale=en](https://www.freereg.org.uk/places?locale=en)
Reported Issue:
Needs to be added as Overseas British.  All Chapman Codes listed under Manage Counties should be listed.
If I have selected Manage Counties and OVB is there, but when trying to create a new Place it asks me for the Country and County again.  Not really necessary.
I have chosen to put this under the Country of England.  This is not strictly correct but not that important.    

![Screenshot](https://www.freereg.org.uk)

**Comment by edickens** [comment]
I use OTH now.  So this can be closed unless it needs to work like FreeCEN.

**Comment by Captainkirkdawson** [comment]
To have it and OVF work properly I would have to  delete the county as is and let you recreate them as and when required

**Comment by edickens** [comment]
I suggest you do that because it is better to have something working, even if we don't use it.  There will then not be a question for a programmer in the future should they come into use.
There is OVB as well.

**Comment by richpomfret** [comment]
No longer needed so closing.
