### ISSUE TITLE
Support Welsh Forename/Surname in Search Parameters (Howdy)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#122]
Issue reported by **Howdy** at 2014-12-20 00:50:25 UTC
Time: 2014-12-20T00:23:36+00:00
Session ID: bed674ec412bfa34111e4cd71d8f9346
Problem Page URL: [/search_queries/5494c187e937904b1000000f](/search_queries/5494c187e937904b1000000f)
Previous Page URL: [http://test2.freereg.org.uk/search_queries/new?search_id=5494c15fe937904b1000000d](http://test2.freereg.org.uk/search_queries/new?search_id=5494c15fe937904b1000000d)
Reported Issue:
I know this is late, but I think it is worth mentioning.

Several Welsh names have mutated over time to accommodate English naming practices.

The practice of using the patronymic naming convention was practiced until 1800 when it was abolished by law.  Welsh forenames (Jenkin, Evan,  Robert, etc) have become surnames, often with the addition of an "s" (Jenkins, Evans, Roberts, etc.) where, under the patronymic system, surnames would have remained  as the forename.  I might also add that not all Welsh followed the patronymic system and the addition of the "s" started before 1800.  The "s" is not the only mutation; ap Robert becomes Probert; ab owen becomes Bowen, etc.

 It would be beneficial to have the choice to include a "contains" option (much like the Genuki search)

Howard Evans    

![Screenshot](http://test2.freereg.org.uk)

**Comment by Sherlock21** [comment]
Meaning exactly what, Howard? to which fields do you refer, on which forms?
I Guess search form, but you might be somewhere else.
Then are you wanting this to be in First name fields?
Or in Surname fields?

Won't you get this either or if the searcher uses the Fuzzy flag? 
Or are you asking for this this to be hard coded into the application without there being a tick option?  - like variations in the spellings and abbreviations in English names?

**Comment by benwbrum** [comment]
This is something we might handle through the emendation system the same way we match abbreviated or Latinized forenames. Give me a list of "transcript says X, researcher will search for Y; make them match" X/Y pairs and I'll spec it out.

**Comment by Captainkirkdawson** [comment]
Comment included
