### ISSUE TITLE
142679851 Creating a register causes red error message (Ericd)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1220]
Issue reported by **REGManager** at 2019-07-10 09:17:31 UTC
Time: 2019-07-10T09:16:04+00:00
Session ID: c789eadcf91dbd4915ac1ea6d60480c4
Problem Page URL: [/churches/5d25aca7f493fd1ef42b5e90?locale=en](/churches/5d25aca7f493fd1ef42b5e90?locale=en)
Previous Page URL: [https://www.freereg.org.uk/places/5d25aafdf493fd1eef2cb80b?locale=en](https://www.freereg.org.uk/places/5d25aafdf493fd1eef2cb80b?locale=en)
Reported Issue:
Trying to create a register for OTH, At Sea, Ships    

![Screenshot](https://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Issue has been resolved. @SteveBiggs  @edickens  please confirm it is fixd on test3

**Comment by edickens** [comment]
OTH is not in Test3.

**Comment by Captainkirkdawson** [comment]
But you can create it by activating it then do the test

**Comment by edickens** [comment]
Forgot that.  Done now.
Register Type created.
But creating Source fails.
First Red Warning.
Then logs me out...
![Capture](https://user-images.githubusercontent.com/8876165/61021008-9b282780-a397-11e9-93d4-80dda1cd4ada.JPG)
then the home pages says it is creating the source but it has not...
![Capture1](https://user-images.githubusercontent.com/8876165/61021038-bbf07d00-a397-11e9-83ae-3a5806ff5d64.JPG)

**Comment by edickens** [comment]
When I try to create a Source it takes me back to the production website from Test3.

**Comment by Captainkirkdawson** [comment]
the image server knows nothing about test2/3 all it knows is production so creation of the image source on test3 would be problematic. Totally expected.
Your ability to create the register worked so the fix can be deployed.

**Comment by edickens** [comment]
Understood.  Please deploy.

**Comment by Captainkirkdawson** [comment]
Deployed into production on colobus only

**Comment by edickens** [comment]
All working fine.  Some images uploaded to OTH for your interest.  Am checking format with Steve before I do any more.
TY  Eric
