### ISSUE TITLE
142846302 Does the transcriber use TR or OT (Ericd)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1221]
Issue reported by **REGManager** at 2019-07-12 07:31:42 UTC
Time: 2019-07-12T07:25:25+00:00
Session ID: f8f3d5010d1b324ad2c0c96369c7f84f
Problem Page URL: [/registers/5d2835c8f493fd2513d6ceb1?locale=en](/registers/5d2835c8f493fd2513d6ceb1?locale=en)
Previous Page URL: [https://www.freereg.org.uk/registers/5d2835c8f493fd2513d6ceb1?locale=en](https://www.freereg.org.uk/registers/5d2835c8f493fd2513d6ceb1?locale=en)
Reported Issue:
I have created the register type Other Transcript (OT) from the pick list.  But the server has created a folder in the image server with TR.  Should the transcriber use OT or TR or does in not matter?
The images that will be uploading are indexes, which contain Name, Year and Ship, so have all the basic information.  We do not have a register type for indexes, which is why I used this one.
https://www.freereg.org.uk/uploads/feedback/screenshot/5d28375ef493fd2513d6d161/Capture.JPG    

![Screenshot](https://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
It matters not TR or OT will go to same register. REG demands a reister type so that one is appropriate

**Comment by edickens** [comment]
Thanks for the clarification.  Perhaps a comment in the Help as the name of the Register Type is "Other Transcription" (OT) but the image folder created is TR.
Can be closed as far as I am concerned.

**Comment by Captainkirkdawson** [comment]
But you are the only who sees that.
