### ISSUE TITLE
143088847 Register disappeared (Barrie)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1222]
Issue reported by **brobinson43** at 2019-07-15 02:54:07 UTC
Time: 2019-07-15T02:50:49+00:00
Session ID: 987a0cc2e591500164ac9c8626502ff4
Problem Page URL: [/manage_counties/place_range?params=D-F](/manage_counties/place_range?params=D-F)
Previous Page URL: [https://www.freereg.org.uk/manage_counties/selection?option=Work%20with%20Active%20Places](https://www.freereg.org.uk/manage_counties/selection?option=Work%20with%20Active%20Places)
Reported Issue:
I tried to move an unspecified batch (WAR:Fenny Compton:(only one church):unspecified (the second one):Marriages 1627-1812) to a newly created register of Phillimore's Transcript. I got a message of "Something went wrong" and both the batch and the new register have disappeared.    

![Screenshot](https://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Do not understand story. There is a Phillmores Transcript register  for St Peter and St Clare in Fenny Compton. That contains one batch WARFENMA.CSV.  Seems as if things went as requested
