### ISSUE TITLE
143107021 Duplicate CSV batch has been accepted (Ericd)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1223]
Issue reported by **REGManager** at 2019-07-15 07:57:01 UTC
Time: 2019-07-15T07:54:28+00:00
Session ID: 654ad948fd9632e7b4e9f5c981e6f9e8
Problem Page URL: [/registers/55ad9999f493fd92c001e758?locale=en](/registers/55ad9999f493fd92c001e758?locale=en)
Previous Page URL: [https://www.freereg.org.uk/manage_counties/place_range?params=G-I](https://www.freereg.org.uk/manage_counties/place_range?params=G-I)
Reported Issue:
The batch WARHATMA0.CSV has been accepted twice.
How can this happen and how is it corrected?
https://www.freereg.org.uk/uploads/feedback/screenshot/5d2c31cdf493fd31ff4c47f8/Capture.JPG    

![Screenshot](https://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
As written this story is incorrect. There is only 1 file with the name WARHATMA0.CSV in the userid folder for Spanishken so "a duplicate csv batch has been accepted" is incorrect.
What Spanishken was doing to this file on 15 July will require research (size 5). A brief review shows multiple replacements of the file at 3:10 3:11 3:12 on July 15 2019 to a file that was originally uploaded on 3 March 2014. The file replacements were of different sizes.
Looking at the register today 17 July shows that the reported duplicate batches are no longer there.
So is someone doing something as I look at the story? Further commentary terminated

**Comment by edickens** [comment]
Duplicate is still there...

![Capture.JPG](https://images.zenhubusercontent.com/5cb4c5e2cccdd751e9e85870/5955d107-a528-43ed-b817-b046e071ed46)

**Comment by Captainkirkdawson** [comment]
Now there are 4 so spanishken is changing things. I am not going to touch this story unstill static.
![hatton](https://user-images.githubusercontent.com/2874694/61460133-5a965400-a92b-11e9-99fd-61adc0c48f7e.JPG)

**Comment by Sherlock21** [comment]
I am NOT doing a deletions of big files for Michael Clarke- so not of my making.
- last ones tried by me on 4th June - but I stopped, pending attention to the problem a little before that date, where there appeared to be 'leftovers' that appeared in a researcher search but not as batches in the list of batches for the church concerned,-ref no 1919 perhaps - I can't remember now.
