### ISSUE TITLE
142537174 Data Question (Barry Lambert)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1224]
Issue reported by **Barry Lambert** at 2019-07-08 17:39:34 UTC
Time: 2019-07-08T17:27:51+00:00
Session ID: 683c1fe428e77ffa1fbad8d3e914b0f3
Problem Page URL: []()
Previous Page URL: [https://www.freereg.org.uk/contacts/new](https://www.freereg.org.uk/contacts/new)
Reported Issue:
I have not used FreeReg for several years, but I now notice an inconsistancy between earlier and current data.  I was, and am, researching Somerset  records.  In 2013, I copied and pasted results for all Cooper burials in East Pennard and found the following:
663  Burials	31 May 1707 COOPER * Somerset East Pennard	Surname

Before I went back to my old files and found this I had done a current search of FreeReg and there is now no burial shown for a Cooper on that date in East Pennard.  Can you please advise.    

![Screenshot](https://www.freereg.org.uk)

**Comment by SteveBiggs** [comment]
Jackie James wrote:

He's right there is something a bit odd here. The record is in the file
![image](https://user-images.githubusercontent.com/25303607/61294254-4d635300-a7cd-11e9-9ce1-a324e8ee8723.png)

It comes up if you search in SOM, East Pennard, all types & also SOM, East Pennard, Burials. 
But if you deselect East Pennard, I got 499 search results (has that been increased from 250 or is that a one-off?) but the record is not there. 
![image](https://user-images.githubusercontent.com/25303607/61294272-58b67e80-a7cd-11e9-8f0b-cf97d29346ac.png)

Is this something to do with the old problem of UCFs not being recognised by the search engine?

**Comment by Captainkirkdawson** [comment]
The record is there and retrieved in a general search of Somerset
![cooper.JPG](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/c4b48343-a6bf-4ee5-81f6-350179f929ce)

**Comment by Captainkirkdawson** [comment]
There may be an issue but it is not related to this directly.
I have a suspicion that the handling of  the results when reaching the search number limit has been changed. It would appear to provide results if the limit has been exceeded.  Will write separate story
#1989

**Comment by SteveBiggs** [comment]
Have explained to Jackie. This can be closed.
