### ISSUE TITLE
143367468 Archived Contacts to be displayed in reverse date order (Ericd)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1225]
Issue reported by **REGManager** at 2019-07-18 08:17:48 UTC
Time: 2019-07-18T08:12:59+00:00
Session ID: a6a55a2ee8c7b6089898dd470d99c86d
Problem Page URL: [/contacts/list_archived?locale=en](/contacts/list_archived?locale=en)
Previous Page URL: [https://www.freereg.org.uk/contacts](https://www.freereg.org.uk/contacts)
Reported Issue:
I have been checking if a Contact of yesterday had received a reply because it was no longer in the Active list.  It had received a reply and been Archived, which is exactly what should have been done, but to find it, I have to scroll to the bottom, and all the archive had to load.
And do we need to hold the Archive that far back?    

![Screenshot](https://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
You can list them in a number of ways including Most Recent Date
![recent.JPG](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/7370925b-fb1e-413f-9a8b-a4112f681f99)

**Comment by edickens** [comment]
I must concentrate more.  I was looking to click the column heading.
I've been uploading images at the same time and it is a soul destroying and monotonous job.
