### ISSUE TITLE
143371714 In the list of images Available for transcribing, only show the counties with images (Ericd)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1226]
Issue reported by **REGManager** at 2019-07-18 09:28:34 UTC
Time: 2019-07-18T09:25:41+00:00
Session ID: cc6b9ae6e86be8370941aa8661876fa7
Problem Page URL: [/assignments/select_county?locale=en](/assignments/select_county?locale=en)
Previous Page URL: [https://www.freereg.org.uk/assignments/select_county?locale=en](https://www.freereg.org.uk/assignments/select_county?locale=en)
Reported Issue:
To encourage transcribers to look for work, only show those counties with Unallocated images.  They have to select each county as it is, but if they keep getting counties without images, they will not find the ones with work available.
https://www.freereg.org.uk/uploads/feedback/screenshot/5d303bc2f493fd297e61ba2d/Capture.JPG    

![Screenshot](https://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
In what way is this different from #1440

**Comment by edickens** [comment]
Sorry.  Forgot that was there.  Close this.
