### ISSUE TITLE
143731078 Problems viewing images for OTH (Ericd)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1227]
Issue reported by **REGManager** at 2019-07-22 13:17:58 UTC
Time: 2019-07-22T13:15:40+00:00
Session ID: eaaf354c78b80ff3970af0e08aeb5e5f
Problem Page URL: [/image_server_images/5d2f0647f493fd211f5809eb/index?locale=en](/image_server_images/5d2f0647f493fd211f5809eb/index?locale=en)
Previous Page URL: [https://www.freereg.org.uk/image_server_groups/5d2f0647f493fd211f5809eb?assignment_filter_list=county&locale=en](https://www.freereg.org.uk/image_server_groups/5d2f0647f493fd211f5809eb?assignment_filter_list=county&locale=en)
Reported Issue:
Selected Assignments, Available, OTH and tried to view images.  Got the attached.
Eric
https://www.freereg.org.uk/uploads/feedback/screenshot/5d35b786f493fd74dfe65f22/Capture.JPG    

![Screenshot](https://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
@edickens Sorry forgot that I had a chapman_code check on the image server. Updated the list. Should be OK now

**Comment by edickens** [comment]
All fixed.  TY  Eric
