### ISSUE TITLE
143992108 Editing entry does not allow "Paste" (Ericd)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1228]
Issue reported by **REGManager** at 2019-07-25 13:48:28 UTC
Time: 2019-07-25T13:43:45+00:00
Session ID: b758f1a72f528d2da4e0b75b8beddd22
Problem Page URL: [/freereg1_csv_entries/54cd29b1e9379053ce0cdce0?locale=en](/freereg1_csv_entries/54cd29b1e9379053ce0cdce0?locale=en)
Previous Page URL: [https://www.freereg.org.uk/contacts/5d35e279f493fd74dfe80792?locale=en](https://www.freereg.org.uk/contacts/5d35e279f493fd74dfe80792?locale=en)
Reported Issue:
This is the first entry I have come across where we have the image, but the film and image number have not been entered.  Very annoying as it took time to identify the image.
But having done so, I tried to copy and paste the image filename, but it would not let me paste into both Film and Image numbers.
Also, the fields do not look like Flexible CSV.  I would like to have put the path to the Image Group and Filename.
bunothan.ELNTRABA5.CSV.2398 
https://www.freereg.org.uk/uploads/feedback/screenshot/5d39b32cf493fd16c113ce72/Capture.JPG    

![Screenshot](https://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
You most certainly can paste into a form using with the cntl-v option or the drop down edit paste

**Comment by edickens** [comment]
I got the drop down menu, hit paste, but nothing happened.  There was something there because I tried a few times and also into another document where it did paste.

**Comment by Captainkirkdawson** [comment]
Need to make sure you have entered into the field box first and that you are in the edit page

**Comment by edickens** [comment]
I will try again on this entry.

**Comment by edickens** [comment]
I don't know now what I did or didn't do.  But it works now.  I know I was able to type into the boxes and save so it must have been in edit more, but not able to use the drop down menu.
Close this story.

**Comment by Captainkirkdawson** [comment]
Please do as I am able to paste into that entry
![paste](https://user-images.githubusercontent.com/2874694/61891253-7d45e100-aec6-11e9-8aac-8f1829b7b9cc.JPG)
