### ISSUE TITLE
144405247 Edit Details of Syndicate Crash (Stephen)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1229]
Issue reported by **SBManager** at 2019-07-30 08:34:07 UTC
Time: 2019-07-30T08:31:33+00:00
Session ID: b8e4078f196ddfc68ef061417eb1ef4d
Problem Page URL: [/syndicates](/syndicates)
Previous Page URL: [https://www.freereg.org.uk/userid_details/options](https://www.freereg.org.uk/userid_details/options)
Reported Issue:
When I click Edit Details against a Syndicate under Listing of Syndicates, I get the red 'Something went wrong ...' screen. Tried in Chrome and Edge with same result.    

![Screenshot](https://www.freereg.org.uk)

E0 6 S7 C7: P20

**Comment by Captainkirkdawson** [comment]
Fix applied and deployed to test3 @edickens @SteveBiggs please review

**Comment by edickens** [comment]
OK.   Deploy to production.  TY  E

**Comment by SteveBiggs** [comment]
Yes works for me too.

**Comment by Captainkirkdawson** [comment]
TY both will add to this sprints deployment
