### ISSUE TITLE
Wild Card (Howdy)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#123]
Issue reported by **Howdy** at 2014-12-20 01:05:36 UTC
Time: 2014-12-20T01:01:56+00:00
Session ID: bed674ec412bfa34111e4cd71d8f9346
Problem Page URL: [/tips-for-searching-the-database](/tips-for-searching-the-database)
Previous Page URL: [http://test2.freereg.org.uk/search_queries/new](http://test2.freereg.org.uk/search_queries/new)
Reported Issue:
I have tried using the "?" to get Evans from an entry of Evan.  It didn't work.  I also tried it in the first position to obtain Bowen from the last name of Owen.

My previous report is germane.

Howard Evans    

![Screenshot](http://test2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
There is no wild card capability in either FR2 nor was there in FR1

**Comment by edickens** [comment]
```
Hi Kirk,
  We are asking for the reaction of new users to the website, and
  this would seem to be something that they had expected from day
  one.  It is in most other genealogy websites and is important. 
  But would Soundex (or Ben's fuzzy if it is different) do instead. 
  If so do we need to mention it more prominently - or say that it
  does not work and flag an error if someone tries?
  This also applies to UCF because we know from FR1 that anything
  with underscore or a question mark at the end tends not to be
  found.  Lots of entries are not included at present.
  We discussed this a lot when we started on FR2.
  E
  _____________________________________
```

Eric J Dickens
FreeREG Chairman
      On 20/12/2014 16:17, Kirk Dawson wrote:

```
  There is no wild card capability in either FR2 nor was there in
    FR1
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by Captainkirkdawson** [comment]
Comment added in hover
