### ISSUE TITLE
144404511 Image server problems (Spelling error)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1230]
Issue reported by **STSCoord** at 2019-07-30 08:21:51 UTC
Time: 2019-07-30T08:14:44+00:00
Session ID: 0ba35a1850d887eb6454d3f6af28d97a
Problem Page URL: [/manage_counties/selection?option=Manage%20Images](/manage_counties/selection?option=Manage%20Images)
Previous Page URL: [https://www.freereg.org.uk/manage_counties/select_action?locale=en](https://www.freereg.org.uk/manage_counties/select_action?locale=en)
Reported Issue:
1. We sometimes have Image Sever rather than Image Server. This happens on several screens. An example is attached.
2. There is no error reporting mechanism on Image Server pages.
https://www.freereg.org.uk/uploads/feedback/screenshot/5d3ffe1ff493fd185215d389/Capture.JPG    

![Screenshot](https://www.freereg.org.uk)

E0 C4 S5 C8: P17

**Comment by Captainkirkdawson** [comment]
Change was on Image Server. Langur updated. Change in effect
