### ISSUE TITLE
144439051 Data Question (Susan TRYHORN)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1236]
Issue reported by **Susan TRYHORN** at 2019-07-30 17:57:31 UTC
Time: 2019-07-30T17:41:10+00:00
Session ID: 76d6a910eb8b0b7102bdd8339db47c59
Problem Page URL: []()
Previous Page URL: [https://www.freereg.org.uk/contacts/new](https://www.freereg.org.uk/contacts/new)
Reported Issue:
Date problem Reference 144268711, 28 July 2019 and your agreement to my request also dated 28 July 2019.  
I checked your amended entry online, entering Charlotte NORRIS, Baptism 29 May 1784, Aldingbourne St Mary, Sussex. Instead of transcript, "other transcript" followed.  I clicked on Row 1 and the following appeared in RED:
"We are sorry but the record you requested no long exists; possibly as a result of some date being edited.  You will need to redo the search with the original criteria to obtain the updated version."  Why would I have to enter something wrong, BORRIS, in order to bring up the correct version NORRIS? 
I then clicked on Printable Format.  Something similar to clicking on Citation then Family Tree Maker came up.  I always copy and paste the Printable Format result directly into my FamilyTree Maker File but not this time! It appears that the correction from BORRIS to NORRIS has caused a hiccup on your website.
I should be grateful if you would investigate this matter quickly because I am in the middle of a complicated revision of thousands of my TRUSSLERs and your website has been a godsend.  Kind regards, Susan TRYHORN.    

![Screenshot](https://www.freereg.org.uk)

**Comment by richpomfret** [comment]
@edickens to take a look and try and replicate the issue - then update.

**Comment by edickens** [comment]
I get the same problem...

![Capture2.JPG](https://images.zenhubusercontent.com/5cb4c5e2cccdd751e9e85870/d58e2f74-60bd-433f-9e33-c01ce5fb21b1)

I amended the Baptism and Birth dates on the second entry.  I don't know why there are two search results.  They both give not found errors...

![Capture3.JPG](https://images.zenhubusercontent.com/5cb4c5e2cccdd751e9e85870/d2d6de40-c73b-407b-96c5-334fb4bc42db)

**Comment by edickens** [comment]
The online Edit, as well as losing the link  to Details on a search, also seems to duplicate the entry.  Can someone else please check this out.

**Comment by suffolkroots** [comment]
This sounds similar to #1216

**Comment by Captainkirkdawson** [comment]
Definitely related to #1236

**Comment by Captainkirkdawson** [comment]
@edickens @Sherlock21 fix developed and deployed to test3. Could you please test for me. 
Fix eliminates creation of new problems. It does not fix existing problems.

**Comment by Captainkirkdawson** [comment]
There are 723 search Records that do not have a connection to their original entry as a result of an on-line update. This requires the development of a rake task to correct them story #2013

**Comment by edickens** [comment]
I don't know if this has worked or not.  The entry I was working on is not in the Test3 database.  So I chose another.
I get two results for a search from one Entry...
![Capture.JPG](https://images.zenhubusercontent.com/5cb4c5e2cccdd751e9e85870/7feaf58e-9dd4-4b6d-8533-f03df3c44d58)
I then Edited this entry by adding a Birth year.  I still get two results.  (In production I would have got an extra result.)
The first is before the Edit...
![Capture1.JPG](https://images.zenhubusercontent.com/5cb4c5e2cccdd751e9e85870/924f929a-d465-488f-83b8-d0d2fa2e8ac1)
and the second after the Edit...
![Capture2.JPG](https://images.zenhubusercontent.com/5cb4c5e2cccdd751e9e85870/28144f88-d63b-428d-a74b-d8357b14f3eb)
So I don't know why there were two entries to start with and why only the second got changed.

**Comment by edickens** [comment]
Forget my previous reply.  I was unlucky and chose an entry that is duplicated exactly in a different batch.
So the amendment is working fine.  Thanks.  Eric

**Comment by Captainkirkdawson** [comment]
ericb is conducting final set of tests

**Comment by Captainkirkdawson** [comment]
Awaiting results of final testing of marriage by @Sherlock21

**Comment by Captainkirkdawson** [comment]
@SteveBiggs you may wish to get back to  Susan TRYHORN with the message that the issue has finally been resolved.
You may wish to  apologize for the time taken but note that we are a volunteer organization with limited resources 
![norris.JPG](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/cbbfbe2b-b6ba-4ecc-8cf7-9a4a5a9f5eec)

**Comment by SteveBiggs** [comment]
Reply sent to Susan.
