### ISSUE TITLE
146748092 Accessing the Roadmap (Ericd)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1237]
Issue reported by **REGManager** at 2019-08-26 11:21:32 UTC
Time: 2019-08-26T11:19:34+00:00
Session ID: 18089c24cd0bd0869e17a844c7cd7573
Problem Page URL: [/manage_resources/new?locale=en](/manage_resources/new?locale=en)
Previous Page URL: [https://www.freereg.org.uk/](https://www.freereg.org.uk/)
Reported Issue:
If I select the Action to see the Roadmap, it asks me to log in again and then I cannot get back to the website.  I think that viewing the Roadmap should be in a separate Tab.    

![Screenshot](https://www.freereg.org.uk)

**Comment by richpomfret** [comment]
Updated permissions - this should now be available for all.
