### ISSUE TITLE
146995862 Destruction of UserID not successful (Ericd)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1240]
Issue reported by **REGManager** at 2019-08-29 08:11:02 UTC
Time: 2019-08-29T08:08:51+00:00
Session ID: aa9bf863dd6f7ee8e6a22c668fdfe707
Problem Page URL: [/userid_details/5462b407e937907d70000133?locale=en&option=Select+specific+userid](/userid_details/5462b407e937907d70000133?locale=en&option=Select+specific+userid)
Previous Page URL: [https://www.freereg.org.uk/userid_details/selection?option=Select%20specific%20userid](https://www.freereg.org.uk/userid_details/selection?option=Select%20specific%20userid)
Reported Issue:
I responded to:-
"These userids has empty syndicate attribute Eiddac"
by destroying this UserID.  I received a report to say it was successful.  But it is still there.
https://www.freereg.org.uk/uploads/feedback/screenshot/5d678896f493fdf2651efd67/Capture.JPG    

![Screenshot](https://www.freereg.org.uk)

E0 U 6 S7 C6: P19

**Comment by SteveBiggs** [comment]
I've set the user as inactive and assigned a county but get the same result as Eric - Destroy says successful but user still there.

**Comment by Captainkirkdawson** [comment]
Associated with #1241; suggest it be closed

**Comment by SteveBiggs** [comment]
No this is still a problem. We are unable to destroy ANY userids. Eiddac has been set as inactive but is reported in the log of bounced emails every day.

**Comment by Captainkirkdawson** [comment]
Confirmed there is an issue

**Comment by Captainkirkdawson** [comment]
@edickens @SteveBiggs Code corrected. test3 has it deployed

**Comment by SteveBiggs** [comment]
Tested and now works.
