### ISSUE TITLE
147253449 Update UserID syndicate not recognised (Ericd)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1241]
Issue reported by **REGManager** at 2019-09-01 07:44:09 UTC
Time: 2019-09-01T07:40:24+00:00
Session ID: e16288bde51a64c525dc84edd19ce584
Problem Page URL: [/userid_details/5462b407e937907d70000133?locale=en&option=Select+specific+userid](/userid_details/5462b407e937907d70000133?locale=en&option=Select+specific+userid)
Previous Page URL: [https://www.freereg.org.uk/userid_details/selection?option=Select%20specific%20userid](https://www.freereg.org.uk/userid_details/selection?option=Select%20specific%20userid)
Reported Issue:
The overnight checks at 01.35 on 1st September say "These userids has empty syndicate attribute Eiddac" but it has been edited and does have a syndicate.
    

![Screenshot](https://www.freereg.org.uk)

**Comment by SteveBiggs** [comment]
Eiddac was assigned to a syndicate in live but still giving this report. I have now assigned them in test2 and test3 and it appears that the 'empty syndicate' reports have now stopped.

**Comment by Captainkirkdawson** [comment]
Closed?

**Comment by SteveBiggs** [comment]
Yes this can be closed.

**Comment by richpomfret** [comment]
Closing.
