### ISSUE TITLE
148475871 The Live Website says that is a Test website (Eric D)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1243]
Issue reported by **REGManager** at 2019-09-15 11:17:51 UTC
Time: 2019-09-15T11:17:01+00:00
Session ID: 212cca5811acc94967934ff01af9c9b9
Problem Page URL: [/manage_resources/new?locale=en](/manage_resources/new?locale=en)
Previous Page URL: [https://www.freereg.org.uk/cms/refinery/login](https://www.freereg.org.uk/cms/refinery/login)
Reported Issue:
Urgent correction needed
https://www.freereg.org.uk/uploads/feedback/screenshot/5d7e1ddff493fde793c1eb52/Capture.JPG    

![Screenshot](https://www.freereg.org.uk)

**Comment by richpomfret** [comment]
Fixed. Shall close.
