### ISSUE TITLE
148486974 Data Question (Daphne Aust)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1244]
Issue reported by **Daphne Aust** at 2019-09-15 14:22:54 UTC
Time: 2019-09-15T14:20:47+00:00
Session ID: e36c8a0ffad2ee3f66fd42f7fde699b6
Problem Page URL: []()
Previous Page URL: [https://www.freereg.org.uk/contacts/new](https://www.freereg.org.uk/contacts/new)
Reported Issue:
Why is there a red warning coming up on the site page saying that this is a development only page and to go to freeREG which is highlighted.   When pressed it only returns you to the same page

This has not happened before    

![Screenshot](https://www.freereg.org.uk)

**Comment by edickens** [comment]
I see that it has been fixed.

**Comment by richpomfret** [comment]
Shall close.
