### ISSUE TITLE
148820052 With all forms of messages the archiving lists the whole archive (Eric D)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1245]
Issue reported by **REGManager** at 2019-09-19 10:54:12 UTC
Time: 2019-09-19T10:50:49+00:00
Session ID: a325e7219d0b4da4abf1ff618b227c27
Problem Page URL: [/contacts/list_archived?locale=en](/contacts/list_archived?locale=en)
Previous Page URL: [https://www.freereg.org.uk/contacts/5d80c1e7f493fd68e3c611bf?locale=en](https://www.freereg.org.uk/contacts/5d80c1e7f493fd68e3c611bf?locale=en)
Reported Issue:
When I archive a Comment, Feedback or Message, the server then switches screen and downloads the whole of the archive.
Can the current screen be retained and the cursor left on the next entry?
If I need to look at the Archive, there is a button for this.
Eric D    

![Screenshot](https://www.freereg.org.uk)

Lists, rather than downloads the archive.

E0 U4 S8 C8: P20

**Comment by edickens** [comment]
Title needs changing to say that it is archiving of Messages so as not to confuse with archiving batches.

**Comment by Captainkirkdawson** [comment]
@edickens The backlog has been eliminated. List much smaller and will be pruned monthly see production
