### ISSUE TITLE
150452176 Number of records (Edwin)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1247]
Issue reported by **14247** at 2019-10-08 08:16:16 UTC
Time: 2019-10-08T08:13:05+00:00
Session ID: c98be1624a3cb20a75fdab18acf72ff3
Problem Page URL: [/freereg1_csv_files/my_own](/freereg1_csv_files/my_own)
Previous Page URL: [https://www.freereg.org.uk/userid_details/my_own](https://www.freereg.org.uk/userid_details/my_own)
Reported Issue:
Quite some time ago I asked if the total number of records uploaded could be added to the 'profile'. You said it would go in the pipeline but would be a while.
I am not sure how long ago I asked but it must be 2 or 3 years. Any sign of progress here ?

Edwin Furnival    

![Screenshot](https://www.freereg.org.uk)

**Comment by richpomfret** [comment]
We have this as a story (1134) and will address in due course. @PatReynolds to get back Edwin.

**Comment by PatReynolds** [comment]
E£mail sent 5/5/2019

**Comment by richpomfret** [comment]
Closing.
