### ISSUE TITLE
151229842 Simon 2709 On the full listing of all transcribers in the syndicate it says that Simone has 1 file.  When you ask for it to show her batches there are 2.  I'm hoping this is just the system not putting the right number and that all entries from both files are included for searching purposes (Joanne)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1249]
Issue reported by **ManCity** at 2019-10-17 08:17:22 UTC
Time: 2019-10-17T08:17:01+00:00
Session ID: 8e2c073ed1d5ce819f884fa34a349b18
Problem Page URL: [/manage_resources/new?locale=en](/manage_resources/new?locale=en)
Previous Page URL: [https://www.freereg.org.uk/cms/refinery/login](https://www.freereg.org.uk/cms/refinery/login)
Reported Issue:
    

![Screenshot](https://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
I can assure Joanne that the 3 files that are there now are loaded.
Why it is reporting 2 and not 3 is unclear and will be impossible to determine.
One can speculate that 1 was somehow loaded while the person was being changed from trainee to transcriber but it is not possible to confirm.
This will be corrected when we rewrite the process of calculating files and records for userids
I do suggest that Joanne look at the transcriptions for the burials as they are quite problematic
![burial entries.JPG](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/af56cd0d-c9a6-412b-bc34-0a29de102fe0)

**Comment by richpomfret** [comment]
@SteveBiggs to reply. Can then close.

**Comment by SteveBiggs** [comment]
Reply sent so closing.
