### ISSUE TITLE
About page missing (juliancheal)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#125]
Issue reported by **juliancheal** at 2014-12-24 00:02:27 UTC
Time: 2014-12-24T00:01:33+00:00
Session ID: 5deb3d1a0a21313708d6e1b3fe45210a
Problem Page URL: [/about](/about)
Previous Page URL: [http://test2.freereg.org.uk/](http://test2.freereg.org.uk/)
Reported Issue:
The About Us link leads to a missing page    

![Screenshot](http://test2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Should be there now Julian; you caught me in the middle of doing some changes (usually done at night in the UK!!!)
