### ISSUE TITLE
151798019 Search not finding surnames (Staffordshire)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1250]
Issue reported by **STSCoord** at 2019-10-23 22:06:59 UTC
Time: 2019-10-23T21:51:07+00:00
Session ID: 965ded2caa802c0d76ec6ebf0a66fabc
Problem Page URL: [/search_records/5817edb6e93790eca328ffe1/joshua-wettwood-baptism-staffordshire-newcastle-under-lyme-1707-10-16?locale=en](/search_records/5817edb6e93790eca328ffe1/joshua-wettwood-baptism-staffordshire-newcastle-under-lyme-1707-10-16?locale=en)
Previous Page URL: [https://www.freereg.org.uk/search_queries/5db0cafff493fdd3de078dec?locale=en](https://www.freereg.org.uk/search_queries/5db0cafff493fdd3de078dec?locale=en)
Reported Issue:
A problem initiated by EricB but I know the details so I am entering the problem report.

I have been splitting files into more manageable chunks.

There is a baptism entry in the large file with a name of Joshua Birks 1707. As I split the large file, I noticed that there was a note recording the name of the father as Samll. Wettwood. I amended the record in the small file so that the father's name was recorded which of course meant that the surname Birks was moved into the mothers surname. The small file was processed into FreeREG.

So now, theoretically, there should be two search results for Joshua Birks, one with the fathers surname in the large file and one with the mothers surname in the small file.

BUT THERE IS ONLY ONE - the one in the large file.

Why?

But the record can be found by doing a search for Joshua Wettwood.

Does this mean that FreeREG only searches the fathers surname?

Other screen captures are available if required.
https://www.freereg.org.uk/uploads/feedback/screenshot/5db0cf03f493fdd3e4024f3c/details_of_search_different_surname.JPG    

![Screenshot](https://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
If you do a search for Joshua Birks WITH the Family Members option you will retrieve the new record.
This is how the search is expected to work. On baptisms the search is always a paternal surname search which is the reason for the search option to include family members ie a maternal search in the case of baptisms.

**Comment by richpomfret** [comment]
@SteveBiggs to reply and we can then close.

**Comment by SteveBiggs** [comment]
Reply sent so closing.
