### ISSUE TITLE
152181250 No statistics (Eric D)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1251]
Issue reported by **REGManager** at 2019-10-28 08:34:10 UTC
Time: 2019-10-28T08:32:59+00:00
Session ID: b6ea91dd2bbd3f285f6e90a86019ad5c
Problem Page URL: [/manage_resources/new?locale=en](/manage_resources/new?locale=en)
Previous Page URL: [https://www.freereg.org.uk/cms/refinery/login](https://www.freereg.org.uk/cms/refinery/login)
Reported Issue:
The footer says that no records were uploaded yesterday.  This cannot be correct.  Something has gone wrong.    

![Screenshot](https://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Suspect its a result of your clock fall back change
