### ISSUE TITLE
152616967 General Comment (Tom Brookes)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1252]
Issue reported by **Tom Brookes** at 2019-11-02 09:36:07 UTC
Time: 2019-11-02T09:28:35+00:00
Session ID: a7d11d4510fccf1be353ac764791ae3f
Problem Page URL: []()
Previous Page URL: [https://www.freereg.org.uk/contacts/new](https://www.freereg.org.uk/contacts/new)
Reported Issue:
Possible bug in nearby places option.

Hi there,
I think there is a bug in the nearby places option.  To recreate it do the following:
Surname Darby, first year 1650, last year 1700, set soundex
If you choose Staffordshire, Rowley Regis with nearby places set, you get about 150 records returned.
If you choose Worcestershire, Netherton with nearby places set you only get 15 records returned, none of which are from Rowley Regis.
If you look at the map, these places are only about 2 miles apart.

Hope that this helps a very good site to get better.

Kind Regards

Tom Brookes

**Comment by Sherlock21** [comment]
The Netherton (WOR) that Tom Brooks refers to, is actually the one near Evesham - so no wonder its a bit out of range with Rowley Regis (STS).
He had in mind the district of Netherton that is in Dudley (WOR) - so I will consider making the latter into a place of its own. It will take a while to do,
- Thanks for finding that snag.

 The other pint of Tom Brooks note leads me to a discovery of something that is a snag however. - I will write another story on that, as it will no doubt develop somewhat.

**Comment by Sherlock21** [comment]
The Netherton (WOR) that Tom Brooks refers to, is actually the one near Evesham - so no wonder its a bit out of range with Rowley Regis (STS).
He had in mind the district of Netherton that is in Dudley (WOR) - so I will consider making the latter into a place of its own. It will take a while to do,
- Thanks for finding that snag.

 The other pint of Tom Brooks note leads me to a discovery of something that is a snag however. - I will write another story on that, as it will no doubt develop somewhat.

**Comment by richpomfret** [comment]
@edickens to reply. We can otherwise close this now that another story has been created.

**Comment by edickens** [comment]
Done.  Eric
