### ISSUE TITLE
153221170 Contacts for userID LDMDX (Sandra)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1254]
Issue reported by **LDMDX** at 2019-11-09 09:26:10 UTC
Time: 2019-11-09T09:24:02+00:00
Session ID: a99b137263c0c3a9c84fdc53365e124c
Problem Page URL: [/contacts?](/contacts?)
Previous Page URL: [https://www.freereg.org.uk/manage_resources/new?locale=en](https://www.freereg.org.uk/manage_resources/new?locale=en)
Reported Issue:
All contacts for the website, inc for other counties and ones that would be handled by the Communications Coordinator or their delegate are some some reason showing up here (please see screen shot attached}. Can you please fix this. Thanks
https://www.freereg.org.uk/uploads/feedback/screenshot/5dc68632f493fd7b7411be90/LND.jpg    

![Screenshot](https://www.freereg.org.uk)

**Comment by SteveBiggs** [comment]
This appears to be unique to Sandra's userid - LDMDX which is a County Coord role. When I log in with my CC id, I only see Contacts for my counties. Could it be connected with the fact that Sandra used to be the Comms Coord?
