### ISSUE TITLE
149680811 Website Problem (Warren Meads)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1255]
Issue reported by **Warren Meads** at 2019-09-29 10:00:11 UTC
Time: 2019-09-29T09:54:32+00:00
Session ID: 44fd0ab9c4b0d7f3038b0a3f02fcd8a8
Problem Page URL: []()
Previous Page URL: [https://www.freereg.org.uk/contacts/new](https://www.freereg.org.uk/contacts/new)
Reported Issue:
I am getting errors when I use the URL in the generated Citation for WikiTree.  Here is an example

The citation generated 
Dursley : St James : Register of unspecified type : "Parish Register" database, FreeREG (https://www.freereg.org.uk/search_records/581832d1e93790ec8be6919c : viewed 29 Sep 2019) baptism Mary Harman 17 Jun 1781 

the URL when the record is actually looked at is 
https://www.freereg.org.uk/search_records/581832d1e93790ec8be6919c/mary-harman-baptism-gloucestershire-dursley-1781-06-17?locale=en

So it looks like the URL in the Citation is being truncated.

Warren Meads

**Comment by richpomfret** [comment]
@PatReynolds to respond.

**Comment by PatReynolds** [comment]
Cannot find this feedback/contact - can't seem to find anything starting 14 (15 is the earliest).

**Comment by Captainkirkdawson** [comment]
I expect it got cleared out given its age.

**Comment by PatReynolds** [comment]
Maybe we are deleting too soon.  It took six weeks to get from being made to our attention, and then a little over three months to resolution.  
In this case, I could contact the sender via the Wikitree page for Mary Harman born 17 Jun 1781.

**Comment by Captainkirkdawson** [comment]
We have a keep option for any story

**Comment by PatReynolds** [comment]
Ah ... will use in future!  Just chcked open stories raised this way, and all are either too old to hold, or from a FreeREG volunteer, so contactable.
