### ISSUE TITLE
154012756 Unsuccessful attempt to change register type (Barrie)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1257]
Issue reported by **brobinson43** at 2019-11-18 13:19:16 UTC
Time: 2019-11-18T13:10:29+00:00
Session ID: 5da974fc58217933be27e06ac2b8d8d6
Problem Page URL: [/csvfiles/new?locale=en](/csvfiles/new?locale=en)
Previous Page URL: [https://www.freereg.org.uk/csvfiles/new?locale=en](https://www.freereg.org.uk/csvfiles/new?locale=en)
Reported Issue:
I overlooked putting "PR" into the church/register name in brobinson43:WARALLBU1.CSV, so I went in and changed the register type, successfully. However, it was still listed under register type Unspecified, so I tried to move it to the register, Parish Register, and you will no doubt have been notified the "Something went wrong." This batch does not now appear under that place and church, but the system still recognizes that it is present, or at least that I have uploaded it, as I tried to upload again the file with the PR added, and the system told me I couldn't do this.
I rather think the batch is still present, but in limbo somewhere. If it isn't, once you have acquainted the system of that fact, I can re-upload the batch, but I await your instructions.

Barrie Robinson    

![Screenshot](https://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Cleaned up
