### ISSUE TITLE
154367772 age section needs updating (Corinne)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1258]
Issue reported by **chm** at 2019-11-22 15:56:12 UTC
Time: 2019-11-22T15:48:14+00:00
Session ID: edd388bd97a96c89d4e0d6ef5d3406be
Problem Page URL: [/cms/information-for-transcribers/entering-data-from-registers](/cms/information-for-transcribers/entering-data-from-registers)
Previous Page URL: []()
Reported Issue:
The section on "age" needs to include that "h" is an acceptable abbreviation for hours (assuming this is correct - the system certainly seems to accept hours).

It also needs to mention "infant" as an acceptable value here, if it is accepted by the system, as Cathy on the transcribers mailing list has suggested to be the case.

It would also be helpful if it gave advice on which is preferred between "infant" or "0" in the case where the age is given as under an hour.  I would have thought infant should be avoided where possible as it can mean a young child of quite a range of ages (an infants' school is not for babies).    

![Screenshot](https://www.freereg.org.uk)

**Comment by AlOneill** [comment]
Details for this update are not complete — the description has a couple of unanswered questions.

Can someone please confirm:
1. whether or not 'infant' is an acceptable entry
2. 'infant' or '0' (zero) — which is preferred for an age given as **less than an hour**?

Thank you.

**Comment by PatReynolds** [comment]
1. Yes, 'infant' is an acceptable entry.
2. '0' - actual age, e.g. "less than an hour old" should be fully transcribed in the notes.

**Comment by AlOneill** [comment]
Three pages updated:
https://test3.freereg.org.uk/cms/information-for-transcribers/flexible-csv-format/extended-baptism-fields
https://test3.freereg.org.uk/cms/information-for-transcribers/flexible-csv-format/extended-burial-fields
https://test3.freereg.org.uk/cms/information-for-transcribers/entering-data-from-registers#burL

The pages are sync-ready.
