### ISSUE TITLE
154396834 CommsCoord contact header spelling wrong (Communiations)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1259]
Issue reported by **CommsCoord** at 2019-11-23 00:00:34 UTC
Time: 2019-11-22T23:56:23+00:00
Session ID: 5b985ab94fd067136606fb68b9c3e9f8
Problem Page URL: [/messages/5dd6a2abf493fd1fcd1c785c?locale=en&source=original](/messages/5dd6a2abf493fd1fcd1c785c?locale=en&source=original)
Previous Page URL: [https://www.freereg.org.uk/messages/select_individual?id=5dd6a2abf493fd1fcd1c785c&locale=en&role=county_coordinator](https://www.freereg.org.uk/messages/select_individual?id=5dd6a2abf493fd1fcd1c785c&locale=en&role=county_coordinator)
Reported Issue:
The CommsCoord contact header has the word Communications spelled incorrectly. Can this please be fixed? Thank you
https://www.freereg.org.uk/uploads/feedback/screenshot/5dd876a2f493fd785323d860/Comms.jpg    

![Screenshot](https://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
This is not a systems issue. The misspelt word is the forename entered for the userid. Have edited the userid
