### ISSUE TITLE
Just a test (Kirk Dawson)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#126]
Issue reported by **Kirk Dawson** at 2014-12-28 20:33:14 UTC
Time: 2014-12-28T20:33:14+00:00
Session ID: 32f6140cf86c665b6e114409ed2a8d73
Problem Page URL: [/contacts](/contacts)
Previous Page URL: [http://test2.freereg.org.uk/contacts/new](http://test2.freereg.org.uk/contacts/new)
Reported Issue:
Testing    

![Screenshot](http://test2.freereg.org.uk/tmp/carrierwave/1419798794-65304-2299/_1.JPG)

**Comment by Captainkirkdawson** [comment]
Just a test of the contact system
