### ISSUE TITLE
155864660 Odd problem in new county report (Staffordshire)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1261]
Issue reported by **STSCoord** at 2019-12-09 23:44:20 UTC
Time: 2019-12-09T23:32:30+00:00
Session ID: f631a0a48a0c910c4bd84a85463d1759
Problem Page URL: [/manage_counties/selection?option=Offline%20Reports](/manage_counties/selection?option=Offline%20Reports)
Previous Page URL: [https://www.freereg.org.uk/manage_counties/select_action?locale=en](https://www.freereg.org.uk/manage_counties/select_action?locale=en)
Reported Issue:
I have used the new county report and received the email containing the CSV file. This is good.

BUT, there is a problem in the file. For some reason the data gets offset by one column for STS|Bilston|Bilston Cemetery| Cemetery Lane (Consecrated Ground) for userid Judith. The "Register", Userid", "records", "Min year" and "Max year" column data is offset to the right by one column.

This is very unusual.    

![Screenshot](https://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
The off set is likely caused by one of the fields having a comma in it somewhere. Since csv files are comma separated it will produce such an offset. Place Church and Register should not have any internal comma's

**Comment by richpomfret** [comment]
@edickens to take a look and review this.

**Comment by edickens** [comment]
I have run the report and cannot find a problem.  There is no offset at the end of the report, so if I missed one entry, then it does not affect future rows.
I suggest a screen-print of the problem Place/Church is needed.

**Comment by richpomfret** [comment]
@SteveBiggs or @edickens can you request extra info here for us?

**Comment by edickens** [comment]
I will request a copy of the report because the screen shot does not come up in the first message above.

**Comment by edickens** [comment]
The Church name has a comma in it.
![Capture.JPG](https://images.zenhubusercontent.com/5cb4c5e2cccdd751e9e85870/6caeb3fd-487b-4679-8cc8-c8811aa31172)
The solution is that in the CSV file, all fields should be enclosed in double quotes.

**Comment by richpomfret** [comment]
@edickens shall we remove the 'high priority' on this? Is this still valid?

**Comment by edickens** [comment]
The problem is in the Offline Reports 
![Capture1.JPG](https://images.zenhubusercontent.com/5cb4c5e2cccdd751e9e85870/010a76af-fc9c-4897-8675-7010507a2c4c)
where the County Content Report does not have quotes around the fields.
![Capture.JPG](https://images.zenhubusercontent.com/5cb4c5e2cccdd751e9e85870/d475a5b0-0743-4db3-9b0e-b93a962405bc)
It is a CSV report so would be opened in a spreadsheet.
This should be sorted out, but it is a report only used by CCs, and if they know the problem it is quite easy to fix, so I don't think High Priority is needed.  Eric D

**Comment by Captainkirkdawson** [comment]
@jayto581 would you like to try your hand at this one?

You would have to locate where the field is written and ensure it is quoted "field"

**Comment by jayto581** [comment]
Pull request submitted.  branch: odd issue 155864660

Based on what if can figure out in the code, this should fix the problem. I am able to generate a county coordinator report to properly test the fix.

**Comment by Captainkirkdawson** [comment]
Tested, pulled into master and being deployed
