### ISSUE TITLE
156171952 What 'Upload button" (Staffordshire)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1262]
Issue reported by **STSCoord** at 2019-12-13 13:05:52 UTC
Time: 2019-12-13T13:02:39+00:00
Session ID: f631a0a48a0c910c4bd84a85463d1759
Problem Page URL: [/csvfiles/5463a5cee937904abbc6053e/edit?locale=en](/csvfiles/5463a5cee937904abbc6053e/edit?locale=en)
Previous Page URL: [https://www.freereg.org.uk/freereg1_csv_files/5463a5cee937904abbc6053e?locale=en](https://www.freereg.org.uk/freereg1_csv_files/5463a5cee937904abbc6053e?locale=en)
Reported Issue:
There is no "Upload button"in the Replace process.
https://www.freereg.org.uk/uploads/feedback/screenshot/5df38cb0f493fdde82eed848/Capture.JPG    

![Screenshot](https://www.freereg.org.uk)

**Comment by SteveBiggs** [comment]
It should say "Click the Replace button ...."
