### ISSUE TITLE
156207473 Zero errors but many lines rejected on a replace processing email (Staffordshire)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1263]
Issue reported by **STSCoord** at 2019-12-13 22:57:53 UTC
Time: 2019-12-13T22:49:44+00:00
Session ID: f631a0a48a0c910c4bd84a85463d1759
Problem Page URL: [/registers/5cf161c8f493fd23aebc2f44?locale=en](/registers/5cf161c8f493fd23aebc2f44?locale=en)
Previous Page URL: [https://www.freereg.org.uk/churches/5409d257eca9eba2061b4704?locale=en](https://www.freereg.org.uk/churches/5409d257eca9eba2061b4704?locale=en)
Reported Issue:
Subject of processing email states zero errors, But many lines are shown as ignored.

This can be very misleading and, potentially, lose transcribed records when the transcriber thinks they have been successfully processed.
https://www.freereg.org.uk/uploads/feedback/screenshot/5df41771f493fdde82f30fe6/Capture.JPG    

![Screenshot](https://www.freereg.org.uk)

**Comment by richpomfret** [comment]
Agreed for @PatReynolds to inform users that an email should still be read even if there is 0 errors found - as this does not cover every eventuality.

**Comment by SteveBiggs** [comment]
I have replied to Michael.

**Comment by PatReynolds** [comment]
Message sent 19/2/2020

**Comment by PatReynolds** [comment]
A transcriber asks "That will teach me to check the "zero errors" message as I must admit to assuming, quite wrongly it seems, that everything is OK.  I would like to correct any errors but do I have to go back through all the registers I have transcribed or just the last two or three?"

What is the answer, pleae?

**Comment by SteveBiggs** [comment]
I would suggest that if they have deleted the processing email, there's little point in going back to check as it will be very difficult and time consuming to identify problems.

**Comment by PatReynolds** [comment]
@SteveBiggs  a transcriber has replied "I am a new(ish) transcriber and have uploaded 4 batches so far but have never received an email to say my file has been uploaded with "zero errors". I have always presumed there are no errors when I click on "Files with errors" or "Action: ER" and it says "There are no errors". I have checked the email address on my profile and it is correct. Not sure why I'm not getting any emails."  Could you let me know what to tell them?  Thanks, Pat

**Comment by SteveBiggs** [comment]
Looking at the messages, this userID is Juec and she is set so that "SC uploads my data:" is true meaning she will not get any processing emails. She's in Julie Harold's Essex syndicate so I suggest you copy Julie as well.
