### ISSUE TITLE
156515847 Why is a registration incomplete (Eric D)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1265]
Issue reported by **REGManager** at 2019-12-17 12:37:27 UTC
Time: 2019-12-17T12:35:26+00:00
Session ID: 40df6e8e6072cb12bc31c3ab16a9893e
Problem Page URL: [/userid_details/incomplete_registrations](/userid_details/incomplete_registrations)
Previous Page URL: [https://www.freereg.org.uk/userid_details/options?locale=en](https://www.freereg.org.uk/userid_details/options?locale=en)
Reported Issue:
Can the Action to list incomplete registrations also show the reason?    

![Screenshot](https://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
There is only one reason. The person has not responded to the email requesting that they set their own password

**Comment by edickens** [comment]
Is this in the Help?  If it is, why did the CC ask?
