### ISSUE TITLE
156983949 Most of the links for County options are not working (Mick)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1266]
Issue reported by **Mick** at 2019-12-22 22:39:09 UTC
Time: 2019-12-22T22:35:48+00:00
Session ID: c6ad03b48e373e64ed1cfba387a269a8
Problem Page URL: [/manage_counties/select_action?locale=en](/manage_counties/select_action?locale=en)
Previous Page URL: [https://www.freereg.org.uk/manage_counties/select_action?locale=en](https://www.freereg.org.uk/manage_counties/select_action?locale=en)
Reported Issue:
Whenever I click to view most recent batch for example I get a message saying Missing Parameters    

![Screenshot](https://www.freereg.org.uk)

**Comment by SteveBiggs** [comment]
I have tested and get the same problem under Manage County. (It is possible to view batches under Manage Syndicate).

**Comment by Captainkirkdawson** [comment]
Fixed
