### ISSUE TITLE
160150660 Website Problem (Ros Norris)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1269]
Issue reported by **Ros Norris** at 2020-01-28 14:17:40 UTC
Time: 2020-01-28T14:15:01+00:00
Session ID: 4842725b85cd167ac32767afc5802ebb
Problem Page URL: []()
Previous Page URL: [https://www.freereg.org.uk/contacts/new](https://www.freereg.org.uk/contacts/new)
Reported Issue:
I can hardly use Freereg on the iPad anymore because there are adverts halfway across the results list. This seems to be a recent problem as it was ok last week. Is it possible to fix this?

**Comment by Captainkirkdawson** [comment]
@PatReynolds @richpomfret It would appear that MM have switched our left side add to a skyscraper without our changing the page layout  ie dropping one and repositioning to right. Hence display is bad on all screens

This will be especially notable on the original ipad with a 1024x768 display.

**Comment by Captainkirkdawson** [comment]
@DeniseColbert @PatReynolds @richpomfret 
Have adjusted layout on test3.  **note I am using the left side bar ad as this is 300px. The right one was still 160**

**Comment by DeniseColbert** [comment]
The left ad has gone, the one on the right is fine: (edited: the ad dimensions change- hadn't realised)

**Comment by DeniseColbert** [comment]
![image](https://user-images.githubusercontent.com/19173257/73310461-4c02f080-421c-11ea-89bc-6af2c2ce41fb.png)

**Comment by Captainkirkdawson** [comment]
Deployed
