### ISSUE TITLE
Hover over Selections (steveroland)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#127]
Issue reported by **steveroland** at 2014-12-30 13:21:54 UTC
Time: 2014-12-30T13:15:02+00:00
Session ID: fcd22e5450ae39b4400a0ea83969f220
Problem Page URL: [/search_queries/new](/search_queries/new)
Previous Page URL: [http://test2.freereg.org.uk/freereg_contents/5409dab6eca9eba206373cab/show_church](http://test2.freereg.org.uk/freereg_contents/5409dab6eca9eba206373cab/show_church)
Reported Issue:
On the main search page (http://test2.freereg.org.uk/search_queries/new), I would suggest adding information icons as used on the search results page so that hovering over the 'i' gives the info rather than hovering on the clickable selection itself.    

![Screenshot](http://test2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Included in analyis
