### ISSUE TITLE
160309861 Issue with Members menu (Mick)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1270]
Issue reported by **Mick** at 2020-01-30 10:31:01 UTC
Time: 2020-01-30T10:29:03+00:00
Session ID: f3c72bfc586b90aec0a57a8e2316e626
Problem Page URL: [/manage_counties/select_action?locale=en](/manage_counties/select_action?locale=en)
Previous Page URL: [https://www.freereg.org.uk/manage_counties/select_action?locale=en](https://www.freereg.org.uk/manage_counties/select_action?locale=en)
Reported Issue:
When I click on the menu button to review most recent batch uploaded it comes back with the error message Missing Parameter.    

![Screenshot](https://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Insufficient information on which to conduct any diagnosis. What county?

**Comment by richpomfret** [comment]
Should now be fixed.
