### ISSUE TITLE
160409681 different results.. Download/Browse (Doreen)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1272]
Issue reported by **deo123** at 2020-01-31 14:14:41 UTC
Time: 2020-01-31T14:05:32+00:00
Session ID: 47d24678e60bb3bf76753ad805346987
Problem Page URL: [/freereg1_csv_files/5463cf0de9379027829f4aa9?locale=en](/freereg1_csv_files/5463cf0de9379027829f4aa9?locale=en)
Previous Page URL: [https://www.freereg.org.uk/registers/540a1615eca9ebd28e1c0c46?locale=en](https://www.freereg.org.uk/registers/540a1615eca9ebd28e1c0c46?locale=en)
Reported Issue:
Hi Team,

I have just found a different results between Download batch & Browse batch
Download is showing year date as 1818 and the browse is showing year date 1828

I did a screen shot of the browse taken at the same time

Regards Doreen
https://www.freereg.org.uk/uploads/feedback/screenshot/5e343651f493fdb37f9c84db/LEIBARBA1_5_Feb_1818_from_download_batch.JPG    

![Screenshot](https://www.freereg.org.uk)

**Comment by SteveBiggs** [comment]
Doreen sent the other screen shot showing the discrepancy.

![LEIBARBA1 5 feb 1828 fron Browse  records.JPG](https://images.zenhubusercontent.com/5cb596063b6bd6333fc1dc24/ee8edd2d-ab1c-48c7-8c82-527cd7296819)

**Comment by Captainkirkdawson** [comment]
I am sorry but there is no discrepancy between the on-line file and a download of the file.

There are actually 2 records both online and in the file; one with 1818 and the other with 1828
![one.JPG](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/6a343c7c-7c9f-4f50-9428-aba919ee738a) 
![two.JPG](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/4e902f1b-8bbd-49a7-b477-ac42efb4a038)
