### ISSUE TITLE
161697953 Send Message waiting wheel is not there (Eric D)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1276]
Issue reported by **REGManager** at 2020-02-15 12:05:53 UTC
Time: 2020-02-15T12:04:13+00:00
Session ID: 706eb191d9b898733a3571ffacd0a3e4
Problem Page URL: [/messages/5e3a4e52f493fd1ad1c634a3?locale=en&source=original](/messages/5e3a4e52f493fd1ad1c634a3?locale=en&source=original)
Previous Page URL: [https://www.freereg.org.uk/messages/5e3a4e52f493fd1ad1c634a3/select_recipients?locale=en&source=original](https://www.freereg.org.uk/messages/5e3a4e52f493fd1ad1c634a3/select_recipients?locale=en&source=original)
Reported Issue:
When I send a message to a lot of people the circle for the waiting wheel is there, but nothing in it.    

![Screenshot](https://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
@edickens Move your mouse off the button

**Comment by edickens** [comment]
I will check that next time I send to a large group.  TY
Can be closed.
