### ISSUE TITLE
161740944 Website Problem (Claire Reilly)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1277]
Issue reported by **Claire Reilly** at 2020-02-16 00:02:24 UTC
Time: 2020-02-15T23:56:14+00:00
Session ID: 8acaf05986e2c1d6c32dcb1866a927de
Problem Page URL: []()
Previous Page URL: [https://www.freereg.org.uk/contacts/new](https://www.freereg.org.uk/contacts/new)
Reported Issue:
Hi
I'm wondering if there is a problem with the website lay out at the moment. 

The adverts on the right hand side aren't alined to the right side. There is a gap. It means that the table of search results is narrowed and squashed which makes it harder to view. 

When I narrow the browser window it gets worse. 

Screen shots attached, in case this is not supposed to be happening. The browser I am using is Chrome. 

https://www13.freereg.org.uk/uploads/contact/screenshot/5e488690f493fdcfe6aa7c13/Screenshot_2020-02-15_at_23.56.37.png

**Comment by Captainkirkdawson** [comment]
Have tried floating the ad to the right on test3

**Comment by PatReynolds** [comment]
Works as expected (and looks good).

**Comment by Captainkirkdawson** [comment]
The only issue is that at low screen width the ad overlaps the table

**Comment by richpomfret** [comment]
Let's roll it out onto live and see what comes back (if anything).
