### ISSUE TITLE
161974280 Date should read Year? (Stephen)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1280]
Issue reported by **steveroland** at 2020-02-18 16:51:20 UTC
Time: 2020-02-18T16:49:49+00:00
Session ID: a72ace5b1a5f9959d6558c25e4533e00
Problem Page URL: [/gaps/new?freereg1_csv_file=5c7f38b2f493fdaf4732fd92&locale=en&register=5c7ad346f493fd447480b27a](/gaps/new?freereg1_csv_file=5c7f38b2f493fdaf4732fd92&locale=en&register=5c7ad346f493fd447480b27a)
Previous Page URL: [https://www.freereg.org.uk/gaps/new?freereg1_csv_file=5c7f38b2f493fdaf4732fd92&locale=en&register=5c7ad346f493fd447480b27a](https://www.freereg.org.uk/gaps/new?freereg1_csv_file=5c7f38b2f493fdaf4732fd92&locale=en&register=5c7ad346f493fd447480b27a)
Reported Issue:
As only years can be entered should it ask for Start Year and End Year?    

![Screenshot](https://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Fix deployed to test3

**Comment by SteveBiggs** [comment]
Looks good.
