### ISSUE TITLE
162598035 typo! (Helen)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1281]
Issue reported by **HelenB** at 2020-02-25 22:07:15 UTC
Time: 2020-02-25T22:05:27+00:00
Session ID: 5399af66bf8654c2da7984bfe844b62c
Problem Page URL: [/gaps?freereg1_csv_file=5e0916dff493fd6b33c18688&locale=en&register=56d389e4f493fdb10d000002](/gaps?freereg1_csv_file=5e0916dff493fd6b33c18688&locale=en&register=56d389e4f493fdb10d000002)
Previous Page URL: [https://www.freereg.org.uk/gaps/new?freereg1_csv_file=5e0916dff493fd6b33c18688&locale=en&register=56d389e4f493fdb10d000002](https://www.freereg.org.uk/gaps/new?freereg1_csv_file=5e0916dff493fd6b33c18688&locale=en&register=56d389e4f493fdb10d000002)
Reported Issue:
The reason  "No Access (Custiodian/Owner untraced) "   contains a typo in the work Custodian.    

![Screenshot](https://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
done
