### ISSUE TITLE
163763379 Transcription is showing all places, not just those with entries (Eric D)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1282]
Issue reported by **REGManager** at 2020-03-10 09:49:39 UTC
Time: 2020-03-10T09:46:32+00:00
Session ID: 4ea02014bd707cc48fec883af3d354ff
Problem Page URL: [/freereg_contents/53cbf5fceca9eb03a6007524?locale=en](/freereg_contents/53cbf5fceca9eb03a6007524?locale=en)
Previous Page URL: [https://www.freereg.org.uk/freereg_contents?locale=en](https://www.freereg.org.uk/freereg_contents?locale=en)
Reported Issue:
When a researcher selects Transcriptions, all place are coming up.  We tell them that this is just a list of what we have.  There are no entries shown if there aren't any, but this could be confusing.  It is also easier to know that if the place is not in the list, then there are no entries.    

![Screenshot](https://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
This was a deliberate design change due to the decision on gaps and showing registers and therefore places and churches for which we have no access.
It was also one of the main reasons for seeking an automated means of loading all known churches

**Comment by Captainkirkdawson** [comment]
The chapeau to transcriptions says
These pages contain information about each County, Place, Church and Register in the database: everything from a detailed county listing right down to how many records the database holds for every ten-year period of an individual register. In some cases it may also contains information about why there are no records available including known Gaps and Embargoes imposed by our sources.

**Comment by edickens** [comment]
Thanks Kirk for the explanation.  This can be closed.
