### ISSUE TITLE
163948322 New Unique Names layout required (Staffordshire)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1283]
Issue reported by **STSCoord** at 2020-03-12 13:12:02 UTC
Time: 2020-03-12T13:05:57+00:00
Session ID: a052e2255bb8c30c8b88571aed01612c
Problem Page URL: [/freereg1_csv_files/unique_names?locale=en&object=5463c5bae937904abb64b642](/freereg1_csv_files/unique_names?locale=en&object=5463c5bae937904abb64b642)
Previous Page URL: [https://www.freereg.org.uk/freereg1_csv_files/5463c5bae937904abb64b642?locale=en](https://www.freereg.org.uk/freereg1_csv_files/5463c5bae937904abb64b642?locale=en)
Reported Issue:
The layout of the new "List of unique names" needs to be re-thought. For files with many unique names we need to scroll through the list - this is not the problem. The problem is that there is so much information that it is not easy to see things like "SMITH ALIAS JONES" or "SMITH OR JONES". It is also more difficult to see punctuation marks in names. I suggest one line per unique name. This will involve a lot more scrolling but, I believe, will increase the benefit of this useful addition.    

![Screenshot](https://www.freereg.org.uk)

E0 U3 S4 C6: P 13

**Comment by richpomfret** [comment]
List by letter?

**Comment by richpomfret** [comment]
@PatReynolds to discuss this with @AlOneill in relation to accessibility.

**Comment by AlOneill** [comment]
Splitting into paragraphs by first letter would help, as would constraining the line width. (Lines are too wide now and paragraphs too long.)

Putting one name per line would introduce other readability issues.

**Comment by Captainkirkdawson** [comment]
New version with split by alphabet deployed to test3
