### ISSUE TITLE
164455183 ANS Dundee batch not correctly linked (Eric D)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1285]
Issue reported by **REGManager** at 2020-03-18 09:59:43 UTC
Time: 2020-03-18T09:57:34+00:00
Session ID: e913d093e78423aabe2b374036f69122
Problem Page URL: [/registers/54080653eca9eb024879af4a?locale=en](/registers/54080653eca9eb024879af4a?locale=en)
Previous Page URL: [https://www.freereg.org.uk/registers/54080653eca9eb024879af4a?locale=en](https://www.freereg.org.uk/registers/54080653eca9eb024879af4a?locale=en)
Reported Issue:
The attached report has come up.
https://www.freereg.org.uk/uploads/feedback/screenshot/5e71f10ff493fd79542cb5b7/Capture.JPG    

![Screenshot](https://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Duplicate
