### ISSUE TITLE
164456201 ANS Files not correctly linked (Eric D)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1286]
Issue reported by **REGManager** at 2020-03-18 10:16:41 UTC
Time: 2020-03-18T10:15:51+00:00
Session ID: e913d093e78423aabe2b374036f69122
Problem Page URL: [/registers/540817ffeca9eb0248a77c55?locale=en](/registers/540817ffeca9eb0248a77c55?locale=en)
Previous Page URL: [https://www.freereg.org.uk/registers/540817ffeca9eb0248a77c55?locale=en](https://www.freereg.org.uk/registers/540817ffeca9eb0248a77c55?locale=en)
Reported Issue:
All the attached are not linked.
https://www.freereg.org.uk/uploads/feedback/screenshot/5e71f509f493fd79542ce615/Capture.JPG    

![Screenshot](https://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Issue is that the places have Angus as the County name and the chapman code name is Angus (Forfarshire) so validation fails. Looking at a solution

**Comment by Captainkirkdawson** [comment]
Fixed
