### ISSUE TITLE
164816115 BUTKILBA.CSV not linked (Eric D)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1287]
Issue reported by **REGManager** at 2020-03-22 14:15:15 UTC
Time: 2020-03-22T14:13:21+00:00
Session ID: 7ca54c271f196d762d61508aea1a6f4c
Problem Page URL: [/registers/5409f87feca9eb7182992fc0?locale=en](/registers/5409f87feca9eb7182992fc0?locale=en)
Previous Page URL: [https://www.freereg.org.uk/registers/5409f87feca9eb7182992fc0?locale=en](https://www.freereg.org.uk/registers/5409f87feca9eb7182992fc0?locale=en)
Reported Issue:
See attached report

https://www.freereg.org.uk/uploads/feedback/screenshot/5e7772f3f493fd57f597e2b5/Capture.JPG    

![Screenshot](https://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
The Chapman Code has Bute as the County name; the places have Buteshire which is correct?

**Comment by edickens** [comment]
I think we have to go for Bute as that is what is everywhere on the server.

**Comment by Captainkirkdawson** [comment]
Done
