### ISSUE TITLE
165072965 Seqence of list of Available counties (Eric D)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1289]
Part of same work as #1288
Issue reported by **REGManager** at 2020-03-25 13:36:05 UTC
Time: 2020-03-25T13:33:23+00:00
Session ID: 0ff072ed0dfbdeff87e8015ced0a4061
Problem Page URL: [/assignments/select_county?locale=en](/assignments/select_county?locale=en)
Previous Page URL: [https://www.freereg.org.uk/assignments/5462b414e937907d7000035c/list_assignments_of_myself?locale=en](https://www.freereg.org.uk/assignments/5462b414e937907d7000035c/list_assignments_of_myself?locale=en)

E0 U1 S8 C5: P14
Reported Issue:
If someone is looking to transcribe for LAN they may miss it because it is not in its alphabetic place in the list but on the end.  See attached.
https://www.freereg.org.uk/uploads/feedback/screenshot/5e7b5e45f493fd5437c3a47a/Capture.JPG    

![Screenshot](https://www.freereg.org.uk)

Overall priority 
E3 U 3 S8 C5: P19

**Comment by PatReynolds** [comment]
Now in correct place:
![image.png](https://images.zenhubusercontent.com/5b695a5dac3a200155c765e3/f9156c42-40f5-47d5-aa30-a250ffe27beb)

**Comment by PatReynolds** [comment]
Still a problem with list of Counties with images available.

@Vino-S to put a sort on this list.

**Comment by DeniseColbert** [comment]
County list now sorted alphabetically on Test 3. @edickens could you test and if this solves the issue we can close

**Comment by edickens** [comment]
Yes, correct now.  Please make live.  I will keep an eye on it because the problem occured when new counties were added.  I'm not sure what happens when counties are removed because they have no more available images.

**Comment by edickens** [comment]
Sequence looks good in Test3, but DEV is not there to check.  In the live version it is at the bottom...![Capture.JPG](https://images.zenhubusercontent.com/5cb4c5e2cccdd751e9e85870/f9605352-77a0-45af-9c86-2492ce22f20c)
So make this live and then I can see if it works.

**Comment by edickens** [comment]
Also, DEV Coordinator has reported that when a new place has new images which are Unallocated, they do not appear in this list.
Clayhanger should be in the  DEV list which only shows Stoke Gabriel.

**Comment by edickens** [comment]
Ignore my last comment.  New Places are added.

**Comment by DeniseColbert** [comment]
Done, closing
