### ISSUE TITLE
cosmetic (deo123)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#129]
Issue reported by **deo123** at 2014-12-31 12:58:49 UTC
Time: 2014-12-31T12:53:07+00:00
Session ID: e946ea3666061453803acd2bc598fddb
Problem Page URL: [/search_queries/54a3f1b3e937905374000020](/search_queries/54a3f1b3e937905374000020)
Previous Page URL: [http://test2.freereg.org.uk/search_queries/new?search_id=54a3f16be93790537400001e](http://test2.freereg.org.uk/search_queries/new?search_id=54a3f16be93790537400001e)
Reported Issue:
"results Found!"  just above the "report problem"

not clear like the rest of highlight functions.

Regards Doreen    

![Screenshot](http://test2.freereg.org.uk/tmp/carrierwave/1420030729-28834-8533/02.._cosmetic.JPG)

**Comment by Captainkirkdawson** [comment]
Comment included
