### ISSUE TITLE
165250269 Sort sequence of Batches offline report (Eric D)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1291]
Issue reported by **REGManager** at 2020-03-27 14:51:09 UTC
Time: 2020-03-27T14:46:01+00:00
Session ID: 47d43f5e4bc6ed12f4b6d2988c9e3aae
Problem Page URL: [/manage_counties/selection?option=Offline%20Reports](/manage_counties/selection?option=Offline%20Reports)
Previous Page URL: [https://www.freereg.org.uk/manage_counties/select_action?county=Lincolnshire&locale=en](https://www.freereg.org.uk/manage_counties/select_action?county=Lincolnshire&locale=en)
Reported Issue:
I have been comparing images with this report and it would help a lot to find any missing years if the report was sorted into Batch filename within Register Type, within Church, within Place.  It is the lowest level that does not seem to be working, see attached.
Also, if it is possible to put a blank line between each place and church, that would help, especially where place names are similar.
Thanks Eric D
https://www.freereg.org.uk/uploads/feedback/screenshot/5e7e12ddf493fd8237e29bb5/Capture.JPG    

![Screenshot](https://www.freereg.org.uk)

**Comment by richpomfret** [comment]
@edickens to see if this sort is possible via the spreadsheet.

**Comment by edickens** [comment]
Yes, the sort does work, but the header disappears down the table.  I could select all except the first row, but with some files being more than 4,000 rows this is tedious.  Also, it doesn't solve the problem with different Church Codes being used in the batch filename for the same Church.  I might try adding an extra column and extract the BA, BU and MA and sort on that instead.  The frustrating thing is that the Batches are shown in the most useful order when the contents of a Register Type are displayed.  But I can't get that open at the same time as the Image Server.
I don't know how many CCs use this report and will do the sort.
But don't spend time on this.  There are more important things to do.  I will close it.

**Comment by Captainkirkdawson** [comment]
@edickens 
Tell the sort you have a header row.
use the custom sort
![custom sort](https://user-images.githubusercontent.com/2874694/78168442-2e652980-740d-11ea-8de9-eef3d84e364d.JPG)
Tell it you have a header row
![custom sort](https://user-images.githubusercontent.com/2874694/78168497-45a41700-740d-11ea-9c3f-e542d7bc49b0.JPG)
You can add sort rows to sort by various columns

**Comment by edickens** [comment]
My Excel doesn't look anything like that, fortunately.  I have Office 2002 which does not use all those graphics.  My sort option only allows three sort keys, but you can sort twice and it keeps the order of the lowest level which you have to do first.  The sequence I would prefer is the sequence used when the batches of a Register are displayed.  That does Batch Type and Start Date, not Batch name.
I can get around  this because I am only going to do each County once, but I am not sure what a CC would like who may use it on a regular basis.

**Comment by Captainkirkdawson** [comment]
Mine is 2007 also obsolete
