### ISSUE TITLE
165332824 Latest additions (steve Newby)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1292]
Issue reported by **steve Newby** at 2020-03-28 13:47:04 UTC
Time: 2020-03-28T13:40:52+00:00
Session ID: 3b47c04e12c6371abbb6faa0d5b2e0f8
Problem Page URL: []()
Previous Page URL: [https://www.freereg.org.uk/contacts/new](https://www.freereg.org.uk/contacts/new)
Reported Issue:
I have up to now found your site extremely useful but that has been made practically impossible by the way the transcriptions page can no longer be searched by County to see what updates have been made and when in parishes across the board.Now one has to search parishes one by one which is a complete waste of time to see whether anything has been done recently which would make it worth while to search a parish.Is there some reason for this as before you could put a search in on multiple parishes to see whether any recent transcriptions had been added.    

E1 U3 S8 C6:P18

**Comment by SteveBiggs** [comment]
Would it be feasible to display a County summary table listing all places in the format of the individual place tables?:
![image](https://user-images.githubusercontent.com/25303607/77847623-7fc7ab80-71b6-11ea-8f42-2030d5ff6980.png)

**Comment by Captainkirkdawson** [comment]
Possibly or maybe a display of places by most recent upload date.

**Comment by Captainkirkdawson** [comment]
Have responded to story with code running on test3.
Added action link to first display of a county that goes to a Latest Additions page.
![latest additions.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/0bbb09fc-3a90-461b-9fc8-d86f544a1510)


This is the page displayed.
![latest additions 1.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/77368452-65f6-4787-9c1c-26259116d363)


When reviewing remember test3 is rarely updated by people.

**Comment by SteveBiggs** [comment]
Looks good to me.
