### ISSUE TITLE
165657192 If a Batch is all Birth dates, then start year is default (Eric D)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1293]
Issue reported by **REGManager** at 2020-04-01 07:53:12 UTC
Time: 2020-04-01T07:49:28+00:00
Session ID: 2bea2431ad5d99b52844b223b33eb43c
Problem Page URL: [/freereg1_csv_files/5463bf64e937902782544a00/zero_year?locale=en](/freereg1_csv_files/5463bf64e937902782544a00/zero_year?locale=en)
Previous Page URL: [https://www.freereg.org.uk/freereg1_csv_files/5463bf64e937902782544a00?locale=en](https://www.freereg.org.uk/freereg1_csv_files/5463bf64e937902782544a00?locale=en)
Reported Issue:
If a batch has no BA dates the start year is now 2020 and it comes last in the list.
For example
LINSPABA5 (LCD) in Unspecified of St Mary and St Nicholas in Spalding of 
All entries also appear in the Zero years report    

![Screenshot](https://www.freereg.org.uk)

E0 U3 S8 C

**Comment by edickens** [comment]
Reprocessing sorts out the problem.  Thanks Kirk.  Perhaps an FAQ for Coordinators?
This can be closed.
