### ISSUE TITLE
166544597 Initalise Groups  of Images does not include those which have never been initialised (Eric D)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1294]
Issue reported by **REGManager** at 2020-04-11 14:23:17 UTC
Time: 2020-04-11T14:11:06+00:00
Session ID: 2ee35b97d8cd4bdc2030eaa3015892dc
Problem Page URL: [/image_server_groups/5a9ec119f493fdbfcb9649fc/index?locale=en](/image_server_groups/5a9ec119f493fdbfcb9649fc/index?locale=en)
Previous Page URL: [https://www.freereg.org.uk/image_server_groups/5a9ec12af493fdbfcb965019/initialize_status?locale=en&type=allocate+accept](https://www.freereg.org.uk/image_server_groups/5a9ec12af493fdbfcb965019/initialize_status?locale=en&type=allocate+accept)
Reported Issue:
I'm going through all counties to Initialise all Image Groups.  But it is taking a long time.  If the bulk Initialise Image Groups action, which is on the Group Listing Screen, worked I could do it in seconds.  But it only includes those groups which have been initialised  once.  Obviously intended to be used for bulk allocation, but it omits all groups which have never been initialised.  See attached.
Also, after initialising a group, the screen returns ot the top of  the page and I have to scroll down again, rather than returning to where I was, as the list of Sources does. I have spent more than an hour on this Church when it could have been seconds.  And I have many more counties to do as I want to make sure that every Image Group is marked as either Unallocated or Transcribed.  We then know what we need to transcribe.  I am also checking years for gaps using Kirk's new report.  I did ask CCs to do this, but understand that they have more important things to do.
I think about two more months of work to go.
I know that this part of the code is not easy to amend.

https://www.freereg.org.uk/uploads/feedback/screenshot/5e91d2d5f493fd2b4cda5bea/Capture.JPG    

![Screenshot](https://www.freereg.org.uk)

**Comment by richpomfret** [comment]
This can now be closed.
