### ISSUE TITLE
167148906 Calculation of Year ranges of BA and BU batches (Eric D)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1299]
Issue reported by **REGManager** at 2020-04-18 14:15:06 UTC
Time: 2020-04-18T14:07:30+00:00
Session ID: 03c6ee69c78f0df32846e03aa5321de9
Problem Page URL: [/image_server_groups/5a9ecf04f493fdbfcb9bacbe/index?locale=en](/image_server_groups/5a9ecf04f493fdbfcb9bacbe/index?locale=en)
Previous Page URL: [https://www.freereg.org.uk/sources/5a9ecf04f493fdbfcb9bacbe?image_group_filter=&locale=en](https://www.freereg.org.uk/sources/5a9ecf04f493fdbfcb9bacbe?image_group_filter=&locale=en)
Reported Issue:
A minor thing, but it makes checking for missing transcriptions more difficult.
The year range is calculated using the lowest and highest value of Baptism and Birth years in BA, and Burial and Death years in BU.  But these can be way out from the years covered in the Batch.  For example someone being Baptised in their 50s, this would give a start year for the Batch 50 years too early and the birth year would be used for the lowest.
So can the calculation of Batch years be the Baptism year, or the Birth year but  only if there is is not Baptism date.  Similarly with Burials, but that is usually not so different.    

![Screenshot](https://www.freereg.org.uk)

**Comment by richpomfret** [comment]
Disregard.
