### ISSUE TITLE
search for parents (deo123)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#130]
Issue reported by **deo123** at 2014-12-31 13:05:19 UTC
Time: 2014-12-31T12:59:20+00:00
Session ID: e946ea3666061453803acd2bc598fddb
Problem Page URL: [/search_queries/54a3f328e937905374000024](/search_queries/54a3f328e937905374000024)
Previous Page URL: [http://test2.freereg.org.uk/search_queries/new?search_id=54a3f1b3e937905374000020](http://test2.freereg.org.uk/search_queries/new?search_id=54a3f1b3e937905374000020)
Reported Issue:
1..  Like the "viewed" in the detail column, very useful.

2...It would be nice to search for anumebr children for a given set of parents.

3.. when doing a revised search all the previous results stay, but not the type (Bap/Bur/Mar). In my searching on other sites this usually stays. It is a variation of name thats gets changed.

![Screenshot](http://test2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Comments included in analysis
