### ISSUE TITLE
168185322 not correctly linked (Doreen)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1305]
Issue reported by **deo123** at 2020-04-30 14:08:42 UTC
Time: 2020-04-30T14:07:05+00:00
Session ID: 2f16a46ef8b3ee44cb3e06b4bbabfd40
Problem Page URL: [/contacts/5ea06fb1f493fd8191509c78?locale=en&source=index](/contacts/5ea06fb1f493fd8191509c78?locale=en&source=index)
Previous Page URL: [https://www.freereg.org.uk/contacts](https://www.freereg.org.uk/contacts)
Reported Issue:
I cannot do this query, I pressed "Show Record" but it is saying not correctly linked?    

![Screenshot](https://www.freereg.org.uk)

**Comment by SteveBiggs** [comment]
I tried (Record in Question) and received the same response.

**Comment by Captainkirkdawson** [comment]
Problem is that the county was filled as Orkney Isles rather than just Orkney. Fixed

All places in that county fixed

**Comment by SteveBiggs** [comment]
Tested and looks good.
