### ISSUE TITLE
168268285 What does the U and A mean in the list of SC UserIDs? (Eric D)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1306]
Issue reported by **REGManager** at 2020-05-01 13:11:25 UTC
Time: 2020-05-01T13:08:46+00:00
Session ID: d7c1b129bca6b2815c9c819cc29a3d08
Problem Page URL: [/userid_details?locale=en](/userid_details?locale=en)
Previous Page URL: [https://www.freereg.org.uk/manage_syndicates/select_action.%3Fsyndicate=Staffordshire%20-%20Michael%20Clarke?locale=en](https://www.freereg.org.uk/manage_syndicates/select_action.%3Fsyndicate=Staffordshire%20-%20Michael%20Clarke?locale=en)
Reported Issue:
See the attached.  The two people look the same but have a different code.
Perhaps an i bubble will help as I have been asked this question a few times.
https://www.freereg.org.uk/uploads/feedback/screenshot/5eac1ffdf493fd204966e644/Capture.JPG    

![Screenshot](https://www.freereg.org.uk)

**Comment by edickens** [comment]
I think that these are indications to show if they have agreed to the Transcriber Agreement.  A = Agreed, U = Unknown..  This is not the title of the column.

**Comment by Captainkirkdawson** [comment]
Fixed on test3

**Comment by SteveBiggs** [comment]
Looks good.
