### ISSUE TITLE
168269977 register type unspecified (Julie )

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1307]
Issue reported by **JulieHarold** at 2020-05-01 13:39:37 UTC
Time: 2020-05-01T13:36:57+00:00
Session ID: c22c82b72a690ccfe1699554443e778c
Problem Page URL: [/freereg1_csv_entries/5463973fe937904abb72eedd?locale=en](/freereg1_csv_entries/5463973fe937904abb72eedd?locale=en)
Previous Page URL: [https://www.freereg.org.uk/contacts/5e9e7e8af493fd451a02f016?locale=en&source=list_by_date](https://www.freereg.org.uk/contacts/5e9e7e8af493fd451a02f016?locale=en&source=list_by_date)
Reported Issue:
When I look at individual entries for Norfolk file they are all showing 
Register type (Links to more information)	Unspecified

Looking at register information the right type is listed - eg Parish Register

Julie Harold (Norfolk Coordinator)    

![Screenshot](https://www.freereg.org.uk)

**Comment by SteveBiggs** [comment]
An example is Acle:
![image](https://user-images.githubusercontent.com/25303607/80831094-15a18c80-8be2-11ea-9385-359ddd5630e2.png)

**Comment by Captainkirkdawson** [comment]
Same issue and same resolution as #1256

**Comment by richpomfret** [comment]
Duplicate - closing.
