### ISSUE TITLE
168358078 Reprocess batch is sending emails to inactive UserIDs (Eric D)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1308]
Issue reported by **REGManager** at 2020-05-02 14:07:58 UTC
Time: 2020-05-02T14:03:04+00:00
Session ID: 877fcf0fc9eefc11892bbdca72ad2988
Problem Page URL: [/freereg1_csv_files/5463a1d8e937904abbaebefa?locale=en](/freereg1_csv_files/5463a1d8e937904abbaebefa?locale=en)
Previous Page URL: [https://www.freereg.org.uk/registers/572f0a52f493fd6f400002de?locale=en](https://www.freereg.org.uk/registers/572f0a52f493fd6f400002de?locale=en)
Reported Issue:
I'm getting feedback that inactive transcribers are getting"Batch processed" emails when I reprocess a batch to correct the year range calculation.
I suggest that the email should only go to the person who is logged in and doing the reprocessing.  I never got any emails, not even a copy, so I did not know this was happening.  Or perhaps an email is not needed.    

![Screenshot](https://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Sorry I do not understand. emails from the processing system will be distributed as per the normal rules. 
A reprocess is nothing more than the submission of  a file for processing. The processing system does not know anything about how the file got into the queue or who was responsible.
Emails will go to the user if active and to their coordinator.

**Comment by edickens** [comment]
I responded to this from Anna NTH:-

**A strange one: Not sure who to ask about this.**

**A lot of my old inactive transcribers have this week received messages that their files have been uploaded/not been able to be uploaded, and have been emailing me asking what is going on.**

I had been reprocessing old batches with 2020 start years, which worked fine.  But I don't have a specific example to hand.

Suggest close until it is reported again.

**Comment by Captainkirkdawson** [comment]
Were they set as inactive???????????

**Comment by edickens** [comment]
I was told Yes.  But I think I had better do a test with Test3.

**Comment by edickens** [comment]
Have done a test in Test3 and emails are NOT sent to the transcriber when reprocessing and they are set as Active = False.
So seems to be OK.
Close this and wait for another report with more details, although I will try to find the email I got a while ago on this subject.
