### ISSUE TITLE
168435117 file is not linked (Doreen)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1309]
Issue reported by **deo123** at 2020-05-03 11:31:57 UTC
Time: 2020-05-03T11:26:43+00:00
Session ID: 21e3d29312c6495d9d6c1c911e98976b
Problem Page URL: [/registers/54081dd1eca9eb0248b5b88f?locale=en](/registers/54081dd1eca9eb0248b5b88f?locale=en)
Previous Page URL: [https://www.freereg.org.uk/registers/54081dd1eca9eb0248b5b88f?locale=en](https://www.freereg.org.uk/registers/54081dd1eca9eb0248b5b88f?locale=en)
Reported Issue:
Hi,

I have tried to view a file 1817-1839 paulsy32 (OKIHARBA1.CSV), see attachment.
I have also tried to view a record in my contacts with the same results.

Regards Doreen
https://www.freereg.org.uk/uploads/feedback/screenshot/5eaeabadf493fd385444fce3/1817-1839_paulsy32_OKIHARBA1_.JPG    

![Screenshot](https://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
This is the same issue as 168185322 not correctly linked (Doreen) #1305
It has been resolved.
Problem originates with REG1 when OKI was defined as Orkney Isles. In REG2 it is Orkney. Hence the mismatch.
Has been resolved
