### ISSUE TITLE
detail column "viewed" (deo123)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#131]
Issue reported by **deo123** at 2014-12-31 13:44:36 UTC
Time: 2014-12-31T13:40:51+00:00
Session ID: e946ea3666061453803acd2bc598fddb
Problem Page URL: [/search_queries/54a3fba5e937905c11000001?page=3](/search_queries/54a3fba5e937905c11000001?page=3)
Previous Page URL: [http://test2.freereg.org.uk/search_queries/54a3fba5e937905c11000001?page=2](http://test2.freereg.org.uk/search_queries/54a3fba5e937905c11000001?page=2)
Reported Issue:
it is intentional to omit the "viewed" in the detail column?

I am sure all the normal questions views on the page layout has been said.

Regards Doreen    

![Screenshot](http://test2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
No it is not being removed
