### ISSUE TITLE
168729345 Data Problem (Angela Lynch)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1311]
Issue reported by **Angela Lynch** at 2020-05-06 21:15:45 UTC
Time: 2020-05-06T21:15:21+00:00
Session ID: 218578fa594a6b826dbd1da7a2ee1022
Problem Page URL: [https://www.freereg.org.uk/search_records/5e1b6653f493fd2da27a8754/walter-dennis-ryder-burial-staffordshire-leek-1959-05-28?locale=en](https://www.freereg.org.uk/search_records/5e1b6653f493fd2da27a8754/walter-dennis-ryder-burial-staffordshire-leek-1959-05-28?locale=en)
Previous Page URL: [https://www.freereg.org.uk/contacts/5e1b6653f493fd2da27a8754/report_error?locale=en&query=5eb326a3791e3be335f1c424](https://www.freereg.org.uk/contacts/5e1b6653f493fd2da27a8754/report_error?locale=en&query=5eb326a3791e3be335f1c424)
Reported Issue:
Burial date	28 May 1959
Death date	22 May 2012

**Comment by Captainkirkdawson** [comment]
Why is this here?

**Comment by SteveBiggs** [comment]
I can only assume that the new STS coord clicked 'Convert to issue' in the Contact. I will ask not to do that in future.
