### ISSUE TITLE
168967063 Other transcript folder (Julie)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1312]
Issue reported by **JHarold** at 2020-05-09 15:17:43 UTC
Time: 2020-05-09T15:16:05+00:00
Session ID: fa2f02478d8c1c7ab7e2b113a99b355b
Problem Page URL: [/churches/564b3a3bf493fd01c6000852?locale=en](/churches/564b3a3bf493fd01c6000852?locale=en)
Previous Page URL: [https://www.freereg.org.uk/registers/5ea92c39f493fd84199ab2fd?locale=en](https://www.freereg.org.uk/registers/5ea92c39f493fd84199ab2fd?locale=en)
Reported Issue:
I have two other transcript folders - one is empty.  If I destroy it, it says it is done.
If I merge it with the other one, it says it is done.

And yet when I check - there is always the second empty folder - please make it go away !!!

thanks, 
Julie Harold, Essex coordinator    

![Screenshot](https://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Your wish is my command
Gone

**Comment by SteveBiggs** [comment]
Looks good.
