### ISSUE TITLE
168966070 error message when saving an edit (Julie)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1313]
Issue reported by **JHarold** at 2020-05-09 15:01:10 UTC
Time: 2020-05-09T14:59:01+00:00
Session ID: fa2f02478d8c1c7ab7e2b113a99b355b
Problem Page URL: [/freereg1_csv_entries/5eb6c4f9f493fd549be8963f/error?locale=en&referrer=https%3A%2F%2Fwww.freereg.org.uk%2Ffreereg1_csv_files%2F5e527f81f493fd4550d2bfc9%3Flocale%3Den](/freereg1_csv_entries/5eb6c4f9f493fd549be8963f/error?locale=en&referrer=https%3A%2F%2Fwww.freereg.org.uk%2Ffreereg1_csv_files%2F5e527f81f493fd4550d2bfc9%3Flocale%3Den)
Previous Page URL: [https://www.freereg.org.uk/freereg1_csv_files/5e527f81f493fd4550d2bfc9/error?locale=en](https://www.freereg.org.uk/freereg1_csv_files/5e527f81f493fd4550d2bfc9/error?locale=en)
Reported Issue:
I am getting this error often when I save an edited entry (over the last week or so).
When I check the entry appears to have been edited successfully.
Julie Harold Essex Coordinator
https://www.freereg.org.uk/uploads/feedback/screenshot/5eb6c5b6f493fd65fbc4ffed/Capture.JPG    

![Screenshot](https://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
https://errbit.freeukgen.org.uk/apps/56297e8be93790333a000009/problems/5e91af77e937901dbf245c65

**Comment by Captainkirkdawson** [comment]
Believe to have been fixed on test3
