### ISSUE TITLE
168936453 Flexible CSV Marriages Download is missing groom_father_title (Michael)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1314]
Issue reported by **BKMCoord** at 2020-05-09 06:47:33 UTC
Time: 2020-05-09T06:38:16+00:00
Session ID: 26704b5f198a957239e3cddf31e1850e
Problem Page URL: [/cms/information-for-transcribers/flexible-csv-format/extended-marriage-fields](/cms/information-for-transcribers/flexible-csv-format/extended-marriage-fields)
Previous Page URL: [https://www.freereg.org.uk/cms/information-for-transcribers/flexible-csv-format](https://www.freereg.org.uk/cms/information-for-transcribers/flexible-csv-format)
Reported Issue:
Although the field groom_father_title is described, it is not in the downloadable file.    

![Screenshot](https://www.freereg.org.uk)

**Comment by SteveBiggs** [comment]
This is the template file downloadable in the Help.

**Comment by Captainkirkdawson** [comment]
Revised version needs checking on test3

**Comment by SteveBiggs** [comment]
Looks good.
