### ISSUE TITLE
169026411 File incorrectly linked (Eric D)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1315]
Issue reported by **REGManager** at 2020-05-10 07:46:51 UTC
Time: 2020-05-10T07:43:49+00:00
Session ID: f8c90328e909e11b379365c854d545ab
Problem Page URL: [/registers/54093426eca9eb5fd8259365?locale=en](/registers/54093426eca9eb5fd8259365?locale=en)
Previous Page URL: [https://www.freereg.org.uk/registers/54093426eca9eb5fd8259365?locale=en](https://www.freereg.org.uk/registers/54093426eca9eb5fd8259365?locale=en)
Reported Issue:
See attached.  Needs reprocessing as well.
https://www.freereg.org.uk/uploads/feedback/screenshot/5eb7b16bf493fd827e8b0f86/Capture.JPG    

![Screenshot](https://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
The same problem as with the Orkney Isles. Shetland has had 2 county names one with and one without the Isles depending on when they were created. This one had the Isle  which we no longer use.
Corrected.
Know nothing about reporocessing

**Comment by edickens** [comment]
TY.  I will do the reprocessing.
