### ISSUE TITLE
169118514 The picture tells it all (Michael)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1316]
Issue reported by **BKMCoord** at 2020-05-11 09:21:54 UTC
Time: 2020-05-11T09:17:14+00:00
Session ID: 26704b5f198a957239e3cddf31e1850e
Problem Page URL: [/freereg1_csv_files?locale=en](/freereg1_csv_files?locale=en)
Previous Page URL: [https://www.freereg.org.uk/csvfiles/new](https://www.freereg.org.uk/csvfiles/new)
Reported Issue:
The attached picture tells it all. This also happened with STS.
https://www.freereg.org.uk/uploads/feedback/screenshot/5eb91932f493fd460fd98835/Capture.JPG    

![Screenshot](https://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Fixed on test3

**Comment by SteveBiggs** [comment]
Checked and looks good.
