### ISSUE TITLE
169232283 Could not view Record in Question (Stephen)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1317]
Issue reported by **steveroland** at 2020-05-12 16:58:03 UTC
Time: 2020-05-12T16:56:13+00:00
Session ID: 84d46fee0300b721b1130a1f47ee14a8
Problem Page URL: [/contacts/5ebaa3f8f493fd6e8348b531?locale=en&source=index](/contacts/5ebaa3f8f493fd6e8348b531?locale=en&source=index)
Previous Page URL: [https://www.freereg.org.uk/contacts](https://www.freereg.org.uk/contacts)
Reported Issue:
When clicked it gives the red "Something went wrong .." message    

![Screenshot](https://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
@SteveBiggs Is this still an issue as the message has been archived

**Comment by SteveBiggs** [comment]
The message (169232283) hasn't been archived, but I just tried it again and did not get the red error message but did get a message that the entry is not correctly linked which is probably because I have edited the date on it.
