### ISSUE TITLE
169371665 Destroy Register Type say Successful but does not destroy (Eric D)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1318]
Issue reported by **REGManager** at 2020-05-14 07:41:05 UTC
Time: 2020-05-14T07:36:27+00:00
Session ID: 5ece491ae5c94cb476c3a741b71ac066
Problem Page URL: [/registers/5a9ebb5bf493fdbfcb92a194?locale=en](/registers/5a9ebb5bf493fdbfcb92a194?locale=en)
Previous Page URL: [https://www.freereg.org.uk/manage_counties/place_range?params=A-D](https://www.freereg.org.uk/manage_counties/place_range?params=A-D)
Reported Issue:
For exampe, CUL Cockermouth , Independent Chapel, PR.
I suspect that the images are attached  to the PR with no data, so cannot be Destroyed, but the report says that Destroy was successful.
Also, in this PR, there are dates for data but no data?    

![Screenshot](https://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Deletion failing because of an image server source. Bug was that message not being given
Fixed on test3
