### ISSUE TITLE
169468897 LND not linked (Eric D)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1319]
Issue reported by **REGManager** at 2020-05-15 10:41:37 UTC
Time: 2020-05-15T10:40:14+00:00
Session ID: 443b82735775d32d78aaf1d7588846e8
Problem Page URL: [/registers/564c96a0f493fd798b000003?locale=en](/registers/564c96a0f493fd798b000003?locale=en)
Previous Page URL: [https://www.freereg.org.uk/registers/564c96a0f493fd798b000003?locale=en](https://www.freereg.org.uk/registers/564c96a0f493fd798b000003?locale=en)
Reported Issue:
Kirk,
Another batch of not linked.  Seems like all of them.  See attached.
Thanks
Eric
https://www.freereg.org.uk/uploads/feedback/screenshot/5ebe71e1f493fddae2cf01fd/Capture.JPG    

![Screenshot](https://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Fixed on test3

**Comment by PatReynolds** [comment]
@Captainkirkdawson can this now be closed - please close if so.
