### ISSUE TITLE
general look of search pages (deo123)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#132]
Issue reported by **deo123** at 2015-01-01 12:56:47 UTC
Time: 2015-01-01T12:35:23+00:00
Session ID: f216360d933b9dcfa5452d99614ae54a
Problem Page URL: [/search_queries/54a53e63e937905a0c000047?page_number=0](/search_queries/54a53e63e937905a0c000047?page_number=0)
Previous Page URL: [http://test2.freereg.org.uk/search_records/546b4319e93790cdedd603ed?search_id=54a53e63e937905a0c000047](http://test2.freereg.org.uk/search_records/546b4319e93790cdedd603ed?search_id=54a53e63e937905a0c000047)
Reported Issue:
I find there is too much scrolling going on, before you get to the results. The boxes for results are too big. Also if you have a family tree you want to view at the same time, you cannot as F2 is stuck in the middle.

The writing is too light, I am not sure this is for people with bad eye sight. But a good percentage of users would want to have the results highlighted, like F1 result page.
This site was fine just want a few tweeks.
If you are wanting to attract users to use the site and hopefully donate, then you need to accomandate the majority not the minority.

The type, if choosing more than one type then would it not be best to sort into types, instead of all mixed up.

I would like to see the front search page ready for use, not having to scroll down to it.

I notice "viewed" appeared on some searches but not all, it would be nice to have consistancy across the board.

You specify there must be a surname, but what happens if only a christian name is in the register, how will these be shown? This is often the case in early registers which we are encourage to transcribe. I have just done a register from 1549 and there are a lot of 
part names.
It would be nice to see a list of these entries for a given Parish.

Overall the look is like looking at a childrens book, not an adult book. It really needs
a re-think of the general look, otherwise what will the pblic think of us.

Regards Doreen

![Screenshot](http://test2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Included in analysis
