### ISSUE TITLE
169739635 Files not correctly linked - OKI (Eric D)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1321]
Issue reported by **REGManager** at 2020-05-18 13:53:55 UTC
Time: 2020-05-18T13:52:34+00:00
Session ID: d380568953504248624c260ba5ce4c7e
Problem Page URL: [/registers/5501f868e93790decc07351c?locale=en](/registers/5501f868e93790decc07351c?locale=en)
Previous Page URL: [https://www.freereg.org.uk/registers/5501f868e93790decc07351c?locale=en](https://www.freereg.org.uk/registers/5501f868e93790decc07351c?locale=en)
Reported Issue:
See attached.
E
https://www.freereg.org.uk/uploads/feedback/screenshot/5ec29373f493fd84b185d8ef/Capture.JPG    

![Screenshot](https://www.freereg.org.uk)

**Comment by richpomfret** [comment]
Check if these have been fixed or not.

**Comment by edickens** [comment]
File not fixed.  Have sent in error report.
It is only LDN and OKI which are affected, as far as I know.  I will tell the CC.
This can be closed as Kirk says that all he can do is fix them when they are reported.

**Comment by edickens** [comment]
Here follows the ones that I have found so far.  These are all files with suspect year transcriptions.

Thanks Eric

**Comment by edickens** [comment]
hank you for your feedback at 04:35 on 2020-05-28. Please quote the following number 170570209 in any subsequent communication with us on this matter.
![image.png](https://images.zenhubusercontent.com/5cb4c5e2cccdd751e9e85870/0f9474c9-c54f-4240-8c45-b4ef55c54394)

**Comment by edickens** [comment]
Thank you for your feedback at 04:26 on 2020-05-28. Please quote the following number 170569702 in any subsequent communication with us on this matter.
![image.png](https://images.zenhubusercontent.com/5cb4c5e2cccdd751e9e85870/8f262cc0-e56a-4158-b7fd-55dd221b7ed2)

**Comment by edickens** [comment]
Thank you for your feedback at 04:23 on 2020-05-28. Please quote the following number 170569538 in any subsequent communication with us on this matter.
![image.png](https://images.zenhubusercontent.com/5cb4c5e2cccdd751e9e85870/e238dce9-3138-4068-af8c-0ed01fd96468)

**Comment by edickens** [comment]
Thank you for your feedback at 04:21 on 2020-05-28. Please quote the following number 170569369 in any subsequent communication with us on this matter.
![image.png](https://images.zenhubusercontent.com/5cb4c5e2cccdd751e9e85870/074440f0-c760-4d2c-8c1d-6a5b2395d4ce)

**Comment by edickens** [comment]
Thank you for your feedback at 04:18 on 2020-05-28. Please quote the following number 170569240 in any subsequent communication with us on this matter.
![image.png](https://images.zenhubusercontent.com/5cb4c5e2cccdd751e9e85870/a45f8a87-bd81-49a2-8619-fa3619bbf988)

**Comment by edickens** [comment]
Thank you for your feedback at 04:14 on 2020-05-28. Please quote the following number 170569103 in any subsequent communication with us on this matter.
![image.png](https://images.zenhubusercontent.com/5cb4c5e2cccdd751e9e85870/a68ec723-ff8f-4f05-b070-657a58d139b5)

**Comment by edickens** [comment]
Thank you for your feedback at 04:10 on 2020-05-28. Please quote the following number 170568817 in any subsequent communication with us on this matter.
![image.png](https://images.zenhubusercontent.com/5cb4c5e2cccdd751e9e85870/45c5a702-7235-49cc-98b8-53299316d12b)

**Comment by edickens** [comment]
Thank you for your feedback at 04:07 on 2020-05-28. Please quote the following number 170568572 in any subsequent communication with us on this matter.
![image.png](https://images.zenhubusercontent.com/5cb4c5e2cccdd751e9e85870/03c072aa-c78b-4f7c-bace-38ff3247b8b9)

**Comment by edickens** [comment]
Thank you for your feedback at 04:02 on 2020-05-28. Please quote the following number 170568385 in any subsequent communication with us on this matter.
![image.png](https://images.zenhubusercontent.com/5cb4c5e2cccdd751e9e85870/eed80944-ed0a-44ea-886f-0871c6394f82)

**Comment by edickens** [comment]
Thank you for your feedback at 03:57 on 2020-05-28. Please quote the following number 170568121 in any subsequent communication with us on this matter.
![image.png](https://images.zenhubusercontent.com/5cb4c5e2cccdd751e9e85870/a061b4fe-ac2f-4071-83bb-4a1106b2bf48)

**Comment by edickens** [comment]
Thank you for your feedback at 03:57 on 2020-05-28. Please quote the following number 170568121 in any subsequent communication with us on this matter.
![image.png](https://images.zenhubusercontent.com/5cb4c5e2cccdd751e9e85870/c6146488-d640-4c58-a6bd-2d158ace6cb9)

**Comment by edickens** [comment]
Thank you for your feedback at 03:54 on 2020-05-28. Please quote the following number 170567761 in any subsequent communication with us on this matter.
![image.png](https://images.zenhubusercontent.com/5cb4c5e2cccdd751e9e85870/da892ca7-0948-4b0e-a7f2-95f04e1a4996)

**Comment by edickens** [comment]
Thank you for your feedback at 03:52 on 2020-05-28. Please quote the following number 170567611 in any subsequent communication with us on this matter.
![image.png](https://images.zenhubusercontent.com/5cb4c5e2cccdd751e9e85870/c0b1b106-b796-4aba-8cf3-a52eafd8406e)

**Comment by edickens** [comment]
Thank you for your feedback at 03:50 on 2020-05-28. Please quote the following number 170567505 in any subsequent communication with us on this matter.
![image.png](https://images.zenhubusercontent.com/5cb4c5e2cccdd751e9e85870/a2bc5ff6-68bb-4fa2-9bcf-6c5a40670bef)

**Comment by edickens** [comment]
Thank you for your feedback at 03:46 on 2020-05-28. Please quote the following number 170567369 in any subsequent communication with us on this matter.
![image.png](https://images.zenhubusercontent.com/5cb4c5e2cccdd751e9e85870/34842b2d-09d1-4e55-b844-de565f82f720)

And that is it for now.

**Comment by richpomfret** [comment]
@edickens to check this again and see if still open..

**Comment by edickens** [comment]
I've not checked them all but those that I have done are fine.  This can be closed.
Kirk - In future, if you add a note to say that you have done them then I will check and close the story.
