### ISSUE TITLE
170637074 coordinator cannot download batch file (Dale)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1324]
Issue reported by **STSCC** at 2020-05-28 23:11:14 UTC
Time: 2020-05-28T23:04:53+00:00
Session ID: 18ee2647bd0ed45c2724bb62057c1a4f
Problem Page URL: [/freereg1_csv_files?locale=en](/freereg1_csv_files?locale=en)
Previous Page URL: [https://www.freereg.org.uk/freereg1_csv_files?locale=en](https://www.freereg.org.uk/freereg1_csv_files?locale=en)
Reported Issue:
A transcriber uploaded a file that was rejected due to errors.  I am the county coordinator and I want to download the file.  So I click on the button that says "Review Batches with Errors" and I see the file with the usual options like SH, ED, DL, and so forth.  I click on DL and am given this error:

"We cannot download the file: file has error records that would be lost for STSALSBA.CSV . Contact your coordinator if you need advise. "

In the first place, the system should not allow any information to be deleted simply because someone wants to download a file.  Secondly, coordinators should not be disallowed from downloading a file that has been uploaded into their territory.
https://www.freereg.org.uk/uploads/feedback/screenshot/5ed04512f493fd8ff99636ea/Screenshot_2020-05-28_FreeREG_UK_Parish_Register_Records.png    

![Screenshot](https://www.freereg.org.uk)

**Comment by edickens** [comment]
The problem is, and Kirk can correct me if I am wrong, that when you download a batch it has to be assembled from the entries.  If there is an error in the entry, then it cannot be assembled for inclusion in the download.  The best solution is to correct the error online then you can download it.

**Comment by richpomfret** [comment]
File with errors must be edited online or original file must be uploaded again with errors fixed.

**Comment by richpomfret** [comment]
@SteveBiggs to communicate this.

**Comment by richpomfret** [comment]
To then close.

**Comment by SteveBiggs** [comment]
Reply sent.
