### ISSUE TITLE
170671329 UCF dates in MI (Ali)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1325]
Issue reported by **alsibk** at 2020-05-29 08:42:09 UTC
Time: 2020-05-29T08:36:09+00:00
Session ID: 7a7412f63733cc6ceabeba26d65dd23a
Problem Page URL: [/freereg1_csv_files/5ec28fd4f493fd468afd5b4f/zero_year?locale=en](/freereg1_csv_files/5ec28fd4f493fd468afd5b4f/zero_year?locale=en)
Previous Page URL: [https://www.freereg.org.uk/freereg1_csv_files?locale=en](https://www.freereg.org.uk/freereg1_csv_files?locale=en)
Reported Issue:
In MI transcriptions there are many many instances where no date is given, and, due to the manner of entry for MIs, no opportunity to estimate the possible date.
These fields are therefore left blank.
Should there be UCF to indicate that these dates are in fact missing in the original?    

![Screenshot](https://www.freereg.org.uk)

**Comment by edickens** [comment]
I would have thought that just leaving an important field blank is not good practice.  So, with the present coding, an Asterisk needs to be entered to indicate unreadable = unavailable date.  UCF search will find this,
We have plans for a Record Type of MI where the fields and also validation will be different.  Some other counties are not transcribing their MI images even if they have them but keeping them on the image server until we have the MI record type.  Instead, if they have no work, they are doing more modern entries and putting them under Embargo if they are not for release just yet.

**Comment by suffolkroots** [comment]
Single asterisk in date column returned as error. 3 asterisks in date column returned as error. Only blank date found.

**Comment by Sherlock21** [comment]
Seems to me that we need ALL the rules defining for MI transcriptions, THEN start transcribing the images - and not the reverse was round else you will eld up with a lot os records that down work again.

**Comment by suffolkroots** [comment]
I was instructed to have MIs transcribed in flexi format, at no time has it been suggested that they should not yet be done.

**Comment by SteveBiggs** [comment]
I am not aware of any plan to implement a MI record type. It's certainly not in the Roadmap.

Flexible csv includes fields to record memorial information, burial location, etc. and AFAIK should be used for MI's.

We do, however, need to decide how we should deal with a burial where there is no way of even estimating the year.

**Comment by richpomfret** [comment]
Discussed the answer being a single asterisk - which is now accepted.

**Comment by richpomfret** [comment]
@SteveBiggs to try this out.

**Comment by SteveBiggs** [comment]
Checked out OK and reply sent to Ali.
