### ISSUE TITLE
170959366 File processing problem (Mick)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1327]
Issue reported by **Mick** at 2020-06-01 16:42:46 UTC
Time: 2020-06-01T16:40:33+00:00
Session ID: 69b6f2ea932114c5f79b9207d1f01a81
Problem Page URL: [/freereg1_csv_files?locale=en](/freereg1_csv_files?locale=en)
Previous Page URL: [https://www.freereg.org.uk/manage_syndicates/select_action?locale=en](https://www.freereg.org.uk/manage_syndicates/select_action?locale=en)
Reported Issue:
I'm trying to upload a batch and get an error notification that all the dates are invalid. Have rechecked the file and the dates are all ok    

![Screenshot](https://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
duplicate
