### ISSUE TITLE
170957259 Error reports in auto emails (John)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1328]
Issue reported by **JHT** at 2020-06-01 16:07:39 UTC
Time: 2020-06-01T15:57:30+00:00
Session ID: 6a7e059d981c622bd1c3654719831dd8
Problem Page URL: [/cms/information-for-coordinators](/cms/information-for-coordinators)
Previous Page URL: [https://www.freereg.org.uk/freereg1_csv_entries?locale=en](https://www.freereg.org.uk/freereg1_csv_entries?locale=en)
Reported Issue:
Files uploaded this afternoon DBYASHBA2 by witchy989 and DBYHOPBA2 by JHT have both been reported as having a large number of errors with baptism dates. I have examined both files and can see nothing wrong with dates. I tried online editing one of the error entries in DBYHOPBA2 as it is my file but it didn't work.

John Turton (JHT)
Coordinator Derbyshire    

![Screenshot](https://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
duplicate
