### ISSUE TITLE
Decadal display dies on a count error (Captainkirk)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#133]
Issue reported by **Captainkirk** at 2015-01-02 01:27:26 UTC
Time: 2015-01-02T01:22:28+00:00
Session ID: d1b75ef0da17dc613a9a9a3d6625d3e0
Problem Page URL: [/freereg_contents/540a01beeca9eba206bb94a9/show_register](/freereg_contents/540a01beeca9eba206bb94a9/show_register)
Previous Page URL: [http://test2.freereg.org.uk/freereg_contents/540a01beeca9eba206bb94a7/show_church](http://test2.freereg.org.uk/freereg_contents/540a01beeca9eba206bb94a7/show_church)
Reported Issue:

![Screenshot](http://test2.freereg.org.uk/tmp/carrierwave/1420162046-68489-5357/Capture.JPG)

**Comment by Captainkirkdawson** [comment]
Fixed
