### ISSUE TITLE
171039890 List Batches only shows the first page (Stephen)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1331]
Issue reported by **steveroland** at 2020-06-02 15:04:50 UTC
Time: 2020-06-02T15:00:43+00:00
Session ID: b569b25af0303f27f5d25282e4e57372
Problem Page URL: [/freereg1_csv_files?locale=en](/freereg1_csv_files?locale=en)
Previous Page URL: [https://www.freereg.org.uk/manage_counties/select_action?county=Sussex&locale=en](https://www.freereg.org.uk/manage_counties/select_action?county=Sussex&locale=en)
Reported Issue:
It would appear that every action to List Batches under Manage County or Manage Syndicate no longer give the page selections at the top so you can only see the first page of batches.
https://www.freereg.org.uk/uploads/feedback/screenshot/5ed66a92f493fd2e86a1b6e0/Capture.jpg    

![Screenshot](https://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
@SteveBiggs there have been no code changes to the image server in at least 2 years

**Comment by SteveBiggs** [comment]
@Captainkirkdawson this is not the image server. It's the listing of batches.

**Comment by Captainkirkdawson** [comment]
I do not understand the list of batches is not paginated. It is a complete listing with the side scroll bar/

None of those listing are paginated

**Comment by SteveBiggs** [comment]
Nor do I. Maybe the lists are just truncated now. Listing SSX batches alphabetically the list starts at Albourne (SSWINBA is a misnamed batch):
![image](https://user-images.githubusercontent.com/25303607/83553649-679c4180-a503-11ea-9e3a-a46f526ddc03.png)
and ends at Billingshurst:
![image](https://user-images.githubusercontent.com/25303607/83553704-7f73c580-a503-11ea-8f47-8d0afa2d5954.png)

The places with batches go through the alphabet to Yapton.

I thought they used to be paginated, but ....

**Comment by Captainkirkdawson** [comment]
Its been this way for months. Code changed.
Deployed to test3 @SteveBiggs please review

**Comment by SteveBiggs** [comment]
As you can gather, I rarely use this method to view batches - I go via the Active Places to the place I'm interested in. I was testing it based on a problem report. Test3 view batches looks OK now. Thank you.
