### ISSUE TITLE
171034666 Since when has UCF "_" been invalid for a date? (Michael)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1332]
Issue reported by **LINCC** at 2020-06-02 13:37:46 UTC
Time: 2020-06-02T13:34:59+00:00
Session ID: 66f6e2ede4815f05b8d139a72e58813a
Problem Page URL: [/freereg1_csv_entries/5ed64582f493fd7006359dd0/error?locale=en&referrer=https%3A%2F%2Fwww.freereg.org.uk%2Ffreereg1_csv_files%2F5ed515a2f493fdf9edb6f79e%3Flocale%3Den](/freereg1_csv_entries/5ed64582f493fd7006359dd0/error?locale=en&referrer=https%3A%2F%2Fwww.freereg.org.uk%2Ffreereg1_csv_files%2F5ed515a2f493fdf9edb6f79e%3Flocale%3Den)
Previous Page URL: [https://www.freereg.org.uk/freereg1_csv_files/5ed515a2f493fdf9edb6f79e/error?locale=en](https://www.freereg.org.uk/freereg1_csv_files/5ed515a2f493fdf9edb6f79e/error?locale=en)
Reported Issue:
I have been using "_" in dates for a fair time but they seem to have suddenly become an error. See attachment.
https://www.freereg.org.uk/uploads/feedback/screenshot/5ed6562af493fd2e86a0e15e/Capture.JPG    

![Screenshot](https://www.freereg.org.uk)

**Comment by SteveBiggs** [comment]
Appears Ok now.
