### ISSUE TITLE
171058800 Invalid date using * (Michael)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1333]
Issue reported by **LINCC** at 2020-06-02 20:20:00 UTC
Time: 2020-06-02T20:17:09+00:00
Session ID: 66f6e2ede4815f05b8d139a72e58813a
Problem Page URL: [/freereg1_csv_entries/5ed67865f493fd4b8d252ced/error?locale=en&referrer=https%3A%2F%2Fwww.freereg.org.uk%2Ffreereg1_csv_files%2F5ed67830f493fd4b8d252c45%3Flocale%3Den](/freereg1_csv_entries/5ed67865f493fd4b8d252ced/error?locale=en&referrer=https%3A%2F%2Fwww.freereg.org.uk%2Ffreereg1_csv_files%2F5ed67830f493fd4b8d252c45%3Flocale%3Den)
Previous Page URL: [https://www.freereg.org.uk/freereg1_csv_files/5ed67830f493fd4b8d252c45/error?locale=en](https://www.freereg.org.uk/freereg1_csv_files/5ed67830f493fd4b8d252c45/error?locale=en)
Reported Issue:
SInce when has a date containing a * been invalid?

Something with regards to date validation changed some time over 1-2 Jun 2020
https://www.freereg.org.uk/uploads/feedback/screenshot/5ed6b470f493fd8f949c9e1e/Capture.JPG    

![Screenshot](https://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Fix applied to test3

**Comment by SteveBiggs** [comment]
I've made a few tests and it appears OK now.
