### ISSUE TITLE
171098527 UCF Dates rejected (Mike)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1334]
Issue reported by **mgf** at 2020-06-03 07:22:07 UTC
Time: 2020-06-03T07:02:50+00:00
Session ID: 9ac6657d5151bd00fbdc9949ed4da711
Problem Page URL: [/freereg1_csv_files/my_own](/freereg1_csv_files/my_own)
Previous Page URL: [https://www.freereg.org.uk/manage_resources/new?locale=en](https://www.freereg.org.uk/manage_resources/new?locale=en)
Reported Issue:
Baptism transcription file uploaded with UCF dates in birth and baptism date columns such as:
    * * 1836?
    * * 1859
(which the help files say are valid ways to enter missing dates or dates with year only) had some accepted and some rejected.

My userid: mgf (mgf@froddles.me.uk)
Filename: KENCWLBA8

The upload errors were:
Updating the current batch for KEN, Charlton (Greenwich), St Luke, Parish Register.
Data Error in line 542 problem was {:birth_date=>["Invalid date"]}.
Data Error in line 967 problem was {:baptism_date=>["Invalid date"]}.
Data Error in line 968 problem was {:baptism_date=>["Invalid date"]}.
Data Error in line 969 problem was {:baptism_date=>["Invalid date"]}.

Which relate to these records:
KEN,Charlton (Greenwich),St Luke PR,542,* * 1840?,27 Jun 1858,Mary Ann,,Ellis,Ann,HOBDAY,,Shooters Hill Road,Currier,Birth year estimated by transcriber - a note in the Child's Christian Name column reads: aged 17 years,,0040
KEN,Charlton (Greenwich),St Luke PR,966,,* * 1861,,,,,,,,,Entire entry crosssed through at bottom of page to start new year on new page.,,0067
KEN,Charlton (Greenwich),St Luke PR,967,,* * 1861,,,,,,,,,Entire entry crosssed through at bottom of page to start new year on new page.,,0067
KEN,Charlton (Greenwich),St Luke PR,968,,* * 1861,,,,,,,,,Entire entry crosssed through at bottom of page to start new year on new page.,,0067

However, this file also contains entries such as the following which were not rejected:
KEN,Charlton (Greenwich),St Luke PR,676,* * 1848?,11 Sep 1859,Francis Martin,,Thomas,Mary Ann,SCUDDS,,"Blackheath Park, Charlton",Coachman,Birth year estimated by transcriber - a note under Child's Christian Name reads: aged 11 yrs.,,0048
KEN,Charlton (Greenwich),St Luke PR,677,* * 1849?,11 Sep 1859,Mary Jane,,Thomas,Mary Ann,SCUDDS,,Blackheath Park Charlton,Coachman,Birth year estimated by transcriber - a note under Child's Christian Name reads: aged 10 yrs.,,0048
KEN,Charlton (Greenwich),St Luke PR,704,,* * 1859,,,,,,,,,Entire entry crosssed through at bottom of page - presumably to start new year on new page.,,0050

Hope this helps!
    

![Screenshot](https://www.freereg.org.uk)

**Comment by SteveBiggs** [comment]
Appears OK now
