### ISSUE TITLE
171115997 Date validation (Edwin)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1335]
Issue reported by **14247** at 2020-06-03 12:13:17 UTC
Time: 2020-06-03T12:10:15+00:00
Session ID: 94b19d2e73d348cf28aa26c9ad47b01d
Problem Page URL: [/](/)
Previous Page URL: []()
Reported Issue:
I have just uploaded 3 databases, all apparently have date errors, but I can't see any problem.
Edwin,
The file submitted for processing has been completed. Please review the following report.
Started on the file ESSCPEBA1.CSV for 14247 at 2020-06-03 12:18:54 +0100. 
Creating a new batch for ESS, Colchester, St Peter, Parish Register. 
Data Error in line 22 problem was {:birth_date=>["Invalid date"]}.
Data Error in line 33 problem was {:birth_date=>["Invalid date"]}.
Data Error in line 74 problem was {:baptism_date=>["Invalid date"]}.
Data Error in line 145 problem was {:baptism_date=>["Invalid date"]}.
173 records were processed of which 173 were updated/added and 4 had data errors. 
Created 173 entries at an average time of 433ms per record at 2020-06-03 12:20:09 +0100. 

Edwin,
The file submitted for processing has been completed. Please review the following report.
Started on the file ESSCPEBU1.CSV for 14247 at 2020-06-03 12:25:09 +0100. 
Creating a new batch for ESS, Colchester, St Peter, Parish Register. 
Data Error in line 51 problem was {:burial_date=>["Invalid date"]}.
Data Error in line 66 problem was {:burial_date=>["Invalid date"]}.
105 records were processed of which 105 were updated/added and 2 had data errors. 
Created 105 entries at an average time of 447ms per record at 2020-06-03 12:25:56 +0100. 

Edwin,
The file submitted for processing has been completed. Please review the following report.
Started on the file ESSCPEMA1.CSV for 14247 at 2020-06-03 12:30:57 +0100. 
Creating a new batch for ESS, Colchester, St Peter, Parish Register. 
Data Error in line 14 problem was {:marriage_date=>["Invalid date"]}.
Data Error in line 15 problem was {:marriage_date=>["Invalid date"]}.
Data Error in line 18 problem was {:marriage_date=>["Invalid date"]}.
45 records were processed of which 45 were updated/added and 3 had data errors. 
Created 45 entries at an average time of 622ms per record at 2020-06-03 12:31:25 +0100. 
    

![Screenshot](https://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
This is a duplicate of previously reported issues that are believed to be resolved on test3 but waiting for feedback. @SteveBiggs please do not convert any new date issue until the code on test3 is checked. I cannot deploy until I have third party testing. I informed both users but no response
