### ISSUE TITLE
171217403 Cannot download a file (Michael)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1336]
Issue reported by **LINCC** at 2020-06-04 16:23:23 UTC
Time: 2020-06-04T15:31:19+00:00
Session ID: b8a902f3b80cac8121e84fbdda65fe93
Problem Page URL: [/freereg1_csv_files/5463e30fe937902782f79e04?locale=en](/freereg1_csv_files/5463e30fe937902782f79e04?locale=en)
Previous Page URL: [https://www.freereg.org.uk/registers/5409ec5ceca9eba206749329?locale=en](https://www.freereg.org.uk/registers/5409ec5ceca9eba206749329?locale=en)
Reported Issue:
I am trying to download a file from FreeREG to my pc. I have begun to receive the message displayed in the attachment.

I am running WIndows 10 and Firefox browser.

Chrome browser gives a different message but the result is the same - no download.
https://www.freereg.org.uk/uploads/feedback/screenshot/5ed91ffbf493fd0ab7e2f00a/Capture.JPG    

![Screenshot](https://www.freereg.org.uk)

**Comment by richpomfret** [comment]
Let's see if this happens again. Closing in the meantime (we think this may be due to a security certificate issue after server issues).
