### ISSUE TITLE
171385719 Incorrect display after file upload (Michael)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1337]
Issue reported by **LINCC** at 2020-06-06 15:08:39 UTC
Time: 2020-06-06T15:01:48+00:00
Session ID: b8a902f3b80cac8121e84fbdda65fe93
Problem Page URL: [/freereg1_csv_files?locale=en](/freereg1_csv_files?locale=en)
Previous Page URL: [https://www.freereg.org.uk/csvfiles/new](https://www.freereg.org.uk/csvfiles/new)
Reported Issue:
I have been uploading files for the last week as various userids. Therefore, most recent dates in the displayed list should be in 2020 but they appear to be much older at 2015.

Either the heading is wrong or the contents of the table is wrong. See attached
https://www.freereg.org.uk/uploads/feedback/screenshot/5edbb177f493fda58bc59629/Capture.JPG    

![Screenshot](https://www.freereg.org.uk)

**Comment by SteveBiggs** [comment]
From Michael:

I have just turned Lincolnshire syndicate recruiting ON. Now, when I submit a file, the system comes up with NO files in this page. Could the fault be that I had submitted the file for someone who was not in my syndicate and that my syndicate was not recruiting?

**Comment by edickens** [comment]
Lincolnshire only has these UserIDs
![Capture.JPG](https://images.zenhubusercontent.com/5cb4c5e2cccdd751e9e85870/f8e0e4fe-beb5-4e54-a1e7-2f1f21ef9e7a)
The other transcribers are in Lincolnshire - Mick Claxton
None of the Lincolnshire UserIDs has any batches.

**Comment by richpomfret** [comment]
@SteveBiggs to look at providing new specification for this.

**Comment by edickens** [comment]
Going back to Michael's original question.  If you look at his Screenshot the files should be listed by Most Recent, but they are not.  The Breadcrumb doesn't give the path to get to the screenshot, which I think is looking at the "Specific Place" of LIN, Addlethorpe.  But I do not have an Action to List files for a Place.
![Capture1.JPG](https://images.zenhubusercontent.com/5cb4c5e2cccdd751e9e85870/271e04c6-e403-45ae-a2c4-aa18dda0950e)

**Comment by SteveBiggs** [comment]
My suggestion is that after the file is uploaded, you are returned to the upload page here:
![image](https://user-images.githubusercontent.com/25303607/84391639-2a197180-abf1-11ea-91b9-eaa75b9ec0ca.png)

**Comment by Captainkirkdawson** [comment]
Title was appropriate; but sort was not set. Correction deployed to test3. Only affects coordinator uploads/replace  for users

**Comment by Captainkirkdawson** [comment]
Do not like @SteveBiggs s suggestion. This would lead to people redoing the action

**Comment by SteveBiggs** [comment]
I tried uploading a file as CC on behalf of a transcriber on test3 and it returned the error page "Something went wrong ....".

**Comment by Captainkirkdawson** [comment]
Please retry. Was the same problem as the other crash

**Comment by SteveBiggs** [comment]
Yes, works as expected now.
