### ISSUE TITLE
171641273 query  when record has been processed (Doreen)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1338]
Issue reported by **deo123** at 2020-06-09 14:07:53 UTC
Time: 2020-06-09T13:59:46+00:00
Session ID: 8471a26fa8405d44b6f91c65cf0136de
Problem Page URL: [/freereg1_csv_files/5edeb090f493fd400f36740a?locale=en](/freereg1_csv_files/5edeb090f493fd400f36740a?locale=en)
Previous Page URL: [https://www.freereg.org.uk/freereg1_csv_entries/5edf95cbf493fdf4d1412540?locale=en](https://www.freereg.org.uk/freereg1_csv_entries/5edf95cbf493fdf4d1412540?locale=en)
Reported Issue:
Hi,

sorry to both you, but can someone explain why we suddenly have extra data on header records please.

1.. "first set of comment about a batch",  why all the extra data that is appearing of late mainly dates?

2.. Why is the "processed date" always set to "01 Jan 1998"  this is appearing on all batches of late?

Regards Doreen Olds
https://www.freereg.org.uk/uploads/feedback/screenshot/5edf97b9f493fdf4d1413fa5/query_01.JPG    

![Screenshot](https://www.freereg.org.uk)

**Comment by SteveBiggs** [comment]
![image.png](https://images.zenhubusercontent.com/5cb596063b6bd6333fc1dc24/064fcaf7-1ed4-4f1a-8b02-c279ed0fe02b)

**Comment by richpomfret** [comment]
Rather than put nothing, we put in '1st Jan 1998'. That is added if no other date is provided.

**Comment by richpomfret** [comment]
@edickens to track down the file for this in order to check if there is a date in the header or not..

**Comment by edickens** [comment]
The file is:-
GLSDURBU.CSV (Chewitt26) in Parish Register of St James in Dursley of Gloucestershire

I  tried to download the Physical File but, although the server said "Downloaded", it didn't reach me.  I will now get the original from Doreen or perhaps FR1.

**Comment by edickens** [comment]
Doreen has created a file and uploaded it.  The server is changing the date now.  It is not old files.  This could be for every file uploaded.
She create a file using WinREG so the format of the header is correct.  This is it:-
![after WinREG before FreeREG.JPG](https://images.zenhubusercontent.com/5cb4c5e2cccdd751e9e85870/90b5064f-849e-4aef-af1f-2ec341833d82)
After uploading it becomes:-
![abberley test after uploaded to FReeREG  (deo123)WORABBBA99.JPG](https://images.zenhubusercontent.com/5cb4c5e2cccdd751e9e85870/d9d3170f-64c2-4e5a-96ae-696b850ac101)
There is a problem here.

**Comment by SteveBiggs** [comment]
Looking at SSX files by date, the problem appears to have started between 1st and 5th June.

**Comment by edickens** [comment]
Doreen has also reported that the upload date is being added to the front of the first comments field and not the date field.

![extra data.JPG](https://images.zenhubusercontent.com/5cb4c5e2cccdd751e9e85870/740cd4d0-1f5c-4528-a448-b5cf4f985b2a)

See also in the snips above.

**Comment by Captainkirkdawson** [comment]
There are 2 issues being commented on here.
Firstly the date of transcription is being incorrectly processed as an unintended consequence of the changes made to correctly validate the search date field that was introduced at the beginning of this month. The transcription date failed the check for a valid date failed so the default date was used.
Secondly the appearance of the date in the comment field was also an unintended consequence of the changes made to correctly validate the search date field that was introduced at the beginning of this month. In the latter case since the date validation on the comment failed it was treated as a comment.
A fix has been applied to test3.

**Comment by SteveBiggs** [comment]
Attempted to test on test3 but the button 'Review Batches by Most Recent Date of change' returns error "Something went wrong ......"

**Comment by SteveBiggs** [comment]
Uploaded a file and the details look correct now.

**Comment by Captainkirkdawson** [comment]
Please retry that use of 'Review Batches by Most Recent Date of change'

**Comment by SteveBiggs** [comment]
Review Batches actions work as expected now.
