### ISSUE TITLE
Case sensitive filename extension should be added to the Help

### ISSUE THREAD

**Issue by SteveBiggs** [FreeUKGen/FreeUKRegProductIssues#1339]
The filename including the extension is case sensitive meaning for example that a single user could have two files named SSXFERBA.CSV and SSXFERBA.csv that are different. This can cause confusion in the future if just the filename part is looked at since it might appear to be a duplicate.

An explanation of case sensitivity should be added to the transcriber help here:
https://www.freereg.org.uk/cms/information-for-transcribers/creating-a-transcription-file

![image](https://user-images.githubusercontent.com/25303607/84318791-e4b06200-ab66-11ea-9d3e-3a6df532b501.png)

E0 U6 S6 C6: P18

**Comment by richpomfret** [comment]
@PatReynolds to prioritise before moving it over.

**Comment by AlOneill** [comment]
Which version of the file extension, .csv or .CSV, do we ask transcribers to use? Or do we just want them to be aware of the issue?

**Comment by SteveBiggs** [comment]
Either version is supported so we just need them to be aware of the case sensitivity issue.

**Comment by AlOneill** [comment]
@SteveBiggs The draft, https://test3.freereg.org.uk/cms/information-for-transcribers/draft-creating-a-transcription-file
has the new text.

**Comment by SteveBiggs** [comment]
Looks good thanks @AlOneill

**Comment by AlOneill** [comment]
Draft file promoted and made sync-ready.
