### ISSUE TITLE
Print/Save Search result detail (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#134]
Issue reported by **REGManager** at 2015-01-02 11:36:45 UTC
Time: 2015-01-02T11:30:03+00:00
Session ID: 78b410dbdf72739128b83d91b70350c5
Problem Page URL: [/search_records/5465362de93790cfcf0ead37?search_id=54a68126e937904d8900000b](/search_records/5465362de93790cfcf0ead37?search_id=54a68126e937904d8900000b)
Previous Page URL: [http://test2.freereg.org.uk/search_queries/54a68126e937904d8900000b](http://test2.freereg.org.uk/search_queries/54a68126e937904d8900000b)
Reported Issue:
Icons/Buttons needed to Print or Save the search result detail.

This may have been requested before but is not there.

Since the result detail requires scrolling it is not possible to take a screen print and save that for the family record.  The web browser "Print" is also not useful.  So options to Print (a small printer icon) or Save (a small disc icon) would help to save a printer friendly version.  The Save should have the usual options of selecting/creating folders and choosing a filename.

EricD    

![Screenshot](http://test2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Comment included in analysis
