### ISSUE TITLE
172147997 MIs (Ali)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1342]
Issue reported by **alsibk** at 2020-06-15 10:53:17 UTC
Time: 2020-06-15T10:48:51+00:00
Session ID: 04b2c462de4ff4aa16dcecaf9d62184c
Problem Page URL: [/freereg1_csv_entries?locale=en](/freereg1_csv_entries?locale=en)
Previous Page URL: [https://www.freereg.org.uk/freereg1_csv_files/5ee740eff493fd51fcf950dd?locale=en](https://www.freereg.org.uk/freereg1_csv_files/5ee740eff493fd51fcf950dd?locale=en)
Reported Issue:
MIs are recorded on flexi file as death date column is available. There are usually no burial dates.

On checking file, SH/Browse entries, there is only burial date heading, so no dates shown.

On searching, retrieved info suggests that the date given is a burial date.    

![Screenshot](https://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Sorry but there is no issue as far as I can see.
The browse shows a limited set of fields
![ali1](https://user-images.githubusercontent.com/2874694/84708778-58af8900-af1e-11ea-85e9-5dd320e8a617.png)
If you look at the record detail it clearly shows as a death date
![ali2](https://user-images.githubusercontent.com/2874694/84708833-70870d00-af1e-11ea-82a8-5f84544e53ea.png)
Search for ABSON in Askern and you retrieve the record and if you look at the record detail it also clearly shows as a Death date
![ali3](https://user-images.githubusercontent.com/2874694/84709048-d2477700-af1e-11ea-9c83-add5cf35349b.png)
This is all we can do without creating a Record Type for MIs

**Comment by Captainkirkdawson** [comment]
Propose it be closed at next scrum

**Comment by SteveBiggs** [comment]
This issue arose because the batch showed a strange end date so Ali went to the file/SH/Browse entries to find the suspect entry by scanning the dates for a strange one. However, as they are death dates, none are shown in the summary fields so she couldn't easily find it.

Now that we have added the death date to the burial record type, it would be useful to add it to the summary fields in the same way that the birth date is shown in the baptism summary fields.

**Comment by Captainkirkdawson** [comment]
Added death date and contract date in respective summary page; deployed to test3

**Comment by SteveBiggs** [comment]
Checked and looks good.
