### ISSUE TITLE
172843842 RED error message when deleting an entry (Eric D)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1345]
Issue reported by **REGManager** at 2020-06-23 12:10:42 UTC
Time: 2020-06-23T12:08:56+00:00
Session ID: 8b6efd7c73346858d44b013928400010
Problem Page URL: [/freereg1_csv_entries?locale=en](/freereg1_csv_entries?locale=en)
Previous Page URL: [https://www.freereg.org.uk/freereg1_csv_files/5eedbc04f493fd7d9b24c819?locale=en](https://www.freereg.org.uk/freereg1_csv_files/5eedbc04f493fd7d9b24c819?locale=en)
Reported Issue:
The attached is the last entry in the batch and is blank, so shows as zero years.  Using DE produces a RED error.
https://www.freereg.org.uk/uploads/feedback/screenshot/5ef1f142f493fde341445664/Capture.JPG    

![Screenshot](https://www.freereg.org.uk)

**Comment by richpomfret** [comment]
Needs further testing. @SteveBiggs has offered his services.

**Comment by richpomfret** [comment]
We can close if deemed not to be an issue after testing.
