### ISSUE TITLE
172787997 Downloading files to my pc (Michael)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1346]
Issue reported by **LINCC** at 2020-06-22 20:39:57 UTC
Time: 2020-06-22T20:33:11+00:00
Session ID: ab207e815ed677aa4d6dc9f5384006be
Problem Page URL: [/freereg1_csv_files/54639237e937904abb5690d2?locale=en](/freereg1_csv_files/54639237e937904abb5690d2?locale=en)
Previous Page URL: [https://www.freereg.org.uk/registers/54082a4ceca9eb81e2c6da81?locale=en](https://www.freereg.org.uk/registers/54082a4ceca9eb81e2c6da81?locale=en)
Reported Issue:
Note: the screen that I was working from is irrelevant to this problem.

It appears that the speed of downloading a file from FreeREG to my pc is proportional to the number of files in the userid. The more files in the userid, the longer it takes to download a file.

Userids with just a few files download almost instantaneously. For userid Mick, with around 3000 files, the file download takes about 30 seconds.

Why is this?    

![Screenshot](https://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Because a file can be composed of different batches it has to be "reintegrated" into a file to download. Therefore a search has to be undertaken of all batches to select those that need "integration". The more batches the longer it takes.

**Comment by SteveBiggs** [comment]
Thanks @Captainkirkdawson I'll pass that back to Michael.

**Comment by SteveBiggs** [comment]
Reply sent to Michael.
