### ISSUE TITLE
173183392 Data Problem (Jennifer Reeve)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1347]
Issue reported by **Jennifer Reeve** at 2020-06-27 10:29:52 UTC
Time: 2020-06-27T10:28:46+00:00
Session ID: c8330386fc71317aeaf60bdd49c76928
Problem Page URL: [https://www.freereg.org.uk/search_records/5c5edbf9f493fd66f4a8d2a8/ethel-may-baker-baptism-kent-dover-1885-09-13?locale=en](https://www.freereg.org.uk/search_records/5c5edbf9f493fd66f4a8d2a8/ethel-may-baker-baptism-kent-dover-1885-09-13?locale=en)
Previous Page URL: [https://www.freereg.org.uk/contacts/5c5edbf9f493fd66f4a8d2a8/report_error?locale=en&query=5ef71f3133045b1a7ab57e47](https://www.freereg.org.uk/contacts/5c5edbf9f493fd66f4a8d2a8/report_error?locale=en&query=5ef71f3133045b1a7ab57e47)
Reported Issue:
Fathers name is Henry Cannon Baker

**Comment by richpomfret** [comment]
@SteveBiggs to check this before closing.

**Comment by SteveBiggs** [comment]
This Contact has been replied to by Sandra and archived so it must have been converted to issue in error.
