### ISSUE TITLE
173631776 Change Register Type apparently not working (Barrie)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1348]
Issue reported by **brobinson43** at 2020-07-02 15:02:56 UTC
Time: 2020-07-02T14:56:30+00:00
Session ID: 9356fefdc113f60772fd2835427630a1
Problem Page URL: [/registers/5409f135eca9eba206851a59?locale=en&notice=There+are+too+many+records+for+an+on-line+relocation](/registers/5409f135eca9eba206851a59?locale=en&notice=There+are+too+many+records+for+an+on-line+relocation)
Previous Page URL: [https://www.freereg.org.uk/registers/5409f135eca9eba206851a59?locale=en](https://www.freereg.org.uk/registers/5409f135eca9eba206851a59?locale=en)
Reported Issue:
I used the button "Change Register Type" for the registers "Unspecified" at the two churches, St Laurence Foleshill and St Mary at Walsgrave on Sowe, as I now know what the type of these registers should be. After I clicked on the button, an alert box appeared asking if I really wanted to change the register type, to which I clicked Yes. After this, nothing happened, unless I was too impatient, and it had gone away to think about it. If so, could we please at least have some indication that something is happening?
IN the meantime, I think I will just create the new registers and move all the batches over. This will take time, but I know it works.    

![Screenshot](https://www.freereg.org.uk)

**Comment by SteveBiggs** [comment]
Change Register Type appears to work on test3 but does not on the production site.

**Comment by Captainkirkdawson** [comment]
Same software

**Comment by Captainkirkdawson** [comment]
In both cases the system determined there were too many records for an online processing (21,000 and 9000 respectively). In both cases the system returned to the register display with a blue message saying There were too many records for an online change
![rename2](https://user-images.githubusercontent.com/2874694/86420564-46f71100-bc94-11ea-84af-77a784ef972f.JPG)
![rename1](https://user-images.githubusercontent.com/2874694/86420565-478fa780-bc94-11ea-8e32-36275b799fb9.JPG)

**Comment by SteveBiggs** [comment]
Something appears to have changed because yesterday when I clicked Change Register Type -> OK on production nothing happened.

There is still a problem because when you click Change Register Type -> OK, it returns the page:
![image](https://user-images.githubusercontent.com/25303607/86442111-2c10b500-bd05-11ea-9dc8-a781b1113bce.png)

then click Rename and it returns saying it was successful:
![image](https://user-images.githubusercontent.com/25303607/86442255-6a0dd900-bd05-11ea-82ff-4dc6b2e037e6.png)

However, the type remains as Unspecified so it didn't actually work and wrongly reports that it did.

**Comment by Captainkirkdawson** [comment]
@SteveBiggs I am unsure of the point you are making.
The logs in my post clearly show that a message was returned to the user saying **there were too many records for an online update of the registertype.** They hare limited to 4000 records; DM can do 15000 and SA 100000 (It being assumed that SAs are more careful on timing!! and that it is really needed.
If I ever had time to deal with FreeUKGen/FreeUKRegProductIssues#1256 these limits and likely many similar issues would go away

Your test is different ; in your role you are permitted to process larger numbers of records.Hence your attempt would work.

The updated time in the register shows you did indeed update today
`mongos> db.registers.find({_id: ObjectId("54081289eca9eb0248992e74")})
{ "_id" : ObjectId("54081289eca9eb0248992e74"), "chapman_code" : "WAR", "register_type" : " ", "place_name" : "Foleshill", "church_name" : "St Laurence", "alternate_register_name" : "St Laurence  ", "last_amended" : "26 Apr 2011", "transcription_date" : "18-Sep-09", "record_types" : [ "bu" ], "church_id" : ObjectId("54081289eca9eb0248992e72"), **"u_at" : ISODate("2020-07-03T07:20:50.758Z"),** "c_at" : ISODate("2014-09-04T07:19:37.151Z"), "records" : "21647", "datemin" : "1706", "datemax" : "1913", `
The update shows that there was no attempt to actually change the type; ie a different type had not be selected
Processing by RegistersController#update as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"Oz8McX+Ah9rW8BKnGYSLfmvjrtsWw1ziuwqwoFVyU19YzmvHVx90nSyDE4ZNgAw4Sn6krGZf3Z0+2j76PH3gYg==", "register"=>{"register_type"=>" "}, "commit"=>"Rename", "locale"=>"en", "id"=>"54081289eca9eb0248992e74"}

So the update successfully updated the register with the same type Unspecified and that is what it show

**Comment by SteveBiggs** [comment]
I didn't know that the Sys Admin role could change the register type for larger numbers of records and fair point about not actually trying to change the type!

So, as SSX CC, I just went to All Saints, Chichester and clicked 'Change Register Type' then 'OK' on the pop-up box and the pop-up box went away but there was no message displayed about too many records. This is what Barrie experienced in the first place. I tried this in Chrome and Edge with the same result.

**Comment by SteveBiggs** [comment]
I've just noticed that the message is in the browser URL!:
![image](https://user-images.githubusercontent.com/25303607/86486421-23df6680-bd53-11ea-9ecf-cdb6b5f1e9a4.png)

**Comment by Captainkirkdawson** [comment]
Aha evidence I can now use

**Comment by Captainkirkdawson** [comment]
Message now displayed; there are been a change in rails specification.
Deployed to test3

**Comment by SteveBiggs** [comment]
Yes, looks good now.
