### ISSUE TITLE
173867365 Burial Subject fields (Anna)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1349]
Issue reported by **AMSA** at 2020-07-05 08:29:25 UTC
Time: 2020-07-05T08:28:16+00:00
Session ID: 74e8c5a5197b3c137565b9879950e0cd
Problem Page URL: [/messages/5effb48bf493fde59da873c1?locale=en&source=original](/messages/5effb48bf493fde59da873c1?locale=en&source=original)
Previous Page URL: [https://www.freereg.org.uk/messages/userid_messages?locale=en](https://www.freereg.org.uk/messages/userid_messages?locale=en)
Reported Issue:
Message forwarded by coordinator:

The subject fields do not include an Occupation column which, In my experience, is a fairly common attribute of a burial record.
Having to put a stated Occupation in the Notes column stands out to me as a glaring oversight that would be an easy fix going forward.

Can you advise on the reason for the omission and if it is a recognised on the todo list?

Regards, Frank.    

![Screenshot](https://www.freereg.org.uk)

**Comment by richpomfret** [comment]
This information currently goes into the notes. This is a more recent addition to burial records and therefore only impacts upon a relatively small number of results. We will reassess this in the future.

**Comment by richpomfret** [comment]
@SteveBiggs to communicate our response.

**Comment by SteveBiggs** [comment]
I have responded to Anna.
