### ISSUE TITLE
174210463 Destroy UserID fails (Eric D)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1350]
Issue reported by **REGManager** at 2020-07-09 07:47:43 UTC
Time: 2020-07-09T07:45:46+00:00
Session ID: 3ff14199571b5f534ee231888f25e331
Problem Page URL: [/userid_details/57a0d0bbf493fd76ae000a3e?locale=en](/userid_details/57a0d0bbf493fd76ae000a3e?locale=en)
Previous Page URL: [https://www.freereg.org.uk/userid_details?locale=en](https://www.freereg.org.uk/userid_details?locale=en)
Reported Issue:
I can't destroy this UserID.  E
https://www.freereg.org.uk/uploads/feedback/screenshot/5f06cb9ff493fde30bf5c455/Capture.JPG    

![Screenshot](https://www.freereg.org.uk)

**Comment by PatReynolds** [comment]
When this happends it is because there is a file or files in the attic. - or other dependency.

Adding a reason would be helpful.

**Comment by PatReynolds** [comment]
Decided due to limited number of people deleiting IDs, to take no action.
