### ISSUE TITLE
174315611 Issue with system reporting how many errors there are and number of entries (Ali)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1351]
Issue reported by **alsibk** at 2020-07-10 13:00:11 UTC
Time: 2020-07-10T12:54:45+00:00
Session ID: b3c1da634858ee49c8b60aa8f3723e3b
Problem Page URL: [/freereg1_csv_files?locale=en](/freereg1_csv_files?locale=en)
Previous Page URL: [https://www.freereg.org.uk/manage_counties/select_action?locale=en](https://www.freereg.org.uk/manage_counties/select_action?locale=en)
Reported Issue:
I can't download this file as it has errors and no entries, but it says 299 entries---what's that all about please?

https://www.freereg.org.uk/uploads/feedback/screenshot/5f08665bf493fdce9343ffc3/Capture.JPG    

![Screenshot](https://www.freereg.org.uk)

**Comment by SteveBiggs** [comment]
I explained that the system is designed to not allow files with errors to be downloaded, but I can't explain why it says it has no entries. The last numbered entry is 1285 and there are 983 errors which would suggest that 302 should be viewable rather than 299?

**Comment by PatReynolds** [comment]
Particular instance of issue has been resolved.

If problem appears again, will need to be investigated.
