### ISSUE TITLE
175074161 Destroy Syndicate (Eric D)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1354]
Issue reported by **REGManager** at 2020-07-19 07:42:41 UTC
Time: 2020-07-19T07:40:39+00:00
Session ID: 368450fc08bdc16231ca97946c2c33c6
Problem Page URL: [/manage_syndicates/select_action?locale=en](/manage_syndicates/select_action?locale=en)
Previous Page URL: [https://www.freereg.org.uk/manage_syndicates/new?locale=en](https://www.freereg.org.uk/manage_syndicates/new?locale=en)
Reported Issue:
Kirk,

Please destroy:-
Northern Ireland - Sandra Adams-West

There are no UserIDs.

Thanks,
Eric    

![Screenshot](https://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Why destroy? Why not rename?

**Comment by edickens** [comment]
I didn't think you could because of all the links to Allocated images and such.

**Comment by Captainkirkdawson** [comment]
If there are links then it cannot be destroyed

**Comment by edickens** [comment]
Have used Edit Name.  Seemed to work.
Can be closed.
TY
