### ISSUE TITLE
175334492 Query record number (Ali)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1356]
Issue reported by **alsibk** at 2020-07-22 08:01:32 UTC
Time: 2020-07-22T07:59:16+00:00
Session ID: dfbdd10c2c5ae77244c54a5883f6cf1b
Problem Page URL: [/feedbacks/new?utf8=%E2%9C%93&feedback_time=2020-07-22+07%3A58%3A22+UTC&session_id=dfbdd10c2c5ae77244c54a5883f6cf1b&user_id=alsibk&problem_page_url=%2Fregisters%2F5409cf1beca9ebd28e0fe0d6%3Flocale%3Den&previous_page_url=https%3A%2F%2Fwww.freereg.org.uk%2Fmanage_counties%2Fplace_range%3Fparams%3DS&feedback_type=issue](/feedbacks/new?utf8=%E2%9C%93&feedback_time=2020-07-22+07%3A58%3A22+UTC&session_id=dfbdd10c2c5ae77244c54a5883f6cf1b&user_id=alsibk&problem_page_url=%2Fregisters%2F5409cf1beca9ebd28e0fe0d6%3Flocale%3Den&previous_page_url=https%3A%2F%2Fwww.freereg.org.uk%2Fmanage_counties%2Fplace_range%3Fparams%3DS&feedback_type=issue)
Previous Page URL: [https://www.freereg.org.uk/registers/5409cf1beca9ebd28e0fe0d6?locale=en](https://www.freereg.org.uk/registers/5409cf1beca9ebd28e0fe0d6?locale=en)
Reported Issue:
WRYSANMA.csv Unspecified has 2753 records.

Try to change reg type I'm told too many to change----9000+    

![Screenshot](https://www.freereg.org.uk)

**Comment by SteveBiggs** [comment]
Unspecified register for St Helen in Sandal Magna of Yorkshire, West Riding

There is only a marriages file but the Register info reports burials exist as well.

**Comment by PatReynolds** [comment]
Overnight update may fix this - propogation only happens overnight. @SteveBiggs to talk to Ali.

**Comment by SteveBiggs** [comment]
All good now.

**Comment by richpomfret** [comment]
Closing as now appears fixed.
