### ISSUE TITLE
freereg_contents/new needs refresh on back

### ISSUE THREAD

**Issue by EmJayFry** [FreeUKGen/FreeUKRegProductIssues#136]
On first entry to this page, and after selecting a county, the place list fill up and a place can be selected. From there, things work well down to and including the display of the decade information. Upon returning up the chain, using the browser back button, re-entering this page causes the place list to be lost. It can only be refilled for the selected county by selecting another county and then selecting the original one.

**Comment by Captainkirkdawson** [comment]
Fixed; place list is retained
