### ISSUE TITLE
176507503 File disappears during Change Report Type (Michael)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1362]
Issue reported by **LINCC** at 2020-08-04 21:51:43 UTC
Time: 2020-08-04T21:33:41+00:00
Session ID: 65b353bdca571d09cd9a2bfcfa3cc4ed
Problem Page URL: [/registers/5c5202eaf493fdb8560986ea/rename?locale=en](/registers/5c5202eaf493fdb8560986ea/rename?locale=en)
Previous Page URL: [https://www.freereg.org.uk/registers/5c5202eaf493fdb8560986ea?locale=en](https://www.freereg.org.uk/registers/5c5202eaf493fdb8560986ea?locale=en)
Reported Issue:
Imagine two files with the following properties:

Unspecified/Mick/LIN/Leadenham/Blank/LEDMA1.csv
and
Parish Register/Mick/LIN/Leadenham/St Swithin/LEDMA1.csv

Now use Change Register Type for the "Unspecified" to "Parish Register". Note that a file of the same name already exists in "Parish Register".

A message is displayed along the lines of "something has gone wrong, ask your coordinator to contact the webmaster".

The "Unspecified" register type empties and it is possible, and I did it, to destroy the "Unspecified" register type and, subsequently, the church named "Blank".

The file from "Blank" has been lost. It is not in the attic and could not be found by E. Dickens.

Surely, the result of displaying the error message should have been to leave the file untouched.
    

![Screenshot](https://www.freereg.org.uk)

**Comment by richpomfret** [comment]
@Captainkirkdawson to send @edickens the file.

**Comment by Captainkirkdawson** [comment]
There is no such file  as LEDMA1.csv
Unspecified/Mick/LIN/Leadenham/Blank/
and
Parish Register/Mick/LIN/Leadenham/St Swithin/LEDMA1.csv

There is a file  LINLEDMA1.csv which was sent to ericd; its creation date is 2008

**Comment by richpomfret** [comment]
Closing this specific issue.
