### ISSUE TITLE
177092085 Contact link error (Ali)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1365]
Issue reported by **alsibk** at 2020-08-11 16:14:45 UTC
Time: 2020-08-11T16:11:47+00:00
Session ID: b6cbcf168f189cbd36ec89e256c85b2e
Problem Page URL: [/freereg1_csv_entries/5463cea5e9379010fc7a9c4b](/freereg1_csv_entries/5463cea5e9379010fc7a9c4b)
Previous Page URL: []()
Reported Issue:
The link in contact email leads to file details  Unspecified.

The files are Other Transcript    

![Screenshot](https://www.freereg.org.uk)

**Comment by richpomfret** [comment]
Can we have further details?

**Comment by richpomfret** [comment]
@SteveBiggs to investigate...

**Comment by SteveBiggs** [comment]
This looks like another case where a file has been deleted but the overnight process did not happen before a further change was made. Every entry in the file has type Other Transcript apart from this one.

**Comment by suffolkroots** [comment]
This issue arose after I received a request to change a record in WRYINGBU.CSV.
The file shows all records as TR, ie as should be, including the queried one---
WRY,Ingleton,St Mary TR,"",05 Oct 1641,Elinor,dau of,Bryan,"",HDHSON,HODGSON,"","","","",""
This contact came in on 11 August should you wish to check it.

**Comment by PatReynolds** [comment]
To be reassessed when @Captainkirkdawson is available

**Comment by Captainkirkdawson** [comment]
Do not understand the requirement

**Comment by SteveBiggs** [comment]
Nor do I now, and since the Contact from last August has long been deleted, this may as well be closed.

**Comment by suffolkroots** [comment]
OK by me @SteveBiggs

**Comment by SteveBiggs** [comment]
Thanks @suffolkroots
