### ISSUE TITLE
177510893 File MONABDBA6 not linked (Eric D)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1366]
Issue reported by **REGManager** at 2020-08-16 12:34:53 UTC
Time: 2020-08-16T12:30:13+00:00
Session ID: fa1bc0c08e4f665603795231e4613848
Problem Page URL: [/freereg1_csv_files/5a8deb10f493fd507b08b4c5/by_userid?locale=en](/freereg1_csv_files/5a8deb10f493fd507b08b4c5/by_userid?locale=en)
Previous Page URL: [https://www.freereg.org.uk/freereg1_csv_files/5a8deb10f493fd507b08b4c5/by_userid?locale=en](https://www.freereg.org.uk/freereg1_csv_files/5a8deb10f493fd507b08b4c5/by_userid?locale=en)
Reported Issue:
Kirk,

The UserID is gemmicat and the file MONABDBA6.CSV in MON Abergavenny, St Mary, Parish Register.

Please delete this and the transcriber will start again.

Request from Sandra.

Thanks,
Eric    

![Screenshot](https://www.freereg.org.uk)

**Comment by Sherlock21** [comment]
It seems like someone has done this already!

EB

On 16 Aug 2020, at 17:45, FreeUKGenIssues <notifications@github.com> wrote:


Issue reported by REGManager at 2020-08-16 12:34:53 UTC
Time: 2020-08-16T12:30:13+00:00
Session ID: fa1bc0c08e4f665603795231e4613848
Problem Page URL: /freereg1_csv_files/5a8deb10f493fd507b08b4c5/by_userid?locale=en <x-msg://7/freereg1_csv_files/5a8deb10f493fd507b08b4c5/by_userid?locale=en>
Previous Page URL: https://www.freereg.org.uk/freereg1_csv_files/5a8deb10f493fd507b08b4c5/by_userid?locale=en <https://www.freereg.org.uk/freereg1_csv_files/5a8deb10f493fd507b08b4c5/by_userid?locale=en>
Reported Issue:
Kirk,

The UserID is gemmicat and the file MONABDBA6.CSV in MON Abergavenny, St Mary, Parish Register.

Please delete this and the transcriber will start again.

Request from Sandra.

Thanks,
Eric

 <https://camo.githubusercontent.com/e9d19cb6aa736c609f5ff3343c15ce9c620bff9f/68747470733a2f2f7777772e667265657265672e6f72672e756b>

**Comment by Captainkirkdawson** [comment]
Not me; just saw it

Kirk Dawson
Fairmont, B.C. Canada

**Comment by richpomfret** [comment]
Any further action here or can we close? Closing.
