### ISSUE TITLE
178302538 WHy draw the line at certain names for "Unique Names" option? (Michael)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1369]
Issue reported by **BKMCoord** at 2020-08-25 16:28:58 UTC
Time: 2020-08-25T16:24:21+00:00
Session ID: 829896705bdbcd6580594fb015a88fbf
Problem Page URL: [/freereg1_csv_files/unique_names?locale=en&object=5f3298cef493fd4052907f15](/freereg1_csv_files/unique_names?locale=en&object=5f3298cef493fd4052907f15)
Previous Page URL: [https://www.freereg.org.uk/freereg1_csv_files/5f3298cef493fd4052907f15?locale=en](https://www.freereg.org.uk/freereg1_csv_files/5f3298cef493fd4052907f15?locale=en)
Reported Issue:
The "unique names" option does not give witness names on baptisms (and probably not on marriages too). Although these fields are not currently searchable, they could be eventually and it would be useful to get these names correct too.    

![Screenshot](https://www.freereg.org.uk)

**Comment by SteveBiggs** [comment]
I pointed out that Witnesses are searchable if the box is ticked.

**Comment by PatReynolds** [comment]
@Captainkirkdawson is this possible?  If so could you give an estitate?

**Comment by PatReynolds** [comment]
Assigned @Captainkirkdawson  as awaiting his thoughts in due course.

**Comment by Captainkirkdawson** [comment]
Should be done at same time as Restructure Unique Names#2309

**Comment by Captainkirkdawson** [comment]
Adding baptism witnesses and correcting code that generates the marriage witness unique names

**Comment by Captainkirkdawson** [comment]
@SteveBiggs made sure witness for marriage worked and it does. Added witness for baptism. Running on test3

**Comment by SteveBiggs** [comment]
Looks good on test3.
