### ISSUE TITLE
179233960 Missing upload update emails (Eric)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1371]
Issue reported by **nejws05** at 2020-09-05 11:12:40 UTC
Time: 2020-09-05T09:15:05+00:00
Session ID: 2da6773bed4abb481a4887b6a709950e
Problem Page URL: [/freereg1_csv_files?locale=en](/freereg1_csv_files?locale=en)
Previous Page URL: [https://www.freereg.org.uk/manage_counties/select_action?county=Northumberland&locale=en](https://www.freereg.org.uk/manage_counties/select_action?county=Northumberland&locale=en)
Reported Issue:
There have been a few  missing upload update emails to myself and transcribers in the last  2 days. Example was for NBLELSMA on 3/9/20, received by neither, and NBLELSBA2 only received by myself
Eric Wealleans  NBL  Coord    

![Screenshot](https://www.freereg.org.uk)

**Comment by SteveBiggs** [comment]
We have also had a report from Mick Claxton that he stopped getting processing emails on 3rd Sep. Was there a software deployment that may have caused this?

**Comment by SteveBiggs** [comment]
Another report in today:

Feedback 179391205 from Stuart email vk3dwu@live.com.au -

"I uploaded 4 new files today (7 Sep) but did not receive a single email confirming the results."

It seems to be a sporadic problem with some processing emails being received but others not.

**Comment by Captainkirkdawson** [comment]
There has been no software change deployed to FreeREG since 2020-07-18T15:36:09+00:00

**Comment by Captainkirkdawson** [comment]
We had intermittent mail issues with send grid 3 times on 2 Sept. Sent septembers mail log to @SteveBiggs off line

**Comment by SteveBiggs** [comment]
Thanks @Captainkirkdawson , hopefully the intermittent issue won't reoccur.

**Comment by SteveBiggs** [comment]
More reports from Mick Claxton yesterday that he is not receiving processing emails and now from John Turton today:

" I have received an email this morning from Jo regarding a new
> transcriber who apparently joined my team last week. I did not receive
> any notification about this and also sometimes I get auto emails about
> uploads of files and sometimes I don't. A couple of transcribers have
> also not received auto emails recently either about uploads. I haven't
> changed my email address and neither have any of my team. Is there
> something wrong with the FreeREG email system."

**Comment by Captainkirkdawson** [comment]
Mail log for past week sent to @SteveBiggs off line to check

**Comment by PatReynolds** [comment]
@SteveBiggs  to test.

**Comment by SteveBiggs** [comment]
I uploaded a file to the live site to Mick's userID and he DID get the processing email which makes it even stranger why he doesn't when he uploads his own files. Not sure where to go with this one.

**Comment by edickens** [comment]
I think Mick uploads into UserIDs that are set "SC uploads files".  Is this significant?  Does he get emails if he uploads into his own UserID?

**Comment by SteveBiggs** [comment]
He said that when he uploads to his own ID he doesn't get the email.

If he uploads to another ID that's set to "SC uploads", as CC or SC, he should still get the email.

**Comment by edickens** [comment]
I'm gong to try changing Mick's email address to remove the +1.
![Capture.JPG](https://images.zenhubusercontent.com/5cb4c5e2cccdd751e9e85870/08596863-4649-4739-b7af-429414381fed)
It shouldn't make any difference, but I can't think of anything else.
Also, these UesrIDs say that Mick has not uploaded into his account since June.  That doesn't seem right.

**Comment by edickens** [comment]
Mick will not get the CC copy in his hotmail account.
![Capture.JPG](https://images.zenhubusercontent.com/5cb4c5e2cccdd751e9e85870/dbf0730c-1389-45f9-9b2c-7e1f5ff3fda9)
So I don't understand why he doesn't get this as well.

**Comment by edickens** [comment]
I have changed Mick's SC email address to remove the +1
![Capture.JPG](https://images.zenhubusercontent.com/5cb4c5e2cccdd751e9e85870/e74f88c5-e02d-4bb0-8ed3-fd4287914d69)

**Comment by SteveBiggs** [comment]
Is this still an issue?

**Comment by DeniseColbert** [comment]
We think this is fine now so closing
