### ISSUE TITLE
181121678 Broken link (Ali)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1374]
Issue reported by **alsibk** at 2020-09-27 07:34:38 UTC
Time: 2020-09-27T07:30:52+00:00
Session ID: 825fb06e5402581f407993f5decd5bed
Problem Page URL: [/cms/information-for-transcribers](/cms/information-for-transcribers)
Previous Page URL: [https://www.freereg.org.uk/cms/information-for-coordinators](https://www.freereg.org.uk/cms/information-for-coordinators)
Reported Issue:
Information for Transcribers/Entering data from registers/General guidance----

The link to Names is not working    

![Screenshot](https://www.freereg.org.uk)

**Comment by AlOneill** [comment]
Fixed on test3.

**Comment by PatReynolds** [comment]
@SteveBiggs to test

**Comment by SteveBiggs** [comment]
Tested and works now.

**Comment by Vino-S** [comment]
deployed to production
