### ISSUE TITLE
181323283 Incorrect reporting of transcribers (Michael)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1376]
Issue reported by **LINCC** at 2020-09-29 15:34:43 UTC
Time: 2020-09-29T15:28:09+00:00
Session ID: 0f6784dde478a449cbe028a44cc620c2
Problem Page URL: [/registers/5f72c722f493fd176fa88821?locale=en](/registers/5f72c722f493fd176fa88821?locale=en)
Previous Page URL: [https://www.freereg.org.uk/churches/5408787deca9eb0248c2c12f?locale=en](https://www.freereg.org.uk/churches/5408787deca9eb0248c2c12f?locale=en)
Reported Issue:
I recently uploaded some new sets of  OT transcriptions

ALL had exactly the same file header apart from the event type (BA/BU) and filename.

Why are the Transcribed By column headings different for the different event types - see image?
https://www.freereg.org.uk/uploads/feedback/screenshot/5f735413f493fd42bc1ec776/Capture.JPG    

![Screenshot](https://www.freereg.org.uk)

**Comment by PatReynolds** [comment]
@PatReynolds to investigate

**Comment by PatReynolds** [comment]
Now seem to to be displayed correctly:
![image.png](https://images.zenhubusercontent.com/5b695a5dac3a200155c765e3/4afdf9f0-6e32-4162-aab1-9dfd603c62a4)

**Comment by PatReynolds** [comment]
@PatReynolds  to check with Michael.

**Comment by PatReynolds** [comment]
Contacted 2/2/2021

**Comment by Mick-Claxton** [comment]
Checked the summary table and everything is correctly laid out now.

**Comment by DeniseColbert** [comment]
Fixed so closing
