### ISSUE TITLE
181555840 Cannot find message (Pat)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1377]
Issue reported by **PatReynolds** at 2020-10-02 08:10:40 UTC
Time: 2020-10-02T08:06:25+00:00
Session ID: 37a610fe3e3e5b6f21300ed72badc374
Problem Page URL: [/messages/select_by_identifier?locale=en](/messages/select_by_identifier?locale=en)
Previous Page URL: [https://www.freereg.org.uk/messages/list_by_most_recent?locale=en](https://www.freereg.org.uk/messages/list_by_most_recent?locale=en)
Reported Issue:
I have been told that there is a message for me No. 181520749 but can't see it on my list of messages (just ones from me or from EricD) and can't see it on the drop-down list which has a 'select role' button rather than 'select message' as I thought it would be ... maybe separate issues.  

https://www.freereg.org.uk/uploads/feedback/screenshot/5f76e080f493fd6b7b4c817b/Message_selection.JPG    

![Screenshot](https://www.freereg.org.uk)

**Comment by PatReynolds** [comment]
@PatReynolds to test again

**Comment by PatReynolds** [comment]
OK - there now!  Must have just been the wind direction or something.
