### ISSUE TITLE
part 2 of my previous Report re  Replacing a file. (ericb)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#138]
Issue reported by **ericb** at 2015-01-03 14:37:45 UTC
Time: 2015-01-03T14:32:31+00:00
Session ID: a6177376409989f67df249544a1541f9
Problem Page URL: [/freereg1_csv_files/my_own?](/freereg1_csv_files/my_own?)
Previous Page URL: [http://test2.freereg.org.uk/manage_resources/new](http://test2.freereg.org.uk/manage_resources/new)
Reported Issue:
I had to close my browser before I could do anything else in FR2 - each time I tried to do anything in FR2, I got no reply.

So closed Browser (Mac Safari) and logged on another session to the server. OK

Then navigated to My files, and chose Upload a new file ( since it had showed previously the one I wanted was not listed.)
As soon as I clicked on the uplaod button, it crashed me out    

![Screenshot](http://test2.freereg.org.uk)

**Comment by Sherlock21** [comment]
I gave it a few minutes whilst I thought, and compiled another report ( that will have next number?).

Then I had another go to upload.

This time I could log in to members area, and right through the process to upload and process the new file.
So: is my working dependant on server work at the time? This file is only some 2500 records of Baptisms. - 328 KB as a csv file.

My file correction job is actually completed now. But the issue of timing out obviously remains.
Is it only a Mac issue?

**Comment by edickens** [comment]
```
I don't think this is a Mac issue. 
  Kirk did say once that uploading does a lot of indexing and will
  be slow.  That is why he introduced the "background" option.  In
  fact I was working on FR2 at the time you were uploading and it
  got very slow.  It actually crashed my working on the refinery,
  which seems to be OK now.
  EricD
  _____________________________________
```

Eric J Dickens
FreeREG Chairman
      On 03/01/2015 14:54, Sherlock21 wrote:

```
  I gave it a few minutes whilst I thought, and compiled another
    report ( that will have next number?).
  Then I had another go to upload.
  This time I could log in to members area, and right through the
    process to upload and process the new file.
    So: is my working dependant on server work at the time? This
    file is only some 2500 records of Baptisms. - 328 KB as a csv
    file.
  My file correction job is actually completed now. But the issue
    of timing out obviously remains.
    Is it only a Mac issue?
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by Captainkirkdawson** [comment]
I have no reports of anyone else reporting upload timeouts. That does NOT mean that they do not exist just that Eric may be the only one doing it,

Since you were able to do the same work latter it tells me that it was a server issue.
Given that the issue occurred at the same time as Eric D was experiencing unrelated issues I have a strong feeling that the problem was a server problem caused by unrelated activities.

These will happen while we function on a test server.
