### ISSUE TITLE
181907832 Enhancement Suggestion (John Gauss)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1380]
Issue reported by **John Gauss** at 2020-10-06 09:57:12 UTC
Time: 2020-10-06T09:54:01+00:00
Session ID: d124fe530a4d0ddab511b66e91927a16
Problem Page URL: []()
Previous Page URL: [https://www.freereg.org.uk/contacts/new](https://www.freereg.org.uk/contacts/new)
Reported Issue:
I’ve just been using FreeREG and like the Number of Records per Decade tables for each parish.  The lack of this on other sites like Ancestry and FindMyPast is a big disadvantage, as it’s hard to know whether you’re failing to find an entry because the years are badly indexed, not indexed, unreadable or missing.

Part of Systemwide #158

However, can I suggest that an even clearer display would be a bar chart showing the number of entries for each year (fictitious example attached).  This would make it quite clear that some years for each event are not in the database, or only partially so, for whatever reason.

Regards,
John Gauss

https://www13.freereg.org.uk/uploads/contact/screenshot/5f7c3f78f493fdd2a65672c7/Parish_Event_Year_Statistics_Example.png

**Comment by edickens** [comment]
What  aboujt this...

![Capture.JPG](https://images.zenhubusercontent.com/5cb4c5e2cccdd751e9e85870/339d610e-c15a-4432-9210-0046bd5ee289)

**Comment by edickens** [comment]
This is just one person's request, although we discussed it a few years ago.  If we think it is worth it, and it is a lot of programming, then it should go in the Roadmap for some time in the future.
I have replied to the sender.
