### ISSUE TITLE
182814774 Wrong spelling on error message from FreeREG (Michael)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1382]
Issue reported by **BKMCoord** at 2020-10-16 21:52:54 UTC
Time: 2020-10-16T21:49:06+00:00
Session ID: cc2cb3846e3b55f807e6630df8d2f33c
Problem Page URL: [/freereg1_csv_files/5f77170cf493fd8afe15ce44?locale=en](/freereg1_csv_files/5f77170cf493fd8afe15ce44?locale=en)
Previous Page URL: [https://www.freereg.org.uk/freereg1_csv_files/5f77170cf493fd8afe15ce44?locale=en](https://www.freereg.org.uk/freereg1_csv_files/5f77170cf493fd8afe15ce44?locale=en)
Reported Issue:
I always thought that one can "advise" but one can receive "advice". See aatachment for FreeREG error message involved.
https://www.freereg.org.uk/uploads/feedback/screenshot/5f8a1636f493fd644a2d13c8/Capture.JPG    

![Screenshot](https://www.freereg.org.uk)

**Comment by jayto581** [comment]
Pull request submitted. branch sp-issue-182814774

**Comment by Captainkirkdawson** [comment]
Pulled into master. Thank you Joseph
