### ISSUE TITLE
182874876 Search limits (Michael)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1383]
Issue reported by **BKMCoord** at 2020-10-17 14:34:36 UTC
Time: 2020-10-17T14:18:08+00:00
Session ID: cc2cb3846e3b55f807e6630df8d2f33c
Problem Page URL: [/search_queries/5f8afd1ff493fdd3797ed030?locale=en](/search_queries/5f8afd1ff493fdd3797ed030?locale=en)
Previous Page URL: [https://www.freereg.org.uk/search_queries/new?locale=en&search_id=5f8afcccf493fdd3797ecd7d](https://www.freereg.org.uk/search_queries/new?locale=en&search_id=5f8afcccf493fdd3797ecd7d)
Reported Issue:
I understand that FreeREG feels that it is important not to overload a researcher with "too many" records.

However, telling a researcher that there are over 500 records found for the search and then saying that no records have been found is a little bit stupid. Surely it would be better to let the researcher see what has been found so far. It may be that the thing that is being searched for is within the 500. Obviously, it may not.

Would it be possible to return the "found" records in "frames" similar to the way that items are displayed for Coordinators and Transcribers? I realise that the data for Coordinators and Transcribers is finite and known beforehand whereas the results of a search are only known as the search progresses.

    

![Screenshot](https://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
We have not done so since the result list is not reproducible. The same search will likely produce a different set of results each time and lead to total confusion

**Comment by PatReynolds** [comment]
Nothing to be done
