### ISSUE TITLE
183915108 File gets duplicated if uploaded again before the first upload is complete (Eric D)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1385]
Issue reported by **REGManager** at 2020-10-29 15:31:48 UTC
Time: 2020-10-29T15:26:56+00:00
Session ID: 7a44384e7879f072727d3491282eb3ae
Problem Page URL: [/attic_files/?userid=Mizztraveller](/attic_files/?userid=Mizztraveller)
Previous Page URL: [https://www.freereg.org.uk/attic_files/select_userid](https://www.freereg.org.uk/attic_files/select_userid)
Reported Issue:
A new transcriber uploaded the file Mizztraveller/MONZZNBA.CSV again before the first upload was complete.  An easy mistake to make as they thought the first upload had not worked.  The result is that the two uploads were merged and all entries duplicated.  This might have gone un-noticed by other transcribers so there could be others like this.
I suggest a check is needed to reject an upload if the same UserID/Filename is in the waiting to be processed, or being processed queues.    

![Screenshot](https://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
There is already a check to see if the file is waiting to be processed on a replace

**Comment by PatReynolds** [comment]
Can happen if tiimed right to the millisecond.
