### ISSUE TITLE
183981923 Review batches syndicate WRY (Ali)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1387]
Issue reported by **alsibk** at 2020-10-30 10:05:23 UTC
Time: 2020-10-30T10:00:35+00:00
Session ID: 8bf194e324d8939378160a91ecc14ed4
Problem Page URL: [/manage_syndicates/select_action.%3fsyndicate=Yorkshire,%20West%20Riding%20-%20Ali%20Hill?locale=en](/manage_syndicates/select_action.%3fsyndicate=Yorkshire,%20West%20Riding%20-%20Ali%20Hill?locale=en)
Previous Page URL: [https://www.freereg.org.uk/messages/list_syndicate_messages?source=list_syndicate_messages](https://www.freereg.org.uk/messages/list_syndicate_messages?source=list_syndicate_messages)
Reported Issue:
Most Review Batches buttons in Syndicate actions not working.    

![Screenshot](https://www.freereg.org.uk)

**Comment by SteveBiggs** [comment]
On testing, the buttons do work but take a long time to return the lists and on a very large syndicate, they take a very long time which seems longer than it used to.

**Comment by PatReynolds** [comment]
Is select a specific file sufficient?

Need to look into the option of paging (toggle to that)

**Comment by SteveBiggs** [comment]
The files are paginated but still take between 30 and 50 secs to load depending on Syndicate size. However, there have been no complaints for a long time.

**Comment by PatReynolds** [comment]
... therefore closing.
