### ISSUE TITLE
183738819 Data Problem (Susan Firestone)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1389]
Issue reported by **Susan Firestone** at 2020-10-27 14:33:39 UTC
Time: 2020-10-27T14:31:46+00:00
Session ID: 48a30ee5aaf1ab152e3e40c4b51dcbb3
Problem Page URL: [https://www.freereg.org.uk/search_records/5d580b30f493fdda978ade19/sarah-gathercole-baptism-suffolk-lakenheath-1813-07-01?locale=en](https://www.freereg.org.uk/search_records/5d580b30f493fdda978ade19/sarah-gathercole-baptism-suffolk-lakenheath-1813-07-01?locale=en)
Previous Page URL: [https://www.freereg.org.uk/contacts/5d580b30f493fdda978ade19/report_error?locale=en&query=5f982831f493fdf5322269a6](https://www.freereg.org.uk/contacts/5d580b30f493fdda978ade19/report_error?locale=en&query=5f982831f493fdf5322269a6)
Reported Issue:
Mother's name is Lucy, not Amy according to familysearch.org.

**Comment by PatReynolds** [comment]
@SteveBiggs to forward to Jule Harrold

**Comment by SteveBiggs** [comment]
On checking Contacts, Julie has already answered this so it must have been a mistake to raise as an issue. Closing.
