### ISSUE TITLE
Improve access to the Help documentation (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#139]
Issue reported by **REGManager** at 2015-01-03 15:54:48 UTC
Time: 2015-01-03T15:47:00+00:00
Session ID: eb453775b9c3dede60b0730e9e49b6db
Problem Page URL: [/information-for-coordinators](/information-for-coordinators)
Previous Page URL: [http://test2.freereg.org.uk/](http://test2.freereg.org.uk/)
Reported Issue:
Bernie has suggested that we should tell the researcher about the contents of the database using the document "the-freereg-databases".
So I am suggesting that on selecting the Help button, there should be a menu which will have "tips-for-searching-the-database" and also "the-freereg-databases" as well perhaps as Contact Us, Volunteer and so on.
I can't do a screen print  because I had to log in to write this and the Help is different if you are logged in.  So perhaps that is another thing to consider.  We should have the same Help menu when not logged in, but with more options depending on the type of person.  All the Transcribing Help pages could be accessed this way.
EricD    

![Screenshot](http://test2.freereg.org.uk)

**Comment by Sherlock21** [comment]
I tend to favour Contact Us to be a freestanding link with its own menu like: problems you have, volunteer with different classes, 

These topics are different to, and should be on a different link to the How FR2 is set up and works.

**Comment by Captainkirkdawson** [comment]
Comments in analysis
