### ISSUE TITLE
186513148 File upload problem (Mick)

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeUKRegProductIssues#1394]
Issue reported by **Mick** at 2020-11-28 17:12:28 UTC
Time: 2020-11-28T17:06:44+00:00
Session ID: 3a81ad7906fe44b91176834db8a89a85
Problem Page URL: [/csvfiles/new](/csvfiles/new)
Previous Page URL: [https://www.freereg.org.uk/csvfiles/new](https://www.freereg.org.uk/csvfiles/new)
Reported Issue:
Trying to upload a file and get the following error message,i have checked the file and there doesn't appear to be anything wrong with it. -

"The file either does not exist or is too small to be a valid file"    

![Screenshot](https://www.freereg.org.uk)

**Comment by SteveBiggs** [comment]
Many others have raised the same problem of course.

**Comment by richpomfret** [comment]
Fixed now so closing.
