### ISSUE TITLE
186578498 Delete blank line at end of batch gives error. (Barrie)

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeUKRegProductIssues#1395]
Issue reported by **brobinson43** at 2020-11-29 11:21:38 UTC
Time: 2020-11-29T11:15:49+00:00
Session ID: 61aa5f84f967556eac0d8e68dd8e93fb
Problem Page URL: [/freereg1_csv_entries?locale=en](/freereg1_csv_entries?locale=en)
Previous Page URL: [https://www.freereg.org.uk/freereg1_csv_files/5faffc00f493fd4627ed4678?locale=en](https://www.freereg.org.uk/freereg1_csv_files/5faffc00f493fd4627ed4678?locale=en)
Reported Issue:
My transcriber attempted to use the Destroy button to delete a redundant blank line at the end of his batch, but we got the "We're sorry but ...." error message. I tried the same thing, and also the DE button on the line.

The batch was Pev:WARLOXBU1.CSV, the final line.    

![Screenshot](https://www.freereg.org.uk)

**Comment by SteveBiggs** [comment]
Same thing happened when I tried it.

**Comment by Captainkirkdawson** [comment]
Issue fixed

Nothing to do with the recent code changes

Kirk Dawson
Programmer and Technical Advisor
FreeUKGEN

**Comment by richpomfret** [comment]
@SteveBiggs can you briefly test this? It's now live.

**Comment by SteveBiggs** [comment]
Tested and working now
