### ISSUE TITLE
186482337 contacts list confused (Julie )

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeUKRegProductIssues#1396]
Issue reported by **JulieHarold** at 2020-11-28 08:38:57 UTC
Time: 2020-11-28T08:34:21+00:00
Session ID: 00fef9974c80ccadc61b5a67c0309ef7
Problem Page URL: [/contacts/list_by_date?locale=en](/contacts/list_by_date?locale=en)
Previous Page URL: [https://www.freereg.org.uk/contacts](https://www.freereg.org.uk/contacts)
Reported Issue:
I intended to work through some more contacts for NFK to sort out corrections.  The list is confused today - dating back to July (which were dealt with long ago), and with other counties mixed in.  It was not like this yesterday as I was working on on the early evening.  I think the earliest date for the outstanding contacts should be about 10 Nov.
Julie (Norfolk coordinator)    

![Screenshot](https://www.freereg.org.uk)

**Comment by SteveBiggs** [comment]
It appears that coordinators can currently see Contacts for ALL counties.

**Comment by Captainkirkdawson** [comment]
This code has not been changed in over a year  and was unaffected by the recent deployment.

Clearly Julie is looking at the archived list if she is seeing July entries.

The current list has nothing earlier than Nov 10 for NFK

I see nothing in the code that does a selection by county but I could be missing something

**Comment by Captainkirkdawson** [comment]
Found the selection code; it is very old and untouched

**Comment by SteveBiggs** [comment]
All very strange, but when I log in as my SSX CC userID, I can see Contacts for all counties too now. This has only started happening in the last couple of days.

**Comment by SteveBiggs** [comment]
And the Active ones go back to 7th July 2020:

![image](https://user-images.githubusercontent.com/25303607/100557253-c0c11400-329f-11eb-8bbb-850632c68f75.png)

but some have a Restore button suggesting they are really Archived?

**Comment by Captainkirkdawson** [comment]
@SteveBiggs I have rewritten the coordinator selection; can you tell me if it works as expected. A county coordinator will receive a list for ALL the counties  for which they are responsible

**Comment by SteveBiggs** [comment]
It would appear to be fixed because I can see no active Contacts under my CC userID (I have dealt with all of them).

**Comment by richpomfret** [comment]
Fixed so closing. @edickens to drop Julie a line and check it is fixed for her.
