### ISSUE TITLE
186743198 Download of Physical File doesn't work (Eric D)

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeUKRegProductIssues#1397]
Issue reported by **REGManager** at 2020-12-01 09:06:38 UTC
Time: 2020-12-01T09:01:04+00:00
Session ID: ed6780be956af4854a526268f3da4b9a
Problem Page URL: [/physical_files?locale=en](/physical_files?locale=en)
Previous Page URL: [https://www.freereg.org.uk/physical_files?locale=en](https://www.freereg.org.uk/physical_files?locale=en)
Reported Issue:
I wanted to look at a Physical File to see if there is more than one Place, Church, or Register Type in the file.  There is no Browse.
The Download button reports Downloaded but it isn't.  I usually also get a message to say Open or Save the file, but I don't.
I can download the Batch, but that is not what I want to check.
https://www.freereg.org.uk/uploads/feedback/screenshot/5fc6079ef493fd44f4fcecb0/Capture.JPG    

![Screenshot](https://www.freereg.org.uk)

E2 U2 S7 C6: P17

**Comment by edickens** [comment]
Not urgent as I have downloaded the file from FR1.  It is just one Place so would only create one batch, which is what I needed to know.  I can't use the FR1 file as it looks to have been edited, but as it is only one batch, that is not a problem as I can download the batch.

I don't know if anyone else uses this facility as they have not complained.

**Comment by Captainkirkdawson** [comment]
@edickens I believe it should work now.
The Physical Files action is a restricted access action
