### ISSUE TITLE
187264611 The UserID list of email addresses is case sensitive (Eric D)

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeUKRegProductIssues#1398]
Issue reported by **REGManager** at 2020-12-07 09:56:51 UTC
Time: 2020-12-07T09:23:37+00:00
Session ID: ec697abc5fd10ba121227c6788b45a43
Problem Page URL: [/userid_details/selection?option=Select%20specific%20email](/userid_details/selection?option=Select%20specific%20email)
Previous Page URL: [https://www.freereg.org.uk/userid_details/options](https://www.freereg.org.uk/userid_details/options)
Reported Issue:
The sorted list of UserID emails has upper and lower case first letters not together.  I came across this because some UserIDs have their email starting with a capital letter here but lower case in the Transcribers mailgroup.  It makes matching very difficult.
I thought we had sorted this out years ago, but perhaps it was a different list.    

![Screenshot](https://www.freereg.org.uk)

E0U1 SS1 C6 =P8

**Comment by Captainkirkdawson** [comment]
@edickens Twas a different list.
Your email addresses are now sorted case independent. deployed to production

**Comment by edickens** [comment]
TY.  Can be closed.
