### ISSUE TITLE
187297145 server can't read valid file, which then cannot be replaced (Dale)

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeUKRegProductIssues#1399]
Issue reported by **dbraden** at 2020-12-07 18:59:05 UTC
Time: 2020-12-07T18:25:48+00:00
Session ID: fb1de8ebd118a0c381779511b7522d05
Problem Page URL: [/freereg1_csv_files/my_own?locale=en](/freereg1_csv_files/my_own?locale=en)
Previous Page URL: [https://www.freereg.org.uk/csvfiles/5fce6e12f493fd6007826c40/edit?locale=en](https://www.freereg.org.uk/csvfiles/5fce6e12f493fd6007826c40/edit?locale=en)
Reported Issue:
Yesterday (6 Dec) I uploaded a file called STSSEDBU2.CSV which the server said was invalid (wrong format or invalid character).  The file was created with WinREG and can also be read by LibreOffice Calc and does not show any obvious problem.  After rejecting the file, the server did not show the file in the list of files with errors, so I could not replace it.  Nor could I re-upload it, because the server said the file was already present on the system.  So I changed the name of the file and began removing records to try to figure out what the problem was.  Each time I uploaded a bad file, the server would reject it but then register the filename as being in my account, so that filename was no longer usable. The following files are now associated with my account but are not actually visible (at lesat not at the time of this writing): STSSEDBU2.CSV, STSSEDBU3.CSV, STSSEDBU4.CSV and STSSEDBU5.CSV.  I have isolated the problem to lines 264-274, and the problem is in the Notes field, and may have something to do with the use of double and single quotes.  The file called STSSEDBU6.CSV has now been accepted by the server, so lines 264-274 in that file can be used for comparison to figure out what the parser was getting hung up on.     

![Screenshot](https://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
The empty files have been removed

**Comment by SteveBiggs** [comment]
Do we know what the cause of the problem was? If the file was error-free in WinREG, why would the website have a problem?
