### ISSUE TITLE
Required new fields - CC has data to transcribe and CC is recruiting (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#140]
Issue reported by **REGManager** at 2015-01-04 14:29:07 UTC
Time: 2015-01-04T14:24:16+00:00
Session ID: 450965e559ac6bc07a51ed677c5aa51a
Problem Page URL: [/counties/531a1998231040725c000015/edit](/counties/531a1998231040725c000015/edit)
Previous Page URL: [http://test2.freereg.org.uk/counties](http://test2.freereg.org.uk/counties)
Reported Issue:
In FR1 under "How to Volunteer" we show which  counties have data and so are recruiting.  This is needed so that we don't get volunteers asking for counties where we cannot accommodate them.  In the "Volunteer" when the select a county, then if these markers are not set, the volunteer should be advised to go to another county, unless they have access to data.
Default is True.  These fields to be amendable by the CC.
EricD    

![Screenshot](http://test2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
I am puzzled at this stated requirement. County coordinators do not have transcribers. 

Syndicate coordinators do and fields already exist for syndicates that indicate that they are recruiting volunteers or not. The volunteer page only includes those syndicates seeking volunteers

**Comment by edickens** [comment]
```
Hi Kirk,
  You are correct.  The "Recruiting" should be and is under the
  control of the SC, but we need a "Have data" under the CC.  It is
  the CC who will be managing the data ready for transcribing.
  This has come to my mind because Mary has said that she has run
  out of work to transcribe for HUN.
  EricD
  _____________________________________
```

Eric J Dickens
FreeREG Chairman
      On 04/01/2015 21:43, Kirk Dawson wrote:

```
  I am puzzled at this stated requirement. County coordinators do
    not have transcribers. 
  Syndicate coordinators do and fields already exist for
    syndicates that indicate that they are recruiting volunteers or
    not. The volunteer page only includes those syndicates seeking
    volunteers
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by edickens** [comment]
```
Hi Kirk,
  Forget what I have said here.  I have a bad cold and was not
  thinking straight.  The marker to say when we have data to
  transcribe should be at Place/Church or even Register level.  We
  can define this system and sort it out when we integrate the image
  server.  This topic can be closed.
  Regards EricD
  _____________________________________
```

Eric J Dickens
FreeREG Chairman
      On 04/01/2015 22:22, Eric Dickens-gmail wrote:

```
  Hi Kirk,
    You are correct.  The "Recruiting" should be and is under the
    control of the SC, but we need a "Have data" under the CC.  It
    is the CC who will be managing the data ready for transcribing.
    This has come to my mind because Mary has said that she has run
    out of work to transcribe for HUN.
    EricD
    _____________________________________
```

Eric J Dickens
FreeREG Chairman
        On 04/01/2015 21:43, Kirk Dawson wrote:

```
    I am puzzled at this stated requirement. County coordinators
      do not have transcribers. 
    Syndicate coordinators do and fields already exist for
      syndicates that indicate that they are recruiting volunteers
      or not. The volunteer page only includes those syndicates
      seeking volunteers
    —
      Reply to this email directly or view

        it on GitHub.
```
