### ISSUE TITLE
187879104 Meaningless error report in batch upload (Barrie)

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeUKRegProductIssues#1400]
Issue reported by **brobinson43** at 2020-12-14 12:38:24 UTC
Time: 2020-12-14T12:30:15+00:00
Session ID: 36a3bd53cbdd366974dd0023571f86fe
Problem Page URL: [/freereg1_csv_files/5fd759a4f493fd9aad6c5fae/error?locale=en](/freereg1_csv_files/5fd759a4f493fd9aad6c5fae/error?locale=en)
Previous Page URL: [https://www.freereg.org.uk/freereg1_csv_files/5fd759a4f493fd9aad6c5fae?locale=en](https://www.freereg.org.uk/freereg1_csv_files/5fd759a4f493fd9aad6c5fae?locale=en)
Reported Issue:
I have just uploaded the batch, WARNWTBA3.CSV and received a message alleging the same error in two lines (24 and 141): {:groom_age=>["Invalid age"]}
As this is a baptism batch, and as far as I can see there is no such field as groom_age, this error is meaningless, and I can't determine what caused the errors.    

![Screenshot](https://www.freereg.org.uk)

**Comment by SteveBiggs** [comment]
The error should say 'person_age' rather than 'groom_age'. (There are genuine errors in person_age which I've pointed out to Barrie).

**Comment by Captainkirkdawson** [comment]
Correction applied. Deployed to test3

**Comment by DeniseColbert** [comment]
@SteveBiggs could you ask Barrie to test this on Test3 please?

**Comment by SteveBiggs** [comment]
Have asked Barrie to test

**Comment by SteveBiggs** [comment]
Barrie has tested and it looks good now.
