### ISSUE TITLE
188141416 Not seeing contacts (Joanne)

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeUKRegProductIssues#1401]
Issue reported by **ManCity** at 2020-12-17 13:30:16 UTC
Time: 2020-12-17T13:24:55+00:00
Session ID: 2a8e69a0b947f75a7581bc8a952886b2
Problem Page URL: [/manage_resources/new?locale=en](/manage_resources/new?locale=en)
Previous Page URL: [https://www.freereg.org.uk/cms/refinery/login](https://www.freereg.org.uk/cms/refinery/login)
Reported Issue:
When go through contacts I’m seeing list of data errors instead, at the moment there aren’t any.  I do get an email copy for some contacts so am replying through email to those however there won’t be a record on the website of my replies.  Those contacts that don’t give a copy by email I obviously don’t know have come in so can’t reply to them.    

![Screenshot](https://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Fix applied so that secondary role for volunteer_coordinator sees all contacts. Applied to test3

**Comment by DeniseColbert** [comment]
Denise to tell Joanne that this can be tested on Test3 (if she can't access she needs to sign up)

**Comment by DeniseColbert** [comment]
I emailed Jo back in April (CCd Steve) but have had no reply. Did you @SteveBiggs ?

**Comment by SteveBiggs** [comment]
What date did you send the email @DeniseColbert ?

**Comment by SteveBiggs** [comment]
I have not had a reply either.
