### ISSUE TITLE
188313350 Modification or additional reason would be helpful (Somerset)

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeUKRegProductIssues#1402]
Issue reported by **SOMCoord** at 2020-12-19 13:15:50 UTC
Time: 2020-12-19T12:56:06+00:00
Session ID: 844937e51376bb86f209069eb1d16e37
Problem Page URL: [/gaps?locale=en&register=5409e2b5eca9eb71824ed635](/gaps?locale=en&register=5409e2b5eca9eb71824ed635)
Previous Page URL: [https://www.freereg.org.uk/registers/5409e2b5eca9eb71824ed635?locale=en](https://www.freereg.org.uk/registers/5409e2b5eca9eb71824ed635?locale=en)
Reported Issue:
See my three GAPs for Som Taunton St Mary. There is valuable information in the Register about why some (but not all) entries are missing, and I have put that information in the Notes. 

However a researcher does not get to see the Notes. When a researcher looks at the Gaps all he sees is " No entries for these years". This is not true, there are some entries for parts of these years, but not for all months. 

I would be better if the researcher could see the notes, or there was an extra choice when creating the GAP. 

If the start and end date could include months, that would make it clear there is some data, and some gaps. 

Or an additional reason is needed, such as No entries for these months.

Jackie James
Somcoord    

![Screenshot](https://www.freereg.org.uk)

**Comment by edickens** [comment]
Jackie,
I have created a new reason...
![Capture.JPG](https://images.zenhubusercontent.com/5cb4c5e2cccdd751e9e85870/27bf7a4b-2adf-4a9a-bde3-8419e594f14d)
A good point that the researcher needs to see the notes.
