### ISSUE TITLE
188919792 Transcription tab now Records (Angela)

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeUKRegProductIssues#1405]
Issue reported by **AngieBEast** at 2020-12-26 13:43:12 UTC
Time: 2020-12-26T13:39:33+00:00
Session ID: 7cc1ad8e3406530eb758cd904899cea8
Problem Page URL: [/cms/help](/cms/help)
Previous Page URL: [https://www.freereg.org.uk/freereg_contents/new?locale=en](https://www.freereg.org.uk/freereg_contents/new?locale=en)
Reported Issue:
A small thing, but the help for Records says to click on Transcriptions link on main page, but that has now been renamed Records? I dont know if theres anywhere else it mentions Transcriptions instead of Records?    

![Screenshot](https://www.freereg.org.uk)

**Comment by SteveBiggs** [comment]
'Transcriptions' is referenced several times in the researcher help and should be changed to 'Records'

**Comment by PatReynolds** [comment]
@AlOneill has kindly done this en passant another task (#2332)

**Comment by DeniseColbert** [comment]
Done- closing

**Comment by DeniseColbert** [comment]
Found an instance:

![image.png](https://images.zenhubusercontent.com/5cab6cc818447254e461e741/6e06387b-9fa1-4bef-9162-86c8b25ad119)

**Comment by AlOneill** [comment]
@DeniseColbert TY, fixed on test3.
