### ISSUE TITLE
189188169 General Comment (Richard Thompson)

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeUKRegProductIssues#1406]
Issue reported by **Richard Thompson** at 2020-12-29 16:16:09 UTC
Time: 2020-12-29T16:09:55+00:00
Session ID: 
Problem Page URL: []()
Previous Page URL: [https://www.freereg.org.uk/contacts/new](https://www.freereg.org.uk/contacts/new)
Reported Issue:
One of the ways I use your site is to find children of particular parents. To do this it is necessary to ‘dip’ into and back out of the baptism pages for the many children. Could I make a suggestion? Would it be possible to add a sixth and seventh column with mother and father’s names to baptismal pages. This would make the information far more accessible.

Regards Richard    

E0 U3 S6 C8: P17

**Comment by PatReynolds** [comment]
Is this comment still in the system?  I can't find it.

**Comment by DeniseColbert** [comment]
@DeniseColbert to see if the contact appears in my account and pass email to Pat
