### ISSUE TITLE
190457169 Settiing and Embargo for an Entry (Eric D)

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeUKRegProductIssues#1411]
Issue reported by **REGManager** at 2021-01-13 08:46:09 UTC
Time: 2021-01-13T08:41:24+00:00
Session ID: 20849ae697308972f553eaaad8f8e616
Problem Page URL: [/freereg1_csv_entries/5f37dc9ff493fd15274b1bd9?locale=en](/freereg1_csv_entries/5f37dc9ff493fd15274b1bd9?locale=en)
Previous Page URL: [https://www.freereg.org.uk/feedbacks/new?utf8=%E2%9C%93&feedback_time=2021-01-13+08%3A30%3A51+UTC&session_id=20849ae697308972f553eaaad8f8e616&user_id=REGManager&problem_page_url=%2Ffreereg1_csv_entries%2F5f37dc9ff493fd15274b1bd9%3Flocale%3Den&previous_page_url=https%3A%2F%2Fwww.freereg.org.uk%2Ffreereg1_csv_entries%2F5f37dc9ff493fd15274b1bd9%2Fedit_embargo%3Flocale%3Den&feedback_type=issue](https://www.freereg.org.uk/feedbacks/new?utf8=%E2%9C%93&feedback_time=2021-01-13+08%3A30%3A51+UTC&session_id=20849ae697308972f553eaaad8f8e616&user_id=REGManager&problem_page_url=%2Ffreereg1_csv_entries%2F5f37dc9ff493fd15274b1bd9%3Flocale%3Den&previous_page_url=https%3A%2F%2Fwww.freereg.org.uk%2Ffreereg1_csv_entries%2F5f37dc9ff493fd15274b1bd9%2Fedit_embargo%3Flocale%3Den&feedback_type=issue)
Reported Issue:
PS.  I see now that the details of the Embargo are shown at the end of the list of fields in the entry.  So is this downloaded with the batch as part of CSV?    

![Screenshot](https://www.freereg.org.uk)

**Comment by DeniseColbert** [comment]
It is not.
