### ISSUE TITLE
191169349 MGY Area Circuit Registers (Team)

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeUKRegProductIssues#1413]
Issue reported by **alycymru** at 2021-01-21 14:35:49 UTC
Time: 2021-01-21T14:29:13+00:00
Session ID: ed4d042151bd7cf5f3c4ef51a23954d7
Problem Page URL: [/manage_counties/select_action?county=Montgomeryshire&locale=en](/manage_counties/select_action?county=Montgomeryshire&locale=en)
Previous Page URL: [https://www.freereg.org.uk/freereg1_csv_files?locale=en](https://www.freereg.org.uk/freereg1_csv_files?locale=en)
Reported Issue:
Uploads for this place are treated as invalid. The place name has a notification of an error which I have been informed by Eric is not the problem but it still keeps rejecting the file as follows:
The place name at field Area Circuit Registers is invalid at line 1. 
The church name Llanidloes Particular Baptist is not in the database for Area Circuit Registers at line 1. 
    

![Screenshot](https://www.freereg.org.uk)

**Comment by Sherlock21** [comment]
please send me the .csv file that you are trying to upload and I will see what is wrong with the place name .
send it via your Cc please to my email address.

**Comment by DeniseColbert** [comment]
@edickens to check status of this.

**Comment by edickens** [comment]
Glen confirms all sorted and this can be closed.
