### ISSUE TITLE
192913693  (Jackie)

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeUKRegProductIssues#1416]
Issue reported by **jd1363sry** at 2021-02-10 19:08:13 UTC
Time: 2021-02-10T19:04:03+00:00
Session ID: 41e83b06d5801e4de458cd009e244269
Problem Page URL: [/manage_resources/new?locale=en](/manage_resources/new?locale=en)
Previous Page URL: []()
Reported Issue:
When entering the baptism date followed by the birth date errors in the second date are not highlighted.    

![Screenshot](https://www.freereg.org.uk)

**Comment by PatReynolds** [comment]
@PatReynolds to check the contact for the image.

**Comment by PatReynolds** [comment]
@edickens to ask Jackie for the file / more details

**Comment by DeniseColbert** [comment]
@edickens to ask Jackie for more info

**Comment by SteveBiggs** [comment]
Jackie is referring to WinREG not flagging the birthdate error so nothing to do with the website and nothing we can do about it so this can be closed.

**Comment by edickens** [comment]
Can be closed.
