### ISSUE TITLE
193353137 Not receiving contacts (Joanne)

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeUKRegProductIssues#1417]
Issue reported by **ManCity** at 2021-02-15 21:12:17 UTC
Time: 2021-02-15T21:06:56+00:00
Session ID: 1891eb8adafe0ad4cd7b508bf3f24c5e
Problem Page URL: [/manage_resources/new?locale=en](/manage_resources/new?locale=en)
Previous Page URL: [https://www.freereg.org.uk/cms/refinery/login](https://www.freereg.org.uk/cms/refinery/login)
Reported Issue:
Receiving volunteering contacts are by email but they don't appear under contacts on the home page, can only reply by email, due to that there won't be an copy of my reply online.    

![Screenshot](https://www.freereg.org.uk)

**Comment by SteveBiggs** [comment]
Details from Jo, our Volunteer Coordinator:

A while ago when I went through contacts the heading had changed to 'data problem' - it's still 'data problem' now.   Just logged on and the below is what's showing when I click on contacts.
![image](https://user-images.githubusercontent.com/25303607/108127492-35d40680-70a3-11eb-8593-6ad3157246a5.png)
In my emails I've a contact for Neill Reed asking about how many hours - as you can clearly see that is definitely not showing so I can't reply to him online

**Comment by PatReynolds** [comment]
@Vino-S to take a look

**Comment by Vino-S** [comment]
ready for testing in test3

**Comment by SteveBiggs** [comment]
I raised a Contact Us Volunteering question on test3 and it looks like the email only went to Commscoord:
![image](https://user-images.githubusercontent.com/25303607/126532441-73bbd023-1f20-42a1-9bc8-b1417302ed96.png)

We'll see if it appears in Jo's Contacts list on test3 and if she gets the email notification.

**Comment by SteveBiggs** [comment]
Jo has confirmed that she did not get an email nor can she see the Volunteering Question in her Contacts list on test3.

Whatever @Vino-S did it has not fixed the problem.

**Comment by Vino-S** [comment]
Hi @SteveBiggs 
I noticed Jo did not have the Volunteer Coordinator role in test3. Assigned her the role. She should now be able to see the Volunteer Questions in her Contacts list.
This might be the reason she did not receive the email.

**Comment by SteveBiggs** [comment]
Thanks @Vino-S, I will test again then.

**Comment by SteveBiggs** [comment]
@Vino-S , Jo reports that she does now receive the Contact emails and can see them in her list on test3 so it looks good. Thanks.
