### ISSUE TITLE
193939610 "Unspecified" register type - or not  (Michael)

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeUKRegProductIssues#1419]
Issue reported by **LINCC** at 2021-02-22 16:06:50 UTC
Time: 2021-02-22T15:44:20+00:00
Session ID: e5ff0020e3510b38ca97b28f4d1a0fc2
Problem Page URL: [/search_records/58183976e93790ec8bf2d272/jane-maria-kitchener-baptism-hertfordshire-aldbury-1827-07-01?locale=en](/search_records/58183976e93790ec8bf2d272/jane-maria-kitchener-baptism-hertfordshire-aldbury-1827-07-01?locale=en)
Previous Page URL: [https://www.freereg.org.uk/search_queries/6033d009f493fd79dc107b55?locale=en](https://www.freereg.org.uk/search_queries/6033d009f493fd79dc107b55?locale=en)
Reported Issue:
There are two entries in Aldbury, Herts for offspring of Elisha Kitchener. One is Eliza Jane Kitchener baptised 1 Jul 1827 with register entry number 304, file line number 303, line id eastwood4346.HRTALDBA.CSV.303 and NO register type. The other is Jane Maria Kitchener baptised 1 jul 1827 with register entry number 303, file line number 302, line id eastwood4346.HRTALDBA.CSV.302 and "Unspecified" register type. They both have the same parents (Elisha and Lydia), baptised on the same day and, by all accounts, contained in the same file. So why the different register types?

I have also noted that navigating around these three people using different sequences, sometimes the register type of "Unspecified" is displayed and sometimes not. This seems to happen with both the "back" button of the browser AND the "Back to Results" button from FreeREG. Any idea why this is.

Note that I am both a transcriber for FreeREG AND CC for BKM so I am well aware of the vagaries of the FreeREG system.
https://www.freereg.org.uk/uploads/feedback/screenshot/6033d69af493fd79ebfe098a/Capture.JPG    

![Screenshot](https://www.freereg.org.uk)

**Comment by PatReynolds** [comment]
@SteveBiggs to get back to Michael.

**Comment by SteveBiggs** [comment]
I have replied to Michael.

**Comment by DeniseColbert** [comment]
Known issue in backlog: closing
