### ISSUE TITLE
Link to How to Volunteer under About Us has problems (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#142]
Issue reported by **REGManager** at 2015-01-06 12:23:45 UTC
Time: 2015-01-06T12:18:46+00:00
Session ID: c89de9b7fcd8d3e791cf370963e33c8a
Problem Page URL: [/](/)
Previous Page URL: [http://test2.freereg.org.uk/manage_resources/new](http://test2.freereg.org.uk/manage_resources/new)
Reported Issue:
When we go live someone will try About Us and How to Volunteer.  The latter link says that you need to have logged in to access the How to Volunteer page.  This should be viewable by all.
EricD
PS.  It has been mentioned before, but having this Problem Report in a new Tab would help a lot as I can then look at what I am talking about.    

![Screenshot](http://test2.freereg.org.uk/tmp/carrierwave/1420547025-66778-5826/Capture1.JPG)

**Comment by Captainkirkdawson** [comment]
My error had mistyped the link.

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1
