### ISSUE TITLE
195075656 Website Problem (Sarah Green)

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeUKRegProductIssues#1421]
Issue reported by **Sarah Green** at 2021-03-07 19:40:56 UTC
Time: 2021-03-07T19:40:47+00:00
Session ID: 
Problem Page URL: []()
Previous Page URL: [https://www.freereg.org.uk/contacts/new](https://www.freereg.org.uk/contacts/new)
Reported Issue:
It looks like this link is broken on your site: https://www.freereg.org.uk/system/images/w1siziisijiwmjavmdcvmt...nil1d/donate.png?sha=675000132025c920

I thought you would like to know :).  Silly mistakes can ruin your site's credibility.  I've used a tool called linkSniff.com in the past to keep mistakes off of my website.

-Sarah

**Comment by DeniseColbert** [comment]
Used a free service: no broken links. This smells like it could be a "use our paid service to find the broken link that doesn't exist" thing. @Captainkirkdawson does the URL reported as broken fire any of your synapses?

**Comment by Captainkirkdawson** [comment]
Its someone trying to scam us.
