### ISSUE TITLE
198076164 Researcher "search" query (Michael)

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeUKRegProductIssues#1425]
Issue reported by **LINCC** at 2021-04-11 13:09:24 UTC
Time: 2021-04-11T12:59:56+00:00
Session ID: 4f096aa584c54bdfc5bf24f7a61d9e3d
Problem Page URL: [/search_records/5a998d37f493fd586e5170a1/mary-neale-richard-coote-marriage-sussex-sidlesham-1838-07-23?locale=en](/search_records/5a998d37f493fd586e5170a1/mary-neale-richard-coote-marriage-sussex-sidlesham-1838-07-23?locale=en)
Previous Page URL: [https://www.freereg.org.uk/search_queries/6072f283f493fd7be7ecde31?locale=en](https://www.freereg.org.uk/search_queries/6072f283f493fd7be7ecde31?locale=en)
Reported Issue:
Assume the results of a search that returns more than a page-worth of results.

Now look at a result on the second (third etc.) page. This works fine.

Having looked at that result, go back to the "results of the search" and you will find that you are back at the top of the list. Every time. Then you have to scroll down to find the entry that you just looked at!

Why can't this return to the page containing the entry just examined? Very frustrating!    

![Screenshot](https://www.freereg.org.uk)

**Comment by PatReynolds** [comment]
It is meant to go back to the result, so needs a fix.

**Comment by Captainkirkdawson** [comment]
Fixed in production
