### ISSUE TITLE
199091104 Chapman codes MIL and RNS (Eric D)

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeUKRegProductIssues#1426]
Issue reported by **REGManager** at 2021-04-23 07:05:04 UTC
Time: 2021-04-23T07:01:10+00:00
Session ID: e88c3877787289344d4d791d2d1512fb
Problem Page URL: [/search_queries/new?locale=en](/search_queries/new?locale=en)
Previous Page URL: [https://www.freereg.org.uk/counties](https://www.freereg.org.uk/counties)
Reported Issue:
These two codes are in the Search list of counties, and also in Records.  But they do not appear in the list of County Coordinators or Counties to transcribe.
We are transcribing BU at sea but they are in the county OTH.    

![Screenshot](https://www.freereg.org.uk)

Decision to remove these from FreeREG.

E0 U1 S2 C7:P10

**Comment by Captainkirkdawson** [comment]
Fixed on test3
