### ISSUE TITLE
200068818 All Active Feedback Messages have Disappeared (Stephen)

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeUKRegProductIssues#1427]
Issue reported by **SBManager** at 2021-05-04 14:40:18 UTC
Time: 2021-05-04T14:37:54+00:00
Session ID: 4cbfecd7c7aeffc7f553ee18aa7776e6
Problem Page URL: [/feedbacks](/feedbacks)
Previous Page URL: [https://www.freereg.org.uk/manage_resources/new?locale=en](https://www.freereg.org.uk/manage_resources/new?locale=en)
Reported Issue:
    

![Screenshot](https://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Nothing is missing. They are in archived
