### ISSUE TITLE
200076295 In Records, Place name error (Eric D)

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeUKRegProductIssues#1428]
Issue reported by **REGManager** at 2021-05-04 16:44:55 UTC
Time: 2021-05-04T16:41:20+00:00
Session ID: cf4bfc5601dcfabf93c146c940228a08
Problem Page URL: [/freereg_contents/53cbf5beeca9eb03a6000b50?locale=en](/freereg_contents/53cbf5beeca9eb03a6000b50?locale=en)
Previous Page URL: [https://www.freereg.org.uk/freereg_contents?locale=en](https://www.freereg.org.uk/freereg_contents?locale=en)
Reported Issue:
Select Records, BKM, Akeley and the place name is wrong.  See attached.  Could it be because there is no Register Type?
https://www.freereg.org.uk/uploads/feedback/screenshot/60917a07f493fd0f9910a1e8/Capture.JPG    

![Screenshot](https://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Fixed on test3

**Comment by edickens** [comment]
Yes.   Fixed.  Deploy.  TY  Eric
