### ISSUE TITLE
201095489 Broken Register Type link SSX Catsfield (Eric D)

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeUKRegProductIssues#1429]
Issue reported by **REGManager** at 2021-05-16 11:51:29 UTC
Time: 2021-05-16T11:50:20+00:00
Session ID: c6d8d9d720b04fe55765b352333a3f7a
Problem Page URL: [/freereg_contents/53cbf613eca9eb03a6009d35?locale=en](/freereg_contents/53cbf613eca9eb03a6009d35?locale=en)
Previous Page URL: [https://www.freereg.org.uk/freereg_contents/53cbf613eca9eb03a6009d35?locale=en](https://www.freereg.org.uk/freereg_contents/53cbf613eca9eb03a6009d35?locale=en)
Reported Issue:
See attached
https://www.freereg.org.uk/uploads/feedback/screenshot/60a10741f493fd752ab18fea/Capture.JPG    

![Screenshot](https://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Fixed and deployed
