### ISSUE TITLE
Additional Church Field - Enhancement (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#143]
Issue reported by **REGManager** at 2015-01-06 14:51:50 UTC
Time: 2015-01-06T14:44:27+00:00
Session ID: 3bfc791fa58f6dd10872d6c90d1c5d97
Problem Page URL: [/churches/5407f117eca9eb1ee04aab76](/churches/5407f117eca9eb1ee04aab76)
Previous Page URL: [http://test2.freereg.org.uk/places?page=2](http://test2.freereg.org.uk/places?page=2)
Reported Issue:
We  have just had an offer of transcriptions from a Church in WOR, which adds to our set.  But they have a website http://www.bewdley.actinet.net/allsaints/main.htm and it would be nice to have a website link field so as to be able to promote the Church to encourage Genealogy Tourism.  We may get more cooperation from the Churches if we do this.
EricD    

![Screenshot](http://test2.freereg.org.uk/tmp/carrierwave/1420555910-40135-4580/Capture.JPG)

**Comment by Sherlock21** [comment]
That would be a fine idea. just like the existing one we have from the Place name to Genuki to show the place location. I go with that idea.

But it  would need to be at the Place/ Church name level.
and no limits on how many such links per Placename.

**Comment by edickens** [comment]
```
I think we need just one website
  address per Church.  Not sure that we need a website address for a
  Place.  That can be obtained through GENUKI.
  EricD
  _____________________________________
```

Eric J Dickens
FreeREG Chairman
      On 06/01/2015 15:33, Sherlock21 wrote:

```
  That would be a fine idea. just like the existing one we have
    from the Place name to Genuki to show the place location. I go
    with that idea.
  But it would need to be at the Place/ Church name level.
    and no limits on how many such links per Placename.
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by Sherlock21** [comment]
I wasn't suggesting we needed an additional website per place name - rather summarising the total so that the existing Place name link to Genuki did not get used instead of your new proposal.

**Comment by Captainkirkdawson** [comment]
Implemented
