### ISSUE TITLE
201164973 Footer statistics (Eric D)

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeUKRegProductIssues#1430]
Issue reported by **REGManager** at 2021-05-17 07:09:33 UTC
Time: 2021-05-17T07:08:32+00:00
Session ID: f1785e4ba4283f6f1d534a50726a860f
Problem Page URL: [/manage_resources/new?locale=en](/manage_resources/new?locale=en)
Previous Page URL: [https://www.freereg.org.uk/cms/refinery/login](https://www.freereg.org.uk/cms/refinery/login)
Reported Issue:
The statistics have disappeared from the footer.    

![Screenshot](https://www.freereg.org.uk)

**Comment by edickens** [comment]
Still no statisitcs in the footer.  I look at these daily to make sure that transcribing is still being uploaded.

Also, there are no advertisements in the box in the top right of the home page.

**Comment by PatReynolds** [comment]
I am seeing the statistics, and the advert.

**Comment by edickens** [comment]
Here is the FreeREG footer...

![Capture.JPG](https://images.zenhubusercontent.com/5cb4c5e2cccdd751e9e85870/d7183034-bb34-4a52-b6ea-b73ea5e27274)

and the Advert...

![Capture1.JPG](https://images.zenhubusercontent.com/5cb4c5e2cccdd751e9e85870/4cd5bd35-d02f-49f0-b202-268934cdcf67)

Eric

**Comment by Captainkirkdawson** [comment]
I had turned the stats computation off during the move and forgotten to turn them on again. Have done so now. Stats should reappear tomorrow.
