### ISSUE TITLE
201820235 Data Question (Lisa Dickerson )

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeUKRegProductIssues#1431]
Issue reported by **Lisa Dickerson ** at 2021-05-24 21:10:35 UTC
Time: 2021-05-24T21:06:01+00:00
Session ID: 
Problem Page URL: []()
Previous Page URL: [https://www.freereg.org.uk/contacts/new](https://www.freereg.org.uk/contacts/new)
Reported Issue:
Trouble using wild card in search.
See attached screen capture of my search.

What am I doing wrong?
Goal was to find possible children with Misspelled surname of Dickerson and mothers first name Mary. 
https://www13.freereg.org.uk/uploads/contact/screenshot/60ac164bf493fd78289e7098/FreeReg-WildCard.PNG

**Comment by SteveBiggs** [comment]
It's not clear why this search is failing as it appears to follow the rules for using a wildcard.

**Comment by ghost** [comment]
Unfortunately the screenshot has been removed and there is no information on which an investigation can be conducted

**Comment by PatReynolds** [comment]
At first I thought her  problem is that she was not using www.freereg.org.uk, but www13.freereg.org.uk, but it's on the main website, too.

Search was 
![image](https://user-images.githubusercontent.com/6338822/119789650-28f95700-becb-11eb-98bf-0b8f142c1b1a.png)
Surname DI* first name Mary, 1800 to 1900, Bedfordshire, Apsley Guise, baptisms, family members ticked.

Searching for Al* John 1800-1810, North Yorkshire, Arkengarthdale, baptisms, family members ticked gives same error (searching with Alcock gives 4 results).

**Comment by SteveBiggs** [comment]
Actually this is the search Lisa made:

![image](https://user-images.githubusercontent.com/25303607/119796771-901a0a00-bed1-11eb-8497-c64d3cfe833a.png)

**Comment by ghost** [comment]
@SteveBiggs Before I start hitting the logs can you confirm the day of the search to have been 2021-05-24

**Comment by ghost** [comment]
@SteveBiggs ignore my request

**Comment by ghost** [comment]
@SteveBiggs caused by missing index; looking at it later

**Comment by Captainkirkdawson** [comment]
Actually index was there; I had reversed first and last name in the code index hint!

**Comment by Captainkirkdawson** [comment]
Deployed to production

**Comment by SteveBiggs** [comment]
Tested in production and works fine now. Thanks Kirk.
