### ISSUE TITLE
202534463 Totals for each type of record (Barrie)

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeUKRegProductIssues#1432]
Issue reported by **brobinson43** at 2021-06-02 03:34:23 UTC
Time: 2021-06-02T03:32:42+00:00
Session ID: 4a63e743ceb58291a12b05aac9a67d8a
Problem Page URL: [/freereg_contents/6033a41ff493fd79dc0ca3d7/show_register?locale=en](/freereg_contents/6033a41ff493fd79dc0ca3d7/show_register?locale=en)
Previous Page URL: [https://www.freereg.org.uk/freereg_contents/53cd498ceca9ebee4f00a2a8?locale=en](https://www.freereg.org.uk/freereg_contents/53cd498ceca9ebee4f00a2a8?locale=en)
Reported Issue:
This is not a problem, but it would be nice under the decadal analysis to have a total for Batisms, for Marriages and for Burials.    

![Screenshot](https://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Quite a substantial amount of coding and checking is required to add a total by record type at the bottom of each column in the register, church and place displays because of the way that the tables are constructed from the file up to the register then to the church and finally to the place. Since these tables  have been around for several years and this is the first suggestion  for the addition and even that puts it at a nice to have I wonder about the value of it in view of the cost and possible breaking of displays.. Perhaps it would be a useful project for a new developer wanting to extend their experience

**Comment by edickens** [comment]
What about just on the screen that has displayed the results?

https://www.freereg.org.uk/freereg_contents/6033a41ff493fd79dc0ca3d7/show_register?locale=en

**Comment by Captainkirkdawson** [comment]
You totally missed the point. It is not a display issue per see. The total number is not in the data_range hash for any of the levels. We have to go back to the code that does the heavy lifting to create the hash to add more information

**Comment by edickens** [comment]
OK.  another approach.

Add a report that can be run on demand under "Statistics" Action.  It will scan all entries and come up with the 9 totals.  It will probably be best run in background, so when a request has been made for this report, say that an email with the results will be sent to the logged in person and close the tab.

The reason for these statistics has come up in a message that i received today where I was asked how we were doing with the pre-1837.  I want to save these statistics then compare them every four weeks in my report so as to check progress and put pressure on SCs to do the pre-1837.  So I would ask for this report once every four weeks.  I assume that this coding is just a rake task that is embedded in Statistics and does not affect any other coding.

If this is acceptable, it would be nice, as well as all counties, to also have the option to select one county and get the totals for that county.

**Comment by edickens** [comment]
PS.  I realise now that this is not really what Barrie is asking for, but may be of some use to him.  It is what I have asked for in #2439.  There is also another request in #1018.
