### ISSUE TITLE
205148818 Cannot replace an existing file ((Rosemary) Sue)

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeUKRegProductIssues#1433]
Issue reported by **sueme** at 2021-07-02 09:46:58 UTC
Time: 2021-07-02T09:44:21+00:00
Session ID: 5e2f5a57cbf54650a2752c18600e39b1
Problem Page URL: [/csvfiles/60daf0e4f493fd76b991f3fb/edit?locale=en](/csvfiles/60daf0e4f493fd76b991f3fb/edit?locale=en)
Previous Page URL: [https://www.freereg.org.uk/csvfiles/60daf0e4f493fd76b991f3fb/edit?locale=en](https://www.freereg.org.uk/csvfiles/60daf0e4f493fd76b991f3fb/edit?locale=en)
Reported Issue:
Am attempting to update my file NFKCASBU6.  Am just getting a message "You are attempting to replace a file you do not have. Likely you are a coordinator replacing a file belonging to someone else. You must replace into their userid."  I do have the file as it is listed on my batch. 
Sue Ireland    

![Screenshot](https://www.freereg.org.uk)

**Comment by SteveBiggs** [comment]
This problem has been reported by a few people over the last day or so. Has a change been made that may be the cause?

**Comment by Sherlock21** [comment]
I made a change to one entry in an already uploaded file of my own, and Replaced the online one in the usual way.

The Reload worked correctly.

Eric B

On 2 Jul 2021, at 12:00, Stephen Biggs ***@***.***> wrote:


This problem has been reported by a few people over the last day or so. Has a change been made that may be the cause?

**Comment by SteveBiggs** [comment]
Thanks Eric. Could you try uploading a new file please?

**Comment by Sherlock21** [comment]
Hi, Steve.
as it happened I had a new baptisms file with a few records in it for DEV/ Branscombe

so I tided that up and tried to upload it.
after I has put in the file name to the appropriate box for uploading, FR would not respond to me clicking to upload.

nor was these a message on the same screen saying it had gone off for processing as it usually does.

I have put in a Report no 205183355 for this event.

going off line now for the evening.
EB


On 2 Jul 2021, at 17:33, Stephen Biggs ***@***.***> wrote:


Thanks Eric. Could you try uploading a new file please?
