### ISSUE TITLE
205159027 A search on all register types (BA, MA, BU)does not respect the Embago rules (Eric D)

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeUKRegProductIssues#1434]
Issue reported by **REGManager** at 2021-07-02 12:37:07 UTC
Time: 2021-07-02T12:34:31+00:00
Session ID: 6c4ab25c2f2043c97c0d8029a1f6cdd2
Problem Page URL: [/search_queries/60df07d6f493fd42a7650fe8?locale=en](/search_queries/60df07d6f493fd42a7650fe8?locale=en)
Previous Page URL: [https://www.freereg.org.uk/search_queries/new?locale=en](https://www.freereg.org.uk/search_queries/new?locale=en)
Reported Issue:
See DEV Thelbridge Hitchcock
There are quite a few entries.    

![Screenshot](https://www.freereg.org.uk)

E5 U10 S9 C6 : P 30

**Comment by PatReynolds** [comment]
Should be done by a nightly rake task.

Does NOT work on updated records.

**Comment by PatReynolds** [comment]
Button to re-run embago, too. @Vino-S to write up for help.

**Comment by PatReynolds** [comment]
@Vino-S has written help. @edickens and @AlOneill could you check, please?

**Comment by edickens** [comment]
I can't remember where there is an Embargo rule in Test2.  There is no point in setting one up otherwise this button is not needed.  It is just a reprocess button.  Steve do you know?  If not, I suggest that this is made Live and I will get CCs to check.  But should this be run for all Embargoed entries?  There is a lot to find.  Or just when someone reports a problem?

**Comment by PatReynolds** [comment]
Help to be checked, and updated if needed.

Transcriber to check if there is an embarbo rule (or just press the button anyway).

**Comment by PatReynolds** [comment]
Help: To review at next documenation meeting, also @edickens to look 

Embago button: @edickens to test on test3

**Comment by DeniseColbert** [comment]
@Vino-S Could you let us know where to find your addition to the Help please?

**Comment by edickens** [comment]
Embargo processing button works, but I cannot test all combinations.  This does not affect other operations so can be made operational.
