### ISSUE TITLE
206981244 Burial Age can be entered as hours (Stephen)

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeUKRegProductIssues#1438]
Issue reported by **SBManager** at 2021-07-23 14:47:24 UTC
Time: 2021-07-23T14:44:59+00:00
Session ID: d138cad5803c6f8a79242e9aa2dfab0a
Problem Page URL: [/cms/information-for-transcribers/entering-data-from-registers](/cms/information-for-transcribers/entering-data-from-registers)
Previous Page URL: [https://www.freereg.org.uk/cms/information-for-transcribers](https://www.freereg.org.uk/cms/information-for-transcribers)
Reported Issue:
A burial age of e.g. 2 hours can be entered as "2h". This should be added to the help section.    

![Screenshot](https://www.freereg.org.uk)

**Comment by AlOneill** [comment]
Apologies — I thought this had been dealt with months ago.

Age at death updated on both 'Entering data from registers' and 'Extended burial fields'.

**Comment by SteveBiggs** [comment]
Thanks @AlOneill - I've just remembered that the 'Extended baptism fields' include Age so that should be updated too.

**Comment by AlOneill** [comment]
@SteveBiggs Well remembered! Age field updated on 'Extended baptism fields'.

**Comment by SteveBiggs** [comment]
Looks good in test3. Just need to move across to the production site.
