### ISSUE TITLE
Adding to Church Notes - Timed out (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#144]
Issue reported by **REGManager** at 2015-01-06 14:57:06 UTC
Time: 2015-01-06T14:52:00+00:00
Session ID: 3bfc791fa58f6dd10872d6c90d1c5d97
Problem Page URL: [/churches/5407f117eca9eb1ee04aab76/edit](/churches/5407f117eca9eb1ee04aab76/edit)
Previous Page URL: [http://test2.freereg.org.uk/churches/5407f117eca9eb1ee04aab76](http://test2.freereg.org.uk/churches/5407f117eca9eb1ee04aab76)
Reported Issue:
I was just adding to the details for a Church and processing took ages and timed out.  Is the server trying to amend the Church name in all the records, when it has not been changed?  If so, needs a test to only update records if the Church name has changed.
EricD    

![Screenshot](http://test2.freereg.org.uk/tmp/carrierwave/1420556226-40135-1771/Capture.JPG)

**Comment by Captainkirkdawson** [comment]
Issue definitely caused by the system updating every entry and search record because the church had changed

**Comment by edickens** [comment]
```
Hi Kirk,
  But I didn't change the Church, just added a note.  Should there
  be a check to only update the records if the Church dedication
  changes?
  EricD
  _____________________________________
```

Eric J Dickens
FreeREG Chairman
      On 06/01/2015 21:52, Kirk Dawson wrote:

```
  Issue definitely caused by the system updating every entry and
    search record because the church had changed
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by Captainkirkdawson** [comment]
Was only supposed to do that if there was a name or location change!
neither of those conditions apply so there has to be a logic error.

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Captainkirkdawson** [comment]
Code has been rewritten to ensure that we only update the indexes when required
