### ISSUE TITLE
207910869 Website Problem (Karen Allen)

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeUKRegProductIssues#1441]
Issue reported by **Karen Allen** at 2021-08-03 09:01:09 UTC
Time: 2021-08-03T09:01:03+00:00
Session ID: 
Problem Page URL: []()
Previous Page URL: [https://www.freereg.org.uk/contacts/new](https://www.freereg.org.uk/contacts/new)
Reported Issue:
Greetings,

I see you have a broken link on your website:  https://www.freereg.org.uk/system/images/w1siziisijiwmjavmdcvmt...nil1d/donate.png?sha=675000132025c920

In the past I've used a service like DeadLinkScanner.com to help keep broken links off of my websites.

-Karen

**Comment by PatReynolds** [comment]
Link exists (and is broken) but is not on our live website, so closing (issue raised by someone looking at code not a user).
