### ISSUE TITLE
Inconsistent description in the transcriber's Help for Age field

### ISSUE THREAD

**Issue by SteveBiggs** [FreeUKGen/FreeUKRegProductIssues#1443]
The flexible csv description of Age in marriages is different to the original non-flex description.

The orginal should be copied into the flex Help to be consistent.

**Comment by PatReynolds** [comment]
Refinery is not letting me copy and paste the current llex html into a draft page for editing.  @AlOneill or @DeniseColbert doe it work for you?   

I can then add the missing paragraph!

**Comment by AlOneill** [comment]
@PatReynolds I'll give it a shot …

**Comment by AlOneill** [comment]
Copy and paste worked OK. Will proceed with adding the missing paragraph.

**Comment by AlOneill** [comment]
Have amended description of Groom's age and Bride's age in [DRAFT extended marriage fields](https://test3.freereg.org.uk/cms/information-for-transcribers/flexible-csv-format/extended-marriage-fields/draft-extended-marriage-fields) on t3.

**Comment by SteveBiggs** [comment]
Is the text case sensitive? Both 'Minor' and 'minor' are referenced.

**Comment by AlOneill** [comment]
@SteveBiggs I would be surprised if case mattered, but I'll defer to wiser heads …

**Comment by PatReynolds** [comment]
@SteveBiggs can you try entering both "Minor" and "minor" into the age at marriage field to see if this is case sensitive, or not?  Thanks!

**Comment by SteveBiggs** [comment]
I tried Minor, minor & MINOR and all worked so can confirm it is not case sensitive.

**Comment by AlOneill** [comment]
@Irene-ene Please do not close documentation issues before I indicate that they are sync-ready — I lose track of the issue if it is closed before the work is completed. Thank you!

**Comment by AlOneill** [comment]
Extended marriage fields is now sync-ready.

**Comment by Captainkirkdawson** [comment]
production refinery updated. Leave it you @AlOneill to confirm and close

**Comment by AlOneill** [comment]
Confirmed, so closing
