### ISSUE TITLE
211027996 When you click on list of places, for those with alternate place names, you get error screen (was UNable to create new church (Team))

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeUKRegProductIssues#1446]
Issue reported by **alycymru** at 2021-09-08 10:53:16 UTC
Time: 2021-09-08T10:52:02+00:00
Session ID: 6656171afc1a84c29b1a028319bfc184
Problem Page URL: [/manage_counties/place_range?params=K-L](/manage_counties/place_range?params=K-L)
Previous Page URL: [https://www.freereg.org.uk/manage_counties/selection?option=Work%20with%20All%20Places](https://www.freereg.org.uk/manage_counties/selection?option=Work%20with%20All%20Places)
Reported Issue:
Hi I am unable to create a new church in MON Llantilo Pertholey. When I click on the place information button, it gives me an error message that says We're sorry, but something went wrong with processing your request. A report has been produced and sent to the webmaster. Please return to your prior activity but try to avoid doing the exact same action again.

Can someone please help me gain access?

E0 U6 S8 C6: P20

Thanks 
Sandra    

![Screenshot](https://www.freereg.org.uk)

**Comment by SteveBiggs** [comment]
It would seem that for some counties (not all) when a Place is selected in the place Range Selection, the red error screen is returned. E.g. as well as MON, some in BRE such as Maesmynys:
![image](https://user-images.githubusercontent.com/25303607/132509532-fa1fcba0-249f-4dae-bab7-704e2c4495c1.png)

**Comment by Captainkirkdawson** [comment]
https://errbit.freeukgen.org.uk/apps/56297e8be93790333a000009/problems/61389531e93790ade2dfe6c6

**Comment by SteveBiggs** [comment]
@Captainkirkdawson I don't have access to errbit. Could you explain what the error is please?

**Comment by Captainkirkdawson** [comment]
@SteveBiggs you really do not need to know the details; I put the link there for Vino or myself. There is a coding error dealing with the look up of alternate place names

**Comment by SteveBiggs** [comment]
OK thanks.

**Comment by Captainkirkdawson** [comment]
@SteveBiggs I have deployed and tested a fix for this on test3. Can you also test. Using the same place as in the original problem. Test3 has that place with an alternate_name.

**Comment by SteveBiggs** [comment]
Seems to work fine now.

**Comment by Sherlock21** [comment]
And fine for me too in T2.

**Comment by edickens** [comment]
This works.  Can be closed.
