### ISSUE TITLE
214472136 Incomplete registrations (Eric D)

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeUKRegProductIssues#1448]
Issue reported by **REGManager** at 2021-10-18 07:35:36 UTC
Time: 2021-10-18T07:31:26+00:00
Session ID: 561c3a84a8bae1fbfd20dd76e247db81
Problem Page URL: [/userid_details/54735701e93790259c0005f5?locale=en&page_name=incomplete_registrations](/userid_details/54735701e93790259c0005f5?locale=en&page_name=incomplete_registrations)
Previous Page URL: [https://www.freereg.org.uk/userid_details/incomplete_registrations](https://www.freereg.org.uk/userid_details/incomplete_registrations)
Reported Issue:
We have quite a long list of incomplete registrations, but some are SC controlled UserIDs with batches.  I think these should be completed.  Shall I warn SCs then send out Password updates?
Also, shall I destroy those without batches?
My understanding is that you cannot log in until the registration is completed, but is this true?
Eric    

![Screenshot](https://www.freereg.org.uk)

**Comment by edickens** [comment]
I get this information from the UserID "Incomplete Registrations" action.
Answers to my questions please.

**Comment by Captainkirkdawson** [comment]
Technically they can log in if they know the temp password; but this is extremely unlikely so to all intents you can assume they have not.
The other questions are policy

**Comment by PatReynolds** [comment]
@edickens to delete registration of those without batches.

**Comment by edickens** [comment]
I've started to look at these.  Some are Coordinator controlled with batches so I have asked for the registration to be completed.  Some are in the Syndicate "To be destroyed" where there is a "Destroy" button.  They have no files, so can I destroy them?  If I set the ones that are in Syndicates to "To be destroyed" they will still stay in the list.  Or can I then Destroiy them too?  Advice please before I do any more.

**Comment by Captainkirkdawson** [comment]
IMHO I would destroy

**Comment by edickens** [comment]
TY.   I just wanted to be sure that it would not leave any broken links.

**Comment by edickens** [comment]
Thinking again about those incomplkete registrations with batches.  If they are Coordinator controlled, it is perhaps a good thing to leave htem like that, or even adopt it as a standard.  It is easy for the SC to set up a UserID and not complete the registration as they can then use the UserID for holding batches, but nobody else can access them.
