### ISSUE TITLE
Scrolling and tablets (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#145]
Issue reported by **REGManager** at 2015-01-09 17:43:19 UTC
Time: 2015-01-09T17:41:59+00:00
Session ID: 2e7b3f75475d7fe202d218ed620b8e06
Problem Page URL: [/search_queries/new](/search_queries/new)
Previous Page URL: [http://test2.freereg.org.uk/manage_resources/new](http://test2.freereg.org.uk/manage_resources/new)
Reported Issue:
Just got the attached from a researcher.  Scrolling is a concern and tablets are used.  So we are doing the right thing.
EricD    

![Screenshot](http://test2.freereg.org.uk/tmp/carrierwave/1420825399-52274-6524/Capture.JPG)

**Comment by Captainkirkdawson** [comment]
Being handled elsewhere
