### ISSUE TITLE
214923226 Reply to a No results search if there is a Gap (Eric D)

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeUKRegProductIssues#1450]
Issue reported by **REGManager** at 2021-10-23 12:53:46 UTC
Time: 2021-10-23T12:49:10+00:00
Session ID: 1bfd2e5ad432dda574375e93b556da13
Problem Page URL: [/search_queries/617404c5f493fda6f42c79d5?locale=en](/search_queries/617404c5f493fda6f42c79d5?locale=en)
Previous Page URL: [https://www.freereg.org.uk/search_queries/new?locale=en](https://www.freereg.org.uk/search_queries/new?locale=en)
Reported Issue:
If a search is made quoting a year range and a County and a Place, and No Results are found, check if there is a GAP matching this search and if so, report it on the Result screen.  The text does say that there could be a Gap, but the researcher needs to then go to Records and look there for the Gap information.  It is more user friendly if this information comes up just after the search.    

![Screenshot](https://www.freereg.org.uk)

**Comment by Irene-ene** [comment]
Covered by #2409
