### ISSUE TITLE
216994789 Manage Image Server fails (Eric D)

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeUKRegProductIssues#1453]
Issue reported by **REGManager** at 2021-11-16 12:19:49 UTC
Time: 2021-11-16T12:14:38+00:00
Session ID: da239bcd4e17fd2399caf4ace5d9994e
Problem Page URL: [/manage_counties/select_action?county=Devon&locale=en](/manage_counties/select_action?county=Devon&locale=en)
Previous Page URL: [https://www.freereg.org.uk/image_server_groups/617582b8f493fdf40c2a4638/index?locale=en](https://www.freereg.org.uk/image_server_groups/617582b8f493fdf40c2a4638/index?locale=en)
Reported Issue:
"Something went wrong" when I try to look at DEV Bampton.  Unfortunately since moving to my new computer I can't use PuTTY because I can't remember my password so can't have a look at what has been uploaded.
DEV is getting "Already there" but can't find Bampton_PR19_BU04_
Eric    

![Screenshot](https://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
@edickens Unable to detect any problems
![devon](https://user-images.githubusercontent.com/2874694/143148801-84a1b2d4-a999-4fdb-a12a-cf6abc87305d.png)

**Comment by Captainkirkdawson** [comment]
I cannot duplicate the problem when accessing this through the Manage Images action in a county. But it fails through the Manage Image Server action

**Comment by edickens** [comment]
Another example:-
AYR, Galton, PR.  has images under Image Server, but does not show any images under Manage Image Server/Converted 2.  This may be because they are .tif images.

**Comment by Captainkirkdawson** [comment]
@edickens have fixed the crash problem but the server times out trying to display the list of files because there are 1400 files in there

**Comment by edickens** [comment]
I think it is because it is trying to create thumbnails.  Would it be easy to create another button to "List image filenames" rather than "Show images".
We use this facility to compare the files with the Image Groups so I only really need the filenames.  Showing the images would be useful when searching for something, but the filenames are what I need now.
Thanks
Eric

**Comment by Captainkirkdawson** [comment]
@edickens added a limit of 750 on the calculation of thumbnails. DEV Bampton now displays in Manage Image Server (without Thumbnails) Galston PR in AYR shows list of images and yes most are tifs. There are no images in Ayr-Converted2 PR in AYR nor for Ayr-Converted3 PR in AYR

**Comment by PatReynolds** [comment]
@edickens to test

**Comment by edickens** [comment]
Works OK now in production.  This can be closed.
