### ISSUE TITLE
218308692 Not possible to use Ladyday as start/end dates of years (Michael)

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeUKRegProductIssues#1455]
Issue reported by **LINCC** at 2021-12-01 17:18:12 UTC
Time: 2021-12-01T17:05:09+00:00
Session ID: f9300d2541102b7c582fe697e0015c91
Problem Page URL: [/gaps/new?freereg1_csv_file=5463b3cae9379010fc084938&locale=en&register=540a04aeeca9ebd28ed1da59](/gaps/new?freereg1_csv_file=5463b3cae9379010fc084938&locale=en&register=540a04aeeca9ebd28ed1da59)
Previous Page URL: [https://www.freereg.org.uk/freereg1_csv_files/5463b3cae9379010fc084938?locale=en](https://www.freereg.org.uk/freereg1_csv_files/5463b3cae9379010fc084938?locale=en)
Reported Issue:
I have a register where the vicar has reported something like "Marriages Ladyday 1676 to Ladyday 1677 None". How can this period be converted into a Gap? It actually covers two part-years. There may be valid entries in 1675/6 and/or 1677/8. Gaps are only allowed for whole years (which the example is) but not parts of years (which is actually required in this case). This is a potential shortcoming of the Gap system. I have got around it by listing the "Ladyday" dates in record 4 of the file header of a transcription file so that the dates are recorded BUT they are not in the Gap system.    

![Screenshot](https://www.freereg.org.uk)

**Comment by PatReynolds** [comment]
Decided not to action - e.g. may be other gaps noted.
