### ISSUE TITLE
219194312 Data Problem (Nick Dew)

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeUKRegProductIssues#1457]
Issue reported by **Nick Dew** at 2021-12-11 23:18:32 UTC
Time: 2021-12-11T22:58:34+00:00
Session ID: 
Problem Page URL: [https://www.freereg.org.uk/search_records/58188253e93790ec8b8eeaa1/melita-gask-baptism-lincolnshire-belton-in-axholme-1818-06-18?locale=en](https://www.freereg.org.uk/search_records/58188253e93790ec8b8eeaa1/melita-gask-baptism-lincolnshire-belton-in-axholme-1818-06-18?locale=en)
Previous Page URL: [https://www.freereg.org.uk/contacts/58188253e93790ec8b8eeaa1/report_error?locale=en&query=61b52ca7791e3b6e5f090839](https://www.freereg.org.uk/contacts/58188253e93790ec8b8eeaa1/report_error?locale=en&query=61b52ca7791e3b6e5f090839)
Reported Issue:
Whenever the location of BELTON IN AXHOLME is requested, the map presented shows BELTON near Grantham i.e. near Belton House.
Surely Belton in Axholme refers to Belton village in the Isle of Axholme, which is NORTH LINCOLNSHIRE, near to Epworth and Crowle.
Please investigate
https://www13.freereg.org.uk/uploads/contact/screenshot/61b531c8f493fde94057cd02/Belton_-_wrong_location.jpg

**Comment by Captainkirkdawson** [comment]
Corrected and user notified
