### ISSUE TITLE
Difficulty selecting County and Place in DAP (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#146]
Issue reported by **REGManager** at 2015-01-10 15:56:44 UTC
Time: 2015-01-10T15:47:15+00:00
Session ID: 6e8b47edff79546b7afac1266f833040
Problem Page URL: [/freereg_contents/new](/freereg_contents/new)
Previous Page URL: [http://test2.freereg.org.uk/](http://test2.freereg.org.uk/)
Reported Issue:
I think we are back to cell padding again.  If you try to Select Somerset and Area Registers the sliders, slider buttons and even my mouse scroll wheel all move the list, particularly the places as this is a large list, in such big steps that it is difficult to pick what you want.   (I know I can adjust the sensitivity of my mouse scroll wheel, but mine is not unusual.)

So I think the boxes need to be larger in all directions.  Even horizontally as the place names do not fit.  If you can see more entries at one time you do not need to be so accurate in the scrolling.

EricD    

![Screenshot](http://test2.freereg.org.uk/tmp/carrierwave/1420905404-99064-9683/Capture.JPG)

**Comment by Captainkirkdawson** [comment]
Done
