### ISSUE TITLE
223289811 Flexi headings (Ali)

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeUKRegProductIssues#1462]
Issue reported by **alsibk** at 2022-01-28 08:56:51 UTC
Time: 2022-01-28T08:46:15+00:00
Session ID: 6a013bcdd11daf37662743f219561124
Problem Page URL: [/freereg1_csv_files?locale=en](/freereg1_csv_files?locale=en)
Previous Page URL: [https://www.freereg.org.uk/csvfiles/new](https://www.freereg.org.uk/csvfiles/new)
Reported Issue:
To be strictly accurate and in line with other headings, relative_surname should be male_relative_surname    

![Screenshot](https://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Is it worth the effort? the code would have to continue to support the existing heading to avoid creaming previous files that have been uploaded

**Comment by PatReynolds** [comment]
Agreed not worth the effort, so closing.
