### ISSUE TITLE
224770046 UserID REGScotland (Eric D)

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeUKRegProductIssues#1464]
Issue reported by **REGManager** at 2022-02-14 12:07:26 UTC
Time: 2022-02-14T12:04:02+00:00
Session ID: c440811fb62f3ff7c879f7a52778e38d
Problem Page URL: [/userid_details/5462b414e937907d7000035d?locale=en&page_name=](/userid_details/5462b414e937907d7000035d?locale=en&page_name=)
Previous Page URL: [https://www.freereg.org.uk/userid_details/5462b414e937907d7000035d/edit?locale=en](https://www.freereg.org.uk/userid_details/5462b414e937907d7000035d/edit?locale=en)
Reported Issue:
I have just been setting up the UserID for Cheryl and noticed the attached list of Counties.  What are the list of nil?
Eric
https://www.freereg.org.uk/uploads/feedback/screenshot/620a45fef493fd071a1d542c/Capture.JPG    

![Screenshot](https://www.freereg.org.uk)

**Comment by DeniseColbert** [comment]
@edickens the page is missing, could you redo a screenshot of the issue please?

**Comment by edickens** [comment]
I can't temember.  Too loing ago.  Close this story.
