### ISSUE TITLE
225066921 Image group header shows zero images (Barrie)

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeUKRegProductIssues#1467]
Issue reported by **brobinson43** at 2022-02-17 22:35:21 UTC
Time: 2022-02-17T22:31:33+00:00
Session ID: 591b9e7f97fbeba27764e88b55c5f4dd
Problem Page URL: [/image_server_groups/620ecbcdf493fd3cd0ce0120?locale=en](/image_server_groups/620ecbcdf493fd3cd0ce0120?locale=en)
Previous Page URL: [https://www.freereg.org.uk/image_server_images/620ecbcdf493fd3cd0ce0120/index?locale=en](https://www.freereg.org.uk/image_server_images/620ecbcdf493fd3cd0ce0120/index?locale=en)
Reported Issue:
This image group has nine images which are displayed if you click on LS. However it shows 0 for number of images and so cannot be allocated.
https://www.freereg.org.uk/uploads/feedback/screenshot/620ecda9f493fd3cd0ce0750/Screen_Shot_2022-02-18_at_9.32.56_am.png    

![Screenshot](https://www.freereg.org.uk)

**Comment by edickens** [comment]
Which image group?  Those links don't bring up the name of the image group.

**Comment by DeniseColbert** [comment]
Seems to be resolved, can reopen if not
