### ISSUE TITLE
225181955 Upload report emails 2 for each upload one fails one success (Susan)

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeUKRegProductIssues#1468]
Issue reported by **hawkinssm** at 2022-02-19 06:32:35 UTC
Time: 2022-02-19T06:25:58+00:00
Session ID: 3cb1026e45d6a934b3e9d7ae90617934
Problem Page URL: [/manage_resources/new?locale=en](/manage_resources/new?locale=en)
Previous Page URL: [https://www.freereg.org.uk/image_server_images/5a9ebc8ff493fdbfcb93bef9/index?locale=en](https://www.freereg.org.uk/image_server_images/5a9ebc8ff493fdbfcb93bef9/index?locale=en)
Reported Issue:
My Transcribers are reporting that they are recieving 2 emails after an upload or replace. The first is usually a successful upload :-
The file submitted for processing has been completed. Please review the following report.
Started on the file KENROPBA7.CSV for Rae at 2022-02-17 23:44:57 +0000. 
The second is usually a failure:-
We are sorry but the file and its records were not processed. The processing log follows and should contain a reason.
Started on the file KENROPBA7.CSV for Rae at 2022-02-17 23:44:57 +0000. 
This began on Friday.
Cheers
Sue Hawkins - Kent Coordinator    

![Screenshot](https://www.freereg.org.uk)

**Comment by SteveBiggs** [comment]
Following the problems with file processing stalling, for every file that is currently being processed, we are getting two emails - one saying it failed and one saying it was successfully processed. I'm telling everyone to ignore the failure messages but it needs investigating and fixing.

**Comment by Captainkirkdawson** [comment]
@SteveBiggs @edickens I have reworked the code dealing with processor crashes that has addressed this issue and should improve processor stalls. Deployed to test3. Please test

**Comment by edickens** [comment]
I don't have files for uploading.  Steve, can you do this?

**Comment by SteveBiggs** [comment]
Yes, I will test this later.

Steve

Stephen Biggs
FreeREG Chairman

**Comment by Captainkirkdawson** [comment]
Remember this is test3

**Comment by SteveBiggs** [comment]
Have uploaded a couple of files and only one (successful) processing email was received each time so looks good.

**Comment by Captainkirkdawson** [comment]
@SteveBiggs deployed to production
