### ISSUE TITLE
re link to Genuki & google maps for place name location etc. (ericb)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#147]
Issue reported by **ericb** at 2015-01-12 19:34:32 UTC
Time: 2015-01-12T19:23:36+00:00
Session ID: 47a766ddf2fe3e8404e5fccfc13dcb6a
Problem Page URL: [/manage_resources/new](/manage_resources/new)
Previous Page URL: [http://test2.freereg.org.uk/](http://test2.freereg.org.uk/)
Reported Issue:
On my iMac, this link no longer shows the zoom capability ( be the +/-  in the top LH corner of the Map).

I checked on a Windows PC and its still there and working.
I am not sure when I last visited this feature, so don't know when It ceased being displayed.
If I copy the Genuki url off to a new browser window, and log to that site, the right map is shown with all the details one gets when doing same form FreeReg Place name, But the zoom is still not there.
If I just  find the same place on Google Maps on the same iMac + browser, as a stand alone action, then it works correctly - ie the zoom +/- are there as a slider bar as they always were too.
Its not life & death desperate but it is very frustrating not to be able to use the zoom, Makes the link almost worthless.

Is it that url that needs a revision for OS X?
I have not done an operating system update for some long time now so my first thought: its not me>    

![Screenshot](http://test2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
This is an external page; the way it functions is not adjusted by FR2. We simply link to the page. It is either a Genuki or an IMac issue
