### ISSUE TITLE
226068378 Blank Processed Date  (Stephen)

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeUKRegProductIssues#1471]
Issue reported by **steveroland** at 2022-03-01 12:46:18 UTC
Time: 2022-03-01T12:44:11+00:00
Session ID: eb57af14829628de96d7a6ce36d02b2c
Problem Page URL: [/freereg1_csv_files?locale=en](/freereg1_csv_files?locale=en)
Previous Page URL: [https://www.freereg.org.uk/manage_counties/select_action?locale=en](https://www.freereg.org.uk/manage_counties/select_action?locale=en)
Reported Issue:
Since around 19th Feb it appears that all files processed in FreeREG are not showing the processed date.
https://www.freereg.org.uk/uploads/feedback/screenshot/621e159af493fd30b75ca11f/Capture.JPG    

![Screenshot](https://www.freereg.org.uk)

**Comment by Sherlock21** [comment]
There is a snag with this email

The url link 3rd down in the message below, fails 2 times out of three.

ericb

**Comment by PatReynolds** [comment]
Eric reports something similar happens when he replaces a file.

@Captainkirkdawson working on this, planning to deploy to test 3 at the end of the week.

**Comment by Captainkirkdawson** [comment]
Deployed to production
