### ISSUE TITLE
226600525 Can "To be destroyed" UserIDs log in? (Eric D)

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeUKRegProductIssues#1472]
Issue reported by **REGManager** at 2022-03-07 16:35:25 UTC
Time: 2022-03-07T16:06:31+00:00
Session ID: a831d81ee7ff0ed56387123596eb3580
Problem Page URL: [/userid_details/600f4477f493fd4755438255?locale=en](/userid_details/600f4477f493fd4755438255?locale=en)
Previous Page URL: [https://www.freereg.org.uk/userid_details?locale=en](https://www.freereg.org.uk/userid_details?locale=en)
Reported Issue:
I have been tidying up the "To be destroyed" syndicate and there are a lot of UserIDs there.  And a lot of these are marked as Active.  They are ones that Jo has deleted for whatever reason during training or if they probably never started .
There is no need for Jo to set them as Inactive with a reason if the UserID is soon to be Destroyed and so the information is lost.  But if one of these UserIDs tries to log in, can they do that as they are still technically Active?  They should not be able to log in if they are in the To be Destroyed syndicate.    

![Screenshot](https://www.freereg.org.uk)

**Comment by PatReynolds** [comment]
@edickens  has sorted this out - they could have logged in (no-one did). Ability to login now removed.
