### ISSUE TITLE
226967179 Website Problem (Rosemary)

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeUKRegProductIssues#1473]
Issue reported by **Rosemary** at 2022-03-11 22:26:19 UTC
Time: 2022-03-11T22:22:56+00:00
Session ID: 
Problem Page URL: []()
Previous Page URL: [https://www.freereg.org.uk/contacts/new](https://www.freereg.org.uk/contacts/new)
Reported Issue:
The attached query, when sorted by date, always has 2 matches out of sequence at the top. Just odd, wouldn't you say?
https://www13.freereg.org.uk/uploads/contact/screenshot/622bcc8bf493fd62de55a77b/FreeREG_Image.JPG

**Comment by SteveBiggs** [comment]
The researcher ticked the '(Include) Family Members' box which seems to affect the date order. The first two results are for family members with the name searched for, however, the third result is also a family member and that doesn't follow date sequence so there certainly is something odd going on.

**Comment by SteveBiggs** [comment]
Looking further at the results, I notice that the first two out of date sequence results have only a birth date with no baptism date recorded. This seems very likely to be part of the problem.

![image](https://user-images.githubusercontent.com/25303607/158236343-0a390d45-131e-4b54-88af-fafe393c82d3.png)

**Comment by PatReynolds** [comment]
FreeREG is sorting by birth date (first) if no baptism date.

Can this be fixed?

If not, need to note somewhere that this is the reason.

**Comment by PatReynolds** [comment]
@PatReynolds to look at this again - are the first two a birth date but no baptism date?

**Comment by PatReynolds** [comment]
The first two are both dates of birth, and there is no baptism in the record.  This particular church, St Mary Baptist, Norwich, is a church where adult baptism, not child baptism, is practiced.

**Comment by PatReynolds** [comment]
@PatReynolds to add to Help.

**Comment by SteveBiggs** [comment]
Looks good in test3.

**Comment by DeniseColbert** [comment]
Sync done so closing
