### ISSUE TITLE
224150554 Data Problem (Frances Jardine)

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeUKRegProductIssues#1474]
Issue reported by **Frances Jardine** at 2022-02-07 08:02:34 UTC
Time: 2022-02-07T08:00:27+00:00
Session ID: 
Problem Page URL: [https://www.freereg.org.uk/search_records/604cbd29f493fd52d22fe7eb/sarah-cockman-joseph-maskell-marriage-essex-halstead-1806-11-12?locale=en](https://www.freereg.org.uk/search_records/604cbd29f493fd52d22fe7eb/sarah-cockman-joseph-maskell-marriage-essex-halstead-1806-11-12?locale=en)
Previous Page URL: [https://www.freereg.org.uk/contacts/604cbd29f493fd52d22fe7eb/report_error?locale=en&query=6200c75e33045be0abe3ce7f](https://www.freereg.org.uk/contacts/604cbd29f493fd52d22fe7eb/report_error?locale=en&query=6200c75e33045be0abe3ce7f)
Reported Issue:
Reference Number: 224041680
Dear Eric
Thankyou for updating Frances Greenwell from a male to a female.  
Unfortunately the program doesn’t seem to be working properly since this change.
For example the marriage between Frances Greenwell and James Robson in 1738 at Corbridge, Northumberland can no longer be found.  However I can still find her birth in 1714.
I do hope this can be fixed.
Regards.
Frances

**Comment by PatReynolds** [comment]
@SteveBiggs to take a look

**Comment by SteveBiggs** [comment]
I asked Eric Wealleans (NBL CC) who replied as follows:

As far as I remember, she emailled me after the first reply about the now missing marriage, which as you can see was rubbish anyways 124 years after her birth, this caused my comment about 1738.
It looked to me that she had seen the marriage for 1838 on findmypast, which is there, and somehow made appear on her records as 1738 on FreeREG.
I do not think it has ever been on FreeREG, and told her so in my reply via email.
Then the second query appeared and as I had already emailled her, presumed the query was already dealt with hence my reply.
As far as I am concerned the matter is closed
