### ISSUE TITLE
227868059 Cookies are essential for the website to work (Eric D)

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeUKRegProductIssues#1475]
Issue reported by **REGManager** at 2022-03-22 08:40:59 UTC
Time: 2022-03-22T08:31:39+00:00
Session ID: 975282fd73a26d69575bd2111f89e027
Problem Page URL: [/manage_resources/new?locale=en](/manage_resources/new?locale=en)
Previous Page URL: [https://www.freereg.org.uk/cms/refinery/login](https://www.freereg.org.uk/cms/refinery/login)
Reported Issue:
I identified a recent problem back to Cookies.  A new CC was having problems and in the end I found that she had said No to Cookies.  And, in general, this is a good think to do.  But in FreeREG, especially if you are a Coordinator, Cookies are needed for the system to work.  The problem was that after logging in as CC, then doing an Action, on returning to the Home page she returned to being a transcriber and all her CC Actions had gone.  I'm assuming that, with no Cookies, the default of Transcriber Actions is used.
So I suggest that every time someone logs in having said No to Cookies, then they are asked again if they want them, and a good explanation is needed as to why FreeREG needs Cookies, and that they are not there to collect personal information, just for the system to work.
This will get more important when we let people register as Researchers.  The default will need to be Researcher Actions, not Transcriber as at present.  We don't want Researchers getting Transcriber access.    

![Screenshot](https://www.freereg.org.uk)

**Comment by PatReynolds** [comment]
@PatReynolds to talk to @Vino to get a list of essential cookies for cookie consent.

**Comment by PatReynolds** [comment]
Are they objecting to sharing data about their activity with google (Analytics cookies) and/or sharing their data with advertisers (Advertising cookies)?  If so, then they can choose the link (not a button) to the "more options and information link' (nb a linked text, not a button):
![image.png](https://images.zenhubusercontent.com/5b695a5dac3a200155c765e3/b953c310-88bb-4ef8-89d4-7da72ae8818d)
it will automatically turn off both Advertising and Analytics cookies.

**Comment by PatReynolds** [comment]
Are they objecting to sharing data about their activity with google (Analytics cookies) and/or sharing their data with advertisers (Advertising cookies)?  If so, then they can choose the link (not a button) to

**Comment by PatReynolds** [comment]
@PatReynolds to find a Cookie Consent that does NOT allow essential cookies to be turned off (if that's legal) and is a positive turn-off for Analtytics and/or Advertising cookies.

**Comment by PatReynoldsFUG** [comment]
Added to specification FreeBMD #303 so suggest closing here.
