### ISSUE TITLE
228467418 Record count in footer (Eric D)

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeUKRegProductIssues#1476]
Issue reported by **REGManager** at 2022-03-29 07:10:18 UTC
Time: 2022-03-29T07:08:20+00:00
Session ID: d3237746f5b9632e6e7387a330e9a969
Problem Page URL: [/manage_resources/new?locale=en](/manage_resources/new?locale=en)
Previous Page URL: [https://www.freereg.org.uk/cms/refinery/login](https://www.freereg.org.uk/cms/refinery/login)
Reported Issue:
Two days in a row now it has said that "No records have been added".  I don't think this is correct.  It is usually more than 5,000 a day.    

![Screenshot](https://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
![added](https://user-images.githubusercontent.com/2874694/160633237-d04b43de-c3be-4702-a82e-074a77df330e.png)
