### ISSUE TITLE
230107761 Missing female surname in burials (Ali)

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeUKRegProductIssues#1477]
Issue reported by **alsibk** at 2022-04-17 06:49:21 UTC
Time: 2022-04-17T06:48:46+00:00
Session ID: c73e17857e5b8bb172aa423999a4bab8
Problem Page URL: [/search_queries/625bb84df493fd8a3ae18813?locale=en](/search_queries/625bb84df493fd8a3ae18813?locale=en)
Previous Page URL: [https://www.freereg.org.uk/search_queries/new?locale=en](https://www.freereg.org.uk/search_queries/new?locale=en)
Reported Issue:
Is there a touch of misogyny afoot in burial records?

Burial person with female as only relative is not found, as female's surname not included in search.

eg--Ruth, daughter of Elizabeth WOOLHOUSE, buried 3 Jul 1740 at Sheffield is not found.

On browsing WRYSHEBU10 online, any female relative where there is no male relative is not afforded a surname.

And yet---if we search Elizabeth WOOLHOUSE with family members selected, Ruth's burial is found. Very strange.

In the file as uploaded all relevant details are present.    

![Screenshot](https://www.freereg.org.uk)

**Comment by DeniseColbert** [comment]
Pinned so it doesn't get lost- to be moved in a future sprint.

**Comment by SteveBiggs** [comment]
This is also the case with a baptism search, however, it appears that searches in 'Other Transcript' records DO return when only the mother's name is present whereas for PR types it doesn't. Very odd!

Info from Mary Korna:

"I've had a contact about a record for Caldecote, CAM.  We have two sources for Caldecote, the PR and a donated transcript.  They give different names for the mother of Smith Parish baptised  in 1792. 

I've sorted out the query BUT when I searched for the name myself I only got one record, the transcript.  I've looked on the database and the BA file for Caldecote is there, listed under the parish register.

I've searched for several other Caldecote records and found that if there is no surname for the father, only the TR appears but with a fathers surname both records are listed.  On the PR file where there is no fathers name the transcriber has used -.  I don't know if this is of any significance

I've also searched for Elizabeth Westnutt baptised at Caldecote on 16 Oct 1836.  On the TR she is listed only as Elizabeth Westnutt, on the PR her fathers surname is given as Westnutt and her mothers as Izzard.  On a search for Elizabeth Westnutt, I get both records.  On a seach for Elizabeth Izzard, there is no result"

**Comment by DeniseColbert** [comment]
@Vino-S to check if FreeREG will allow surname search of male relative but not female relative.

**Comment by DeniseColbert** [comment]
@Vino-S to add female surname if field would usually be blank

@Vino-S to look into the difference between OT record type and PR (re. Steve's comment above)

If we can't get all record types to act properly, could change info in tooltip: suggest changing language to include "parents" among family memebrs.

**Comment by DeniseColbert** [comment]
The word "parent" is already in the tooltip!

**Comment by DeniseColbert** [comment]
Required a rebuild of the search records, almost done

**Comment by Vino-S** [comment]
@Vino-S to look into the no-results  issue

**Comment by DeniseColbert** [comment]
Ready for testing in Test 2 @Vino-S to write to @edickens with info on changes made and instructions on how to test.

**Comment by Vino-S** [comment]
Hi @SteveBiggs 
I have updated the code in test2.
When the record does not have a surname, it can be searched by both Relative surname and Female Relative Surname.
Example Record: 
[(https://test2.freereg.org.uk/search_records/6583af82bd30f2d7875a2f22/george-tyson-george-callum-burial-yorkshire-west-riding-sheffield-1736-03-25?locale=en)]
Screenshot:
<img width="914" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMU45QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4d734a29ad5231e9c8c43d235a67fd9733cf581c/image.png" alt="image.png" />
The Record details:
Forename: George
Relative Surname: TYSON
Female Relative Surname: CALLUM

The record is now searchable as George TYSON and George CALLUM
<img width="1641" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVo5QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bdea839acc3a9dd4d2107cab28a52da11a49c41f/image.png" alt="image.png" />

**Comment by SteveBiggs** [comment]
Looks good thanks Vino.

**Comment by Vino-S** [comment]
deployed

**Comment by DeniseColbert** [comment]
Keeping open to monitor

**Comment by DeniseColbert** [comment]
@CommsCoord please could you ask Ali if she's aware that this has been fixed?

**Comment by DeniseColbert** [comment]
(Can close when above is done)

**Comment by DeniseColbert** [comment]
Done, closing
