### ISSUE TITLE
232572298 server claims files exist when they don't (Dale)

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeUKRegProductIssues#1478]
Issue reported by **STSCC** at 2022-05-15 19:24:58 UTC
Time: 2022-05-15T18:51:17+00:00
Session ID: c6f95ae41ae96a03624d499003f3464b
Problem Page URL: [/csvfiles/new](/csvfiles/new)
Previous Page URL: [https://www.freereg.org.uk/csvfiles/new](https://www.freereg.org.uk/csvfiles/new)
Reported Issue:
I just tried to upload a file (STSSEDBA11) into my own account (dbraden) and the server says I already have a file by that name.  I don't.  So I renamed the file to STSSEDBA13 and then STSSEDBA14 and tried again, but got the same error messages.  These files do not exist in my account.  Then a transcriber told me that a file that he had uploaded a few days ago was now missing from his account (STSTECBU for account userid chrisw; we have the emails showing that the server accepted this file).  When I tried to upload that file for him, again the server told me that the file already exists.  I think the server might be hanging onto the names of files that have actually been *deleted* from our accounts.  In any case, this is pretty urgent.    

![Screenshot](https://www.freereg.org.uk)

**Comment by SteveBiggs** [comment]
dbraden does actually already have a file called STSSEDBA11 which he uploaded on 08-Dec-2021, but I don't see STSSEDBA13 or 14 so don't know why they gave the 'already exists' message.
Looking in the Attic, I see that chrisw uploaded several versions of STSTECBU with the last one being on May 12th but there is not one in his active list of files so again, I cannot explain why his upload fails.

**Comment by Captainkirkdawson** [comment]
The person dbraden has been doing some strange things that are more complicated that he indicates. He has uploaded STSSEDBA11/12/13/14. All were uploaded late on 2021-12-08 together with may other files 
![STSSEDBA11-13](https://user-images.githubusercontent.com/2874694/168498956-fe7c6be0-7d14-490c-85f3-09e6bc956708.png)
Most of them are in his file folder
![STSSEDBA](https://user-images.githubusercontent.com/2874694/168498985-50c4d2ce-0bcb-466b-a32e-bb85507ea8b9.png)
So somewhere somehow he has been uploading/replacing and perhaps deleting these files

**Comment by SteveBiggs** [comment]
Thanks @Captainkirkdawson. I couldn't find BA13 or BA14 in Dale's files but it turns out they were in the 'Files not processed' list. I assume the fact they are there stops the user from uploading/replacing them? 

Should we consider automatically deleting files from this not processed list after a period as I can't see any benefit in leaving them sitting there?

**Comment by Captainkirkdawson** [comment]
That is for you to suggest. Personally I would have preferred a human to make that decision. Perhaps the rake task that looks at the queue length should be extended so that if nothing is waiting then it also checks for not processed files and reports this if any are found.

**Comment by PatReynolds** [comment]
Agreed - sent to Coordinator to resolve.

Tip should be put in Help for Transcribers, telling them to contact their SysCoord if they can't see something that should be there.

**Comment by PatReynolds** [comment]
In progress: @AlOneill is adding to tips.

**Comment by AlOneill** [comment]
Tip added to [DRAFT Info for transcribers, tips for transcribers](https://test3.freereg.org.uk/cms/information-for-transcribers/draft-information-for-transcribers#tipsForBy)

**Comment by FreecenBren** [comment]
Cheers

**Comment by PatReynolds** [comment]
Closing as complete.

**Comment by FreecenBren** [comment]
Unsubscribe
