### ISSUE TITLE
232724834 Marriages selected but birth dates sorted (Michael)

### ISSUE THREAD

**Issue by Freeukgencomputer** [FreeUKGen/FreeUKRegProductIssues#1479]
Issue reported by **LINCC** at 2022-05-17 13:47:14 UTC
Time: 2022-05-17T13:43:56+00:00
Session ID: c28d36755ee75e11ff3df983262fc6b2
Problem Page URL: [/search_queries/6283a69cf493fdf00b9ad841?locale=en](/search_queries/6283a69cf493fdf00b9ad841?locale=en)
Previous Page URL: [https://www.freereg.org.uk/search_queries/new?locale=en](https://www.freereg.org.uk/search_queries/new?locale=en)
Reported Issue:
When doing a search, selecting the record type of "Marriage", returns a list which is purportedly sorted by birth date!!!! Surely this should be marriage date or, better still and easier, just date.    

![Screenshot](https://www.freereg.org.uk)

**Comment by SteveBiggs** [comment]
For any of baptism, marriage or burial searches, it reports the same thing - "sorted by birth date". Can this be changed to simply "sorted by date"?

**Comment by PatReynolds** [comment]
Hi @Vino-S please give this a size.
