### ISSUE TITLE
testing rewritten church/placename/ county package. - Relocate Batch (ericb)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#148]
Issue reported by **ericb** at 2015-01-14 19:47:01 UTC
Time: 2015-01-14T19:40:21+00:00
Session ID: 07db2d536f7ec281c011a97238cf9207
Problem Page URL: [/freereg1_csv_files/54762a7de9379035bb000001/relocate](/freereg1_csv_files/54762a7de9379035bb000001/relocate)
Previous Page URL: [http://test2.freereg.org.uk/freereg1_csv_files/54762a7de9379035bb000001](http://test2.freereg.org.uk/freereg1_csv_files/54762a7de9379035bb000001)
Reported Issue:
working with WRY/ Alverthorpe/ batch (ericb) WRYALVBA1.csv.

this file started life in St Paul's church. Successfully relocated it into a new church of St Mary. that had checked out OK.
next test was to change the Register Type code from PR as it was when uploaded, to Phillimore Transcript (picked from drop down list under option Relocate Batch - which seems an odd title incedentally)

As soon as I hit Submit, it crashed into this error state. screen print of msg attached in case you dont get it!    

![Screenshot](http://test2.freereg.org.uk/tmp/carrierwave/1421264821-60196-1984/Screen_shot_2015-01-14_at_19.41.36.png)

**Comment by Captainkirkdawson** [comment]
Fixed, that will teach me yet again to not change that which is working
