### ISSUE TITLE
237224575 Some witness data missing on lines in error (Michael)

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeUKRegProductIssues#1481]
Issue reported by **LINCC** at 2022-07-08 15:42:55 UTC
Time: 2022-07-08T15:11:09+00:00
Session ID: d954fe15b118f6aea4c59bbd48d1470c
Problem Page URL: [/freereg1_csv_entries/62c846aef493fd8a9c741d1e?locale=en](/freereg1_csv_entries/62c846aef493fd8a9c741d1e?locale=en)
Previous Page URL: [https://www.freereg.org.uk/freereg1_csv_entries?locale=en](https://www.freereg.org.uk/freereg1_csv_entries?locale=en)
Reported Issue:
I submitted a file for processing on behalf of Mick. The file was LINCRWMA55.CSV.

I received a "Processed with Errors" email message. There were 3 errors - one was a wrong age and two were marriage date errors.

I used the "Listing of error entries" facility to find the errors and correct the problems.

When I processed the last message (I did not notice anything untoward with the first two messages but they may have shown this same problem) I noticed that there was a Note about witnesses. BUT THERE WERE NO WITNESSES DISPLAYED.

I checked the input file (CSV) and the record did have witnesses but, it seems, for some reason they were disregarded.

I checked the entries in FreeREG immediately before and after this entry and they both showed witnesses.

I have been investigating further and have found the same problem with the "wrong age" correction.

It appears to me that either (a) after finding an error while processing the file, some fields (i.e. witnesses) are ignored and not processed into FreeREG or (b) the correction process loses the witnesses.     

![Screenshot](https://www.freereg.org.uk)

**Comment by SteveBiggs** [comment]
Further testing by Michael:

I have tried an experiment by re-submitting the file as myself (not relevant, I think).
When I look at the "Listing of error entries", before I do any online edits, there ARE witnesses in the list of fields.
When I select one of the errors and use the "Edit" button, the display DOES NOT SHOW WITNESSES.
The same thing occurs when using the "Browse entries"/"Listing of all Error Records in this Batch"
So it looks, to me, like it is the online editing of error records that is at fault.

**Comment by PatReynolds** [comment]
@Vino-S to take a look.

**Comment by SteveBiggs** [comment]
I have reproduced the problem. When the Edit button is clicked, the list of fields for the record does not show any witnesses:
![image](https://user-images.githubusercontent.com/25303607/185372356-24de90aa-cd23-4076-a9df-312075483c98.png)
So that when an edit change is saved, the witnesses are lost.

**Comment by edickens** [comment]
Could thils error apply to all new Flexible CSV fields?

**Comment by SteveBiggs** [comment]
The file I tested on does not use flexible csv so I don't know.

**Comment by DeniseColbert** [comment]
@SteveBiggs to test

**Comment by SteveBiggs** [comment]
I already tested it and it is still not fixed. I sent Vino an email about it.

**Comment by Vino-S** [comment]
Hi @SteveBiggs ,
I made some changes and updated test3 again yesterday. Could you test it again, please?
Sorry for the confusion.

**Comment by SteveBiggs** [comment]
@Vino-S yes that looks good now. Thanks

**Comment by DeniseColbert** [comment]
Done, closing
