### ISSUE TITLE
238246775 A Question about Trainee Status (Eric D)

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeUKRegProductIssues#1482]
Issue reported by **REGManager** at 2022-07-20 11:39:35 UTC
Time: 2022-07-20T11:35:16+00:00
Session ID: cb10747365d86f6e8a2f47424ffe36d3
Problem Page URL: [/userid_details/selection?option=Select%20specific%20userid](/userid_details/selection?option=Select%20specific%20userid)
Previous Page URL: [https://www.freereg.org.uk/userid_details/options](https://www.freereg.org.uk/userid_details/options)
Reported Issue:
If a UserID is set as Trainee, are the files that they upload entered into the live database?  I don't think they should be.
I know that Jo's trainees use the County ENG which does not go into the live database, but what if they upload a valid county code?
And, if trainee's files are not entered into the live database, have SCs made sure that their transcribers' status is not Trainee.  Otherwise all their work may not be in the live database, and they would never know.
Eric    

![Screenshot](https://www.freereg.org.uk)

**Comment by PatReynolds** [comment]
Just one person has trainee status.  @SteveBiggs to contact the relevant coordinator.
