### ISSUE TITLE
246968297 Data Problem (Michael Burbeck)

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeUKRegProductIssues#1487]
Issue reported by **Michael Burbeck** at 2022-10-29 10:18:17 UTC
Time: 2022-10-29T09:53:56+00:00
Session ID: 
Problem Page URL: [https://www.freereg.org.uk/search_records/5a2fe29df493fd51a7bf6b01/an-birkbeck-baptism-yorkshire-north-riding-grinton-1688-01-29?locale=en](https://www.freereg.org.uk/search_records/5a2fe29df493fd51a7bf6b01/an-birkbeck-baptism-yorkshire-north-riding-grinton-1688-01-29?locale=en)
Previous Page URL: [https://www.freereg.org.uk/contacts/5a2fe29df493fd51a7bf6b01/report_error?locale=en&query=635cf51086557402eb62593b](https://www.freereg.org.uk/contacts/5a2fe29df493fd51a7bf6b01/report_error?locale=en&query=635cf51086557402eb62593b)
Reported Issue:
Yorkshire, North Riding Line 2056 refers to the Baptism of An Birkbeck on 29 Jan 1687/8 and this is duplicated in line 2203. It is suggested that Line 2203 be deleted.

**Comment by SteveBiggs** [comment]
A search for An Birkbeck returns two results for the same entry with different line numbers but there is only one entry in the FreeREG database. Where is the other result coming from?

**Comment by SteveBiggs** [comment]
Mystery solved.
