### ISSUE TITLE
there is a "spare" church header left over from previous test (ericb)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#149]
Issue reported by **ericb** at 2015-01-14 21:25:20 UTC
Time: 2015-01-14T21:18:24+00:00
Session ID: 4bc7485e739c63d160d71257bb11d92f
Problem Page URL: [/places](/places)
Previous Page URL: [http://test2.freereg.org.uk/manage_counties/select_action?county=WRY](http://test2.freereg.org.uk/manage_counties/select_action?county=WRY)
Reported Issue:
refer to WRY/ Alverthorpe/ and last test which failed
= this was changing the Register type of batch for St Mary church. It had started life as RP and the last test was to change the type to Phillimore transcription but that failed ( now fixed by Kirk).
But when i look at the records for Alverthorpe we have a "spare" row. 
- the half filled row between St Mary - Phillimore's transcript and St Paul Parish Register.

Is this a left over form the failed test ( the St Mary batch had been a Parish Register type before the failed test tried to change it.I can't see from typing this where the batch file is now located.    

![Screenshot](http://test2.freereg.org.uk/tmp/carrierwave/1421270720-78413-1446/Screen_shot_2015-01-14_at_21.19.06.png)

**Comment by Sherlock21** [comment]
I can now see there are no batches associated to the Parish Register labelled row, the WRYALVBA1.csv file is correctly in the St Mary row.
So why the PR label still there please? How to remove it?

**Comment by Captainkirkdawson** [comment]
It was left over from the previous failed change. Since there are no batches simply delete it.

Click on the Parish Register link and in the Destroy the Register if it is not needed.
