### ISSUE TITLE
258632673 Image assignment (Somerset)

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeUKRegProductIssues#1495]
Issue reported by **SOMCoord** at 2023-03-13 10:24:33 UTC
Time: 2023-03-13T10:19:06+00:00
Session ID: d6867ef86227ca32d42fd13be692e6ca
Problem Page URL: [/assignments/5a9ec5c9f493fdbfcb984909/assign?assign_type=transcriber&locale=en](/assignments/5a9ec5c9f493fdbfcb984909/assign?assign_type=transcriber&locale=en)
Previous Page URL: [https://www.freereg.org.uk/image_server_images/5a9ec5c9f493fdbfcb984909/index?locale=en](https://www.freereg.org.uk/image_server_images/5a9ec5c9f493fdbfcb984909/index?locale=en)
Reported Issue:
When I assign a list of images to a transcriber, the images are listed in my coordinator's screen numerical sequence, as here. 

This transcriber (ctvw) has reported before on previous assignments that when those same images appear in his Assignments, they are listed OUT OF numerical sequence. 

That might sound a small thing, but it is very irritating for transcribers to have to hunt about for the next image in the sequence, if only because the original registers themselves are often out of sequence, or jumbled up, and so it is difficult to tell whether anything is missing unless you have the images in numerical sequence. 

Is it possible for the images to be shown to the transcriber in their proper numerical sequence please? Thank you

    

![Screenshot](https://www.freereg.org.uk)

**Comment by DeniseColbert** [comment]
@SteveBiggs to ask SOM coord to test

**Comment by SteveBiggs** [comment]
Have asked Jackie to verify if it's now fixed.

**Comment by SteveBiggs** [comment]
Jackie says it's not fixed:

I assigned some images to myself at the time of your email, and they were okay, but I've just allocated some to myself now for other reasons (North Cadbury) and here's what I see:

![image.png](https://images.zenhubusercontent.com/5cb596063b6bd6333fc1dc24/2d4282ac-d711-4ec1-95f7-aef4dfe5d591)

**Comment by suffolkroots** [comment]
Same here. Not using image server until it's sorted.
Ali

**Comment by DeniseColbert** [comment]
@SteveBiggs @suffolkroots this is ready for testing on Test 3

**Comment by Vino-S** [comment]
Sandra to get back from Julie

**Comment by ghost** [comment]
Emailed Jackie as she was the original contact.

**Comment by ghost** [comment]
Jackie replied and said the transcriber reported things are better but does not appear to be completely fixed, She is asking the transcriber for a more detailed explanation.

**Comment by ghost** [comment]
Jackie sent along the following note and screenshots:

Here are some screen prints of an Assignment I just made to myself (ie as Syncoord to Transcriber). 

Obviously I can't show the whole image group in one screen print but I hope I have overlapped the early images in this group sufficiently that the programmers can see the problem.
To be clear this is what I see when I look in my Assignments (as transcriber). When I look as Syndicate Coordinator at the images in their image groups ( Actions, Manage Syndicate, Manage Images, Image Server etc, List.) they are listed correctly in numerical sequence.

![jackie 1](https://github.com/FreeUKGen/FreeUKRegProductIssues/assets/20557838/8f2be634-db05-4d58-bd81-108f7e587944)
![jackie2](https://github.com/FreeUKGen/FreeUKRegProductIssues/assets/20557838/3114d9c9-31d1-4921-884a-a00fe399f514)
![Jakcie3](https://github.com/FreeUKGen/FreeUKRegProductIssues/assets/20557838/4999394a-6fbe-4049-9d0a-9d35a4b470f0)

**Comment by DeniseColbert** [comment]
Vino will deploy to live so that Jackie can test there, @CommsCoord to send Jackie a note to test at the end of the week.

**Comment by ghost** [comment]
Jackie reports all seems to be in order.
This can be closed

**Comment by DeniseColbert** [comment]
UserIDs that have experienced this problem since closing:

Jackie let us know the userIDs who experienced the problem, in case it is significant: ctvw, DMasters, JRTot.

**Comment by DeniseColbert** [comment]
This needs testing, Sandra to check back with jackie

**Comment by ghost** [comment]
Jackie says all looks clear.

**Comment by DeniseColbert** [comment]
Working on live: closing
