### ISSUE TITLE
258830817 File Processor Frequently Stalls (Stephen)

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeUKRegProductIssues#1496]
Issue reported by **SBManager** at 2023-03-15 17:26:57 UTC
Time: 2023-03-15T17:24:51+00:00
Session ID: 446462b78fc9e2f85675936b5e93f083
Problem Page URL: [/physical_files/waiting_to_be_processed](/physical_files/waiting_to_be_processed)
Previous Page URL: [https://www.freereg.org.uk/physical_files/select_action](https://www.freereg.org.uk/physical_files/select_action)
Reported Issue:
This last four weeks the queue has stalled quite a few times and it needs Vino to start it again. Can the restart be automated?  If all Vino does is start the first file processing again, then it might be possible to automate that.  Perhaps when that limit message is created, something could be set to start the first file in say an hour's time.    

![Screenshot](https://www.freereg.org.uk)

**Comment by DeniseColbert** [comment]
Fix deployed to production so closing
