### ISSUE TITLE
260076700 Image server 'exists' but does not appear (Barrie)

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeUKRegProductIssues#1497]
Issue reported by **brobinson43** at 2023-03-30 03:31:40 UTC
Time: 2023-03-30T03:25:30+00:00
Session ID: 1cd3c0a27ad7baae86ebddba1ef860ba
Problem Page URL: [/manage_counties/selection?option=Manage%20Images](/manage_counties/selection?option=Manage%20Images)
Previous Page URL: [https://www.freereg.org.uk/manage_counties/select_action?county=Warwickshire&locale=en](https://www.freereg.org.uk/manage_counties/select_action?county=Warwickshire&locale=en)
Reported Issue:
I went to View Active Places -> [Warwickshire] Ansley St Laurence Parish Register  and clicked Creat Image Server. The request timed out. I went back and tried again, and it replied Creat Image Server Failed, [it] already exists.
Ok, so I went to Manage Images -> View all Image Sources and there is no sign of Ansley St Laurence Parish Register. Can you fix this please?

Barrie Robinson
    

![Screenshot](https://www.freereg.org.uk)

**Comment by DeniseColbert** [comment]
@Vino-S will look into this

**Comment by DeniseColbert** [comment]
Should be fixed, Barrie can try again and this should work.

**Comment by SteveBiggs** [comment]
Email sent to Barrie to check and confirm.

**Comment by Vino-S** [comment]
Sandra to check with Barrie

**Comment by ghost** [comment]
Emailed Barrie this morning

**Comment by ghost** [comment]
Barrie has replied and said all seems to be currently running smoothly. This issue can be closed

**Comment by DeniseColbert** [comment]
Done; closing
