### ISSUE TITLE
261886459 Data Problem (Robert G Crawford)

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeUKRegProductIssues#1498]
Issue reported by **Robert G Crawford** at 2023-04-20 02:14:19 UTC
Time: 2023-04-20T01:56:11+00:00
Session ID: 
Problem Page URL: [https://www.freereg.org.uk/search_records/5f16051ff493fd147f0e576f/eliza-richardson-richardson-baptism-lincolnshire-great-steeping-1819-06-01?locale=en](https://www.freereg.org.uk/search_records/5f16051ff493fd147f0e576f/eliza-richardson-richardson-baptism-lincolnshire-great-steeping-1819-06-01?locale=en)
Previous Page URL: [https://www.freereg.org.uk/contacts/5f16051ff493fd147f0e576f/report_error?locale=en&query=64409b978655746ce9fb3eea](https://www.freereg.org.uk/contacts/5f16051ff493fd147f0e576f/report_error?locale=en&query=64409b978655746ce9fb3eea)
Reported Issue:
You have a record for an Eliza Richardson Richardson, born in 1819 in Great Steeping, Lincolnshire

The surnames for her parents have been reversed.
They should have been John Crawford and Ann Richardson, and her name should have been Eliza Richardson Crawford
https://www13.freereg.org.uk/uploads/contact/screenshot/64409ffbf493fd59c51d9470/Baptism_of_Eliza_Richardson_Richardson__John__Ann_Crawford__in_All_Saints__Great_Steeping__Lincolnshire_1819.jpg

**Comment by DeniseColbert** [comment]
@CommsCoord to liaise with Mick on this contact

**Comment by ghost** [comment]
![261886459](https://github.com/FreeUKGen/FreeUKRegProductIssues/assets/20557838/efb49cfb-a4db-493b-8012-75d72ad144d2)

Liaising is now with Michael Clarke who is now handling LIN. I have emailed him but am confident what is in the attachment is what the issue is regarding (the page cutting off part of the query wording), not the query itself. I have restored the contact to the LIN page and asked him to answer the query (the entire message can be viewed by clicking Create Reply) whilst the issue is dealt with separately if needed.

**Comment by ghost** [comment]
This has been dealt with and the issue can be closed.

**Comment by DeniseColbert** [comment]
Closing
