### ISSUE TITLE
262043844 Corrupt file (Misty)

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeUKRegProductIssues#1499]
Issue reported by **macie** at 2023-04-21 21:57:24 UTC
Time: 2023-04-21T21:52:07+00:00
Session ID: d9e34d94da821bc6e138ea5539828084
Problem Page URL: [/freereg1_csv_files/display_my_own_files?locale=en&page=2](/freereg1_csv_files/display_my_own_files?locale=en&page=2)
Previous Page URL: [https://www.freereg.org.uk/freereg1_csv_files/display_my_own_files?locale=en&page=2](https://www.freereg.org.uk/freereg1_csv_files/display_my_own_files?locale=en&page=2)
Reported Issue:
This file has not loaded properly for some reason and I cannot delete it. The entire file can be destroyed as I will be uploading it under a different file name. Thank you
https://www.freereg.org.uk/uploads/feedback/screenshot/644306c4f493fd83c20822df/FLN_file.jpg    

![Screenshot](https://www.freereg.org.uk)

**Comment by SteveBiggs** [comment]
I am unable to delete this file so will need Vino to do it please. UserID is macie:

![image](https://user-images.githubusercontent.com/25303607/233785827-d0c02b29-2b06-4390-93f3-8389abc3bf93.png)

**Comment by DeniseColbert** [comment]
There was a problem with the upload of this file: @Vino-S to investigate and delete the file

**Comment by SteveBiggs** [comment]
The file has gone so this can be closed.
