### ISSUE TITLE
264204436 Message to Devon Syndicate sent to possibly everyone  (Janelle)

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeUKRegProductIssues#1500]
Issue reported by **Janelle** at 2023-05-16 22:07:16 UTC
Time: 2023-05-16T22:02:01+00:00
Session ID: 5bc8103844a3889d069617105894a5d4
Problem Page URL: [/messages/list_syndicate_messages?source=list_syndicate_messages](/messages/list_syndicate_messages?source=list_syndicate_messages)
Previous Page URL: [https://www.freereg.org.uk/manage_syndicates/select_action?locale=en](https://www.freereg.org.uk/manage_syndicates/select_action?locale=en)
Reported Issue:
Seems that my latest message that I thought I set up for only active syndicate members went to other user ids and even to FreeBMD addresses. Please review and fix if broken.  I do find the selection boxes awkward. Active syndicate members should be the default ?
  
Thanx ;)  
Janelle     

![Screenshot](https://www.freereg.org.uk)

**Comment by DeniseColbert** [comment]
@AnneV-Learn this could be another glitch in the Syndicate Message system, but over on FreeREG this time?

**Comment by DeniseColbert** [comment]
@SteveBiggs to ask Janelle to keep an eye on this in case it happens again.

**Comment by SteveBiggs** [comment]
Have asked Janelle to check when she next sends out a Syndicate Message.

**Comment by Vino-S** [comment]
Sandra to contact Janelle

**Comment by ghost** [comment]
Emailed Janelle today. Awaiting reply

**Comment by ghost** [comment]
Emailed Janelle again via Comms on the website and also by email

**Comment by ghost** [comment]
Reply from Janelle (first bit left out as contained personal info)
****
Anyhoo,
The problem I reported happened on 15 May.
I’ve used since used it on
27 June 
11 Sep
23 Nov
No repetition of others receiving the last 3 that I am aware of, which would only be if non Devon folks reply …

The set up for sending out is really clunky, there’s no confirmation that anything has happened. 
I only know a message is sent because I am a syndicate member and receive a notification that I have a new message, which I must presume went to all active members.

I would have more confidence in the system if the sender, ie the syndicate coordinator, got a notification listing the success and who were the recipients.

Thanx
Janelle 
*****
I am not sure if her suggestion regarding notification of successful deliveries can be implemented but an interesting idea. 

I assume  this can be closed now?

**Comment by DeniseColbert** [comment]
Done; closing

**Comment by DeniseColbert** [comment]
See #1573 also
