### ISSUE TITLE
265816088 Irrelevant info for transcribers. (Ali)

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeUKRegProductIssues#1503]
Issue reported by **alsibk** at 2023-06-04 13:48:08 UTC
Time: 2023-06-04T13:45:05+00:00
Session ID: cd0219678e71e475db263b4338a9262e
Problem Page URL: [/cms/information-for-transcribers/creating-a-transcription-file](/cms/information-for-transcribers/creating-a-transcription-file)
Previous Page URL: [https://www.freereg.org.uk/cms/information-for-transcribers](https://www.freereg.org.uk/cms/information-for-transcribers)
Reported Issue:
Please could I suggest that this be removed from "information for transcribers"?
It is no longer relevant

WinFreeREG

Some of our more experienced transcribers are involved in testing our new program, WinFreeREG. When this is ready for general use, it will replace WinREG for Windows users. In the meantime, new and most existing transcribers should continue to use WinREG.
    

![Screenshot](https://www.freereg.org.uk)

**Comment by SteveBiggs** [comment]
Another doc change needed.

**Comment by DeniseColbert** [comment]
@AlOneill are you OK to make this change?

**Comment by AlOneill** [comment]
@DeniseColbert Will do so.

**Comment by AlOneill** [comment]
Working on making the change. Should be straightforward …

**Comment by AlOneill** [comment]
@SteveBiggs

I've removed the text that applied to WinFreeREG.

While we are there, is there anything else that needs updating in [DRAFT Creating a transcription file](https://test3.freereg.org.uk/cms/information-for-transcribers/draft-creating-a-transcription-file) ?

**Comment by AlOneill** [comment]
OK, moving on. Updated page is now sync-ready.

**Comment by DeniseColbert** [comment]
Thanks @AlOneill, closing
