### ISSUE TITLE
266725237 Website Problem (Janalou)

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeUKRegProductIssues#1504]
Issue reported by **Janalou** at 2023-06-15 02:20:37 UTC
Time: 2023-06-15T02:07:41+00:00
Session ID: 
Problem Page URL: []()
Previous Page URL: [https://www.freereg.org.uk/contacts/new](https://www.freereg.org.uk/contacts/new)
Reported Issue:
Hello!

Your website has become a priceless resource for millions w who are interested in genealogy. 

However, the green background with blue links is nearly impossible to read and is giving me migraines. The colors are just too close together in color scheme ame just about the same degree. 

Can you please have someone change it back PLEASE? .... OR if the background has to be such a strong green, then change the links color to something that will stand out and be legible... maybe a bright yellow... or stay with white. But just black and white would be better overall and use less ink to print.  

Thank you for your time and consideration. 
Janalou Sonafrank 
https://www13.freereg.org.uk/uploads/contact/screenshot/648a7575f493fd112c8b86c5/Screenshot_20230614-200651_Chrome.jpg

**Comment by SteveBiggs** [comment]
This colour scheme is used for the record detail view on a smartphone for some reason. As the researcher says, it is very hard to read. Here is the screen grab:
![image](https://github.com/FreeUKGen/FreeUKRegProductIssues/assets/25303607/035de609-abf7-4fad-a297-f00300e71c30)

**Comment by DeniseColbert** [comment]
Good grief! I'm sure that hasn't always been that scheme; I wonder when it changed and why. I'll ask Vino to take a look.

**Comment by DeniseColbert** [comment]
@SteveBiggs to test on live

**Comment by SteveBiggs** [comment]
Looks good now. Can be closed.

**Comment by DeniseColbert** [comment]
Closing
