### ISSUE TITLE
267002726 Image Source WOR Bradley St John doesn't show (Eric D)

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeUKRegProductIssues#1505]
Issue reported by **REGManager** at 2023-06-18 07:25:26 UTC
Time: 2023-06-18T07:20:34+00:00
Session ID: dd4d90e6b7a7c630357413ecb3cfd3da
Problem Page URL: [/manage_counties/selection?option=Manage%20Images](/manage_counties/selection?option=Manage%20Images)
Previous Page URL: [https://www.freereg.org.uk/manage_counties/select_action?locale=en](https://www.freereg.org.uk/manage_counties/select_action?locale=en)
Reported Issue:
The Image Source for Bradley St John the Baptist PR is there in Manage Images Action but doesn't show in the County Manage Images.
My back door program doesn't work any more so I can't sort this out.  All the Sources for this place can be deleted as no images have been uploaded.  I will then start again.
Eric
https://www.freereg.org.uk/uploads/feedback/screenshot/648eb166f493fd9b99685f18/Capture1.JPG    

![Screenshot](https://www.freereg.org.uk)

**Comment by edickens** [comment]
This is urgent because I have images waiting to be uploaded with work for transcribers.

**Comment by DeniseColbert** [comment]
Make sure there are no images in there, if there are, get back to Eric.

**Comment by Vino-S** [comment]
Issue fixed. Closing
