### ISSUE TITLE
267209287 CCs/SCs can see all counties/syndicate (Stephen)

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeUKRegProductIssues#1506]
Issue reported by **steveroland** at 2023-06-20 16:48:07 UTC
Time: 2023-06-20T16:44:15+00:00
Session ID: 16bcfc304730bd4d4eb33cb5e51dd983
Problem Page URL: [/manage_counties/new?locale=en](/manage_counties/new?locale=en)
Previous Page URL: [https://www.freereg.org.uk/manage_resources/new?locale=en](https://www.freereg.org.uk/manage_resources/new?locale=en)
Reported Issue:
When I'm logged in with my County Coord userID and select 'Manage Counties' or 'Manage Syndicates', I can see ALL counties/syndicates in the selection list rather than just those I actually manage. I don't know if this is the case for other CCs/SCs as no one has reported it yet.    

![Screenshot](https://www.freereg.org.uk)

**Comment by ghost** [comment]
It is affecting my Wales Coordinator account but not the Wales syndicate

**Comment by SteveBiggs** [comment]
Another report suggests it's a problem for all County Coords.
