### ISSUE TITLE
267360790 Contacts action no longer work for CCs (Stephen)

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeUKRegProductIssues#1507]
Issue reported by **steveroland** at 2023-06-22 10:53:10 UTC
Time: 2023-06-22T10:51:08+00:00
Session ID: ebcade7fbdd2cbecc687ae367e526058
Problem Page URL: [/manage_resources/new?locale=en](/manage_resources/new?locale=en)
Previous Page URL: [https://www.freereg.org.uk/cms/refinery/login](https://www.freereg.org.uk/cms/refinery/login)
Reported Issue:
When a CC clicks on the Contacts action, a red error message comes up. When I select Contacts in my Sys_Admin userID it takes me to the Contacts but the list is empty.    

![Screenshot](https://www.freereg.org.uk)

**Comment by SteveBiggs** [comment]
This needs fixing urgently as CCs are unable to use the Contacts system to reply to problems raised.

**Comment by DeniseColbert** [comment]
Fixed, closing
