### ISSUE TITLE
268480218 Comms Contact page (Communications)

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeUKRegProductIssues#1508]
Issue reported by **CommsCoord** at 2023-07-05 09:50:18 UTC
Time: 2023-07-05T09:46:56+00:00
Session ID: 82fd416ae2760f5e22153c9b6aabbbea
Problem Page URL: [/contacts](/contacts)
Previous Page URL: [https://www.freereg.org.uk/manage_resources/new?locale=en](https://www.freereg.org.uk/manage_resources/new?locale=en)
Reported Issue:
Hi. We seem to be having a problem again with which contacts are appearing on the Comms Contact page. I need to have access to the following: Data Question, Website Problem, Enhancement Suggestion and General Comment. The Comms email is getting notice of these items as they come in, but not all appear on the contacts page. Can this be sorted out ASAP. Thanks    

![Screenshot](https://www.freereg.org.uk)

**Comment by DeniseColbert** [comment]
Need to agree which of these contacts should have Sandra (comms coord) as primary recipient

**Comment by DeniseColbert** [comment]
Website/enhancement suggestion should go to Steve
Thank you- no longer there
Data question and General comment should go to Sandra (Comms)

@Vino-S to provide us with a list of a) who gets the emails and copies of emails (cc) and b) where do the Contacts go in the system

**Comment by Vino-S** [comment]
@Vino-S to deploy to production

**Comment by ghost** [comment]
General Comment emails are not coming to Comms.

Case in point, the following contact showed up in the Comms Gmail account, but did not appear in Contacts on FR.  Steve confirmed it was a General Comment so we are still having an issue. Here is the contact:

Dear Communications;

We have received correspondence 279575863 from Nona email [dwintonswift@gmail.com](mailto:dwintonswift@gmail.com) at 19:47 on 2023-11-10.

You are requested to take action on the correspondence preferably using the on-line contact system

The following is the information submitted.

General Comment:

Hello, My great uncle Guy Douglas Winton was not buried at St Mary de Haura Churchyard, New Shoreham, Sussex, England as per your burial entry at https://www.freereg.org.uk/search_records/5a0e29f0f493fd266d345e48/guy-douglas-winton-burial-sussex-new-shoreham-1897-08-03?locale=en Guy Douglas Winton was buried at Mill Lane Cemetery, Shoreham-by-Sea, Adur District, West Sussex, England on 03 Aug 1897. Plot: Section A (Traditional), Row 1, Grave 1. I have been in contact with St Mary de Haura and was informed that Guy Douglas Winton was not buried at their churchyard. An enquiry to the Adur and Worthing Council yielded the location of his grave in Mill Lane Shoreham. Regards, Nona S

The FreeREG Team

@Vino-S could you check this please?

**Comment by Vino-S** [comment]
Hi @CommsCoord 
I have fixed the issue on Live. Could you have a look, please?
I have also provided the action: '**Display Communication Coordinators**' on Your Actions list, which will display the Userids managing the different communications.
Please let me know if further improvement is needed.

**Comment by ghost** [comment]
@Vino-S thank you, all seems to be in order now.

This can be closed

**Comment by DeniseColbert** [comment]
Done; closing
