### ISSUE TITLE
Destroy UserID does not know that I am logged in. (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#151]
Issue reported by **REGManager** at 2015-01-15 17:03:14 UTC
Time: 2015-01-15T17:01:31+00:00
Session ID: 8586669480d97a19d5141a3ff61a89df
Problem Page URL: [/userid_details/5462b41ae937907d70000447](/userid_details/5462b41ae937907d70000447)
Previous Page URL: [http://test2.freereg.org.uk/userid_details/selection?option=Select%20specific%20userid](http://test2.freereg.org.uk/userid_details/selection?option=Select%20specific%20userid)
Reported Issue:
I am trying to delete (destroy) a UserID but when I say OK it says that I must be logged in and takes me back to the home page to log in.  The UserID has not been destroyed.    

![Screenshot](http://test2.freereg.org.uk)

**Comment by Sherlock21** [comment]
I had something very similar earlier this afternoon - trying to delete a church Parish Register. I was logged in ( having navigated to the right point (which is only accessible with a logged in ID) even got the challenge: do you really want to delete this? Then got bombed out with the same msg: you need to be logged in to do this ...or something like that.

**Comment by Captainkirkdawson** [comment]
Yes it appears that all destroy actions are failing for the same reason at all levels. It is caused by Can't verify CSRF token authenticity.

It has only occurred since we introduced styling and I changed the page linkages.

Likely I have done something stupid but have not determined what that is yet!!!!!

**Comment by Sherlock21** [comment]
Any use undoing the styling and having plain black & white - (or brownish grey on off white) in old-fashined table like layout as the green bleeds into the white text and  messes up my eyes after half an hour!

**Comment by Captainkirkdawson** [comment]
Fixed

**Comment by edickens** [comment]
```
Still not working this morning.
  EricD
  _____________________________________
```

Eric J Dickens
FreeREG Chairman
      On 16/01/2015 01:45, Kirk Dawson wrote:

```
  Fixed
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by Sherlock21** [comment]
I had experienced this issue yesterday, as previously noted. So I was please to see it recorded as fixed. And testing it on Destroy a Place name ( from the Unapproved places list for WRY) it DID work correctly for me now, to delete 2 occurrences of Bolton by Bowland. 08:40 GMT  Friday 16 Jan.

**Comment by Captainkirkdawson** [comment]
Sorry Eric forgot to pull it into the server before going to bed
