### ISSUE TITLE
271154536 Website Problem (SIMON TODD)

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeUKRegProductIssues#1512]
Issue reported by **SIMON TODD** at 2023-08-05 08:42:16 UTC
Time: 2023-08-05T08:40:42+00:00
Session ID: 
Problem Page URL: []()
Previous Page URL: [https://www.freereg.org.uk/contacts/new](https://www.freereg.org.uk/contacts/new)
Reported Issue:
I do understand that adverts are needed to help finance the site, but the new way of effectively blocking the site with a car advert is hideous. Could it at least be amended to reduce the time it prevents us from actually using the site?

Si Todd

**Comment by DeniseColbert** [comment]
Vino fixed this on the day of the report; I've replied. Can close.
