### ISSUE TITLE
271866316 Data Question (Philip Perks)

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeUKRegProductIssues#1514]
Issue reported by **Philip Perks** at 2023-08-13 14:25:16 UTC
Time: 2023-08-13T14:13:39+00:00
Session ID: 
Problem Page URL: []()
Previous Page URL: [https://www.freereg.org.uk/contacts/new](https://www.freereg.org.uk/contacts/new)
Reported Issue:
Following on from #271618946

Apology for the original miscommunication.
To clear this up, although my name is spelt PERKS I am now aware that my ancestors originally spelt it PIERKS.
Overtime, the original name PIERKS has mutated into the modern day PERKS
Please xref both names as they are variants.

**Comment by SteveBiggs** [comment]
Reply sent to the researcher about Soundex use. Can be closed.
