### ISSUE TITLE
272561361 Who gets the messages and who just gets copies? (Eric D)

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeUKRegProductIssues#1515]
Issue reported by **REGManager** at 2023-08-21 15:29:21 UTC
Time: 2023-08-21T15:18:43+00:00
Session ID: cf538967e7d82e75a5e01ee81772ac06
Problem Page URL: [/contacts](/contacts)
Previous Page URL: [https://www.freereg.org.uk/manage_resources/new?locale=en](https://www.freereg.org.uk/manage_resources/new?locale=en)
Reported Issue:
Recently I got a message (attached) from a new transcriber who could not set up their password.  It is addrssed to freereg-registration@freereg.org.uk and nobody else seems to have got a copy, although the SC should have got it and dealt with this.  So I dealt with it, even though I had been away and would like to give up this sort of work as I cannot guarantee to give a timely response.
I would find it very useful to have a document, perhaps in the Help, listing all the emails generated by the server, who they are addressed to, and who gets copies.
Also, I still find it difficult to know which message system has been used for the message.  Contact (Contact us?), Message System, Communicate, Report a Problem and so on.  What did the transcriber use to create the attached message?
Eric D
https://www.freereg.org.uk/uploads/feedback/screenshot/64e382d1f493fd539cd0b3ea/Capture.JPG    

![Screenshot](https://www.freereg.org.uk)

**Comment by SteveBiggs** [comment]
The volunteer simply replied directly to the registration email from the FreeREG system and only Eric is set up to receive any emails to the system. This needs to be changed.

**Comment by DeniseColbert** [comment]
Denise and Vino to check with lemon if these can be no reply with info.

**Comment by DeniseColbert** [comment]
@lemon-ukgen can we chat about this on Monday too?

**Comment by DeniseColbert** [comment]
@lemon-ukgen is working on this

**Comment by lemon-ukgen** [comment]
Mails sent to the following addresses will generate an immediate delivery failure with the message "This is a no-reply address. Please consult the original mail for the appropriate addressee."

```
noreply@freebmd.org.uk
noreply@freecen.org.uk
noreply@freereg.org.uk
noreply@freeukgen.org.uk
no-reply@freebmd.org.uk
no-reply@freecen.org.uk
no-reply@freereg.org.uk
no-reply@freeukgen.org.uk
```

So the apps should set one of those as their mail's From address

(Specifically, the envelope-from address, rather than the header-from address. Looking at Devise, ActionMailer and `mail` gems it looks like these should be the same, and therefore ok. But worth testing.)

**Comment by DeniseColbert** [comment]
Done, closing
