### ISSUE TITLE
272822120 Enhancement Suggestion (Julie Stewart)

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeUKRegProductIssues#1516]
Issue reported by **Julie Stewart** at 2023-08-24 15:55:20 UTC
Time: 2023-08-24T15:47:55+00:00
Session ID: 
Problem Page URL: []()
Previous Page URL: [https://www.freereg.org.uk/contacts/new](https://www.freereg.org.uk/contacts/new)
Reported Issue:
I would LOVE a search that allows for two surnames (along with all of the varieties). I have been TRYING to google search for incidences of Gage and Jermyn, but the variant spellings are killing my confidence in the results. Your awesome site has the best variant results I've seen, and a two-surname search option would be fantastic!  

I will be volunteering once I recover from hand surgery. Cheers, Julie

**Comment by SteveBiggs** [comment]
Question sent to the researcher on whether they are referring specifically to marriage records.

**Comment by DeniseColbert** [comment]
@SteveBiggs did you hear back from the researcher? Would you like @CommsCoord to pick this up?

**Comment by SteveBiggs** [comment]
No, I never heard back so would be happy for Sandra to follow up please.

**Comment by ghost** [comment]
@SteveBiggs do you have her email address? I cannot find her as with a userid on the website.

**Comment by SteveBiggs** [comment]
She's a researcher not a member. I replied within the Contacts system but here email is recorded as printme@aol.com.

**Comment by ghost** [comment]
Makes sense. Thanks for the email addy.

Emailed Julie this morning and will await reply

**Comment by ghost** [comment]
No reply from researcher. Since on cards since Aug perhaps this should be closed for lack of activity?

**Comment by DeniseColbert** [comment]
Done; closing
