### ISSUE TITLE
273412514 Website Problem (B. Perry)

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeUKRegProductIssues#1517]
Issue reported by **B. Perry** at 2023-08-31 11:55:14 UTC
Time: 2023-08-31T11:52:17+00:00
Session ID: 
Problem Page URL: []()
Previous Page URL: [https://www.freereg.org.uk/contacts/new](https://www.freereg.org.uk/contacts/new)
Reported Issue:
Website on freereg is very very slow to load anything, search anything and even get on the site. even had problem submitting this form. Been like it for some days now. Not my internet or computer as no problems using your other websites
Thanks

**Comment by DeniseColbert** [comment]
No longer an issue, closing
