### ISSUE TITLE
277308111 Reply not going to Comms Messages or email (Communications)

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeUKRegProductIssues#1518]
Issue reported by **CommsCoord** at 2023-10-15 14:01:51 UTC
Time: 2023-10-15T13:51:33+00:00
Session ID: 8c124c652852b314c5f57e66ba19e804
Problem Page URL: [/messages/652a90a3f493fd39ebf983f2/show_reply_message?locale=en&source=reply](/messages/652a90a3f493fd39ebf983f2/show_reply_message?locale=en&source=reply)
Previous Page URL: [https://www.freereg.org.uk/messages/652517c7f493fd262c74606b/reply_messages?locale=en&source=reply](https://www.freereg.org.uk/messages/652517c7f493fd262c74606b/reply_messages?locale=en&source=reply)
Reported Issue:
A message had been sent out via messages when I responded to it, emails were sent to both the contact and the Comms email. However, the contact replied to say thanks, and the reply was sent to Eric, not to Comms messages or email. 

As a side note, when I respond to a contact, I not only see it in Comms messages but also I get an email of the reply. I don't need it in two places, and it never used to go to the emails. This also applies to responses from the other county coords, I get notifications in messages and by email. I have to remove them in two spots now. I don't understand what has happened.
https://www.freereg.org.uk/uploads/feedback/screenshot/652bf0cff493fd4f9979cc3c/Screenshot_Comms_FR_page.jpg    

![Screenshot](https://www.freereg.org.uk)

**Comment by ghost** [comment]
Screenshot of the original response to contact and then the reply that bypassed Comms and went to Eric instead.

![Screenshot Comms FR page](https://github.com/FreeUKGen/FreeUKRegProductIssues/assets/20557838/220fb3e0-0346-41ec-97a1-b5d96b6c335c)
![Response with reply](https://github.com/FreeUKGen/FreeUKRegProductIssues/assets/20557838/a792580a-fe53-41d1-9e0a-691e0f1d8b25)

**Comment by DeniseColbert** [comment]
This is similar to the story in Needs review for a No-Reply email address and guidance in automated emails about how to reply.

**Comment by ghost** [comment]
I did a test today on the contacts form for an unrelated matter and I got an email back saying do not reply to this email address, so I think this problem may be resolved.

**Comment by ghost** [comment]
I should add that the 'Do Not Reply' email was on a contact for a data problem. I sent a message by clicking on the report a problem button so I think we need add the Do not reply to those emails as well. @Vino-S is this something we can do?

**Comment by DeniseColbert** [comment]
@CommsCoord to send this (or a replicated email) to Denise to help inform lemon's work

**Comment by ghost** [comment]
![image](https://github.com/FreeUKGen/FreeUKRegProductIssues/assets/20557838/f7c81018-322f-4a11-906e-26378555c64e)

Here is a copy of an email as requested. @DeniseColbert I forwarded this to you also as requested

**Comment by DeniseColbert** [comment]
@CommsCoord could you send me the info about the sending of the email, similar to this?

![image](https://github.com/FreeUKGen/FreeUKRegProductIssues/assets/19173257/431b10c1-474e-4e81-be64-579c0440b435)

You can reach it via the downward pointing triangle next to "to me"

**Comment by ghost** [comment]
@DeniseColbert  @Vino-S 

Unable to replicate the exact email, but came close. This was done via the Report A Problem button. Generated holding email does not contain a Do Not Reply. 

![image](https://github.com/FreeUKGen/FreeUKRegProductIssues/assets/20557838/19e3643c-2d96-41ef-9941-ce2be34d1eb1)

Here is the pointing triangle as requested:

![image](https://github.com/FreeUKGen/FreeUKRegProductIssues/assets/20557838/a46d9313-85b5-40e2-9a06-2ce1ae32a846)

**Comment by DeniseColbert** [comment]
This should be solved by moving to the no-reply email address

**Comment by Sandra-AW** [comment]
I think this has been sorted and can be closed
