### ISSUE TITLE
an issue with uploading batch: case gets changed in Place name (ericb)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#152]
Issue reported by **ericb** at 2015-01-17 12:13:10 UTC
Time: 2015-01-17T12:08:42+00:00
Session ID: af4b6793417aec020d2f7262c95b2f45
Problem Page URL: [/freereg1_csv_entries](/freereg1_csv_entries)
Previous Page URL: [http://test2.freereg.org.uk/freereg1_csv_files/54ba50a6e937903c8b000003](http://test2.freereg.org.uk/freereg1_csv_files/54ba50a6e937903c8b000003)
Reported Issue:
This file is for place name Alsop en le Dale. no hyphens and only the 1st and 4th word start with caps.
but when I upload it, it gets changed so that en becomes En. And then its creating a place name which is Not Approved.
the correct place name is: Alsop en le Dale.

When files are uploaded in the normal F1 to FR2 upload, the same happens there.    

![Screenshot](http://test2.freereg.org.uk/tmp/carrierwave/1421496790-38464-0303/DBYALDMA1.csv)

**Comment by edickens** [comment]
```
I suggest we do not assume any
  capitalisation or hyphenation because in due course Places (and
  Churches) will be validated against the Server version so whatever
  the CC enters will be the standard.
  EricD
  _____________________________________
```

Eric J Dickens
FreeREG Chairman
      On 17/01/2015 12:13, FreeUKGenIssues wrote:

```
  Issue reported by ericb at 2015-01-17
    12:13:10 UTC
    Time: 2015-01-17T12:08:42+00:00
    Session ID: af4b6793417aec020d2f7262c95b2f45
    Problem Page URL: /freereg1_csv_entries
    Previous Page URL: http://test2.freereg.org.uk/freereg1_csv_files/54ba50a6e937903c8b000003
    Reported Issue:
    This file is for place name Alsop en le Dale. no hyphens and
    only the 1st and 4th word start with caps.
    but when I upload it, it gets changed so that en becomes En. And
    then its creating a place name which is Not Approved.
    the correct place name is: Alsop en le Dale.
  When files are uploaded in the normal F1 to FR2 upload, the
    same happens there. 

  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by Sherlock21** [comment]
I think some confusion with the words. do you mean that the program when validating incoming place name should ignore case and hyphens other syntax?

Place name wont be put there ( in the Location fields) by the CC - its there now by me, from the old MPN table unless I have edited it since. Missing place names now give rise to the batch going into a list that is separate from the Approved Places  so we can more easily find and deal with.

Church names do need validating. People type any old lazy rubbish even if given the correct name.
Church names that are not in the Church Name table at the time of upload ( as that's a more dynamic position at present) will create a new church name to match the incoming file.

I am just testing out the latest rewrite as you know. And the philosophy is somewhat different to pervious methods of who and what can be done.

**Comment by edickens** [comment]
```
No, I think validation should be exact,
  by case and punctuation.  Yes, you are the only one to put in new
  places, but I want CCs to put in new Churches, without any changes
  to capitalisation or punctuation, before transcriptions are
  uploaded, then they can be validated exactly too.  We have to have
  the present system of creating Churches until we have gone live,
  then we can insist that transcriptions match.
  EricD
  _____________________________________
```

Eric J Dickens
FreeREG Chairman
      On 17/01/2015 12:46, Sherlock21 wrote:

```
  I think some confusion with the words. do you mean that the
    program when validating incoming place name should ignore case
    and hyphens other syntax?
  Place name wont be put there ( in the Location fields) by the
    CC - its there now by me, from the old MPN table unless I have
    edited it since. Missing place names now give rise to the batch
    going into a list that is separate from the Approved Places so
    we can more easily find and deal with.
  Church names do need validating. People type any old lazy
    rubbish even if given the correct name.
    Church names that are not in the Church Name table at the time
    of upload ( as that's a more dynamic position at present) will
    create a new church name to match the incoming file.
  I am just testing out the latest rewrite as you know. And the
    philosophy is somewhat different to pervious methods of who and
    what can be done.
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by Captainkirkdawson** [comment]
Have added en to list of words that are not capitalized.
List is now 
"a", "an", "and", "at", "but", "by", "cum", "de", "en" ,"for", "has", "in", "la", "le", "near", "next", "nor", "nr", "or", "on", "of", "so", "the", "to", "von", "with", "yet", "y"

**Comment by Sherlock21** [comment]
I wondered how you did this trick!
If you add: "under" to the list, that should be all of them then.

**Comment by Captainkirkdawson** [comment]
Done

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Sherlock21** [comment]
In the cold light of day this morning, I realise we might not have got this one totally cracked - depending on how your code works.
We have plenty of Place names which use the middle words as in your list of "don't Capitalize"
BUT this is England! and we have some  like  "by" or "under" or "De" which do NEED to be Capitalized sometimes and sometimes are NOT. eg Newcstle upon Tyne but Kingston Upon Thames
or Woolsthorpe By Belvoir but Weston by Welland

If the Place name contains hyphens then sometimes the following words are Capitalized and sometimes not. eg Berwick-Upon-Tweed but Newark-on-Trent

So it depends upon how you do this.
If we were to say: on import of the batch, leave the case & syntax as typed by the transcriber, and if it matches exactly to the Place names Table, then all is well - add to normal collection,

If any of the incoming words in the Place name do  not exactly match, then import but create a new place name and mark it in red like you do for the Not Approved Place.  And the CC and or me will have to sort them out.

Do you have any idea of how many batches in an upload do have their place name corrected by this process?

Lets discuss in detail before you do this one though dont you think

**Comment by Captainkirkdawson** [comment]
I would far prefer to leave all names unadjusted for exactly the reasons you state. There are exceptions to the rules.
We introduced the code because the content of the existing files was such a mishmash of spellings.
Internally I actually downcase all place church names etc and do comparisons at the downcased level otherwise the system really would not work. (FR1 did the same) 
I suggest that this is part of a new story Place Name Validation. As you are say we would need to research the implications before making any change.

**Comment by Sherlock21** [comment]
Right. And EricD has quite different views to mine. So lets close this topic now and put up with what we have. Anyone who is of a mind can correct their Placenames now if they wish.
And i will raise a new  topic of Validation of Place Name and Church Name for the whole scenario, as you suggest.

One last query please? do the record details on any Placenames that carry the red code for Not Approved, feature in any data searches?

**Comment by Captainkirkdawson** [comment]
eric

Likely not in a radius search as they have the tower of London location.

As for the specific location perhaps I do not know.

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Sherlock21** [comment]
K

Ok drat - I forgot that! Tower of London element.

i will go find some records from one of the red places, and do a search.

End of exchange unless i find another issue!

E
