### ISSUE TITLE
283091663 Destroy is not working (Eric D)

### ISSUE THREAD

**Issue by FreeREGcomputer** [FreeUKGen/FreeUKRegProductIssues#1520]
Issue reported by **REGManager** at 2023-12-21 12:34:23 UTC
Time: 2023-12-21T12:26:34+00:00
Session ID: 2695491a9c1ece826be5ab1079c67a72
Problem Page URL: [/userid_details/5d7ca4f5f493fd2b73feec7e?locale=en](/userid_details/5d7ca4f5f493fd2b73feec7e?locale=en)
Previous Page URL: [https://www.freereg.org.uk/userid_details?locale=en](https://www.freereg.org.uk/userid_details?locale=en)
Reported Issue:
SysAdmin can delete UserIDs which are in the To be destroyed syndicate.  These are ones with no files and been inactive for ages.
But to do this I have to select Show then Destroy then a Red Something went wrong screen comes up.
 
https://www.freereg.org.uk/uploads/feedback/screenshot/658430cff493fddc892d01bc/Capture.JPG    

![Screenshot](https://www.freereg.org.uk)

**Comment by SteveBiggs** [comment]
It would also be useful to have a button "Delete All" to save Eric's time.

**Comment by edickens** [comment]
I'm not too bothered about a Delete all because I like to look at each to make sure there are no batches and only Delete those from a few years ago.  But if I remember correctly, when it was working, after each delete it went back to My Actions and I had to Manage Syndicate and a lot more before I found the next one to delete.  So after a successful deletion it needs to go back to List UserIDs and preferably the next one in the list.

**Comment by DeniseColbert** [comment]
Bulk delete with checkboxes is a future story.

@Vino-S to look at feature not working

**Comment by Vino-S** [comment]
Ready for testing in test3

**Comment by DeniseColbert** [comment]
Bug fixed: Vino to add the path for testing (UserID, link)

**Comment by Vino-S** [comment]
#List Userids after successful deletion: Deployed to production
Added Destroy action in the Userids Listing: Ready for testing in test3
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEZaQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9336ea5b671ec3f711c5fee46a71cdcf9ecc00b9/image.png" alt="image.png" />

The Destroy is only available for To Be Destroyed syndicate

**Comment by DeniseColbert** [comment]
@edickens to test in Test 3

**Comment by edickens** [comment]
Still not working.
<img width="1392" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMS9hQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--51214adbc214b100fb29627b528c199072b0853a/Capture.JPG" alt="Capture.JPG" />
Selecting Destroy does something and come back to this screen, but the UserID is still there.
This screen shows the Destroy button, and on selection asks "Are you sure", but it is still there..
<img width="1382" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnJhQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c7d02a088ea587d1a53726290d587589f400589a/Capture1.JPG" alt="Capture1.JPG" />

**Comment by edickens** [comment]
My mistake?  The reason for not destroying is that the UserID I was trying to delete was EricHunts.  It has a "Last upload" date and I think that is blocking the delete, but there is no error report to say that the delete was unsuccessful.  Also, provided there are no Files, then the UserID can be deleted even if there is a date.

**Comment by edickens** [comment]
A thought?  These UserIDs, because they have a "Last upoad" date, most likely have files stored in the Attic.  The files for these UserIDs have most likely been moved to another UserID, but the Attic will not have been changed.  However, I thnk the Attic entry can be deleted together with the UserID.

**Comment by ghost** [comment]
@edickens you can try this on WalesSweet on the live site if you like. Their files are safe with another userID.

**Comment by ghost** [comment]
This has been sorted. Deleting the attic files then allows the userID to be destroyed. This can be closed

**Comment by DeniseColbert** [comment]
Closing
