### ISSUE TITLE
283124942 Cannot delete File (Stephen)

### ISSUE THREAD

**Issue by FreeREGcomputer** [FreeUKGen/FreeUKRegProductIssues#1521]
Issue reported by **SBManager** at 2023-12-21 21:49:02 UTC
Time: 2023-12-21T21:47:11+00:00
Session ID: 90ce6adde076a3481d132b79fd3912a3
Problem Page URL: [/physical_files/waiting_to_be_processed](/physical_files/waiting_to_be_processed)
Previous Page URL: [https://www.freereg.org.uk/physical_files/select_action](https://www.freereg.org.uk/physical_files/select_action)
Reported Issue:
When I try to delete or do anything with the file GLACBABA2 from the processing queue I get the red error message "Something went wrong ....."    

![Screenshot](https://www.freereg.org.uk)

**Comment by DeniseColbert** [comment]
Just seems to be this file; Vino to take a look

**Comment by SteveBiggs** [comment]
I have deleted several files today and all works fine now.
