### ISSUE TITLE
283698195 Data Problem (Kate)

### ISSUE THREAD

**Issue by FreeREGcomputer** [FreeUKGen/FreeUKRegProductIssues#1522]
Issue reported by **Kate** at 2023-12-28 13:03:15 UTC
Time: 2023-12-28T13:00:43+00:00
Session ID: 
Problem Page URL: [https://www.freereg.org.uk/search_records/5891ecabf493fd8f169a503c/-burial-sussex-sutton-1727-09-01?locale=en](https://www.freereg.org.uk/search_records/5891ecabf493fd8f169a503c/-burial-sussex-sutton-1727-09-01?locale=en)
Previous Page URL: [https://www.freereg.org.uk/contacts/5891ecabf493fd8f169a503c/report_error?locale=en&query=658d70d3865574c46667349f](https://www.freereg.org.uk/contacts/5891ecabf493fd8f169a503c/report_error?locale=en&query=658d70d3865574c46667349f)
Reported Issue:
Hello :) I hope you are well. 

I've contacted you using the link on one result page, but the issue seems to be for a whole dataset. I've just searched for records in Sutton, Cambridgeshire, but I'm getting results for Sutton, Sussex. 

Best wishes,
Kate

**Comment by SteveBiggs** [comment]
This would appear to be the same problem as in issue #2683

**Comment by DeniseColbert** [comment]
Captured in other story so closing

**Comment by DeniseColbert** [comment]
@CommsCoord could you test this in light of #2683?

**Comment by Sandra-AW** [comment]
I did a similar search to Kate's and all looks well in Test3.
![image](https://github.com/FreeUKGen/FreeUKRegProductIssues/assets/163754895/a8ddbff5-45e6-498d-b8d3-82238022032a)

**Comment by DeniseColbert** [comment]
Vino to investigate if the system could run the cleaning effect every 6 months in a way doesn't impact the system too much.

**Comment by DeniseColbert** [comment]
Done, closing
