### ISSUE TITLE
289760528 A Snag editing multiple place names in same County (Eric)

### ISSUE THREAD

**Issue by FreeREGcomputer** [FreeUKGen/FreeUKRegProductIssues#1524]
Issue reported by **ericb** at 2024-03-07 17:02:08 UTC
Time: 2024-03-07T16:57:19+00:00
Session ID: a81f39617d71c9118938b5f8e99964dd
Problem Page URL: [/manage_resources/new?locale=en](/manage_resources/new?locale=en)
Previous Page URL: [https://www.freereg.org.uk/cms/refinery/login](https://www.freereg.org.uk/cms/refinery/login)
Reported Issue:
As Data Manager, I create and maintain the Place Names index for FreeReg.

When creating a new Place Name in a County, I check to find out if there is no duplication of the same name (also with a church}, in that County concerned. If there is more than one, I distinguish by the addition of (Nr Aaa) after the name. -and (Nr Bbbb and so on if more than 1 duplicate)
This has worked well up to now. 
But It now happens that there is that such a duplication of place name in GLS where the original name - Staunton had a church that already had some records in the Images system.
And Now, a second occurrence of the place name Staunton has been found in GLS 
so I would normally backtrack and add the customary appendix making the place name Staunton (Nr Colford). and create the newly found place name Staunton (Nr Newent).

However, because of the existence of the link to the Images Register, I cannot do that to the existing place name.

Please fix this situation so I can alter the present place name Staunton.

Having thought about the problem, I suggest the most useful software change would be 
to permit me to EDIT the existing place name - whether or not it has the links to the Images Register- then having changed the Place Name, the links if any could be revised overnight.

Or of course you may see a better way forward.
    

![Screenshot](https://www.freereg.org.uk)

**Comment by edickens** [comment]
At present the only way to sort this out is to download the images, if they are not already available on someone's computer, then upload into the newly named Place, then Delete them (SysAdmin Action) from where they are now.  But if the images are already mixed in one Place, then it is best to use the Move Action to get them into Image Groups identifying the new Place name.  Images can only be moved between Image Groups within a Source.  The best thing, of course, is to create the new style Place name before any images are uploaded.  This also goes for the transcriptions which have to have the new style place name.  ED

**Comment by edickens** [comment]
Hi Eric B,
I see that there are no Images uploaded for Staunton and it looks as if you have moved all the transcriptions out of Staunton.  So the problem now is to delete Staunton, which has no Appendix.  This I have now done, including the image server.  I have left Staunton (No Church) for you to delete.  If you cannot, let me know.  ED

**Comment by Sherlock21** [comment]
Hi, Eric D

Thank you for the help.
Doreen has downloaded the existing files i think, and thus made the way clear for us each to remove bits.

so I have now removed the ‘just Stanton’ ok.

incidentally, Kirk did not do a clean REMOVE of any place names - he just set the code into a limbo state of not visible or something like that, It does make it hard if i use those letters in some new name though I seem to recall.

However: it might never cone to needing to do that.

Thanks for your help.

Eric B
On 13 Mar 2024, at 13:37, Eric Dickens ***@***.***> wrote:


Hi Eric B,
I see that there are no Images uploaded for Staunton and it looks as if you have moved all the transcriptions out of Staunton. So the problem now is to delete Staunton, which has no Appendix. This I have now done, including the image server. I have left Staunton (No Church) for you to delete. If you cannot, let me know. ED

**Comment by edickens** [comment]
This can be closed
