### ISSUE TITLE
291633440 UserID ManCity1 reports unable to view county (Fr)

### ISSUE THREAD

**Issue by FreeREGcomputer** [FreeUKGen/FreeUKRegProductIssues#1525]
Issue reported by **FR Exec Lead** at 2024-03-29 09:17:20 UTC
Time: 2024-03-29T08:42:42+00:00
Session ID: db68e13bc8caef0612439675e4756e33
Problem Page URL: [/userid_details/list_users_handle_communications](/userid_details/list_users_handle_communications)
Previous Page URL: [https://www.freereg.org.uk/physical_files/select_action](https://www.freereg.org.uk/physical_files/select_action)
Reported Issue:
Jo reports that she is not able to see the Manage County(ies) button from this page, but can view all syndicates. UserUD ManCity1 was a new userID created when another userID, ManCity, was experiencing issues. Roles were moved about and all appeared to be well, but is now experiencing more issues. 
https://www.freereg.org.uk/uploads/feedback/screenshot/66068721f493fdc9c5ef046b/Jo_screenshot.jpg    

![Screenshot](https://www.freereg.org.uk)

**Comment by edickens** [comment]
ManCity1 has a secondary role of County Coordinator and shows the counties coordinated so should have this action.

**Comment by Sandra-AW** [comment]
Here is her screenshot where she can get to the syndicate but the Manage county button is missing under Actions:

![image](https://github.com/FreeUKGen/FreeUKRegProductIssues/assets/163754895/93c9f3f7-ad80-4ccc-8f6f-9c3b911ada1d)

**Comment by Sandra-AW** [comment]
She also reports she can view all syndicates, but this is not something she should be able to do:
![image](https://github.com/FreeUKGen/FreeUKRegProductIssues/assets/163754895/f355f1ff-7da1-454f-87eb-383780c46a84)

**Comment by DeniseColbert** [comment]
Fix implemented closing
