### ISSUE TITLE
292851702 Review specific batch missing CC action. (Ali)

### ISSUE THREAD

**Issue by FreeREGcomputer** [FreeUKGen/FreeUKRegProductIssues#1526]
Issue reported by **alsibk** at 2024-04-12 11:41:42 UTC
Time: 2024-04-12T11:39:35+00:00
Session ID: 1d0ee36dde4d615e8757954a381013b2
Problem Page URL: [/freereg1_csv_files/65af9bd6f493fd35d2bd0506](/freereg1_csv_files/65af9bd6f493fd35d2bd0506)
Previous Page URL: [https://www.freereg.org.uk/manage_counties/selection?option=Review%20Specific%20Batch](https://www.freereg.org.uk/manage_counties/selection?option=Review%20Specific%20Batch)
Reported Issue:
Please could we have Lock/Unlock option in in Review specific batch.    

![Screenshot](https://www.freereg.org.uk)

**Comment by Sandra-AW** [comment]
Ali emailed today and asked this request be cancelled. Closing
