### ISSUE TITLE
298220259 Change wording on Move to Inactive Syndicate  (Exec Lead)

### ISSUE THREAD

**Issue by FreeREGcomputer** [FreeUKGen/FreeUKRegProductIssues#1528]
Issue reported by **FR Exec Lead** at 2024-06-13 14:57:39 UTC
Time: 2024-06-13T14:55:19+00:00
Session ID: 7bebe49cc3a9d6e249a9a1a42ddadf8a
Problem Page URL: [/feedbacks](/feedbacks)
Previous Page URL: [https://www.freereg.org.uk/userid_details/5659b272f493fdb47e000289?locale=en](https://www.freereg.org.uk/userid_details/5659b272f493fdb47e000289?locale=en)
Reported Issue:
Can the wording on the button be changed to something like Move to Destroy syndicate?  The button is confusing to coordinators who sometimes mistake with simply making a user inactive
https://www.freereg.org.uk/uploads/feedback/screenshot/666b08e3b18f7c7caa44fb5f/Inactive_Syndicate.jpg    

![Screenshot](https://www.freereg.org.uk)

**Comment by DeniseColbert** [comment]
Sandra to test in test3

**Comment by Sandra-AW** [comment]
Shows in test3 as 'Move to Destroy Syndicate'. Ready to be moved to Live
