### ISSUE TITLE
re creating a new approved place name  - Ridgeway SK402812 (ericb)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#153]
Issue reported by **ericb** at 2015-01-17 14:32:30 UTC
Time: 2015-01-17T14:26:15+00:00
Session ID: af4b6793417aec020d2f7262c95b2f45
Problem Page URL: [/places/53ce1fd9eca9ebd90c0e98cd](/places/53ce1fd9eca9ebd90c0e98cd)
Previous Page URL: [http://test2.freereg.org.uk/places?page=13](http://test2.freereg.org.uk/places?page=13)
Reported Issue:
There is an unapproved place DBY/ Ridgeway. it has a church and file attacked, from an upload.
But its Not Approved.

So I tried to create a new place name with correct gridref SK402812 ( then SK4081 on second attempt as one had to in the early days) 
First fail I just got msg: unsuccessful.

After the second try  & fail, with 4 digit GridRef, I got: Already exists - but it doesn't in All Places
A fresh full list view only lists the Not Approved one.
I could try delete the Batch & church from the unappoved version, then delete the place name. But that seems wrong way round.

![Screenshot](http://test2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
An interesting one. Ridgeway is not an approved place name in DBY. Hence any file uploaded with that will be unapproved. This is the correct action. You attempt to create an approved place name of Ridgeway but the system will not permit it because it sees the unapproved name. OK I see the solution.

**Comment by Captainkirkdawson** [comment]
You are now permitted to create a new Place even if there was one of the same name that was unapproved.

**Comment by Sherlock21** [comment]
Is that fix uploaded yet please?

**Comment by Captainkirkdawson** [comment]
Totally unable to duplicate the issue.

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Sherlock21** [comment]
Well I have no idea why either but until you put in the fix to let me make a new place while there existed an Un Approved one with the same County/ Placename, I could repeat the problem it all day long.

Have now created a new Approved place Ridgeway, with the 4 digit GR. I will now edit it up to 6 digits, then go move the batch into the (now) Approved correct place, then clean up, as demo.

Thanks.

**Comment by Captainkirkdawson** [comment]
Ah are there may  be a lead there

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1
