### ISSUE TITLE
303226246 test (Sk)

### ISSUE THREAD

**Issue by FreeREGcomputer** [FreeUKGen/FreeUKRegProductIssues#1531]
Issue reported by **FR Exec Lead** at 2024-08-10 13:30:46 UTC
Time: 2024-08-10T13:29:37+00:00
Session ID: 135cd6a619229ed21c35c48c3ab23075
Problem Page URL: [/manage_resources/new?locale=en](/manage_resources/new?locale=en)
Previous Page URL: [https://test3.freereg.org.uk/cms/refinery/login](https://test3.freereg.org.uk/cms/refinery/login)
Reported Issue:
testing for github issue    

![Screenshot](https://test3.freereg.org.uk)

**Comment by Sandra-AW** [comment]
Closed. This was a test only
