### ISSUE TITLE
304861121 Testing of Communicate system (Communications)

### ISSUE THREAD

**Issue by FreeREGcomputer** [FreeUKGen/FreeUKRegProductIssues#1534]
Issue reported by **CommsCoord** at 2024-08-29 11:38:41 UTC
Time: 2024-08-29T11:34:13+00:00
Session ID: cab64ac2ce19d438b1edb5a5ea0a6855
Problem Page URL: [/messages/select_individual?id=66d05bc8b18f7c091c66a822&locale=en&role=county_coordinator](/messages/select_individual?id=66d05bc8b18f7c091c66a822&locale=en&role=county_coordinator)
Previous Page URL: [https://www.freereg.org.uk/messages/66d05bc8b18f7c091c66a822/select_role?locale=en&source=original](https://www.freereg.org.uk/messages/66d05bc8b18f7c091c66a822/select_role?locale=en&source=original)
Reported Issue:
When choosing whom to send messages to in Communicate, when a role is chosen (such as county coordinator), there are former coordinators listed rather than the current,  and people in roles who are no longer with us. Is there any way we can have a clean up/clear out to make sure we have the right people against the right roles?
https://www.freereg.org.uk/uploads/feedback/screenshot/66d05dc1b18f7c091c66b63d/CC_list_in_Commumicate.jpg    

![Screenshot](https://www.freereg.org.uk)

**Comment by Sandra-AW** [comment]
. I checked all the roles and everything is present and correct. This story can be closed.
