### ISSUE TITLE
303473283 Move multiple images does not work for me (Janelle)

### ISSUE THREAD

**Issue by FreeREGcomputer** [FreeUKGen/FreeUKRegProductIssues#1536]
Issue reported by **Janelle** at 2024-08-13 10:08:03 UTC
Time: 2024-08-13T09:58:05+00:00
Session ID: b1a1fc8ce91d56b2b07ababb42e8ecba
Problem Page URL: [/image_server_images/66b60485b18f7c12933442a1/index?locale=en](/image_server_images/66b60485b18f7c12933442a1/index?locale=en)
Previous Page URL: [https://www.freereg.org.uk/image_server_groups/66b60485b18f7c12933442a1?locale=en](https://www.freereg.org.uk/image_server_groups/66b60485b18f7c12933442a1?locale=en)
Reported Issue:
I have uploaded 30 BU images to the wrong image group and I want to move over to the correct group. When I select them and the proper group, and hit submit, I get blue successful message, but nothing has actually happened. I have also tried to delete both image groups and get again the blue successful message but nothing happened. The files are in Petton PR GR 1701 to 1812, but should be in Petton PR BU 1813 to 1933.  Thankyou,  Janelle
https://www.freereg.org.uk/uploads/feedback/screenshot/66bb3083b18f7cb654d33918/Screenshot_2024-08-13_200419.png    

![Screenshot](https://www.freereg.org.uk)

**Comment by Sandra-AW** [comment]
Issue is no longer a problem per contact. Closing
