### ISSUE TITLE
302348445 FreeREG Policy Action (Eric D)

### ISSUE THREAD

**Issue by FreeREGcomputer** [FreeUKGen/FreeUKRegProductIssues#1537]
Issue reported by **REGManager** at 2024-07-31 09:40:45 UTC
Time: 2024-07-31T09:38:34+00:00
Session ID: 78d37caab4c28ec0278909adeaee91de
Problem Page URL: [/manage_resources/new?locale=en](/manage_resources/new?locale=en)
Previous Page URL: [https://www.freereg.org.uk/cms/refinery/login](https://www.freereg.org.uk/cms/refinery/login)
Reported Issue:
Not in Alphabetical sequence.
https://www.freereg.org.uk/uploads/feedback/screenshot/66aa069db18f7c7b9bb609bb/Capture.JPG    

![Screenshot](https://www.freereg.org.uk)

**Comment by DeniseColbert** [comment]
Done, closing
