### ISSUE TITLE
305639239 URGENT - Sites stats are not being recorded (Exec Lead)

### ISSUE THREAD

**Issue by FreeREGcomputer** [FreeUKGen/FreeUKRegProductIssues#1539]
Issue reported by **FR Exec Lead** at 2024-09-07 11:47:19 UTC
Time: 2024-09-07T11:44:31+00:00
Session ID: 2a582b3c94f227ba9c7c02615245f63d
Problem Page URL: [/site_statistics](/site_statistics)
Previous Page URL: [https://www.freereg.org.uk/manage_resources/new?current_role=system_administrator&locale=en](https://www.freereg.org.uk/manage_resources/new?current_role=system_administrator&locale=en)
Reported Issue:
Site stats have not been recorded since 18-8-24. I don't know if this has affected counties' day-to-day recording.
https://www.freereg.org.uk/uploads/feedback/screenshot/66dc3d47b18f7c41422431ab/stats.jpg    

![Screenshot](https://www.freereg.org.uk)

**Comment by Sandra-AW** [comment]
Accidentally added as story when there was no need. Closing
