### ISSUE TITLE
deleting a batch failed (ericb)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#154]
Issue reported by **ericb** at 2015-01-17 21:06:40 UTC
Time: 2015-01-17T21:01:36+00:00
Session ID: 6b840cd79225e65e8c00713b95af46ee
Problem Page URL: [/freereg1_csv_files/5463ad3ce937904abbeeb3bc](/freereg1_csv_files/5463ad3ce937904abbeeb3bc)
Previous Page URL: [http://test2.freereg.org.uk/registers/5409de4beca9eba206437519](http://test2.freereg.org.uk/registers/5409de4beca9eba206437519)
Reported Issue:
Deleting the batch: DBYRIDMA.csv - accessing it from Display  Batch tab.
Seemed to be going OK, but taking a while. only 450 records in it.

Then it crashed. error display attached.    

![Screenshot](http://test2.freereg.org.uk/tmp/carrierwave/1421528800-23006-3869/Screen_shot_2015-01-17_at_21.03.03.jpg)

**Comment by Captainkirkdawson** [comment]
The delete was trying to clean up the Register/Church/Place chain and failed when it tries to delete the Place. I had not rewritten the file level as I thought it worked. Clearly not. 

Have reverted to KISS at this level too. Batch delete now just deletes the batch and its associated entries and search records. It leaves the Chain above untouched.

**Comment by Sherlock21** [comment]
Fine. I will remember this logic. thanks.
