### ISSUE TITLE
305562839 WinREG install failure (Alun)

### ISSUE THREAD

**Issue by FreeREGcomputer** [FreeUKGen/FreeUKRegProductIssues#1540]
Issue reported by **Alun_George** at 2024-09-06 14:33:59 UTC
Time: 2024-09-06T14:29:17+00:00
Session ID: f8d500700f0625c4c807239f3f0c3272
Problem Page URL: [/cms/information-for-transcribers](/cms/information-for-transcribers)
Previous Page URL: [https://www.freereg.org.uk/manage_resources/new?locale=en](https://www.freereg.org.uk/manage_resources/new?locale=en)
Reported Issue:
I have recently had a disc issue and I am having to reinstall many of my apps. When installing FreeREG it stops and I get the message "Error writing to file C:\ProgramFiles(x86)\FreeREG\WinReg for Windows\WPFToolkit.dll Verify you have access to that directory". I can find no way of getting past this point.    

![Screenshot](https://www.freereg.org.uk)

**Comment by stsccfr** [comment]
I corresponded with Alun and learned that he has resolved the problem himself.  He said he had an older installation that he was still able to use. This case can be closed.
