### ISSUE TITLE
306025232 New Embargo rules for Derbyshire not working ? (Janelle)

### ISSUE THREAD

**Issue by FreeREGcomputer** [FreeUKGen/FreeUKRegProductIssues#1542]
Issue reported by **Janelle** at 2024-09-11 23:00:32 UTC
Time: 2024-09-11T22:26:41+00:00
Session ID: 2bfa9e450d8fd48e82e7140534d38d75
Problem Page URL: [/cms/information-for-coordinators/the-embargo-system](/cms/information-for-coordinators/the-embargo-system)
Previous Page URL: [https://www.freereg.org.uk/cms/information-for-coordinators/the-image-server](https://www.freereg.org.uk/cms/information-for-coordinators/the-image-server)
Reported Issue:
Hello tech folks,  
I am caretaker of DBY and I have been creating embargo rules this week for parishes that appear in search results with baptisms data for 1925 onwards requiring 100 year embargo. Places that I set up yesterday are still appearing in a new search today … how long do they usually take to be effective ? Am I missing something ? Is there a problem ? 
Screenshot attached of today’s search results for surname Smith DBY baptisms. I also checked my county Devon where I made 100 year rules a couple of years ago and they are working fine. 
Thankyou, 
Janelle 
https://www.freereg.org.uk/uploads/feedback/screenshot/66e22110b18f7c4c5daeacd5/709DC97C-6D51-4F85-8CB0-82FEAAAE8A21.png    

![Screenshot](https://www.freereg.org.uk)

**Comment by Sandra-AW** [comment]
![image](https://github.com/user-attachments/assets/ed09275e-8da6-47d9-9df1-352f307743b0)

Everything appears to be in order for the rules that were created, so unable to see why these would not be working

**Comment by DeniseColbert** [comment]
Waiting for Janelle to confirm fix is good before closing.
