### ISSUE TITLE
307209284 Test report for GitHub #2736 (Dale)

### ISSUE THREAD

**Issue by FreeREGcomputer** [FreeUKGen/FreeUKRegProductIssues#1544]
Issue reported by **STSCC** at 2024-09-25 15:54:44 UTC
Time: 2024-09-25T15:52:51+00:00
Session ID: f4118f6b87661ad892bae263e817d1f3
Problem Page URL: [/manage_resources/new?locale=en](/manage_resources/new?locale=en)
Previous Page URL: [https://www.freereg.org.uk/cms/refinery/login](https://www.freereg.org.uk/cms/refinery/login)
Reported Issue:
Please turn this into a GitHub issue and then I will see if I receive an email from the system.    

![Screenshot](https://www.freereg.org.uk)

**Comment by stsccfr** [comment]
Vino, this issue should be in the Myopic Vicar repo issues where it is #2736 and I have posted there.

**Comment by DeniseColbert** [comment]
Done: closing
