### ISSUE TITLE
309185656 A lot of emails being received appearing to come from freereg (Barrie)

### ISSUE THREAD

**Issue by FreeREGcomputer** [FreeUKGen/FreeUKRegProductIssues#1545]
Issue reported by **brobinson43** at 2024-10-18 12:54:16 UTC
Time: 2024-10-18T12:46:59+00:00
Session ID: ec8ba3b75639646f8f745a87ac0afb3b
Problem Page URL: [/contacts](/contacts)
Previous Page URL: [https://www.freereg.org.uk/manage_resources/new?locale=en](https://www.freereg.org.uk/manage_resources/new?locale=en)
Reported Issue:
This is probably not the right place to report this, but what is?
I have received a very large number of emails like the attachment, and they appear to come from freereg. I thought it was just me as a coordinator, but this evening I got a message from a transcriber who said the same thing.
Has the system gone into some kind of malfunctional loop, or have we been hacked? It looks serious, I can simply delete the emails, but maybe it refers to emails I should have received but haven't (and there are apparently quite a few of those, too.)
If it's not the recipient's job, can s/he please forward this to the one whose itr is?
Thanks,
Barrie Robinson
Warwickshire
https://www.freereg.org.uk/uploads/feedback/screenshot/67125a78b18f7cec7eda5588/Screen_Shot_2024-10-18_at_11.45.13_pm.png    

![Screenshot](https://www.freereg.org.uk)

**Comment by DeniseColbert** [comment]
We think that this issue has been fixed now, so closing the story.
