### ISSUE TITLE
310254537 Actions Page buttons changed for an individual coord. (Exec Lead)

### ISSUE THREAD

**Issue by FreeREGcomputer** [FreeUKGen/FreeUKRegProductIssues#1546]
Issue reported by **FR Exec Lead** at 2024-10-30 21:48:57 UTC
Time: 2024-10-30T21:42:58+00:00
Session ID: 8d6e36ef7982ad25cd271237c0c6de05
Problem Page URL: [/messages/6720e557b18f7ca35dd47fd1?locale=en&source=original](/messages/6720e557b18f7ca35dd47fd1?locale=en&source=original)
Previous Page URL: [https://www.freereg.org.uk/messages/userid_messages?locale=en](https://www.freereg.org.uk/messages/userid_messages?locale=en)
Reported Issue:
This came in from Doreen. Can we help?

Hi Team,

I have noticed your change to the Actions, mainly Display Actions. These two additions added to the list means the acons I use most, and often in a day are moved down the list, hence an addtion for me to keep scrolling every time I want select MANAGE County, MANAGE syndicate.
With someone who is struggling at the moment with no thumb and minim fingers.

So can I have my MANAGE  high up the list please.

Best Wishes
Doreen    

![Screenshot](https://www.freereg.org.uk)

**Comment by Sandra-AW** [comment]
Not sure if this can be done for an individual or if it would affect all coordinators.

**Comment by Sandra-AW** [comment]
Closing as I for some unknown reason forgot to turn this into an issue from Feedback on the FR site, Created issue 1547 direct from Feedback
