### ISSUE TITLE
311356458 test (Sandra)

### ISSUE THREAD

**Issue by FreeREGcomputer** [FreeUKGen/FreeUKRegProductIssues#1548]
Issue reported by **FR Exec Lead** at 2024-11-12 15:54:18 UTC
Time: 2024-11-12T15:51:42+00:00
Session ID: 308a3dd32c51239369768feb184c5588
Problem Page URL: [/manage_resources/new?locale=en](/manage_resources/new?locale=en)
Previous Page URL: [https://www.freereg.org.uk/cms/refinery/login](https://www.freereg.org.uk/cms/refinery/login)
Reported Issue:
test please ignore    

![Screenshot](https://www.freereg.org.uk)

**Comment by Sandra-AW** [comment]
Closing, used for test
