### ISSUE TITLE
312047819 test re github # 2736 (Communications)

### ISSUE THREAD

**Issue by FreeREGcomputer** [FreeUKGen/FreeUKRegProductIssues#1550]
Issue reported by **CommsCoord** at 2024-11-20 15:56:59 UTC
Time: 2024-11-20T15:56:06+00:00
Session ID: 8091f749545b0cfa7760dc9335e51c87
Problem Page URL: [/manage_resources/new?locale=en](/manage_resources/new?locale=en)
Previous Page URL: [https://www.freereg.org.uk/cms/refinery/login](https://www.freereg.org.uk/cms/refinery/login)
Reported Issue:
test    

![Screenshot](https://www.freereg.org.uk)

**Comment by Sandra-AW** [comment]
Test for #2736. Closing
