### ISSUE TITLE
314002848 Image group not found (Barrie)

### ISSUE THREAD

**Issue by FreeREGcomputer** [FreeUKGen/FreeUKRegProductIssues#1555]
Issue reported by **brobinson43** at 2024-12-13 07:00:48 UTC
Time: 2024-12-13T06:58:13+00:00
Session ID: 461263955300cb973aeb35fb902ba504
Problem Page URL: [/manage_counties/manage_image_group?locale=en](/manage_counties/manage_image_group?locale=en)
Previous Page URL: [https://www.freereg.org.uk/manage_counties/selection?option=Manage%20Images](https://www.freereg.org.uk/manage_counties/selection?option=Manage%20Images)
Reported Issue:
I tried to create a new image group for Bentley St John PR, but this was denied as it said the image group already exists.
It is not to be found on the list of all image groups, so I cannot upload some images to it.

Barrie Robinson
WAR County Coordinator    

![Screenshot](https://www.freereg.org.uk)

**Comment by stsccfr** [comment]
Barrie did not remember ever creating the image group for Bentley St John PR, but Vino was able to remove the rogue entry, and that allowed Barrie to re-create the image group and upload images.  Closing this case.
