### ISSUE TITLE
search involving  Places with Not Approved names appear not to get found. (ericb)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#156]
Issue reported by **ericb** at 2015-01-18 17:47:28 UTC
Time: 2015-01-18T17:38:30+00:00
Session ID: 1d527f907d0270eafe56d17b12c87767
Problem Page URL: [/freereg1_csv_entries](/freereg1_csv_entries)
Previous Page URL: [http://test2.freereg.org.uk/freereg1_csv_files/54ba50a6e937903c8b000003](http://test2.freereg.org.uk/freereg1_csv_files/54ba50a6e937903c8b000003)
Reported Issue:
refer to DBY/ Alsop En le Dale. It is a Not Approved place. It has batch DBYALDMA1 which first record is Marriage 6 Nov 1702 between Richard Heath and Hannah Allen.
The true place name should be Alsop en le Dale.

In a SEARCH for this record, BOTH versions of Place name are in the pick list (ie En and en).

But a search using male name does not find this record. -  using either of the 2 versions of Place name on its own, OR using BOTH place names together.
Screen print of copy of current file for this person is attached.    

![Screenshot](http://test2.freereg.org.uk/tmp/carrierwave/1421603248-35129-3759/Screen_shot_2015-01-18_at_17.38.34.jpg)

**Comment by Sherlock21** [comment]
I am inclined to the view that: if the place name is Not Approved, then that version of the Placename should NOT appear in the Search List of Placenames. and it would be right to not include the data in a search.

**Comment by Captainkirkdawson** [comment]
Not true

**Comment by Sherlock21** [comment]
Strictly, this was true. 
The original label of "Not Approved" for such place names seems to have just been replaced by Colouring the Date Updated in RED but no warning text.
EricB
