### ISSUE TITLE
Redesign Placename and Churchname validation for reloads prior to and for GoLive of FR2

### ISSUE THREAD

**Issue by Sherlock21** [FreeUKGen/FreeUKRegProductIssues#157]
Redesign Validation of data file Placename against Main Placename table. 
Take account of multi word names and hyphenation without editing or omitting parts.
Flag all mis-matched Placenames by adding label: Not Approved Placename and coloured Red to aid finding for correction.
Rectify errors in F1 so they are ready for snag-free final data cutover from F1 to FR2.
Arrange DataManager's option to find all RED Flag places, to list ALL Not- Approved Place names in one composite list so the total scope of the issue can readily be seen instead of having to take each of the 132 Counties, one at a time, and sum by hand the individual counts every time we need a check.

Pre golive, there needs to be no validation, as there is no table of Church name per Place. This will be created by the Golive upload.

**Comment by Captainkirkdawson** [comment]
I believe this is np longer an active requirement
