### ISSUE TITLE
Design Placename and Churchname validation for individual data uploads post GoLive of FR2 to replace #157

### ISSUE THREAD

**Issue by Sherlock21** [FreeUKGen/FreeUKRegProductIssues#158]
These arrangements are to replace #157 after Golive in FR2. 
Post Golive in FR2, Validation of Place name against the Table of Approved Place names, should reject all batches which fail the full place name validation.
AND validation of church name against the table of Approved Church names per place name should also reject the batch.
Return message to Uploader and copy to CC advising details of why Validation has rejected the batch.
If the upload is a Replace activity, then do not destroy the present batch until the incoming new batch has passed the Validation process.

**Comment by edickens** [comment]
```
Kirk,
  I don't know if you can differentiate between batches loaded
  directly into FR2 by a transcriber and those which you are
  bringing across from FR1?  If you can, then any batch uploaded
  directly into FR2 and not by your conversion, should be validated
  as EricB has said here now, and not just after Golive in FR2.
  Anyone uploading into FR2 should already have a Place and Church
  created for their work.  It is perhaps a bit early to also have a
  Register record.
  EricD
  _____________________________________
```

Eric J Dickens
FreeREG Chairman
      On 19/01/2015 10:31, Sherlock21 wrote:

```
  Post Golive in FR2, Validation of Place name against the Table
    of Approved Place names, should reject all batches which fail
    the full place name validation.
    AND validation of church name against the table of Approved
    Church names per place name should also reject the batch.
    Return message to Uploader and copy to CC advising details of
    why Validation has rejected the batch.
    If the upload is a Replace activity, then do not destroy the
    present batch until the incoming new batch has passed the
    Validation process.
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by Sherlock21** [comment]
Is it possible to create a check application, like the Red Not Approved Place names (for managers & CC's) to help find the Church names that need resolving?
Not the same issues as Places - so list when there is more than 1 church name in a place (there will be many of these that are correct of course.
Or list if name has an apostrophe "s" like: St Mary's.

Or is it too difficult for the potential gain?
Or can you think of better way.
 There will be many where this is correct

**Comment by edickens** [comment]
```
Hi EricB,
  I think we need to know the scale of the problem.  It is not the
  same as Places because we didn't create a Master List.  Kirk's
  early spreadsheet report which listed all Places/Churches showed
  it very well.  If there is a report generator in the database
  package, then a list of County/Place/Church would do.
  E
  _____________________________________
```

Eric J Dickens
FreeREG Chairman
      On 19/01/2015 19:17, Sherlock21 wrote:

```
  Is it possible to create a check application, like the Red Not
    Approved Place names (for managers & CC's) to help find the
    Church names that need resolving?
    Not he same issues as Places - so list when there is more than 1
    church name in a place? (there will be many of these that are
    correct of course.
    Or list if name has an apostrophe "s" like: St Mary's.
  Or is it too difficult for the potential gain?
    Or can you think of better way.
    There will be many where this is correct
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by Sherlock21** [comment]
Indeed it would. I agree the first element is to get a grip on the scale of the problem by the easiest route we can devise. Then take it from there.

**Comment by edickens** [comment]
I think #157 is Complete
I understand why this is Version 1.4, but should we implement the Place/Church validation as soon as FR2 has been opened to CCs in Version 1.2?  During the overnight update, exact match without case will do, and only against approved place names and all Church names.  Mismatched files not to be processed but reported.  My reasoning is that this will stop any more Unapproved Places being created and any new Churches being created.  Since FR2 is now an exact match of FR1, then all files that come across from now on should be corrections and not match Unapproved Places.
When CCs have access they can create new Churches if needed.

**Comment by PatReynolds** [comment]
Alternatively, on new system, do not allow transcribers to edit these fields?

**Comment by Sherlock21** [comment]
Transcribers cant edit these fields as such anyway.
Place name fields are now done and fixed. ( unlike at the start of this Issue.)
Now its only about Church names. and whatever a Transcriber puts into their file, for a church name, gets created when the file is uploaded. This needs to stop.
Church field needs to become a validated field PER PLACE NAME, created from the present list of what's there.
Editable by SC, CC, & Managers  and new church names Created only by the same.
ALSO these above profiles need to be able to create a new church name for a Place, and display same in that Place's listing in All Places and in Active Places without any data attached, so its showing, and ready to accept new upload form any source - either via WinReg or direct upload from Spreadsheet users.

A Place should remain Not Active until its got some data, rather than when its just got one or more Church names with no date.

**Comment by Sherlock21** [comment]
What we need right now, is a simple sql listing:-
DISTINCT Region / County code / Place Name / Church Name from (All Places)
downloaded in csv format, so that Reg Mgr & Data Mgr can make a sensible decision on how to correct any existing rubbish church names ( depending on which Counties they are in, and the quantities.
This is only assessable by eye, scanning down a simple big csv file.

**Comment by edickens** [comment]
```
This CSV listing is easy to do.  Open the report, right-click,
select all, copy, save into a spreadsheet as text.  It will get put
into columns.  Contact me if you want an example.  E

On 08/04/2016 10:38, Sherlock21 wrote:


  What we need right now, is a simple sql listing:-
    DISTINCT Region / County code / Place Name / Church Name from
    (All Places)
    downloaded in csv format, so that Reg Mgr & Data Mgr can
    make a sensible decision on how to correct any existing rubbish
    church names ( depending on which Counties they are in, and the
    quantities.
    This is only assessable by eye, scanning down a simple big csv
    file. 
  —
    You are receiving this because you commented.
    Reply to this email directly or view
      it on GitHub
```

**Comment by Sherlock21** [comment]
Eric D

the only way i know to do this from where we stand now,  is to do one by each County. so 157 separate job lists. ! I want them all in one list

and repeatable regularly, so one can see progress.

If you have something that you can manage to do this with, please can you knock one off so we know the total scope please.?

I am out to lunch party soon, back by teatime though I dont supposeI will need any tea!

thanks,
eb

**Comment by helhyde** [comment]
So I think this issue now is two tasks:
a) easy-to-run report as specified by EricB so that he can check progress
b) lock-down of Church so Transcribers cannot change

_\- -_

_Dr Pat Reynolds_
Executive Director
Free UK Genealogy  http://www.freeukgenealogy.org.uk/
A charity registered in England and Wales, number 1096940.  VAT
registration: 233 0105 70

​+44 ​1904 541411​ +44 7943 145387

36 Albemarle Road, York, YO23 1ER, UK

**Comment by Sherlock21** [comment]
With Eric D’s help, I have got a version ( or the solution to (a) below, that I am working from at the moment. It is subject to people messing up what I have corrected of course, so if its easy to do then it will have value in the interim until we implement Church name validation.

eric B

**Comment by Captainkirkdawson** [comment]
Church name validation is part of the new processor code and will be deployed the last week of April
