### ISSUE TITLE
Batch names are not unique. (ericb)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#159]
Issue reported by **ericb** at 2015-01-19 15:28:35 UTC
Time: 2015-01-19T15:18:03+00:00
Session ID: b48a0fe9128f45a6e6bee445af0c6ee1
Problem Page URL: [/registers/54bad142e9379022bd000005](/registers/54bad142e9379022bd000005)
Previous Page URL: [http://test2.freereg.org.uk/places?page=13](http://test2.freereg.org.uk/places?page=13)
Reported Issue:
In the Place/ Church name/ Register type page, the list of batches attached to that church are shown at the foot of the details page. But this shows just the batch name - ie the uploaded file name like: DBYRIDMA1.csv. But this is the Transcriber's own filing system name.
If there are several transcribers for this church its likely they will all start their file numbering from MA1.csv so looking at the Church data, there will appear to be multiple files of same name.

We previously opted to not publicise Transcriber user names ( which might fit here but that's against the confidentiality request.
So what can we do - if anything is needed?    

![Screenshot](http://test2.freereg.org.uk)

**Comment by edickens** [comment]
```
I don't see a problem showing UserID in
  the Administration screens.  It is the Database Content which is
  open to the public where they should not be shown.  As it is
  editing which is your concern, this will only be in the
  Administration area and also probably only at Coordinator level.
  EricD
  _____________________________________
```

Eric J Dickens
FreeREG Chairman
      On 19/01/2015 15:28, FreeUKGenIssues wrote:

```
  Issue reported by ericb at 2015-01-19
    15:28:35 UTC
    Time: 2015-01-19T15:18:03+00:00
    Session ID: b48a0fe9128f45a6e6bee445af0c6ee1
    Problem Page URL: /registers/54bad142e9379022bd000005
    Previous Page URL: http://test2.freereg.org.uk/places?page=13
    Reported Issue:
    In the Place/ Church name/ Register type page, the list of
    batches attached to that church are shown at the foot of the
    details page. But this shows just the batch name - ie the
    uploaded file name like: DBYRIDMA1.csv. But this is the
    Transcriber's own filing system name.
    If there are several transcribers for this church its likely
    they will all start their file numbering from MA1.csv so looking
    at the Church data, there will appear to be multiple files of
    same name.
  We previously opted to not publicise Transcriber user names (
    which might fit here but that's against the confidentiality
    request.
    So what can we do - if anything is needed? 

  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by Sherlock21** [comment]
OK, then should we show the UserID prefix to the file name - to distinguish between possible duplicate file names?

**Comment by edickens** [comment]
```
Yes, but only at CC and SC level and
  above.  Transcribers can only see their work, so it doesn't matter
  if we do or don't at that level.
  EricD
  _____________________________________
```

Eric J Dickens
FreeREG Chairman
      On 19/01/2015 15:49, Sherlock21 wrote:

```
  OK, then should we show the UserID prefix to the file name - to
    distinguish between possible duplicate file names?
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by Captainkirkdawson** [comment]
Implemented
