### ISSUE TITLE
Tips on Searching links (EricD)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#16]
Issue reported by **EricD** at 2014-09-16 09:25:20 UTC
Time: 2014-09-16T09:20:25+00:00
Session ID: a21f4eec15f02701428105a5131d7cca
Problem Page URL: [/manage_resources/539a6a14eca9eb57f100013a](/manage_resources/539a6a14eca9eb57f100013a)
Previous Page URL: [http://xanthus.freereg2.zomo.co.uk/refinery/login](http://xanthus.freereg2.zomo.co.uk/refinery/login)
Reported Issue:
The links in "Tips for Searching" which were taken from F1 do not work.  How do they need changing?  See attached.

**Comment by graphiclunarkid** [comment]
Supserseded by #172
