### ISSUE TITLE
Navigation with the Database Contents causes a problem (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#168]
Issue reported by **REGManager** at 2015-02-06 08:06:14 UTC
Time: 2015-02-06T08:01:41+00:00
Session ID: e92ce6aa3e39150e3c2c2db539a9c8d0
Problem Page URL: [/search_queries/54d474e5e93790d081000002](/search_queries/54d474e5e93790d081000002)
Previous Page URL: [http://freereg2.freereg.org.uk/search_queries/new](http://freereg2.freereg.org.uk/search_queries/new)
Reported Issue:
This has been reported by a transcriber...
Michael Clarke: divermikenl@hotmail.com

I have found a discrepancy in FreeREG2.

Do the following:

 1   Select "Database Contents" from "home" screen
 2   On the "Select County and Place" screen, click on Buckinghamshire in the "County" box - a list of places in Bucks is displayed in the "Place" box
3    Click on Addington
4    Click on Select button - information about Addington is dsplayed in a new screen
5    Click the browser's "Back" button (NOT the "Back to County/Place Selection" button) - The "Select County and Place" screen is re-displayed with Buckinghamshire highlighted  in the "County" box. The "Place" box is empty.
 6   Click on Buckinghamshire - nothing happens and the "Place" box remains empty.
 7   Repeat steps 2 through 4.
 8   Click on the "Back to County/Place Selection" button -  The "Select County and Place" screen is re-displayed with nothing highlighted in the "County" box. The "Place" box is empty.

To my mind, this is a discrepancy where one of the actions is inconsistent with the other. I am using Vista and Torch.

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Database contents has been rewritten
