### ISSUE TITLE
Button to Change Register Type has wrong links (ericb)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#169]
Issue reported by **ericb** at 2015-02-16 09:32:47 UTC
Time: 2015-02-16T09:27:16+00:00
Session ID: 03899b7503ba4b4224531b3f49997b37
Problem Page URL: [/registers/5407f15ceca9eb1ee04b462a](/registers/5407f15ceca9eb1ee04b462a)
Previous Page URL: [http://freereg2.freereg.org.uk/churches/5407f15ceca9eb1ee04b4628](http://freereg2.freereg.org.uk/churches/5407f15ceca9eb1ee04b4628)
Reported Issue:
Clicking on the ChangeRegister Type button does not take one to a feature that enables that to be done - it goes to a table of adding other Church data

Also, it appears that it may change All of one type to ALL of another. This may be appropriate in some cases  but wont be in other cases - like all the  Unspecified for one church May need to go the PR, but there should be the option of do ALL ( for that church) or one at a time.    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Unable to duplicate. The Change Register Type button does go to the correct page. Where there is a selection of register type.
If you wish to change the register type for an individual batch then do so by selecting the batch and then use the  Edit Header feature
