### ISSUE TITLE
Field Error - Trapped emails (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#171]
Issue reported by **REGManager** at 2015-02-16 13:02:28 UTC
Time: 2015-02-16T12:53:08+00:00
Session ID: 76f6eeb1d5878d451bfbfbd08b1b457d
Problem Page URL: [/search_queries/new](/search_queries/new)
Previous Page URL: [http://freereg2.freereg.org.uk/manage_resources/new](http://freereg2.freereg.org.uk/manage_resources/new)
Reported Issue:
I am starting to get Trapped emails about data errors.  These must be from transcribers, unless someone is just testing the system.  But what do I do with them?

In the attached the "Access the contact" and "Record in question" do not work.  The "Body" does not state the county, so I don't know where to find the Place.

Also, who are these emails addressed to?  In FR1, the CC and reg-data@freereg.org.uk (the Data Administrator (Bob Wilkins) and myself) get copies.

At this stage, should we be accepting these corrections?  I would say Yes, but they need to work.    

![Screenshot](http://freereg2.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1424091748-93666-9542/Capture.JPG)

**Comment by Captainkirkdawson** [comment]
They  were working  fine when  I left.  You must be logged into  the system
for  the access to the links.
You can also review all contacts by accessing the  Contacts Admin function.

The data contacts/error reports go to the datamanagers and the  CC.

**Comment by edickens** [comment]
```
When you get back I will sort this
  out.  I was trying the links in the email when in my email editor
  and not looking at them on the server, even though I had the
  server open and logged in.  Will have to learn how.

  E
  _____________________________________
```

Eric J Dickens
FreeREG Chairman
      On 16/02/2015 13:36, Kirk Dawson wrote:

```
They were working fine when I left. You must be logged
  into the system
  for the access to the links.
  You can also review all contacts by accessing the Contacts Admin
  function.

  The data contacts/error reports go to the datamanagers and the CC.
  On Feb 16, 2015 8:02 AM, "FreeUKGenIssues"
  <notifications@github.com>
  wrote:

  > Issue reported by *REGManager* at 2015-02-16 13:02:28 UTC
  > Time: 2015-02-16T12:53:08+00:00
  > Session ID: 76f6eeb1d5878d451bfbfbd08b1b457d
  > Problem Page URL: /search_queries/new
  > Previous Page URL:
  http://freereg2.freereg.org.uk/manage_resources/new
  > Reported Issue:
  > I am starting to get Trapped emails about data errors. These
  must be from
  > transcribers, unless someone is just testing the system. But
  what do I do
  > with them?
  >
  > In the attached the "Access the contact" and "Record in
  question" do not
  > work. The "Body" does not state the county, so I don't know
  where to find
  > the Place.
  >
  > Also, who are these emails addressed to? In FR1, the CC and
  > reg-data@freereg.org.uk (the Data Administrator (Bob Wilkins)
  and myself)
  > get copies.
  >
  > At this stage, should we be accepting these corrections? I
  would say Yes,
  > but they need to work.
  >
  > [image: Screenshot]
  >
```

https://camo.githubusercontent.com/953f1bbabb44142e0bce6e04ab7c7624d13dda1b/687474703a2f2f66726565726567322e667265657265672e6f72672e756b2f686f6d652f6170616368652f686f7374732f66726565726567322f70726f64756374696f6e2f746d702f63617272696572776176652f313432343039313734382d39333636362d393534322f436170747572652e4a5047
      >
      > —
      > Reply to this email directly or view it on GitHub
      >
      https://github.com/FreeUKGen/FreeUKGenProductIssues/issues/171.
      >
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Captainkirkdawson** [comment]
Is this still an open issue?????????

**Comment by edickens** [comment]
No.  Can be closed.  Let's see how it goes when we get more researchers 
and data errors get reported.
EricD

---

Eric J Dickens
FreeREG Chairman
