### ISSUE TITLE
Results page sorting error (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#173]
Issue reported by **REGManager** at 2015-02-16 20:45:53 UTC
Time: 2015-02-16T20:44:18+00:00
Session ID: f6821efde090e297cc760b1f2ea5f6d5
Problem Page URL: [/search_queries/54e256a1e937906120000001](/search_queries/54e256a1e937906120000001)
Previous Page URL: [http://freereg2.freereg.org.uk/search_queries/new](http://freereg2.freereg.org.uk/search_queries/new)
Reported Issue:
From a transcriber...
I’ve spotted a small error on the search results page:
clicking on the ‘Participants’ column heading to sort the surnames actually sorts by date instead.
Overall, I think it’s easy to use and a definite improvement though. I like the ‘search nearby’ feature.
Cathy    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by benwbrum** [comment]
This has been fixed, but needs to be re-tested when we get a rebuild.
