### ISSUE TITLE
the Search facility of NEARBY has lost its ABOUT link to places and changing the radius  (ericb)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#174]
Issue reported by **ericb** at 2015-02-18 08:47:09 UTC
Time: 2015-02-18T08:42:24+00:00
Session ID: 98f85926ab8cad551537ce15ba68443d
Problem Page URL: [/manage_resources/new](/manage_resources/new)
Previous Page URL: [http://freereg2.freereg.org.uk/refinery/login](http://freereg2.freereg.org.uk/refinery/login)
Reported Issue:
I notice - following a comment by Jon Maxfield that doing a Nearby  search, one no longer gets the ABOUT link to the list of Place names which are included with the given radius, not=r the then ability to reduce the radius so as to get more results within the smaller radius if one has got the limit of the quantity of records ( 250 at present) permitted.

Have these been removed for a reason? Or dropped off as a result of moving things about recently?    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Sherlock21** [comment]
Whilst you are fixing this, could you please change the units from Km to Miles. "set" radii could be in increments of 5 miles.
[We started off with the choice for users to pick ( Km or Miles) but went to no choice, for simplicity. but Miles is preferred by those who have commented to me]

**Comment by Sherlock21** [comment]
The NEARBY feature seems to be there and working now [ it might have been that i could not see/read the button  in the first place. - white on strong green is not the easiest! ]
The request to change units still stands though please.

**Comment by Captainkirkdawson** [comment]
Units changed to miles

**Comment by Sherlock21** [comment]
Tested this out, and its all fine now - including round up to interger only.

BUT whilst the list of place names in the ABOUT > Nearby list have been rounded up, the label on the Search REsults list is headed: PLACE aaaa (including nn additional places within 11.2 miles)

If you edit that text, then this can be closed too.
