### ISSUE TITLE
User re-ordering search results column (ericb)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#176]
Issue reported by **ericb** at 2015-02-18 19:23:17 UTC
Time: 2015-02-18T19:16:22+00:00
Session ID: 23ae94fbca25436b6b39974f802fc85f
Problem Page URL: [/search_queries/54e4e503e937902207000007](/search_queries/54e4e503e937902207000007)
Previous Page URL: [http://freereg2.freereg.org.uk/search_queries/54e4e4fce937902207000004](http://freereg2.freereg.org.uk/search_queries/54e4e4fce937902207000004)
Reported Issue:
A tiny point in the scale of things, but the feature to sort columns of search results: is the first column of participant name only meant to search on Surname?

if so, please edit the Info  Icon to say SURNAME.
If its a sort on First name then Surname or something, then there is a snag.
If one does a search of a surname,  then to try a sort order on this column has no effect. - wheras one might expect & hope it would have an effect of sorting by first names - since all the surnames are  the same.    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by benwbrum** [comment]
Eric, can you try out the same sort on the test site:
http://test2.freereg.org.uk ? There was a bug in the participation sort
which I believe I fixed, and which has been deployed to the dev site but
not to production.

Ben

**Comment by Sherlock21** [comment]
Ben: I can't make head nor tail of how col 1 is sorting. If I do marriages search (so as to get variable surnames) and sort into date order first. Then order it again by col1, it does make a change but not sure what the new sort order is.

copy of first screen results attached.
Search was for marriages of  Fysher +with  family members.
Order was Date Ascending. first Record was Elin Hyne + Edward Fisher (first copy called Date order.jpg)
Then re order on coll 1.
