### ISSUE TITLE
Order of counties (Ivor Clucas)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#177]
Issue reported by **Ivor Clucas** at 2015-02-21 15:03:57 UTC
Time: 2015-02-21T14:55:57+00:00
Session ID: 
Problem Page URL: []()
Previous Page URL: [http://freereg2.freereg.org.uk/contacts](http://freereg2.freereg.org.uk/contacts)
Reported Issue:
Hi, 

As a long time FreeReg transcriber (NTH) I have been looking at the new FreeReg search page. 

One comment so far as follows:

It is not obvious that the counties have been separated into England, Scotland and Wales. In version one they were all in one long list. For a researcher not familier with UK geography they might not realise that, for instance, to find Montgomeryshire they will not find it next after Middlesex but further on down amongst the Welsh counties. I think a undivided list as in version one would be better.    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Sherlock21** [comment]
Adding in a first field: "Region" would solve this one.

**Comment by benwbrum** [comment]
Adding England/Scotland/Wales as an HTML OptionGroup would make this much more usable, even though we won't be providing any functionality to search on a region.

**Comment by Sherlock21** [comment]
Whilst my suggestion above to add a Region field first would be a solution, I fear it would bring other complaints from those who like to pick a bundle of Counties in their search.
I know that our new Place + Nearby feature will suffice for many, but there will remain those researchers who want their own traditional multiple Counties selection.
 A Region select first would prevent this being done at the  Cross Region interface. [ie the England/ Scotland border and the England/ Wales border.
So what order would be fair to all?

One single County list, in alphabetical order I think is the best compromise all round. - with the first line a blank, = ALL ( without any text in it, as it is at present) if you just click on the space, it works as ALL)
One list of all Counties at least everyone can recognise if they are seeking to select Counties starting with B they go slowly at the top of the list, or if they want Yorkshire, zoom to the bottom, and work slowly back up. This should satisfy the tablet & phone people who finger flick, and the desktop Pc + mouse user who can drag the sidebar down, or just hold on the up/down arrow to scroll in the usual way.
Sorry Ben if this messes your plan up!

**Comment by edickens** [comment]
```
FR1 has all counties in alphabetical, with no regions.  (It even has
England since someone has uploaded a file with ENG!)  Why change
from that?

But more importantly, we must be sure to inform the researcher if
they select a county with no data.

There are a lot of Chapman codes that we do not use, such as the
whole of Ireland.  We should only include those that are valid.

E

_____________________________________
```

Eric J Dickens
FreeREG Chairman

**Comment by Sherlock21** [comment]
The debate stems from the way the present FR2 collection of Counties started off in FR2. - which is not the same as it was in F1.

w.r.t the mystery file against ENG ( ref above) you should correct it.
And w.r.t. chapman codes that are "not Valid" I suggest that we keep those codes for Counties which are IN the regions we intend to cover, and remove those for Counties that are in Regions which we do not intend to cover, even if we don't have records today. - Else someone will have to remember to go and add the County and its Places to the system as we expand from today.

**Comment by edickens** [comment]
An FR1 update has taken place and the ENG file has been corrected. But I 
need to confirm with Kirk that it will get corrected in FR2.

E

---

Eric J Dickens
FreeREG Chairman

**Comment by benwbrum** [comment]
Channel Islands -- what should be done about CHI and Alderney?

**Comment by benwbrum** [comment]
And Sark, and Jersey, and Guernsey

**Comment by benwbrum** [comment]
And the Isle of Man

**Comment by Sherlock21** [comment]
The rule seems to be " just make FR2 a copy of F1 - for good or bad!

The Isles of Scilly are rolled in with Cornwall in both F1 and Chapman!
And for that matter, the Isle of White  has its own  code (IOW Chapman) although we roll that one in with Hampshire and its Place names area in the Gazetteer under Hampshire.

In F1, The Channel Islands comprises: Jersey, Guernsey, Alderney & Sark as one "County" ( CHI chapman). But each also has its own code so I suggest raise at Thursday meeting. We have no Placenames in theGazetteer so far as I can see.

Same for Isle of Man (IOM Chapman)
So, do we just ignore the latter 2 Island sets?

**Comment by Sherlock21** [comment]
Having just had a look in FR2 at what records we have ( some under Jersey as a "County" and some under Isle of White  as another "County" ) it seems to me to be inconsistent.
And Phillimore does not seem to list these as Counties - so as we define that as our Guide, I would like to debate this further.

**Comment by edickens** [comment]
Since we advertise that we are transcribing the registers of England, 
Wales and Scotland (and we would do Ireland if we had any access), then 
I think these should be the major groups.

If we start to go down the route of an intermediate group, then the 
Channel Islands are like Yorkshire.  And there is Birmingham which 
covers more than one county.  Even near where I live here in 
Peterborough we have Stamford which has parts in Cambridgeshire, 
Northamptonshire, Rutland, Nottinghamshire and Lincolnshire.

So I think we should define England as a Region and have just the four 
Regions.  Everything should come under these groups.  So the Chapman 
codes CHI and YKS should not be used.  If we don't then we get into 
problems with the Isle of Man, Scilly Isles and so on.

E

**Comment by Sherlock21** [comment]
But we have dealt with the Isles of Scilly, which are part of Cornwall, by the mechanism of a naming structure eg: CON / Isles of Scilly (Bryher) etc. and this has effectively been deployed and fits well in the searching features too.

We have also declared somewhere in the Text guides and notes which Bernie is doing - that we have used the County and Place definitions in Phillimore's Atlas and Index. So we should stick with that, and apply concepts which I have created so far.

So I prefer to adopt this for The Isle of White - which Chapman shows clearly in HAM - hence Sandown would be: HAM / Isle of White (Sandown) if you wish to identify that its part of the Isle of White - else  its HAM / Sandown just like anywhere else. This is not  what has been done however.

Then for the Channel Islands, I would have the County = CHI and Place Names like St Helier would be Jersey (St Helier) making: CHI / Jersey (St Helier) at the composite.

These are all in Region: England although we don't actually have a field for England as i think the last contributor is saying above.

The Isle of Man does not feature in Phillimore so far as I can determine.  so we should/ could do as we please with this. Call is County on its own? IOM?  this would then take the natural place names.

**Comment by Captainkirkdawson** [comment]
An Island group has been added (comes after England) which includes the channel islands and Ilse of Man. The IOW has been left as part of England but as a separate county even though it is part of HAM. IT appears that the current transcriptions for places in IOW are coded against IOW and not HAM. There is nothing to stop the coordinator involved moving these places to HAM rather than the IOW.

**Comment by Sherlock21** [comment]
I dont quite get the logic of what you have done - as well as not being able to see where you have put the new Island Group ( comes after England) - I done even see England. in my view, its the least logical solution. and the IOM is nowhere near the Chanel Islands - its some 400 miles away. And there are many, many other islands which are already catered for in their real Counties.

I would create a NEW  single County for IOM
A NEW single County CHI for the Chanel Islands - with my composite style Place names to show which island the Place is on.
Leave IOW as a County on its own if you insist
Leave Isles of Scilly where they are,  in CON.

As to where they come in a listing of Counties: well on all i see, the Full County list is in simple alphabetical order is it not?
Or is there a move to do something different?

**Comment by Captainkirkdawson** [comment]
Viewable on the test server
http://test3.freereg.org.uk/search_queries/new

**Comment by Sherlock21** [comment]
OK, Thanks for the preview. In this case, I can agree with why you have IOM & CHI together like this,  and have not included the IOW.
However, I still think the logic should be to have Either the CHI as the collective, or the individual Island names - but not both.
The structure comes first, then make the records agree. - not the reverse way round.

**Comment by Captainkirkdawson** [comment]
A search on CHI will search all channel Island codes, just like YKS searches all the ridings. But one can search individual ridings so similarly one can search the individual channel islands.

**Comment by Sherlock21** [comment]
Ah!! I thought we had abandoned the YKS = the group of Ridings, following the recent little hic-up. 
But do we therefore need to have NO entries against the CHI County - in the same  way as no entries against YKS?

In other words, put the Place names and the data at the lower level in all cases?

**Comment by Captainkirkdawson** [comment]
That is the way it currently works. No data is currently expected under CHI or YKS.

**Comment by Sherlock21** [comment]
You say that no data is currently expected under these higher level county codes - do you mean it actively vetoed out - ie If someone tried to upload such a batch against CHI / AnyPlace, it would get rejected rather than just get entered but create a record which shows Red date ( = Not Approved Place name in old terms).

I am happy with the rule of No data against these "group" County name if there is a positive block on creating Place Names under it in the manner we would create Place names under normal Counties.
