### ISSUE TITLE
Search  Baptisms with Search Family Members does not seem to do anything

### ISSUE THREAD

**Issue by Sherlock21** [FreeUKGen/FreeUKRegProductIssues#178]
There seems no difference in the results when a Baptism search uses Search Family Members, as opposed to not used.

**Comment by benwbrum** [comment]
I've just investigated this, and can't duplicate it.

Take the record at http://freereg2.freereg.org.uk/search_records/5465efeae93790431afee4e6?search_id=54fe009fe93790f9f4000001 , which is a baptism in Gloustershire, Hanham and Olds, Chapelries from 19 Dec 1592.  The father name is Ruben SMITH, while the baptizee is Hugh SMITH.  

A search for Ruben Smith, Baptism, Gloustershire/Hanham and Olds, with "Include Family Members"=true (like http://freereg2.freereg.org.uk/search_queries/54fe0312e937906638000005 ) returns the record of Hugh Smith's baptism based on a search for his father.

I'm closing this, but @Sherlock21 please feel free to re-open/email/comment if you can find a specific contrary example.

**Comment by Sherlock21** [comment]
It must have just been a coincidence of my choice of names.
I Repeated the query now with chosen different names and it works OK.
Sorry to trouble you!

**Comment by benwbrum** [comment]
Better safe than sorry.  Thanks, Eric!
