### ISSUE TITLE
appear to be different results to same query on different browsers (ericb)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#180]
Issue reported by **ericb** at 2015-02-25 19:17:46 UTC
Time: 2015-02-25T19:09:53+00:00
Session ID: e1a981112f8a1f0d0dcc151228143419
Problem Page URL: [/search_queries/54ee1e01e937909c13000004](/search_queries/54ee1e01e937909c13000004)
Previous Page URL: [http://freereg2.freereg.org.uk/search_queries/new?search_id=54ee1da1e937909c13000002](http://freereg2.freereg.org.uk/search_queries/new?search_id=54ee1da1e937909c13000002)
Reported Issue:
If I use Safari on Mac, I get one set of results.
If I use Opera on same Mac, at same time, I get different ( much reduced) results.
( This report attaches Opera screen shot. Next report attaches Safari screen shot.)

OR am i not inputting exact same query?     

![Screenshot](http://freereg2.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1424891866-57095-7323/Opera_browser.jpg)

**Comment by Captainkirkdawson** [comment]
I am sorry there is no way that this can happen. The search engine does not know or care what the browser is.
Now there might be the possibility of the browser sending different search criteria
