### ISSUE TITLE
Safari screenshot (ericb)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#182]
Issue reported by **ericb** at 2015-02-25 19:27:37 UTC
Time: 2015-02-25T19:25:30+00:00
Session ID: e1a981112f8a1f0d0dcc151228143419
Problem Page URL: [/](/)
Previous Page URL: []()
Reported Issue:
part 2 of last report.    

![Screenshot](http://freereg2.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1424892457-59681-7787/Safari_browser.jpg)

**Comment by Sherlock21** [comment]
![safari browser](https://cloud.githubusercontent.com/assets/9368704/6379814/e2f11906-bd2c-11e4-86a5-d9705701b81e.jpg)

**Comment by Sherlock21** [comment]
This apparently isolated screen print is part of the previous report of mine [#180]  I could not get this onto the part 1 because I started writing the report BEFORE I copied the screenprint - and one cannot get from mis report back to the application to pick up attachments like this!
