### ISSUE TITLE
Using Firefox browser on Mac has snags navigating.

### ISSUE THREAD

**Issue by Sherlock21** [FreeUKGen/FreeUKRegProductIssues#184]
Using the Mac browser: Firefox, it does not show the "Viewed" label after picking a search result row, then clicking on Details, and Return to data to get back to the results table.

It does work correctly on Opera Browser and Safari.
All 3 Browsers ( Safari, Firefox & Opera) will show return search results and let one navigate through to the Genuki map page. But only Opera & Firefox display the Genuki magnifying tools and the Move map tool.
but Opera and Firefox dont seem to respond to allow me to log on to test site to report this findings direst.( this one has to be done back on Safari, which wont display the mapping tools!)

**Comment by PatReynolds** [comment]
I've got viewed showing up on Firefox.

I got a bit lost with the last part. I'm not sure it's our responsibility to fix Genuki.
