### ISSUE TITLE
? wrong processing of batches which have a Placename error? (ericb)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#186]
Issue reported by **ericb** at 2015-03-11 10:04:47 UTC
Time: 2015-03-11T09:48:59+00:00
Session ID: 9ddd49ee18a29d15097fe888d353985f
Problem Page URL: [/places](/places)
Previous Page URL: [http://freereg2.freereg.org.uk/manage_counties/select_action?county=MLN](http://freereg2.freereg.org.uk/manage_counties/select_action?county=MLN)
Reported Issue:

THIS partly overlaps with my comment previously written into #172 .

Take Midlothian county / Cannongate. there are 2 rows in the display or all please for this one.
One Place name, but 2 church names both the same as it happens, but the first row has a RED last changed date. The second row is "normal" colours.
Clicking on the Church Name of the first row leads to the default Place GridReg  Tower of London. There is no batch number shown anywhere so how to find the error?
Clicking on the second row Church Name navigates through correctly.

Take  then WRY County, / Bolton-by-Bowland. there is one row here for the place name and one church and nothing in red 
BUT each batch file has a syntax error in the file name - "-by- in the middle in the Place name and "-By-" in the batches. SO have you changed the software to ignore this? or is there an error here?
IF changed, what else by way of errors can now be left please?
Will same syntax mis-matches pass the  user-upload phase as well, or is this just a F1 > FR2 fix please?

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Direct result of KISS approach
