### ISSUE TITLE
Search is not testing for Birth Year (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#187]
Issue reported by **REGManager** at 2015-03-16 16:54:44 UTC
Time: 2015-03-16T16:51:53+00:00
Session ID: 29d695157679b8e230e39d278a58c061
Problem Page URL: [/search_queries/55070a29e937909f4700002c](/search_queries/55070a29e937909f4700002c)
Previous Page URL: [http://freereg2.freereg.org.uk/](http://freereg2.freereg.org.uk/)
Reported Issue:
This search "Goyles" "1793-1795" "Staffordshire" "BA" gives no results.
Fanny Goyles was baptised in 1814.
So a researcher would not know that she was baptised when aged 20.    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by benwbrum** [comment]
Birthday calculation is not on the 1.1 roadmap.  I think that we discussed this several months ago and decided it's complex enough it should be prioritized when we add new capacities like UCF and wild cards to the search engine.

**Comment by Sherlock21** [comment]
Yes,Ben I have raised this one before. 
I have recently transcribed many records where "children" have been up to 25 years old at data of baptism. So i campaigned strongly for using Birth date first choice, then if that not present, use Baptism date.
I would like it top priority in next rev please.

**Comment by Captainkirkdawson** [comment]
It is clear that FR1 does search using  the birth date as well as a baptism date.

**Comment by benwbrum** [comment]
Do we have any idea where it pulls this birth date from?  If there's a
field (or combination of them) in `freereg1_csv_entry`, we might be able to
turn `search_record.search_date` into an array and fill it with both
values.

This would likely take 2-4 days of my time, so we need to be very careful
about how it might affect an Easter release of FreeREG 2.1.1.

**Comment by Captainkirkdawson** [comment]
The 'freereg1_csv_entry` for a baptism has 2 fields. baptism_date and birth_date. In most cases the latter is not in the register.

**Comment by benwbrum** [comment]
Have we decided that this is a "must do" for 1.1?

**Comment by Captainkirkdawson** [comment]
Ben

Good scrum only me/eric and darren

If possible yes BUT only after other actions. The last of 1.1 things
however may require rebuild methinks. Lets discuss tomorrow.

Waffleboard is up to date

K

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

On Thu, Mar 19, 2015 at 10:12 AM, Ben W. Brumfield <notifications@github.com

**Comment by benwbrum** [comment]
Sounds good. Will do sort work in master and only attempt birth date in a branch.

**Comment by Sherlock21** [comment]
A fairly obvious comment on this topic if I may: with the related speak about extrapolating & "calculating" dates: that can only be done in the case of BAPTISM dates, & not for Birth dates. And the Register is written in Baptism data order, ONLY if the rows being used for the interpolation of Birth Year contains sequentially numbered entries as EricD says elsewhere.
For Birth dates its only the Year which is necessary and so dates like \* \* yyyy can be used.

**Comment by EmJayFry** [comment]
On 2015/03/19 20:17 PM, Sherlock21 wrote:

> And the Register is written in Baptism data order,

Whilst this is the general case, it doesn't always apply to earlier records. 
I've seen registers in which leaves have become detached  and then images taken 
of the leaves in the sequence found. Resulting in "out of sequence" records.

## 

Regards,
Mike Fry (Jhb)

**Comment by Sherlock21** [comment]
All the records that I had come across which do have Register Numbers, were all in tact - so they are capable of indexing into that order to facilitate such manoeuvring. I only had loose pages of the stuff that was so old it was pre- sequence numbers.
- so i did not think about that option, Mike. 
  So I How does the coder cover this eventuality?
- BEN - can you cope with this? Are the records that you will be taking into account to work out the Year, be next to each other by some mechanism at this point, like they were in the input file?

OR do we have to give up on records that don't have a BIRTH YEAR of their own?
 and abandon trying to work out the year?

**Comment by Captainkirkdawson** [comment]
My twopeneth. Two steps. Replicate FR1 and use included birth-date from a
transcription then later think about calculation

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Sherlock21** [comment]
The more I try and think out how i would specify exactly what to do in order to compute missing Birth Dates, the harder I find it to cover all the possibilities - as you can see from my remarks above.
If the Exec wants to put the application for searching out there to public in the next few weeks, then I would agree with Kirk - just include the simple bit of extracting real full birth dates for that Go Live launch. ( equates to What we had in F1). 

Then have all the debate about the extra bits of sources for the next rev.

**Comment by edickens** [comment]
I think the whole question of missing dates is the same as UCF. There 
are entries with just a Star which need the approximate date working 
out.  And perhaps we could include in this debate what we do about 
ranges of years which we know are missing, perhaps because the registers 
are lost.
This level of detail is not important as it is not in FR1.  But it would 
be a huge bonus to us over the other websites.  We do need to have a 
full discussion and define what we want to do before we do any 
programming in this area.  V1.4+?
EricD

---

Eric J Dickens
FreeREG Chairman

**Comment by Captainkirkdawson** [comment]
Well done Ben

![sts](https://cloud.githubusercontent.com/assets/2874694/6830014/b8e858de-d2dc-11e4-8c5d-6360eea0aad2.JPG)
