### ISSUE TITLE
Search results by county do not match by results by county/place nor FR1 (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#188]
Issue reported by **REGManager** at 2015-03-18 12:12:10 UTC
Time: 2015-03-18T11:58:54+00:00
Session ID: 50171e76f67cfc3d0df3b4665e5c7448
Problem Page URL: [/search_queries/5509687ee93790a09b000026](/search_queries/5509687ee93790a09b000026)
Previous Page URL: [http://freereg2.freereg.org.uk/search_queries/new](http://freereg2.freereg.org.uk/search_queries/new)
Reported Issue:
If you search Joseph TAYLOR STS MA 1780 to 1790 then there are 12 results.  (FR1 give 191 but that is a red herring.)  The first relevant entry that is in FR1 but not FR2 that is significant is Joseph TAYLOR married on 7 Nov 1797 in Clent.  This does not show in the results but if you specify Clent, then you get two results and this entry is there.  See attachment.  So why does specifying a Place bring up entries  that do not come up for the county?
This is a good example for comparing Fr1 and FR2 and Jon and I are working on it.  Let me know if you need more details.    

![Screenshot](http://freereg2.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1426680730-79483-4457/Capture.JPG)

**Comment by Captainkirkdawson** [comment]
Think I know what is going on. It is a results of our using a new form of limiting number of records scanned; which does not give a termination message

**Comment by edickens** [comment]
I have done a detailed analysis and there should  be 25 results not 12.  So when corrected and tested, then this should be what is found.

**Comment by Captainkirkdawson** [comment]
The issue with respect to Clent not appearing in the county all places
results is resolved in the new search.

However I only get 8 marriages for that period. and 48 events in total.

Can you provide additional information if you believe that more results
should be produced.

K

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Captainkirkdawson** [comment]
My reading of the FR1 results is that there are only 7 marriages of a
Joseph Taylor in the period.

Remember FR1 does not do an exact match a Luke Taylor groom is retrieved if
there is a Joseph Something as a witness

K

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1
