### ISSUE TITLE
Where has the batch gone to that generated the Church name "St Mary the Virgin Lds" (ericb)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#189]
Issue reported by **ericb** at 2015-03-19 14:57:39 UTC
Time: 2015-03-19T14:50:38+00:00
Session ID: dd5fc72c6f86772c7b2c58c144e55dba
Problem Page URL: [/registers/5409ca42eca9eba206013794](/registers/5409ca42eca9eba206013794)
Previous Page URL: [http://freereg2.freereg.org.uk/places](http://freereg2.freereg.org.uk/places)
Reported Issue:
I noticed this wrong church name here (in CON/ Place = Botus Flemming).
- noticed it only on account of the Lds at the end of the church name.

But There is no file listed here - which there must have been once upon a time, to generate the church name.
If there was a file once, which got deleted by some means, why did the file deleting or the next reload not remove the upward trail of church name with no matching up file please?
Is there not such a tidy up in the daily update program?    

![Screenshot](http://freereg2.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1426777059-65055-0671/Screen_shot_2015-03-19_at_14.51.24.jpg)

**Comment by Captainkirkdawson** [comment]
As discussed elsewhere we are presently using the KISS approach for name management in Place/Church/Register.
Hence it is up to you/CC to decide if the name should be retained.
