### ISSUE TITLE
Kirk Test (kirkbedfordshire)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#19]
Issue reported by **kirkbedfordshire** at 2014-09-17 16:26:57 UTC
Time: 2014-09-17T16:23:29+00:00
Session ID: 53cb56102e68fd7ab543227eeb9fb40c
Problem Page URL: [/manage_resources/539a6a43eca9eb57f100060b](/manage_resources/539a6a43eca9eb57f100060b)
Previous Page URL: [http://xanthus.freereg2.zomo.co.uk/refinery/login](http://xanthus.freereg2.zomo.co.uk/refinery/login)
Reported Issue:
Just testing

**Comment by Captainkirkdawson** [comment]
Further testing
