### ISSUE TITLE
"About us" has gone missing (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#190]
Issue reported by **REGManager** at 2015-03-24 15:54:17 UTC
Time: 2015-03-24T15:52:11+00:00
Session ID: f05336e34488eb8b4b0136ab6b10632c
Problem Page URL: [/search_queries/new](/search_queries/new)
Previous Page URL: [http://freereg2.freereg.org.uk/manage_resources/new](http://freereg2.freereg.org.uk/manage_resources/new)
Reported Issue:
The About Us link on the homepages  comes up with Page not found.  But I cannot report a problem from it because when I have logged in and return to the homepage, the About Us option is no longer there.
EricD    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
That's because the page that the link goes to has been removed from refinery

**Comment by FreeUKGenIssues** [comment]
Do we need to restore it from backup?

**Comment by Captainkirkdawson** [comment]
No. The file has been renamed. Need to change the link. Cannot do until we have completed the testing and redeployment of the update that recently finished.

**Comment by benwbrum** [comment]
That's good news.

**Comment by Captainkirkdawson** [comment]
Relinked
