### ISSUE TITLE
File not being updated from FR1 (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#192]
Issue reported by **REGManager** at 2015-03-31 13:51:33 UTC
Time: 2015-03-31T13:44:50+00:00
Session ID: 1647081f08df72f54436f7fa3c3eda81
Problem Page URL: [/freereg1_csv_entries?_method=get&page=211](/freereg1_csv_entries?_method=get&page=211)
Previous Page URL: [http://freereg2.freereg.org.uk/freereg1_csv_entries?_method=get&page=212](http://freereg2.freereg.org.uk/freereg1_csv_entries?_method=get&page=212)
Reported Issue:
The file STSSTBBU1.CSV of UserID bevstubbs1 for Stoke-on-Trent : Fenton Cemetery Records was update on 27 March 2015 in FR1 but the version in FR2 is 14 March 2015.    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
That's because I have not had time to run the processes. I had been trying
to get the deployment to production servers done. There are only so many
hours in a day.

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by edickens** [comment]
Sorry Kirk.

I thought that they were running every night.  Please let me know when 
you get to that stage.

Ignore my other emails on the subject of file updating.

Eric

---

Eric J Dickens
FreeREG Chairman

**Comment by Captainkirkdawson** [comment]
They are automated but still need a manual kickoff as I have yet to learn
how to execute a regularly scheduled task.

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1
