### ISSUE TITLE
Missing batch/ file of mine Ericb/WRYDEWBA9.csv (ericb)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#194]
Issue reported by **ericb** at 2015-04-04 16:18:07 UTC
Time: 2015-04-04T16:06:55+00:00
Session ID: e4373bd4885d4ba0b729ca566f0c965e
Problem Page URL: [/freereg1_csv_files/selection?option=List%20by%20Filename](/freereg1_csv_files/selection?option=List%20by%20Filename)
Previous Page URL: [http://freereg2.freereg.org.uk/freereg1_csv_files/my_own?](http://freereg2.freereg.org.uk/freereg1_csv_files/my_own?)
Reported Issue:
I noticed that this file of mine ( which has been in F1 for some weeks in various states of increasing the data in it,) was last updated 31 Mar 2015 in by area in F1.

But this file is nowhere to be seen in FR2.
Does your daily update take from my filestore in F1? or from what's been uploaded into F1 app? 
Some unique records from this file do come out in a search of F1 so one edition of the file must be there in F1.     

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Caused by a failed update and finger trouble on the restart. Trying too hard; need to slow down. Will appear after you do another change to the file in FR1

**Comment by edickens** [comment]
I think that there are a few files like this, which have not got onto 
FR2 for various reasons.  But, once everything has settled down, then 
these will come across, either when they next get amended, or when we 
identify them and then upload them again into FR1 to force a new updated 
date and so they will get passed to FR2.

When we open to Coordinators I want to do some reconciliation between 
the two databases and then we can see how they match up. Anything can be 
fixed just by uploading again into FR1.  No editing facilities are 
needed yet in FR2.

The number of these files is very small and I don't think this will stop 
us from going live to researchers as soon as Kirk can get the FR2 from 
FR1 updating to run automatically every day.

E

**Comment by Sherlock21** [comment]
Noted that. i think we are all suffering from the fatigue.
Done another update on the file in F1. So see where we go from here - 16:26 BST. if I am in-time for today's update.
EB

**Comment by Captainkirkdawson** [comment]
Actual problem was that the character set had a space at the end. Now strip the field
