### ISSUE TITLE
Table formatting incorrect (Helen)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#195]
Issue reported by **Helen** at 2015-04-09 16:43:23 UTC
Time: 2015-04-09T16:37:10+00:00
Session ID: 
Problem Page URL: []()
Previous Page URL: [http://www13.freereg.org.uk/contacts/new](http://www13.freereg.org.uk/contacts/new)
Reported Issue:
Hi, the FreeReg2 search screen returns a list of results which may be correct but it is difficult to tell as the left hand side of the list, and consequently most of the christian names, is cropped off.  I reported this to Eric Dickens when FreeReg2 was first made available for beta, so this is just to let you know that the recent improvements you have made have not yet solved this issue.    

![Screenshot](http://test-cluster.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1428597803-12458-4222/screenshot_of_freereg2_bug.JPG)

**Comment by Sherlock21** [comment]
I just ran a search  on my Desktop iMac and all is well with that result screen.( snip of screen image attached)  Its just fine.
What instrument was the user using?

**Comment by Captainkirkdawson** [comment]
No attachment or screeshot

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Sherlock21** [comment]
K

I tried to attach the jpg ( now on here)

No clue that it had not been attached except that I could not see the image at that time.
Not unusual, as I have to log out and back again to see it in the website page.

E

**Comment by Captainkirkdawson** [comment]
Problem is caused by use of IE 8 which does support most formatting.
IE8 is no longer supported.

**Comment by Sherlock21** [comment]
So what's the consequence of this disclosure please - if any?

What do we need to do?
or NOT do?

EricB

**Comment by edickens** [comment]
I suggest we do nothing, unless we put something in the Help notes.
E

---

Eric J Dickens
FreeREG Chairman
