### ISSUE TITLE
Transcriber Registration page the info boxes are clipped by the page header/footer (Cathy)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#196]
Issue reported by **Cathy** at 2015-04-10 09:50:21 UTC
Time: 2015-04-10T09:42:16+00:00
Session ID: 
Problem Page URL: []()
Previous Page URL: [http://www13.freereg.org.uk/contacts/new](http://www13.freereg.org.uk/contacts/new)
Reported Issue:
Hi. Just a few minor errors I have spotted:
On the Transcriber Registration page the info boxes are clipped by the page header/footer

Otherwise, looks great at the moment. 

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by benwbrum** [comment]
Possibly an IE8 issue?
