### ISSUE TITLE
Ann does not find Anne except with soundex (Keith Hayton)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#198]
Issue reported by **Keith Hayton** at 2015-04-11 08:37:41 UTC
Time: 2015-04-11T08:26:34+00:00
Session ID: 
Problem Page URL: []()
Previous Page URL: [http://www13.freereg.org.uk/contacts/new](http://www13.freereg.org.uk/contacts/new)
Reported Issue:
Enter text here...Trying the new FreeReg2 search facility, I find a couple of oddities
1) When entering data the tab key does not work immediately to move from one box to the next - you have to press the tab key twice in succession to get it to move
2) When entering forenames that can vary in spelling - the example that I used was Ann or Anne - it does not find an entry if the "wrong" spelling is used without soundex on the surname, but does find it with soundex on the surname selected (but then also finds numerous other entries that clutter the search).  The example that I used is a baptism for Sarah Ann Hayton at Lancaster St Thomas on 16 May 1852.  Can soundex be automatic on forenames because the spelling of so many forenames can vary, whilst still retaining exact spelling for surnames?    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Sherlock21** [comment]
Should the solution here appears to be to just put ANNE and also ANNIE into the lookup list of common variations of first names which you once told me you have.
Or was such a table a "future development" because I just tried to locate Ben records without soundex (knowing there are Benjamin ones)

**Comment by benwbrum** [comment]
I believe that we need to work on this in #516
