### ISSUE TITLE
SNAG for Place Name Edit in F2. (ericb)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#20]
Issue reported by **ericb** at 2014-09-18 13:34:15 UTC
Time: 2014-09-18T13:32:36+00:00
Session ID: addd8d1925dd1b9f48f0060015c27312
Problem Page URL: [/manage_resources/539a6a3ceca9eb57f1000550](/manage_resources/539a6a3ceca9eb57f1000550)
Previous Page URL: [http://xanthus.freereg2.zomo.co.uk/refinery/login?](http://xanthus.freereg2.zomo.co.uk/refinery/login?)
Reported Issue:
The edit feature does not do the right things, or is wrongly named for what it does do. ie Called Edit Place. but won't edit Place Names.

Long email to Kirk also sent.

EricB

**Comment by Captainkirkdawson** [comment]
Have changed the label to Edit Place Details
