### ISSUE TITLE
Daily  update check of UserIDs (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#200]
Issue reported by **REGManager** at 2015-04-13 07:19:24 UTC
Time: 2015-04-13T07:14:42+00:00
Session ID: 13c89f08c94ff411b1ccecf52c32a774
Problem Page URL: [/userid_details/selection?option=Select%20specific%20userid](/userid_details/selection?option=Select%20specific%20userid)
Previous Page URL: [http://freereg2.freereg.org.uk/userid_details/options](http://freereg2.freereg.org.uk/userid_details/options)
Reported Issue:
The report is showing UserID for people who have not completed registration.
If "NewlyEntered" = "True" then these UserIDs should be ignored.  They cannot upload into FR1.  We get a few who never complete registration.
Anyone who completes registration I also enter into FR2.
E    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
But FR1 has created folders for them. Currently the system does no processing of the information in those folders it simply reports that they do not exist in FR2. 
Not sure that we should be putting application logic into this process that may/may not always be true.

**Comment by Captainkirkdawson** [comment]
Propose to close.I do not think we should eliminate these from the report.

**Comment by edickens** [comment]
```
Yes Close.  I have told CCs that I will delete non-completed
registrations in FR1 after a week so these will eventually
disappear.
Interesting that there are some which I have deleted and are not in
FR1 and not in FR2 but are still in the report.  I'm waiting to see
if they disappear after the FR1 update.
E
_____________________________________
```

Eric J Dickens
FreeREG Chairman
    On 22/04/2015 17:27, Kirk Dawson wrote:

```
  Propose to close.I do not think we should eliminate these from
    the report.
  —
    Reply to this email directly or view
      it on GitHub.
```
