### ISSUE TITLE
possible duplicated record ( reported by user) (ericb)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#204]
Issue reported by **ericb** at 2015-04-15 15:17:12 UTC
Time: 2015-04-15T15:11:50+00:00
Session ID: 5ee6286d55d8d7ad60fdfe00930c9761
Problem Page URL: [/search_records/5510c049e93790332ea0e589?search_id=552e7f72f493fd77dc00087a](/search_records/5510c049e93790332ea0e589?search_id=552e7f72f493fd77dc00087a)
Previous Page URL: [http://freereg2.freereg.org.uk/search_queries/552e7f72f493fd77dc00087a](http://freereg2.freereg.org.uk/search_queries/552e7f72f493fd77dc00087a)
Reported Issue:
Robert Clark Bap LIN/ Horncastle 28 Oct 1791 come up twice in a name/ place/ date Bap. search.

One is from file: Mick.LINHORBA1.CSV.686
OTHER IS from file: Mick1952.LINHORBA1.CSV686

Is this from having 2 user ids for the transcriber? or just bad luck 2 people did the same bit or Register!
Not referred to the CC for LIN . if you think its his call, please reply thus & I will pass to Mick.

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
This is not a system problem but a data input matter and should be dealt
with by the syndicate/county coordinator.

K

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Sherlock21** [comment]
K

OK, I thought as much.

So shall you close that one then ?

EB

**Comment by edickens** [comment]
```
Hi Kirk,
We will get the same entry more than once if we have more than one
of PR, TR, BT, PH or others.  The point that needs to be made it
that the Register Source needs to be entered.
I would like to sort this sort of thing out when CCs are live.
E
_____________________________________
```

Eric J Dickens
FreeREG Chairman
    On 15/04/2015 16:17, FreeUKGenIssues
      wrote:

```
  Issue reported by ericb at 2015-04-15
    15:17:12 UTC
    Time: 2015-04-15T15:11:50+00:00
    Session ID: 5ee6286d55d8d7ad60fdfe00930c9761
    Problem Page URL: /search_records/5510c049e93790332ea0e589?search_id=552e7f72f493fd77dc00087a
    Previous Page URL: http://freereg2.freereg.org.uk/search_queries/552e7f72f493fd77dc00087a
    Reported Issue:
    Robert Clark Bap LIN/ Horncastle 28 Oct 1791 come up twice in a
    name/ place/ date Bap. search.
  One is from file: Mick.LINHORBA1.CSV.686
    OTHER IS from file: Mick1952.LINHORBA1.CSV686
  Is this from having 2 user ids for the transcriber? or just bad
    luck 2 people did the same bit or Register!
    Not referred to the CC for LIN . if you think its his call,
    please reply thus & I will pass to Mick.

  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by Sherlock21** [comment]
Yes EricD
That possibility had not escaped me, and indeed I checked that before I wrote to either of you.

But yes: At what point do we introduce the stand alone code for the Record source types?

My view is ASAP after go live since we could really do with a back-fit task by CC's so we can resolve that reason for seeing duplicates in a search before i get millions more emails!

EricB

**Comment by edickens** [comment]
CCs should now be getting the transcribers to add the register source 
after the Church name whenever a file is amended.
E

---

Eric J Dickens
FreeREG Chairman

**Comment by Sherlock21** [comment]
Eric d

my point was: Introduce the new stand alone field for the code.
and have it validated on upload of the file when we do the changes to work with FR2 only.

EB

**Comment by edickens** [comment]
We have quite a few extra fields to add, but that will be in the 
Enhancement Versions, after we have everything else working.

---

Eric J Dickens
FreeREG Chairman
