### ISSUE TITLE
Website Problem (Rob Hoare)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#206]
Issue reported by **Rob Hoare** at 2015-04-17 01:24:07 UTC
Time: 2015-04-17T01:17:31+00:00
Session ID: 
Problem Page URL: []()
Previous Page URL: [http://www13.freereg.org.uk/contacts/new](http://www13.freereg.org.uk/contacts/new)
Reported Issue:
I was going to suggest having a list of the places that are being searched for the "nearby" search, and how far they are, but I see you have that on the "about this search" page.

However, it lists places which are NOT nearby.  In the example below, only the first 20 are geographically close, the second 20 are far away, don't have a county shown, and have the wrong distance:

Name

Search Criteria: 
First Name is THOMAS, Last Name is HOARE. Exact matching is enabled

Date

No date criteria specified.

Records

All three record types, Baptisms, Burials and Marriages were included.

Location

Search Criteria: Search additional places near Charterhouse in Middlesex

Farringdon (London) (0 miles)
Cripplegate (London) (0 miles)
Clerkenwell (Middlesex) (0 miles)
Castle Baynard (London) (0 miles)
Bread Street (London) (0 miles)
Cheap (London) (0 miles)
Cordwainer (London) (0 miles)
Broad Street (London) (0 miles)
Walbrook (London) (0 miles)
Queenhithe (London) (0 miles)
Cornhill (London) (0 miles)
Vintry (London) (0 miles)
Bishopsgate (London) (0 miles)
Langbourn (London) (0 miles)
Bloomsbury (Middlesex) (1 miles)
St Pancras (Middlesex) (1 miles)
Aldgate (London) (1 miles)
Tower (London) (1 miles)
Covent Garden (Middlesex) (1 miles)
Shoreditch (Middlesex) (1 miles)
Aird and Sheshader () (1 miles)
Leek Civil Registration District () (1 miles)
Cannock Civil Registration District () (1 miles)
Nk () (1 miles)
Greenwichenwich () (1 miles)
Idmiston with Porton () (1 miles)
Fuggleston and Bemerton () (1 miles)
Bodington () (1 miles)
Canworthy () (1 miles)
Newton(cambridge) () (1 miles)
Feckham () (1 miles)
Lythe () (1 miles)
North Otterington () (1 miles)
St Just in Penwith () (1 miles)
West Hamm () (1 miles)
Stanford le Hope () (1 miles)
Cwmamman () (1 miles)
Prior's Dean () (1 miles)
Lincoln Pr () (1 miles)
Horsham () (1 miles)

Rob    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Ben
This is NOT an error in your coding.
Places that have an invalid Place name and therefore no known location have an assigned location. The Tower of London until they are corrected!! My sick sense of humour.

**Comment by Captainkirkdawson** [comment]
Also duplicate
