### ISSUE TITLE
Website Problem (Ian Maule)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#207]
Issue reported by **Ian Maule** at 2015-04-17 07:30:29 UTC
Time: 2015-04-17T07:25:19+00:00
Session ID: 
Problem Page URL: []()
Previous Page URL: [http://www13.freereg.org.uk/contacts/new](http://www13.freereg.org.uk/contacts/new)
Reported Issue:
Thanks you for the new website and enhanced search facility. However, light grey text on a white background is _very_ hard to read.      

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Replied using comments by Darren
