### ISSUE TITLE
Snag: Creste New Place name (ericb)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#21]
Issue reported by **ericb** at 2014-09-18 13:35:57 UTC
Time: 2014-09-18T13:34:16+00:00
Session ID: addd8d1925dd1b9f48f0060015c27312
Problem Page URL: [/feedbacks/541adf57eca9ebb47a000001](/feedbacks/541adf57eca9ebb47a000001)
Previous Page URL: [http://xanthus.freereg2.zomo.co.uk/feedbacks/new?feedback_time=2014-09-18+13%3A32%3A36+UTC&feedback_type=issue&previous_page_url=http%3A%2F%2Fxanthus.freereg2.zomo.co.uk%2Frefinery%2Flogin%3F&problem_page_url=%2Fmanage_resources%2F539a6a3ceca9eb57f1000550&session_id=addd8d1925dd1b9f48f0060015c27312&user_id=ericb](http://xanthus.freereg2.zomo.co.uk/feedbacks/new?feedback_time=2014-09-18+13%3A32%3A36+UTC&feedback_type=issue&previous_page_url=http%3A%2F%2Fxanthus.freereg2.zomo.co.uk%2Frefinery%2Flogin%3F&problem_page_url=%2Fmanage_resources%2F539a6a3ceca9eb57f1000550&session_id=addd8d1925dd1b9f48f0060015c27312&user_id=ericb)
Reported Issue:
This will no longer work with inputting a Grid REf. - only responds to a Lat/long values. - but these can be changed to GridREf after the place name is created.

It was like this once before. but was fixed.

EricB

**Comment by Captainkirkdawson** [comment]
Ben
This issue has urls linked to the feedback pages which are clearly of limited value

**Comment by Captainkirkdawson** [comment]
Issue with failure of code to add location from Grid Ref fixed
