### ISSUE TITLE
PDF print (Damian Cummings)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#210]
Issue reported by **Damian Cummings** at 2015-04-19 18:24:17 UTC
Time: 2015-04-19T18:05:34+00:00
Session ID: 
Problem Page URL: []()
Previous Page URL: [http://www13.freereg.org.uk/contacts](http://www13.freereg.org.uk/contacts)
Reported Issue:
Thank you so much for the update to the website- it is looking really great and I much prefer the new layout.

I have an issue when I print a page to PDF (which I do routinely for every record I refer to, and link it on the Sources pages on my genealogy software).  As you will see from the attached file (which I have converted to a JPG file for attachment), it is impossible to see any of the information.  I have tried changing a few settings but to no avail and I do not usually have a problem with other sites. I do not have a printer to check if I would have the same problem if I printed a hard copy but presumably so...

Any chance of addressing this somehow?

Thanks,

Damian    

![Screenshot](http://freereg2.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1429467857-60420-3511/ROBBINS__Ursula_Coleman__bap1835.jpg)

**Comment by Sherlock21** [comment]
There is a need to enable users to be able to use the traditional quick keys for Print result (CMD+P in Mac, ) and for copy a block of results ( CMD+C in Mac followed by CMD+V to print the copied information in another user document without loosing its format.
As well as saving it formatted as a pdf.
Maybe the loss of formatting that we have, is related to the point made by Rob Hoare relating to padding and borders. - sort that, and we can effectively increase the number of records per page.

**Comment by Sherlock21** [comment]
Well, whatever someone has done, has restored one of the Mac ways to capture the screen of FR2 data. Attaches search result screen can be copied off and saved or then printed.
Also, the full screen dump now works too.
Quick keys are CMD+Shift+4 for the copy what part you want and CMD+shift+3 is full screen dump.
So this could take some pressure off producing a Record Print icon and support for the time being.
This puts the copied item on your desktop if that's where you route it to, from where you can print.

Unless you can't remember what you did stop this failing 5 days ago!

**Comment by Captainkirkdawson** [comment]
We introduced a print format option on results quite a while ago; guess we forgot to close
