### ISSUE TITLE
Website Problem (Damian Cummings)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#211]
Issue reported by **Damian Cummings** at 2015-04-19 18:29:28 UTC
Time: 2015-04-19T18:05:34+00:00
Session ID: 
Problem Page URL: []()
Previous Page URL: [http://www13.freereg.org.uk/contacts](http://www13.freereg.org.uk/contacts)
Reported Issue:
Thank you so much for the update to the website- it is looking really great and I much prefer the new layout.

I have an issue when I print a page to PDF (which I do routinely for every record I refer to, and link it on the Sources pages on my genealogy software).  As you will see from the attached file (which I have converted to a JPG file for attachment), it is impossible to see any of the information.  I have tried changing a few settings but to no avail and I do not usually have a problem with other sites. I do not have a printer to check if I would have the same problem if I printed a hard copy but presumably so...

Any chance of addressing this somehow?

Thanks,

Damian    

![Screenshot](http://freereg2.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1429468168-60417-5571/ROBBINS__Ursula_Coleman__bap1835.jpg)

**Comment by Captainkirkdawson** [comment]
Duplicates
