### ISSUE TITLE
For future transcriber versions (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#212]
Issue reported by **REGManager** at 2015-04-19 21:04:52 UTC
Time: 2015-04-19T21:03:45+00:00
Session ID: 4f771f03a2fe7881014a74bb7a21f76e
Problem Page URL: [/contacts/5533f408f493fdb5c6003068](/contacts/5533f408f493fdb5c6003068)
Previous Page URL: [http://freereg2.freereg.org.uk/contacts](http://freereg2.freereg.org.uk/contacts)
Reported Issue:
18:05 on 2015-04-19
Name of Contactor:  Damian Cummings
Email address of Contactor :    damiancummings@gmail.com
Explanation:    Thank you so much for the update to the website- it is looking really great and I much prefer the new layout. I have an issue when I print a page to PDF (which I do routinely for every record I refer to, and link it on the Sources pages on my genealogy software). As you will see from the attached file (which I have converted to a JPG file for attachment), it is impossible to see any of the information. I have tried changing a few settings but to no avail and I do not usually have a problem with other sites. I do not have a printer to check if I would have the same problem if I printed a hard copy but presumably so... Any chance of addressing this somehow? Thanks, Damian    

![Screenshot](http://freereg2.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1429477492-60417-1703/Capture.JPG)

**Comment by Captainkirkdawson** [comment]
Eric

Those contacts that are sent as Website problems are automatically created as github issues. This one was 211. So all you need to do is add a comment to it on github

But thank you for doing it

**Comment by edickens** [comment]
```
Hi Kirk,

I'm not sure of all the distribution yet.  Also, whether we send a
copy back to the originator to thank them.  I also don't know, after
I have send on details to a CC, whether they have done anything with
it.

E
_____________________________________
```

Eric J Dickens
FreeREG Chairman
    On 20/04/2015 09:00, Kirk Dawson wrote:

```
  Eric
  Those contacts that are sent as Website problems are
    automatically created as github issues. This one was 211. So all
    you need to do is add a comment to it on github
  But thank you for doing it
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by Captainkirkdawson** [comment]
Website issues come directly to Ben and I.
Data problems go to DM and CCs

**Comment by edickens** [comment]
```
Thanks.  I will only deal with data problems.  I'll let you and Ben
reply to the website problems.

E
_____________________________________
```

Eric J Dickens
FreeREG Chairman
    On 20/04/2015 09:11, Kirk Dawson wrote:

```
Website issues come directly to Ben and I.
  Data problems go to DM and CCs

  On Mon, Apr 20, 2015 at 2:07 AM Eric Dickens
  <notifications@github.com>
  wrote:

  >
  >
  >
  >
  >
  > Hi Kirk,
  >
  > I'm not sure of all the distribution yet. Also, whether we
  send a
  > copy back to the originator to thank them. I also don't know,
  after
  > I have send on details to a CC, whether they have done
  anything with
  > it.
  >
  > E
  > _____________________________________
  > Eric J Dickens
  > FreeREG Chairman
  > On 20/04/2015 09:00, Kirk Dawson wrote:
  >
  >
  > Eric
  > Those contacts that are sent as Website problems are
  > automatically created as github issues. This one was 211. So
  all
  > you need to do is add a comment to it on github
  > But thank you for doing it
  > —
  > Reply to this email directly or view
  > it on GitHub.
  >
  > —
  > Reply to this email directly or view it on GitHub
  >
```

https://github.com/FreeUKGen/FreeUKGenProductIssues/issues/212#issuecomment-94387896
      > .
      >
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by benwbrum** [comment]
This covered by #366
