### ISSUE TITLE
Places Nearby are claimed to showbe (ericb)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#213]
Issue reported by **ericb** at 2015-04-20 11:02:12 UTC
Time: 2015-04-20T11:01:35+00:00
Session ID: 2e58f4768baea72f520d8a05b2e15ae8
Problem Page URL: [/search_queries/5534daaff493fdb5c6003821](/search_queries/5534daaff493fdb5c6003821)
Previous Page URL: [http://freereg2.freereg.org.uk/search_queries/5534daaff493fdb5c6003821/about](http://freereg2.freereg.org.uk/search_queries/5534daaff493fdb5c6003821/about)
Reported Issue:

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Sherlock21** [comment]
DELET THIS PLEASE>  RUBBISH TITLE- report went off to Github before I had compiled it!
