### ISSUE TITLE
Setting up a new UserID reports an error (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#215]
Issue reported by **REGManager** at 2015-04-20 16:35:04 UTC
Time: 2015-04-20T16:25:27+00:00
Session ID: 75770d37a984f0288eb3fccb0a4cc7b5
Problem Page URL: [/userid_details/55352821f493fdb5c6003abe](/userid_details/55352821f493fdb5c6003abe)
Previous Page URL: [http://freereg2.freereg.org.uk/userid_details/selection?option=Select%20specific%20userid](http://freereg2.freereg.org.uk/userid_details/selection?option=Select%20specific%20userid)
Reported Issue:
When setting up a new UserID I get the attached message.  But the UserID has been set up.  I think the problem is with sending out the email to get them to set up their Password.  That is not being generated as far as I can tell.

It has happened twice with UserIDs SMB and jonbunker

This has been working until today, the first time I have used it since  16 April.    

![Screenshot](http://freereg2.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1429547704-60417-8096/Capture.JPG)

**Comment by Captainkirkdawson** [comment]
Did a quick fix to stop the blow up

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by edickens** [comment]
Sorry.  Same problem.
E

---

Eric J Dickens
FreeREG Chairman

**Comment by Captainkirkdawson** [comment]
Had not deployed at that point; have now

**Comment by edickens** [comment]
Working fine now.  Can be closed.

---

Eric J Dickens
FreeREG Chairman

**Comment by Captainkirkdawson** [comment]
The cause of the issue has to be addressed There was an error in my code to
allow the inclusion of the link as an active address, Simply removed that
code to fix your problem.

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Captainkirkdawson** [comment]
Have fixed the message I hope

**Comment by edickens** [comment]
```
Yes.  Working fine.  I have been using it.
Eric
_____________________________________
```

Eric J Dickens
FreeREG Chairman
    On 22/04/2015 16:31, Kirk Dawson wrote:

```
  Have fixed the message I hope
  —
    Reply to this email directly or view
      it on GitHub.
```
