### ISSUE TITLE
New update report message (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#216]
Issue reported by **REGManager** at 2015-04-21 10:24:22 UTC
Time: 2015-04-21T10:20:20+00:00
Session ID: 6e9ce921e9a16ec4616ba4ee622d2e5c
Problem Page URL: [/freereg_contents/new](/freereg_contents/new)
Previous Page URL: [http://freereg2.freereg.org.uk/](http://freereg2.freereg.org.uk/)
Reported Issue:
I have not seen the attached message before and it has occurred twice last night.
It is saying that the file has not changed.  But if it hasn't changed, why has it been selected for updating and yet not processed?  Is this part of Kirk's new quicker system?  Or is it because the date and file size are the same?  If the latter it could be just a date change when the file does need updating.
E    

![Screenshot](http://freereg2.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1429611862-84209-6044/Capture.JPG)

**Comment by Captainkirkdawson** [comment]
Yes noticed that too.

The files in question had somehow got a different modification date on FR1
and were therefore notified to the update processor as having changed. The
later then looks at the digest of the file on the file on FR2 and says it
has not changed so it does not get processed.. It would be useful for you
to determine if  someone had /had not done something to the file and is so
what.

K

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by edickens** [comment]
It could have been a header change or they just uploaded again for 
backup.  I'll investigate.
E

---

Eric J Dickens
FreeREG Chairman
