### ISSUE TITLE
New PlaceName has Data but flag shows False (ericb)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#22]
Issue reported by **ericb** at 2014-09-19 14:24:04 UTC
Time: 2014-09-19T14:18:33+00:00
Session ID: 46b07f304a3d1594cdaddf73851400d1
Problem Page URL: [/places?page=3](/places?page=3)
Previous Page URL: [http://xanthus.freereg2.zomo.co.uk/places?page=2](http://xanthus.freereg2.zomo.co.uk/places?page=2)
Reported Issue:
I created a new place Danby (Guisborough) in NRY. then relocated three batches into it, from Danby. Flag for Danby showed still Data Present. And data present for this place flag shows false.
see email for screen copy of false info. 
Danby Place name now deleted though.

EricB

**Comment by Captainkirkdawson** [comment]
Given deletion of Darby it is no possible to review. Issue closed until we can get duplicated event.
