### ISSUE TITLE
Still a Snag with Nearby feature in Results list.

### ISSUE THREAD

**Issue by Sherlock21** [FreeUKGen/FreeUKRegProductIssues#220]
refer to separate email EB  - BenB 26 Apr 2015.

**Comment by Captainkirkdawson** [comment]
Can you append a copy of that note to this story. No one else can do anything otherwise.

**Comment by Captainkirkdawson** [comment]
See 214

**Comment by benwbrum** [comment]
I found the note: 

I have written the details of this into this email, as I could not do email on my Ipad!

I suggest you run this search to see exactly what's going on.

Search for:  Fisher, Thomas/ Baptisms/ 1700/1850
WRY/ Dewsbury/ Nearby.

I get 13 results and About gives 40 Places out to 11 miles radius.

Seems OK to this point.
Then reduce the radius by the Narrow search.
Still 13 results (OK) and 19 places over 7.5 miles

reduce right down to as far as it goes - 1.2 miles
This says13 results including 1 additional place . - But this does not add up.
There are 13 records listed, but they have:-
Dewsbury ( the nominated Place)
AND
Thornhill, Flockton, Horbury despite it saying ! Additional place.

Using Andrew Hedges online calc ( as mentioned before) and the Lat/ Long from our Locations table,

Dewsbury - Horbury is 3.617 miles       rounded = 4 miles
Dewsbury - Thornhill is 1.964 miles. rounded = 2 miles

**Comment by Captainkirkdawson** [comment]
Confirmed as an issue

**Comment by Captainkirkdawson** [comment]
Fixed
