### ISSUE TITLE
A search on full Forename does not get standard abbreviations and v v.

### ISSUE THREAD

**Issue by Sherlock21** [FreeUKGen/FreeUKRegProductIssues#221]
When I search for Ben  Archer (WRY/DEWSBURY 1837/1840 Baptisms) using his full First Name of Benjamin, he is not picked up.
Similarly: search for Dan does not pick up  any Daniel First names records.
[ in both cases, the record searched for does exist]

**Comment by benwbrum** [comment]
Apparently we didn't load the emendation rules before we did the last rebuild from CSV:

```
irb(main):008:0> pp r.attributes;0
{"_id"=>"551091c2e937900271712213",
 "transcript_dates"=>["20 Aug 1546"],
 "search_dates"=>["1546-08-20"],
 "location_names"=>["Sandy (St Swithin)", "[Unspecified]"],
 "search_soundex"=>
  [{"first_name"=>"W500", "last_name"=>"S530", "type"=>"p"},
   {"first_name"=>"R100", "last_name"=>"S530", "type"=>"f"}],
 "record_type"=>"ba",
 "chapman_code"=>"BDF",
 "file_line_number"=>210,
 "line_id"=>"Biggles.BDFSANBA.CSV.210",
 "transcript_names"=>
  [{"role"=>"ba", "type"=>"primary", "first_name"=>"Wm", "last_name"=>"SMITH"},
   {"role"=>"f", "type"=>"other", "first_name"=>"Rob", "last_name"=>"SMITH"}],
 "freereg1_csv_entry_id"=>"546391e4e9379010fc59e53d",
 "place_id"=>"53cd4934eca9ebee4f00072c",
 "search_names"=>
  [{"_id"=>"551091c2e937900271712214",
    "first_name"=>"wm",
    "last_name"=>"smith",
    "origin"=>"transcript",
    "type"=>"p"},
   {"_id"=>"551091c2e937900271712215",
    "first_name"=>"rob",
    "last_name"=>"smith",
    "origin"=>"transcript",
    "type"=>"f"}]}
=> 0
irb(main):009:0> EmendationRule.count
=> 0
irb(main):010:0> EmendationType.count
=> 0
```

As a result, records like this did not have their search names expanded.

**Comment by Captainkirkdawson** [comment]
Interesting observation.

The build has loading of the emendations as the first step.

OK So what is the recovery?

**Comment by Captainkirkdawson** [comment]
Can we write a rake task to update the search records? If so I can likely fit it into the work next week

**Comment by benwbrum** [comment]
We can absolutely write a rake task to update the search records.  The challenge is figuring out how to make one that performs well and can be scaled.

In testing a few weeks ago, @Sherlock21 discovered that we hadn't incorporated any of the forename research findings into the emendations.  He's made a feature request that we 1) revise the static list of emendations to reflect more common abbreviations and latinizations, and 2) add a feature to coordinator/administrator tools to allow users to add new abbreviations and apply them to the database.  This latter feature may be particularly important for FreeCEN, as I'm finding that frequency and diversity of abbreviations is far more extensive in that dataset than in the FreeREG data.

So it's a good idea to keep that in mind while thinking about possible approaches here, though of course I don't suggest we implement that in the limited time we have to fix this bug.

Possible approaches:
- Naively loop through all search_records and ask them to-redo their `freecen1_csv_entry`-to-`search_record` transformation.  Pro: very straightforward.  Con: would touch every single record in the system; equivalent to a rebuild.
- As in the naive approach, but in batches.  Pro: somewhat more scalable.  Con: not that much better.
- Apply emendations in batches, searching for SearchRecords which match the verbatim text in a particular abbreviation rule (say, `wm`), then transform only those records.  Pro: Much more scalable -- only touches records that need changing.  Con: may double-transform some records (e.g. marriages between `wm` and `eliz`)

What do you think of the approaches, @Captainkirkdawson ?  I'm especially interested in what you think the production database can handle with regards to percolating changes to replica sets.  (Especially changes like this, which are incremental, and fairly low-urgency compared with displaying new transcripts to the volunteers.)

**Comment by Sherlock21** [comment]
A comment on your last para if I may:
I think both types "sources" of data are equally important to the researcher.
In my own transcriptions the pre 1800 data range used a larger percentage of abbreviations in first names than the post 1800 -  eg at random: 9 versions of Elizabeth, 3 versions of George, 4 of Thomas and William. [in a file of 4500 records from 1720 - 1750] Compared with 2 Elizabeth, 1 George, 2 Thomas, 2 William in a file of 2000 records from 1834 to 1840 ]

**Comment by benwbrum** [comment]
I'm going to experiment with this approach: 

Given that we have indexes on `(chapman_code, search_names.first_name,...)`, I'll add a new method to `Emendor` that applies a single rule as follows:

```
   for each chapman_code
      results = search_query on chapman_code & first_name==verbatim text in emendation rule
      for each record in results
         re-transform or re-emend the names
```

That should 1) ensure that we're using an index for processing this mess, and 2) make some stab that the B+tree rebalancing which will be necessary post-transformation will be somewhat localized to the subtree for that chapman_code.

After doing that, I'll create a rake task to call this method on a subset of emendation rules specified on the command line.

**Comment by Captainkirkdawson** [comment]
Sorry for the delay; golf and drinks yesterday pm!!

Like your approach Ben (your 3rd option) (Did not like 1 and 2). It is much
better than recreating search_records. We only update the records that need
an update. Not too concerned over the double for marriages.

Not sure that multiple tasks would help due to IO contention.

Make sure you use no_timeout on the selection.

It would be nice to add edit abilities to the emendations I don't think
that we could ever consider doing an on-line update of the search_records.
We might be able to schedule an emendation update and run overnight. We
might have a better idea of the cost/impact of changing emendations based
on this work and see if it looks viable.

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Captainkirkdawson** [comment]
Ben says the emendations completed BUT it did not appear to fix the issue

**Comment by FreeUKGenIssues** [comment]
What are the specific matches we're attempting that are failing?

**Comment by Captainkirkdawson** [comment]
Anne does not find Ann
Will does not find William

**Comment by benwbrum** [comment]
William does find "Wm" -- search for Wm Smith in Bedfordshire 1500-1600,
then again William Smith using the same criteria.

**Comment by Captainkirkdawson** [comment]
Comment on ann and anne is withdrawn they are not in the rules.
Did my tests on an ancestor. Wm does not get William
Went to Bedforshire
Did a test for Wm Smith . Only Wm was retrieved. A search for William Smith finds Wm
Did a test for thos and only thos is found. A search for Thomas finds thos.
So its only one way; Search on the expansion gives the contraction; Seach on contraction gives only the contraction

**Comment by benwbrum** [comment]
Exactly!  The goal is to support researchers who either don't know about
common abbreviations or don't need to search all possible variants.

Eric Booker has come up with a much improved, data-driven list of
emendation rules, which I hope to create a story to apply.  I think that it
should wait until more of the 1.4 work is finished, however.

**Comment by Sherlock21** [comment]
Ben & Kirk particularly: In my list ( Ben's  ref above) I would be expecting you will enable: A to find B AND vice versa. And also A to find ANY of B or C or D  and each way Vice versa. [ C finds A and B and D for those abbreviations that have more than one option in my list]

**Comment by Captainkirkdawson** [comment]
My comment was that it is one way and not visa versa.

I had been under the impression that it was two way ie visa versa would work

Agree to the need for a story to do a complete rebuild with a new set that
is visa versa as well.Likely 1.7

**Comment by FreeUKGenIssues** [comment]
I think it's likely that we'll have to do a rebuild to pick up the 1.4
changes to the search engine, since there will be substantial re-plumbing
to support wildcards and UCF.  Perhaps we'll be able to apply Eric's
changes then.

(And no, i haven't figured out how to do a rebuild-in-place, though I've
got some ideas.)

**Comment by Captainkirkdawson** [comment]
We could just build a new database and do a switch at the appropriate time

**Comment by FreeUKGenIssues** [comment]
That would certainly be simpler, but how would we deal with updates to the
system between start-of-rebuild and the end, now that the system is open to
transcribers?

**Comment by Captainkirkdawson** [comment]
rsync all files to holding folder. After rebuild from holding folder; lock
upload. rsync changed files to hold, process changed files just like we do
now, switch database, remove upload lock

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1
