### ISSUE TITLE
"Report a problem" going to the wrong person (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#223]
Issue reported by **REGManager** at 2015-05-03 15:03:03 UTC
Time: 2015-05-03T14:56:29+00:00
Session ID: 8e01666e671a4dbfe533dee4d748283a
Problem Page URL: [/freereg_contents/new](/freereg_contents/new)
Previous Page URL: [http://freereg2.freereg.org.uk/](http://freereg2.freereg.org.uk/)
Reported Issue:
Steve (SSX) has received the attached report which is meant for Kent.
How can this happen?
Also, it says it is from reg-web@freereg.org.uk but this should only go to BenL and myself.  These reports, which are not website problems, should go to reg-corrections@freereg.org.uk.
Errors in the place names should go to reg-data@freereg.org.uk
E    

![Screenshot](http://freereg2.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1430665383-12293-9793/Capture.JPG)

**Comment by Captainkirkdawson** [comment]
The report is a copy going to Steve because he has the data_manager role in FR2 so he is getting them as part of that role.
The original went to the Kent coordinator
