### ISSUE TITLE
Updating my own profile fails  (ericb)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#224]
Issue reported by **ericb** at 2015-05-08 20:10:37 UTC
Time: 2015-05-08T20:08:18+00:00
Session ID: f89e836f09cfeabdbabe17ee21c2a4cd
Problem Page URL: [/userid_details/5462b421e937907d70000569](/userid_details/5462b421e937907d70000569)
Previous Page URL: [http://freereg2.freereg.org.uk/userid_details/5462b421e937907d70000569/edit](http://freereg2.freereg.org.uk/userid_details/5462b421e937907d70000569/edit)
Reported Issue:
Tried to update my email address ( from eric.booker@virgin.net) on FR2 but it fails with attached message.    

![Screenshot](http://freereg2.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1431115837-2832-5543/profile_from_FR2.jpg)

**Comment by Captainkirkdawson** [comment]
That is a valid rejection. The system is working as it should.

You have that email address associated with a userid of sherlock22

**Comment by Sherlock21** [comment]
But in FR2, the userid  is me as the DM.

it is ericb and the virgin.net email address.

I think this is a leftover from whenI had to set up several accounts with EricD, to do something for him
so what's the FR2 way out of this one please.

?? delete the sherlock22? 
EB

**Comment by Captainkirkdawson** [comment]
sherlock22 has been destroyed

K

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1
