### ISSUE TITLE
Contact form action to be taken (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#226]
Issue reported by **REGManager** at 2015-05-15 15:43:44 UTC
Time: 2015-05-15T15:19:42+00:00
Session ID: cce86ea3572047bb452685dc0122e3e5
Problem Page URL: [/contacts/55560af5f493fde159001f7a](/contacts/55560af5f493fde159001f7a)
Previous Page URL: [http://freereg2.freereg.org.uk/contacts](http://freereg2.freereg.org.uk/contacts)
Reported Issue:
I'm still not happy with this reporting system.  It works, but is not giving me all the support that I think it could.
The attached has just come in.
My questions on this are:-
- Has the CC had a copy, and if so which one?  He mentions Somerset, but there is nothing here to say that Diana got a copy.
- The "Session ID" just gives me "Something has gone wrong."
- What he is saying is quite worrying.  Should I investigate?
- Who should reply to him?

E    

![Screenshot](http://freereg2.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1431704624-88023-6582/Capture.JPG)

**Comment by Captainkirkdawson** [comment]
Since it came in as a question it went only to the freereg_manager no where else.
So no Diana did not get a copy.
Normally you take the lead.
In this case I reacted quickly as I also was very concerned. There is a bug but not quite as bad as it might be. See 489 for the issue raised. I replied to researcher with cc to you

**Comment by Captainkirkdawson** [comment]
Dear @name %>;

**Comment by Captainkirkdawson** [comment]
NoMethodError: undefined method `strftime' for nil:NilClass

**Comment by edickens** [comment]
Yes, go that.

Thanks

Eric

**Comment by Captainkirkdawson** [comment]
Believe that the current contact/feedback system is working

**Comment by edickens** [comment]
```
Yes, this is an old one and can be closed.  E

  On 21/06/2016 01:09, Kirk Dawson wrote:


  Believe that the current contact/feedback system is working
  —
    You are receiving this because you commented.
    Reply to this email directly, view
      it on GitHub, or mute
      the thread.
```
