### ISSUE TITLE
Unable to print record(E P Fletcher)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#227]
Issue reported by **E P Fletcher** at 2015-05-18 09:45:43 UTC
Time: 2015-05-18T09:43:29+00:00
Session ID: 
Problem Page URL: []()
Previous Page URL: [http://www13.freereg.org.uk/contacts/new](http://www13.freereg.org.uk/contacts/new)
Reported Issue:
Problem with print preview in Firefox 38.0.1 - see attachment.

Info at bottom of screen is overlaid at the middle - is it you or Firefox ??    

![Screenshot](http://freereg2.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1431942343-88023-4109/freg.jpg)

**Comment by Captainkirkdawson** [comment]
Se 366
