### ISSUE TITLE
Deleted UserIDs are still showing on the overnight update (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#228]
Issue reported by **REGManager** at 2015-05-18 14:07:27 UTC
Time: 2015-05-18T14:05:50+00:00
Session ID: 02081f62350c1b4ab1d4d9c8bf59a141
Problem Page URL: [/userid_details/options](/userid_details/options)
Previous Page URL: [http://freereg2.freereg.org.uk/manage_resources/new](http://freereg2.freereg.org.uk/manage_resources/new)
Reported Issue:
I have deleted two UserIDs in both FR1 and FR2, but they show as a problem in the overnight update report.  See attached.    

![Screenshot](http://freereg2.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1431958047-88023-4700/Capture.JPG)

**Comment by Captainkirkdawson** [comment]
See 234
