### ISSUE TITLE
Search does not find Baptism with maternal surname (Stuart Tokely)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#229]
Issue reported by **Stuart Tokely** at 2015-05-19 05:54:34 UTC
Time: 2015-05-19T05:48:06+00:00
Session ID: 
Problem Page URL: []()
Previous Page URL: [http://www13.freereg.org.uk/contacts/new](http://www13.freereg.org.uk/contacts/new)
Reported Issue:
Using the old search engine, when searching for baptisms for 1810 in Norfolk for the surname Salmon, the baptism of Susanna Manship (born 15/1/1810 and baptised 18/1/1810) whose mother's surname is shown as Manship is found.  However, the new search engine does not find this.

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
User says that it should have read  "mother's surname is Salmon"

**Comment by dougkdev** [comment]
In the old system the search for family members was performed
automatically.  In the new system the user must check the box at the bottom
that says "family members."  With that option checked, Susanna Manship is
found.  We should let the user who reported the issue know of the change so
they can use the family members checkbox in the future.

**Comment by PatReynolds** [comment]
This needs adding to the help page (when written). I wonder if Alison would
be willing to take on documentation for FreeCEN2, too.

Best wishes,

Pat

Pat Reynolds
Executive Director, Free UK Genealogy
