### ISSUE TITLE
Marriage search does not find Witness (Stuart Tokely)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#230]
Issue reported by **Stuart Tokely** at 2015-05-19 06:13:49 UTC
Time: 2015-05-19T06:08:44+00:00
Session ID: 
Problem Page URL: []()
Previous Page URL: [http://www13.freereg.org.uk/contacts/new](http://www13.freereg.org.uk/contacts/new)
Reported Issue:
I like the new search engine in some respects but it certainly has some shortcomings when compared against the old one.  Not only does it not find matches with the mother's surname for baptisms but It does not find marriage witnesses either.  I have already submitted an example of the former and now here is an example of the latter ....
Using the old search engine, a search for a marriage using the surname Sword in Norfolk finds a marriage of John Bishop to Elizabeth Fox in 1890 with a witness Samuel Sword.
The same search using the new search engine does not find it.    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by edickens** [comment]
No, it doesn't seem to work, even with Family members.
Try searching for "parnell"
SOM,Easton in Gordano,St George,81,23 Dec 1832,George,BUCK,,,,,,Prudence,NASH,,,,,,,,,,,,Samuel,COLE,Henretta?,PARNELL,
