### ISSUE TITLE
Place name error (Ian)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#231]
Issue reported by **Ian** at 2015-05-19 19:00:50 UTC
Time: 2015-05-19T18:54:31+00:00
Session ID: 
Problem Page URL: []()
Previous Page URL: [http://www13.freereg.org.uk/contacts](http://www13.freereg.org.uk/contacts)
Reported Issue:
Hi
I thought I'd try FreeReg2 as a search for one of my brickwalls. The search was:
Jonathan Holliday
Kent
No year or place specified. Not finding any ref for a baptism in East Kent, I thought I'd try the parish where he married which was Ash-next- Sandwich (nowadays usually referred to as just "Ash") but this parish does not appear in the drop down list. Instead, the parish of Ash-Ridley appears twice (with the same registers) _ I wonder if somebody inputting the info double entered the data?
Just trying to help
regards
Ian    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Sherlock21** [comment]
This can be closed. I have resolved the fundamental Place names issue. No programming required.
