### ISSUE TITLE
Link from search Results to Place Name details & Genuki fails (ericb)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#232]
Issue reported by **ericb** at 2015-05-21 07:12:23 UTC
Time: 2015-05-21T07:09:05+00:00
Session ID: 2e8b41223e8f9fb2c7eba54c6ee5d1a0
Problem Page URL: [/manage_resources/new](/manage_resources/new)
Previous Page URL: [http://freereg2.freereg.org.uk/refinery/login](http://freereg2.freereg.org.uk/refinery/login)
Reported Issue:
eg: search WRY/ Dewsbury/ Baptisms 1500 - 1800/John Fisher. you get 4 results. OK.
Click on Details, and you get the right info.
Click on the Place name in the details header, to link to Genuki and it fails - with an error msg: sorry something went wrong. 
Its very repeatable.
EB    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Unable to duplicate

**Comment by edickens** [comment]
It is not your link but I think the one in the Refinery page that was brought across from FR1.  Should take out all these links since they are in the FR2 Place Name record?
E

**Comment by Sherlock21** [comment]
I will do you a set of screen prints after dinner. if that helps.?

**Comment by Sherlock21** [comment]
Well, there you go , as it were, just to defeat me!
same search for WRY/ Dewsbury /Ffisher 1500-1850 Baptisms
And today, it worked properly and got right through to the Genuki Map.

I did the same as I did 2 days ago, so what's changed in FR2?

**Comment by Sherlock21** [comment]
i was using the same computer (Mac) same setup, not done any updates in since the last use when it failed to navigate. Used same process of clear all caches at the end at the end of the day's work so next startup is not cluttered up.

**Comment by Captainkirkdawson** [comment]
Same FR2

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1
