### ISSUE TITLE
Enhancement to find the file that a User has uploaded (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#235]
Issue reported by **REGManager** at 2015-05-24 07:36:07 UTC
Time: 2015-05-24T07:33:05+00:00
Session ID: 2f67df591ab920556e9de0f8f7c07809
Problem Page URL: [/freereg1_csv_files/my_own](/freereg1_csv_files/my_own)
Previous Page URL: [http://freereg2.freereg.org.uk/userid_details/54bed559e9379030aa00007f](http://freereg2.freereg.org.uk/userid_details/54bed559e9379030aa00007f)
Reported Issue:
It would be helpful to have the option to select files by a specific UserID, or to have an option when looking at a UserID's details to then see which files they have uploaded.  This is a FR1 option.
E    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Option already exists for the SC

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by edickens** [comment]
```
Agreed.  I don't know why I put this in!
This can be closed.
E
_____________________________________
```

Eric J Dickens
FreeREG Chairman
    On 01/06/2015 15:46, Kirk Dawson wrote:

```
Option already exists for the SC

  Kirk Dawson
  Fairmont Hot Springs, B.C.
  V0B 1L1

  On Sun, May 24, 2015 at 1:36 AM, FreeUKGenIssues
  <notifications@github.com>
  wrote:

  > Issue reported by *REGManager* at 2015-05-24 07:36:07 UTC
  > Time: 2015-05-24T07:33:05+00:00
  > Session ID: 2f67df591ab920556e9de0f8f7c07809
  > Problem Page URL: /freereg1_csv_files/my_own
  > Previous Page URL:
  >
  http://freereg2.freereg.org.uk/userid_details/54bed559e9379030aa00007f
  > Reported Issue:
  > It would be helpful to have the option to select files by a
  specific
  > UserID, or to have an option when looking at a UserID's
  details to then see
  > which files they have uploaded. This is a FR1 option.
  > E
  >
  > [image: Screenshot]
  >
```

https://camo.githubusercontent.com/a204f2529ce3a03337dc1d560f28fbf5b37ad308/687474703a2f2f66726565726567322e667265657265672e6f72672e756b
      >
      > —
      > Reply to this email directly or view it on GitHub
      >
      https://github.com/FreeUKGen/FreeUKGenProductIssues/issues/235.
      >
      —
        Reply to this email directly or view
          it on GitHub.
