### ISSUE TITLE
KBishop has a file, but this does not show in the Syndicate report (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#236]
Issue reported by **REGManager** at 2015-05-24 07:46:08 UTC
Time: 2015-05-24T07:38:27+00:00
Session ID: 2f67df591ab920556e9de0f8f7c07809
Problem Page URL: [/manage_syndicates/selection?_method=get&option=Review+Batches+by+Userid+then+Filename&page=4](/manage_syndicates/selection?_method=get&option=Review+Batches+by+Userid+then+Filename&page=4)
Previous Page URL: [http://freereg2.freereg.org.uk/manage_syndicates/selection?option=Review%20Batches%20by%20Userid%20then%20Filename](http://freereg2.freereg.org.uk/manage_syndicates/selection?option=Review%20Batches%20by%20Userid%20then%20Filename)
Reported Issue:
I am trying to find KBishop's file in their Syndicate which is Surrey & Sussex.  Have selected "Manage Syndicates" and listed by UserID/Filename but KBishop is not there, even though the UserID says they they have uploaded a file.
Attached is the FR1 report which shows the one file which was reported in the Update Error that I report just now.
E    

![Screenshot](http://freereg2.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1432453568-30259-0754/Capture.JPG)

**Comment by Captainkirkdawson** [comment]
Eric. Is this still an issue. Need to know before I spend time on it

**Comment by edickens** [comment]
I doubt it.  The date is 24 May and a lot has happened since then.  I tried the screenshot link in the first comment to see if I could get more detail of the file, but that does not work.  I've checked and the two files for this UserID match in FR1 and FR on name and date.  DONE.  E

**Comment by Captainkirkdawson** [comment]
Too old and Eric is happy to close
