### ISSUE TITLE
Return Place after deletion of a Church (deo123)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#239]
Priority  7 (0	1	1	5)

Issue reported by **deo123** at 2015-06-03 15:17:06 UTC
Time: 2015-06-03T15:12:58+00:00
Session ID: 61ec534b759d4353c98e684fb97d1543
Problem Page URL: [/churches/540a3188eca9ebd28e834fae](/churches/540a3188eca9ebd28e834fae)
Previous Page URL: [http://freereg2.freereg.org.uk/registers/540a3188eca9ebd28e834fb0](http://freereg2.freereg.org.uk/registers/540a3188eca9ebd28e834fb0)
Reported Issue:
Hi,

once a deletion task has been done, see example, it would be nice to go back to where I was last time, not at the beginning of the place names.

Regards Doreen    

![Screenshot](http://freereg2.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1433344626-58501-9108/BKM_Problem_1.JPG)

**Comment by Captainkirkdawson** [comment]
I am afraid I do not understand the request. On the deletion it does not go back to the list of place names. It goes to the church for which you were deleting the register which seems the most logical location. If you want to go back to the place in which this church is located then select Place Information in the breadcrumb list.

**Comment by Captainkirkdawson** [comment]
Coordinator clarified that she had 
"I deleted the Register then the Church, that is when i couldn't go back to the last Place Name I was on, it sends you to the beginning of the Place Name list."

**Comment by Captainkirkdawson** [comment]
Result of using a paged listing. Low priority

**Comment by Captainkirkdawson** [comment]
No longer use paged display.
