### ISSUE TITLE
Report Generator (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#24]
Issue reported by **REGManager** at 2014-09-22 15:18:07 UTC
Time: 2014-09-22T15:15:08+00:00
Session ID: 7fc77c408b46b37eee3d380a3cde616b
Problem Page URL: [/manage_resources/539a6a29eca9eb57f100034a](/manage_resources/539a6a29eca9eb57f100034a)
Previous Page URL: [http://xanthus.freereg2.zomo.co.uk/refinery](http://xanthus.freereg2.zomo.co.uk/refinery)
Reported Issue:
Hi EricB,

Interesting that I have just been thinking about a decadel report for a different reason.  When we met Keith from Family Search he said that he would like us to try to complete counties rather than starting new one.  This is because (something I have found as well) researchers get more benefit and are likely to use those counties where they have more chance of getting results.  I found that 250K records seems to be the trigger point where we start to get thanks from people and also volunteers.  So I would like to see a decadel report showing all parishes, with data or not, and with county totals by decadel.  This is also because I want to be able to see those counties which are doing the post-1837 in preference to the more difficult pre-1837.

But, as you say, all the information is already there.  So is there a report generator in the Mongo database package?  Most package do have this.  If so it should be an option for CC and SC and above.  And we should be able to save the format of the report for future use.  In this way we can build up a library of reports.  This should not involve Ben or Kirk as this should be an operational facility.

Regards,

Eric

**Comment by Captainkirkdawson** [comment]
This is not a problem but an enhancement request.
