### ISSUE TITLE
Different sort for batches with Errors (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#240]
Issue reported by **REGManager** at 2015-06-04 07:30:11 UTC
Time: 2015-06-04T07:24:19+00:00
Session ID: 6e9b1a588e7f98dac104baa95168bd84
Problem Page URL: [/manage_counties/selection?option=Review%20Batches%20with%20Errors](/manage_counties/selection?option=Review%20Batches%20with%20Errors)
Previous Page URL: [http://freereg2.freereg.org.uk/manage_counties/select_action.%3Fcounty=Norfolk](http://freereg2.freereg.org.uk/manage_counties/select_action.%3Fcounty=Norfolk)
Reported Issue:
The attached report is very useful, but it is sorted by number of errors.  Can the columns be sorted by Place or UserID.
I have been looking at the overnight update errors and they all seem to be proper validation errors.  I therefore do not propose to look at them any more, but leave them until CCs work on this report.  It is very useful, far better than FR1 (when every UserID had to be accessed) and this will be the best time for them to correct errors.
E    

![Screenshot](http://freereg2.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1433403011-96744-4126/Capture.JPG)

**Comment by Captainkirkdawson** [comment]
This refers to an off line report that was used in the initial deployment and correction of FR. It is no longer relevant
