### ISSUE TITLE
Contact problem "Something went wrong" (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#241]
Issue reported by **REGManager** at 2015-06-04 12:44:45 UTC
Time: 2015-06-04T12:42:04+00:00
Session ID: 8356837916ae165a8afadfa75d79ea69
Problem Page URL: [/contacts/556f2a5ef493fd36fe000bc4](/contacts/556f2a5ef493fd36fe000bc4)
Previous Page URL: [http://freereg2.freereg.org.uk/contacts](http://freereg2.freereg.org.uk/contacts)
Reported Issue:
In the attached contact report if you select "Search queries for this session" you get "Something went wrong".
E    

![Screenshot](http://freereg2.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1433421885-96744-1811/Capture.JPG)

**Comment by Captainkirkdawson** [comment]
That option should not be there in a contact. Has been removed
