### ISSUE TITLE
Registers with no batches (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#242]
Issue reported by **REGManager** at 2015-06-05 14:59:32 UTC
Time: 2015-06-05T14:55:28+00:00
Session ID: ee0189da3cce21fcf010e311eea487ec
Problem Page URL: [/registers/540909bfeca9eb5fd8137697](/registers/540909bfeca9eb5fd8137697)
Previous Page URL: [http://freereg2.freereg.org.uk/places](http://freereg2.freereg.org.uk/places)
Reported Issue:
If it is not too difficult, can a message be put where the list of batches would be to say "No batches" if there aren't any.  I'm getting a number of questions where CCs think there is a batch because the Register is there.  This will show which ones can be deleted, unless of course some transcriptions will come later.    

![Screenshot](http://freereg2.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1433516372-96863-8064/Capture.JPG)

**Comment by Captainkirkdawson** [comment]
Surely the fact there is no list of batch names should be enough! If there is a batch there will be a button with its name

**Comment by edickens** [comment]
You would have though so, but there is no indication where the list 
would be shown.  In some other screens the batches are listed at the bottom.

**Comment by Captainkirkdawson** [comment]
As far as I am aware they are all at the top (Used to be at the bottom with
registers but I moved to the top to be consistent)

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1
