### ISSUE TITLE
Website Problem (Kirk Dawson)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#243]
Issue reported by **Kirk Dawson** at 2015-06-06 19:19:18 UTC
Time: 2015-06-06T19:18:41+00:00
Session ID: 
Problem Page URL: []()
Previous Page URL: [http://test3.freereg.org.uk/contacts/new](http://test3.freereg.org.uk/contacts/new)
Reported Issue:
Testing Website problem.    

![Screenshot](http://test3.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Was a test
