### ISSUE TITLE
No acces to the Detail Link (Dale Braden)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#244]
Issue reported by **Dale Braden** at 2015-06-07 19:33:05 UTC
Time: 2015-06-07T19:25:31+00:00
Session ID: 
Problem Page URL: []()
Previous Page URL: [http://www13.freereg.org.uk/contacts/new](http://www13.freereg.org.uk/contacts/new)
Reported Issue:
When displaying the results of a search, the table of results is often truncated at the right, such that the "Detail" column is missing. This happens with Firefox v38 on either Linux or Windows and happened with earlier versions as well.  Enlarging the browser window or zooming out does not correct this, so the problem seems to be in the way the website itself handles the display of search results.  It may have to do with the amount of text in the "Location" column.  If the Location is lengthy, then the Detail column is lost.  For example, search for burials with the surname Braden in Staffordshire for the years 1850-1900.  The Detail column will be missing. But if you limit the range of years to 1850-1880 so as to remove the records with long Locations, then the Detail column becomes visible.  I hope this can be fixed sooner rather than later, because not being able to look at the details limits one's ability to determine whether a given search result is valid or not.    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Resolved
