### ISSUE TITLE
Transcriber credit (Dale Braden)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#245]
Issue reported by **Dale Braden** at 2015-06-07 19:51:32 UTC
Time: 2015-06-07T19:33:11+00:00
Session ID: 
Problem Page URL: []()
Previous Page URL: [http://www13.freereg.org.uk/contacts/new](http://www13.freereg.org.uk/contacts/new)
Reported Issue:
The FreeREG2 website does not correctly list the transcribers of a given set of registers, but FreeREG1 did.  For example, click "Database Contents" from the main menu and search Staffordshire -> Tipton -> Alexandra Rd Cemetery (the second item in the list of "churches" that comes up) -> Unspecified.  This should bring you to the following page:

http://freereg2.freereg.org.uk/freereg_contents/5409d437eca9eb718220b222/show_register

This shows Derek Gardner as the only transcriber, but in fact the transcribers were Derek and myself.  The website may be assuming that all transcription files associated with a given location were created by the same transcriber, but this is not true.  

The same problem shows up with other churches as well, such as that of St Martin in Tipton in Staffordshire, which credits only one person with transcribing the baptisms, whereas FreeREG1 lists 5 transcribers for the baptisms.    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
This is not a system issue but an input issue
