### ISSUE TITLE
Notes about the Church (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#247]
Issue reported by **REGManager** at 2015-06-08 16:13:18 UTC
Time: 2015-06-08T16:12:11+00:00
Session ID: 5e0c19aa9b30a47e4cba98f6c757253d
Problem Page URL: [/churches/5408f3d8eca9eb0d220a2707](/churches/5408f3d8eca9eb0d220a2707)
Previous Page URL: [http://freereg2.freereg.org.uk/churches/5408f3d8eca9eb0d220a2707/edit](http://freereg2.freereg.org.uk/churches/5408f3d8eca9eb0d220a2707/edit)
Reported Issue:
The Edit Church Fields does not let you edit the Notes Field.
E    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Good catch. Corrected
