### ISSUE TITLE
creating a new place name does not allow Genuki link to be added. (ericb)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#249]
Issue reported by **ericb** at 2015-06-10 13:31:21 UTC
Time: 2015-06-10T13:27:27+00:00
Session ID: d61e1384f368f7f480a32b7f0e63b1ce
Problem Page URL: [/places/55783a75f493fdaba70000a4](/places/55783a75f493fdaba70000a4)
Previous Page URL: [http://freereg2.freereg.org.uk/places/55783a75f493fdaba70000a4](http://freereg2.freereg.org.uk/places/55783a75f493fdaba70000a4)
Reported Issue:
I created a new place name: WRY/ New Otterington.

fine. worked very slowly, but got there.
Then accessed the new place name to add the Genuki link ( as I did not have it at the start of the task).
When the Place details page was accessed, the Genuki link field already has a green box: Location showing. (Why? )
So I did not not proceed further. - guess: need to do an edit on thin page?    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Edit the place and add the website link

You are working on a system that is doing thousands of searches so you can expect it to be slow from time to time
