### ISSUE TITLE
Improve radius-search Results page

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#25]
Issue reported by **EricD** at 2014-09-23 08:53:01 UTC
Time: 2014-09-23T08:50:09+00:00
Session ID: 4b408a17cd84ecb5fbcd09d3469687ed
Problem Page URL: [/search_queries/5421342ceca9eb6b47000001/about?page_number=0](/search_queries/5421342ceca9eb6b47000001/about?page_number=0)
Previous Page URL: [http://xanthus.freereg2.zomo.co.uk/search_queries/5421342ceca9eb6b47000001](http://xanthus.freereg2.zomo.co.uk/search_queries/5421342ceca9eb6b47000001)
Reported Issue:
When I did this search, the "About this search" raised a few questions because I was thinking what I would do next.
- The places listed are nearby, but some are in a different county.  So if I wanted to search I would need to know which.
- I'm not sure I need the distance to this level of accuracy.  One decimal place will do.
- Kilometres is spelt with "res" on the end, at least over here.
- You say "Records within these places" but are these places where we have transcriptions or just that they are in the MPN.  Perhaps we should say "We have records within these places"?

Thanks,

Eric

**Comment by graphiclunarkid** [comment]
Standardising on en_GB spelling is #302. I have raised #320, #321 and #322 to cover the other points. Closing this issue in favour of those referenced.
