### ISSUE TITLE
Changing Unapproved Place to Approved (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#250]
Issue reported by **REGManager** at 2015-06-12 08:21:02 UTC
Time: 2015-06-12T08:13:15+00:00
Session ID: bac5c7273d445d6c701d5777e8a36239
Problem Page URL: [/places/554c15fbf493fd1e41014e7e](/places/554c15fbf493fd1e41014e7e)
Previous Page URL: [http://freereg2.freereg.org.uk/manage_counties/selection?option=Places%20with%20Unapproved%20Names](http://freereg2.freereg.org.uk/manage_counties/selection?option=Places%20with%20Unapproved%20Names)
Reported Issue:
There are instances where the Unapproved place should be the Approved place, but there is no means to "Unset" the Unapproved marker.
Is it just necessary to enter some key facts for the Unapproved marker to change?
At present it is necessary to move everything out of the Unapproved, delete the Unapproved, create a new Place just the same as the Unapproved but it will be Approved now, then move all the batches to the new Place and then destroy the original.  We just need to remove the Unapproved marker.
E    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
All that "creates" the Unapproved Flag is the absence of a valid location. To make this approved simply put in the correct location in place of the Tower of London one used for Unapproved places. and then Remove the flag; I will have to code this function.

**Comment by edickens** [comment]
Yes.  Please may the Data Manager only have a "Remove Unapproved Flag" 
function.  Quite important.
E

**Comment by Sherlock21** [comment]
I like this. A lot. There will be loads of these to do. so worth the time to set it up.
I have an example ready to test out right now.
Please advise as soon as its ready.

**Comment by Sherlock21** [comment]
Will it make any difference whether the Not Approved Place has one or more batches in one or more churches already associated with it?

**Comment by Captainkirkdawson** [comment]
No

But only proviso is to make sure that the location has been changed first
to the location you want OR it will be approved in the Tower!!!!!.

So it will be 2 steps. Edit the place to change its location. Remove flag.
Doing it that way to make sure that there is a valid location before going
ahead.

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by edickens** [comment]
```
EricB, Remember that you may have to enter grid references and such
to the Place when you make it Approved because it will have been set
up by information from a transcription and not when the MPN was set
up.
E
```

**Comment by Sherlock21** [comment]
Yes indeed.
[ I have to admit I had to do one or two again in the past on account of having the wrong County]
 I do appreciate Set it  up Once, then Read it all Again. Then Commit.

**Comment by Captainkirkdawson** [comment]
The remove flag capability now appears on the edit place information if you
are DM or SA AND the flag is set.

It is deployed for you to test on the test server test3. Please test that
capability. Take your time.

Let me know if it is OK and it will be deployed tonight to the production
servers

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Sherlock21** [comment]
Thanks,K.

I will have a look at it over the next hour or so and let you know asap that i am happy.

EB

**Comment by Sherlock21** [comment]
I need the url please - I did not save the previous one for Test2

e

**Comment by Captainkirkdawson** [comment]
http://test3.freereg.org.uk/refinery/login

**Comment by Sherlock21** [comment]
K

I have done  5, some with data batches attached & 1 without. All go OK.

I did notice that the Last Updated date does change from Red as i expected, but the actual date does not change to Today.

Might that metter in the future?

Else go with it. And thank you.

EricB

**Comment by Captainkirkdawson** [comment]
That's because the last amended date in the main place table is the last date that a record in the place was changed.
In the information on the Place you will see an additional date that shows when the information about the place itself was last changed

I will deploy this evening during quiet time on the servers
