### ISSUE TITLE
Website Problem (A Hedges)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#251]
Issue reported by **A Hedges** at 2015-06-13 07:54:09 UTC
Time: 2015-06-13T07:36:50+00:00
Session ID: 
Problem Page URL: []()
Previous Page URL: [http://www13.freereg.org.uk/contacts/new](http://www13.freereg.org.uk/contacts/new)
Reported Issue:
I write to advise you that there certain places/parishes in Suffolk cause confusion as they appear more than once within the county.
They are as follows:
Denham (near Bury St Edmunds) - St Mary
Denham (near Eye) - St John
Rushmere (near Lowestoft) -St Michael
Rushmere (near Ipswich) - St Andrew
Holton - St Peter
Holton St Mary
Hopton (near Ixworth) - All Saints
Hopton (near Lowestoft) - St Margaret

If you agree, would it not be possible for the Suffolk parish index be amended to include the additional information?    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by edickens** [comment]
```
A good idea.

The relevant transcriptions will need amending.

Eric

PS.  I can't reply to the author direct as there is no email
address.
_____________________________________
```

Eric J Dickens
FreeREG Chairman
    On 13/06/2015 08:54, FreeUKGenIssues
      wrote:

```
  Issue reported by A Hedges at 2015-06-13
    07:54:09 UTC
    Time: 2015-06-13T07:36:50+00:00
    Session ID: 
    Problem Page URL: 
    Previous Page URL: http://www13.freereg.org.uk/contacts/new
    Reported Issue:
    I write to advise you that there certain places/parishes in
    Suffolk cause confusion as they appear more than once within the
    county.
    They are as follows:
    Denham (near Bury St Edmunds) - St Mary
    Denham (near Eye) - St John
    Rushmere (near Lowestoft) -St Michael
    Rushmere (near Ipswich) - St Andrew
    Holton - St Peter
    Holton St Mary
    Hopton (near Ixworth) - All Saints
    Hopton (near Lowestoft) - St Margaret
  If you agree, would it not be possible for the Suffolk parish
    index be amended to include the additional information? 

  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by Sherlock21** [comment]
For Place names that occur more than once within a County, we already add a qualifier Place name. eg Denham (Eye). So all we don;t do is use the word "near" to reduce the line length on our results tables - already an issue on some reading devices. the Holton ones above are incorrect examples. these will resolve by not including Non Approved Place names in the results to searches.
