### ISSUE TITLE
Contact report is showing wrong information (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#254]
Issue reported by **REGManager** at 2015-06-14 08:18:43 UTC
Time: 2015-06-14T08:12:32+00:00
Session ID: 6c4d869ed6b8b560b4ead896b130e201
Problem Page URL: [/freereg1_csv_entries/5463b981e937902782387ff6](/freereg1_csv_entries/5463b981e937902782387ff6)
Previous Page URL: [http://freereg2.freereg.org.uk/contacts/557d18c233045bd54b0004d1](http://freereg2.freereg.org.uk/contacts/557d18c233045bd54b0004d1)
Reported Issue:
After Show a Contact, then select the Record in Question, and if this is MA, Grooms forename is showing the Surname.    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
This is a transcription error not a system error.

**Comment by edickens** [comment]
```
No.  Because if you do a search on this record you get shown a
different result.  I'll send an email with screen-shots.
E
_____________________________________
```

Eric J Dickens
FreeREG Chairman
    On 15/06/2015 00:02, Kirk Dawson wrote:

```
  This is a transcription error not a system error.
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by Captainkirkdawson** [comment]
You are correct it is a display problem. Fix has been applied
