### ISSUE TITLE
County information missing(ericb)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#255]
Issue reported by **ericb** at 2015-06-14 12:13:15 UTC
Time: 2015-06-14T12:09:49+00:00
Session ID: 32a9a88cc60e85b14a8b93c5682d9629
Problem Page URL: [/search_queries/557d6eeff493fdb8440000eb](/search_queries/557d6eeff493fdb8440000eb)
Previous Page URL: [http://freereg2.freereg.org.uk/](http://freereg2.freereg.org.uk/)
Reported Issue:
Hi,

I think there is a problem with the Place field losing the display information.

Regards Doreen    

![Screenshot](http://freereg2.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1434283995-95992-3405/Lan_search_for_Alice_Walker_1832_Mar.JPG)

**Comment by Captainkirkdawson** [comment]
This is too vague to be followed up

**Comment by Captainkirkdawson** [comment]
The search results is missing the county on some entries

**Comment by Captainkirkdawson** [comment]
Issue appears to be associated with records that are tagged to an unapproved place name.

**Comment by Sherlock21** [comment]
Ahhh.

OK Srap this one then.
