### ISSUE TITLE
Editing Gridref does not now change the Lat/Lon (ericb)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#259]
Issue reported by **ericb** at 2015-06-20 14:32:13 UTC
Time: 2015-06-20T14:29:23+00:00
Session ID: 2d5ceb3af105cefcf1712b8bbfc3cfe7
Problem Page URL: [/places/55856e24f493fd437d000737](/places/55856e24f493fd437d000737)
Previous Page URL: [http://freereg2.freereg.org.uk/places?page=2](http://freereg2.freereg.org.uk/places?page=2)
Reported Issue:
When I edit the Gridref of a place, although the new gridref is not rejected, the update is rejected. But the change to OS REG is retained although not reflected through to change the Lat /lon as it used to do.    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
It works as it always has done. 
If the lat/lon are present it will always use those in preference to the Reference as those are taken to be more accurate. 
Hence if you do not change the lat/lon and they are present in the form then no recalculation is done.
If you want to force a recalulation from the Reference then you will have to blank out the lat/lon and insert a new Reference

**Comment by Sherlock21** [comment]
Yes,I blanked out the existing Lat/ Lon and put in the new GridREf, and it got rejected ( see CGN/Borth) if you need to see the history.
I was only doing is as I had put in the wrong GridRef when making the new place.!
I will have another try and come back to you

**Comment by Captainkirkdawson** [comment]
Please do, this code is unchanged in a year

**Comment by Sherlock21** [comment]
Yes,I am correct.
In Test3 system For Anglesey/ Aberffraw.
i blanked out the Lat 53/190746 & Lon -4.465145
and changed the gridREf from: SH354688  to SH360650  . But it rejected my change.

I did it again, attempting to leave the old GridRef as it had been, but just BlankLat/Lon but again rejected.

**Comment by Sherlock21** [comment]
K

In Github,I have corrected the first edition I wrote of this WhatI did - I got mixed up.
Its correct in Github now.
So if you are just going off the first edition which it sends you as an email, that version is wrong.

E

**Comment by Captainkirkdawson** [comment]
Thank you much clearer now.

**Comment by Captainkirkdawson** [comment]
Have committed a change that permits either lat/lon or Grid to be changed. If both are changed it will prefer the lat/lon. You no longer have to clear the lat/lon to force a recal from a new grid

**Comment by Sherlock21** [comment]
Thank you, Kirk. I will have a test in T3 later.
