### ISSUE TITLE
Approved place selection list in Relocate Batch (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#260]
Issue reported by **REGManager** at 2015-06-21 16:49:00 UTC
Time: 2015-06-21T16:24:25+00:00
Session ID: f594329220fdb341362560ef334ebc1f
Problem Page URL: [/freereg1_csv_files/54638f9fe9379010fc4d4bb1/relocate](/freereg1_csv_files/54638f9fe9379010fc4d4bb1/relocate)
Previous Page URL: [http://freereg2.freereg.org.uk/freereg1_csv_files/54638f9fe9379010fc4d4bb1](http://freereg2.freereg.org.uk/freereg1_csv_files/54638f9fe9379010fc4d4bb1)
Reported Issue:
Can the list show the present place as the default starting point in the Approved Places destination list.  This is because this routine may be used a lot of correcting Churches and Register Types when the Place will remain the same.
E    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
If the batch that is being relocated is already an approved place then it does do that already. i.e. it assumes you are not going to move from one approved place to another (But you can if you want to)

If you are relocating an unapproved place it does not have a valid staring point so you must select
