### ISSUE TITLE
County & Record Type inconsistency (Kyran)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#264]
Issue reported by **Kyran** at 2015-06-23 01:33:53 UTC
Time: 2015-06-23T01:22:40+00:00
Session ID: 3108cd0521e50d4d49cd1de76799b6b7
Problem Page URL: [/search_queries/new](/search_queries/new)
Previous Page URL: [http://freereg2.freereg.org.uk/manage_resources/new](http://freereg2.freereg.org.uk/manage_resources/new)
Reported Issue:
The County field has an already enabled list of names from which to choose.  Once a surname is filled in, the list is ready for choosing.  
The Record type field, with only 3 choices, must first be enabled by the searcher clicking in the field space.
If the County can be enabled automatically, cannot the Record type as well?    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Different field types
