### ISSUE TITLE
Participant Cloumn (Results Page) (Kyran)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#265]
Issue reported by **Kyran** at 2015-06-23 01:46:08 UTC
Time: 2015-06-23T01:37:24+00:00
Session ID: 3108cd0521e50d4d49cd1de76799b6b7
Problem Page URL: [/search_queries/5588b84df493fd76f9000020](/search_queries/5588b84df493fd76f9000020)
Previous Page URL: [http://freereg2.freereg.org.uk/search_queries/new?search_id=5588b825f493fd76f900001a](http://freereg2.freereg.org.uk/search_queries/new?search_id=5588b825f493fd76f900001a)
Reported Issue:
Takes the first name from one field and the surname from another field and puts them together as a full name, in one column, and usually on one line.
Having first and last names on different rows is somewhat confusing.  One has to check the row Title for each word to be sure one has the correct names together.
Seems like all the pieces and parts of a database should result in more flow, rather than present itself as individual pieces and parts.
Also I though that such an arrangement could not be accomplished for the other names in the database, such as father's name, mother's name, witness' name etc..    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Do not understand or accept
