### ISSUE TITLE
Expand the tool which moved a batch from one place to another, to include changing County

### ISSUE THREAD

**Issue by Sherlock21** [FreeUKGen/FreeUKRegProductIssues#268]
With the removal of the tools for relocating whole Place Names' worth of batches from one County to another County, there is a need for expanding the present Batch by Batch relocation tool, to allow batch relocation to any other County - ie not restricted to Same County.

**Comment by edickens** [comment]
Hi EricB,
I wouldn't want Kirk to spend too much time on this because the files 
can be changed in FR1.  When we get to validation it will not be 
possible to upload a place into the wrong county.  How many times will 
this be used?
E

**Comment by Sherlock21** [comment]
I have just spent 2 hours doing half of the process of moving 4 files from LAN to WRY.Rest of job will take a CC at least an hour to do. So given the numbers of files/ places that you found  had been uploaded to  apparently the wrong County in Scotland, it seems a useful tool - else CC's will have to do the lot themselves in future. 
It had been indicated to me that this change would be relatively simple to implement.
And given that there seems a move to do all file uploading in FR2 in the very near future, doing this in F1 will be a thing of the past 'er long.
