### ISSUE TITLE
Doing Change Name of batch for Watton (Phillimore TX) in HRT. /something went wrong Error msg. (ericb)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#269]
Issue reported by **ericb** at 2015-06-24 18:48:39 UTC
Time: 2015-06-24T18:43:24+00:00
Session ID: 1753894f608cebd8462726b9f791a248
Problem Page URL: [/places/53cedf92eca9eb5f6d498133/rename](/places/53cedf92eca9eb5f6d498133/rename)
Previous Page URL: [http://freereg2.freereg.org.uk/places/53cedf92eca9eb5f6d498133](http://freereg2.freereg.org.uk/places/53cedf92eca9eb5f6d498133)
Reported Issue:
This WATTON batch only contained 709 records so well below the 2000 limit.
Used rename batch and picked the right name from drop down list (Watton at Stone).

Hit go and after a shortish while, during which all seemed fine, i then got error msg: Something went wrong.
Created this Problem Report.
Noi will have a search around and see what if anything did change or not and add another part.    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Sherlock21** [comment]
All the batch of 709 records appears to have changed the Place name correctly.
But i have one Place name that's Approver ( which was there originally, for a different church) and the other is NotApproved - which is the one with the Batch that i thought i was moving into the Approved place name. appears not so and just created another name for the Not approved set.
Is this what was supposed to happen? If so Action button labels are misleading.
The impression was : the batch in not approved, with the wrong place name, would be moved into the right, Approved Place.

**Comment by Captainkirkdawson** [comment]
The logs clearly show that you were using the Place Relocation Function.
Not the Batch Relocation Function.I specifically said that the ONLY
relocation function that had been tested and approved for use was the Batch
Relocation. You were involved in its testing earlier this week. When asked
I said that the Place/Church and Register relocation code had yet to be
refactored and that it was extremely unlikely to ever release the Place
relocation code. I am not at all surprised at the failure  the code has not
been tested.

Started PUT "/places/53cedf92eca9eb5f6d498133" for 5.9.125.163 at
2015-06-24 19:43:40 +0100
Processing by PlacesController#update as HTML
  Parameters: {"utf8"=>"✓",
"authenticity_token"=>"4S8/G6itlYy8E4wVlxMhLL7Ob0RI2CLbKgdr7jxUUrE=",
"place"=>{"place_name"=>"Watton at Stone"}, "commit"=>"Rename",
"id"=>"53cedf92eca9eb5f6d498133"}
Completed 500 Internal Server Error in 25.8ms
*\* [Airbrake] Unable to contact the Airbrake server. HTTP
Error=Net::ReadTimeout
*\* [Airbrake] Failure: NilClass

ArgumentError (wrong number of arguments (1 for 2)):
  app/models/place.rb:228:in `block in propogate_place_name_change'
  app/models/place.rb:226:in`propogate_place_name_change'
  app/models/place.rb:217:in `change_name'
  app/controllers/places_controller.rb:130:in`update'

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Captainkirkdawson** [comment]
While the Place Name may have been changed; the search records in the database will not reflect this change. The solution is a reload of the original file.

**Comment by Captainkirkdawson** [comment]
As a final note the best approach is that you relocate the churches to the correct place then delete the unapproved

**Comment by Sherlock21** [comment]
Sorry - mis -read the title - I will re-load the thing one way or another.

Thanks.

EB

**Comment by Sherlock21** [comment]
K 
this is what i thoughtI was doing in the first place!

Thanks for advice.
