### ISSUE TITLE
Place name not showing (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#270]
Issue reported by **REGManager** at 2015-06-25 10:59:47 UTC
Time: 2015-06-25T10:57:12+00:00
Session ID: 3031266428275b7db3c50b43741e5267
Problem Page URL: [/places/53ce941aeca9eb1a905c0726](/places/53ce941aeca9eb1a905c0726)
Previous Page URL: [http://freereg2.freereg.org.uk/places?page=7](http://freereg2.freereg.org.uk/places?page=7)
Reported Issue:
Very minor.  But if you select a place from the All Places, you get a screen which does not show the place name anywhere.  So if you have been working on a number of things, or go for a break, it is not easy to know where you are.  Even the breadcrumb does not show the name.  See attached.    

![Screenshot](http://freereg2.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1435229987-42701-3715/Capture.JPG)

**Comment by edickens** [comment]
Forget this.  Doing too many things.
E
