### ISSUE TITLE
Status of a new volunteer (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#271]
Issue reported by **REGManager** at 2015-06-26 10:31:31 UTC
Time: 2015-06-26T10:26:03+00:00
Session ID: 7a4c6e54da8f667ff13a1d89c0c6124e
Problem Page URL: [/userid_details/558d19db791e3b35090005c9](/userid_details/558d19db791e3b35090005c9)
Previous Page URL: [http://freereg2.freereg.org.uk/userid_details/selection?option=Select%20specific%20userid](http://freereg2.freereg.org.uk/userid_details/selection?option=Select%20specific%20userid)
Reported Issue:
The UserID tello2015 has just registered but sent in a report stating that she thought that she had "messed up".  I have looked at her UserID and it looks fine.  But what it does not tell me is whether she has set up a password and so completed the registration.  I know that I could wait 24 hours to see if the registration gets cancelled, but it would be helpful to know if the registration was fully set up.
Hopefully I will hear why she thinks she has "messed up" because something must have not been clear to her.
E    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by edickens** [comment]
I have heard back from the volunteer.
She was concerned because after entering her password she was bounced back to the home page.  This is because Transcribers are blocked from logging in.
Should we do something different for those trying to register in FR2 because they are going to have to register again in FR1?

**Comment by Captainkirkdawson** [comment]
There is an issue. It appears that the registration is taking place on the slaves when it should only be on the master.

**Comment by Captainkirkdawson** [comment]
I have temporarily removed the registration link until such a time that a) we can ensure that the process runs on the master and b) we are ready for transcribers to work on FR2.

**Comment by Captainkirkdawson** [comment]
Registration page is now back as we have resolved (apparently) the cause of our difficulty.
