### ISSUE TITLE
Improve the Relocate screen (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#272]
Issue reported by **REGManager** at 2015-06-28 07:15:33 UTC
Time: 2015-06-28T07:04:07+00:00
Session ID: b99d6ae9941827f2d0df62616a51e4cc
Problem Page URL: [/freereg1_csv_files/5463b1b5e937904abb05b73a/relocate](/freereg1_csv_files/5463b1b5e937904abb05b73a/relocate)
Previous Page URL: [http://freereg2.freereg.org.uk/freereg1_csv_files/5463b1b5e937904abb05b73a](http://freereg2.freereg.org.uk/freereg1_csv_files/5463b1b5e937904abb05b73a)
Reported Issue:
A minor point, but it might improve the accuracy.
When relocating a batch, it should go to a valid Place/Church/Register Type.  The Place and Register Type have pick lists, but not the Church.  See attached.  I can see this creating extra Churches in a Place if for example the other entry is "The Parish Church" and the one being relocated is just "Parish Church".
So is it worthwhile getting the Place selected first and then bringing up a pick list of Churches in that place?  The Church of the existing Batch should be included in the pick list in case a new church needs to be made or the Place does not have any Churches.
In the attached example I had to enter the Church as it did not exist.
The other possibility is to make it necessary to create the Church in the destination before the relocate takes place.  The pick list must then be for valid Churches in the destination Place.
E    

![Screenshot](http://freereg2.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1435475733-3994-0088/Capture.JPG)

**Comment by Sherlock21** [comment]
I support the idea of making the application help us to NOT get a proliferation of inaccurate church names from the process here.
