### ISSUE TITLE
BUTTON: FILL COUNTY & COUNTRY navigates to Relocate Place instead. (ericb)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#273]
Issue reported by **ericb** at 2015-06-28 13:43:19 UTC
Time: 2015-06-28T13:35:57+00:00
Session ID: 4b6a8e12369dabcedd714e908b133e3b
Problem Page URL: [/places?page=25](/places?page=25)
Previous Page URL: [http://freereg2.freereg.org.uk/places?page=24](http://freereg2.freereg.org.uk/places?page=24)
Reported Issue:
Having just Approved a Not Approved Place ( STS/ Yoxall) and put in the Genuki link for location, i went to fill in the County & Country fields - by using the button so labelled.
It navigated to Relocate Place instead.    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Yes it is a very similar page that enable you to fill in the county and the country that are missing from the Unapproved place
