### ISSUE TITLE
SOM has an entry of a Blank Name (ericb)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#274]
Issue reported by **ericb** at 2015-06-28 16:04:48 UTC
Time: 2015-06-28T16:02:00+00:00
Session ID: 4b6a8e12369dabcedd714e908b133e3b
Problem Page URL: [/manage_counties/selection?option=Places%20with%20Unapproved%20Names](/manage_counties/selection?option=Places%20with%20Unapproved%20Names)
Previous Page URL: [http://freereg2.freereg.org.uk/manage_counties/select_action](http://freereg2.freereg.org.uk/manage_counties/select_action)
Reported Issue:
Is this an issue?

If you start at the Actions for SOM > Places with NoT Approved Warning.

> pick Blank 
> there is a Register and church listed. but no data. and no place name.

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by edickens** [comment]
Then just delete it.  Has probably been fixed in FR1 and the batch moved.
You can get a few of these because if someone makes a mistake in FR1 it 
can create a Place/Church/Register then when the batch gets moved this 
gets left behind.
E

**Comment by Sherlock21** [comment]
But the point is: I has no place name so I can't get started!

EricB

**Comment by edickens** [comment]
```
Try All Places under B...



E
```

**Comment by Captainkirkdawson** [comment]
Did it for you. Delete the register; delete the church then delete the place.
