### ISSUE TITLE
The link to view My Batches does not go anywhere. (ericb)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#275]
Issue reported by **ericb** at 2015-06-29 14:45:09 UTC
Time: 2015-06-29T14:43:09+00:00
Session ID: 8c66d6db56bb91fe37e33ee3cb175aa4
Problem Page URL: [/manage_resources/new?](/manage_resources/new?)
Previous Page URL: [http://freereg2.freereg.org.uk/manage_resources/new](http://freereg2.freereg.org.uk/manage_resources/new)
Reported Issue:
Is it temporary veto'd? or is it supposed to function as it has done before?

If its temp vetoed Would it not be better to actually take the button off please. Its most confusing.    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Wonder who is more paranoid you or me!!
Not sure what gives at this instant

**Comment by Captainkirkdawson** [comment]
My bad!!! sorry about that. Fixed

**Comment by Sherlock21** [comment]
Don't get the impression that I am always complaining....

But with so many things for us to do, i guess if you are half as bad as I am, some will get left behind, only part done.

Then we start asking..is it me??

Have a good day.
EB
