### ISSUE TITLE
CC Functions (edickens)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#276]
Issue reported by **edickens** at 2015-06-30 08:44:19 UTC
Time: 2015-06-30T08:40:41+00:00
Session ID: 3111ea8b0ae5b8c8f130d1bad3ff7209
Problem Page URL: [/manage_resources/new](/manage_resources/new)
Previous Page URL: [http://test3.freereg.org.uk/manage_resources/new](http://test3.freereg.org.uk/manage_resources/new)
Reported Issue:
I am getting some proper images for a CC only and have set myself up as CC for CAM.  But as a CC only, I get Syndicate functions, see attached, although if I request them my request is refused.
Manage Syndicates should not be there if the person is not a SC.
E    

![Screenshot](http://test3.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1435653859-32086-1156/Capture.JPG)

**Comment by Captainkirkdawson** [comment]
Since they have no syndicate they cannot do anything. I view this as an extremely low priority request

**Comment by edickens** [comment]
Yes, not important.

**Comment by Captainkirkdawson** [comment]
@edickens  Propose to close as not really required
