### ISSUE TITLE
Merge Batches (edickens)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#277]
Issue reported by **edickens** at 2015-06-30 09:56:04 UTC
Time: 2015-06-30T09:53:08+00:00
Session ID: bdd18df7dd7800e65b0d45d6b9a96777
Problem Page URL: [/freereg1_csv_files/5463d138e937902782a8d7e5](/freereg1_csv_files/5463d138e937902782a8d7e5)
Previous Page URL: [http://test3.freereg.org.uk/freereg1_csv_files/5463d138e937902782a8d7e5](http://test3.freereg.org.uk/freereg1_csv_files/5463d138e937902782a8d7e5)
Reported Issue:
Not sure of this.  It happened so fast.  I don't think that there is an "Are you  sure?".  I think that there should be as this function cannot be undone.  It could be easy to hit  the button by mistake.
E    

![Screenshot](http://test3.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
here is a challenge for confirmation
