### ISSUE TITLE
Amending comments in FR1 file headers (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#278]
Issue reported by **REGManager** at 2015-07-02 06:33:27 UTC
Time: 2015-07-02T06:29:31+00:00
Session ID: 96979c0bccb8f5bd0ec3a410e8ad1e09
Problem Page URL: [/places?page=22](/places?page=22)
Previous Page URL: [http://freereg2.freereg.org.uk/places?page=25](http://freereg2.freereg.org.uk/places?page=25)
Reported Issue:
We have had the situation where a comment has been put against a place name, which should have been in the file header.  This is being corrected.
But as the Batch will already have been created, and the Place/Church already created, when the comment in line 4 of the FR1 header is amended, will this get carried across to FR2?
E    

![Screenshot](http://freereg2.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1435818807-14879-1254/Capture.JPG)

**Comment by Captainkirkdawson** [comment]
Yes
