### ISSUE TITLE
Fleur-de-lis (Howdy)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#279]
Issue reported by **Howdy** at 2015-07-02 18:46:33 UTC
Time: 2015-07-02T18:44:17+00:00
Session ID: bc0884363583a93712e51a745fa5671b
Problem Page URL: [/places/53cbf5f6eca9eb03a6006a25](/places/53cbf5f6eca9eb03a6006a25)
Previous Page URL: [http://freereg2.freereg.org.uk/places?page=5](http://freereg2.freereg.org.uk/places?page=5)
Reported Issue:
Why are the files not showing under one church?  Currently each file for this location has a separate church.    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Sherlock21** [comment]
Howdy: which County please?

EricB

**Comment by Sherlock21** [comment]
I took a guess, and it was the second choice>MON.
I see what you mean and the answer is that i don't know right now. I will check further.
One church name is spelled: Parish Chruch whilst the rest are Parish Church.
I looked in detail at the content of MONFLEBA50.csv. and i don't see anything here except now, the file is no longer visible in this place.
Needs Kirk to investigate both issue please.

**Comment by edickens** [comment]
You need to get back to me not Kirk.  I am checking the overnight update 
report.

If the Place in the file does not match a Place in the MPN, exactly and 
Approved, then all entries in that file which are wrong are rejected.  
If this is the whole file, then it will not appear in FR2.  Kirk and I 
have a list of these files and we will get in contact with everyone 
involved in due course.

However, if the person realises their mistake, and corrects the file, it 
will get reinstated in FR2. So the first step must be to check if what 
has gone missing has an invalid Place name, correct it and try again.

We have been asking for two years or more for place names to be correct.

There were two such files last night;

GailO   NFKSAHBA.CSVThe Place SahamToney
oldskoolraver   DEVSEABU3.CSVThe Place Seaton & Beer

E

**Comment by edickens** [comment]
We have found a few places like this.  We think it was a problem during 
initial set up.  I have sorted it out.  But do correct that file with 
"Chruch".
Please let me know if you find any more.
E

**Comment by edickens** [comment]
This may have been a set up problem that needs fixing using existing functions.  No programming is needed.

**Comment by Sherlock21** [comment]
1)Seaton&Beer is not an Approved Placename. the location of the church concerned is I think in Seaton. And that is Approved.i have asked the CC to correct the file in F1.
2) The Place SahamToney  is news to me. Julie Harold & i have recently corrected all the NFK/ SFK & ESS Place name errors and did not come across that.
I can do no more on these 2 snags - which don't have anything to do with Church Names mis-spellings.
