### ISSUE TITLE
Unlock batch by SC (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#28]
Issue reported by **REGManager** at 2014-09-25 21:59:08 UTC
Time: 2014-09-25T21:57:30+00:00
Session ID: f074b97b2fb59e6d9a6320c7506b2135
Problem Page URL: [/freereg1_csv_files/53e7bb19eca9ebaca0000001/by_userid](/freereg1_csv_files/53e7bb19eca9ebaca0000001/by_userid)
Previous Page URL: [http://xanthus.freereg2.zomo.co.uk/userid_details/all?page=38](http://xanthus.freereg2.zomo.co.uk/userid_details/all?page=38)
Reported Issue:
Unlock does not work although the report says that the update of the batch has been successful.

See email from EricD 25/09/14 at 23:00

**Comment by Captainkirkdawson** [comment]
Resolved as part of FR2.1.0
