### ISSUE TITLE
UserIDs overnight update validation (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#281]
Issue reported by **REGManager** at 2015-07-05 05:46:54 UTC
Time: 2015-07-05T05:38:53+00:00
Session ID: 9a61343b778e47acfdd651b5db90d736
Problem Page URL: [/userid_details/5462b409e937907d70000169/edit](/userid_details/5462b409e937907d70000169/edit)
Previous Page URL: [http://freereg2.freereg.org.uk/userid_details/5462b409e937907d70000169](http://freereg2.freereg.org.uk/userid_details/5462b409e937907d70000169)
Reported Issue:
I am entering changes in FR1 UserIDs, such as when a new person registers, when a UserID is deleted, and also when a SC Enables/Disables a UserID.  But does the overnight update check for a valid and active UserID and only accept these records?  It should never happen, but if I have not set up a new UserID before they upload their first batch, that could be a problem.  Also, if I have not enabled a UserID before a file is submitted.    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by edickens** [comment]
Further to this problem.  CCs are Enabling a UserID in FR1 so as to be able to upload a file amended for the place name, then disabling it again.  This means that at the time of the overnight update the UserID will be Inactive in FR2.  So please do NOT check for Inactive in the overnight update, but a valid UserID check is needed.
E

**Comment by Captainkirkdawson** [comment]
A userid must exist for a file to be processed.

**Comment by edickens** [comment]
So I assume they can be Active or Inactive.

**Comment by Captainkirkdawson** [comment]
Correct
