### ISSUE TITLE
Editing "Role in  FreeREG" (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#283]
Issue reported by **REGManager** at 2015-07-05 09:46:36 UTC
Time: 2015-07-05T09:38:28+00:00
Session ID: f06eb505a1d3a6e91db6a48cad60d2db
Problem Page URL: [/userid_details/5462b408e937907d70000144/edit](/userid_details/5462b408e937907d70000144/edit)
Previous Page URL: [http://freereg2.freereg.org.uk/userid_details/5462b408e937907d70000144](http://freereg2.freereg.org.uk/userid_details/5462b408e937907d70000144)
Reported Issue:
I have been trying to change the Role of one of my UserIDs so that I could help EricB by getting rid of the "St." entries, particularly in Scotland which I am trying to tidy up.
But although I select Edit Profile, and the field goes dark as if it can be amended, and there is a star to say "Required" it seems that this can only be set at registration.
Obviously you cannot amend your own profile and change your Role.  But I am logged in as REGManager.
So either this is a non-editable field and should not be shown, or it needs a pick list.
E    

![Screenshot](http://freereg2.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1436089596-56833-8865/Capture.JPG)

**Comment by Captainkirkdawson** [comment]
REGManager can do anything that the Data Manager can do so you can just do what you need to do as REGManager.
REGManager can change the role but you cannot change your own role.
It is a pick list

**Comment by edickens** [comment]
TY
