### ISSUE TITLE
upload a new batch appears to go no further than the Action button at logon. (ericb)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#284]
Issue reported by **ericb** at 2015-07-05 11:46:39 UTC
Time: 2015-07-05T11:43:46+00:00
Session ID: fccb5c67077c27fe8b27750e0878a597
Problem Page URL: [/manage_counties/new](/manage_counties/new)
Previous Page URL: [http://freereg2.freereg.org.uk/manage_counties/select_action](http://freereg2.freereg.org.uk/manage_counties/select_action)
Reported Issue:
It used to allow Mgrs & CC's to upload in the userid of ones choice. but now if i select this immediately after logon ( from the RH column of actions)  it just presents a list of Counties to chose from and when in the selected County, the Upload button is no where to be seen.    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Function has yet to be enabled on the live servers.
