### ISSUE TITLE
Error in file? (brobinson43)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#285]
Issue reported by **brobinson43** at 2015-07-06 12:59:12 UTC
Time: 2015-07-06T12:56:03+00:00
Session ID: 28d36ca2046a92a34b0a402b4b6f9183
Problem Page URL: [/manage_resources/new](/manage_resources/new)
Previous Page URL: [http://freereg2.freereg.org.uk/refinery/login](http://freereg2.freereg.org.uk/refinery/login)
Reported Issue:
My coordinator on HUN reported that she received a message that the file HUNALCBA1.CSV could not be uploaded because of an error.

I have checked and rechecked on freereg1 and there is no sign of an error.

Which site is right?

Barrie Robinson

PS since I am registered with the NTH syndicate, Mary Korna cannot see my files on the site.    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by edickens** [comment]
```
Hi Barrie,

Both are now right.  The problem was that we did not have the
capitalisation right in FreeREG2.  This has now been fixed.  You
just need to upload your file again, but either add some more
records, or put a space in a blank field somewhere, to force an
update otherwise the overnight update will think that the file has
not changed.

All part of the settling in problems, but we are getting there.

Regards, 

Eric
_____________________________________
```

Eric J Dickens
FreeREG Chairman
    On 06/07/2015 13:59, FreeUKGenIssues
      wrote:

```
  Issue reported by brobinson43 at 2015-07-06
    12:59:12 UTC
    Time: 2015-07-06T12:56:03+00:00
    Session ID: 28d36ca2046a92a34b0a402b4b6f9183
    Problem Page URL: /manage_resources/new
    Previous Page URL: http://freereg2.freereg.org.uk/refinery/login
    Reported Issue:
    My coordinator on HUN reported that she received a message that
    the file HUNALCBA1.CSV could not be uploaded because of an
    error.
  I have checked and rechecked on freereg1 and there is no sign
    of an error.
  Which site is right?
  Barrie Robinson
  PS since I am registered with the NTH syndicate, Mary Korna
    cannot see my files on the site. 

  —
    Reply to this email directly or view
      it on GitHub.
```
