### ISSUE TITLE
Update UserID is not saving an edit. (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#286]
Issue reported by **REGManager** at 2015-07-09 21:29:55 UTC
Time: 2015-07-09T21:26:11+00:00
Session ID: 75f9fcf1c1db58a80ef19ce6b6c55ce1
Problem Page URL: [/userid_details/559ee55ef493fded8d000992](/userid_details/559ee55ef493fded8d000992)
Previous Page URL: [http://freereg2.freereg.org.uk/userid_details/selection?option=Select%20specific%20userid](http://freereg2.freereg.org.uk/userid_details/selection?option=Select%20specific%20userid)
Reported Issue:
I have entered Rachel_Lacey but after going back to change the Syndicate, and getting the message that the update was successful, on returning my changes have not been saved.  I will now check other UserIDs that I have done over the last few weeks.  I had not before gone back to check that the editing had taken.
E    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by edickens** [comment]
It only seems to be this evening or this particular UserID.
E

**Comment by Captainkirkdawson** [comment]
Logs show userid being created. 
Then at 22:21 being assigned to Devon then 3 minutes later being assigned to technical.
Have assigned to Devon with no difficulty.
Have activated the previous syndicate field to keep track of a change.
Please report any further such instance. At this time I propose no further action.

**Comment by edickens** [comment]
```
OK Now.  I set it up as Technical with my email address, did the
password, then went back in to assign to Devon and change the email
address to hers.  So don't know why it went back to Technical with
my email address again.  I do this routine for all new registrants. 
Have now change the email address - no problem.
E
_____________________________________
```

Eric J Dickens
FreeREG Chairman
    On 10/07/2015 01:09, Kirk Dawson wrote:

```
  Logs show userid being created. 
    Then at 22:21 being assigned to Devon then 3 minutes later being
    assigned to technical.
    Have assigned to Devon with no difficulty.
    Have activated the previous syndicate field to keep track of a
    change.
    Please report any further such instance. At this time I propose
    no further action.
  —
    Reply to this email directly or view
      it on GitHub.
```
