### ISSUE TITLE
ALTERNATE PLACE NAMES- add one and it generates 2 entries in Place name detail (ericb)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#287]
Issue reported by **ericb** at 2015-07-12 08:38:03 UTC
Time: 2015-07-12T08:34:34+00:00
Session ID: 11f85be5afc3c2f7041601e89bdf9cc1
Problem Page URL: [/places/5589faf7f493fd0e2e005f6d](/places/5589faf7f493fd0e2e005f6d)
Previous Page URL: [http://freereg2.freereg.org.uk/places/5589faf7f493fd0e2e005f6d/edit](http://freereg2.freereg.org.uk/places/5589faf7f493fd0e2e005f6d/edit)
Reported Issue:
Refer to BRE/ Llanthetty. which I edited & Approved just now. 
Then edited it to add Alternate name ( once!)
But on looking at the Place name detail, there are 2 lines showing  Alternate Place name.
I noticed yesterday in NFK there are many places with the same Alternate name being there 4 times!    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Sherlock21** [comment]
I do recall on e place where someone ( not me) has created 4 or more identical Alternative place name.
I cant remember where it was now.

**Comment by Captainkirkdawson** [comment]
Byproduct of the embedded collection process

**Comment by Captainkirkdawson** [comment]
Corrected

**Comment by Sherlock21** [comment]
Great. K

did it do a backfit tidy up  to start with please?

E

**Comment by Captainkirkdawson** [comment]
Has yet to be deployed. Only on test3 at this point

No it does not do a clean up. Easy for CC/others to do

Did you try to break it?
