### ISSUE TITLE
Stenness in Orkney has 2  identical Placename entries - can't delete one of them (ericb)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#288]
Issue reported by **ericb** at 2015-07-12 21:05:19 UTC
Time: 2015-07-12T21:02:30+00:00
Session ID: 7cf3b7ec7b22e85832581cb38a0bfc59
Problem Page URL: [/places/53cd8c41eca9eb1a9096c5e3](/places/53cd8c41eca9eb1a9096c5e3)
Previous Page URL: [http://freereg2.freereg.org.uk/places/53cd8c41eca9eb1a9096c5e3](http://freereg2.freereg.org.uk/places/53cd8c41eca9eb1a9096c5e3)
Reported Issue:
Tried changing the name of the one I want to delete into Stenness2 but that was rejected.
Tried to change it into StennessX so as to make it different to the other ( which has the church & file. But that  was also rejected.

What's gone wrong?    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Have no idea what happened but there were actually 3 distinct place documents with the place name of Stenness. Removed the 2 with no churches/registers.
Unable to duplicate problem with name change.
Propose to close. Please report any further instance.

**Comment by Sherlock21** [comment]
Yes, there were originally 3 identical place names.
One with files attached & 2 not.
I deleted one of the 2 without files
But not able to do anything with the remaining 2.

I am happy with that decision.
