### ISSUE TITLE
Locating a Locked problem (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#289]
Issue reported by **REGManager** at 2015-07-13 14:34:13 UTC
Time: 2015-07-13T14:30:16+00:00
Session ID: 20579890306c9fb830a1ea83def46f50
Problem Page URL: [/physical_files/userid?params=BobChown](/physical_files/userid?params=BobChown)
Previous Page URL: [http://freereg2.freereg.org.uk/physical_files/files_for_specific_userid](http://freereg2.freereg.org.uk/physical_files/files_for_specific_userid)
Reported Issue:
I have this report...
BobChown    KENTHUMA1.csv had been locked by either yourself or the coordinator and is not processed
But I cannot find the place.  I can look at Files and list by this UserID, but I need to find the place so that the Approval can be sorted out.
Having a Show contents, or list the Place/Church in the Files list by UserID would help

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Fail to see the requirement. There are so many different ways of doing what you want already. 
It is straight forward to select the Manage County option (Kent), use the Review Specific Batch option. Select the batch in question and you get access to the batch.
Alternatively go into the Manage Syndicate for Kent and List Files by Userid
![kent](https://cloud.githubusercontent.com/assets/2874694/8654218/429ddfbc-2946-11e5-8ad4-fe26863eb5eb.JPG)

**Comment by edickens** [comment]
Sorry.  Practice makes perfect.  And I think you told me once before!
E

**Comment by edickens** [comment]
```
Hi Ali,

This is the file in FR1...



Although uploaded on 12th, this is the file contents...



Still has the spelling error.

Regards,

Eric

_____________________________________
```

Eric J Dickens
FreeREG Chairman
    On 13/07/2015 17:07, Kirk Dawson wrote:

```
  Fail to see the requirement. There are so many different ways
    of doing what you want already. 
    It is straight forward to select the Manage County option
    (Kent), use the Review Specific Batch option. Select the batch
    in question and you get access to the batch.
    Alternatively go into the Manage Syndicate for Kent and List
    Files by Userid

  —
    Reply to this email directly or view
      it on GitHub.
```
