### ISSUE TITLE
System fails when I try to create a new Place name (ericb)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#290]
Issue reported by **ericb** at 2015-07-13 17:16:22 UTC
Time: 2015-07-13T17:14:10+00:00
Session ID: 64b06300fd0468842f9c80ca84d3d019
Problem Page URL: [/places/new](/places/new)
Previous Page URL: [http://freereg2.freereg.org.uk/places](http://freereg2.freereg.org.uk/places)
Reported Issue:
Tried to create HAUGHTON in Lancs.

GridRef SJ 933935

I Tried 3 times, and each timeI get the msg: sorry something seems to have gone wrong.    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
2 problems 1 yours and the other mine. Yours is the creation is failing likely because the Grid Ref is incorrectly formatted. No space between SJ and numbers please. Mine is an error on navigation when trying to tell you the creation failed.

**Comment by Sherlock21** [comment]
Thank you for the clue to my error - I copied it from elsewhere, and pasted it in . Sorry!

**Comment by Captainkirkdawson** [comment]
NP It was my error that masked the error message.

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Captainkirkdawson** [comment]
Fixed
