### ISSUE TITLE
Review  Specific Batch is not showing all batches (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#292]
Issue reported by **REGManager** at 2015-07-16 16:05:55 UTC
Time: 2015-07-16T16:00:38+00:00
Session ID: d96075d1b09ad53e841cc027735572ba
Problem Page URL: [/registers/5409ece0eca9eb7182707fbf](/registers/5409ece0eca9eb7182707fbf)
Previous Page URL: [http://freereg2.freereg.org.uk/places?page=2](http://freereg2.freereg.org.uk/places?page=2)
Reported Issue:
The attached shows all the batches.  There are three with the same batch name LEIHUMMA1.CSV but with different UserIDs.  The Review Specific Batch and the List of Batches, only show one.
E (notified by Doreen)

![Screenshot](http://freereg2.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1437062755-24568-0018/Capture.JPG)

**Comment by Captainkirkdawson** [comment]
Agreed that the Review Specific Batch is not showing the multiple batches. The List of batches in the Register and the list of batches by userid/ilename both show all batches.

**Comment by Captainkirkdawson** [comment]
Fixed
