### ISSUE TITLE
Download batch not offering a folder (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#293]
Issue reported by **REGManager** at 2015-07-18 11:13:03 UTC
Time: 2015-07-18T11:10:56+00:00
Session ID: c1ec405c3f30502d468d94f1d700ef8f
Problem Page URL: [/freereg1_csv_files/5463db23e9379010fcb6984c](/freereg1_csv_files/5463db23e9379010fcb6984c)
Previous Page URL: [http://freereg2.freereg.org.uk/registers/540a01deeca9eb7182b89bbb](http://freereg2.freereg.org.uk/registers/540a01deeca9eb7182b89bbb)
Reported Issue:
When I download a batch and select "Save" it does not let me select a folder.  I have now got to find out where it has been put.  Please add "Select folder".
E    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
To the best of my knowledge we have no influence on where you store or open files on your computer. It is something you tell your browser what to do according to the file type.

**Comment by edickens** [comment]
```
I found it in my Downloads folder.  I wanted to put it in my
Transcripts.
E
_____________________________________
```

Eric J Dickens
FreeREG Chairman
    On 18/07/2015 15:55, Kirk Dawson wrote:

```
  To the best of my knowledge we have no influence on where you
    store or open files on your computer. It is something you tell
    your browser what to do according to the file type.
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by Captainkirkdawson** [comment]
That's because you have set your browser to saving into that folder as your default. 
Its up to you how you set your browser up to respond to any file you download

**Comment by Sherlock21** [comment]
I have not had a play with this yet - where's the feature located please? T2 or T3?
Sherlock

**Comment by edickens** [comment]
```
Find the batch.  E
_____________________________________
```

Eric J Dickens
FreeREG Chairman
    On 18/07/2015 17:40, Sherlock21 wrote:

```
I have not had a play with this yet - where's the
  feature located please? T2 or T3?
  Sherlock
  On 18 Jul 2015, at 16:41, Kirk Dawson wrote:

  > That's because you have set your browser to saving into that
  folder as your default. 
  > Its up to you how you set your browser up to respond to any
  file you download
  > 
  > —
  > Reply to this email directly or view it on GitHub.
  > 

  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by Captainkirkdawson** [comment]
EricB

Its the download of a batch. Its operation on the production servers and on test3.

Go to any batch by any means and its one of the options offered for a batch

**Comment by Sherlock21** [comment]
I have been downloading batches for as long as the feature has been  available.  No problem at all  and exceptionally fast.
