### ISSUE TITLE
Can not move nearer the start of place name list than page 2.  (ericb)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#299]
Issue reported by **ericb** at 2015-07-22 11:47:44 UTC
Time: 2015-07-22T11:44:41+00:00
Session ID: ce4acb97e6ae6e35a63804ae19ed0543
Problem Page URL: [/places](/places)
Previous Page URL: [http://freereg2.freereg.org.uk/places](http://freereg2.freereg.org.uk/places)
Reported Issue:
this repeats an odd feature of last night's "Test3 changes" snag reported by email to Kisk    

![Screenshot](http://freereg2.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1437565664-2291-5390/Screen_shot_2015-07-22_at_12.44.55.jpg)

**Comment by Sherlock21** [comment]
I logged out, cleared all my browser cache, reset it, and logged on again straight to Test2 region.
Logged in, accessed DEV county ( as before) . it opened on page 1 as normal.
then went to page 6 or so, and tried back to page 1 but it sticks at page 2 - as in the image attached to original report.

**Comment by edickens** [comment]
I had the same.  I wasn't sure if it was me.  Had to log out and in 
again to clear it because even going back to "Your Actions" did not 
clear it.  When I went back to the same report and I was still stuck in 
the middle.
E

**Comment by Captainkirkdawson** [comment]
Premature deployment of part of a restructure. Removed
