### ISSUE TITLE
failure to create place: DBY/Ridgeway (ericb) On Hold pending additional material

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#30]
Issue reported by **ericb** at 2014-10-08 17:03:23 UTC
Time: 2014-10-08T17:01:06+00:00
Session ID: 9445437dbe405b2935e4d86b018735e6
Problem Page URL: [/manage_resources/539a6a3ceca9eb57f1000550](/manage_resources/539a6a3ceca9eb57f1000550)
Previous Page URL: [http://xanthus.freereg2.zomo.co.uk/refinery/login?](http://xanthus.freereg2.zomo.co.uk/refinery/login?)
Reported Issue:
please refer to email: Booker to Dawson 7 Oct 2014 GMT.

**Comment by Captainkirkdawson** [comment]
Unsure of issue cannot locate email.
DBY Ridgeway exists but as an unapproved name.
Additional information is needed to purue

**Comment by PatReynolds** [comment]
Email now not available.  Eric B. reports that error seems resolved.
