### ISSUE TITLE
Downloading a batch adds a 'C' to 'CCC' (steveroland)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#300]
Issue reported by **steveroland** at 2015-07-22 14:30:15 UTC
Time: 2015-07-22T13:52:22+00:00
Session ID: 12d5092c15947d5ac4668449a3e6c80c
Problem Page URL: [/freereg1_csv_files/5463a959e937904abbd9863e](/freereg1_csv_files/5463a959e937904abbd9863e)
Previous Page URL: [http://freereg2.freereg.org.uk/registers/5409d7fbeca9eba2062de017](http://freereg2.freereg.org.uk/registers/5409d7fbeca9eba2062de017)
Reported Issue:
If I download a batch, the second line starts: #,CCCC, 
but it should be #,CCC,    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Fixed
