### ISSUE TITLE
Server Down Message (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#302]
Issue reported by **REGManager** at 2015-07-23 05:55:49 UTC
Time: 2015-07-23T05:52:56+00:00
Session ID: 58dbb91e14a81451b0e11bf562c95f90
Problem Page URL: [/manage_resources/new](/manage_resources/new)
Previous Page URL: [http://freereg2.freereg.org.uk/freereg1_csv_entries/5463a35ee937904abbb76578/edit](http://freereg2.freereg.org.uk/freereg1_csv_entries/5463a35ee937904abbb76578/edit)
Reported Issue:
When the servers have to be taken off line for program corrections, can the URL be redirected to an "Apology try later" screen rather than just coming up with an error.  Researchers (Transcribers are emailing me to say "Server down".    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by PatReynolds** [comment]
Good idea - personally, I'd find 'Sorry, we are offline for a short period, while we are updating the program, please try later' has the information I'd need.

**Comment by Captainkirkdawson** [comment]
No action needed until such an event occurs in the future
