### ISSUE TITLE
When someone re (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#303]
Issue reported by **REGManager** at 2015-07-23 05:58:43 UTC
Time: 2015-07-23T05:58:24+00:00
Session ID: 58dbb91e14a81451b0e11bf562c95f90
Problem Page URL: [/search_records/55106b15e93790f8ad2bc23e?search_id=55b08276f493fd0b9100003d](/search_records/55106b15e93790f8ad2bc23e?search_id=55b08276f493fd0b9100003d)
Previous Page URL: [http://freereg2.freereg.org.uk/search_queries/55b08276f493fd0b9100003d](http://freereg2.freereg.org.uk/search_queries/55b08276f493fd0b9100003d)
Reported Issue:

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by edickens** [comment]
I accidentally hit Enter while doing this report and it sent it.  That is why there is a part complete subject line.  Perhaps it should wait until the "Submit" button is hit?

**Comment by Captainkirkdawson** [comment]
Enter is always viewed as submit
