### ISSUE TITLE
County coordinator selecting county (AMSA)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#305]
Issue reported by **AMSA** at 2015-07-23 09:22:38 UTC
Time: 2015-07-23T09:17:32+00:00
Session ID: ed960289d2de32516716753125f77890
Problem Page URL: [/manage_counties/new](/manage_counties/new)
Previous Page URL: [http://freereg2.freereg.org.uk/manage_resources/new](http://freereg2.freereg.org.uk/manage_resources/new)
Reported Issue:
Not a big issue but irritating!
When I go in to manage county I get the message "You have access to multiple counties, please select one"
The drop down box then lists the ONE county I have access to which I have to click and then press select.
1) The message is incorrect
2. As I DO only have access to 1 county can I not be directed straight there rather than an unnecessary drop down box & extra clicks???.

Thanks
AnnaRufer
Northamptonshire coordinator

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by edickens** [comment]
And may I add.  When you do have more than one county, after finding the 
one you want, and clicking on it, you then have to click the Select 
button.  There are other pick lists where it is not necessary to have a 
separate Select button.  This is only necessary if you are selecting 
multiple entries at the same time, such as the Places list on the Search 
page, but I don't think this is necessary when a CC is selecting a 
County to work on.

---

Eric J Dickens
FreeREG Chairman

**Comment by Captainkirkdawson** [comment]
Propose to close. If there is only 1 county then there is no selection.
