### ISSUE TITLE
Relocate function (REGScotland)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#306]
Issue reported by **REGScotland** at 2015-07-23 16:50:09 UTC
Time: 2015-07-23T16:48:21+00:00
Session ID: 3628728e160dc8d1b09a03a404cdd385
Problem Page URL: [/freereg1_csv_files/5463a976e9379010fcd67195](/freereg1_csv_files/5463a976e9379010fcd67195)
Previous Page URL: [http://freereg2.freereg.org.uk/registers/5408fc37eca9eb260e0c91ec](http://freereg2.freereg.org.uk/registers/5408fc37eca9eb260e0c91ec)
Reported Issue:
I have not been able to use the relocate fuction since yesterdat afternoon.

Is there a problem?    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Nothing to do with relocate
