### ISSUE TITLE
Overnight update failed? (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#307]
Issue reported by **REGManager** at 2015-07-24 05:15:48 UTC
Time: 2015-07-24T05:14:32+00:00
Session ID: b480864eb37d7be7b96c46aded0b2ab2
Problem Page URL: [/manage_resources/new](/manage_resources/new)
Previous Page URL: [http://freereg2.freereg.org.uk/refinery/login](http://freereg2.freereg.org.uk/refinery/login)
Reported Issue:
The overnight update has only processed one file.  This is definitely not correct.
E    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by edickens** [comment]
I have now had reports that some other files were updated, so perhaps it is just a report that I am missing.
It is interesting that now we do overnight updates, transcribers are looking for their work the next day and emailing me if it is not there.  They look at the record count for the place that they are working on.
We processed 3489 entries, but the database count went up by 8944.
E

**Comment by Captainkirkdawson** [comment]
Update failed twice last night. 
Once on permissions. Fixed that and reran but the re-sync overwrote the change list so only 1 new record was found  Should never do these things after celebrating ones 76 birthday!
Then did a comparison update, something i had wanted to do to clean up the missing files in the base database. That died will I was in bed. Will investigate and get a copy of the report of what id did. Will complete tonight if issue can be found in time.

**Comment by Sherlock21** [comment]
I resist the temptation to comment upon which was the wrong decision here!

Congratulations Kirk. And here's to many more of them. X X X
just a couple of months in front of me. - i will remember the your example and book the day off!

**Comment by edickens** [comment]
Congratulations, but I am a year and a half ahead of you.
E

**Comment by Captainkirkdawson** [comment]
Resolved
