### ISSUE TITLE
Sequence of Manage Syndicate; List by UserID:Filename (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#309]
Issue reported by **REGManager** at 2015-07-24 13:47:20 UTC
Time: 2015-07-24T13:44:21+00:00
Session ID: 5611929fcdbf7c25ca0919bbedcad54a
Problem Page URL: [/manage_syndicates/selection?_method=get&authenticity_token=S%2Fmhy%2BKtPsiE1%2F3b%2FicZAeK%2FErMbgr5P8yMqnheDnDk%3D&option=Review+Batches+by+Userid+then+Filename&page=7](/manage_syndicates/selection?_method=get&authenticity_token=S%2Fmhy%2BKtPsiE1%2F3b%2FicZAeK%2FErMbgr5P8yMqnheDnDk%3D&option=Review+Batches+by+Userid+then+Filename&page=7)
Previous Page URL: [http://freereg2.freereg.org.uk/manage_syndicates/selection?_method=get&authenticity_token=S%2Fmhy%2BKtPsiE1%2F3b%2FicZAeK%2FErMbgr5P8yMqnheDnDk%3D&option=Review+Batches+by+Userid+then+Filename&page=8](http://freereg2.freereg.org.uk/manage_syndicates/selection?_method=get&authenticity_token=S%2Fmhy%2BKtPsiE1%2F3b%2FicZAeK%2FErMbgr5P8yMqnheDnDk%3D&option=Review+Batches+by+Userid+then+Filename&page=8)
Reported Issue:
All uppercase come before the start of lowercase UserIDs.  Attached shows the change.
This might apply to all "List by UserID:Filename".
E    

![Screenshot](http://freereg2.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1437745640-84943-1147/Capture.JPG)

**Comment by Captainkirkdawson** [comment]
Fixed
