### ISSUE TITLE
testing (ericb)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#31]
Issue reported by **ericb** at 2014-10-18 13:40:21 UTC
Time: 2014-10-18T13:38:12+00:00
Session ID: 72c945ce80ce97a763215f5f5f8fa76d
Problem Page URL: [/manage_resources/539a6a3ceca9eb57f1000550](/manage_resources/539a6a3ceca9eb57f1000550)
Previous Page URL: [http://test2.freereg.org.uk/refinery/login?](http://test2.freereg.org.uk/refinery/login?)
Reported Issue:
The Register a new Transcriber fails when i complete the form and send it.

No way to pick the error message and attach it to here either.

No Agreement form attached to Registration now.

EricB

**Comment by Captainkirkdawson** [comment]
Need information on error to make any progress on this. All other tests of registration have worked.

**Comment by Captainkirkdawson** [comment]
I have made a number of tests and am unable to find any problem.

**Comment by Captainkirkdawson** [comment]
Eric has confirmed he has no problems
