### ISSUE TITLE
Order Church Names and Register  names in alphabetical order asc. (ericb)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#310]
Issue reported by **ericb** at 2015-07-25 16:17:58 UTC
Time: 2015-07-25T16:14:39+00:00
Session ID: 486dfdc549619a5a05c49de381425340
Problem Page URL: [/manage_counties/new](/manage_counties/new)
Previous Page URL: [http://freereg2.freereg.org.uk/manage_resources/new](http://freereg2.freereg.org.uk/manage_resources/new)
Reported Issue:
The present ordering of church names within a Place name is random. So is the order of Register types within a Church name.

Much easier for the reader to find, if you would put in Alphabetical order Asc. please. - when you have a moment or are in the appropriate area of coding.    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by PatReynolds** [comment]
Where is this, please?  Researchers can order results how they will.  In listing we looked at last week the 'incorrect' ordering was due to typos of names.

**Comment by Captainkirkdawson** [comment]
This is only on the index listing of Places for Coordinators. The churches are "random"

**Comment by PatReynolds** [comment]
Thanks, is this something that should be fixed in Version 1.2, Version 1.5, or sometime/never?

**Comment by Captainkirkdawson** [comment]
Assigned 1.5

**Comment by Captainkirkdawson** [comment]
Implemented
