### ISSUE TITLE
merged file (REGScotland)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#311]
Issue reported by **REGScotland** at 2015-07-26 16:38:23 UTC
Time: 2015-07-26T16:33:19+00:00
Session ID: 3dbfc1b051f8b2b919c95b81ea30a7fe
Problem Page URL: [/freereg1_csv_files/54639c32e9379010fc90353a](/freereg1_csv_files/54639c32e9379010fc90353a)
Previous Page URL: [http://freereg2.freereg.org.uk/registers/54084ce6eca9eb02483b5d68](http://freereg2.freereg.org.uk/registers/54084ce6eca9eb02483b5d68)
Reported Issue:
Hi,

I have just merge two files ELNBOLBU 25 records & 2 records
USerid = bunothan.

IT was successfull but I noticed "The number od decades in each year" are the wrong count (see Snapshot).

It may be I have to wait until the over night upload but not sure.

Regards Doreen    

![Screenshot](http://freereg2.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1437928703-95910-4588/ELN__ELNBOLBU.CSV_for_kirk.JPG)

**Comment by Captainkirkdawson** [comment]
Good catch

**Comment by Captainkirkdawson** [comment]
Added the recalculation of the distribution. Also added the putting of early and late years in first and last bins
