### ISSUE TITLE
date errors on newly uploaded file (JHarold)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#312]
Issue reported by **JHarold** at 2015-07-27 12:22:45 UTC
Time: 2015-07-27T12:20:02+00:00
Session ID: 23a8f0a29ad5e77f28d23e522da20ff9
Problem Page URL: [/freereg1_csv_files/55b59654f493fdc517000202/error](/freereg1_csv_files/55b59654f493fdc517000202/error)
Previous Page URL: [http://freereg2.freereg.org.uk/manage_counties/selection?option=Review%20Batches%20by%20Most%20Recent%20Date%20of%20Change](http://freereg2.freereg.org.uk/manage_counties/selection?option=Review%20Batches%20by%20Most%20Recent%20Date%20of%20Change)
Reported Issue:
I am getting these dates showing up as errors 

31 Jan 1599/1600
14 Feb 1599/1600

can you tell me why ?  This didn't get flagged as an error on FR1

Julie

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Fixed
