### ISSUE TITLE
Would it be possible to navigate directly to all churches beginning with a certain letter? (MikeNL)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#314]
Issue reported by **MikeNL** at 2015-07-28 15:36:57 UTC
Time: 2015-07-28T15:35:04+00:00
Session ID: 1fedb10379a2c8cf20d6494cf557dea1
Problem Page URL: [/places](/places)
Previous Page URL: [http://freereg2.freereg.org.uk/places?page=4](http://freereg2.freereg.org.uk/places?page=4)
Reported Issue:

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Sherlock21** [comment]
??Is this a researcher question or a Member??
?? why do this?? is this a spoof /fishing sort of query to get us to reveal basics?
?? IN a County?? 
or IN the whole Country??
And what's the benefit?

**Comment by edickens** [comment]
MikeNL is Michael Clarke, the new CC for STS.
It is interesting to get a new person's reaction to the website.
E

**Comment by Captainkirkdawson** [comment]
Given that there has been no further request for this I propose to close

**Comment by Sherlock21** [comment]
I thought this is  a good idea when raised  even though i suggest some more parameters are needed.

And I still think it a useful tool for Both Researchers and Members.

e.g.: IN ANY ONE COUNTY: where are all the churches named 'All Saints'? then one can navigate straight to that County /Place name, using the machine to do the work of backtracking, re typing and scrolling down. No data would be seen until one had got down the the appropriate lever, depending one ones Profile.

I think this tool would be very useful in for example LDN or MDX ( but not exclusively these)- where the church name is known but not the 'Town' 

It would also show the user how many ST Mary churches there are in a County. Handy where one has a register which does not have recognisable  Placename  on it and thus a degree of research is needed before one can even start transcribing. - something that I often get asked to help in.

**Comment by Sherlock21** [comment]
There has not been further comment because we were awaiting the job coming to its turn.
