### ISSUE TITLE
Clean up database for duplicate/blank Witness entries 

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#315]
Issue reported by **REGManager** at 2015-07-29 13:55:25 UTC
Time: 2015-07-29T13:53:11+00:00
Session ID: 6ec296ab5b0272cde4d872b1d7e49717
Problem Page URL: [/freereg1_csv_entries/54639d0be9379027829907ae](/freereg1_csv_entries/54639d0be9379027829907ae)
Previous Page URL: [http://test3.freereg.org.uk/freereg1_csv_entries?_method=get&authenticity_token=jarT8A3eIl22tUbcqsjjEj%2BTSlJpBJ00ZryVS1GwD38%3D&page=4](http://test3.freereg.org.uk/freereg1_csv_entries?_method=get&authenticity_token=jarT8A3eIl22tUbcqsjjEj%2BTSlJpBJ00ZryVS1GwD38%3D&page=4)
Reported Issue:
The two witness names are copied into the next witness fields.  See attached.
But edit and everything else works fine.
I like the second notes field.
E    

![Screenshot](http://test3.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1438178125-1420-7958/Capture.JPG)

**Comment by Captainkirkdawson** [comment]
This is not anything to do with the edit capability. 
It actually has shown that the database was being incorrectly populated with a double set of witness entries as well as blank entries.
The database creation/update software now works correctly.
Database needs to be cleaned up.

**Comment by edickens** [comment]
I would suggest it does not need cleaning up, unless someone is working 
on that record.  The facts are there and a search will find the person - 
perhaps more than once, but that does not matter.
The only thing that could be done, if not too difficult, is to blank out 
Witnesses 3+ as these cannot be entered in FR1 and will have nothing in 
them as yet.  Will Mike introduce these fields to WinFreereg?  (As well 
as the Transcriber's Notes?)
E

**Comment by Captainkirkdawson** [comment]
FR2 permits as many witnesses as there are in the original record. Yes WinFreeREG will need to accommodate. 
Lets not eliminate features because FR1 does not support!
Database does need to be cleaned up because its incorrect.

**Comment by edickens** [comment]
So is that list of Witness names that long in the example I gave because 
they have spaces?  Not all have names in them.  In which case a field 
with just a Space should be ignored.
E

**Comment by Captainkirkdawson** [comment]
I refuse to add patches into display and edit software to coverup an underlying content problem. The correct solution is to correct the underlying content problem.

**Comment by edickens** [comment]
Agreed.  Needs a once off routine to edit the database.
E

**Comment by Captainkirkdawson** [comment]
Code is written; will run next week during the Freereg slot

**Comment by Captainkirkdawson** [comment]
Waitin end of BMD update
