### ISSUE TITLE
Add Alternate County for a Place (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#316]
Issue reported by **REGManager** at 2015-07-29 14:08:40 UTC
Time: 2015-07-29T13:55:59+00:00
Session ID: 6ec296ab5b0272cde4d872b1d7e49717
Problem Page URL: [/places/53cd4939eca9ebee4f000fbe/edit](/places/53cd4939eca9ebee4f000fbe/edit)
Previous Page URL: [http://test3.freereg.org.uk/places/53cd4939eca9ebee4f000fbe](http://test3.freereg.org.uk/places/53cd4939eca9ebee4f000fbe)
Reported Issue:
I'm not sure if it will cause problems when BenB programs the use of the Alternate place name, but I would like it to have an Alternate County as well.  This can then be used for county boundary changes where the same place name but a different county could be entered.
The place selection list in the Search will need to show these places in the other county, but still select the primary county/place records.  See #313
See attached where GENUKI Gazatteer is mis-spelt.  s/b Gazetteer.    

![Screenshot](http://test3.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1438178920-1420-0491/Capture.JPG)

**Comment by Captainkirkdawson** [comment]
Edited title to be specific; original was far too broad

**Comment by PatReynolds** [comment]
Discussion relating to this issue can be found at #313 (one of two issues with this number)

**Comment by Sherlock21** [comment]
I don't like this idea one bit.
Are you suggesting that someone takes notes of all the County Boundary changes done, since 1834 ( which is our declared baseline) and progressively updates all the Placenames to match these changes?

If so, who?

**Comment by Captainkirkdawson** [comment]
@Sherlock21 story is closed. Nothing is to be done
