### ISSUE TITLE
Display a witness number (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#317]
Issue reported by **REGManager** at 2015-07-29 14:49:50 UTC
Time: 2015-07-29T14:45:59+00:00
Session ID: 277c2ffebe137877f3980662749a1c2a
Problem Page URL: [/freereg1_csv_entries/54639d0ae937902782990565](/freereg1_csv_entries/54639d0ae937902782990565)
Previous Page URL: [http://test3.freereg.org.uk/freereg1_csv_entries](http://test3.freereg.org.uk/freereg1_csv_entries)
Reported Issue:
Would it be a good idea in the MA entry display to identify the witnesses by number?  The reason is that someone may report a problem and will need to say "Witness 5 last name s/b".
E    

![Screenshot](http://test3.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1438181390-1420-3516/Capture.JPG)

**Comment by Captainkirkdawson** [comment]
The display you are referring to is an internal display available only to transcribers/coordinators.
