### ISSUE TITLE
Witness Edit not updating the search record collection (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#318]
Issue reported by **REGManager** at 2015-07-29 16:19:38 UTC
Time: 2015-07-29T16:15:06+00:00
Session ID: 2b614ec70b37a7129af23b38c84ebbf0
Problem Page URL: [/search_records/55109350e937907e5f525c72?search_id=55b8fbfae93790fdf5000008](/search_records/55109350e937907e5f525c72?search_id=55b8fbfae93790fdf5000008)
Previous Page URL: [http://test3.freereg.org.uk/search_queries/55b8fbfae93790fdf5000008](http://test3.freereg.org.uk/search_queries/55b8fbfae93790fdf5000008)
Reported Issue:
I have now used the Search function to look at the display of Witnesses in the entry that I amended .  See attached.  The amendment which I made to Witness 1, changing the first name to Sarah, does not show.
Also, Witnesses 3+ do not show and Notes do not show.  I added a Transcriber Note.    

![Screenshot](http://test3.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1438186778-1420-3049/Capture.JPG)

**Comment by Captainkirkdawson** [comment]
I believe this was fixed some time ago. Need Eric to confirm

**Comment by edickens** [comment]
Looks OK now.  E
