### ISSUE TITLE
Sequence of report "Select UserID by Surname:Firstname (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#319]
Issue reported by **REGManager** at 2015-07-30 09:01:29 UTC
Time: 2015-07-30T08:59:01+00:00
Session ID: e6dba8704725932799bfc03c1e48b22a
Problem Page URL: [/userid_details/5462b407e937907d70000116/edit](/userid_details/5462b407e937907d70000116/edit)
Previous Page URL: [http://freereg2.freereg.org.uk/userid_details/5462b407e937907d70000116/edit](http://freereg2.freereg.org.uk/userid_details/5462b407e937907d70000116/edit)
Reported Issue:
Can the selection list be case insensitive.  Those names starting lowercase are at the end.  I nearly missed them.    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Given that there has been no further request for this feature propose to close

**Comment by edickens** [comment]
This feature now exists.  And by email address.
