### ISSUE TITLE
action LB (List Batches) (deo123)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#320]
Issue reported by **deo123** at 2015-08-01 15:41:06 UTC
Time: 2015-08-01T15:34:05+00:00
Session ID: c61a923d3221aefc902da087ff0b619a
Problem Page URL: [/userid_details](/userid_details)
Previous Page URL: [http://freereg2.freereg.org.uk/manage_syndicates/select_action](http://freereg2.freereg.org.uk/manage_syndicates/select_action)
Reported Issue:
Hi,

select Userid 2121914 Pauline Starling it says one batch 2088 records. But when I select
LB (List Batches), there are no batches. Also on F1 she has NO batches.

Regards Doreen    

![Screenshot](http://freereg2.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1438443666-33168-3330/Userid_Pauline_Starling-2121914.JPG)

**Comment by Captainkirkdawson** [comment]
Thanks Doreen; you should find that this has been addressed on Monday.

K

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1
