### ISSUE TITLE
Action In/Act (deo123)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#321]
Issue reported by **deo123** at 2015-08-01 16:06:27 UTC
Time: 2015-08-01T15:58:27+00:00
Session ID: 037198241b218161245992571cbc795f
Problem Page URL: [/userid_details](/userid_details)
Previous Page URL: [http://freereg2.freereg.org.uk/manage_syndicates/select_action](http://freereg2.freereg.org.uk/manage_syndicates/select_action)
Reported Issue:
Hi,

I have just selected "All Members"  yet they are all set to "in"  which in the action windows say's
in/act: inactive/active

I pressed "in" and an error came up "were sorry but something went wrong"

Regards Doreen    

![Screenshot](http://freereg2.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1438445187-33165-0745/changing_In_to_Act.JPG)

**Comment by Captainkirkdawson** [comment]
Cannot duplicate the first statement that All Members Shows the IN/ACT as
IN. This only happens if you have selected the Active list.Check the page
title.

Second issue is a breadcrumb bug. Will deploy the fix tonight

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1
