### ISSUE TITLE
Pressing the "Record In question" button (MikeNL)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#322]
Issue reported by **MikeNL** at 2015-08-01 22:13:54 UTC
Time: 2015-08-01T22:01:33+00:00
Session ID: 0e00dcaf3d1afc89450a1b9d61b2058b
Problem Page URL: [/contacts/55bd35bd33045bd5e100225d](/contacts/55bd35bd33045bd5e100225d)
Previous Page URL: []()
Reported Issue:
When I pressed the "Record In question" button on the "Contact Details" screen I got the message "The page you were looking for doesn't exist."

As coordinator for STS I cannot get to the record, reported by the user, that is in error. As a result, I cannot make the alteration(s) to the record that the user requested.    

![Screenshot](http://freereg2.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1438467234-33165-0435/Start_Screen.JPG)

**Comment by edickens** [comment]
Hi Mike,
You have to be logged in first.  I find it is easier to log in and 
select Contacts and find the message by Date and Time,
Eric
