### ISSUE TITLE
Problem on Problem Report page (MikeNL)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#323]
Issue reported by **MikeNL** at 2015-08-01 22:25:32 UTC
Time: 2015-08-01T22:13:54+00:00
Session ID: 0e00dcaf3d1afc89450a1b9d61b2058b
Problem Page URL: [/contacts/55bd35bd33045bd5e100225d](/contacts/55bd35bd33045bd5e100225d)
Previous Page URL: [http://freereg2.freereg.org.uk/feedbacks/new?utf8=%E2%9C%93&feedback_time=2015-08-01+22%3A01%3A33+UTC&session_id=0e00dcaf3d1afc89450a1b9d61b2058b&user_id=MikeNL&problem_page_url=%2Fcontacts%2F55bd35bd33045bd5e100225d&previous_page_url=&feedback_type=issue](http://freereg2.freereg.org.uk/feedbacks/new?utf8=%E2%9C%93&feedback_time=2015-08-01+22%3A01%3A33+UTC&session_id=0e00dcaf3d1afc89450a1b9d61b2058b&user_id=MikeNL&problem_page_url=%2Fcontacts%2F55bd35bd33045bd5e100225d&previous_page_url=&feedback_type=issue)
Reported Issue:
There are actually two "problems" that I would bring to your attention. They both concern this page.
1. Which is the correct button, out of "Submit Problem Report" and "Report a Problem", to press to submit/report a problem? Are the two buttons there for different reasons? If they are different, the difference should be made clear on the page.
2. Using the "Choose File" button only allows one screenshot to be added. I feel that it should have the possibility, similar to emails, to add one or more screen shots.    

![Screenshot](http://freereg2.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1438467932-33165-5527/Problem_Report.JPG)

**Comment by Captainkirkdawson** [comment]
Mike. TY for your comment; agree that the two buttons are too close; will
look at changing positions.  You clearly know the answer.

We have a story for adding additional attachments but it has yet to work
its way up the priority list.

PS welcome aboard as a Coordinator

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Captainkirkdawson** [comment]
Separation of buttons was achieved.
