### ISSUE TITLE
The 'County' value in a search results list is sometimes blank (ericb)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#324]
Issue reported by **ericb** at 2015-08-02 09:29:51 UTC
Time: 2015-08-02T09:13:14+00:00
Session ID: 9ebe27f4dafffeb98239a3159849aa19
Problem Page URL: [/search_queries/55bddf2af493fd95aa0000cd](/search_queries/55bddf2af493fd95aa0000cd)
Previous Page URL: [http://freereg2.freereg.org.uk/search_queries/new](http://freereg2.freereg.org.uk/search_queries/new)
Reported Issue:
This appears to link up to whether the Place & county boxes have been populated in the Place name details page.
- When the feature to populate these fields was introduced, Kirk advised: "Its only decorative".
  but it seems to actually link to the search results fields. Or is that just a coincidence?

having got a result that had no County shown I went to the Place name Edit, and populated the Place & County & Region properly and then ran the same query again and these values then appeared in the right place in the results list.
Can you give me a listing of all the Places without the Region & County present so i can update please if this was the real cause?    

![Screenshot](http://freereg2.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1438507791-8454-2349/Clent___Nearby.jpg)

**Comment by Captainkirkdawson** [comment]
It is decorative in the sense that it is displayed in the results. Its
absence does not affect the search which uses the Chapman Code.

A report could be written

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Captainkirkdawson** [comment]
The tool to fix is there. It just needs to be used

**Comment by edickens** [comment]
```
And remember to unlock the batch after fixing.
E
_____________________________________
```

Eric J Dickens
FreeREG Chairman
    On 12/08/2015 04:55, Kirk Dawson wrote:

```
  The tool to fix is there. It just needs to be used
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by Captainkirkdawson** [comment]
Excuse me  why?

Changing information about a place does not lock a batch.

Just like changing information about a church or register lock a file.

ie it is only changing the actual place/church/register IN a batch that
lock the file.

I hope you know what you are doing with that advise because it will
 overwrite the change made.

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by PatReynolds** [comment]
Just writing something so that EricB and others can see this.  

I may have been mistaken, but I think when we discussed this at the last scrum, Kirk said there was no fix, and missing counties should be notified individually.

**Comment by Sherlock21** [comment]
The key question remaining is the absence of the Region & County in a Place name info page, anything to do with the fact that some Search results come out without a County in the appropriate column? Or was Michael Clarke's complaint about Stoke-on-Trent which exhibited this, just a coincidence?

**Comment by Sherlock21** [comment]
After a test of mine, If I pick King's Lynn and do a search of any particular name, the result sheet does not contain the County name in it 9 because the Place name details field does not contain England/ Norfolk.
If I edit the Placename/ County + Country fileds, then run same query, the result sheet DOES contain the missing 'County' name.

SO all we need is for a List of all Places where the Region + County is missing.
in csv form so I can order it.  I can then use on a spreadsheet to work though and populate these omissions - If you can organise that please Pat?

**Comment by Captainkirkdawson** [comment]
The absence of Region and County in a Place is 100% the reason that there is no County in the search results column. It arrises because the Place was originally unapproved and there was you Region and County for the Place.

**Comment by PatReynolds** [comment]
I have started
https://docs.google.com/document/d/1h2ozIGN_UtsnHCMX7BlzrhQj08V56EVbLJjpqTs1rj4/edit?usp=sharing
- could you circulate this link to people who might be happy to contribute
  to it?

Is this ok as a format - please do change if need be.

Best wishes,

Pat

_\- -_

_Dr Pat Reynolds_
Executive Director
Free UK Genealogy  http://www.freeukgenealogy.org.uk/
A charity registered in England and Wales, number 1096940

​+44 ​1904 541411​ +44 7943 145387

36 Albemarle Road, York, YO23 1ER, UK

**Comment by Captainkirkdawson** [comment]
Pat

It would be much easier for me to generate the report, but it is not in the
scrum backlog.

K

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by PatReynolds** [comment]
Thanks, Kirk.  We can move to backlog at the scrum.

Best wishes,

Pat

**Comment by Captainkirkdawson** [comment]
A report listing the 100 Places affected by this have been provided to the data manager to correct

**Comment by Sherlock21** [comment]
This can be closed now.

**Comment by Captainkirkdawson** [comment]
Thank you for the work
