### ISSUE TITLE
Editing Register details of Church name & register type. (ericb)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#325]
Issue reported by **ericb** at 2015-08-02 14:50:58 UTC
Time: 2015-08-02T14:43:10+00:00
Session ID: 0775e04efc2f44f441260664fdd9ddd2
Problem Page URL: [/manage_resources/new](/manage_resources/new)
Previous Page URL: [http://freereg2.freereg.org.uk/refinery/login](http://freereg2.freereg.org.uk/refinery/login)
Reported Issue:
To edit the Register Type one needs to go through the whole string of effectively Relocate
and stands a significant chance of getting the  Region or Place name wrong - just to get to the bottom line of change the register from Nothing (Unspecified) to PR or whatever. and also the church name from Parish Church to St John.

When we get to standardising church names, all CC's will be expected to do this however good and careful at it  - OR OTHERWISE they may be.

A short version which prevents them doing more harm than good, seems a good option for all.

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
There already is a very simple function.

On the Register Page simply click Change Register Type

**Comment by Sherlock21** [comment]
Forgive me but which page do you refer to?

this one for edit Register?:

if i do Edit Register Fields it does not give me anything like the above the below is where it goes to;-

**Comment by Captainkirkdawson** [comment]
![register](https://cloud.githubusercontent.com/assets/2874694/9027067/a1cc77ce-3903-11e5-8ca1-853b1eefaba8.JPG)

**Comment by Sherlock21** [comment]
But I don't have a St Thomas in Durham ( neither in FR2 or 3) these are all for Durham

Pick on any church - say St Margaret

which gives me a different set of actions to you. and although there is one: Edit Register it navidates to a totally different collection - Quality of images etc. NOT to let me change the Reg Type as one would expect. - same as in the set of screen prints which i first sent you.
EB

**Comment by Captainkirkdawson** [comment]
I see why it was a protected function

**Comment by Captainkirkdawson** [comment]
PS never got any screen shots from you on this or your own profile issue

**Comment by Captainkirkdawson** [comment]
Have removed the protection and will be generally available tomorrow

**Comment by Sherlock21** [comment]
Thank you, Kirk.
