### ISSUE TITLE
FR2 Profile email address does not update auto emails from FreeUKGenissues (ericb)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#326]
Issue reported by **ericb** at 2015-08-02 14:53:46 UTC
Time: 2015-08-02T14:51:35+00:00
Session ID: 0775e04efc2f44f441260664fdd9ddd2
Problem Page URL: [/userid_details/my_own?](/userid_details/my_own?)
Previous Page URL: [http://freereg2.freereg.org.uk/manage_resources/new](http://freereg2.freereg.org.uk/manage_resources/new)
Reported Issue:
I still get auto produced emails from " Report an Issue" even though I have updated my Profile email.    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
You will have to provide more information than a simple assertion.
Am unaware of a " Report an Issue"  system.

**Comment by Sherlock21** [comment]
screen dump images sent by personal email to Kirk

**Comment by Captainkirkdawson** [comment]
Not FR2 issue
