### ISSUE TITLE
Links not found and undelivered mail (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#327]
Issue reported by **REGManager** at 2015-08-02 15:14:19 UTC
Time: 2015-08-02T15:08:31+00:00
Session ID: 1e5e5d35ccf9783465917f9f43a16a9c
Problem Page URL: [/contacts/55be24d833045bd17f000312](/contacts/55be24d833045bd17f000312)
Previous Page URL: [http://freereg2.freereg.org.uk/contacts](http://freereg2.freereg.org.uk/contacts)
Reported Issue:
The attached Contact does not help because neither Record in Question or Convert to issue work, both giving "Something has gone wrong".  In addition this email address for Julie is not correct, so without knowing the County or where this report was generated I will have to do some digging to find out.
E    

![Screenshot](http://freereg2.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1438528459-8454-5397/Capture.JPG)

**Comment by Captainkirkdawson** [comment]
I had no problem.
Attached are my screenshots.
I do not know why Julie submitted such a report using that address but that is what was entered
Perhaps it was just to remind her.
Why are you even trying to do something? This is something for the coordinator is it not?
![julie1](https://cloud.githubusercontent.com/assets/2874694/9026766/7bb92870-38f9-11e5-80b5-fc2bd4736718.JPG)
![julie](https://cloud.githubusercontent.com/assets/2874694/9026767/7bba1c3a-38f9-11e5-8874-a81df4deeaaa.JPG)

**Comment by Sherlock21** [comment]
ok

auto generated email to me.
comes to eric.booker@virgin.net

but here is my Profile page

**Comment by Captainkirkdawson** [comment]
Eric; I am unsure of the relevance of this post to this story

**Comment by edickens** [comment]
I only followed it up because I got a "Return to sender unknown email 
address" through reg-web.
Julie must have been searching something in STS.
E

---

Eric J Dickens
FreeREG Chairman

**Comment by Captainkirkdawson** [comment]
Exactly; so what is issue?

**Comment by edickens** [comment]
Not worth spending time on this.  The links didn't work for me but I 
have too many other things to do.
Same with Undeliverable mail.
Can be closed.
E
