### ISSUE TITLE
Links not found and undelivered mail - PS (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#328]
Issue reported by **REGManager** at 2015-08-02 15:27:14 UTC
Time: 2015-08-02T15:18:33+00:00
Session ID: 1e5e5d35ccf9783465917f9f43a16a9c
Problem Page URL: [/feedbacks/55be33cbf493fd95aa000265](/feedbacks/55be33cbf493fd95aa000265)
Previous Page URL: [http://freereg2.freereg.org.uk/feedbacks](http://freereg2.freereg.org.uk/feedbacks)
Reported Issue:
Looking at the Feedback report, I am even more confused.  See attached at the bottom of it.  I have not been anywhere near STS or the file concerned.
The wrong email address for Julie looks to be through re-web@freereg.org,uk which only goes to Ben Laurie and myself.  Julie is not in the FR1 Alias list at all.  And this email address of her's julie@highfields.plus.com is not in any UserID.  So where has it come from?
E    

![Screenshot](http://freereg2.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1438529234-8454-2777/Capture.JPG)

**Comment by Captainkirkdawson** [comment]
See 327
