### ISSUE TITLE
Duplication of witness names (MaryKay)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#329]
Issue reported by **MaryKay** at 2015-08-02 17:06:45 UTC
Time: 2015-08-02T16:56:44+00:00
Session ID: a0f751162e77b3b141cf3e7c5e8fe9f8
Problem Page URL: [/freereg1_csv_entries/54d0af39e9379089030b27c0](/freereg1_csv_entries/54d0af39e9379089030b27c0)
Previous Page URL: [http://freereg2.freereg.org.uk/freereg1_csv_entries/54d0af39e9379089030b27c0/edit](http://freereg2.freereg.org.uk/freereg1_csv_entries/54d0af39e9379089030b27c0/edit)
Reported Issue:
editing record 

There are two witnesses (See below from download)

CAM,Wisbech,St Peter PR,40,21 Oct 1918,George Edward,WHITE,33,"",bachelor,Soldier,37 Canal Side,Margaret Ellen,WHITEHEAD,18,"",spinster,"",37 Canal Side,John Thomas,WHITE,Labourer,Henry James,WHITEHEAD,Labourer,Henry James,WHITEHEAD,Alice Susan,WHITEHEAD,"",1546343,CAM-WisbechStPeter-MA-1917-1923-004203685_00809

On editing screen, both witness names have been duplicated, ie witness 1 is also witness 3 & witness 2 is also witness 4.  Sorry don't know how to do a screenshot as a jpg etc

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
This is a known issue that is being addressed in the near future.

The database has actually stored multiple copies that need to be removed.

Does not affect the search

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1
