### ISSUE TITLE
uploading batch with date error (ericb)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#33]
Issue reported by **ericb** at 2014-10-21 16:20:51 UTC
Time: 2014-10-21T16:14:13+00:00
Session ID: 4125562a2ea083a2a8ed290ea439e365
Problem Page URL: [/places/53cd4994eca9ebee4f00b040](/places/53cd4994eca9ebee4f00b040)
Previous Page URL: [http://test2.freereg.org.uk/places](http://test2.freereg.org.uk/places)
Reported Issue:
I created a batch AAAWRYBA5.csv that had a deliberate date error - first record has baptised date of 2037 to check what happens to validation & Errors.

System says Batch uploaded OK.
it only has 20 or so records. So processed while I wait.
System says: Batch processed OK.
But its not where it should be ie: in WRY /ALVERTHORPE / StEric

so where has it gone to?
Is the validation gone wrong? Other bulk loaded batches show  such records in Errors lists but not this one.
Same done by Ali Hill with here ID. but file name AAAWRYBA_.csv (_ is other numbers)

Ericb

**Comment by Captainkirkdawson** [comment]
The problem is caused by date being beyond the permitted range of boxes for the range of data which is currently 2020. 
1)We need to trap the condition and avoid the failure.
2) We also need a failed upload to give an error condition to the upload.

**Comment by Captainkirkdawson** [comment]
1) The original problem has been resolved. 2)The failure is being trapped; unfortunately it occured on the first record and resulted in a null file.

**Comment by Captainkirkdawson** [comment]
Eric has confirmed bug is resolved
