### ISSUE TITLE
cosmetic (deo123)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#330]
Issue reported by **deo123** at 2015-08-03 11:46:37 UTC
Time: 2015-08-03T11:40:55+00:00
Session ID: c941154f2283d5fbc6b3d0ad7b856775
Problem Page URL: [/userid_details?page=](/userid_details?page=)
Previous Page URL: [http://freereg2.freereg.org.uk/userid_details](http://freereg2.freereg.org.uk/userid_details)
Reported Issue:
IS your spelling wrong?

Re-Activared or Re-Activated??

many thanks for all your hard work. I appreciate all the correction.

Regards Doreen    

![Screenshot](http://freereg2.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1438602397-66042-0411/re-activated.JPG)

**Comment by Captainkirkdawson** [comment]
Thank you; will get corrected next time the system is upated

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1
