### ISSUE TITLE
Looking at a UserID -"No" (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#331]
Issue reported by **REGManager** at 2015-08-03 12:32:54 UTC
Time: 2015-08-03T12:31:04+00:00
Session ID: 4b02bde9893cb6e373542cc70a7b1ab2
Problem Page URL: [/userid_details/5462b408e937907d70000159](/userid_details/5462b408e937907d70000159)
Previous Page URL: [http://freereg2.freereg.org.uk/userid_details/selection?option=Select%20specific%20userid](http://freereg2.freereg.org.uk/userid_details/selection?option=Select%20specific%20userid)
Reported Issue:
The word "No" has cropped up here.  What is it?  I have tried other UserIDs and it is not there and repeated the opening of this one.  See screenshot.
E    

![Screenshot](http://freereg2.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1438605174-66042-8968/Capture.JPG)

**Comment by Captainkirkdawson** [comment]
Bad piece of code. Will get fixed next time the system is updated.

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Captainkirkdawson** [comment]
Fixed
