### ISSUE TITLE
Missing Active Transcribers (Kyran)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#332]
Issue reported by **Kyran** at 2015-08-03 22:12:36 UTC
Time: 2015-08-03T22:10:26+00:00
Session ID: 0bcfcdecb45bf1df3fea25cbabbb19bc
Problem Page URL: [/userid_details](/userid_details)
Previous Page URL: [http://freereg2.freereg.org.uk/manage_syndicates/select_action](http://freereg2.freereg.org.uk/manage_syndicates/select_action)
Reported Issue:
there are two active transcribers missing from my list of Active transcribers - they are Pat Lawrence, UserID FlyInside & Michael Wright, UserID mikewright

According to Eric Dickens these two transcribers are listed as inactive.  This is incorrect & requires correction.  Thanks, Kyran Payne.    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
You may do that yourself.
If you go to the All Members function you will see them listed there. Go to
the Action on the right. On the line for the member you wish to activate;
click the ACT button they they will be activated.
You have full control over your members

K

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1
