### ISSUE TITLE
date error (JHarold)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#333]
Issue reported by **JHarold** at 2015-08-06 10:08:51 UTC
Time: 2015-08-06T10:07:45+00:00
Session ID: d43e58a9a4c7f519833c19c8e793a46f
Problem Page URL: [/freereg1_csv_files/55b59654f493fdc517000202/error](/freereg1_csv_files/55b59654f493fdc517000202/error)
Previous Page URL: [http://freereg2.freereg.org.uk/manage_counties/selection?option=Review%20Batches%20with%20Errors](http://freereg2.freereg.org.uk/manage_counties/selection?option=Review%20Batches%20with%20Errors)
Reported Issue:
Hi Kirk, 

these are still showing as errors - I thought you had made a change to accept that format ?

14 Feb 1599/1600

Julie    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
When was the file loaded into the system?. If it was loaded prior to the
fix the error will still be there. Simply correct the record. ie edit the
error and submit as is to have it reprocessed with the new algorithm

K

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1
