### ISSUE TITLE
Possibly incorrect coordinator (MikeNL)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#334]
Issue reported by **MikeNL** at 2015-08-07 09:39:09 UTC
Time: 2015-08-07T09:31:22+00:00
Session ID: 3e1eaf648903e0198116090ff9c221cc
Problem Page URL: [/freereg1_csv_files/54cdac89e93790802f188ce0](/freereg1_csv_files/54cdac89e93790802f188ce0)
Previous Page URL: [http://freereg2.freereg.org.uk/manage_counties/selection?option=Review%20Specific%20Batch](http://freereg2.freereg.org.uk/manage_counties/selection?option=Review%20Specific%20Batch)
Reported Issue:
This record shows the coordinator  as Jon Maxfield.

The current coordinator is me, Michael Clarke.

If the intention of this entry is to show historical information then this file was transcribed by the transcriber for Jon and this is the correct text.

If, however, the intention is to show the current coordinator, then this record points at the wrong coordinator.    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by edickens** [comment]
Hi Mike,
Kirk can confirm, but the coordinator information is saved with batch at 
the time of uploading, so it is correct.  This is the same as saving the 
name of the transcriber since the batch can get moved, but it is useful 
to know the situation at the time when the record was entered into the 
database.
Thanks Eric

**Comment by Captainkirkdawson** [comment]
Eric is correct

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Captainkirkdawson** [comment]
OK. I understand. I was just checking - it could have been something that
had been overlooked.

Kind Regards

Michael Clarke

_FreeREG Staffordshire Coordinator_

_PLEASE NOTE:_
The opinions expressed within this email represent those of the individual
and not necessarily those of FreeREG. Contents of the email may be
privileged and confidential. It may not be disclosed to or used by, anyone
other than the addressee(s), nor copied in any way. Please notify the
sender immediately if you are not the intended recipient and then delete
the email and do not disclose the contents to another person, use, copy or
store the information in any medium. .

_Full terms and conditions can be found on our website._
www.f http://www.essentiallaptoprepairs.co.uk/reereg.org.uk

**Comment by PatReynolds** [comment]
This seems to be closed.

**Comment by Captainkirkdawson** [comment]
It is
