### ISSUE TITLE
Request for the ability to search for a date (MikeNL)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#335]
Issue reported by **MikeNL** at 2015-08-07 09:43:11 UTC
Time: 2015-08-07T09:41:58+00:00
Session ID: 3e1eaf648903e0198116090ff9c221cc
Problem Page URL: [/freereg1_csv_entries?_method=get&authenticity_token=qTWnO1DoKgciOqldiI9N7xa5YtdZuhOl4eZuX0LNApE%3D&page=49](/freereg1_csv_entries?_method=get&authenticity_token=qTWnO1DoKgciOqldiI9N7xa5YtdZuhOl4eZuX0LNApE%3D&page=49)
Previous Page URL: [http://freereg2.freereg.org.uk/freereg1_csv_entries?_method=get&authenticity_token=qTWnO1DoKgciOqldiI9N7xa5YtdZuhOl4eZuX0LNApE%3D&page=50](http://freereg2.freereg.org.uk/freereg1_csv_entries?_method=get&authenticity_token=qTWnO1DoKgciOqldiI9N7xa5YtdZuhOl4eZuX0LNApE%3D&page=50)
Reported Issue:

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Use the search engine to located the record number
