### ISSUE TITLE
Request for the ability to search this file for specific information. (MikeNL)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#336]
Issue reported by **MikeNL** at 2015-08-07 09:48:16 UTC
Time: 2015-08-07T09:43:12+00:00
Session ID: 3e1eaf648903e0198116090ff9c221cc
Problem Page URL: [/freereg1_csv_entries?_method=get&authenticity_token=qTWnO1DoKgciOqldiI9N7xa5YtdZuhOl4eZuX0LNApE%3D&page=49](/freereg1_csv_entries?_method=get&authenticity_token=qTWnO1DoKgciOqldiI9N7xa5YtdZuhOl4eZuX0LNApE%3D&page=49)
Previous Page URL: [http://freereg2.freereg.org.uk/feedbacks/new?utf8=%E2%9C%93&feedback_time=2015-08-07+09%3A41%3A58+UTC&session_id=3e1eaf648903e0198116090ff9c221cc&user_id=MikeNL&problem_page_url=%2Ffreereg1_csv_entries%3F_method%3Dget%26authenticity_token%3DqTWnO1DoKgciOqldiI9N7xa5YtdZuhOl4eZuX0LNApE%253D%26page%3D49&previous_page_url=http%3A%2F%2Ffreereg2.freereg.org.uk%2Ffreereg1_csv_entries%3F_method%3Dget%26authenticity_token%3DqTWnO1DoKgciOqldiI9N7xa5YtdZuhOl4eZuX0LNApE%253D%26page%3D50&feedback_type=issue](http://freereg2.freereg.org.uk/feedbacks/new?utf8=%E2%9C%93&feedback_time=2015-08-07+09%3A41%3A58+UTC&session_id=3e1eaf648903e0198116090ff9c221cc&user_id=MikeNL&problem_page_url=%2Ffreereg1_csv_entries%3F_method%3Dget%26authenticity_token%3DqTWnO1DoKgciOqldiI9N7xa5YtdZuhOl4eZuX0LNApE%253D%26page%3D49&previous_page_url=http%3A%2F%2Ffreereg2.freereg.org.uk%2Ffreereg1_csv_entries%3F_method%3Dget%26authenticity_token%3DqTWnO1DoKgciOqldiI9N7xa5YtdZuhOl4eZuX0LNApE%253D%26page%3D50&feedback_type=issue)
Reported Issue:
This file contains at least 2000 records.

I wish to look at a specific record (in this case the date of 18 Oct !875)
and the only way of getting to it is by going page by page for many pages, either from the first page or the last page.

This is not convenient for use by a coordinator who could be quite busy.    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by edickens** [comment]
Mike - Some reports can be sorted by clicking the column heading.  I 
don't know if this is one.  But if not, perhaps it should be.  Then you 
can sort by date and find what you want. - E

**Comment by Captainkirkdawson** [comment]
Mike

The easiest solution is to use the main search to locate the record the
record in question _while logged in_ then it will display the record
number.

Then in the batch information display select the Select page of records
option rather than Browse and enter your record number.

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Captainkirkdawson** [comment]
Solution exists
