### ISSUE TITLE
Website Problem (wendy)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#342]
Issue reported by **wendy** at 2015-08-09 23:14:49 UTC
Time: 2015-08-09T23:06:25+00:00
Session ID: 
Problem Page URL: []()
Previous Page URL: [http://freereg2.freereg.org.uk/contacts/new](http://freereg2.freereg.org.uk/contacts/new)
Reported Issue:
I love Free reg and feel bad for being critical but I have a problem with the new system . In the Scottish records and in particular the Highlands a mothers maiden new is recorded in parish baptisms. Therefore to find a persons  I would put  the maiden name into search and then look for married name in results to find siblings. This helps to pinpoint marriage and find grandparents with naming pattern. I can no longer do this making a search tedious. Could this be reinstated please.    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Wonder if she has tried the include family members option

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by edickens** [comment]
That is what I'm going to say to her.
E

---

Eric J Dickens
FreeREG Chairman
