### ISSUE TITLE
Sending reset password (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#343]
Issue reported by **REGManager** at 2015-08-10 17:57:42 UTC
Time: 2015-08-10T17:53:59+00:00
Session ID: a4d47744028dfbe3d1fabc66b03a687d
Problem Page URL: [/manage_resources/new](/manage_resources/new)
Previous Page URL: [http://freereg2.freereg.org.uk/userid_details/55c24e22f493fdbe9d00155b](http://freereg2.freereg.org.uk/userid_details/55c24e22f493fdbe9d00155b)
Reported Issue:
For the first time I have had to get someone to reset their password.  This will be needed for everyone who has registered since we started and I had to set them up.  The wording says to "Contact your coordinator", but shouldn't there be a "Forgotten password" button?
E    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
There is 
![member](https://cloud.githubusercontent.com/assets/2874694/9179392/74b607a8-3f59-11e5-82ed-eb125bfb25e5.JPG)
