### ISSUE TITLE
Remove registration link (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#344]
Issue reported by **REGManager** at 2015-08-13 05:32:14 UTC
Time: 2015-08-13T05:23:57+00:00
Session ID: 60789a62e6688954f2518ded94c647bd
Problem Page URL: [/userid_details/55cb6f0ef493fd247b001621](/userid_details/55cb6f0ef493fd247b001621)
Previous Page URL: [http://freereg2.freereg.org.uk/userid_details/selection?option=Select%20specific%20userid](http://freereg2.freereg.org.uk/userid_details/selection?option=Select%20specific%20userid)
Reported Issue:
The UserID Lholloway87 was created on 12 August with the Syndicate "Researcher" and role "Transcriber".  They have not registered in FR1.
I didn't think anyone could register in FR2.  Should I email to find out what is going on?
Also, the registration message starts "Dear Eric; (Coordinator for )" and does not quote the Syndicate, which in this case should be "Researcher".    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Remove registration link

**Comment by Captainkirkdawson** [comment]
Done; added the contact link in its place
