### ISSUE TITLE
Test3 is failing if I log in as a transcriber (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#345]
Issue reported by **REGManager** at 2015-08-14 07:46:50 UTC
Time: 2015-08-14T07:45:27+00:00
Session ID: 1443c26ae597a7cec7fec11aaa107895
Problem Page URL: [/manage_resources/new](/manage_resources/new)
Previous Page URL: [http://test3.freereg.org.uk/refinery/login](http://test3.freereg.org.uk/refinery/login)
Reported Issue:
The page is not found.  See screenshot.  But it works if I log in as REGManager.
E    

![Screenshot](http://test3.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1439538410-99812-5003/Capture.JPG)

**Comment by edickens** [comment]
Doesn't work in live Website too.  It used to.  Is this to do with Cookies.  There is no advice as to what to do.  Searching OK.

**Comment by edickens** [comment]
If after getting this error report, I do a Back then look at Contact us in the footer, I find that I am signed in.  But the Back does not show My Actions.

**Comment by Captainkirkdawson** [comment]
Transcriber access is turned off
