### ISSUE TITLE
Database contents has no breadboards (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#346]
Issue reported by **REGManager** at 2015-08-14 08:35:32 UTC
Time: 2015-08-14T08:34:22+00:00
Session ID: 90f8469c235112439427456189f209c7
Problem Page URL: [/freereg_contents/5409d48ceca9eba206226f8a/show_church](/freereg_contents/5409d48ceca9eba206226f8a/show_church)
Previous Page URL: [http://freereg2.freereg.org.uk/freereg_contents/53cd4934eca9ebee4f00065c/show_place](http://freereg2.freereg.org.uk/freereg_contents/53cd4934eca9ebee4f00065c/show_place)
Reported Issue:
Because the Database contents goes down a few levels it should have breadboards.
E    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by edickens** [comment]
I appreciate that these have the buttons to go back, but I'm getting used to using breadboards.  So we need one or the other.
E

**Comment by FreeUKGenIssues** [comment]
Bread_crumbs_!

Sorry for the correction, but I'm not sure what "breadboard" means in the
UK, but in the US it's a very large platform for wiring circuits together,
so every time I see the word I get nightmare flashbacks from my digital
logic design classes.

**Comment by edickens** [comment]
OOOps!
E

---

Eric J Dickens
FreeREG Chairman
