### ISSUE TITLE
Contact Us screen suggestions (edickens)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#347]
Issue reported by **edickens** at 2015-08-14 09:09:06 UTC
Time: 2015-08-14T08:59:41+00:00
Session ID: 81e0819ac54bc5a2ce52f14eba742289
Problem Page URL: [/contacts/new](/contacts/new)
Previous Page URL: [http://freereg2.freereg.org.uk/](http://freereg2.freereg.org.uk/)
Reported Issue:
The drop down box for the type of question could be just a bit bigger and so show all the options.  As it is, you do not know what they all are.
CCs have suggested that a volunteer should contact them first before registering, so that they know what is involved before committing themselves.  This Contact Us page would be just as good.  So if (when we reinstate the registration page) we include a button to say "Need more information first" then the volunteer can ask the CC for more information.  Similarly a button to specific Help items for volunteers.    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by PatReynolds** [comment]
The pathway
Person wants to volunteer
|
Person makes contact with specific co-ordinator / allocated co-ordinator, who discuss skills, desires, etc, and transfer to a different co-ordinator (if it turns out they really don't want to do Wales, or something)
|
Person signs up (or reason for not signing up recorded)

The main problem I can see is how to stop person delving into the Become a Transcriber pathway before they've done the 'Contact a CC' pathway. Or are you saying that the first step down the Transcriber pathway is contact, and then ....  (from what you wrote, it seemed you were talking about the contract rather than the sign-up form).

**Comment by edickens** [comment]
```
Pat,
When we put FR2 together we deliberately avoided involving the SC
before registration in order to try to automate it all.  When we get
to online data entry it should be possible for it all to be done by
the transcriber without reference to the SC.  That is why we
categorise the skill of the transcriber and match that to the
quality of the images.  Hopefully we should get loads of new
volunteers which would overwhelm the SC!
But, in practice, the volunteer needs to know more.  We often get
the question "what is involved" and others, even though the
Volunteer page http://www.freereg.org.uk/volunteers/index.shtml says
something, although it is not very good.  So the Registration page
with its associated Help needs to be a lot better.
E
_____________________________________
```

Eric J Dickens
FreeREG Chairman
    On 14/08/2015 10:43, PatReynolds wrote:

```
  The pathway
    Person wants to volunteer
    |
    Person makes contact with specific co-ordinator / allocated
    co-ordinator, who discuss skills, desires, etc, and transfer to
    a different co-ordinator (if it turns out they really don't want
    to do Wales, or something)
    |
    Person signs up (or reason for not signing up recorded)
  The main problem I can see is how to stop person delving into
    the Become a Transcriber pathway before they've done the
    'Contact a CC' pathway. Or are you saying that the first step
    down the Transcriber pathway is contact, and then .... (from
    what you wrote, it seemed you were talking about the contract
    rather than the sign-up form).
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by PatReynolds** [comment]
Thanks, Eric, that makes sense.   Do we have a task list for Alison - as 'I want to know more about what being a Transcriber involves' should be on that (if it isn't already).  Plus the sign-up process needs to have two options 'sign me up as a transcriber now!' and 'I have more questions ....:' which would first-off take the person to the additional information about being a transcriber, with an option to return to sign-up and an option to ask a question.  Should the question go to a named individual (e.g. the Engagement Officer, a random SC, the trainer), or should it be poured into the contact/forum for first passing person to answer?

**Comment by edickens** [comment]
```
I think that what we have, which is based on 15 years of FR1, should
do for starters.  Then, as transcribers come on board they will ask
questions.  That is when we need to amend the instructions or build
up a searchable FAQ.
E

On 21/08/2015 17:22, PatReynolds wrote:


  Thanks, Eric, that makes sense. Do we have a task list for
    Alison - as 'I want to know more about what being a Transcriber
    involves' should be on that (if it isn't already). Plus the
    sign-up process needs to have two options 'sign me up as a
    transcriber now!' and 'I have more questions ....:' which would
    first-off take the person to the additional information about
    being a transcriber, with an option to return to sign-up and an
    option to ask a question. Should the question go to a named
    individual (e.g. the Engagement Officer, a random SC, the
    trainer), or should it be poured into the contact/forum for
    first passing person to answer?
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by Captainkirkdawson** [comment]
I have enlarged the options box. The other comments are associated with the sign up process and are dealt with elsewhere 269 and 537

**Comment by Captainkirkdawson** [comment]
Propose to close
