### ISSUE TITLE
failure to create place: DBY/Ridgeway (ericb)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#35]
Issue reported by **ericb** at 2014-10-08 17:03:23 UTC
Time: 2014-10-08T17:01:06+00:00
Session ID: 9445437dbe405b2935e4d86b018735e6
Problem Page URL: [/manage_resources/539a6a3ceca9eb57f1000550](/manage_resources/539a6a3ceca9eb57f1000550)
Previous Page URL: [http://xanthus.freereg2.zomo.co.uk/refinery/login?](http://xanthus.freereg2.zomo.co.uk/refinery/login?)
Reported Issue:
please refer to email: Booker to Dawson 7 Oct 2014 GMT.

**Comment by Sherlock21** [comment]
Kirk

As you have closed this out, it suggests there is nothing wrong. 
so, can you offer any clues as to why creating this place name did not work for us ?

Eric

**Comment by Captainkirkdawson** [comment]
This was just the duplicate. Issue 30 which was the original is still open
and awaiting time to be looked at

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Sherlock21** [comment]
Kirk

Ahhhhh
I had not noticed there were two documents, Sorry If I sounded a bit miffed!

I will put a bit more text on to #30.

EricB
