### ISSUE TITLE
Contrast in displays needs to be increased (Heather Shave)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#350]
Issue reported by **Heather Shave** at 2015-08-15 14:39:09 UTC
Time: 2015-08-15T14:36:01+00:00
Session ID: 
Problem Page URL: []()
Previous Page URL: [http://freereg2.freereg.org.uk/contacts/new](http://freereg2.freereg.org.uk/contacts/new)
Reported Issue:
Freereg 2 is much better to search but I have a problem with the contrast. At present I do have an eye problem (cataracts) but find I can read results in the old site much easier. Can the contrast be increased for us oldies with eye problems?  Thanks.    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
See 548
