### ISSUE TITLE
This page has a spelling mistake on it (MikeNL)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#352]
Issue reported by **MikeNL** at 2015-08-16 01:09:56 UTC
Time: 2015-08-16T01:06:23+00:00
Session ID: 615c19a130810ab6789ce07f0dcce786
Problem Page URL: [/manage_resources/new](/manage_resources/new)
Previous Page URL: [http://freereg2.freereg.org.uk/manage_counties/selection?option=Places%20with%20Unapproved%20Names](http://freereg2.freereg.org.uk/manage_counties/selection?option=Places%20with%20Unapproved%20Names)
Reported Issue:
"... plan old bug..." - should this be "...plain old bug"?    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
TY Fixed

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1
