### ISSUE TITLE
Don't display selection if nothing to be selected (MikeNL)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#353]
Issue reported by **MikeNL** at 2015-08-16 01:17:03 UTC
Time: 2015-08-16T01:05:55+00:00
Session ID: 615c19a130810ab6789ce07f0dcce786
Problem Page URL: [/manage_counties/selection?option=Places%20with%20Unapproved%20Names](/manage_counties/selection?option=Places%20with%20Unapproved%20Names)
Previous Page URL: [http://freereg2.freereg.org.uk/manage_counties/select_action](http://freereg2.freereg.org.uk/manage_counties/select_action)
Reported Issue:
Either there are no unapproved places in STS which, I suppose, is possible or the system is not doing what I would expect.

I get the "Select" button which contains the down arrow. When I press this button I get a small, empty box. If there are NO unapproved place then surely it would be better to display a message stating this and NOT to give a "Select" prompt when there is nothing to select from.

If STS DOES have some unapproved places, then they did not come up on this display.

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
You have no unapproved Place names.

This is primarily due to the fact that the Data Manager "approved" a number
of the STS Place names prior to your appointment even though they did not
conform to the standards for Place naming. Perhaps you need to discuss this
with him

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by edickens** [comment]
```
Hi Kirk,

I get four unapproved for STS when logged in at REGManager.  For
example "Stafford Castle Church".

E

PS.  Have copied to Michael.
_____________________________________
```

Eric J Dickens
FreeREG Chairman
    On 16/08/2015 03:58, Kirk Dawson wrote:

```
You have no unapproved Place names.

  This is primarily due to the fact that the Data Manager "approved"
  a number
  of the STS Place names prior to your appointment even though they
  did not
  conform to the standards for Place naming. Perhaps you need to
  discuss this
  with him

  Kirk Dawson
  Fairmont Hot Springs, B.C.
  V0B 1L1

  On Sat, Aug 15, 2015 at 7:17 PM, FreeUKGenIssues
  <notifications@github.com>
  wrote:

  > Issue reported by *MikeNL* at 2015-08-16 01:17:03 UTC
  > Time: 2015-08-16T01:05:55+00:00
  > Session ID: 615c19a130810ab6789ce07f0dcce786
  > Problem Page URL:
  >
  /manage_counties/selection?option=Places%20with%20Unapproved%20Names
  > Previous Page URL:
  > http://freereg2.freereg.org.uk/manage_counties/select_action
  > Reported Issue:
  > Either there are no unapproved places in STS which, I
  suppose, is possible
  > or the system is not doing what I would expect.
  >
  > I get the "Select" button which contains the down arrow. When
  I press this
  > button I get a small, empty box. If there are NO unapproved
  place then
  > surely it would be better to display a message stating this
  and NOT to give
  > a "Select" prompt when there is nothing to select from.
  >
  > If STS DOES have some unapproved places, then they did not
  come up on this
  > display.
  >
  > [image: Screenshot]
  >
```

https://camo.githubusercontent.com/a204f2529ce3a03337dc1d560f28fbf5b37ad308/687474703a2f2f66726565726567322e667265657265672e6f72672e756b
      >
      > —
      > Reply to this email directly or view it on GitHub
      >
      https://github.com/FreeUKGen/FreeUKGenProductIssues/issues/353.
      >
      —
        Reply to this email directly or view
          it on GitHub.
