### ISSUE TITLE
Overnight update has accepted a Not Approved Place (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#354]
Issue reported by **REGManager** at 2015-08-17 06:24:48 UTC
Time: 2015-08-17T06:21:04+00:00
Session ID: 02c4d42fc752a325e08e5c05730d2140
Problem Page URL: [/places/55ceb771f493fda7ab00a437](/places/55ceb771f493fda7ab00a437)
Previous Page URL: [http://freereg2.freereg.org.uk/places?page=2](http://freereg2.freereg.org.uk/places?page=2)
Reported Issue:
The overnight update validation report has changed and reported an Unapproved Place Name but accepted the file.  See STS Dudley and attached.
Perhaps not a problem now that CCs can correct batches, and there was only one such report.
But this was not expected.    

![Screenshot](http://freereg2.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1439792688-91296-1502/Capture.JPG)

**Comment by Captainkirkdawson** [comment]
Fixed
