### ISSUE TITLE
A suggestion about the information shown in the Contact messages (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#355]
Issue reported by **REGManager** at 2015-08-17 08:01:49 UTC
Time: 2015-08-17T07:56:38+00:00
Session ID: 65da6e5aa329a4cc8042b1b3d685b1f0
Problem Page URL: [/contacts/55d139ef33045b3ad100022a](/contacts/55d139ef33045b3ad100022a)
Previous Page URL: [http://freereg2.freereg.org.uk/contacts](http://freereg2.freereg.org.uk/contacts)
Reported Issue:
In the contact messages sent out is this comment...
You may review the contact on line if you are logged into the system.
Contact 
But if I "Reply" to the sender it will include this information, but they cannot log in to see the message, so I have to delete it every time.  Perhaps just leave it out as we know that the Contacts are on the server, or use some different wording.
E    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Included as pert of #605
