### ISSUE TITLE
Create new Place name no longer works on my Mac on T3 ( this test) nor FR2. (ericb)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#356]
Issue reported by **ericb** at 2015-08-17 08:16:14 UTC
Time: 2015-08-17T08:10:30+00:00
Session ID: 0ed08c871d684f219169a051ee17bd66
Problem Page URL: [/places/new](/places/new)
Previous Page URL: [http://test3.freereg.org.uk/places](http://test3.freereg.org.uk/places)
Reported Issue:
Before Wednesday 12 Aug 2015 if functioned fine on this mac (OSX 10.6.8 with  Safari 5.1.10).
Now (Sunday 16 Aug) it will not do: Add a New Place  - see initial logon screen attached for the opening window, from which i cannot select nor move.

Same is the case on FR2.    

![Screenshot](http://test3.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1439799374-12371-9627/Create_Place_name_fails.jpg)

**Comment by Captainkirkdawson** [comment]
Form updated on rest3 for evaluation

**Comment by Sherlock21** [comment]
Yes I works now to create a new place name, without the boxes overlapping.
but can you remove one of the 2 entries for England please from the COUNTRY group

**Comment by Captainkirkdawson** [comment]
Try again

**Comment by Sherlock21** [comment]
Fine now here in T3 than you.
