### ISSUE TITLE
Website Problem (Michael Walsby)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#357]
Issue reported by **Michael Walsby** at 2015-08-17 09:04:52 UTC
Time: 2015-08-17T09:03:34+00:00
Session ID: 
Problem Page URL: []()
Previous Page URL: [http://freereg2.freereg.org.uk/contacts/new](http://freereg2.freereg.org.uk/contacts/new)
Reported Issue:
I tried to send a message but was told my e-mail address is invalid !  Why ?    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Likely because it had been entered incorrectly
