### ISSUE TITLE
IN T3, :Using Opera browser for Mac, the Region pick list for Create a New Place has duplicates in it (ericb)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#358]
Issue reported by **ericb** at 2015-08-17 10:30:09 UTC
Time: 2015-08-17T10:24:20+00:00
Session ID: 52cd4692598eb265a603a6ab2083b31e
Problem Page URL: [/places/new](/places/new)
Previous Page URL: [http://test3.freereg.org.uk/places?page=6](http://test3.freereg.org.uk/places?page=6)
Reported Issue:
creating a New Place I get the Region selection first ( correctly)
but it contains: England / Wales/ Scotland/ England/ Ireland

But the Counties picklist is not a subset of the Region ( As i thought it  used to be?)    

![Screenshot](http://test3.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
These are not linked tables.

Gueess I could do that but is it need for 1 person???
