### ISSUE TITLE
Years for Places (caroline norton)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#359]
Issue reported by **caroline norton** at 2015-08-17 08:16:19 UTC
Time: 2015-08-17T07:58:14+00:00
Session ID: 
Problem Page URL: []()
Previous Page URL: [http://freereg2.freereg.org.uk/contacts/new](http://freereg2.freereg.org.uk/contacts/new)
Reported Issue:
HI FreeREG,

Perhaps I've missed something ... but on this new site, there appears not to be a means of readily seeing which years are included for which places (other than by places individually, but only as "Anytown : 200 records in total"). The at-a-glance county/parish/years listings broken down by baptisms/marriages/burials on the old site were very useful. 

Half the battle the researcher faces is finding out which places/years are or are not included in a "collection" in order to evaluate the list of results. Can a county-by-county chart of places with relevant baptism/marriage/burial coverage be included somewhere on the otherwise excellent new website.

Thanks
Caroline Norton    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
See 549
