### ISSUE TITLE
Search on County

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeUKRegProductIssues#36]
EricB reported.
We have lost the ability to search on whole County.

And the place name search list is temperamental - sometimes its not there (at the start of a new search) and other times if one does Revise Search, then its there available - and if one does not notice the screen has changed, It defaults to the first placename.

**Comment by graphiclunarkid** [comment]
Depends on #293

**Comment by Captainkirkdawson** [comment]
The ability is there
