### ISSUE TITLE
Suggestion (MikeNL)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#360]
Issue reported by **MikeNL** at 2015-08-17 11:54:57 UTC
Time: 2015-08-17T11:32:09+00:00
Session ID: 6194c0d91d1aafb1eb0f80ed737e2e2b
Problem Page URL: [/manage_counties/selection?option=Review%20Batches%20with%20Errors](/manage_counties/selection?option=Review%20Batches%20with%20Errors)
Previous Page URL: [http://freereg2.freereg.org.uk/manage_counties/select_action](http://freereg2.freereg.org.uk/manage_counties/select_action)
Reported Issue:
On this screen there is a section that describes what the various colours mean. I have no idea what colour the colour "Teal" is. Could the colour names be displayed in the colours that they describe?

And also on any other screen that use a similar colour coding.    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Done
