### ISSUE TITLE
Website Problem (tony healy)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#361]
Issue reported by **tony healy** at 2015-08-17 11:13:37 UTC
Time: 2015-08-17T11:05:36+00:00
Session ID: 
Problem Page URL: []()
Previous Page URL: [http://freereg2.freereg.org.uk/contacts/new](http://freereg2.freereg.org.uk/contacts/new)
Reported Issue:
Hey guys,
              like the new website and the new features are REALLY useful. One small problem I have is using placenames in counties. After I have looked at the results for a search, and then return to the search page, I find the placenames have disappeared, though the county remains selected. I can workaround by selecting a different county and then reselecting my original county which refreshes placenames but this becomes a littles tedious after a few searches.
            Love what you do and how you do it. Keep up the GREAT work.
                                                                   Tony.    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Sherlock21** [comment]
I just tried a standard researcher  search, followed results right through to look up location on Genuki then back.[ to get rid of the genuki link its changed but not unfathomable] so Browser back navigate to search results table is as always was and the Placename is still there in the Location.
Using Revise Search the Places list that matches the original County is still there  And reuseable.

Using New Search, the Place name  table is empty awaiting the user to select a County before the place name list can be provided. - As it always was.

So It seems the Person raising this Problem does not understand the significance of "Revise the present search" and New Search - which resets all to the initial conditions.

**Comment by Captainkirkdawson** [comment]
Documentation has been changed to emphasize use of revise and new search

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Captainkirkdawson** [comment]
See #547
