### ISSUE TITLE
Data Problem (Kirk Dawson)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#362]
Issue reported by **Kirk Dawson** at 2015-05-08 19:07:46 UTC
Time: 2015-05-08T19:05:08+00:00
Session ID: 
Problem Page URL: [unknown](unknown)
Previous Page URL: [http://test3.freereg.org.uk/contacts/5510b1efe937900271aa59c1/report_error?query=554d08cfe93790419f000001](http://test3.freereg.org.uk/contacts/5510b1efe937900271aa59c1/report_error?query=554d08cfe93790419f000001)
Reported Issue:
Well the previous test did not go well. Unfortunately the test server was not set up correctly!!!! This is what I hope is the final test of an improved data record reporting process. This is from the test server. This message goes to you Julie with a copy to the Data Manager (Both EricB and Bob) The message should contain the line_id of the record in question. The link should be active and take you to the specific record on the system. If you are logged in (Hopefully active next week) then you will have a set of actions. If not there will be no actions permitted. There is also a link to the contact on the contact database that is only effective if logged in. This would contain any screenshot submitted by the reporter. A screenshot is attached. It is not relevant in content. Eric and Bob you should both be able to see the same information and your links should be active if logged in as you both do have access to the system right now. Please confirm this message is received and works as specified and I will deploy to production. I will then work on activating the corrections coordinator function that EricD has requested.     

![Screenshot](http://test3.freereg.org.uk/uploads/contact/screenshot/554d0982e93790419f000005/relic_1.JPG)

**Comment by Captainkirkdawson** [comment]
This was a test to confirm that contact issue can be converted into github issue

**Comment by Sherlock21** [comment]
Message received by normal email OK.
And I like the new position of the button  "Report Error" separated form the other buttons.

OK to go for me!
