### ISSUE TITLE
There are two non-identical versions of Newcastle-under-Lyme (MikeNL)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#363]
Issue reported by **MikeNL** at 2015-08-18 00:09:29 UTC
Time: 2015-08-18T00:06:23+00:00
Session ID: aefefbe0ea63e4fd6eca4beeb411ae3b
Problem Page URL: [/manage_counties/places?params=Newcastle-under-Lyme](/manage_counties/places?params=Newcastle-under-Lyme)
Previous Page URL: [http://freereg2.freereg.org.uk/manage_counties/selection?option=Work%20with%20Specific%20Place](http://freereg2.freereg.org.uk/manage_counties/selection?option=Work%20with%20Specific%20Place)
Reported Issue:
One of them has two churches, the other none. This is not to be confused with the place name that does NOT contain "-"    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Good catch

Fixed.

The selection was picking up a disabled place.

The one Newcastle-under-Lyme now shows only one Place (It only has one
church)

K

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Sherlock21** [comment]
The whole topic of apparent Multiple Placenames in STS needs systematically clearing.
Now the new CC  is starting to get to grips with it -with my assistance-.
some of the problem comes from a single file with 2 different spellings of the Placename.

**Comment by Captainkirkdawson** [comment]
On this case there was a bug in the select specific place that was allowing disables place names to be displayed
