### ISSUE TITLE
Dwelly's not Dwellies in Record Type (bev bonning)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#364]
Issue reported by **bev bonning** at 2015-08-18 02:10:35 UTC
Time: 2015-08-18T01:55:35+00:00
Session ID: 
Problem Page URL: []()
Previous Page URL: [http://freereg2.freereg.org.uk/contacts/new](http://freereg2.freereg.org.uk/contacts/new)
Reported Issue:
I'm only just getting around to finding things in Freereg2. 
In looking up parishes I have transcribed in the past (Somerset) I came across an unusual word.
Some of the data has come from transcribing Dwelly's Transcripts. And then I see attached to the church name - Dwellies Transcripts. 
Isn't this a mis-application of the rule for converting a singular word to plural? A proper name as in the surname Dwelly cannot be forced into such a pattern.
I found this in Somerset, Seavington St Mary, and I wonder whether this has been perpetrated through all parishes and counties where Dwelly's Transcripts have been used.    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by edickens** [comment]
Should be Dwelly's Transcript.  I think singular as it will be a Register's Type.

E

**Comment by Captainkirkdawson** [comment]
Fixed
