### ISSUE TITLE
File  Joynsonj / STSNEWBA4 shows Error in the list of files but no such error can be found (ericb)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#365]
Issue reported by **ericb** at 2015-08-18 09:09:54 UTC
Time: 2015-08-18T08:55:55+00:00
Session ID: bd7edb1cd23bc371c544173f23bd0dba
Problem Page URL: [/manage_counties/selection?_method=get&authenticity_token=0AforGPW4GWhj%2Fi252wEJVhS2vOwaDtJHeXEpvJaQ4k%3D&option=Review+Batches+by+Filename&page=18](/manage_counties/selection?_method=get&authenticity_token=0AforGPW4GWhj%2Fi252wEJVhS2vOwaDtJHeXEpvJaQ4k%3D&option=Review+Batches+by+Filename&page=18)
Previous Page URL: [http://freereg2.freereg.org.uk/manage_counties/selection?_method=get&authenticity_token=0AforGPW4GWhj%2Fi252wEJVhS2vOwaDtJHeXEpvJaQ4k%3D&option=Review+Batches+by+Filename&page=16](http://freereg2.freereg.org.uk/manage_counties/selection?_method=get&authenticity_token=0AforGPW4GWhj%2Fi252wEJVhS2vOwaDtJHeXEpvJaQ4k%3D&option=Review+Batches+by+Filename&page=16)
Reported Issue:
This single file got divided because the spelling of Place name has 2 versions as you go though the records [ upper case "Under" and lower case "under".

But one shows an Error - which I can't find under tab ER. even though its coloured red in the list of STS files.    

![Screenshot](http://freereg2.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1439888994-34119-4474/Joynsonj-STSNEWBA4.jpg)

**Comment by Captainkirkdawson** [comment]
Is this still an active issue?It is no longer listed as a file with errors so propose to close.
