### ISSUE TITLE
Create a New Place name failed. (ericb)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#368]
Issue reported by **ericb** at 2015-08-19 20:44:52 UTC
Time: 2015-08-19T20:42:33+00:00
Session ID: e8e4127c45f7707f7289fe82fcc0c179
Problem Page URL: [/places](/places)
Previous Page URL: [http://freereg2.freereg.org.uk/places/new](http://freereg2.freereg.org.uk/places/new)
Reported Issue:

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Sherlock21** [comment]
Scrap this one please - my error - i clicked "submit" by accident, before I had entered the Placename.
