### ISSUE TITLE
Min & max date range not changing when date corrected (MaryKay)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#369]
Issue reported by **MaryKay** at 2015-08-20 11:32:28 UTC
Time: 2015-08-20T11:23:18+00:00
Session ID: 0174631895d7a0cc55e42c4c5bb1f2e4
Problem Page URL: [/freereg1_csv_files/5463b159e937904abb03d5a0](/freereg1_csv_files/5463b159e937904abb03d5a0)
Previous Page URL: [http://freereg2.freereg.org.uk/registers/5474736fe93790c32f000002](http://freereg2.freereg.org.uk/registers/5474736fe93790c32f000002)
Reported Issue:
Yesterday I edited a record in this file, changing the year from 1660 to something within the range 1608-1618.  The edit was said to be successful and a lock applied to prevent overwriting.  When I checked the date range after this edit, the maximum date still showed 1660 not 1618
I checked the date range of the file again just now and the max of the range is still 1660.  I've downloaded the file into WinReg and sorted on the dates to check I've not missed another incorrectly dated record.

I've changed 'wrong' dates affecting the range in at least one other file and this has been correctly reflected in the range

I've no idea how to produce a screen shot in the formats your accepting so cannot submit one    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
On an edit correction the range was not being recomputed. Fixed
