### ISSUE TITLE
Website Problem (bev bonning)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#370]
Issue reported by **bev bonning** at 2015-08-20 11:34:33 UTC
Time: 2015-08-20T11:31:53+00:00
Session ID: 
Problem Page URL: []()
Previous Page URL: [http://freereg2.freereg.org.uk/contacts/new](http://freereg2.freereg.org.uk/contacts/new)
Reported Issue:
In the tables showing the decades that have been transcribed, is the final in the list really meant to be 1910 - 2029?    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
This is repeated in 372
