### ISSUE TITLE
Min and max date range incorrect (MaryKay)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#371]
Issue reported by **MaryKay** at 2015-08-20 11:41:52 UTC
Time: 2015-08-20T11:35:16+00:00
Session ID: 0174631895d7a0cc55e42c4c5bb1f2e4
Problem Page URL: [/freereg1_csv_files/5463b162e937904abb04031f](/freereg1_csv_files/5463b162e937904abb04031f)
Previous Page URL: [http://freereg2.freereg.org.uk/registers/5474736fe93790c32f000002](http://freereg2.freereg.org.uk/registers/5474736fe93790c32f000002)
Reported Issue:
The date range shown on the 'summary' sheet for BDFAMPBA6.CSV shows 1656-1656.  

On viewing the records they start at 1653 and the last one is June 1657

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Issue is caused by there being just 1 baptism in the batch. It is 1656 All of the other records are birth dates. Information is calculated on Baptism, Burial and Marriage dates.

**Comment by PatReynolds** [comment]
This sounds like a FAQ/documentation issue.

Is Alison now getting these emails?

Best wishes,

Pat

On Thursday, 24 September 2015, Kirk Dawson notifications@github.com
wrote:

> Issue is caused by there being just 1 baptism in the batch. It is 1656 All
> of the other records are birth dates. Information is calculated on Baptism,
> Burial and Marriage dates.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/FreeUKGen/FreeUKGenProductIssues/issues/371#issuecomment-143041262
> .

## 

_\- -_

_Dr Pat Reynolds_
Executive Director
Free UK Genealogy  http://www.freeukgenealogy.org.uk/
A charity registered in England and Wales, number 1096940

​+44 ​1904 541411​ +44 7943 145387

36 Albemarle Road, York, YO23 1ER, UK
