### ISSUE TITLE
Decade range description (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#372]
Issue reported by **REGManager** at 2015-08-20 11:43:50 UTC
Time: 2015-08-20T11:40:27+00:00
Session ID: 53fa74562127b85efce088e06071e9d3
Problem Page URL: [/contacts/55d5bb49f4040bdc190009c7](/contacts/55d5bb49f4040bdc190009c7)
Previous Page URL: [http://freereg2.freereg.org.uk/contacts](http://freereg2.freereg.org.uk/contacts)
Reported Issue:
Bev Bonning's Contact, which I can't convert to an issue as it says "Something has gone wrong".  So see attached.
I have suggested...
Perhaps the limit decade ranges should just be Post-1910, just as the first should be Pre-1539.    

![Screenshot](http://freereg2.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1440071030-67715-5587/Capture.JPG)

**Comment by PatReynolds** [comment]
The screenshot isn't visible to me on github - not sure why! Can others see
it?

Best wishes,

Pat

_\- -_

_Dr Pat Reynolds_
Executive Director
Free UK Genealogy  http://www.freeukgenealogy.org.uk/
A charity registered in England and Wales, number 1096940

​+44 ​1904 541411​ +44 7943 145387

36 Albemarle Road, York, YO23 1ER, UK

**Comment by edickens** [comment]
I just get "Not found".
E

---

Eric J Dickens
FreeREG Chairman

**Comment by Captainkirkdawson** [comment]
As stated previously there is no need to create a Github issue for a
contact that has a been submitted with a subject of Website Problem that is
done automatically.

A screen shot that is submitted directly into Github is displayed in Github.

A screenshot that is submitted as part of the FR2 Feedback process is
visible within that process.  It is not transferred to Github. That clearly
is a feature that needs to be added.

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Captainkirkdawson** [comment]
PS
The code to convert a contact to an issue has been corrected but not deployed. I have not had the time. Too many alligators and issues.

**Comment by edickens** [comment]
Here is the screen print as requested.
![capture](https://cloud.githubusercontent.com/assets/8876165/10160551/3204f856-6696-11e5-8995-009299c2f423.JPG)

**Comment by edickens** [comment]
Here is the screen shot as requested.  E
![capture](https://cloud.githubusercontent.com/assets/8876165/10160576/633502a4-6696-11e5-93ac-0602eaf8525d.JPG)

**Comment by Captainkirkdawson** [comment]
Since we are now in the decade of the 2020s an end of 2029 is now appropriate

**Comment by edickens** [comment]
But what about in 10 years time!
