### ISSUE TITLE
Editing of UserID say OK but not done (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#373]
Issue reported by **REGManager** at 2015-08-20 14:29:09 UTC
Time: 2015-08-20T14:24:59+00:00
Session ID: e264383e054fcab88925697af7e0b06f
Problem Page URL: [/userid_details/55cb3fc2f493fd247b000ecb](/userid_details/55cb3fc2f493fd247b000ecb)
Previous Page URL: [http://freereg2.freereg.org.uk/userid_details/55cb3fc2f493fd247b000ecb/edit](http://freereg2.freereg.org.uk/userid_details/55cb3fc2f493fd247b000ecb/edit)
Reported Issue:
I have had a lot of attempts to edit the Syndicate to LEI and the email address of this UserID diversue.  It says Updated OK, but the changes have not been done.  I have done another UserID AnitaY just now and that worked.  I cannot see what is wrong.
E    

![Screenshot](http://freereg2.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1440080949-67731-4430/Capture.JPG)

**Comment by Captainkirkdawson** [comment]
Cannot duplicate, Just did it with no problem

**Comment by edickens** [comment]
```
And now I have updated the email address, no problem.  Weird.  But
close now.
E
_____________________________________
```

Eric J Dickens
FreeREG Chairman
    On 20/08/2015 15:37, Kirk Dawson wrote:

```
  Cannot duplicate, Just did it with no problem
  —
    Reply to this email directly or view
      it on GitHub.
```
