### ISSUE TITLE
"Details" Lookup link to one PLacename then leave wrong trail which falsely tags to next lookup. (ericb)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#374]
Issue reported by **ericb** at 2015-08-21 09:50:30 UTC
Time: 2015-08-21T09:37:59+00:00
Session ID: d0053a0207b5b2b273344c6558bcd42c
Problem Page URL: [/freereg_contents/53cd4995eca9ebee4f00b234/show_place](/freereg_contents/53cd4995eca9ebee4f00b234/show_place)
Previous Page URL: [http://freereg2.freereg.org.uk/search_records/5510bfd7e937900ae8bf9f28?search_id=55d6f16ff493fd569500075f](http://freereg2.freereg.org.uk/search_records/5510bfd7e937900ae8bf9f28?search_id=55d6f16ff493fd569500075f)
Reported Issue:
I did a search on STS Newcastle-under-Lyme to check out the effect of the GRO records there.
Followed Details link, and then clicked on the Place  name to see where it went.

Got a story about the CC and this group's policy etc. - see top half of the attached screen print.
Then  ditched this session of Search, and got a fresh browser connection and did a second search. this time for a different  County ( WRY / Dewsbury) and surname:Fisher / baptisms again. to see this  style of info about the County.
The result was: to show the details of the WRY search correctly, but The Info data is the same STS info. - ie wherever that STS data is saved, it is not cleared on leaving the Search which created it.  - Thus giving the completely wrong info to the searcher.

In this case, it is obvious there is a data error. [ and i was doing an experiment anyway] B:UT the cross- mixing of information may not be so obvious to the general user, and give false information that's not immediately obvious.

Obviously If I clear my caches and browser history between each search, this may get rid of the stored (wrong) info. but that's not the right solution.       

![Screenshot](http://freereg2.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1440150630-17274-4673/WRY_search_details_page.jpg)

**Comment by Sherlock21** [comment]
The issue is worse than above. its not a  'carry over' matter as a virgin search on surname + date range + Baptism ONLY - ie no County or Place - appears to return a "normal' result, but drilling on detail, goes to the proper detail but under a rogue header nothing to do with any of the researcher's previous places visited in a search this day.

**Comment by Captainkirkdawson** [comment]
Fixed
