### ISSUE TITLE
Display of search Results - use individual field for Register Type and Place  & Church Name.

### ISSUE THREAD

**Issue by Sherlock21** [FreeUKGen/FreeUKRegProductIssues#375]
To assist with handling of extra long Place names + Church name + Register name,
I suggest:-
a) use individual fields for Place name and Church name, and display these  in same column but on 2 lines - many records already have 2 lines of text from Names of participants, so it will not add much overall row height.
 b) use an individual column  for what is presently called Register type in full words - but use the standard abbreviation instead.

-REASON: to counter the 'Details' column dropping of the RH end of the screen -

**Comment by Captainkirkdawson** [comment]
If churches have a reasonable length this is not an issue

**Comment by Sherlock21** [comment]
So what does thins mean then Gentlemen?
Its is scrapped?
or it will get done - sometime soon?

**Comment by edickens** [comment]
```
Hi EricB.  It is thought not to be necessary now that the very long
Church names have been shortened.  EricD
_____________________________________
```

Eric J Dickens
FreeREG Chairman
    On 24/09/2015 19:17, Sherlock21 wrote:

```
  So what does thins mean then Gentlemen?
    Its is scrapped?
    or it will get done - sometime soon?
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by Sherlock21** [comment]
In which case then, we should set a limit to the number of chars in a church name. I have some in York which are a bit long
eg: Place  = York
church name examples:-
St Lawrence- Without Walmsgate
St Michael cum Gregory- Michlegate
St Mary Bishopgate the Younger

using up to 34 chars so far

this style of including the district name resolves the duplicates

And I am intending to apply this to all the larger place names where the "districts" are not really Place names in themselves. like Birmingham.

**Comment by edickens** [comment]
```
Why can't the Church name wrap-around after a set number of
characters?  E
_____________________________________
```

Eric J Dickens
FreeREG Chairman
    On 25/09/2015 11:08, Sherlock21 wrote:

```
In which case then, we should set a limit to the
  number of chars in a church name. I have some in York which are a
  bit long
  eg: Place = York
  church name examples:-
  St Lawrence- Without Walmsgate
  St Michael cum Gregory- Michlegate
  St Mary Bishopgate the Younger

  using up to 34 chars so far

  this style of including the district name resolves the duplicates

  And I am intending to apply this to all the larger place names
  where the "districts" are not really Place names in themselves.
  like Birmingham.


  On 24 Sep 2015, at 22:24, Eric Dickens wrote:

  > 
  > 
  > 
  > 
  > 
  > Hi EricB. It is thought not to be necessary now that the very
  long
  > Church names have been shortened. EricD
  > _____________________________________
  > Eric J Dickens
  > FreeREG Chairman
  > On 24/09/2015 19:17, Sherlock21 wrote:
  > 
  > 
  > So what does thins mean then Gentlemen?
  > Its is scrapped?
  > or it will get done - sometime soon?
  > —
  > Reply to this email directly or view
  > it on GitHub.
  > —
  > Reply to this email directly or view it on GitHub.
  > 

  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by Sherlock21** [comment]
Well I suppose it amount to work load. If a solution which involves NO code changes can be found, then that must be more welcome over the pond, than one which does need coding??
I would not want wrap-round if it involves splitting words. But otherwise OK - but when i put in such a request some long time ago, for break the Place / Church name / register type string at the "/" then that got vetoed.

The later suggestion of mine, to limit the number of characters would be easy to implement as we move into church name code table & verification. So long as the coders tell me what the name limit is. IT only arose in the first place due to accommodating STS and their GRO records contrived Place /names + church /names essays,

**Comment by EmJayFry** [comment]
On 28 Sep 2015 5:19 PM, Sherlock21 wrote:

> Well I suppose it amount to work load. If a solution which involves NO code
> changes can be found, then that must be more welcome over the pond, than one
> which does need coding??
> I would not want wrap-round if it involves splitting words. But otherwise OK -
> but when i put in such a request some long time ago, for break the Place /
> Church name / register type string at the "/" then that got vetoed.
> 
> The later suggestion of mine, to limit the number of characters would be easy to
> implement as we move into church name code table & verification. So long as the
> coders tell me what the name limit is. IT only arose in the first place due to
> accommodating STS and their GRO records contrived Place /names + church /names
> essays,

Can't we do what Microsoft do with long strings that won't fit in the field?

They truncate from the middle until the string fits. Then they allow the mouse 
to hover over the field and display the full string.

## 

Regards,
Mike Fry (Jhb)
