### ISSUE TITLE
Testing T3 uploading file to another ID FAILED (ericb)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#376]
Issue reported by **ericb** at 2015-08-24 09:39:32 UTC
Time: 2015-08-24T09:34:38+00:00
Session ID: 89fe66b06b636fc7b85028423f909d22
Problem Page URL: [/csvfiles/new](/csvfiles/new)
Previous Page URL: [http://test3.freereg.org.uk/manage_counties/select_action](http://test3.freereg.org.uk/manage_counties/select_action)
Reported Issue:
Tried upload a file to another ID
using ABD/ Alsibk as destination

file is WRYDEWBA92.csv
county in file is WRY
Place is Dewsbury 
church All SaintsTR

Deliberately sen it to a different county ABD to see the result - expected it to get rejected after upload, rather than during upload.    

![Screenshot](http://test3.freereg.org.uk)

**Comment by Sherlock21** [comment]
I expected it to fail, as I had not got the county match between the file data and the Destination. But I did not expect it to get rejected  during the Upload, by  a message saying: oops something went wrong.... etc.
was my expectation wrong? or the process?

**Comment by Captainkirkdawson** [comment]
The failure arose from not selecting a file for the upload. My test for this situation was inadequate. A new trap for this condition has been applied.
