### ISSUE TITLE
Query: colour coded header at top of a list of batches (ericb)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#377]
Issue reported by **ericb** at 2015-08-24 10:07:53 UTC
Time: 2015-08-24T10:01:40+00:00
Session ID: 89fe66b06b636fc7b85028423f909d22
Problem Page URL: [/manage_counties/selection?option=Review%20Batches%20by%20Most%20Recent%20Date%20of%20Change](/manage_counties/selection?option=Review%20Batches%20by%20Most%20Recent%20Date%20of%20Change)
Previous Page URL: [http://test3.freereg.org.uk/manage_counties/select_action](http://test3.freereg.org.uk/manage_counties/select_action)
Reported Issue:
The header at the top of a County list of batches where it defined status  by colour. has Orange with the title: not Processed.

But its not clear if this is Not yet processed because its awaiting the job to run overnight, OR its never going to get processed for some reason that's not mentioned?
Would: Waiting Processing be better words?    

![Screenshot](http://test3.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Well its definitely not waiting to be processed.

So possibly the title should be " Not in Database"

**Comment by Captainkirkdawson** [comment]
Have changed text to Just Verified
