### ISSUE TITLE
Trying to use unacceptable search criteria (Joan Ann Powell)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#378]
Issue reported by **Joan Ann Powell** at 2015-08-25 04:37:41 UTC
Time: 2015-08-25T04:35:21+00:00
Session ID: 
Problem Page URL: []()
Previous Page URL: [http://freereg2.freereg.org.uk/contacts/new](http://freereg2.freereg.org.uk/contacts/new)
Reported Issue:
Hi, I can't get the site to work properly. It might be me? Every time I enter either Yorkshire or combined three ridings of Yorkshire and complete the rest of the form correctly, I receive an error message saying that I must enter a Place. Can you please help?    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Joan

Sorry for the delay in responding.

The only time you must select a Place is when you have selected the Nearby
Places option.

But you cannot select multiple counties and at the same time select a Place.

If you want to search Yorkshire which is a combination of 3 counties. You
cannot use the nearby option.

So if you want to do a Nearby search you need to select just one county eg
Yorkshire, North Riding then you can select a starting place

If you want to search Yorkshire then do not select the Nearby option

K

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1
