### ISSUE TITLE
Website Problem (Margaret Baldry)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#379]
Issue reported by **Margaret Baldry** at 2015-08-25 19:36:18 UTC
Time: 2015-08-25T19:32:27+00:00
Session ID: 
Problem Page URL: []()
Previous Page URL: [http://freereg2.freereg.org.uk/contacts/new](http://freereg2.freereg.org.uk/contacts/new)
Reported Issue:
Hello
I'm a registered transcriber trying for the first time to log in to the new website in order to upload transcriptions.  Each time I log in I get the search page with the message Signed Out Successfully.  Have I missed something crucial?  PLease advise.
Margaret    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
By design at this time
