### ISSUE TITLE
Data Problem (Jane Roberts)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#380]
Issue reported by **Jane Roberts** at 2015-08-16 10:16:38 UTC
Time: 2015-08-16T10:15:13+00:00
Session ID: 
Problem Page URL: [unknown](unknown)
Previous Page URL: [http://freereg2.freereg.org.uk/contacts/55108207e937907e5f3702a2/report_error?query=55d0622bf493fd9ba4000d17](http://freereg2.freereg.org.uk/contacts/55108207e937907e5f3702a2/report_error?query=55d0622bf493fd9ba4000d17)
Reported Issue:
/Users/User/Desktop/Screen Shot 2015-08-16 at 11.15.05.png
The attached record is incorrect and I transcribe the records myself so I know there is a more accurate record his name was Thomas    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by edickens** [comment]
The record link does not work  There was also no attachment.  I replied..
Hi Jane,
There was no attachment by the time this email reached me.  Please provide details of the entry and I will forward it to the relevant coordinator.
Thanks,
Eric
Also, this message reached me for answering on 25/8/2015 at 22.27.
