### ISSUE TITLE
Screen does not say what it is (MikeNL)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#382]
Issue reported by **MikeNL** at 2015-08-26 07:18:32 UTC
Time: 2015-08-26T07:13:27+00:00
Session ID: e65dfc4c54612d5176a4e9497a59ba9f
Problem Page URL: [/manage_counties/selection?option=Places%20with%20Unapproved%20Names](/manage_counties/selection?option=Places%20with%20Unapproved%20Names)
Previous Page URL: [http://freereg2.freereg.org.uk/manage_counties/select_action](http://freereg2.freereg.org.uk/manage_counties/select_action)
Reported Issue:
Apart from the url, it is not possible to know that this is the "Places with unapproved names" screen.

After "processing" an unapproved name and using the browser "back one level" to get back to this screen, you cannot see what this screen is.    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Sherlock21** [comment]
This feature will soon be redundant - as soon as the Unapproved Places in STS and WAR are dealt with. SO the effort to change this little snag is not justified.
The easiest way to see the current status, after you have Resolved an Unapproved Place is to navigate back to your county start Options page, and get a fresh list of your UnApproved Place Names.

**Comment by Captainkirkdawson** [comment]
Propose to close
