### ISSUE TITLE
Funny church name after trying to relocate a batch (MikeNL)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#384]
Issue reported by **MikeNL** at 2015-08-26 14:14:23 UTC
Time: 2015-08-26T14:11:06+00:00
Session ID: e65dfc4c54612d5176a4e9497a59ba9f
Problem Page URL: [/registers/55ddc77ef493fd559e000a58](/registers/55ddc77ef493fd559e000a58)
Previous Page URL: [http://freereg2.freereg.org.uk/churches/55ddc77ef493fd559e000a57](http://freereg2.freereg.org.uk/churches/55ddc77ef493fd559e000a57)
Reported Issue:
I tried to relocate a batch online. I received a message that there were too many records to be relocated online. Now the church that was the origin for the reloation has become corrupted. "Details of the Unspecified for 5409d6a3eca9ebd28e28e4e9 in Brownhills of Staffordshire"    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Sherlock21** [comment]
I have had 2 today! ( & none ever before) where a CC asked me to get rid of a church name thats just an alphanumeric string. - one in STS and one in CON.
I have no evidence of what the CC was trying to do - but i guess trying to relocate the church somehow? 

For me to rename the church, i would  use the tool: Renaming the Place & church. but than does not work. the alphanumeric string just comes with me to the next location if the Placename is a variant of the first Placename  
The only way i did succeed on the first one, was rename Place to a temporary Place of a totally different Place name, that had no churches existing, then delete the rubbish church in the original Place name Then rename the temporary Place & Church to what i wanted the both to be. That worked fine. 
Then clear up the leftovers.
Is it a vey rare event, in which case i will put up with doing it this way?

Or if you know what caused it? are there likely loads of them and still coming?

it was:
5407d0daeca9eb81e201e6f1

or as i have to write this in here, as it wont attach the jpg file, the zero and O may be mixed.

**Comment by Sherlock21** [comment]
I just had a "help" request from the STS CC, who had managed top create one of these weird numbered church name. Said he was "trying to Relocate a "set of records" ".

May be this is how the rest got these alphanumeric Church names?

I did not remember that you had given them this facility? Is that worth a Policy review in view of the number of these events created this last few days? 
I would be better employed just doing the first job myself, than having to keep digging people out of the holes. [ No comment K!!!]

**Comment by Captainkirkdawson** [comment]
EricB is fixing

**Comment by Captainkirkdawson** [comment]
EricB is fixing
