### ISSUE TITLE
DAP improvement (Lesley Morgan)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#385]
Issue reported by **Lesley Morgan** at 2015-08-26 18:12:44 UTC
Time: 2015-08-26T18:09:22+00:00
Session ID: 
Problem Page URL: []()
Previous Page URL: [http://freereg2.freereg.org.uk/contacts/new](http://freereg2.freereg.org.uk/contacts/new)
Reported Issue:
How do I discover which (Somerset) parishes have been updated recently?  I am interested in quite a few.  On the old website I can find a list of parishes with the date of their most recent update.    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Kirk,
   What I would like to see is a “what’s new this month” item.  I don’t want to have to click through each parish that I am interested in to see if it has been updated recently.  On the old FreeReg site I could look at at list of parishes, all on one page, with the date of most recent update on the left hand side.  I might even have spotted a recently added parish that I hadn’t looked at before.
Lesley
