### ISSUE TITLE
Cookies on Ipad and Safari (Sue Kinsella)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#386]
Issue reported by **Sue Kinsella** at 2015-08-28 08:17:19 UTC
Time: 2015-08-28T08:08:06+00:00
Session ID: 
Problem Page URL: []()
Previous Page URL: [http://freereg2.freereg.org.uk/contacts/new](http://freereg2.freereg.org.uk/contacts/new)
Reported Issue:
I am writing this from the computer, as I am having problems with the site using the iPad and Safari. When I put in a search , there is a simple statement that, "this site only works if you are prepared to use cookies ". There is nothing after that, that takes you to a tick box (as per the site using Firefox) to accept cookies. You are just left hanging in the air.
Second point. When I tried to communicate via "Contact us", the page simply went to the top of the page repeating that  "this site only works if you are prepared to use cookies ".
Its a somewhat frustrating problem, but i know you guys will get onto it and fix the coding. 
Its a great site, and you do a great job.
Regards Sue Kinsella.    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Unable to duplicate

**Comment by PatReynolds** [comment]
I can't find Sue Kinsella's email, so cannot contact her to see if she still has a problem.
