### ISSUE TITLE
"Verify a batch" reporting of errors (EricD)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#387]
Issue reported by **EricD** at 2015-08-29 08:53:19 UTC
Time: 2015-08-29T08:48:27+00:00
Session ID: 0c6dca9b8034b76d71803958cfa33bc0
Problem Page URL: [/freereg1_csv_files?page=](/freereg1_csv_files?page=)
Previous Page URL: [http://test3.freereg.org.uk/freereg1_csv_files/5463cb4be9379010fc691cb0](http://test3.freereg.org.uk/freereg1_csv_files/5463cb4be9379010fc691cb0)
Reported Issue:
I tried forcing an error in a file to see what happened.  The processing worked and I had an email to say that it was successful, but no comment about there being an error.
Then on looking at the list of batches, the file appears at the top, see attached screenshot, but this does not show in Red as an Error, but looks as if it is ready for processing.  Obviously the file can be processed, but there is no indication of the error.
I think that some form or warning of an error should be shown.    

![Screenshot](http://test3.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1440838399-42886-3095/Capture.JPG)

**Comment by Captainkirkdawson** [comment]
You will see the errors by clicking either in the ER link or by displaying the batch information

**Comment by edickens** [comment]
```
Yes.  I found that, but even when I have Verified nothing says that
there are Errors and the colour on the batch list just shows as
Waiting to be processed.  Perhaps Red for errors should override
Orange Waiting for processing.

On 29/08/2015 15:41, Kirk Dawson wrote:


  You will see the errors by clicking either in the ER link or by
    displaying the batch information 
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by Captainkirkdawson** [comment]
Red overrides all unless locked when  Maroon is used
