### ISSUE TITLE
Listing of batches uploaded (EricD)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#388]
Issue reported by **EricD** at 2015-08-29 09:07:15 UTC
Time: 2015-08-29T09:05:27+00:00
Session ID: 0c6dca9b8034b76d71803958cfa33bc0
Problem Page URL: [/freereg1_csv_files/selection?option=List%20by%20Number%20of%20Errors%20then%20Filename](/freereg1_csv_files/selection?option=List%20by%20Number%20of%20Errors%20then%20Filename)
Previous Page URL: [http://test3.freereg.org.uk/freereg1_csv_files/my_own](http://test3.freereg.org.uk/freereg1_csv_files/my_own)
Reported Issue:
It will be helpful to be able to sort this report by date, most recent first, so that what has just been uploaded comes first.  More important if the User has many files.    

![Screenshot](http://test3.freereg.org.uk)

**Comment by edickens** [comment]
Cancel this.  There is a report to do list by date, but perhaps this should come first so that others do not make the same mistake that I did.

**Comment by Captainkirkdawson** [comment]
The order is irrelevant, if people don't read they will always make
mistakes.

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by PatReynolds** [comment]
Hi Alison,

For your information / possible inclusion in training materials.

Best wishes,

Pat

**Comment by Captainkirkdawson** [comment]
Pat

Alison is not a member of the GitHub repository. Hence she will never see
such a message unless you add her as a CC to the message.

From what I see Sean is not a member either

K

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1
