### ISSUE TITLE
Unwanted F1> FR2 upload case conversion (ericb)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#390]
Issue reported by **ericb** at 2015-08-29 11:42:52 UTC
Time: 2015-08-29T11:37:14+00:00
Session ID: 280a2b6f4b68edc80713af9f83067b9b
Problem Page URL: [/places](/places)
Previous Page URL: [http://freereg2.freereg.org.uk/places?page=2](http://freereg2.freereg.org.uk/places?page=2)
Reported Issue:
Please remove the bit of code which automatically changes CASE in a Church Name. Its messing things up

Could do with speedy resolution, as we are trying to work out the plan for dealing with the GRO records and how to convert/ rename them all.    

![Screenshot](http://freereg2.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1440848572-28497-5423/unwanted_CASE_conversion.jpg)

**Comment by PatReynolds** [comment]
Please bare with us: we have some capacity issues.

With best wishes,

Pat

Cc Sean as not sure if you get these.

**Comment by Captainkirkdawson** [comment]
To do this now would be an absolute disaster.

Changes to the methodology of processing church names will require
significant research and planning.

I am sure that you can find a solution that works within the current
framework.

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by edickens** [comment]
Agreed.  Tell CCs that if they do not make sure of what their 
transcribers do, then they will have to sort it out.  Should sharpen 
their minds.  As soon as we move to uploading into FR2 the problem goes 
away.  (Have not tried to see if Church is validated.  Place is.)  E

---

Eric J Dickens
FreeREG Chairman

**Comment by Captainkirkdawson** [comment]
Church is NOT validated

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1
