### ISSUE TITLE
Selecting file to upload only works now if its on my desktop (ericb)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#391]
Issue reported by **ericb** at 2015-08-29 11:53:53 UTC
Time: 2015-08-29T11:50:15+00:00
Session ID: d117df0ae4a2e1600327f431c67f8f5b
Problem Page URL: [/csvfiles](/csvfiles)
Previous Page URL: [http://test3.freereg.org.uk/csvfiles](http://test3.freereg.org.uk/csvfiles)
Reported Issue:
I thought in previous test, i selected some files from my Documents folder.
Then later I transferred the ones to my desktop as it was easier to edit and save there.

Today, i tried from my documents folder and it fails - keeps saying: "please Select file"
Same file when moved onto desktop, goes OK    

![Screenshot](http://test3.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Sorry Eric it has to be something you are doing. Its your browser/computer that is doing the navigation and opening the file.
