### ISSUE TITLE
Cookies request button does not work with IE8 (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#394]
Issue reported by **REGManager** at 2015-08-30 14:43:49 UTC
Time: 2015-08-30T14:42:34+00:00
Session ID: 788a3a143f9c21c845fa2f40d8c421e1
Problem Page URL: [/](/)
Previous Page URL: [http://freereg2.freereg.org.uk/manage_resources/new](http://freereg2.freereg.org.uk/manage_resources/new)
Reported Issue:
Message from researcher...
Found it doesn't work with Internet Explorer 8 (XP) after going to Mozilla.
Needs a note on the opening page. 
Regards 
Bob    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Really don"t understand the comment nor the heading.

What button? 
Does he mean that if he switches between browsers then the acceptance in one is not honoured by the other?  Why should it be? Cookies are stored by the browser so are independent of each other.  Nothing you do in Firefox is known by IE or any other browser.
If that is what is meant then why do we need to explain that; no one else does.
If that is not what is meant then we need far more information.

**Comment by edickens** [comment]
```
When the Cookie message comes up there is a tick box..




My understanding is that this does not work with IE8.
_____________________________________
```

Eric J Dickens
FreeREG Chairman
    On 30/08/2015 16:00, Kirk Dawson wrote:

```
  Really don"t understand the comment nor the heading.
  What button? 
    Does he mean that if he switches between browsers then the
    acceptance in one is not honoured by the other? Why should it
    be? Cookies are stored by the browser so are independent of each
    other. Nothing you do in Firefox is known by IE or any other
    browser.
    If that is what is meant then why do we need to explain that; no
    one else does.
    If that is not what is meant then we need far more information.
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by Captainkirkdawson** [comment]
Please find us a person who runs XP and IE8 to document what happens and what does not and to provide screenshots. I do not have access to those platforms

**Comment by edickens** [comment]
```
Bob Rust - robert.rust@ukgateway.net who reported the problem.

On 30/08/2015 16:28, Kirk Dawson wrote:


  Please find us a person who runs XP and IE8 to document what
    happens and what does not and to provide screenshots. I do not
    have access to those platforms
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by PatReynolds** [comment]
I have XP on a netbook several thousand miles away and could test install
ie8 in October if still wanted. BUT one of my policy suggestions is that
"we do not support operating systems which no longer have corporate
support" (that is for discussion). I was looking for a wording that
included both owned such as Microsoft and open source.

Best wishes,

Pat

**Comment by Captainkirkdawson** [comment]
I agree fully with your proposed policy position.

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Captainkirkdawson** [comment]
I have created a virtual XP machine running IE8 and confirmed that the cookie javascript will not run on that configuration.
I have also confirmed that the Application itself will not run on that configuration. due to its inability to run the chaining javascript that fills the place selection from the county selection.
Based on this evaluation I believe we should change the cookie message to include the observation that if they receive the "you need to have accepted our use of cookies" to include a statement to the effect that if you see this message and have NOT seen the Cookie Policy statement you are using  a browser that is incapable of running the application and encourage the user to use a modern browser.
The alternative is a great deal of research to support an out of date browser/platform

**Comment by PatReynolds** [comment]
100% agree, Kirk.

Best wishes,

Pat

On Monday, 31 August 2015, Kirk Dawson notifications@github.com wrote:

> I have created a virtual XP machine running IE8 and confirmed that the
> cookie javascript will not run on that configuration.
> I have also confirmed that the Application itself will not run on that
> configuration. due to its inability to run the chaining javascript that
> fills the place selection from the county selection.
> Based on this evaluation I believe we should change the cookie message to
> include the observation that if they receive the "you need to have accepted
> our use of cookies" to include a statement to the effect that if you see
> this message and have NOT seen the Cookie Policy statement you are using a
> browser that is incapable of running the application and encourage the user
> to use a modern browser.
> The alternative is a great deal of research to support an out of date
> browser/platform
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/FreeUKGen/FreeUKGenProductIssues/issues/394#issuecomment-136449739
> .

## 

_\- -_

_Dr Pat Reynolds_
Executive Director
Free UK Genealogy  http://www.freeukgenealogy.org.uk/
A charity registered in England and Wales, number 1096940

​+44 ​1904 541411​ +44 7943 145387

36 Albemarle Road, York, YO23 1ER, UK
