### ISSUE TITLE
List of Physical Files has many with no UserID or Filename (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#396]
Issue reported by **REGManager** at 2015-08-31 10:44:07 UTC
Time: 2015-08-31T10:41:01+00:00
Session ID: 73bcd37adf09bd1c085c6c6368b26c33
Problem Page URL: [/physical_files?page=13](/physical_files?page=13)
Previous Page URL: [http://freereg2.freereg.org.uk/physical_files?page=14](http://freereg2.freereg.org.uk/physical_files?page=14)
Reported Issue:
The list does not start with UserID and Filename until page 13.  What are these files?  E    

![Screenshot](http://freereg2.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1441017847-57173-9567/Capture.JPG)

**Comment by Captainkirkdawson** [comment]
Sorry Eric I have not properly deployed to production

**Comment by Captainkirkdawson** [comment]
Fixed
