### ISSUE TITLE
Files can be loaded direct into FR2 with no File/Batch name (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#397]
Issue reported by **REGManager** at 2015-08-31 11:03:57 UTC
Time: 2015-08-31T11:00:01+00:00
Session ID: 73bcd37adf09bd1c085c6c6368b26c33
Problem Page URL: [/physical_files?page=2](/physical_files?page=2)
Previous Page URL: [http://freereg2.freereg.org.uk/physical_files](http://freereg2.freereg.org.uk/physical_files)
Reported Issue:
Needs some validation to ensure at least something in the Filename.  Will this also be the Batch Name, in which case can we use something more useful?    

![Screenshot](http://freereg2.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1441019037-57173-0481/Capture.JPG)

**Comment by Captainkirkdawson** [comment]
I do not believe this to be true. You cannot upload without identifying a file with a name.

**Comment by edickens** [comment]
```
Perhaps it is just the report.  If you are sure, then no problem. 
Close this.  E

On 31/08/2015 15:32, Kirk Dawson wrote:


  I do not believe this to be true. You cannot upload without
    identifying a file with a name.
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by Captainkirkdawson** [comment]
You should try it; don't just take my word for it! I have been known to be wrong,

As said in 396 I had not completed the deployment of the Physical File changes I made last week to production so the reports are inconsistent with the database. Sorry about that but I had not expected to run into availability issues
