### ISSUE TITLE
Relocating batch does not allow church name to be created in new location (ericb)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#398]
Issue reported by **ericb** at 2015-08-31 16:01:14 UTC
Time: 2015-08-31T15:54:20+00:00
Session ID: 83d946e20b27b3e167e132172c757942
Problem Page URL: [/freereg1_csv_files/update_churches?place=53cd4984eca9ebee4f0094ea](/freereg1_csv_files/update_churches?place=53cd4984eca9ebee4f0094ea)
Previous Page URL: [http://freereg2.freereg.org.uk/freereg1_csv_files/update_places?county=Staffordshire](http://freereg2.freereg.org.uk/freereg1_csv_files/update_places?county=Staffordshire)
Reported Issue:
Relocating Batch from Place name: STS/ "Sedgley, Staffs" into STS / Sedgley

(Batch is for church name Christchurch)
There are already 2 churches in the target location, and these come up in the church names field
but  I need to type in the Church: Christchurch and the app wont let me here. 

I have only needed to add a cburch name if there were none before (I think). otherwise pick from the list has satisfied what I needed to do.    

![Screenshot](http://freereg2.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1441036874-57176-1725/Christchurch.jpg)

**Comment by Captainkirkdawson** [comment]
Why not create it first? Then you will be able to select

**Comment by edickens** [comment]
```
As a basic principle I would like to see all CCs creating Churches,
Register Types and eventually Batch Headers, with range of years,
prior to transcribing.  All uploads would be validated against
these, and images would be assigned to the Batches.  Allocation to
Transcribers would then be at Batch level.   But that is a long way
off, although we could work towards it.  E
_____________________________________
```

Eric J Dickens
FreeREG Chairman
    On 31/08/2015 18:28, Kirk Dawson wrote:

```
  Why not create it first? Then you will be able to select
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by PatReynolds** [comment]
That is what I would like to see us work towards. In the meantime, can the
instructions say this is what should happen, although transcribers still
have this function?

Best wishes,

Pat
