### ISSUE TITLE
Data Problem (Richard Graham)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#399]
Issue reported by **Richard Graham** at 2015-08-31 20:01:33 UTC
Time: 2015-08-31T19:59:20+00:00
Session ID: 
Problem Page URL: [unknown](unknown)
Previous Page URL: [http://freereg2.freereg.org.uk/contacts/551097e1e93790f8ad74e20a/report_error?query=55e4aff4f493fd2066001bba](http://freereg2.freereg.org.uk/contacts/551097e1e93790f8ad74e20a/report_error?query=55e4aff4f493fd2066001bba)
Reported Issue:
Enter text here..Nani Picton b. 25 Jan 1823 should read Naomi Picton    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by edickens** [comment]
Another email...

Correction – Nani is on the original record and therefore corect

Apologies
Richard Graham
