### ISSUE TITLE
Last amended date not updated (MikeNL)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#400]
Issue reported by **MikeNL** at 2015-09-01 10:31:35 UTC
Time: 2015-09-01T10:29:27+00:00
Session ID: 560937d53f90b78ea6577a26022d5c24
Problem Page URL: [/churches/5409cddfeca9eba2060cb885](/churches/5409cddfeca9eba2060cb885)
Previous Page URL: [http://freereg2.freereg.org.uk/places](http://freereg2.freereg.org.uk/places)
Reported Issue:
After adding web address and other things to this church the Last Amended date remained as 14 Feb     

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Miss understanding of field. It is the last date a record/search entry was amended. New text added
