### ISSUE TITLE
Possible improvement to wording (Church in Parish of County) (MikeNL)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#401]
Priority  10 (0	1	2	7)

Issue reported by **MikeNL** at 2015-09-01 10:36:51 UTC
Time: 2015-09-01T10:31:42+00:00
Session ID: 560937d53f90b78ea6577a26022d5c24
Problem Page URL: [/churches/5409cddfeca9eba2060cb885](/churches/5409cddfeca9eba2060cb885)
Previous Page URL: [http://freereg2.freereg.org.uk/feedbacks/new?utf8=%E2%9C%93&feedback_time=2015-09-01+10%3A29%3A27+UTC&session_id=560937d53f90b78ea6577a26022d5c24&user_id=MikeNL&problem_page_url=%2Fchurches%2F5409cddfeca9eba2060cb885&previous_page_url=http%3A%2F%2Ffreereg2.freereg.org.uk%2Fplaces&feedback_type=issue](http://freereg2.freereg.org.uk/feedbacks/new?utf8=%E2%9C%93&feedback_time=2015-09-01+10%3A29%3A27+UTC&session_id=560937d53f90b78ea6577a26022d5c24&user_id=MikeNL&problem_page_url=%2Fchurches%2F5409cddfeca9eba2060cb885&previous_page_url=http%3A%2F%2Ffreereg2.freereg.org.uk%2Fplaces&feedback_type=issue)
Reported Issue:
The current wording is "St Nicholas in Abbots Bromley of Staffordshire". Does "St Nicholas in Abbots Bromley within Staffordshire" sound better?

This occurs on many different screens.

If this is not acceptable, I think "in" is better than "of"    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by PatReynolds** [comment]
I agree - 'within Orkney' or other islands isn't quite correct, but neither is 'in Orkney' nor 'of Orkney'.

**Comment by AlOneill** [comment]
Why not simply a comma? Would work for counties and islands.

**Comment by Captainkirkdawson** [comment]
This applies only to internal pages.

**Comment by Captainkirkdawson** [comment]
Edit heading lines in member pages to use , as link between components of a location instead of in, of, for,  within.
How important is this?

**Comment by edickens** [comment]
```
I agree with Mike that I usually think of County/Place/Church rather
than the other way round.  So if I am looking at a details screen I
have to read it from the right.

I would like it to be "Transcriptions for the Norfolk, Acle,
Methodist Circuit, Parish Register" 

instead of...



But not urgent.  E
```

**Comment by Captainkirkdawson** [comment]
It is a 1.5 deliverable?.
As a result of this story the articles in of for within will be replaced by a comma.
The order of the location components will be reversed,
