### ISSUE TITLE
A few UserIDs may have whitespace in the name parts (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#402]
Issue reported by **REGManager** at 2015-09-02 11:49:12 UTC
Time: 2015-09-02T11:47:08+00:00
Session ID: 16cbfdcecc69db191efffc1243be3c65
Problem Page URL: [/userid_details/select?name=Hughes:Chris](/userid_details/select?name=Hughes:Chris)
Previous Page URL: [http://freereg2.freereg.org.uk/userid_details/selection?option=Select%20specific%20surname/forename](http://freereg2.freereg.org.uk/userid_details/selection?option=Select%20specific%20surname/forename)
Reported Issue:
I am logged in as REGManager and I get the full listing of names, but when I select someone it goes to Syndicate searching.  It has been working OK.  See attached.  E    

![Screenshot](http://freereg2.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1441194551-89659-6680/Capture.JPG)

**Comment by Captainkirkdawson** [comment]
You mean that when you use the Select a Userid as RegManager you do not get
a selection of all userids and when you select someone you don"t get the
correct person? What do you get instead?

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by edickens** [comment]
I get the list of Surname:firstname, but when I select someone I don't 
get them but the image that I attached.  E

---

Eric J Dickens
FreeREG Chairman

**Comment by Captainkirkdawson** [comment]
It is clear that there is no navigation issue.

I have tried a number of people at random and it displays correctly. i.e.
the profile if there is only 1 of that name and the possible userids if the
name appears multiple times.

What is happening is that Chris Hughes does not have a userid hence is not
displayed.

Now the $64,000 question is why we have Chris Hughes without a profile.

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Captainkirkdawson** [comment]
Interesting: there is a Chris Hughes
![chris](https://cloud.githubusercontent.com/assets/2874694/9637844/54bff4c2-5160-11e5-94ee-ef2de4b3de8a.JPG)
This is his profile 
![chris1](https://cloud.githubusercontent.com/assets/2874694/9637854/6a4de68c-5160-11e5-8e22-a1cd0efb016e.JPG)

**Comment by Captainkirkdawson** [comment]
OK Found it.

When the userid was created the forename was entered with a blank at the end of the forename i.e. there was a whitespace at the end of Chris  so the search which was for a Chris (without whitespace) could not find the Chris  (with  whitespace).

We removed whitespace from names on creation some months ago but there are likely one or two cases sitting in the database where the name components may have whitespace. This is not going to impact the operation of the system but will be an irritation for SCs. The solution is to scan the database for whitespace in the person name fields of userids.

**Comment by edickens** [comment]
```
I'll do that tomorrow.  I will edit the Firstname in these UserIDs. 
Easy to do with my level of access to the list of names.

E
_____________________________________
```

Eric J Dickens
FreeREG Chairman
    On 02/09/2015 18:11, Kirk Dawson wrote:

```
  OK Found it.
  When the userid was created the forename was entered with a
    blank at the end of the forename i.e. there was a whitespace at
    the end of Chris so the search which was for a Chris (without
    whitespace) could not find the Chris (with whitespace).
  We removed whitespace from names on creation some months ago
    but there are likely one or two cases sitting in the database
    where the name components may have whitespace. This is not going
    to impact the operation of the system but will be an irritation
    for SCs. The solution is to scan the database for whitespace in
    the person name fields of userids.
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by edickens** [comment]
```
Is this important now?  If I remember correctly, these have a space
on the front of their surname.  There are none of these now.  There
may be some with a space in front of their firstname, but that does
not matter as it does not affect the sequence of reports.
There is a "Blank" Name at the top if I list Profiles by name.  But
I cannot select it.  E

On 16/09/2015 15:36, Kirk Dawson wrote:


  Assigned #402 to @edickens.
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by Captainkirkdawson** [comment]
You tell me; you initiated the story. We researched it found the problem and volunteered to edit the problem people. Hence the assignment to you.
"I'll do that tomorrow.  I will edit the Firstname in these UserIDs. 
    Easy to do with my level of access to the list of names.
    E"

**Comment by edickens** [comment]
```
There was only one surname and I have done it.  E

On 17/09/2015 14:55, Kirk Dawson wrote:


  You tell me; you initiated the story. We researched it found
    the problem and volunteered to edit the problem people. Hence
    the assignment to you.
    "I'll do that tomorrow. I will edit the Firstname in these
    UserIDs. 
    Easy to do with my level of access to the list of names.
    E"
  —
    Reply to this email directly or view
      it on GitHub.
```
