### ISSUE TITLE
Website Problem (Cheryl)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#403]
Issue reported by **Cheryl** at 2015-09-02 13:16:00 UTC
Time: 2015-09-02T13:14:34+00:00
Session ID: 
Problem Page URL: []()
Previous Page URL: [http://freereg2.freereg.org.uk/contacts/new](http://freereg2.freereg.org.uk/contacts/new)
Reported Issue:
Hi I have signed up as a volunteer to transcribe and I have done my password and username and when I sign in it takes me to a page which says I have signed out.     

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Volunteers cannot currently log into FR2. System is operating correctly
