### ISSUE TITLE
Website Problem (Forrest Manning)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#404]
Issue reported by **Forrest Manning** at 2015-09-03 00:21:59 UTC
Time: 2015-09-03T00:20:14+00:00
Session ID: 
Problem Page URL: []()
Previous Page URL: [http://freereg2.freereg.org.uk/contacts/new](http://freereg2.freereg.org.uk/contacts/new)
Reported Issue:
Ringstead, Northamptonshire- list of churches:  a misspelling of church which you have as curch.    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Not a website problem
