### ISSUE TITLE
bedfordshore (bevb)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#405]
Issue reported by **bevb** at 2015-09-03 05:53:44 UTC
Time: 2015-09-03T05:49:03+00:00
Session ID: 85c6693d751a6c55fdb61772f526eb90
Problem Page URL: [/manage_syndicates/select_action](/manage_syndicates/select_action)
Previous Page URL: [http://freereg2.freereg.org.uk/manage_counties/select_action](http://freereg2.freereg.org.uk/manage_counties/select_action)
Reported Issue:
Can we fix the spelling of Bedfordshire please. Thanks.
Bev

![Screenshot](http://freereg2.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1441259624-43833-9242/bedfordshore.JPG)

**Comment by edickens** [comment]
```
Hi Bev.  Done.  Eric

On 03/09/2015 06:53, FreeUKGenIssues
  wrote:


  Issue reported by bevb at 2015-09-03 05:53:44
    UTC
    Time: 2015-09-03T05:49:03+00:00
    Session ID: 85c6693d751a6c55fdb61772f526eb90
    Problem Page URL: /manage_syndicates/select_action
    Previous Page URL: http://freereg2.freereg.org.uk/manage_counties/select_action
    Reported Issue:
    Can we fix the spelling of Bedfordshire please. Thanks.
    Bev

  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by edickens** [comment]
Thanks for all.

Bev
