### ISSUE TITLE
Test3 Uploading Report (EricD)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#406]
Issue reported by **EricD** at 2015-09-04 08:48:18 UTC
Time: 2015-09-04T08:44:40+00:00
Session ID: 7fc57536ccbb13fba483fdf9c8334b23
Problem Page URL: [/csvfiles/new](/csvfiles/new)
Previous Page URL: [http://test3.freereg.org.uk/csvfiles/new](http://test3.freereg.org.uk/csvfiles/new)
Reported Issue:
I tried uploading a file that I thought was error free but got the attached.  I need a reason so that I know what to do.
It is possible that this should have been a "Replace", but there is no option for that.  And if that is the reason, then it should say so. E    

![Screenshot](http://test3.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1441356498-23526-0323/Capture.JPG)

**Comment by Captainkirkdawson** [comment]
Message added
![eric](https://cloud.githubusercontent.com/assets/2874694/9692550/f0ca7200-5306-11e5-8862-6d5e70341304.JPG)
