### ISSUE TITLE
Physical files reporting problem (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#408]
Issue reported by **REGManager** at 2015-09-08 11:57:26 UTC
Time: 2015-09-08T11:48:16+00:00
Session ID: 47e8ce5f22c88c9900c48f393aa38431
Problem Page URL: [/physical_files/files_for_specific_userid](/physical_files/files_for_specific_userid)
Previous Page URL: [http://freereg2.freereg.org.uk/physical_files/select_action](http://freereg2.freereg.org.uk/physical_files/select_action)
Reported Issue:
The attached screenprint set of options reports "There is a problem".  The other two options work.  But I expect there are no files because this transcriber is just starting and has uploaded the first few records with the wrong place name so the file has been completely rejected.  They have done this on two consecutive days now  E    

![Screenshot](http://freereg2.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1441713446-91862-3866/Capture.JPG)

**Comment by Sherlock21** [comment]
EricD

this is not one of the STS places that have been relocated i it? I don't get the attachment
On 8 Sep 2015, at 12:57, FreeUKGenIssues wrote:

Ericb

**Comment by edickens** [comment]
```
No.  It was a WAR Exhall file.  E

On 08/09/2015 13:38, Sherlock21 wrote:

EricD

  this is not one of the STS places that have been relocated i it? I
  don't get the attachment
  On 8 Sep 2015, at 12:57, FreeUKGenIssues wrote:

  Ericb

  > Issue reported by REGManager at 2015-09-08 11:57:26 UTC
  > Time: 2015-09-08T11:48:16+00:00
  > Session ID: 47e8ce5f22c88c9900c48f393aa38431
  > Problem Page URL: /physical_files/files_for_specific_userid
  > Previous Page URL:
  http://freereg2.freereg.org.uk/physical_files/select_action
  > Reported Issue:
  > The attached screenprint set of options reports "There is a
  problem". The other two options work. But I expect there are no
  files because this transcriber is just starting and has uploaded
  the first few records with the wrong place name so the file has
  been completely rejected. They have done this on two consecutive
  days now E
  > 
  > 
  > 
  > —
  > Reply to this email directly or view it on GitHub.
  > 

  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by Sherlock21** [comment]
Would that be Exhall (Alcester) or Exhall (Coventry) which are OK, or Exhall with Wixford which is Not Approved and needs the CC to get the Transcriber to use the right Placename.

**Comment by edickens** [comment]
He just put Exhall.  I always email the CC with any overnight rejections  E

---

Eric J Dickens
FreeREG Chairman

**Comment by Captainkirkdawson** [comment]
Fixed the problem with the display. Was trying to display the date of a nil field; should not have been one but!
I note the userid is a member of the training syndicate
