### ISSUE TITLE
Having ignored Cookie search page options not refreshed (Simon Pickering)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#409]
Issue reported by **Simon Pickering** at 2015-09-09 19:14:31 UTC
Time: 2015-09-09T19:11:42+00:00
Session ID: 
Problem Page URL: []()
Previous Page URL: [http://freereg2.freereg.org.uk/contacts/new](http://freereg2.freereg.org.uk/contacts/new)
Reported Issue:
Hi,

The new cookie question could be handled better. If you don't notice it and fill the search form in although you can only get so far. When you confirm cookies, you lose any input. 

Can you either
1) disallow input until cookies confirmed or
2) keep input    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
propose to close; user should follow instructions
