### ISSUE TITLE
Empty details for userID (MikeNL)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#410]
Issue reported by **MikeNL** at 2015-09-10 09:58:30 UTC
Time: 2015-09-10T09:53:02+00:00
Session ID: a582c20704ef463c4eecb548ca15f90e
Problem Page URL: [/userid_details/select?name=jones:pamela](/userid_details/select?name=jones:pamela)
Previous Page URL: [http://freereg2.freereg.org.uk/userid_details/selection?option=Select+specific+surname%2Fforename](http://freereg2.freereg.org.uk/userid_details/selection?option=Select+specific+surname%2Fforename)
Reported Issue:
Attempting to correctly capitalise username "jones:pamela". When choosing from the drop down list, the subsequent display show no details at all.    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Problem was a trailing whitespace on the person forename

We introduced whitespace stripping some time ago but there are clearly one or two left in the system.

Name has been corrected.
