### ISSUE TITLE
Data Problem appears late and as a system issue? (Rosemary Thorburn)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#412]
Issue reported by **Rosemary Thorburn** at 2015-09-09 15:40:31 UTC
Time: 2015-09-09T15:36:31+00:00
Session ID: 
Problem Page URL: []()
Previous Page URL: [http://freereg2.freereg.org.uk/contacts](http://freereg2.freereg.org.uk/contacts)
Reported Issue:
Bride's name is Dorothy Sowler daughter of Joseph Sowler. Married to George Stephenson (widower). Marriage certificate attached. I have the original.    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by EmJayFry** [comment]
On 11 Sep 2015 10:53 AM, FreeUKGenIssues wrote:

> Issue reported by _Rosemary Thorburn_ at 2015-09-09 15:40:31 UTC
> Time: 2015-09-09T15:36:31+00:00
> Session ID:
> Problem Page URL:
> Previous Page URL: http://freereg2.freereg.org.uk/contacts
> Reported Issue:
> Bride's name is Dorothy Sowler daughter of Joseph Sowler. Married to George
> Stephenson (widower). Marriage certificate attached. I have the original.

This doesn't matter! Without being able to see the original image, researchers 
should not be questioning the transcription. There needs to be a strong 
statement (as there is on FreeBMD) that corrections and issues raised by 
researchers will be ignored unless a mis-transcription can be proved.

## 

Regards,
Mike Fry (Jhb)

**Comment by Sherlock21** [comment]
You are right,Mike.
And even if the commenter  does have access to the original image, how does our CC & Transcriber actually check the transcription if we have sent the Image back to the Lender?

**Comment by edickens** [comment]
```
The original message said "Marriage certificate attached." which is
wasn't.  There was "No screenshot attached".  So perhaps our wording
should say something about attaching a scan of any document as
evidence.

But my concern is that this message did not seem to go to the
relevant CC.  The distribution says "Copies went to all registered
system administrators: (Kirk,John,Eric,Ben,)".  It recommends that I
answer, but this seems a long way round as I now have to find out
which CC it should go to.  E


On 11/09/2015 10:22, Sherlock21 wrote:


  You are right,Mike.
    And even if the commenter does have access to the original
    image, how does our CC & Transcriber actually check the
    transcription if we have sent the Image back to the Lender?
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by Sherlock21** [comment]
Wasn't it to MikeTL of something similar?

EB

**Comment by Captainkirkdawson** [comment]
I agree with Mike we need a much clearer policy on what we accept and what we do not.
WE also need the ability for a researcher to post additional information.
There is indeed something odd about this report. It is timestamped 15:36 on 9 Sept. It did not arrive in my mailbox until 36hrs later. In addition a data problem should not come through to the system administrators

**Comment by edickens** [comment]
```
I thought (but it does not seem to be there) that in V1.4 we were
going to add some extra Actions for Researchers.  They need to
Register first so that we know that their email address is correct,
then they can...
- Add a Comment to a Record
- Ask to receive an email when a Place/Church has any records added
or amended.
- Have their favourites marked.
- Join a mailing list

These are all things that I mentioned when we planned a few years
ago.  E

On 11/09/2015 16:07, Kirk Dawson wrote:


  I agree with Mike we need a much clearer policy on what we
    accept and what we do not.
    WE also need the ability for a researcher to post additional
    information.
    There is indeed something odd about this report. It is
    timestamped 15:36 on 9 Sept. It did not arrive in my mailbox
    until 36hrs later. In addition a data problem should not come
    through to the system administrators
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by Captainkirkdawson** [comment]
Those suggested stories are not part of this issue

**Comment by PatReynolds** [comment]
At the moment, only one of these stories is on gitbhub.  Are you able to
add the rest (please add as individual stories, not a group, and tag as
1.4)?  I am not sure if I can get on to github at the moment, but will do
when I am able, if you are not?

With thanks,

Pat

On Friday, 11 September 2015, Eric Dickens notifications@github.com wrote:

> I thought (but it does not seem to be there) that in V1.4 we were
> going to add some extra Actions for Researchers.  They need to
> Register first so that we know that their email address is correct,
> then they can...
> - Add a Comment to a Record
> - Ask to receive an email when a Place/Church has any records added
>   or amended.
> - Have their favourites marked.
> - Join a mailing list
> 
> These are all things that I mentioned when we planned a few years
> ago.  E
> 
> On 11/09/2015 16:07, Kirk Dawson wrote:
> 
> I agree with Mike we need a much clearer policy on what we
> accept and what we do not.
> WE also need the ability for a researcher to post additional
> information.
> There is indeed something odd about this report. It is
> timestamped 15:36 on 9 Sept. It did not arrive in my mailbox
> until 36hrs later. In addition a data problem should not come
> through to the system administrators
> —
> Reply to this email directly or view
> it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/FreeUKGen/FreeUKGenProductIssues/issues/412#issuecomment-139575901
> .

## 

_\- -_

_Dr Pat Reynolds_
Executive Director
Free UK Genealogy  http://www.freeukgenealogy.org.uk/
A charity registered in England and Wales, number 1096940

​+44 ​1904 541411​ +44 7943 145387

36 Albemarle Road, York, YO23 1ER, UK

**Comment by PatReynolds** [comment]
Thanks, all.  Stupid question (unable to run away and look it up for
myself, as Tristanians are now at work, so no wifi here): can the
researcher see the source of the transcription under details - if so, the
directions for how-to-ask-for-a-correction should be that they need to
attach a copy of the source material.

If they can't, or if they have different source material, such as the
actual certificate, or other evidence, the message needs to be that they
need to wait until we have a new feature added, where they will be able to
sign in and add a comment.

Best wishes,

Pat


## 

_\- -_

_Dr Pat Reynolds_
Executive Director
Free UK Genealogy  http://www.freeukgenealogy.org.uk/
A charity registered in England and Wales, number 1096940

​+44 ​1904 541411​ +44 7943 145387

36 Albemarle Road, York, YO23 1ER, UK

**Comment by edickens** [comment]
```
No they can't see the original at present.  But that opens up a huge
discussion.  Are the registers in the public domain?  Are we showing
just a sample?
FreeBMD and FreeCEN will be able to.
Again a future version to enhance our service where some can be
shown and some not.
Yes, some extra wording needs to go in.  E
_____________________________________
```

Eric J Dickens
FreeREG Chairman
    On 16/09/2015 17:47, PatReynolds wrote:

```
Thanks, all. Stupid question (unable to run away and
  look it up for
  myself, as Tristanians are now at work, so no wifi here): can the
  researcher see the source of the transcription under details - if
  so, the
  directions for how-to-ask-for-a-correction should be that they
  need to
  attach a copy of the source material.

  If they can't, or if they have different source material, such as
  the
  actual certificate, or other evidence, the message needs to be
  that they
  need to wait until we have a new feature added, where they will be
  able to
  sign in and add a comment.

  Best wishes,

  Pat

  >
  >

  -- 
  *- -*

  *Dr Pat Reynolds*
  Executive Director
  Free UK Genealogy <http://www.freeukgenealogy.org.uk/>
  A charity registered in England and Wales, number 1096940

  ​+44 ​1904 541411​ +44 7943 145387

  36 Albemarle Road, York, YO23 1ER, UK
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by PatReynolds** [comment]
Hi Eric  my fault for  not being clear.  By 'source of the transcription
details' I meant text, such as 'Register of Births at St Michael's Leeds
1913-1976, Deposited at West Yorkshire Record Office by the incumbant' or
'Burial Records,, Hexam Borough Council Cemetary 1960-1980., Owned by
Northumberland County Archives' - i.e. the fields which will enable the
person to see where the record came from - and to know that the
transcription was incorrect, because they have in front of them the
original (or a copy of the original), rather than having in front of them
something which may not have the same information as the record which was
transcribed.

Best wishes,

Pat

On Wednesday, 16 September 2015, Eric Dickens notifications@github.com
wrote:

> No they can't see the original at present.  But that opens up a huge
> discussion.  Are the registers in the public domain?  Are we showing
> just a sample?
> FreeBMD and FreeCEN will be able to.
> Again a future version to enhance our service where some can be
> shown and some not.
> Yes, some extra wording needs to go in.  E
> 
> ---
> 
> Eric J Dickens
> FreeREG Chairman
> On 16/09/2015 17:47, PatReynolds wrote:
> 
> Thanks, all. Stupid question (unable to run away and
> look it up for
> myself, as Tristanians are now at work, so no wifi here): can the
> researcher see the source of the transcription under details - if
> so, the
> directions for how-to-ask-for-a-correction should be that they
> need to
> attach a copy of the source material.
> 
> If they can't, or if they have different source material, such as
> the
> actual certificate, or other evidence, the message needs to be
> that they
> need to wait until we have a new feature added, where they will be
> able to
> sign in and add a comment.
> 
> Best wishes,
> 
> Pat
> 
> 
> ## 
> 
> _\- -_
> 
> _Dr Pat Reynolds_
> Executive Director
> Free UK Genealogy http://www.freeukgenealogy.org.uk/
> A charity registered in England and Wales, number 1096940
> 
> ​+44 ​1904 541411​ +44 7943 145387
> 
> 36 Albemarle Road, York, YO23 1ER, UK
> —
> Reply to this email directly or view
> it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/FreeUKGen/FreeUKGenProductIssues/issues/412#issuecomment-140910652
> .

## 

_\- -_

_Dr Pat Reynolds_
Executive Director
Free UK Genealogy  http://www.freeukgenealogy.org.uk/
A charity registered in England and Wales, number 1096940

​+44 ​1904 541411​ +44 7943 145387

36 Albemarle Road, York, YO23 1ER, UK

**Comment by edickens** [comment]
Understood now.
I think the ancillary information and links to GENUKI etc. need some 
improvement.  But that must be the last job.  We did not have in FR1 
anything like we already have in FR2.  E

**Comment by Captainkirkdawson** [comment]
WE have many fields already defined it FR2 to provide information on source and related matters. More can be added if required. Since this information never existed in FR1 the fields need entry information added.
![register](https://cloud.githubusercontent.com/assets/2874694/9948291/092b06b8-5d5f-11e5-9dde-5cdb51d33b8f.JPG)

**Comment by Captainkirkdawson** [comment]
Close this specific issue as it was a data issue. Raised separate issues on policy and process 581/582/583
