### ISSUE TITLE
put the userid at the front of the filename (was Request for enhancement) (MikeNL)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#413]
Issue reported by **MikeNL** at 2015-09-11 11:09:35 UTC
Time: 2015-09-11T10:26:00+00:00
Session ID: ac5b07270ac848178eb3056ab399656d
Problem Page URL: [/freereg1_csv_files/55ef8a59f493fde17c00366f](/freereg1_csv_files/55ef8a59f493fde17c00366f)
Previous Page URL: [http://freereg2.freereg.org.uk/registers/5407e257eca9eb1ee028088e](http://freereg2.freereg.org.uk/registers/5407e257eca9eb1ee028088e)
Reported Issue:
Would it be possible to put the userid at the front of the filename. This would certainly be useful for looking at different userid's that contain the same filename, possibly for comparison etc.    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Implemented
