### ISSUE TITLE
Church name changes between F1 and FR2 in upload (ericb)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#414]
Issue reported by **ericb** at 2015-09-11 12:13:01 UTC
Time: 2015-09-11T12:06:55+00:00
Session ID: 9df2dacd20645af9015baa85bdd6d73c
Problem Page URL: [/places?page=5](/places?page=5)
Previous Page URL: [http://freereg2.freereg.org.uk/places?page=3](http://freereg2.freereg.org.uk/places?page=3)
Reported Issue:
A file in F1 for SAL. Clunbury/ St. Swithin

becomes in FR2 SAL/ Clunbury/ St Swith1n. 
Yes, the name in F1 should be St without the stop BUt its the appearance of the digit "1" replacing letter "i' in SWITHIN which is the concern
snip from FR2 attached. note file uploaded 11 Sept 2015.

CC assures me it is correct at source in F1 as SWITHIN ( i have no F1 access to check)    

![Screenshot](http://freereg2.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1441973581-82528-7095/Swithin.jpg)

**Comment by edickens** [comment]
```
Yes, the file is correct and spelt "St Swithins" in FR1.

But what is unusual is that these files have not been amended but
just moved from one UserID "deo123"  to another "LynneK".  Also, I
believe that Church is not a case sensitive match now, so perhaps
this would cause the match if "St Swith1ns" had been created earlier
and not deleted when the entry was corrected.

Both versions of the Church show the same batches with the same
contents including the From and Too UserIDs of the move.

E
_____________________________________
```

Eric J Dickens
FreeREG Chairman
    On 11/09/2015 13:13, FreeUKGenIssues
      wrote:

```
  Issue reported by ericb at 2015-09-11
    12:13:01 UTC
    Time: 2015-09-11T12:06:55+00:00
    Session ID: 9df2dacd20645af9015baa85bdd6d73c
    Problem Page URL: /places?page=5
    Previous Page URL: http://freereg2.freereg.org.uk/places?page=3
    Reported Issue:
    A file in F1 for SAL. Clunbury/ St. Swithin
  becomes in FR2 SAL/ Clunbury/ St Swith1n. 
    Yes, the name in F1 should be St without the stop BUt its the
    appearance of the digit "1" replacing letter "i' in SWITHIN
    which is the concern
    snip from FR2 attached. note file uploaded 11 Sept 2015.
  CC assures me it is correct at source in F1 as SWITHIN ( i have
    no F1 access to check) 

  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by Sherlock21** [comment]
So is this another example of the same file  multiplying  itself - as with the jonny ones in STS that were mentioned earlier?

do we need a major investigation?
Eb

**Comment by Captainkirkdawson** [comment]
St Swith1n has 6 files. So does St Swithin
![st swithin](https://cloud.githubusercontent.com/assets/2874694/9824872/050eca1e-588d-11e5-9df4-00ef5af136c5.JPG)
![st swith n](https://cloud.githubusercontent.com/assets/2874694/9824873/0a9ae292-588d-11e5-846c-9a0cb0f63fc0.JPG)

**Comment by Captainkirkdawson** [comment]
It will take me at least a day or more of dedicated time to research this stated issue. Shoild it be done?

**Comment by edickens** [comment]
```
Kirk - Wait until we have done the deletes, because this example had
duplicates which could be confusing the issue.  E
_____________________________________
```

Eric J Dickens
FreeREG Chairman
    On 11/09/2015 21:03, Kirk Dawson wrote:

```
  It will take me at least a day or more of dedicated time to
    research this stated issue. Shoild it be done?
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by Captainkirkdawson** [comment]
Indeed there was an incorrect church name conversion that no one has picked up even though the table has been reviewed many many times by a whole bunch of people.

'Swithins' => 'Swith1n', other variations in the name Swithin and Swithin's were being processed OK.
Correction applied.

Anyone care to pick up other errors?
   'Albans' => 'Alban',
    'Albright\'s' => 'Albright',
    'Andrews' => 'Andrew',
    'Andrew\'s' => 'Andrew',
    'Annes' => 'Anne',
    'Augustines' => 'Augustine',
    'Augustine\'s' => 'Augustine',
    'Barthlomew' => 'Bartholomew',
    'Bartholemew' => 'Bartholomew',
    'Bartholemews' => 'Bartholomew',
    'Batholomew' => 'Bartholomew',
    'Batholomews' => 'Bartholomew',
    'Benedict\'s' => 'Benedict',
    'Benedicts' => 'Benedict',
    'Bololph' => 'Botolph',
    'Boltolph' => 'Botolph',
    'Boltoph' => 'Botolph',
    'Boltophs' => 'Botolph',
    'Botoph' => 'Botolph',
    'Catherines' => 'Catherine',
    'Catherine\'s' => 'Catherine',
    'Chads' => 'Chad',
    'Clements' => 'Clement',
    'Clement\'s' => 'Clement',
    'Cuthberts' => 'Cuthbert',
    'Davids' => 'David',
    'David\'s' => 'David',
    'Dunstans' => 'Dunstan',
    'Edmonds' => 'Edmond',
    'Edmunds' => 'Edmund',
    'Edwards' => 'Edward',
    'Edward\'s' => 'Edward',
    'Elphins' => 'Elphin',
    'Faiths' => 'Faith',
    'Georges' => 'George',
    'George\'s' => 'George',
    'Germans' => 'German',
    'Guthlac\'s' => 'Guthlac',
    'Helens' => 'Helen',
    'Helen\'s' => 'Helen',
    'Johns' => 'John',
    'Julians' => 'Julian',
    'Leonards' => 'Leonard',
    'Loenard\'s' => 'Loenard',
    'Lukes' => 'Luke',
    'Margarets' => 'Margaret',
    'Margaret\'s' => 'Margaret',
    'Marks' => 'Mark',
    'Martins' => 'Martin',
    'Martin\'s' => 'Martin',
    "Marys" => 'Mary',
    'Mary\'s' => 'Mary',
    'Matthews' => 'Matthew',
    'Michaels' => 'Michael',
    'Michael\'s' => 'Michael',
    'Oswalds' => 'Oswald',
    'Pauls'=> 'Paul',
    'Paul\'s' => 'Paul',
    'Pega\'s' => 'Pega',
    'Peters' => 'Peter',
    'Peter\'s' => 'Peter',
    'Philips' => 'Philip',
    'Stevens' => 'Steven',
    'Steven\'s' => 'Steven',

```
'Swithen' => 'Swithin',
'Swithins' => 'Swithin',
'Swithin\'s' => 'Swithin',
'Swithuns' => 'Swithun',
'Wilfreds' => 'Wilfred',
'Wilfrid\'s' => 'Wilfrid',
'Cemetry' => 'Cemetery',
'Marys' => 'Mary',
"Mary\'s" => 'Mary',
"Marys\'" => 'Mary',
```

  'Nicholas\'' => 'Nicholas'}
  COMMON_WORD_EXPANSIONS = {
    'Saints\'' => 'St',
    'Saint\'s' => 'St',
    'Saint' => 'St',
    'SAINT' => 'St',
    'St.' => 'St',
    'st.' => 'St',
    'sT.' => 'St',
    'ST' => 'St',
    'Gt' => 'Great',
    'GT' => 'Great',
    'Gt.' => 'Great',
    'GT.' => 'Great',
    'Lt' => 'Little',
    'LT' => 'Little',
    'Lt.' => 'Little',
    'LT.' => 'Little',
    '&' => "and",
    'NR' => 'near',
    'nr' => 'near',
  }

**Comment by Sherlock21** [comment]
Thank you

**Comment by edickens** [comment]
```
Hi Sean,
What am I supposed to do?  We think this problem is Kirk's
conversion where there was a spelling error which has been fixed.  E
_____________________________________
```

Eric J Dickens
FreeREG Chairman
    On 13/09/2015 12:04, sean-wood wrote:

```
  Assigned #414 to @edickens.
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by Sherlock21** [comment]
The issue lay in the conversion table ( above) which Kirk says he had fixed yesterday and would be in place overnight last night.

But would the then need someone to recycle bot the files or will it do itself?

**Comment by Captainkirkdawson** [comment]
Nothing does it by itself. An action is required, 

The church name has been change, merged and the registers merged, All batches are now in the correct location.

Only question I have now is wither the files with identical names loaded by deo123 and LynneK are duplicates
