### ISSUE TITLE
Batch uploaded 10 Aug 2015 creates a Place name Unapproved. (ericb)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#415]
Issue reported by **ericb** at 2015-09-11 18:18:17 UTC
Time: 2015-09-11T17:13:09+00:00
Session ID: 9df2dacd20645af9015baa85bdd6d73c
Problem Page URL: [/freereg1_csv_files/55c96a0af493fdf4bd05c7fe](/freereg1_csv_files/55c96a0af493fdf4bd05c7fe)
Previous Page URL: [http://freereg2.freereg.org.uk/registers/555a80bcf493fdb4b6005a20](http://freereg2.freereg.org.uk/registers/555a80bcf493fdb4b6005a20)
Reported Issue:
The bar on uploading files against Place names which don't exists still manage to get uploaded.
eg attached batch uploaded to LAN/ Saddleworth in Lizzzz (LANSACBA.csv) + 2 others,  whilst this place name had been relocated to WRY before that  (on 23 June 2015)

Is the block not working if places are relocated?
or is someone overriding it?

these 3 files were relocated to WRY/Saddleworth on today's date 11 Sep 2015.

I am sure there are others.    

![Screenshot](http://freereg2.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1441995497-82528-1697/LAN-Saddleworth.jpg)

**Comment by Captainkirkdawson** [comment]
I am sorry Eric but where do you find any Saddleworth place in LAN?
![lan-saddleworth](https://cloud.githubusercontent.com/assets/2874694/9825338/de6d27e0-588f-11e5-851c-90d35bc61b9d.JPG)
If you have gone and moved them how do you expect me to track anything

**Comment by Sherlock21** [comment]
I had relocated these from LAN, to the pre-existing WRY/Saddleworth, before I found other cased of newly formed  uploads creating their own Place name, and realised that there might be an issue.

If you wish, I will create a " test file" and upload it via F1 to a not Existing Place if you wish?

**Comment by Captainkirkdawson** [comment]
Please do that
