### ISSUE TITLE
Font and box size (Pat Shepherd)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#416]
Issue reported by **Pat Shepherd** at 2015-09-11 19:58:22 UTC
Time: 2015-09-11T19:25:38+00:00
Session ID: 
Problem Page URL: []()
Previous Page URL: [http://freereg2.freereg.org.uk/contacts/new](http://freereg2.freereg.org.uk/contacts/new)
Reported Issue:
Not a problem - just a question.  The old format for BMD parish records also showed the mother where available.  I'm researching the Patch/Patche (etc) family of South Petherton, Somerset.  From 3 brothers, all with more than one marriage there were a large number of children with the same names, and some mothers with only first names known.  Often the only way to distinguish one from another is more often than not with the mother.  The old records showed a family number which helped.  Is there a way to get birth, marriage and death in one search so you can tell if a child died young?  It seemed customary in some families (certainly in my British ancestors), to give the next male child the name given to the most recently deceased infant male child (same with females).  Such is the case of Nicholas Patch who was baptised 13 Feb 1591, the son of Nicholas.  Followed with the baptism of Nicholas Patch on 20 Jun 1596, also the son of Nicholas.  My first guess is that the Nicholas born in 1591 did not survive, but with the current system (such as I know it) I must run another search to find out.  I am attempting to create a reliably researched family tree with very old records.  Of course I'm in the first stages so I don't have much structure yet.  I would appreciate your correcting my mistakes in usage of this site.  From my side, I must say that I find the boxes and font too large.  Hard to view and takes up way too much paper to print.  Yes, I'm old, retired, and poor.  Thanks for your help.
Pat Shepherd    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by PatReynolds** [comment]
I don't understand her issue with BM+D in one search - already possible if you enter a county.

**Comment by PatReynolds** [comment]
Print issue is #210

**Comment by Captainkirkdawson** [comment]
There is no issue with BDM search. In fact the display of all events at once is far superior to FR1

**Comment by Captainkirkdawson** [comment]
210 was addressed 6 weeks ago.
In my opinion there will be no way to satisfy every persons view on font and size of font. 

IMLMO anyone can copy the ouput into any word or text processor and change them for themselves

**Comment by PatReynolds** [comment]
In  which case, I'll close
