### ISSUE TITLE
Database Contents How to Use (Jan)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#417]
Issue reported by **Jan** at 2015-09-13 13:13:14 UTC
Time: 2015-09-13T13:06:53+00:00
Session ID: 
Problem Page URL: []()
Previous Page URL: [http://freereg2.freereg.org.uk/contacts/new](http://freereg2.freereg.org.uk/contacts/new)
Reported Issue:
As a long term user of the original FreeReg, I just wanted to comment that in FreeReg2 it is VERY difficult to work out what registers have been transcribed in your database. 

I was trying to find out what is available for Herefordshire and I can't work out at all what BMD events you have for what dates.

It would be much easier if you could bring back the table format by county from FreeReg1, where we can just scroll down the page to quickly see what data is available for which parish, and also what is currently being worked on.

Many thanks for all your great work though!    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Once again it is, I believe, because the researcher does not understand how to use the Database Contents

**Comment by Captainkirkdawson** [comment]
Alison has put an excellent write up on how to use the contents into the help.

**Comment by Captainkirkdawson** [comment]
Have added the following test as a chapeau to that page.
The database contents pages contain a wealth of information about what the database contains for each and every register we have transcribed. They contain far more detail and accurate information than available in the first version of FreeREG, including the number of transcription records for each decade. If you want to know more about the contents or in doubt about how to use these pages please read our HELP notes.
