### ISSUE TITLE
Website Problem (Dru)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#418]
Issue reported by **Dru** at 2015-09-13 12:28:12 UTC
Time: 2015-09-13T12:23:59+00:00
Session ID: 
Problem Page URL: []()
Previous Page URL: [http://freereg2.freereg.org.uk/contacts](http://freereg2.freereg.org.uk/contacts)
Reported Issue:
Hello:
Yesterday & again today I am unable to open the any information after completing a search because the box does not extend to enable one to click on the source, thus opening for furthe rinformation.
Has there been a website problem this weekend or is it a priblem I have to resolve this end.
I had been able to open any box during anytime last week.
Hoping you can assist.
Thank you.    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by edickens** [comment]
I have replied that it could be long place/church names.  But with no idea of the search I cannot reproduce it.  E

**Comment by edickens** [comment]
His email address is wrong too.  It is bouncing.  A good reason for people to register before being able to comment as that will verify the email address.  As other websites require.
