### ISSUE TITLE
Report error in file "Upload processed" email (EricD)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#420]
Issue reported by **EricD** at 2015-09-14 18:49:14 UTC
Time: 2015-09-14T18:46:25+00:00
Session ID: 2544defdb8c1bfd8b80701b645346dd3
Problem Page URL: [/csvfiles/new](/csvfiles/new)
Previous Page URL: [http://freereg2.freereg.org.uk/freereg1_csv_files/my_own](http://freereg2.freereg.org.uk/freereg1_csv_files/my_own)
Reported Issue:
Kirk - Is it possible to say in the "Upload Processed" email if the file is error free or with errors?
This will avoid the need to check the Processed file listing.  E and Alison    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Done
