### ISSUE TITLE
Cookie request does not go away (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#422]
Issue reported by **REGManager** at 2015-09-15 10:40:35 UTC
Time: 2015-09-15T10:37:56+00:00
Session ID: ee6312abacdbff215799fd9a5ff43a6e
Problem Page URL: [/search_queries/new](/search_queries/new)
Previous Page URL: [http://freereg2.freereg.org.uk/manage_resources/new](http://freereg2.freereg.org.uk/manage_resources/new)
Reported Issue:
Mary (CAM) has reported this to me...
Incidentally, the 'cookie' notice is driving me crackers.  I run ccclean almost daily & so get the notice up almost daily.  This doesn't seem to happen on other websites that put up an initial cookie notice.
I think she needs to mark FR2 as being safe or something.  Advice needs to be given in our Help pages or in the initial Cookie message.  E    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by PatReynolds** [comment]
I've copied in Alison for her suggestions and Helena for information.  The
trouble is, the procedure needed is different for every browser.

Best wishes,

Pat

On Tuesday, 15 September 2015, FreeUKGenIssues notifications@github.com
wrote:

> Issue reported by _REGManager_ at 2015-09-15 10:40:35 UTC
> Time: 2015-09-15T10:37:56+00:00
> Session ID: ee6312abacdbff215799fd9a5ff43a6e
> Problem Page URL: /search_queries/new
> Previous Page URL: http://freereg2.freereg.org.uk/manage_resources/new
> Reported Issue:
> Mary (CAM) has reported this to me...
> Incidentally, the 'cookie' notice is driving me crackers. I run ccclean
> almost daily & so get the notice up almost daily. This doesn't seem to
> happen on other websites that put up an initial cookie notice.
> I think she needs to mark FR2 as being safe or something. Advice needs to
> be given in our Help pages or in the initial Cookie message. E
> 
> [image: Screenshot]
> https://camo.githubusercontent.com/a204f2529ce3a03337dc1d560f28fbf5b37ad308/687474703a2f2f66726565726567322e667265657265672e6f72672e756b
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/FreeUKGen/FreeUKGenProductIssues/issues/422.

## 

_\- -_

_Dr Pat Reynolds_
Executive Director
Free UK Genealogy  http://www.freeukgenealogy.org.uk/
A charity registered in England and Wales, number 1096940

​+44 ​1904 541411​ +44 7943 145387

36 Albemarle Road, York, YO23 1ER, UK

**Comment by Captainkirkdawson** [comment]
I am sorry but if you run a cookie cleaner then you will have to accept the use of cookies again

**Comment by PatReynolds** [comment]
Think Alison has completed this some time ago.
