### ISSUE TITLE
Creating UserID not reporting success (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#423]
Issue reported by **REGManager** at 2015-09-16 07:13:04 UTC
Time: 2015-09-16T07:08:30+00:00
Session ID: 06ffa990f2d5e234253c4765e43f3719
Problem Page URL: [/userid_details/new](/userid_details/new)
Previous Page URL: [http://freereg2.freereg.org.uk/userid_details/options](http://freereg2.freereg.org.uk/userid_details/options)
Reported Issue:
I seem to remember that after I create a UserID as part of my Coordinator Actions, I used to get a message to say that the action was successful.  It now goes straight back to the start page.  My concern is that it might also not be telling me if I have made a mistake, such as a duplicate UserID.  E    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
You cannot create a duplicate userid nor use the same email address. You will always get an error message
