### ISSUE TITLE
Could the userid be included in this display (MikeNL)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#426]
Issue reported by **MikeNL** at 2015-09-21 15:16:52 UTC
Time: 2015-09-21T11:06:02+00:00
Session ID: 8d44d15b3b088eaa8cb182bd466f37e1
Problem Page URL: [/userid_details/5462b419e937907d7000042b](/userid_details/5462b419e937907d7000042b)
Previous Page URL: [http://freereg2.freereg.org.uk/userid_details/selection?option=Select%20specific%20userid](http://freereg2.freereg.org.uk/userid_details/selection?option=Select%20specific%20userid)
Reported Issue:
There is virtually everything about a transcriber that is displayed on this screen but their userid is not displayed.    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by edickens** [comment]
```
Hi Mike

I took time to find it, but it is in the Breadcrumb.  It is not
amendable...





Cheers

Eric

_____________________________________
```

Eric J Dickens
FreeREG Chairman
    On 21/09/2015 16:16, FreeUKGenIssues
      wrote:

```
  Issue reported by MikeNL at 2015-09-21
    15:16:52 UTC
    Time: 2015-09-21T11:06:02+00:00
    Session ID: 8d44d15b3b088eaa8cb182bd466f37e1
    Problem Page URL: /userid_details/5462b419e937907d7000042b
    Previous Page URL: http://freereg2.freereg.org.uk/userid_details/selection?option=Select%20specific%20userid
    Reported Issue:
    There is virtually everything about a transcriber that is
    displayed on this screen but their userid is not displayed. 

  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by Sherlock21** [comment]
Isn't it at the top - just above the table? in Green, Just under the line: Search/ Your Actions / Logout / Help?

**Comment by Captainkirkdawson** [comment]
You must both remeber that simply replying never goes to MikeNL. You must add a cc to get it to him

**Comment by Captainkirkdawson** [comment]
Is this really required?

**Comment by edickens** [comment]
```
The  UserID just needs to be in bold.  Or as a non-amendable field. 
It is not very obvious in the breadcrumb. E
_____________________________________
```

Eric J Dickens
FreeREG Chairman
    On 24/09/2015 22:57, Kirk Dawson wrote:

```
  Is this really required?
  —
    Reply to this email directly or view
      it on GitHub.
```
