### ISSUE TITLE
Print Page to identify FR and person/date (Cormac Kilmurry)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#427]
Issue reported by **Cormac Kilmurry** at 2015-09-22 19:24:32 UTC
Time: 2015-09-22T19:16:29+00:00
Session ID: 
Problem Page URL: []()
Previous Page URL: [http://freereg2.freereg.org.uk/contacts/new](http://freereg2.freereg.org.uk/contacts/new)
Reported Issue:
Printable format: Would you consider having FreeReg identified on the print? The date of printing would be useful, too. The person's name could be printed at the top, also.
Sample (all in bold type):

Baptism entry                      Jane GREEN              FreeReg                            12 December 2016

I hope you don't mind my suggesting this!
Thanks.
Cormac    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Implemented
