### ISSUE TITLE
No results when retrying a search (Audrey German)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#428]
Issue reported by **Audrey German** at 2015-09-23 14:23:51 UTC
Time: 2015-09-23T14:22:01+00:00
Session ID: 
Problem Page URL: []()
Previous Page URL: [http://www.freereg.org.uk/contacts/new](http://www.freereg.org.uk/contacts/new)
Reported Issue:
I am not at the moment getting any results even when I retry a search Which previously resulted in information.     

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Totally lacking in information on which to conduct any investigation

**Comment by Captainkirkdawson** [comment]
Totally lacking in information on which to conduct any investigation

**Comment by Captainkirkdawson** [comment]
I do not consider this to be a bug.
