### ISSUE TITLE
Transciber has registered as researcher (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#429]
Issue reported by **REGManager** at 2015-09-24 08:26:58 UTC
Time: 2015-09-24T08:19:25+00:00
Session ID: 879610cd5ba77c84fbfa17777e0d2f46
Problem Page URL: [/userid_details/56031fe8f493fda83b000086](/userid_details/56031fe8f493fda83b000086)
Previous Page URL: [http://www.freereg.org.uk/userid_details/selection?option=Select%20specific%20userid](http://www.freereg.org.uk/userid_details/selection?option=Select%20specific%20userid)
Reported Issue:
I don't  know how some people are registering now, but these could be being done by SCs to match with a FR1 registration.
But this new one with UserID tremble has registered with the Researcher syndicate as a Transcriber.  I know from FR1 that this should be NBL.
The message from FR does not say which syndicate they have used to register, and as I get copies, it would help to know and hence pick up problems.
TY E    

![Screenshot](http://freereg2.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1443083218-92901-7660/Capture.JPG)

**Comment by PatReynolds** [comment]
Hello,

Probably the effect of too much South Atlantic air, but I am confused by
what 'Researcher' means here.

I think 'Researcher' means 'member of the public who visits our website
looking for information' - but is that the case here?  Registered
Researchers (members of the public who have signed up) isn't live yet, is
it?

I think we also need to be careful with 'User' (I am at fault here) -
sometimes it is used to mean 'member of the public who ....' but sometimes
it is used to mean the 'user of this particular system'.

Thanks,

Pat

—

> Reply to this email directly or view it on GitHub
> https://github.com/FreeUKGen/FreeUKGenProductIssues/issues/429.

## 

_\- -_

_Dr Pat Reynolds_
Executive Director
Free UK Genealogy  http://www.freeukgenealogy.org.uk/
A charity registered in England and Wales, number 1096940

​+44 ​1904 541411​ +44 7943 145387

36 Albemarle Road, York, YO23 1ER, UK

**Comment by Captainkirkdawson** [comment]
Uses the link in FR1

**Comment by edickens** [comment]
```
I had better get rid of that.  E
_____________________________________
```

Eric J Dickens
FreeREG Chairman
    On 24/09/2015 15:26, Kirk Dawson wrote:

```
  Uses the link in FR1
  —
    Reply to this email directly or view
      it on GitHub.
```
