### ISSUE TITLE
Website Problem (JK)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#430]
Issue reported by **JK** at 2015-09-25 11:57:57 UTC
Time: 2015-09-25T11:54:08+00:00
Session ID: 
Problem Page URL: []()
Previous Page URL: [http://www.freereg.org.uk/contacts/new](http://www.freereg.org.uk/contacts/new)
Reported Issue:
The typeface used on the new website is rather faint and difficult to read.  Could 
you use a bolder one please?    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by PatReynolds** [comment]
Duplicate issue.  Alison, can you add this to FAQ?
