### ISSUE TITLE
search of database (deo123)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#431]
Issue reported by **deo123** at 2015-09-25 15:25:06 UTC
Time: 2015-09-25T15:21:13+00:00
Session ID: d370ab95f9553204d1ee15ab741247f2
Problem Page URL: [/search_queries/56056669f493fde10300030f](/search_queries/56056669f493fde10300030f)
Previous Page URL: [http://freereg2.freereg.org.uk/search_queries/new](http://freereg2.freereg.org.uk/search_queries/new)
Reported Issue:
Searching for Richard Ashford 1769-1769 Cornwall

I was expecting one record 
Richd Ashford 12 Jun 1769 Cornwall Isles of Scilly

but it didn't return anything.    

![Screenshot](http://freereg2.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1443194706-51887-0781/richard_ashford_1769.JPG)

**Comment by Sherlock21** [comment]
He is actually in the CON / Isles of Scilly (Various locations)
I agree with implication: its hard to guess which island so try NO Place name
or try St Mary with Nearby.

but copy of image won't attach.

**Comment by PatReynolds** [comment]
He is in twice

CON/Isle of Scilly (Various locations) (Unknown) [Transcript]
and
CON/Isles of Scilly (St Marys) (St Marys) [Parish Register]

Both records seem fine to me, and easily found.

Something to add to the help file, as this kind of thing will be happening
a lot, I guess?

Best wishes,

Pat

On Friday, 25 September 2015, Sherlock21 notifications@github.com wrote:

> He is actually in the CON / Isles of Scilly (Various locations)
> I agree with implication: its hard to guess which island so try NO Place
> name
> or try St Mary with Nearby.
> 
> but copy of image won't attach.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/FreeUKGen/FreeUKGenProductIssues/issues/431#issuecomment-143260207
> .

## 

_\- -_

_Dr Pat Reynolds_
Executive Director
Free UK Genealogy  http://www.freeukgenealogy.org.uk/
A charity registered in England and Wales, number 1096940

​+44 ​1904 541411​ +44 7943 145387

36 Albemarle Road, York, YO23 1ER, UK

**Comment by AlOneill** [comment]
Second entry took me a while to find as surname is not Ashford:
Richd EXFORD    Baptism     12 Jun 1769     Cornwall    Isles of Scilly (St Mary's) (St Mary) [Parish Register] 

It took a combination of search strategies,  but I think all the ways I tried are covered somehow in Help.

Pat: What aspect specifically is currently missing?

**Comment by PatReynolds** [comment]
I can't remember how I did it!
There was a way I got to Richd Exford, but itwasn't soundex - which doesn't pick up either the Richard or the Ashford....
I think we have to close this as being one of those searches which is just difficult.
