### ISSUE TITLE
Changing Church name does not now count up how many records (ericb)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#432]
Issue reported by **ericb** at 2015-09-25 17:57:46 UTC
Time: 2015-09-25T17:53:08+00:00
Session ID: d8b50ab480417828d4267902ef6b771f
Problem Page URL: [/churches/55908fd1f493fdda76000289/rename](/churches/55908fd1f493fdda76000289/rename)
Previous Page URL: [http://www.freereg.org.uk/churches/55908fd1f493fdda76000289](http://www.freereg.org.uk/churches/55908fd1f493fdda76000289)
Reported Issue:
In F2 Production, when I start a Change Church Name, the red message no longer counts up how many Records.    

![Screenshot](http://freereg2.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1443203866-51861-8267/deansgate_St_John.jpg)

**Comment by Captainkirkdawson** [comment]
Suspect it never did. There are many change actions

**Comment by sean-wood** [comment]
needs further investigation to understand full scope

**Comment by Captainkirkdawson** [comment]
Fixed
