### ISSUE TITLE
Website Problem (Christine Wynne)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#433]
Issue reported by **Christine Wynne** at 2015-09-25 22:00:56 UTC
Time: 2015-09-25T21:45:39+00:00
Session ID: 
Problem Page URL: []()
Previous Page URL: [http://freereg2.freereg.org.uk/contacts/new](http://freereg2.freereg.org.uk/contacts/new)
Reported Issue:
Hi,
I am unable to find an old entry that I had previously copied from the old format of Free REG.
The person that I was searching for back in 2013  is Thos (Thomas) Hedley and the Details  that I was given then are : 
Search Record Details: County Northumberland Place Chollerton Church St Giles Tr BaptismDate 10 May 1722 Forename Thos Sex M FatherForename John MotherForename Doro FatherSurname HEDLEY Abode Toms hole FileNumber 31031.
Could you please look into this as it is not the first time that this has happened.

Chris Wynne of South Australia.    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
![hedley](https://cloud.githubusercontent.com/assets/2874694/10113500/54fb8c7c-63a2-11e5-91bf-531382a8328f.JPG)

I had no trouble finding that record
