### ISSUE TITLE
Question (Gordon Webb)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#434]
Issue reported by **Gordon Webb** at 2015-09-28 12:52:16 UTC
Time: 2015-09-28T12:42:02+00:00
Session ID: 
Problem Page URL: []()
Previous Page URL: [http://freereg2.freereg.org.uk/contacts/new](http://freereg2.freereg.org.uk/contacts/new)
Reported Issue:
I find the new search engine very good and through it I have found information which I could not find via the earlier search engine.
What has happened to the coverage page ie which registers you have transcribed?
Also you no longer say when an update has been done.
If you are redesigning these pages might I suggest an update page like your sister site FreeCen which says what new records have been uploaded.
Also will there be a way notes could be added to an entry like the notems of FreeBMD?
Thanks for a brilliant site and keep up the good work.
Gordon    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by edickens** [comment]
My reply - E
Hello Gordon,

Thank you for the feedback.

You can find the contents of the database under "Database Contents" on the home page.  The format is different to previously, but the information is generated automatically so is accurate.

The database is updated every night, details are shown in the footer of the home page.

We are working on further developments and one is a means for you to be emailed when a particular place has records added or amended.

We have a long way to go, but all feedback is very welcome.

Best wishes,

Eric
