### ISSUE TITLE
Improvement to search results (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#437]
Issue reported by **REGManager** at 2015-09-29 15:02:10 UTC
Time: 2015-09-29T14:57:47+00:00
Session ID: dd4c07d939d66e931aeb9f02fa4dd86f
Problem Page URL: [/search_records/5510bdcbe937900ae8baf5d7?search_id=560aa6e4f493fd3246000140](/search_records/5510bdcbe937900ae8baf5d7?search_id=560aa6e4f493fd3246000140)
Previous Page URL: [http://www.freereg.org.uk/search_queries/560aa6e4f493fd3246000140](http://www.freereg.org.uk/search_queries/560aa6e4f493fd3246000140)
Reported Issue:
When the Detail is selected, then the Batch header notes should be shown at the top and not in the boxes.  It does not need to be large text.  This is needed to show if the result is from a PR or TR and show any links to the RO or OPC or anything else.  E    

![Screenshot](http://freereg2.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1443538930-22551-9835/Capture.JPG)

**Comment by Captainkirkdawson** [comment]
Would suggest that we show the Register Notes not the Batch header notes which can be garbage, Do  not understand comment on PR/TR as this is already displayed.

**Comment by PatReynolds** [comment]
Sounds good to me, I think the comment about PR and TR meant that those are the kinds of registers where the Notes should be displayed, in order to show links to RO, etc.

**Comment by Captainkirkdawson** [comment]
Register note was implemented some time ago
