### ISSUE TITLE
Display of selection buttons on Search results (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#438]
Issue reported by **REGManager** at 2015-09-29 15:04:20 UTC
Time: 2015-09-29T15:02:12+00:00
Session ID: dd4c07d939d66e931aeb9f02fa4dd86f
Problem Page URL: [/search_records/5510bdcbe937900ae8baf5d7?search_id=560aa6e4f493fd3246000140](/search_records/5510bdcbe937900ae8baf5d7?search_id=560aa6e4f493fd3246000140)
Previous Page URL: [http://www.freereg.org.uk/feedbacks/new?utf8=%E2%9C%93&feedback_time=2015-09-29+14%3A57%3A47+UTC&session_id=dd4c07d939d66e931aeb9f02fa4dd86f&user_id=REGManager&problem_page_url=%2Fsearch_records%2F5510bdcbe937900ae8baf5d7%3Fsearch_id%3D560aa6e4f493fd3246000140&previous_page_url=http%3A%2F%2Fwww.freereg.org.uk%2Fsearch_queries%2F560aa6e4f493fd3246000140&feedback_type=issue](http://www.freereg.org.uk/feedbacks/new?utf8=%E2%9C%93&feedback_time=2015-09-29+14%3A57%3A47+UTC&session_id=dd4c07d939d66e931aeb9f02fa4dd86f&user_id=REGManager&problem_page_url=%2Fsearch_records%2F5510bdcbe937900ae8baf5d7%3Fsearch_id%3D560aa6e4f493fd3246000140&previous_page_url=http%3A%2F%2Fwww.freereg.org.uk%2Fsearch_queries%2F560aa6e4f493fd3246000140&feedback_type=issue)
Reported Issue:
I saw an email these last few days saying that a button layout had been fixed.  There are buttons here which run together.  E    

![Screenshot](http://freereg2.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1443539060-22547-7228/Capture.JPG)

**Comment by Captainkirkdawson** [comment]
Thank you
