### ISSUE TITLE
Offer "All places" to researcher (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#439]
Issue reported by **REGManager** at 2015-10-01 06:25:55 UTC
Time: 2015-10-01T06:17:59+00:00
Session ID: 742c0fa2b2698e4757aea6e4c8ae1f49
Problem Page URL: [/freereg_contents/new](/freereg_contents/new)
Previous Page URL: [http://www.freereg.org.uk/](http://www.freereg.org.uk/)
Reported Issue:
We get a lot of requests/complaints that the Database Contents does not list all the places.
So can we give them the "All Places" report that a CC can see?  I think this has all that is needed.  If the link "All places" could go before the list of places - see attached screen print) - then it could go to the All Places report.  The only thing that is missing would be the year ranges covered, but they can find that by selecting the Place.  No new report is needed.
I think this will stop the Comments we keep getting.  E    

![Screenshot](http://freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1443680755-11164-0571/Capture.JPG)

**Comment by edickens** [comment]
PS. The links on the All places for a Researcher should not go down to Batch level.  Just show Church details.  Needs some thought.  E
![capture](https://cloud.githubusercontent.com/assets/8876165/10214517/e7aef6b8-6810-11e5-9d24-080afc05c955.JPG)
