### ISSUE TITLE
What are the nils?

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeUKRegProductIssues#44]
EricD reported
What are the "nil"s?
![capture](https://cloud.githubusercontent.com/assets/2874694/4861580/7c9d2a48-6104-11e4-9e48-5a1ca7925af2.JPG)

**Comment by EmJayFry** [comment]
On 31 Oct 2014 15:49, Kirk Dawson wrote:

> EricD reported
> What are the "nil"s?
> capture
> https://cloud.githubusercontent.com/assets/2874694/4861580/7c9d2a48-6104-11e4-9e48-5a1ca7925af2.JPG

NULL entries. Blanks. Nothings. Empty entries.

## 

Regards,
Mike Fry (Jhb)

**Comment by Captainkirkdawson** [comment]
True but they should not be there.

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Captainkirkdawson** [comment]
Unable to replicate in FR2.1.0
![nil](https://cloud.githubusercontent.com/assets/2874694/5094267/d5819ac4-6f1c-11e4-8c90-dd88f9dc9dbf.JPG)

**Comment by Captainkirkdawson** [comment]
May be a symptom of #276
