### ISSUE TITLE
Resetting password gives URL not found (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#440]
Issue reported by **REGManager** at 2015-10-01 11:08:09 UTC
Time: 2015-10-01T11:05:56+00:00
Session ID: 3157f5c9577747226f1c919e32f47718
Problem Page URL: [/userid_details/options](/userid_details/options)
Previous Page URL: [http://www.freereg.org.uk/manage_resources/new](http://www.freereg.org.uk/manage_resources/new)
Reported Issue:
I think this is the first UserID I have had to set up since we went to FR.  The link in the email below which I usually use does not work.  E

This is the messages...

Dear Trevor;

You have requested a password reset. Please click on the following link or paste a copy into your browser address window to reset your password to something only you know.

http://freereg.org.uk/refinery/users/password/edit?initial=true&reset_password_token=ngAcKXYFBL5MinDtP1Df

Do not reply to this email but if you have any difficulties please contact your coordinator.

Eric Dickens at freereg.edickens+unk@gmail.com

We hope you are enjoying working with FreeREG.

The FreeREG Team

![Screenshot](http://freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
fixed
