### ISSUE TITLE
Help button on Search input page header is mis routed. (ericb)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#442]
Issue reported by **ericb** at 2015-10-02 14:35:48 UTC
Time: 2015-10-02T14:31:19+00:00
Session ID: 72756f45f07ecd82b790a9cc597c9513
Problem Page URL: [/registered-researchers](/registered-researchers)
Previous Page URL: [http://www.freereg.org.uk/](http://www.freereg.org.uk/)
Reported Issue:
Clicking on the HELP button on the main starter page does not go to help items. - goes here instead.

the attached page     

![Screenshot](http://www.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1443796548-51126-5594/Help_button_shows_this.jpg)

**Comment by Sherlock21** [comment]
Well as if by magic, it's OK now.
