### ISSUE TITLE
This Place name (DBY/ Riddings) does not feature in the user Search list of places. (ericb)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#443]
Issue reported by **ericb** at 2015-10-04 16:59:48 UTC
Time: 2015-10-04T16:55:09+00:00
Session ID: ac20f97b7d49cfb8b0bd86ba6e297959
Problem Page URL: [/places/53cbf5cfeca9eb03a600249d](/places/53cbf5cfeca9eb03a600249d)
Previous Page URL: [http://www.freereg.org.uk/places?page=3](http://www.freereg.org.uk/places?page=3)
Reported Issue:
The Place Name seems sound, has a GridRef & Genuki Linmk, and is not showing that it need to be Approved. It appears  to have a church and a Batch attached .

After The Place name was  edited to improve its GridRef & Genuki link today, it still does not appear in the Places under DBY County in  a Search Specification form.

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Rewrote conditions under which the cache is rebuilt. File has been resubmitted for processing overnight

**Comment by Captainkirkdawson** [comment]
Resolved
