### ISSUE TITLE
One page scroll-down view of batch (alsibk)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#445]
Issue reported by **alsibk** at 2015-10-05 08:07:17 UTC
Time: 2015-10-05T08:00:30+00:00
Session ID: 90b157e2ce8ba0a8507816d873416814
Problem Page URL: [/manage_counties/selection?option=Review%20Batches%20by%20Most%20Recent%20Date%20of%20Change](/manage_counties/selection?option=Review%20Batches%20by%20Most%20Recent%20Date%20of%20Change)
Previous Page URL: [http://freereg2.freereg.org.uk/feedbacks/new?utf8=%E2%9C%93&feedback_time=2015-10-05+07%3A51%3A52+UTC&session_id=90b157e2ce8ba0a8507816d873416814&user_id=alsibk&problem_page_url=%2Fmanage_counties%2Fselection%3Foption%3DReview%2520Batches%2520by%2520Most%2520Recent%2520Date%2520of%2520Change&previous_page_url=http%3A%2F%2Ffreereg2.freereg.org.uk%2Fmanage_counties%2Fselect_action&feedback_type=issue](http://freereg2.freereg.org.uk/feedbacks/new?utf8=%E2%9C%93&feedback_time=2015-10-05+07%3A51%3A52+UTC&session_id=90b157e2ce8ba0a8507816d873416814&user_id=alsibk&problem_page_url=%2Fmanage_counties%2Fselection%3Foption%3DReview%2520Batches%2520by%2520Most%2520Recent%2520Date%2520of%2520Change&previous_page_url=http%3A%2F%2Ffreereg2.freereg.org.uk%2Fmanage_counties%2Fselect_action&feedback_type=issue)
Reported Issue:
Please could we have the additional facility to view a whole batch top to bottom as in FreeREG1, rather than having to trawl through page after page.

This would be useful for CCs and Transcribers alike.

![Screenshot](http://www.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1444032437-70312-9403/One_page_view_file.jpg)

**Comment by Captainkirkdawson** [comment]
Done
