### ISSUE TITLE
Screen shots in Github (alsibk)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#446]
Issue reported by **alsibk** at 2015-10-05 09:17:22 UTC
Time: 2015-10-05T09:15:35+00:00
Session ID: 2c89b17657b4a67b59a83b2392b9ae8d
Problem Page URL: [/manage_counties/selection?option=Review%20Batches%20by%20Most%20Recent%20Date%20of%20Change](/manage_counties/selection?option=Review%20Batches%20by%20Most%20Recent%20Date%20of%20Change)
Previous Page URL: [http://freereg2.freereg.org.uk/manage_counties/select_action](http://freereg2.freereg.org.uk/manage_counties/select_action)
Reported Issue:
"A screenshot that is submitted as part of the FR2 Feedback process is
visible within that process.  It is not transferred to Github. That clearly
is a feature that needs to be added."  Aug 20th

Please could this be actioned?

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Can see no easy way of doing. Having approached Github for advise.

**Comment by edickens** [comment]
When taking and saving a screen print, look for the "Save As" which will 
give all the standard format.

**Comment by Captainkirkdawson** [comment]
Excuse me Eric but that is not the issue or my problem. The issue is moving a copy of the image that comes as part of a Feedback into the Github issue on the Github server and how to do that through their API,

**Comment by edickens** [comment]
Understood now.  No idea either.  E
