### ISSUE TITLE
Return to top on pages (MikeNL)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#448]
Priority  11 (0	3	2	6)

Issue reported by **MikeNL** at 2015-10-05 14:47:49 UTC
Time: 2015-10-05T14:42:55+00:00
Session ID: 07f5b33b87b343748b3455674f5abf76
Problem Page URL: [/freereg1_csv_entries](/freereg1_csv_entries)
Previous Page URL: [http://www.freereg.org.uk/freereg1_csv_files/55b04252f493fd5dc90172c4](http://www.freereg.org.uk/freereg1_csv_files/55b04252f493fd5dc90172c4)
Reported Issue:
Would it be possible to put a copy of the breadcrumbs at the bottom of long screens, similar to the way that First, Next, n,... n, Prev, Last is done?

This would prevent having to always scroll back to the top of the screen if the required information is found near the bottom of the screen.    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Can add return to top but additional breadcrumb line requires rewrite of the GEM we use

**Comment by Captainkirkdawson** [comment]
Scrum Oct 19 2016 decided to implement a return to top on those pages where it might be desirable
