### ISSUE TITLE
Could the userid be included in this display? (MikeNL)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#449]
Issue reported by **MikeNL** at 2015-10-05 14:55:43 UTC
Time: 2015-10-05T14:47:50+00:00
Session ID: 07f5b33b87b343748b3455674f5abf76
Problem Page URL: [/freereg1_csv_entries](/freereg1_csv_entries)
Previous Page URL: [http://www.freereg.org.uk/feedbacks/new?utf8=%E2%9C%93&feedback_time=2015-10-05+14%3A42%3A55+UTC&session_id=07f5b33b87b343748b3455674f5abf76&user_id=MikeNL&problem_page_url=%2Ffreereg1_csv_entries&previous_page_url=http%3A%2F%2Fwww.freereg.org.uk%2Ffreereg1_csv_files%2F55b04252f493fd5dc90172c4&feedback_type=issue](http://www.freereg.org.uk/feedbacks/new?utf8=%E2%9C%93&feedback_time=2015-10-05+14%3A42%3A55+UTC&session_id=07f5b33b87b343748b3455674f5abf76&user_id=MikeNL&problem_page_url=%2Ffreereg1_csv_entries&previous_page_url=http%3A%2F%2Fwww.freereg.org.uk%2Ffreereg1_csv_files%2F55b04252f493fd5dc90172c4&feedback_type=issue)
Reported Issue:
One or two of the screens now display the userid as part of the filename. Unfortunately, it is not done on all screens.

As a further point, the register description that gives filename, place, church name and county name is not consistent over all screens where this information is displayed. Sometimes the text is in bold, other times the county is missing, and there is an overall difference of the small words between the fields - in,  of etc.    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Userid is now consistently displayed
