### ISSUE TITLE
Search issue with date

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeUKRegProductIssues#45]
Eric D reported

If you enter the dates the wrong way round the search still takes place but finds nothing.

Also, after my attempt to search with no entries, I "stopped" my request but when I tried my next test the server was very slow. Does "Stop" on my website stop the search on the server?. It should as someone may have realised that they have made a mistake.

**Comment by graphiclunarkid** [comment]
We should also validate that the date entered is in fact a valid date.

**Comment by Captainkirkdawson** [comment]
Implemented
