### ISSUE TITLE
Decadels Part II (MikeNL)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#451]
Issue reported by **MikeNL** at 2015-10-06 09:59:43 UTC
Time: 2015-10-06T09:53:24+00:00
Session ID: e1018501d1ff40f469495e7bb4110e9b
Problem Page URL: [/freereg1_csv_files/5604a631f493fdb28e002e37](/freereg1_csv_files/5604a631f493fdb28e002e37)
Previous Page URL: [http://www.freereg.org.uk/feedbacks/new?utf8=%E2%9C%93&feedback_time=2015-10-06+09%3A39%3A16+UTC&session_id=e1018501d1ff40f469495e7bb4110e9b&user_id=MikeNL&problem_page_url=%2Ffreereg1_csv_files%2F5604a631f493fdb28e002e37&previous_page_url=http%3A%2F%2Fwww.freereg.org.uk%2Fregisters%2F55ea27d7f493fdd3ed000025&feedback_type=issue](http://www.freereg.org.uk/feedbacks/new?utf8=%E2%9C%93&feedback_time=2015-10-06+09%3A39%3A16+UTC&session_id=e1018501d1ff40f469495e7bb4110e9b&user_id=MikeNL&problem_page_url=%2Ffreereg1_csv_files%2F5604a631f493fdb28e002e37&previous_page_url=http%3A%2F%2Fwww.freereg.org.uk%2Fregisters%2F55ea27d7f493fdd3ed000025&feedback_type=issue)
Reported Issue:
Are the decadels for a baptisms file based on birth dates or baptism dates? 

It seems to me that it is a combination of both. Is this correct?    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
baptism date is primary. if no baptism date then birth date is issed
