### ISSUE TITLE
User ID list problem (alsibk)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#452]
Issue reported by **alsibk** at 2015-10-06 14:57:23 UTC
Time: 2015-10-06T14:50:51+00:00
Session ID: 7c9222e14ac6aecdc19e5171f552532a
Problem Page URL: [/userid_details/selection?option=Select%20specific%20userid](/userid_details/selection?option=Select%20specific%20userid)
Previous Page URL: [http://freereg2.freereg.org.uk/userid_details/options?](http://freereg2.freereg.org.uk/userid_details/options?)
Reported Issue:
User ID dropdown menu out of window on RH side.
Box too wide?    

![Screenshot](http://www.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1444143443-55874-0401/ID_screen.jpg)

**Comment by Captainkirkdawson** [comment]
Opera not playing nicely with some displays

**Comment by Captainkirkdawson** [comment]
This one fixed
