### ISSUE TITLE
Can't select ID for upload (alsibk)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#454]
Issue reported by **alsibk** at 2015-10-07 15:36:23 UTC
Time: 2015-10-07T15:30:17+00:00
Session ID: 9634cbcb233764cc8ab9cacb7d3dba36
Problem Page URL: [/csvfiles/55f241f3f493fd7f4907bc11/edit](/csvfiles/55f241f3f493fd7f4907bc11/edit)
Previous Page URL: [http://freereg2.freereg.org.uk/freereg1_csv_files/55f241f3f493fd7f4907bc11](http://freereg2.freereg.org.uk/freereg1_csv_files/55f241f3f493fd7f4907bc11)
Reported Issue:
ID select has again reverted to useless.
Can't select ID to which to upload file.     

![Screenshot](http://www.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1444232183-46795-3269/ID_screen2.jpg)

**Comment by Captainkirkdawson** [comment]
Opera not playing nicely with some displays

**Comment by Captainkirkdawson** [comment]
fixed
