### ISSUE TITLE
CC cannot select ID for replace batch. (alsibk)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#455]
Issue reported by **alsibk** at 2015-10-08 03:10:53 UTC
Time: 2015-10-08T03:05:02+00:00
Session ID: 9d54d43b7d8c2dea4ac62b0ee36844b9
Problem Page URL: [/csvfiles/551f7cf0e93790eb5300dac6/edit](/csvfiles/551f7cf0e93790eb5300dac6/edit)
Previous Page URL: [http://test3.freereg.org.uk/manage_counties/selection?option=Review%20Batches%20by%20Most%20Recent%20Date%20of%20Change](http://test3.freereg.org.uk/manage_counties/selection?option=Review%20Batches%20by%20Most%20Recent%20Date%20of%20Change)
Reported Issue:
Problem persists this is in Firefox.

CC login/Manage county/View batches by most recent date/RPL/ID screen has no dropdown menu    

![Screenshot](http://test3.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1444273853-16369-7578/ID_screen4.jpg)

**Comment by Captainkirkdawson** [comment]
Fixed
