### ISSUE TITLE
Attic not working (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#456]
Issue reported by **REGManager** at 2015-10-08 06:30:20 UTC
Time: 2015-10-08T06:22:42+00:00
Session ID: b6fe6415153a661d5f82c82fad27a4d7
Problem Page URL: [/attic_files/padWRY](/attic_files/padWRY)
Previous Page URL: [http://www.freereg.org.uk/attic_files/select](http://www.freereg.org.uk/attic_files/select)
Reported Issue:
EricB wanted a file recovering.  See attached.  I did it through FR1 because I did not understand the batch name.  This file has now updated FR.  But if I  try to download the latest version I get the Red "Something has gone wrong".  The filename is WRYWRAMA1.CSV and the place WRY,Wragby,St Michael PR - E    

![Screenshot](http://www.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1444285820-87089-2665/Capture.JPG)

**Comment by PatReynolds** [comment]
Has this been resolved?

**Comment by Captainkirkdawson** [comment]
No idea

**Comment by edickens** [comment]
I don't  know.  When looking at my first comment where I refer to a screenshot, all I get is "Not found" for the screenshot.  But that Filename is NOT in the attic so does not look as though it was saved when deleted.  So looks as if the Attic is not saving.   I have now tried a file that Alison deleted and it is there, but the batch name is .1446174613 which means nothing to me.  So it looks as if the Delete is saving but the Batch Name might have been the problem, not that it was failing to save.  The batch name should be the UserID:Filename.   E

**Comment by Captainkirkdawson** [comment]
Resolved an issue when an upload replace did not append the file name to the attic record. The actual file is correctly saved; its just the attic collection that is in error.
