### ISSUE TITLE
Suffolk county summary (JHarold)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#458]
Issue reported by **JHarold** at 2015-10-08 07:57:24 UTC
Time: 2015-10-08T07:54:04+00:00
Session ID: 89b9e3c9ff95ec068ffac5cfa1792706
Problem Page URL: [/freereg_contents/Suffolk](/freereg_contents/Suffolk)
Previous Page URL: [http://freereg2.freereg.org.uk/freereg_contents/new](http://freereg2.freereg.org.uk/freereg_contents/new)
Reported Issue:
page 1 is fine (goes through to Oulton) - click through to the second page and it shows nothing - there should be data for parishes from P onwards.

Julie (Suffolk coordinator)    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Cannot duplicate problem
Neither can reporter
