### ISSUE TITLE
Start date in search

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeUKRegProductIssues#46]
EricB reported

to find a Baptism record that has a date of 1820, it is necessary to put START at 1819. [start at 1820 does not pick it up]

It would be more usual to expect the start/end dates default to be inclusive.

Although there is a box called INCLUSIVE at the foot of the SEARCH form, this appears to be part of the Radius search feature - though just what I don't know.
I Suggest take it off altogether and change the default as above.

**Comment by Sherlock21** [comment]
I think BenB has fixed this one now.

I just ran a test search now (31 oct 2014) and it the search now runs traditionally.  ie just enter 1820 to 1820 to get 1820 results.
EricB

**Comment by benwbrum** [comment]
My opinion is that this is working properly.  If you run across any issues, can you include the specific record that should be appearing but isn't?  It's always possible that we're missing some edge case.

**Comment by Sherlock21** [comment]
Its OK now, Ben - as I just posted - I think this might be a mater of catching up with the formality entering the snags onto the formal listing system.
EB
