### ISSUE TITLE
link not working (JHarold)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#460]
Issue reported by **JHarold** at 2015-10-08 12:32:55 UTC
Time: 2015-10-08T12:31:08+00:00
Session ID: f638821a1f7ce312d8c0d3d0e584df69
Problem Page URL: [/freereg_contents/Essex/show?_method=get&authenticity_token=QIe7%2Bn7kwBTMM7ODB%2BgG0%2B6e2hRuLA7xI4ekcyNZSNw%3D&page=3](/freereg_contents/Essex/show?_method=get&authenticity_token=QIe7%2Bn7kwBTMM7ODB%2BgG0%2B6e2hRuLA7xI4ekcyNZSNw%3D&page=3)
Previous Page URL: [http://www.freereg.org.uk/freereg_contents/Essex/show?_method=get&authenticity_token=QIe7%2Bn7kwBTMM7ODB%2BgG0%2B6e2hRuLA7xI4ekcyNZSNw%3D&page=4](http://www.freereg.org.uk/freereg_contents/Essex/show?_method=get&authenticity_token=QIe7%2Bn7kwBTMM7ODB%2BgG0%2B6e2hRuLA7xI4ekcyNZSNw%3D&page=4)
Reported Issue:
looking at county summary for essex - clicking on Pebmarsh (or it's church, or parish register) I get this message

"If you have arrived at page expecting to find the original freereg search page please note that that site is no longer suppoerted by remains available at Original Freereg Website
If not click the return on your browser and renter your request."

also note the spelling mistake (suppoerted) in that message :)

Julie (essex coordinator)    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Corrected spelling mistake.
Cannot duplicate problem; neither can reppporter
