### ISSUE TITLE
The process for Changing UserID has a major Issue (ericb)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#462]
Issue reported by **ericb** at 2015-10-09 12:49:18 UTC
Time: 2015-10-09T12:33:48+00:00
Session ID: 464ab7e68d7efcd6222be6d2bd9e1f60
Problem Page URL: [/manage_counties/select_action](/manage_counties/select_action)
Previous Page URL: [http://www.freereg.org.uk/manage_counties/new](http://www.freereg.org.uk/manage_counties/new)
Reported Issue:
I changed the UserID for 7 files ( over 3 Place names) earlier int he week.
In this scenario, there were in FR:-

WOR - 3 files  going from deowor to deo123
BKM - 2 files going from deobkm to deo123
CUL - 2 files going from deocul to deo123.

Using the WOR files as example ( County picked at random only as I recall one Place was Stoke Prior) refer to attachment please. This was copied of the Batches list  lunchtime today BST.
I:t Clearly shows the 3 files which now have the correct new UserID deo123.
 However, now there are the same 3 files with the original IUserID back again - then were not in the list after I had done the change ( either on Wednesday afternoon or Thursday afternoon I think)

I have just confirmed that the other 2 Counties - CUL & BKM have the same error. 

further supporting data from EricD is in an email I just copied to you header with this #nbr.

We have stopped using this tool    

![Screenshot](http://www.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1444394958-32010-5411/WOR-DOE_files.jpg)

**Comment by Captainkirkdawson** [comment]
duplicate
