### ISSUE TITLE
the UserID change tool is faulty. (ericb)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#463]
Issue reported by **ericb** at 2015-10-09 12:50:29 UTC
Time: 2015-10-09T12:49:53+00:00
Session ID: 01a6965acf061edabd921f2fc0fd3bc4
Problem Page URL: [/manage_resources/new](/manage_resources/new)
Previous Page URL: [http://www.freereg.org.uk/refinery/login](http://www.freereg.org.uk/refinery/login)
Reported Issue:
I changed the UserID for 7 files ( over 3 Place names) earlier int he week.
In this scenario, there were in FR:-

WOR - 3 files  going from deowor to deo123
BKM - 2 files going from deobkm to deo123
CUL - 2 files going from deocul to deo123.

Using the WOR files as example ( County picked at random only as I recall one Place was Stoke Prior) refer to attachment please. This was copied of the Batches list  lunchtime today BST.
I:t Clearly shows the 3 files which now have the correct new UserID deo123.
 However, now there are the same 3 files with the original IUserID back again - then were not in the list after I had done the change ( either on Wednesday afternoon or Thursday afternoon I think)

I have just confirmed that the other 2 Counties - CUL & BKM have the same error. 

further supporting data from EricD is in an email I just copied to you header with this #nbr.

We have stopped using this tool    

![Screenshot](http://www.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1444395029-32010-3984/WOR-DOE_files.jpg)

**Comment by Captainkirkdawson** [comment]
Fixed 2 days ago
