### ISSUE TITLE
error message (JHarold)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#464]
Issue reported by **JHarold** at 2015-10-09 15:57:26 UTC
Time: 2015-10-09T15:51:24+00:00
Session ID: 5b3a06286ef4820d91e41770decff4fe
Problem Page URL: [/manage_counties/select_action](/manage_counties/select_action)
Previous Page URL: [http://freereg2.freereg.org.uk/manage_resources/new](http://freereg2.freereg.org.uk/manage_resources/new)
Reported Issue:
clicking through database contents to the church for Mistley in Essex I got this 

If you have arrived at page expecting to find the original freereg search page please note that that site is no longer suppoerted by remains available at Original Freereg Website

If not click the return on your browser and renter your request.

For reference for Kirk - the frereg2_session cookie shows saki

Julie (essex coordinator)

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Unable to duplicate
