### ISSUE TITLE
Listing User's Batches by Batch Name Order gets numbers wrong (ericb)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#465]
Issue reported by **ericb** at 2015-10-09 16:08:52 UTC
Time: 2015-10-09T16:05:15+00:00
Session ID: 475415917d99cb7f511f478185c5554a
Problem Page URL: [/freereg1_csv_files/selection?option=List%20by%20Filename](/freereg1_csv_files/selection?option=List%20by%20Filename)
Previous Page URL: [http://www.freereg.org.uk/freereg1_csv_files/my_own?](http://www.freereg.org.uk/freereg1_csv_files/my_own?)
Reported Issue:
When one selects By File name then they come in order .....BA1.csv: BA10.csv: BA11.csv; BA2.csv BA3.csv etc instead of proper numeric order.
When the numbers get into the 40's its difficult to find.     

![Screenshot](http://www.freereg.org.uk)

**Comment by EmJayFry** [comment]
On 09 Oct 2015 6:08 PM, FreeUKGenIssues wrote:

> When one selects By File name then they come in order .....BA1.csv: BA10.csv:
> BA11.csv; BA2.csv BA3.csv etc instead of proper numeric order.
> When the numbers get into the 40's its difficult to find.

These are in alphabetic order. If you want them in numeric order, name them 
accordingly using two digits instead of 1. WinREG will allow you to rename the 
files.

## 

Regards,
Mike Fry (Jhb)

**Comment by Captainkirkdawson** [comment]
Sorry Eric that's what you get with an alphabetic sort. There is nothing to constrain a file_name nor would I advocate one,

**Comment by Sherlock21** [comment]
We will have to put up with it then. Scrap this report therefore.

sorry to trouble you.
