### ISSUE TITLE
Stop/amend how case is changed on churches [Not required letter case changing (MikeNL)]

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#466]
Issue reported by **MikeNL** at 2015-10-10 10:34:24 UTC
Time: 2015-10-10T10:17:44+00:00
Session ID: f5d1a1e2ed652b9652db11b19ec058ee
Problem Page URL: [/places/5583614ef493fdf0f200169b](/places/5583614ef493fdf0f200169b)
Previous Page URL: [http://freereg2.freereg.org.uk/manage_counties/selection?option=Work%20with%20Specific%20Place](http://freereg2.freereg.org.uk/manage_counties/selection?option=Work%20with%20Specific%20Place)
Reported Issue:
I have recently uploaded two files using FR2. The contents of these files were to be added to a currently existing church.

In both cases, somewhere in the process, my church name formats have been changed.

The first example was in "Stoke-upon-Trent" and the church "St Peter ad Vincula" - a new church "St Peter Ad Vincula" was created.

The second example was in "Burton-upon-Trent" and the church "GRO Civil Registrations" - a new church "Gro Civil Registrations" was created.

In both cases, a church with the correctly cased name already existed.

I am going to re-locate the files into the correct churches and then destroy the offending churches.    

![Screenshot](http://www.freereg.org.uk)

**Comment by Sherlock21** [comment]
Whilst using the Change Church Name tool is OK for small batches, there is a limit
on what one can do.
And it relies on the CC or DM noticing that the number of Variants of the church name has increased for that Place.

So its not a satisfactory solution.

This case changing software was not always in use - so please revert back.

**Comment by PatReynolds** [comment]
Is this an open issue, if so what is the request?

**Comment by edickens** [comment]
```
Hi Pat/Kirk,
I don't know if Mike sees your replies.  It would have been a
feedback message.
I think he is referring to the overnight update changing the case in
the Churches.
It is an open issue, but if we move people across to FR then the
overnight update will stop.
Does the FR upload convert case of Churches?
E

On 20/10/2015 15:47, PatReynolds wrote:


  Is this an open issue, if so what is the request?
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by Captainkirkdawson** [comment]
Mike will never see unless copied.

The nightly update will never stop;

All files from what ever source are treated by the same software so this will still happen

**Comment by PatReynolds** [comment]
Thanks, Eric.  I've changed the title to your query.

Best wishes,
Pat

On Tuesday, 20 October 2015, Eric Dickens notifications@github.com wrote:

> Hi Pat/Kirk,
> I don't know if Mike sees your replies.  It would have been a
> feedback message.
> I think he is referring to the overnight update changing the case in
> the Churches.
> It is an open issue, but if we move people across to FR then the
> overnight update will stop.
> Does the FR upload convert case of Churches?
> E
> 
> On 20/10/2015 15:47, PatReynolds wrote:
> 
> Is this an open issue, if so what is the request?
> —
> Reply to this email directly or view
> it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/FreeUKGen/FreeUKGenProductIssues/issues/466#issuecomment-149591595
> .

## 

_\- -_

_Dr Pat Reynolds_
Executive Director
Free UK Genealogy  http://www.freeukgenealogy.org.uk/
A charity registered in England and Wales, number 1096940

​+44 ​1904 541411​ +44 7943 145387

36 Albemarle Road, York, YO23 1ER, UK

**Comment by PatReynolds** [comment]
Hi Kirk,

I didn't think this needed input from Mike - I was just unclear as to
whether the problem had been addressed or not.

Are we saying that no matter how often Mike change the place name, it will
revert?  Sorry, I'm being very slow on the uptake on this.

Thanks,

Pat

On Tuesday, 20 October 2015, Kirk Dawson notifications@github.com wrote:

> Mike will never see unless copied.
> 
> The nightly update will never stop;
> 
> All files from what ever source are treated by the same software so this
> will still happen
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/FreeUKGen/FreeUKGenProductIssues/issues/466#issuecomment-149594926
> .

## 

_\- -_

_Dr Pat Reynolds_
Executive Director
Free UK Genealogy  http://www.freeukgenealogy.org.uk/
A charity registered in England and Wales, number 1096940

​+44 ​1904 541411​ +44 7943 145387

36 Albemarle Road, York, YO23 1ER, UK

**Comment by Sherlock21** [comment]
The real point of this original Problem ticket was and still is: CASE of Church name is getting changed wrongly between the Transcriber's file as uploaded, to the result of the batch as seen in FR.
in particular the one Michael refers to  St Peter ad Vincula in his file comes out as St Peter Ad Vincula in FR. and therby creates an unwanted additional church name.
And in this particular chase, I cannot change it for him, because the file is too big.

**Comment by Sherlock21** [comment]
Pat

You are correct in your assumption here.

The matter is live and needs rectifying please - as the my on Github on this topic.

Whats needed is to remove the font changing of church names.

EricB

**Comment by Captainkirkdawson** [comment]
I believe this is no longer an active requirement

**Comment by PatReynolds** [comment]
You are correct, Kirk.  I'll close.
