### ISSUE TITLE
Relocation of batch winall10(CAMCHHBA.CSV (MaryKay)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#467]
Issue reported by **MaryKay** at 2015-10-10 10:57:04 UTC
Time: 2015-10-10T10:49:49+00:00
Session ID: 76fbb040b1ed22d93a0896502f40fd6b
Problem Page URL: [/registers/5618eb00f493fdad39000557](/registers/5618eb00f493fdad39000557)
Previous Page URL: [http://freereg2.freereg.org.uk/places](http://freereg2.freereg.org.uk/places)
Reported Issue:
Whilst relocating this batch from Cherry Hinton St Andrew unspecified to Cherry Hinton St Andrew PR, the operation appears to have created a new church in Cherry Hinton called 540856c1eca9eb0248574506 (sounds like an address). 
I have tried relocating the batch to the correct location so as to destroy the new church.  The church box fills in as St Andrew (but is long enough to accommodate the 54etc) but relocates back to 540856c1eca9eb0248574506

The batch needs to sit with Cherry Hinton St Andrew PR and 540856c1eca9eb0248574506 got rid of.  Please could you sort this.

Not idea how this happened as I'd waited for the boxes before selecting the church (there is only the one for Cherry Hinton)

Thank you

![Screenshot](http://www.freereg.org.uk)

**Comment by Sherlock21** [comment]
I rectified the coded church name but cannot get the 2 entries of Parish Church batches to merge into the one.!!

**Comment by Captainkirkdawson** [comment]
There was only 1 church when I looked. 2 registers so I merged them
