### ISSUE TITLE
Active to inactive (ManCity)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#468]
Issue reported by **ManCity** at 2015-10-10 16:13:33 UTC
Time: 2015-10-10T16:07:38+00:00
Session ID: 2c07fd190bb8d264a29aaceaf46ac5ab
Problem Page URL: [/userid_details/5462b426e937907d70000632](/userid_details/5462b426e937907d70000632)
Previous Page URL: [http://freereg2.freereg.org.uk/userid_details/selection?option=Select%20specific%20userid](http://freereg2.freereg.org.uk/userid_details/selection?option=Select%20specific%20userid)
Reported Issue:
Transcriber has quit therefore needs to be changed from active to inactive - I got a message immediately saying:

The registrant Catherine Bradley at kraan.bradley@casema.nl and userid of bommel has been assigned to your syndicate.
Please make them welcome
The FreeREG Team

which suggests that Catherine, in this case, has just joined up when in fact she's quit and I just want her taken off.    

![Screenshot](http://www.freereg.org.uk)

**Comment by PatReynolds** [comment]
A version of issue #496
