### ISSUE TITLE
new place name for Suffolk (Julie-Harold)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#469]
Issue reported by **Julie-Harold** at 2015-10-10 17:09:01 UTC
Time: 2015-10-10T17:05:21+00:00
Session ID: 3ab1781c64d9ee99c22bc0a33ccfc99f
Problem Page URL: [/places/53cbf610eca9eb03a6009784](/places/53cbf610eca9eb03a6009784)
Previous Page URL: [http://www.freereg.org.uk/places?page=5](http://www.freereg.org.uk/places?page=5)
Reported Issue:
Could we add the place name Creeting St Peter in addition to Creeting St Mary - it is the neighbouring parish just to the west. 

Julie (Suffolk Coordinator)    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
ericb can you action with Julie

**Comment by Sherlock21** [comment]
New Place name now Created.
