### ISSUE TITLE
Multiple forenames

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeUKRegProductIssues#47]
EricB reports that multiple forenames are only found on search with all forenames as in F1

**Comment by Captainkirkdawson** [comment]
tried to find Charles Howard Broughton. of Dewsbury married on 26 Dec 1832.

If I put in his full 3 names, then it finds him.
If I just use one or the other first name, then result says: Nil.

It is from Batch WRYDEWMA3 by ericb.

**Comment by benwbrum** [comment]
This has been addressed in the source code, but as it was a problem in search record creation, it needs a rebuild to make the change visible for testing.

**Comment by Sherlock21** [comment]
Are we going to do such a rebuild then, in the present plan, before we go much further?

It will prevent many others raising the same issue.

EB

**Comment by Captainkirkdawson** [comment]
Yes one is planned but NOT yet scheduled. See 234

**Comment by graphiclunarkid** [comment]
Closing in favour of FreeUKGen/MyopicVicar#234
