### ISSUE TITLE
Only active userids displayed (MikeNL)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#470]
Issue reported by **MikeNL** at 2015-10-11 10:17:40 UTC
Time: 2015-10-11T10:12:33+00:00
Session ID: bdb255275b929eb7a8f80739a18c49e1
Problem Page URL: [/userid_details/selection?option=Select%20specific%20surname/forename](/userid_details/selection?option=Select%20specific%20surname/forename)
Previous Page URL: [http://freereg2.freereg.org.uk/userid_details/options](http://freereg2.freereg.org.uk/userid_details/options)
Reported Issue:
I have a userid for whom I have a transcription file to upload.

However, I have changed the status of this userid to inactive as the transcriber did not wish to carry on transcribing for FreeREG.

I cannot see her userid in the "Surname/Forename" option.

I can, however, see her userid if I use the "Email Address" option.

What is going on?    

![Screenshot](http://www.freereg.org.uk)

**Comment by PatReynolds** [comment]
Mike did not confirm that there was a continuing issue (notified 17th November) so presume solved.
