### ISSUE TITLE
Record count difference (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#471]
Issue reported by **REGManager** at 2015-10-11 11:45:26 UTC
Time: 2015-10-11T11:39:11+00:00
Session ID: 99a4b9f90a1f0e965ae75a0aa0b05125
Problem Page URL: [/freereg_contents/new](/freereg_contents/new)
Previous Page URL: [http://www.freereg.org.uk/](http://www.freereg.org.uk/)
Reported Issue:
It is the FR maintenance slot next week.  So I am doing my newsletter.  Part of that is the statistics.  I have put the new totals from the Database Contents/County list for each county into my spreadsheet and I get a total of 33,488,041, but the footer shows 33,944,295.  I would have expected my total to be slightly more than the footer because of any files uploaded today.
My spreadsheet shows a gain of 680,483 since 20 July, the last FR1 update.  This is what I would have expected.  So I suspect that the footer total is wrong.
Graphs coming out soon.  E    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
The footer will be incorrect due to the presence of the orphan records that is documented in 579
