### ISSUE TITLE
Syndicate active members listing (deo123)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#472]
Issue reported by **deo123** at 2015-10-11 15:05:09 UTC
Time: 2015-10-11T15:01:52+00:00
Session ID: 29a07114d32f7217d1f41880ca6442a4
Problem Page URL: [/userid_details](/userid_details)
Previous Page URL: [http://freereg2.freereg.org.uk/manage_syndicates/select_action](http://freereg2.freereg.org.uk/manage_syndicates/select_action)
Reported Issue:
As you can see fromt he attachment, I am only getting ONE userid per page.
I did come out and went back in but still the same.    

![Screenshot](http://www.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1444575909-33419-1861/Syndicate-active-members_listing.JPG)

**Comment by Captainkirkdawson** [comment]
Conflict with a new css cllass
