### ISSUE TITLE
Cannot select ID (alsibk)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#474]
Issue reported by **alsibk** at 2015-10-11 17:31:21 UTC
Time: 2015-10-11T17:25:41+00:00
Session ID: b6a1159dee38f0c6a42fedfed88b6be6
Problem Page URL: [/csvfiles/55f24141f493fd7f49078800/edit](/csvfiles/55f24141f493fd7f49078800/edit)
Previous Page URL: [http://freereg2.freereg.org.uk/freereg1_csv_files/55f15d79f493fd28fe000104/by_userid](http://freereg2.freereg.org.uk/freereg1_csv_files/55f15d79f493fd28fe000104/by_userid)
Reported Issue:
Only one ID (mine) in list. Trying to replace a file for transcriber----cannot select her ID.    

![Screenshot](http://www.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1444584681-30247-6818/ID_screen_5.jpg)

**Comment by Captainkirkdawson** [comment]
Resolved
