### ISSUE TITLE
Northamptonshire Duplicated entries caused by transfer between user-IDs in FR1? (AMSA)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#477]
Issue reported by **AMSA** at 2015-10-12 07:59:52 UTC
Time: 2015-10-12T07:38:42+00:00
Session ID: f798bd821fd1706ae3f3875886b93e95
Problem Page URL: [/registers/56089884f493fd1e2700545c](/registers/56089884f493fd1e2700545c)
Previous Page URL: [http://freereg2.freereg.org.uk/churches/54084766eca9eb02482bebac](http://freereg2.freereg.org.uk/churches/54084766eca9eb02482bebac)
Reported Issue:
Last night I transferred several files from the converter's user-id to the actual transcriber's user-id in FR1. I have been doing this (as requested by admin to get files registering under the actual transcriber) for years with no apparent problem. Today it appears that the transferred files are now included under BOTH IDs.  Converter: Windsurfing_Widow  Transcriber: mgeneas
My Northamptonshire stats have gone up a corresponding 9000-odd entries overnight.
I am uncomfortable making these changes in FR yet as it makes a discrepancy between FR1 & FR & cause confusion as to which version is correct     

![Screenshot](http://www.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1444636792-42354-9145/Scrrenshot.jpg)

**Comment by Captainkirkdawson** [comment]
EricD
Can you investigate this please as it deals with moving files in FR1. I do not have the access to assess the story

**Comment by edickens** [comment]
```
Hi Kirk,
It is the same problem that we identified recently where a file is
moved in FR1 but FR sees it as a new file in the new UserID, but
does not delete it from the old UserID.  This creates duplicates in
FR.  I have said to CCs that moving files in FR1 should only be done
to correct errors and that they should be moved back the same day. 
The overnight update will then not see this as a change of UserID,
just an amendment.  The same problem will occur if the Change UserID
is used in FR but the file is not moved in FR1.  The overnight
update will see the file left in the old UserID in FR1 as a new
files as it no longer matches the UserID:Filename in FR.  Sandra is
making changes of UserID, but is also destroying the file in the old
UserID.
E
_____________________________________
```

Eric J Dickens
FreeREG Chairman
    On 12/10/2015 15:30, Kirk Dawson wrote:

```
  EricD
    Can you investigate this please as it deals with moving files in
    FR1. I do not have the access to assess the story
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by Captainkirkdawson** [comment]
You have me totally confused. The other problem you are referring to was when Ericb moved a file between userids within FR. There was an issue in the clean up following the move in that the file was removed from the FR copy of FR1 which led to it being identified as a new file for the old user by the syncing with FR1. This was fixed.
This is reported to be a problem of moving files between userids in FR1. As you know FR DOES NOT delete files that are deleted in FR1. It has no way of knowing that the file in FR is not legitimately there as a result of a direct upload.

**Comment by edickens** [comment]
```
Hi Kirk,
You are not confused (although I may not have expressed it very
well) because your last paragraph is correct.
Eric

On 12/10/2015 16:25, Kirk Dawson wrote:


  You have me totally confused. The other problem you are
    referring to was when Ericb moved a file between userids within
    FR. There was an issue in the clean up following the move in
    that the file was removed from the FR copy of FR1 which led to
    it being identified as a new file for the old user by the
    syncing with FR1. This was fixed.
    This is reported to be a problem of moving files between userids
    in FR1. As you know FR DOES NOT delete files that are deleted in
    FR1. It has no way of knowing that the file in FR is not
    legitimately there as a result of a direct upload. 
  —
    Reply to this email directly or view
      it on GitHub.
```
