### ISSUE TITLE
Edit function (milliemoll)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#478]
Issue reported by **milliemoll** at 2015-10-12 10:07:37 UTC
Time: 2015-10-12T10:03:21+00:00
Session ID: 0f85514980c1859372e3b2d15b188d4e
Problem Page URL: [/freereg1_csv_entries/54639d36e9379027829a2623](/freereg1_csv_entries/54639d36e9379027829a2623)
Previous Page URL: [http://www.freereg.org.uk/freereg1_csv_entries/54639d36e9379027829a2623/edit](http://www.freereg.org.uk/freereg1_csv_entries/54639d36e9379027829a2623/edit)
Reported Issue:
I successfully edited this record - but unwittingly added a date of birth.
I have tried to edit this record again but I cannot seem to eliminate this date of birth.

![Screenshot](http://www.freereg.org.uk)

**Comment by Sherlock21** [comment]
Millie
Have you unlocked the file after you did the first edit? You need to go the the LIST ALL FILES action button (LH side column in your activities. find file concerned, then Unlock it.
Then go back to the Edit file place (where you edited it the first time) & put it make the change you want.  A bit of a long way round, I agree butt///////

**Comment by PatReynolds** [comment]
Is this resolved?

**Comment by Captainkirkdawson** [comment]
Identical to 479 which is resolved
