### ISSUE TITLE
Edit function (milliemoll)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#479]
Issue reported by **milliemoll** at 2015-10-12 10:20:04 UTC
Time: 2015-10-12T10:17:10+00:00
Session ID: 0f85514980c1859372e3b2d15b188d4e
Problem Page URL: [/freereg1_csv_entries/54639d36e9379027829a2623](/freereg1_csv_entries/54639d36e9379027829a2623)
Previous Page URL: [http://www.freereg.org.uk/freereg1_csv_entries/54639d36e9379027829a2623/edit](http://www.freereg.org.uk/freereg1_csv_entries/54639d36e9379027829a2623/edit)
Reported Issue:
Further to my last query re accidentally adding a date of birth.

I have changed the d of b from 1 Feb 1810 to 1852 successfully.

It will not allow me to not have a date of birth which is the required state.    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Definite bug

**Comment by Captainkirkdawson** [comment]
Fixed
