### ISSUE TITLE
Roadmap (deo123)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#480]
Issue reported by **deo123** at 2015-10-12 11:10:32 UTC
Time: 2015-10-12T11:08:04+00:00
Session ID: 1bd883ddfd75c8aeb991de70e054195e
Problem Page URL: [/manage_resources/system-documents/development-roadmap](/manage_resources/system-documents/development-roadmap)
Previous Page URL: [http://www.freereg.org.uk/manage_resources/new](http://www.freereg.org.uk/manage_resources/new)
Reported Issue:
Hi Kirk,

seems there is  still a problem with this site.

Last night I was working from my iPad.  This is from Windows 7 on my laptop.

Regards Doreen    

![Screenshot](http://www.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1444648232-42354-0496/for_Kirk_RoadMap.JPG)

**Comment by Captainkirkdawson** [comment]
Have found a better way of making the link. will deploy this evening

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1
