### ISSUE TITLE
no marriage dates in file (deo123)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#481]
Issue reported by **deo123** at 2015-10-12 11:31:50 UTC
Time: 2015-10-12T11:29:13+00:00
Session ID: 02c000617b114021a9bbc5ad3e513eb6
Problem Page URL: [/freereg1_csv_entries](/freereg1_csv_entries)
Previous Page URL: [http://www.freereg.org.uk/freereg1_csv_files/55a31432f493fd2750014428](http://www.freereg.org.uk/freereg1_csv_files/55a31432f493fd2750014428)
Reported Issue:
Hi.

CONJUSMA  Userid= windingwool

Is not hsowing Marriage dates. I have check with F1 and the dates are there, I have two screen shots, So I presume I would have to send this "report a problem" twice.

Regards Doreen    

![Screenshot](http://www.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1444649510-42354-0618/F1-St_Just-in-Penwith_Mar_CONJUSMA.JPG)

**Comment by Captainkirkdawson** [comment]
The file directly uploaded into FR on Oct 9 had no dates
