### ISSUE TITLE
part2 of No marriage dates. (deo123)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#482]
Issue reported by **deo123** at 2015-10-12 11:33:22 UTC
Time: 2015-10-12T11:31:51+00:00
Session ID: 02c000617b114021a9bbc5ad3e513eb6
Problem Page URL: [/freereg1_csv_entries](/freereg1_csv_entries)
Previous Page URL: [http://www.freereg.org.uk/feedbacks/new?utf8=%E2%9C%93&feedback_time=2015-10-12+11%3A29%3A13+UTC&session_id=02c000617b114021a9bbc5ad3e513eb6&user_id=deo123&problem_page_url=%2Ffreereg1_csv_entries&previous_page_url=http%3A%2F%2Fwww.freereg.org.uk%2Ffreereg1_csv_files%2F55a31432f493fd2750014428&feedback_type=issue](http://www.freereg.org.uk/feedbacks/new?utf8=%E2%9C%93&feedback_time=2015-10-12+11%3A29%3A13+UTC&session_id=02c000617b114021a9bbc5ad3e513eb6&user_id=deo123&problem_page_url=%2Ffreereg1_csv_entries&previous_page_url=http%3A%2F%2Fwww.freereg.org.uk%2Ffreereg1_csv_files%2F55a31432f493fd2750014428&feedback_type=issue)
Reported Issue:
Hi,

this screen shot is of FR showing no date, but if you look at the decdale is show the diffentent decades.

Regards Doreen    

![Screenshot](http://www.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1444649602-42354-9995/FR-St_Just-in-Penwith_Mar_CONJUSMA.JPG)

**Comment by Captainkirkdawson** [comment]
See 481
