### ISSUE TITLE
Fr files for a give USerid out of sequence. (deo123)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#483]
Issue reported by **deo123** at 2015-10-12 11:38:22 UTC
Time: 2015-10-12T11:33:42+00:00
Session ID: 02c000617b114021a9bbc5ad3e513eb6
Problem Page URL: [/freereg1_csv_files?page=](/freereg1_csv_files?page=)
Previous Page URL: [http://www.freereg.org.uk/freereg1_csv_entries?page=9](http://www.freereg.org.uk/freereg1_csv_entries?page=9)
Reported Issue:
Hi,

yes me again.

While checking the previous reported problem, I came across this one.

Userid=windingwool>CONJUSMA>SH>browse records in batch>select page 5>select page 9>click list batches in this userid

The batch are all out of order.

Regards Doreen

![Screenshot](http://www.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1444649902-42354-9294/Batches_out_of_order_in_listing.JPG)

**Comment by PatReynolds** [comment]
Doreen responded "as we now have slide side bar's, I think this one is redundant"
