### ISSUE TITLE
Inconsistent use of Yes/No and True/False (MikeNL)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#484]
Priority 8 (0	1	2	5)

Issue reported by **MikeNL** at 2015-10-13 09:17:07 UTC
Time: 2015-10-13T09:15:01+00:00
Session ID: 599273e9adc27e32ab14f49ff14f4d82
Problem Page URL: [/freereg1_csv_files/55eb9880f493fd55e9005f46/edit](/freereg1_csv_files/55eb9880f493fd55e9005f46/edit)
Previous Page URL: [http://www.freereg.org.uk/freereg1_csv_files/55eb9880f493fd55e9005f46](http://www.freereg.org.uk/freereg1_csv_files/55eb9880f493fd55e9005f46)
Reported Issue:
I feel that only one of the combinations of Yes/No and True/False should be used on a single page. The two combinations are mixed on this page.    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Agree we are inconsistent but changing from a string to a boolean in the database is a major undertaking. We can fake it if others feel this is required

**Comment by Captainkirkdawson** [comment]
Consistent usage on page stated; will do other pages as opportunity permits
