### ISSUE TITLE
Suggestion (MikeNL)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#485]
Issue reported by **MikeNL** at 2015-10-13 12:11:38 UTC
Time: 2015-10-13T12:10:17+00:00
Session ID: 9f166e200818125005675aa67bf7cd15
Problem Page URL: [/freereg_contents/Staffordshire](/freereg_contents/Staffordshire)
Previous Page URL: [http://freereg2.freereg.org.uk/freereg_contents/new](http://freereg2.freereg.org.uk/freereg_contents/new)
Reported Issue:
Although the lines are separated by quite some distance, would it be an idea to shade alternate lines differently ala the old 132 column computer printout stationery?    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
I find this absolutely hilarious, I initially stripped all of our tables. I was asked to remove the stripping by the Exec Dir

**Comment by edickens** [comment]
People have different opinions and preferences.   We have to be careful not to react to a single suggestion but canvas opinions.   This is where we need overall management moderation of ideas that are put forward.  E

**Comment by Captainkirkdawson** [comment]
alternates are show on test3; record display baptisms striped; burials marriages not

**Comment by PatReynolds** [comment]
This is 548, I think (accessibility).

Beste wishes,

Pat

## 

_\- -_

_Dr Pat Reynolds_
Executive Director
Free UK Genealogy  http://www.freeukgenealogy.org.uk/
A charity registered in England and Wales, number 1096940

​+44 ​1904 541411​ +44 7943 145387

36 Albemarle Road, York, YO23 1ER, UK
