### ISSUE TITLE
Cannot move to next/previous page after selecting a specific page (steveroland)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#486]
Issue reported by **steveroland** at 2015-10-13 12:14:50 UTC
Time: 2015-10-13T12:10:13+00:00
Session ID: d20f2e1cffecff491930d8006b69e868
Problem Page URL: [/freereg1_csv_files/54639d76e9379010fc977c6c](/freereg1_csv_files/54639d76e9379010fc977c6c)
Previous Page URL: [http://www.freereg.org.uk/freereg1_csv_entries/54639d7ee9379010fc97b7dd](http://www.freereg.org.uk/freereg1_csv_entries/54639d7ee9379010fc97b7dd)
Reported Issue:
When the 'Select page of records in batch' option is used to select a page in a large file, it would be useful if you could then use the next or previous page buttons. If you try to use them, you get bumped back to the Select page screen.    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Option is being removed and being replaced by a scrollable table

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1
