### ISSUE TITLE
Listing of batches to be processed for my user name but all for Staffordshire (milliemoll)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#488]
Issue reported by **milliemoll** at 2015-10-14 09:58:20 UTC
Time: 2015-10-14T09:46:31+00:00
Session ID: a2647553cf0de41e5eb7579bc8f51dff
Problem Page URL: [/freereg1_csv_files/selection?option=List%20files%20waiting%20to%20be%20processed](/freereg1_csv_files/selection?option=List%20files%20waiting%20to%20be%20processed)
Previous Page URL: [http://www.freereg.org.uk/freereg1_csv_files/my_own](http://www.freereg.org.uk/freereg1_csv_files/my_own)
Reported Issue:
I logon as me.
Right hand column click on batches
Left hand column click on files to be processed.
I expected to see the file listed for Kelloe DURKELBA2.CSV that had been reported as not processed overnight as the file had been locked.
I saw listed about 10 files for STS (Staffordshire) going back to October 4 2015.

I have unlocked the Kelloe file - would that cause the non processed file to be removed from the list?

I have made an alteration to one of my files and put it for reprocessing. This has appeared at the top of the list.
I do not appear to have screenshot facility btw

![Screenshot](http://www.freereg.org.uk)

**Comment by edickens** [comment]
```
Hi Amanda,
If a file is not processed in the overnight update it has to be
resubmitted AND it has to have the date amended, otherwise the
update thinks that it has not been changed.
But very soon we will move to the new website.  This will avoid all
of these problems.
Regards,
Eric

On 14/10/2015 10:58, FreeUKGenIssues
  wrote:


  Issue reported by milliemoll at 2015-10-14
    09:58:20 UTC
    Time: 2015-10-14T09:46:31+00:00
    Session ID: a2647553cf0de41e5eb7579bc8f51dff
    Problem Page URL: /freereg1_csv_files/selection?option=List%20files%20waiting%20to%20be%20processed
    Previous Page URL: http://www.freereg.org.uk/freereg1_csv_files/my_own
    Reported Issue:
    I logon as me.
    Right hand column click on batches
    Left hand column click on files to be processed.
    I expected to see the file listed for Kelloe DURKELBA2.CSV that
    had been reported as not processed overnight as the file had
    been locked.
    I saw listed about 10 files for STS (Staffordshire) going back
    to October 4 2015.
  I have unlocked the Kelloe file - would that cause the non
    processed file to be removed from the list?
  I have made an alteration to one of my files and put it for
    reprocessing. This has appeared at the top of the list.
    I do not appear to have screenshot facility btw

  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by Captainkirkdawson** [comment]
The issue of showing all waiting files has been resolved. Other aspect on specifics is unknown to me
