### ISSUE TITLE
Selecting All places (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#489]
Issue reported by **REGManager** at 2015-10-15 08:07:14 UTC
Time: 2015-10-15T08:04:06+00:00
Session ID: d4445d5b5bae6f2607119feb39b7e7d7
Problem Page URL: [/](/)
Previous Page URL: [http://www.freereg.org.uk/manage_resources/new](http://www.freereg.org.uk/manage_resources/new)
Reported Issue:
Is it possible to put the word "All" in the blank row at the top of the list of places to create a positive action to select all places rather than just omitting to select a place?  E    

![Screenshot](http://www.freereg.org.uk)

**Comment by PatReynolds** [comment]
Identical to 118
