### ISSUE TITLE
Cannot download file (alsibk)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#49]
Issue reported by **alsibk** at 2014-11-01 15:23:28 UTC
Time: 2014-11-01T15:21:14+00:00
Session ID: 8d2e7445a6dcd75657bd794c653a6c5a
Problem Page URL: [/freereg1_csv_files](/freereg1_csv_files)
Previous Page URL: [http://test2.freereg.org.uk/manage_counties](http://test2.freereg.org.uk/manage_counties)
Reported Issue:

**Comment by Sherlock21** [comment]
Was this a user- specific issue Kirk, or a common one?
I can download my own batches and other WRY batches OK this morning.
EricB

**Comment by Sherlock21** [comment]
Can someone point me at the particular Batch please. I will give it a check , since i can download OK today.
EricB

**Comment by Sherlock21** [comment]
Kirk:
I had reported this morning, that download worked OK for me.

But I have just tried the Offending Batch that Ali reported yesterday, and I can't download that one!
Neither from starting at the List Active Places in WRY / Dewsbury Moor / WRYDWMBU.csv by marg?

NOR from list all batches in file name then download. No doubt its the same process once the Batch has been identified, but just incase the approach did anything bad to it, I tried both ways!

EricB

**Comment by Captainkirkdawson** [comment]
As noted on the FR2 page
PLEASE BE AWARE THAT THERE MAY BE ISSUES ARISING FROM THE SERVER MOVE IN OCTOBER THAT MEANS THAT THE DATABASE IS NOT ACTUALLY CONSISTENT WITH THE FILE BASE
Marg in FR1 does not have that file. That file was uploaded into FR2 in September and stored into the FR2 file set as well as appearing in the database. Then during the server move a more recent file set from FR1 was made the file set for FR2; that did not contain the uploaded file hence the  FR2 database cannot find the file. The issue will apply to all files uploaded into FR2  that do not exist in the October FR1 dataset. This will correct itself when FR2 is rebuilt. It is not a software problem.
