### ISSUE TITLE
Bouncing email generated by the server

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#490]
Issue reported by **Peter Ellis** at 2015-10-14 13:05:59 UTC
Time: 2015-10-14T12:36:34+00:00
Session ID: 
Problem Page URL: [unknown](unknown)
Previous Page URL: [http://www.freereg.org.uk/contacts/55108febe93790ccb644bf19/report_error?query=561e4c344325a65e5e001a25](http://www.freereg.org.uk/contacts/55108febe93790ccb644bf19/report_error?query=561e4c344325a65e5e001a25)
Reported Issue:
Hi

I am researching the Tebbutt family of Mears Ashby and may have come  across an anomaly in the data. On 16 February 1716 at St Andrew's in  Old a marriage takes place between Samuel Tebbutt of Holcot and Ann Garret of Old. Laer they will move to Mears Ashny and have 2 children Thomas and Mary. Unfortunately the record for Mears Ashby prior to their baptisms either do not exist or are illegible. That said when I attempt to find a baptism record for Ann Garret in England which is even remotely a match I find I cannot. However, in 1678  Thomas Garret of Old marries Mary Hain of Broughton and they have 7 children. One of the children baptised 2 Nov 1690 is named Mary, presumably after her mother. I cannot find any records after 1690 for Mary Garret....which is the reason for this query.  Is it possible the register was wrong at entry or t has been incorrectly transcribed or that Mary adopted the name of Ann to differentiate herself from her mother.  All the other data concerning Ann would they be as expected.

All the data is sourced from parish records. 

Garret’s of Old possibly related to Tebbutt’s of Holcot and Mears Ashby
Place   St Andrew, Old, Northamptonshire
Marriage date   14 Oct 1678
Groom   Thomas GARRET otp
Bride   Mary HAIN Broughton

Place   St Andrew, Old, Northamptonshire
Baptism date    02 Nov 1690
Person  Mary
Parents     Thomas GARRAT and wife Mary

Place   St Andrew, Old, Northamptonshire
MarriageDate    16 Feb 1716
Groom Details   Samuel TEBBUT of Holcot 
Bride Details   Ann Garret of Old

They move to Mears Ashby between 1716 and 1718

Baptism Records: Children of  Samuel and Ann Tebbutt (nee Garret) 

Place   All Saints, Mears Ashby, Northamptonshire 
BaptismDate 14 Sep 1718
Forename    Thomas
Parents     Samuel Tebat

Place   All Saints, Mears Ashby, Northamptonshire 
BaptismDate 15 Jan 1721
Forename    Mary
Parents     Samuel Tebat and wife Anne 

Kind Regards

Peter

![Screenshot](http://www.freereg.org.uk)

**Comment by edickens** [comment]
This message has bounced as it is hotmail.  Lemon has asked that we raise this as an issue.  He says...

> Microsoft had blocks on several more of our servers. What's puzzling 
> (and sort-of why I missed the mail at first check) is that these
> servers only ever send UKGEN-generated mail (which should always be
> not-spam), rather than distributing incoming mail (which is sometimes
> spam).
> 
> Either we are sending mail that their automated filtering thinks is
> spam or recipients are marking it as spam and that then informs the
> filters.
> 
> So this could happen again, I think. I don't know how many times we
> can be delisted before they say 'no'.

and to an aol bounce...
I will see if AOL have a gripe with us.

It might perhaps help if these mails looked less spammy, eg: URLs with
random-looking digits at the end are a common spammer technique to evade
fixed string filters, and thus come under suspicion themselves.
