### ISSUE TITLE
Revise Search does not handle mutiple-place selection.  [was: Search of Database (deo123)]

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#491]
Issue reported by **deo123** at 2015-10-15 13:28:42 UTC
Time: 2015-10-15T13:22:01+00:00
Session ID: 492ca9dc9e334fdde01d1497f0c373c5
Problem Page URL: [/search_queries/new](/search_queries/new)
Previous Page URL: [http://www.freereg.org.uk/manage_resources/new](http://www.freereg.org.uk/manage_resources/new)
Reported Issue:
Hi,

when searching the dadabase if I use the revise a search, it does NOT retain the place names selected, but retains just one of the place names.
As I only want to change the dates to reduce the number of results, it is annoying.

example..CORNWALL

if I select all the Place Names for "Isles of Scilly" then search, when I revise the search, it
only saves one of the Place Names. 

It would be nace the have a select all Scilly Isles please.

Regards Doreen    

![Screenshot](http://www.freereg.org.uk)

**Comment by benwbrum** [comment]
This will be handled in #609
