### ISSUE TITLE
Soundex not picking up a likely variation (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#494]
Issue reported by **REGManager** at 2015-10-17 15:11:22 UTC
Time: 2015-10-17T15:08:44+00:00
Session ID: 5562aa1da521e2887c5c793acdb87514
Problem Page URL: [/manage_resources/new](/manage_resources/new)
Previous Page URL: [http://www.freereg.org.uk/attic_files/select](http://www.freereg.org.uk/attic_files/select)
Reported Issue:
[From Cathy Jury but I destroyed the contact before converting it to an issue. - E]
I noticed today, by the way, that a Soundex search for ‘Gerrans’ does not bring up ‘Jerrans’. Shouldn’t G’s and J’s be interchangeable? Cathy    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Nor will it ever so do. 
Please see the definition of Soundex.
Quote: The Soundex code for a name consists of a letter followed by three numerical digits: the letter is the first letter of the name, and the digits encode the remaining consonants.  Unquote.
There are other phonetic algorithms available which could be considered as part of a rewrite/rebuild of the database.
