### ISSUE TITLE
Role in FreeREG on registration (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#495]
Issue reported by **REGManager** at 2015-10-18 11:27:51 UTC
Time: 2015-10-18T11:24:25+00:00
Session ID: e1e77f87007ae9b22f6f454e4d8feb7e
Problem Page URL: [/userid_details/561c02b9f493fdd8ec001352](/userid_details/561c02b9f493fdd8ec001352)
Previous Page URL: [http://www.freereg.org.uk/userid_details/selection?option=Select%20specific%20userid](http://www.freereg.org.uk/userid_details/selection?option=Select%20specific%20userid)
Reported Issue:
Sean has just registered with a Role in FreeREG of Technical.
Can a new transcriber, when opened to them, register at this high level?  I would think we need to ensure that above Transcriber can only be set up by SysAdmin editing their Profile.  E    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Any person registering in such a manner is Inactive and can do nothing until you as the coordinator decide to make them active and give them access. The control is already in place
I suggest you activate Sean!

**Comment by edickens** [comment]
```
I have made Sean Active but he did not select "Accepted Transcriber
Agreement".
Alison, I think something needs to go into the SC Help because I can
see SCs not making their new volunteers Active.  I missed that.  But
it is a good idea that the SC has to have the final say as to who
joins so that they make sure that they have signed up to the correct
things and skill level.  E
_____________________________________
```

Eric J Dickens
FreeREG Chairman
    On 18/10/2015 16:25, Kirk Dawson wrote:

```
  Any person registering in such a manner is Inactive and can do
    nothing until you as the coordinator decide to make them active
    and give them access. The control is already in place
    I suggest you activate Sean!
  —
    Reply to this email directly or view
      it on GitHub.
```
