### ISSUE TITLE
Inappropriate message to county co-ordinator (hawkinssm)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#496]
Issue reported by **hawkinssm** at 2015-10-18 15:51:35 UTC
Time: 2015-10-18T15:45:58+00:00
Session ID: 7cf712ecd1a7ed82a2672f5a4fea15b3
Problem Page URL: [/manage_resources/new](/manage_resources/new)
Previous Page URL: [http://freereg2.freereg.org.uk/refinery/login](http://freereg2.freereg.org.uk/refinery/login)
Reported Issue:
Changing a transcriber's status from Active to inactive results in a message such as:
The registrant Sarah Shaw at sarsha9@googlemail.com and userid of Sarsha9 has been assigned to your syndicate.

This is a sensible message only if the individual had been moving from Inactive to Active.    

![Screenshot](http://www.freereg.org.uk)

**Comment by PatReynolds** [comment]
This is happening on all changes relating to ID - e.g. request for new password.

**Comment by Captainkirkdawson** [comment]
This is not a bug but a feature change. The system does as it was designed to do

**Comment by PatReynolds** [comment]
Marked up as such.

**Comment by Captainkirkdawson** [comment]
Fixed
