### ISSUE TITLE
Search Report with Nearby - Problem with locations included. (ericb)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#497]
Issue reported by **ericb** at 2015-10-18 16:16:29 UTC
Time: 2015-10-18T16:05:54+00:00
Session ID: 5e336b8a5a3c704a5ed97577267b1483
Problem Page URL: [/search_queries/5623c35cf493fdf6cc000f2a](/search_queries/5623c35cf493fdf6cc000f2a)
Previous Page URL: [http://www.freereg.org.uk/search_queries/new?search_id=5623c315f493fd1ea20000c0](http://www.freereg.org.uk/search_queries/new?search_id=5623c315f493fd1ea20000c0)
Reported Issue:
Search of  HUDSON in LDN/ Cornhill WITH Nearby also finds a record from Ashton-under-Lyne in LAN.

Gridref of Ashton under Lyme is SJ938991 - [ this was last amened 11 Sep 2015 ] but was originally the TQ336805 default.    

![Screenshot](http://www.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1445184989-17315-3101/A-u-L.jpg)

**Comment by Sherlock21** [comment]
Cancel this one please. I have realised that this T3  Places & data list must be an old  one- before this issue had been changed in Production. Sorry!
