### ISSUE TITLE
Are transcribers going to be allowed to have different churches in one file? (MikeNL)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#499]
Issue reported by **MikeNL** at 2015-10-19 13:25:49 UTC
Time: 2015-10-19T13:21:31+00:00
Session ID: 0521f903a0d5400ea56318d646a048b6
Problem Page URL: [/information-for-transcribers](/information-for-transcribers)
Previous Page URL: [http://freereg2.freereg.org.uk/information-for-transcribers/uploading-files](http://freereg2.freereg.org.uk/information-for-transcribers/uploading-files)
Reported Issue:
This is what the help suggests.

Is it really a good idea to have this facility and, even if the facility is available, should it be publicised?    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
It is NOT recommended.
