### ISSUE TITLE
Email addresses with + fail (kirkdawson)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#50]
Issue reported by **kirkdawson** at 2014-11-02 14:34:17 UTC
Time: 2014-11-02T14:29:24+00:00
Session ID: dac698f563170485db74fad5e59e967a
Problem Page URL: [/userid_details/selection?user=email](/userid_details/selection?user=email)
Previous Page URL: [http://test2.freereg.org.uk/manage_freeregs](http://test2.freereg.org.uk/manage_freeregs)
Reported Issue:
On the selection of a userid containing a + fails

**Comment by Captainkirkdawson** [comment]
Fixed
