### ISSUE TITLE
Instructions for spreadsheet use (MikeNL)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#500]
Issue reported by **MikeNL** at 2015-10-19 13:36:15 UTC
Time: 2015-10-19T13:25:58+00:00
Session ID: 0521f903a0d5400ea56318d646a048b6
Problem Page URL: [/information-for-transcribers/creating-a-transcription-file](/information-for-transcribers/creating-a-transcription-file)
Previous Page URL: [http://freereg2.freereg.org.uk/information-for-transcribers](http://freereg2.freereg.org.uk/information-for-transcribers)
Reported Issue:
In the help, it states that column headings may be useful and would be useful if frozen.

If a transcriber adds these column headings, there is nothing in the help to say that this row of the spreadsheet should be removed before creating the CSV file from the spreadsheet, or that, after creating the CSV using the spreadsheet, the first line of the CSV file, which contains the column headings should be removed in the text editor.

Or is FreeREG capable of recognising this sort of line and ignoring it?    

![Screenshot](http://www.freereg.org.uk)

**Comment by AlOneill** [comment]
Apologies for omission. There are now two reminders: on Creating a transcription and File headers pages.

**Comment by AlOneill** [comment]
Fixed -- advised that field names row should be removed, either before or after creating the CSV file. Advice in 2 places: Creating a transcription file, File headers.
