### ISSUE TITLE
Cannot move a file between UserIDs (steveroland)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#501]
Issue reported by **steveroland** at 2015-10-19 14:23:27 UTC
Time: 2015-10-19T14:18:41+00:00
Session ID: ebdcd31891b6075ddeecfadda4e899c5
Problem Page URL: [/freereg1_csv_files/54d07534e9379089030554d4/change_userid](/freereg1_csv_files/54d07534e9379089030554d4/change_userid)
Previous Page URL: [http://www.freereg.org.uk/freereg1_csv_files/54d07534e9379089030554d4/change_userid](http://www.freereg.org.uk/freereg1_csv_files/54d07534e9379089030554d4/change_userid)
Reported Issue:
I have been consolidating my files into a single userID of steveroland from my other county specific IDs, but one file fails to move per the attached error. I have checked and there is no existing file called SRYBETBA for user steveroland, so I don't understand why it reports this problem.    

![Screenshot](http://www.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1445264607-60431-4774/Capture.jpg)

**Comment by Captainkirkdawson** [comment]
I have looked at the actual files and the system is not lying. There is  a
file SRYBETBE.CSV in your folder. It was moved there on Oct 17. The
original is still sitting there in  your Surrey alter ego.

Did you have a problem when you did the initial change?

Did anyone else try something to assist you?

**Comment by Captainkirkdawson** [comment]
Hi Kirk,

I first tried to move the file on 17th and it came back with the
"unsuccessful" message, so I left it and moved a bunch of other files
successfully. I then tried again and of course got the same message so
raised the problem report.

Although you can see the file in my folder, I cannot see it in my batches:

[image: Inline images 1]

and when I look under physical files, it shows as you say under my SRY ID
(and not under steveroland):

[image: Inline images 2]
How do I get it to show up under steveroland?

Thanks
Steve

**Comment by Captainkirkdawson** [comment]
Can you recall the original error message. That is important.

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Captainkirkdawson** [comment]
Suspect finger problem
