### ISSUE TITLE
There must be a better method than this!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! (MikeNL)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#502]
Issue reported by **MikeNL** at 2015-10-19 15:57:22 UTC
Time: 2015-10-19T15:49:18+00:00
Session ID: 2a8133183aa995f42c393e633a0c7695
Problem Page URL: [/information-for-transcribers/entering-data-from-registers](/information-for-transcribers/entering-data-from-registers)
Previous Page URL: [http://freereg2.freereg.org.uk/information-for-transcribers/uploading-files](http://freereg2.freereg.org.uk/information-for-transcribers/uploading-files)
Reported Issue:
To look a burial record field you have to scroll down many, many, many ... many lines.

This is certainly not useful for a quick lookup.    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
What would you suggest? We went to scrolling because coordinators disliked
the paging approach.

Any further changes will have to await a clear consensus on what is better.

**Comment by Captainkirkdawson** [comment]
MikeNL replied

I found the better method. There are shortcuts that I had not seen. Sorry about this one!
