### ISSUE TITLE
Register Types do not match list in Help (MikeNL)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#503]
Issue reported by **MikeNL** at 2015-10-19 22:18:37 UTC
Time: 2015-10-19T22:16:52+00:00
Session ID: 42e55e8cf310ba74f3fdf809d083e7be
Problem Page URL: [/freereg1_csv_files/update_registers?church=55e9b819f493fd09a7000d2c](/freereg1_csv_files/update_registers?church=55e9b819f493fd09a7000d2c)
Previous Page URL: [http://freereg2.freereg.org.uk/freereg1_csv_files/update_churches?place=5583614ef493fdf0f200169b](http://freereg2.freereg.org.uk/freereg1_csv_files/update_churches?place=5583614ef493fdf0f200169b)
Reported Issue:
Although shown in Help as valid I could not enter the "OR" register type from the drop down list.    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Help is ahead of the system
