### ISSUE TITLE
Error message while trying to submit a processing run. (MikeNL)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#504]
Issue reported by **MikeNL** at 2015-10-19 22:37:10 UTC
Time: 2015-10-19T22:34:12+00:00
Session ID: 42e55e8cf310ba74f3fdf809d083e7be
Problem Page URL: [/csvfiles](/csvfiles)
Previous Page URL: [http://freereg2.freereg.org.uk/csvfiles/new](http://freereg2.freereg.org.uk/csvfiles/new)
Reported Issue:
I have a file that has been successfully uploaded but when I try to action the "Process" buttone I receive this message:-
 "If you have arrived at page expecting to find the original freereg search page please note that that site is no longer supported but remains available at Original Freereg Website

If not click the return on your browser and renter your request."    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Saw this earlier today. Fix is awaiting people to go to bed so we can
deploy and restart the servers

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1
