### ISSUE TITLE
Refinery interferes with the flash message (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#505]
Issue reported by **REGManager** at 2015-10-20 06:43:40 UTC
Time: 2015-10-20T06:40:35+00:00
Session ID: 895be77fa0cee2a61d2966d0f7ca82fc
Problem Page URL: [/manage_resources/new](/manage_resources/new)
Previous Page URL: [http://www.freereg.org.uk/refinery/login](http://www.freereg.org.uk/refinery/login)
Reported Issue:
Although Kirk has changed the wording on the homepage so as not to direct transcribers to FR1, the log in as a transcriber just throws me back to the home page.  Does anyone else have a transcribe only UserID which they use to can check?  We are supposed to be open to transcribers now.  E    

![Screenshot](http://www.freereg.org.uk)

**Comment by edickens** [comment]
My mistake!!!  My UserID was not Active and I had not accepted the transcriber agreement.  all OK now!
But it does raise the question.  If a transcriber is thrown out and back to the home page, then a reason should be given, not just say "You have logged out".

**Comment by Captainkirkdawson** [comment]
I stumbled over the solution while looking for something else

**Comment by Captainkirkdawson** [comment]
I was wrong

**Comment by Captainkirkdawson** [comment]
Found alternate way. Inactive user now goes back to login page with a message
