### ISSUE TITLE
Batch list not showing for userid brisle (milliemoll)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#506]
Issue reported by **milliemoll** at 2015-10-20 11:23:15 UTC
Time: 2015-10-20T11:14:31+00:00
Session ID: 2d485a37a95306a860f46d0cf958512a
Problem Page URL: [/freereg1_csv_files/5462b41ce937907d700004b2/by_userid](/freereg1_csv_files/5462b41ce937907d700004b2/by_userid)
Previous Page URL: [http://www.freereg.org.uk/userid_details/5462b41ce937907d700004b2](http://www.freereg.org.uk/userid_details/5462b41ce937907d700004b2)
Reported Issue:
I am co-ordinator for Durham. I am trying to find the batch with typo 1917 for Middleton in Teesdale BT.
I found that John Morton has transcribed BT but he uploads to Somerset I believe.
I found his userid and info via the name tab.
Clicked on list batches - page appeared but no batches listed.
Is this to be expected? Or should I be able to see batches to check for typos etc?

Amanda    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
As the county coordinator you can see all of the files that have been
loaded for Durham; no matter in which syndicate they are located.

If you go to Middleton in Teesdale as the CC. I suggest you use the select
specific place or the active places display. Go down to the Register for
BTs and have a look at the various files you will see that you actually
uploaded all of the files on behalf of John Morton.

The file "DURMITMA.CSV (milliemoll) in Bishop's Transcripts of St Mary the
Virgin in Middleton in Teesdale of Durham" is the file that has the records
in error.

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by PatReynolds** [comment]
Seems to be resolved.
