### ISSUE TITLE
batch showing 1863 as latest record date (milliemoll)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#508]
Issue reported by **milliemoll** at 2015-10-20 12:58:05 UTC
Time: 2015-10-20T12:50:32+00:00
Session ID: 2d485a37a95306a860f46d0cf958512a
Problem Page URL: [/freereg1_csv_entries](/freereg1_csv_entries)
Previous Page URL: [http://www.freereg.org.uk/freereg1_csv_files/55ada541f493fd92c002a956](http://www.freereg.org.uk/freereg1_csv_files/55ada541f493fd92c002a956)
Reported Issue:
Hi

I have found two other date errors and changed those.

I have searched through 'find' facility for the 1863 and looked on my own as well but I do not see it.

Amanda

![Screenshot](http://www.freereg.org.uk)

**Comment by dougkdev** [comment]
I am unable to reproduce this.  When I log in to FreeReg and follow the
link to the batch
http://www.freereg.org.uk/freereg1_csv_files/55ada541f493fd92c002a956 it
says maximum year in the dataset is 1796.  Has this already been fixed, or
is there somewhere else that is showing it as 1863?  If so, where is this
error being seen?

**Comment by dougkdev** [comment]
Although I cannot reproduce for this batch, it sounds like this may have
been the same issue as in #575 and #519?

**Comment by Captainkirkdawson** [comment]
Personally I would not put any more effort into this.
