### ISSUE TITLE
Locating Batches with possible date errors as shown on decadal reports. (ericb)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#51]
Issue reported by **ericb** at 2014-11-03 11:23:38 UTC
Time: 2014-11-03T11:14:15+00:00
Session ID: b0811d4b8276285278c496beb3e49645
Problem Page URL: [/freereg1_csv_files](/freereg1_csv_files)
Previous Page URL: [http://test2.freereg.org.uk/manage_counties?](http://test2.freereg.org.uk/manage_counties?)
Reported Issue:
The present decadal report shows up batches that have a potential date-year problem. This is fine if one is looking at a single Batch data report.
But it is not practicable as a means of finding ALL the possible such Batches in a County.
Can we have a view which shows ALL the Batches (in Active Places) within each County, in decadal format, all on one A4 landscape form. Exactly like was produced when the decadal concept was introduced in F1 please?
If it could incorporate an "Accept" flag for those that genuinely do have gaps in the data,  so the CC does not keep reviewing the same batch over and over again that would be a great help.

**Comment by Captainkirkdawson** [comment]
This is not a product fault but a system enhancement, It has been documented as story 246. This fault report will be closed.

**Comment by graphiclunarkid** [comment]
Closing in favour of FreeUKGen/MyopicVicar#246 as per Kirk's note
