### ISSUE TITLE
Delete User ID (alsibk)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#510]
Issue reported by **alsibk** at 2015-10-21 09:44:01 UTC
Time: 2015-10-21T09:39:53+00:00
Session ID: 26670317b30b2baba51d5db28526cea6
Problem Page URL: [/userid_details/5462b406e937907d700000fe/edit](/userid_details/5462b406e937907d700000fe/edit)
Previous Page URL: [http://www.freereg.org.uk/userid_details/5462b406e937907d700000fe](http://www.freereg.org.uk/userid_details/5462b406e937907d700000fe)
Reported Issue:
No apparent  delete User ID function.    

![Screenshot](http://www.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1445420641-76675-9240/User_delete.jpg)

**Comment by Captainkirkdawson** [comment]
Designed that way; system manager has ability if really needed.
