### ISSUE TITLE
Search result concerns(Robin Lasbury)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#511]
Issue reported by **Robin Lasbury** at 2015-10-21 11:54:52 UTC
Time: 2015-10-21T11:38:00+00:00
Session ID: 
Problem Page URL: []()
Previous Page URL: [http://www.freereg.org.uk/contacts/new](http://www.freereg.org.uk/contacts/new)
Reported Issue:
I have noticed new Freereg searches differently to old Freereg.

I often have a need to search for a marriage where I only know the groom surname and the bride forename, and old Freereg  found what I was looking for.

As an example I placed the following in the search fields
Surname = horler
Forename = jane
County = somerset
Type = marriage

Old Freereg returns 31 results, searching across all fields

New Freereg returns 11 results, and it seems to make no difference whether I tick the "Family Members" option. The tick box appears to offer a search across all fields but it does not deliver any more results than when un-ticked.

Do I have a correct understanding of this "Family Members" feature and I am using it as intended?

Is this feature in fact working?

Is there any way I can obtain the results I am used to from using old Freereg?

Regards
Robin Lasbury

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Marriage search in FR is different from the old one and more rational
