### ISSUE TITLE
film/film number on record (deo123)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#513]
Issue reported by **deo123** at 2015-10-21 14:39:16 UTC
Time: 2015-10-21T14:35:24+00:00
Session ID: 83450bd5b064d32d331e06f3798e3e00
Problem Page URL: [/freereg1_csv_entries/551f35d3f493fd795e0026a1/edit](/freereg1_csv_entries/551f35d3f493fd795e0026a1/edit)
Previous Page URL: [http://www.freereg.org.uk/freereg1_csv_entries](http://www.freereg.org.uk/freereg1_csv_entries)
Reported Issue:
Hi,

Should the "Film" = Film No.
and "Film Number" = Image No.

Also are these two fields only visible on Editing?  It really should be on the show page, as I often get queries and they would be easier to pin point the record.

Regards Doreen    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Added in passing
