### ISSUE TITLE
Add Batch Count and Sort to List Batches (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#515]
Issue reported by **REGManager** at 2015-10-21 15:28:13 UTC
Time: 2015-10-21T15:22:37+00:00
Session ID: c2704edef5a2494e7793700f7c7676a5
Problem Page URL: [/freereg1_csv_files/5462b41de937907d700004df/by_userid](/freereg1_csv_files/5462b41de937907d700004df/by_userid)
Previous Page URL: [http://www.freereg.org.uk/userid_details/5462b41de937907d700004df](http://www.freereg.org.uk/userid_details/5462b41de937907d700004df)
Reported Issue:
When selecting UserID/List Batches the batches are in batch name order, although sometimes not.  So a Sort on Batch Name and another on Date and perhaps Place will make it easier to find an entry.
A batch count is also useful, particularly now for reconciliation when tidying up and moving batches.  Not urgent.  Thanks E    

![Screenshot](http://www.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1445441293-76675-5783/Capture.JPG)

**Comment by Captainkirkdawson** [comment]
The current order is by batch name

![capture](https://cloud.githubusercontent.com/assets/2874694/10641844/330a3f9c-77d8-11e5-8f08-822657554653.JPG)

**Comment by edickens** [comment]
```
But I don't get this when looking at a specific UserID.  E
_____________________________________
```

Eric J Dickens
FreeREG Chairman
    On 21/10/2015 16:43, Kirk Dawson wrote:

```
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by Captainkirkdawson** [comment]
Buts that's what the transcriber gets; the coordinators get more

**Comment by PatReynolds** [comment]
Is this resolved?

**Comment by Captainkirkdawson** [comment]
Not to my knowledge

**Comment by edickens** [comment]
Not important.  Close this.  Wait for feedback from CC and SC in the light of operational experience.  E
