### ISSUE TITLE
Results included from year after last search year

### ISSUE THREAD

**Issue by dougkdev** [FreeUKGen/FreeUKRegProductIssues#517]
Records that have only a year (without day/month) from the year after the "last year" specified in a search are returned. All results that should be shown are shown, we are just seeing extras that shouldn't be shown.

To reproduce: search for surname Salmon, all record types, first year: 1810, last year: 1810, Norfolk.
Results in two extra results (a baptism and a marriage from 1811).

Proposed fix: in lib/date_parser self.end_search_date(), use "#{year}-12-31" in the else instead of "#{next_year}-01-01"

**Comment by dougkdev** [comment]
unless we are doing a less-than instead of less-than-or -equal, then the proposed fix needs to be modified to account for Dec 31.

**Comment by FreeUKGenIssues** [comment]
No objection, but we need to make sure that we handle split dates (March 25
as New Year) as well as "1700-*-05"
