### ISSUE TITLE
Incorrect earliest date of register in summary (susiem)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#519]
Issue reported by **susiem** at 2015-10-22 07:18:10 UTC
Time: 2015-10-22T07:03:04+00:00
Session ID: 7dbcc385647d153701719fded23e79ce
Problem Page URL: [/freereg1_csv_files/5463ae35e937904abbf3f772](/freereg1_csv_files/5463ae35e937904abbf3f772)
Previous Page URL: [http://www.freereg.org.uk/freereg1_csv_files](http://www.freereg.org.uk/freereg1_csv_files)
Reported Issue:
NBLBAMBU1 userid Tickettyboo shows the summary earliest date as 1172, when it should be 1762. This is then repeated throughout the search information for the registers.
Eric Wealleans nejws05    

![Screenshot](http://www.freereg.org.uk)

**Comment by PatReynolds** [comment]
Seems to be #575

**Comment by Captainkirkdawson** [comment]
User has corrected data
