### ISSUE TITLE
Lock/Unlock (alsibk)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#52]
Issue reported by **alsibk** at 2014-11-04 08:23:16 UTC
Time: 2014-11-04T08:17:48+00:00
Session ID: 4b91db35cfb9ce772157b2ba975e076a
Problem Page URL: [/freereg1_csv_files/5409f744eca9eb718294c7d1](/freereg1_csv_files/5409f744eca9eb718294c7d1)
Previous Page URL: [http://test2.freereg.org.uk/freereg1_csv_files](http://test2.freereg.org.uk/freereg1_csv_files)
Reported Issue:
There is no Lock/Unlock facility on the Show specific batch page..

**Comment by Captainkirkdawson** [comment]
There is as part of FR2.1.0
