### ISSUE TITLE
Password change request fails if transcriber agreement not accepted (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#520]
Issue reported by **REGManager** at 2015-10-22 08:02:25 UTC
Time: 2015-10-22T07:59:40+00:00
Session ID: 517ab9458058d16c7eb60ba3667ec75c
Problem Page URL: [/manage_resources/new](/manage_resources/new)
Previous Page URL: [http://www.freereg.org.uk/userid_details/5462b41de937907d700004dd](http://www.freereg.org.uk/userid_details/5462b41de937907d700004dd)
Reported Issue:
If the password change request is requested when the transcriber agreement is set as not accepted, then the red "There is a problem" comes up.  Setting the transcriber agreement to accept lets the password change request go ahead.  E    

![Screenshot](http://www.freereg.org.uk)

**Comment by edickens** [comment]
This does not seem to be the problem.
I have tried the procedure and can see how there can be confusion when someone wants to reset their password. ...
- After selecting Reset password, if you enter an email address that does not exist, nothing seems to happen.  There is no report to say that the email address does not exist.  You have to guess that that is the problem.
- When you enter the correct email address, it takes you to the Log in screen.  But I had not reset my password by then.  You are given the script on the login screen again, which  I think looks as if your request has not worked.  I think that there should be a message to say that an email has been sent and this should be found and actioned before logging in.
- The system does work, and if you read the instructions and do them then there is no problem.  But people don't seem to be able to do that!!  E
