### ISSUE TITLE
Report states editing of email address is successful, in error (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#525]
Issue reported by **REGManager** at 2015-10-22 15:04:31 UTC
Time: 2015-10-22T15:01:11+00:00
Session ID: 0b45adec8442e796a768f34bf6ac4aa7
Problem Page URL: [/userid_details/55a4d1c8f493fdf27d000030/edit](/userid_details/55a4d1c8f493fdf27d000030/edit)
Previous Page URL: [http://www.freereg.org.uk/userid_details/55a4d1c8f493fdf27d000030](http://www.freereg.org.uk/userid_details/55a4d1c8f493fdf27d000030)
Reported Issue:
I am trying to correct this email address in the UserID ChristineH.  It is showing as..
Echristineharris377+1@gmail.com
but should not have the E on the front or the +1.  After Edit the report is "Successful" and this is not a duplicate email address.    

![Screenshot](http://www.freereg.org.uk)

**Comment by edickens** [comment]
Sorry.  This email address IS a Duplicate.  The E and +1 are added by the server.   But the confusion is that the report said that the update was successful.  E

**Comment by Captainkirkdawson** [comment]
Solution prepared. Ready for deployment

**Comment by edickens** [comment]
I am still trying to amend Damien's email address, but now get an Unsuccessful update - see attached.  It looks like a duplicate email address, but that is not the case.  He wants to replace the damien with freereg.  Thoughts?  E
![capture](https://cloud.githubusercontent.com/assets/8876165/11897825/deee6178-a58a-11e5-8523-5f3e49b3dd67.JPG)

**Comment by Captainkirkdawson** [comment]
This is not a bug. The system is stating that the email address you are trying to enter already exists in the system.  Any further investigation requires the email address you are trying to assign.

**Comment by edickens** [comment]
```
I am trying to assign freereg@dcpendleton.plus.com but this is not
listed when I select to list by email address.  E

On 18/12/2015 15:32, Kirk Dawson wrote:


  This is not a bug. The system is stating that the email address
    you are trying to enter already exists in the system. Any
    further investigation requires the email address you are trying
    to assign.
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by Captainkirkdawson** [comment]
DamienS-P (freereg@dcpendleton.plus.com) added Tuesday, 20 October 2015 is the entry in refinery. Have destroyed the userid. Recreate with email address he prefers
