### ISSUE TITLE
Reset password appears to have a problem (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#527]
Issue reported by **REGManager** at 2015-10-22 21:28:37 UTC
Time: 2015-10-22T21:25:30+00:00
Session ID: b0421f81124f6b49252d7e9847c15e19
Problem Page URL: [/userid_details/55aeabddf493fd8066001413](/userid_details/55aeabddf493fd8066001413)
Previous Page URL: [http://www.freereg.org.uk/userid_details/selection?option=Select%20specific%20userid](http://www.freereg.org.uk/userid_details/selection?option=Select%20specific%20userid)
Reported Issue:
I have had more emails than I would expect from people not being able to reset their password.  It may be the description of what they need to do, or there is a problem.  This is an example...

I have a problem with one of my transcribers who cannot login to the new site - Tim Green (Tim37). He has tried the 'Reset password' link but says he never received an email. So I tried to go into his profile to change his email address to mine so that I could reset his password, but I am unable to change his email address.
Steve Biggs SSX CC    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
There are 2 reasons why a person does not get an email after a password
reset is sent.  1) the email address is incorrect; if it is the coordinator
can correct it 2) his email spam filter has determined it is spam. The
latter can usually be avoided by the person putting our email address in
their address book. (reg-web@freereg.org.uk)

Any coordinator/system administrator can edit the email address  and send
out a password reset.

The userid edit is as shown in the attached. Any green box can be edited.

No one can change an email address to an existing one:. email addresses
must be unique

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Captainkirkdawson** [comment]
Thanks Kirk,

It was the point that I forgot at first - I then realised and changed the
email to one of mine not used already in FR. I'm guessing his first email
did go in his spam folder.

Steve

On Friday, 23 October 2015, Kirk Dawson kirk.dawson.bc@gmail.com wrote:

> There are 2 reasons why a person does not get an email after a password
> reset is sent.  1) the email address is incorrect; if it is the coordinator
> can correct it 2) his email spam filter has determined it is spam. The
> latter can usually be avoided by the person putting our email address in
> their address book. (reg-web@freereg.org.uk
> <javascript:_e(%7B%7D,'cvml','reg-web@freereg.org.uk');>)
> 
> Any coordinator/system administrator can edit the email address  and send
> out a password reset.
> 
> The userid edit is as shown in the attached. Any green box can be edited.
> 
> No one can change an email address to an existing one:. email addresses
> must be unique
> 
> Kirk Dawson
> Fairmont Hot Springs, B.C.
> V0B 1L1

## 

Sent from Gmail Mobile
