### ISSUE TITLE
Open to new Transcribers (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#529]
Issue reported by **REGManager** at 2015-10-23 11:47:27 UTC
Time: 2015-10-23T11:41:49+00:00
Session ID: 4f6dfd6b0e29cb161ec2fbc0018f8c17
Problem Page URL: [/manage_resources/new](/manage_resources/new)
Previous Page URL: [http://www.freereg.org.uk/refinery/login](http://www.freereg.org.uk/refinery/login)
Reported Issue:
Following yesterday's meeting I would like to reinstate the Volunteer Link, perhaps not in the header, but in the Footer as "Become a transcriber".
But if we do, then we need to consider what to say about the Transcriber Agreement which is not ready  yet.
If we don't do this, I will have to set everyone up by using "Create a UserID" using details emailed to me by SCs or the volunteer.  This is not a serious problem, but the Coordinators need to know and their instructions amended accordingly, because at present a new volunteer has to register in FR1 then I copy it across, but we want to get away from FR1 and they need to register direct into FR.  E    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
test3 has the link in the footer with some new text

**Comment by edickens** [comment]
Have had a problem with a new volunteer not getting the password emails.  This is the reply..
Hi Eric

Have done a search for those emails,  Yes I did receive one (1) request to reset PW request from reg-web@freereg.org.uk reg-web@freereg.org.uk at 24-Oct-15 1558 (my local time), This is where it does gets interesting, I have had to go back to my old computer (Running Vista Pro, using Windows Mail) and there it was sitting in my Inbox, however on my new computer (Running Windows 10 Home, using Mail app) it never arrived.  I did do it about 3-4 times thinking I had made a error, Usually something like that will always come in within a couple of minutes, I did sit and wait for them to arrive but nothing came in, which is when I contacted yourself, I did send a message to Ken Davies, regarding a few issues as well, no reply for Ken yet.  I did receive your emails in W10 (Windows 10) and replied to you in that environment. 

This morning I saw your email regarding this issues in (W10 Mail) did a sync and the inbox cleared itself.  All the emails deleted themselves!  I am now back on Vista for Emails,  I don't trust this "Mail" app.

The other thing to note is I was using Windows 10, IE 11 when I used the "I forgot my password" on FR.

In the end I did receive one email but only to my old computer running vista pro.  Don't know if W10 or Mail is the issue, or IE 11

Sorry If I have caused a problem.

Regards
Daniel Benedict  (UserID eggs)

**Comment by Captainkirkdawson** [comment]
I am unsure of the point of the previous comment as it relates to our work on this story.

The revised registration page is available for review on test3 follow the link in the footer; there may be a few tweaks

It would be useful to place a link to this early on in the About page if Pat agrees.

**Comment by AlOneill** [comment]
There is (and always has been) a link on About, in the Membership section.

**Comment by Captainkirkdawson** [comment]
Agreed but it is even less visible that the link in the footer.
It really needs to stand out; perhaps in another aside box under the current one. We are always looking for volunteers.

**Comment by AlOneill** [comment]
Yes, see what you mean. Am wondering, though, if a splash-style link should go to a page of basic info re transcribing, answering **simply** such questions as:
- where does the data come from?
- how much of a time commitment is transcribing?
- what do I need in order to transcribe?

Plus any other questions a potential transcriber might reasonably want answers to before actually registering. 

Someone who has made up their mind will hunt for the link; someone with doubts/queries needs to see some simple answers before deciding.

**Comment by edickens** [comment]
When we first started the word "Volunteer" was in the header next to 
"Donate".  E

**Comment by PatReynolds** [comment]
Good ideas!

Best wishes,

Pat

Pat Reynolds
Executive Director, Free UK Genealogy

**Comment by Captainkirkdawson** [comment]
Link added to nav bar
