### ISSUE TITLE
Browse records in batch (alsibk)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#53]
Issue reported by **alsibk** at 2014-11-04 08:29:49 UTC
Time: 2014-11-04T08:23:17+00:00
Session ID: 4b91db35cfb9ce772157b2ba975e076a
Problem Page URL: [/freereg1_csv_files/5409f744eca9eb718294c7d1](/freereg1_csv_files/5409f744eca9eb718294c7d1)
Previous Page URL: [http://test2.freereg.org.uk/feedbacks/new?utf8=%E2%9C%93&feedback_time=2014-11-04+08%3A17%3A48+UTC&session_id=4b91db35cfb9ce772157b2ba975e076a&user_id=alsibk&problem_page_url=%2Ffreereg1_csv_files%2F5409f744eca9eb718294c7d1&previous_page_url=http%3A%2F%2Ftest2.freereg.org.uk%2Ffreereg1_csv_files&feedback_type=issue](http://test2.freereg.org.uk/feedbacks/new?utf8=%E2%9C%93&feedback_time=2014-11-04+08%3A17%3A48+UTC&session_id=4b91db35cfb9ce772157b2ba975e076a&user_id=alsibk&problem_page_url=%2Ffreereg1_csv_files%2F5409f744eca9eb718294c7d1&previous_page_url=http%3A%2F%2Ftest2.freereg.org.uk%2Ffreereg1_csv_files&feedback_type=issue)
Reported Issue:
There is no facility for a one page scrollable online view of the batch, such as we have in F1, where errors and anomalies may be more efficiently tracked, rather than searching through many, many pages

**Comment by Captainkirkdawson** [comment]
Do not understand. errors are displayed individually

**Comment by Sherlock21** [comment]
It is the INDIVIDUALNESS of each Place name + batch that creates the issue.

How is a CC supposed to logon to Every single place in their County, ( or worse still several Counties) to trawl through to see if there are any decadal issues? It would take days or even weeks to do this to sort the backlog once we move over to clean FR2 working. And i am sure it wont get done by some CC's because of this methodology.

FAR BETTER for theCC to have a County's worth of batches on a single OLDFASHIONED Spreadsheet where one can scroll down them and see at a glance where the problems are. Then target fixing the errors your way.

**Comment by edickens** [comment]
```
If I was a CC looking for decadel
  issues, I would like the server to find them for me.  My reason
  for asking for the year range in the Register set of fields (which
  is there now waiting for years to be entered) is so that dates
  outside this range can be identified.  Not only when transcribing
  so as to stop errors being entered, but also so that a report
  could be created of entries outside the year range of  the
  register.
  Another alternative, or perhaps we need it anyway, is to be able
  to sort the report of entries in a register/batch into date
  order.  Finding a particular date would be easier and dates
  outside the range would be either at the beginning or end.
  But we are not working on this part of the system yet.  We will
  get there in due course.
  EricD
  _____________________________________
```

Eric J Dickens
FreeREG Chairman
      On 03/01/2015 09:17, Sherlock21 wrote:

```
  It is the INDIVIDUALNESS of each Place name + batch that
    creates the issue.
  How is a CC supposed to logon to Every single place in their
    County, ( or worse still several Counties) to trawl through to
    see if there are any decadal issues? It would take days or even
    weeks to do this to sort the backlog once we move over to clean
    FR2 working. And i am sure it wont get done by some CC's because
    of this methodology.
  FAR BETTER for theCC to have a County's worth of batches on a
    single OLDFASHIONED Spreadsheet where one can scroll down them
    and see at a glance where the problems are. Then target fixing
    the errors your way.
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by Sherlock21** [comment]
We are working at present on the Search facility, are we not?
And one of the things which researchers access is the details link from the Search Results.

So, in my mind, everything that the searcher can get to [ even if its also what the CC and other Members handle] is in this scope of work is it not?

Else, if we can only comment on the literal first view list of records returned form a Search, then we ought to have the right brief.

**Comment by edickens** [comment]
```
Hi EricB,
  Correct.  But Ali was talking about browsing records in a batch. 
  I didn't think that a researcher could do this.  If they can, then
  we should think again otherwise they can access every record
  without having to enter a search.
  EricD
  _____________________________________
```

Eric J Dickens
FreeREG Chairman
      On 03/01/2015 10:36, Sherlock21 wrote:

```
  We are working at present on the Search facility, are we not?
    And one of the things which researchers access is the details
    link from the Search Results.
  So, in my mind, everything that the searcher can get to [ even
    if its also what the CC and other Members handle] is in this
    scope of work is it not?
  Else, if we can only comment on the literal first view list of
    records returned form a Search, then we ought to have the right
    brief.
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by suffolkroots** [comment]
A browseable view of records and lists etc should be regarded as essential for the efficient running of SCs' and CCs' tasks in F2.

Re decadal anomalies, perhaps they could be included in error flagging----the Error heading changed to Errors and Anomalies.
