### ISSUE TITLE
Files waiting to be processed are not all mine. (MikeNL)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#532]
Issue reported by **MikeNL** at 2015-10-23 15:21:58 UTC
Time: 2015-10-23T15:19:20+00:00
Session ID: a153b855344afa04d44c1774c8bfed5b
Problem Page URL: [/freereg1_csv_files/selection?option=List%20files%20waiting%20to%20be%20processed](/freereg1_csv_files/selection?option=List%20files%20waiting%20to%20be%20processed)
Previous Page URL: [http://www.freereg.org.uk/freereg1_csv_files/my_own](http://www.freereg.org.uk/freereg1_csv_files/my_own)
Reported Issue:
The report "Files waiting to be processed" for userid MikeNL shows some files that I have NOT asked to be processed. They are not even in my county.    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Corrected
