### ISSUE TITLE
County stats do not appear to be working? (AMSA)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#535]
Issue reported by **AMSA** at 2015-10-24 07:58:07 UTC
Time: 2015-10-24T07:53:32+00:00
Session ID: 05b03b3d1ea9050fec27faac039038ba
Problem Page URL: [/freereg_contents//show_place](/freereg_contents//show_place)
Previous Page URL: [http://freereg2.freereg.org.uk/freereg_contents/new](http://freereg2.freereg.org.uk/freereg_contents/new)
Reported Issue:
I select county (Northamptonshire) & leave everything else blank as advised and press the "contents" button.
All I get is a notice saying "there is something wrong with the request"
I have also tried clicking on the (empty) top line of the Place list but with the same result.
I have tried when I am logged in, and logged out.
Same result.
Help! 
Thanks, Anna (NTH CC)    

![Screenshot](http://www.freereg.org.uk)

**Comment by edickens** [comment]
```
Hi Anna,

You seem to be using freereg2...

.

You need to use freereg.org.uk and accepted Cookies?  Kirk does say
that using freereg2 should not matter, but I am not so sure.

Regards,

Eric
_____________________________________
```

Eric J Dickens
FreeREG Chairman
    On 24/10/2015 08:58, FreeUKGenIssues
      wrote:

```
  Issue reported by AMSA at 2015-10-24 07:58:07
    UTC
    Time: 2015-10-24T07:53:32+00:00
    Session ID: 05b03b3d1ea9050fec27faac039038ba
    Problem Page URL: /freereg_contents//show_place
    Previous Page URL: http://freereg2.freereg.org.uk/freereg_contents/new
    Reported Issue:
    I select county (Northamptonshire) & leave everything else
    blank as advised and press the "contents" button.
    All I get is a notice saying "there is something wrong with the
    request"
    I have also tried clicking on the (empty) top line of the Place
    list but with the same result.
    I have tried when I am logged in, and logged out.
    Same result.
    Help! 
    Thanks, Anna (NTH CC) 

  —
    Reply to this email directly or view
      it on GitHub.
```
