### ISSUE TITLE
Letter case changing is causing a problem (MikeNL)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#536]
Issue reported by **MikeNL** at 2015-10-24 11:16:56 UTC
Time: 2015-10-24T11:05:55+00:00
Session ID: aa858ac230980bb237551040a70494ce
Problem Page URL: [/freereg1_csv_files/56284d9df493fdf07200d30c](/freereg1_csv_files/56284d9df493fdf07200d30c)
Previous Page URL: [http://www.freereg.org.uk/registers/56284d9df493fdf07200d30d](http://www.freereg.org.uk/registers/56284d9df493fdf07200d30d)
Reported Issue:
In my county (STS) there is a church in Stoke-upon-Trent called St Peter ad Vincula (note the lower case "a" in "ad"). 

Transcription files are being created with this name in the church field. 

When one of these transcription files is processed into FreeREG, a new church called St Peter Ad Vincula is created (note the upper case "A" in "Ad") (or another batch is added to this (wrong) church if it already exists). 

For some reason (probably that it is surrounded by "-" and is in a place rather than a church) the "upon" in the place name remains all in lower case.    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Have added ad to non capitalize list
