### ISSUE TITLE
Profile:List BatchesScroll is only showing the first 50 (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#537]
Issue reported by **REGManager** at 2015-10-24 11:31:32 UTC
Time: 2015-10-24T11:30:05+00:00
Session ID: 25bae1a3bb2ffbd60447c271862ac8c0
Problem Page URL: [/freereg1_csv_files/5462b41ee937907d7000050b/by_userid](/freereg1_csv_files/5462b41ee937907d7000050b/by_userid)
Previous Page URL: [http://www.freereg.org.uk/userid_details/5462b41ee937907d7000050b](http://www.freereg.org.uk/userid_details/5462b41ee937907d7000050b)
Reported Issue:
Try davejo.  E    

![Screenshot](http://www.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1445686292-53438-0898/Capture.JPG)

**Comment by Captainkirkdawson** [comment]
Dam me thought I had found them all; hope I have now
