### ISSUE TITLE
Things missing from Contacts screen (MikeNL)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#539]
Issue reported by **MikeNL** at 2015-10-24 14:20:16 UTC
Time: 2015-10-24T14:16:47+00:00
Session ID: 8c8e61c2ee68424ef43cc41a5b3f0c96
Problem Page URL: [/contacts](/contacts)
Previous Page URL: [http://www.freereg.org.uk/manage_resources/new](http://www.freereg.org.uk/manage_resources/new)
Reported Issue:
Could we have (a) a scrollable list similar to the other places where scrollable lists have been introduced and (b) a list in alphabetical order of contact name rather than what is there at present, i.e. by contact date.    

![Screenshot](http://www.freereg.org.uk)

**Comment by edickens** [comment]
```
I would prefer a sequence number in the Subject of the Contact
report in the same way as github does for the Feedback messages.  E

On 24/10/2015 15:20, FreeUKGenIssues
  wrote:


  Issue reported by MikeNL at 2015-10-24
    14:20:16 UTC
    Time: 2015-10-24T14:16:47+00:00
    Session ID: 8c8e61c2ee68424ef43cc41a5b3f0c96
    Problem Page URL: /contacts
    Previous Page URL: http://www.freereg.org.uk/manage_resources/new
    Reported Issue:
    Could we have (a) a scrollable list similar to the other places
    where scrollable lists have been introduced and (b) a list in
    alphabetical order of contact name rather than what is there at
    present, i.e. by contact date. 

  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by Captainkirkdawson** [comment]
Dealt with as part of #605
