### ISSUE TITLE
Case sensitive filename match on  replace (PollyAnna)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#541]
Issue reported by **PollyAnna** at 2015-10-24 15:11:30 UTC
Time: 2015-10-24T15:09:29+00:00
Session ID: 68b388859f258e8a24c24a3f2a0d33f3
Problem Page URL: [/csvfiles/5463954de937904abb679b88/edit](/csvfiles/5463954de937904abb679b88/edit)
Previous Page URL: [http://www.freereg.org.uk/csvfiles/5463954de937904abb679b88/edit](http://www.freereg.org.uk/csvfiles/5463954de937904abb679b88/edit)
Reported Issue:
Hi 

high this is the result of trying to please a file. attachment 02

Regards    

![Screenshot](http://www.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1445699490-53459-9053/CONISLBA-Replace-02.JPG)

**Comment by Captainkirkdawson** [comment]
It is a case sensitive match. User had different case in replacement file.
We could make it a case insensitive match; but the check is there to make sure that the user really is replacing the file they think they want to replace.

**Comment by edickens** [comment]
```
We still need case sensitive as it is in FR1.  E

On 24/10/2015 17:05, Kirk Dawson wrote:


  It is a case sensitive match. User had different case in
    replacement file.
    We could make it a case insensitive match; but the check is
    there to make sure that the user really is replacing the file
    they think they want to replace.
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by Sherlock21** [comment]
I would not fiddle with the way it is. It's There to remind user that Case matters.
