### ISSUE TITLE
New Place Name just created has disappeared!  (ericb)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#542]
Issue reported by **ericb** at 2015-10-25 07:59:21 UTC
Time: 2015-10-25T07:54:21+00:00
Session ID: b55a0d3ace4707e445b4725ebda353a9
Problem Page URL: [/places](/places)
Previous Page URL: [http://www.freereg.org.uk/manage_counties/select_action]
DELETED

**Comment by Captainkirkdawson** [comment]
{ "_id" : ObjectId("562c8d46f493fdd211000473"), "disabled" : "false", "alternate" : "", "country" : "England", "county" : "Yorkshire, West Riding", "place_name" : "Walton (Thorpe Arch)", "grid_reference" : "SE441478", "latitude" : "53.924465", "longitude" : "-1.329943", "genuki_url" : "http://www.genuki.org.uk/cgi-bin/gazplace?GR=SE441478,PLACE=WALTON,CCC=WRY", "source" : "", "place_notes" : "", "data_present" : true, "chapman_code" : "WRY", "modified_place_name" : "walton (thorpe arch)", "location" : [ -1.329943, 53.924465 ], "u_at" : ISODate("2015-10-25T08:28:34.819Z"), "original_chapman_code" : "WRY", "original_county" : "Yorkshire, West Riding", "original_country" : "England", "original_place_name" : "Walton (Thorpe Arch)", "original_grid_reference" : "SE441478", "original_latitude" : "53.924465", "original_longitude" : "-1.329943", "original_source" : "", "last_amended" : "25 Oct 2015" }

**Comment by Captainkirkdawson** [comment]
![walton](https://cloud.githubusercontent.com/assets/2874694/10718403/7b465c0c-7b37-11e5-841b-54bce81a4a1f.JPG)
