### ISSUE TITLE
Trying to change UserID but reporting file exists when it doesn't (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#543]
Issue reported by **REGManager** at 2015-10-25 08:32:16 UTC
Time: 2015-10-25T08:28:29+00:00
Session ID: a725ec1a8c88e7e8243835108aba84f4
Problem Page URL: [/freereg1_csv_files/5462b41ee937907d7000050b/by_userid](/freereg1_csv_files/5462b41ee937907d7000050b/by_userid)
Previous Page URL: [http://www.freereg.org.uk/userid_details/5462b41ee937907d7000050b](http://www.freereg.org.uk/userid_details/5462b41ee937907d7000050b)
Reported Issue:
I'm tidying up davejo but the file HAMWTCMA will not move from davejoHAM as it says that the file exists, but it is not listed in the destination UserID davejo.  E    

![Screenshot](http://www.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1445761936-90148-3836/Capture.JPG)

**Comment by edickens** [comment]
See also moving HEFBFRMA2 from davejoHEF to davejo.  There is a HEFBFRMA so is the problem that it is not seeing the number?  E

**Comment by Captainkirkdawson** [comment]
Think the message said that a file existed in the file folder. This happened when you has a system problem with the move.

Both files have been removed so you now be able to complete your task
