### ISSUE TITLE
Add a comment to an existing Feedback report (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#544]
Issue reported by **REGManager** at 2015-10-25 08:38:34 UTC
Time: 2015-10-25T08:35:43+00:00
Session ID: a725ec1a8c88e7e8243835108aba84f4
Problem Page URL: [/feedbacks/562c9390f493fdd2110004c9](/feedbacks/562c9390f493fdd2110004c9)
Previous Page URL: [http://www.freereg.org.uk/feedbacks](http://www.freereg.org.uk/feedbacks)
Reported Issue:
I'm using the facilities in FR to work on a Feedback Report.  It would be useful to have a button at the bottom to be able to add another comment to this github report.  E    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Added that as part of 605 until suxh a time as it is created as a Github issue then all comments must go through that system.
