### ISSUE TITLE
NOW we have scrolling tables, Return goes to the top of the List, and not to where one came from (ericb)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#545]
Issue reported by **ericb** at 2015-10-25 12:05:11 UTC
Time: 2015-10-25T11:52:55+00:00
Session ID: b55a0d3ace4707e445b4725ebda353a9
Problem Page URL: [/places](/places)
Previous Page URL: [http://www.freereg.org.uk/manage_counties/select_action](http://www.freereg.org.uk/manage_counties/select_action)
Reported Issue:
In the ALL Place Name  and the Active Places listings in the scroll display style, if one does a lookup - either to the Place name detail, or to the church & Batches contents, then Return to the table, using the back arrow on the Browser, one gets to the top of the whole table instead of -  as in the Page style view- to the point one came from.

Since for some of us it takes an age to scroll down to lower points in the alphabetical list, its a serious set back if one is doing a collection on jobs on the same Place name.

Please restore: "go back to where I came from".    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
That is why you have the breadcrumbs so that you go back to the place you were working on.

The browser back button will always go back to the top of a page because it does not know where you were on a page.

You may notice that with the breadcrumb that it initially loads the page and then positions to where it  needs to be.

None of this has changed as a result of scrolling; nothing was removed so nothing needs to be restored. Just use the breadcrumbs.

**Comment by Sherlock21** [comment]
What the Hxxxx are the bread crumbs!

**Comment by Captainkirkdawson** [comment]
![hxxxxx](https://cloud.githubusercontent.com/assets/2874694/10716319/af6c6536-7afa-11e5-9b25-1f939b73741b.JPG)

**Comment by edickens** [comment]
```
And if you are using the Database Contents, use the buttons not the
browser back button.
```

**Comment by Sherlock21** [comment]
ok so they are the Breadcrumbs.

But if I was on West Bromwich for the last lookup, Where in the things in Red do I put West Bromwich to navigate straight to there again? 
That is what the issue as about. If I have 10 lookups tpo do in West Bromwich, then I will be all morning starting at  A ( the place which is all i can go back to from say a batch header page lookup or whatever.

I May be old fashioned  as we said just recently but this is all what you get. So this is what is needed to be coped with. 22nd Century Stuff is for the kids to play games with.

**Comment by Captainkirkdawson** [comment]
Just click on the breadcrumb for Place and it will position at the last
place you were working on and want to work on a another place;  or Place
Information if you want to keep working on West Bromwich and it goes no
where near the places page. Each of those links takes you to where you were
last.

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Sherlock21** [comment]
Ahhhh well what  a surprise.

Thanks.
E
