### ISSUE TITLE
Create UserID Action does not show all Syndicates (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#546]
Issue reported by **REGManager** at 2015-10-26 07:44:06 UTC
Time: 2015-10-26T07:35:08+00:00
Session ID: b3e0d626156caba75eab3022dcf3d0ba
Problem Page URL: [/userid_details/new](/userid_details/new)
Previous Page URL: [http://www.freereg.org.uk/userid_details/options](http://www.freereg.org.uk/userid_details/options)
Reported Issue:
Last night's change has removed "Technical " from the list of possible syndicates when setting up a new UserID under "Create UserID".  I cannot now get the emails to be sent to me and not to the transcriber.  I have been using this to keep FR in step with FR1 by creating UserID for new transcribers and after completing registration editing the Syndicate as necessary.  Edit UserID shows all Syndicates.
Can Create UserID present all Syndicates, just as Edit UserID does?  E    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Fixed
