### ISSUE TITLE
Column Title  (Tim37)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#547]
Issue reported by **Tim37** at 2015-10-26 11:33:47 UTC
Time: 2015-10-26T11:30:16+00:00
Session ID: b2c30c1f4b3363199397f805f59873b2
Problem Page URL: [/freereg1_csv_files/selection?option=List%20files%20waiting%20to%20be%20processed](/freereg1_csv_files/selection?option=List%20files%20waiting%20to%20be%20processed)
Previous Page URL: [http://www.freereg.org.uk/freereg1_csv_files/my_own](http://www.freereg.org.uk/freereg1_csv_files/my_own)
Reported Issue:
1st column - Title Userid - Should be "User ID".  It would look a lot better    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Done
