### ISSUE TITLE
Website Problem (Mary Pollard)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#548]
Issue reported by **Mary Pollard** at 2015-10-26 18:45:09 UTC
Time: 2015-10-26T18:44:14+00:00
Session ID: 
Problem Page URL: []()
Previous Page URL: [http://www.freereg.org.uk/contacts/new](http://www.freereg.org.uk/contacts/new)
Reported Issue:
There seems to be no "Member" section to log in with my transcriptions    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Member link is now there under all circumstances unless logged already
