### ISSUE TITLE
No member section so cannot log on to your site with my transcriptions. (DerbyKid)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#549]
Issue reported by **DerbyKid** at 2015-10-26 18:48:14 UTC
Time: 2015-10-26T18:45:46+00:00
Session ID: 762a26b14cbb5a837804e80f096fb286
Problem Page URL: [/](/)
Previous Page URL: []()
Reported Issue:
 You said 
"http://www.freereg.org.uk/ and select Members. Log in  "

BUT
No member section so cannot log on to your site with my transcriptions.

You must know wghat your website looks like by now.  Print screen will not show it.    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Made sure the Members link is always there
