### ISSUE TITLE
CON/ ADDINGTON info page  says Data Exists for this place - yet there are no churches nor files. (ericb)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#550]
Issue reported by **ericb** at 2015-10-27 10:48:22 UTC
Time: 2015-10-27T10:43:00+00:00
Session ID: 6649e3aa641bce69eaa6fb99e6187ac1
Problem Page URL: [/places/53cbf5c7eca9eb03a6001869](/places/53cbf5c7eca9eb03a6001869)
Previous Page URL: [http://www.freereg.org.uk/places?page=](http://www.freereg.org.uk/places?page=)
Reported Issue:
This Place Name existed by 28 Apr 2014 ( see T3 site).

But in FR, it appears  in the Active Places - but without  either. - so will confuse Researchers who will see the place in their Picklist.
It may be that a file was uploaded and later deleted. if so the process does not reset the Data Present Flag.
Or it may be much worse! - can you tell from Attic what caused the latest edit of the Place Name and who did it?    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Could well be orphans; still have had no time to deal with that issue

**Comment by Captainkirkdawson** [comment]
Fixed; name will go from selection next time the place cache gets rebuilt
