### ISSUE TITLE
Soundex findings (Tim37)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#552]
Issue reported by **Tim37** at 2015-10-27 17:45:29 UTC
Time: 2015-10-27T17:38:31+00:00
Session ID: 095b7355a6f173db663cbbd2afbd5762
Problem Page URL: [/search_queries/562fb697f493fd75f5000316](/search_queries/562fb697f493fd75f5000316)
Previous Page URL: [http://www.freereg.org.uk/search_queries/new?search_id=562fb68cf493fd75f5000313](http://www.freereg.org.uk/search_queries/new?search_id=562fb68cf493fd75f5000313)
Reported Issue:
Did a Sussex search and had a First name of ' Xpian ' appear assumed this was Chispian in rector shorthand, but if I add soundex it does not show.  Likewise for  Xtian or Xian for Christian / Christiana.

Don think many would think of searching on an X.... Surname ??

There are several in Petworth (St Mary).

![Screenshot](http://www.freereg.org.uk)

**Comment by benwbrum** [comment]
This should be handled in #516 by the de-latinization emendation update task.  Soundex will never handle everything -- it's a well defined algorithm built for the US Census in the late 19th century.  We should make sure that we cover the chi-rho abbreviations for Chris/Christopher.  cc @sherlock21
