### ISSUE TITLE
Bulk date changes (hawkinssm)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#553]
Issue reported by **hawkinssm** at 2015-10-27 18:44:29 UTC
Time: 2015-10-27T18:42:39+00:00
Session ID: fa70f1abcc5af86ad64f36d1e38f7397
Problem Page URL: [/freereg1_csv_entries/55497711f493fd771101cf5b/edit](/freereg1_csv_entries/55497711f493fd771101cf5b/edit)
Previous Page URL: [http://freereg2.freereg.org.uk/freereg1_csv_entries](http://freereg2.freereg.org.uk/freereg1_csv_entries)
Reported Issue:
It would be useful if these were possible.

I have had to change 1869 to 1769 on 34 individuals separately with lots of to-ing and fro-ing!    

![Screenshot](http://www.freereg.org.uk)

**Comment by edickens** [comment]
```
Sue,
In this case it is better to download, edit with Notepads, and
replace.
Cheers Eric

On 27/10/2015 18:44, FreeUKGenIssues
  wrote:


  Issue reported by hawkinssm at 2015-10-27
    18:44:29 UTC
    Time: 2015-10-27T18:42:39+00:00
    Session ID: fa70f1abcc5af86ad64f36d1e38f7397
    Problem Page URL: /freereg1_csv_entries/55497711f493fd771101cf5b/edit
    Previous Page URL: http://freereg2.freereg.org.uk/freereg1_csv_entries
    Reported Issue:
    It would be useful if these were possible.
  I have had to change 1869 to 1769 on 34 individuals separately
    with lots of to-ing and fro-ing! 

  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by PatReynolds** [comment]
Alison, can you add this suggestion to the documention.  Then closed?

**Comment by AlOneill** [comment]
This would be fine if editing own files... but would there have to be any caveats for mixed OSs, etc, if editing someone else's files?

**Comment by edickens** [comment]
A SC can download, correct and upload Batches to the Transcribers UserID.   The Batch is then  locked until the transcriber downloads it to correct the version on their computer, if ever.  This situation does not occur often and is better by Notepad.  I would say documentation only.   OS should not be a problem.  E

**Comment by AlOneill** [comment]
Note for coordinators added to http://www.freereg.org.uk/information-for-transcribers/file-and-batch-actions#edit
