### ISSUE TITLE
STS/ Broome does not appear in the Search Places list but it has data. (ericb)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#554]
Issue reported by **ericb** at 2015-10-28 08:30:13 UTC
Time: 2015-10-28T08:25:33+00:00
Session ID: a77ba07f1f2d0e529ec06f35b201f055
Problem Page URL: [/freereg_contents/new](/freereg_contents/new)
Previous Page URL: [http://www.freereg.org.uk/](http://www.freereg.org.uk/)
Reported Issue:
STS / Broome was removed form STS ( by me) recently. But then we needed to put it back in STS.
It has data - for the church of St Peter -

BUT although the place name is in Members area:ALL Places and also in Active Places, it does NOT appear in the Search feature of Place names NOR in the Database list of places - copy attached of missing name    

![Screenshot](http://www.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1446021013-55132-4939/STS_Broome.jpg)

**Comment by Captainkirkdawson** [comment]
It is there now
