### ISSUE TITLE
widen the date range for records to accept 633 AD (ericb)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#556]
Issue reported by **ericb** at 2015-10-28 14:29:24 UTC
Time: 2015-10-28T14:23:17+00:00
Session ID: fa0accb8c693324a62dc3cbcd5efd90b
Problem Page URL: [/manage_resources/new](/manage_resources/new)
Previous Page URL: [http://www.freereg.org.uk/refinery/login](http://www.freereg.org.uk/refinery/login)
Reported Issue:
A report by Susan Hawkins( CC for Kent) that they have Burial records from Rochester Cathedral of burials starting 633 AD which get rejected on upload ( because  of our start cut-off date)

Perhaps we should treat Baptisms, Marriages as well as Burials to this earlier start.
And where do we make the new Start date? 0001 AD?    

![Screenshot](http://www.freereg.org.uk)

**Comment by benwbrum** [comment]
I would like us to think pretty hard about to what extent we want FreeREG
to be a database of burials (including burial information extracted from
tombstones) and to what extent it should be a database of registers.

**Comment by Sherlock21** [comment]
An interesting question,Ben.
We already have record (in STS) that are not Parish Register originated and I was resistant to having these. - the ones with the GRO church names!
We do have lots of Transcriptions that may or may not be PR sourced originally

As a Non-UK person, what would you like to see if you were just a researcher or transfer this topic to off-line?

**Comment by benwbrum** [comment]
I think I wouldn't expect to find non-register entries in the data set.
However, if I found a record for one of my ancestors unexpectedly, I'd be
very happy indeed.  It is important that there is some way to communicate
to the user that what they're seeing isn't sourced from a register --
perhaps that's handled via notes for the GRO and church-yard sources?

**Comment by Captainkirkdawson** [comment]
FreeReg went away from its prime mission 18 years ago; it actually has register type for MI and many other things from cemeteries and books and archives: because of difficulty in getting access to the PR

**Comment by Captainkirkdawson** [comment]
Ben its handled by the Register Type flag which is defined.

**Comment by benwbrum** [comment]
Thanks, Kirk -- I'd have assumed it'd be a new record type and that we were
conflating sources, but register type makes perfect sense here.

**Comment by Sherlock21** [comment]
The Record Source is in the code PR = Parish Register ( and means similar Registers of other Religions.
TR means our source was another Transcription of undisclosed type.
There is a table for all of them - perhaps we need to expand that - I don't know where the table is in the code right now!
So may be your concern IS satisfied in this methodology - may be it could be written out better in the results though?

**Comment by edickens** [comment]
```
Yes, I would go from 0001, especially as we now have the decadel
analysis which shows up bad errors, and when we have validation
against register years, then that will tie it up.  E

On 28/10/2015 14:29, FreeUKGenIssues
  wrote:


  Issue reported by ericb at 2015-10-28
    14:29:24 UTC
    Time: 2015-10-28T14:23:17+00:00
    Session ID: fa0accb8c693324a62dc3cbcd5efd90b
    Problem Page URL: /manage_resources/new
    Previous Page URL: http://www.freereg.org.uk/refinery/login
    Reported Issue:
    A report by Susan Hawkins( CC for Kent) that they have Burial
    records from Rochester Cathedral of burials starting 633 AD
    which get rejected on upload ( because of out start cut-off
    date)
  Perhaps we should treat Baptisms, Marriages as well as Burials
    to this earlier start.
    And where do we make the new Start date? 0001 AD? 

  —
    Reply to this email directly or view
      it on GitHub.
```
