### ISSUE TITLE
Error message (norlian)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#557]
Issue reported by **norlian** at 2015-10-29 07:18:22 UTC
Time: 2015-10-29T07:10:56+00:00
Session ID: 712b56a439a24e079689da077fb4743d
Problem Page URL: [/manage_resources/new](/manage_resources/new)
Previous Page URL: [http://www.freereg.org.uk/refinery/users/password/edit?initial=true&reset_password_token=5rpa68Dqiht1JHyQL9FP](http://www.freereg.org.uk/refinery/users/password/edit?initial=true&reset_password_token=5rpa68Dqiht1JHyQL9FP)
Reported Issue:
I am getting this message each time I open my winreg programme.
Lilian Fraser    

![Screenshot](http://www.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1446103102-31998-1495/FreeREG_error_notice.JPG)

**Comment by PatReynolds** [comment]
Lillian replied that she would get back to me in 'a few days' if still an issue (on 19th November) so presume solved.
