### ISSUE TITLE
trying to delete a file (JulieHarold)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#558]
Issue reported by **JulieHarold** at 2015-10-29 08:06:07 UTC
Time: 2015-10-29T08:04:34+00:00
Session ID: 6a614202c109298db17723a7dba4cf6a
Problem Page URL: [/manage_syndicates/selection?option=Review%20Batches%20with%20Errors](/manage_syndicates/selection?option=Review%20Batches%20with%20Errors)
Previous Page URL: [http://freereg2.freereg.org.uk/manage_syndicates/select_action.%3Fsyndicate=Norfolk,%20Suffolk%20and%20Essex%20-%20Julie%20Harold](http://freereg2.freereg.org.uk/manage_syndicates/select_action.%3Fsyndicate=Norfolk,%20Suffolk%20and%20Essex%20-%20Julie%20Harold)
Reported Issue:
UserId  JulieHarold  ESSTENMA

I have tried to delete it but it remains as locked with errors.

thanks, 
Julie    

![Screenshot](http://www.freereg.org.uk)

**Comment by Sherlock21** [comment]
Julie
The file is locked by CC. so you need to unlock it first ( the L/U button on it's row in files for ESS). - I have done this for you so now you should be able to delete it.
ericb
