### ISSUE TITLE
File in processing queue has incorrect filename (milliemoll)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#559]
Issue reported by **milliemoll** at 2015-10-29 11:48:22 UTC
Time: 2015-10-29T11:33:38+00:00
Session ID: 162705edafb27220e8dba3da10255997
Problem Page URL: [/manage_syndicates/display_files_waiting_to_be_processed](/manage_syndicates/display_files_waiting_to_be_processed)
Previous Page URL: [http://www.freereg.org.uk/manage_syndicates/select_action](http://www.freereg.org.uk/manage_syndicates/select_action)
Reported Issue:
Hi

Adrian Rowe has uploaded a file through new freereg file name DURDURMA.CSV

It should be DURDSMMA.CSV

Is there any way that this file can be deleted by any party before processing?

I have written and told him

Amanda     

![Screenshot](http://www.freereg.org.uk)

**Comment by edickens** [comment]
```
Hi Amanda,

I have a management report for files waiting to be processed...



So I have now deleted this file.



Regards,

Eric

_____________________________________
```

Eric J Dickens
FreeREG Chairman
    On 29/10/2015 11:48, FreeUKGenIssues
      wrote:

```
  Issue reported by milliemoll at 2015-10-29
    11:48:22 UTC
    Time: 2015-10-29T11:33:38+00:00
    Session ID: 162705edafb27220e8dba3da10255997
    Problem Page URL: /manage_syndicates/display_files_waiting_to_be_processed
    Previous Page URL: http://www.freereg.org.uk/manage_syndicates/select_action
    Reported Issue:
    Hi
  Adrian Rowe has uploaded a file through new freereg file name
    DURDURMA.CSV
  It should be DURDSMMA.CSV
  Is there any way that this file can be deleted by any party
    before processing?
  I have written and told him
  Amanda 

  —
    Reply to this email directly or view
      it on GitHub.
```
