### ISSUE TITLE
Cancelling an Upload (edickens)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#560]
Issue reported by **edickens** at 2015-10-29 12:02:47 UTC
Time: 2015-10-29T11:54:17+00:00
Session ID: 9239c6fc414b9a3d7180495faf72fed1
Problem Page URL: [/freereg1_csv_files/selection?option=List%20by%20Filename](/freereg1_csv_files/selection?option=List%20by%20Filename)
Previous Page URL: [http://www.freereg.org.uk/freereg1_csv_files/my_own](http://www.freereg.org.uk/freereg1_csv_files/my_own)
Reported Issue:
I was just trying something out, and it has raised a possible problem.
I started to upload a file.  Selected the file and had to press "Upload".  But I did not process because I thought I may have selected the wrong file.  The Filename is not shown on the "Process" screen so I am not sure what I selected.  There is no "Cancel" option in the "Process" screen, which should delete the selected file.  So now I have a file somewhere in limbo.  I was using the ID "edickens" which is my Transcriber only ID.  Now looking at the files for that ID the file is not there as waiting to be processed.  It has been Uploaded, but where is it?  I would like to delete it and so cancel the processing.  I know that I can do this as a management function, but if I were a transcriber who had selected the wrong file I have no way to undo my Upload.  E    

![Screenshot](http://www.freereg.org.uk)

**Comment by edickens** [comment]
On further investigation, I can't find this file anywhere, not even in the Physical files or those waiting to be processed.  E

**Comment by Captainkirkdawson** [comment]
Deal with in 628
