### ISSUE TITLE
Checked for typo date but is correct! (milliemoll)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#562]
Issue reported by **milliemoll** at 2015-10-29 14:13:03 UTC
Time: 2015-10-29T14:04:15+00:00
Session ID: 162705edafb27220e8dba3da10255997
Problem Page URL: [/freereg1_csv_entries](/freereg1_csv_entries)
Previous Page URL: [http://www.freereg.org.uk/freereg1_csv_files/54638e9be9379010fc476d41](http://www.freereg.org.uk/freereg1_csv_files/54638e9be9379010fc476d41)
Reported Issue:
Having checked the single 1699 record at the source - it is correct

Can a way be found to highlight that this is the case to avoid rechecking at a later date unnecessarily?

Amanda    

![Screenshot](http://www.freereg.org.uk)

**Comment by PatReynolds** [comment]
Need further evidence that this is a problem before taking on.
