### ISSUE TITLE
list batches for syndicate coordinator (JulieHarold)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#563]
Issue reported by **JulieHarold** at 2015-10-29 15:08:39 UTC
Time: 2015-10-29T15:06:52+00:00
Session ID: 5253bfa336ed9bcdeb8dec9d6c408072
Problem Page URL: [/freereg1_csv_files/5462b401e937907d70000022/by_userid](/freereg1_csv_files/5462b401e937907d70000022/by_userid)
Previous Page URL: [http://freereg2.freereg.org.uk/userid_details/5462b401e937907d70000022](http://freereg2.freereg.org.uk/userid_details/5462b401e937907d70000022)
Reported Issue:
Another thing to add to your long wish list :)

It would be really useful as a coordinator to have the start and end date and number of entries added to the list batches output.

Julie (Essex/Suffolk/Norfolk)    

![Screenshot](http://www.freereg.org.uk)

**Comment by edickens** [comment]
```
In future versions I have already indicated that I would like to see
the Batch Header set up by the CC with start and end dates.  The
transcription can then be validated against this.  So the change to
the listing can be done then, but it is V1.5 or even V1.6.  E

On 29/10/2015 15:08, FreeUKGenIssues
  wrote:


  Issue reported by JulieHarold at 2015-10-29
    15:08:39 UTC
    Time: 2015-10-29T15:06:52+00:00
    Session ID: 5253bfa336ed9bcdeb8dec9d6c408072
    Problem Page URL: /freereg1_csv_files/5462b401e937907d70000022/by_userid
    Previous Page URL: http://freereg2.freereg.org.uk/userid_details/5462b401e937907d70000022
    Reported Issue:
    Another thing to add to your long wish list :)
  It would be really useful as a coordinator to have the start
    and end date and number of entries added to the list batches
    output.
  Julie (Essex/Suffolk/Norfolk) 

  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by Captainkirkdawson** [comment]
Long since implemented
