### ISSUE TITLE
something went wrong with your request .... (JulieHarold)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#564]
Issue reported by **JulieHarold** at 2015-10-29 15:16:29 UTC
Time: 2015-10-29T15:10:09+00:00
Session ID: 5253bfa336ed9bcdeb8dec9d6c408072
Problem Page URL: [/freereg_contents/select_places?character=C](/freereg_contents/select_places?character=C)
Previous Page URL: [http://freereg2.freereg.org.uk/freereg_contents/alphabet](http://freereg2.freereg.org.uk/freereg_contents/alphabet)
Reported Issue:
I was using the county contents summary for C in Norfolk - I had made some changes to files (moving from unspecified to parish register etc) so I used the browser refresh to reload the output (http://freereg2.freereg.org.uk/freereg_contents/select_places?character=C) and I got a something went wrong with your request error.

Julie (NFK coordinator)    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Latest deployment should fix
