### ISSUE TITLE
Many transcribers are confused about reload (MikeNL)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#565]
Issue reported by **MikeNL** at 2015-10-29 16:55:40 UTC
Time: 2015-10-29T14:53:13+00:00
Session ID: c4f9bd8a4867e5ba8e28fdb898f6b096
Problem Page URL: [/manage_counties/select_action](/manage_counties/select_action)
Previous Page URL: [http://freereg2.freereg.org.uk/manage_resources/new](http://freereg2.freereg.org.uk/manage_resources/new)
Reported Issue:
I have had queries from several transcribers about the fact that they try to upload a file but the upload fails with a "already exists, do replace" message. The transcribers are not reading the error message through but even if they do read it completely, it is not obvious where to find the "Replace" button.

In FR1, several of the file handling options were grouped together. In FR2, they are not.

An existing transcriber who has already uploaded a file using FR1 now has to convert to using FR2 and the only option that he sees on the first screen is the option to upload. So upload is chosen. Bang. Error.     

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
It is covered in the information for transcribers page.
We can group them by removing the upload from the list of btach options and have it only on the index of batches. But then we will get complaints about extra clicks!

**Comment by edickens** [comment]
```
Hi Kirk,

The other way round would be better.  That is a "Replace" button
alongside the "Upload".  Transcribers will know if is new or not. 
Select the filename then choose "Upload new" or "Replace".
```

**Comment by Captainkirkdawson** [comment]
Can't do it that way. Have to know which file they are replacing.

**Comment by edickens** [comment]
```
What about this screen?




This is what they want to replace, but of course it might not exist
if they press Replace instead of New.  = Error.  Just as selecting
New when it Exists = Error.
```

**Comment by Captainkirkdawson** [comment]
What screen

**Comment by Captainkirkdawson** [comment]
What I am suggesting is that on the list of batches we insert an upload button in the place with the red region
![upload](https://cloud.githubusercontent.com/assets/2874694/10834883/d045bfa8-7e62-11e5-8df9-99ef130c898a.JPG)

**Comment by PatReynolds** [comment]
I think using the phrase 'Upload new batch' rather than 'upload' - where
space allows - will be a helpful reminder.

Best wishes,

Pat

On Friday, 30 October 2015, Kirk Dawson notifications@github.com wrote:

> What I am suggesting is that on the list of batches we insert an upload
> button in the place with the red region
> [image: upload]
> https://cloud.githubusercontent.com/assets/2874694/10834883/d045bfa8-7e62-11e5-8df9-99ef130c898a.JPG
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/FreeUKGen/FreeUKRegProductIssues/issues/565#issuecomment-152356550
> .

## 

_\- -_

_Dr Pat Reynolds_
Executive Director
Free UK Genealogy  http://www.freeukgenealogy.org.uk/
A charity registered in England and Wales, number 1096940

​+44 ​1904 541411​ +44 7943 145387

36 Albemarle Road, York, YO23 1ER, UK

**Comment by edickens** [comment]
```
But will this just introduce an extra page selection when starting
to upload a new batch?  However, perhaps not a problem, as most
Uploads are replacements.  What I do like is that the transcriber
will be directed to the List Batches page and so make sure that they
know what they are doing with Filename, Place, Church and Register
Type and if the batch is locked.  This is the initial validation
that we need, rather than having to wait until the update is done,
perhaps overnight.

Will this affect Mike Fry and WinFreeREG?

E

PS.  An interesting example, because that first Church needs some
sorting out.  Three spellings in one file.
_____________________________________
```

Eric J Dickens
FreeREG Chairman
    On 29/10/2015 23:31, Kirk Dawson wrote:

```
  What I am suggesting is that on the list of batches we insert
    an upload button in the place with the red region

  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by EmJayFry** [comment]
On 30 Oct 2015 10:53 AM, Eric Dickens wrote:

> But will this just introduce an extra page selection when starting
> to upload a new batch?  However, perhaps not a problem, as most
> Uploads are replacements.  What I do like is that the transcriber
> will be directed to the List Batches page and so make sure that they
> know what they are doing with Filename, Place, Church and Register
> Type and if the batch is locked.  This is the initial validation
> that we need, rather than having to wait until the update is done,
> perhaps overnight.
> 
> Will this affect Mike Fry and WinFreeREG?

Isn't it possible just to have an upload button, and for the server to decide if 
it's a new file or an existing one that's being replaced?

As for me, I would use the same basic logic that WinREG uses. I have two lists 
of files: one for the files on the PC and the other, a refreshed copy of what 
has been previously uploaded. By merging the two, I can determine what is new 
and what has been altered since it was last uploaded.

## 

Regards,
Mike Fry (Jhb)

**Comment by edickens** [comment]
```
Assuming you mean using the present Upload screen with just the
filename selection and "Upload" button, my concern would be that the
transcriber may have used the same filename again and so overwrite,
unknowingly, some previous work.  It is different with WinReg
because they see all the files rather like the List Batches.  And
that is why I like using the FR List Batches screen with an "Upload
new batch" button as Kirk suggested, because you can see where you
are putting the file.  This is very like WinReg.  It might help,
even with new files - especially a new batch for the same
Place/Church - to avoid spelling differences.  E


On 30/10/2015 09:04, Mike wrote:

On 30 Oct 2015 10:53 AM, Eric Dickens wrote:

  > But will this just introduce an extra page selection when
  starting
  > to upload a new batch? However, perhaps not a problem, as
  most
  > Uploads are replacements. What I do like is that the
  transcriber
  > will be directed to the List Batches page and so make sure
  that they
  > know what they are doing with Filename, Place, Church and
  Register
  > Type and if the batch is locked. This is the initial
  validation
  > that we need, rather than having to wait until the update is
  done,
  > perhaps overnight.
  >
  > Will this affect Mike Fry and WinFreeREG?

  Isn't it possible just to have an upload button, and for the
  server to decide if 
  it's a new file or an existing one that's being replaced?

  As for me, I would use the same basic logic that WinREG uses. I
  have two lists 
  of files: one for the files on the PC and the other, a refreshed
  copy of what 
  has been previously uploaded. By merging the two, I can determine
  what is new 
  and what has been altered since it was last uploaded.

  -- 
  Regards,
  Mike Fry (Jhb)
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by Captainkirkdawson** [comment]
Dealt with in 628
