### ISSUE TITLE
email confirmation (ozfor)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#566]
Issue reported by **ozfor** at 2015-10-30 10:20:49 UTC
Time: 2015-10-30T10:17:24+00:00
Session ID: 660493aec422c7e94970a606b308a887
Problem Page URL: [/manage_resources/new](/manage_resources/new)
Previous Page URL: [http://www.freereg.org.uk/search_queries/new](http://www.freereg.org.uk/search_queries/new)
Reported Issue:
Not getting an "its processed" email confirmation when I upload .  I can't send to my user group if I use my ntlworld address - only when I use a gmail, but my ntlworld address is the one I'm registered with on the site.  Is this the cause of the problem?    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Asked her to check her spam

**Comment by Captainkirkdawson** [comment]
Dependant on 626
