### ISSUE TITLE
Who gets the email which says that a file has been uploaded (edickens)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#567]
Issue reported by **edickens** at 2015-10-30 16:57:04 UTC
Time: 2015-10-30T16:38:54+00:00
Session ID: 524c93265cc86e244b7f4a2c9d3b5168
Problem Page URL: [/information-for-transcribers/uploading-files](/information-for-transcribers/uploading-files)
Previous Page URL: [http://www.freereg.org.uk/information-for-transcribers](http://www.freereg.org.uk/information-for-transcribers)
Reported Issue:
The documentation is not clear as to who gets the email that a file has been uploaded, or if a copy is sent to anyone.    

![Screenshot](http://www.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1446224224-84184-6545/Capture.JPG)

**Comment by Captainkirkdawson** [comment]
Following the abortive and acrimonious consultation with coordinators that did not lead to any consensus. 
I adopted the following. Active users get emails on success/failure of every file processed by FR. The SC gets a copy of every file processed for a member of their syndicate unless they were the owner. The CC gets a copy of every file processed for their count unless that already got a copy as the SC or the owner.

**Comment by edickens** [comment]
```
Do you use the email address in the UserID or the file header, and
if the latter, which one as there can be two, the transcriber and
the uploader?  E
```

**Comment by Captainkirkdawson** [comment]
I am sorry Eric but how many times do I have to say that FR makes no use of the header emails other than for display as part of the header information!
All email addresses are taken from the userid.

**Comment by edickens** [comment]
```
It is just that it needs to be said in the Help.  E

On 30/10/2015 17:44, Kirk Dawson wrote:


  I am sorry Eric but how many times do I have to say that FR
    makes no use of the header emails other than for display as part
    of the header information!
    All email addresses are taken from the userid.
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by AlOneill** [comment]
So, to summarise, the 'Uploading files' page should say, in effect, that:
- When a File is Uploaded and Processed, _whoever uploaded it_ will get a confirmation email.
- The SC of the _person uploading the file_ will get a copy of the email, unless they are one and the same person.
- The CC of the relevant county will also get a copy of the email, unless they are also the SC or the uploader.

In other words, if a file is uploaded and processed by anyone _other than the Transcriber_, the Transcriber will _not_ get a copy of the email -- the Transcriber's email address in the File headers is for information only.

What about a previously processed file that is Replaced: does the above apply again?

**Comment by Captainkirkdawson** [comment]
Afraid   not Alison; sent email off list

**Comment by AlOneill** [comment]
I have added to the Info for Coords page:

**Please note that**: If you Upload or Replace a file for one of your Transcribers, then both yourself and the Transcriber will get an email reporting the success or failure of the processing. In addition, the other relevant SC or CC will get a copy of the email (unless they have been sent one anyway). The only exception is that Inactive Transcribers will not be sent an email.

And to the Uploading files page (in Info for Transcribers):

Your SC will also get a copy of the email, as will the relevant CC (if they are not the same person as your SC)

**Comment by edickens** [comment]
```
Inactive transcribers cannot get emails because then cannot log in
and so cannot upload.  But a SC can upload into these accounts, and
if this happens then the transcriber should definitely not get the
email.

On 06/11/2015 18:15, AlOneill wrote:


  I have added to the Info for Coords page:
  Please note that: If you Upload or Replace a
    file for one of your Transcribers, then both yourself and the
    Transcriber will get an email reporting the success or failure
    of the processing. In addition, the other relevant SC or CC will
    get a copy of the email (unless they have been sent one anyway).
    The only exception is that Inactive Transcribers will not be
    sent an email.
  And to the Uploading files page (in Info for Transcribers):
  Your SC will also get a copy of the email, as will the relevant
    CC (if they are not the same person as your SC)
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by Captainkirkdawson** [comment]
Dependant on 626

**Comment by Captainkirkdawson** [comment]
see 625
