### ISSUE TITLE
Ardwick cemetery year errors (keithhayton)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#568]
Issue reported by **keithhayton** at 2015-10-30 19:08:45 UTC
Time: 2015-10-30T19:05:08+00:00
Session ID: dc278107074f4bff81ca7edcb0aa7fc4
Problem Page URL: [/freereg_contents/Burial/show_decade](/freereg_contents/Burial/show_decade)
Previous Page URL: [http://www.freereg.org.uk/freereg_contents/5408374ceca9eb81e2ec8f10/show_register](http://www.freereg.org.uk/freereg_contents/5408374ceca9eb81e2ec8f10/show_register)
Reported Issue:
The cemetery opened in 1838 and closed in 1950 so, by definition, those entries on FreeReg that lie outside these years must be in error.  Could someone look into the alleged burial records before 1838 and after 1950 in order to make necessary corrections please    

![Screenshot](http://www.freereg.org.uk)

**Comment by PatReynolds** [comment]
Does Eric (B) see these messages, or should I forward to him?

Pat Reynolds
Executive Director, Free UK Genealogy

**Comment by Sherlock21** [comment]
Hi,Pat

yes I do get them, and i have passed this one on the the LAN CC. - to whom it should have gone in the first place - as I can;t see who it was addressed to.

Its a transcribing snag if its anything.
Thanks
ericB

**Comment by PatReynolds** [comment]
Thanks!

Pay

Pat Reynolds
Executive Director, Free UK Genealogy
