### ISSUE TITLE
Lancaster St John baptism errors (keithhayton)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#569]
Issue reported by **keithhayton** at 2015-10-30 19:27:07 UTC
Time: 2015-10-30T19:16:22+00:00
Session ID: dc278107074f4bff81ca7edcb0aa7fc4
Problem Page URL: [/freereg_contents/540a017ceca9ebd28ec5b9f3/show_register](/freereg_contents/540a017ceca9ebd28ec5b9f3/show_register)
Previous Page URL: [http://www.freereg.org.uk/freereg_contents/540a017ceca9ebd28ec5b9f1/show_church](http://www.freereg.org.uk/freereg_contents/540a017ceca9ebd28ec5b9f1/show_church)
Reported Issue:
in the database report for Lancaster St John parish register baptisms there are three that are recorded as being in 1964, which seem likely to be year errors.  They are not in the records transcribed by me between 1750 and 1900, so are presumably in the batch done by Amanda Astin, who transcribed between 1691 and 1749.  Could someone check these records please.
Keith Hayton    

![Screenshot](http://www.freereg.org.uk)

**Comment by PatReynolds** [comment]
Do the "data" issues get routed here?  Or are transcribers ignoring Eric
D's email?

Pat Reynolds
Executive Director, Free UK Genealogy

**Comment by Captainkirkdawson** [comment]
Data errors are not routed here

This is a transcriber who has logged in and browsed the contents and sent in a feedback report which was expected to be used by transcribers and coordinators to report problems and issues with the system
So yes he is ignoring Eric's note if he saw it

**Comment by Sherlock21** [comment]
Suggestions that there are Transcription errors should go direct to the CC. Not to DM. I cant do anything other than post forward to the CC concerned & I have more to worry about than being a post box.
