### ISSUE TITLE
Lancaster St John baptisms (keithhayton)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#570]
Issue reported by **keithhayton** at 2015-10-30 20:00:13 UTC
Time: 2015-10-30T19:55:15+00:00
Session ID: dc278107074f4bff81ca7edcb0aa7fc4
Problem Page URL: [/freereg_contents/Baptism/show_decade](/freereg_contents/Baptism/show_decade)
Previous Page URL: [http://www.freereg.org.uk/freereg_contents/540a017ceca9ebd28ec5b9f3/show_register](http://www.freereg.org.uk/freereg_contents/540a017ceca9ebd28ec5b9f3/show_register)
Reported Issue:
There are numerous baptisms listed between 1690 and 1749 under the database contents page for Lancaster St John (transcribed by Amanda Astin apparently), but Lancaster St John church was not dedicated until 1755, so these baptisms must be wrongly attributed.  I think that they should be for Lancaster St Mary the Priory church, which was the only church in Lancaster at that period.
Keith Hayton    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Data issue only
