### ISSUE TITLE
re downloading weird batches from KEN/ pateric/ BA8 repeatedly crashes out. (ericb)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#571]
Issue reported by **ericb** at 2015-10-31 15:32:45 UTC
Time: 2015-10-31T15:27:50+00:00
Session ID: 62414e76aa878828ccdb75da59aca5a9
Problem Page URL: [/manage_counties/selection?option=Review%20Batches%20by%20Userid%20then%20Filename](/manage_counties/selection?option=Review%20Batches%20by%20Userid%20then%20Filename)
Previous Page URL: []()
Reported Issue:
I just tried to download the first of the batches from KEN/ userID pateric/ filename KENxxxBA8.csv and it crashes on me with the red "Something seems to have gone wrong" msg.
- it was the FIRST row in the list for this user,  with no place name or church.
  email to Kirk relates  

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
The system is correct there is missing information so it is likely better that there be a crash than trying to download something that is incorrect.
