### ISSUE TITLE
Activate is off the screen and no scroll bar (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#573]
Issue reported by **REGManager** at 2015-11-01 11:49:12 UTC
Time: 2015-11-01T11:46:49+00:00
Session ID: 46b369eb9238097eae7de2ef729f2646
Problem Page URL: [/userid_details](/userid_details)
Previous Page URL: [http://www.freereg.org.uk/manage_syndicates/select_action](http://www.freereg.org.uk/manage_syndicates/select_action)
Reported Issue:
In Syndicates list of UserIDs the Act button is off the screen and not visible.  See screenprint.  E    

![Screenshot](http://www.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1446378552-96993-9036/Capture.JPG)

**Comment by edickens** [comment]
Forget what I said.  The screen I was looking at were all Active.  But it might be helpful to show the Inactive in a different colour (they are red in FR1) because the only indication is the button on the right changing to ACT to show that they are Inactive people.  E

**Comment by Captainkirkdawson** [comment]
Not true There is a Y/N flag on every line.
