### ISSUE TITLE
major security snag (alsibk)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#574]
Issue reported by **alsibk** at 2015-11-01 13:47:05 UTC
Time: 2015-11-01T13:26:32+00:00
Session ID: ed03b1a35a69731dd82a61bb3399b0c4
Problem Page URL: [/freereg1_csv_files/5462b420e937907d70000534/by_userid](/freereg1_csv_files/5462b420e937907d70000534/by_userid)
Previous Page URL: [http://www.freereg.org.uk/freereg1_csv_files/5462b420e937907d70000534/by_userid](http://www.freereg.org.uk/freereg1_csv_files/5462b420e937907d70000534/by_userid)
Reported Issue:
I logged on with Ali's ID.
Access: User IDs
then Select a UserID ( I chose Doreens)

List Batches > gives attached collection.
Chose any row. They are all green normal state.
Picked L/U (as this is Production data) I could change it back again.
Changed one row. It responded correctly.

Changed it back again  quickly.
I would guess any green actions would respond the same way but would not be recoverable here.

![Screenshot](http://www.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1446385625-96993-5303/snag.jpg)

**Comment by Captainkirkdawson** [comment]
Dam good catch, that was added 8 months ago when someone wanted to be able to find out how to email someone.
Have left in the basic display but nothing else
