### ISSUE TITLE
Start and end date (alycymru)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#575]
Issue reported by **alycymru** at 2015-11-01 15:03:37 UTC
Time: 2015-11-01T15:02:09+00:00
Session ID: 89ee429b0e970974006a6c8c5cef2f0b
Problem Page URL: [/freereg1_csv_entries](/freereg1_csv_entries)
Previous Page URL: [http://freereg2.freereg.org.uk/freereg1_csv_files/54639fade937904abba268a4](http://freereg2.freereg.org.uk/freereg1_csv_files/54639fade937904abba268a4)
Reported Issue:
Start and end date do not correspond with data    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Reprocessing of the file cleared any issues
