### ISSUE TITLE
Redirection of Comment messages (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#576]
Issue reported by **REGManager** at 2015-11-01 15:28:14 UTC
Time: 2015-11-01T15:25:11+00:00
Session ID: aac92de3c81db1691a6ead401d2bccb1
Problem Page URL: [/contacts](/contacts)
Previous Page URL: [http://www.freereg.org.uk/manage_resources/new](http://www.freereg.org.uk/manage_resources/new)
Reported Issue:
Hi Kirk,
Will you please amend the email address for Comments which are addressed to me as the suggested person to answer to Damien at damien@dcpendleton.plus.com
At present the address you use is freereg.edickens+REG@gmail.com but I can't find where I can amend this.
TY E    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Your request is not practical.

Emails do not go to people. They go to the people who have specified roles. Just to avoid requests such as this.

data problem subject go to data managers (unless they cam in from the record page in which case they go to the coordinator with a cc to DM)
website problem subject go to system administrators
Volunteer subjects go to volunteer coordinators and a copy to REGmanger ( Not sure you have ever assigned the volunteer coordinator role)
Question and thank you subjects go to system administrators

If we are to have a contact_responder then I suggest that we define that as a role. You assign that to whomever ie Damian
Then we have certain contact subject go to the contact responder. Perhaps you start with question thank you subjects

emails are sent to people with the relevant role in FR. ie emails that are website problems go to system_administrators.  volunteer goes to the volunteer coordinator.

**Comment by PatReynolds** [comment]
Agreed in meeting

**Comment by PatReynolds** [comment]
Agreed in meeting

**Comment by Captainkirkdawson** [comment]
The contact for question and thank you will go to Damien. Should a copy go anywhere else?

General data problems will go to DM as before (Specific ones still go to CC)

Website will still go to SA with Eric as the lead.

**Comment by Captainkirkdawson** [comment]
Still waiting for answer as to whether copy is need and if so to whom?

**Comment by Captainkirkdawson** [comment]
Have placed Daien in as the contacts coordinator with a copy also going to Eric
