### ISSUE TITLE
No records shown in Browse records (alsibk)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#577]
Issue reported by **alsibk** at 2015-11-02 08:03:56 UTC
Time: 2015-11-02T08:00:13+00:00
Session ID: 20e43a279a543773d5b7c9f11bf1b2f6
Problem Page URL: [/freereg1_csv_entries](/freereg1_csv_entries)
Previous Page URL: [http://www.freereg.org.uk/freereg1_csv_files/5636c5d2f493fd4d4100c022](http://www.freereg.org.uk/freereg1_csv_files/5636c5d2f493fd4d4100c022)
Reported Issue:
Browse records shows no records. Screenshot WRYLINBA1.CSV.

This file has 2240 records somewhere.    

![Screenshot](http://www.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1446451436-31599-3482/No_records_shown.jpg)

**Comment by Captainkirkdawson** [comment]
fixed
