### ISSUE TITLE
No display of records (MikeNL)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#578]
Issue reported by **MikeNL** at 2015-11-02 09:47:17 UTC
Time: 2015-11-02T09:45:54+00:00
Session ID: f6b31d283df720400c23424ad8f4b8df
Problem Page URL: [/freereg1_csv_entries](/freereg1_csv_entries)
Previous Page URL: [http://freereg2.freereg.org.uk/freereg1_csv_files/5463af28e93790278201ab6c](http://freereg2.freereg.org.uk/freereg1_csv_files/5463af28e93790278201ab6c)
Reported Issue:
When attempting to browse a file the box that usually contains records does not contain any.    

![Screenshot](http://www.freereg.org.uk)

**Comment by PatReynolds** [comment]
This is marked as duplicated, but I can't find which issue it duplicates.

**Comment by Captainkirkdawson** [comment]
Cannot remember # was an issue that several people had. Has been fixed.
This can be closed

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1
