### ISSUE TITLE
Cannot upload an amended file. (Bombhead)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#579]
Issue reported by **Bombhead** at 2015-11-02 12:20:56 UTC
Time: 2015-11-02T12:12:57+00:00
Session ID: 70a8c67d0d409d953ac483c2ce389505
Problem Page URL: [/manage_resources/new](/manage_resources/new)
Previous Page URL: [http://freereg2.freereg.org.uk/freereg1_csv_files/my_own](http://freereg2.freereg.org.uk/freereg1_csv_files/my_own)
Reported Issue:
Previously I could, after a transcribing session, just go to the file and replace. Now, if Itry, all I get is told that a batch under that heading already exists and basically I am told to go away. Why are things steadily becoming more complicated?    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Being dealt with in 628
