### ISSUE TITLE
Norfolk database contents  (JulieHarold)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#580]
Issue reported by **JulieHarold** at 2015-11-02 14:16:19 UTC
Time: 2015-11-02T14:15:31+00:00
Session ID: 28f181b2e5b9a0ee9507f07f2644e440
Problem Page URL: [/freereg_contents//show_place](/freereg_contents//show_place)
Previous Page URL: [http://freereg2.freereg.org.uk/freereg_contents/new](http://freereg2.freereg.org.uk/freereg_contents/new)
Reported Issue:
trying to do a county summary and get - oops - something went wrong.  

Julie (Norfolk coordinator)    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
There is no crash report in errbit or the logs.

**Comment by Captainkirkdawson** [comment]
/freereg_contents//show_place  indicates that attempt was made to show a place that had not been selected. How the user does that is beyond me but have put in traps for possible blank selections for place, church, register, and decade.
