### ISSUE TITLE
Unlock on multiple batches in the same file (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#581]
Issue reported by **REGManager** at 2015-11-03 10:54:22 UTC
Time: 2015-11-03T10:52:53+00:00
Session ID: 053169015bf47e46b915fe51c6a14435
Problem Page URL: [/freereg1_csv_files/5462b41fe937907d70000523/by_userid](/freereg1_csv_files/5462b41fe937907d70000523/by_userid)
Previous Page URL: [http://www.freereg.org.uk/freereg1_csv_files/5462b41fe937907d70000523/by_userid](http://www.freereg.org.uk/freereg1_csv_files/5462b41fe937907d70000523/by_userid)
Reported Issue:
See attached.  Selecting Unlock has no effect.  E    

![Screenshot](http://www.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1446548062-58230-5695/Capture.JPG)

**Comment by Sherlock21** [comment]
I am sure that it worked for me yesterday. the lock was Y by CC, and the Transcriber flag was N and I undid the Y Ok.

**Comment by edickens** [comment]
```
I'll try again and confirm.  E

On 03/11/2015 11:51, Sherlock21 wrote:


  I am sure that it worked for me yesterday. the lock was Y by
    CC, and the Transcriber flag way N and i undid the Y Ok.
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by edickens** [comment]
```
I think I have solved the problem.  There are two batches with the
same filename in this UserID davejoSTS and when I unlock one it does
it on the other.  In fact there are other duplicate entries in the
batches list, for one there are six with the same name but different
places, so could be different place names in the one file.  Will
have to sort this out with Kirk.  E

On 03/11/2015 11:51, Sherlock21 wrote:


  I am sure that it worked for me yesterday. the lock was Y by
    CC, and the Transcriber flag way N and i undid the Y Ok.
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by Captainkirkdawson** [comment]
The lock operates at the file level not the batch level. There is no easy way of locking just at a batch level; this is one of the reasons why we really should discourage the practise. Implementation of batch locking would require that we process a file and do the lock check when we go to replace the records and if set not proceed with the processing of that part of the file. This means that we have files where some batches have been updated and other batches which is going to really confuse people. What could be done is to flag that when unlocking one batch in a multi batch file the other batches will be unlocked and to list those

**Comment by Captainkirkdawson** [comment]
Have improved the messages and made it consistent
