### ISSUE TITLE
Too many Register type to change online  (alsibk)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#582]
Issue reported by **alsibk** at 2015-11-03 11:53:50 UTC
Time: 2015-11-03T11:48:07+00:00
Session ID: b511ec5d4a46c9fe27681e2fd19bf455
Problem Page URL: [/registers/5409ad96eca9eb260e4d135f](/registers/5409ad96eca9eb260e4d135f)
Previous Page URL: [http://www.freereg.org.uk/registers/5409ad96eca9eb260e4d135f](http://www.freereg.org.uk/registers/5409ad96eca9eb260e4d135f)
Reported Issue:
Too many registers to change type.

Go to individual files, no facility to edit register type.

What am I missing please?

If we have to download and replace to carry out functions, where's the improvement?    

![Screenshot](http://www.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1446551630-58227-3386/Register_type_change.jpg)

**Comment by edickens** [comment]
```
You can use Relocate.  The only problem with this is that the
version on the transcribers computer will not match, although you
could Download after Relocate.
But this is not the most important job at present.  E

On 03/11/2015 11:53, FreeUKGenIssues
  wrote:


  Issue reported by alsibk at 2015-11-03
    11:53:50 UTC
    Time: 2015-11-03T11:48:07+00:00
    Session ID: b511ec5d4a46c9fe27681e2fd19bf455
    Problem Page URL: /registers/5409ad96eca9eb260e4d135f
    Previous Page URL: http://www.freereg.org.uk/registers/5409ad96eca9eb260e4d135f
    Reported Issue:
    Too many registers to change type.
  Go to individual files, no facility to edit register type.
  What am I missing please?
  If we have to download and replace to carry out functions,
    where's the improvement? 

  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by sean-wood** [comment]
will not fix due to system constraints
