### ISSUE TITLE
Re-alignment of buttons (MikeNL)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#584]
Issue reported by **MikeNL** at 2015-11-03 13:38:43 UTC
Time: 2015-11-03T13:01:20+00:00
Session ID: 0e326d1ebcfe846e90194e15ff29a524
Problem Page URL: [/freereg1_csv_files/54639005e9379010fc4fb5ba](/freereg1_csv_files/54639005e9379010fc4fb5ba)
Previous Page URL: [http://freereg2.freereg.org.uk/registers/54081a95eca9eb0248adf24d](http://freereg2.freereg.org.uk/registers/54081a95eca9eb0248adf24d)
Reported Issue:
The gap between the "List of all Error Records in this Batch" button and the "Remove Batch" button is not consistent with the other gaps between buttons on this display.

May I also suggest that the "Relocate" button is put onto the same line as the other two coordinator-only buttons. That way, there is a clear distinction between transcriber's optiona and coordinator's options.    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Implemented
