### ISSUE TITLE
Decadels no longer using birth date on Baptism records (MikeNL)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#585]
Issue reported by **MikeNL** at 2015-11-03 14:57:40 UTC
Time: 2015-11-03T14:48:53+00:00
Session ID: 0e326d1ebcfe846e90194e15ff29a524
Problem Page URL: [/freereg1_csv_entries](/freereg1_csv_entries)
Previous Page URL: [http://freereg2.freereg.org.uk/freereg1_csv_files/54639006e9379010fc4fba59](http://freereg2.freereg.org.uk/freereg1_csv_files/54639006e9379010fc4fba59)
Reported Issue:
Firstly, I am assuming that decadels, once calculated for a file, are not re-calculated for that file unless the file changes.

I have a file that is showing the value 1 in one entry in a decadel. In one version of the file (older) this single entry, if searched for, is a birth date. In a later version of the same file, although the birth date is still in the file but does not get counted in the decadel.    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Decada range is recomputed when a record changes

**Comment by Captainkirkdawson** [comment]
Birth date is used if baptism date is not present.
