### ISSUE TITLE
Change Coordinator (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#587]
Issue reported by **REGManager** at 2015-11-03 21:19:28 UTC
Time: 2015-11-03T21:17:27+00:00
Session ID: 1008939e62022c28c5579ba3f526050c
Problem Page URL: [/syndicates](/syndicates)
Previous Page URL: [http://www.freereg.org.uk/manage_resources/new](http://www.freereg.org.uk/manage_resources/new)
Reported Issue:
I am trying to change the GLS Coordinator but I am getting "Something went wrong" for both Show and Edit.  It is the same for other Syndicates.  E    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Forgot to add the scope when  nil and blank deletion was added to conrollers
