### ISSUE TITLE
Wrong list of Userids appear for Northumberland under Susan Marr (susiem)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#588]
Issue reported by **susiem** at 2015-11-04 09:32:39 UTC
Time: 2015-11-04T09:14:36+00:00
Session ID: a0273b79f1d08b64d93376f8006502e7
Problem Page URL: [/csvfiles/5463a08ce937904abba7910c/edit](/csvfiles/5463a08ce937904abba7910c/edit)
Previous Page URL: [http://www.freereg.org.uk/freereg1_csv_files](http://www.freereg.org.uk/freereg1_csv_files)
Reported Issue:
I am logged on as susiem, coordinator for Northumberland. I was trying to change a church name which had a silly ending. I downloaded and altered it on notepad and was trying to REplace.
This came up with a list of userids to allocate it to which are not for Northumberland
This included Susan's but not mine nejws05
I do remember one of the Eric's saying she appeared under Devon
Eric Wealleans
eric.wealleans@btinternet.com    

![Screenshot](http://www.freereg.org.uk)

**Comment by edickens** [comment]
Hi Eric,

```
Susiem is registered in Devon, which I think is why you got that
list of UserIDs.  But she is set as Syndicate Coordinator for
Northumberland.  Her role is as a County Coordinator and she is
County Coordinator for Northumberland.

So I think you have found a bug.  It looks as if the server is
taking Devon's list of UserIDs, not Susie's Syndicate of
Northumberland.

I don't know why she is registered for DEV, so when Kirk has had a
look at this I will move her to Northumberland and that should fix
the problem.
```

**Comment by Captainkirkdawson** [comment]
The SC gets a list of people for their syndicate; it matters not what their personal syndicate is. The CC gets a full list of all people. Unable to reproduce.

**Comment by edickens** [comment]
```
This is similar to the problem Mary had.  We need to know which
Action they were using to reproduce.  E


On 13/11/2015 22:56, Kirk Dawson wrote:


  The SC gets a list of people for their syndicate; it matters
    not what their personal syndicate is. The CC gets a full list of
    all people. Unable to reproduce.
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by Captainkirkdawson** [comment]
Its closed until I get something far more substantial to go on. I have made myself just a coordinator and cannot duplicate
