### ISSUE TITLE
Not receiving registrant's confirmation email (alsibk)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#589]
Issue reported by **alsibk** at 2015-11-04 11:12:13 UTC
Time: 2015-11-04T11:09:05+00:00
Session ID: 06c2ab33bcf0b53484f573ec91b7abc2
Problem Page URL: [/userid_details/5632111ef493fd42380007e1](/userid_details/5632111ef493fd42380007e1)
Previous Page URL: [http://www.freereg.org.uk/userid_details/selection?option=Select%20specific%20userid](http://www.freereg.org.uk/userid_details/selection?option=Select%20specific%20userid)
Reported Issue:
3 times in last week I have not received email as below----

You should receive confirmation of that final step in the registration processas soon as they have actioned that link.

They are NOT in my spam box.    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Dependent on 626

**Comment by Captainkirkdawson** [comment]
Have rewritten distribution code.
