### ISSUE TITLE
WinFreeREG (MikeNL)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#593]
Issue reported by **MikeNL** at 2015-11-06 23:14:28 UTC
Time: 2015-11-06T23:10:53+00:00
Session ID: bd5586a51b0b4eed916c3d91623c936f
Problem Page URL: [/information-for-transcribers/creating-a-transcription-file](/information-for-transcribers/creating-a-transcription-file)
Previous Page URL: [http://freereg2.freereg.org.uk/information-for-transcribers](http://freereg2.freereg.org.uk/information-for-transcribers)
Reported Issue:
At this time (06 Nov) there is no released version of this software available to transcribers.

Why is it being promoted? 

Is this another example of the Help being supplied for future software rather than what is now available.    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Mike

That is just not true.

WinReg continues to work just fine as a transcription tool and there is
every reason to continue to use it and promote it. The name change is just
that a name change to get over an issue where many virus scanners think
winreg is a virus and this is as good a time as any to so do

The only thing it cannot do is to connect through a gateway into the
server. This simply means that the transcriber has to upload the file that
WinReg creates which is the way WinReg was used for the first 7 years of it
life.

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by PatReynolds** [comment]
No issue, so closed.

**Comment by Captainkirkdawson** [comment]
Issue is the documentation refers to it and yet there is no such product available as of today

**Comment by PatReynolds** [comment]
Ah - because of hosting of WinREG ceasing ...  Would putting it on our
dropbox be a solution?

_\- -_

_Dr Pat Reynolds_
Executive Director
Free UK Genealogy  http://www.freeukgenealogy.org.uk/
A charity registered in England and Wales, number 1096940

​+44 ​1904 541411​ +44 7943 145387

36 Albemarle Road, York, YO23 1ER, UK

**Comment by Captainkirkdawson** [comment]
No its just the name change; the coordinator is saying that the documentation on WinReg refers to it by its new name WinFreeREG and the product is not using that new name yet!!

**Comment by AlOneill** [comment]
Have edited the [Creating a transcription file](http://www.freereg.org.uk/information-for-transcribers/creating-a-transcription-file) page to describe the current situation more clearly.
