### ISSUE TITLE
Breadcrumbs don't work correctly (steveroland)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#594]
Issue reported by **steveroland** at 2015-11-07 14:11:58 UTC
Time: 2015-11-07T14:07:13+00:00
Session ID: 9d9f3146b4995b4a133d21488666c496
Problem Page URL: [/freereg1_csv_files](/freereg1_csv_files)
Previous Page URL: [http://www.freereg.org.uk/freereg1_csv_files/5639fa71f493fd8aef000001](http://www.freereg.org.uk/freereg1_csv_files/5639fa71f493fd8aef000001)
Reported Issue:
Select 'County options' -> 'List batches by date of upload (descending)', click 'SH' on one of the batches, then click the breadcrumb 'List batches' and there are no batches listed. So you have to go back through 'County options'.    

![Screenshot](http://www.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1446905518-36600-6091/Capture.jpg)

**Comment by Captainkirkdawson** [comment]
Steve: I am unable to duplicate this issue as described.

Are you able to reproduce?

Had you done something else after the show?

**Comment by Captainkirkdawson** [comment]
Hi Kirk,

It happens consistently for me -
- click 'Manage Counties' - select SSX (or SRY)
- click 'Review batches ...'
- click 'SH' on any file to show Batch Information
- click 'List of Batches' breadcrumb at top and I get an empty list

Steve

**Comment by Captainkirkdawson** [comment]
Ah; associated with being a DM will dig into why

**Comment by Captainkirkdawson** [comment]
Please go to test3 and check it out for me.

**Comment by Captainkirkdawson** [comment]
Yes, works fine, now.

Thanks
Steve

**Comment by Captainkirkdawson** [comment]
Fixed
