### ISSUE TITLE
Bad format date accepted (Seamus)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#595]
Issue reported by **Seamus** at 2015-11-08 10:34:54 UTC
Time: 2015-11-08T10:27:20+00:00
Session ID: 84ab2abb8a7367d5e3670fb41ba9b39b
Problem Page URL: [/freereg1_csv_entries](/freereg1_csv_entries)
Previous Page URL: [http://test3.freereg.org.uk/freereg1_csv_files/563dc5efe93790c882000001](http://test3.freereg.org.uk/freereg1_csv_files/563dc5efe93790c882000001)
Reported Issue:
Bad format date (common problem with spreadsheet) accepted as OK

05-Sep-00    

![Screenshot](http://test3.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1446978894-95613-5300/Bad_date.jpg)

**Comment by Captainkirkdawson** [comment]
Dependent on 610

**Comment by dougkdev** [comment]
This format is erroneously accepted because FreeregValidations.cleandate()
splits on spaces, so the entire "05-Sep-00" is passed to check_year(), and
immediately matches the WILD_CHARACTER regular expression because of the
dash, returning true.

The UCF documentation at
http://www.freereg.org.uk/information-for-transcribers/dealing-with-uncertainty#ucf
doesn't mention dashes as wildcards, only underscores.  Is it ok to remove
the dash from the WILD_CHARACTER regular expression, or are dashes used as
some other meaning in UCF and need to be added to the documentation?

**Comment by EmJayFry** [comment]
On 12 Dec 2015 8:50 AM, dougkdev wrote:

> This format is erroneously accepted because FreeregValidations.cleandate()
> splits on spaces, so the entire "05-Sep-00" is passed to check_year(), and
> immediately matches the WILD_CHARACTER regular expression because of the
> dash, returning true.

WinREG currently permits the use of three separators in dates - spaces, - and /

## 

Regards,
Mike Fry (Jhb)

**Comment by edickens** [comment]
```
Hi Mike,

But think it should upload them all as Spaces.

Also, that date should have four characters of Year.  The example
would be 05 Sep 2000 or perhaps 1900.   My guess is that this person
is not using WinReg.

E


On 12/12/2015 07:44, Mike wrote:

On 12 Dec 2015 8:50 AM, dougkdev wrote:

  > This format is erroneously accepted because
  FreeregValidations.cleandate()
  > splits on spaces, so the entire "05-Sep-00" is passed to
  check_year(), and
  > immediately matches the WILD_CHARACTER regular expression
  because of the
  > dash, returning true.

  WinREG currently permits the use of three separators in dates -
  spaces, - and /

  -- 
  Regards,
  Mike Fry (Jhb)
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by EmJayFry** [comment]
On 12 Dec 2015 10:06 AM, Eric Dickens wrote:

> But think it should upload them all as Spaces.

It does. But I can't be responsible for files created with a spreadsheet and 
uploaded via a browser. Yet!

## 

Regards,
Mike Fry (Jhb)

**Comment by Captainkirkdawson** [comment]
I believe the test should have been against VALID_UCF rather than WILD_CHARACTER.

Even then the problem will still occur as - was included (by me unilaterally since many people "misuse" the - as a missing field indicator). Best solution is to use VALID_UCF and withdraw the - from it.

**Comment by edickens** [comment]
```
Where I have seen hyphens is usually because Excel has tried to be
too clever and converted the entry into something more recent than
1900 and so is in fact an error.  I think we should only accept a
space as the separator in dates.  WinReg and any online data entry
that we do can make sure that this is the case.  E


On 12/12/2015 17:46, Kirk Dawson wrote:


  I believe the test should have been against VALID_UCF rather
    than WILD_CHARACTER.
  Even then the problem will still occur as - was included (by me
    unilaterally since many people "misuse" the - as a missing field
    indicator). Best solution is to use VALID_UCF and withdraw the -
    from it.
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by dougkdev** [comment]
Thanks.  Will follow Kirk's suggestion.
