### ISSUE TITLE
lock/unlock (deo123)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#596]
Issue reported by **deo123** at 2015-11-08 14:36:29 UTC
Time: 2015-11-08T14:26:29+00:00
Session ID: d049dcb284c6c83d51dbc3c227dae7c5
Problem Page URL: [/manage_counties/selection?option=Review%20Batches%20by%20Userid%20then%20Filename](/manage_counties/selection?option=Review%20Batches%20by%20Userid%20then%20Filename)
Previous Page URL: [http://www.freereg.org.uk/manage_counties/selection?option=Review%20Batches%20by%20Userid%20then%20Filename](http://www.freereg.org.uk/manage_counties/selection?option=Review%20Batches%20by%20Userid%20then%20Filename)
Reported Issue:
Hi Guy's,

me again.  Oh no you say well, some little mouse has to burrow around.

I have two problems, but will deal with !st one here. Same files/batches same Userid.

County GLS
USerid jimanderin
Batch GLSABEBU (3 batches)

If I try to unlock one of these files as it is in blue, then it LOCKS the other two after saying update of the batch was successful, see attachment.
So just wondering if I am finally loosing it.

Regards Doreen    

![Screenshot](http://www.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1446993389-23794-3792/Lock-Unlock_GLSABEBU_jimanderrin.JPG)

**Comment by Captainkirkdawson** [comment]
We were always going to have "difficulties" with files that have multiple
batches. So I am not surprised at this and the other report. I will
investigate in due course.
There are two suggested courses of action.
1) If the batches are created by errors then correct the errors and merge
into a single file. You already know how to do this.
2) If the batches are legitimately different. Download each batch in turn,
rename the downloaded file as soon as downloaded (they will all download
with the same file name) retaining the same filename for the largest batch.
Once all are downloaded then replace the main file, This should remove all
but the main batch. Then upload the other files that were created. This
process creates one batch per file.
We need to document both of these for all coordinators

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Sherlock21** [comment]
I would be in favour of just dividing into 3 distinct files and going down Kirk's Plan 3 route.
I will work with Doreen to do this. But can't get logged on right now due to overloading.
Do you want it to remain as an issue to resolve the coding Kirk?

**Comment by Captainkirkdawson** [comment]
Lets leave open. I need to look at this over time. Also we need to document the 2 approaches. Will spin off separate story for that.

You should be able to get in now. Severs could not cope with SOM listing all files several times. Another issue!!
