### ISSUE TITLE
review specific batch (deo123)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#597]
Issue reported by **deo123** at 2015-11-08 14:49:14 UTC
Time: 2015-11-08T14:39:52+00:00
Session ID: d049dcb284c6c83d51dbc3c227dae7c5
Problem Page URL: [/manage_counties/selection?option=Review%20Specific%20Batch](/manage_counties/selection?option=Review%20Specific%20Batch)
Previous Page URL: [http://www.freereg.org.uk/manage_counties/select_action.%3Fcounty=Gloucestershire](http://www.freereg.org.uk/manage_counties/select_action.%3Fcounty=Gloucestershire)
Reported Issue:
Hi Guy's,

yes, it is your trusty mouse again. with No2.

county GLS
userid jimanderin
batch(S) GLSABEBU

as you know there are three of these batches, with the same Userid & Batch/file name
They do have different Place/church names.
Yes, I know should never have happened in F1.

So we have
Abenhall (1 batch)
Parkend (Forest of Dean) (2 batches)

When I select "review Specific batch only one batch is shown, although there are two different place names. Then I thought AH!!  same Id same Batch name so I entry.??????
But I click this entry it takes me to just one of the batches. And not the one I wanted.

Regards Doreen

![Screenshot](http://www.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1446994154-23794-0960/GLSABEBU__three_files.JPG)

**Comment by Captainkirkdawson** [comment]
I believe that this issue has been resolved. Looking at the description the situation no longer seems to exist.
