### ISSUE TITLE
Document how to deal with multiple batches in a file

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeUKRegProductIssues#598]
Sometimes there is a need to deal with multiple batches in a file. We should document for coordinators the best way of dealing with them.
1) If the batches are created by errors in church and register and place then correct the errors and merge into a single file. Process. Correct each batch in turn.until there are multiple batches that are all the same place/church/register then merge the batches with the same filename into the largest batch. Then delete any empty register/churches
2) If the batches are legitimately different. Download each batch in turn,
rename the downloaded file as soon as downloaded (they will all download
with the same file name) retaining the same file name for the largest batch.
Once all are downloaded then replace the main file, This should remove all
but the main batch. Then upload the other files that were created. This
process creates one batch per file.

**Comment by AlOneill** [comment]
Noted. Will email draft separately when done.

**Comment by AlOneill** [comment]
Done. See section on [Coordinator actions](http://www.freereg.org.uk/information-for-coordinators/coordinator-actions#multiBatch) page.

**Comment by Captainkirkdawson** [comment]
Excellent
