### ISSUE TITLE
Too much button - too little text (MikeNL)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#600]
Issue reported by **MikeNL** at 2015-11-09 00:25:16 UTC
Time: 2015-11-09T00:23:08+00:00
Session ID: e6210eed1ca92557bc42d1c6e4c22a21
Problem Page URL: [/registers/55eafaf7f493fdd3ed0001d0](/registers/55eafaf7f493fdd3ed0001d0)
Previous Page URL: [http://freereg2.freereg.org.uk/churches/55eafac8f493fdd3ed0001ce](http://freereg2.freereg.org.uk/churches/55eafac8f493fdd3ed0001ce)
Reported Issue:
Since the update on 8 Nov the text on a lot of buttons has been made a lot smaller and less clear. However, the buttons seem to be the same size.    

![Screenshot](http://www.freereg.org.uk)

**Comment by PatReynolds** [comment]
Will be dealt with in #548 (Access issues)

**Comment by Captainkirkdawson** [comment]
Not sure why this will be dealt with under #548. Very different issues and #548 is already closed, that issue related to the Members link on the navigation bar not being there under some conidtions

**Comment by PatReynolds** [comment]
548 on the waffle board is 'accessibility' - github has a different issue.

On Wednesday, 11 November 2015, Kirk Dawson notifications@github.com
wrote:

> Not sure why this will be dealt with under #548
> https://github.com/FreeUKGen/FreeUKRegProductIssues/issues/548. Very
> different issues and #548
> https://github.com/FreeUKGen/FreeUKRegProductIssues/issues/548 is
> already closed, that issue related to the Members link on the navigation
> bar not being there under some conidtions
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/FreeUKGen/FreeUKRegProductIssues/issues/600#issuecomment-155852557
> .

## 

_\- -_

_Dr Pat Reynolds_
Executive Director
Free UK Genealogy  http://www.freeukgenealogy.org.uk/
A charity registered in England and Wales, number 1096940

​+44 ​1904 541411​ +44 7943 145387

36 Albemarle Road, York, YO23 1ER, UK

**Comment by Captainkirkdawson** [comment]
Noted. Would be nice if there were separate numbering schemes for our
sources; Had this problem before, Github linked your closure to the github
one hence the comment!!
Sorry about that,
Ecstatic to see someone looking at these issues

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1
