### ISSUE TITLE
Waiting for processing not showing (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#601]
Issue reported by **REGManager** at 2015-11-09 04:45:21 UTC
Time: 2015-11-09T04:41:41+00:00
Session ID: c6cd7a7e9592ecd74e345ffe230ae025
Problem Page URL: [/freereg1_csv_files/my_own](/freereg1_csv_files/my_own)
Previous Page URL: [http://www.freereg.org.uk/freereg1_csv_files/selection?option=List%20files%20waiting%20to%20be%20processed](http://www.freereg.org.uk/freereg1_csv_files/selection?option=List%20files%20waiting%20to%20be%20processed)
Reported Issue:
I have just uploaded five small files and set them for overnight processing.  But if I look at my Batches "Waiting for processing" report there is nothing there.  It may be that this report is for when the file fails to process after the overnight update, but I think transcribers may think that their file has disappeared into the ether and they will upload again.  E    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Up early. Files are shown as waiting in PhysicalFiles for you and in the processing list for tonight.

**Comment by Captainkirkdawson** [comment]
A screen shot of your waiting for processing would have been helpful.

**Comment by Captainkirkdawson** [comment]
Any better now?

**Comment by edickens** [comment]
```
Yes, OK now.
(Still recovering from the fireworks success, so not back to routine
yet!!)

On 09/11/2015 05:12, Kirk Dawson wrote:


  Any better now?
  —
    Reply to this email directly or view
      it on GitHub.
```
