### ISSUE TITLE
listings not sorted properly (JulieHarold)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#602]
Issue reported by **JulieHarold** at 2015-11-09 07:45:05 UTC
Time: 2015-11-09T07:41:51+00:00
Session ID: 48f3d40010be80743b3c3551a60b4770
Problem Page URL: [/freereg1_csv_files](/freereg1_csv_files)
Previous Page URL: [http://freereg2.freereg.org.uk/manage_syndicates/select_action.%3Fsyndicate=Norfolk,%20Suffolk%20and%20Essex%20-%20Julie%20Harold](http://freereg2.freereg.org.uk/manage_syndicates/select_action.%3Fsyndicate=Norfolk,%20Suffolk%20and%20Essex%20-%20Julie%20Harold)
Reported Issue:
Further to an email I just sent Kirk, if I select files sorted by oldest date it isn't in date order.  The first file does seem to be one of mine from 2008 - I am positive there are older files than that.

I think this used to work  (I am sure I would  have noticed if it hadn't) - but I only use this one rarely so can't comment on how long it has been wrong.

Julie (NFK,SFK,ESS)    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Resolved
