### ISSUE TITLE
new layout for users batches (jmh)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#603]
Issue reported by **jmh** at 2015-11-09 14:53:47 UTC
Time: 2015-11-09T14:52:51+00:00
Session ID: 2460d19d280e9a348b349005d00eb212
Problem Page URL: [/freereg1_csv_files/my_own](/freereg1_csv_files/my_own)
Previous Page URL: [http://freereg2.freereg.org.uk/csvfiles](http://freereg2.freereg.org.uk/csvfiles)
Reported Issue:
just wanted to say I really like the new layout for batches for users - much better :)

Julie  (Nfk, Sfk, Ess coordinator)    

![Screenshot](http://www.freereg.org.uk)

**Comment by PatReynolds** [comment]
Nice to hear!
