### ISSUE TITLE
Error in data not picked up (alsibk)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#605]
Issue reported by **alsibk** at 2015-11-09 16:54:14 UTC
Time: 2015-11-09T16:49:02+00:00
Session ID: fd7d54d385849ed0dfefa1b3853e652f
Problem Page URL: [/manage_resources/new](/manage_resources/new)
Previous Page URL: [http://www.freereg.org.uk/refinery/login](http://www.freereg.org.uk/refinery/login)
Reported Issue:
re email notification----

WRYBUSBA.CSV

The file submitted for processing has been completed. We processed 1804 records and there were 0 data errors and 0 header errors.

This file had an error in  birthdate, "year 190" 

So why no errors reported to transcriber/uploader?    

![Screenshot](http://www.freereg.org.uk)

**Comment by PatReynolds** [comment]
Not sure if this is a bug or a data issue.

**Comment by Captainkirkdawson** [comment]
Perhaps a bug; not a data problem

**Comment by Captainkirkdawson** [comment]
Same as 654
