### ISSUE TITLE
Updating thom:teresea does not bring up the Profile (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#606]
Issue reported by **REGManager** at 2015-11-09 22:49:29 UTC
Time: 2015-11-09T22:47:19+00:00
Session ID: 66fda78d33028bae0d8c87f72d4b59c2
Problem Page URL: [/userid_details/select?name=thom:teresa](/userid_details/select?name=thom:teresa)
Previous Page URL: [http://www.freereg.org.uk/userid_details/selection?option=Select%20specific%20surname/forename](http://www.freereg.org.uk/userid_details/selection?option=Select%20specific%20surname/forename)
Reported Issue:
Something is wrong with this Profile (last in list by name) so that it goes to the list of Syndicates.  E    

![Screenshot](http://www.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1447109369-80153-2788/Capture.JPG)

**Comment by edickens** [comment]
There were others that also went to "List of syndicates" and not the Profile when selected from "Manage UserID"/"List by name".  I had to browse all the UserIDs to find the names and have just done an edit.  This seems to have recreated the links.  They no longer go to "List of Syndicates".  I don't know if there are others as I have just edited those names where the Surname started lowercase.
Suggest that validation ensues last name starts with a capital if the listing of UserIDs by name cannot be sorted case insensitive.  E

**Comment by edickens** [comment]
Have just checked again and links still do not work.  Try using UserID by name then select McCluskey:Charlotte.

**Comment by edickens** [comment]
I have now been through all the 2,234 Profiles and have removed all Spaces after firstnames which were in 40 records.  There were a few after lastnames and some before firstnames.  I have done these as well.  Also, to get the sort sequence right, I have put all those lastnames that were all capitals to be lowercase starting with a capital.
But please note:-
- There is one record that is all blanks, including UserID and Name, and I cannot delete that, even though I can see it.
- I recommend that the Action to list Profiles by name should sort case insensitive.
- The validation when amending a Profile should ensure no trailing or starting spaces in names.
  E

**Comment by Captainkirkdawson** [comment]
Blank record removed
