### ISSUE TITLE
I cannot re-activate a userid with a different email address (MikeNL)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#607]
Issue reported by **MikeNL** at 2015-11-10 19:21:00 UTC
Time: 2015-11-10T19:13:45+00:00
Session ID: 524aa8b418a80492ad6989eb80a77ba3
Problem Page URL: [/userid_details/5462b40ce937907d700001f3/edit](/userid_details/5462b40ce937907d700001f3/edit)
Previous Page URL: [http://freereg2.freereg.org.uk/userid_details/select?name=Waltho:Jane](http://freereg2.freereg.org.uk/userid_details/select?name=Waltho:Jane)
Reported Issue:
I have a transcriber who had two userids, one was active and the other in-active. Because of her unusual surname she wanted some anonymity and she requested the userid that was inactive but wanted the email address of the active userid.

So, active made inactive and vice versa for the two userids. This seemed to be successful.

However, I cannot change the email address of the re-activated userid to the one that was, and still is, in the now de-actvated userid. The change is accepted and submitted but when revisitint the re-activated userid, it still shows the old email. So the change was not actioned.

Why?    

![Screenshot](http://www.freereg.org.uk)

**Comment by edickens** [comment]
```
Because at one stage you will have the same email address in both. 
Email address has to be unique.

- Amend the unwanted UserID's email address by just adding an X
somewhere.
- Copy and paste this email address to the Active UserID, but remove
the X before saving.
- Change the email address in the unwanted email address to
something that will work but different.

E

_____________________________________
```

Eric J Dickens
FreeREG Chairman
    On 10/11/2015 19:21, FreeUKGenIssues
      wrote:

```
  Issue reported by MikeNL at 2015-11-10
    19:21:00 UTC
    Time: 2015-11-10T19:13:45+00:00
    Session ID: 524aa8b418a80492ad6989eb80a77ba3
    Problem Page URL: /userid_details/5462b40ce937907d700001f3/edit
    Previous Page URL: http://freereg2.freereg.org.uk/userid_details/select?name=Waltho:Jane
    Reported Issue:
    I have a transcriber who had two userids, one was active and the
    other in-active. Because of her unusual surname she wanted some
    anonymity and she requested the userid that was inactive but
    wanted the email address of the active userid.
  So, active made inactive and vice versa for the two userids.
    This seemed to be successful.
  However, I cannot change the email address of the re-activated
    userid to the one that was, and still is, in the now de-actvated
    userid. The change is accepted and submitted but when revisitint
    the re-activated userid, it still shows the old email. So the
    change was not actioned.
  Why? 

  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by PatReynolds** [comment]
Ready to close?

**Comment by Captainkirkdawson** [comment]
Yes

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1
