### ISSUE TITLE
Test3 Place Selection stray code (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#608]
Issue reported by **REGManager** at 2015-11-12 07:33:47 UTC
Time: 2015-11-12T07:32:30+00:00
Session ID: 410d47434e00ee5e1937ca65104eb49a
Problem Page URL: [/freereg_contents](/freereg_contents)
Previous Page URL: [http://test3.freereg.org.uk/freereg_contents/new](http://test3.freereg.org.uk/freereg_contents/new)
Reported Issue:
There is a piece of stray coding.  See screen print.  E    

![Screenshot](http://test3.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1447313627-56823-6442/Capture.JPG)

**Comment by Captainkirkdawson** [comment]
Ben this has nothing to do with the search, It was an unchanged helper which did not reflect the rewrite of Database Contents. Was fixed
