### ISSUE TITLE
database contents : county summary  (JHarold)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#609]
Issue reported by **JHarold** at 2015-11-12 08:18:38 UTC
Time: 2015-11-12T08:16:36+00:00
Session ID: ba928ae4d54cf3694d0d2e3097c9d370
Problem Page URL: [/freereg_contents/new](/freereg_contents/new)
Previous Page URL: [http://freereg2.freereg.org.uk/search_queries/new](http://freereg2.freereg.org.uk/search_queries/new)
Reported Issue:
Odd results - when asking for a county summary getting 

"If you have arrived at page expecting to find the original freereg search page please note that that site is no longer supported but remains available at Original Freereg Website
If not click the return on your browser and renter your request."

Julie (Essex, Norfolk, Suffolk)    

![Screenshot](http://www.freereg.org.uk)

**Comment by PatReynolds** [comment]
I could swear that I 've already seen this error but now cannot trace the issue.

**Comment by edickens** [comment]
```
Julie.  Is this the production version or Kirk's Test3?

On 12/11/2015 08:52, PatReynolds wrote:


  I could swear that I 've already seen this error but now cannot
    trace the issue.
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by Captainkirkdawson** [comment]
Have deployed the new version to see if it resolves the issue. No point trying to fix the old version.
