### ISSUE TITLE
Reviewing active members - not members of syndicate (MaryKay)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#610]
Issue reported by **MaryKay** at 2015-11-12 11:00:20 UTC
Time: 2015-11-12T10:55:33+00:00
Session ID: c34bf900f331ab65cbf2628f854dd394
Problem Page URL: [/userid_details](/userid_details)
Previous Page URL: [http://freereg2.freereg.org.uk/manage_syndicates/select_action](http://freereg2.freereg.org.uk/manage_syndicates/select_action)
Reported Issue:
Selecting 'review active members' gives a list of IDs whose names I do not recognise as active members.  I think there are three who have been members.  One now belongs to another syndicate and two have been disabled as I don't think they ever uploaded any CAM/HUN (or BDF) files

Cannot send screen shot as no idea how to turn it into any of the file types you accept    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
This is not a development issue. Coordinators needs assistance to learn how to use the tools available.
