### ISSUE TITLE
Freereg2 is still in use (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#611]
Issue reported by **REGManager** at 2015-11-12 13:41:01 UTC
Time: 2015-11-12T13:37:34+00:00
Session ID: d95bc52164af44f06264a08e28bbd407
Problem Page URL: [/manage_resources/new](/manage_resources/new)
Previous Page URL: [http://www.freereg.org.uk/refinery/login](http://www.freereg.org.uk/refinery/login)
Reported Issue:
Mary (CAM) has used Freereg2  (see screenshot) and this has given her a list of all UserIDs although she is just a CC and SC.  But I thought Kirk said that this would direct you to the live version.  This does not seem to be the case.  I recommend that freereg2 be taken down.  E    

![Screenshot](http://www.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1447335661-15043-8130/Capture.JPG)

**Comment by Captainkirkdawson** [comment]
I am sorry Eric there is no difference between Freereg2 and Freereg. There is only one piece of software and there is only one database. 
Both urls go to other addresses anyway depending on the server selected by the system which are actually www13.freereg.org.uk or 14 or 15 or 16 or 17.
All Members when logged in run on www13 regardless
There was an issue with syndicates that Steve was having and I fixed that.
I am totally unable to reproduce the effect on my server, test3 or the production server.
Until there is additional information the matter is considered closed.

**Comment by edickens** [comment]
Agreed.  I think it was another problem.  Mary was seeing more
    UserIDs than she expected, and the only difference I could see to
    what I got was freereg2.  But since then I have been through all her
    UserIDs and they are all her syndicate.
    Please close.  E
    _____________________________________
Eric J Dickens
FreeREG Chairman
    On 13/11/2015 22:48, Kirk Dawson wrote:

```
  I am sorry Eric there is no difference between Freereg2 and
    Freereg. There is only one piece of software and there is only
    one database. 
    Both urls go to other addresses anyway depending on the server
    selected by the system which are actually www13.freereg.org.uk
    or 14 or 15 or 16 or 17.
    All Members when logged in run on www13 regardless
    There was an issue with syndicates that Steve was having and I
    fixed that.
    I am totally unable to reproduce the effect on my server, test3
    or the production server.
    Until there is additional information the matter is considered
    closed.
  —
    Reply to this email directly or view
      it on GitHub.
```
