### ISSUE TITLE
Uploading a file directly into FR showed error message but appears to be OK (AMSA)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#615]
Issue reported by **AMSA** at 2015-11-14 10:42:39 UTC
Time: 2015-11-14T10:37:09+00:00
Session ID: b29b4cff28098aa08b5d4129f22e72d5
Problem Page URL: [/manage_syndicates/select_action](/manage_syndicates/select_action)
Previous Page URL: [http://www.freereg.org.uk/manage_resources/new](http://www.freereg.org.uk/manage_resources/new)
Reported Issue:
Writing on behalf of my transcriber Alex17
He uploaded his first file into FR & received an error message & asked me to investigate. I can find nothing wrong with the file but he still would like an explanation, especially with regards the comment re his email address.

NTHSTNBA   uploaded 29Oct2015
The error comments  are exactly as follows:
Expected 5-12 parts in a  +INFO line (got 15) at line 1 + 
INFO, alexanderstewart390@btinternet#com, password, SEQUENCED, BAPTISMS, No Name
3#02#18,F8 to F15(separated by commas).
Unknown problem with your e-mail address.   Is your resolver resolving?
- same statement as above from INFO.......

Many thanks
Anna Rufer - NTH coordinator

![Screenshot](http://www.freereg.org.uk)

**Comment by edickens** [comment]
Hi Anna,
    The email address is an easy one.  It should not have a # in it.
    The first bit is because there are too many fields on the end of the
    first +INFO header record.  He seems to have got an Excel function
    in there.
    The best thing in these cases is to get the transcriber to email you
    their file and then you can look at exactly what was entered.
    Regards Eric

   .

**Comment by edickens** [comment]
Hi Anna,
FR accepts all valid records but reports on any error records.  So the file will be searchable in total, even if some of the header information is wrong.  But interesting that it shows in his FR list of files as Error Free, but I expect that is because all the entries are error free.
In FR1 this error of extra fields on the end of a record would would be a yellow Caution, just as the wrong format email address would be a Caution, as they do not cause data to be rejected.
Regards Eric

**Comment by Captainkirkdawson** [comment]
You should be aware that the quoted error message is NOT a FR error message. We do not care how many extra fields there are in the file.
The message quoted is actually an FR1 error message. I suspect that the transcriber has loaded a file that contains the FR1 errors messages within its headers. We likely made enough sense of what was there to process the file
