### ISSUE TITLE
The new Transcriptions pages. (AMSA)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#616]
Issue reported by **AMSA** at 2015-11-14 10:52:47 UTC
Time: 2015-11-14T10:45:21+00:00
Session ID: b29b4cff28098aa08b5d4129f22e72d5
Problem Page URL: [/freereg_contents](/freereg_contents)
Previous Page URL: [http://www.freereg.org.uk/freereg_contents/new](http://www.freereg.org.uk/freereg_contents/new)
Reported Issue:
No problem.
Just wanted to say I like the new "Transcriptions" page MUCH BETTER!
Thank you. Thank you. Thank you!!!
The stats come up when I first go to the county now, and the format of the county page, with places down 1 side & letter range down the other is  both nicer to look at & easier to navigate. I would still like as few alpha options as possible -  A-G, H-M, N-S, T-Z???  but this is still a vast improvement.
Anna - NTH COord.    

![Screenshot](http://www.freereg.org.uk)

**Comment by edickens** [comment]
I agree with Anna about the new "Transcriptions".
    On the subject of the Alphabetic ranges, I don't mind the present
    set, provided they are all visible and no scrolling is needed, and
    you can just hit one and it goes.
    E
