### ISSUE TITLE
Search is not picking up any pre 1740 baptisms even though file is in the database (SOMCoord)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#617]
Issue reported by **SOMCoord** at 2015-11-14 18:09:27 UTC
Time: 2015-11-14T18:04:30+00:00
Session ID: 6e436144a348fbf4bd1225c9a702e353
Problem Page URL: [/search_queries/564777aef493fda76e000e94](/search_queries/564777aef493fda76e000e94)
Previous Page URL: [http://www.freereg.org.uk/search_queries](http://www.freereg.org.uk/search_queries)
Reported Issue:
Problem came to light from a researcher. Earlier Baptisms including for the surname BOND are included in file SOMPITBA, which for some reason the search is not picking up. As Coordinator I have checked and see no reason why  not.    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
The file as loaded does not have any pre 1740 baptisms for BOND. It has 22
bond entries and all are displayed in a search. The file has 1704 records
that start in 1538 and end in 1816.

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1
