### ISSUE TITLE
Automatic locking not required (hawkinssm)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#618]
Issue reported by **hawkinssm** at 2015-11-15 12:12:49 UTC
Time: 2015-11-15T12:08:28+00:00
Session ID: 458c3e93cca0dd02685ec8ec3ca7865e
Problem Page URL: [/freereg1_csv_files/5463af41e9379010fcf22eac](/freereg1_csv_files/5463af41e9379010fcf22eac)
Previous Page URL: [http://freereg2.freereg.org.uk/freereg1_csv_files/update_registers?church=540812a7eca9eb02489983f1](http://freereg2.freereg.org.uk/freereg1_csv_files/update_registers?church=540812a7eca9eb02489983f1)
Reported Issue:
I am using relocate to change a batch description from unspecified to PR.

Not that it matters (I guess) but this change results in a change from Teal to blue.

Incidentally, would it not be helpful to have the default situation for relocation to be set to the place and church being relocated, rather than having to chase around for them.

Thanks

Graham Upton (Sue Hawkins' body double): grahamjgu@gmail.com    

![Screenshot](http://www.freereg.org.uk)

**Comment by edickens** [comment]
```
Graham,
The reason is that the version on the server now disagrees with that
on the transcribers computer.  If they do not change then when they
next upload they will recreate the old register type.  But if you
download the file so that it is the same on the server as on your
computer, the lock is automatically removed.  E

On 15/11/2015 12:12, FreeUKGenIssues
  wrote:


  Issue reported by hawkinssm at 2015-11-15
    12:12:49 UTC
    Time: 2015-11-15T12:08:28+00:00
    Session ID: 458c3e93cca0dd02685ec8ec3ca7865e
    Problem Page URL: /freereg1_csv_files/5463af41e9379010fcf22eac
    Previous Page URL: http://freereg2.freereg.org.uk/freereg1_csv_files/update_registers?church=540812a7eca9eb02489983f1
    Reported Issue:
    I am using relocate to change a batch description from
    unspecified to PR.
  Not that it matters (I guess) but this change results in a
    change from Teal to blue.
  Incidentally, would it not be helpful to have the default
    situation for relocation to be set to the place and church being
    relocated, rather than having to chase around for them.
  Thanks
  Graham Upton (Sue Hawkins' body double): grahamjgu@gmail.com


  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by Captainkirkdawson** [comment]
I hope you copied this to Graham

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by edickens** [comment]
Yes.  E

---

Eric J Dickens
FreeREG Chairman
