### ISSUE TITLE
Website Problem (Michael James EDGOOSE)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#620]
Issue reported by **Michael James EDGOOSE** at 2015-11-15 13:44:34 UTC
Time: 2015-11-15T13:36:01+00:00
Session ID: 
Problem Page URL: []()
Previous Page URL: [http://www.freereg.org.uk/contacts](http://www.freereg.org.uk/contacts)
Reported Issue:
VEHANT? = VIRGIN.

I have no access to the original register but the proof can be found in later census entries for Eliza Butcher of Martock.
If in doubt consult the transcriptions under Eliza BUTCHER born 1842 on database medgoose1538 at WorldConnect. She later married Giles Tolley.

George Butcher of Martock is my gggrandfather.

www.wc.rootsweb.ancestry.com/cgi-bin/igm.cgi?db=medgoose1538    

![Screenshot](http://www.freereg.org.uk)

**Comment by edickens** [comment]
```
I have had two contact reports with this same information.  E

On 15/11/2015 13:44, FreeUKGenIssues
  wrote:


  Issue reported by Michael James EDGOOSE at
    2015-11-15 13:44:34 UTC
    Time: 2015-11-15T13:36:01+00:00
    Session ID: 
    Problem Page URL: 
    Previous Page URL: http://www.freereg.org.uk/contacts
    Reported Issue:
    VEHANT? = VIRGIN.
  I have no access to the original register but the proof can be
    found in later census entries for Eliza Butcher of Martock.
    If in doubt consult the transcriptions under Eliza BUTCHER born
    1842 on database medgoose1538 at WorldConnect. She later married
    Giles Tolley.
  George Butcher of Martock is my gggrandfather.
  www.wc.rootsweb.ancestry.com/cgi-bin/igm.cgi?db=medgoose1538


  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by PatReynolds** [comment]
Forwarded to Damian CC Eric D for resolution
