### ISSUE TITLE
Profile telephone number visible (DavidJames)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#621]
Issue reported by **DavidJames** at 2015-11-15 16:15:53 UTC
Time: 2015-11-15T16:11:25+00:00
Session ID: e5719afca2b62c165ddda1e4db74135c
Problem Page URL: [/userid_details/my_own?](/userid_details/my_own?)
Previous Page URL: [http://www.freereg.org.uk/manage_resources/new](http://www.freereg.org.uk/manage_resources/new)
Reported Issue:
I don't know if my telephone number is supposed to be hidden or not on my profile (for security reasons), but I can see it because the lettering is in white against a very light grey background.  If the background was white it would be invisible.    

![Screenshot](http://www.freereg.org.uk)

**Comment by PatReynolds** [comment]
Issue continued, and dealt with, as #622
