### ISSUE TITLE
Profile telephone number visible (DavidJames)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#622]
Issue reported by **DavidJames** at 2015-11-15 16:18:44 UTC
Time: 2015-11-15T16:15:54+00:00
Session ID: e5719afca2b62c165ddda1e4db74135c
Problem Page URL: [/userid_details/my_own?](/userid_details/my_own?)
Previous Page URL: [http://www.freereg.org.uk/feedbacks/new?utf8=%E2%9C%93&feedback_time=2015-11-15+16%3A11%3A25+UTC&session_id=e5719afca2b62c165ddda1e4db74135c&user_id=DavidJames&problem_page_url=%2Fuserid_details%2Fmy_own%3F&previous_page_url=http%3A%2F%2Fwww.freereg.org.uk%2Fmanage_resources%2Fnew&feedback_type=issue](http://www.freereg.org.uk/feedbacks/new?utf8=%E2%9C%93&feedback_time=2015-11-15+16%3A11%3A25+UTC&session_id=e5719afca2b62c165ddda1e4db74135c&user_id=DavidJames&problem_page_url=%2Fuserid_details%2Fmy_own%3F&previous_page_url=http%3A%2F%2Fwww.freereg.org.uk%2Fmanage_resources%2Fnew&feedback_type=issue)
Reported Issue:
Sorry - this is a continuation of an earlier report.  Just noticed that the telephone number on my profile is both visible AND selectable as it is detected as a link on my iPad!  Perhaps it ought to be shown as a string of asterisks.    

![Screenshot](http://www.freereg.org.uk)

**Comment by edickens** [comment]
```
David,
The telephone number is optional.  You can remove it.  We only ask
in case we lose contact with you by email.  We don't ask for your
address.
But a good point about it being hidden.  It is available only to you
and Coordinators and Administration.  This should be mentioned in
the Help notes.
Thanks Eric
_____________________________________
```

Eric J Dickens
FreeREG Chairman
    On 15/11/2015 16:18, FreeUKGenIssues
      wrote:

```
  Issue reported by DavidJames at 2015-11-15
    16:18:44 UTC
    Time: 2015-11-15T16:15:54+00:00
    Session ID: e5719afca2b62c165ddda1e4db74135c
    Problem Page URL: /userid_details/my_own?
    Previous Page URL: http://www.freereg.org.uk/feedbacks/new?utf8=%E2%9C%93&feedback_time=2015-11-15+16%3A11%3A25+UTC&session_id=e5719afca2b62c165ddda1e4db74135c&user_id=DavidJames&problem_page_url=%2Fuserid_details%2Fmy_own%3F&previous_page_url=http%3A%2F%2Fwww.freereg.org.uk%2Fmanage_resources%2Fnew&feedback_type=issue
    Reported Issue:
    Sorry - this is a continuation of an earlier report. Just
    noticed that the telephone number on my profile is both visible
    AND selectable as it is detected as a link on my iPad! Perhaps
    it ought to be shown as a string of asterisks. 

  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by AlOneill** [comment]
Done.
