### ISSUE TITLE
Inadvertent disabling of Relocation (hawkinssm)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#624]
Issue reported by **hawkinssm** at 2015-11-16 09:23:17 UTC
Time: 2015-11-16T09:18:48+00:00
Session ID: e9193239424e3dbf416342f37c9d0e1a
Problem Page URL: [/freereg1_csv_files](/freereg1_csv_files)
Previous Page URL: [http://freereg2.freereg.org.uk/freereg1_csv_files/5463927ce9379010fc5d6d75](http://freereg2.freereg.org.uk/freereg1_csv_files/5463927ce9379010fc5d6d75)
Reported Issue:
I have been adding PR to old files.

Clicking on Relocate brought up an "Are you sure?" window. There appeared to be an option to disable that window. So I disabled it.

The result appears to be that I have disabled my ability to relocate!
Presumably not the intention of the tick box.

grahamjgu@gmail.com

PS I will log out and re-login.

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
The disabling of the challenge is not an option that we provide; it is one
that your browser decides to offer you.

In my opinion the challenge should never be disabled. It is there for a
reason to make sure that you really want to do what you have asked the
system to do. Its time for a sober thought in stead of just charging ahead.
Recovery from a mistake can often be 100 times worse than the extra second
of thinking before acting.

K

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1
