### ISSUE TITLE
File not showing (derekg)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#629]
Issue reported by **derekg** at 2015-11-17 10:23:10 UTC
Time: 2015-11-17T10:06:36+00:00
Session ID: 89d0275fc2d5ee0fdf894a7b9f559ba5
Problem Page URL: [/freereg1_csv_files/my_own](/freereg1_csv_files/my_own)
Previous Page URL: [http://freereg2.freereg.org.uk/manage_resources/new](http://freereg2.freereg.org.uk/manage_resources/new)
Reported Issue:
I am currently working on St Giles - Rowley Regis -  Burials  (STSROWBU1) which I have uploaded a few times as a new file. This file does not appear on my list of files despite repeatedly uploading as a new file. Why does it not appear?
I get messages that it has been accepted for processing, so FreeReg does know it exists.
Do I keep uploading it as a new file and hope that eventually it will appear, or what?
Please advise.
The original file STSROWBU is on the list but not STSROWBU1.
Help please.
Derek Gardner    

![Screenshot](http://www.freereg.org.uk)

**Comment by edickens** [comment]
```
Hi Derek,

I cannot find your UserID in the overnight updates.  Did you load
into FreeREG1 or the new FreeREG?  If so which date?  Have you
received an email to say that your file has been processed?  Is it
just that it does not show in the list of Places?

Regards,

Eric
_____________________________________
```

Eric J Dickens
FreeREG Chairman
    On 17/11/2015 10:23, FreeUKGenIssues
      wrote:

```
  Issue reported by derekg at 2015-11-17
    10:23:10 UTC
    Time: 2015-11-17T10:06:36+00:00
    Session ID: 89d0275fc2d5ee0fdf894a7b9f559ba5
    Problem Page URL: /freereg1_csv_files/my_own
    Previous Page URL: http://freereg2.freereg.org.uk/manage_resources/new
    Reported Issue:
    I am currently working on St Giles - Rowley Regis - Burials
    (STSROWBU1) which I have uploaded a few times as a new file.
    This file does not appear on my list of files despite repeatedly
    uploading as a new file. Why does it not appear?
    I get messages that it has been accepted for processing, so
    FreeReg does know it exists.
    Do I keep uploading it as a new file and hope that eventually it
    will appear, or what?
    Please advise.
    The original file STSROWBU is on the list but not STSROWBU1.
    Help please.
    Derek Gardner 

  —
    Reply to this email directly or view
      it on GitHub.
```
