### ISSUE TITLE
Limited CC options (alsibk)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#630]
Issue reported by **alsibk** at 2015-11-17 14:42:21 UTC
Time: 2015-11-17T14:37:56+00:00
Session ID: efeafab925b557e6fe19cdfbfb454a12
Problem Page URL: [/manage_counties/select_action](/manage_counties/select_action)
Previous Page URL: [http://www.freereg.org.uk/manage_syndicates/select_action](http://www.freereg.org.uk/manage_syndicates/select_action)
Reported Issue:
In CC options there is no "List files awaiting processing"

Why is this please?    

![Screenshot](http://www.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1447771341-43702-3433/cc_options.jpg)

**Comment by PatReynolds** [comment]
Ali replied:
It is a feature that I feel should be available in both CC and SC functions.

CCs should be able to see a list of files waiting to be processed particularly as we are told that---

County Coordinator (CC) actions deal with the data

This highlights the peculiarity of separating these functions which were in the past all down to CCs

**Comment by edickens** [comment]
```
Due in a future version.  The RAP (Records Available - and in
progress -Page) will address this problem.  We had the "In progress"
in FR1.
Although we have not looked at the detail yet, it should be a report
which Coordinators use to know what is going on, waiting to be done,
or where there are problems, or where a transcriber seems to have
stalled.  The key management report.  E

On 08/12/2015 14:22, PatReynolds wrote:


  Ali replied:
    It is a feature that I feel should be available in both CC and
    SC functions.
  CCs should be able to see a list of files waiting to be
    processed particularly as we are told that---
  County Coordinator (CC) actions deal with the data
  This highlights the peculiarity of separating these functions
    which were in the past all down to CCs
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by PatReynolds** [comment]
#68 (the RAP)
