### ISSUE TITLE
Suggestions for naming of fields (MikeNL)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#633]
Issue reported by **MikeNL** at 2015-11-19 17:43:08 UTC
Time: 2015-11-19T14:38:12+00:00
Session ID: e1561e28be5c0dd153861a70d36f5cd1
Problem Page URL: [/freereg1_csv_files/555d5440f493fdb12d029893](/freereg1_csv_files/555d5440f493fdb12d029893)
Previous Page URL: [http://freereg2.freereg.org.uk/freereg1_csv_files/555d5440f493fdb12d029893/edit](http://freereg2.freereg.org.uk/freereg1_csv_files/555d5440f493fdb12d029893/edit)
Reported Issue:
"Minimum year in dataset" could become "Earliest year in file" (or batch) because many transcribers are not tekkies.

"Maximum year in dataset" could become "Latest year in file" as above    

![Screenshot](http://www.freereg.org.uk)

**Comment by PatReynolds** [comment]
Workding is clear on Researcher interface - version changed to 1.6

**Comment by Captainkirkdawson** [comment]
Internal display only; field name changed
