### ISSUE TITLE
Batches waiting for processing 20/11/2015 (Dinahst)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#634]
Issue reported by **Dinahst** at 2015-11-20 09:51:20 UTC
Time: 2015-11-20T09:49:06+00:00
Session ID: 02ec119d8f6a9f7263e55e585fd2f736
Problem Page URL: [/freereg1_csv_files/selection?option=List%20files%20waiting%20to%20be%20processed](/freereg1_csv_files/selection?option=List%20files%20waiting%20to%20be%20processed)
Previous Page URL: [http://freereg2.freereg.org.uk/freereg1_csv_files/my_own?](http://freereg2.freereg.org.uk/freereg1_csv_files/my_own?)
Reported Issue:
I have several batches that have been waiting for processing since 16/11/2015.  Is there a problem?    

![Screenshot](http://www.freereg.org.uk)

**Comment by edickens** [comment]
```
Yes.  Transcribers and Coordinators have been told, but if you are
not on the list you will not know.
PS.  I do not know this person's email address from this message so
cannot reply.
_____________________________________
```

Eric J Dickens
FreeREG Chairman
    On 20/11/2015 09:51, FreeUKGenIssues
      wrote:

```
  Issue reported by Dinahst at 2015-11-20
    09:51:20 UTC
    Time: 2015-11-20T09:49:06+00:00
    Session ID: 02ec119d8f6a9f7263e55e585fd2f736
    Problem Page URL: /freereg1_csv_files/selection?option=List%20files%20waiting%20to%20be%20processed
    Previous Page URL: http://freereg2.freereg.org.uk/freereg1_csv_files/my_own?
    Reported Issue:
    I have several batches that have been waiting for processing
    since 16/11/2015. Is there a problem? 

  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by PatReynolds** [comment]
I have it (the email address) and will send privately.
