### ISSUE TITLE
Replacing a file not working first time round (Kyran)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#635]
Issue reported by **Kyran** at 2015-11-20 22:08:21 UTC
Time: 2015-11-20T22:04:08+00:00
Session ID: ea235cff6d07acd93517530fb457ef65
Problem Page URL: [/csvfiles/5463a84fe937902782d664c1/edit](/csvfiles/5463a84fe937902782d664c1/edit)
Previous Page URL: [http://freereg2.freereg.org.uk/csvfiles/5463a84fe937902782d664c1/edit](http://freereg2.freereg.org.uk/csvfiles/5463a84fe937902782d664c1/edit)
Reported Issue:
"The upload with file name LNDNEWBA.CSV was unsuccessful because {:file_name=>["A file of that name already exists. You cannot upload a file with the same name. You must replace the existing file"]} "
This is the message I continue to receive when doing a Replace.  If I do it exactly the same way again it works.  Very frustrating & time consuming.  I am doing Replace & not an unload.
Thanks,
Kyran Payne
Middlesex & London Coordinator    

![Screenshot](http://www.freereg.org.uk)

**Comment by PatReynolds** [comment]
I have let kyran know of the issue we are having.

Pat Reynolds
Executive Director, Free UK Genealogy

**Comment by Sherlock21** [comment]
Which is the correct # number that covers this one then, please Pat?
because I have just had the same rejection.

**Comment by PatReynolds** [comment]
Replied offline to Sherlock21

**Comment by Captainkirkdawson** [comment]
Kyran

I am unable to duplicate. Can you email me directly you experience the
first rejection with time and file number so I can explore the logs

Thx

K

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1
