### ISSUE TITLE
Incorrect church name (deo123)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#636]
Issue reported by **deo123** at 2015-11-21 14:41:14 UTC
Time: 2015-11-21T14:33:55+00:00
Session ID: 557c4226b31db22e4fd217ed35fa0157
Problem Page URL: [/places?page=](/places?page=)
Previous Page URL: [http://www.freereg.org.uk/registers/5407e5edeca9eb1ee030aff2](http://www.freereg.org.uk/registers/5407e5edeca9eb1ee030aff2)
Reported Issue:
Hi Techies,

yes! it is me again.

Tried to "relocate a batch"  have already done loads today. so not confused.

Well it did do the reloacte but look what it has given as the church name.
Lanteglos-by-Fowey, snippet attached.

Also the responce time today is not good. very slow just to view places.

Regards Doreen    

![Screenshot](http://www.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1448116874-27940-8750/change_register_type.JPG)

**Comment by edickens** [comment]
```
I think that the update is trying to catch up, which is why things
are slow and I asked people not to upload until we know all is
well.  E

On 21/11/2015 14:41, FreeUKGenIssues
  wrote:


  Issue reported by deo123 at 2015-11-21
    14:41:14 UTC
    Time: 2015-11-21T14:33:55+00:00
    Session ID: 557c4226b31db22e4fd217ed35fa0157
    Problem Page URL: /places?page=
    Previous Page URL: http://www.freereg.org.uk/registers/5407e5edeca9eb1ee030aff2
    Reported Issue:
    Hi Techies,
  yes! it is me again.
  Tried to "relocate a batch" have already done loads today. so
    not confused.
  Well it did do the reloacte but look what it has given as the
    church name.
    Lanteglos-by-Fowey, snippet attached.
  Also the responce time today is not good. very slow just to
    view places.
  Regards Doreen 

  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by Captainkirkdawson** [comment]
EricB could you clean this up please its one of those occasional oddities
