### ISSUE TITLE
Change waiting for processing selection (deo123)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#637]
Issue reported by **deo123** at 2015-11-22 11:30:30 UTC
Time: 2015-11-22T11:27:10+00:00
Session ID: 0e00a5ad301bdb6a92f93231c825477a
Problem Page URL: [/manage_syndicates/display_files_waiting_to_be_processed](/manage_syndicates/display_files_waiting_to_be_processed)
Previous Page URL: [http://www.freereg.org.uk/manage_syndicates/select_action](http://www.freereg.org.uk/manage_syndicates/select_action)
Reported Issue:
Hi yes it is me again.

what would you do without me to annoy you.

I have a file still waiting for process, submitted on the 17th Nov.

Regards Doreen    

![Screenshot](http://www.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1448191830-63195-0626/waiting_for_process.JPG)

**Comment by Captainkirkdawson** [comment]
Never a concern over a well stated issues with documentation.

Have resubmitted; likely got lost in one of our problems on Thursday.

We need to change how we pick up the waiting files.

**Comment by Captainkirkdawson** [comment]
Rather than create and destroy a list; select those with the waiting flag set.

**Comment by Captainkirkdawson** [comment]
rake task added to create list just before update starts
