### ISSUE TITLE
Replacing an existing file (Mick)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#638]
Issue reported by **Mick** at 2015-11-22 20:04:07 UTC
Time: 2015-11-22T20:01:41+00:00
Session ID: 1834b23cd52d80c4c824b36d8f7c4708
Problem Page URL: [/freereg1_csv_files/my_own](/freereg1_csv_files/my_own)
Previous Page URL: [http://freereg2.freereg.org.uk/csvfiles](http://freereg2.freereg.org.uk/csvfiles)
Reported Issue:
When I try to replace an existing file it fails the first time round telling me that a file of that name already exists. If I try again immediately afterwards  the file will be replaced.    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Mick

I am unable to duplicate please can you email me if this happens again. If
it does do not repeat but let me know time and files so I can look it up in
the logs

K

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1
