### ISSUE TITLE
Upload replace file broken (HelenB)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#639]
Issue reported by **HelenB** at 2015-11-23 00:15:18 UTC
Time: 2015-11-23T00:08:30+00:00
Session ID: 6d73ca5e8155ae04a10b34c60caf5c86
Problem Page URL: [/csvfiles/564fb858f493fd0b30000001/edit](/csvfiles/564fb858f493fd0b30000001/edit)
Previous Page URL: [http://www.freereg.org.uk/csvfiles/564fb858f493fd0b30000001/edit](http://www.freereg.org.uk/csvfiles/564fb858f493fd0b30000001/edit)
Reported Issue:
Hi, I understood that the overnight load was broken, but Eric's note said it was ok to upload small files.  I selected my batch, pressed Replace, chose the file ... then got an error message saying I cannot upload a file with the same name as a file that already exists.  It is Definitely the Replace screen, not the new uploads, so the whole point is that the file should have the same name.  I have taken a screenshot.    

![Screenshot](http://www.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1448237718-14461-0011/error.gif)

**Comment by PatReynolds** [comment]
This may be #645.  I'll ask her to have another go after that is is resolved.
