### ISSUE TITLE
No Source on this display (MikeNL)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#641]
Issue reported by **MikeNL** at 2015-11-23 22:30:17 UTC
Time: 2015-11-23T22:27:04+00:00
Session ID: 6e7a02d92d54cb96a75a4e4efef7af2b
Problem Page URL: [/freereg1_csv_files/55836857f493fdf0f2014e4e](/freereg1_csv_files/55836857f493fdf0f2014e4e)
Previous Page URL: [http://freereg2.freereg.org.uk/registers/5409e5bdeca9eba2065da9ba](http://freereg2.freereg.org.uk/registers/5409e5bdeca9eba2065da9ba)
Reported Issue:
After studiously entering a Source text into the file header using WinREG, there is no record of it in this display. Is this intentional and where can I find it?    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Not sure why you would do that.  Those are obsolete fields. The best way to
deal with source and other information about a register is to enter it
directly into the appropriate fields in the Register that were designed for
such purpose.

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by AlOneill** [comment]
I realise Mike is talking about WinREG, but  maybe because the File headers page currently says:

Line 4: We suggest that the third data field is used to detail the source of the data
and the fourth for any copyright restrictions.

What _should_ be entered in theses 2 fields please.

**Comment by AlOneill** [comment]
Point taken. I can work it out...
