### ISSUE TITLE
Dates before 1000 (hawkinssm)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#642]
Issue reported by **hawkinssm** at 2015-11-24 10:03:09 UTC
Time: 2015-11-24T09:59:05+00:00
Session ID: 703b0ab14b766a24a374c8600ec91ffe
Problem Page URL: [/freereg1_csv_entries](/freereg1_csv_entries)
Previous Page URL: [http://freereg2.freereg.org.uk/freereg1_csv_entries/5568f7f8f493fd1eec00698e/error](http://freereg2.freereg.org.uk/freereg1_csv_entries/5568f7f8f493fd1eec00698e/error)
Reported Issue:
Bp of Rochester, dyed October 10 633 & was bur in his own Cathedral [insecretario B. Apostoli Annixe quod Rex Ethelbertry construxit]. He was afterwards canonized & inshrined. "Godwin ed_, *. Bede. Wharton Ang_

But 633 as a burial year causes a red band of horror    

![Screenshot](http://www.freereg.org.uk)

**Comment by EmJayFry** [comment]
On 24 Nov 2015 12:03 PM, FreeUKGenIssues wrote:

> Bp of Rochester, dyed October 10 633 & was bur in his own Cathedral
> [insecretario B. Apostoli Annixe quod Rex Ethelbertry construxit]. He was
> afterwards canonized & inshrined. "Godwin ed/, *. Bede. Wharton Ang/
> 
> But 633 as a burial year causes a red band of horror

This is what happens when you diverge from the original mandate - Registers. 
These only ever existed from 1538.

## 

Regards,
Mike Fry (Jhb)

**Comment by PatReynolds** [comment]
This is #556
