### ISSUE TITLE
Password/PASSWORD change (hawkinssm)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#643]
Issue reported by **hawkinssm** at 2015-11-24 13:18:10 UTC
Time: 2015-11-24T13:15:56+00:00
Session ID: 938e6a3372e6571ac583204b50ee0bc3
Problem Page URL: [/freereg1_csv_files](/freereg1_csv_files)
Previous Page URL: [http://freereg2.freereg.org.uk/freereg1_csv_entries?page=](http://freereg2.freereg.org.uk/freereg1_csv_entries?page=)
Reported Issue:
Some Kent batches are rejected because the password is set as PASSWORD. is there an easy fix?    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
There is no way this can be happening. We do not process that field.
