### ISSUE TITLE
replace fuction (deo123)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#644]
Issue reported by **deo123** at 2015-11-24 14:38:28 UTC
Time: 2015-11-24T14:33:26+00:00
Session ID: b2cf81e03b3cb3be81351ced3ba384c6
Problem Page URL: [/csvfiles/5463b432e9379010fc0a7a5d/edit](/csvfiles/5463b432e9379010fc0a7a5d/edit)
Previous Page URL: [http://www.freereg.org.uk/csvfiles/5463b432e9379010fc0a7a5d/edit](http://www.freereg.org.uk/csvfiles/5463b432e9379010fc0a7a5d/edit)
Reported Issue:
Hi guy's,

this is embarresing, I don't mean to find these error well what I think of error's.

As you can see from the snippet, I was replacing a file and got this message about "uploading"

Regards Doreen    

![Screenshot](http://www.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1448375908-16925-7307/replace_function_CONBODBA_davejo.JPG)

**Comment by Captainkirkdawson** [comment]
All replace issues can be closed
