### ISSUE TITLE
Problems logging in (PatReynolds)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#645]
Issue reported by **PatReynolds** at 2015-11-24 16:08:05 UTC
Time: 2015-11-24T11:12:43+00:00
Session ID: 5225331a53d9621e3bf283072fb28e03
Problem Page URL: [/manage_resources/new](/manage_resources/new)
Previous Page URL: [http://www.freereg.org.uk/refinery/users/login](http://www.freereg.org.uk/refinery/users/login)
Reported Issue:
A number of people are reporting on lists that they are having difficulty logging in.

I myself (Pat) have no problem getting in, and some other users have no problem logging in.   Those who do log in are experiencing issues.    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Issue was a hangover from the recovery from last weeks crash. We used a
configuration script from one of the slaves and did not set the consistency
to strong as a result some people were being directed to a slave to login
which is not possible.
Only surprise is that it took nearly a week to manifest itself. Perhaps as
a result of heavy loading on the master with the FreeBMD rebuild that is
going on at the moment.

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1
