### ISSUE TITLE
Website Problem (Derek Gardner)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#646]
Issue reported by **Derek Gardner** at 2015-11-24 20:58:33 UTC
Time: 2015-11-24T20:55:12+00:00
Session ID: 
Problem Page URL: []()
Previous Page URL: [http://freereg2.freereg.org.uk/contacts/new](http://freereg2.freereg.org.uk/contacts/new)
Reported Issue:
I cannot log in, I am getting a message that I am not currently allowed to access the system.
The system must have a memory as bad as mine.    

![Screenshot](http://www.freereg.org.uk)

**Comment by Sherlock21** [comment]
Hi,Derek

there has been a problem, which most in the UK found lasted much of the day.

but it was cleared about 20:00 GMT.
so if you clear your browser and try again you  should be OK.

IF NOT, reply to this in the negative. - but it would get picked up til tomorrow afternoon GMT

regards,
ericB

**Comment by PatReynolds** [comment]
#645?  People are still reporting issues - shall I forward to you Kirk and/or ask for specifics first?

**Comment by Captainkirkdawson** [comment]
All login users can be closed.
