### ISSUE TITLE
Update file crashed the processor (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#648]
Issue reported by **REGManager** at 2015-11-25 16:07:42 UTC
Time: 2015-11-25T15:48:24+00:00
Session ID: 0657a4ab07fd8d13ca1de64ec970191c
Problem Page URL: [/manage_resources/new](/manage_resources/new)
Previous Page URL: [http://www.freereg.org.uk/userid_details/5462b402e937907d70000045](http://www.freereg.org.uk/userid_details/5462b402e937907d70000045)
Reported Issue:
In the update of 25th November we had the attached report.  I have never seen this before.  What needs to be corrected?  E    

![Screenshot](http://www.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1448467662-54349-9068/Capture.JPG)

**Comment by Captainkirkdawson** [comment]
Need to avoid checking on a nil entry. Fix applied but not deployed
