### ISSUE TITLE
Website Problem (Derek Gardner)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#649]
Issue reported by **Derek Gardner** at 2015-11-25 20:23:19 UTC
Time: 2015-11-25T20:08:02+00:00
Session ID: 
Problem Page URL: []()
Previous Page URL: [http://www.freereg.org.uk/contacts/new](http://www.freereg.org.uk/contacts/new)
Reported Issue:
2015-11-24 @ 1:58 pm I reported a problem when trying to login.
2015-11 24 @ 20:55 I received a reply from you.
2015-11-24 @ 1930  GMT, Kirk Dawson replied with solution.
I have uploaded a file today, but tonight the problem has returned and I cannot login.
Please sort this out.
Derek Gardner    

![Screenshot](http://www.freereg.org.uk)

**Comment by PatReynolds** [comment]
#645 Will let Derek know.

**Comment by Sherlock21** [comment]
Hold off until the mail log-in snag is cleared formally. Hopefully it may be by the time Kirk gets up today.
