### ISSUE TITLE
external links from Northamptonshire transcriptions page (AMSA)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#650]
Issue reported by **AMSA** at 2015-11-26 08:46:35 UTC
Time: 2015-11-26T08:43:42+00:00
Session ID: 87d7975271f16137d5554ebbac50b568
Problem Page URL: [/freereg_contents](/freereg_contents)
Previous Page URL: [http://www.freereg.org.uk/freereg_contents/new](http://www.freereg.org.uk/freereg_contents/new)
Reported Issue:
The links from the Northamptonshire page to Northamptonshire Records Office pages no longer work. These were for lists of PR & NC records available at the NRO.
Can these links please be removed. I am pretty sure I can no longer do this myself?
Thanks,
Anna     

![Screenshot](http://www.freereg.org.uk)

**Comment by edickens** [comment]
```
Hi Anna,

Done

Eric

On 26/11/2015 08:46, FreeUKGenIssues
  wrote:


  Issue reported by AMSA at 2015-11-26 08:46:35
    UTC
    Time: 2015-11-26T08:43:42+00:00
    Session ID: 87d7975271f16137d5554ebbac50b568
    Problem Page URL: /freereg_contents
    Previous Page URL: http://www.freereg.org.uk/freereg_contents/new
    Reported Issue:
    The links from the Northamptonshire page to Northamptonshire
    Records Office pages no longer work. These were for lists of PR
    & NC records available at the NRO.
    Can these links please be removed. I am pretty sure I can no
    longer do this myself?
    Thanks,
    Anna 

  —
    Reply to this email directly or view
      it on GitHub.
```
