### ISSUE TITLE
 (alycymru)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#651]
Issue reported by **alycymru** at 2015-11-28 01:14:10 UTC
Time: 2015-11-28T01:09:21+00:00
Session ID: 967eced08d2740da61f3eb17cc00fa49
Problem Page URL: [/freereg1_csv_files](/freereg1_csv_files)
Previous Page URL: [http://www.freereg.org.uk/manage_counties/select_action](http://www.freereg.org.uk/manage_counties/select_action)
Reported Issue:
Cannot sort files to review in any screen such as review file by most recent change. Have tried in IE11, Firefox, Chrome and Opera. I get an  message that says no files. Eric Dickens was able to bring the file list  up on his computer, so it must be something to do with mine. Hope you can help.    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Sorry I don't understand the problem. There is far too little in the
problem statement to assist or make any suggestion.

From what I see alycymu only has two files so why are you trying to sort 2
files?.

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1
