### ISSUE TITLE
FreeREG does not have ID for transcriber (Geoff Masters)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#652]
Issue reported by **Geoff Masters** at 2015-11-28 05:18:59 UTC
Time: 2015-11-28T05:13:30+00:00
Session ID: 
Problem Page URL: []()
Previous Page URL: [http://www.freereg.org.uk/contacts/new](http://www.freereg.org.uk/contacts/new)
Reported Issue:
Just a note to advise that my login will not work on the new website.
I tried to get in to download a new version of the Transcription program but as  I am unable to login that is on hold. 
I tried the Lost my Password but  I failed to receive the email.
Is it possible my member login was not carried over to the new website ?

Regards
Geoff Masters    

![Screenshot](http://www.freereg.org.uk)

**Comment by PatReynolds** [comment]
I have checked on FreeREG and there is no-one there called Geoff Masters, so it seems he is correct, his profile isn't here.  I've assigned to Eric to take forwards.

**Comment by edickens** [comment]
```
Yes, he is there.  He has spelt his name all capitals so it comes at
the start of "M".

I have sent him a password reset.  He is with bigpond and I think
that is the problem.  The password reset email is getting lost when
sent from "Forgotten password" but not from the "Send Password
reset" against the Profile.  E

On 28/11/2015 12:39, PatReynolds wrote:


  I have checked on FreeREG and there is no-one there called
    Geoff Masters, so it seems he is correct, his profile isn't
    here. I've assigned to Eric to take forwards.
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by PatReynolds** [comment]
Thanks, longer term we need to decide whether it is possible and reasonable to make the listing not case-sensitive, or should intervene to normalise, or should simply tell new users to use mixed case.
