### ISSUE TITLE
File not precessed (drh123)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#653]
Issue reported by **drh123** at 2015-11-28 09:37:27 UTC
Time: 2015-11-28T09:34:59+00:00
Session ID: e1223f014364681400f0c34586c6b6dc
Problem Page URL: [/freereg1_csv_files/selection?option=List%20files%20waiting%20to%20be%20processed](/freereg1_csv_files/selection?option=List%20files%20waiting%20to%20be%20processed)
Previous Page URL: [http://freereg2.freereg.org.uk/freereg1_csv_files/my_own](http://freereg2.freereg.org.uk/freereg1_csv_files/my_own)
Reported Issue:
I replaced the file SOMWERBA9 two nights ago but it has still not been processed. Other files uploaded since have been.    

![Screenshot](http://www.freereg.org.uk)

**Comment by PatReynolds** [comment]
I have emailed the transcriber and asked him to re-try.

**Comment by Captainkirkdawson** [comment]
The system has no file waiting to be processed from 2 nights ago. I note the file has since been loaded and processed today

**Comment by Captainkirkdawson** [comment]
See also #637 for long term solution
