### ISSUE TITLE
System sending "no errors" email notification when there are errors (AMSA)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#654]
Issue reported by **AMSA** at 2015-11-28 09:59:15 UTC
Time: 2015-11-28T09:41:32+00:00
Session ID: e5a9d5fe798ad0a534212ab5bfb6e3d6
Problem Page URL: [/freereg1_csv_files](/freereg1_csv_files)
Previous Page URL: [http://www.freereg.org.uk/manage_syndicates/select_action](http://www.freereg.org.uk/manage_syndicates/select_action)
Reported Issue:
Already briefly mentioned to Eric but would now like proper investigation. 
I have asked transcriber to leave these files as is for now.
3 files uploaded via FR.  NTHBUWBA1, NTHBUWBU1, NTHBUWMA1.
Email notification for the 1st 2 received back:
Windsurfing_Widow/NTHBUWBA1.csv was processed by FreeREG at 2015-11-16 08:17:39 +0000
Ilona,
The file submitted for processing has been completed. We processed 981 records and there were 0 data errors and 0 header errors. If there were any errors you will need to review the on-line information for this file to see the details.
The FreeREG Team
and
Windsurfing_Widow/NTHBUWBU1.csv was processed by FreeREG at 2015-11-16 09:52:53 +0000
Ilona,
The file submitted for processing has been completed. We processed 747 records and there were 0 data errors and 0 header errors. If there were any errors you will need to review the on-line information for this file to see the details.
The FreeREG Team
NTHBUWMA1 never received notification and is not showing in FR.
These files are conversions of an excel based transcript. NTHBUWBA1 clearly has a number of fields conversion error and EVERY line in the transcript is wrong.
NTHBUWBU1 contains 2 date typos.
These errors were not picked up at the time of uploading, and were not notified in the misleading confirmation email sent to both transcriber and coordinator.
I have noticed this before with a header error not being notified in email and will attempt to replicate this & report it next time.
When you have examined please let us know so we may apply fix.
We have no idea what happened to NTHBUWMA1!
Many thanks,
Anna. Northamptonshire Coord.    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Error message is indeed incorrect due to code dealing with multiple batches

**Comment by PatReynolds** [comment]
Another couple of folk reporting the same problem.  I have closed these.  Do we need to inform people that this is a known problem, or is resolution imminent?

**Comment by Captainkirkdawson** [comment]
Should be put into known issue.

Solution is not imminent.

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Captainkirkdawson** [comment]
Fix applied but not deployed

**Comment by Captainkirkdawson** [comment]
Fix has been deployed
