### ISSUE TITLE
When I click on the FreeReg Icon to open file it will not work (Gepetto)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#656]
Issue reported by **Gepetto** at 2015-11-29 04:45:54 UTC
Time: 2015-11-29T02:41:24+00:00
Session ID: c71c4cbb182994ef1d239a0fbfe447ea
Problem Page URL: [/manage_resources/new](/manage_resources/new)
Previous Page URL: [http://www.freereg.org.uk/refinery/users/login](http://www.freereg.org.uk/refinery/users/login)
Reported Issue:
Hi,
When I click on the FreeReg Icon to open file it will not work  and shows a sign to say it has a problem sending that command. ( File attached )

If I open Excel and then attempt to open the file from there I get another message which says  it can't find the file. (attached)
There is no indication that the attachments have  been attached.

Regards
Geoff Masters    

![Screenshot](http://www.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1448772354-64634-5313/FreeReg_warning.jpg)

**Comment by PatReynolds** [comment]
Querying Geoff: suspect WinREG rather than FreeREG issue or maybe FreeREG1.

**Comment by PatReynolds** [comment]
Turns out to be a Windows 10 issue, and nothing to do with us at all.
