### ISSUE TITLE
transcriber locked out. Coordinator cannot send password reset (AMSA)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#657]
Issue reported by **AMSA** at 2015-11-29 08:22:32 UTC
Time: 2015-11-29T08:12:23+00:00
Session ID: 3bcc7ec3ea96f80b41435624c58f5a50
Problem Page URL: [/userid_details/5462b404e937907d700000b3](/userid_details/5462b404e937907d700000b3)
Previous Page URL: [http://www.freereg.org.uk/userid_details/5462b404e937907d700000b3](http://www.freereg.org.uk/userid_details/5462b404e937907d700000b3)
Reported Issue:
NTH transcriber "Carol" cannot log-in to FR. The system says her username or password is incorrect.
She can log into FR1 and the FR image server with these details.
She has tried to request a password reset but that did not work.
She has recently upgraded to windows10
I have investigated all I can.Her profile is active with batches uploaded as recently as 27Oct.. I have tried logging in with her username/password on my windows8 system but same problem.
I requested a password reset as recommended but got the following message: 
There was a problem with the reset: There is no refinery entry 
((attempted) screenshot provided
Please investigate urgently. I have reactivated Carol's FR1 account for now so that she can continue to transcribe & upload files but this is only a temporary solution.
Thanks, Anna
NTH Coord.    

![Screenshot](http://www.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1448785352-64634-8770/Password_reset.jpg)

**Comment by edickens** [comment]
```
Hi Anna,
I have had problems with this UserID for ages.  The difficulty is
that in FR1 there were two UserIDs "Carol" and "carol".  This upset
the system and certain functions in FR1 would get a "Program
error".  These two UserIDs still exist in the Image server, but not
in FR as that checks without capitalisation.
What I would prefer is that Carol create a new UserID by following
the Volunteer link and uses the UserID "CarolBeattie", or "CarolB"
if she prefers.  Once set up I will move her files to her new
UserID.
Thanks Eric

On 29/11/2015 08:22, FreeUKGenIssues
  wrote:


  Issue reported by AMSA at 2015-11-29 08:22:32
    UTC
    Time: 2015-11-29T08:12:23+00:00
    Session ID: 3bcc7ec3ea96f80b41435624c58f5a50
    Problem Page URL: /userid_details/5462b404e937907d700000b3
    Previous Page URL: http://www.freereg.org.uk/userid_details/5462b404e937907d700000b3
    Reported Issue:
    NTH transcriber "Carol" cannot log-in to FR. The system says her
    username or password is incorrect.
    She can log into FR1 and the FR image server with these details.
    She has tried to request a password reset but that did not work.
    She has recently upgraded to windows10
    I have investigated all I can.Her profile is active with batches
    uploaded as recently as 27Oct.. I have tried logging in with her
    username/password on my windows8 system but same problem.
    I requested a password reset as recommended but got the
    following message: 
    There was a problem with the reset: There is no refinery entry 
    ((attempted) screenshot provided
    Please investigate urgently. I have reactivated Carol's FR1
    account for now so that she can continue to transcribe &
    upload files but this is only a temporary solution.
    Thanks, Anna
    NTH Coord. 

  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by edickens** [comment]
Fixed.  Have moved her to a new UserID CarolB.  But am waiting for the link to the image server to be fixed as she needs to access her images.  She can use her old UserID but this is not ideal.  E
