### ISSUE TITLE
another example of "no error" email received where there is in fact an error in batch (AMSA)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#658]
Issue reported by **AMSA** at 2015-11-29 08:44:59 UTC
Time: 2015-11-29T08:37:51+00:00
Session ID: 3bcc7ec3ea96f80b41435624c58f5a50
Problem Page URL: [/freereg1_csv_files/564a79cdf493fdf9f5001081/error](/freereg1_csv_files/564a79cdf493fdf9f5001081/error)
Previous Page URL: [http://www.freereg.org.uk/freereg1_csv_files](http://www.freereg.org.uk/freereg1_csv_files)
Reported Issue:
This is the email received by the transcriber and by myself:
Windsurfing_Widow/NTHNOKMA4.csv was processed by FreeREG at 2015-11-29 01:56:28 +0000
Ilona,
The file submitted for processing has been completed. We processed 310 records and there were 0 data errors and 0 header errors. If there were any errors you will need to review the on-line information for this file to see the details.
The FreeREG Team

There IS a data error in this batch. These e-mails are misinformation. If the transcriber is told their file is error free how can they possibly know there are problems that need addressing??
Maybe rather than the system sending an (incorrect) email the transcriber should be directed to the site to CHECK THEIR OWN FILE for errors.
Regards, Anna.     

![Screenshot](http://www.freereg.org.uk)

**Comment by PatReynolds** [comment]
#654
