### ISSUE TITLE
No errors but errors in file (Seamus)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#659]
Issue reported by **Seamus** at 2015-11-29 10:55:10 UTC
Time: 2015-11-29T10:49:04+00:00
Session ID: a928323be8b379caa3de8fa9e985bf53
Problem Page URL: [/freereg1_csv_files/565ad76be93790549e000001](/freereg1_csv_files/565ad76be93790549e000001)
Previous Page URL: [http://test3.freereg.org.uk/freereg1_csv_entries?page=](http://test3.freereg.org.uk/freereg1_csv_entries?page=)
Reported Issue:
Email reported no errors, baptism date 05-Sep-00 accepted,  error in birthdate shown as after baptism, when no birthdate included.    

![Screenshot](http://test3.freereg.org.uk)

**Comment by PatReynolds** [comment]
#654
