### ISSUE TITLE
this is a problem report for demo purposes only (benwbrum)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#66]
Issue reported by **benwbrum** at 2014-11-06 15:12:59 UTC
Time: 2014-11-06T15:11:51+00:00
Session ID: 046ea235bd4eeaae57f3f9743440d7d8
Problem Page URL: [/search_queries/new](/search_queries/new)
Previous Page URL: [http://test2.freereg.org.uk/](http://test2.freereg.org.uk/)
Reported Issue:
there are many problems    

![Screenshot](http://test2.freereg.org.uk/uploads/feedback/screenshot/545b8ffbe93790435d000001/4034127_00102.jpg)

**Comment by Sherlock21** [comment]
Ben - this example of a jpeg image being attached to a problem report is good. very clear and can be copied off to dest top to further expand etc.
EricB
