### ISSUE TITLE
HELP pahe (ericb)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#660]
Issue reported by **ericb** at 2015-12-01 11:04:49 UTC
Time: 2015-12-01T11:03:51+00:00
Session ID: d74a9f5dbd909b07c8bd9168a216ad44
Problem Page URL: [/registered-researchers](/registered-researchers)
Previous Page URL: [http://www.freereg.org.uk/search_queries/new](http://www.freereg.org.uk/search_queries/new)
Reported Issue:

![Screenshot](http://www.freereg.org.uk)

**Comment by PatReynolds** [comment]
#661

**Comment by Sherlock21** [comment]
Yes, this is scrap - it went off by accident before I got to correct the title.
