### ISSUE TITLE
Help Page from Logged in as a Member goes nowhere (ericb)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#661]
Issue reported by **ericb** at 2015-12-01 11:07:19 UTC
Time: 2015-12-01T11:04:50+00:00
Session ID: d74a9f5dbd909b07c8bd9168a216ad44
Problem Page URL: [/registered-researchers](/registered-researchers)
Previous Page URL: [http://www.freereg.org.uk/feedbacks/new?utf8=%E2%9C%93&feedback_time=2015-12-01+11%3A03%3A51+UTC&session_id=d74a9f5dbd909b07c8bd9168a216ad44&user_id=ericb&problem_page_url=%2Fregistered-researchers&previous_page_url=http%3A%2F%2Fwww.freereg.org.uk%2Fsearch_queries%2Fnew&feedback_type=issue](http://www.freereg.org.uk/feedbacks/new?utf8=%E2%9C%93&feedback_time=2015-12-01+11%3A03%3A51+UTC&session_id=d74a9f5dbd909b07c8bd9168a216ad44&user_id=ericb&problem_page_url=%2Fregistered-researchers&previous_page_url=http%3A%2F%2Fwww.freereg.org.uk%2Fsearch_queries%2Fnew&feedback_type=issue)
Reported Issue:
 I tried to find  the current "FR Instructions to Transcribers". count not find in Public HELP pages,
so expected it to be in Members Help pages - but  that link goes no where.

IF its in neither, then where is it please?

![Screenshot](http://www.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1448968039-60638-1091/Help_page_from_Logged_in.jpg)

**Comment by PatReynolds** [comment]
I have a vague feeling that you need to be registered as a transcriber before it will show you transcribers' help in the members area.  Alison will know for sure.

**Comment by Sherlock21** [comment]
But surely I am a Transcriber as well as DM etc. Having been in NFK syndicate for years, then perhaps now in WRY?

**Comment by Captainkirkdawson** [comment]
Sorry about that EricD someone who is just DM went through the cracks. You
will get coordinators help which include a link to the transcriber help

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Sherlock21** [comment]
Fine.

Thank you.

Eb

**Comment by AlOneill** [comment]
When logged in, I now get Help link to Info for Coords (thanks).

If all such instances have now been fixed, this can be closed.
