### ISSUE TITLE
Process listing/Queue (deo123)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#662]
Issue reported by **deo123** at 2015-12-02 15:19:23 UTC
Time: 2015-12-02T15:14:29+00:00
Session ID: 69246344f839cb836bed57f8cff691cc
Problem Page URL: [/manage_syndicates/display_files_waiting_to_be_processed](/manage_syndicates/display_files_waiting_to_be_processed)
Previous Page URL: [http://www.freereg.org.uk/manage_syndicates/select_action.%3Fsyndicate=England,%20Rest%20of%20-%20Doreen%20Olds](http://www.freereg.org.uk/manage_syndicates/select_action.%3Fsyndicate=England,%20Rest%20of%20-%20Doreen%20Olds)
Reported Issue:
Hi Guy's,

Well!  I ahve given your a few day's grace.

The above Process listing and the processing of files, seems to leave the bottom file.

I have a file CONLRHBA has been waiting on the queue since 30 Nov 2015

Regards Doreen    

![Screenshot](http://www.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1449069563-24344-4656/process_listing.JPG)

**Comment by Captainkirkdawson** [comment]
Its been added for tonight.

The processing for picking up waiting files is due to rewrite in #637

Currently those files that are added while the update process is running
will be overlooked.

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1
