### ISSUE TITLE
Coordinators not communicating with transcribers (derekg)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#663]
Issue reported by **derekg** at 2015-12-03 10:53:58 UTC
Time: 2015-12-03T10:46:42+00:00
Session ID: 69c1ae25927c0f5ee3687aaaf3e3ad2a
Problem Page URL: [/manage_resources/new](/manage_resources/new)
Previous Page URL: [http://www.freereg.org.uk/refinery/login](http://www.freereg.org.uk/refinery/login)
Reported Issue:
I have just checked my emails and found that last night you processed 839 items of my file STSSEDBU55. 
I did not submit this file for processing because I have not created this file.
Something is amiss, files are being created that do not exist.
I am currently working on STSSEDBU3 & STSROWBU1 only.
Regards.
Derek Gardner

![Screenshot](http://www.freereg.org.uk)

**Comment by PatReynolds** [comment]
Could you have a look t this, Eric B.?

**Comment by Sherlock21** [comment]
Nothing to do with anything that I was doing yesterday

eric B

**Comment by Sherlock21** [comment]
All that i can see for STS is that file STSSEDBU3  was last processed on 02 Dec 2015 
and STSSEDBU4 was last processed on 03 Dec 2015. both with userID derekg.

Nothing about STSSEDBU55 in the list that i have access to.
Maybe there is an issue here then??

?action Kirk??

**Comment by edickens** [comment]
```
The files could have been uploaded by the SC directly into the
transcribers UserID.

E

On 03/12/2015 12:07, Sherlock21 wrote:


  All that i can see for STS is that file STSSEDBU3 was last
    processed on 02 Dec 2015 
    and STSSEDBU4 was last processed on 03 Dec 2015. both with
    userID derekg.
  Nothing about STSSEDBU55 in the list that i have access to.
    Maybe there is an issue here then??
  ?action Kirk??
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by Sherlock21** [comment]
Ar your saying then that batches exist in listing other than are shown under:ALL Batches by filename for a County? [ or one of the other ordering - userID / date last uploaded .]?

**Comment by edickens** [comment]
No.  Just that a file can be uploaded by a SC and they can select any 
UserID in their syndicate to put it.  This will create a report to the 
Person named in the UserID into which the file was loaded. They might 
not be expecting this if the SC has not told them that they have been 
moving files around.  E

**Comment by edickens** [comment]
I suspect that a SC has uploaded a file into the UserID of an Active 
Transcriber without telling them what they are doing.  Should upload by 
a SC only be allowed into an Inactive UserID?  Or at least put a warning 
to ask if the UserID had been advised that they will get an email saying 
that a file has been posted to their Account?  E

**Comment by Sherlock21** [comment]
Interesting if you look at the Attic for this file.
Penultimate entry for STSSEDBU55 is dated 2015-12-03T00:20:25
and Ultimate entry is 2015-12-03T00:27:58.

So either someone is up late fiddling
or is it the nightly batch processor?

NOW if we had used timestamp + UserID of who did it, (as I requested on day one) we would know who and why. and not spend a dozen man hours trying to  guess. and write numerous emails.

**Comment by edickens** [comment]
```
They were not processed in the overnight batch.  These are the only
ones for this UserID.
derekg  STSSEDBU3.CSV   processed  334 data lines for location STS, Sedgley, All Saints, PR, bu;  269 unchanged and 0 removed.  0 header errors and 0 data errors
```

derekg  STSSEDBU4.csv   processed  3281 data lines for location STS, Sedgley, All Saints,  , bu;  0 unchanged and 0 removed.  0 header errors and 0 data errors

```
Interesting that the first is PR and the second Unspecified.

On 03/12/2015 15:40, Sherlock21 wrote:

  Interesting if you look at the Attic for this file.
    Penultimate entry for STSSEDBU55 is dated 2015-12-03T00:20:25
    and Ultimate entry is 2015-12-03T00:27:58.
  So either someone is up late fiddling
    or is it the nightly batch processor?
  NOW if we had used timestamp + UserID of who did it, (as I
    requested on day one) we would know who and why. and not spend a
    dozen man hours trying to guess. and write numerous emails. 
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by Captainkirkdawson** [comment]
I am unsure why we are investigating this matter. It really is an issue for
the coordinator to deal with.

MikeNL seems to be doing things with this person's files.

derekg is one of our transcribers with a history of very large files. STSSEDBU
is a file of 16,000 entries.

I think the transcriber is correct he knows nothing of this file. It was
processed as an ASAP just after midnight. That is Mikes working time

#<Mail::Message:17385982900, Multipart: false, Headers: <Date: Thu, 03 Dec
2015 00:22:39 +0000>, <From: freereg-processing@freereg.org.uk>, <To:
gardner263@talktalk.net>, <Cc: freereg2.sts.coordinator@gmail.com>,
<Message-ID: <565f8b4f2d562_ea9f4012c5bf08006d@colobus.freebmd.org.uk.mail>>,
<Subject: derekg/STSSEDBU55.csv was processed by FreeREG at 20

It was then almost immediately deleted.

derekg.STSSEDBU55.CSV.1,STS, Sedgley,All Saints,  , bu
839 records deleted for 565f8adcf493fdfdaf000001,derekg,STSSEDBU55.csv

Also deleted were

derekg.STSSEDBU7.CSV.1,STS, Sedgley,All Saints,  , bu
656 records deleted for 561b92fef493fdab7b000001,derekg,STSSEDBU7.csv
derekg.STSSEDBU72.CSV.1,STS, Sedgley,All Saints,  , bu
3281 records deleted for 562c4958f493fd23fb00d027,derekg,STSSEDBU72.csv
derekg.STSSEDBU71.CSV.797,STS, Sedgley,All Saints,  , bu
797 records deleted for 562b9199f493fdf507000001,derekg,STSSEDBU71.csv
derekg.STSSEDBU77.CSV.615,STS, Sedgley,All Saints,  , bu
3225 records deleted for 562c5067f493fd23fb016dac,derekg,STSSEDBU77.csv
derekg.STSSEDBU53.CSV.10,STS, Sedgley,All Saints,  , bu
800 records deleted for 561b9294f493fd738b000001,derekg,STSSEDBU53.csv
derekg.STSSEDBU52.CSV.1466,STS, Sedgley,All Saints,  , bu
1600 records deleted for 561c64fcf493fd95a6018f57,derekg,STSSEDBU52.csv
derekg.STSSEDBU51.CSV.1,STS, Sedgley,All Saints,  , bu
3209 records deleted for 561c648ff493fd95a601625a,derekg,STSSEDBU51.csv
derekg.STSSEDBU50.CSV.1,STS, Sedgley,All Saints,  , bu
3202 records deleted for 561c6432f493fd95a601354f,derekg,STSSEDBU50.csv
derekg.STSSEDBU55.CSV.1,STS, Sedgley,All Saints,  , bu

Last night we deleted 105,000 entries/search records

This sort of thing was why I suggested at yesterdays scrum that we issue an
advise to transcribers/coordinators; I sent out a draft for review after
the meeting but no response

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1
