### ISSUE TITLE
Birth date earlier than baptism date? (MTokely)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#665]
Issue reported by **MTokely** at 2015-12-03 22:31:08 UTC
Time: 2015-12-03T22:01:54+00:00
Session ID: d4b43bfdf38d944959969b0835640b54
Problem Page URL: [/freereg1_csv_files/565f9a62f493fdc40c005565/error](/freereg1_csv_files/565f9a62f493fdc40c005565/error)
Previous Page URL: [http://freereg2.freereg.org.uk/freereg1_csv_files/my_own](http://freereg2.freereg.org.uk/freereg1_csv_files/my_own)
Reported Issue:
Birth date 1 Oct 1787 and baptism date entered as Nov 1787 (no day).  This  should not show as an error.  Have re-entered with "*" in day to see what happens.    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
A \* or _ in the day field will avoid the error message.

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1
