### ISSUE TITLE
Incorrect date comparison (MikeNL)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#666]
Issue reported by **MikeNL** at 2015-12-04 09:25:18 UTC
Time: 2015-12-04T09:08:19+00:00
Session ID: c2357a3cce88c339ca91f2c4ee9a37fe
Problem Page URL: [/freereg1_csv_files/5660f6d3f493fd3e8d00753f/error](/freereg1_csv_files/5660f6d3f493fd3e8d00753f/error)
Previous Page URL: [http://freereg2.freereg.org.uk/freereg1_csv_files/5660f6d3f493fd3e8d00753f](http://freereg2.freereg.org.uk/freereg1_csv_files/5660f6d3f493fd3e8d00753f)
Reported Issue:
In the attached screen capture I have highlighted the record details that demonstrate the problem. WIth a fixed day birth date in February and no day baptism date in March, both in the same year, the system gives an error that the birth date is after the baptism date. This is clearly not the case.

The entry that is being processed is: -- STS,Bilston,High Street Primitive Methodist Chapel  ,"",3 Feb 1874,Mar 1874,John William,M,Joseph,Fanny,CROSS,"",High Street,Butcher,"" --

![Screenshot](http://www.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1449221118-1825-7851/Capture.JPG)

**Comment by Captainkirkdawson** [comment]
Will not occur if the missing day is entered as \* _ - __ ?

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by edickens** [comment]
The problem is that there are already many entries like this on the 
database.  However this is not a problem until the Entry is edited. So 
all that is needed is something in the Help.  E
