### ISSUE TITLE
New Navigation and Profile - Snag (alsibk)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#67]
Issue reported by **alsibk** at 2014-11-07 09:31:47 UTC
Time: 2014-11-07T09:29:09+00:00
Session ID: ccea438914f5fc16d9656fa69ae865ff
Problem Page URL: [/manage_counties/select_action?county=WRY](/manage_counties/select_action?county=WRY)
Previous Page URL: [http://test2.freereg.org.uk/manage_counties?option=mine](http://test2.freereg.org.uk/manage_counties?option=mine)
Reported Issue:
There is no option for CC role to find batches by UserID

In fact there is no capability to do anything by UserID as the main Selection label.

EricB    

![Screenshot](http://test2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
New feature request

**Comment by Captainkirkdawson** [comment]
This was addressed in the new navigation as part of FR2.1.0
