### ISSUE TITLE
main logon - logoff: change style request please (sc1)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#68]
Issue reported by **sc1** at 2014-11-07 09:41:51 UTC
Time: 2014-11-07T09:41:03+00:00
Session ID: fb90a8231d9aa145ea627b88b7a8edaa
Problem Page URL: [/manage_counties/select_action?county=OXF](/manage_counties/select_action?county=OXF)
Previous Page URL: [http://test2.freereg.org.uk/manage_counties?option=mine](http://test2.freereg.org.uk/manage_counties?option=mine)
Reported Issue:
Rather than the single navigation button of MEMBERS, I would prefer to see :Login (or Members Login) and a distinct Logout button here at the top.
The idea of tucking Logout at the bottom of a sub drop down list seems wrong. It should be on the top of every page - else users will just quit by ditching that browser session - which gets the application off the screen, but h=leaves the session still part connected to the server.

![Screenshot](http://test2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Done

**Comment by Sherlock21** [comment]
Thank you, Kirk.
