### ISSUE TITLE
Ben's test msg (ericb)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#69]
Issue reported by **ericb** at 2014-11-07 18:59:20 UTC
Time: 2014-11-07T18:57:27+00:00
Session ID: 0c5ed8819624edf7eb9d3fa9f07856f0
Problem Page URL: [/freereg1_csv_files](/freereg1_csv_files)
Previous Page URL: [http://test2.freereg.org.uk/manage_counties/select_action?county=WRY](http://test2.freereg.org.uk/manage_counties/select_action?county=WRY)
Reported Issue:
This is only a test as requested by Ben
I include a png image file    

![Screenshot](http://test2.freereg.org.uk/tmp/carrierwave/1415386760-85075-5171/Screen_shot_2014-11-07_at_13.56.04.png)

**Comment by Captainkirkdawson** [comment]
Used and system working
