### ISSUE TITLE
test msg 2 to Ben Crashed out twice. (ericb)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#70]
Issue reported by **ericb** at 2014-11-07 19:11:17 UTC
Time: 2014-11-07T19:07:58+00:00
Session ID: ac42ce136d0c4e753f7ae98bba246089
Problem Page URL: [/manage_resources](/manage_resources)
Previous Page URL: [http://test2.freereg.org.uk/refinery/login?](http://test2.freereg.org.uk/refinery/login?)
Reported Issue:
this attached error report is what I got as the error msg when trying to sent you a report with no file attached.

but it then crashes again when I did it with that file attached.
This timeI logged out totally, and sent this as the very first thing I did.
Its a csv file.    

![Screenshot](http://test2.freereg.org.uk/tmp/carrierwave/1415387477-87324-2815/reportcrashed2.csv)

**Comment by Captainkirkdawson** [comment]
Resolved
