### ISSUE TITLE
Improve incorrect place name reporting  (RichardHoward)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#703]
Issue reported by **RichardHoward** at 2015-12-05 17:05:18 UTC
Time: 2015-12-05T17:02:52+00:00
Session ID: 88b21a66bfdafd0e503e6bb1fc664f61
Problem Page URL: [/freereg1_csv_files/my_own](/freereg1_csv_files/my_own)
Previous Page URL: [http://freereg2.freereg.org.uk/csvfiles](http://freereg2.freereg.org.uk/csvfiles)
Reported Issue:
I can't see what is wrong with the headers - but I am getting this error message :
"The file submitted for processing has been completed. We processed 0 records and there were 44 data errors and 44 header errors. If there were any errors you will need to review the on-line information for this file to see the details."

There is no associated batch online.

The headers are :
+INFO,richardg.howard@btinternet.com,password,SEQUENCED,MARRIAGES,
# ,CCC,Richard Howard,Suffolk,SFKCSPMA.CSV,5 Dec 2015
# ,Credit,Richard Howard,original transcriber
# ,5 Dec 2015,from fiche images

Julie (Suffolk coordinator)    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
I agree the message is a little miss-leading.

If you see data errors = header errors it means that all records were
rejected. It means that the place had an unapproved name.

If there were only 44 records then likely it has ended up as an invisible
null file.

We need to do a better job of detection and handling of this situation

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1
