### ISSUE TITLE
Emails incorrectly saying files have no errors when they do (AMSA)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#704]
Issue reported by **AMSA** at 2015-12-06 08:38:42 UTC
Time: 2015-12-06T08:35:36+00:00
Session ID: 8d3b3c067a3fa5021b24c5a34f534e48
Problem Page URL: [/freereg1_csv_files](/freereg1_csv_files)
Previous Page URL: [http://freereg2.freereg.org.uk/manage_syndicates/select_action.%3Fsyndicate=Northamptonshire%20-%20Anna%20%20Rufer](http://freereg2.freereg.org.uk/manage_syndicates/select_action.%3Fsyndicate=Northamptonshire%20-%20Anna%20%20Rufer)
Reported Issue:
Issue already twice reported in detail with copy of emails received..
I have left these 2 files for you to look at as part of investigation but would appreciate notification that this has been done so that we may correct them & get them loaded & searchable.
Many thanks,
Anna
Northants Coord    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Issue was fixed on  30 Nov as reported on information to members

_Production Server Status: Running FR2.1.4 (Updated 30 Nov 2015)_
Known Issues:
1. *Error reporting: *While a solution has been applied to the reporting
   of errors you may observe oddities if you have multiple batches in a single
   file. You are encouraged to avoid creating multiple batches in a file.
2. _Navigation_: Coordinators are encouraged to use the links under the
   main Navigation banner. These are what is called “breadcrumbs” — they allow
   you to go back anywhere in the chain of actions you took to get where you
   are at that instant. They avoid having to reload long pages especially if
   you are working on one Place, Church or Register.
   Also please take special care to refresh a page after using the browser
   back button and _before_ clicking on a link.
3. _Some records may show date errors_: If they do then do an online
   edit on the record with the error and simply resubmit the record and it
   will most likely be passed and added to the database.

Recent Changes:
- (30 Nov 2015): Revised processing algorithm to avoid recreating
  unchanged entries and fix to error reporting

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1
