### ISSUE TITLE
Incorrect date comparison (MikeNL)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#705]
Issue reported by **MikeNL** at 2015-12-07 00:35:40 UTC
Time: 2015-12-07T00:25:54+00:00
Session ID: 36e34d356f33236204ade57a1c0280e8
Problem Page URL: [/freereg1_csv_files/56646301f493fd1190000001/error](/freereg1_csv_files/56646301f493fd1190000001/error)
Previous Page URL: [http://freereg2.freereg.org.uk/freereg1_csv_files/56646301f493fd1190000001](http://freereg2.freereg.org.uk/freereg1_csv_files/56646301f493fd1190000001)
Reported Issue:
The comparison of baptism date with birth date is sometimes wrong. In the attached errors list, in each case the birth date is double dated and the baptism year is the second part of the double date.    

![Screenshot](http://www.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1449448540-57262-1822/Capture.JPG)

**Comment by PatReynolds** [comment]
Doesn't seem to be any attachment and page urls don't work - shall I ask Mike for his list?

**Comment by Captainkirkdawson** [comment]
No it is all visible on the Feedback collection on FR

**Comment by Captainkirkdawson** [comment]
Simplest solution is to remove the check.  To do a full and proper job that permits comparison of 2 dates fields that each have 1-3 date components (dmy) and that permits both split years and the UCF and an override for TWYS  is at least 2 weeks effort

**Comment by edickens** [comment]
```
Agreed.  Not a very important check and WinReg does it anyway.  E


On 09/12/2015 15:38, Kirk Dawson wrote:


  Simplest solution is to remove the check. To do a full and
    proper job that permits comparison of 2 dates fields that each
    have 1-3 date components (dmy) and that permits both split years
    and the UCF and an override for TWYS is at least 2 weeks effort
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by PatReynolds** [comment]
Close?  Or look at again in 1.7?

On Wednesday, 9 December 2015, Eric Dickens notifications@github.com
wrote:

> Agreed.  Not a very important check and WinReg does it anyway.  E
> 
> On 09/12/2015 15:38, Kirk Dawson wrote:
> 
> Simplest solution is to remove the check. To do a full and
> proper job that permits comparison of 2 dates fields that each
> have 1-3 date components (dmy) and that permits both split years
> and the UCF and an override for TWYS is at least 2 weeks effort
> —
> Reply to this email directly or view
> it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/FreeUKGen/FreeUKRegProductIssues/issues/705#issuecomment-163297916
> .

## 

_\- -_

_Dr Pat Reynolds_
Executive Director
Free UK Genealogy  http://www.freeukgenealogy.org.uk/
A charity registered in England and Wales, number 1096940

​+44 ​1904 541411​ +44 7943 145387

36 Albemarle Road, York, YO23 1ER, UK

**Comment by Captainkirkdawson** [comment]
Removed for the time being. Added a 1.5 milestone for a complete fix
