### ISSUE TITLE
Missing XY in burial notes for Methodist, etc (gupton)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#707]
Issue reported by **gupton** at 2015-12-07 18:08:38 UTC
Time: 2015-12-07T11:27:25+00:00
Session ID: 16b9c1a41e6c1bb71867c748bbe8bcab
Problem Page URL: [/information-for-transcribers/entering-data-from-registers](/information-for-transcribers/entering-data-from-registers)
Previous Page URL: [http://freereg2.freereg.org.uk/feedbacks/new?utf8=%E2%9C%93&feedback_time=2015-12-07+11%3A16%3A28+UTC&session_id=16b9c1a41e6c1bb71867c748bbe8bcab&user_id=gupton&problem_page_url=%2Finformation-for-transcribers%2Fentering-data-from-registers&previous_page_url=http%3A%2F%2Ffreereg2.freereg.org.uk%2Finformation-for-transcribers&feedback_type=issue](http://freereg2.freereg.org.uk/feedbacks/new?utf8=%E2%9C%93&feedback_time=2015-12-07+11%3A16%3A28+UTC&session_id=16b9c1a41e6c1bb71867c748bbe8bcab&user_id=gupton&problem_page_url=%2Finformation-for-transcribers%2Fentering-data-from-registers&previous_page_url=http%3A%2F%2Ffreereg2.freereg.org.uk%2Finformation-for-transcribers&feedback_type=issue)
Reported Issue:
Field C: church

Requirements:
An entry in this field is mandatory
Enter in lower case with initial capitals
Examples:
St Ethelred PR, St Mary AT, Holy Trinity EX, Methodist, High Pavement, Congregational

![Screenshot](http://www.freereg.org.uk)

**Comment by AlOneill** [comment]
Updates re new Register types now complete, E&OE.
