### ISSUE TITLE
Test of new feedback (Captainkirk)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#708]
Issue reported by **Captainkirk** at 2015-12-08 19:30:21 UTC
Time: 2015-12-08T19:29:02+00:00
Session ID: dca2beda98fc7063fd40ba646aaa0efe
Problem Page URL: [/manage_resources/new](/manage_resources/new)
Previous Page URL: [http://test3.freereg.org.uk/feedbacks?](http://test3.freereg.org.uk/feedbacks?)
Reported Issue:
This is a simple test of the new feedback on test3. There should be an image attached    

![Screenshot](http://test3.freereg.org.uk/uploads/feedback/screenshot/56672fcde93790e57d000001/mikewright.JPG)

**Comment by PatReynolds** [comment]
I can see the image both on gmail and on github.


## 

_\- -_

_Dr Pat Reynolds_
Executive Director
Free UK Genealogy  http://www.freeukgenealogy.org.uk/
A charity registered in England and Wales, number 1096940

​+44 ​1904 541411​ +44 7943 145387

36 Albemarle Road, York, YO23 1ER, UK
