### ISSUE TITLE
here is a problem report attempting to mimic Eric B's flash error (benwbrum)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#71]
Issue reported by **benwbrum** at 2014-11-07 23:09:00 UTC
Time: 2014-11-07T23:06:50+00:00
Session ID: 2e0cf80f0f47d71db5331f76c524e1bc
Problem Page URL: [http://localhost:3000/county_pages/1](http://localhost:3000/county_pages/1)
Previous Page URL: []()
Reported Issue:
problem report goes here    

![Screenshot](http://localhost:3000)

**Comment by Sherlock21** [comment]
Does this mean you have fixed it? or abandoned the matter?

ericB
