### ISSUE TITLE
Missing link (gupton)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#710]
Issue reported by **gupton** at 2015-12-09 09:57:54 UTC
Time: 2015-12-09T09:45:06+00:00
Session ID: 424437275ee3fbd6354f7332d7247361
Problem Page URL: [/information-for-transcribers/entering-data-from-registers](/information-for-transcribers/entering-data-from-registers)
Previous Page URL: [http://freereg2.freereg.org.uk/information-for-transcribers](http://freereg2.freereg.org.uk/information-for-transcribers)
Reported Issue:
In the following:

---

Illegible or not clear?

If there's something you can't read, or that could be one thing or another, use our Uncertain Character Format (UCF). Even the transcription of uncertainty needs to be done the same way by everybody, so that we can all search the database effectively.

---

the UCF link is broken

Graham Upton    

![Screenshot](http://www.freereg.org.uk)

**Comment by AlOneill** [comment]
Thank you -- fixed.
