### ISSUE TITLE
The pop-up list of Register Types does not allow Unspecified (MikeNL)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#711]
Issue reported by **MikeNL** at 2015-12-09 12:42:07 UTC
Time: 2015-12-09T12:36:41+00:00
Session ID: d185a75a71da2eb8eacd17193ae4be7e
Problem Page URL: [/freereg1_csv_files/update_registers?church=56681f36f493fd7633000809](/freereg1_csv_files/update_registers?church=56681f36f493fd7633000809)
Previous Page URL: [http://freereg2.freereg.org.uk/freereg1_csv_files/update_churches?place=53cbf60eeca9eb03a60094ab](http://freereg2.freereg.org.uk/freereg1_csv_files/update_churches?place=53cbf60eeca9eb03a60094ab)
Reported Issue:
I have a file in one place that has no Register Type. I wish to relocate this file to a different place. I am being forced to enter a Register Type that the original file did not have. I feel that I should be allowed to leave the Register Type as Unspecified when relocating files.    

![Screenshot](http://www.freereg.org.uk)

**Comment by edickens** [comment]
```
Enter "Unknown".  E

On 09/12/2015 12:42, FreeUKGenIssues
  wrote:


  Issue reported by MikeNL at 2015-12-09
    12:42:07 UTC
    Time: 2015-12-09T12:36:41+00:00
    Session ID: d185a75a71da2eb8eacd17193ae4be7e
    Problem Page URL: /freereg1_csv_files/update_registers?church=56681f36f493fd7633000809
    Previous Page URL: http://freereg2.freereg.org.uk/freereg1_csv_files/update_churches?place=53cbf60eeca9eb03a60094ab
    Reported Issue:
    I have a file in one place that has no Register Type. I wish to
    relocate this file to a different place. I am being forced to
    enter a Register Type that the original file did not have. I
    feel that I should be allowed to leave the Register Type as
    Unspecified when relocating files. 

  —
    Reply to this email directly or view
      it on GitHub.
```
