### ISSUE TITLE
marston moretain (bevb)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#713]
Issue reported by **bevb** at 2015-12-10 00:42:52 UTC
Time: 2015-12-10T00:36:53+00:00
Session ID: b618f6327521805ca16628b215a12e98
Problem Page URL: [/places/53cbf5bceca9eb03a6000702](/places/53cbf5bceca9eb03a6000702)
Previous Page URL: [http://freereg2.freereg.org.uk/manage_counties/selection?option=Work with Specific Place](http://freereg2.freereg.org.uk/manage_counties/selection?option=Work with Specific Place)
Reported Issue:
This appears to be an extra. 
There is a Marston Moretaine with relevant batches.

Bev Bonning    

![Screenshot](http://www.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1449708172-33790-5345/Marston_Moretain.JPG)

**Comment by PatReynolds** [comment]
Does this make sense, or do I need to ask Bev to expand?

**Comment by edickens** [comment]
Bev needs to contact EricB.  E
