### ISSUE TITLE
Colour of the relocate button (white) (hawkinssm)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#714]
Issue reported by **hawkinssm** at 2015-12-10 14:12:40 UTC
Time: 2015-12-10T14:11:10+00:00
Session ID: 6f5c9457a78bec775a4598a50e93bdfc
Problem Page URL: [/freereg1_csv_files/update_registers?church=540827e0eca9eb0248d329f7](/freereg1_csv_files/update_registers?church=540827e0eca9eb0248d329f7)
Previous Page URL: [http://freereg2.freereg.org.uk/freereg1_csv_files/update_churches?place=53cd495eeca9ebee4f0050fc](http://freereg2.freereg.org.uk/freereg1_csv_files/update_churches?place=53cd495eeca9ebee4f0050fc)
Reported Issue:
I keep skipping past it and clicking on the report a problem button.    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Button coloured
