### ISSUE TITLE
image no. not in file when replacing a file. (deo123)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#716]
Issue reported by **deo123** at 2015-12-11 13:40:56 UTC
Time: 2015-12-11T13:30:10+00:00
Session ID: 72e38ef669bb2028403fe4f26fa6b89b
Problem Page URL: [/freereg1_csv_entries/565cf2aaf493fd89a1000723/edit](/freereg1_csv_entries/565cf2aaf493fd89a1000723/edit)
Previous Page URL: [http://www.freereg.org.uk/freereg1_csv_entries](http://www.freereg.org.uk/freereg1_csv_entries)
Reported Issue:
Hi Guy's,

yes me again.

Now, I have a file that was amended and the images no's entered.
I replaced this file on FR, next day no image no's entered in file on FR, except the   two entries I amended
Line 12
line 1592? i think

All the rest of the file have not entered these image no's.

The only way I would be able to see these iamge no's, which I use a lot, is to Delete the file and then Upload a new one.

REgards Doreen    

![Screenshot](http://www.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1449841256-86191-4742/image_no..JPG)

**Comment by Captainkirkdawson** [comment]
I can see no bug here. The current file uploaded on the system has as stated basically no film numbers. The last file in the attic does. The previous one does not. The one prior to that does. The one prior to that does not. So looks to me like there may be 2 files on the users computer 1 with and 1 without. Depending which 1 is selected sometimes there will be film numbers on other times not.

**Comment by PatReynolds** [comment]
I will get back to user on this.

Pat Reynolds
Executive Director, Free UK Genealogy

**Comment by PatReynolds** [comment]
Turned out every time Doreen uploaded the correct file the transcriber reloaded.
He was confused with the processing information he received.
