### ISSUE TITLE
Issues with The Transcriber Agreement (ericb)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#717]
Issue reported by **ericb** at 2015-12-11 15:21:13 UTC
Time: 2015-12-11T15:14:54+00:00
Session ID: 2ffccfc2d366370a664898b99f28f939
Problem Page URL: [/manage_resources/new](/manage_resources/new)
Previous Page URL: [http://www.freereg.org.uk/refinery/login](http://www.freereg.org.uk/refinery/login)
Reported Issue:
I see several major issues with The Transcriber Agreement:-
1) As a New Transcriber considering becoming a Member,  one cannot see the text before starting the sign up process. - And I would not join anything on that basis.

2) Assuming I did sign up, one cannot afterwards,  get a printout copy of what one signed on to - that is dated with the date of signing up.

3) Nor can one look up afterwards, the version of the agreement one signed on to.
All a bit negative, but taken  together, it does not seem well thought out.    

![Screenshot](http://www.freereg.org.uk)

**Comment by PatReynolds** [comment]
Unfortunately, the development of FreeREG and the implementation of the
Transcriber Agreement got out of sync, and there doesn't seem to be a
better way of dealing with this than the current situation.  There is no
Transcriber Agreement in existence.  We will launch a consultation process
in January, which will consult on both the content of the agreement and its
implementation.  Only after the conclusion of that consultation, and
consideration by the Trustees, will there be an Agreement for new
transcribers to sign.

The draft agreement makes provision for revision to the agreement, so
(presuming somewhat) that there is a mechanism for future change, and
change does happen to the agreement in future, provision for Transcribers
to have a copy of the agreement they signed up to, and the date of
subscription, sounds like a very good idea.  I will edit the subject to
reflect this.

On Friday, 11 December 2015, FreeUKGenIssues notifications@github.com
wrote:

> Issue reported by _ericb_ at 2015-12-11 15:21:13 UTC
> Time: 2015-12-11T15:14:54+00:00
> Session ID: 2ffccfc2d366370a664898b99f28f939
> Problem Page URL: /manage_resources/new
> Previous Page URL: http://wwwfreeregorguk/refinery/login
> Reported Issue:
> I see several major issues with The Transcriber Agreement:-
> 1) As a New Transcriber considering becoming a Member, one cannot see the
> text before starting the sign up process - And I would not join anything on
> that basis
> 
> 2) Assuming I did sign up, one cannot afterwards, get a printout copy of
> what one signed on to - that is dated with the date of signing up
> 
> 3) Nor can one look up afterwards, the version of the agreement one signed
> on to
> All a bit negative, but taken together, it does not seem well thought out
> 
> [image: Screenshot]
> https://camo.githubusercontent.com/a6b0c2d9e0cc1a2014e6e8c0ad0996201df75a07/687474703a2f2f777777667265657265676f7267756b
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/FreeUKGen/FreeUKRegProductIssues/issues/717.

## 

_\- -_

_Dr Pat Reynolds_
Executive Director
Free UK Genealogy  http://www.freeukgenealogy.org.uk/
A charity registered in England and Wales, number 1096940

​+44 ​1904 541411​ +44 7943 145387

36 Albemarle Road, York, YO23 1ER, UK

**Comment by Captainkirkdawson** [comment]
In the registration process there is no mention of an agreement nor the need to accept a non existent agreement. Acceptance is displayed as false/true. The default is false. It is an editable field. These could be dropped if desired.

**Comment by Sherlock21** [comment]
But some ID's - mine included currently show Agreement = TRUE. - this being from early day testing where to get going in the testing, I have to tick the box. That flag is still set.  So perhaps step one is to reset all to false = it would save any wrong positions being taken.

What is the actual text of the F1 Agreement please ( as I can't remember so far back!)
This being what I suppose could be construed to cover the present position for everyone?

**Comment by Sherlock21** [comment]
If you are wondering where this came from, --
I started this topic because I just began the process of creating a new ID.  and remembered the strong debate we had in the very early days about some of Darren's input, so wished to check what it currently said.

**Comment by Captainkirkdawson** [comment]
There is no Transcriber Agreement. The version proposed by Darren was
withdrawn. There is to be a consultation on a new version in the New Year.

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by PatReynolds** [comment]
​Hi Eric,

Just came across this as not answered as I was tidying things up before the
conference: the data currently in FreeREG with regard to the Transcriber
agreement is just noise.  Oncve the consultation is closed, the Trustees
have decided on any changes to agreement or implimentation, everyone will
be invited to sign up/decline.

Best wishes,
​

Pat Reynolds

Executive Director, Free UK Genealogy
