### ISSUE TITLE
Searching feature. (ericb)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#72]
Issue reported by **ericb** at 2014-11-19 16:00:56 UTC
Time: 2014-11-19T15:55:52+00:00
Session ID: 8eb1c7cad41b25876adcd1a1d40e9a57
Problem Page URL: [/search_queries/new](/search_queries/new)
Previous Page URL: [http://test2.freereg.org.uk/](http://test2.freereg.org.uk/)
Reported Issue:
After selecting a County (SOM) the application does not put up the County list of Place names (whichI wanted to have rather than the whole County).
If I tick the "nearby" box ( which is what I wanted)
It returns an error message saying: must select a Place name.

I might have put this in before!
EricB    

![Screenshot](http://test2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Same as 293
