### ISSUE TITLE
29532621 issue (Kirk)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#720]
Issue reported by **Captainkirk** at 2015-12-08 19:30:21 UTC
Time: 2015-12-08T19:29:02+00:00
Session ID: dca2beda98fc7063fd40ba646aaa0efe
Problem Page URL: [/manage_resources/new](/manage_resources/new)
Previous Page URL: [http://test3.freereg.org.uk/feedbacks?](http://test3.freereg.org.uk/feedbacks?)
Reported Issue:
This is a simple test of the new feedback on test3. There should be an image attached. Was there?    

![Screenshot](http://test3.freereg.org.uk/uploads/feedback/screenshot/56672fcde93790e57d000001/mikewright.JPG)

**Comment by PatReynolds** [comment]
I am looking on gmail on a smartphone. 4g, but slow to get the image. It
says "not found" but that could be a connectivity issue.

Pat Reynolds
Executive Director, Free UK Genealogy

**Comment by edickens** [comment]
I get the same.  I think that the problem is that you first need to be 
logged in for it to be possible to just click the "screen print" link.  E
