### ISSUE TITLE
Use of the new "Role" Action 30099999 issue (Eric)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#721]
Issue reported by **REGManager** at 2015-12-15 09:06:39 UTC
Time: 2015-12-15T08:56:57+00:00
Session ID: 4daccc8ce87bffd933263cbf06594ac9
Problem Page URL: [/userid_details/person_roles](/userid_details/person_roles)
Previous Page URL: [http://www.freereg.org.uk/userid_details/options](http://www.freereg.org.uk/userid_details/options)
Reported Issue:
I can now list all those who are assigned to certain Roles.  I have looked at them all and many, even "Executive Director", are vacant.
My question is therefore how we should use this facility?  Every UserID has to be assigned a Role, from Researcher to Executive Director.  But they can only be assigned one Role.   Each Role provides access to different Actions, but I am not sure which.
I think this is a great facility, but we need to discuss how to use it and I will allocate the Roles accordingly.
I would like to avoid someone having to have more than one UserID in order to access the relevant Actions, but this may be necessary, if only to provide the correct distribution of messages generated from the website.
I have more than one UserID, but I have only done this so that I can see what a Syndicate Coordinator is able to do.  I use just one for all my work on the website.
Thoughts?  E    

![Screenshot](http://www.freereg.org.uk)

**Comment by Sherlock21** [comment]
The last time i/ did one of these jobs in Industry, we had a spreadsheet or Role title / actions  (ie permissions).

and Role title could have a subset of one or more.
OR we could have ( say)
Transcriber that had all its expected limited actions.
CC which had all the normaL functions for each County it had responsibility over + all the TRanscriber functions.
DM that had the specifics, + CC for ALL + Transcriber.

and so on.

Surely this exists now, - even if its in Kirk's mind.? so what is needed is access to that! for those who need to see. and access to this spreadsheet would be READ ONLY or Read + Write.

**Comment by edickens** [comment]
I have made a start on this.  I was going to change my Profile to all the different Roles to see what happens, but I will wait for Kirk's reply first.
Attached is where I have got to.  E
![capture](https://cloud.githubusercontent.com/assets/8876165/11807672/282c34ca-a313-11e5-8085-38f517a68123.JPG)

**Comment by PatReynolds** [comment]
Please let Helena or me know if you want this converting to a google doc
for all to edit.

Best wishes,

Pat

On Tuesday, 15 December 2015, Eric Dickens notifications@github.com wrote:

> I have made a start on this. I was going to change my Profile to all the
> different Roles to see what happens, but I will wait for Kirk's reply first.
> Attached is where I have got to. E
> [image: capture]
> https://cloud.githubusercontent.com/assets/8876165/11807672/282c34ca-a313-11e5-8085-38f517a68123.JPG
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/FreeUKGen/FreeUKRegProductIssues/issues/721#issuecomment-164710515
> .

## 

_\- -_

_Dr Pat Reynolds_
Executive Director
Free UK Genealogy  http://www.freeukgenealogy.org.uk/
A charity registered in England and Wales, number 1096940

​+44 ​1904 541411​ +44 7943 145387

36 Albemarle Road, York, YO23 1ER, UK

**Comment by edickens** [comment]
```
Hi Pat,
Have been at a loose end so have sorted out those of lesser status
than myself...



N/A means that it is blocked and not in use at present.
I have this as an Excel spreadsheet if that helps.  I would like
Kirk to update it.
E

On 15/12/2015 11:56, PatReynolds wrote:

Please let Helena or me know if you want this
  converting to a google doc
  for all to edit.

  Best wishes,

  Pat
```

**Comment by Captainkirkdawson** [comment]
OPTIONS = {
    'researcher' => [ "Profile","Roadmap"],
    'trainee' => [ "Profile", "Batches","Roadmap"],
    'pending' => [ "Profile"],
    'transcriber' => [  "Profile", "Batches","Roadmap"],
    'syndicate_coordinator' => [  "Profile", "Batches", "Manage Syndicate","Roadmap"],
    'contacts_coordinator'=> [ "Profile", "Batches", "Feedback", "Contacts", "System Documentation" ,"Roadmap"],
    'county_coordinator' =>  [  "Profile", "Batches", "Manage Syndicate", "Manage County", "Access Profiles","Contacts","Roadmap"],
    'country_coordinator' => [  "Profile", "Batches", "Manage Syndicate","Manage Country", "Manage County","Access Profiles","Contacts","Roadmap"],
    'volunteer_coordinator' => [  "Profile", "Batches", "Manage Syndicates", "Manage Userids","Contacts","Roadmap"],
    'data_manager' => [  "Profile", "Batches", "Manage Syndicate", "Manage Counties", "Access Profiles", "RefineryCMS", "Physical Files","Access Attic", "Search Performance",
                         "Feedback", "Contacts", "System Documentation","Roadmap" ],
    'technical' => [  "Profile", "Batches",   "RefineryCMS", "Access Attic","Search Performance", "Feedback", "Contacts", "Site Statistics",
                      "System Documentation","Access Profiles","Roadmap"],
    'system_administrator' =>[  "Profile", "Batches", "Manage Syndicate", "Manage Counties", "Manage Userids", "Syndicate Coordinators",
                                "County Coordinators", "Country Coordinators","Physical Files","RefineryCMS", "Access Attic","Site Statistics","Search Performance",
                                "Feedback", "Contacts", "System Documentation","Roadmap" ],
    'project_manager' =>[  "Profile", "Batches", "Manage Userids", "RefineryCMS", "Site Statistics","Search Performance",
                                "Feedback", "Contacts", "System Documentation","Roadmap" ],  
    'executive_director' =>[  "Profile", "Batches", "Manage Userids", "Syndicate Coordinators",
                                "County Coordinators", "Country Coordinators","RefineryCMS", "Site Statistics","Search Performance",
                                "Feedback", "Contacts", "System Documentation","Roadmap" ], 
    'publicity_coordinator'=> [ "Profile", "Batches",  "Contacts", "System Documentation" ,"Roadmap"],  
    'genealogy_coordinator'=> [ "Profile", "Batches", "Contacts", "System Documentation" ,"Roadmap"],
    'documentation_coordinator' => [  "Profile", "Batches", "Manage Syndicate", "Manage Counties", "Access Profiles", "RefineryCMS",
                         "Feedback", "Contacts", "System Documentation","Roadmap" ],
    'engagement_coordinator' => [  "Profile", "Batches", "Access Profiles", "RefineryCMS", "Contacts", "System Documentation","Roadmap" ]  
  }
