### ISSUE TITLE
29842231 Enhancement Suggestion (Pat)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#722]
Issue reported by **Pat** at 2015-12-12 09:30:31 UTC
Time: 2015-12-12T09:21:21+00:00
Session ID: 
Problem Page URL: []()
Previous Page URL: [http://test3.freereg.org.uk/contacts/new](http://test3.freereg.org.uk/contacts/new)
Reported Issue:
Another test this time with image    

![Screenshot](http://test3.freereg.org.uk/uploads/contact/screenshot/566be937e93790f186000002/IMG_20151212_091903081.jpg)

**Comment by Captainkirkdawson** [comment]
Was a test
