### ISSUE TITLE
30795964 Missing records from FR (Eric McMullin)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#723]
Issue reported by **Eric McMullin** at 2015-12-23 10:26:04 UTC
Time: 2015-12-23T10:20:28+00:00
Session ID: 
Problem Page URL: []()
Previous Page URL: [http://freereg2.freereg.org.uk/contacts/new](http://freereg2.freereg.org.uk/contacts/new)
Reported Issue:
I found that events on the old site are not on the new site.
Does this mean that there were problems with the old transcriptions?
Are the events on the old site still valid or have they been found to be incorrect?

There are 600 files on the userid files that have not been processed. These need to be reviewed and, if required, processed.    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Needs700

**Comment by Sherlock21** [comment]
Is this not the same problem as #695 ?

In which case, Kirk's msg on 695 says "Leave it to Me" - ie to kirk now he has found the different groupings.

IF this is a different topic, then please explain how its different and what amI supposed to do with it?
Its not the same thing as dealing with the 1100   in the Unprocessed Files listing is it?

**Comment by Captainkirkdawson** [comment]
This story has nothing to do with #695 which dealt with the failure to promulgate a change in Chapman Code and some other changes to search records and is being dealt with at this moment,
This story deals with the Physical Files  (1100) that have not been processed.  This cannot be dealt with automatically as a human(s) has to determine if each file  should be processed or deleted,

**Comment by edickens** [comment]
```
Hi Kirk,

EricB and I are cautious about doing anything until you have stopped
the over night FR1/FR update (because we will be deleting FR files)
and you have sorted out the STS/WOR problem, where I think you are
doing a fix, because a lot of the unprocessed are STS files.

Please let us know when it is OK for us to get stuck in.

Thanks,

Eric
```

**Comment by Captainkirkdawson** [comment]
The overnight update was stopped 2 months ago.  Is this still open?

**Comment by edickens** [comment]
There are still files in the "Unprocessed" which are from FR1, so this could be the reason why FR1 records are not showing in FR.
EricB needs to talk to Kirk about what has happened while he has been away.

**Comment by Sherlock21** [comment]
The "UnProcessed files " is suspended at the moment.
Reasons being: 
A) CC's had been advised this was going on, and should tell their Transcribers BUT the loop is too slow, and attempts to resurrect files over 6 months cause massive complaints from Transcribers and CCs regarding the standard email that its successfully loaded - if it works - or that it failed if it does not - when they say they knew nothing about it!  
B) the perception by me that some files which were dealt with by putting in the Process list, then came back next day in the Unprocessed list! And with no system messages to me ( the one doing the job) Its like working blind.
c) Process is too slow asking CCs if an old file is still needed  or has it been superseded  takes too long to get answers back.
d) listing of 1100 or more files needs means of ordering by user by any of the columns to make it handleable. 

e) one user (CC of STS ) refuses any help and said he would do all his own but as he cannot access the tool he is working off an old screen copy I gave him in January. - hence separate request for CC's to have access to the main list, for their own County.  

f) too much of my time being used by Transcribers & CC;s asking me to keep explaining WHY files are in this state - when i dont know all the possible responses!

**Comment by Captainkirkdawson** [comment]
Excellent summary EricB. Lets see what we can do to develop a better process that makes it more efficient and effective, 
In the meantime lets suspend work on "The Not Approved listing is continuously growing. 738" until we have evidence and the Physical Files component of "CC and SC have Files Waiting to be processed report to CC and SC have Files Waiting to be processed report  of 734" until we see a specific general need.
Firstly, the requirement to clean up these unprocessed files exists; Secondly, the reason they are in this state is unknown and the reason is irrelevant; the situation exists,.Thirdly, some coordinators (but not all) have sufficient technical background to deal with the issue themselves without leading to long term issues, Fourthly, the current tools available to Ericb are insufficient. Fifthly, the amount of work required is too much for one person to undertake. 
Proposal. Provide ability for DM to produce a report on demand from the list. Provide process by which DM can submit and receive processing report of a file with no reference to CC/Transcriber?. Work on one county and one userid at a time to clear a county. Involve other DMs in activity,

**Comment by edickens** [comment]
```
And is it possible to divert the "File processed" reports to the DM
only when the request has come from clicking "Process" on this
list?  Perhaps even always process immediately, because it will only
be the DM requesting the process and so can be done gradually.  This
will get over the problem of Transcribers and SCs getting unexpected
messages.  ED

On 14/03/2016 14:50, Kirk Dawson wrote:


  Excellent summary EricB. Lets see what we can do to develop a
    better process that makes it more efficient and effective, 
    In the meantime lets suspend work on "The Not Approved listing
    is continuously growing. 738" until we have evidence and the
    Physical Files component of "CC and SC have Files Waiting to be
    processed report to CC and SC have Files Waiting to be processed
    report of 734" until we see a specific general need.
    Firstly, the requirement to clean up these unprocessed files
    exists; Secondly, the reason they are in this state is unknown
    and the reason is irrelevant; the situation exists,.Thirdly,
    some coordinators (but not all) have sufficient technical
    background to deal with the issue themselves without leading to
    long term issues, Fourthly, the current tools available to Ericb
    are insufficient. Fifthly, the amount of work required is too
    much for one person to undertake. 
    Proposal. Provide ability for DM to produce a report on demand
    from the list. Provide process by which DM can submit and
    receive processing report of a file with no reference to
    CC/Transcriber?. Work on one county and one userid at a time to
    clear a county. Involve other DMs in activity, 
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by Sherlock21** [comment]
i like the idea of diverting emails if the DM does the "fix" job. AND also implement the Do As Soon As option so one can keep on the same job instead of "doing a bit today, and the remainder of it tomorrow"

**Comment by Captainkirkdawson** [comment]
The scope of the problem may be smaller than previously anticipated, I need to do more research into "The Not Approved listing is continuously growing. 738" following EricB last postings which may have pointed to a possible logic problem. Having a vacation does give one a clearer view.

**Comment by Captainkirkdawson** [comment]
After research it is clear that the report produced on unprocessed files is in correct. A revised list will be ready by 21 st March

**Comment by Captainkirkdawson** [comment]
After extensive research based on information in FR  have concluded that the following are likely the only files that exist in the FR1 datafiles on FR that have possibly never been processed.

***_,amb1291,LANDOBBA.CSV,likely never processed
***_,amb1291,LANDOBBU.CSV,likely never processed
***_,brobinson43,HUNALCBU1,CSV.csv,likely never processed
***_,DSR,SOMNFIBU2.CSV,likely never processed
***_,Jonny,STSBRDBU.CSV,likely never processed
***_,meghoppe, LEILETBA6.csv,likely never processed
***_,Pateric,KENLEWBU45.CSV,likely never processed
***_,RReeve,NFKINGBA.CSV,likely never processed
***_,RReeve,NFKINGBA1.CSV,likely never processed
***_,RReeve,NFKINGBU.CSV,likely never processed
***_,RReeve,NFKINGBU1.CSV,likely never processed
***_,RReeve,NFKINGMA.CSV,likely never processed
****,RReeve,NFKINGMA1.CSV,likely never processed

**Comment by Captainkirkdawson** [comment]
Ignore bolding; all are the same

**Comment by Captainkirkdawson** [comment]
What an excellent piece of work. My thanks to you and the support of EricD. It was very well done.

Based on what you have done and what information we currently have we can, I think, conclude that there are no known missing files that have not been loaded into FR from the old FR1 during the period in which we were loading them both at the same time from FR1.

That is not to say that there are no missing files but that we have no easy way of detecting them. 

The only way that I can see of doing it  is to take a new complete copy of the data files for FR1. Systematically process the first 10/20 records from each file and see if they are in FR by doing a search for them. If all 10 are missing the file is not loaded into FR. However that situation could exist because of a deliberate decision of the coordinator.

I am unconvinced of the value of  such an undertaking.

**Comment by edickens** [comment]
```
Definitely no need for more work on this.  Too much other clean up
work has taken place and whatever you might do would not now
reconcile.

The RAP and GAP reports in V1.5 will show gaps, for whatever reason,
and then CCs can take what action is needed from uploading again to
re-transcribing.

Thanks,

Eric
_____________________________________
```

Eric J Dickens
FreeREG Chairman
    On 18/03/2016 22:19, Kirk Dawson wrote:

```
  What an excellent piece of work. My thanks to you and the
    support of EricD. It was very well done.
  Based on what you have done and what information we currently
    have we can, I think, conclude that there are no known missing
    files that have not been loaded into FR from the old FR1 during
    the period in which we were loading them both at the same time
    from FR1.
  That is not to say that there are no missing files but that we
    have no easy way of detecting them. 
  The only way that I can see of doing it is to take a new
    complete copy of the data files for FR1. Systematically process
    the first 10/20 records from each file and see if they are in FR
    by doing a search for them. If all 10 are missing the file is
    not loaded into FR. However that situation could exist because
    of a deliberate decision of the coordinator.
  I am unconvinced of the value of such an undertaking.
  —
    You are receiving this because you commented.
    Reply to this email directly or view
      it on GitHub
```
