### ISSUE TITLE
32031183 Sending reset password does not work (Eric)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#724]
Issue reported by **REGManager** at 2016-01-06 17:33:03 UTC
Time: 2016-01-06T17:31:21+00:00
Session ID: 80d68f865505613798b70f74f670e4d5
Problem Page URL: [/userid_details/5462b42fe937907d70000783](/userid_details/5462b42fe937907d70000783)
Previous Page URL: [http://www.freereg.org.uk/userid_details/5462b42fe937907d70000783](http://www.freereg.org.uk/userid_details/5462b42fe937907d70000783)
Reported Issue:
I've had another problem with someone trying to reset their password.  See attached.  I think that there could be a problem.  E    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/568d4fcff493fdaa7a000a6e/Capture.JPG)

**Comment by Captainkirkdawson** [comment]
There were 18 missing entries in Refinery. These have been added.
