### ISSUE TITLE
32380421 "Next result" button skipping lots of results (Helen)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#726]
Issue reported by **helvissa** at 2016-01-10 18:33:41 UTC
Time: 2016-01-10T18:31:53+00:00
Session ID: b2a3bac54eb1c64d7bd25a7ad38d57a5
Problem Page URL: [/search_records/5510ac5fe93790f8ad94b85e?page_number=0&search_id=5692a394f493fd8014000d78](/search_records/5510ac5fe93790f8ad94b85e?page_number=0&search_id=5692a394f493fd8014000d78)
Previous Page URL: [http://www.freereg.org.uk/search_records/5690fd1df493fda3d7000308?search_id=5692a394f493fd8014000d78](http://www.freereg.org.uk/search_records/5690fd1df493fda3d7000308?search_id=5692a394f493fd8014000d78)
Reported Issue:
I did a search for the surname Hazel in Elmstead, Essex, using soundex. I wanted to go through all the baptisms one after the other, so I clicked on John Hazel's 1739 baptism (the first result), then clicked "next result" expecting to be taken to his sibling's baptism which follows. Except it jumped over several results and took me to his marriage in 1764!

I've noticed this happen with other searches I've done - but it doesn't _always_.

I haven't attached a screenshot as it's difficult to show it happening - maybe you can try reproducing the search using the info above?

I'm using Chrome on Windows 7.    

![Screenshot](http://www.freereg.org.uk)

**Comment by dougkdev** [comment]
Diagnosed the problem: When a search is performed, a list of results is
returned.  Previous/Next is currently based on the order in the unsorted
list, not the sorted order in which the results are displayed on the
screen.  (Notice that if we re-sort the list by clicking various other
column headings, the previous/next traversal is always in the same order).
The fix will be to take the current display sort order into account when
choosing the previous or next result.
