### ISSUE TITLE
32904403 Data Problem (Kevin Barnes)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#728]
Issue reported by **Kevin Barnes** at 2016-01-16 20:06:43 UTC
Time: 2016-01-16T19:55:03+00:00
Session ID: 
Problem Page URL: [unknown](unknown)
Previous Page URL: [http://www.freereg.org.uk/contacts/55108ef8e937907e5f4b2262/report_error?query=569a9bacf4040bab70000c7e](http://www.freereg.org.uk/contacts/55108ef8e937907e5f4b2262/report_error?query=569a9bacf4040bab70000c7e)
Reported Issue:
John should be Job
I got the original details from the actual Corse parish records a while ago for my family tree but somehow all the siblings of my direct ancestor, Job,  have gone missing. I was looking through your website to find them. John, a sibling, was baptised 25 Jan 1763 as stated, but the next John baptised on 8 March 1772 corresponds to Job I already have on my family tree.    

![Screenshot](http://www.freereg.org.uk)

**Comment by Sherlock21** [comment]
DELETE THIS GITHUB RECORD PLEASE. CEATED IN ERROR>
