### ISSUE TITLE
33215614 Add list of places updated to nightly report (Lesley Morgan)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#729]
Issue reported by **Lesley Morgan** at 2016-01-20 10:33:34 UTC
Time: 2016-01-20T10:20:45+00:00
Session ID: 
Problem Page URL: []()
Previous Page URL: [http://www.freereg.org.uk/contacts/new](http://www.freereg.org.uk/contacts/new)
Reported Issue:
The information that "14,054 records (2,917 baptisms, 9,096 marriages and 2,041 burials) were added in the 24 hrs ending at midnight GMT. " is not of much value unless the names of the parishes that have been added/updated is also given.    

![Screenshot](http://www.freereg.org.uk)

**Comment by edickens** [comment]
```
Hello everyone,

With Kirk now on vacation, I need to deal with these messages, but I
am still not confident enough in how this system works.

This email has come from FreeUKGenIssues, but who is that?  I cannot
reply to the sender as this message is no longer in the list of
contacts, so perhaps it has been answered and then Destroyed?  I
have not seen a reply to the sender.  With no message left on the
server, I cannot find a return email address.

However, the answer should be that we will be providing the means
for registered researchers to ask to be told when the parish in
which they are interested is changed.  In this way it will not be
necessary to look at the website every day to see what has changed.

E
_____________________________________
```

Eric J Dickens
FreeREG Chairman
    On 21/01/2016 05:34, FreeUKGenIssues
      wrote:

```
  Issue reported by Lesley Morgan at 2016-01-20
    10:33:34 UTC
    Time: 2016-01-20T10:20:45+00:00
    Session ID: 
    Problem Page URL: 
    Previous Page URL: http://wwwfreeregorguk/contacts/new
    Reported Issue:
    The information that "14,054 records (2,917 baptisms, 9,096
    marriages and 2,041 burials) were added in the 24 hrs ending at
    midnight GMT " is not of much value unless the names of the
    parishes that have been added/updated is also given 

  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by PatReynolds** [comment]
Hello Eric,

This is coming through from the 'members' section.  So you need to look up
Lesley Morgan to find her email address.

Best wishes,

Pat

On 21 January 2016 at 08:11, Eric Dickens notifications@github.com wrote:

> Hello everyone,
> 
> With Kirk now on vacation, I need to deal with these messages, but I
> am still not confident enough in how this system works.
> 
> This email has come from FreeUKGenIssues, but who is that?  I cannot
> reply to the sender as this message is no longer in the list of
> contacts, so perhaps it has been answered and then Destroyed?  I
> have not seen a reply to the sender.  With no message left on the
> server, I cannot find a return email address.
> 
> However, the answer should be that we will be providing the means
> for registered researchers to ask to be told when the parish in
> which they are interested is changed.  In this way it will not be
> necessary to look at the website every day to see what has changed.
> 
> E
> 
> ---
> 
> Eric J Dickens
> FreeREG Chairman
> On 21/01/2016 05:34, FreeUKGenIssues
> wrote:
> 
> Issue reported by Lesley Morgan at 2016-01-20
> 10:33:34 UTC
> Time: 2016-01-20T10:20:45+00:00
> Session ID:
> Problem Page URL:
> Previous Page URL: http://wwwfreeregorguk/contacts/new
> Reported Issue:
> The information that "14,054 records (2,917 baptisms, 9,096
> marriages and 2,041 burials) were added in the 24 hrs ending at
> midnight GMT " is not of much value unless the names of the
> parishes that have been added/updated is also given
> 
> —
> Reply to this email directly or view
> it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/FreeUKGen/FreeUKRegProductIssues/issues/729#issuecomment-173490939
> .

## 

_\- -_

_Dr Pat Reynolds_
Executive Director
Free UK Genealogy  http://www.freeukgenealogy.org.uk/
A charity registered in England and Wales, number 1096940

​+44 ​1904 541411​ +44 7943 145387

36 Albemarle Road, York, YO23 1ER, UK

**Comment by PatReynolds** [comment]
I've put this in 1.4 but perhaps can wait to 1.7 - and the alerts system may make it redundant?
