### ISSUE TITLE
33295939 change of order in options (Julie )

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#730]
Priority 12 (0	1	2	9)

Issue reported by **JulieHarold** at 2016-01-21 08:52:19 UTC
Time: 2016-01-21T08:50:04+00:00
Session ID: 0ee4fd3c6433bbce3f1005d9f0cb072a
Problem Page URL: [/registers/5407fe0ceca9eb81e264d8cb/rename](/registers/5407fe0ceca9eb81e264d8cb/rename)
Previous Page URL: [http://freereg2.freereg.org.uk/registers/5407fe0ceca9eb81e264d8cb](http://freereg2.freereg.org.uk/registers/5407fe0ceca9eb81e264d8cb)
Reported Issue:
When you change a register type you have to scroll down to get to parish register.  Since it is the most likely one you want to change it to (especially above extract and memorial inscription) could it be moved up the listing so that scrolling isn't needed to select it ?

I appreciate they are in alphabetical order at present but it would seem a pragmatic and relatively simple change.

Julie
(Norfolk coordinator)    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Implemented
