### ISSUE TITLE
33424653 Missing search results (Ann)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#731]
Issue reported by **AnnSumner** at 2016-01-22 20:37:33 UTC
Time: 2016-01-22T20:23:31+00:00
Session ID: 4f30085f570f96e043ed375110e6f6a1
Problem Page URL: [/search_queries/56a28fc2f493fddb0c000884](/search_queries/56a28fc2f493fddb0c000884)
Previous Page URL: [http://www.freereg.org.uk/search_queries/new?search_id=56a28f17f493fddb0c000878](http://www.freereg.org.uk/search_queries/new?search_id=56a28f17f493fddb0c000878)
Reported Issue:
Children without first names are not showing in search results for burials at Biddulph, Staffordshire    

![Screenshot](http://www.freereg.org.uk)

**Comment by edickens** [comment]
There are records with no entry in the Firstname.  For example when a child is buried before it is given a name.   The entry is something like "Male child of" and that is it.  It looks as if the Search is ignoring these entries.  They are found in FR1.  E

**Comment by FreeUKGenIssues** [comment]
That's very interesting, and entirely believable.  Can we find a specific
example record in Biddulph which I can use to verify I've fixed the problem?

**Comment by edickens** [comment]
```
As you found, the URL in the Feedback report gives the search that
was taking place...


which leads me by looking at the place/register/batch information...



But I have not tried searching for this entry.

Regards,

Eric

_____________________________________
```

Eric J Dickens
FreeREG Chairman
    On 23/01/2016 01:39, FreeUKGenIssues
      wrote:

```
That's very interesting, and entirely believable. Can
  we find a specific
  example record in Biddulph which I can use to verify I've fixed
  the problem?

  On Fri, Jan 22, 2016 at 4:09 PM, Eric Dickens
  <notifications@github.com>
  wrote:

  > There are records with no entry in the Firstname. For example
  when a child
  > is buried before it is given a name. The entry is something
  like "Male
  > child of" and that is it. It looks as if the Search is
  ignoring these
  > entries. They are found in FR1. E
  >
  > —
  > Reply to this email directly or view it on GitHub
  >
```

https://github.com/FreeUKGen/FreeUKRegProductIssues/issues/731#issuecomment-174068486
      > .
      >
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Sherlock21** [comment]
Who knew that the record was actually created in the first place, and not being found by the Program?
Please tell me the file name and userID of the Transcriber / Uploader and i will try to find out why.

**Comment by Captainkirkdawson** [comment]
I can confirm that the search does not locate the record with a blank entry in the forename of a burial. A valid search record is not created from the entry. I created one

{ "_id" : ObjectId("56a3e7f32310403226000001"), "error_flag" : "false", "line_id" : "kirkcaptainkirk.LINBEEBU.CSV.1", "file_line_number" : 1, "register_entry_number" : "474", "burial_date" : "24 Feb 1936", "year" : "1936", "burial_person_forename" : null, "relationship" : null, "male_relative_forename" : null, "female_relative_forename" : null, "relative_surname" : null, "burial_person_surname" : "CHAPMAN", "person_age" : "83", "burial_person_abode" : "78 Lord Street, Grimsby", "notes" : "Died 21st February. Added beneath name: '(seeNo. 470)'", "county" : "LIN", "place" : "Beelsby", "church_name" : "St Andrew", "register_type" : " ", "record_type" : "bu", "freereg1_csv_file_id" : ObjectId("5696e058231040517500
0001"), "record_digest" : "BypjBual1eOYmneLY8Lb8w==", "u_at" : ISODate("2016-01-23T20:52:03.984Z"), "c_at" : ISODate("2016-01-23T20:52:03.984Z") }
 and this is the search record

> db.search_records.find({freereg1_csv_entry_id: ObjectId("56a3e7f32310403226000001")})
> { "_id" : ObjectId("56a3e7f32310403226000002"), "transcript_dates" : [  "24 Feb 1936" ], "search_dates" : [  "1936-02-24" ], "location_names" : [  "Beelsby (St Andrew)",  " [Unspecified]" ], "search_soundex" : [ ], "record_type" : "bu", "chapman_code" : "LIN", "file_line_number" : 1, "line_id" : "kirkcaptainkirk.LINBEEBU.CSV.1", "transcript_names" : [ ], "freereg1_csv_entry_id" : ObjectId("56a3e7f32310403226000001"), "place_id" : ObjectId("53cd4967eca9ebee4f006172") }

**Comment by Captainkirkdawson** [comment]
PS that record was a test record on my server

**Comment by Captainkirkdawson** [comment]
Have further confirmed that an empty forename in a marriage leaves that participant out of the marriage (either bride or groom)
Similarly the participant in a baptism with an empty forename is not included as a participant in the search record.

**Comment by Captainkirkdawson** [comment]
Have confirmed that code appears to function correctly on test3 with new processor
