### ISSUE TITLE
33850630 Provide a printable version of the Search Results

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#732]
Issue reported by **Patrick Delaney** at 2016-01-27 18:57:10 UTC
Time: 2016-01-27T18:55:13+00:00
Session ID: 
Problem Page URL: [unknown](unknown)
Previous Page URL: [http://freereg2.freereg.org.uk/contacts/564bf163f493fdc2fa022bfe/report_error?query=56a911d9791e3b1365000f22](http://freereg2.freereg.org.uk/contacts/564bf163f493fdc2fa022bfe/report_error?query=56a911d9791e3b1365000f22)
Reported Issue:
I am unable to print this transcription as it is not available in a printable format    

![Screenshot](http://www.freereg.org.uk)

**Comment by edickens** [comment]
Although the detail can be printed, there is no "Printable" version for the list of results.  This is useful so that the researcher can go through what they have found checking off what is not relevant.  E

**Comment by Captainkirkdawson** [comment]
This is available
