### ISSUE TITLE
33983945 Data Question (Liz Rushton)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#733]
Issue reported by **Liz Rushton** at 2016-01-29 07:59:05 UTC
Time: 2016-01-29T07:57:48+00:00
Session ID: 
Problem Page URL: []()
Previous Page URL: [http://freereg2.freereg.org.uk/contacts/new](http://freereg2.freereg.org.uk/contacts/new)
Reported Issue:
Hi,
Having chosen a county for my search, how do I "unselect" that county without having to start completely again?  There is a feature to erase years but not places.    

![Screenshot](http://www.freereg.org.uk)

**Comment by AlOneill** [comment]
Just as Ctrl (or Cmd on Mac) click selects a (usually second or third) county, Ctrl click will deselect any county, yes?

**Comment by AlOneill** [comment]
As per the Help ...
