### ISSUE TITLE
34872399 Message System improvement (Eric)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#734]
Issue reported by **REGManager** at 2016-02-08 14:46:39 UTC
Time: 2016-02-08T14:19:23+00:00
Session ID: 9758923e59d126d6171a5081e7ece45f
Problem Page URL: [/messages](/messages)
Previous Page URL: [http://www.freereg.org.uk/manage_resources/new](http://www.freereg.org.uk/manage_resources/new)
Reported Issue:
Recipients, especially Coordinators, do not know who else the message has gone to.  I suggest that at the bottom of the text is something like the following:-
"This messages has been sent to all Transcribers, Syndicate Coordinators", listing whichever groups have been selected in the "Send to" option.    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Is this really super urgent; who is this aimed at?

**Comment by edickens** [comment]
Probably mostly for my benefit!  But it is to avoid two people dealing with it.
Not urgent.  E

**Comment by Captainkirkdawson** [comment]
System has totally changed. No longer relevant
