### ISSUE TITLE
34870046 Sending message from REGManager (Eric)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#735]
Issue reported by **REGManager** at 2016-02-08 14:07:26 UTC
Time: 2016-02-08T14:06:01+00:00
Session ID: 9758923e59d126d6171a5081e7ece45f
Problem Page URL: [/messages/56b89d36f493fd31ad0007b5](/messages/56b89d36f493fd31ad0007b5)
Previous Page URL: [http://www.freereg.org.uk/messages](http://www.freereg.org.uk/messages)
Reported Issue:
I set up the message with a good layout, but all the line endings have been lost on transmission.  The message now reads very badly.  E    

![Screenshot](http://www.freereg.org.uk)

**Comment by dougkdev** [comment]
I switched the message format from html to plain-text, so newlines and
spaces should be preserved. Fix is on test3, not live on production server
yet.

**Comment by edickens** [comment]
```
Does not seem to work.


The message was...



I am not bothered about font size or colour.  Just the line
endings.  I have left the message in Test3 as not sent.

Thanks

Eric

On 12/02/2016 06:55, dougkdev wrote:

I switched the message format from html to plain-text,
  so newlines and
  spaces should be preserved. Fix is on test3, not live on
  production server
  yet.

  On Wed, Feb 10, 2016 at 11:27 AM, sean-wood
  <notifications@github.com>
  wrote:

  > Assigned #735
  >
  <https://github.com/FreeUKGen/FreeUKRegProductIssues/issues/735>
  to
  > @dougkdev <https://github.com/dougkdev>.
  >
  > —
  > Reply to this email directly or view it on GitHub
  >
```

https://github.com/FreeUKGen/FreeUKRegProductIssues/issues/735#event-546178967
      > .
      >
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by dougkdev** [comment]
The formatting is correct when the message is sent.  Since you didn't send
the message, I suspect you are concerned that on the "show" page for a
message, the newlines/spacing are not displayed even though they are
actually present (html ignores newlines and multiple spaces when
displaying).  I will change the show page so newlines/spaces are not
ignored when viewing the message contents.

**Comment by dougkdev** [comment]
The message "show" page should now display the message body within a
textarea so that end of lines and spaces are displayed. Deployed to test3.
