### ISSUE TITLE
36433198 General Comment  (Penny)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#737]
Issue reported by **Penny** at 2016-02-26 16:19:58 UTC
Time: 2016-02-26T16:12:01+00:00
Session ID: 
Problem Page URL: []()
Previous Page URL: [http://freereg2.freereg.org.uk/contacts/new](http://freereg2.freereg.org.uk/contacts/new)
Reported Issue:
Today while searching I've found a couple of things different to when I searched a few weeks ago. While searching Somerset, I used to be able to put several villages in at once. Today I can put in only one. The one I put in first is cancelled when I add a second. Also when a village is ticked, it won't untick so another can be searched. Weather it's because I'm using an iPad, I don't know but it didn't used to be like that.
Thanks for a brilliant website. It's much better than the old version
Penny     

![Screenshot](http://www.freereg.org.uk)

**Comment by edickens** [comment]
Penny also says that you cannot deselect a place by clicking on it again so as to be able to select a different one.  This used to work  but does not now.

**Comment by dougkdev** [comment]
I am not able to reproduce the problem- I can select a different place or
select the blank (no place). May be confusion on how the web browser
control works? She doesn't need to click the place again to unselect it
before choosing the new place, just needs to click the new place. If it
really doesn't work for her can we find out what browser and operating
system she is using? Thanks.

**Comment by PatReynolds** [comment]
We took out 'select up to 3 places' as this is covered (better) by ticking
'nearby places' (issue 609, in user testing).

Clicking again on place (or county) does not de-select.  It isn't too much
of a problem with place, as you can click on the blank at the top.  I
thought this was already an issue, but cannot now locate it on the waffle
board.

On 27 February 2016 at 08:17, dougkdev notifications@github.com wrote:

> I am not able to reproduce the problem- I can select a different place or
> select the blank (no place). May be confusion on how the web browser
> control works? She doesn't need to click the place again to unselect it
> before choosing the new place, just needs to click the new place. If it
> really doesn't work for her can we find out what browser and operating
> system she is using? Thanks.
> On Feb 27, 2016 12:56 AM, "Eric Dickens" notifications@github.com wrote:
> 
> > Penny also says that you cannot deselect a place by clicking on it again
> > so as to be able to select a different one. This used to work but does
> > not
> > now.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/FreeUKGen/FreeUKRegProductIssues/issues/737#issuecomment-189603278
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/FreeUKGen/FreeUKRegProductIssues/issues/737#issuecomment-189604380
> .

## 

_\- -_

_Dr Pat Reynolds_
Executive Director
Free UK Genealogy  http://www.freeukgenealogy.org.uk/
A charity registered in England and Wales, number 1096940

​+44 ​1904 541411​ +44 7943 145387

36 Albemarle Road, York, YO23 1ER, UK

**Comment by Captainkirkdawson** [comment]
I do not see this as a bug

**Comment by Captainkirkdawson** [comment]
What is required

**Comment by dougkdev** [comment]
Not a bug.  The first issue is as Pat said, we now tick "nearby places"
instead of selecting up to 3.  The second issue is simply the standard
difference in the way browsers handle multi-select vs single-select.  This
is the standard browser behaviour and not a bug in our system.

**Comment by dougkdev** [comment]
I think the only thing to be done is someone to respond to the user to let
the user know.

**Comment by PatReynolds** [comment]
I'll let Penny know.  Not being able to deselect county as one deselects place remains an issue (#118)

**Comment by PatReynolds** [comment]
Eric, who is Penny?  There is no-one with that ID.

**Comment by edickens** [comment]
```
Hi Pat,

I don't know as I cannot find the original message.  You can look up
by email address if you cannot find a name.

She must have registered otherwise she cannot create this type of
message.  Someone must also have converted it to an Issue.

E

_____________________________________
```

Eric J Dickens
FreeREG Chairman
    On 22/05/2016 17:34, PatReynolds wrote:

```
  Eric, who is Penny? There is no-one with that ID.
  —
    You are receiving this because you commented.
    Reply to this email directly or view
      it on GitHub
```

**Comment by PatReynolds** [comment]
The only information I have is what is here - the name "Penny" which I
assumed was an ID.

_\- -_

_Dr Pat Reynolds_
Executive Director
Free UK Genealogy  http://www.freeukgenealogy.org.uk/
A charity registered in England and Wales, number 1096940.  VAT
registration: 233 0105 70

​+44 ​1904 541411​ +44 7943 145387

36 Albemarle Road, York, YO23 1ER, UK

**Comment by edickens** [comment]
```
Hi Pat,

Because this message is no longer on the server we must assume that
it has been answered.

But I think you are correct that Penny should have been the UserID,
and there is not one.  Just PennyB, PennyC and Pennyh.

Regards,

Eric
_____________________________________
```

Eric J Dickens
FreeREG Chairman
    On 23/05/2016 08:32, PatReynolds wrote:

```
The only information I have is what is here - the name
  "Penny" which I
  assumed was an ID.



  *- -*

  *Dr Pat Reynolds*
  Executive Director
  Free UK Genealogy <http://www.freeukgenealogy.org.uk/>
  A charity registered in England and Wales, number 1096940. VAT
  registration: 233 0105 70

  ​+44 ​1904 541411​ +44 7943 145387

  36 Albemarle Road, York, YO23 1ER, UK

  On 23 May 2016 at 07:57, Eric Dickens
  <notifications@github.com> wrote:

  >
  >
  >
  >
  >
  > Hi Pat,
  >
  > I don't know as I cannot find the original message. You can
  look up
  > by email address if you cannot find a name.
  >
  > She must have registered otherwise she cannot create this
  type of
  > message. Someone must also have converted it to an Issue.
  >
  > E
  >
  > _____________________________________
  > Eric J Dickens
  > FreeREG Chairman
  > On 22/05/2016 17:34, PatReynolds wrote:
  >
  >
  > Eric, who is Penny? There is no-one with that ID.
  > —
  > You are receiving this because you commented.
  > Reply to this email directly or view
  > it on GitHub
  >
  > —
  > You are receiving this because you modified the open/close
  state.
  > Reply to this email directly or view it on GitHub
  >
```

https://github.com/FreeUKGen/FreeUKRegProductIssues/issues/737#issuecomment-220901135
      >
      —
        You are receiving this because you commented.
        Reply to this email directly or view
          it on GitHub

**Comment by Captainkirkdawson** [comment]
The title (subject) tells us that this came in from a researcher not
Feedback from a member

36433198 General Comment (Penny)

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1
