### ISSUE TITLE
36682823 Delete file confirmation has incomplete text (Michael)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#738]
Issue reported by **MikeNL** at 2016-02-29 13:40:23 UTC
Time: 2016-02-29T13:22:58+00:00
Session ID: 9c27c36b53d59f48c6943002c010bee0
Problem Page URL: [/freereg1_csv_files](/freereg1_csv_files)
Previous Page URL: [http://freereg2.freereg.org.uk/csvfiles](http://freereg2.freereg.org.uk/csvfiles)
Reported Issue:
The pop up box that is displayed when trying to delete a file does not make sense.

I think that it should read "Are you sure you want to delete this file? This may take a few minutes if there are many records". I have added the word "are"    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/56d44a47f493fd0f0200081e/Capture.JPG)

**Comment by Captainkirkdawson** [comment]
Done
