### ISSUE TITLE
34125627 Data Problem (Circe Powell)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#740]
Issue reported by **Circe Powell** at 2016-01-30 23:20:27 UTC
Time: 2016-01-30T23:18:25+00:00
Session ID: 
Problem Page URL: [unknown](unknown)
Previous Page URL: [http://www.freereg.org.uk/contacts/56629abff493fd020c0630c2/report_error?query=56ad42cd791e3b65d200138c](http://www.freereg.org.uk/contacts/56629abff493fd020c0630c2/report_error?query=56ad42cd791e3b65d200138c)
Reported Issue:
Year is listed as '08 and I wasn't sure which '08 it related to ie 1808 or1908    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Issue has not been reported again, I suggest it be closed
