### ISSUE TITLE
37383217 Witness Download issues (Alison)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#741]
Issue reported by **AlisonOne** at 2016-03-08 16:13:37 UTC
Time: 2016-03-08T16:02:55+00:00
Session ID: 86e2fd3fa1f808aef80da6d7a6d5ef03
Problem Page URL: [/freereg1_csv_files](/freereg1_csv_files)
Previous Page URL: [http://www.freereg.org.uk/manage_resources/new](http://www.freereg.org.uk/manage_resources/new)
Reported Issue:
1. a witness added online does not get dowloaded. 
2. a file uploaded with Register Type OT gets downloaded as OR. 
You can see the issues by looking at file MLNEDIMA23.csv (AlisonOne), reg_no 143ba, Matthew Combe, Jean Cleghorn. The witness is Alexander Wilson (who was the bride's previous husband). He is there when the file is viewed online, but absent from the downloaded file.    

![Screenshot](http://www.freereg.org.uk)

**Comment by AlOneill** [comment]
Doh! I have replaced file by mistake. So (1) no longer applies to that file. If needed, I will recreate the situation.
