### ISSUE TITLE
38411387 Upload notification (Mick)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#742]
Issue reported by **Mick** at 2016-03-20 13:49:47 UTC
Time: 2016-03-20T13:48:11+00:00
Session ID: 282d82097c79ee2225a2b71c687d16c1
Problem Page URL: [/manage_resources/new](/manage_resources/new)
Previous Page URL: [http://freereg2.freereg.org.uk/refinery/login](http://freereg2.freereg.org.uk/refinery/login)
Reported Issue:
When members of my syndicate are uploading files i'm not receiving any notifications as to whether the files uploaded successfully or not.    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Problem introduced by revised processor issue 728
