### ISSUE TITLE
39428225 Display of reason to make inactive (Eric)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#743]
Issue reported by **REGManager** at 2016-04-01 08:17:05 UTC
Time: 2016-04-01T08:12:47+00:00
Session ID: 950d517fafbd82b3155646d50f80a518
Problem Page URL: [/userid_details/5462b41ee937907d7000050b](/userid_details/5462b41ee937907d7000050b)
Previous Page URL: [http://www.freereg.org.uk/userid_details/5462b41ee937907d7000050b/edit](http://www.freereg.org.uk/userid_details/5462b41ee937907d7000050b/edit)
Reported Issue:
After editing the reason for making inactive, these fields are not displayed.
Also, when first looking at the Profile, can the Skill level be displayed before the reasons to make inactive as it breaks up the set of relevant fields.    

![Screenshot](http://www.freereg.org.uk)

**Comment by PatReynolds** [comment]
One or two issues? I'm guessing that they are development, but putting a bug label on in case.

**Comment by Captainkirkdawson** [comment]
Done in test3
