### ISSUE TITLE
40753986 The online program did not show me that I had uploaded a new file (Pat)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#744]
Issue reported by **FlyInside** at 2016-04-16 16:33:06 UTC
Time: 2016-04-16T16:29:02+00:00
Session ID: eabc50c94a91bfd1ef5f0921b0f26678
Problem Page URL: [/manage_resources/new](/manage_resources/new)
Previous Page URL: [http://www.freereg.org.uk/refinery/login](http://www.freereg.org.uk/refinery/login)
Reported Issue:
I did part of a transcript and uploaded what I had, and the usual page that says "you can close the program, you will receive an email, etc" did not appear, merely the batch page. I checked the "waiting for processing" page and there were no files showing. So I tried it again, and the same occurred. Then I received an email for both of the files, and when I went back into the program, there were two of the same file, one of which I had to delete.    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Fixed
