### ISSUE TITLE
39736207 Guidance for handling missing (blank) information in key fields (Graeme)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#745]
Issue reported by **GDABNOR** at 2016-04-04 21:50:07 UTC
Time: 2016-04-04T21:44:16+00:00
Session ID: eca5e5299f5db2bcbeff9c61729299d9
Problem Page URL: [/information-for-transcribers/entering-data-from-registers](/information-for-transcribers/entering-data-from-registers)
Previous Page URL: [http://freereg2.freereg.org.uk/information-for-transcribers](http://freereg2.freereg.org.uk/information-for-transcribers)
Reported Issue:
Need guidance note concerning entry for:
"A Man Unknown" + variants of this sort    

![Screenshot](http://www.freereg.org.uk)

**Comment by PatReynolds** [comment]
cf #757 - guidance on blanks in this circumstance

**Comment by Captainkirkdawson** [comment]
Is this still relevant @AlOneill

**Comment by AlOneill** [comment]
The guidance for entering names could be described as implied rather than specific: I will make specific.

Dates are covered. Are there other fields that require similar treatment?

**Comment by AlOneill** [comment]
Guidance re Names is now specific for both missing names (leave blank) and register entries for names such as "Unknown" (leave blank, add a note).

See https://www.freereg.org.uk/cms/information-for-transcribers/entering-data-from-registers#names

**Comment by SteveBiggs** [comment]
Checked and good.
