### ISSUE TITLE
41181890 removing empty lines in a batch (Julie)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#749]
Issue reported by **Julie-Harold** at 2016-04-21 15:24:50 UTC
Time: 2016-04-21T15:22:43+00:00
Session ID: fa05bd6ab5a481260d015ad522680ac9
Problem Page URL: [/freereg1_csv_files/5718205af493fd887e000001/error](/freereg1_csv_files/5718205af493fd887e000001/error)
Previous Page URL: [http://freereg2.freereg.org.uk/freereg1_csv_files](http://freereg2.freereg.org.uk/freereg1_csv_files)
Reported Issue:
Now that files are coming up with errors if they have an empty line in a file (ie just place and church but no data), is there anyway we can simply remove those lines online ?  As far as I can see it can only be done by replacing it with a file that has had the line removed.

Julie (Suffolk Coordinator)    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Yes delete the entry

**Comment by Captainkirkdawson** [comment]
We now totally ignore lines without location information
