### ISSUE TITLE
Can't change batch header (Howdy)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#75]
Issue reported by **Howdy** at 2014-11-20 01:27:15 UTC
Time: 2014-11-20T01:23:48+00:00
Session ID: c4004f2cfc519e359a2bfea10d41feeb
Problem Page URL: [/freereg1_csv_files/546388dce9379027822a98d4](/freereg1_csv_files/546388dce9379027822a98d4)
Previous Page URL: [http://test2.freereg.org.uk/freereg1_csv_files/546388dce9379027822a98d4](http://test2.freereg.org.uk/freereg1_csv_files/546388dce9379027822a98d4)
Reported Issue:
Incorrect entry "Carmarten" can't be changed in the associated file (CMNCAEBA50.CSV)    

![Screenshot](http://test2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Invalid. I had turned off edits
