### ISSUE TITLE
41064430 Remove notes from transcriber field until new csv format (Julie)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#750]
Issue reported by **JHarold** at 2016-04-20 06:47:10 UTC
Time: 2016-04-20T06:42:39+00:00
Session ID: a9602feb0e9d4fd9fc37d6997117393f
Problem Page URL: [/search_records/56dbef7af493fd2883000373?search_id=571724ccf493fd42aa0000d3](/search_records/56dbef7af493fd2883000373?search_id=571724ccf493fd42aa0000d3)
Previous Page URL: [http://freereg2.freereg.org.uk/search_queries/571724ccf493fd42aa0000d3](http://freereg2.freereg.org.uk/search_queries/571724ccf493fd42aa0000d3)
Reported Issue:
1837 Robert Tracey marriage Brightlingsea:

the data in the notes from the transcriber field are not showing in this output.  Are they going to be shown at a later date, or do all notes that are displayed need to go in the notes field ?

Julie, 
Essex coordinator    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
EricD wrote
If I enter something in Transcriber's notes, what happens if the Batch is uploaded again, because it cannot have this transcribers note at this time? Will these transcriber's notes be lost, even if this entry is not changed?

**Comment by PatReynolds** [comment]
bug if notes lost.  Otherwise 1.7

**Comment by Captainkirkdawson** [comment]
We can enter on line. They will be displayed if entered.  There is no way to download that information to a csv file with the current format.  If someone update using a current csv formatted file then the transcriber note will be overwritten.
Until we have implemented a flexible csv file format scheme the transcriber notes field should not be used.
Propose to remove from edit in interim
