### ISSUE TITLE
42907271 Auto generated email for Comments (Team)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#752]
Issue reported by **alycymru** at 2016-05-11 14:41:11 UTC
Time: 2016-05-11T14:39:49+00:00
Session ID: f90eae5c5e99c7b9630a9b5b1f0640c0
Problem Page URL: [/manage_counties/select_action?county=Glamorgan](/manage_counties/select_action?county=Glamorgan)
Previous Page URL: [http://www.freereg.org.uk/freereg1_csv_entries](http://www.freereg.org.uk/freereg1_csv_entries)
Reported Issue:
Hi all

Was wondering if we might be able to change the wording of the auto generated email when someone sends us a query?

The line 'Your correspondence has been forwarded to a member of the team for action' does not make a lot of sense when I may be responding with the same thing, to tell them what I am going to do, makes that email or my initial response redundant.

Could we substitute some thing like 'A member of our team will be in touch shortly or in due course'?

That way if I respond I can at least tell them what the action will be or if their query is sorted in a personalised style, or gives the coords who are answering for themselves a bit of time leeway

The line as it stands now implies to me that something will be done, and that is not often the case. Creates a impression that we can always follow. 

We use auto email at my company, and it simply says thank you for writing in and someone will be in touch within X amount of days. And it does help that people don't expect something immediate, nor that action will be taken based on their email contact without fail.

Sandra    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Pat is in favour
