### ISSUE TITLE
42745492 error on transcripts page (Julie)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#753]
Issue reported by **jmh** at 2016-05-09 17:44:52 UTC
Time: 2016-05-09T17:43:49+00:00
Session ID: 7e3a78a9d9341028314cb5ff36ceeaa5
Problem Page URL: [/freereg_contents](/freereg_contents)
Previous Page URL: [http://freereg2.freereg.org.uk/freereg_contents/new](http://freereg2.freereg.org.uk/freereg_contents/new)
Reported Issue:
Trying to look at the transcripts summary for Farnham in Essex, getting this error 

We're sorry, but something went wrong with processing your request. A report has been produced and sent to the webmaster. Please return to your prior activity but try to avoid doing the exact same action again.    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Totally unable to reproduce
