### ISSUE TITLE
43143821 Missing Files (Diana)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#756]
Issue reported by **Dinahst** at 2016-05-14 08:23:41 UTC
Time: 2016-05-14T08:19:12+00:00
Session ID: d1789b6c88d00821cf7e8dcf6bd05c3f
Problem Page URL: [/freereg1_csv_files/selection?option=List+by+uploaded+date+%28descending%29](/freereg1_csv_files/selection?option=List+by+uploaded+date+%28descending%29)
Previous Page URL: [http://freereg2.freereg.org.uk/freereg1_csv_files/my_own](http://freereg2.freereg.org.uk/freereg1_csv_files/my_own)
Reported Issue:
Files KENROMMA16 and KENROMBA21 processed between 5th May and 12 May missing from the list of batches.  Am unable to upload replacement files    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Issue was that all records were rejected as the church name did not match with that on the website
