### ISSUE TITLE
Change the wording of the auto generated contact emailc45227851 Sandra Adams-West (Sandra)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#759]
Issue reported by **CommsCoord** at 2016-06-07 11:17:31 UTC
Time: 2016-06-07T11:11:58+00:00
Session ID: f7866fbd8d8a5afd5659791a8982c659
Problem Page URL: [/manage_resources/new](/manage_resources/new)
Previous Page URL: [https://www.freereg.org.uk/refinery/login](https://www.freereg.org.uk/refinery/login)
Reported Issue:
Need to change the wording of the auto generated contact email for volunteering needs to be changed in the first and second paragraph to say:  (1st paragraph) Thank you for your kind offer to volunteer with FreeREG and (2nd) A member of staff should be in touch within two business days.    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Finally done
