### ISSUE TITLE
46945854 "Processed" emails (Michael)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#763]
Issue reported by **MikeNL** at 2016-06-27 08:30:54 UTC
Time: 2016-06-27T08:29:40+00:00
Session ID: bb88a8cf96a3fdcf2e8da5c354e2d0dc
Problem Page URL: [/manage_resources/new](/manage_resources/new)
Previous Page URL: [http://freereg2.freereg.org.uk/refinery/login](http://freereg2.freereg.org.uk/refinery/login)
Reported Issue:
As a coordinator, I receive many emails per day detailing that a transcriber's file has been processed. BUT I have to open the email to see if the processing produced any errors or was successful.

Would it be possible to include something like "with errors" in the Subject line of the email, giving a message like:
derekg/STSSEDBU8.CSV was processed with errors by FreeReg at 2016-06-26 03:46:39 +0100

If this change is made, it would mean that I don't have to open EVERY "processed" email, but just those with errors.

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
See also 765

**Comment by Captainkirkdawson** [comment]
Added number  records
