### ISSUE TITLE
47249626 Add Date of Death to burial record

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#764]
Issue reported by **Newlady** at 2016-06-30 20:53:46 UTC
Time: 2016-06-30T20:50:48+00:00
Session ID: 43fd015f9ea97239a224162e45a5dc05
Problem Page URL: [/manage_resources/new](/manage_resources/new)
Previous Page URL: [http://www.freereg.org.uk/freereg1_csv_files/my_own](http://www.freereg.org.uk/freereg1_csv_files/my_own)
Reported Issue:
I have found that much non church information contains death dates in lieu/addition to internment dates.  BUT there is no column for date of death in the burial format.
Could you please add one?
Thanks.    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
This is part of #809

**Comment by Captainkirkdawson** [comment]
@SteveBiggs can you check we have this in the list of new fields in #809. If so we can close this story

**Comment by SteveBiggs** [comment]
Yes we have this.
