### ISSUE TITLE
47216822 Date range of file (Ali)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#765]
Issue reported by **alsibk** at 2016-06-30 11:47:02 UTC
Time: 2016-06-30T11:33:56+00:00
Session ID: 81ba67e803d9026aa8ba9db3d2c3fddd
Problem Page URL: [/freereg1_csv_files/5774d0f8f493fda6f7000001](/freereg1_csv_files/5774d0f8f493fda6f7000001)
Previous Page URL: [http://www.freereg.org.uk/registers/569f440bf493fd57c9000003](http://www.freereg.org.uk/registers/569f440bf493fd57c9000003)
Reported Issue:
Please would it be possible to include in the file processed email the date range of the file in question?     

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
See also 763

**Comment by Captainkirkdawson** [comment]
Added date range. NOTE THIS INFORMATION MAY BE MISLEADING IF FILE CONTAINS MORE THAN ONE BATCH
