### ISSUE TITLE
47520500 Downloading a file adds +LDS line in header (Michael)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#768]
Issue reported by **MikeNL** at 2016-07-04 00:08:20 UTC
Time: 2016-07-03T23:57:47+00:00
Session ID: 5ad1f6bcf4e9403d5e491258eb9f4e7e
Problem Page URL: [/freereg1_csv_files/5774697af493fdcba0000001](/freereg1_csv_files/5774697af493fdcba0000001)
Previous Page URL: [http://freereg2.freereg.org.uk/registers/57631a79f493fdee2a00094e](http://freereg2.freereg.org.uk/registers/57631a79f493fdee2a00094e)
Reported Issue:
Recently I have needed to download a file that had no "Image numbers available with record". I thought that this meant that the +LDS line in the file header was NOT in the file. So +LDS means "Image numbers available with record" is Yes. Now, even when the "Image numbers available with record" is No, the downloaded file has +LDS in the file header.     

![Screenshot](http://www.freereg.org.uk)

**Comment by PatReynolds** [comment]
Labeled as bug but may be communication/training

**Comment by edickens** [comment]
Adding the +LDS line when there are no Film/Image numbers does not
    matter.  The problem is the other way round, in that you cannot have
    film/image numbers without the +LDS line.  So putting it in every
    time is the easiest option and will ensure that everything in the
    batch is downloaded.  E

**Comment by Captainkirkdawson** [comment]
Problem fixed

**Comment by Captainkirkdawson** [comment]
Problem fixed while looking at another issue
