### ISSUE TITLE
48755092 Wrong messages from Freereg registration (Ali)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#769]
Issue reported by **alsibk** at 2016-07-18 07:04:52 UTC
Time: 2016-07-18T07:01:39+00:00
Session ID: ffad90de3556abf8a00375322c7393ce
Problem Page URL: [/manage_resources/new](/manage_resources/new)
Previous Page URL: [http://www.freereg.org.uk/refinery/login](http://www.freereg.org.uk/refinery/login)
Reported Issue:
EG-----I edit an existing transcriber's profile and receive a message stating that he/she has been 

"re-assigned to your syndicate.

Please make them welcome"    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Fixed in mongoid5 branch; awaiting deployment

**Comment by PatReynolds** [comment]
See also #841
