### ISSUE TITLE
Content of "Contents" file (Howdy)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#77]
Issue reported by **Howdy** at 2014-11-22 01:49:52 UTC
Time: 2014-11-22T01:46:05+00:00
Session ID: b800a85e1cf412a82266bc259c3f8c56
Problem Page URL: [/freereg_contents/5407f1f3eca9eb1ee04c77a7/show_church](/freereg_contents/5407f1f3eca9eb1ee04c77a7/show_church)
Previous Page URL: [http://test2.freereg.org.uk/freereg_contents/Brecknockshire/show](http://test2.freereg.org.uk/freereg_contents/Brecknockshire/show)
Reported Issue:
All (?) files in AGY & ?

I don't see that the present screen presents the promised information.  There is no indication of which rites have documentation and there are no date ranges.

![Screenshot](http://test2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
"which rites" not sure what you mean.

I think you may have a point about needing to provide more info at the higher levels. It is there at the register level.

Interestingly these pages have been showing the same information without comment for the past year.

But that does not mean your comments are not valid I think they are,

**Comment by Captainkirkdawson** [comment]
Additional fields have been added that have the number and year range of transcriptions
