### ISSUE TITLE
48868715 Failure to display complete witness name in a marriage search (Mick)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#770]
Issue reported by **Mick** at 2016-07-19 14:38:35 UTC
Time: 2016-07-19T14:33:34+00:00
Session ID: 0d57adde62adad862a500595341503c9
Problem Page URL: [/manage_resources/new](/manage_resources/new)
Previous Page URL: [http://freereg2.freereg.org.uk/refinery/login](http://freereg2.freereg.org.uk/refinery/login)
Reported Issue:
If the witness has only one Christian name, the full name is returned  correctly.
However if the witness has two (or more) Christian names then the Christian names are returned in the search but the surname is ignored.

I have checked a few files on the server itself and the files that should contain two christian names and the surname are only showing the christian names.
I have uploaded a file where there are witnesses with more than one christian name and when i view this file on the server again the christian names are there but the surname has been ignored.

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/578e3b6bf493fdb12e000015/Kirton_marriage.JPG)

**Comment by Captainkirkdawson** [comment]
Specific example needs to be provided

**Comment by Captainkirkdawson** [comment]
My tests do not support issue.
![multiple](https://cloud.githubusercontent.com/assets/2874694/17458436/60b71904-5bcd-11e6-9bf3-70b3a4419a0d.JPG)

**Comment by edickens** [comment]
So has it been fixed by Ben?
Mick gave me this example today:-
As an example the marriage of Alice ANDERSON, Kirton in Holland, Lincolnshire on 01 Mar 1923. The witnesses were Annie Elizabeth PEARSON and Lawrence Frederic BIRD. A website search returns the witnesses as Annie Elizabeth and Lawrence Frederic, their surnames are completely ignored.

**Comment by Captainkirkdawson** [comment]
Confirm there is an issue with an example provided

**Comment by Captainkirkdawson** [comment]
Witness surnames has been incorrectly extracted from entry when creating multiple witness embedded collection entry when there are multiple forenames.
freereg2:PRIMARY> db.freereg1_csv_entries.find({_id: ObjectId("55141335e937902a2901d57c")})
{ "_id" : ObjectId("55141335e937902a2901d57c"), "error_flag" : "false", "line_id" : "PhilOsbourn.LINKIRMA2.CSV.2", "file_line_number" : 2, "register_entry_number" : "380", "marriage_date" : "01 Mar 1923", "year" : "1923", "groom_forename" : "John Charles", "groom_surname" : "BIRD", "groom_age" : "23", "groom_parish" : null, "groom_condition" : "bachelor", "groom_occupation" : "*", "groom_abode" : "Kirton", "bride_forename" : "Alice", "bride_surname" : "ANDERSON", "bride_age" : "25", "bride_parish" : null, "bride_condition" : "spinster", "bride_occupation" : null, "bride_abode" : "Kirton", "groom_father_forename" : "Joseph", "groom_father_surname" : "BIRD", "groom_father_occupation" : "Platelayer", "bride_father_forename" : "William", "bride_father_surname" : "ANDERSON", "bride_father_occupation" : "Farm Labourer", "witness1_forename" : "Annie Elizabeth", "witness1_surname" : "PEARSON", "witness2_forename" : "Lawrence Frederic", "witness2_surname" : "BIRD", "notes" : null, "county" : "LIN", "place" : "Kirton in Holland", "church_name" : "St Peter and St Paul", "register_type" : " ", "record_type" : "ma", "freereg1_csv_file_id" : ObjectId("580f1e4df493fd7abae03220"), "u_at" : ISODate("2016-10-25T08:56:47.260Z"), "c_at" : ISODate("2015-03-26T14:09:57.204Z"), "multiple_witnesses" : [ { "_id" : ObjectId("55f14d80f493fd8f0e273c16"), "witness_forename" : "Annie", "witness_surname" : "Elizabeth" }, { "_id" : ObjectId("55f14d80f493fd8f0e273c17"), "witness_forename" : "Lawrence", "witness_surname" : "Frederic" } ], "record_digest" : "jXpfCgR8DjmaOSH27Mx5yw==" }

**Comment by Captainkirkdawson** [comment]
I can see no reason for this to happen

**Comment by edickens** [comment]
It doesn't happen now.  Close.  E
