### ISSUE TITLE
48950976 Last amended date not correct (Ali)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#771]
Issue reported by **alsibk** at 2016-07-20 13:29:36 UTC
Time: 2016-07-20T13:25:22+00:00
Session ID: 27d59565259872e8bd8ae27a28fb61f2
Problem Page URL: [/manage_resources/new](/manage_resources/new)
Previous Page URL: [http://www.freereg.org.uk/refinery/login](http://www.freereg.org.uk/refinery/login)
Reported Issue:
Added data is not triggering an update in last recorded date of change in files.

![Screenshot](http://www.freereg.org.uk)

**Comment by suffolkroots** [comment]
Example---Last addition of processed data for Alverthorpe WRY was 9 Aug 2016.
Information about the Register itself states Last changed 28 Jul 2016.

**Comment by Sherlock21** [comment]
Online Correction of a Year in a date ( is shown as 2 May 1854 and was corrected to 2 May 1654) does not shift the count from the decadel 1850 - 1859 to add into the correct decadel (1650-1659) as it should .

**Comment by Captainkirkdawson** [comment]
Please tell  us what batch you adjusted. The decadal recalculations are usually done overnight as the work to recompute all batches for all churches in some large places is a big undertaking

**Comment by Sherlock21** [comment]
It was one of the WRYSED files of by own.

I have checked this morning and yes, the there are now NO out of sync count - so the 0 start year and the 1854 >1654 correction on line has been picked up.

I did not know that part of the process was down overnight - I had expected the correction to ripple through there and then.
Perhaps everyone else will also expect it top work the same as I did?

so close this one not thanks.?

**Comment by PatReynolds** [comment]
Users need to know that changes are not reflected instantaneously - done offline, overnight.

**Comment by Captainkirkdawson** [comment]
Coordinator is complaining that the date of amendment is not being updated not that the changes to data are not reflected. 
Given complexity of calculations; this will only be calculated and updated daily and will not ripple through to register/ church and place instantaneously.

**Comment by richpomfret** [comment]
Alison to review/update documentation if required.

**Comment by AlOneill** [comment]
Done:
http://www.freereg.org.uk/cms/information-for-transcribers/file-and-batch-actions#edit
