### ISSUE TITLE
49098375 Search Navigation General Comment  (shirley elrick)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#773]
Issue reported by **shirley elrick** at 2016-07-22 06:26:15 UTC
Time: 2016-07-22T06:13:18+00:00
Session ID: 
Problem Page URL: []()
Previous Page URL: [http://freereg2.freereg.org.uk/contacts/new](http://freereg2.freereg.org.uk/contacts/new)
Reported Issue:
Feedback.  There is an 'annoyance' in the search process flow. This comment is meant as an aid to you when you are considering what to change - not as blatant criticism.  I use Firefox, latest version available, on windows 7.

After a search completes I click on any result to see the details.  The only way that I can get back to the list of hits is to use the back arrow.  This I am more than comfortable with.

However, to get back to the search page I have to use the Revise Search button.  The back arrow does take me back to the search page, and it allows me to change the data in the search fields, but then pressing enter or clicking the on SEARCH button does nothing.  There is NO error message. This appears to be counter productive.  

If I HAVE to use the back arrow to move one page back on some pages, I would expect the process to allow me to use it again to move one more page back.

OR

The back arrow should be made none functional on all pages, and a similar method of returning to previous page be used on all pages

Regardless of what you decide, I would much prefer a function that is NOT going to work be made immediately obvious.  i.e. not allow me to update the search data fields if the search button is disabled because I used the back arrow to get to the page.

Thanks for all the good work - shirley    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
After a search completes I click on any result to see the details. The only way that I can get back to the list of hits is to use the back arrow. This I am more than comfortable with.

This statement is incorrect. The search result details page provides for navigation that is independent of the back button.  These links were developed to assist people navigate correctly around the site. 

We strongly recommend avoidance of the back button. If a user does they need to use the left button click of the back button to select the page they wish to go back to.
![search1](https://cloud.githubusercontent.com/assets/2874694/17458249/285bf146-5bc9-11e6-8476-a8933fd8230e.JPG)
