### ISSUE TITLE
49038765 Inconsistent number of errors (Barrie)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#774]
Issue reported by **brobinson43** at 2016-07-21 13:52:45 UTC
Time: 2016-07-21T13:49:37+00:00
Session ID: d37934e93e88f56a446c819ea0bbc79e
Problem Page URL: [/freereg1_csv_files/5790d08ef493fd77f9000001](/freereg1_csv_files/5790d08ef493fd77f9000001)
Previous Page URL: [http://freereg2.freereg.org.uk/freereg1_csv_files/my_own](http://freereg2.freereg.org.uk/freereg1_csv_files/my_own)
Reported Issue:
My batch had errors (two I was informed of and corrected.) Batch NTHSTDBU2.CSV. ER says file has no errors, but SH continues to show number of errors = 1 (but also says there are no errors when I click on Listing of Errors in Batch.)
Even after I logged out ands then logged back in. Which am I supposed to believe?    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Issue no longer apparent. Barrie reports he is not experiencing the issue. It appears to have been caused by editing a batch on-line while a  replaced version  was  waiting to be processed. See #970
