### ISSUE TITLE
49188177 "Ad" (Stuart)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#775]
Issue reported by **vk3dwu** at 2016-07-23 07:22:57 UTC
Time: 2016-07-23T01:01:16+00:00
Session ID: 1e9d8d46b19bd28d87273a9a5d7274b0
Problem Page URL: [/freereg1_csv_files/my_own](/freereg1_csv_files/my_own)
Previous Page URL: [http://freereg2.freereg.org.uk/freereg1_csv_files/selection?option=List+files+waiting+to+be+processed](http://freereg2.freereg.org.uk/freereg1_csv_files/selection?option=List+files+waiting+to+be+processed)
Reported Issue:
When I logged in to FreeReg, an ad from tweakbit.com popped up telling me that I may need to fix WIndows errors.  It wanted me to scan my PC and fix errors.  Some of these so called error fixers are highly dangerous malware and to be avoided at all costs.  Does anyone vet ads posted on the FreeUKGenealogy sites?  Ads for software such as operating system and performance fixers should not be allowed unless that software has been carefully vetted by FreeUKGenealogy.  If no-one is presently monitoring these ads, then someone needs to in order to protect our more gullible members.    

![Screenshot](http://www.freereg.org.uk)

**Comment by PatReynolds** [comment]
Have reported violation to Google, blocked site, and informed reporter.
