### ISSUE TITLE
49889191 Why is transcriber's email address changed? (Sandra)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#776]
Issue reported by **CommsCoord** at 2016-07-31 10:06:31 UTC
Time: 2016-07-31T10:04:40+00:00
Session ID: 8cdc8f6ca4e6afc8745f668ac4964cc3
Problem Page URL: [/manage_resources/new](/manage_resources/new)
Previous Page URL: [http://www.freereg.org.uk/contacts](http://www.freereg.org.uk/contacts)
Reported Issue:
A coordinator submitted a file that contained their personal email address in the "Transcribers email address". The same address was also put into the "Email address for the person who has been credited". When they looked at the file as CC they see that (a) "Transcribers email address" is their CC email address - not their personal one and (b) the "Email address for the person who has been credited" has been blanked out.    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Unsure what is being requested here.

I do not know why a CC is changing file header contents in the first place.

email addresses  in header are not being blanked out.
