### ISSUE TITLE
49923491 Testing on test3 (Kirk)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#778]
Issue reported by **Captainkirk** at 2016-07-31 19:38:11 UTC
Time: 2016-07-31T19:37:38+00:00
Session ID: ea130165d166807d830cd5ae2f104ac9
Problem Page URL: [/search_queries/579e5382e937903851549614](/search_queries/579e5382e937903851549614)
Previous Page URL: [https://test3.freereg.org.uk/search_queries/new](https://test3.freereg.org.uk/search_queries/new)
Reported Issue:
aaaaaaaaaaaaaaa    

![Screenshot](http://test3.freereg.org.uk/uploads/feedback/screenshot/579e53a3e937903851549616/Kirk.jpg)

**Comment by Sherlock21** [comment]
What a smart guy!

**Comment by benwbrum** [comment]
"aaaaaaaaaaaaa" indeed!
