### ISSUE TITLE
50054032 "email address of person being credited" is lost (Michael)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#779]
Issue reported by **MikeNL** at 2016-08-02 07:53:52 UTC
Time: 2016-08-02T07:49:46+00:00
Session ID: 17665e791935b551fb00574c831d8d46
Problem Page URL: [/freereg1_csv_files/579d591ef493fd57eb00a73f](/freereg1_csv_files/579d591ef493fd57eb00a73f)
Previous Page URL: [http://freereg2.freereg.org.uk/registers/54081af9eca9eb0248aef2fe](http://freereg2.freereg.org.uk/registers/54081af9eca9eb0248aef2fe)
Reported Issue:
Recently, I have noticed that the "email address of person being credited" is being blanked out when looking at a file header in CC mode.

Although the file had this email address when submitted, for some strange reason it is not displayed.    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Unable to duplicate

The email address displays and the code is common for all users.
![email](https://cloud.githubusercontent.com/assets/2874694/17457923/09dd708e-5bc2-11e6-8e4f-db07f9e78d4f.JPG)

**Comment by edickens** [comment]
I think the problem is that transcribers do not put this information in 
the correct header field.  E

**Comment by Sherlock21** [comment]
I Agree with you, Eric D

I have asked before that somewhere simple and easy, we put up a CURRENT usage of the header fields, what goes in which and What the entry is then used for.
SO everyone can read it.

**Comment by Captainkirkdawson** [comment]
The header structure remains totally unchanged from what it has been for 20 years and it is included in the Information for Transcribers

**Comment by edickens** [comment]
```
Hi Kirk,

That is correct, but it is not specified (as far as I know) which
fields are for internal use in FR, which are ignored, and which are
shown to researchers.

E
```

**Comment by Captainkirkdawson** [comment]
Is it not time that you read the excellent documentation written by Alison!

**Comment by edickens** [comment]
```
Touché.  Yes Alison's Help is excellent and so well written.

But I do find that the Help is not quick to find an answer.  It is
very good for first time users.  There is not a "Search" for a word,
nor FAQ.  Also, it is not obvious, because of the text colour, which
words have links to other pages.

E

On 07/08/2016 17:57, Kirk Dawson wrote:

  Is it not time that you read the excellent documentation
    written by Alison!
  —
    You are receiving this because you commented.
    Reply to this email directly, view
      it on GitHub, or mute
      the thread.







  {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/FreeUKGen/FreeUKRegProductIssues","title":"FreeUKGen/FreeUKRegProductIssues","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/modules/aws/aws-bg.jpg","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/FreeUKGen/FreeUKRegProductIssues"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Captainkirkdawson in #779: Is it not time that you read the excellent documentation written by Alison!"}],"action":{"name":"View Issue","url":"https://github.com/FreeUKGen/FreeUKRegProductIssues/issues/779#issuecomment-238093877"}}}
```

**Comment by Sherlock21** [comment]
You are right,Eric D

I followed up Kirk’s advice of today on #779 to read the Information for Transcribers to see that is in the Header fields.

Can I  Find it? can I ****

EB

**Comment by Captainkirkdawson** [comment]
http://www.freereg.org.uk/information-for-transcribers/file-headers

**Comment by Sherlock21** [comment]
Kirk:

Thank you.
