### ISSUE TITLE
50575120 Field sequence on Edit Record not the same as Show Record (Michael)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#781]
Issue reported by **MikeNL** at 2016-08-08 08:38:40 UTC
Time: 2016-08-08T08:36:11+00:00
Session ID: ea16673bfea1e17723d3018c8af47812
Problem Page URL: [/freereg1_csv_entries/57a81ee3f493fd3802020d16](/freereg1_csv_entries/57a81ee3f493fd3802020d16)
Previous Page URL: [http://freereg2.freereg.org.uk/freereg1_csv_entries/57a81ee3f493fd3802020d16/edit](http://freereg2.freereg.org.uk/freereg1_csv_entries/57a81ee3f493fd3802020d16/edit)
Reported Issue:
Because the field sequences on Edit and Show records (certainly for Burials) are different, it can be difficult to transfer data from one record to another.    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
It is certainly true that the sequence may be different.  They are very different pages that serve very different  functions. Are there many fields that are likely to be common between 2 entries that make this important??

**Comment by ghost** [comment]
No further commentary on subject. Closing
