### ISSUE TITLE
51475320 Testing report (Stephen)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#782]
Issue reported by **steveroland** at 2016-08-18 18:42:00 UTC
Time: 2016-08-18T18:41:03+00:00
Session ID: bcbba69466f242ffcddadd917aafbefc
Problem Page URL: [/manage_resources/new](/manage_resources/new)
Previous Page URL: [http://test3.freereg.org.uk/cms/refinery/login](http://test3.freereg.org.uk/cms/refinery/login)
Reported Issue:
This is a test.    

![Screenshot](http://test3.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Just a test to see if conversion to github worked

**Comment by Sherlock21** [comment]
K

I did not get a message out of Github ( as this one is from Stephen’s test.)

Should i have got a similar one for Steve Biggs and for my own?

EB
