### ISSUE TITLE
51529912 Search facility reaches limits too easily (Eric)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#783]
Issue reported by **ericb** at 2016-08-19 09:51:52 UTC
Time: 2016-08-19T09:48:11+00:00
Session ID: 6ef087da324cf937315c1c1c60c4844d
Problem Page URL: [/manage_resources/new](/manage_resources/new)
Previous Page URL: [http://www.freereg.org.uk/cms/refinery/users/login](http://www.freereg.org.uk/cms/refinery/users/login)
Reported Issue:
A search for WRY/ Dewsbury/ 1800-1800/ Baptisms
for ( say) John Greenwood reaches the new limit and stops.

SO no chance of adding in Nearby.    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Have extended the limit from 5 to 15 seconds. Also added a logging of those searches that reach the limit

**Comment by Captainkirkdawson** [comment]
Will analyze a days performance at this level

**Comment by Sherlock21** [comment]
I will do a few tests now.
they will all be in WRY so you stand a chance of knowing they were mine.
All the rest will be genuine public.

**Comment by Sherlock21** [comment]
This seems to be a reasonable limit now.

with a common Yorkshire surname and All WRY, and 1500 - 1800 date range -  we reach the old 250 records limit for burials and Baptisms.
trimming back on the Year range easily overcomes the problem

As a quick test, it seems a reasonable  time limit figure now - as I reached the Number limit of 250 a few times, but never reached the time limit.
-end of testing.

**Comment by Captainkirkdawson** [comment]
The average search time is now 2.1 Sec (with a 5 sec limit it had been 1.6. and with no limit it had been 3.6 sec with maximums of 900 seconds)

**Comment by helhyde** [comment]
Reading emails backwards, see that it isn't a timing problem (or rather,
some searches seem to be taking longer than typical)?

**Comment by Captainkirkdawson** [comment]
Please see #765 Features

**Comment by Captainkirkdawson** [comment]
Placed the following o the search page.
Since our update of earlier this week we have been receiving comments about searches reaching their time limit. This is a new limit and was introduced to stop long running searches that were occurring under the previous system. At 7pm BST we have increased the limit to 30 seconds from 15 seconds. If you continue to experience hitting this limit please review your search criteria. Searches limited to specific places will rarely experience issues. Adding a date range will often CAUSE you to hit the limit because of the number of records that have to be reviewed.

**Comment by Captainkirkdawson** [comment]
With the time limit set at 15 seconds then 15% of searches were reaching limit

**Comment by Captainkirkdawson** [comment]
At the current limit of 30 seconds we are limiting 6 % of the searches (94). 
Average search time is 3.5 sec and server performance looks good
While all search indexes are limiting searches some more than others

county_ln_sd    29
county_lnsdx_fnsdx_sd   20
county_fn_ln_sd 10
ln_rt_fn_sd 9
lnsdx_rt_fnsdx_sd   7
place_ln_fn_sd  7
place_lnsdx_sd  5
place_ln_sd 4
place_fnsdx_lnsdx_sd    3

Propose to increase limit to 50 seconds unless I hear counter views

**Comment by Captainkirkdawson** [comment]
With the limit set to 50 seconds there are 1% of the searches hitting the limit. The average search time remains at 3.5 seconds.
#765 Features remains the fundamental issue for long running searches and is counter intuitive for the user

**Comment by Captainkirkdawson** [comment]
#756 Features is causing an increase in limit hits
10% of searches are limiting on colobus with only 2% limiting on slaves

**Comment by Captainkirkdawson** [comment]
Interesting. The number of COMPLETED daily searches has increased since we implemented the limit

**Comment by suffolkroots** [comment]
Kirk said  #765 remains the fundamental issue for long running searches and is counter intuitive for the user

How, please? Adding date range of processed file to info email for CC/SC and transcriber is counter intuitive?

**Comment by edickens** [comment]
Perhaps people are putting in sensible criteria now.  It is possible
    to just enter a name and it will search everywhere and create a slow
    search.  As soon as you enter a year range, or county, it should
    reduce the search time and so produce a completed search.  E

**Comment by Captainkirkdawson** [comment]
Do not understand your question suffolkroots. Please email me directly

**Comment by Captainkirkdawson** [comment]
The comment made by suffolkroots was related to there being two 765s; one Features and 1 issues. This problem is related to the 765 Features. It has no relationship to 765 Issues which is a very different story

**Comment by Sherlock21** [comment]
How on earth do 2 totally different stories get the same number please?

viz: 765 and 783

**Comment by Sherlock21** [comment]
Picking up on Eric Dickens 4 comments above here, why should adding a realistic date range to a search, cause a longer search time? It seems counter intuitive to me.

Surley, adding a date range is the obvious thing a user will do, when told to narrow down his search, when the first attempt reaches the time out limit?

**Comment by Captainkirkdawson** [comment]
Because 1 came in as an issue and the other as a feedback through the reporting systems

**Comment by Captainkirkdawson** [comment]
As we said it is counter intuitive

If you search without dates it works solely with an index

If you add a date band it reads the documents to see if they meet the criteria. 

It does this because our date field is an array and we already have name an array and you cannot index 2 different array fields Hence the need to fix that issue

**Comment by FreeUKGenIssues** [comment]
The date search performance issue has been planned for the sprint ending
September 7.  I'm unavailable for most of the upcoming week, but it's my
top priority once I'm back at the coal front.
