### ISSUE TITLE
51798692 password problems (Edwin)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#785]
Issue reported by **14247** at 2016-08-22 12:31:32 UTC
Time: 2016-08-22T12:27:49+00:00
Session ID: 8820de9a0120837b833e6723f5d496bb
Problem Page URL: [/freereg1_csv_files/display_my_own_files_waiting_to_be_processed](/freereg1_csv_files/display_my_own_files_waiting_to_be_processed)
Previous Page URL: [http://www.freereg.org.uk/freereg1_csv_files/my_own](http://www.freereg.org.uk/freereg1_csv_files/my_own)
Reported Issue:
Today and a recent previous occasion I have had problems logging in. It seemed to not recognise my password. The last time about the fourth go it decided it would work. Today I had the same problem. I decided to change my password. I tried several times to do this but it seems it would not remember it. Eventually I tried my old password again and it worked. Something wrong here!    

![Screenshot](http://www.freereg.org.uk)

**Comment by edickens** [comment]
We think a time out problem, but seems OK now.  Suggest that this is Closed.
