### ISSUE TITLE
51984460 Time out now appears to be set too long (W Hazel Dickinson)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#786]
Issue reported by **W Hazel Dickinson** at 2016-08-24 16:07:40 UTC
Time: 2016-08-24T16:05:45+00:00
Session ID: d9711c15d1118d1a5795aa8d64ccf776
Problem Page URL: []()
Previous Page URL: [http://www.freereg.org.uk/contacts/new](http://www.freereg.org.uk/contacts/new)
Reported Issue:
I don't mind the time-out feature in principle.  However, after the first time-out and a change in the search criteria, the second search goes on and on and on and on ,,,,  Neither results nor the opportunity to change the search criteria yet again.
Am I just unlucky?  Or is this a common occurrence now?    

![Screenshot](http://www.freereg.org.uk)

**Comment by ghost** [comment]
No further commentary from originator. Closing down
