### ISSUE TITLE
52070581 Enhancement Suggestion (John Gauss)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#787]
Issue reported by **John Gauss** at 2016-08-25 16:03:01 UTC
Time: 2016-08-25T16:00:56+00:00
Session ID: 05c89de6dda80e2d6e8310c37952d8a6
Problem Page URL: []()
Previous Page URL: [http://www.freereg.org.uk/contacts/new](http://www.freereg.org.uk/contacts/new)
Reported Issue:
Of course I’m very grateful for all the volunteer effort that goes into these indexes, but then there’s always an additional feature I’d like!

When I do a search and don’t find the expected entry, I want to know why.  Apart from using the wrong search strategy the most likely reason is that the parish/event/date range has not been indexed.  Although I can look up the parish and check, it can be tedious if I also want to check neighbouring parishes.

So, my suggestion is for county parish maps for each of baptisms, marriages and burials with the parishes coloured in, say, bright red to indicate completely indexed, and lighter shades of red to white if only some years or none have been indexed.  Then one could see at a glance which parishes might need to be checked in some other way.

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
We do have plans for an enhancement that provides additional information on why the search might not have found the record. Places in our list of place names all have data. Completeness and gaps are different matters. We are actively looking at this matter but it will likely be 6 months

**Comment by Captainkirkdawson** [comment]
Since this is part of the GAP  story 123 we should likely close this after telling user
