### ISSUE TITLE
52143257 System moved me to another user login (Mick)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#789]
Issue reported by **Mick** at 2016-08-26 12:14:17 UTC
Time: 2016-08-26T12:08:47+00:00
Session ID: 4966174cd961624e6af319e11d8ec1d2
Problem Page URL: [/manage_counties/select_action](/manage_counties/select_action)
Previous Page URL: [http://www.freereg.org.uk/manage_counties/new](http://www.freereg.org.uk/manage_counties/new)
Reported Issue:
I was logged in as steveroland doing coord work and when finished left it logged in. A few hours later I went back to the browser and clicked 'Actions' and then 'Manage counties' and the system seems to have bumped to be logged in as a different user - "Mick".    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/57c03299f493fd395d788129/Capture.jpg)

**Comment by Captainkirkdawson** [comment]
An inactive member neds to be logged out and session cleared after a period of time

**Comment by edickens** [comment]
```
FR1 used to log you out after I think an hour of inactivity.  A good
idea.  E
```

**Comment by Captainkirkdawson** [comment]
In meantime members should be encouraged to logout at the end of a session

This is a major issue if a system administrator doe NOT log out

**Comment by benwbrum** [comment]
We need to get to the bottom of the underlying security/session issue.

1) Has anyone else reported being logged in as another user?
2) Do we have any guess how to duplicate this?

Ben

**Comment by Captainkirkdawson** [comment]
We have had a few reports of other issues that clearly link back to the same basic issue.

Have no ability to reproduce and never experienced it myself. BUT i always log out at the end of a session!

I have changed to lifetime for a session cookie from 2 days to 30 minutes. I have introduced the :timeoutable method of devise and set that to 10 minutes.  This gives a maximum inactive session time of 40 minutes after which the user must relog in to continue as a member.  I believe the issue revolves around was was a totally unreasonable session cookie lifetime.

Has been checked on test3 and will deploy later today to production.

It is a shot in the dark but will continue to monitor

**Comment by Captainkirkdawson** [comment]
Issue detected and solution applied.

**Comment by helhyde** [comment]
Splendid!

_\- -_

_Dr Pat Reynolds_
Executive Director
Free UK Genealogy  http://www.freeukgenealogy.org.uk/
A charity registered in England and Wales, number 1096940, transitioning to
a Charitable Incorporated Organisation registered in England and Wales,
number 1167484
VAT registration: 233 0105 70

​+44 ​1904 541411​ +44 7943 145387

36 Albemarle Road, York, YO23 1ER, UK
