### ISSUE TITLE
52300729 Website Problem (Julie Harold (Essex Coordinator))

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#790]
Issue reported by **Julie Harold (Essex Coordinator)** at 2016-08-28 07:58:49 UTC
Time: 2016-08-28T07:56:54+00:00
Session ID: 623d9cbf98f97306656cf3ca58a231db
Problem Page URL: []()
Previous Page URL: [http://www.freereg.org.uk/contacts/new](http://www.freereg.org.uk/contacts/new)
Reported Issue:
Selected transcriptions and Essex, and got this message - the change you wanted was rejected.    

![Screenshot](http://www.freereg.org.uk/uploads/contact/screenshot/57c299b9f493fd6eabd528a8/snip.jpg)

**Comment by Captainkirkdawson** [comment]
See #789
