### ISSUE TITLE
52648530 CC and SC Actions are not correct (Eric)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#794]
Issue reported by **EricD** at 2016-09-01 08:35:30 UTC
Time: 2016-09-01T08:30:29+00:00
Session ID: 1446c2c7a93e8365779abb513d45eca1
Problem Page URL: [/manage_resources/new](/manage_resources/new)
Previous Page URL: [http://test3.freereg.org.uk/cms/refinery/login](http://test3.freereg.org.uk/cms/refinery/login)
Reported Issue:
In Test3 I have logged in as EricD (Role in FR is CC) and got the attached list of Actions.  Profile is not there.  Manage Syndicate is there.  Steve Biggs, SC and CC, is also having problems as he does not have all the Actions he needs.    

![Screenshot](http://test3.freereg.org.uk/uploads/feedback/screenshot/57c7e852e937904a18a361e2/Capture.JPG)

**Comment by PatReynolds** [comment]
Possibly related to #789?  This is what happened when I was logged in as me, but by 'manage profile' was the Comms Coord.
