### ISSUE TITLE
52960765 Nothing Listed for London City (Kyran)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#797]
Issue reported by **Kyran** at 2016-09-04 23:19:25 UTC
Time: 2016-09-04T23:14:51+00:00
Session ID: e9785f57b5763f3a28def663f54d5f18
Problem Page URL: [/manage_counties/place_range?params=A-D](/manage_counties/place_range?params=A-D)
Previous Page URL: [http://www.freereg.org.uk/manage_counties/selection?option=Work%20with%20Active%20Places](http://www.freereg.org.uk/manage_counties/selection?option=Work%20with%20Active%20Places)
Reported Issue:
Wanting to check transcriber files located in London City, looking for Bishopsgate & nothing is entered.  There is nothing present for the whole of London.  Middlesex appears to be okay.  Thanks,
Kyran Payne - Middlesex & London County Coordinator    

![Screenshot](http://www.freereg.org.uk)

**Comment by edickens** [comment]
Kyran is correct.  There is a problem.  It looks as if LND is not
    being processed in the Contents screens.  There is data:-

```
If you select CC Actions, LND and Active Places, the alphabet option
comes up but no places or data.

The Homepage "Transcriptions" does work.
```

**Comment by Captainkirkdawson** [comment]
Yes I fixed the Transcriptions aspect of the issue yesterday but not the Members display.

**Comment by Captainkirkdawson** [comment]
Fixed as I left for the UK
