### ISSUE TITLE
53280657 number of transcriptions? (Doreen)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#798]
Issue reported by **deo123** at 2016-09-08 16:10:57 UTC
Time: 2016-09-08T16:06:48+00:00
Session ID: eef0aae00642712dac4a824c97697333
Problem Page URL: [/places/53cbf619eca9eb03a600a8d3](/places/53cbf619eca9eb03a600a8d3)
Previous Page URL: [http://www.freereg.org.uk/registers/57d031a6f493fd57e3eaa602](http://www.freereg.org.uk/registers/57d031a6f493fd57e3eaa602)
Reported Issue:
Hi,

can some tell me what is the point of this list at the bottom of Place Info/Church info/Registration info please.
This information is in the church details.
Why does  the date go to 2029? when this church fell down in 1850?    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/57d18d91f493fd5b39951d1b/number_of_transcriptions.JPG)

**Comment by Captainkirkdawson** [comment]
All displays give the decadal breakdown for transcribed records to assist the coordinator in locating errors. The decadal range spans 1530-2029

**Comment by ghost** [comment]
Should I close this?​

---

Sandra Adams-West
_FreeREG Communications Coordinator_
____________________________________________________________________________________

**Comment by PatReynolds** [comment]
It would be good to give an answer. I'm guessing that it is that changing
the end date (e.g. always having it as the end of the current year, or end
of the current decade) costs time/money/downtime for the systems, so we
have put it a reasonably far date into the future.

_\- -_

_Dr Pat Reynolds_
Executive Director
Free UK Genealogy  http://www.freeukgenealogy.org.uk/
A charity registered in England and Wales, number 1096940, transitioning to
a Charitable Incorporated Organisation registered in England and Wales,
number 1167484
VAT registration: 233 0105 70

​+44 ​1904 541411​ +44 7943 145387

36 Albemarle Road, York, YO23 1ER, UK

**Comment by Captainkirkdawson** [comment]
Sandra

You can provide feedback response to reporter

Leave for Scrum to close please.

Pat

Just about anything can be programmed if it is deemed worthwhile. The data
range calculations and displays have always been on the basis of 1530-2029.
The start of mandated recording and an end date. The later was selected as
a decade in the future.

Personally I find it easy to understand but others may not.

K

Kirk Dawson
5220 Riverside Drive
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by helhyde** [comment]
Thanks, Kirk.  That's how I understand it, too.  Sandra, can you say it is
just a random future date?

_\- -_

_Dr Pat Reynolds_
Executive Director
Free UK Genealogy  http://www.freeukgenealogy.org.uk/
A charity registered in England and Wales, number 1096940, transitioning to
a Charitable Incorporated Organisation registered in England and Wales,
number 1167484
VAT registration: 233 0105 70

​+44 ​1904 541411​ +44 7943 145387

36 Albemarle Road, York, YO23 1ER, UK

**Comment by ghost** [comment]
​Will do.

---

Sandra Adams-West
_FreeREG Communications Coordinator_
____________________________________________________________________________________
