### ISSUE TITLE
Replacing a batch

### ISSUE THREAD

**Issue by Sherlock21** [FreeUKGen/FreeUKRegProductIssues#80]
When i select "replace" against a batch of my own, and pick the right batch from my computer, the process begins - as seen by "my Browser is doing something" whirly wheel ( its a iMac).

But there is no reaction or indication from FR2 as to progress ( or lack of)
Next i know is after a couple of minutes, i get a browser error msg saying : TIMEOUT _ SERVER DID NOT RESPOND IN TiME.

Batch in question is/was ericb/ WRYDEWBA4.csv. It has 2000 odd rows of data. The job started possibly about 14:00 or earlier on 23 Nov 2014 GMT. This batch was shown as last updated early Nov 2014 in my Batches list.

Should there be a token send back to the user to keep the timeout happy?
Should there be a simple Upload the batch quickly ( like the 2-part upload then process a new Batch)?
What happens after the first 2 mins or so and a Timeout  MSG appears?
Does the FR2 process stop? IfI come back tomorrow, will the replace have been completed? 
Or does it too die?

I did not take a clock time when i started the reload. But now ( at 14:10 GMT) the original file name is no longer on my list of batches. and nor has the reloaded one appeared yet.

**Comment by Sherlock21** [comment]
- update: at 16:00 the replacement file is not there yet - if indeed its still on its way.

**Comment by Captainkirkdawson** [comment]
If it has time out it has indeed timed out.

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Sherlock21** [comment]
So what's the solution please?
It worked OK when I did Darren's original test week x jobs. Ericb

**Comment by Sherlock21** [comment]
Whilst you are thinking about this one, can/ shall I resort to the Delete present file, then try a straight upload?
Or do you wish me to leave all alone.
Please advise. EricB

**Comment by Captainkirkdawson** [comment]
We have changed servers and a hell of a great deal since.

Needs to be investigated for both upload and replace.

Please wait

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Sherlock21** [comment]
Yes,I agree. Several issue were ok before, but have gone wrong since.

This topic included.

SO fine.
I will stop until you call me. 

Ericb

**Comment by Captainkirkdawson** [comment]
Your file was uploaded at 13:59 yesterday. There is no indication that it
was submitted for processing.

I can see no issues with system. Have uploaded and processed several files.

Please try again.

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Sherlock21** [comment]
OK I note what you tell me.
I don't think that I have uploaded any files since moving server so far as I can recall.
and this one was the only one that i have done as a "replace"

I will try to upload the same one now ( as its previous version appears to me to have been despatched.
I will send a separate msg when its been done - or otherwise.
it will be WRYDEWBA4,csv
E

**Comment by Sherlock21** [comment]
Uploaded OK.
then I moved into process it mode.
following window returned:

PROBLEM: why does it say Place = Bolton By Bowland when the data is for DEWSBURY?

Ericb

**Comment by Sherlock21** [comment]
K

File now finished uploading - i know there are 2 errors in it - due to my fault. 
but its  there.

shall i now do a REPLACE of the same one after correcting errors in my input file?

E

**Comment by Captainkirkdawson** [comment]
sure

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Sherlock21** [comment]
here is the screen print with the Bolton by Bowland msg that was missing from 3 msgs above. sorry.

**Comment by Captainkirkdawson** [comment]
Have committed a different return location. Since the same code is entered from any different locations a common return logic is difficult hence have decided to go further back.
From all I can see the upload works fine.
But have added additional reporting messages.

**Comment by benwbrum** [comment]
If we do need to deal with context-sensitive return URLs, I did something
similar in the internals for the problem report code.  Happy to walk
through it -- not least because the problem reporting code needs some extra
eyes on it itself!

**Comment by Sherlock21** [comment]
Does this ( and Kirk's) dialogue mean that the user needs to do something different? or is it all your "behind the screens skullduggery?

EricB

**Comment by Captainkirkdawson** [comment]
The user has to do nothing different.
As far as I am concerned the upload/replace systems works as expected and
advertized.
There was an issue with permissions which has been fixed. This might/might
not have caused your original problem. Or you were "caught" by my making a
change to fix an earlier bug report by Ali which had identified the
permissions issue.
At this point I believe this item is closed.

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Sherlock21** [comment]
Yes, OK closed.
