### ISSUE TITLE
53431739 Editing messages in the Message System (Eric)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#800]
Issue reported by **REGManager** at 2016-09-10 10:08:59 UTC
Time: 2016-09-10T10:07:26+00:00
Session ID: 4d882e3f060dddc14c6d30267cbf016e
Problem Page URL: [/messages/57d1566cf493fd3c63fe9c1a/edit](/messages/57d1566cf493fd3c63fe9c1a/edit)
Previous Page URL: [http://www.freereg.org.uk/messages](http://www.freereg.org.uk/messages)
Reported Issue:
Please make the edit box bigger.  It is very difficult to see what you are editing.  (Only minor problem) E    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Faster to deal with than to comment. Done
