### ISSUE TITLE
53399079 Persistent Urls (David Wallis)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#801]
Issue reported by **David Wallis** at 2016-09-10 01:04:39 UTC
Time: 2016-09-10T00:53:54+00:00
Session ID: 1bd14025bc6d24e76199f1f41b454ead
Problem Page URL: []()
Previous Page URL: [http://freereg2.freereg.org.uk/contacts/new](http://freereg2.freereg.org.uk/contacts/new)
Reported Issue:
You need to provide a permanent URL reference for each database record. Right now, if I save the URL of a record it does no good. If I try to use it again without a search or give it to someone else to use to reach that record it doesn't give the record. 

I can store URLs from familysearch.org (and most other sites) as sources in my family tree and I can get the same record back at any time, or use the URL to refer other people to the same data without a search. This requirement is crucial for the usability of any genealogy site.    

![Screenshot](http://www.freereg.org.uk)

**Comment by PatReynolds** [comment]
The Open Data - technical roadmap email discussion among Trustees in November concluded that persistent urls were wanted in all sites.  #439 discussions may be relevant  I will write to David and let him know

**Comment by Captainkirkdawson** [comment]
#439 is not relevant

**Comment by benwbrum** [comment]
See also #1144 and #1145

**Comment by benwbrum** [comment]
This story is the same as https://waffle.io/freeukgen/myopicvicar/cards/58cbd4c4f48e9b0044539d05 as it covers permalinks for URLs for individual records.  I will do research into previous discussions and move them here.

**Comment by benwbrum** [comment]
From email correspondence with @richardofsussex in May of 2012:


> I have just tidied up and published my blog post about initial work on FreeBMD:
> 
> http://light.demon.co.uk/wordpress/?p=117
> 
> This is probably pretty simplistic stuff, from the PoV of anyone who is already familiar with FreeBMD, but at least it starts a discussion about what is possible.
> 
> In general terms, I would like to explore the idea of assigning unique identifiers (persistent URLs) to each B, M and D event, and supporting the delivery of a machine-processible version of that event.  These URLs could (well, in my view should) be based on the database identifier for that entry, e.g.:
> 
> http://data.freebmd.org.uk/id/160112902
> 
> You could have various delivery formats, each indicated by a suitable suffix, e.g.:
> 
> http://data.freebmd.org.uk/id/160112902.rdf
> http://data.freebmd.org.uk/id/160112902.json
> 
> It would be nice also to have a way of submitting a search as a URL:
> 
> http://data.freebmd.org.uk/search?type=all&surname=Kerridge&district=Conway (to 1937)&format=rdf
> 
> and getting back RDF (or XML) as a response.
> 
> How hard would it be to build that sort of functionality on top of the current database?
>

**Comment by benwbrum** [comment]
From email correpondence relating to SEO and Open Data from May 2014:


> Apparently, using a hierarchy of human-parseable names improves search engine optimization in the kinds of non-slimy ways that might benefit our genealogical researchers who are just typing in names, dates, and places into Google.  This sort of thing can be done straightforwardly in Ruby on Rails so that, rather than an 1688 burial record for John Smith of East Newton, Hull, ERY having the URL of www.freereg.com/search_record/689493956819048301, it could have the URL of www.freereg.com/search_record/east-riding-of-yorkshire/hull/east-newton/1688/burial/john-smith

**Comment by richardofsussex** [comment]
The article quoted above now has the URL:

http://richardofsussex.me.uk/wordpress/exploring-freebmd-as-a-potential-linked-data-resource/

I can see the value of SEO-friendly URLs, but against that we need to balance absolute persistence of the link, possibly in the face of the data changing slightly.  A win-win solution might involve re-direction of SEO-friendly URLs to impenetrable-but-persistent ones.

**Comment by benwbrum** [comment]
Implementation-wise, we should probably use the `friendly-id` gem.  [Gemfile example](https://github.com/benwbrum/fromthepage/blob/a0c95237e5cb94d76fb6706f1fd202dcfc2aabc6/Gemfile#L77) [Usage example](https://github.com/benwbrum/fromthepage/blob/2a83e6a2fdf96ec080590c29fe209f99b4184d32/app/models/user.rb#L147-L164)

Open issues:
* What happens if a "parent" record like church name or placename changes?  How frequent is that?  (Raised by @richardofsussex above)
* What happens when a slug datum changes, as when Rich Jones is corrected to Rick Jones?
* What happens if a record is replaced?  (cf how we handle hashes in CSV processing)
* What happens if data internal to a record changes?

**Comment by richardofsussex** [comment]
I still think that basing identifiers on (mutable) data is a broken strategy which gives us maintenance problems we simply don't need to lumber ourselves with.

**Comment by PatReynolds** [comment]
I think we need to use www.freereg.com/search_record/689493956819048301, and make our pages as SEO friendly as possible (e.g. 'share this on google+' button, etc.)  This one record could have multple SEO-friendly URLS redirecting to it  www.freereg.com/search_record/east-riding-of-yorkshire/hull/east-newton/1688/burial/john-smith www.freereg.com/search_record/east-riding-of-yorkshire/hull/1688/burial/father_john-smijth-john-smith etc.  
*edited for spelling and missing closing bracket.

**Comment by richardofsussex** [comment]
Absolutely: agreed.

**Comment by Sherlock21** [comment]
Both url links go nowhere for me - just an error 404 Not found message.

and what are SEP and SEO friendly please?


[ and I cant log in to github as my password wont reset - sorry for doing comment htis way!
eric b

**Comment by PatReynolds** [comment]
No worries.  SEP is a typo for SEO (now corrected).  SEO is an abbreviation for Search Engine Optimisation - what makes FreeREG appear first (or a hundred and first) on the list when you search for  "John Smith" Hull burial 1688.  Or doesn't at all, at the moment. Looking at what happens when that search is made, it's clear that our results page for John Smith's burial is probably the best thing on the web, but it isn't at all discoverable.  So people searching for 'free baptism records' will find us but people searching for a specific person won't.

**Comment by richardofsussex** [comment]
See the discussion on exactly this topic from the MCG list:
https://www.jiscmail.ac.uk/cgi-bin/webadmin?A1=ind1712&L=MCG#12
Their conclusion is 'id plus human-readable as an optional extra'.

**Comment by benwbrum** [comment]
ID plus human-readable is fine.  We still face the question of what happens to a record that's been updated?  If a file has had one entry corrected and been re-uploaded we face a potential for the unchanged records to have their ID change.  (This is not always the case, as FreeREG is pretty careful about only updating changed records, but it may be a concern for FreeCEN).

Currently the permalink to John Jones of Kimbolton's census record is as follows:  https://freecen2.freecen.org.uk/search_records/5903414ae9379091b11d36f3

We can pretty easily change this to https://freecen2.freecen.org.uk/search_records/5903414ae9379091b11d36f3/john-jones-1891-census-kimbolton-huntingdonshire which I think contains the most important information.

If there's no concern about hierarchy (i.e. no preference for  https://freecen2.freecen.org.uk/search_records/1891-census/huntingdonshire/kimbolton/5903414ae9379091b11d36f3/john-jones ) then that's entirely straightforward, and we can create a story to implement.

**Comment by richardofsussex** [comment]
Surely the solution to persistence of IDs is to store them with the data as they are allocated.

On the human-readable URL side, I don't have any strong views in favour of a pseudo-hierarchy in the URL: your dash-separated form would be fine.

**Comment by benwbrum** [comment]
I think we're in agreement, then.  Let's build it!

**Comment by benwbrum** [comment]
See https://github.com/FreeUKGen/MyopicVicar/issues/1144 for story tracking the implementation of this.
