### ISSUE TITLE
53684196 Minus two errors in a file (Staffordshire)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#802]
Issue reported by **STSCoord** at 2016-09-13 08:16:36 UTC
Time: 2016-09-13T08:10:18+00:00
Session ID: 9d06f33935d68ffc31c8f5100c48eba6
Problem Page URL: [/freereg1_csv_files/5463a206e937902782b4b359](/freereg1_csv_files/5463a206e937902782b4b359)
Previous Page URL: [http://www.freereg.org.uk/registers/5408f5aeeca9eb260e09b3fc](http://www.freereg.org.uk/registers/5408f5aeeca9eb260e09b3fc)
Reported Issue:
I have a file that contains -2 errors in it. This should be impossible.    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/57d7b5e4f493fd784503cc95/Capture.JPG)

**Comment by Captainkirkdawson** [comment]
Definitely. fixed
