### ISSUE TITLE
54316672 change of Reg type (Doreen)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#806]
Issue reported by **deo123** at 2016-09-20 15:57:52 UTC
Time: 2016-09-20T15:54:24+00:00
Session ID: 822fb47ae0660a901d6f259f7946fafd
Problem Page URL: [/registers/57e08dc5f493fdf6850a94bc](/registers/57e08dc5f493fdf6850a94bc)
Previous Page URL: [http://www.freereg.org.uk/freereg1_csv_files/57e08dc5f493fdf6850a94bb](http://www.freereg.org.uk/freereg1_csv_files/57e08dc5f493fdf6850a94bb)
Reported Issue:
after changing the Reg Type, the file information has changed, see attachment.

This file was uploaded correctly last night.

So I think you have something of quiet right.  This has also happened with other files.    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/57e15c80f493fd86ef00a6df/register_type_change.JPG)

**Comment by Captainkirkdawson** [comment]
There was a birth date of 1969
