### ISSUE TITLE
54131085 Number of Transcriptions Report (Doreen)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#807]
Issue reported by **deo123** at 2016-09-18 12:24:45 UTC
Time: 2016-09-18T12:18:28+00:00
Session ID: c2a7814046e1d7f71987a1f73553e155
Problem Page URL: [/registers/5408314feca9eb81e2db249b](/registers/5408314feca9eb81e2db249b)
Previous Page URL: [http://www.freereg.org.uk/manage_counties/place_range?params=C](http://www.freereg.org.uk/manage_counties/place_range?params=C)
Reported Issue:

can you look at Cornwall, Constantine
see attachments 01/02/03

01 displays all the files for Parish Registers for Constantine.
If you look at each file at the start-end dates they seem ok to me. Start at 1562 to 1901

02
Then if you move down to "First actual year entry" "Last actual year entry"  you have ....zero to 1958

03  number of Transcriptions
well I could fit all of this section into my screen...another gripe...this is a work area and not for the outside world
so why all the top/bottom stuff on the page.....
back to it..
Dates start at 1560-1569 decade but finish at 1930 which has 30 records.
but they are not mentioned in the listing above

will send the other to screen shots.    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/57de878df493fd4c0ba17ef7/01__Cornwall-Constantine.JPG)

**Comment by Captainkirkdawson** [comment]
Cannot duplicate the problem

**Comment by Sherlock21** [comment]
I have researched this today, and believe that it is related to the use of \* in dates.
It appears that if the first record in a file is in the form \* Jan 1805 ( say) then the calc of the start year for the range gives 0. The end year always seems to come out right however,!

Whereas if the first record is a real date, then the start year comes out right.

BUT to complicate it, if a date in the file anywhere is in the form 13 \* Dec 1786, then the start year for that file is 0
and if the form \* \* \* is used, that also give 0 as start year. 

my file was a Mac file, UTF-8 coding and run in Production 27 Sep 2016.

**Comment by Sherlock21** [comment]
Refer to personal email E Booker > Kirk containing copies of file used today to repeat the testing.

It concludes they any Marriage date with :\* in the year position - i.e. 28 Sep 2016 being written was 28 Sep \* or as \* or as 3 stars \* \* *, then they are the ones that create the erroneous start year 0 for the record count.
as in Test3 region WRY/ Sedbergh Marriages collection - files by ericb

**Comment by Captainkirkdawson** [comment]
That is exactly what I would have expected. There is no year information for a year with \*  therefore it is 0

**Comment by Captainkirkdawson** [comment]
EricB wrote 
one last thing on this topic.

Given that you say the product is designed to who 0 as the start yeasr of a Register, when there is a record that has  \* or incomplete year date,, how does this one arise then please - given that each of the individual batches are showing a positive year start ( in the header listing) but a 0  as the First Actual year of Records, in the sumary listing.

scan of  sumary page attached - its for CON /Gulval

**Comment by PatReynolds** [comment]
Can this now be closed?

**Comment by Captainkirkdawson** [comment]
No there remains a question raised by EricB

**Comment by PatReynolds** [comment]
What is the question?  You raised a question 3 days ago - is that it?

**Comment by Sherlock21** [comment]
The situation referred to in posts 4 above remains still the issue concerning \* years.

But as it has been explained that this is the designer's logic - viz if there is record with an undefined year in a batch, then that must be 0 stagy year.

It is therefore this logic that is questioned since it confuses everyone else.
It is suggested that it is more understandable to the users,  to just ignore \* years and use the next lowest year value.

**Comment by edickens** [comment]
```
But for CCs, it is useful to know if there is a * year in a batch,
which needs sorting out.  So the Decade analysis could show a zero,
but this zero year count would be ignored for year ranges, totals
and summary reports.  E
```

**Comment by Captainkirkdawson** [comment]
Pat

It is unfortunate that sometime people send me comments by email that really need to be part of the thread so I copy them in. Unfortunately they then come in under my flag and I sometimes forget to add a note that they really belong to someone else. Github will not allow me to use someone else's flag. Nor should it.

**Comment by Captainkirkdawson** [comment]
It becomes extremely problematic with attempting to use information to meet very different requirements. The datamax/min and decadal ranges are used in many different displays. If in one display they say one thing then in another they something else then the next bug report we will get is a statement to that effect!!!!!

**Comment by edickens** [comment]
Understood.  So is it possible to omit the \* years entries from the
    count everywhere, but have a marker somewhere that CCs can find,
    perhaps in the batch listing, to say that there is an entry with no
    year in this batch.  But this must be V1.5 - Coordinators
    enhancements.  Don't spend time now on it.  E

**Comment by PatReynolds** [comment]
Has this been completed or overtaken by the wildcard / UCF stories?
