### ISSUE TITLE
54766927 Acknowledgement email addresses are not being removed when headers are updated (Eric)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#808]
Issue reported by **REGManager** at 2016-09-25 21:02:07 UTC
Time: 2016-09-25T20:56:37+00:00
Session ID: 1e0f43c4395fe28e92fcdf377a9c9e21
Problem Page URL: [/freereg_contents/564c3684f493fdc2fa060c87/show_register](/freereg_contents/564c3684f493fdc2fa060c87/show_register)
Previous Page URL: [http://www.freereg.org.uk/freereg_contents/Bishopsgate](http://www.freereg.org.uk/freereg_contents/Bishopsgate)
Reported Issue:
In LDN Bishopsgate St Botolph an email address got into the Acknowledgement field.  This has not been removed, but the Register Type information still shows this person's email address.
So amendments to the headers are not being carried through to the Transcriptions pages and so are being made public.  E
PS.  Organisations is spelt with an S in UK English.    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/57e83b4ff493fdcea2a0fe42/Capture.JPG)

**Comment by Captainkirkdawson** [comment]
Can you please confirm what is meant by "This has not been removed, but the Register Type information still shows this person's email address." Do you mean it has now been removed? If so how was it removed and which file was involved

**Comment by edickens** [comment]
```
I can't find the email easily, it is 100s down my list, but I think
I put it in a story.  What happened is that an email address got
into the Credit Transcriber Name field from a batch header.  When
the file header is edited and the "Credit Transcriber" field, which
contained an email address, is cleared the entry still stays in the
public information report.  E
```

**Comment by Captainkirkdawson** [comment]
How is the "When the file header is edited" done on-line or file upload???

**Comment by edickens** [comment]
```
On line to the best of my knowledge.  And the batch is locked.  E
```

**Comment by Captainkirkdawson** [comment]
TY That is what I need to know.

**Comment by Captainkirkdawson** [comment]
Fixed
