### ISSUE TITLE
I can't enter the surname of a new UserID (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#81]
Issue reported by **REGManager** at 2014-11-23 17:06:36 UTC
Time: 2014-11-23T16:58:41+00:00
Session ID: 0430b70a658901a91f8535c8fc606da6
Problem Page URL: [/userid_details/new](/userid_details/new)
Previous Page URL: [http://test2.freereg.org.uk/userid_details/options](http://test2.freereg.org.uk/userid_details/options)
Reported Issue:
I get down to forename, but when I try to click Surname the cursor will not go there.  It just adds the name to the forename.  If I hit  Return to get the cursor to move on, I get a program crash.

I don't know if these reports can be opened in a separate window, because while writing this I have now lost the page I was working on and cannot do a screen print.  I will have to log in again to get to where I was.

I was working on REGManager Add New UserID.

E    

![Screenshot](http://test2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Update applied. Problem introduced by styling
