### ISSUE TITLE
54973567 Split year error (Ali)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#810]
Issue reported by **alsibk** at 2016-09-28 06:26:07 UTC
Time: 2016-09-28T06:20:36+00:00
Session ID: 8f0ce34fb2da248ea193e060a1d7f8c6
Problem Page URL: [/freereg1_csv_entries](/freereg1_csv_entries)
Previous Page URL: [http://www.freereg.org.uk/freereg1_csv_files/57aa06c9f493fdf47f000001](http://www.freereg.org.uk/freereg1_csv_files/57aa06c9f493fdf47f000001)
Reported Issue:
File WRYSEDBA.CSV has an accepted baptism date of 
- Apr 1608/9

WinREG also accepts this format, and totally blank day.

With a day entered, eg 12 Apr 1608/9, it is shown as an error

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/57eb627ff493fd171f679c34/Split_year_error.jpg)

**Comment by EmJayFry** [comment]
Bug in Date validation routines. Corrected for WinFreeREG but not for WinREG since a further release of that program is not envisaged.

**Comment by PatReynolds** [comment]
To close?

**Comment by ghost** [comment]
As nothing is will be done for WinREG, I assume that it is OK for me to go
back to the contact to let them know why no change to WinREG, but that the
issue has been sorted for WinFreeREG?​

---

Sandra Adams-West
_FreeREG Communications Coordinator_
____________________________________________________________________________________

**Comment by suffolkroots** [comment]
The concern is that FR accepts this wrong date format.
viz
File WRYSEDBA.CSV has an accepted baptism date of

```
Apr 1608/9
```

**Comment by PatReynolds** [comment]
Can you clarify what Apr 1608/9 means - why is there uncertainty about the year?

**Comment by edickens** [comment]
```
The split years finish in March.  They can only apply to Jan to
March.  E

  On 07/10/2016 09:57, PatReynolds wrote:


  Can you clarify what Apr 1608/9 means - why is there
    uncertainty about the year?
  —
    You are receiving this because you are subscribed to this
    thread.
    Reply to this email directly, view
      it on GitHub, or mute
      the thread.







  {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/FreeUKGen/FreeUKRegProductIssues","title":"FreeUKGen/FreeUKRegProductIssues","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/FreeUKGen/FreeUKRegProductIssues"}},"updates":{"snippets":[{"icon":"PERSON","message":"@PatReynolds in #810: Can you clarify what Apr 1608/9 means - why is there uncertainty about the year?"}],"action":{"name":"View Issue","url":"https://github.com/FreeUKGen/FreeUKRegProductIssues/issues/810#issuecomment-252187730"}}}
```

**Comment by EmJayFry** [comment]
On 07 Oct 2016 11:12, Eric Dickens wrote:

> The split years finish in March.  They can only apply to Jan to
> March.  E
> 
> On 07/10/2016 09:57, PatReynolds wrote:
> 
> Can you clarify what Apr 1608/9 means - why is there
> uncertainty about the year?
> —
> You are receiving this because you are subscribed to this
> thread.
> Reply to this email directly, view
> it on GitHub, or mute
> the thread.

Double-dating for 1st January to 24th March up to but not including 1752 (in the 
UK). Also, in 1752, 3rd to 13th September (incl.) shouldn't exist.

## 

Regards,
Mike Fry (Jhb)

**Comment by ghost** [comment]
I think all that needs to be done is to notify Ali that the bug was
corrected for WinFreeREG, but will not be for WinREG because that will not
be moving forward. I will also include the bits of info given via this
thread, such as that contained in Mike's previous post.

Surely this can be closed now?

Sandra​

---

Sandra Adams-West
_FreeREG Communications Coordinator_
____________________________________________________________________________________

**Comment by EmJayFry** [comment]
On 10 Oct 2016 10:46, CommsCoord wrote:

> Surely this can be closed now?

Close it. We're only a day or so from releasing WinFreeREG which does have the 
correction.

## 

Regards,
Mike Fry (Jhb)

**Comment by ghost** [comment]
Closing as per Mike's post.

**Comment by suffolkroots** [comment]
FR accepts this bad date format---shouldn't this be addressed? It was the initial issue raised.
Please could this be re-opened until dealt with?

**Comment by EmJayFry** [comment]
On 10 Oct 2016 17:18, suffolkroots wrote:

> FR accepts this bad date format---shouldn't this be addressed? It was the
> initial issue raised.
> Please could this be re-opened until dealt with?

WinFreeREG is being made available from today. Get your users to run through 
their existing files using the new program to pick up any existing bad dates, or 
bad Place and Church names. No need to re-open.

## 

Regards,
Mike Fry (Jhb)

**Comment by suffolkroots** [comment]
What about the many who do not use WinREG or its descendant?

FR should not accept bad date format.

**Comment by ghost** [comment]
Is it possible to either reopen if this is needed or get an explanation as
to the what happens with FR in this instance? A resolution or explanation
would be very welcome in putting the issue to bed.

Sandra​

---

Sandra Adams-West
_FreeREG Communications Coordinator_
____________________________________________________________________________________

**Comment by Sherlock21** [comment]
But this amounts to saying: if the transcriber uses WinFreeReg ( in the future) this issue will not arise - rather than fixing the problem in FR. Wont the issue still stay for those who are Spreadsheet users?

**Comment by Sherlock21** [comment]
Your efforts are a help, Mike, but the issue needs to be fixed in FR really.

EB

**Comment by edickens** [comment]
```
But Mac users cannot use WinFreeREG or WinREG so need the validation
on the server.  E

  On 10/10/2016 17:27, Mike wrote:

On 10 Oct 2016 17:18, suffolkroots wrote:

  > FR accepts this bad date format---shouldn't this be
  addressed? It was the
  > initial issue raised.
  > Please could this be re-opened until dealt with?

  WinFreeREG is being made available from today. Get your users to
  run through 
  their existing files using the new program to pick up any existing
  bad dates, or 
  bad Place and Church names. No need to re-open.

  -- 
  Regards,
  Mike Fry (Jhb)
  —
    You are receiving this because you commented.
    Reply to this email directly, view
      it on GitHub, or mute
      the thread.







  {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/FreeUKGen/FreeUKRegProductIssues","title":"FreeUKGen/FreeUKRegProductIssues","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/FreeUKGen/FreeUKRegProductIssues"}},"updates":{"snippets":[{"icon":"PERSON","message":"@EmJayFry in #810: On 10 Oct 2016 17:18, suffolkroots wrote:\n\n\u003e FR accepts this bad date format---shouldn't this be addressed? It was the\n\u003e initial issue raised.\n\u003e Please could this be re-opened until dealt with?\n\nWinFreeREG is being made available from today. Get your users to run through \ntheir existing files using the new program to pick up any existing bad dates, or \nbad Place and Church names. No need to re-open.\n\n-- \nRegards,\nMike Fry (Jhb)\n"}],"action":{"name":"View Issue","url":"https://github.com/FreeUKGen/FreeUKRegProductIssues/issues/810#issuecomment-252671515"}}}
```

**Comment by Sherlock21** [comment]
Seems as though no one is listening to the real issue here.

**Comment by suffolkroots** [comment]
Nail on the head, Sherlock21. Thankyou. 

Real issue---FR should not accept bad format dates.

**Comment by PatReynolds** [comment]
I agree - with those who say that we need to get the bottom of why this date was entered.  I can think of two circumstances.

First: a previous date is, say,  12 January 1608, and the subsequent date is 14 May 1609, but this record is (illegible) April (illegible).  So its either April 1608, or April 1609.  And should be recorded as *\* April 160\* with a note (perhaps - I'm not perfect on the illegibility convention).

The other is that it preceding date is 12 January 1600 and the subsequent is 14 May 1609, and this date is (illegible) April 160 (either an 8 or a 9, can't quite tell).  Again should use \* to indicate unknowns (with a note saying that it looks like an 8 or a 9.

**Comment by edickens** [comment]
```
There is another reason.  That is what was entered in the register. 
We do find errors by the clerk.  So we TWYS.

I'm not sure how important this is, because we only use the year in
the search.  So provided the year is understood by the server, then
a year search will find the record.  in the example you give * Apr
160_ (This is how it would be entered under UCF) I am not sure how
the server would find a year.  E

  On 11/10/2016 09:30, PatReynolds wrote:


  I agree - with those who say that we need to get the bottom of
    why this date was entered. I can think of two circumstances.
  First: a previous date is, say, 12 January 1608, and the
    subsequent date is 14 May 1609, but this record is (illegible)
    April (illegible). So its either April 1608, or April 1609. And
    should be recorded as ** April 160* with a note (perhaps - I'm
    not perfect on the illegibility convention).
  The other is that it preceding date is 12 January 1600 and the
    subsequent is 14 May 1609, and this date is (illegible) April
    160 (either an 8 or a 9, can't quite tell). Again should use *
    to indicate unknowns (with a note saying that it looks like an 8
    or a 9.
  —
    You are receiving this because you commented.
    Reply to this email directly, view
      it on GitHub, or mute
      the thread.







  {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/FreeUKGen/FreeUKRegProductIssues","title":"FreeUKGen/FreeUKRegProductIssues","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/FreeUKGen/FreeUKRegProductIssues"}},"updates":{"snippets":[{"icon":"PERSON","message":"@PatReynolds in #810: I agree - with those who say that we need to get the bottom of why this date was entered.  I can think of two circumstances.\r\n\r\nFirst: a previous date is, say,  12 January 1608, and the subsequent date is 14 May 1609, but this record is (illegible) April (illegible).  So its either April 1608, or April 1609.  And should be recorded as ** April 160* with a note (perhaps - I'm not perfect on the illegibility convention).\r\n\r\nThe other is that it preceding date is 12 January 1600 and the subsequent is 14 May 1609, and this date is (illegible) April 160 (either an 8 or a 9, can't quite tell).  Again should use * to indicate unknowns (with a note saying that it looks like an 8 or a 9.\r\n\r\n"}],"action":{"name":"View Issue","url":"https://github.com/FreeUKGen/FreeUKRegProductIssues/issues/810#issuecomment-252846308"}}}
```

**Comment by suffolkroots** [comment]
Pat's scenario does not take account of the fact that a valid date should be entered and any discrepancy highlighted in the notes. Apr 1608/9 is not a valid date.

**Comment by edickens** [comment]
```
I'm not sure, but I think the server creates a "Search year"
extracted from the date.  Perhaps we need to be able to enter that
when the TWYS is wrong?  E

  On 11/10/2016 11:10, suffolkroots wrote:


  Pat's scenario does not take account of the fact that a valid
    date should be entered and any discrepancy highlighted in the
    notes. Apr 1608/9 is not a valid date.
  —
    You are receiving this because you commented.
    Reply to this email directly, view
      it on GitHub, or mute
      the thread.







  {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/FreeUKGen/FreeUKRegProductIssues","title":"FreeUKGen/FreeUKRegProductIssues","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/FreeUKGen/FreeUKRegProductIssues"}},"updates":{"snippets":[{"icon":"PERSON","message":"@suffolkroots in #810: Pat's scenario does not take account of the fact that a valid date should be entered and any discrepancy highlighted in the notes. Apr 1608/9 is not a valid date."}],"action":{"name":"View Issue","url":"https://github.com/FreeUKGen/FreeUKRegProductIssues/issues/810#issuecomment-252868273"}}}
```

**Comment by suffolkroots** [comment]
"we need to get the bottom of why this date was entered." 

Here's the bottom---it was an error---should have been Apr 1609

Why was Apr 1608/9 accepted by FR? is the question.

**Comment by Sherlock21** [comment]
This story is about Why did FR accept a split year date that is invalid. that is a bug and needs fixing.

the extra point put in to the discussion by Pat, on what the transcriber might or might not have meant if they wrote 160\* is a red herring. Indeed if any of the possible arguments which have been put forward, if the whole year could not be read, then the existing rules are: type in the year only, from the record in the Register that immediately precedes the one in question.
AND generate a Note saying: the year cannot be read for this record in the Register. However this record  is immediately preceded by one dated (ddmmyyyy) and followed by the next record which has the date: (ddmmyyyy). the Researcher should consult the original register for further details.

And lets move on please.
