### ISSUE TITLE
55015699 FreeREG needs to recognise Patronymics (Glen)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#811]
Issue reported by **GJenkins** at 2016-09-28 18:08:19 UTC
Time: 2016-09-28T17:43:16+00:00
Session ID: 006dc0d71e16c964228767ff41310433
Problem Page URL: [/contacts](/contacts)
Previous Page URL: [http://www.freereg.org.uk/feedbacks](http://www.freereg.org.uk/feedbacks)
Reported Issue:
The patronymic system of naming was used in Wales prior to 1813. Indeed it has been suggested that all names prior to this date are probably patronymic and the priest followed  the English system of naming – forename & surname – without regard for the patronymic system in place. The changeover fully to the English system varies throughout Wales and in some places is as late as 1840. Patronymic naming also exists in Cornwall and Scotland. 
Example : CMN Conwil Caio St Philip and St James Parish Register 1718
The entry for 23 APR 1718 reads
David fil Rees ap Evan L.H.
LH signifies ‘Lower Hamlet’ and is a place name
However, there is no SURNAME in this construction. If TWYS was operated properly for this transcription, the father entry of both Rees and Evan should be in the forename with no entry in the surname column as there is no surname. 
However to accommodate the existing column layout in FreeREG entries for the father have been entered as:
1.  Forename Rees surname ap Evan
2.  Forename Rees ap surname Evan
However the person above is not David Evan but David Rees or more precisely David ap Rees . So if you search for David Rees you will not find him on FreeREG.
To make matters worse the person called David ap Rees at the point of changeover of naming systems would in some cases be called David Price, David Prys /Preece/Preess or stayed as David Rees. This largely depended on how the priest interpreted the name later on as surnames became established in Wales.
I have picked out one entry on this page because it is clearly patronymic. However, all these entries on this page are probably patronymic. 
Recommendation
We have hundreds of entries like this in Wales that cannot be entered onto the existing system. We therefore need a patronymic column layout were David son of Rees son of Evan can be entered properly and then searched. 
Alternatively,one could accommodate this by having a column for the ‘surname’ of the child (in this case Rees) differs from the father’s (in this case Evan). Patronymic searches could then be used to find people who have been names in the patronymic system. 
I appreciate that this is a tall order but needs to be addressed. 

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/57ec0713f493fd171f67a8c1/GLA_Conwil_Caio_Parish_Church.jpg)

**Comment by Captainkirkdawson** [comment]
Relevant to #809

**Comment by SteveBiggs** [comment]
The new proposed BA fields include surname of the child which should address this.
