### ISSUE TITLE
55014195 Column layout for Non-Conformist Registers (Glen)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#812]
Issue reported by **GJenkins** at 2016-09-28 17:43:15 UTC
Time: 2016-09-28T17:20:04+00:00
Session ID: 006dc0d71e16c964228767ff41310433
Problem Page URL: [/contacts](/contacts)
Previous Page URL: [http://www.freereg.org.uk/manage_resources/new](http://www.freereg.org.uk/manage_resources/new)
Reported Issue:
The post 1813 column layout assumes that a child is baptised at birth but in non-conformist registers it can include adults and normally there is much more data that could be searchable in these types of registers.
Example 1: GLA Castell Nedd (Neath) Church of Jesus Christ of Latter Day Saints Baptism Register 1848-1884.
I have attached a screen shot of on one of two pages of the register (a translation of what each column means is available in excel format). These are Post 1813 baptisms and as can be seen include data that cannot be entered into the Post 1813 column layout. 
For example entries from this register that cannot be accommodated and have to be entered in notes are:
• Condition
• Status
• Occupation of Baptised (only father occupation enabled)
• Parish of Birth
• County of Birth
• Age
• Confirmation Date (given this is part of the entry into the church/ divided into two parts Baptism and Confirmation as in CofE)

Another example is also available contact me if you want this.
Example 2: GLA Hermon Independent Chapel Baptism Register 1804-1837.
This register would normally need to be split under the present column layouts. 1804-1813 and 1813-1837. Usually one column layout has to be chosen because the entries are the same.  Post 1813 was chosen for this register. 
Entries from this register that cannot be accommodated and have to be entered in notes are:
• Father’s Parish
• Mother’s condition at marriage
• Mother’s Parish before marriage
• Parish of Birth of child

Recommendation

There should be a non-conformist layout that includes the possibility to enter adult baptisms that differ markedly from baby baptisms and columns reflecting the above. 

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/57ec0133f493fd171f67a882/GLA_LDS_Castell_Nedd_Page_1.jpg)

**Comment by PatReynolds** [comment]
Task for Intern

**Comment by Captainkirkdawson** [comment]
Should be addressed as part of #809 flexible CSV

**Comment by Captainkirkdawson** [comment]
@SteveBiggs can you check we have this in the list of new fields in #809. If so we can close this story

**Comment by SteveBiggs** [comment]
Many of these were not included and adding them will obviously increase the number fields again. I've added them to the google sheet in purple.
