### ISSUE TITLE
overnight processor faied to run last night in Production

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeUKRegProductIssues#813]
Message from Eric B.

**Comment by Captainkirkdawson** [comment]
The update completed satisfactorily at 11:38 GMT.   There is no bug.
The update had 2 extremely large files with every record being changed. One took 5 hrs to process and the other 3hrs.
Have no idea what user/coordinator was doing
******************************************************************\* <br>
Started on the file STSWESBA.CSV for dbraden at 2016-10-03 02:56:44 +0100. <p>
There are 1 locations and 17942 existing records corresponding to the new file. <p>
Updating the current batch for STS, West Bromwich, All Saints, Parish Register. <br>
17942 records were processed of which 17942 were updated/added and 0 had data errors. <p>
There were 17942 entries in the original file that did not exist in the new one and hence were deleted. <br>
Created  17942 entries at an average time of 1042ms per record at 2016-10-03 08:08:37 +0100. <br>
******************************************************************\* <br>
Started on the file STSWESBU.CSV for dbraden at 2016-10-03 08:08:38 +0100. <p>
There are 1 locations and 11391 existing records corresponding to the new file. <p>
Updating the current batch for STS, West Bromwich, All Saints, Parish Register. <br>
11391 records were processed of which 11391 were updated/added and 0 had data errors. <p>
There were 11391 entries in the original file that did not exist in the new one and hence were deleted. <br>
Created  11391 entries at an average time of 1024ms per record at 2016-10-03 11:23:06 +0100. <br>
******************************************************************\* <br>
Started on the file STSWESBU2.CSV for dbraden at 2016-10-03 11:23:06 +0100. <p>
There are 1 locations and 4479 existing records corresponding to the new file. <p>
Updating the current batch for STS, West Bromwich, All Saints, Parish Register. <br>
4479 records were processed of which 4479 were updated/added and 0 had data errors. <p>
There were 4479 entries in the original file that did not exist in the new one and hence were deleted. <br>
Created  4479 entries at an average time of 997ms per record at 2016-10-03 12:37:35 +0100. <br>
Created  47915 entries at an average time of 829ms per record at 2016-10-03 12:37:36 +0100. <br>
