### ISSUE TITLE
56189380 Merging registers leads to loss of source and decadal info (Susan)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#815]
Issue reported by **hawkinssm** at 2016-10-12 08:09:40 UTC
Time: 2016-10-12T08:05:51+00:00
Session ID: dd41b35b56d03cedadc5f04648c987c3
Problem Page URL: [/registers/5772d158f493fdedb4000002](/registers/5772d158f493fdedb4000002)
Previous Page URL: [http://freereg2.freereg.org.uk/manage_counties/place_range?params=G](http://freereg2.freereg.org.uk/manage_counties/place_range?params=G)
Reported Issue:
Gillingham St Alfege provides an example.

A batch was uploaded as unspecified. I checked with the transcriber that it should have been PR. Changed it to PR. Then merged with others of that type.

The result is that the decadal list of attributions etc for the zillion other files no longer appears. I thought it might refresh overnight, but it has not done so.    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Expect this will happen if the merge is done the "wrong" way round. ie merge many into 1 rather than i into many

**Comment by Captainkirkdawson** [comment]
Added code to force re-computation regardless of order. Fixed
