### ISSUE TITLE
56188556 "Suranme" of the groom's father (Susan)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#816]
Issue reported by **hawkinssm** at 2016-10-12 07:55:56 UTC
Time: 2016-10-12T07:54:40+00:00
Session ID: dd41b35b56d03cedadc5f04648c987c3
Problem Page URL: [/freereg1_csv_entries/5463949de937904abb63ab36?](/freereg1_csv_entries/5463949de937904abb63ab36?)
Previous Page URL: [http://freereg2.freereg.org.uk/contacts/57fdde1233045bec5b2d883e](http://freereg2.freereg.org.uk/contacts/57fdde1233045bec5b2d883e)
Reported Issue:
An all pervasive typo in the master code    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Corrected
