### ISSUE TITLE
56466219 Re-name of register is not propagated. (Ali)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#817]
Issue reported by **alsibk** at 2016-10-15 13:03:39 UTC
Time: 2016-10-15T12:57:58+00:00
Session ID: 0a30a80ba0151249fd0aa313a29a849d
Problem Page URL: [/freereg1_csv_files](/freereg1_csv_files)
Previous Page URL: [http://www.freereg.org.uk/manage_counties/select_action?county=Yorkshire%2C+West+Riding](http://www.freereg.org.uk/manage_counties/select_action?county=Yorkshire%2C+West+Riding)
Reported Issue:
having re-named WRYSADBU7.CSV Transcript instead of Unspecified, in the list of IDs and files it is unchanged and not locked. I have logged out and back in again. Still unchanged    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/5802292bf493fdfe3c709775/Unchanged_register.jpg)

**Comment by Captainkirkdawson** [comment]
How was attempt made. ie what process was followed to re-name?
Normal process is to move a batch from one register to another

**Comment by ghost** [comment]
I think what she is getting at is that in the batch listing in her
syndicate pages, there is no TR to identify what the file is (please look
at the screen shot). Everything else seems to look ok. ​

I will however pass on your comments to her and see what we can come up
with.

---

Sandra Adams-West
_FreeREG Communications Coordinator_
____________________________________________________________________________________

**Comment by Captainkirkdawson** [comment]
No screenshot available
That batch is shown as a transcript  when I look at the system and there are no unspecified batches

**Comment by suffolkroots** [comment]
In List of batches this file is still shown as Unspecified.

It was re-named, is in the Transcripts list, but shown as unspecified in List batches

**Comment by Captainkirkdawson** [comment]
Ali states that process used was rename register

**Comment by Captainkirkdawson** [comment]
Have been able to duplicate problem will now work on solution

**Comment by Captainkirkdawson** [comment]
Fixed and affected batches corrected
