### ISSUE TITLE
Allow individuals to set their status (e.g. 'away')

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeUKRegProductIssues#818]
A question rather than a suggestion.  Should we allow individuals to set their status - e.g. a temporary away, a permanent step down, rather than have the coord or manager do this?  One advantage of people doing it themselves is that personal data (e.g. I am away on holiday, I am going into hospital for a minor op) doesn't get passed to us or stored by us, just that the person is unaviailable.

**Comment by Captainkirkdawson** [comment]
Currently the active is a true/false setting with its change a management action.
The planned communicate opt in/out is expected to be a member action.

**Comment by edickens** [comment]
I think this relates to communication and the sender should not
    expecting a reply, rather than the Status which would make them
    Inactive and so not able to log in to change the setting back
    again.  They would not want to change their status from
    "Transcriber" and that should only be done by the SC.  E

**Comment by PatReynolds** [comment]
Yes - it would allow someone to step back for a few weeks / months (e.g.
due to a long holiday or sickness), without becoming inactive.

**Comment by Captainkirkdawson** [comment]
I am sorry I no longer understand this story and the requirement.
Status is not defined within the current data model.  We have 2 fields which may be relevant.
1. We have an active/inactive field which is binary ( logical true/false) one is either one or the other. To change this definition of this field requires a major rewrite of the system
2, We are proposing a new field that relates to communications in #692 . A transcriber or any member can opt to receive communications or not.  This can be set/reset by the transcriber at anytime. Again the field will be binary. (The message system will permit override "for emergency" reasons as defined by the Executive Director)
If neither of these meets the need for a new field called status is to perform please indicate the requirement..

**Comment by helhyde** [comment]
I didn't realise that active/inactive was binary and required a major
rewrite to change.

We have other 'select by' field(s) current or planned, and I don't know how
they (will) work - e.g. deceased, member of a specific syndicate,
temporarily away, email bouncing). Probably all these should be (re)
considered in total and then individual stories developed?

_\- -_

_Dr Pat Reynolds_
Executive Director
Free UK Genealogy  http://www.freeukgenealogy.org.uk/
A charity registered in England and Wales, number 1096940, transitioning to
a Charitable Incorporated Organisation registered in England and Wales,
number 1167484
VAT registration: 233 0105 70

​+44 ​1904 541411​ +44 7943 145387

36 Albemarle Road, York, YO23 1ER, UK

**Comment by Captainkirkdawson** [comment]
That depends on what you want to achieve, As noted we have 2 fields. active/inactive which is logical/binary with standard reasons for inactive or opt/in for messaging or email valid/invalid.

Sound to me you wish to redesign the system. Needs a new story and likely a biggie to deal with

**Comment by richpomfret** [comment]
On hold - common gateway question/design.

**Comment by Captainkirkdawson** [comment]
Given age and lack of specificity on any action  propose we close
