### ISSUE TITLE
county Coords to be able to contact all transcribers working on the county

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeUKRegProductIssues#819]
Once image allocation is working (i.e. we know who is working on a county) this data to be available so county coord can email those working on a county.  Also manual over-ride (e.g. for persons in training, allocated to a county but not yet transcribing)

**Comment by Captainkirkdawson** [comment]
This puzzles me as it seems to be in conflict with our work flow model that has syndicate coordinators working with transcribers and county coordinators working with syndicate coordinators

**Comment by edickens** [comment]
I agree, because it is the Syndicate Coordinator who should be the
    contact with the transcriber.  The only situation is where a County
    Coordinator wants to contact anyone who has worked on their county's
    data, however I cannot think of a circumstance as they are more
    likely to want to contact everyone because they have more data and
    want transcribers.  E
