### ISSUE TITLE
Missing batch (alsibk)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#82]
Issue reported by **alsibk** at 2014-11-23 18:28:26 UTC
Time: 2014-11-23T18:26:51+00:00
Session ID: 4f806550e697ec022f4f05e75eb3a459
Problem Page URL: [/manage_counties/selection?option=Review%20Specific%20Batch](/manage_counties/selection?option=Review%20Specific%20Batch)
Previous Page URL: [http://test2.freereg.org.uk/manage_counties/select_action?county=WRY](http://test2.freereg.org.uk/manage_counties/select_action?county=WRY)
Reported Issue:
WRYWRABU1.CSV replaced yesterday apparently successfully but not present on list    

![Screenshot](http://test2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
The file was uploaded at 16:46 on Nov 22.
There is no indication that the file was submitted for processing

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1
