### ISSUE TITLE
Use a Responsive Advert in place of  current advert / position for current form of advert

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeUKRegProductIssues#820]
To be trialled first on FreeCEN2

**Comment by Captainkirkdawson** [comment]
Given it is dependent on  other activities and that the requirement does no relate to coordinator or transcriber matters do not understand its assignment to completion of 1.5 which is due for Dec 31 2016
The same comment applies to 821-823

**Comment by helhyde** [comment]
I'm hoping Rich might be able to suggest a way of marking tasks like this
which are running parallel to the main development.

**Comment by PatReynolds** [comment]
Needed for income generation

**Comment by PatReynolds** [comment]
Pat to ask David for code

**Comment by PatReynolds** [comment]
Resent code to Israel

**Comment by PatReynolds** [comment]
@PatReynolds to resend code to @israelriibeiro and ask him to progress

**Comment by PatReynolds** [comment]
Resent code to @israelriibeiro
