### ISSUE TITLE
Place additional adverts on search and results pages, ensuring at each stage that user experience is not compromised.

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeUKRegProductIssues#821]
Priority to be established currently 0
Base upon learning with FreeCEN2

Needs #42

**Comment by AlOneill** [comment]
Each ad will require a skiplink (and destination) -- those who have to navigate by keyboard will need a way to skip over the 7 or more links in a single typical ad block.

**Comment by richpomfret** [comment]
Waiting on FC2 results before we give the go-ahead here.

**Comment by richpomfret** [comment]
We are now working with an advert company on this and have a suggested set of adverts/layout to add.

**Comment by Captainkirkdawson** [comment]
Replace by #2074
