### ISSUE TITLE
Consider the placement of adverts on other pages.

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeUKRegProductIssues#822]
Based on learning from FreeCEN2
Inc. ad on main page section of Transcriber sign-up see #1320

**Comment by AlOneill** [comment]
Again, each ad will require a skiplink (and destination) -- those who have to navigate by keyboard will need a way to skip over the 7 or more links in a single typical ad block.

**Comment by Captainkirkdawson** [comment]
I(s this not a duplicate of #821
