### ISSUE TITLE
57489047 Many Unprocessed Files (Stephen)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#825]
Issue reported by **steveroland** at 2016-10-27 09:10:47 UTC
Time: 2016-10-27T09:05:33+00:00
Session ID: c4cfc550a04a09dc7b09641edd30fda3
Problem Page URL: [/physical_files?page=](/physical_files?page=)
Previous Page URL: [http://www.freereg.org.uk/physical_files?page=](http://www.freereg.org.uk/physical_files?page=)
Reported Issue:
There are over 2000 unprocessed files. I found 4 Sussex files that were uploaded some time ago and should have been processed, so I've now submitted them, but there are likely lots for other counties sitting unprocessed too that need to be checked by coordinators.    

![Screenshot](http://www.freereg.org.uk)

**Comment by ghost** [comment]
There has been others who have passed along similar feedback. Some files are processing (at least 2 for Wales overnight) so not sure if this is a system wide issue or not.

**Comment by Sherlock21** [comment]
Interesting issue.
I found a couple of counties at random ( 2 out of 2) that did not have any pending.

So I looked as SSX and downloaded the one by suegagen.

seems OK to me EXCEPT that the header does not show character set ref in cell 1F. I though that was the outcome of the issue about weird characters appearing in the data some few months back? Is this not that case? 
Or is it only for non windows generated files or something?

**Comment by Captainkirkdawson** [comment]
Let us be very careful here. Do not mix 2 very different issues.
!. Files waiting to be processed. and 2) old files apparently never processed.

WRT 1) we had an issue with processing overnight on Sunday/Monday/Tuesday 23-25 Oct 2016. story 991 The problem was resolved for all except the one file responsible for the crashing. All waiting files were processed on Wednesday night. The only waiting files were entered today.
WRT 2) Yes there is a report that provides a listing of files that have been loaded into FR at some time and were never processed this was during the development period.  Many of the files were repackaged and reloaded under different names for different userid and the data that these original files MAY WELL BE IN THE DATABASE.  There was a massive effort by the 2 Erics and some coordinators to look at these files and do a reconciliation with FR1. This was undertaken in story 
30795964 Missing records from FR (Eric McMullin) #723 in March of this year.
As a result of their work they concluded that there WAS NOT AN ISSUE and that story was closed. So it WOULD BE VERY UNWISE for any person to just submit these files for processing without first determining that there is a real need. This specific report and others available in Physical Files are only available to DMs. CCs and SCs have access to the waiting list

**Comment by Captainkirkdawson** [comment]
PS There is no known bug

**Comment by edickens** [comment]
There are 2,176 files, but Kirk is correct.  These may have been 
uploaded.  However there are a few that have been uploaded recently.  
e.g. anchorman/LANLPEMA6.CSV on 16 Oct 2016.  (Kirk - Can the report be 
sorted by Date uploaded on request?  It needs to remain UserID as now to 
start.)

**Comment by Captainkirkdawson** [comment]
Have changed sort. Can still select for an individual

**Comment by Captainkirkdawson** [comment]
Suggest that DMs review the last first set of files for this year.

**Comment by Sherlock21** [comment]
re EricD 's comment 3 items above here, when he and I did a massive review of the historical problem many months ago, and concluded none of the listed files merited trying to process these, as their content had already got into FR by other means.
So I thought that they were all removed from the Awaiting Processing collection, and we started off with a clean slate at that point.
Am I not correct here please?
If I am, then what's happened to generate another 2000+ pile?

**Comment by edickens** [comment]
```
And this list includes a lot which were first uploaded years ago. 
So has the list regenerated itself?  E
```

**Comment by Captainkirkdawson** [comment]
There never was any request to delete the files. So the list has not "regenerated". it never went away

As noted above "Suggest that DMs review the last first set of files for this year." these have appeared since the initial study was done.

PS you can download the report as CSV file

**Comment by Sherlock21** [comment]
there are currently 4 files Awaiting Processing at this point in time in FR.
[16:06 on 28 Oct 2016 BST]
so what's the issue please? Am I looking at the wrong thing?

**Comment by Captainkirkdawson** [comment]
The report Steve was looking at was the Not processed ones
![notprocessed](https://cloud.githubusercontent.com/assets/2874694/19812614/86d07ec0-9cf3-11e6-8930-e0663607fe15.JPG)
contents are 
![notprocessed1](https://cloud.githubusercontent.com/assets/2874694/19812713/e4862ec0-9cf3-11e6-9a14-87d8f778d5e6.JPG)

I suspect that what is happening is the user uploads the file but does NOT select to process the file

**Comment by edickens** [comment]
So shall we just process them all?  BUT, if they have uploaded since, it 
will remove the latest additions.  Or is there a check for a more recent 
version existing?

To stop this happening again, should upload not take place until Process 
is selected?  Or do you think these are validate only and then never 
processed?

These are a lot of files to check for a more recent one in the system.

Interesting that we have not had a complaint from a transcriber that 
their work had not been processed.

A lot of these were from the early days, so shall we try processing 
those first of all?

**Comment by Captainkirkdawson** [comment]
Personally i would be careful!! I do not think anything should be done without investigation and consultation with the person(s) involved. They make have already acted when they did not get a message. Who knows I don't.
In my opinion one works from the most recent going backwards. We may find a pattern. ef there is one there from today which makes me think some one forgot to hit process
Will write a story to look at setting default for processing overnight.
But that will not address this list!!

**Comment by Captainkirkdawson** [comment]
Looking at the Anchorman there was an earlier file of that name loaded on 9 Oct so this looks like an unprocessed replacement BUT only user can say.

**Comment by Captainkirkdawson** [comment]
@Sherlock21  commented on a different story
On a quick check, 
although the online page of “Files not Processed", says: 2180 files, when I download them there are only 501.
There are 120 of these which are dated between 8 September 2015 and 30 Dec 2015
and the remaining 381 are all this year (2016).
So where are the rest please? and what happened on 8th Sept 2015 to give this start date?

**Comment by Captainkirkdawson** [comment]
Results are paginated. Hence you only get 500 at a go. To get at the others go to a different page.

**Comment by Captainkirkdawson** [comment]
@edickens commented
So are we also getting files left here if, when uploading, they select Browse and choose a different filename?  In FR1, the browse was really just to find the folder and it would not let you use a different filename.
NO the file name MUST be the same for a replace.

**Comment by Captainkirkdawson** [comment]
Found an issue with the report; fixed. There may be another I am researching

**Comment by Captainkirkdawson** [comment]
Followed a false trail. Believe the report is correctly reporting

**Comment by Captainkirkdawson** [comment]
@Sherlock21 privately reported that 3 files had been loaded under "wrong" names. Coordinator had  requested that they change their file name, Then amend the online file by downloading and uploading, then delete the wrong name file. 
Issue is; When coordinator deletes the batch for a userid the system does not remove the physical file entry for the userid but for the coordinator. Hence the list will grow. Will raise story to correct

**Comment by Captainkirkdawson** [comment]
In summary it appears there are 2 reasons for files appearing in this list. 1) A file has been uploaded or replaced and the user has not requested that it be processed See 995. and 2) When a batch is removed by a manager for a userid the physical file information for the userid is not amended. See 998. These "extra" entries are not hurting anything and can  be cleaned up as part of the story.
That leaves a decision on how to clean up those from 1)

**Comment by Sherlock21** [comment]
I can't keep up with the pace of this as its dinner time!!

separate email to Kirk with screen print of bit of downloaded trellised pages table suggests theres are duplicates in the present list of 1000.

**Comment by Sherlock21** [comment]
ALSO please could you change the text associated with the csv tab for downloading to indicate its Download the page you have selected only.?

i will write a new story later this evening if you can do it please.
this request is supported by 2 other CCs just surveyed.

**Comment by Captainkirkdawson** [comment]
Actually the CSV download only downloads the firs page!!!!!

Thats why there are duplicates when you combine.

Sorry about that

**Comment by Captainkirkdawson** [comment]
PS Never knew you used the csv download!!

**Comment by Sherlock21** [comment]
I didn’t until today.

But as I had an hour to spare this morning,I thought I would have a look at the subject of what’s involved to clear them out.

Little did I realise!!!
Anyway 
If we need them clearing up, then we need a bit of collective effort.  so…….
onward.
E

**Comment by suffolkroots** [comment]
_@Sherlock21 privately reported that 3 files had been loaded under "wrong" names. Coordinator had requested that they change their file name, Then amend the online file by downloading and uploading, then delete the wrong name file.
Issue is; When coordinator deletes the batch for a userid the system does not remove the physical file entry for the userid but for the coordinator.

This particular problem would never have arisen if we could edit file names online. In all 3 cases the code linked to church name was wrong.

**Comment by edickens** [comment]
With Sandra I have looked into an example of these files.  She found two which did not seem to have been processed.  So I set them for processing last night and got this:-
******************************************************************\* <br>
Started on the file CMNLFEMA41.CSV for AngieJ at 2016-10-30 01:26:43 +0100. <p>
The file CMNLFEMA41.CSV for AngieJ does not exist. <br>
******************************************************************\* <br>
Started on the file CMNLNFMA05.CSV for AngieJ at 2016-10-30 01:26:43 +0100. <p>
The file CMNLNFMA05.CSV for AngieJ does not exist. <br>
******************************************************************\* <br>
I don't know if this is any help in resolving the problem.
Eric

**Comment by Captainkirkdawson** [comment]
WRT to comment by suffolkroots there is no correct/incorrect file name as far as system is concerned. The file no matter what its name connects to the correct church.

**Comment by Captainkirkdawson** [comment]
WRT comment by @edickens. I am not surprised. That is what would happen under the situation described in 998

**Comment by suffolkroots** [comment]
WRT to comment by Captainkirkdawson for admin purposes each church needs a unique code. Should this be entered wrongly by transcriber it has to be corrected. It would be useful to be able to do this online.

**Comment by Captainkirkdawson** [comment]
New story generated

**Comment by Captainkirkdawson** [comment]
@Sherlock21  wrote Regarding  almost all of the files listed in this now 910 (for some reason reducing)  were now non existent files in terms of my being able download a copy and have a look, i am totally bemused.

Can we recap please?
Tell me please exactly  what conditions put a file into this category? 
and if it got into the list some time in the past, how does it now get to the state of being Not seeable online?
Not downloadable?

How then, given my success rate of only 1 out of 11 at random behaved like a normal file, - i.e. have a file name and some content even if its empty after the userid/filenmae and header rows, are we to make any headway in determining if they are still needed?

Let alone if we find one that has a userid + Filename +date loaded into FR waiting, but no content, and there is no matching filename in FR - a situation which I have not yet involved CC's in looking for.

instead of me trawling through the 914 list to see if the file is Genuine, ( at 11 an hour would be 9 solid days of excitement), Can we not get a little bit of code to do the lookup for content in the filespace thats listed behind the Not Processed list, to determine if there is any actually data there? i.e. in PC speck for these files with a file size greater than what;s needed for the header alone?

**Comment by Captainkirkdawson** [comment]
As written earlier
In summary it appears there are 2 reasons for files appearing in this list. 1) A file has been uploaded or replaced and the user has not requested that it be processed See 995. and 2) When a batch is removed by a manager for a userid the physical file information for the userid is not amended. See 998. These "extra" entries are not hurting anything and can be cleaned up as part of that story.
As concluded you do not have to do anything wrt those in 2). 
There are some that "likely" need processing but not my decision.
If you start with the most recent in the Not processed display.
If you click on the show you will get what we know about the file
![explanation1](https://cloud.githubusercontent.com/assets/2874694/19839354/c2297ca2-9ea5-11e6-8e0f-20217ceeef7c.JPG)
If a user uploaded a new file then you will see 
![explanation2](https://cloud.githubusercontent.com/assets/2874694/19839359/dba2c9a4-9ea5-11e6-8a81-2ad7a6da9fe5.JPG)

If they did a replace then you would see
![explanation3](https://cloud.githubusercontent.com/assets/2874694/19839368/eec8d0fa-9ea5-11e6-87b4-74522881f236.JPG)

Perhaps those that look like the last should be submitted for processing.

**Comment by Captainkirkdawson** [comment]
Final comment. 
We are shutting system down in a few hrs so likely nothing can be done until much later.  
I am then away for 5 weeks so if my input is needed it will have to wait

**Comment by Sherlock21** [comment]
OK

I have started to write up my test report for the upload of  files for Processing.

Conclusion is: put it into practice. i am fine with it.

it automatically sorts small uploaded files and processes them Now
And put larger files into the overnight Processing collection.
in each case, an onscreen message correctly advises the uploader what is  happening, and issues an email when the processing is completed.

I tested out both sizes of files, and both work correctly, with the right messages.

It is clear and simple, and does not rely on the Uploaded remembering to make a choice and then confirm the action.
eb

**Comment by ghost** [comment]
Can this be closed now?

**Comment by Captainkirkdawson** [comment]
No there are still 60 files that the Eric's have to review

**Comment by ghost** [comment]
Are any of the remaining 60 files from Welsh counties?​

---

Sandra Adams-West
_FreeREG Communications Coordinator_
____________________________________________________________________________________

**Comment by Sherlock21** [comment]
I will have a look soon.

it depends iif the related job of letting me print ALL the list (, instead of just the first page) has been done. - on a differnt # job I think?

E B

**Comment by ghost** [comment]
I think this could be closed now. Unless there are still some running around?

**Comment by Captainkirkdawson** [comment]
There are 32 batches still recorded as not having been processed, This should not be closed until the status of these files has been reviewed and resolved either by processing or deleting.

**Comment by Sherlock21** [comment]
I am working through them slowly, with the CC concerned. but its hard work.
Yes, close this job.
