### ISSUE TITLE
57574346 Reset password is reporting invalid token (Eric)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#827]
Issue reported by **REGManager** at 2016-10-28 08:52:26 UTC
Time: 2016-10-28T08:49:22+00:00
Session ID: 98638a54bb2310b767d4a7716e97fd0f
Problem Page URL: [/userid_details/5805cd86f493fd7d7ef9857e](/userid_details/5805cd86f493fd7d7ef9857e)
Previous Page URL: [http://www.freereg.org.uk/userid_details/selection?option=Select%20specific%20surname/forename](http://www.freereg.org.uk/userid_details/selection?option=Select%20specific%20surname/forename)
Reported Issue:
I have tried everything with Anne Bonner.  She has changed email address to a gmail.  I have resent password resets.  Still she cannot sign up properly.
Our emails:-
Hi Eric

I got the gmail reset password email but when I try to change it it says Reset password token is invalid.

Regards 

Anne

From: Eric Dickens-gmail freereg.edickens@gmail.com
Sent: Thursday, 27 October 2016 4:07 PM
To: Anne Bonner
Subject: Re: Thank you for question about volunteering. Reference 56706945

Hi Anne,

Have changed to your gmail account and will send another password reset just after this email.

We have had problems with ISP filters, but that has been blueyonder.

Regards,

Eric

---

Eric J Dickens
FreeREG Chairman

On 27/10/2016 02:21, Anne Bonner wrote:

> Hi Eric
> 
> This is really strange, I didn't receive the password reset email that you sent, nor the one that I sent yesterday. I have a gmail email, avbonner66@gmail.com, maybe I should use that one. What do you think? I really don't know what else to do. 
> 
> Thank you.
> 
> Regards
> 
> Anne
> 
> From: Eric Dickens-gmail freereg.edickens@gmail.com
> Sent: Thursday, 27 October 2016 2:00 AM
> To: Anne Bonner
> Subject: Re: Thank you for question about volunteering. Reference 56706945
> 
> Hi Anne,
> 
> I can't see a problem.  I'm going to send you a password reset, which you should get immediately after this message.
> 
> Let's see if that works.
> 
> Regards,
> 
> Eric
> ---
> 
> Eric J Dickens
> FreeREG Chairman
> On 26/10/2016 02:29, Anne Bonner wrote:
> 
> > Hi Eric
> > 
> > I did receive an email quoting my reference number 56706945 and that someone would be in touch in 2 business days. There's nothing in my Junk email. I have also received Jo's email re setting me up for transcribing. I have tried logging in but the system wont let me. 
> > 
> > I have even tried to reset my password but the email to do so didn't arrive.
> > 
> > Thank you.
> > 
> > Regards
> > 
> > Anne

![Screenshot](http://www.freereg.org.uk)

**Comment by edickens** [comment]
Anne reports that since the rebuild she has been able to change her password.  This can be Closed.  E

**Comment by ghost** [comment]
Closing as per Eric
