### ISSUE TITLE
57565778 0 date (Ali)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#828]
Issue reported by **alsibk** at 2016-10-28 06:29:38 UTC
Time: 2016-10-28T06:09:33+00:00
Session ID: b07a90eb6d20b77fd3a4766ad5680aff
Problem Page URL: [/freereg1_csv_entries](/freereg1_csv_entries)
Previous Page URL: [http://www.freereg.org.uk/freereg1_csv_files/57ed66b0f493fd6006f3ebd4](http://www.freereg.org.uk/freereg1_csv_files/57ed66b0f493fd6006f3ebd4)
Reported Issue:
I have a file showing 0 start date (not entirely sure whether we should interpret this as BC, AD or even limbo) which appears to be caused by one extra line at end of file with no record. Please could we have an end to 0 dates.    

![Screenshot](http://www.freereg.org.uk)

**Comment by richpomfret** [comment]
The data needs to be corrected here in order to avoid the 0 start date appearing. Delete the extra line and this should disappear..

**Comment by Sherlock21** [comment]
Are you sure your advice is correct, Richard?

These 0 start dates occur whenever the date in one of the records ing the file is in the form "5 Jul \* " 
or even just *
i.e. without a 4 digit year.

If the original record had no year - or was illegible, then our basic Transcribing Rule says TWYS and as there is no year there for the Transcriber to type -  our rule 2 says use the format which I give above.

**Comment by Sherlock21** [comment]
Closing the issue is a little premature in my view.
The preferred logic is to change the logic of the coding.

**Comment by edickens** [comment]
```
I agree that this is a situation which will give rise to the 0 year
and it is not an error.

But how does the search work when someone asks for a range of years
which might include this record because it is within the years
covered by the register and the year can often be deduced?  I think
we need an exception to the TWYS, or we need a "Transcriber's assume
year" field.

Leaving 0 years statements to the researcher is confusing.

E

  On 31/10/2016 19:45, Sherlock21 wrote:


  Are you sure your advice is correct, Richard?
  These 0 start dates occur whenever the date in one of the
    records ing the file is in the form "5 Jul * " 
    or even just *
    i.e. without a 4 digit year.
  If the original record had no year - or was illegible, then our
    basic Transcribing Rule says TWYS and as there is no year there
    for the Transcriber to type - our rule 2 says use the format
    which I give above.







  {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/FreeUKGen/FreeUKRegProductIssues","title":"FreeUKGen/FreeUKRegProductIssues","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/FreeUKGen/FreeUKRegProductIssues"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Sherlock21 in #828: Are you sure your advice is correct, Richard?\r\n\r\nThese 0 start dates occur whenever the date in one of the records ing the file is in the form \"5 Jul * \" \r\nor even just *\r\ni.e. without a 4 digit year.\r\n\r\nIf the original record had no year - or was illegible, then our basic Transcribing Rule says TWYS and as there is no year there for the Transcriber to type -  our rule 2 says use the format which I give above.\r\n"}],"action":{"name":"View Issue","url":"https://github.com/FreeUKGen/FreeUKRegProductIssues/issues/828#issuecomment-25739936
```

**Comment by Sherlock21** [comment]
I agree with your, Eric D

I have said in other audiences, that the only practical way to handle these sort of dates is to use the YEAR only, and take this year from the next useable record immediately prior to the unreadable/missing record and put an explanation in the notes:-
"This record has an illegible year ( or has no year given) but is in the Register immediately after the year used here. Researchers should consult the original if it matters".

That will cure the 0 date year problem and will assist the researcher.
