### ISSUE TITLE
Place name error when changing (Howdy)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#83]
Issue reported by **Howdy** at 2014-11-23 19:17:17 UTC
Time: 2014-11-23T19:16:04+00:00
Session ID: b6930c8b37159a9a9b4ed275aba34366
Problem Page URL: [/places?page=4](/places?page=4)
Previous Page URL: [http://test2.freereg.org.uk/places](http://test2.freereg.org.uk/places)
Reported Issue:
Hi Kirk,

I've been changing erroneous place names to correspond to the correct ones.  I often get an error message when making the change.

This message would not transmit with a file attached.

Howard    

![Screenshot](http://test2.freereg.org.uk)

**Comment by Sherlock21** [comment]
Howard: email me a name that you wish to "change" and spell out how you would do it your way. [ dont actually do it though]. i will have a look at your method and get back.
Which  "Name: have you successfully changed by your method?

ericb

**Comment by Captainkirkdawson** [comment]
Did you and Eric resolve this?

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Sherlock21** [comment]
K

No, Howdy never came back to me so no idea what he was doing or if he managed to find his own solution.

EricB

**Comment by Captainkirkdawson** [comment]
Insufficient information on which to mount any investigation
