### ISSUE TITLE
UCF dates to be retrieved in date bounded search

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeUKRegProductIssues#832]
Alternative to abandoning TWYS on dates: UCF dates are ignored in counting decadels.

**Comment by edickens** [comment]
Just UCF Years.

**Comment by Captainkirkdawson** [comment]
Do not understand.  There are multiple stories here.
Moving away from TWYS is dangerous 
The search currently retrieves records with UCF dates in basic searches so the correct solution is to use the UCF in date bounded searches.
We can ignore UCF year dates in the datemin calculation if required.

**Comment by edickens** [comment]
We have not done the Help to this level of detail for researcher yet.  
Would they know how to use UCF in dates?

Information please.  If I ask for 1735 to 1755 in a search, will it 
include:-
174_
17*
*
1745?

All are valid UCF.

I think a researcher should be able to enter the year range that they 
are looking for and get all records that appeared in the registers 
during that period.

E .

**Comment by Captainkirkdawson** [comment]
The search does not find dates containing UCF in a date bounded search. The story should be that it does.

**Comment by Captainkirkdawson** [comment]
email with test file sent to @benwbrum 
example shown below
![seele1](https://cloud.githubusercontent.com/assets/2874694/19948918/a8106706-a114-11e6-8a32-76b3a237304c.JPG)
![seele2](https://cloud.githubusercontent.com/assets/2874694/19948935/b33f68c0-a114-11e6-9e58-57dc7f0e462c.JPG)

**Comment by Captainkirkdawson** [comment]
09 Apr 1_27 creates a "search_date" : "1_27-04-09"

**Comment by Captainkirkdawson** [comment]
"24 Aug _" creates a "search_date" : "_-08-24"

**Comment by PatReynolds** [comment]
Changed 'guess' to 'deduced'.  See Eric B's email for how dates can be deduced.

**Comment by benwbrum** [comment]
I've just finished a full review of the UCF date support in the system, and it seems that the existing code is far more limited than I recalled.

Currently, year digits or decade digits which are expressed with an underscore are getting assigned a searchable date in the middle of their decade or century.  However, this is not full UCF support, as the (very common) use of asterisks is not handled, nor is the less-common use of underscores in the middle of a year,, asterisks in place of the entire date, or square braces.

**Comment by PatReynolds** [comment]
See #852 for possible temporary fix

**Comment by Sherlock21** [comment]
So, what exactly is the proposed permanent fix (or change) please?

**Comment by benwbrum** [comment]
This is fixed in the source code for new uploads, but we need to remediate old records.  I'm running a script on brazza to identify those records.

**Comment by benwbrum** [comment]
The script is finished, and--to my astonishment--only identified a handful of records with asterisks in dates.  I'll try to put together a list for review, since I don't really trust this as a result.

**Comment by Sherlock21** [comment]
If you do a csv file, including County/ Placename/ church as well as the userid/ filename, I will have a look over the result, Ben if you wish?
And spell out what date characteristics SHOULD be in the list, I will work backwards for my own files to see which of mine should be in your list.

**Comment by edickens** [comment]
Ben.  It isn't just asterisks to represent the whole date which are the problem.  Underscores, brackets, and perhaps question marks, cause a wrong year, which will be out of the range of the transcription, to be created.
Is this something which should wait until we have extra fields.  I would like to see "Transcriber assumed year" which can be deduced from the position in the register, just as we need "Transcribers notes" to distinguish it from notes in the register.  ED

**Comment by benwbrum** [comment]
I'd appreciate a second set of eyes on this listing of the dates in the production system which contain an asterisk following a digit.  It looks suspiciously short to me.

[asterisk_search_date.txt](https://github.com/FreeUKGen/FreeUKRegProductIssues/files/1200125/asterisk_search_date.txt)
[asterisk_secondary_search_date.txt](https://github.com/FreeUKGen/FreeUKRegProductIssues/files/1200124/asterisk_secondary_search_date.txt)

**Comment by Sherlock21** [comment]
#["13 Apr 1922", "1_ Oct 18*"]
57e3a0acf493fd917030e06a
The above is a value style at present but is no use to anyone as the year is impossible to handle.
#["30 Sep 1792", "1* Aug 1792"]
585b7a5bf493fda71602bfc0
The above is NOT valid. the * should be an underscore as its only one digit.
#["09 Jul 1853", "18 Nov 185*"]
5850a295f493fd8e18100d41
The above is invalid se of *. it should be underscore if its UCF. BUT its no use then either - it needs to adopt the guide for handling incomplete year values.
#["17 Jul 1865", "13 Sep 18**"]
5634caf5f493fd4a1f000060
The above is a double sin! see above comment abut year. It should be single *, but even then its no use to us really.

My concluding comment is that I think there should not be any *'s in a date value except in the form: * 1652.

**Comment by edickens** [comment]
Ben
I think many would have used underscore not asterisk for just one character missing, and that is enough for the date to produce a zero.
EricD

**Comment by benwbrum** [comment]
I'd agree -- we are handling trailing underscores correctly, but need to address internal underscores as well.

**Comment by Captainkirkdawson** [comment]
EricD This story is nothing to do with zero. It deals with "correctly"
processing the UCF in a date especially in a year. ie we handle 1_78, 17_7
and 177_ as well as 1*, 1*7, *78, and 17*

EricB why is 18* a double sin?  why is it impossible to handle? It should
be retrieved for any search that includes 1800 to 1899

Kirk Dawson
5220 Riverside Drive
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Sherlock21** [comment]
I agree that my 'Double Sin' comment was not the best choice of phrase
I should have said that * can stand for one missing character or for more than one ( in the guidance notes). But since its Year, and we know that years have 4 digits unless they are pre 1000 AD, there are 2 missing digits there - unlike the one missing year in all the others in Ben's list.
In fact its probably the best example in his set!

**Comment by SteveBiggs** [comment]
This raises the question - should we allow pre-1000 AD dates to be transcribed? There are sources for Royal lines that give such dates, so why not include them? That would mean 18* could be 180 to 189 or 1800 to 1899. 18_ must be 180 to 189 and 18__ must be 1800 to 1899, etc.

I just searched for John Smith, from year 1 to 999 in all counties and received one result:

![Capture.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/588631f51e19621a00230146/125516c66e82c728ace21e0d46cb958a379791accda5fd53b652fa912a5265296b51f02e7384e671e6162351580d4bac43585f45ffac8928f0a42062c80d55b98e30063e937f03a6aa8717b804b0218e4f87beb48e4ec8e93523ee99c2.jpg)

I then revised the dates to between 1000 and 1500 and get NO results:

![Capture.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/588631f51e19621a00230146/125516c66e82c728ace21e0d46cb958a379791accda5fd53b652fa912a5265296b51f02e7384e671e6162351580d4bac43585f45ffac8928f0a42062c80d55b98e30063e937f03a6aa8019b500bf2089478db2b98944c2ea3d37aa.jpg)

**Comment by Sherlock21** [comment]
I recall  one CC recently asked the question: how to put in records that she had access to, where the dates were in fact pre 1000AD.
I recall suggesting: use the format 0964 for the year ( OK if you format the field as Text) then the software checking that the year is a genuine year, sill has to find 4 digits.
The suggestion seemed to fall by the wayside though.

**Comment by SteveBiggs** [comment]
Seems reasonable to me. The year could be BC too .....

**Comment by edickens** [comment]
Can't be BC because we are using Parish Registers.
Also, a lot of the old marriages, such as the Kings and the Plantagenet line (my partner's lineage is direct into this line) are just extracts.  Although of interest, they are not of much use to most researchers.

**Comment by SteveBiggs** [comment]
Are we restricted to Parish Registers ONLY? That would rule out monumental inscriptions that were never recorded in a register and all other historical documents that may be available with BMD data that would be useful to some researchers - especially if like your partner (and me), they are in your lineage.

**Comment by edickens** [comment]
No, we need to be more pragmatic.  FreeBMD and FreeCEN do not go back further than 1837, so we need to fill that gap.
But BC monumental hieroglyphs could pose a problem.

**Comment by benwbrum** [comment]
This story has drifted -- we now handle asterisks in dates, but need to do a rebuild of the affected records.  I'm not sure what to do with the ensuing discussion about BC dates.
