### ISSUE TITLE
58466908 CONLDUMA..error (Doreen)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#835]
Issue reported by **deo123** at 2016-11-07 16:48:28 UTC
Time: 2016-11-07T16:43:33+00:00
Session ID: 8026cecaefdc442ed38c1ac37c95b6f0
Problem Page URL: [/freereg1_csv_entries](/freereg1_csv_entries)
Previous Page URL: [http://www.freereg.org.uk/freereg1_csv_files/57843bd4f493fd84f70003cc](http://www.freereg.org.uk/freereg1_csv_files/57843bd4f493fd84f70003cc)
Reported Issue:
replaced a file and it only produced the last record. Overwritting the file with one record....

The message from FreeREG .....
Started on the file CONLDUMA.CSV for Barty at 2016-11-07 15:14:24 +0000.

While processing continued there were the following header warnings.

There was only one header line.
Updating the current batch for CON, Landulph, St Leonard, Parish Register.
1 records were processed of which 1 were updated/added and 0 had data errors.

Created 1 entries at an average time of 101000ms per record at 2016-11-07 15:16:05 +0000.     

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Not sure what the user who commented was requesting, The statements made are factually correct the uploaded file has 1 header record and 1 data entry, So the system did what was expected.
Now looking at the uploaded file it has had all but 1 CR/LF eliminated. The one header lane includes all headers and almost all entries as 1 line. The next line has all of the remaining entries in 1 line.
The file needs to be correctly formatted with line endings and resubmitted

**Comment by edickens** [comment]
Problem solved.  File now uploaded successfully.  This can be Closed.
