### ISSUE TITLE
58586964 File processing shows file missing  (Susan)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#837]
Issue reported by **hawkinssm** at 2016-11-09 02:09:24 UTC
Time: 2016-11-09T02:03:55+00:00
Session ID: 6bd0796f7be94ef008ffac9b9dabaa96
Problem Page URL: [/freereg1_csv_files?page=4](/freereg1_csv_files?page=4)
Previous Page URL: [http://www.freereg.org.uk/freereg1_csv_files?page=3](http://www.freereg.org.uk/freereg1_csv_files?page=3)
Reported Issue:
The file KENDEDBU10.CSV for PeterDavidEvans processed successfully at 2016-11-08 02:06:58 +0000.  
But the next day(today)
file KENDEDBU10.CSV for PeterDavidEvans at 2016-11-08 15:34:47 +0000. The file KENDEDBU10.CSV for PeterDavidEvans does not exist. Can you help with this as when checking the web site the file is showing but with a last change date of 30/10/2016.    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Since the file was reprocessed  on the 10th of November successfully it is no longer possible to investigate this issue.

Started on the file KENDEDBU10.CSV for PeterDavidEvans at 2016-11-10 01:31:28 +0000.

**Comment by ghost** [comment]
closed as file was successfully reprocessed.
