### ISSUE TITLE
58956428 File relocation not working (Anna)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#838]
Issue reported by **AMSA** at 2016-11-13 08:47:08 UTC
Time: 2016-11-13T08:44:48+00:00
Session ID: f2e1d10d246de49050231240ba34c71b
Problem Page URL: [/freereg1_csv_files/5463830de9379010fc090fbc](/freereg1_csv_files/5463830de9379010fc090fbc)
Previous Page URL: [http://www.freereg.org.uk/registers/5407d8eaeca9eb024813c554](http://www.freereg.org.uk/registers/5407d8eaeca9eb024813c554)
Reported Issue:
I have not been able to make any file relocations since the last update. It tells me it has tried reloading too many times & I should check my cookies (which I have done to no avail)     

![Screenshot](http://www.freereg.org.uk)

**Comment by ghost** [comment]
Doreen also reported basically the same issue saying that she had been given the message 'the server cannot redirect as the link is not complete.'

**Comment by Captainkirkdawson** [comment]
For everyone's information the last update was NOT a software update, We have been using the same software for sometime now, In the last update we updated the data,

**Comment by edickens** [comment]
But didn't you deploy the new uploading pages?  Only minor really. E

**Comment by Captainkirkdawson** [comment]
Unable to duplicate. I relocated the file to a  Dwellies just as a test. See
![relocation](https://cloud.githubusercontent.com/assets/2874694/20247537/f66ff216-a98b-11e6-9390-8624621efec9.JPG)
The coordinator should try again. It is essential that there be no attempt to use the back button during any part of this process

**Comment by Sherlock21** [comment]
Kirk

I can do Relocate no problem, with my ID

but using the ID of a CC, it does not work.

eb

**Comment by edickens** [comment]
Should not be offered if a CC cannot relocate.  But I think a CC should 
be able to.  E

**Comment by ghost** [comment]
CCs had this ability before. I tried in a Welsh county and it is not
working. Is there any particular reason this might have been taken away?
​

---

Sandra Adams-West
_FreeREG Communications Coordinator_
____________________________________________________________________________________

**Comment by Sherlock21** [comment]
The Relocate button is the only way to change the Register Type of a single file, if its in a group of several files in one church.
In these circumstances it seems fine for a CC to do it. but it would be possible if done wrongly to move a file to a different County!

could it be that the reload job slightly changed the CC's profile?

or is it to do with the  browser as that's where the error message comes from.?

**Comment by Sherlock21** [comment]
here is the Safari screen message when it crashes me out of Fr completely, as I try to do Relocate a batch. same in t3 and in Production.

There is no means of adding an image to this so its in an email to Kirk & EricD

**Comment by Captainkirkdawson** [comment]
Have located he issue but no fix yet

**Comment by Captainkirkdawson** [comment]
I believe it to be fixed and works for both CC and DM.

This needs to be confirmed by DM as both DM and CC before getting CCs to use

**Comment by Sherlock21** [comment]
I have just tested this fix out both T3 system and in Production, for both DM and CC profiles and it works fine ( for me).

So OK to use by CC's

**Comment by Sherlock21** [comment]
close this ticket now please.
