### ISSUE TITLE
58903828 Witness with 2 forenames incorrectly displayed  (Mick Claxton)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#839]
Issue reported by **Mick Claxton** at 2016-11-12 18:10:28 UTC
Time: 2016-11-12T18:03:59+00:00
Session ID: 83b5fe905b391bdba311cd9de9f7b654
Problem Page URL: [unknown](unknown)
Previous Page URL: [http://www.freereg.org.uk/contacts/581811a7e93790eb7f23dc65/report_error?query=5827594cf493fd749c5ed799](http://www.freereg.org.uk/contacts/581811a7e93790eb7f23dc65/report_error?query=5827594cf493fd749c5ed799)
Reported Issue:
If a marriage witness has two or more Christian names then the search is ignoring the surname when returning a search result..
As an example. The wedding in Whaplode, Lincolnshire 28 May 1878 between Jabez FLETCHER and Rosetta FARROW. The second witness was transcribed as Alice Parnham FLETCHER but in the search result she is returned as Alice Parnham and her surname is ignored.
 This is the third time over a number of months that I have reported this issue but it has not been fixed.    

![Screenshot](http://www.freereg.org.uk)

**Comment by edickens** [comment]
I have followed this up and given details to Mick.  The server is
    showing the information correctly.  But the second forename of the
    second witness is in the surname field and the surname is lost.

```
If this is an uploading problem we could have lost many surnames of
people with two or more forenames.
```

**Comment by edickens** [comment]
If this is an upload problem, where a second witness forename has 
replaced the surname, can we list the UserID/Filename of any record 
where the second witness surname is lower-case?  This will identify 
those records with a problem.  E

**Comment by richpomfret** [comment]
To discuss further in our sprint-planning meeting. Ben to explore.

**Comment by Captainkirkdawson** [comment]
Before Ben does anything to investigate this story, which would likely be a waste of his time. I believe I know the source of the issue,
But first of all could EricB conduct a test upload of a batch that has witnesses with several forenames. I believe that this will confirm that the upload and search code are functioning correctly.
The problem is I think a result of a task run in September 2015 to create the multiple witness collection that did not correctly handle multiple forenames, The issue will affect only batches loaded and unchanged up until that date. Since the original entry contains the multiple forenames and correct surname it should be possible to retrieve and correct the affected records.

**Comment by edickens** [comment]
Kirk,

I don't think that the test needs doing because there are entries there 
with two names that have worked correctly.  I think your reasoning is 
correct.  What we need to do now is to identify which entries need 
correcting.  So any entry with a witness surname in lower-case will need 
to be uploaded again.  We just need a list.  E

**Comment by edickens** [comment]
I asked Mick to replace the file to correct the entry and he reports:-
Just replacing the file didn’t work. I got the message from the server that zero records had been updated, and when i did the search  the surname was still ignored.
In the end i had to delete the file on the server and then upload it again and this appears to have fixed it .
If this is the only way to do it’s going to be very time consuming, i guess there are a large number of Norfolk and Somerset files that are in the same boat.
Mick

**Comment by Sherlock21** [comment]
Prompted by Eric D's comment about Replace failed, i just did a Replace File in Test3 on the records I am using here for Kirk's other tests, and it worked fine for me.

**Comment by edickens** [comment]
Mick was replacing the file but with no changes.  So his CSV version 
would be the same as that on the server.  His file was correct but the 
server has saved it incorrectly.  At least that is what it looks like.  E

**Comment by Sherlock21** [comment]
But if the Server file is not the same as Mick's file, then surely it will see the Reload as a revision and action it.

Is he in Production? I am testing in T3 some revised code so perhaps he needs to wait this going over to Prod? I have advised Kirk that my testing has not found any snags in the revised code at all. - so perhaps await this afternoon's shift starting.

**Comment by Captainkirkdawson** [comment]
EricD it is always essential to ensure the hypothesis is correct before going further. The testing by EricB has confirmed the hypothesis. 
There is no software difference between test3 and production at this time and nothing was deployed to correct the hypothesis.
A straightforward replacement of a file will not self correct but with a small tweak it can be made to so do, Developing a rake task to do the correction would be as straightforward as doing one to produce the list.
Given that I have no access to my development server it is unlikely I can do anything to fix this until my return

**Comment by edickens** [comment]
Hi Kirk,

The report I had from Mick was "I got the message from the server that 
zero records had been updated".  So I assume that the file processed but 
did not find any changes.  Would this be correct?

So are the Surnames of the witnesses with two or more forenames still 
somewhere in the system?  When I downloaded the file, the entry that we 
are looking at had the second forename in the surname field.  I assumed 
that the download had taken that from the surname field and hence the 
original surname had been overwritten.  Mick's file is correct.  Do I 
need to get him to force an replace by making an alteration and try again?

**Comment by Captainkirkdawson** [comment]
That is what I would have expected. The test for replace looks to see if the  entry version of the witness ie witness1 or winess2 has changed. It has not hence will not replace.
A download will download from the multiple_witness collection hence you will get a "damaged" file with incorrect information.
The only way that you or he can fix is by deleting the file and all its records and then reloading. This is a painful way of fixing the problem from a user and system performance perspective.
Given that the issue has been with us a year why not wait for it to be fixed as suggested above.

**Comment by edickens** [comment]
To be clear.  Will all these entries with multiple witness forenames 
have to be fixed this way.  There could be a lot.

Can Ben run a search for lower-case witness surnames to see how many 
there are?

**Comment by Captainkirkdawson** [comment]
Sorry do not understand "fixed this way". I do not want to see you or others trying to fix this by deleting a file and then reloading it. 
Please wait for an automatic correction process.

No idea on Ben"s availability.

**Comment by edickens** [comment]
Will do.  No hurry.  E

```
  On 15/11/2016 18:09, Kirk Dawson wrote:


  Sorry do not understand "fixed this way". I do not want to see
    you or others trying to fix this by deleting a file and then
    reloading it. 
    Please wait for an automatic correction process.
  No idea on Ben"s availability.
```

**Comment by benwbrum** [comment]
I'll be available week after next, and would love to tackle this.  If I
paired with Alex, it might be a good introduction to the code for him.

Ben

**Comment by Captainkirkdawson** [comment]
Not sure I would say that was a high enough priority especially as it is a clean up rather than a bug

**Comment by Captainkirkdawson** [comment]
A rake task to take the entry witness information and correct the multiple witness record with an update of the search record based on the changes in the multiple witnesses has been written and tested on vervet. Mick has been asked to review on a specific file before going further.

**Comment by Captainkirkdawson** [comment]
Mick has confirmed that the witnesses for one file was correctly transformed. Now running a larger volume test on vervet

**Comment by Captainkirkdawson** [comment]
Mick has confirmed that his userid batches have been corrected on test3 including those with more than 2 forenames.
Have commenced a background task on colobus to make the corrections

**Comment by Captainkirkdawson** [comment]
There were 330,000 forenames with more than one name on vervet. Correction completed there.
Still underway on colobus expect 3-4 days.

**Comment by Captainkirkdawson** [comment]
Correction of production servers is complete
Randon check by Erics and Mick should be undertaken

**Comment by ghost** [comment]
Can this issue be considered closed once checks by the Erics and Mick are
completed?​

_________________________________________________________________________________

Sandra Adams-West
*FreeREG Communications Coordinator*
*__________________________________________________________________________________*

**Comment by edickens** [comment]
I thought Mick had said that it was OK.  E

**Comment by Sherlock21** [comment]
I dont have WinReg so i can’t do anything with these.

EB

**Comment by Captainkirkdawson** [comment]
This has nothing to do with WinREG

Mick checked test3 I have no idea if he checked production

Kirk Dawson
5220 Riverside Drive
Fairmont Hot Springs, B.C.
V0B 1L1
