### ISSUE TITLE
Testing of screenshot (Captainkirk)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#84]
Issue reported by **Captainkirk** at 2014-11-23 23:53:04 UTC
Time: 2014-11-23T23:52:00+00:00
Session ID: 1f2190a0558072a0114aec9c501a7462
Problem Page URL: [/feedbacks](/feedbacks)
Previous Page URL: [http://test2.freereg.org.uk/manage_resources/new](http://test2.freereg.org.uk/manage_resources/new)
Reported Issue:
Several people have reported issues    

![Screenshot](http://test2.freereg.org.uk/tmp/carrierwave/1416786784-18452-3545/_0.JPG)

**Comment by Captainkirkdawson** [comment]
There was a permissions problem with the tmp/carrierwave folder. Now fixed

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1
