### ISSUE TITLE
58822983 Link not working (Joanne)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#840]
Issue reported by **ManCity** at 2016-11-11 19:43:03 UTC
Time: 2016-11-11T19:41:46+00:00
Session ID: d9332f543aa1549c525e35b27b6acd2c
Problem Page URL: [/manage_resources/new](/manage_resources/new)
Previous Page URL: [http://www.freereg.org.uk/cms/refinery/login](http://www.freereg.org.uk/cms/refinery/login)
Reported Issue:
This link is none-responsive:
http://www.freereg.org.uk/information-for-transcribers/entering-data-from-registers#regCodes    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Unable to duplicate.
The reported link is not a correct link. All help pages are located as shown below. Note the cms/ before the page name. It looks like the user is using an old link perhaps an old bookmark.
http://www.freereg.org.uk/cms/information-for-transcribers/entering-data-from-registers#regCodes

**Comment by richpomfret** [comment]
We suspect this is an old or outdated link - potentially from the old version of the site.
