### ISSUE TITLE
Enable UCF search feature on production

### ISSUE THREAD

**Issue by richpomfret** [FreeUKGen/FreeUKRegProductIssues#843]

**Comment by Captainkirkdawson** [comment]
I would be extremely reluctant to see this done until 1) we had done a performance impact assessment on vervet ans 2) addressed the 2 outstanding performance issues on production 1007  update performance  and 465 search indexes

**Comment by benwbrum** [comment]
I'll be throwing myself at this on November 28th, and will try to reassess
these as part of the process.

Ben

**Comment by benwbrum** [comment]
TODO:
add new index on place_id, record_type, search_date, secondary_search_date
Eliminate params.merge!(name_params) from search_params.rb

Deploy new revised_index branch on brazza
test that for performance
enable UCF on brazza
test that for performance

cc @Captainkirkdawson

**Comment by Captainkirkdawson** [comment]
Processed a test file on test 3 which has 6 UCF records. 

MCKERON?, GRA_NT, SHE_{2,3}ER, MCR__OBERT, HUTCH[E_]SON,  and GRE[EI]N

We create a ucf list in Aberlour.

The Place Aberlour has 4 ucf search records  for the file 5890df4ee937907d388855a4

GRA_NT,  SHE_{2,3}ER, MCR__OBERT, and HUTCH[E_]SON (This record contained 2 entries for ucf origin field of hutcheson

Results

1. We have missed the trailing ? This is a significant isse

2.GRA_NT is found by any search with a letter in the 4th character of GRAXNT where X is any character. This is correct

3. SHE_{2,3}ER is only found by a search for that. This is not correct It should be found by sheaaer or sheaaaer

4. MCR__OBERT is only found by a search for that.  This is not correct It should be found by searches like macrooobert or maccreaobert

5. HUTCH[E_]SON is found by a search for HUTCHESON by the results also include HUTCH[E_]SON (not as UCF). HUTCHASON does not give a result Partially correct

6. GRE[EI]N is found by Green and also by Grein but the later gives a display of  GRE[EI]N. Partially correct



 "ucf_list" : {
                "57917cd2f493fddf7b00ef0c" : [
                        ObjectId("5817a9e0e93790eb7f5918c2"),
                        ObjectId("5817a9e2e93790eb7f591c6e"),
                        ObjectId("5817a9e3e93790eb7f591db9")
                ],
                "57917dfcf493fddf7b00f88a" : [
                        ObjectId("5817a955e93790ec753cd537")
                ],
                "57a14c1bf493fd3526008a52" : [
                        ObjectId("5817adbde93790ec8befb085"),
                        ObjectId("5817adbfe93790ec8befb41a"),
                        ObjectId("5817adbfe93790ec8befb443")
                ],
                "5890df4ee937907d388855a4" : [
                        ObjectId("5890df4fe937907d388855aa"),
                        ObjectId("5890df4fe937907d388855b0"),
                        ObjectId("5890df50e937907d388855b7"),
                        ObjectId("5890df50e937907d388855ba")
                ]
        },

**Comment by FreeUKGenIssues** [comment]
This is tremendously useful.

On #1, I have not interpreted ? as a wildcard, since it indicates
uncertainty of the entire word.  What do you think the correct behavior
should be when searching against "MCKERON?"

On #3, this is certainly a bug I should have caught.  I will log a separate
issue for it.

Please double-check #4.  If your described use case is accurate, the search
will fail because of the mismatch between "MC" in the record and "mac" in
the search query.

#5 is also an omission.  The square-brace UCF transformation prunes the
wildcard, so it does not get added to the wildcard UCF transformation.  I
will log a separate issue for it.

On #6, I'm confused by your description.  I'd want a search for "Grein" or
"Green" to find the same record (as you describe), but I'd expect both of
them to display "GRE[EI]N".

**Comment by Captainkirkdawson** [comment]
WRT 1) We return the record as if it had been entered as MCKERON and it was not. There is no ? in the display of the record.  I would have expected it to be found as a UCF possible.  (A search for MCKERON? times out)
4. It is MC not MAC

6. Comment withdrawn

**Comment by edickens** [comment]
I have tried to follow this thread, but have left it to EricB to test.

The problem I have is that to me Wildcard is what you enter into the 
search criteria should you not know what to ask for, such as "Dick*" to 
find all the versions of "Dickens", whereas UCF is what the transcriber 
has entered which could still be "Dick*" where the end of the name is 
unreadable.

So the UCF feature is making the server able to read what the 
transcriber has entered.  Wildcard would be something totally different 
as it is what the researcher enters.

Am I correct?

Eric J Dickens

**Comment by Sherlock21** [comment]
There is a lot of confusion on this topic,
We must be quite specific about which part of the process ( Transcriber action, or Researcher Specification) we are talking about. especially with regard to the ? and * characters.

I agree with the last comment: Wild card is what the researcher should put into their search parameters if they are uncertain of part of a word following the point where they type the * mark ( * begin the wild card).
UCF  is the marker [] that the  Transcriber uses to show they have not been able to read a single letter. There can be more than one UCF occurrence in a single word. e.g. [EI] indicates a single letter could be E or I. or could use [E_] meaning that single letter is most probably E but could be anything.
ALSO the Transcriber can use * in his transcription indicating there is nothing in  mandatory field, where there should be a value - perhaps a date or a name that's not in the original Register.

clearly its important to not confuse the 2 aspects.
Maybe we should spell the agreed version out more clearly in the rules for Transcribers and for researchers

**Comment by Captainkirkdawson** [comment]
This story deals only with the UCF. 

It attempts to retrieve records that have been transcribed with UCF according to the rules of UCF. It has nothing to do with a wildcard search which may/may not be an appropriate way to also get at those records.

To assist I have added KIRK?, K{IU]R[KT] and K*K to the same file in the date range 1700 -1710.
It confirms that problem 1 is serious. KIRK? is not found period
It confirms that the [] works correctly
It shows that the use of an * does not.
