### ISSUE TITLE
Implement donate icon

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeUKRegProductIssues#844]
Source a 'donate' button icon for use on all projects.

**Comment by PatReynolds** [comment]
EG https://thenounproject.com/term/donate/ - these have a cc by 3.0 licence, so we can modify.

**Comment by richpomfret** [comment]
Andrew is making the code for this - us to then test/review.

**Comment by richpomfret** [comment]
Colours to be reviewed (to schedule a meeting to go over this).

**Comment by richpomfret** [comment]
For code to go onto Github>then to be implemented by Kirk (or Alison/Israel).

**Comment by DeniseColbert** [comment]
Code now in Github

**Comment by richpomfret** [comment]
For us to check on how the assets have been provided, request any changes as needed.

**Comment by DeniseColbert** [comment]
@dougkdev https://github.com/FreeUKGen/Coordination/pull/304

**Comment by Captainkirkdawson** [comment]
Vino  I made one change to your code in FreeREG and that was to delete the existing link which was not needed with the new icon

**Comment by Captainkirkdawson** [comment]
WRT this it is also a duplicate 938

**Comment by DeniseColbert** [comment]
Tested and all fine.
