### ISSUE TITLE
59570060 FreeREG is changing register types between uploading and downloading (Staffordshire)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#845]
Issue reported by **STSCoord** at 2016-11-20 11:14:20 UTC
Time: 2016-11-20T11:04:38+00:00
Session ID: ab31149e5d975cc5d2dc957630d325fc
Problem Page URL: [/freereg1_csv_files/58312924f493fd4c27dae006](/freereg1_csv_files/58312924f493fd4c27dae006)
Previous Page URL: [http://www.freereg.org.uk/registers/58304529f493fd9414161041](http://www.freereg.org.uk/registers/58304529f493fd9414161041)
Reported Issue:
I have a file that was uploaded with a register type of OT but when I downloaded the file, after processing by FreeREG, the register type was TR. This is clearly wrong when the FreeREG Help system states that TR is the old style for transcriptions.    

![Screenshot](http://www.freereg.org.uk)

**Comment by ghost** [comment]
The file in questions is MikeNL:STSWPABA.CSV

**Comment by ghost** [comment]
Another feedback which came in that I believe is related:    FreeREG Help has a list of valid Register Types that are required. For some reason, the list of Register Types presented when trying to relocate a file does not match the Help list. The one that caused me to raise this discrepancy was OT which has disappeared from the offered list and, in another Problem Report, looks like files with OT are being converted to TR.

**Comment by Captainkirkdawson** [comment]
The Internal representation of OT is TR they are one and the same as far as the system is concerned. 
This is because we did not want to go back and convert all TR batches to OT batches since they are exactly the same definition.
Personally speaking I saw no reason to introduce the OT as it had the same definition as TR

**Comment by PatReynolds** [comment]
What is the action that is needed here?

**Comment by edickens** [comment]
Perhaps just something in the Help.
    
    For some Register Types we have two codes, the latest and those that
    were used in FR1.  If someone uploads a file using the old FR1
    codes, then downloads it, FR has changed the code to the new one.
    
    There is no problem.
    
    E
    
      On 28/11/2016 08:57, PatReynolds wrote:
    
    
      What is the action that is needed here?
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/FreeUKGen/FreeUKRegProductIssues","title":"FreeUKGen/FreeUKRegProductIssues","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/FreeUKGen/FreeUKRegProductIssues"}},"updates":{"snippets":[{"icon":"PERSON","message":"@PatReynolds in #845: What is the action that is needed here?"}],"action":{"name":"View Issue","url":"https://github.com/FreeUKGen/FreeUKRegProductIssues/issues/845#issuecomment-263215915"}}}

**Comment by ghost** [comment]
Issue apparently resolved at Coordinator level. Closing story accordingly
