### ISSUE TITLE
59604989 Dates of Marriages have disappeared (Sandra)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#846]
Issue reported by **CommsCoord** at 2016-11-20 20:56:29 UTC
Time: 2016-11-20T20:54:39+00:00
Session ID: b875239b806656fb916a93efe8a900bc
Problem Page URL: [/freereg1_csv_entries](/freereg1_csv_entries)
Previous Page URL: [http://www.freereg.org.uk/freereg1_csv_entries/55c6e0f6f493fd857c02bb27](http://www.freereg.org.uk/freereg1_csv_entries/55c6e0f6f493fd857c02bb27)
Reported Issue:
This issue was found after a contact was sent regarding one marriage without dates. Further investigation shows all marriages in the file have no dates, yet the file summary shows decadal date ranges.    

![Screenshot](http://www.freereg.org.uk)

**Comment by ghost** [comment]
The file affected in this instance is STSWEKMA.CSV. I also had an issue previously in which the bride's forename was missing. I was able to replace them but never thought about it being an issue. It is possible it was the same sort of issue.

**Comment by Captainkirkdawson** [comment]
The only comment I can make is that the file was uploaded on 2015-10-25T14:28:04+00:00 and that file contained no dates. All subsequent uploads had no dates. There were 5 uploads of that file in the past 2 days

**Comment by ghost** [comment]
Closing
