### ISSUE TITLE
59813608 Cannot select a file on PC to replace (Staffordshire)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#848]
Issue reported by **STSCoord** at 2016-11-23 06:53:28 UTC
Time: 2016-11-23T06:48:30+00:00
Session ID: b3caa6a50d5fd24496a7f9f900436f65
Problem Page URL: [/csvfiles/5834ecfff493fddd5b03acba/edit](/csvfiles/5834ecfff493fddd5b03acba/edit)
Previous Page URL: [http://www.freereg.org.uk/freereg1_csv_files/5834ecfff493fddd5b03acba](http://www.freereg.org.uk/freereg1_csv_files/5834ecfff493fddd5b03acba)
Reported Issue:
When trying to do a "Replace" of a file, after going into "Browse..." and selecting a file, either by double-clicking or "Open" the file is displayed in the "Select File" window but does not get back into the web page. Result - unable to use "Replace" functionality. Windows 10 system with Internet Explorer    

![Screenshot](http://www.freereg.org.uk)

**Comment by PatReynolds** [comment]
Could he try again?

**Comment by ghost** [comment]
Contact has resolved issue. Closing the story accordingly.
