### ISSUE TITLE
59616329 Help for uploading/replacing file on the server no longer reflects the current system (Staffordshire)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#849]
Issue reported by **STSCoord** at 2016-11-21 00:05:29 UTC
Time: 2016-11-20T23:46:46+00:00
Session ID: 9e49d52be94d4b1270d8b52453c08c5c
Problem Page URL: [/cms/information-for-transcribers/file-and-batch-actions](/cms/information-for-transcribers/file-and-batch-actions)
Previous Page URL: [http://www.freereg.org.uk/cms/information-for-transcribers](http://www.freereg.org.uk/cms/information-for-transcribers)
Reported Issue:
The Help for uploading/replacing files still shows some of the options for processing and having to press the "Process" button to get the file processed. Since the major update, this process works differently.    

![Screenshot](http://www.freereg.org.uk)

**Comment by AlOneill** [comment]
Oops! File and Batch actions now updated.

**Comment by AlOneill** [comment]
Also now updated: [Info for Transcribers](http://www.freereg.org.uk/cms/information-for-transcribers).

**Comment by ghost** [comment]
Can this be closed now?
