### ISSUE TITLE
Edit Syndicate is not a REGManager option (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#85]
Issue reported by **REGManager** at 2014-11-24 13:47:09 UTC
Time: 2014-11-24T13:44:02+00:00
Session ID: 948ebda726d7269a8e996465222dbbd0
Problem Page URL: [/manage_syndicates/select_action?syndicate=Rest%20of%20England](/manage_syndicates/select_action?syndicate=Rest%20of%20England)
Previous Page URL: [http://test2.freereg.org.uk/manage_syndicates/new](http://test2.freereg.org.uk/manage_syndicates/new)
Reported Issue:
I want to tidy up the Syndicates so need to amend the name, delete and insert, but none of these is an option for me.   I understood that they should be.

E    

![Screenshot](http://test2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
You have access to Syndicate Coordinators where you can do all the things you want.  Had to use a different name for the function so it was not the same as the Manage Syndicate which is there for SCs putting an s on the end left it too similar.

![ericd6](https://cloud.githubusercontent.com/assets/2874694/5167583/70b8e11c-73b6-11e4-9123-2c1fee394604.JPG)
![ericd5](https://cloud.githubusercontent.com/assets/2874694/5167582/70b847b6-73b6-11e4-90a7-2a9022ff39a9.JPG)
