### ISSUE TITLE
60167901 Help text for burials seems to be wrong for nee/late (Staffordshire)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#850]
Issue reported by **STSCoord** at 2016-11-27 09:18:21 UTC
Time: 2016-11-27T09:12:40+00:00
Session ID: 7ac94a38a91007db951494aca1ee9ff8
Problem Page URL: [/cms/information-for-transcribers/entering-data-from-registers](/cms/information-for-transcribers/entering-data-from-registers)
Previous Page URL: [http://www.freereg.org.uk/cms/information-for-transcribers](http://www.freereg.org.uk/cms/information-for-transcribers)
Reported Issue:
Help text for registering maiden name of mother is wrong? Currently, it reads "More than one relative surname?

Some entries have two different relative surnames:
Joseph Brown son of William and Elizabeth (late Green)

To make Elizabeth's previous surname searchable, you will need two records. The three Relative fields and the Notes field respectively would be:

First:
William, Elizabeth, BROWN
Elizabeth Brown (late Green)
Second:
, Elizabeth, BROWN
Elizabeth Brown (late Green). Son of William Brown
For the second record, the rel1-male-first field is left empty because William was not called Green. (We are planning to add a second relative surname field when this becomes feasible.)" Surely, using the example given, the mother is still NOT searchable by her maiden name, Green. Should the second example not use GREEN instead of BROWN (capitalization matches capitalization in the help text)?    

![Screenshot](http://www.freereg.org.uk)

**Comment by AlOneill** [comment]
Good catch! Apologies for the typo and poor checking.

Now fixed.
