### ISSUE TITLE
UCF for year - temporary fix

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeUKRegProductIssues#852]
Eric D suggests that rather than using UCF on years, transcribers are told to use nnnn? (i.e. a deduced or guessed year followed by a question mark) rather than UCF, until #832 is implemented, when the nnnn? entries will need to be revisited. 
I suggest that earlier transcriptions using UCF are not converted to nnnn?

**Comment by Captainkirkdawson** [comment]
Strongly disagree with such an action
