### ISSUE TITLE
Crashed out when I uploaded a Replace Batch

### ISSUE THREAD

**Issue by Sherlock21** [FreeUKGen/FreeUKRegProductIssues#853]
I uploaded a Replacement batch ( from My Batches listing UPON LOGON TO Production, NOT T3).
Selected my correct file and hit: upload.
Immediately I got thrown out of FR application, to this screen:-

**Comment by Sherlock21** [comment]
I had previously stopped in the middle of doing a file update, and had to come back to the job now. I could not remember if I had actually uploaded the file to Production, so I checked in the Not Processed files list. The  file concerned was not there. 
It is ericb.WRYDEWBA4.csv.

I uploaded a Replacement batch ( from My Batches listing UPON LOGON TO Production, NOT T3).
Selected my correct file and hit: upload.

Immediately I then got thrown out.
to a screen with this message

this  darned system will not let me attach the image no matter what i do!!

**Comment by Sherlock21** [comment]
This morning, ( 29 Nov 2016) I see that the overnight processing log shows that the file concerned, (WRYDEWBA4.csv) was processed at 01:07:05 this morning. SO it was in the Not Processed state when I searched my list yesterday evening. 
So why did it not appear there?

There were said to be no software changes implemented in the recent FR reload so it was said.

But it perhaps does account for the crash out which is the subject of this ticket? - is it the wrong system response? or the wrong system message then?

**Comment by Captainkirkdawson** [comment]
As noted in 865 this issue was caused by a failed software update that made the file system unavailable for uploads/replaces. See  1033 for specifics.
