### ISSUE TITLE
60717471 Website Problem (Eric Dickens)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#857]
Issue reported by **Eric Dickens** at 2016-12-03 17:57:51 UTC
Time: 2016-12-03T17:56:21+00:00
Session ID: d392b18b002c04918219551f996f5d14
Problem Page URL: []()
Previous Page URL: [http://www.freereg.org.uk/contacts/new](http://www.freereg.org.uk/contacts/new)
Reported Issue:
STS places are not coming up in the Search Screen.  I thought we had fixed this.

Eric    

![Screenshot](http://www.freereg.org.uk/uploads/contact/screenshot/5843079ff493fd61c0e3c831/Capture.JPG)

**Comment by Captainkirkdawson** [comment]
Someone needs to refresh the place cache for STS

**Comment by Captainkirkdawson** [comment]
Ran the place_cache refresh task, See system documentation for additional info on process
http://www.freereg.org.uk/cms/system-documents?

**Comment by edickens** [comment]
OK now.  Cheers E
    
      On 05/12/2016 20:53, Kirk Dawson wrote:
    
    
      Ran the place_cache refresh task, See system documentation for
        additional info on process
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/FreeUKGen/FreeUKRegProductIssues","title":"FreeUKGen/FreeUKRegProductIssues","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/FreeUKGen/FreeUKRegProductIssues"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Captainkirkdawson in #857: Ran the place_cache refresh task, See system documentation for additional info on process"}],"action":{"name":"View Issue","url":"https://github.com/FreeUKGen/FreeUKRegProductIssues/issues/857#issuecomment-264973841"}}}

**Comment by ghost** [comment]
Closing as issue has been resolved
