### ISSUE TITLE
61042196 Registration emails not being received (Eric)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#859]
Issue reported by **REGManager** at 2016-12-07 12:09:56 UTC
Time: 2016-12-07T11:58:59+00:00
Session ID: c6ceb9730409f0a2774ebcb8e1432994
Problem Page URL: [/userid_details/5846f5f4f493fd4ee4311bc8](/userid_details/5846f5f4f493fd4ee4311bc8)
Previous Page URL: [http://www.freereg.org.uk/userid_details/select?name=Tidball:Richard](http://www.freereg.org.uk/userid_details/select?name=Tidball:Richard)
Reported Issue:
I'm having lots of problems with new transcribers.  Some register easily, but some just do not get the password reset email, or it creates "invalid token".
The latest is Richard Tidball who has even tried setting up a second UserID with a different email address.  But that does not work either.
Both his UserIDs say "Transcriber agreement accepted" = False.  Is this the problem?  He and I have tried everything, but no luck.  We cannot work out why some work and some not.  DSwymp registered successfully yesterday.
This is URGENT because otherwise we will lose volunteers.  E    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/5847fc14f493fd78601b9ec7/Capture.JPG)

**Comment by edickens** [comment]
I have now looked further and there are others with "Agreement" = False, so that is not the problem.

**Comment by edickens** [comment]
Do contact the volunteer and include Doreen and myself.  We need to get this sorted out.  E

**Comment by edickens** [comment]
I have reproduced the problem and have screen shots if whoever is going to sort this out will contact me.  E

**Comment by dougkdev** [comment]
@edickens, is this the same behaviour that was seen with #973 (the issue with user timeout defaulting to 10 minutes)?  Sounds like it is something different, but just want to verify.  If you send me the info I can take a quick look to see if anything sticks out to me.  I suspect that "some just do not get the password reset email" may not be the exact same issue as "it creates 'invalid token'".  Also, can you clarify-- is this only happening when the user submits her or his registration initially, or does the failure to receive the email and/or invalid token also happen when a password reset link is requested by the user ("I forgot my password" link) or manually sent by you or other coordinator through the actions available to you?  Thanks.

**Comment by richpomfret** [comment]
Duplicate issue.
