### ISSUE TITLE
Changing your own profile crashes the program (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#86]
Issue reported by **REGManager** at 2014-11-24 13:52:36 UTC
Time: 2014-11-24T13:47:35+00:00
Session ID: 78946078be1ff2c30ee2a83fa671bd5d
Problem Page URL: [/userid_details/5462b414e937907d7000035c/edit](/userid_details/5462b414e937907d7000035c/edit)
Previous Page URL: [http://test2.freereg.org.uk/userid_details/my_own](http://test2.freereg.org.uk/userid_details/my_own)
Reported Issue:
I was trying to change Reg and Manager to Eric and Dickens.  But when I selected Submit I got the attached.

I'm also not sure if the "greyed out" meaning "not amendable" is correct in all fields.  I will look out for that in future.

E    

![Screenshot](http://test2.freereg.org.uk/tmp/carrierwave/1416837156-86542-3683/Capture.JPG)

**Comment by Captainkirkdawson** [comment]
Issue is that having changed your profile the system no longer knows who you are; have to consider asking you to login using your new profile rather than continuing on.

**Comment by edickens** [comment]
```
This must apply to anyone who amends
  their name.

  Well found!

  E
  _____________________________________
```

Eric J Dickens
FreeREG Chairman
      On 24/11/2014 17:38, Kirk Dawson wrote:

```
  Issue is that having changed your profile the system no longer
    knows who you are; have to consider asking you to login using
    your new profile rather than continuing on.
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by Sherlock21** [comment]
Hey...

Does this apply to any profile change, or just what EricD was doing?

There is the option at present to change ones SC as needed - refer to earlier discussions - 
and the discussion was to the effect that is what I (users) should do ones self.
so are you saying option is going to be changed?

To whom? the Old SC or the proposed New SC or any other SC or CC?

EricB
