### ISSUE TITLE
61202445 Last amended date incorrect (Great Easton, Essex) (Julie)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#860]
Issue reported by **jmh** at 2016-12-09 08:40:45 UTC
Time: 2016-12-09T08:38:15+00:00
Session ID: 4613e6cd5feee7dfcfaa14591f0d61d6
Problem Page URL: [/freereg_contents/564c796ef493fd11500001b4/show_register](/freereg_contents/564c796ef493fd11500001b4/show_register)
Previous Page URL: [http://www.freereg.org.uk/freereg_contents/Great%20Easton](http://www.freereg.org.uk/freereg_contents/Great%20Easton)
Reported Issue:
the last date has been for a while, and still is despite new data added yesterday, 10 Nov 2916.

10 Nov was a date when the data was updated - but the 2916 is obviously wrong.  Something wrong with your algorithm ?

Julie Harold (Essex Coordinator and transcriber of these files)    

![Screenshot](http://www.freereg.org.uk)

**Comment by suffolkroots** [comment]
See #771 still ongoing. Skipton updated 7/12/2016 but last update is stated as 24/11/2016

**Comment by Captainkirkdawson** [comment]
Coordinator is complaining that the date of amendment is not being updated not that the changes to data are not reflected. 
Given complexity of calculations; this will only be calculated and updated daily and will not ripple through to register/ church and place instantaneously. See also 771

**Comment by Captainkirkdawson** [comment]
There are 2 ways of calculating this 1) use the date that the system records as the last date of modification of the batch or 2) the modification date in the batch. The former will change when we "reprocess" the  batch for some reason.  Hence provide a more recent date than the actual transcription. The later is under the control of a transcriber/coordinator and could more accurately reflect the actual date

**Comment by Captainkirkdawson** [comment]
If we use the latter approach we can make that date editable on-line as well is in the batch. If we use the former then it cannot be changed except by the system

**Comment by edickens** [comment]
Unless the transcriber is using WinReg, I have found quite often that the transcriber does not update the Amended date in the header, which could be why under 2) this date does not change.
I would prefer 1) even though it is not amendable.  Remember in a future version we are suggesting that we will contact a registered Researcher to tell them that a Year Range in which they are interested has changed or more records have been added, so the Last Amended Date might be used.

**Comment by Sherlock21** [comment]
I agree that Spreadsheet users may forget to change the issue date in the file header.

SO, could you not arrange to revise the header "last updated Date" field, & make it the system date of the upload? and put it in the header field for all to see.

same way as you put the system date of a downloaded file into the same field for the user.

**Comment by Captainkirkdawson** [comment]
Adopting approach suggested by EricB to use the date of the last upload. There will be a few occasions when there is an on-line update to an entry in the batch that is more recent. However the time of upload is the most meaningful in terms of transcriber action

**Comment by Captainkirkdawson** [comment]
Have implemented suggestion on test3. 
Could Erics and suffolkroots and julie please review

**Comment by Sherlock21** [comment]
K

yes I did  new file upload for test. I like the distinction on the file details, of the various specific dates. 

and I did a Reload too - file ericb. WRYDYMBA3.csv.
it uploaded as processed as expected
BUT  whilst the date of Upload comes out correct ( ‘Today'), regardless of the date on the file,
the date in the FR Details of Date modified shows as 22-Aug-2014 which bears no relation to any dates in the uploded file
field 2F is 01-0Nov-2016 and 3B is 15-Jul-2016.

you can view the actual in T3 under WRY/ Dewsbury Moor/ Baptisms/ ericb.WRYDYMBA3.csv.

Otherwise, this is a big improvement. Thank you. 
Eric b

**Comment by suffolkroots** [comment]
Uploaded WRYSKIBU10.CSV last date of change now showing correctly in T3:
Transcriptions/West Riding/Skipton/15/12/2016
Still not correct in FR:
Transcriptions/West Riding/Skipton/24/11/2016

**Comment by edickens** [comment]
Am I correct that this change is not backdated.  So that is why the 
24/11/2016 upload will not show correctly in Transcriptions.  So the 
amendment is good.  E

**Comment by Captainkirkdawson** [comment]
Points to remember. 1) Statistics like this are computed overnight only. 2) Code is only deployed to test3 for  evaluation, production has not been changed 3) Since stats are recomputed nightly it will be retroactive when deployed and run. 4) Stats have been rerun on test3
