### ISSUE TITLE
61212923 Destroy UserID Timed Out (Eric)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#861]
Issue reported by **REGManager** at 2016-12-09 11:35:23 UTC
Time: 2016-12-09T11:26:33+00:00
Session ID: 0ac4252ef8b780accfba9e068040413a
Problem Page URL: [/userid_details/58441c4ef493fd2b1f596cce](/userid_details/58441c4ef493fd2b1f596cce)
Previous Page URL: [http://www.freereg.org.uk/userid_details/select?name=Tidball:Richard](http://www.freereg.org.uk/userid_details/select?name=Tidball:Richard)
Reported Issue:
I did report a problem with Destroy UserID some months ago and thought the problem was fixed.  But I am now trying to delete some UserIDs where the volunteer did not complete registration.
See attached.  The volunteer was Richard Tidball.  E    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/584a96fbf493fda64bfcb5fb/Capture.JPG)

**Comment by ghost** [comment]
A further issue noted:  'on returning to the website I got a "Document does not exist" and then after logging out and in again it seems that the Destroy UserID has worked.'

**Comment by Captainkirkdawson** [comment]
Problem was caused by the failed software update which left it impossible to access the actual file system. See #1033
