### ISSUE TITLE
61293873 Unable to add new church for Fawdon NBL (Eric)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#862]
Issue reported by **nejws05** at 2016-12-10 10:04:33 UTC
Time: 2016-12-10T10:01:09+00:00
Session ID: bc5e502425061a628cee074754819e3f
Problem Page URL: [/places/53cbf5fceca9eb03a60075e9](/places/53cbf5fceca9eb03a60075e9)
Previous Page URL: [http://www.freereg.org.uk/manage_counties/place_range](http://www.freereg.org.uk/manage_counties/place_range)
Reported Issue:
Unable to add new church for Fawdon NBL, error message reporting to webmaster    

![Screenshot](http://www.freereg.org.uk)

**Comment by ghost** [comment]
Also reported for Etal NBL (61293224)

**Comment by Sherlock21** [comment]
I confirm that I can't create a new church anywhere!

i did test this feature and it was OK, after the data reshuffle at the start of Kirk's vacation - if thats any help.

**Comment by Captainkirkdawson** [comment]
Issue caused by the code introduced as part of "Church denomination can be accidentally overwritten (Staffordshire) #826"

**Comment by Captainkirkdawson** [comment]
EricB
Please check code change on test3
Please also confirm that code change did not destroy 826 denomination override

**Comment by Sherlock21** [comment]
Test results in T3:
Created a New  church in  NBL/ Acomb. -St Mary C of E. OK
Created a second new church in same place. ST Joseph. Different Denomination ( Baptist - Scottish). - both are OK.

Edited the master table of Denominations for the Baptist - Scittish to Baptist - Scottish2. The edit was accepted but it did not back fit to my just created church. -??SHOULD IT HAVE?? IF my change had been to correct a typo or similar, in the master table of Denominations, how would we have done that to get it to back fit?

Created St Stephen in the adjacent place name of Akeld as  Baptist Scottish2. OK. it did not affect any others.
I created a 4rd new church St John in Acomb. denomination chosen as the default C of E. - all came out correct. and nothing cross interfered with any other. -

Then to address 826:
I tried to Relocate Church to another Place - I used my just created church of Acomb / St Mary now: Baptist - Scottish, to Acklington also in NBL. there are no files attached to any of these places of churches involved in this test. Is that significant?
Should I do it all again with some date attached, see what the indexes do?

PROBLEM: it immediately came up with Red Error: SORRY SOMETHING WENT WRONG. 
**********
And the query point above remains a question please.

Now I Stopped testing until you review this.

**Comment by Captainkirkdawson** [comment]
EricB
Relocation should now work with church with no records
There is no way that a "back fit" can be implemented when you edit the table of denominations. 
Please confirm that things are now OK

**Comment by Sherlock21** [comment]
OK,Kirk

I accept you never designed the edit Denomination name  to cope with back fit. so leave that one out of it.


SO  Reloate a church to another place. IF NO files attached, then Yes, it does relocate properly.

BUT if there are data files attaches, then it fails.

eg NBL.. St Peter from Allendale was being moved into Acomb. it has 1147 records according to the onscreen inf.
and it fails with the red msg: Sorry but something went wrong.

Leave it with you. I might get a momet to look back in 2 hours -else it will be Monday Morning GMT.

Eb

**Comment by Captainkirkdawson** [comment]
Should be OK now

**Comment by Sherlock21** [comment]
Kirk

OK, I have done the final set of testing on this topic and the related church moving with files attached.
And also the church renaming with and without files attached.

ALL SEEMS FINE TO ME NOW so put into production when you are ready as far as I am concerned.
E

**Comment by Captainkirkdawson** [comment]
Thank you very much EricB. A good bit of testing as always

**Comment by ghost** [comment]
Can this be closed now?​

_________________________________________________________________________________

Sandra Adams-West
*FreeREG Communications Coordinator*
*__________________________________________________________________________________*

**Comment by Captainkirkdawson** [comment]
Not yet deployed

Kirk Dawson
5220 Riverside Drive
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by richpomfret** [comment]
Now deployed.
