### ISSUE TITLE
61268796 Manage Country Button does not work (Sue)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#863]
Issue reported by **REGScotland** at 2016-12-10 03:06:36 UTC
Time: 2016-12-10T03:02:24+00:00
Session ID: 7cf8fedabd7d83a830f28709e05b4b07
Problem Page URL: [/manage_resources/new](/manage_resources/new)
Previous Page URL: [http://www.freereg.org.uk/userid_details/confirm_email_address](http://www.freereg.org.uk/userid_details/confirm_email_address)
Reported Issue:
When I click on the teal button for manage Country (Scotland) I get a message that reads - 
Missing Page
You have requested a page that does not exist on our server. Please make sure that you have actually accessed the FreeReg Website.    

![Screenshot](http://www.freereg.org.uk)

**Comment by edickens** [comment]
I think this should be a System Administrator Action.  All it does
    is to assign the Coordinator for the Country and REGScotland is the
    Coordinator for Scotland.  E

**Comment by Captainkirkdawson** [comment]
There is no support for managing a country, There is only the ability to assign a country coordinator who will have access to all the counties in a country. Will limit capability to change country coordinator to system administrator
