### ISSUE TITLE
61223737 First uploading problem (Alexander)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#865]
Issue reported by **Alex17** at 2016-12-09 14:35:37 UTC
Time: 2016-12-09T14:25:31+00:00
Session ID: a9b645947f2c85758c4acd298524f3c5
Problem Page URL: [/csvfiles/new](/csvfiles/new)
Previous Page URL: [http://www.freereg.org.uk/freereg1_csv_files/my_own](http://www.freereg.org.uk/freereg1_csv_files/my_own)
Reported Issue:
I tried to upload the file NTHTITBA1.CSV a few minutes ago, but was told there was a problem and not to repeat the action. 
I have not experienced this before. No problem when uploaded earlier this week.
Please advise.
Alex Stewart
alexanderstewart390@btinternet.com    

![Screenshot](http://www.freereg.org.uk)

**Comment by ghost** [comment]
This has been reported by other users as well, files cannot be loaded in one account but can be uploaded in another.

**Comment by Captainkirkdawson** [comment]
Problem was byproduct of a failed software update on dec 9 see 1033.
Users should be told to repeat upload/replace

**Comment by edickens** [comment]
Is it fixed?  I'll not send a message until I know.  If you want to 
create a message in the Message system, I will send it when requested.  E

**Comment by Captainkirkdawson** [comment]
1033 has not been touched yet.
However the failed software update that caused the specific issue of yesterday has been completed by Alex so people can go about uploading and replacing as noted in my comment

**Comment by edickens** [comment]
All

It is now 1120 in the Netherlands.

I do not know what the problem with upload/replace was, but I do have a problem now.

In the Upload screen, I can browse for a file and select one, 
What normally works is that the filename is included in the small display next to the browse button. This is not happening now.

Michael Clarke 11/12/16

**Comment by Captainkirkdawson** [comment]
I am unable to duplicate any issue in Edge; it does look like Edge has been updated recently and may be displaying things differently.
![capture](https://cloud.githubusercontent.com/assets/2874694/21080965/9298947e-bf79-11e6-9d36-4a7ad3375c4d.JPG)
