### ISSUE TITLE
61130764 UserID changes when error message shown (Staffordshire)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#866]
Issue reported by **STSCoord** at 2016-12-08 12:46:04 UTC
Time: 2016-12-08T12:39:24+00:00
Session ID: 22ec6225d389d40c88fb5f45d304e806
Problem Page URL: [/csvfiles/new](/csvfiles/new)
Previous Page URL: [http://www.freereg.org.uk/csvfiles/new](http://www.freereg.org.uk/csvfiles/new)
Reported Issue:
The attached shows an error message and the UserID of STSCoord. I was trying to upload a file on behalf of UserID MikeNL so if I now try to upload a different file using this screen and for the same userid (MikeNL), I will accidentally be doing it as STSCoord.    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/5849560cf493fd3f57873948/Capture.JPG)

**Comment by ghost** [comment]
I could not find a similar story so have opened this, sorry if duplicated

**Comment by Captainkirkdawson** [comment]
Without screenshot can do nothing

**Comment by ghost** [comment]
![capture866](https://cloud.githubusercontent.com/assets/20557838/21118115/61f569e6-c0b4-11e6-9efe-300d856e0b6e.JPG)

**Comment by ghost** [comment]
As an FYI for me, do I need to do this in future will all screenshots?

**Comment by Captainkirkdawson** [comment]
Yes until such a time as the automatic system gets fixed

**Comment by Captainkirkdawson** [comment]
I do not view this as a bug. It works as designed and as stated. i.e. it pre selects the userid of the person dong the upload. If you want it to go somewhere else you must select that person's id 
If an enhancement is really required to change the system to keep th previous entry then it can be considered along with other change requests

**Comment by ghost** [comment]
I thought the screenshot (if one provided) transferred across when I
convert to issue. But it apparently does not. Hence the question.​

_________________________________________________________________________________

Sandra Adams-West
*FreeREG Communications Coordinator*
*__________________________________________________________________________________*

**Comment by Captainkirkdawson** [comment]
It is supposed to

**Comment by Captainkirkdawson** [comment]
My test on test3 shows screenshot coming through

**Comment by edickens** [comment]
Do not make changes to how things work, but the SCs Help pages
    should reflect any areas where there could be confusion.  In this
    way we have a definition of how things work and SCs should refer to
    the Help.  If what they are looking for is not there, that is when
    they need to ask and the Help be updated.  E
    
      On 12/12/2016 21:56, Kirk Dawson wrote:
    
    
      I do not view this as a bug. It works as designed and as
        stated. i.e. it pre selects the userid of the person dong the
        upload. If you want it to go somewhere else you must select that
        person's id
        If an enhancement is really required to change the system to
        keep th previous entry then it can be considered along with
        other change requests
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/FreeUKGen/FreeUKRegProductIssues","title":"FreeUKGen/FreeUKRegProductIssues","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/FreeUKGen/FreeUKRegProductIssues"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Captainkirkdawson in #866: I do not view this as a bug. It works as designed and as stated. i.e. it pre selects the userid of the person dong the upload. If you want it to go somewhere else you must select that person's id \nIf an enhancement is really required to change the system to keep th previous entry then it can be considered along with other change requests"}],"action":{"name":"View Issue","url":"https://github.com/FreeUKGen/FreeUKRegProductIssues/issues/866#issuecomment-266565646"}}}
