### ISSUE TITLE
61130303 This error is being displayed when I try to upload a file to FreeREG (Staffordshire)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#867]
Issue reported by **STSCoord** at 2016-12-08 12:38:23 UTC
Time: 2016-12-08T12:29:16+00:00
Session ID: 22ec6225d389d40c88fb5f45d304e806
Problem Page URL: [/csvfiles](/csvfiles)
Previous Page URL: [http://www.freereg.org.uk/csvfiles/new](http://www.freereg.org.uk/csvfiles/new)
Reported Issue:
I have received the message several times with different files. I will admit to using the web browser's "back" button instead of trying to use the breadcrumbs.    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/5849543ff493fd4345874170/Capture.JPG)

**Comment by Captainkirkdawson** [comment]
Cannot duplicate even with use of back button.  As noted we do discourage use of the browser backbutton because of changes in the environment that can have taken place
