### ISSUE TITLE
61129575 Grammatical correction to the Physical Files Display (Staffordshire)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#868]
Issue reported by **STSCoord** at 2016-12-08 12:26:15 UTC
Time: 2016-12-08T12:22:15+00:00
Session ID: 22ec6225d389d40c88fb5f45d304e806
Problem Page URL: [/manage_counties/display_files_waiting_to_be_processed](/manage_counties/display_files_waiting_to_be_processed)
Previous Page URL: [http://www.freereg.org.uk/manage_counties/display_files_waiting_to_be_processed](http://www.freereg.org.uk/manage_counties/display_files_waiting_to_be_processed)
Reported Issue:
The message has plural "files" but singular "its". Obviously, one of them is wrong.    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/58495167f493fd4345874105/Capture.JPG)

**Comment by SteveBiggs** [comment]
Reply to Michael.

**Comment by richpomfret** [comment]
Closing.
