### ISSUE TITLE
Syndicate structure (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#87]
Issue reported by **REGManager** at 2014-11-24 14:16:41 UTC
Time: 2014-11-24T14:09:24+00:00
Session ID: d6b6671c26fe1628cd12543b0ff4fa8c
Problem Page URL: [/manage_syndicates/selection?option=Review%20All%20Members](/manage_syndicates/selection?option=Review%20All%20Members)
Previous Page URL: [http://test2.freereg.org.uk/manage_syndicates/select_action?syndicate=Wales](http://test2.freereg.org.uk/manage_syndicates/select_action?syndicate=Wales)
Reported Issue:
I started to look at the job of sorting out the syndicates.  The first problem is that Anglesey is not in the list, even thought in FR1 it has two UserIDs registered there.  I have found these UserIDs registered in the Wales syndicate, even though there are no UserIDs registered against WLS in FR1.
Has someone made changes to the syndicate structure that I don't know about?  Or is this the way the website works?  Or is this some other problem?
E    

![Screenshot](http://test2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Howard requested that all Wales syndicates were in Wales when we first opened FR2 up to functional testing.
So yes it appears that you did not know of that. sorry.
Translation that was used is.
ODES = {'nil' => 'Unknown',
'ABD' => 'Aberdeenshire',
'AGY' => 'Wales',
'ALD' => 'Channel Islands',
'ANS' => 'Forfarshire (Angus)',
'ANT' => 'Ireland',
'ARL' => 'Argyllshire',
'ARM' => 'Ireland',
'AYR' => 'Ayrshire',
'BAN' => 'Banffshire',
'BDF' => 'Bedfordshire',
'BEW' => 'Berwickshire',
'BKM' => 'Buckinghamshire',
'BRE' => 'Wales',
'BRK' => 'Berkshire',
'BUT' => 'Bute',
'CAE' => 'Caernarvonshire',
'CAI' => 'Caithness-shire',
'CAR' => 'Ireland',
'CAV' => 'Ireland',
'CAM' => 'Cambridgeshire',
'CGN' => 'Wales',
'CHI' => 'Channel Islands',
'CHS' => 'Cheshire',
'CLA' => 'Ireland',
'CLK' => 'Rest of Scotland',
'CMN' => 'Wales',
'CON' => 'Rest of England',
'CUL' => 'Cumberland',
'COR' => 'Ireland',
'DBY' => 'Rest of England',
'DNB' => 'Rest of Scotland',
'DEN' => 'Wales',
'DEV' => 'Devon',
'DON' => 'Ireland',
'DFS' => 'Rest of Scotland',
'DOR' => 'Dorset',
'DOW' => 'Ireland',
'DUB' => 'Ireland',
'DUR' => 'Durham',
'ELN' => 'East Lothian',
'ENG' => 'Rest of England',
'ERY' => 'Rest of England',
'ESS' => 'Essex',
'FER' => 'Ireland',
'FIF' => 'Rest of Scotland',
'FLN' => 'Wales',
'GAL' => 'Ireland',
'GLA' => 'Wales',
'GLS' => 'Gloucestershire',
'GSY' => 'Channel Islands',
'HAM' => 'Hampshire',
'HEF' => 'Herefordshire',
'HRT' => 'Hertfordshire',
'HUN' => 'Huntingdonshire',
'INV' => 'Inverness-shire',
'IOM' => 'Isle of Man',
'IOW' => 'Isle of Wight',
'IRL' => 'Ireland',
'JSY' => 'Channel Islands',
'KCD' => 'Rest of Scotland',
'KRS' => 'Rest of Scotland',
'KEN' => 'Kent',
'KER' => 'Ireland',
'KID' => 'Ireland',
'KIK' => 'Ireland',
'KKD' => 'Rest of Scotland',
'LAN' => 'Lancashire',
'LDY' => 'Ireland',
'LEI' => 'Leicestershire',
'LET' => 'Ireland',
'LEX' => 'Ireland',
'LIM' => 'Ireland',
'LIN' => 'Lincolnshire',
'LKS' => 'Rest of Scotland',
'LND' => 'London City',
'LOG' => 'Ireland',
'LOU' => 'Ireland',
'MAY' => 'Ireland',
'MDX' => 'Middlesex',
'MEA' => 'Ireland',
'MER' => 'Merionethshire',
'MGY' => 'Wales',
'MLN' => 'Rest of Scotland',
'MOG' => 'Ireland',
'MON' => 'Wales',
'MOR' => 'Rest of Scotland',
'NAI' => 'Rest of Scotland',
'NBL' => 'Northumberland',
'NFK' => 'Norfolk',
'NRY' => 'North Riding Yorkshire',
'NTH' => 'Northamptonshire',
'NTT' => 'Nottinghamshire',
'OFF' => 'Ireland',
'OKI' => 'Orkney Isles',
'OVB' => 'Overseas',
'OVF' => 'Overseas',
'OXF' => 'Oxfordshire',
'PEE' => 'Peebles',
'PEM' => 'Wales',
'PER' => 'Rest of Scotland',
'RAD' => 'Wales',
'RFW' => 'Rest of Scotland',
'ROC' => 'Rest of Scotland',
'ROS' => 'Ireland',
'ROX' => 'Rest of Scotland',
'RUT' => 'Rutland',
'SCT' => 'Rest of Scotland',
'SEL' => 'Rest of Scotland',
'SAL' => 'Shropshire',
'SFK' => 'Suffolk',
'SHI' => 'Rest of Scotland',
'SLI' => 'Ireland',
'SOM' => 'Somerset',
'SRK' => 'Channel Islands',
'SRY' => 'Surrey',
'SSX' => 'Sussex',
'STI' => 'Rest of Scotland',
'STS' => 'Staffordshire',
'SUT' => 'Sutherland',
'TIP' => 'Ireland',
'TYR' => 'Ireland',
'UNK' => 'Unknown',
'WAR' => 'Warwickshire',
'WAT' => 'Ireland',
'WEM' => 'Ireland',
'WES' => 'Rest of England',
'WEX' => 'Ireland',
'WIC' => 'Ireland',
'WIG' => 'Rest of Scotland',
'WIL' => 'Wiltshire',
'WLN' => 'Rest of Scotland',
'WLS' => 'Wales',
'WOR' => 'Worcestershire',
'WRY' => 'West Riding Yorkshire',
'YKS' => 'Yorkshire'
}

**Comment by Sherlock21** [comment]
I know this is about Syndicates, but isn't it likely to raise confusion using AGY for All Wales in this context, when it is the County code for Anglesey?

EricB

**Comment by Captainkirkdawson** [comment]
No. This was to avoid using the same code for both a syndicate and a
county. i.e. to avoid the confusion that you allude to. Wales only has 1
Syndicate called Wales. All transcribers that were in AGY etc etc are
located in a single syndicate managed by Howard. The individual counties
exist as far as data is concerned.

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by edickens** [comment]
```
I was going to do that anyway!  You may
  have told me, but my brain is not what it was.  This is not the
  only project I work on!

  E
  _____________________________________
```

Eric J Dickens
FreeREG Chairman
      On 24/11/2014 17:45, Kirk Dawson wrote:

```
  Howard requested that all Wales syndicates were in Wales when
    we first opened FR2 up to functional testing.
    So yes it appears that you did not know of that. sorry.
    Translation that was used is.
    ODES = {'nil' => 'Unknown',
    'ABD' => 'Aberdeenshire',
    'AGY' => 'Wales',
    'ALD' => 'Channel Islands',
    'ANS' => 'Forfarshire (Angus)',
    'ANT' => 'Ireland',
    'ARL' => 'Argyllshire',
    'ARM' => 'Ireland',
    'AYR' => 'Ayrshire',
    'BAN' => 'Banffshire',
    'BDF' => 'Bedfordshire',
    'BEW' => 'Berwickshire',
    'BKM' => 'Buckinghamshire',
    'BRE' => 'Wales',
    'BRK' => 'Berkshire',
    'BUT' => 'Bute',
    'CAE' => 'Caernarvonshire',
    'CAI' => 'Caithness-shire',
    'CAR' => 'Ireland',
    'CAV' => 'Ireland',
    'CAM' => 'Cambridgeshire',
    'CGN' => 'Wales',
    'CHI' => 'Channel Islands',
    'CHS' => 'Cheshire',
    'CLA' => 'Ireland',
    'CLK' => 'Rest of Scotland',
    'CMN' => 'Wales',
    'CON' => 'Rest of England',
    'CUL' => 'Cumberland',
    'COR' => 'Ireland',
    'DBY' => 'Rest of England',
    'DNB' => 'Rest of Scotland',
    'DEN' => 'Wales',
    'DEV' => 'Devon',
    'DON' => 'Ireland',
    'DFS' => 'Rest of Scotland',
    'DOR' => 'Dorset',
    'DOW' => 'Ireland',
    'DUB' => 'Ireland',
    'DUR' => 'Durham',
    'ELN' => 'East Lothian',
    'ENG' => 'Rest of England',
    'ERY' => 'Rest of England',
    'ESS' => 'Essex',
    'FER' => 'Ireland',
    'FIF' => 'Rest of Scotland',
    'FLN' => 'Wales',
    'GAL' => 'Ireland',
    'GLA' => 'Wales',
    'GLS' => 'Gloucestershire',
    'GSY' => 'Channel Islands',
    'HAM' => 'Hampshire',
    'HEF' => 'Herefordshire',
    'HRT' => 'Hertfordshire',
    'HUN' => 'Huntingdonshire',
    'INV' => 'Inverness-shire',
    'IOM' => 'Isle of Man',
    'IOW' => 'Isle of Wight',
    'IRL' => 'Ireland',
    'JSY' => 'Channel Islands',
    'KCD' => 'Rest of Scotland',
    'KRS' => 'Rest of Scotland',
    'KEN' => 'Kent',
    'KER' => 'Ireland',
    'KID' => 'Ireland',
    'KIK' => 'Ireland',
    'KKD' => 'Rest of Scotland',
    'LAN' => 'Lancashire',
    'LDY' => 'Ireland',
    'LEI' => 'Leicestershire',
    'LET' => 'Ireland',
    'LEX' => 'Ireland',
    'LIM' => 'Ireland',
    'LIN' => 'Lincolnshire',
    'LKS' => 'Rest of Scotland',
    'LND' => 'London City',
    'LOG' => 'Ireland',
    'LOU' => 'Ireland',
    'MAY' => 'Ireland',
    'MDX' => 'Middlesex',
    'MEA' => 'Ireland',
    'MER' => 'Merionethshire',
    'MGY' => 'Wales',
    'MLN' => 'Rest of Scotland',
    'MOG' => 'Ireland',
    'MON' => 'Wales',
    'MOR' => 'Rest of Scotland',
    'NAI' => 'Rest of Scotland',
    'NBL' => 'Northumberland',
    'NFK' => 'Norfolk',
    'NRY' => 'North Riding Yorkshire',
    'NTH' => 'Northamptonshire',
    'NTT' => 'Nottinghamshire',
    'OFF' => 'Ireland',
    'OKI' => 'Orkney Isles',
    'OVB' => 'Overseas',
    'OVF' => 'Overseas',
    'OXF' => 'Oxfordshire',
    'PEE' => 'Peebles',
    'PEM' => 'Wales',
    'PER' => 'Rest of Scotland',
    'RAD' => 'Wales',
    'RFW' => 'Rest of Scotland',
    'ROC' => 'Rest of Scotland',
    'ROS' => 'Ireland',
    'ROX' => 'Rest of Scotland',
    'RUT' => 'Rutland',
    'SCT' => 'Rest of Scotland',
    'SEL' => 'Rest of Scotland',
    'SAL' => 'Shropshire',
    'SFK' => 'Suffolk',
    'SHI' => 'Rest of Scotland',
    'SLI' => 'Ireland',
    'SOM' => 'Somerset',
    'SRK' => 'Channel Islands',
    'SRY' => 'Surrey',
    'SSX' => 'Sussex',
    'STI' => 'Rest of Scotland',
    'STS' => 'Staffordshire',
    'SUT' => 'Sutherland',
    'TIP' => 'Ireland',
    'TYR' => 'Ireland',
    'UNK' => 'Unknown',
    'WAR' => 'Warwickshire',
    'WAT' => 'Ireland',
    'WEM' => 'Ireland',
    'WES' => 'Rest of England',
    'WEX' => 'Ireland',
    'WIC' => 'Ireland',
    'WIG' => 'Rest of Scotland',
    'WIL' => 'Wiltshire',
    'WLN' => 'Rest of Scotland',
    'WLS' => 'Wales',
    'WOR' => 'Worcestershire',
    'WRY' => 'West Riding Yorkshire',
    'YKS' => 'Yorkshire'
    }
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by Sherlock21** [comment]
OK. cancel by concern
