### ISSUE TITLE
Google analytics codes - got mixed up?

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeUKRegProductIssues#873]
Have the google analytics codes got muddled? See email for stats.

**Comment by Captainkirkdawson** [comment]
No.
Freereg on analytics refers to the original one set up for FR and is used by the original FR1 code
Freereg2 on analytics is the one set up for our new code

**Comment by Captainkirkdawson** [comment]
![analytics](https://cloud.githubusercontent.com/assets/2874694/21355629/fd0077c8-c68b-11e6-99d3-688e2a94dbb3.JPG)
