### ISSUE TITLE
62179957 Add Contact Us button in prominent position (Sandra)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#875]
Issue reported by **CommsCoord** at 2016-12-20 16:12:37 UTC
Time: 2016-12-20T16:09:20+00:00
Session ID: 36b23b3262ab4debe4a0e1835a8ae4ef
Problem Page URL: [/manage_resources/new](/manage_resources/new)
Previous Page URL: [http://www.freereg.org.uk/cms/refinery/login](http://www.freereg.org.uk/cms/refinery/login)
Reported Issue:
It might be a good idea to add a 'Contact Us' type button in places such as on the upper part of the Help page, at the minimum. It would make it easier for the public, rather than having to scroll and try to find a very small link buried at the bottom of a page    

![Screenshot](http://www.freereg.org.uk)

**Comment by AlOneill** [comment]
Two observations:

Plans to revise the footer will result in a larger link.

The footer is where many (or perhaps some, given our demographics?) expect to find a "Contact us" link: think about where you look for such a link on other sites (if it is not in the navigation at the top of a page ... )

**Comment by edickens** [comment]
Yes Ali, I agree that the Contact Us needs to be in the Footer, as now, 
even if the typeface is a bit small.

The question is more to do with people doing a Search not knowing how to 
either report a possible error, or to contact the Coordinators.  It is 
on the Search Results pages that a Contact Us needs to be more 
prominent, perhaps included in "Not found what you want, then look at 
the Help [link] for Tips on Searching, or if you know that the entry 
should be there, then Contact Us[Link]".  Or something like that.

At present the Search pages just concentrate on getting the results.

E

**Comment by Captainkirkdawson** [comment]
Not sure on my demographics but I look first at the main nav and then at the footer but I would not want us to add to main nav!!
I do think Erics suggestion on the message when no results are found is a good one. Perhaps @AlOneill  could propose the exact wording to be added
