### ISSUE TITLE
61753135 Destroy UserID Hangs after "Are you sure" (Eric)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#876]
Issue reported by **REGManager** at 2016-12-15 17:38:55 UTC
Time: 2016-12-15T17:36:29+00:00
Session ID: f28d1d3f4b18f475464560a2ef2659ba
Problem Page URL: [/userid_details/5852a865f493fd42b210691e](/userid_details/5852a865f493fd42b210691e)
Previous Page URL: [http://www.freereg.org.uk/userid_details/select?name=Yu:Bev](http://www.freereg.org.uk/userid_details/select?name=Yu:Bev)
Reported Issue:
Try destroying bevyu.

I've tried twice, same result.

I think I reported this some time ago and we thought it had been fixed.

E    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Appears to be associated with the removal of the physical directory for the user.

**Comment by Captainkirkdawson** [comment]
Changes have been made to the checking of the physical files code. Need to have confirmation that this has resoled issue
