### ISSUE TITLE
62203364 General Comment (David K Dawson)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#879]
Issue reported by **David K Dawson** at 2016-12-20 22:42:44 UTC
Time: 2016-12-20T22:41:56+00:00
Session ID: 384cdbffb0ad72b5044a4c76f9b0c9a1
Problem Page URL: []()
Previous Page URL: [http://localhost:3000/contacts/new](http://localhost:3000/contacts/new)
Reported Issue:
I hope to be right this time
http://localhost:3000/uploads/contact/screenshot/5859b3e4231040318c4b63c2/phone.JPG    

![Screenshot](localhost:3000/uploads/contact/screenshot/5859b3e4231040318c4b63c2/phone.JPG)

**Comment by Captainkirkdawson** [comment]
Yes
