### ISSUE TITLE
After an New UserID error, the website crashes (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#88]
Issue reported by **REGManager** at 2014-11-24 15:53:13 UTC
Time: 2014-11-24T15:45:18+00:00
Session ID: 607403544169709a2c71d65a8777725a
Problem Page URL: [/userid_details](/userid_details)
Previous Page URL: [http://test2.freereg.org.uk/userid_details/new](http://test2.freereg.org.uk/userid_details/new)
Reported Issue:
I am trying to enter the first person who has registered after 11 Nov.
The database has said that the email address exists, so perhaps it got picked up on the update as she completed registration on 12 Nov, but could have started earlier.  I should have checked to see if FR2 had her.  But a good test, because after this error, if I select "Manage UserIDs" the website crashes.
Attached shows the error message but I can't see the comment on the screen at the same time so this is all I can capture.

![Screenshot](http://test2.freereg.org.uk/tmp/carrierwave/1416844393-9658-8974/Capture.JPG)

**Comment by Captainkirkdawson** [comment]
Cannot duplicate by doing what you said you were doing. There is
insufficient information to diagnose. No error message is apparent.  Try to
duplicate and take screenshot personally and tell me exactly what you were
going

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by edickens** [comment]
```
Hi Kirk,

  I can't do it now either!!!!

  I'm sure this is what I did...
   
  Login
  Manage UserIDs
  Create UserID
  Enter this (copy and paste works)...
  The following person has just completed registration with FreeREG
```

Name: Christine Russ
Country: England
Email Address: kristinemiab@yahoo.co.uk
Coordinator: capn-bob@pegleg2.com
Submitter ID: ChrisR
Syndicate ID: DOR

```
  Fiche reader: False
  Straight forward forms
  Transcriber

  Submit

  You will get "Unsuccessful"

  Then select Manage UserIDs.

  E

  _____________________________________
```

Eric J Dickens
FreeREG Chairman
      On 24/11/2014 16:39, Kirk Dawson wrote:

```
Cannot duplicate by doing what you said you were
  doing. There is

  insufficient information to diagnose. No error message is
  apparent. Try to

  duplicate and take screenshot personally and tell me exactly what
  you were

  going


  Kirk Dawson

  Fairmont Hot Springs, B.C.

  V0B 1L1


  On Mon, Nov 24, 2014 at 8:53 AM, FreeUKGenIssues
  <notifications@github.com>

  wrote:


  > Issue reported by *REGManager* at 2014-11-24 15:53:13 UTC

  > Time: 2014-11-24T15:45:18+00:00

  > Session ID: 607403544169709a2c71d65a8777725a

  > Problem Page URL: /userid_details
  <http://userid_details>

  > Previous Page URL:
  http://test2.freereg.org.uk/userid_details/new

  > Reported Issue:

  > I am trying to enter the first person who has registered
  after 11 Nov.

  > The database has said that the email address exists, so
  perhaps it got

  > picked up on the update as she completed registration on 12
  Nov, but could

  > have started earlier. I should have checked to see if FR2 had
  her. But a

  > good test, because after this error, if I select "Manage
  UserIDs" the

  > website crashes.

  > Attached shows the error message but I can't see the comment
  on the screen

  > at the same time so this is all I can capture.

  >

  > [image: Screenshot]

  >
```

https://camo.githubusercontent.com/003d82c198aabac30bd5b4397253169b6f4046c4/687474703a2f2f74657374322e667265657265672e6f72672e756b2f746d702f63617272696572776176652f313431363834343339332d393635382d383937342f436170747572652e4a5047
      >

```
  > —

  > Reply to this email directly or view it on GitHub

  >
  <https://github.com/FreeUKGen/FreeUKGenProductIssues/issues/88>.

  >
  —
    Reply to this email directly or view
      it on GitHub.
```
