### ISSUE TITLE
62445746 Searching for entries with UCF starting with * (Eric)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#881]
Issue reported by **REGManager** at 2016-12-23 18:02:26 UTC
Time: 2016-12-23T17:58:35+00:00
Session ID: 66579eb90699dbb0ef74b4c84d4b127b
Problem Page URL: [/search_queries/new](/search_queries/new)
Previous Page URL: [http://www.freereg.org.uk/manage_resources/new](http://www.freereg.org.uk/manage_resources/new)
Reported Issue:
Cathy (transcriber) has reported that UCF searching is working well, but she has transcribed entries where the beginning of the name is lost due to the binding or the edge of the page being damaged.  So the name starts with a Star.  But these do not come up in a search.  And perhaps this also applies to names where the whole name is unreadable and is just a Star.
What should the server do?  E
http://http://www13.freereg.org.uk/uploads/feedback/screenshot/585d66b2f493fd4df8286356/    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/585d66b2f493fd4df8286356/_old_)

**Comment by benwbrum** [comment]
We have not yet enabled support for wildcards in UCF.  Testing this feature
has revealed a couple of bugs that need to be resolved before it's enabled
in production.  When it is enabled, her results should appear (provided her
search includes a place).

**Comment by edickens** [comment]
Hi Ben,
To be clear.  This is not entering UCF or Wildcard in the search 
criteria, but finding entries that were entered with UCF.  A Star is UCF 
representing more than one character.  A single character is an underscore.
Regards Eric

**Comment by Captainkirkdawson** [comment]
That is what 843 is all about
