### ISSUE TITLE
62272087 Website Problem (Christopher Sanders)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#882]
Issue reported by **Christopher Sanders** at 2016-12-21 17:48:07 UTC
Time: 2016-12-21T17:47:13+00:00
Session ID: 11e2da7ca862dd84c56075d3d68e6edd
Problem Page URL: []()
Previous Page URL: [http://freereg2.freereg.org.uk/contacts/new](http://freereg2.freereg.org.uk/contacts/new)
Reported Issue:
Glamorgan place names are not displaying when Glamorgan is first selected.
http://http://www13.freereg.org.uk/uploads/contact/screenshot/585ac057f493fd5632117de2/    

![Screenshot](http://www.freereg.org.uk/uploads/contact/screenshot/585ac057f493fd5632117de2/_old_)

**Comment by Captainkirkdawson** [comment]
Fixed

**Comment by ghost** [comment]
Thank you, and shall close this down.​

_________________________________________________________________________________

Sandra Adams-West
*FreeREG Communications Coordinator*
*__________________________________________________________________________________*
