### ISSUE TITLE
62942302 Cookie message (Chris Hodder)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#887]
Issue reported by **Chris Hodder** at 2016-12-29 11:58:22 UTC
Time: 2016-12-29T11:46:46+00:00
Session ID: 5dc9728e5913e0342b661b4f6928d56b
Problem Page URL: []()
Previous Page URL: [http://www.freereg.org.uk/contacts/new](http://www.freereg.org.uk/contacts/new)
Reported Issue:
Problem at home page of www.Freereg.org.uk on 17/12/16 at 17.24 and numerous previous occasions.

Calling up the page prompts the cookie warning and acceptance message to appear. This message overfills my screen and the accept tick box and continue button disappear from view. I am unable to scroll the message but when trying this I can see the page scroll bar moving in the direction I scroll.

I have tried changing my browser settings particularly font size and using desktop instead of mobile display. Despite the latter I am accessing the mobile site each time.

Freereg1 works but is no longer updated.

I accessed FreeCen ok after the same message was displayed but this one fitted my screen and I was able to tick accept and press the continue button. This suggests it is the web page and not my device or browser.

I have had this problem for some time now. 

This only happens with my Windows smart phone, Nokia Lumia 1520 OS 8.10.14226.359

I do not experience a problem using my laptop or desktop computer.

I have attached an image of 3 screenshots that I managed to save and hope this helps to explain.

Thank you for your help.
http://www13.freereg.org.uk/uploads/contact/screenshot/5864fa5ef493fde0264a4c26/FreeReg_cookie_warning_issue.jpg    

![Screenshot](http://www.freereg.org.uk/uploads/contact/screenshot/5864fa5ef493fde0264a4c26/FreeReg_cookie_warning_issue.jpg)

**Comment by edickens** [comment]
Same as I have just added to #617.  E

**Comment by AlOneill** [comment]
See #923 for my suggestions to modify the JavaScript on application.html.erb so that size of cookie notice text is reduced, along with other changes to improve access.

**Comment by Captainkirkdawson** [comment]
Sorry Alison never saw your suggestions in 923 as this is in the product backlog.
I tested your suggested changes including removal of opacity. These produced 
![cookie1](https://cloud.githubusercontent.com/assets/2874694/21578991/ab20e42a-cf54-11e6-8015-e8f8e2f4d183.JPG)
Did not like that so reintroduced opacity to 99. This produced 
![cookie2](https://cloud.githubusercontent.com/assets/2874694/21578997/f0fd66a8-cf54-11e6-908b-45d7d72b9c78.JPG)
This is better than the current one.
![cookie3](https://cloud.githubusercontent.com/assets/2874694/21579150/265537f6-cf5d-11e6-8905-b18aa7c85930.JPG)
But am not sure that it  will address the users comment which relates really to the number of words used.

**Comment by Captainkirkdawson** [comment]
I propose shortened wording to address concern.
![cookie4](https://cloud.githubusercontent.com/assets/2874694/21579269/91edbbae-cf63-11e6-9842-605eccf89025.JPG)

**Comment by AlOneill** [comment]
Do we need the checkbox? Many other sites use only a button.

Consider changing link text to "Cookie policy" -- the name of the page -- or vice versa!

As mentioned at scrum, current content has accessibility issues in addition to length of text. I think these are partly source-order  issues, in which case, even removing the checkbox would still leave the button way down the source order and so not reachable by a keyboard-only user, in effect.

Will investigate further on some accessible sites.

**Comment by Captainkirkdawson** [comment]
Have deployed revised text and colours to test3. Colours may need revision.
Need @edickens  to test on his phone

**Comment by Captainkirkdawson** [comment]
Yes both are required as we use explicit acceptance not implicit.
OK on link change
Await any other suggestions.
As I said at the scrum the background does not attract the eye hence many will miss the message. I accept black was too black but something in between? It needs to be different from teal since that confuses it with the rest of the site. Cen uses green which works well against their orange.

**Comment by AlOneill** [comment]
Looks like that will fit OK on a narrow screen.

White on dark grey would be OK, but the link would also have to be white and would need to look different in some other way too: underlined, bold or similar. Would then  need :hover and :focus styles. Same issues for any dark background colour.

Sorry, but the only Accessible colour-contrast combo is the button. I'll have a play with some other combos and get back to you.

**Comment by AlOneill** [comment]
**Opacity**: looks like our setting is overriding another setting, so deleting it does not set opacity back to 1 ('100' in js terms) as I had expected.

A background of #f7a21c, with (font) colour set to pure black would be OK. Do you like it?

Font-size is rather small, but think we can shorten wording further and so increase font-size a little. Will get back to you on that.

**Comment by AlOneill** [comment]
A link colour of #000080 would work with the colour combo I suggested above.

**Comment by AlOneill** [comment]
Oops, lost in translation: `#000080`

**Comment by Captainkirkdawson** [comment]
mutter mutter test3 has the latest set of changes. I liked it and it works
fine on a phone

I had changed text

OK have deployed #000080 on test3

Kirk Dawson
5220 Riverside Drive
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by edickens** [comment]
Yes, works perfectly on my iPod Touch.  E

**Comment by edickens** [comment]
PS.  The Accept button could be a little bigger.  It just looks like a dot.  E

**Comment by AlOneill** [comment]
The clickable area to toggle the checkbox will be larger once all Accessibility changes for cookie message are in place:  #923
