### ISSUE TITLE
63420349 FR2 is altering email addresses during upload/process (Staffordshire)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#888]
Issue reported by **STSCoord** at 2017-01-04 00:45:49 UTC
Time: 2017-01-04T00:35:43+00:00
Session ID: db6766d6302246cf9453ab1f1f7c3945
Problem Page URL: [/freereg1_csv_files/586b4080f493fdc9f6712cc6/edit](/freereg1_csv_files/586b4080f493fdc9f6712cc6/edit)
Previous Page URL: [http://www.freereg.org.uk/freereg1_csv_files/586b4080f493fdc9f6712cc6](http://www.freereg.org.uk/freereg1_csv_files/586b4080f493fdc9f6712cc6)
Reported Issue:
I have been submitting files for UserID Steffy. This UserID has an email address beginning with "fr2" recorded against it.
The file header of the uploaded files has the two email fields in the file header set up with an email address beginning "steffy". After the file has been processed by FreeREG, the file contains the "fr2" email address in the first email field of the file header and the second email field is blanked out.
My feeling is that FreeREG is replacing the email address in the file header with the email address associated with the submitting UserID. This would not normally be visible due to the same email address being used in both places (UserID and uploaded file)
This is wrong - luckily, as CC, I can change this BUT the problem does need reporting.    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/586c45bdf493fd88f9c6e6f6/_old_)

**Comment by ghost** [comment]
![sss](https://cloud.githubusercontent.com/assets/20557838/21654018/b4f1b380-d2ab-11e6-91d7-c91b77dbfc44.png)

Screen Shot of userID Steffy

**Comment by Captainkirkdawson** [comment]
This was a deliberate design decision and has been that way since day 1. We use userid information to the greatest extent possible. Almost nothing is taken from the headers as their content was often incorrect
