### ISSUE TITLE
Addition to Transcriber help page regarding Marriages (Ali)

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeUKRegProductIssues#889]
Can the following please be added to the transcriber help page regarding marriages:

If the register says 'under 21' or 'under age', or 'under', record this as 'minor' in the age field, and add a note as to what the register actually says.

**Comment by AlOneill** [comment]
Done:
http://www.freereg.org.uk/cms/information-for-transcribers/entering-data-from-registers#marrH
