### ISSUE TITLE
View Syndicate crash (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#89]
Issue reported by **REGManager** at 2014-11-24 18:26:03 UTC
Time: 2014-11-24T18:23:59+00:00
Session ID: b6ddc78eb7b708d97b39c50b109dd462
Problem Page URL: [/syndicates](/syndicates)
Previous Page URL: [http://test2.freereg.org.uk/manage_resources/new](http://test2.freereg.org.uk/manage_resources/new)
Reported Issue:
As REGManager Selected Member Functions; Syndicate Coordinators; Show Dorset.

![Screenshot](http://test2.freereg.org.uk/tmp/carrierwave/1416853563-40197-8954/Capture.JPG)

**Comment by Captainkirkdawson** [comment]
Some times I try to be too polite.
Was adding forename and surname to display; works nicely except when the fields are nil.
Fixed
