### ISSUE TITLE
63496189 Data Question (Sue Hadaway)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#890]
Issue reported by **Sue Hadaway** at 2017-01-04 21:49:49 UTC
Time: 2017-01-04T21:48:30+00:00
Session ID: 64cdd5d7437ab8c75a1f9a74715d3d8a
Problem Page URL: []()
Previous Page URL: [http://www.freereg.org.uk/contacts](http://www.freereg.org.uk/contacts)
Reported Issue:
http://www.freereg.org.uk/search_records/58184dd9e93790ec8b206b0b?search_id=586d6b91f493fdb82070e91d

Name should be John George Jeavons (shown as Jno George)    

![Screenshot](http://www.freereg.org.uk/uploads/contact/screenshot/586d6dfdf493fdb82070e947/_old_)

**Comment by ghost** [comment]
Closing as opened by mistake
