### ISSUE TITLE
Guide to forename abbreviations under Forename Variations in Help

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeUKRegProductIssues#891]
Added as an issue because of recent contact regarding 'Jno'. The contact did not know that this was the abbreviation for John. On the old FR there was a rather nice listing for many abbreviations, and this might be a welcome addition to assist researchers.

**Comment by edickens** [comment]
Yes, a documentation suggestion.  This needs to be linked to the Search system where abbreviations are linked together.  E

**Comment by Captainkirkdawson** [comment]
See 1040 as well

**Comment by Captainkirkdawson** [comment]
Dealt with in 1040
