### ISSUE TITLE
63737599 Website Problem (Peter Stuart)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#894]
Issue reported by **Peter Stuart** at 2017-01-07 16:53:19 UTC
Time: 2017-01-07T16:52:22+00:00
Session ID: 2d08269f974de1ae383aba365a7d24e7
Problem Page URL: []()
Previous Page URL: [http://freereg2.freereg.org.uk/contacts/new](http://freereg2.freereg.org.uk/contacts/new)
Reported Issue:
Kent A-Z out of kilter    

![Screenshot](http://www.freereg.org.uk/uploads/contact/screenshot/58711cfff493fd0d93b58bc8/_old_)

**Comment by Captainkirkdawson** [comment]
I am sorry but that statement is too cryptic for me to understand

**Comment by ghost** [comment]
If you look on the search page and click on Kent, it is not in alphabetical order.

**Comment by Captainkirkdawson** [comment]
OK Understood now
Will ry to fix latter in the day when quieter

Kirk Dawson
5220 Riverside Drive
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Captainkirkdawson** [comment]
Resolved
