### ISSUE TITLE
63969206 Message listing says No attachment when there is. (Eric)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#895]
Issue reported by **REGManager** at 2017-01-10 09:13:26 UTC
Time: 2017-01-10T09:11:43+00:00
Session ID: 2d7c30af58f47c3b990c653d045888c8
Problem Page URL: [/messages](/messages)
Previous Page URL: [http://www.freereg.org.uk/messages/5874a52ef493fd244a3cd3b0](http://www.freereg.org.uk/messages/5874a52ef493fd244a3cd3b0)
Reported Issue:
If you look at my Message of 10/01/2017 you will see that it say No  to attachment, but if you Show it, then there is.
Just a minor point.  E    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/5874a5b6f493fd244a3cd3b4/_old_)

**Comment by Captainkirkdawson** [comment]
Fixed
