### ISSUE TITLE
63536255 Give reason to User if they cannot log in because their account is Inactive (Eric)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#896]
Issue reported by **REGManager** at 2017-01-05 08:57:35 UTC
Time: 2017-01-05T08:54:33+00:00
Session ID: d96ea63d48f6e53bde4c30900d595603
Problem Page URL: [/userid_details/5462b420e937907d70000555](/userid_details/5462b420e937907d70000555)
Previous Page URL: [http://www.freereg.org.uk/userid_details/5462b420e937907d70000555/edit](http://www.freereg.org.uk/userid_details/5462b420e937907d70000555/edit)
Reported Issue:
Rather than just bouncing an Inactive UserID back to the home page, say that their Account is Inactive and they need to contact their Coordinator, or use the Contact Us link.
This has arisen because someone thought it was their browser or the server was down, not that their account was Inactive.    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/586e0a7ff493fda4f6dcd9c0/_old_)

**Comment by Captainkirkdawson** [comment]
Added a logout page so we can show ant message on logout such as this situation
