### ISSUE TITLE
64154061 Volunteering Question (AMELIA MARDEN)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#897]
Issue reported by **AMELIA MARDEN** at 2017-01-12 12:34:21 UTC
Time: 2017-01-12T12:33:14+00:00
Session ID: e92cf1ee7c381443ae5b06e8b90c0498
Problem Page URL: []()
Previous Page URL: [http://www.freereg.org.uk/contacts/new](http://www.freereg.org.uk/contacts/new)
Reported Issue:
I have received my email after registering to volunteer but the link i was sent to complete the registeration just goes to you homepage?
    

![Screenshot](http://www.freereg.org.uk/uploads/contact/screenshot/587777cdf493fd9637eefb15/_old_)

**Comment by ghost** [comment]
UserID  Meelystar

**Comment by edickens** [comment]
So does that mean that registration has been successful?  There
    could have been a red message.  She needs to just log in now.  I've
    looked at her UserID and all looks fine, although there is no
    indication that Registration was successfully completed.  E

**Comment by Captainkirkdawson** [comment]
There is no indication of registration completion.
Nor can I identify any issues.
Could  @CommsCoord please ask her to forward the email she received

**Comment by Captainkirkdawson** [comment]
Last successful registration completion was Date: Thu, 12 Jan 2017 12:05:26 +0000
which was 30 minutes after Amelia. 
Last software change was 10 Jan

**Comment by edickens** [comment]
Kirk has added a field to say if registration was completed, and I can 
now confirm that it was NOT.

If she still wants to register, then a Password Change needs to be 
sent.  She registered in Essex.

Eric J Dickens

**Comment by ghost** [comment]
Closing
