### ISSUE TITLE
64232868 Show if registration is incomplete (Eric)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#898]
Issue reported by **REGManager** at 2017-01-13 10:27:48 UTC
Time: 2017-01-13T10:24:30+00:00
Session ID: 1ae45ed30892c347b1bc1394061620a1
Problem Page URL: [/userid_details/58776a24f493fd9637eef9aa](/userid_details/58776a24f493fd9637eef9aa)
Previous Page URL: [http://www.freereg.org.uk/userid_details/selection?option=Select%20specific%20userid](http://www.freereg.org.uk/userid_details/selection?option=Select%20specific%20userid)
Reported Issue:
Would it be possible against a UserID profile to show if a registration had NOT been completed.  This messages is not needed after completion, but a warning when looking at the UserID would be very helpful.
And are there a lot of UserIDs on the database in this state?  They need to be found and deleted.  E    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/5878aba4f493fd0febd5e22f/_old_)

**Comment by Captainkirkdawson** [comment]
Line has been added to the profile to indicate registration is complete/not complete
