### ISSUE TITLE
64138072 Return to incorrect webpage when trying to re-upload a file (Staffordshire)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#899]
Issue reported by **STSCoord** at 2017-01-12 08:07:52 UTC
Time: 2017-01-12T07:59:29+00:00
Session ID: bb2929afb041c768bb9b8059f40d3140
Problem Page URL: [/csvfiles](/csvfiles)
Previous Page URL: [http://www.freereg.org.uk/csvfiles/new](http://www.freereg.org.uk/csvfiles/new)
Reported Issue:
I went through the process of uploading a file to FreeREG and received a "put on queue for overnight processing" message. Subsequent to this, I discovered a problem in the file that had been uploaded so I corrected the problem on my PC and tried to do the upload again. I received the message in the attached screenshot. From past experience of this problem, the uploaded filename appears to be blacklisted because, even a few days later, the message continues to be displayed.
http://www13.freereg.org.uk/uploads/feedback/screenshot/58773958f493fd9637eef53c/Capture.JPG    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/58773958f493fd9637eef53c/Capture.JPG)

**Comment by Captainkirkdawson** [comment]
@CommsCoord  could you please ask for the date and time that he experiences the issue so that I can explore the logs. Without that information its like looking for a needle in a haystack

**Comment by ghost** [comment]
Contact has responded that he cannot remember the time/date or userID connected with this issue.

**Comment by Captainkirkdawson** [comment]
Stumbled across  the situation while testing something else and have a fix ready for deployment
