### ISSUE TITLE
Changing the name of the Syndicate (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#90]
Issue reported by **REGManager** at 2014-11-24 19:13:29 UTC
Time: 2014-11-24T19:06:23+00:00
Session ID: a7fb29efd19c44e6c62aa4277244d303
Problem Page URL: [/syndicates/531a1117231040d7ef00000c/edit](/syndicates/531a1117231040d7ef00000c/edit)
Previous Page URL: [http://test2.freereg.org.uk/syndicates](http://test2.freereg.org.uk/syndicates)
Reported Issue:
Hi Kirk,

I seem to have done it again.  (I was known for doing this years ago!)
Another crash when changing the Syndicate name as attached.

E    

![Screenshot](http://test2.freereg.org.uk/tmp/carrierwave/1416856409-46249-4708/Capture.JPG)

**Comment by Captainkirkdawson** [comment]
Believe to have been resolved

**Comment by edickens** [comment]
```
Yes. Working. E
  _____________________________________
```

Eric J Dickens
FreeREG Chairman
      On 25/11/2014 01:25, Kirk Dawson wrote:

```
  Believe to have been resolved
  —
    Reply to this email directly or view
      it on GitHub.
```
