### ISSUE TITLE
64791301 Search for county of Essex (Stuart)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#900]
Issue reported by **vk3dwu** at 2017-01-19 21:35:01 UTC
Time: 2017-01-19T21:19:07+00:00
Session ID: 50d55ec2be928963418bf74987311aea
Problem Page URL: [/cms/information-for-transcribers](/cms/information-for-transcribers)
Previous Page URL: [http://freereg2.freereg.org.uk/manage_resources/new](http://freereg2.freereg.org.uk/manage_resources/new)
Reported Issue:
I tried to do a search for Essex but, after selecting that county, the place names list did not come up.  I pressed the search button anyway and a search of the entire county was done.  On pressing the Revise Search button, lo and behold, the place names list is displayed.  However, trying a New Search results in no place names list once again.

I have tried a few other counties  at random and Essex seems to be the only county with this problem.    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/58813105f493fdeeb6adf9c3/_old_)

**Comment by Captainkirkdawson** [comment]
Fixed
