### ISSUE TITLE
64933204 cannot see Scotland counties on GetScan (Doreen)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#901]
Issue reported by **deo123** at 2017-01-21 13:00:04 UTC
Time: 2017-01-21T12:51:41+00:00
Session ID: 4cc324a7c8462dfb5839ee8dfeb7dba5
Problem Page URL: [/contacts](/contacts)
Previous Page URL: [http://www.freereg.org.uk/contacts](http://www.freereg.org.uk/contacts)
Reported Issue:
I when using GetScan I can onyl see my Enland Counties, and not Orkney Scotland.    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/58835b54f493fd137ea34956/_old_)

**Comment by Captainkirkdawson** [comment]
The image servers are not part of FR and not supported by the FR development team. We are not in a position to comments on the ause or solution to this issue

**Comment by edickens** [comment]
Hi Kirk.  Doreen made this report because we thought it might be the 
UserID/Password file that you update every night which getscan then uses 
to know who can look at which county.  It may not be showing OKI as deo123.

E

**Comment by Captainkirkdawson** [comment]
All we do is send over a userid/password pair. 

What the image servers decide as a result of receiving them is up to that software.

**Comment by edickens** [comment]
Somewhere getscan matches UserIDs to their Syndicate(s).  Perhaps it is 
in FR1.  And I have just looked there and OKI was Sue Hawkins but is now 
deo123.  Hopefully problem solved.  Thanks E
