### ISSUE TITLE
Delete row functionality bug - WinFreeReg

### ISSUE THREAD

**Issue by richpomfret** [FreeUKGen/FreeUKRegProductIssues#902]
Delete row function neither deletes a single record (it removes two rows) nor does the file get saved properly without the deleted records. In current version 1.1.1

**Comment by EmJayFry** [comment]
Completed and released.

**Comment by richpomfret** [comment]
For Steve to take a look at.

**Comment by SteveBiggs** [comment]
Tested and works correctly with v1.1.4
