### ISSUE TITLE
65184743 Message system failed (Eric)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#903]
Issue reported by **REGManager** at 2017-01-24 10:52:23 UTC
Time: 2017-01-24T10:48:24+00:00
Session ID: 0b8806885b35e8523528b498de05c50f
Problem Page URL: [/messages](/messages)
Previous Page URL: [http://www.freereg.org.uk/manage_resources/new](http://www.freereg.org.uk/manage_resources/new)
Reported Issue:
I have just spent a long time creating a message for the integration of the image server and when I went to submit it I got the attached.  I  expect I was timed out as I have had to log in again.  I think a warning, as the banks do, that I am about to be timed out would help as I could have saved it.  I have to start again and it was very detailed.
A frustrated Eric
http://www13.freereg.org.uk/uploads/feedback/screenshot/588731e7f493fd56a4d4b1e8/Capture.JPG    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/588731e7f493fd56a4d4b1e8/Capture.JPG)

**Comment by ghost** [comment]
![capture](https://cloud.githubusercontent.com/assets/20557838/22244756/c1b77f22-e224-11e6-9422-63f286aa8b9c.JPG)

**Comment by Captainkirkdawson** [comment]
It is for that sort of reason that we provided the ability to attach text documents to a message.

You work off line on your own facilities until such a time as you have finished with the document and then simply attach it to the message.

This permits the document to be shared and edited by others before finalisation.

**Comment by edickens** [comment]
Will do in future.  This can be closed.  E

Eric J Dickens
