### ISSUE TITLE
Contact Sendgrid

### ISSUE THREAD

**Issue by richpomfret** [FreeUKGen/FreeUKRegProductIssues#904]
As next step in trying to resolve issues with spam/bouncing emails (specifically via ntlworld, virgin and blue yonder etc)

**Comment by edickens** [comment]
And 
    <shelley@yared.com.au>

today. 

    Eric J Dickens

    On 25/01/2017 18:38, Rich Pomfret
      wrote:
    
    
      As next step in trying to resolve issues with spam/bouncing
        emails (specifically via ntlworld, virgin and blue yonder etc)
