### ISSUE TITLE
65190036 Baptism date left blank?? (Ali)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#907]
Issue reported by **alsibk** at 2017-01-24 12:20:36 UTC
Time: 2017-01-24T12:17:00+00:00
Session ID: d648b04dd51b1e40c1c150f72fb428fb
Problem Page URL: [/cms/information-for-transcribers/entering-data-from-registers](/cms/information-for-transcribers/entering-data-from-registers)
Previous Page URL: [http://www.freereg.org.uk/cms/information-for-transcribers](http://www.freereg.org.uk/cms/information-for-transcribers)
Reported Issue:
This is the help for bap dates---

"Requirements:

    Enter the baptism date, or leave blank"

Surely "leave blank" is wrong. Causes 0 start dates.    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/58874694f493fd56a4d4b5dc/_old_)

**Comment by AlOneill** [comment]
Good catch. Fixed.
