### ISSUE TITLE
65189790 0 year report discrepancy (Ali)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#908]
Issue reported by **alsibk** at 2017-01-24 12:16:30 UTC
Time: 2017-01-24T12:07:55+00:00
Session ID: d648b04dd51b1e40c1c150f72fb428fb
Problem Page URL: [/registers/58204c4ff493fd31d9837a8b](/registers/58204c4ff493fd31d9837a8b)
Previous Page URL: [http://www.freereg.org.uk/churches/58204c3ff493fd31d3837ce8](http://www.freereg.org.uk/churches/58204c3ff493fd31d3837ce8)
Reported Issue:
WRY Ecclesfield is showing 0 year start, but all 3 files show expected date span.
http://www13.freereg.org.uk/uploads/feedback/screenshot/5887459ef493fd56a4d4b5b9/0_year_discrepancy.jpg    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/5887459ef493fd56a4d4b5b9/0_year_discrepancy.jpg)

**Comment by SteveBiggs** [comment]
I just checked this and it now correctly reports the start year as 1558:

![Capture.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/588631f51e19621a00230146/125516c66e82c728ace21e0d46cb958a379791accda5fd53b652fa912a5265296b51f02e7384e671e6162351580d4bac43585f45ffac8928f0a42062c80d55b98e30063e937f03a6aa811eb500bf2089478db3ba8c4cc3ef3437aa.jpg)

So can this be closed?
