### ISSUE TITLE
Creating a New Place Name does not get it in Alphabetic order

### ISSUE THREAD

**Issue by Sherlock21** [FreeUKGen/FreeUKRegProductIssues#909]
I: just created CREICH - in Scotland/ Sutherland. at Grid Ref NH634892.

It was created OK, but when searching for it, I find it is positioned at the top of the ALL Places list for SUT. instead of alphabetical order. NOTE that This County does not have alphabetic sub sets.

I have done several New Place names  in recent days and don't remember coming across this snag before.t

**Comment by Sherlock21** [comment]
STRANGE!

I have just created another New Place in SUT, and this one came sorted correctly. This one is Kildonan

**Comment by Captainkirkdawson** [comment]
What display of place are you talking about. There are many

**Comment by Captainkirkdawson** [comment]
There is a blank character at the start of CREICH. Corrected for you.

**Comment by Sherlock21** [comment]
Oh dear. Sorry about that. Removed the BUG label as its my typing!

Hard to tell that fault on the part of the typer.

CLOSE OUT or even Delete this. please.
