### ISSUE TITLE
Files omitted (Howdy)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#91]
Issue reported by **Howdy** at 2014-11-25 00:36:43 UTC
Time: 2014-11-25T00:34:36+00:00
Session ID: dbd0f883827923e79386f08bbfbb27e4
Problem Page URL: [/freereg1_csv_files/selection?_method=get&option=List+by+Filename](/freereg1_csv_files/selection?_method=get&option=List+by+Filename)
Previous Page URL: [http://test2.freereg.org.uk/freereg1_csv_files/selection?_method=get&option=List+by+Filename&page=3](http://test2.freereg.org.uk/freereg1_csv_files/selection?_method=get&option=List+by+Filename&page=3)
Reported Issue:
There are more than three AGY files in the database.    

![Screenshot](http://test2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Yes there are about 100 batches.

But only 3 of them are yours

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1
