### ISSUE TITLE
65802189 Processed files not showing (Ali)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#910]
Issue reported by **alsibk** at 2017-01-31 14:23:09 UTC
Time: 2017-01-31T14:21:00+00:00
Session ID: 16104cf8566b98191d873f0193f1f6af
Problem Page URL: [/freereg1_csv_files](/freereg1_csv_files)
Previous Page URL: [http://www.freereg.org.uk/manage_counties/select_action](http://www.freereg.org.uk/manage_counties/select_action)
Reported Issue:
Files processed today 31 Jan are not showing in lists.    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/58909dcdf493fd5747dcc81f/_old_)

**Comment by suffolkroots** [comment]
This report was cancelled subsequently so OK to close.
