### ISSUE TITLE
65886648 Sending Newsletter via the Server (Eric)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#911]
Issue reported by **REGManager** at 2017-02-01 13:50:48 UTC
Time: 2017-02-01T13:44:44+00:00
Session ID: 480d48073324b951316fdd6c068e0392
Problem Page URL: [/messages](/messages)
Previous Page URL: [http://www.freereg.org.uk/messages/new](http://www.freereg.org.uk/messages/new)
Reported Issue:
I've tried to send my newsletter by the server, and you can see the result in the list of messages where I copied and pasted the message, but have not sent it yet.

The problems are that all the images have been left out and I can only add one image and then not in the correct place.  Also the table of county statistics has no format,  but I could save that as a pdf file and attach it, if I could attach more than one file and I think attachments have to be jpg.

Thoughts?

E    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/5891e7b8f493fdbe2204ec8b/_old_)

**Comment by Captainkirkdawson** [comment]
Have to say I had never dreamed of you sending your excellent Newsletter through the messaging facility

**Comment by edickens** [comment]
Neither did I.  But in this week's newsletter I asked about a
    separate mailgroup for those wanting help reading images.  The
    replies I have had noted that, other than my Newsletter, that is all
    the mailgroup is used for.  So if I could do my newsletter through
    the server, then the transcribers mailgroup could  be used just for
    reading images.  We find that some have unsubscribed because of the
    traffic on reading images, and so my newsletter does not reach every
    Active transcriber.
    
    I could save my Newsletter as a pdf and send as an attachment if the
    Server's message system accepted that.

**Comment by PatReynolds** [comment]
put in a link to a pdf on gdrive or web site  [ @DeniseColbert to aid if needed ]
