### ISSUE TITLE
65886165 Remove batch wrong message (Ali)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#912]
Issue reported by **alsibk** at 2017-02-01 13:42:45 UTC
Time: 2017-02-01T13:40:57+00:00
Session ID: 0962d187bad74a641a3e83e35388f081
Problem Page URL: [/manage_resources/new](/manage_resources/new)
Previous Page URL: [http://www.freereg.org.uk/freereg1_csv_files/54638dafe9379010fc419ff9](http://www.freereg.org.uk/freereg1_csv_files/54638dafe9379010fc419ff9)
Reported Issue:
Having removed a batch I am warned "The batch document you are trying to access does not exist. "    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/5891e5d5f493fdbda904f9c8/_old_)

**Comment by Captainkirkdawson** [comment]
Likely you used the back button to go to a batch that no longer exists

Kirk Dawson
5220 Riverside Drive
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by suffolkroots** [comment]
Likely I didn't---

Specific place/church/register/batch/remove batch/Are you sure?/Yes/The batch document you are trying to access does not exist.

**Comment by Captainkirkdawson** [comment]
In which case you will need to provide specific information on the your
navigation to the batch in question.  ie, which place church register and
batch


Kirk Dawson
5220 Riverside Drive
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by suffolkroots** [comment]
This relates to the removal of 2 batches in F2. I have also tested it in Test3.

Specific navigation in F2 =
Manage County/Specific Place/Leeds/Nonconformist Congregational/Unspecified/WRYLEEBA.CSV/Remove batch/OK
Manage County/Specific Place/Leeds/Nonconformist Congregational/Unspecified/WRYLEEBA1.CSV/Remove batch/OK

Message received in all cases--The batch document you are trying to access does not exist.

**Comment by Captainkirkdawson** [comment]
Was trying to go back to display the deleted batch. Go back to register instead. Waiting for deployment to production

**Comment by Captainkirkdawson** [comment]
While this specific story is resolved (when deployed) it is a significant puzzle that there remains a requirement to delete a batch. 
When we first moved from FR1 there was likely a need but now after nearly 2 years of FR why we still find it necessary to  delete batches is unnerving at the very least.

**Comment by Captainkirkdawson** [comment]
Tonight I see that we deleted 34918 records in 3 batches for 1 place.

" Starting 1  58212ffff493fdad75307bb2,JanetOgden,WRYCAVBA.csv\n"
8200 records deleted for 58212ffff493fdad75307bb2,JanetOgden,WRYCAVBA.csv
" Starting 2  54639973e93790278284294b,JanetOgden,WRYCAVBU.csv\n"
24556 records deleted for 54639973e93790278284294b,JanetOgden,WRYCAVBU.csv
" Starting 3  5463999fe937902782854910,JanetOgden,WRYCAVMA.csv\n"
2162 records deleted for 5463999fe937902782854910,JanetOgden,WRYCAVMA.csv
" 34918 records deleted"

If they were duplicates yes but if not why???

**Comment by suffolkroots** [comment]
I found it necessary to change the place code in these file names. There is no facility for this in FR, so they needed to be deleted, amended and re-uploaded.  >:(

**Comment by Sherlock21** [comment]
The other reason was that the file size in at least 1 of them, was greater than the user could do. - 24,000 records I think for one. And it was out of range for me too.

So this seemed only option. - at least we now have files that we can manage wight he tools we have between us, without having to try and get Kirk to do it every time.

**Comment by Captainkirkdawson** [comment]
There is no requirement within FR for file names to follow any convention.
File names are invisible to researchers. FR is not a file based system.
This action made the system unusable for nearly 6 hrs.

Kirk Dawson
5220 Riverside Drive
Fairmont Hot Springs, B.C.
V0B 1L1
