### ISSUE TITLE
65880907 email true/false profile editing (Ali)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#913]
Issue reported by **alsibk** at 2017-02-01 12:15:07 UTC
Time: 2017-02-01T12:12:56+00:00
Session ID: f290a711dbddce60c46c79089c971d71
Problem Page URL: [/userid_details/5462b41ae937907d70000457/edit](/userid_details/5462b41ae937907d70000457/edit)
Previous Page URL: [http://www.freereg.org.uk/userid_details/5462b41ae937907d70000457](http://www.freereg.org.uk/userid_details/5462b41ae937907d70000457)
Reported Issue:
There is no option while editing an ID to set email address as invalid    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/5891d14bf493fdbda904f681/_old_)

**Comment by richpomfret** [comment]
We can add to the 'help' section here i.e. set user to inactive (email invalid comment to be added also).

**Comment by Captainkirkdawson** [comment]
There is currently an email address field. A user is asked to confirm the address at login after a period of inactivity. Requirement: add an capability to allow a manager to change the set the email address as Invalid or valid

**Comment by Captainkirkdawson** [comment]
Coding added by @bev-fc  and committed to master on test3 for checking

**Comment by SteveBiggs** [comment]
Tested in test3 and it works fine.

**Comment by richpomfret** [comment]
To deploy to live/production.
