### ISSUE TITLE
66073447 Data Problem (Bill Ward)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#916]
Issue reported by **Bill Ward** at 2017-02-03 17:44:07 UTC
Time: 2017-02-03T17:35:36+00:00
Session ID: acb17cb7c62dc4d43c2988806476200d
Problem Page URL: [unknown](unknown)
Previous Page URL: [http://www.freereg.org.uk/contacts/58187c70e93790ec8b838853/report_error?query=5894bc1f791e3b4880d70233](http://www.freereg.org.uk/contacts/58187c70e93790ec8b838853/report_error?query=5894bc1f791e3b4880d70233)
Reported Issue:
This is a very minor correction. My search on surname Joyce in Leicestershire gave 42 results. Rows 38 and 39 seem to be duplicates except one is John Hill Joyce and the other John Hall Joyce. John Hall Joyce is the correct version, I believe. He was the son of John Hall Joyce and his wife, Mary Ward (which explains my interest). Confusingly the son  also had a son they called John Hall Joyce. The 3 JHJs were born in 1803, 1833 & 1868.      

![Screenshot](http://www.freereg.org.uk/uploads/contact/screenshot/5894c167f493fd12aca534ca/_old_)

**Comment by SteveBiggs** [comment]
Isn't this a data question that should be dealt with by Commscord or SC/CC as appropriate?

**Comment by Captainkirkdawson** [comment]
@SteveBiggs    Agreed 100%

**Comment by CommsCoord** [comment]
I will take care of this but does anyone know where it came from? There was
nothing on the contacts or feedback pages.​

Kind regards
The Communications Team

**Comment by ghost** [comment]
Unfortunately there is no identifying information contained in the email to respond, and the link goes back to the data report page. The screen shot is not accessible either. If Mr Ward views this, please email the Communications Team at comscoord.freereg@freeukgenealogy.org.uk. Closing this down as there is nothing more that can be done at this point.
