### ISSUE TITLE
66664758 double record numbers (Doreen)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#918]
Issue reported by **deo123** at 2017-02-10 13:59:18 UTC
Time: 2017-02-10T13:56:22+00:00
Session ID: 5c4840dc62f2511ea08e049521c36d42
Problem Page URL: [/freereg1_csv_entries](/freereg1_csv_entries)
Previous Page URL: [http://www.freereg.org.uk/freereg1_csv_files/586cdea5f493fd22a958bf69](http://www.freereg.org.uk/freereg1_csv_files/586cdea5f493fd22a958bf69)
Reported Issue:
Hi,

can you eplain the double record numbers ont he left side of each record please?
Regards Doreen

http://www13.freereg.org.uk/uploads/feedback/screenshot/589dc736f493fd2f7596bffc/double_record_numbers.JPG    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/589dc736f493fd2f7596bffc/double_record_numbers.JPG)

**Comment by Captainkirkdawson** [comment]
Ask the transcriber. They are the entry number fields written in the register and entered by the transcriber.

**Comment by Sherlock21** [comment]
Kirk: I beg to differ. These are not theTranscriber's Register numbers surely.

I  just checked one of my own files where I have NO register numbers, yet in View Batch online, these records are showing a sequential record number - 1 to 247 .

Please refer to my research on ref number 1104 for further investigation and my request.

**Comment by Captainkirkdawson** [comment]
You are likely correct and I am wrong.

**Comment by Captainkirkdawson** [comment]
Tiss time for my retirement

**Comment by Sherlock21** [comment]
Maybe our difference is in the way we describe things.?

I have investigated the history of the file in CON / LUXULYAN and its file by P Hoare: CONLUXMA.csv.
There is nothing wrong with the files as input - i.e. no duplicate records in any.
BUT if one does a Show online, each row if the data is different to any other, BUT the first column of the display is titled: Record Number and its not unique.
Yesterday, there were duplicates of  numbers 5 and also 6, on the first page. others elsewhere. BUT the people were different names - i.e. the firstRecord No.  5 was for Ann Grose and the second Record no 5 was for Sarah Whitford.

looking art the actual file which i downloaded, these numbers 5, 6 etc do not appear in the record. They are not the Register ref nbrs. - there are in fact No register ref nbrs in this file.
SO 5,6 etc have come form the application somewhere.

BUT they don't cross match with anything. if one looks at  the details link, the record numbers on there are different in each of the 5's and in each of the 6's.

These record numbers( col 1 on the Batch display) appear to have no function as far as I can see, and the CC's are confused by them too,

SO if not used by either the CC nor the DM, please don't display them

**Comment by Captainkirkdawson** [comment]
Interesting.

**Comment by Captainkirkdawson** [comment]
![screen shot 2017-02-12 at 19 25 16](https://cloud.githubusercontent.com/assets/2874694/22947296/b8ba5928-f2b7-11e6-9f86-69d2506d4feb.png)

**Comment by Captainkirkdawson** [comment]
I believe this to be a deep seated issue. I suspect any file that has updated records in a file with a different sort order will result in this in this symptom.  This will apply to both the line number and line id. These were originally added to assist in locating a specific record physically with in a file. Replacing and on-line editing destroy the original order. The line number and id serve no purpose within FreeREG itself. They are not displayed to the researcher.  Record are identified by their unique document number and this is assigned by the system and remains with them at all times.
Suggested solution is to remove their display and to stop assigning them in the future.

**Comment by Sherlock21** [comment]
I am pleased that you appear to have found the cause, and the solution.
Lets give it a try.
i know some other file that show this effect too so plenty to use as a test.
So lets give it a go in T3?

**Comment by Sherlock21** [comment]
Although I am content to not have row numbers in a "Show Batch online" I discussed it with a CC, and they are NOT happy to loose this means of navigating back to the point from which they last were working. SO speaking for CC's and CS's to loose the row number would a retrograde step.

**Comment by edickens** [comment]
I've not been following this thread in detail, but we must show 
reference numbers back to the register and back to the image, as well as 
to the transcription.  We ask researchers to check so they need to be 
able to do this easily  E

**Comment by Sherlock21** [comment]
Yes, If References are shown in the Register, then they must be shown as you say.

but this story relates to a file where the Register did not show References. and these which have come out as duplicates are from numbers that Kirk added for processing reasons - see his item above .

There are many source docs that do not have reference numbers in them. and there are also many where the Ref number started at 1 again each January 1st. So if the file covers several years, one does get naturally occurring multiple records for each ref nbr. But as I say far above, these odd duplicates did NOT come in from the source docs.

**Comment by Sherlock21** [comment]
Please hold off doing anything to change the situation for a while Kirk

I need another conversation with the originator of this item. Eric

**Comment by Sherlock21** [comment]
After a reconsideration of the 3 options, The CC who raised the issue, and Myself agree to withdraw this request.

PLEASE CLOSE OR CANCEL IT.

**Comment by edickens** [comment]
Do you want to keep this as an enhancement to the reports in a
    future version?  Say V1.7 Researchers enhancement?  E

**Comment by Sherlock21** [comment]
Kirks' view that its reasonable for the CC to edit online  up to a limit of 30 to 50 rows in a batch. Above that, its more effective for all, to do a download, and replace - via the DM - can be tolerated in the circumstances - for records up to 4,000 rows.

Against this background therefore I think that only the option to fix the code so that these system generated Row Numbers are truly unique, is worth doing.

**Comment by Captainkirkdawson** [comment]
As stated earlier to "fix" the issue requires that we revert to processing
all of the records in a file rather than those records that have changed.

It also means reprocessing all existing files.

If we do that then we will truly have to operate FR as a file based system
aka FR1 and rebuild it monthly.

There are benefits to such a system as it makes it easier to change search
records and indexes. Search performance becomes much more reliable and
predictable.

The downside is that the rebuild will take a full week each month, some new
automation code and upload/processing code and removal of the majority of
the current coordinator actions as they will no longer be relevant.

If that is what you want then raise that as the story.



Kirk Dawson
5220 Riverside Drive
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Sherlock21** [comment]
My view at this point in time is NO.
