### ISSUE TITLE
66555234 New registration for "General" when not recruiting (Eric)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#919]
Issue reported by **REGManager** at 2017-02-09 07:33:54 UTC
Time: 2017-02-09T07:30:44+00:00
Session ID: 23ac77f481824c9859ae1da9fd9bd727
Problem Page URL: [/syndicates](/syndicates)
Previous Page URL: [http://www.freereg.org.uk/manage_resources/new](http://www.freereg.org.uk/manage_resources/new)
Reported Issue:
UserID sameera.bachoti has registered for the "General" syndicate, but it is not recruiting and is not an option in "Volunteer".  How did they manage to do it?    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/589c1b62f493fd71de2c04f1/_old_)

**Comment by edickens** [comment]
Have now found that they registered in Test3 and is a new member of
    the team.
    
    This can be closed.
    
    E
    Eric J Dickens

    On 10/02/2017 19:14, FreeUKGenIssues
      wrote:
    
    
      Issue reported by REGManager at 2017-02-09
        07:33:54 UTC
        Time: 2017-02-09T07:30:44+00:00
        Session ID: 23ac77f481824c9859ae1da9fd9bd727
        Problem Page URL: /syndicates
        Previous Page URL: http://www.freereg.org.uk/manage_resources/new
        Reported Issue:
        UserID sameera.bachoti has registered for the "General"
        syndicate, but it is not recruiting and is not an option in
        "Volunteer". How did they manage to do it?
      
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/FreeUKGen/FreeUKRegProductIssues","title":"FreeUKGen/FreeUKRegProductIssues","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/FreeUKGen/FreeUKRegProductIssues"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"66555234 New registration for \"General\" when not recruiting (Eric) (#919)"}],"action":{"name":"View Issue","url":"https://github.com/FreeUKGen/FreeUKRegProductIssues/issues/919"}}}
