### ISSUE TITLE
Did not return marriage results when christian name  not used (Mick)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#92]
Issue reported by **Mick** at 2014-11-25 11:44:13 UTC
Time: 2014-11-25T11:40:29+00:00
Session ID: f58829c4d0326d8fbf4df9c90b21a5a9
Problem Page URL: [/search_queries/new?search_id=54746aa7e93790641b000002](/search_queries/new?search_id=54746aa7e93790641b000002)
Previous Page URL: [http://test2.freereg.org.uk/search_queries/54746aa7e93790641b000002](http://test2.freereg.org.uk/search_queries/54746aa7e93790641b000002)
Reported Issue:
Carried out a search for the marriages of William HOFF in Lincolnshire and  the search returned several hits. However if I just searched for HOFF marriages in Lincolnshire I got an error message.    

![Screenshot](http://test2.freereg.org.uk/tmp/carrierwave/1416915853-44239-7780/HOFF_search.JPG)

**Comment by benwbrum** [comment]
Great find!  This appears to be due to a nil transcript date for one of the records returned in this result set:

```
 NoMethodError in Search_queries#show

Showing /home/apache/hosts/freereg2/MyopicVicar/app/views/search_queries/show.html.erb where line #89 raised:

undefined method `gsub' for nil:NilClass

Extracted source (around line #89):

86:             <%= RecordType::display_name(search_record.record_type) %>
87:             </td>
88:             <td>
89:             <%= raw(search_record.transcript_date.gsub(' ', '&nbsp;')) %>
90:             </td>
91:             <td>
92:             <%= ChapmanCode::name_from_code(search_record.chapman_code) %>
```
