### ISSUE TITLE
66259603 Remove Tabbing that includes Info Heading in search Form - communicate new system

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#920]
Issue reported by **Peter Clarke** at 2017-02-05 21:26:43 UTC
Time: 2017-02-05T21:09:05+00:00
Session ID: 203531c0a54e17aa964e2c6d11e08cea
Problem Page URL: []()
Previous Page URL: [http://freereg2.freereg.org.uk/contacts/new](http://freereg2.freereg.org.uk/contacts/new)
Reported Issue:
Hi,

On the current version of the query form, (yes I know its been this way for a little while), if you use the tab button to move from data input box to data input box it actually takes you to the header above the box.

For example if you input a surname and then tab to the next input box to add a forename, it will instead take you to the header "Forename(s)". Hitting tab again takes you into the box. 

In my case its frustrating as I'm not a touch typist, so I'll tab once and happily type in the forename, etc, only to look up to see that nothing has come up.

There would not appear to be any value in high-lighting the box header and simply makes for a poorer user experience.  Any chance of simply being able to tab once from box to box.

Thanks,
Peter    

![Screenshot](http://www.freereg.org.uk/uploads/contact/screenshot/58979893f493fd041a6a6dd7/_old_)

**Comment by Captainkirkdawson** [comment]
It performs this way to make the site usable by people with disabilities particularly who use voice navigation. If we were to eliminate it they would not know where they were in the form.

**Comment by AlOneill** [comment]
Kirk is almost right! It works that way particularly for those who _cannot_ use a pointing device, such as mouse, touchpad, etc. They cannot hover over the "i" icon, but have to move around a page using the keyboard.

**Comment by AlOneill** [comment]
I am only too aware of the awkwardness of needing to hit tab twice to get from one input to the next. I would dearly love to find/devise a solution that pleased all users equally: given the complex nature of our requirements for accessibility and responsiveness (to device size), the current setup is the best compromise I have come up with. 

The issue remains on my TODO list. I will keep thinking and searching, but don't hold your breath!

**Comment by richpomfret** [comment]
I don't think we need to change this - we do need to communicate why it is there via comms.
