### ISSUE TITLE
Lower Date Limit

### ISSUE THREAD

**Issue by EmJayFry** [FreeUKGen/FreeUKRegProductIssues#922]
WinREG and WinFreeREG both use the same code to validate dates. The main regular expression that performs most of the validation sets a lower limit of 1538 for the year. Any dates preceding this year are flagged as errors.

1538 is the year when Henry VIII ordered that churches should start keeping Parish Records. The actual date of this decree was 5th September, bur the code rejects 1537 and earlier.

When this code was first implemented, we were only transcribing Parish Registers. That assumption no longer holds true.

**Comment by SteveBiggs** [comment]
I agree that we need to remove this lower date limit since we could be transcribing monumental inscriptions or other sources that go back before 1538. FR itself imposes no limit as a far as I know.

**Comment by edickens** [comment]
Correct, and we have had pre-1000.  Cathedral records.

Also, not every register used the split year when they should or should 
not have done.  We should TWYS.

E

**Comment by EmJayFry** [comment]
Okay, I'll make the change in WinFreeREG. I won't change WinREG.

**Comment by EmJayFry** [comment]
Further investigation shows that WinFreeREG will already accept dates starting from 01 Jan 1000. What it will also do is flag dates in the Jan-to Mar24th as REQUIRING to be double-dated. So, the only problems are with dates prior to the 11th century. Specifying the year as either 3 or 4 digits causes the same 'Badly Formatted' error.

**Comment by edickens** [comment]
The three digit years are so rare that is it best to edit afterwards as 
a text field and insert a leading zero.  E

**Comment by EmJayFry** [comment]
DONE! You can now enter years from 000 (minimum of 3 digits) to 9999 :-) e.g 13Mar0999/00
