### ISSUE TITLE
67602012 Confirming email addresss looks like a new registration (Eric)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#924]
Issue reported by **REGManager** at 2017-02-21 10:20:12 UTC
Time: 2017-02-21T10:15:24+00:00
Session ID: 67276a4e55f711eaae0aa7325d0f95c5
Problem Page URL: [/userid_details/5824af03f493fdeb5a391f9c](/userid_details/5824af03f493fdeb5a391f9c)
Previous Page URL: []()
Reported Issue:
We are receiving the "New registration" emails when someone confirms their email address.  This results in us welcoming them when they are already transcribers.  This causes confusion.    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/58ac145cf493fde149a26fb9/_old_)

**Comment by Captainkirkdawson** [comment]
Could you please provide an example of what you are receiving and what the person has done.

**Comment by Captainkirkdawson** [comment]
Actually nothing to do with the confirmation process but there were circumstance when a password change was missed which could lead to this symptom.
Have applied a band aid to that symptom. 
Added a notification of email address change to SC

**Comment by richpomfret** [comment]
For Eric to test. On test3.

**Comment by edickens** [comment]
As a transcriber I have changed my email address and as SC got the confirmation that I changed the address and I did not get the new registration email.  So it works.  Done.
