### ISSUE TITLE
67741421 Data Question (John Foster)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#925]
Issue reported by **John Foster** at 2017-02-23 01:03:41 UTC
Time: 2017-02-23T00:45:23+00:00
Session ID: 0dc6689ba662ea6908bc041f4594e600
Problem Page URL: []()
Previous Page URL: [https://www.freereg.org.uk/contacts](https://www.freereg.org.uk/contacts)
Reported Issue:
I just encountered your "broken link" page after using an old bookmark (freereg2.freereg.org.uk), and I was amused to see that the page itself contained a form of broken link. The link to freereg.org.uk will work fine when clicked, but anyone writing the address down or re-typing it from what they see will get to https://www.frereg.org.uk/ (missing 'e').

Not the world's greatest problem perhaps but it does seem unfortunate when a page advising a user of their error itself contains a further error... :-)
http://www13.freereg.org.uk/uploads/contact/screenshot/58ae34edf493fde149a2c073/Screenshot_from_2017-02-23_00-58-55.jpg    

![Screenshot](http://www.freereg.org.uk/uploads/contact/screenshot/58ae34edf493fde149a2c073/Screenshot_from_2017-02-23_00-58-55.jpg)

**Comment by Captainkirkdawson** [comment]
Thank him for me. I never could spell.

Corrected now

**Comment by ghost** [comment]
Done. Closing now.
