### ISSUE TITLE
67962156 Won't let me replace  (Somerset)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#926]
Issue reported by **SOMCoord** at 2017-02-25 14:22:36 UTC
Time: 2017-02-25T14:19:32+00:00
Session ID: fd7f6be8c8105276755157d7b0f6bff7
Problem Page URL: [/csvfiles/54cd7ce4e93790802f112e5e/edit](/csvfiles/54cd7ce4e93790802f112e5e/edit)
Previous Page URL: [https://www.freereg.org.uk/freereg1_csv_files/54cd7ce4e93790802f112e5e](https://www.freereg.org.uk/freereg1_csv_files/54cd7ce4e93790802f112e5e)
Reported Issue:
Have updated SOMAXBMA2 with extra records. Have tried twice to Replace existing file with updated file but each time I get a red something went wrong notice from FR. 
Please advise what I should do next?
Jackie James
SOMCOORD    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/58b1932cf493fd1b3692dfd2/_old_)

**Comment by ghost** [comment]
Converted to issue as this is not the only report of issues with replacing and uploading of files. Several are being rejected as the place names not matching when it is the same as what is on FR, or issues with the church/chapel names, particularly if there is a hyphen in the name (i.e. Glan-rhyd) even though the name is what is on FR.

**Comment by Captainkirkdawson** [comment]
The coordinator in question was doing something that is definitely not recommended will lead to significant downstream issues.  (We discussed this yesterday off line)
Recent changes drew what was being attempted  to light. 

We will put in a patch to stop the red screen (always unnerving) but NOT to permit the action. 

The action being attempted was to replace the file of a transcriber but trying to put the replaement file into a different userid. 

By definition a replacement must always be into the same userid space as the original.

I cannot respond to the other comments as they provide insufficient information

**Comment by Sherlock21** [comment]
Thanks for this info,Kirk.
I shall worry no more about this one then.

**Comment by Captainkirkdawson** [comment]
Trap situation where coordinator replaces a file for a userid without specifying that userid thereby "attempting to move the file"
