### ISSUE TITLE
68305524 Files waiting processing (Ali)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#927]
Issue reported by **alsibk** at 2017-03-01 13:45:24 UTC
Time: 2017-03-01T13:43:40+00:00
Session ID: 1a188d41bad2af99ab7ba728568b54e0
Problem Page URL: [/manage_counties/display_files_waiting_to_be_processed](/manage_counties/display_files_waiting_to_be_processed)
Previous Page URL: [https://www.freereg.org.uk/manage_counties/select_action](https://www.freereg.org.uk/manage_counties/select_action)
Reported Issue:
Files awaiting processing are not being listed in CC actions, but are in SC actions.    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/58b6d074f493fd2e71705cf4/_old_)

**Comment by Captainkirkdawson** [comment]
Sorry do not understand.

Are you saying that the action is not available to a county coordinator? You do not have the 2 actions?

![countyactions](https://cloud.githubusercontent.com/assets/2874694/23535053/39588500-ff79-11e6-9d77-d492f7888112.JPG)

**Comment by suffolkroots** [comment]
Files awaiting processing are not being listed in CC actions, but are in SC actions. The actions are both there but the files are not being listed in CC 
![waiting processing](https://cloud.githubusercontent.com/assets/10379655/23540823/9aaf3ce2-ffdb-11e6-81d5-92e1c7ba24f2.JPG)

**Comment by richpomfret** [comment]
Needs further investigation.

**Comment by Captainkirkdawson** [comment]
After investigation we concluded that there was no way to implement the capability for a county coordinator and have removed the action
