### ISSUE TITLE
68053371 PATRONYMIC SEARCHES (Wales)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#928]
Issue reported by **Admin-Wales** at 2017-02-26 15:42:51 UTC
Time: 2017-02-26T15:38:57+00:00
Session ID: 2c29257e4fd51450cd4203324d15bf1b
Problem Page URL: [/manage_resources/new](/manage_resources/new)
Previous Page URL: []()
Reported Issue:
I suggest that FreeREG has a system not of entering patronymics but of searching for them. In Wales and Cornwall, we have no way of knowing from the register what is patronymic or not with the exception of 'ap' being added before a name. This means that the data can be entered as normal with the last name of the person identified as a 'possible' surname. However, the researcher should have the opportunity in Wales and Cornwall etc to search forenames for patronymic relations. In this way, there would be no need to provide a different entry for patronymic data.  

Could this be easier for FR techs in that it could be added to the Search Options box with family members, witnesses, nearby places and name soundex searches?
    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/58b2f77bf493fd1b36930ae5/_old_)

**Comment by Captainkirkdawson** [comment]
Like the lateral thinking

**Comment by Captainkirkdawson** [comment]
I believe the proposed changes under flexible_csv #809 will allow the names to entered appropriately. The search already supports through family members
