### ISSUE TITLE
Drop down lists should not start witha blank entry (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#93]
Issue reported by **REGManager** at 2014-11-25 12:00:28 UTC
Time: 2014-11-25T11:57:03+00:00
Session ID: ff24477d70d8d74700339584005dd06f
Problem Page URL: [/userid_details/all](/userid_details/all)
Previous Page URL: [http://test2.freereg.org.uk/userid_details/5462b41be937907d7000048a/edit](http://test2.freereg.org.uk/userid_details/5462b41be937907d7000048a/edit)
Reported Issue:
I have just noticed at the top of the list of UserIDs that there is a blank.  See screenprint attached.
This shows in the selection list when I ask to find a UserID, but if I select, it seems to be asking to display "all" but then says that this cannot be displayed.    

![Screenshot](http://test2.freereg.org.uk/tmp/carrierwave/1416916828-49615-7086/Capture.JPG)

**Comment by Captainkirkdawson** [comment]
I have been inconsistent in some selects a blank was included in others it was not.
I was leaning towards always including a blank since the action detection is one of change. 
An action detection of click caused too many problems with opening and navigating within the select box.

**Comment by juliancheal** [comment]
On for example Mange Syndicates, if we don't have a blank item as the first item we won't be able to select Aberdeenshire.
An alternative would be to have prompt text, for example like this:

![screen shot 2015-02-02 at 18 51 13](https://cloud.githubusercontent.com/assets/63991/6006785/2783256e-ab0d-11e4-8f32-63f163fc5480.jpg)
But with better text than "Select..."

**Comment by Captainkirkdawson** [comment]
Julian

Agree with your approach
