### ISSUE TITLE
Update tech set-up documentation

### ISSUE THREAD

**Issue by richpomfret** [FreeUKGen/FreeUKRegProductIssues#930]
To include a recommendation for a new dev user to select 'technical' syndicate/group when signing up. Otherwise Jo automatically prepares/sends out a training mail.

**Comment by Captainkirkdawson** [comment]
Done

**Comment by edickens** [comment]
The thing to remember is that the Technical SC needs to change the Role when the Development User has registered, otherwise they will not get all the Actions.  In fact many UserIDs are still "Learning", the default, when the SC should upgrade them as necessary.  E
