### ISSUE TITLE
68738040 Duplicate files created on upload (Stephen)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#931]
Issue reported by **SBManager** at 2017-03-06 13:54:00 UTC
Time: 2017-03-06T13:49:52+00:00
Session ID: da09bf2f98586309df24567e4309aa2e
Problem Page URL: [/registers/589b38e3f493fdf8d119243f](/registers/589b38e3f493fdf8d119243f)
Previous Page URL: [https://www.freereg.org.uk/freereg1_csv_files/58bca990f493fd76f6255699](https://www.freereg.org.uk/freereg1_csv_files/58bca990f493fd76f6255699)
Reported Issue:
On the attached image, the BA1 and MA files for user Tony have been duplicated but he only uploaded each file once.
http://www13.freereg.org.uk/uploads/feedback/screenshot/58bd69f8f493fdeb451f231e/Capture.jpg    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/58bd69f8f493fdeb451f231e/Capture.jpg)

**Comment by SteveBiggs** [comment]
Other coordinators have reported the same duplicating files behaviour in the last 24 hours.

**Comment by Captainkirkdawson** [comment]
It would appear that 2 copies of the processor got initiated at the same time. Each took the same set of waiting files and processed them. There is an interlock to stop this happening. But if there were 2 upload initiate requests at the same time on a loaded system then it is conceivable. It seems clear that colobus was struggling yesterday.
Unless @Vino-S has alternate suggestions I think we will have to go to a cron scheduling of the processor rather than a demand initiation.
It is possible to generate  a list of duplicate files and remove them.

**Comment by edickens** [comment]
Perhaps we will then drop below the 6M marriages again  :-(

**Comment by richpomfret** [comment]
To discuss potential changes/solutions for this.

**Comment by Captainkirkdawson** [comment]
I would like to discuss with @Vino-S

**Comment by Captainkirkdawson** [comment]
It appears that there were 31 duplicate files processing between  6:19am GMT on 5 March and 1:54am GMT on 6 March

**Comment by Captainkirkdawson** [comment]
Duplicates have been removed

**Comment by SteveBiggs** [comment]
Just received the following -  "I have been uploading this morning for one of my team. I got three emails to say the file had uploaded and when I looked there were three copies of it on FreeREG. I deleted two. The file however contained an error which I corrected offline and then tried to replace - I got the same message as my other transcriber so I deleted the file completely and uploaded it again - again three copies of the email and three files called DBYBASBU4 on FreeREG."

**Comment by Captainkirkdawson** [comment]
Had 3 processors running that time! Likely caused by server overload and then this makes it worse.
Will clearly have to take control.
Will go to a double lock. Set a lock on an initiation and not reinitiate if that is set. Have the processor remove the set.

**Comment by Captainkirkdawson** [comment]
Have set a double interlock

Only ask for processor to run once. Processor removes request interlock when running and sets its own interlock. Deployed to production

**Comment by Captainkirkdawson** [comment]
rs that all afected duplicates have been removed
