### ISSUE TITLE
68898687 Destroy UserID is hanging (Eric)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#933]
Issue reported by **REGManager** at 2017-03-08 10:31:27 UTC
Time: 2017-03-08T10:27:28+00:00
Session ID: 2392704765e251a2560606f454f3edab
Problem Page URL: [/userid_details/58bee0ecf493fd0f417c5f4f](/userid_details/58bee0ecf493fd0f417c5f4f)
Previous Page URL: []()
Reported Issue:
I have tried a number of times, including making sure that the server was not busy, to delete the attached UserID.  The link just hangs and I waited more than 2 minutes.  Everything else works quickly.
If the problem is looking to see if the UserID has batches, then make the rule that only UserIDs with 0 batches can be destroyed.  This information has already been obtained when displaying the Profile.  E
http://www13.freereg.org.uk/uploads/feedback/screenshot/58bfdd7ff493fd991da285e2/Capture.JPG    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/58bfdd7ff493fd991da285e2/Capture.JPG)

**Comment by Captainkirkdawson** [comment]
Comment from another duplicate thread by Regmanager

Steve and I have been trying to delete some of these rogue UserIDs. For example "But is developed". But Destroy just hangs. If it is checking to see if there are any files and that is what is taking the time, I suggest that a "Destroy" should not be allowed unless the number of files is zero. This information is available in the UserID and has already been determined. E

**Comment by Captainkirkdawson** [comment]
Code change deployed to test3 for testing

**Comment by Captainkirkdawson** [comment]
@SteveBiggs  and @edickens  to please test3 on test3 prior to deployment

**Comment by edickens** [comment]
Kirk says not in production.  Using production still hangs.  Try Destroying UserID 10 metres.

**Comment by SteveBiggs** [comment]
Destroy tested and working on test3.

**Comment by Captainkirkdawson** [comment]
It is in production

**Comment by SteveBiggs** [comment]
Thanks. The production website appears to be unresponsive (to me at least) at the moment.

**Comment by SteveBiggs** [comment]
I managed to destroy one ID in production, but the website is still erratically unresponsive making meaningful testing unreliable at present.

**Comment by edickens** [comment]
I can't even log in.  It must be very busy.  Will try again later.
