### ISSUE TITLE
68832040 Destroy UserID is hanging (Eric)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#934]
Issue reported by **REGManager** at 2017-03-07 16:00:40 UTC
Time: 2017-03-07T15:54:46+00:00
Session ID: b5f39b03a88910c46cc97fb130a3a6f7
Problem Page URL: [/userid_details/58b9b1f0f493fd2d7b70beaf](/userid_details/58b9b1f0f493fd2d7b70beaf)
Previous Page URL: []()
Reported Issue:
Steve and I have been trying to delete some of these rogue UserIDs.  For example "But is developed".  But Destroy just hangs.  If it is checking to see if there are any files and that is what is taking the time, I suggest that a "Destroy" should not be allowed unless the number of files is zero.  This information is available in the UserID and has already  been determined.  E    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/58bed928f493fd0f417c5ef8/_old_)

**Comment by Captainkirkdawson** [comment]
Duplicate
