### ISSUE TITLE
68479131 Northumberland Place names (Chris)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#937]
Issue reported by **chriselliott** at 2017-03-03 13:58:51 UTC
Time: 2017-03-03T13:54:47+00:00
Session ID: 174e48204602019ae1229ed1a8bdc31f
Problem Page URL: [/manage_resources/new](/manage_resources/new)
Previous Page URL: []()
Reported Issue:
I have just tried a search of Newcastle marriages to ensure a record had been uploaded. However when I enter the name and date and then click Northumberland no places come up so I cannot enter Newcatle uopn Tyne. I end up with a long list of marriages from the whole of Northumberland because I cannot narrow it down to a single place. I have tried clicking other counties and they all seem to work. It appears to be only a problem with Northumberland.    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/58b9769bf493fd2d7b70b555/_old_)

**Comment by ghost** [comment]
Search NBL does not bring up any place names for the county

**Comment by Captainkirkdawson** [comment]
Does now

Kirk Dawson
5220 Riverside Drive
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by ghost** [comment]
Thank you. Will now close.
