### ISSUE TITLE
Add donation button search  results page

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeUKRegProductIssues#938]
Need to choose an appropriate location - ? in the  magenta bar to the left of the statistics?

was 1062: Consider and implement additional positions for the donate button

Milestone: not phased

**Comment by Captainkirkdawson** [comment]
Add code in https://github.com/FreeUKGen/MyopicVicar/blob/freecen_parsing/app/helpers/donate_icon_helper.rb
a helper of that name in the helpers folder
Add
helper DonateIconHelper to search_queries controller just like
https://github.com/FreeUKGen/MyopicVicar/blob/freecen_parsing/app/controllers/search_queries_controller.rb#L1-L2
Use the code in
https://github.com/FreeUKGen/MyopicVicar/blob/freecen_parsing/app/views/search_queries/show.html.erb#L96 with freecen replaced by freereg
as a similar line above
https://github.com/FreeUKGen/MyopicVicar/blob/master/app/views/search_queries/show.html.erb#L89
and eliminate the link to in that line.

**Comment by Captainkirkdawson** [comment]
Done

**Comment by SteveBiggs** [comment]
Button looks good.
