### ISSUE TITLE
69239857 Rejected email addresses (Eric)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#939]
Issue reported by **REGManager** at 2017-03-12 09:17:37 UTC
Time: 2017-03-12T09:13:15+00:00
Session ID: 833dd7cdae25f31ebd5fdf4b5bc23136
Problem Page URL: [/messages](/messages)
Previous Page URL: [https://www.freereg.org.uk/manage_resources/new](https://www.freereg.org.uk/manage_resources/new)
Reported Issue:
I have just received 11 emails, all timed at 08:52 today, each listing dozens of emails which were not delivered by the message system.
I have never seen these before.  What is happening?
See attached my message which was rejected.
http://www13.freereg.org.uk/uploads/feedback/screenshot/58c51231f493fd95b94ae27b/Capture.JPG    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/58c51231f493fd95b94ae27b/Capture.JPG)

**Comment by PatReynolds** [comment]
It may be part of the solution to blocked emails (i.e. knowing what's
blocked so that we can send the message via another route, and mark the
email address as blocked).  Story #989.

**Comment by PatReynolds** [comment]
@edickens can you forward to Rich a message listing dozens of emails so he can deal. TY.
