### ISSUE TITLE
A major issue with Place names (ericb)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#94]
Issue reported by **ericb** at 2014-11-25 15:09:57 UTC
Time: 2014-11-25T15:04:50+00:00
Session ID: a76535e02b68c13a38a1c68040da5125
Problem Page URL: [/](/)
Previous Page URL: []()
Reported Issue:
After an observation by Julie , I have just  looked at County = LONDON  and there are loads of extra place names appeared since Kyran & I created the complement of Places in the Old City of London. They all have GridRef TQ something and are rubbish.

Same in MDX.

Seems something very wrong has happened or someone has messed about with it? or its been hacked.
Can you investigate please. 

Where do we go next?     

![Screenshot](http://test2.freereg.org.uk)

**Comment by Sherlock21** [comment]
Kirk: does the RED warning only come in if there are some churches and or batches attached?
These ones are placename only. I have not looked at any more Counties.

**Comment by Captainkirkdawson** [comment]
Needs specificity to investigate further. Cannot research general
observations.

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Captainkirkdawson** [comment]
Red may well have vanished in our styling

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Captainkirkdawson** [comment]
Just confirmed that the message does show as red

![red](https://cloud.githubusercontent.com/assets/2874694/5188462/543a72bc-7492-11e4-9f06-62351c124b60.JPG)

**Comment by Sherlock21** [comment]
K
Hold off with this one any way 

I might have made an error.
I will check something first with Kyran.

Ericb

**Comment by Sherlock21** [comment]
Kirk

The issue was about places that didn't have any records attached, but which had appeared in the Places list and seemed to be totally wrong and seemed to have your Tower of London gridref.

I think I must have read the data wrongly.
I am checking via the CC concerned.

MEANWHILE can you completely delete this one?
If it really is an issue I will re raise tomorrow with better details.

E
