### ISSUE TITLE
69525624 Improve submit button (Ali)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#940]
Issue reported by **alsibk** at 2017-03-15 16:40:24 UTC
Time: 2017-03-15T16:35:23+00:00
Session ID: 985cf467e78aa8013d7ad26eafce5649
Problem Page URL: [/registers/58c96d4bf493fd5469c6a3c0](/registers/58c96d4bf493fd5469c6a3c0)
Previous Page URL: []()
Reported Issue:
Please could the submit button be as clear and obvious in Create new register as it is in Create new church.

http://www13.freereg.org.uk/uploads/feedback/screenshot/58c96e78f493fd5469c6a403/Submit_button.jpg    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/58c96e78f493fd5469c6a403/Submit_button.jpg)

**Comment by AlOneill** [comment]
Am planning to address some issues of markup/styling on the Members' pages, but not until the main accessibility changes are complete: I will add the request to the review list. Thank you for the heads-up.

**Comment by Captainkirkdawson** [comment]
Easier to fix than comment

**Comment by richpomfret** [comment]
Waiting to be deployed.
