### ISSUE TITLE
69687610 Replacing existing batch brings up error message (Susan)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#941]
Issue reported by **hawkinssm** at 2017-03-17 13:40:10 UTC
Time: 2017-03-17T13:34:59+00:00
Session ID: f9a545b2c003e0320941344d2eada5e2
Problem Page URL: [/manage_syndicates/select_action.%3fsyndicate=Kent%20-%20Sue%20Hawkins](/manage_syndicates/select_action.%3fsyndicate=Kent%20-%20Sue%20Hawkins)
Previous Page URL: [https://www.freereg.org.uk/freereg1_csv_files](https://www.freereg.org.uk/freereg1_csv_files)
Reported Issue:
I have had 3 transcribers in the past 48 hours who are getting this message. Is there some problem with the site. The error message states taht "You are attempting to replace a file you do not have. Likely you are a coordinator replacing a file belonging to someone else etc...
This transcriber was Kelly Smith, the other 2 were Pat West (Pateric) and Chris Hanagan(Cucola)
Thanks Sue Hawkins Kent coordinator
http://www13.freereg.org.uk/uploads/feedback/screenshot/58cbe73af493fd5469c6e123/freereg_snip.JPG    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/58cbe73af493fd5469c6e123/freereg_snip.JPG)

**Comment by ghost** [comment]
This has been reported by others in the last two days. Realise there were problems before but these seem to still be occurring intermittently

**Comment by Captainkirkdawson** [comment]
Thre are no known problems. 

It is essential that all stated  problems be supported by screenshots such as provided by Kelly Smith. 

Simple statements of issues cannot be investigated. 

Even the report by Kelly has insufficient information, It does not include the day on which it happened

**Comment by ghost** [comment]
Passed on information asking for further details to be given in any future reports. Closing as there is nothing further to be done at this time

**Comment by Captainkirkdawson** [comment]
Fixed an issue whereby attempted uploads for an existing file moved the file to the attic so that subsequent attempts to replace the file would not be permitted with the message. ""You are attempting to replace a file you do not have. Likely you are a coordinator replacing a file belonging to someone else". An attempted upload leaves the existing file and provides an error message.

**Comment by ghost** [comment]
Sue tried to upload file KENLEWBA37.CSV at approximately 0128 this morning, and got the same message as above. She asked Comms to try and upload it, but we do not have this capability. We have a copy of the file if needed, but outside of deleting the file from FR and uploading again there does not seem to be any way we can see around the issue.

**Comment by ghost** [comment]
Another report: fault number 69766787. I tried again to upload my file NFKNORBA7.CSV today at 15.17.I just get the message that the file is not mine.my freereg log in name is brilyn
