### ISSUE TITLE
69866900 unable to upload a file. (Brian)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#942]
Issue reported by **brilyn** at 2017-03-19 15:28:20 UTC
Time: 2017-03-19T15:25:03+00:00
Session ID: d00f6a594c4b867b2b4dfea7392cfe64
Problem Page URL: [/manage_resources/new](/manage_resources/new)
Previous Page URL: []()
Reported Issue:
fault number 69766787. I tried  again to upload my file NFKNORBA7.CSV today at 15.17.I just get the message that the file is not mine.my freereg log in name is brilyn    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/58cea394f493fd2d62e4d42b/_old_)

**Comment by Captainkirkdawson** [comment]
File returned from the attic. Replace should now work
