### ISSUE TITLE
70613655 Data Problem (Mick Claxton)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#944]
Issue reported by **Mick Claxton** at 2017-03-28 06:54:15 UTC
Time: 2017-03-28T06:52:00+00:00
Session ID: 82d44cb7ab69eec08bb44e2c08578e08
Problem Page URL: [unknown](unknown)
Previous Page URL: [https://www.freereg.org.uk/contacts/58d99b89f493fddde7698dd1/report_error?query=58da07abf493fd654c023f5e](https://www.freereg.org.uk/contacts/58d99b89f493fddde7698dd1/report_error?query=58da07abf493fd654c023f5e)
Reported Issue:
I have corrected the date on this particular record to 1743 but it is still returned as 1843 in the search results. I have reported this type of fault more than once over the last few months but nothing is being done to correct it.    

![Screenshot](http://www.freereg.org.uk/uploads/contact/screenshot/58da0897f493fd654c023f78/_old_)

**Comment by Captainkirkdawson** [comment]
We do not have any information on the entry or batch. Nor do you indicate how you updated the entry or when.

**Comment by richpomfret** [comment]
Awaiting update with more details.

**Comment by Captainkirkdawson** [comment]
Without more information this will be closed
