### ISSUE TITLE
70817318 batch view unworkable (Ali)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#945]
Issue reported by **alsibk** at 2017-03-30 15:28:38 UTC
Time: 2017-03-30T15:21:36+00:00
Session ID: f3cba7dd2d74b59fe9088716b72877c9
Problem Page URL: [/freereg1_csv_entries](/freereg1_csv_entries)
Previous Page URL: [https://www.freereg.org.uk/freereg1_csv_files/5822152ff493fd9d49c760f6](https://www.freereg.org.uk/freereg1_csv_files/5822152ff493fd9d49c760f6)
Reported Issue:
This batch is not displaying correctly. 

WRYSNABA.CSV 16:28 30/3/2017
http://www13.freereg.org.uk/uploads/feedback/screenshot/58dd2426f493fd67420240cb/Batch_view_WRYSNABA.CSV.jpg    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/58dd2426f493fd67420240cb/Batch_view_WRYSNABA.CSV.jpg)

**Comment by Sherlock21** [comment]
I agree with Ali. I see the same effect on my Mac. - Production was ok last time I logged on to it (yesterday I think)
BUT its File in Test3 region at the time of writing ( 31 March 15:17hrs BST.)
So whats just been done in Production that did not get first ester in T3 ?

**Comment by Sherlock21** [comment]
I just tried to access MY batches straight from logon,  rather than from the PLacename ( which was the route that gave the fail which I tested to see the same view as Ali in both comments above) then I don't see the same malfunction. - if thats any help to you?

Similarly, I tested this out by via: "Access of Batches by most recent date of processing"
and this is OK too.

**Comment by Sherlock21** [comment]
Another oddity: when accessing a batch in Production, as Ali describes, then the Show Details does put up the proper full page view for a few milli seconds, -then suddenly 'hiccups' and produces the very repeatable part page view that Ali attached.

**Comment by Captainkirkdawson** [comment]
This is a transcription level problem. All Ali has to do is correct the record that has an extremely long name.
![correct](https://cloud.githubusercontent.com/assets/2874694/24555753/761656ca-15ef-11e7-93ce-aadbe5e55b5d.JPG)
Browsers attempt to adjust field widths to accommodate the content. Sometimes it becomes almost impossible as in this case. That is why you see the browser adjusting column widths as it processes a table

**Comment by Sherlock21** [comment]
OK, I do remember discussing in the early days, how to break multiple names, so as to keep the format. But I don't remember coming on this issue of and name being too long.

SO whats the max length of a person's name? 
How does edit a person's name fit into TWYS by shortening it?
Or do we tell everyone to "wrap" long names [ how??? ]
Or can you make the product work that out itself - as a Mod?

**Comment by Captainkirkdawson** [comment]
What makes you think that was an original entry?

There is no maximum that I am aware of; if there is its likely 256
I suggest that what is most likely a transcription error be corrected. The name entered is not credible. 100 or so As at the end of a normal name is not something that a vicar would ever have entered in a register.

I proposed to do nothing

**Comment by suffolkroots** [comment]
I'll add this to my list.

Over and out
