### ISSUE TITLE
71068881 Blank dates (Ali)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#948]
Issue reported by **alsibk** at 2017-04-02 13:21:21 UTC
Time: 2017-04-02T13:19:57+00:00
Session ID: eafce31dce9f0533fba0b85945590144
Problem Page URL: [/manage_counties/select_action](/manage_counties/select_action)
Previous Page URL: [https://www.freereg.org.uk/manage_resources/new](https://www.freereg.org.uk/manage_resources/new)
Reported Issue:
Please could this be added to  the Search Help pages?

"A search without date will return any relevant records which had no event date."    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/58e0fad1f493fd540a1ad5e3/_old_)

**Comment by Captainkirkdawson** [comment]
Could Ali please provide a good example

**Comment by suffolkroots** [comment]
[Blank date search.zip](https://github.com/FreeUKGen/FreeUKRegProductIssues/files/892361/Blank.date.search.zip)

**Comment by Sherlock21** [comment]
My view on the expectation is that:
If a search has a date range, then records with no dates should come in the supplementary section of Possibles.
If a search has no date range specified, then I would expect records with no birth or baptism date to appear in the same section s all the rest or the results.

**Comment by Captainkirkdawson** [comment]
TY Ali but that did not look like a blank date. It appeared to be an *

**Comment by suffolkroots** [comment]
Not a blank date but still returning 0 start.

Attached are search results for true blank date 
![blank date 2 jpg](https://cloud.githubusercontent.com/assets/10379655/24691557/0ae70e9a-19cc-11e7-9334-2449056d2abc.JPG)

**Comment by SteveBiggs** [comment]
I would add to EricB's comment " ... records with no VALID dates should ... "

**Comment by Captainkirkdawson** [comment]
replaced with 1259
