### ISSUE TITLE
Regression: WinFreeREG No Longer Works

### ISSUE THREAD

**Issue by EmJayFry** [FreeUKGen/FreeUKRegProductIssues#953]
For some reason, WinFreeREG is unable to logon to either FreeREG system. It appears that the response being generated to the logon request has changed and no longer fits with what WinFreeREG is expecting.

**Comment by Captainkirkdawson** [comment]
1BjoGRVQ%3D--6fd464225691aa27e14f95d72f386ff256d03364 on production

**Comment by Captainkirkdawson** [comment]
PS we are using the secure connection https://www.freereg.org.uk/ these days.  http://www etc no longer works

**Comment by EmJayFry** [comment]
Issue mistakenly raised. Problem caused through an invalid password for the transreg id. Corrected the password on both live and test and the unexpected response disappears.

Have made a small amendment to WinFreeREG to better handle this unexpected response.
