### ISSUE TITLE
Odd behaviour of website (FB post)

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeUKRegProductIssues#955]
freereg 2 is not working for me at the moment. Reports as UP when checked by 'is it up'. Behaviour mighty odd. No error message, browser just sits there with blank screen. No other site behaves like this, and this is the first time I have seen it from free reg. Working OK 30 mins ago

Posted around 1am BST on Facebook

**Comment by DeniseColbert** [comment]
Have responded that work is being done on servers, apologised for inconvenience.

I was in the Members area around 6pm BST sending a message and it was all very slow (had a 504 timeout error also).

Assume these issues a result of the work on sharding?

**Comment by Captainkirkdawson** [comment]
Appears that on returning saki to production last evening I did not check that all parts were working. Hence while I was in bed all searches on saki crashed. However this would NOT provide a blank screen as there is an error message produced.
saki is back in proper health now.
colobus remains overloaded and have turned off all usage for searches in an attempt to relieve the loading.
