### ISSUE TITLE
74883276 Can't see full 'hover over' text (Denise)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#956]
Issue reported by **DenGage** at 2017-05-16 16:54:36 UTC
Time: 2017-05-16T16:46:47+00:00
Session ID: 8bbdf7dd12acd215c78d263bc71fd04c
Problem Page URL: [/messages/new](/messages/new)
Previous Page URL: [https://www.freereg.org.uk/messages?](https://www.freereg.org.uk/messages?)
Reported Issue:
'i' text  is cut off on 'i' button associated with Upload Image in Message System
http://www13.freereg.org.uk/uploads/feedback/screenshot/591b2eccf493fde92411654f/2017-05-16.jpg    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/591b2eccf493fde92411654f/2017-05-16.jpg)

**Comment by ghost** [comment]
![2017-05-16](https://cloud.githubusercontent.com/assets/20557838/26176578/88c1dcca-3b4e-11e7-870c-cb429afc09b2.jpg)

**Comment by richpomfret** [comment]
Should be a simple tag change.
