### ISSUE TITLE
74858311 Records and year span (Ali)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#957]
Issue reported by **alsibk** at 2017-05-16 09:58:31 UTC
Time: 2017-05-16T09:52:49+00:00
Session ID: 74fd98b84464608ff6ac00d57fc1c674
Problem Page URL: [/registers/59156053f493fde924017e42](/registers/59156053f493fde924017e42)
Previous Page URL: [https://www.freereg.org.uk/freereg1_csv_entries](https://www.freereg.org.uk/freereg1_csv_entries)
Reported Issue:
File WRYSHEBA.CSV ID Charlie uploaded 16/5/2017 is showing no date span and no number of records, although records are there in file.

http://www13.freereg.org.uk/uploads/feedback/screenshot/591acd47f493fdfa3cf27df4/Date_span.jpg    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/591acd47f493fdfa3cf27df4/Date_span.jpg)

**Comment by ghost** [comment]
![date_span](https://cloud.githubusercontent.com/assets/20557838/26176720/fd275c8e-3b4e-11e7-9fc4-37355d5d67e1.jpg)

**Comment by Captainkirkdawson** [comment]
There is often a delay in computing this information as it is done overnight. There are occasions when there is further delay due to overloading  on the main server.
The data is there in the display now,
