### ISSUE TITLE
75120514 Volunteering Question (Jacky Long)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#958]
Issue reported by **Jacky Long** at 2017-05-19 10:48:34 UTC
Time: 2017-05-19T10:45:40+00:00
Session ID: 832bc8a855ea1204d9f60aadd3d1287b
Problem Page URL: []()
Previous Page URL: [https://www.freereg.org.uk/contacts/new](https://www.freereg.org.uk/contacts/new)
Reported Issue:
Can you tell me what is involved in volunteering as a transcriber please. I have done some transcribing for another genealogy site. Can I do it from home? Will I be emailed or sent the data which needs transcribing?
Thank you    

![Screenshot](http://www.freereg.org.uk/uploads/contact/screenshot/591ecd82f493fd3866f2b980/_old_)

**Comment by ghost** [comment]
This is an error
