### ISSUE TITLE
Develop Attic access

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#96]
Issue reported by **REGManager** at 2014-11-26 14:21:54 UTC
Time: 2014-11-26T14:17:21+00:00
Session ID: a1885920fa7b0416025a1d78795a47cc
Problem Page URL: [/attic/select](/attic/select)
Previous Page URL: [http://test2.freereg.org.uk/manage_resources/new](http://test2.freereg.org.uk/manage_resources/new)
Reported Issue:
I had a need to access the Attic but got "Page not found".  So has it not been programmed?
My reason for doing this was because some empty files were found but had been deleted by Ali, and I wanted to see what they were as they could account for the update file count not matching the FR1 files.  For example one was for WRY Silkstone.    

![Screenshot](http://test2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Not programmed yet

**Comment by Captainkirkdawson** [comment]
Written and now available
