### ISSUE TITLE
75632570 UserID Triplicated (Eric)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#962]
Issue reported by **REGManager** at 2017-05-25 09:02:50 UTC
Time: 2017-05-25T08:57:20+00:00
Session ID: a9d2f214f654b7a4143559b7442e12c5
Problem Page URL: [/userid_details/selection?option=Select%20specific%20userid](/userid_details/selection?option=Select%20specific%20userid)
Previous Page URL: [https://www.freereg.org.uk/userid_details/options](https://www.freereg.org.uk/userid_details/options)
Reported Issue:
The attached has been triplicated.  She thinks it may be because of an exclamation mark after the UserID.  We should not allow any punctuation.  Please delete all but one.
http://www13.freereg.org.uk/uploads/feedback/screenshot/59269dbaf493fd763208e57b/Capture.JPG    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/59269dbaf493fd763208e57b/Capture.JPG)

**Comment by ghost** [comment]
![capture](https://cloud.githubusercontent.com/assets/20557838/26493201/0a47f10e-4210-11e7-83ea-7ef49d2f7450.JPG)

**Comment by Captainkirkdawson** [comment]
There is currently only one such userid and it is an incomplete registration
The system does not permit duplicate userids

**Comment by richpomfret** [comment]
On hold/closing until issue reappears (if indeed it does).
