### ISSUE TITLE
75738737 Why are we apparently sending emails to inactive userids?

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#965]
Issue reported by **REGManager** at 2017-05-26 14:32:17 UTC
Time: 2017-05-26T14:26:21+00:00
Session ID: 711676c2908214f3cdc61a00f11a8be6
Problem Page URL: [/userid_details/5462b42ae937907d700006ec?option=Select+specific+userid](/userid_details/5462b42ae937907d700006ec?option=Select+specific+userid)
Previous Page URL: []()
Reported Issue:
The UserID popplefords has a peculiar reason for being invalidated, see attached.  We also think that this person has received emails even though they were sent to Active only and the UserID was made Inactive in 2015.
http://www13.freereg.org.uk/uploads/feedback/screenshot/59283c71f493fd2c503e7a4f/Capture.JPG    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/59283c71f493fd2c503e7a4f/Capture.JPG)

**Comment by ghost** [comment]
![capture](https://cloud.githubusercontent.com/assets/20557838/26530488/66462a5c-43cd-11e7-9e64-ce4e869d06b7.JPG)

**Comment by Captainkirkdawson** [comment]
This is in fact the reason provided by sendgrid for  being unable to deliver the message.

So the message is not corrupt. It is why that user now has a false email address

**Comment by Captainkirkdawson** [comment]
What is worthy of investigation is why we were continuing to send a message

**Comment by edickens** [comment]
Understood if it what SendGrid provided.  Perhaps an information button is needed to say that it is the SendGrid response so that others do not report what seems like a problem in the future.

**Comment by Captainkirkdawson** [comment]
Vino I will have a further look at this one if that is OK?

**Comment by Captainkirkdawson** [comment]
I believe that on the scrum of July  19 it was agreed that Vino would look at this

**Comment by edickens** [comment]
frereg-processing has received a bounced email from SpamCop on 25 July at 14:30 for ludlamkeith@virginmedia.com but this has not appeared in the overnight "Bounced emails log".
Also, "Shelley" is still showing in the logs every day.

**Comment by SteveBiggs** [comment]
Shelley is showing because the email valid is set to true. Even if we set it false, the next time she logs in (which seems to be most days) she resets it true.  I've tried to contact her without success.

**Comment by edickens** [comment]
Set her to Inactive then she cannot log in and should contact us and we can get the correct email address.

**Comment by SteveBiggs** [comment]
I'm reluctant to do that, Eric because she is actively transcribing and uploading files and would be understandably upset to be locked out of the site. I'll try John Pingram her coord again as he seems to be able to contact her.
