### ISSUE TITLE
76023827 Data Question (Matthew)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#966]
Issue reported by **Matthew** at 2017-05-29 21:43:47 UTC
Time: 2017-05-29T21:40:01+00:00
Session ID: 8358e3770448ba807cc470685a92f7d3
Problem Page URL: []()
Previous Page URL: [https://www.freereg.org.uk/contacts/new](https://www.freereg.org.uk/contacts/new)
Reported Issue:
I am looking into the possibility of using machine learning to crawl over basic BMD or parish register data to discern relationships between named entities in the records.

I've seen mention that work was moving towards creating an API for data. Has this been completed? Are there ways of having access to subsets of the data?    

![Screenshot](http://www.freereg.org.uk/uploads/contact/screenshot/592c9613f493fd2c503ede80/_old_)

**Comment by PatReynolds** [comment]
Cannot trace Matthew's email to reply.

**Comment by ghost** [comment]
​Here you go:

matthew.davis.1978@gmail.com

Kind regards
The Communications Team

**Comment by PatReynolds** [comment]
Replied 22/8/2017
