### ISSUE TITLE
Early start date causes search to fail

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeUKRegProductIssues#967]
Not sure if this has been raised before or is a new bug (or 'feature') -  a search with an early start date (e.g. 1100) fails to find any records, but one with a later start date (e.g. 1700) finds them. If not a bug, the earlier start dates should raise a warning when used / not be allowed.

**Comment by SteveBiggs** [comment]
Pat, I just tried a search with start year of 1100 and it found all expected records. In fact even a start year of 100 found them. What specific search criteria were you using?

**Comment by PatReynolds** [comment]
Surname Alcock, baptism, Yorkshire (no first name) chrome.

**Comment by SteveBiggs** [comment]
Just searched Alcock, baptism, Yorkshire (no first name) in chrome between 1700-1800, 1100-1800 and 100-1800 and all searches returned around 60 records.

**Comment by Captainkirkdawson** [comment]
I am unable to duplicate on test3, all searches for Alcock ending in 1800 for Yorkshire with a starting date of 0, 100 , 1100, 1500 all produced 61 results. No further action until there is a documentation of a failure

**Comment by SteveBiggs** [comment]
Correct all those searches work, but a start date of 99 or 999 does not (at least not for me).

**Comment by SteveBiggs** [comment]
Did I miss the decision to limit the start date in a search to 1000? I thought we had some records that are pre-1000 ....

**Comment by Captainkirkdawson** [comment]
Clearly I missed making the comment. the 1000 was a temp fix while we worked out what the issue was. Ben has developed a fix we will be testing

**Comment by SteveBiggs** [comment]
All start dates now give expected results.
