### ISSUE TITLE
76969078 Unnotified contact (Eric)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#968]
Issue reported by **nejws05** at 2017-06-09 20:17:58 UTC
Time: 2017-06-09T20:13:32+00:00
Session ID: d0e2a2c4fd8142d6517470033c358aad
Problem Page URL: [/contacts?](/contacts?)
Previous Page URL: [https://www.freereg.org.uk/manage_counties/select_action?county=Northumberland](https://www.freereg.org.uk/manage_counties/select_action?county=Northumberland)
Reported Issue:
On checking my contacts following server changeover, I find one which I have had no email about.
Can the procedure be followed so I can reply
Eric Wealleans NBL Coord    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/593b0276f493fdb135c07e6a/_old_)

**Comment by Captainkirkdawson** [comment]
Unsure of what is being requested. 

All contacts were loaded from the old servers to the new ones. 

Which specific one are you saying you had not received an email?

**Comment by PatReynolds** [comment]
When EricW replies, @CommsCoord can you check it was sent?  Was EricW checking before it was sent?
