### ISSUE TITLE
76956116 Create New Place cannot see NI (Eric)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#969]
Issue reported by **REGManager** at 2017-06-09 16:41:56 UTC
Time: 2017-06-09T16:36:10+00:00
Session ID: 4e48c0b45a3131c939710bc28d98c555
Problem Page URL: [/places/new](/places/new)
Previous Page URL: [https://www.freereg.org.uk/places](https://www.freereg.org.uk/places)
Reported Issue:
Although Ireland is there in the "Manage Counties" "ARM" "All Places" "New Place" "Ireland", the Counties in NI do not show up, even though we are working in that county.  I cannot find where to assign a County to a Country.
Attached are the counties we need in Ireland for now.
http://www13.freereg.org.uk/uploads/feedback/screenshot/593acfd4f493fd30d4ea7c93/Capture.JPG    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/593acfd4f493fd30d4ea7c93/Capture.JPG)

**Comment by ghost** [comment]
![capture](https://user-images.githubusercontent.com/20557838/26995358-1d0d3876-4d64-11e7-845e-d082f9c4c9a4.JPG)

**Comment by Captainkirkdawson** [comment]
As noted to Ericb when he raised this earlier today there are no entriest for counties in NI they need creating.

I asked for a complete list of what is needed not a partial one

**Comment by edickens** [comment]
There are only 6 counties in NI:-  ANT, ARM, DOW, FER, LDY and TYR.
We could add all of Ireland as we do have those counties set up and the Country is Ireland not Northern Ireland.  When registers started this was one country.  But for now we are only working on NI places.

**Comment by Sherlock21** [comment]
Surely though, we should be dealing with Region = Northern Ireland ( as part of theUK)
And if you want to, Eire for the rest.

Rather than just one Ireland?

**Comment by Captainkirkdawson** [comment]
Committed to test3; waiting till later to deploy to production

**Comment by edickens** [comment]
Checked and it works.  TY
