### ISSUE TITLE
Change to colours (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#97]
Issue reported by **REGManager** at 2014-11-26 17:42:40 UTC
Time: 2014-11-26T17:37:42+00:00
Session ID: 97370f99aa64ad2835dafce02d34485a
Problem Page URL: [/userid_details/selection?option=Select%20specific%20userid](/userid_details/selection?option=Select%20specific%20userid)
Previous Page URL: [http://test2.freereg.org.uk/userid_details/options](http://test2.freereg.org.uk/userid_details/options)
Reported Issue:
Hi Kirk,
Am using this so that I can attach a screen print.
The options are now in boxes and are so large that they drop of the bottom of the screen, then if I select "By UserID" the footer jumps up and blocks everything.
The text is still very faint.
Over to you.    

![Screenshot](http://test2.freereg.org.uk/tmp/carrierwave/1417023760-97538-7301/Capture.JPG)

**Comment by Captainkirkdawson** [comment]
EricD you can put any screenshot or text file into by following the link to "view it on Github" and adding it there. As done here
![capture](https://cloud.githubusercontent.com/assets/2874694/5206204/24d459f0-755c-11e4-8169-78b50ab019ae.JPG)

**Comment by Captainkirkdawson** [comment]
Much better than starting a problem!!!!!!!!!!!!!!!!

**Comment by edickens** [comment]
I have just tried to look at FreeREG2 on my iPhone3.  The colours seem better, but the red buttons do not come up so I cannot even search.  The screen size also starts very large and has to be resized down.  The text does wrap around and retains a good sized font, so we are nearly there, but there is something wrong.  Researchers will use iPhones and tablets, so we need to allow for that.
PS.  I can't find out how to delete #98 and #99.

**Comment by Captainkirkdawson** [comment]
The Menu is a known story #283

Stories can be closed on github or moved to done on the waffle board.

However I had asked the scrum master if we should do that before a review,

K

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by PatReynolds** [comment]
Can this issue be closed?

**Comment by PatReynolds** [comment]
#548 (Accessibility issues)
