### ISSUE TITLE
Access to physical files

### ISSUE THREAD

**Issue by suffolkroots** [FreeUKGen/FreeUKRegProductIssues#970]
In T3/Files waiting to be processed, if I click Show, I can  access physical files options.

![physical files options](https://user-images.githubusercontent.com/10379655/27003907-c4ea7ab6-4df7-11e7-9403-2ebc96b943da.jpg)

**Comment by Captainkirkdawson** [comment]
Sorry Ali but I am a little slow on the uptake today after a very heavy
month.

What is the issue in this story?

K

Kirk Dawson
5220 Riverside Drive
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by suffolkroots** [comment]
Sorry  Kirk---I can access ALL physical files In T3/Files waiting to be processed, if I click Show, I can access physical files options.
eg below

![lising of physical files](https://user-images.githubusercontent.com/10379655/27004434-1632cb90-4e01-11e7-8b26-80d1de95455c.jpg)

**Comment by Captainkirkdawson** [comment]
Ah TY.

**Comment by benwbrum** [comment]
I pointed Israel to the sample CSV files, but am not sure if that is enough to enable him to reproduce the problem.  @Captainkirkdawson, can you touch base and see how he's doing?

**Comment by israelriibeiro** [comment]
@Captainkirkdawson ,  
Is that correct?! 
Branch [issue_970](https://github.com/FreeUKGen/MyopicVicar/commit/f1733d582287154aa2eb7018706def18ad0ec4a1)
![test](https://user-images.githubusercontent.com/4265692/29252939-4506e46a-8047-11e7-89e3-026713e9cc24.gif)

**Comment by Captainkirkdawson** [comment]
Looks fine will pull into master

Kirk Dawson
5220 Riverside Drive
Fairmont Hot Springs, B.C.
V0B 1L1
