### ISSUE TITLE
77739416 Data Problem (Judith Young)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#972]
Issue reported by **Judith Young** at 2017-06-18 18:16:56 UTC
Time: 2017-06-18T18:15:53+00:00
Session ID: c0162b4e76a6985ef96e1918474e47f5
Problem Page URL: [unknown](unknown)
Previous Page URL: [https://www.freereg.org.uk/contacts/5818b2dae93790ec75851935/report_error?query=5946b9eff493fdb7fa50a334](https://www.freereg.org.uk/contacts/5818b2dae93790ec75851935/report_error?query=5946b9eff493fdb7fa50a334)
Reported Issue:
Son of John TENNANT or TENANT    

![Screenshot](http://www.freereg.org.uk/uploads/contact/screenshot/5946c398f493fdb7fa50e3c1/_old_)

**Comment by Captainkirkdawson** [comment]
This is a data isuue

**Comment by Sherlock21** [comment]
Pat:
From the data in the above report, there is no way of anyone knowing what the issue si about.
Nor which County/ place/ filename its about.
If its a transcription error,then its the CC concerned, not me.
If its a place name error then it may be mine but as I say above, there are no clues in this url to tell me anything. these urls go nowhere for me.
 So I decline this assignment Sorry.

**Comment by ghost** [comment]
I think the question for me is what is this doing in here in the first instance? I think this passed through Comms a few days ago, but I cant remember the who/what/why of it all. I will try to go back and see if I can find out where it was sent or what happened and maybe that will answer the question as to why it is here.

**Comment by ghost** [comment]
Found the query, it came through Comms on 18 June and was for NRY. I contacted the NRY coordinator on the 20th and she came back to me and said the issue was sorted. Not sure why this story was opened, but as it has been sorted I am closing it down

**Comment by Captainkirkdawson** [comment]
Thanks Sandra

Kirk Dawson
5220 Riverside Drive
Fairmont Hot Springs, B.C.
V0B 1L1
