### ISSUE TITLE
78200859 Donate Icon on printable format of detail is a problem (Andy)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#974]
Issue reported by **Andy** at 2017-06-24 02:27:39 UTC
Time: 2017-06-24T02:27:02+00:00
Session ID: b7f2f2d9ae408f7f7a53bd9fd3c1e9c1
Problem Page URL: []()
Previous Page URL: [https://www.freereg.org.uk/contacts/new](https://www.freereg.org.uk/contacts/new)
Reported Issue:
The new donate button is fine, except on the 'Printable format' page where it adds several VERY large black images as extra pages... seems like a bug.    

![Screenshot](http://www.freereg.org.uk/uploads/contact/screenshot/594dce1bf493fd7decf77825/_old_)

**Comment by ghost** [comment]
Have asked the contact for a screen shot of the issue. Awaiting reply.

**Comment by Captainkirkdawson** [comment]
Report is correct.

@Vino-S please remove the donate icon from the printable format of the details page

**Comment by Vino-S** [comment]
This issue is resolved

**Comment by SteveBiggs** [comment]
Tested on test3 and icon is removed. Can be applied to production.
