### ISSUE TITLE
78156075 bounced e-mails from an inactive transcriber (Mary)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#975]
Issue reported by **MaryKay** at 2017-06-23 14:01:15 UTC
Time: 2017-06-23T13:58:26+00:00
Session ID: 29a16a42c242e54a9e054ce903729b09
Problem Page URL: [/userid_details](/userid_details)
Previous Page URL: []()
Reported Issue:
I keep getting e-mails from 'contacts' telling me that e-mails for popplefords are bouncing.
She is marked as inactive; I thought that e-mails did not go to inactive users.  
    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/594d1f2bf493fd7decf4648b/_old_)

**Comment by Captainkirkdawson** [comment]
Are you uploading for her? If so please make that change in her userid

Kirk Dawson
5220 Riverside Drive
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by edickens** [comment]
I am getting this same message every day for the same person...
![capture](https://user-images.githubusercontent.com/8876165/27576973-e1989a7c-5b16-11e7-9170-da54ab3b84bc.JPG)
I think it has got stuck somewhere.  ED

**Comment by edickens** [comment]
PS.  This UserID has a valid email address, is Active and last uploaded a file on 25 March 2017.  So I cannot see why the bonce message is created.  ED

**Comment by Captainkirkdawson** [comment]
It is being rejected by her server as junk mail

Wht is it being reported each day is likely my mistake; cannot fix on vacation

**Comment by edickens** [comment]
TY.  No problem.  Enjoy the cooler weather.  ED

**Comment by Captainkirkdawson** [comment]
Will bve dealt with as part of 965

**Comment by ghost** [comment]
If this has been dealt with as part of 965, can this story be closed?
