### ISSUE TITLE
78388518 problem with WinFreeREG not logging user into FreeREG (Glenn Rowe)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#978]
Issue reported by **Glenn Rowe** at 2017-06-26 06:35:18 UTC
Time: 2017-06-26T06:30:00+00:00
Session ID: a5db69ea03c3d5a362f55f123a4a9344
Problem Page URL: []()
Previous Page URL: [https://www.freereg.org.uk/contacts/new](https://www.freereg.org.uk/contacts/new)
Reported Issue:
I have tried to login to the server (to upload a data file) using the WinFreeReg program (version 3.2.22) but I get the error that the user ID "growe" is not recognized on the FreeREG system. (See attached screen capture.)
 However, I am able to login to the FreeReg site on a web browser using this ID, so it seems that the user ID is recognized there.
Thanks for your help.
http://www13.freereg.org.uk/uploads/contact/screenshot/5950ab26f493fd7dec038401/Clipboard01.jpg    

![Screenshot](http://www.freereg.org.uk/uploads/contact/screenshot/5950ab26f493fd7dec038401/Clipboard01.jpg)

**Comment by ghost** [comment]
![clipboard01](https://user-images.githubusercontent.com/20557838/27580698-665d71fe-5b23-11e7-853f-a8dff6eb487f.jpg)

**Comment by suffolkroots** [comment]
3.2.22 is WinREG, not WinFreeREG. It has not been possible to login through WinREG for some time.

Files may be uploaded direct to FreeREG site.

**Comment by Captainkirkdawson** [comment]
WinREG has never been able to acess F2

**Comment by ghost** [comment]
Thanks all. Issue sorted. Closing now
