### ISSUE TITLE
Mark all "Orange" email addresses as invalid

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeUKRegProductIssues#979]
Orange.net
Orangehome.co.uk
Wanadoo.co.uk
Freeserve.co.uk
Fsbusiness.co.uk
Fslife.co.uk
Fsmail.net
Fsworld.co.uk
Fsnet.co.uk

**Comment by PatReynolds** [comment]
Coordinators need to check that no user with these email addresses are part of their syndicate - if they are, do they have an alternative email address, or phone / postal address?
General message to be sent to all.
System message

**Comment by Captainkirkdawson** [comment]
Surely this is no longer relevant and I have no idea why we would do this. We have an automatic invalidation process and email address validation by the user
