### ISSUE TITLE
Cololours (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#98]
Issue reported by **REGManager** at 2014-11-26 17:46:04 UTC
Time: 2014-11-26T17:42:51+00:00
Session ID: 97370f99aa64ad2835dafce02d34485a
Problem Page URL: [/userid_details/options](/userid_details/options)
Previous Page URL: [http://test2.freereg.org.uk/manage_resources/new](http://test2.freereg.org.uk/manage_resources/new)
Reported Issue:
Hi Kirk,
My mistake.  The footer should jump up as there is just the picklist.
Attached are the boxes that go off the screen.
E    

![Screenshot](http://test2.freereg.org.uk/tmp/carrierwave/1417023964-97539-8561/Capture.JPG)

**Comment by Captainkirkdawson** [comment]
Don't understand the issue
