### ISSUE TITLE
79116444 No records with batch (Eric)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#981]
Issue reported by **nejws05** at 2017-07-04 16:47:24 UTC
Time: 2017-07-04T16:40:07+00:00
Session ID: 6ae385daeb4d0191ed4c73d4e0054d29
Problem Page URL: [/freereg1_csv_entries](/freereg1_csv_entries)
Previous Page URL: [https://www.freereg.org.uk/freereg1_csv_files/5463a502e937904abbc116a3](https://www.freereg.org.uk/freereg1_csv_files/5463a502e937904abbc116a3)
Reported Issue:
Batch NBLCAMBA has no records attached when attempting to download or browse. The batch was transferred from Cambois St Peter in 2015, BU and MA batches moved ok.
Can you find/reattach file. I can make new batch(es) if that is in order.
Thanks Eric Wealleans Northumberland Coordinator    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/595bc69cf493fd8f726b2c70/_old_)

**Comment by ghost** [comment]
Have written to query userID

**Comment by Sherlock21** [comment]
I have located the latest sensible version of this file from the Attic ( 7/4/2015) and passed to Eric Wealleands so see if its a help.

There is a later dated version in Attic, but when trying to download that one, the message: "this file does not exist" is shown.
-ACTion for Kirk on that part when he returns.

**Comment by ghost** [comment]
Eric W provided the userID, which was StephenAndrews63. My apologies for not getting this up sooner. Have been away.

**Comment by Sherlock21** [comment]
Sandra.

Its all sorted now by Eric W uploading a replacement file as NBLCAMBA1.csv. - but I cant find any trace of the file that got lost in the 'Relocate' process that EW mentioned. so should we NOT close this, until Kirk has had a look into why the rename process seemed to have failed?
