### ISSUE TITLE
Set up Cloud9

### ISSUE THREAD

**Issue by richpomfret** [FreeUKGen/FreeUKRegProductIssues#983]
Need to make a working version of the FreeREG code base onto the FreeUKGEN code team on clould9

**Comment by Captainkirkdawson** [comment]
A fully functioning copy od FreeREG has been implemented. Team members should be able to clone and use. Instructions for use are
https://docs.google.com/document/d/1OWbya7erLmyyFstMwuBJwkquJZG4i4YrMWIHHI4Jvjk/edit#heading=h.r8mtsch418p2
