### ISSUE TITLE
80407064 Search result limit (Pat Lawrence)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#984]
Issue reported by **Pat Lawrence** at 2017-07-19 15:17:44 UTC
Time: 2017-07-19T14:56:31+00:00
Session ID: 1fef8505527b309347b1cc8dcfdc734f
Problem Page URL: []()
Previous Page URL: [https://www.freereg.org.uk/contacts/new](https://www.freereg.org.uk/contacts/new)
Reported Issue:
It is clear how much work has gone into both this database and this website, and as other enhancements continue to be added, I hope you will not forget the person who uses the site for research. I am a long-time, regular user of FreeREG in my own research, but I am finding that I have being hampered recently by some of the limitations you have imposed, and by little annoyances that cause me to have to write search queries twice. (1)The limitation of which I speak is the abitrary limit of 250 results. I have found that with this few items, I am forced to go back three or four times to add (guess) more fields to the query, almost to the point where I have to already know all the information I am feeding into the search before I search for it! My suggestion is, since you claim to be concerned about too many results for devices, is to break up the results into groups of 50 or 100, so that ALL the results can be available without knit-picking, and yet it only makes available on the device the 100 that show. (2) The annoyance of which I spoke is the black info box that shows up as one tabs to the next search field. 9 times out of 10, I am not looking at the page when I put in information, but at the name in a census, or other record. For the search form to stop me dead while I'm typing on, is extremely inefficient. For one thing, that black box should not cover the entire search field box! Secondly, one should not have to tab twice to get the black box to disappear. You have to have FLOW. It's just not right to play stop-start, go-forward-go-backward when one is doing research. So, while I grant you my deepest gratitude for your work and product, I maintain hope that you will continue to correct and modify for the sake of the researcher's sanity. :)    

![Screenshot](http://www.freereg.org.uk/uploads/contact/screenshot/596f7818f493fd8f72e8ba65/_old_)

**Comment by ghost** [comment]
I have added this as an issue because the contact has multiple concerns/comments and I am not sure how to answer all of these.

**Comment by PatReynolds** [comment]
(2)'s answer is 'it is to make the page accessible to those who are controlling their computers with speach' 
(1)'s answer is not known to me, will discuss today

**Comment by AlOneill** [comment]
2) is also for those who cannot use a pointing device (e.g. a mouse), and have to navigate using keyboard alone.

**Comment by richpomfret** [comment]
First step will be to investigate number of searches hitting the 250 limit
