### ISSUE TITLE
Basic user interfaces to image collections

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeUKRegProductIssues#985]
Write the code for basic user interfaces to display and edit the collections associated with the data model for images

**Comment by Captainkirkdawson** [comment]
Bev has completed the Source level index,show, edit and create displays; the Group level index, show create and edit as well as the image level index, show and edit. Also developed are the ability  to difficult, status, transcriber(s) and reviewer(s) individually or by selection.
For this phase we need to develop the index ability for the county level

**Comment by edickens** [comment]
Is it possible to view what Bev has done in Test2 or Test3?  ED

**Comment by Captainkirkdawson** [comment]
When we have done the last piece

**Comment by Captainkirkdawson** [comment]
See test2 for the testing. https://test2.freereg.org.uk/ only has SSX

**Comment by edickens** [comment]
I'm going to add a few things, but they will most likely be minor, although best incorporated now if others agree.
To start:  Should "Sources" be "Image Sources" or "Data Sources"?  More important when none have been entered.
![capture](https://user-images.githubusercontent.com/8876165/29456806-6294d8d6-840f-11e7-9401-c32651eac9b3.JPG)

**Comment by edickens** [comment]
Should the Option be "List Data Groups" not "List Image Server Groups"?  These groups will get created to show where to find data for transcribing which may not be on the Image Server and may not even be images, such as Phillimores Transcripts
![capture](https://user-images.githubusercontent.com/8876165/29457095-66664020-8410-11e7-9efd-9f71db29eba6.JPG)

**Comment by edickens** [comment]
"Delete Source"  I think we need an i (information) icon.  Does it delete all the image groups linked to it and the images?
![capture](https://user-images.githubusercontent.com/8876165/29457220-2163256e-8411-11e7-96de-6a8c1b2e4240.JPG)
I am very hesitant to say "OK".  Perhaps this popup should give more detail of what will happen.  Or should this even be a Data Manager Action?


  I am very hesitant to say "Yes

**Comment by edickens** [comment]
As Previously, should DE be a Data Manager Action.  An icon to define the Actions would help.

![capture](https://user-images.githubusercontent.com/8876165/29457419-fe5d1aec-8411-11e7-93ee-1d3ea94a6b95.JPG)

**Comment by edickens** [comment]
Lowest level.  Delete Image is very serious.  Is this needed?  And if so, does the image go to the Attic?

![capture](https://user-images.githubusercontent.com/8876165/29457518-6b777fe6-8412-11e7-80b6-0c3af90c9369.JPG)

**Comment by edickens** [comment]
I think one of us needs to do a write up which will eventually go into the CC and SC Help.
I could do with it now!

**Comment by Sherlock21** [comment]
IF its down to me to do this,as Eric D suggests, then I would perhaps expect a list of what’s going to be deleted! - but as I have not been able to access this test yet, i just respond here to the sense of Eric D’s commet.

OR if there are multiple  levels of Delete - i.e.: A singel item, multiple items or even the lot! 

Eric b

**Comment by Sherlock21** [comment]
picking up on Eric D’s point:

In which case, please have the Attic a seperate one to the Batches/ datafiles attic. adn with differenet tiles to each. For actions that one does less frequently, its easy to make an error and zap the wrong thing.!

Eric B

**Comment by SteveBiggs** [comment]
I would  be very surprised if "Delete Image" does anymore than remove it from the list of images under the group. Equally "Delete Source" just deletes the image group name from the sources. I don't think any of these actions delete any physical image files from the IS do they?

**Comment by bev-fc** [comment]
Hi Stephen,

Right now 'delete image' button does not do any delete, 'delete source'
will delete the source if there is no image group within i.e. empty,
'delete image group' will delete image group only when there is no images
within.

regards,
Bev

**Comment by SteveBiggs** [comment]
Thanks Bev. What is the ultimate intent of the 'delete image' button?

**Comment by bev-fc** [comment]
Hi Stephen,

I don't know yet, it will be based on the requirement.

regards,
Bev

**Comment by edickens** [comment]
Instead of "Delete Image" perhaps use "Remove image" or "Detach image".  ED

**Comment by bev-fc** [comment]
I will make the change.

regards,
Bev

**Comment by Captainkirkdawson** [comment]
Please make comments on the specific stories. If there is not one please create one. This is too complex to deal with
