### ISSUE TITLE
81192396 Getscan does not like brackets (Eric)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#986]
Issue reported by **REGManager** at 2017-07-28 17:26:36 UTC
Time: 2017-07-28T17:19:16+00:00
Session ID: 4336b8154d59fc0fd27f53b01ce6e400
Problem Page URL: [/manage_counties/place_range?params=P](/manage_counties/place_range?params=P)
Previous Page URL: [https://www.freereg.org.uk/manage_counties/selection?option=Work%20with%20All%20Places](https://www.freereg.org.uk/manage_counties/selection?option=Work%20with%20All%20Places)
Reported Issue:
If we can, we should get away from using Getscan.pl to access the images.  It has problems accessing certain characters, brackets in the folder name and spaces in the image filename for example.
These have to match the FR database.
http://www13.freereg.org.uk/uploads/feedback/screenshot/597b73ccf493fd22c7fe088d/Capture.JPG    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/597b73ccf493fd22c7fe088d/Capture.JPG)

**Comment by ghost** [comment]
![capture](https://user-images.githubusercontent.com/20557838/28746376-2edfb75e-7483-11e7-84f4-64f59ff5aac3.JPG)

**Comment by Captainkirkdawson** [comment]
We need to fix it

**Comment by edickens** [comment]
It is written in Perl and I don't know who knows this.  I was told that we should not make any more changes to modules in this language because we do not have any support for it.

**Comment by Captainkirkdawson** [comment]
We still have access to perl programmers  as FreeBMD is written in Perl.
There are not any in the FreeREG team but that should not stop use getting
support for getscan

Kirk Dawson
5220 Riverside Drive
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by edickens** [comment]
TY.  If they are going to make changes, then please ask me first because there are other problems, such as it will not recognise image filenames with a space in them.
Will we need it in the long term, or is this just while we are doing V1.5?  ED

**Comment by richpomfret** [comment]
May be covered by RAP/GAP/DAP - to be defined and fleshed out.
