### ISSUE TITLE
81294572 Unable to find data (Robin Clay)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#988]
Issue reported by **Robin Clay** at 2017-07-29 21:49:32 UTC
Time: 2017-07-29T19:36:16+00:00
Session ID: ad688836cef8d2af05cf0f88167c1d50
Problem Page URL: []()
Previous Page URL: [https://www.freereg.org.uk/contacts/new](https://www.freereg.org.uk/contacts/new)
Reported Issue:
I have been using FreeBMD (occasionally) for years, and have known about FreeReg, but have never visited it.  Until today.
Very impressive - well done !
But... ;-)
I was seeking burials in Okeford Fitzpaine and Sturminster Newton, Dorset.  I eventually came to the conclusion that you have no information from either.
It would have helped if you had actually given those names in your Lists, but put them in a different colour (or crossed through) to indicate you have no data.  As it was, I kept searching and searching...    

![Screenshot](http://www.freereg.org.uk/uploads/contact/screenshot/597d02ecf493fd22c7088659/_old_)

**Comment by ghost** [comment]
Is it possible to have a sentence about this added to the Search page? Such
as: If the place you are searching for does not appear, there has been no
data transcribed for it.

Kind regards
The Communications Team

**Comment by Sherlock21** [comment]
It would be shorter and snappier just to re title the PLACES box as: "PLACES for which we have data".

Even though that is obvious to those of us who have used it for ages.

Can Comms just put the informer on the right track if we decide to make this change please?

**Comment by Sherlock21** [comment]
The Search/ Places drop down box does not act in the like manner to the Search/ Counties box.
where ALL the Counties are listed and simple don't populate the Places box if we don't have any places with data in that County. So in this case would a single comment in Places box: " No data for this County"  save further comments from users who can't work out the logic?

**Comment by edickens** [comment]
Or even "Places with Data".

**Comment by Vino-S** [comment]
For **All Counties** option we can display message like "All Places with data has been selected"

**Comment by Sherlock21** [comment]
Yes, they would both be great. 
i support them.

**Comment by Captainkirkdawson** [comment]
I am sorry but the results page really could not be much clearer
No results found

This could be because there are no transcriptions for the Places you were searching: our Transcriptions pages will tell you what we have transcribed. 
Or you may need to recast your search options: see our Search Tips for advice on how to get the most out of your searches.

**Comment by PatReynolds** [comment]
I don't think the search results page needs changing (at least until RAP/GAP/DAP and/or Registered Researcher permits additional actions by the researcher).
Proposed change to the search page sounds reasonable, if Robin Clay agrees it would help him and other researchers

**Comment by Captainkirkdawson** [comment]
Agree with title the PLACES box as: "PLACES for which we have data".

**Comment by SteveBiggs** [comment]
I agree. Can we assign Vino to make the wording change?

**Comment by Vino-S** [comment]
Yes. I will do the changes.

**Comment by SteveBiggs** [comment]
Checked and wording is good. Can be closed.
