### ISSUE TITLE
81690904 Request for extra information on "Data Error" line in emails (Staffordshire)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#989]
Issue reported by **STSCoord** at 2017-08-03 11:55:04 UTC
Time: 2017-08-03T11:48:05+00:00
Session ID: 566c74f7c4fab6c1fd79dcc44365ab5c
Problem Page URL: [/manage_resources/new](/manage_resources/new)
Previous Page URL: [https://www.freereg.org.uk/cms/refinery/login](https://www.freereg.org.uk/cms/refinery/login)
Reported Issue:
Would it be possible to show the incorrect data when a Data Error is reported?

It is all very well giving the line number where the error occurred but is this line number inclusive or exclusive of the 4 or 5 line header?    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/59830f18f493fdf3aeb531ca/_old_)

**Comment by SteveBiggs** [comment]
The incorrect data is shown in the "Actual Record" column when you view the error (click "ER")
The "Record Number" is the number against the record when you "Browse record in batch".

**Comment by ghost** [comment]
Can this be closed?

**Comment by SteveBiggs** [comment]
I did not reply with this answer directly to Michael, so that needs to be done before we close it.

**Comment by ghost** [comment]
Have replied directly now, so am closing
