### ISSUE TITLE
82230582 problem replacing one of my batches (Diana)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#991]
Issue reported by **Dinahst** at 2017-08-09 17:49:42 UTC
Time: 2017-08-09T17:45:54+00:00
Session ID: 925457c0284c9c06138d4ad5f53452b1
Problem Page URL: [/cms/information-for-transcribers](/cms/information-for-transcribers)
Previous Page URL: [https://www.freereg.org.uk/csvfiles/5652960ef493fd69b601eb3f/edit](https://www.freereg.org.uk/csvfiles/5652960ef493fd69b601eb3f/edit)
Reported Issue:
When attempting to replace KENROMBA4 which was transcribed and loaded by myself, an error message displayed indicating that I'm not the owner of the file
http://www13.freereg.org.uk/uploads/feedback/screenshot/598b4b36f493fdf3c4a4af51/Freereg_Problem.jpg    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/598b4b36f493fdf3c4a4af51/Freereg_Problem.jpg)

**Comment by SteveBiggs** [comment]
I checked the file and can see no reason why she should not be able to replace it.

**Comment by Sherlock21** [comment]
If I offer to try & upload her replacement, it will mess up the trail for Kirk to investigate. So best wait instruction from K.

**Comment by Captainkirkdawson** [comment]
Thank you EricB for giving me time to look at the trial before it gets clouded by recent activity.

The system is not lying, dinahst does not have a file KENROMBA4 hence she cannot replace it.

Why this is occuring, as she is the primary transcriber of record for this church, will be covered in a subsequent story as it reflects a wider spread issue,

Assuming the transcriber has a file to upload (must have to see the problem!) The solution for this and other similar situations is for EricB to go to physical files for the user. To confirm in a show that the file has a non existant file size and then to use the DELETE option on the file.

If the transcriber does not then download a copy first.

![dinahst](https://user-images.githubusercontent.com/2874694/29242054-0c0544ea-7f43-11e7-88f4-a315b2814047.JPG)

The transcriber should then be asked to do an initial load of the file

**Comment by Sherlock21** [comment]
Well! Interestingly, I cannot find this file listed in Physical Files. So did it disappear after Kirk looked and printed off the image above? OR has someone else deleted it? Either way: its not there for me to do anything with.

From the code letters in the file, i guess it may be for Rochester. I looked in that Active Placename, - there are many files by this UserID, but None of the Flename concerned.
There are a couple of versions from Nov 2015 but nothing from these past few days.

Back to Kirk.

**Comment by Captainkirkdawson** [comment]
I am not going to try to find out. You are correct its gone. Someone should contact her and ask her to do an initial upload of the file

**Comment by Sherlock21** [comment]
Interestingly, there are 5 other files from either 12th or 15th March 2015 that are all showing no content. All for  AvrilS and Cambridge. I have left alone.
I note the rare 558 files in total in this list, dated from Mar 2015 up to Apr 2016, and none since.

**Comment by Sherlock21** [comment]
Steve: shall you do that one please!

**Comment by SteveBiggs** [comment]
I've advised Diane to upload the file rather than replace.
