### ISSUE TITLE
82398115 Results skipping (was Data Question) (David James)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#993]
Issue reported by **David James** at 2017-08-11 16:21:55 UTC
Time: 2017-08-11T16:18:26+00:00
Session ID: 25e6a3a325012733d36caf6f511a54a7
Problem Page URL: []()
Previous Page URL: [https://www.freereg.org.uk/contacts](https://www.freereg.org.uk/contacts)
Reported Issue:
I have noticed recently that when viewing results on the "detail" page pressing the "Next" button will not always take you to the next record.  It sometimes skips a few.  This makes it a little unreliable if you are intending to check every transcription found.    

![Screenshot](http://www.freereg.org.uk/uploads/contact/screenshot/598dd9a3f493fdf3aefb83f1/_old_)

**Comment by SteveBiggs** [comment]
I asked David for specific details and he replied as follows:

I re-ran the search to check that this isn't a temporary glitch - and it isn't.

Search details: Surname AUBREY, Forename (none), First Year 1800, last Year 1850, County Glamorgan, Place (none), Record type Baptism.

This produces 56 results.

I then hit the "Row 1" detail link to inspect the first record and when this had displayed hit the "Next Record" 24 times displaying each record in turn.  Returning to the Search Results page the following were noted as viewed: 1-18, 39-43 and 51-55.  Note this is 28 records - I may have miscounted the number of "next records" viewed.

I cannot confirm if the records viewed were as noted (as there is no record number on the details page, but it is clearly skipping records.

I am using an iMac and my browser is Firefox v.54.01 (64 bit version).

**Comment by SteveBiggs** [comment]
I made this test myself in Windows 7, Chrome and get the same result.

**Comment by Sherlock21** [comment]
I have just run the same test on my iMac, & using Safari.
56 records found ( and all numbered Row1, Row2 etc as usual.
Viewed each one "in turn" by use of the Next button.
There were no apparent jumps nor double keying. And I counted carefully 29 viewed!
Rows 1 to 18 viewed.
skip rows 19 to38 inclusive
Rows 39 to 43 viewed
Skipped rows 44 tp 50 inclusive,
Viewed rows 51 to 56.

= 29 viewed .

Picked row 48 at random, of the Not Viewed marker set. and viewed the details - seem OK at first look - i did not check with the actual file contents though.

conclusion: i support the report by David James. & Steve, noting the count of successful viewing are not exactly same. but Steve, remember you have one on view to start with, so 28 Next" clicks = 29 records viewed

**Comment by Captainkirkdawson** [comment]
Thats likely because the search retrieves and stores all the witness and family member results but only displays those that the reasearcher actually requested.

**Comment by Captainkirkdawson** [comment]
Previous post withdrawn

**Comment by Sherlock21** [comment]
I had not included witnesses in my criteria.
NowI have added Witnesses and get 56 just the same total.

so /i ran the query again but without Witness being requested, I still get 56.
Picking one of the now viewed ones ( from the same idea as before, just doing 'next' to the bottom of the stack, and then going back to the list showing Viewed or not, I picked number 25 ( which had not been viewed) and the Father's surname is shown as Aubrey i.e.: the name we are searching for. Just exactly the same as a vied one ( number 15) - Father = Aubrey.

**Comment by richpomfret** [comment]
Can anyone replicate this?

**Comment by SteveBiggs** [comment]
Yes. I made the same test as above:

Search details: Surname AUBREY, Forename (none), First Year 1800, last Year 1850, County Glamorgan, Place (none), Record type Baptism.

This produced 63 results this time.

I then hit the "Row 1" detail link to inspect the first record and when this had displayed hit the "Next Record" 24 times displaying each record in turn (and waited for browser activity to stop each time). Returning to the Search Results page the following were noted as viewed: 1-18, 42-46 and 54-55.

**Comment by Captainkirkdawson** [comment]
Fix has been applied and in in test2 for review

**Comment by SteveBiggs** [comment]
Tested and works fine in test2
