### ISSUE TITLE
82720284 Message  system pdf attachment (Eric)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#995]
Issue reported by **REGManager** at 2017-08-15 09:51:24 UTC
Time: 2017-08-15T09:48:37+00:00
Session ID: e91fd1259ea6a8f057a75017d513d959
Problem Page URL: [/messages/new](/messages/new)
Previous Page URL: [https://www.freereg.org.uk/messages](https://www.freereg.org.uk/messages)
Reported Issue:
Is it easy to allow PDF files to be attached to the messages?  This is not in the allowed list.
If so, I can do my four weekly reports through the messages system which will reach everyone.    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/5992c41cf493fdad2270b6bf/_old_)

**Comment by PatReynolds** [comment]
Not wanted to be open to the public, so no improvement to SEO.
Needs to be on our server, or on our google drive (on google drive, anyone could see, so preferred to be on our server).

**Comment by edickens** [comment]
This is why I want to put my newsletters through the server and not the transcribers group.

I am a freeREG transcriber but I don't have the time to respond to any of the requests for help from other transcribers. Unfortunately this means I'm getting an unending string of emails which I constantly have to delete as they are filling up my inbox. I still want to receive other informational emails from FreeREG, just not the help requests. I therefore need to unsubscribe from one but not the other. Is this possible? If not then I will have to unsubscribe completely. It would help if there were two separate mailing lists.

**Comment by PatReynolds** [comment]
Tried an experiment (on FreeCEN2, as it doesn't appear that you can test refinery on test2 or test3 of FreeREG) - uploading a pdf into a refinery page.  Does not work because only .png, .jpg and .gif files can be uploaded.
I think we just need to tweak the Refinery code (http://www.refinerycms.com/guides/resources says that we can upload pdf).

**Comment by PatReynolds** [comment]
Sending rtf and pdf on FreeCEN and FreeREG both failing (sends gobledygook).  My laptop completely froze.

**Comment by edickens** [comment]
The  pdf file is inserted not attached.  As a result it is very small and unreadable.  It says that there is a file attached, but it isn't, it is inserted.
PS.  Should we also send a copy of every message to the sender?  If this had happened then I would have seen the problem sooner.  It is also confirmation that it was processed correctly.

**Comment by edickens** [comment]
More information on my previous post.
The message that the server sent out is fine.  It is when you go into the website and select the message system, then you cannot see the attachment.
You just get...
![Capture.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/542531935e93a002006d0247/125516c66e82c728ace21e0d46cb958a379791accda5fd53b652fa912a5265296b51f02e7384e671e6162351580d4bac43585f45ffac8928f0a42062c80d55b98e30063e937f03a6aa8318b500bf21824881b6be884ac3e83437aa.JPG)
which is not a usable link.
