### ISSUE TITLE
Images-delete

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeUKRegProductIssues#996]
Who should be permitted to delete an image?

**Comment by Captainkirkdawson** [comment]
Should it be restricted and to whom

**Comment by Captainkirkdawson** [comment]
EricD posted

Lowest level. Delete Image is very serious. Is this needed? And if so, does the image go to the Attic?

capture

**Comment by Captainkirkdawson** [comment]
EricB responded

IF its down to me to do this,as Eric D suggests, then I would perhaps expect a list of what’s going to be deleted! - but as I have not been able to access this test yet, i just respond here to the sense of Eric D’s commet.

OR if there are multiple  levels of Delete - i.e.: A singel item, multiple items or even the lot!

**Comment by Captainkirkdawson** [comment]
EricB also said
picking up on Eric D’s point:

In which case, please have the Attic a seperate one to the Batches/ datafiles attic. adn with differenet tiles to each. For actions that one does less frequently, its easy to make an error and zap the wrong thing.!

**Comment by Captainkirkdawson** [comment]
Steve responded
I would be very surprised if "Delete Image" does anymore than remove it from the list of images under the group. Equally "Delete Source" just deletes the image group name from the sources. I don't think any of these actions delete any physical image files from the IS do they?

**Comment by Captainkirkdawson** [comment]
Hi Stephen,

Right now 'delete image' button does not do any delete, 'delete source'
will delete the source if there is no image group within i.e. empty,
'delete image group' will delete image group only when there is no images
within.

regards,
Bev

**Comment by Captainkirkdawson** [comment]
Steve said Thanks Bev. What is the ultimate intent of the 'delete image' button?

**Comment by Captainkirkdawson** [comment]
Bev responded

Hi Stephen,

I don't know yet, it will be based on the requirement.

regards,
Bev

**Comment by Captainkirkdawson** [comment]
EricD said

Instead of "Delete Image" perhaps use "Remove image" or "Detach image". ED

**Comment by Captainkirkdawson** [comment]
Bev said

I will make the change.

regards,
Bev

**Comment by Captainkirkdawson** [comment]
I believe a change is not required yet.

What do we want to do with the delete image action and who can ask for it????

Should anyone be permitted to delete the entry?

Should it delete the image on the image server?

There is NO attic function for images at this time. It cannot be integrated with the current attic system

**Comment by SteveBiggs** [comment]
My view is that "Delete Image" should just mean remove it from the group and can be done by the CC and up, so as EricD says, maybe call it "Remove Image".

The decision on whether to discard an image from the IS is a separate issue to the allocation process.

**Comment by Captainkirkdawson** [comment]
The displays to date are designed to manage the the collections bearing in mind their forthcoming use in both allocation/assignment and as EricD has asked to actually manage the images on the image server.
So could I ask what is the intent and purpose of a "remove" image? 
I anticipated that a delete image would actually do that (go to the image server and delete the entry from its current folder)

**Comment by SteveBiggs** [comment]
I misinterpreted the intent of delete image. We can assign images to a group and reassign to another group, but might we want to remove one from a group (without assigning to another nor deleting it from the IS)?

**Comment by Captainkirkdawson** [comment]
That is for you guys to decide. Doing what you suggest as an action will create "orphan images" which is unwise

**Comment by Sherlock21** [comment]
ref item from Kirk 3 above, IS there a Rename Image feature anywhere - in case an image or an Image Group were named wrongly in the first place?

It could therefore be that an image has to be removed or Deleted and reloaded and put in the right bundles.
ALSO: we could have got some images that we have no right to hold so would need to delete these either single images or Groups.

I will tell you  in an email why I put this last line in

**Comment by edickens** [comment]
Some images get uploaded more than once, say if they have been re-scanned.  We have a lot of tif and jpg from the same microfiche.  We may need to delete one set to avoid confusion.  BUT this needs to be a Data Manager Action.
We do need to ensure that there are no Orphan Images.  The overnight processing which looks for newly uploaded images will see these as Orphans.

**Comment by Captainkirkdawson** [comment]
Steve responded 
I am reluctant to allow CC's to delete images as I think there needs to be some level of checking before they can be deleted. So perhaps, DM and SA only - at least to start with?

**Comment by Captainkirkdawson** [comment]
WRT to Ericb. There is no specific rename but the edit permits renaming

**Comment by edickens** [comment]
At present only SysAdmin can delete UserIDs.  I think that this is the same level of importance.

**Comment by Sherlock21** [comment]
Fine with me.
 We do need consistency across all the elements.

**Comment by Captainkirkdawson** [comment]
Summary conclusion.
Only system_administrator can delete image

**Comment by bev-fc** [comment]
@Captainkirkdawson change is pushed, please verify if it works as expected, if you see any errors, please let me know.

**Comment by SteveBiggs** [comment]
I have verified that CC can no longer delete images and sys_admin can so this looks good.
