### ISSUE TITLE
Image-Server-Group-delete

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeUKRegProductIssues#997]
Should anyone be permitted?

**Comment by Captainkirkdawson** [comment]
EricD posted

As Previously, should DE be a Data Manager Action. An icon to define the Actions would help.

capture

**Comment by Captainkirkdawson** [comment]
Steve posted
I would be very surprised if "Delete Image" does anymore than remove it from the list of images under the group. Equally "Delete Source" just deletes the image group name from the sources. I don't think any of these actions delete any physical image files from the IS do they?

**Comment by Captainkirkdawson** [comment]
Hi Stephen,

Right now 'delete image' button does not do any delete, 'delete source'
will delete the source if there is no image group within i.e. empty,
'delete image group' will delete image group only when there is no images
within.

regards,
Bev

**Comment by SteveBiggs** [comment]
Same comment as #998

**Comment by Captainkirkdawson** [comment]
Cnclusion:
Implement a check on the display of Image Group actions so that they can only be seen by those with the authority to use the action. This has been the FreeREG way.

So system_administrators and data_managers can see and use the delete actions for all counties. County_coordinators can see and use the delete actions for thier own county (ies).

**Comment by SteveBiggs** [comment]
CC's can already only access actions for their own counties so is there anything to be done here?

**Comment by Captainkirkdawson** [comment]
At present time anyone can see the delete action; the change limits the ability to see and delete as stated above

**Comment by SteveBiggs** [comment]
Looks good (see #998)

**Comment by Captainkirkdawson** [comment]
@SteveBiggs we have yet to code this and 998 and 996

**Comment by SteveBiggs** [comment]
Apologies, I thought this was covered by #1283

**Comment by bev-fc** [comment]
change is pushed, please verify if it works as expected, and let me know if you see any error or if you want any changes.

**Comment by SteveBiggs** [comment]
Tested and works as expected.
