### ISSUE TITLE
Source Delete

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeUKRegProductIssues#998]
Who should be permitted and under what circumstances

**Comment by Captainkirkdawson** [comment]
"Delete Source" I think we need an i (information) icon. Does it delete all the image groups linked to it and the images?
capture
I am very hesitant to say "OK". Perhaps this popup should give more detail of what will happen. Or should this even be a Data Manager Action?

I am very hesitant to say "Yes

**Comment by Captainkirkdawson** [comment]
Steve said
I would be very surprised if "Delete Image" does anymore than remove it from the list of images under the group. Equally "Delete Source" just deletes the image group name from the sources. I don't think any of these actions delete any physical image files from the IS do they?

**Comment by Captainkirkdawson** [comment]
Hi Stephen,

Right now 'delete image' button does not do any delete, 'delete source'
will delete the source if there is no image group within i.e. empty,
'delete image group' will delete image group only when there is no images
within.

regards,
Bev

**Comment by SteveBiggs** [comment]
I believe we should stay with the approach that 'delete source'
will delete the source only if there is no image group within i.e. empty,
'delete image group' will delete image group only when there are no images
within.

So you have to positively delete all the images in a group, before you can delete the group and then source.

I am reluctant to allow CC's to delete images as I think there needs to be some level of checking before they can be deleted. So perhaps, DM and SA only - at least to start with?

**Comment by Sherlock21** [comment]
OK, but i can see this not being popular with some CCs.

**Comment by Captainkirkdawson** [comment]
The delete action will only function if there are no dependants (already implemented)

**Comment by Captainkirkdawson** [comment]
Conclusion:
Implement a check on the display of Image Source actions so that they can only be seen by those with the authority to use the action. This has been the FreeREG way.

So system_administrators and data_managers can see and use the delete actions for all counties. County_coordinators can see and use the delete actions for thier own county (ies).

**Comment by SteveBiggs** [comment]
CC's can already only access actions for their own counties so is there anything to be done here?

**Comment by Captainkirkdawson** [comment]
At present time anyone can see the delete action; the change limits the ability to see and delete as stated above

**Comment by SteveBiggs** [comment]
Tested using a Documentation Coord userid and only the SH selections are available so looks good.

I also tried as a Country Coord and that didn't allow me to even get into Managing Counties:
![capture](https://user-images.githubusercontent.com/25303607/29740421-4080718e-8a4e-11e7-95b6-d49975d33aae.jpg)
So this is fine.

**Comment by SteveBiggs** [comment]
Apologies, I thought this was covered by #1282

**Comment by bev-fc** [comment]
@Captainkirkdawson change is pushed, please verify if it works as expected, and let me know if you see any error or if you want any changes.

**Comment by SteveBiggs** [comment]
Bev,
In anticipation of Kirk pulling this into Test2, can you clarify what you've changed? It is already the case that only Sys Admin & DM can delete any source and CC can delete only their own county's sources. The only other role that can access Manage Counties and therefore, Manage Images is Documentation Coord and they already can only see the SH action. Who else can see the delete action?

**Comment by Captainkirkdawson** [comment]
I am awaiting @bev-fc making 3 tweaks before pulling into test2

**Comment by Captainkirkdawson** [comment]
Deployed this and other deletes to test2

**Comment by SteveBiggs** [comment]
Can either @Captainkirkdawson or @bev-fc please clarify what has changed because as I reported above, it was already the case that only Sys Admin & DM can delete any source and CC can delete only their own county's sources? No other role could delete sources (or groups).

**Comment by bev-fc** [comment]
Sorry for the confusion Steve, the change was a clean up of code , use ruby's dependency check(no child when delete the parent node, in this case, no image group belongs to a source when you want to delete a source) instead of writing code, no noticeable change at GUI. If no error encountered, then it is a successful submit.

**Comment by SteveBiggs** [comment]
Thanks Bev, in that case it looks good.
